Repository microsoft/winget-pkgs, pull requests merged in 2020-05, with the labels that each got.

#274 Update README.md
  README.md
Labels: Validation-Completed, auto merge

#267 Fix bad file hash
  manifests/TimKosse/FileZillaClient/3.48.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#268 Maxthon fixed bad hash
  manifests/Maxthon/Maxthon5/5.3.8.2000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#269 Azurestorage new version
  manifests/Microsoft/AzureStorageExplorer/1.13.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#270 Powerbi fix hash error
  manifests/Microsoft/PowerBI/2.81.5831.621.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#276 WindowsTerminal -> 1.0.1401.0
  manifests/Microsoft/WindowsTerminal/1.0.1401.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#284 Update vscode 1.41.1 website
  manifests/Microsoft/VisualStudioCode/1.41.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#293 Update vscode 1.44.2 website
  manifests/Microsoft/VisualStudioCode/1.44.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#292 Add Node.js 14.2.0
  manifests/OpenJS/NodeJS/14.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#294 Add the version 18 powertoys
  manifests/Microsoft/PowerToys/0.18.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#287 Add MaxTo.
  manifests/DigitalCreations/MaxTo/2.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#304 Add Python-3.8.3
  manifests/Python/Python/3.8.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#307 Add manifest for WinSCP v5.17.5
  manifests/WinSCP/WinSCP/5.17.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#309 Add Recuva 1.53.1087
  manifests/Piriform/Recuva/1.53.1087.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#317 Fix line endings in PresenceLight
  manifests/isaaclevin/presencelight/2.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#316 Added Azure Cosmos Emulator 2.9.2
  manifests/Microsoft/AzureCosmosEmulator/2.9.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#323 Fix VLC metadata
  manifests/VideoLAN/VLC/3.0.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#305 Add Slack
  manifests/SlackTechnologies/Slack/4.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#315 Correct Git 2.26.2 license
  manifests/Git/Git/2.26.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#326 Submitting Julia version 1.4.1.yaml
  manifests/Julialang/Julia/1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#342 Use permalink for Yarn download
  manifests/Yarn/Yarn/1.22.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#313 Add Speccy 1.32.740
  manifests/Piriform/Speccy/1.32.740.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#336 Add FreeCAD 0.18.4
  manifests/FreeCAD/FreeCAD/0.18.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#337 Add Epic Games Launcher 10.15.2
  manifests/EpicGames/EpicGamesLauncher/10.15.2.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#338 Add ShareX 13.1.0
  manifests/ShareX/ShareX/13.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#352 Update entry for OBS Studio
  manifests/OBSProject/OBSStudio/25.0.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#344 Add Inno Setup 6.0.4
  manifests/JRSoftware/InnoSetup/6.0.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#345 Add BOINC 7.16.5
  manifests/UCBerkeley/BOINC/7.16.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#348 Add a ScreenToGif package
  manifests/NickeManarin/ScreenToGif/2.24.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#351 azurecli package
  manifests/Microsoft/AzureCLI/2.6.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#356 Add TranslucentTB 8.0.0.0
  manifests/TranslucentTB/TranslucentTB/8.0.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#353 Add Postman
  manifests/Postman/Postman/7.24.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#359 Add SpeedCrunch 0.12
  manifests/Speedcrunch/Speedcrunch/0.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#340 NodeJS 14.3.0
  manifests/OpenJS/NodeJS/14.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#314 Add Defraggler 2.22.995
  manifests/Piriform/Defraggler/2.22.995.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#362 UpdateAdoptOpenJDK
  manifests/AdoptOpenJDK/OpenJDK/8.0.252.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#365 Add Gnupg Gpg4win installer, version 3.1.11
  manifests/gnupg/Gpg4win/3.1.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#361 Add Sublime Merge build 1119
  manifests/SublimeHQ/SublimeMerge/1119.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#363 Add Telegram Desktop 2.1.6
  manifests/Telegram/TelegramDesktop/2.1.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#370 Add qBittorrent
  manifests/qBittorrent/qBittorrent/4.2.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#381 Based on community feedback that the content is deprecated. AdoptOpe…
  manifests/AdoptOpenJDK/OpenJDK/8.0.212.03.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#382 Based on community feedback that the content is deprecated. https://…
  manifests/Oracle/JRE/8.241.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#380 Add Anki
  manifests/Anki/Anki/2.1.26.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#379 Add calibre
  manifests/calibre/calibre/4.16.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#384 MySQL 8.0.20
  manifests/Oracle/MySQL/8.0.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#387 New package: Dopamine 2.0.1
  manifests/Digimezzo/Dopamine/2.0.1.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#378 Add Rufus
  manifests/Rufus/Rufus/3.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#369 Add Tencent WeChat
  manifests/Tencent/WeChat/2.9.0.1000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#354 Add Microsoft Edge Stable
  manifests/Microsoft/Edge/81.0.416.77.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#389 Fiddler 5.0.20202.18177
  manifests/Telerik/Fiddler/5.0.20202.18177.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#324 Add manifest for Enpass v6.4.2.669
  manifests/Sinew/Enpass/6.4.2.669.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#402 Add Skype
  manifests/Microsoft/Skype/8.60.0.76.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#393 Added Ubisoft Uplay games launcher
  manifests/Ubisoft/Uplay/109.0.7724.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#310 Add Thunderbird 68.8.0
  manifests/Mozilla/Thunderbird/68.8.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#397 Add HexChat
  manifests/HexChat/HexChat/2.14.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#407 Fix line endings in SpeedCrunch
  manifests/Speedcrunch/Speedcrunch/0.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#408 OpenJDK 11 for AdoptOpenJDK
  manifests/AdoptOpenJDK/OpenJDK/11.0.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#409 OpenJDK 14 for AdoptOpenJDK
  manifests/AdoptOpenJDK/OpenJDK/14.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#483 Add Authy
  manifests/Twilio/Authy/1.8.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#485 Remove bogus special character
  manifests/GitExtensionsTeam/GitExtensions/3.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#358 Create 1.18.0.yaml
  manifests/Microsoft/AzureDataStudio/1.18.0.yaml
Labels: Validation-Completed

#489 Update to latest wireshark
  manifests/WiresharkFoundation/Wireshark/3.2.4.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#502 Added iTunes manifest
  manifests/Apple/iTunes/12.10.6.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#415 Add CPU-Z
  manifests/CPUID/CPU-Z/1.92.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#419 Add Firefox 68.8.0esr
  manifests/Mozilla/FirefoxESR/68.8.0esr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#424 Fix and improve Inno Setup manifest.
  manifests/JRSoftware/InnoSetup/6.0.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#430 Add Tencent Meeting
  manifests/Tencent/TencentMeeting/1.5.0.454.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#434 Add Vrew 0.4.18
  manifests/VoyagerX/Vrew/0.4.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#440 Add Microsoft Edge Beta
  manifests/Microsoft/EdgeBeta/83.0.478.33.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#443 Add Microsoft Edge Dev
  manifests/Microsoft/EdgeDev/84.0.516.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#446 Fixed download Url for Wireshark 3.2.2 and some typos
  manifests/WiresharkFoundation/Wireshark/3.2.2.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#456 Add NVAccess.NVDA. It's a screen reader.
  manifests/NVAccess/NVDA/2020.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#459 Add Meld
  manifests/Meld/Meld/3.20.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#447 Add Raspberry Pi Imager
  manifests/RaspberryPiFoundation/RaspberryPiImager/1.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#463 Add Nmap
  manifests/Insecure/Nmap/7.80.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#467 Add Löve
  manifests/love2d/love2d/11.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#479 Create 1.0.7.5.yaml
  manifests/PascalBerger/MSIXCommander/1.0.7.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#371 Added Keybase
  manifests/Keybase/Keybase/5.4.2.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#555 Musescore
  manifests/Musescore/Musescore/3.4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#553 adding build 1.45
  manifests/Microsoft/VisualStudioCode/1.45.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#559 Add GOG Galaxy 2.0
  manifests/GOG/Galaxy/2.0.14.257.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#441 add microsoft edge
  manifests/Microsoft/Edge/81.0.416.77.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#422 Add Core Temp
  manifests/alcpu/CoreTemp/1.15.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#633 Add NodeJS 10.15.3
  manifests/OpenJS/NodeJS/10.15.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#438 Add voidtools Everything
  manifests/voidtools/Everything/1.4.1.969.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#575 Fix Gimp 2.10.6
  manifests/GIMP/GIMP/2.10.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#505 Add JabRef
  manifests/JabRef/JabRef/5.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#576 Fix Gimp 2.10.8
  manifests/GIMP/GIMP/2.10.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#513 Add BZFlag
  manifests/BZFlag/BZFlag/2.4.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#533 Amazon Corretto 8.252.09.2
  manifests/Amazon/Corretto/8.252.09.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#537 Fix .NET display strings
  manifests/Microsoft/dotnet/3.1.202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#539 Add Windscribe 1.83 Build 18
  manifests/Windscribe/Windscribe/1.83 Build 18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#552 Add Moonlight Game Streaming client
  manifests/MoonlightGameStreamingProject/Moonlight/2.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#554 Add Graphviz 2.38
  manifests/Graphviz/Graphviz/2.38.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#564 Tencent.WeChat: Fix publisher
  manifests/Tencent/WeChat/2.9.0.1000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#573 Fix Gimp 2.10.0
  manifests/GIMP/GIMP/2.10.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#581 Fix Gimp 2.10.16
  manifests/GIMP/GIMP/2.10.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#578 Fix Gimp 2.10.12
  manifests/GIMP/GIMP/2.10.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#589 Submitting Palamedes version 0.47.yaml (2nd attempt)
  manifests/Nikpapa/Palamedes/0.47.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#597 Submitting HelpNDoc version 6.9.0.577
  manifests/IBESoftware/HelpNDoc/6.9.0.577.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#605 Add Signal Desktop
  manifests/Signal/Signal/1.34.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#619 Improve Microsoft Edge results
  manifests/Microsoft/Edge/81.0.416.77.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#624 Add Discord Canary
  manifests/Discord/DiscordCanary/0.0.264.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#636 Add MongoDB Compass Isolated (1.21.2)
  manifests/MongoDB/Compass/Isolated/1.21.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#632 Add MongoDB Compass (1.21.2)
  manifests/MongoDB/Compass/Full/1.21.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#654 Add information to the voidtools Everything listing and use the nullsoft installer type
  manifests/voidtools/Everything/1.4.1.969.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#651 Add Vulkan SDK.
  manifests/KhronosGroup/VulkanSDK/1.2.135.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#640 Add darktable
  manifests/darktable/darktable/3.0.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#482 Fixing Esteem website
  manifests/Esteem/Esteem/2.2.7.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#486 Add LICEcap 1.28
  manifests/Cockos/LICEcap/1.28.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#498 Add manifest for ScummVM 2.1.2
  manifests/ScummVM/ScummVM/2.1.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#339 Add Sourcetree manifest
  manifests/Atlassian/Sourcetree/3.3.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#368 Add Mozilla Firefox 76.0.1
  manifests/Mozilla/Firefox/76.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#375 Add Twitch Desktop App
  manifests/Twitch/Twitch/8.0.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#399 Add Auto Dark Mode
  manifests/Armin2208/WindowsAutoNightMode/2.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#392 Add Playnite
  manifests/Playnite/Playnite/7.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#405 Add Minecraft Launcher
  manifests/Mojang/Minecraft/2.1.14401.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#406 Add CrystalDiskMark
  manifests/CrystalDewWorld/CrystalDiskMark/7.0.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#412 Add CrystalDiskInfo
  manifests/CrystalDewWorld/CrystalDiskInfo/8.5.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#414 WinSCP 5.17.4
  manifests/WinSCP/WinSCP/5.17.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#416 WinSCP 5.17.3
  manifests/WinSCP/WinSCP/5.17.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#420 Add Toggl Desktop 7.5.46
  manifests/Toggl/TogglDesktop/7.5.46.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#429 Add SharePoint Online Management Shall
  manifests/Microsoft/SharePointOnlineManagementShell/16.0.20017.12000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#421 Update KiCad
  manifests/KiCad/KiCad/5.1.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#436 Added StreamlabsOBS 0.21.2
  manifests/Streamlabs/StreamlabsOBS/0.21.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#435 Add Voov Meeting
  manifests/Tencent/VoovMeeting/1.2.10.510.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#432 Add Bitwarden 1.17.1
  manifests/Bitwarden/Bitwarden/1.17.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#453 add Blender
  manifests/BlenderFoundation/Blender/2.82a.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#457 Add EagleGet
  manifests/EagleGet/EagleGet/2.1.5.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#470 Add Typora Typora
  manifests/Typora/Typora/0.9.86.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#477 Add DMM Game Player 2.5.4
  manifests/DMM/GamePlayer/2.5.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#466 add Cyberduck
  manifests/Iterate/Cyberduck/7.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#499 Add AssaultCube
  manifests/RabidViperProductions/AssaultCube/1.2.0.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#496 Add Free Download Manager 6.9.1
  manifests/SoftDeluxe/FreeDownloadManager/6.9.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#508 Fix clink version
  manifests/MRidgers/Clink/0.4.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#509 Add powershell-preview package
  manifests/Microsoft/PowerShell-Preview/7.1.0-preview.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#574 Fix Gimp 2.10.4
  manifests/GIMP/GIMP/2.10.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#495 Add WinCompose
  manifests/SamHocevar/WinCompose/0.9.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, bug

#490 Add Resource Hacker
  manifests/AngusJohnson/ResourceHacker/5.1.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#572 Add 1Password
  manifests/AgileBits/1Password/7.4.767.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#516 Add Github Desktop 2.5.0
  manifests/GitHub/GitHubDesktop/2.5.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#521 Add Golang
  manifests/Golang/Go/1.14.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#526 Gitter 4.1.0
  manifests/GitLab/Gitter.IM/4.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#511 Update GitKraken to v7.0.0
  manifests/Axosoft/GitKraken/7.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#542 Add TortoiseGit 2.10.0.2
  manifests/TortoiseGit/TortoiseGit/2.10.0.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#556 add twinkstar.browser
  manifests/Twinkstar/Browser/7.0.3000.2005.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#577 Fix Gimp 2.10.10
  manifests/GIMP/GIMP/2.10.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#579 Fix Gimp 2.10.14
  manifests/GIMP/GIMP/2.10.14.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#582 Fix Gimp 2.10.18
  manifests/GIMP/GIMP/2.10.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#566 Create 7.09.00.yaml
  manifests/Concept2/Utility/7.09.00.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
