Repository microsoft/winget-pkgs, pull requests merged in 2020-11, with the labels that each got.

#4467 instant jchem 20.19.0
  manifests/ChemAxon/instantjchem/20.19.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4550 Microsoft OneDrive Internal Slow version 20.201.1005.0005
  manifests/Microsoft/OneDriveInternalSlow/20.201.1005.0005.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4583 Add Tibbo Device Monitor 3.3.7
  manifests/Tibbo/tdevmon/3.3.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4582 Add IO Ninja 3.15.0
  manifests/Tibbo/ioninja/3.15.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4580 Added RoyalTS version 5.03.61012.0.
  manifests/RoyalApps/RoyalTS/5.03.61012.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4561 Added Microsoft Edge version 86.0.622.58.
  manifests/Microsoft/Edge/86.0.622.58.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4578 Added Zygor Client version 4.3.9.
  manifests/ZygorGuides/ZygorClient/4.3.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4581 Added AWS CLI version 2.0.61.
  manifests/Amazon/AWSCLI/2.0.61.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4579 Added Vim version 8.2.1923.
  manifests/vim/vim/8.2.1923.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4564 Updated Ubisoft Connect to 115.2.0.10179
  manifests/Ubisoft/Connect/115.2.0.10179.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4563 Update Netron to 4.6.0
  manifests/LutzRoeder/Netron/4.6.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4557 Added Blender 2.90.1
  manifests/BlenderFoundation/Blender/2.90.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4567 adding StarMessage screensaver
  manifests/StarMessage/StarMessageScreensaver/5.9.4.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4573 FileZilla Client Nightly version 3.51.0-20201031
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201031.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4570 Discord Development version 0.0.7774
  manifests/Discord/DiscordDevelopment/0.0.7774.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4571 Microsoft OneDrive Internal Fast version 20.219.1029.0001
  manifests/Microsoft/OneDriveInternalFast/20.219.1029.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4572 Node.js Nightly version 16.0.0-20201031
  manifests/OpenJS/NodeJSNightly/16.0.0-20201031.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4599 Microsoft.VisualStudioCodeInsiders_v1.51.20.fce8fc82ca
  manifests/Microsoft/VisualStudioCodeInsiders/1.51.20.fce8fc82ca.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4600 Add dbeaver 7.2.4
  manifests/DBeaver/DBeaver/7.2.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4527 Added Yarn version 1.22.5.
  manifests/Yarn/Yarn/1.22.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4537 Added NordVPN version 6.32.24.0.
  manifests/NordVPN/NordVPN/6.32.24.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4544 FileZilla Client Nightly version 3.51.0-20201030
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201030.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4589 Added Cold Turkey Blocker version 4.0.
  manifests/ColdTurkeySoftware/ColdTurkeyBlocker/4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4587 FileZilla Client Nightly version 3.51.0-20201101
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4592 Updated VoiceMeeter Potato to version 2.0.5.4.
  manifests/VB-Audio/VoiceMeeterPotato/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4520 Add Primecount version 6.1.yaml
  manifests/Primecount/Primecount/6.1.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4593 Add GOG Galaxy 2.0.23.4
  manifests/GOG/Galaxy/2.0.23.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4513 Added Jackett version 0.16.1922
  manifests/Jackett/Jackett/0.16.1922.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4505 listen1 2.16.1
  manifests/listen1/listen1/2.16.1.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4503 Add pandoc-plot 1.0.0.0
  manifests/LaurentPRenedeCotret/pandoc-plot/1.0.0.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4480 VLC media player nightly version 4.0.0-20201027
  manifests/VideoLAN/VLCNightly/4.0.0-20201027.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4602 Updated Google Chrome to version 86.0.4240.183.
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4576 Updated Heroku CLI to version 7.47.0.0.
  manifests/Heroku/HerokuCLI/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4596 Add IPFS-Desktop-0.13.2.
  manifests/IPFS/IPFS-Desktop/0.13.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4598 Add Docker Desktop stable version 2.5.0.0.49427
  manifests/Docker/DockerDesktop/2.5.0.0.49427.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4597 Add AXIS Camera Station 5.34.252
  manifests/AxisCommunications/AxisCameraStation/5.34.252.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4586 Node.js Nightly version 16.0.0-20201101
  manifests/OpenJS/NodeJSNightly/16.0.0-20201101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4575 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201027
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201027.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4568 Delete 4.3.6.25063.yaml
  manifests/ScooterSoftware/beyondcompare/4.3.6.25063.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4601 Added Microsoft Edge version 86.0.622.61.
  manifests/Microsoft/Edge/86.0.622.61.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4595 Nomachine 6.12.3
  manifests/NoMachine/NoMachine/6.12.3.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4577 Updated Google Chrome Beta to version 87.0.4280.40.
  manifests/Google/ChromeBeta/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4605 Update Orange to 3.27.1
  manifests/UniversityofLjubljana/Orange/3.27.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4604 Welink 6.10.10
  manifests/Huawei/Welink/6.10.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4603 classin 3.1.0.387
  manifests/eeo/classin/3.1.0.387.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4612 Discord Canary version 0.0.285
  manifests/Discord/DiscordCanary/0.0.285.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4611 Discord Development version 0.0.7776
  manifests/Discord/DiscordDevelopment/0.0.7776.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4610 Microsoft OneDrive Insiders version 20.201.1005.0006
  manifests/Microsoft/OneDriveInsiders/20.201.1005.0006.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4609 Notepad++ version 7.9.1
  manifests/Notepad++/Notepad++/7.9.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4608 Node.js Nightly version 16.0.0-20201103
  manifests/OpenJS/NodeJSNightly/16.0.0-20201103.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4607 FileZilla Client Nightly version 3.51.0-20201103
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201103.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4613 Microsoft.VisualStudioCodeInsiders_v1.51.21.a5dfd9dcf8
  manifests/Microsoft/VisualStudioCodeInsiders/1.51.21.a5dfd9dcf8.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4396 Added GeForce Experience version 3.20.5.70.
  manifests/Nvidia/GeForceExperience/3.20.5.70.yaml
Labels: Azure-Pipeline-Passed, Blocking-Issue, Validation-Completed

#4615 Updated Spotify to version 1.1.45.621.
  manifests/Spotify/Spotify/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4614 Add postman 7.35
  manifests/Postman/Postman/7.35.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4566 Update Teamviewer from 15.10.5 to 15.11.6
  manifests/TeamViewer/TeamViewer/15.11.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4584 Add WinDynamicDesktop v4.4.0
  manifests/t1m0thyj/WinDynamicDesktop/4.4.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4574 VLC media player nightly version 4.0.0-20201031
  manifests/VideoLAN/VLCNightly/4.0.0-20201031.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4621 Microsoft.VisualStudioCodeInsiders_v1.51.22.fcac248b07
  manifests/Microsoft/VisualStudioCodeInsiders/1.51.22.fcac248b07.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4623 Update 6.12.3.7.yaml for NoMachine
  manifests/NoMachine/NoMachine/6.12.3.7.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#4624 Update 6.10.10.yaml for Huawei.Welink (add home page)
  manifests/Huawei/Welink/6.10.10.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#4560 Nelson v0.4.10
  manifests/NelsonNumericalSoftware/Nelson/0.4.10.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4616 Add pandoc-2.11.1.
  manifests/JohnMacFarlane/Pandoc/2.11.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4617 Add ModernFlyouts V0.8.1.0
  manifests/ModernFlyouts/ModernFlyouts/0.8.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4618 liribrowser 0.3
  manifests/liri/liribrowser/0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4622 Added Vivaldi 3.4.2066.94 manifest
  manifests/VivaldiTechnologies/Vivaldi/3.4.2066.94.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4626 Update 3.27.1.yaml for University of Ljubljana's Orange
  manifests/UniversityofLjubljana/Orange/3.27.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4634 Updated Google Chrome Beta to version 87.0.4280.47.
  manifests/Google/ChromeBeta/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4633 Added IAP Desktop version 2.8.352.
  manifests/Google/IAPDesktop/2.8.352.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4636 Update 6.10.10.yaml
  manifests/Huawei/Welink/6.10.10.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#4627 Update zotero to 5.0.93
  manifests/Zotero/Zotero/5.0.93.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4625 Added Microsoft Edge version 86.0.622.63.
  manifests/Microsoft/Edge/86.0.622.63.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4620 Add Files v0.19.0
  manifests/Files-Community/Files/0.19.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4631 Add git 2.29.2.2
  manifests/Git/Git/2.29.2.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4632 Updated Google Cloud SDK to version 317.0.0.
  manifests/Google/CloudSDK/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4635 Update 2.5.2.yaml for Huawei Quick App IDE
  manifests/Huawei/QuickAppIde/2.5.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#4639 Microsoft.VisualStudioCode_v1.51.0.fcac248b07
  manifests/Microsoft/VisualStudioCode/1.51.0.fcac248b07.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4640 Microsoft.VisualStudioCodeInsiders_v1.52.1.24b28f57be
  manifests/Microsoft/VisualStudioCodeInsiders/1.52.1.24b28f57be.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4638 Add ShareX 13.3.0
  manifests/ShareX/ShareX/13.3.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4431 Oracle VM VirtualBox Test version 6.1.17-141063
  manifests/Oracle/VirtualBoxTest/6.1.17-141063.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4654 Discord Canary version 0.0.286
  manifests/Discord/DiscordCanary/0.0.286.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4653 Discord Development version 0.0.7781
  manifests/Discord/DiscordDevelopment/0.0.7781.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4652 GitHub Desktop version 2.5.7
  manifests/GitHub/GitHubDesktop/2.5.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4630 add QGIS 3.16.0.yaml
  manifests/OSGeo/QGIS/3.16.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4650 Node.js version 15.1.0
  manifests/OpenJS/NodeJS/15.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4649 Node.js Nightly version 16.0.0-20201106
  manifests/OpenJS/NodeJSNightly/16.0.0-20201106.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4642 LibericaJDK 11.0.9.101 Full
  manifests/BellSoft/LibericaJDK11Full/11.0.9.101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4646 LibericaJDK 8u275
  manifests/BellSoft/LibericaJDK8/8.0.275.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4664 Node.js Nightly version 16.0.0-20201107
  manifests/OpenJS/NodeJSNightly/16.0.0-20201107.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4663 FileZilla Client Nightly version 3.51.0-20201107
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201107.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4660 F-Secure Freedome
  manifests/F-Secure/Freedome/2.36.6555.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4658 Nozbe 3.13
  manifests/Nozbe/NozbePersonal/3.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4657 Add HeidiSQL 11.1
  manifests/HeidiSQL/HeidiSQL/11.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4651 GitHub Desktop Beta version 2.5.8-beta1
  manifests/GitHub/GitHubDesktopBeta/2.5.8-beta1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4644 LibericaJDK 8u275 Full
  manifests/BellSoft/LibericaJDK8Full/8.0.275.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4648 FileZilla Client Nightly version 3.51.0-20201106
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201106.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4645 LibericaJDK 11.0.9.101
  manifests/BellSoft/LibericaJDK11/11.0.9.101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4694 qws 1.56
  manifests/jamesbowden/qws/1.56.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4671 Updated Google Backup and Sync to version 3.53.3404.7585.
  manifests/Google/BackupAndSync/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4690 add LibreOffice 7.0.3.yaml
  manifests/LibreOffice/LibreOffice/7.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4665 Added Dropbox version 109.4.517.
  manifests/Dropbox/Dropbox/109.4.517.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4673 Added Amazon Coretto version 11.0.9.12.1.
  manifests/Amazon/Corretto/11.0.9.12.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4686 Submitting HttpMaster Express 4.7.4
  manifests/Borvid/HttpMasterExpress/4.7.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4676 Fixed link for Shadow Client version 5.0.750.
  manifests/Blade/Shadow/5.0.750.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4678 Updated CloudApp to version 6.1.1.106.
  manifests/CloudApp/CloudApp/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4666 Added Elasticsearch version 7.9.3.
  manifests/Elastic/Elasticsearch/7.9.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4667 Added Winlogbeat version 7.9.3.
  manifests/Elastic/Winlogbeat/7.9.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4670 Added .NET Core Runtime version 3.1.9.29323.
  manifests/Microsoft/dotnetruntime/3.1.9.29323.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4680 Added MariaDB version 10.5.7.
  manifests/MariaDB/Server/10.5.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4681 Added Azure IoT Explorer version 0.13.0.
  manifests/Microsoft/azure-iot-explorer/0.13.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4674 Added AWS CLI version 2.0.62.
  manifests/Amazon/AWSCLI/2.0.62.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4679 Removed non-working CloudApp version 5.7.0.
  manifests/CloudApp/CloudApp/5.7.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, auto merge

#4675 Removed non-working Shadow Client version 5.0.615.
  manifests/Blade/Shadow/5.0.615.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4684 Added Calibre version 5.4.2.
  manifests/calibre/calibre/5.4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4677 Added BrickLink Studio version 2.1.10_5.
  manifests/BrickLink/Studio/2.1.10_5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4669 Added Microsoft Edge Beta version 87.0.664.24.
  manifests/Microsoft/EdgeBeta/87.0.664.24.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4696 Added QTranslate 6.8.0.1
  manifests/QuestSoft/QTranslate/6.8.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4702 Add Mirantis.Lens 3.6.7
  manifests/Mirantis/Lens/3.6.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4698 add Yinxiang 6.21.19.2326
  manifests/Evernote/Yinxiang/6.21.19.2326.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4700 Logitech Camera Settings 2.12.8.0
  manifests/Logitech/CameraSettings/2.12.8.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4606 VLC media player nightly version 4.0.0-20201103
  manifests/VideoLAN/VLCNightly/4.0.0-20201103.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4711 Create 3.4.0.0.yaml for WireShark
  manifests/WiresharkFoundation/Wireshark/3.4.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4710 Create 3.7.9.yaml for Python
  manifests/Python/Python/3.7.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4703 Zoom version 5.4.2
  manifests/Zoom/Zoom/5.4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4709 Node.js Nightly version 16.0.0-20201109
  manifests/OpenJS/NodeJSNightly/16.0.0-20201109.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4705 FileZilla Client Nightly version 3.51.0-20201109
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201109.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4708 Fiddler Everywhere version 1.2.1
  manifests/Telerik/FiddlerEverywhere/1.2.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4706 Fiddler Everywhere Internal version 1.2.1-internal
  manifests/Telerik/FiddlerEverywhereInternal/1.2.1-internal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4707 Fiddler Everywhere Insiders version 1.2.1-insiders
  manifests/Telerik/FiddlerEverywhereInsiders/1.2.1-insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4683 Update SoundSwitch to v5.5.4
  manifests/AntoineAflalo/SoundSwitch/5.5.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4473 ⬆️ Update conan to 1.30.2
  manifests/JFrog/Conan/1.30.2.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4697 add Stretchly 1.3.0
  manifests/Stretchly/Stretchly/1.3.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4695 Add EduMIPS64 v1.2.9
  manifests/EduMIPS64/EduMIPS64/1.2.9.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4588 VLC media player nightly version 4.0.0-20201101
  manifests/VideoLAN/VLCNightly/4.0.0-20201101.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4687 Submitting HttpMaster Professional 4.7.4
  manifests/Borvid/HttpMasterProfessional/4.7.4.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4672 Added Jitsi Meet version 2.4.2.
  manifests/Jitsi/Meet/2.4.2.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4662 VLC media player nightly version 4.0.0-20201107
  manifests/VideoLAN/VLCNightly/4.0.0-20201107.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4655 Update Netron to 4.6.1
  manifests/LutzRoeder/Netron/4.6.1.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4656 Add VSCodium 1.51.0
  manifests/VSCodium/VSCodium/1.51.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4647 VLC media player nightly version 4.0.0-20201106
  manifests/VideoLAN/VLCNightly/4.0.0-20201106.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4713 Microsoft.VisualStudioCodeInsiders_v1.52.2.65f805d98e
  manifests/Microsoft/VisualStudioCodeInsiders/1.52.2.65f805d98e.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#4714 Add ImageMagick 7.0.10-37
  manifests/ImageMagick/ImageMagick/7.0.10-37.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4715 euroscope 3.2.1.0
  manifests/gergelycsernak/euroscope/3.2.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4712 Add Docker Desktop stable version 2.5.0.1.49550
  manifests/Docker/DockerDesktop/2.5.0.1.49550.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4719 Updated Heroku CLI to version 7.47.1.0.
  manifests/Heroku/HerokuCLI/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4717 Updated GeForce Now to version 2.0.25.119.
  manifests/Nvidia/GeForceNow/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4720 TravisFallsMSFT/ChangedCustomSwitchesPassedIn
  manifests/Python/Python/3.7.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4704 VLC media player nightly version 4.0.0-20201109
  manifests/VideoLAN/VLCNightly/4.0.0-20201109.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4716 Microsoft .NET 5.0.100
  manifests/Microsoft/dotnet/5.0.100.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4718 Updated Google Chrome to version 86.0.4240.183.
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
