Repository microsoft/winget-pkgs, pull requests merged in 2020-08, with the labels that each got.

#2619 Add manifest file for LibreOffice v6.4.6.1 x64
  manifests/LibreOffice/LibreOffice/6.4.6.1.yaml
Labels: Blocking-Issue, Needs: Attention, Validation-Completed, Validation-Installation-Error

#2690 Updated microsoft powerbi to 2.83.5894.881
  manifests/Microsoft/PowerBI/2.83.5894.961.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2801 Add manifest file for Mozilla Firefox (Thai) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (TH).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2751 Update 1password to 7.6.780
  manifests/AgileBits/1Password/7.6.780.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2813 Create 3.12.4.yaml
  manifests/OpenMedia/4KYoutubetoMP3/3.12.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#2812 Add manifest file for Mozilla Firefox (Chinese Taiwan) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (ZH-TW).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2811 Add manifest file for Mozilla Firefox (Chinese China) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (ZH-CN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2814 Microsoft.VisualStudioCodeInsiders_v1.48.14.5696babbc1
  manifests/Microsoft/VisualStudioCodeInsiders/1.48.14.5696babbc1.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#2815 Update Dbeaver CE to 7.1.4
  manifests/DBeaver/DBeaver/7.1.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2810 Add manifest file for Mozilla Firefox (Xhosa) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (XH).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2809 Add manifest file for Mozilla Firefox (Vietnamese) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (VI).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2808 Add manifest file for Mozilla Firefox (Uzbek) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (UZ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2806 Add manifest file for Mozilla Firefox (Ukrainian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (UK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2804 Add manifest file for Mozilla Firefox (Chicahuaxtla Triqui) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (TRS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2712 updated manifest to latest VMWare Player Version.
  manifests/VMware/WorkstationPlayer/15.5.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2713 Add manifest file for Mozilla Firefox (Acoli) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (ACH).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2754 Add manifest file for Mozilla Firefox (Gujarati) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (GU-IN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2756 Add manifest file for Mozilla Firefox (Hindi) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (HI-IN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2759 Add manifest file for Mozilla Firefox (Upper Sorbian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (HSB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2758 Add manifest file for Mozilla Firefox (Croatian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (HR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2714 Add manifest file for Mozilla Firefox (Afrikaans) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (AF).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2710 Add manifest file for LibreOffice PreRelease v7.0.0.3 x64
  manifests/LibreOffice/LibreOffice-PreReleases/7.0.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2760 Add manifest file for Mozilla Firefox (Hungarian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (HU).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2716 Add manifest file for Mozilla FIrefox (Arabic) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (AR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2717 Add manifest file for Mozilla Firefox (Asturian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (AST).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2718 Add manifest file for Mozilla Firefox (Azerbaijani) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (AZ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2719 Add manifest file for Mozilla Firefox (Belarusian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (BE).yaml
Labels: Azure-Pipeline-Passed, Internal-Error, Validation-Completed

#2745 Add manfest file for Mozilla Firefox (Western Frisian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (FY-NL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2761 Add manifest file for Mozilla Firefox (Armenian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (HY-AM).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2747 Add manfiest file for Mozilla Firefox (Scottish Gaelic) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (GD).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2749 Update Signal to 1.34.4
  manifests/Signal/Signal/1.34.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2730 Add manifest file for Mozilla Firefox (Lower Sorbian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (DSB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2750 Update Terminus to 1.0.115
  manifests/Eugeny/Terminus/1.0.115.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2873 Microsoft.VisualStudioCodeInsiders_v1.48.15.6250371934
  manifests/Microsoft/VisualStudioCodeInsiders/1.48.15.6250371934.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#2731 Add manifest file for Mozilla Firefox (Greek) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (EL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2732 Add manifest file for Mozilla Firefox (English Canada) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (EN-CA).yaml
Labels: Azure-Pipeline-Passed, Internal-Error, Validation-Completed

#2733 Add manifest file for Mozilla Firefox (English United Kingdom) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (EN-GB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2734 Add manifest file for Mozilla Firefox (Esperanto) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (EO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2874 Microsoft.VisualStudioCodeInsiders_v1.48.16.7906d414c0
  manifests/Microsoft/VisualStudioCodeInsiders/1.48.16.7906d414c0.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#2762 Add manifest file for Mozilla Firefox (Interlingua) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (IA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2763 Add manifest file for Mozilla Firefox (Indonesian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (ID).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2764 Add manifest file for Mozilla Firefox (Icelandic) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (IS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2765 Add manifest file for Mozilla Firefox (Italian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (IT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2767 Add manifest file for Mozilla Firefox (Georgian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2768 Add manifest file for Mozilla Firefox (Kabyle) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KAB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2769 Add manifest file for Mozilla Firefox (Kazakh) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2773 Add manifest file for Mozilla Firefox (Ligurian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (LIJ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2770 Add manifest file for Mozilla Firefox (Central Khmer) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KM).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2771 Add manifest file for Mozilla Firefox (Kannada) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2772 Add manifest file for Mozilla Firefox (Korean) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (KO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2776 Add manifest file for Mozilla Firefox (Macedonian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (MK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2778 Add manfest file for Mozilla Firefox (Malay) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (MS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2779 Add manifest file for Mozilla Firefox (Burmese) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (MY).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2777 Add manifest file for Mozilla Firefox (Marathi) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (MR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2781 Add manifest file for Mozilla Firefox (Nepali) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (NE-NP).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2780 Add manifest file for Mozilla Firefox (Norwegian Bokmål) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (NB-NO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2782 Add manifest file for Mozilla Firefox (Dutch/Flemish) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (NL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2783 Add manifest file for Mozilla Firefox (Norwegian Nynorsk) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (NN-NO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2784 Add manifest file for Mozilla Firefox (Occitan) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (OC).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2787 Add manifest file for Mozilla Firefox (Protuguese Brazil) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (PT-BR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2788 Add manifest file for Mozilla Firefox (Portuguese Portugal) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (PT-PT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2774 Add manifest file for Mozilla Firefox (Lithuanian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (LT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2786 Add manifest file for Mozilla Firefox (Polish) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (PL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2789 Add manifest file for Mozilla Firefox (Romansh) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (RM).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2775 Add manifest file for Mozilla Firefox (Latvian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (LV).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2792 Add manifest file for Mozilla Firefox (Sinhalese) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SI).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2791 Add manifest file for Mozilla Firefox (Russian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (RU).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2793 Add manifest file for Mozilla Firefox (Slovak) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2794 Add manifest file for Mozilla Firefox (Slovenian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2795 Add manifest file for Mozilla Firefox (Songhai Languages) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SON).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2798 Add manifest file for Mozilla Firefox (Swedish) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SV-SE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2800 Add manifest file for Mozilla Firefox (Telugu) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (TE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2797 Add manifest file for Mozilla Firefox (Serbian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2799 Add manifest file for Mozilla Firefox (Tamil) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (TA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2796 Add manifest file for Mozilla Firefox (Albanian) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (SQ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2803 Add manifest file for Mozilla Firefox (Turkish) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (TR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2860 Add manfiest file for Mozilla Thunderbird (Malay) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (MS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2862 Add manifest file for Mozilla Thunderbird (Dutch/Flemish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (NL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2864 Add manfest file for Mozilla Thunderbird (Punjabi) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (PA-IN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2865 Add manifest file for Mozilla Thunderbird (Polish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (PL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2867 Add manifest file for Mozilla Thunderbird (Portuguese Portugal) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (PT-PT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2869 Add manifest file for Mozilla Thunderbird (Romanian/Moldovian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (RO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2866 Add manifest file for Mozilla Thunderbird (Portuguese Brazil) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (PT-BR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2868 Add manifest file for Mozilla Thunderbird (Romansh) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (RM).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2863 Add manifest file for Mozilla Thunderbird (Norwegian Nynorsk) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (NN-NO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2870 Add manifest file for Mozilla Thunderbird (Russian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (RU).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2861 Add manifest file for Mozilla Thunderbird (Norwegian Bokmål) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (NB-NO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2859 Add manifest file for Mozilla Thunderbird (Lithuanian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (LT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2843 Add manifest file for Mozilla Thunderbird (Irish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (GA-IE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2844 Add manifest file for Mozilla Thunderbird (Scottish Gaelic) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (GD).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2846 Add manifest file for Mozilla Thunderbird (Hebrew) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (HE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2845 Add manifest file for Mozilla Thunderbird (Galician) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (GL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2842 Add manifest file for Mozilla Thunderbird (Western Frisian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (FY-NL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2847 Add manifest file for Mozilla Thunderbird (Croatian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (HR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2851 Add manifest file for Mozilla Thunderbird (Indonesian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ID).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2853 Add manifest file for Mozilla Thunderbird (Italian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (IT).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2825 Add manifest file for Mozilla Thunderbird (Catalan) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (CA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2850 Add manifest file for Mozilla Thunderbird (Armenian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (HY-AM).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2841 Add manifest file for Mozilla Thunderbird (French) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (FR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2854 Add manifest file for Mozilla Thunderbird (Japanese) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (JA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2826 Add manifest file for Mozilla Thunderbird (Cakchiquel) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (CAK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2827 Add manifest file for Mozilla Thunderbird (Czech) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (CS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2852 Add manifest file for Mozilla Thunderbird (Icelandic) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (IS).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2848 Add manifest file for Mozilla Thunderbird (Upper Sorbian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (HSB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2840 Add manifest file for Mozilla Thunderbird (Finnish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (FI).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2830 Add manifest file for Mozilla Thunderbird (German) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (DE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2832 Add manifest file for Mozilla Thunderbird (Greek) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (EL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2831 Add manifest file for Mozilla Thunderbird (Lower Sorbian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (DSB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2833 Add manifest file for Mozilla Thunderbird (English Canada) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (EN-CA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2829 Add manifest file for Mozilla Thunderbird (Danish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (DA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2837 Add manifest file for Mozilla Thunderbird (Estonian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ET).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2838 Add manifest file for Mozilla Thunderbird (Basque) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (EU).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2834 Add manfiest file for Mozilla Thunderbird (English United Kingdom) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (EN-GB).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2839 Add manifest file for Mozilla Thunderbird (Persian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (FA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2836 Add manifest file for Mozilla Thunderbird (Spanish Castilian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ES-ES).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2821 Add manifest Mozilla Thunderbird (Asturian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (AST).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2823 Add manifest file for Mozilla Thunderbird (Bulgarian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (BG).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2807 Add manifest file for Mozilla Firefox (Urdu) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (UR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2820 Add manifest file for Mozilla Thunderbird (Arabic) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (AR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2828 Add manifest file for Mozilla Thunderbird (Welsh) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (CY).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2822 Add manifest file for Mozilla Thunderbird (Belarusian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (BE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2835 Add manifest file for Mozilla Thunderbird (Spanish Argentina) v78.1 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ES-AR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2824 Add manifest file for Mozilla Thunderbird (Breton) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (BR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2766 Add manifest file for Mozilla Firefox (Japanese) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (JA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2884 Microsoft.VisualStudioCodeInsiders_v1.48.17.459610f3ef
  manifests/Microsoft/VisualStudioCodeInsiders/1.48.17.459610f3ef.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#2805 listen1_fluent 2.5.2
  manifests/listen1/listen1_fluent/2.5.2.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2711 Added Auto Dark Mode Version 3.0.1
  manifests/Armin2208/WindowsAutoNightMode/3.0.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2709 Add Primesieve 7.5
  manifests/Primesieve/Primesieve/7.5.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2707 Add Streamlink Twitch GUI 1.10.0
  manifests/Streamlink/StreamlinkTwitchGui/1.10.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2704 Update Netron to 4.4.3
  manifests/LutzRoeder/Netron/4.4.3.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2706 Add Streamlink 1.5.0
  manifests/Streamlink/Streamlink/1.5.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2698 Add qBittorrent-Enhanced-Edition versions "4.2.5.13"
  manifests/c0re100/qBittorrent-Enhanced-Edition/4.2.5.13.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#2715 Add manifest file for Mozilla Firefox (Aragonese) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (AN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2875 Add manifest file for Mozilla Thunderbird (Sinhalese) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (SI).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2878 Add manifest file for Mozilla Thunderbird (Albanian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (SQ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2879 Add manifest file for Mozilla Thunderbird (Serbian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (SR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2877 Add manifest for Mozilla Thunderbird (Slovenian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (SL).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2880 Add manifest file for Mozilla Thunderbird (Swedish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (sv-SE).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2881 Add manifest file for Mozilla Thunderbird (Thai) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (TH).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2885 Add manifest file for Mozilla Thunderbird (Uzbek) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (UZ).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2882 Add manifest file for Mozilla Thunderbird (Turkish) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (TR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2886 Add manifest file for Mozilla Thunderbird (Vietnamese) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (VI).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2876 Add manifest file for Mozilla Thunderbird (Slovak) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (SK).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2887 Add manifest file for Mozilla Thunderbird (Chinese China) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ZH-CN).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2855 Add manifest file for Mozilla Thunderbird (Georgian) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (KA).yaml
Labels: Azure-Pipeline-Passed, Internal-Error, Validation-Completed

#2858 Add manifest file for Mozilla Thunderbird (Korean) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (KO).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2888 Add manifest file for Mozilla Thunderbird (Chinese Taiwan) v78.1.0 x64
  manifests/Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0 (ZH-TW).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2725 Add manifest file for Mozilla Firefox (Catalan) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (CA).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#2724 Add manifest file for Mozilla Firefox (Catalan - Valencia) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (CA-Valencia).yaml
Labels: Azure-Pipeline-Passed, Internal-Error, Validation-Completed

#2735 Add manifest file for Mozilla Firefox (Spanish Argentina) v79.0 x64
  manifests/Mozilla/Firefox/Firefox_v79.0/79.0 (ES-AR).yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
