Repository microsoft/winget-pkgs, pull requests merged in 2020-06, with the labels that each got.

#1304 R project.base
  manifests/RProject/R/4.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1350 Add Wings3D 2.2.5
  manifests/Wings3D/Wings3D/2.2.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1351 Add Aurora 0.7.2
  manifests/Aurora/Aurora/0.7.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1352 Add Transmission Remote GUI 5.18.0
  manifests/PeterDaveHello/TransmissionRemoteGUI/5.18.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1357 Add SuperTuxKart
  manifests/SuperTuxKart/SuperTuxKart/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1358 Linrad 04.14a
  manifests/SM5BSZ/Linrad/04.14a.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1359 Add SoundSwitch 5.3.1
  manifests/AntoineAflalo/SoundSwitch/5.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1310 Added Transmission 3.0.0 Early Preview
  manifests/Transmission/Transmission/3.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1332 Add sbt
  manifests/sbt/sbt/1.3.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1333 Add Trillian
  manifests/Trillian/Trillian/6.3.0.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1334 Add TypeFaster
  manifests/TypeFaster/TypeFaster/0.4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1335 Add GoldenDict 1.0.1-1
  manifests/GoldenDict/GoldenDict/1.0.1-1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1321 Add Wordpress
  manifests/Automattic/Wordpress/5.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1322 Add Akelpad
  manifests/AkelPad/AkelPad/4.9.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1325 Add 010 Editor
  manifests/SweetScape/010Editor/10.0.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1326 Add Bitwarden 1.18.0
  manifests/Bitwarden/Bitwarden/1.18.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#991 Add ProtonVPN 1.15.0
  manifests/ProtonVPN/ProtonVPN/1.15.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1460 Add Intel Extreme Tuning Utility 6.5.1.360
  manifests/Intel/ExtremeTuningUtility/6.5.1.360.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1327 Add Google Earth Pro
  manifests/Google/EarthPro/7.3.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1328 Add Microsoft R Open 3.5.3
  manifests/Microsoft/ROpen/3.5.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1329 Add Windows Terminal Preview 1.0.1401.0
  manifests/Microsoft/WindowsTerminalPreview/1.0.1401.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1312 Add Econap 1.3.4
  manifests/SelectCode/Econap/1.3.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1320 Add Brave 1.9.76
  manifests/BraveSoftware/BraveBrowser/1.9.76.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1336 Fix WeChat
  manifests/Tencent/WeChat/2.9.0.1000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1338 Submitting FarManager version 3.0.0.5577.yaml
  manifests/FarManager/FarManager/3.0.0.5577.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1341 Create 1.18.1.yaml
  manifests/Microsoft/AzureDataStudio/1.18.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1319 Add Simplenote
  manifests/Automattic/Simplenote/1.16.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1376 Add Insomnia Designer
  manifests/Insomnia/InsomniaDesigner/2020.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1464 Add Mumble
  manifests/Mumble/Mumble/1.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1456 Add i2pd 2.32.0
  manifests/PurpleI2P/i2pd/2.32.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1374 Add Rambox CE 0.7.5
  manifests/Rambox/RamboxCE/0.7.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1480 Add Firefox Developer Edition 78.0b1
  manifests/Mozilla/FirefoxDeveloperEdition/78.0b1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1372 Add QMPlay2
  manifests/QMPlay2/QMPlay2/19.12.19.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1369 Add Mailspring 1.7.8
  manifests/Foundry376/Mailspring/1.7.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1365 Add Google Chrome Beta 84.0.4147.30
  manifests/Google/ChromeBeta/84.0.4147.30.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1378 Add CubicSDR
  manifests/CubicSDR/CubicSDR/0.2.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1443 Add Those Funny Funguloids! 1.06
  manifests/MHGames/ThoseFunnyFunguloids/1.06.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1442 Add I Have No Tomatoes 1.5
  manifests/MHGames/IHaveNoTomatoes/1.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1441 Add XnView MP
  manifests/XnSoft/XnViewMP/0.94.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1440 Add FastCopy
  manifests/FastCopy/FastCopy/3.89.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1345 Add Persepolis
  manifests/persepolisdm/persepolis/3.2.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1495 Add Rocks'n'Diamonds 4.1.4.1
  manifests/Artsoft/RocksNDiamonds/4.1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1497 Add Cube 2005.08.29
  manifests/Aardappel/Cube/2005.08.29.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1499 Fixes for DuongDieuPhap.ImageGlass
  manifests/DuongDieuPhap/ImageGlass/7.0.7.26.Yaml
Labels: Azure-Pipeline-Passed

#1501 Fixes for Arduino.Arduino
  manifests/Arduino/Arduino/1.8.12.yaml
Labels: Azure-Pipeline-Passed

#1508 Fixed typo, corrected license and added licenseurl
  manifests/Intel/ExtremeTuningUtility/6.5.1.360.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1390 Fix Docker Desktop Edge Moniker
  manifests/Docker/DockerDesktopEdge/2.3.1.0.45408.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1306 Changed name from "Ruby" to "Ruby with DevKit"
  manifests/RubyInstallerTeam/RubyWithDevkit/2.7.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1385 Add Zygor Guides Client 4.3.8
  manifests/ZygorGuides/ZygorClient/4.3.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1308 Moving Liberica JDK 11 into a separate package.
  manifests/BellSoft/LibericaJDK11/11.0.7.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1307 Moving Liberica JDK8 onto a separate package.
  manifests/BellSoft/LibericaJDK8/8.0.252.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1382 Update mRemoteNG manifest
  manifests/mRemoteNG/mRemoteNG/1.76.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1387 Remove obsolete manifest
  manifests/Docker/DockerDesktop/2.3.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1311 add XunleiMediaPlayer
  manifests/Xunlei/XunleiMediaPlayer/6.1.7.810.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1391 Add BPBible 0.5.3.1
  manifests/BPBible/BPBible/0.5.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1392 add DjVuLibre DjView 4.11
  manifests/DjVuLibre/DjView/4.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1393 Add Virtual Magnifying Glass 3.6
  manifests/VirtualMagnifyingGlass/VirtualMagnifyingGlass/3.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1384 Add Cisco Webex Meetings
  manifests/Cisco/CiscoWebexMeetings/40.4.10.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1205 Update to PresenceLight
  manifests/isaaclevin/presencelight/2.0.49.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1147 Add Betaflight Configurator 10.6.0
  manifests/Betaflight/Betaflight-Configurator/10.6.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#797 Add LINE 6.0.3.2213
  manifests/LINE/LINE/6.0.3.2213.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1002 Add Buttercup password manager
  manifests/Buttercup/Buttercup/1.19.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1403 Add Gramps 5.1.2
  manifests/Gramps/Gramps/5.1.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1210 Prevent auto restart after LibreOffice install
  manifests/LibreOffice/LibreOffice/6.4.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1395 Add Cyberduck 7.4.0
  manifests/Iterate/Cyberduck/7.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1262 Add manifest for OpenShot
  manifests/OpenShot/OpenShot/2.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1394 Add Streamlink
  manifests/Streamlink/Streamlink/1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1404 Add LibreCAD
  manifests/LibreCAD/LibreCAD/2.1.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1405 Add OpenSCAD
  manifests/OpenSCAD/OpenSCAD/2019.05.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1400 Add FreeMat 4.2
  manifests/FreeMat/FreeMat/4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1415 Change Maxima installer type to nullsoft
  manifests/MaximaTeam/Maxima/5.43.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1413 Gitter uses inno setup
  manifests/GitLab/Gitter.IM/4.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1425 Add MusicBrainz Picard
  manifests/MusicBrainz/Picard/2.3.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1411 Add Opera GX
  manifests/Opera/OperaGX/68.0.3618.142.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1412 Add Pidgin IM
  manifests/Pidgin/Pidgin/2.13.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1214 Add Intel® Driver & Support Assistant
  manifests/Intel/IntelDriverandSupportAssistant/20.6.22.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1428 Add Visual C++ 2010 SP1 Redistributable (x86)
  manifests/Microsoft/VC++2010Redist-x86/10.0.40219.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1447 Added sqlitebrowser
  manifests/SQLiteBrowser/SQLiteBrowser/3.11.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1451 Add FlightGear
  manifests/FlightGear/FlightGear/2018.3.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1468 Add FontForge 2020.03.14
  manifests/FontForge/FontForge/2020.03.14.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1490 Add Pingus 0.7.6
  manifests/IngoRuhnke/Pingus/0.7.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1498 Wireshark: Switch to x64.
  manifests/WiresharkFoundation/Wireshark/3.2.4.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1502 Fixes for unifi.controller
  manifests/Ubiquiti/UnifiNetworkController/5.12.72.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1505 Update ImageMagick 7.0.10 to -16
  manifests/ImageMagick/ImageMagick/7.0.10-16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1512 Add ImageMagick 6.9.11-16
  manifests/ImageMagick/ImageMagick/6.9.11-16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1431 Add Lightbulb
  manifests/Tyrrrz/LightBulb/2.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1516 Add AzureCLI 2.7.0
  manifests/Microsoft/AzureCLI/2.7.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1521 Add VCV Rack
  manifests/VCVRack/VCVRack/1.1.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1525 Add Firefox ESR 68.9.0esr
  manifests/Mozilla/FirefoxESR/68.9.0esr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1407 Change Resource Hacker installer type to inno
  manifests/AngusJohnson/ResourceHacker/5.1.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1513 Add Canonical.MicroK8s 2.0.0
  manifests/canonical/MicroK8s/2.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1408 Signal uses nullsoft
  manifests/Signal/Signal/1.34.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1522 Use updated description for streamlink
  manifests/Streamlink/Streamlink/1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1417 Add RawTherapee
  manifests/RawTherapee/RawTherapee/5.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1530 Added Plex Media Server 1.19.4.2902
  manifests/Plex/PlexMediaServer/1.19.4.2902.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1542 Add llvm installer
  manifests/LLVM/LLVM/10.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1537 Add GhostScript
  manifests/ArtifexSoftware/GhostScript/9.52.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1546 Fixes for Stellarium.Stellarium
  manifests/Stellarium/Stellarium/0.20.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1548 Add WinDirStat 1.1.2
  manifests/WinDirStat/WinDirStat/1.1.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1554 Add GnuWin32.Wget
  manifests/GnuWin32/Wget/1.11.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1559 Add Zulip
  manifests/Zulip/Zulip/5.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1568 Add MariaDB server
  manifests/MariaDB/Server/10.4.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1580 Add PowerToys 0.18.2
  manifests/Microsoft/PowerToys/0.18.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1574 Add Sonos Controller
  manifests/Sonos/Controller/11.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1587 Added proper casing and description to Transmission
  manifests/Transmission/Transmission/3.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1590 WinSCP uses InnoSetup
  manifests/WinSCP/WinSCP/5.17.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1564 Add IRCCloud Desktop
  manifests/IRCCloud/IRCCloud/0.15.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1581 Fixed description and added tags to Windows Terminal
  manifests/Microsoft/WindowsTerminal/1.0.1401.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1557 Update to GnuWin32.Make
  manifests/GnuWin32/Make/3.81.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1410 Add Tux Paint Stamps
  manifests/NewBreedSoftware/TuxPaintStamps/2018.09.01.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1409 Add Strix Music
  manifests/ArloG/StrixMusic/1.4.7.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1594 Add Vim 8.2.0905
  manifests/vim/vim/8.2.0905.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1433 Add Zint 2.4.2.0
  manifests/Zint/Zint/2.4.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1430 Add Jackett 0.16.589
  manifests/Jackett/Jackett/0.16.589.yaml
Labels: Needs: author feedback, Validation-Completed, Validation-SmartScreen

#1429 Add QuiteRSS 0.19.4
  manifests/QuiteRSS/QuiteRSS/0.19.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1449 Add Krita
  manifests/KDE/Krita/4.2.9.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1426 Add Visual C++ 2015-2019 Redistributable (x64)
  manifests/Microsoft/VC++2015-2019Redist-x64/14.26.28720.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1427 Add Visual C++ 2015-2019 Redistributable (x86)
  manifests/Microsoft/VC++2015-2019Redist-x86/14.26.28720.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1424 Add Visual C++ 2010 SP1 Redistributable (x64)
  manifests/Microsoft/VC++2010Redist-x64/10.0.40219.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#849 Add Microsoft Mouse and Keyboard Center
  manifests/Microsoft/MouseAndKeyboardCenter/12.181.137.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1450 Add DirectX end user runtime web installer
  manifests/Microsoft/DirectX/9.29.1974.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1134 Adding Microsoft Visio Viewer 2016
  manifests/Microsoft/VisioViewer/16.0.433.1001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1165 Add Intel® Driver & Support Assistant 20.5.20.3
  manifests/Intel/IntelDriverAndSupportAssistant/20.5.20.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1258 Add AngryIPScanner 3.7.1
  manifests/angryziber/AngryIPScanner/3.7.1.yaml
Labels: Azure-Pipeline-Passed, Blocking-Issue, Validation-Completed

#1389 Add GnuPG 2.2.20 CLI tool
  manifests/gnupg/GnuPG/2.2.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1452 Create 1.3.959.yaml
  manifests/RStudio/RStudio/1.3.959.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1296 Fix GNU Emacs 27.0.91 license
  manifests/GNU/Emacs/27.0.91.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1297 Add PicoTorrent manifest 0.18.0
  manifests/PicoTorrent/PicoTorrent/0.18.0.yaml
Labels: Azure-Pipeline-Passed

#1462 Add Remote Desktop Manager
  manifests/Devolutions/RemoteDesktopManager/2020.1.20.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1200 add manifest for Ryzom an open source mmorpg
  manifests/WinchGate/Ryzom/3.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1459 Add Iometer 1.1.0
  manifests/Intel/Iometer/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1601 add remote.it
  manifests/remot3it/remoteit/2.5.32.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1606 Add Lazarus
  manifests/Lazarus/Lazarus/2.0.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1610 Add HeidiSQL 11.0.0.5919
  manifests/AnsgarBecker/HeidiSQL/11.0.0.5919.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1614 Add HeidiSQL Nightly 11.0.0.5995
  manifests/AnsgarBecker/HeidiSQLNightly/11.0.0.5995.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1422 TeamSpeak client uses nullsoft
  manifests/TeamSpeakSystems/TeamSpeakClient/3.5.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1457 Add SoftPerfect Network Scanner 7.2.8
  manifests/SoftPerfect/SoftPerfectNetworkScanner/7.2.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1524 Add Firefox 77.0
  manifests/Mozilla/Firefox/77.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1463 Add Wayk Now
  manifests/Devolutions/WaykNow/2020.1.7.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1377 Add GNURadio
  manifests/GNURadio/GNURadio/3.7.13.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#1435 Fix Kdenlive manifest
  manifests/KDE/Kdenlive/20.04.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#159 Persepolis team
  manifests/Persepolis/DownloadManager/3.2.0.0.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#488 Add WinPower
  manifests/francescosorge/winpower/0.1.yaml
Labels: Validation-Completed

#471 Add Motrix
  manifests/agalwood/Motrix/1.5.10.yaml
Labels: Validation-Completed

#474 Add stack
  manifests/commercialhaskell/stack/2.3.1.yaml
Labels: Validation-Completed

#743 Add GitHubReleaseNotes
  manifests/StefHeyenrath/GitHubReleaseNotes/1.0.5.3.yaml
Labels: Validation-Completed

#1469 Add ONLYOFFICE Desktop Editors 5.5.1
  manifests/ONLYOFFICE/DesktopEditors/5.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#853 Nelson 0.4.4 available in winget
  manifests/NelsonNumericalSoftware/Nelson/0.4.4.yaml
Labels: Validation-Completed

#692 Amazon Chime 4.31.9473
  manifests/Amazon/Chime/4.31.9473.yaml
Labels: Validation-Completed

#1142 Add Kebler
  manifests/Kebler/Kebler/0.4.0.0.yaml
Labels: Validation-Completed, Validation-SmartScreen
