Repository microsoft/winget-pkgs, pull requests merged in 2020-10, with the labels that each got.

#3856 Add BatteryBarPro
  manifests/OsirisDevelopment/BatteryBar/3.6.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3818 OneDrive Internal Fast version 20.194.0927.0002
  manifests/Microsoft/OneDriveInternalFast/20.194.0927.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3855 Add Docker Desktop edge version 2.4.1.0.48583
  manifests/Docker/DockerDesktopEdge/2.4.1.0.48583.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3824 Update powershell-preview to 7.1.0-rc.1
  manifests/Microsoft/PowerShell-Preview/7.1.0-rc.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3826 Update signal to 1.36.3
  manifests/Signal/Signal/1.36.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3829 Update Etcher to 1.5.109
  manifests/Balena/Etcher/1.5.109.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3831 Add PowerShell Universal 1.4
  manifests/IronmanSoftware/PowerShellUniversal/1.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3834 Add PhonerLite 2.84.0.yaml
  manifests/PhonerLite/PhonerLite/2.84.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3842 Docker Desktop Internal version 2.4.0.1-48573
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48573.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3852 Submitting Doomsday 2.2.2.yaml
  manifests/Doomsday/Doomsday/2.2.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3843 Docker Desktop Edge Internal version 2.4.1.0-48579
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48579.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3854 WeMod version 6.3.10
  manifests/WeMod/WeMod/6.3.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3859 Update CoreTemp to 1.16.1
  manifests/Alcpu/CoreTemp/1.16.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3847 Node.js Nightly version 15.0.0-20201001
  manifests/OpenJS/NodeJSNightly/15.0.0-20201001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3848 OneDrive Internal Fast version 20.195.0928.0002
  manifests/Microsoft/OneDriveInternalFast/20.195.0928.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3844 Discord Development version 0.0.7761
  manifests/Discord/DiscordDevelopment/0.0.7761.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3853 Update Calibre 5.0.1.yaml
  manifests/calibre/calibre/5.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3860 Added Python version 3.8.6
  manifests/Python/Python/3.8.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3862 Update 010 Editor to 11.0
  manifests/SweetScape/010Editor/11.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3863 Updated Parsec to version 150.50
  manifests/ParsecCloudInc/Parsec/150.50.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3864 New hash fix for Google Chrome
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3846 VLC media player nightly version 4.0.0-20201001
  manifests/VideoLAN/VLCNightly/4.0.0-20201001.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3816 VLC media player nightly version 4.0.0-20200930
  manifests/VideoLAN/VLCNightly/4.0.0-20200930.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3827 Update Alchemy Viewer to 6.3.6.46705
  manifests/Alchemy/Viewer/6.3.6.46705.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3838 Submitting Fedora Media Writer version 4.1.6.yaml
  manifests/Fedora/FedoraMediaWriter/4.1.6.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3880 Microsoft.VisualStudioCodeInsiders_v1.50.15.5052a7bc2e
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.15.5052a7bc2e.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3879 Microsoft.VisualStudioCode_v1.49.2.e5e9e69aed
  manifests/Microsoft/VisualStudioCode/1.49.2.e5e9e69aed.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3883 Microsoft.VisualStudioCodeInsiders_v1.50.16.0ecb64a2c8
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.16.0ecb64a2c8.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3878 beyondcompare 4.3.6.25063
  manifests/ScooterSoftware/beyondcompare/4.3.6.25063.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3876 Microsoft Teams 1.3.00.24755
  manifests/Microsoft/Teams/1.3.00.24755.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3867 Eraser 6.2.0.2990
  manifests/Eraser/Eraser/6.2.0.2990.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3871 add itunes 12.10.9.3
  manifests/Apple/iTunes/12.10.9.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3872 Microsoft Edge Stable v85.0.564.68
  manifests/Microsoft/Edge/85.0.564.68.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3873 Add Skype 8.65.0.76
  manifests/Microsoft/Skype/8.65.0.76.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3866 Update and rename manifests/PhonerLite/PhonerLite/2.84.0.yaml to mani…
  manifests/Phoner/PhonerLite/2.84.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3869 Add Telegram 2.4.1
  manifests/Telegram/TelegramDesktop/2.4.1.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3891 Microsoft.VisualStudioCode_v1.49.3.2af051012b
  manifests/Microsoft/VisualStudioCode/1.49.3.2af051012b.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3875 Kicad
  manifests/KiCad/KiCad/5.1.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3921 Dropbox v106.4.368
  manifests/Dropbox/Dropbox/106.4.368.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3919 Opera v71.0.3770.198
  manifests/Opera/Opera/71.0.3770.198.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3918 CrystalDiskInfo Shizuku Edition v8.8.9
  manifests/CrystalDewWorld/CrystalDiskInfoShizukuEdition/8.8.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3917 CrystalDiskInfo Kurei Kei Edition v8.8.9
  manifests/CrystalDewWorld/CrystalDiskInfoKureiKeiEdition/8.8.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3920 Brave v1.15.69
  manifests/BraveSoftware/BraveBrowser/1.15.69.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3916 CrystalDiskInfo v8.8.9
  manifests/CrystalDewWorld/CrystalDiskInfo/8.8.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3913 StreamlabsOBS v0.24.0
  manifests/Streamlabs/StreamlabsOBS/0.24.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3912 Intel Driver & Support Assistant v20.9.36.10
  manifests/Intel/IntelDriverAndSupportAssistant/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3911 HWiNFO v6 .32
  manifests/REALiX/HWiNFO/6.32.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3910 Malwarebytes v4.2.1.89
  manifests/Malwarebytes/Malwarebytes/4.2.1.89.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3886 Add Trelby, a free and open source screenwriting program
  manifests/Trelby/Trelby/2.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3887 Add version 2.0.9 of Notion app
  manifests/Notion/Notion/2.0.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3890 Add WhatsApp 2.2039.9
  manifests/WhatsApp/WhatsApp/2.2039.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3906 Docker Desktop Edge Internal version 2.4.2.0-48619
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48619.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3885 Added Trufflesuite's Ganache v2.4.0
  manifests/Trufflesuite/ganache/2.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3905 Docker Desktop Internal version 2.4.0.1-48597
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48597.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3904 Lenovo System Update v5.07.0110
  manifests/Lenovo/SystemUpdate/5.07.0110.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3903 Add Dell Command Update v3.1.3
  manifests/Dell/CommandUpdate/3.1.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3897 NZXT CAM 4.12.0
  manifests/NZXT/CAM/4.12.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3898 Everything v1.4.1.992
  manifests/voidtools/Everything/1.4.1.992.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3902 AWS SAM CLI 1.4.0
  manifests/Amazon/SAM-CLI/1.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3899 NZXT CAM 4.13.0
  manifests/NZXT/CAM/4.13.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3922 Delete Beyond Compare 4 version 4.3.4.24657 due to broken installer
  manifests/ScooterSoftware/BeyondCompare4/4.3.4.24657.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3901 AWS SAM CLI 1.3.2
  manifests/Amazon/SAM-CLI/1.3.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3895 Delete Google Chrome Beta invalid specific version
  manifests/Google/ChromeBeta/84.0.4147.38.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3894 Delete Google Chrome Beta invalid specific version
  manifests/Google/ChromeBeta/84.0.4147.30.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3907 Node.js Nightly version 15.0.0-20201002
  manifests/OpenJS/NodeJSNightly/15.0.0-20201002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3893 Google Chrome Beta Latest 86.0.4240.68
  manifests/Google/ChromeBeta/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3900 AWS SAM CLI 1.2.0
  manifests/Amazon/SAM-CLI/1.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3923 Update 2.84.0.yaml
  manifests/Phoner/PhonerLite/2.84.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3908 AWS CLI v2.0.54
  manifests/Amazon/AWSCLI/2.0.54.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3914 Bitwarden v1.22.2
  manifests/Bitwarden/Bitwarden/1.22.2.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3861 Update Jackett to 0.16.1472
  manifests/Jackett/Jackett/0.16.1472.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3874 add geth (1.9.22)
  manifests/Ethereum/geth/1.9.22.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3940 Add switches for Discord Canary version 0.0.283
  manifests/Discord/DiscordCanary/0.0.283.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3941 Add switches for Discord version 0.0.308
  manifests/Discord/Discord/0.0.308.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3942 Update license URL for Fiddler Everywhere version 1.1.0
  manifests/Telerik/FiddlerEverywhere/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3951 bitsmanager 1.12
  manifests/Microsoft/bitsmanager/1.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3949 Add Ghostscript 9.53.3.yaml
  manifests/ArtifexSoftware/GhostScript/9.53.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3930 Update 5.1.7.yaml
  manifests/KiCad/KiCad/5.1.7.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3925 update ScreenToGif to 2.27.3
  manifests/NickeManarin/ScreenToGif/2.27.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3926 snaketail 1.9.6
  manifests/snakefoot/snaketail/1.9.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3931 Update 150.50.yaml
  manifests/ParsecCloudInc/Parsec/150.50.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3927 Update 1.2.10.6.Yaml
  manifests/Greenshot/Greenshot/1.2.10.6.Yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3932 Oracle VM VirtualBox Test version 6.1.15-140728
  manifests/Oracle/VirtualBoxTest/6.1.15-140728.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3934 Node.js Nightly version 15.0.0-20201003
  manifests/OpenJS/NodeJSNightly/15.0.0-20201003.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3935 Microsoft OneDrive Internal Fast version 20.198.0930.0001
  manifests/Microsoft/OneDriveInternalFast/20.198.0930.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3936 Docker Desktop Edge Internal version 2.4.2.0-48621
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48621.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3937 Discord Development version 0.0.7762
  manifests/Discord/DiscordDevelopment/0.0.7762.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3939 Add switches for Discord PTB version 0.0.55
  manifests/Discord/DiscordPTB/0.0.55.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3928 Update 8.7.3.46663.yaml
  manifests/SanfordLP/DYMOLabel/8.7.3.46663.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3953 Added Spotify version 1.1.43.700
  manifests/Spotify/Spotify/1.1.43.700.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3952 Add Files v0.15.4
  manifests/Files-Community/Files/0.15.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3943 Update name for Microsoft OneDrive Insiders version 20.174.0830.0002
  manifests/Microsoft/OneDriveInsiders/20.174.0830.0002.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3945 Update name for Microsoft OneDrive Internal Slow version 20.174.0830.0002
  manifests/Microsoft/OneDriveInternalSlow/20.174.0830.0002.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Needs: Attention, Validation-Completed

#3944 Update name for Microsoft OneDrive Enterprise version 20.114.0607.0002
  manifests/Microsoft/OneDriveEnterprise/20.114.0607.0002.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3958 Docker Desktop Edge Internal version 2.4.2.0-48632
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48632.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3957 Microsoft OneDrive Internal Slow version 20.189.0920.0003
  manifests/Microsoft/OneDriveInternalSlow/20.189.0920.0003.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3841 Microsoft OneDrive version 20.169.0823.0006
  manifests/Microsoft/OneDrive/20.169.0823.0006.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3950 Chefdk4.11.0
  manifests/chef/chefdk/4.11.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3960 expresso 3.1.6224
  manifests/ultrapico/expresso/3.1.6224.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3963 azure-iot-explorer 0.10.16
  manifests/Microsoft/azure-iot-explorer/0.10.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3962 Add PSPad text editor
  manifests/JanFiala/PSPad/5.0.3.377.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3965 git-credential-manager-core: add GCM Core 2.0.252
  manifests/Microsoft/GitCredentialManagerCore/2.0.252.766.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3964 Darktable 3.2.1
  manifests/darktable/darktable/3.2.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3961 streamdeck 4.8.2.13041
  manifests/elgato/streamdeck/4.8.2.13041.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3966 Microsoft.VisualStudioCodeInsiders_v1.50.17.66b6964272
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.17.66b6964272.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3973 webpicmd 5.1
  manifests/Microsoft/webpicmd/5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3959 butterflow-ui 1.1.0
  manifests/wagesj45/butterflow-ui/1.1.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3955 FileZilla Client Nightly version 3.50.0-20201004
  manifests/TimKosse/FileZillaClientNightly/3.50.0-20201004.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3970 Added Python 3.9.0
  manifests/Python/Python/3.9.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3954 VLC media player nightly version 4.0.0-20201004
  manifests/VideoLAN/VLCNightly/4.0.0-20201004.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3929 Create 7.5.14.yaml
  manifests/Hyne/TimberDesign/7.5.14.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3969 Add RoyalTS 5.03.60925.0
  manifests/RoyalApps/RoyalTS/5.03.60925.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3968 Add Geekbench 5.2.4
  manifests/PrimateLabs/Geekbench/5.2.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3889 Add version 5.32.0.1 of StrawberryPerl
  manifests/StrawberryPerl/StrawberryPerl/5.32.0.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3888 add twinkle-tray 1.12.2
  manifests/XanderFrangos/TwinkleTray/1.12.2.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3980 FileZilla Client Nightly version 3.50.0-20201006
  manifests/TimKosse/FileZillaClientNightly/3.50.0-20201006.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3975 Update Seq to 2020.3.4761
  manifests/Datalust/Seq/2020.3.4761.yaml
Labels: Needs: author feedback, URL-Validation-Error, Validation-Completed

#3933 VLC media player nightly version 4.0.0-20201003
  manifests/VideoLAN/VLCNightly/4.0.0-20201003.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3985 Microsoft.VisualStudioCodeInsiders_v1.50.18.2ccf79510a
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.18.2ccf79510a.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3984 Docker Desktop Edge Internal version 2.4.2.0-48676
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48676.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3983 Docker Desktop Internal version 2.4.0.1-48671
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48671.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3988 Microsoft.VisualStudioCodeInsiders_v1.50.19.b0231fd684
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.19.b0231fd684.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3986 Fiddler Everywhere Internal version 1.1.0-internal
  manifests/Telerik/FiddlerEverywhereInternal/1.1.0-internal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3989 Added 1Password version 7.6.785
  manifests/AgileBits/1Password/7.6.785.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3987 Fiddler Everywhere Insiders version 1.1.0-insiders
  manifests/Telerik/FiddlerEverywhereInsiders/1.1.0-insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3981 Oracle VM VirtualBox Test version 6.1.15-140753
  manifests/Oracle/VirtualBoxTest/6.1.15-140753.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3946 Add ModernFlyouts 0.6
  manifests/ModernFlyouts/ModernFlyouts/0.6.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3909 VLC media player nightly version 4.0.0-20201002
  manifests/VideoLAN/VLCNightly/4.0.0-20201002.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3991 Microsoft.VisualStudioCodeInsiders_v1.50.20.93c2f0fbf1
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.20.93c2f0fbf1.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3995 Added GeForce Now version 2.0.24.94
  manifests/Nvidia/GeForceNow/2.0.24.94.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3956 Node.js Nightly version 15.0.0-20201004
  manifests/OpenJS/NodeJSNightly/15.0.0-20201004.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3996 Added JetBrains Toolbox version 1.18.7455
  manifests/JetBrains/Toolbox/1.18.7455.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3998 - adds manifest for GitHub CLI 1.1.0
  manifests/GitHub/cli/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4002 Create 7.10.01.yaml
  manifests/Concept2/Utility/7.10.01.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4004 Update and rename 10.15.2.Yaml to 10.18.8.Yaml
  manifests/EpicGames/EpicGamesLauncher/10.18.8.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3994 Appget 1.0.12.0
  manifests/appget/appget/1.0.12.0.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#3947 Create 8.9.0.yaml for Oliver Schwendener's ueli
  manifests/Oliverschwendener/ueli/8.9.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3993 Mozilla Thunderbird v78.3.2
  manifests/Mozilla/Thunderbird/78.3.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3982 Node.js Nightly version 15.0.0-20201006
  manifests/OpenJS/NodeJSNightly/15.0.0-20201006.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3974 Azure iot explorer0.12.0
  manifests/Microsoft/azure-iot-explorer/0.12.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4006 Added Firefox Developer Edition version 82.0b8
  manifests/Mozilla/FirefoxDeveloperEdition/82.0b8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4018 Welink 6.10.2
  manifests/Huawei/Welink/6.10.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4016 Docker Desktop Edge Internal version 2.4.2.0-48734
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48734.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4011 FileZilla Client Nightly version 3.50.0-20201007
  manifests/TimKosse/FileZillaClientNightly/3.50.0-20201007.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4014 Microsoft OneDrive Internal Fast version 20.201.1005.0002
  manifests/Microsoft/OneDriveInternalFast/20.201.1005.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3972 hosts-file-editor 1.2.0
  manifests/scottlerch/hosts-file-editor/1.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3976 Adding UXL Launcher 3.3.1's manifest.
  manifests/DrewNaylor/UXL-Launcher/3.3.1.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4015 Docker Desktop Internal version 2.4.0.1-48736
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48736.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3967 Add VSCodium 1.49.3
  manifests/VSCodium/VSCodium/1.49.3.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3990 Update to 3.6.10
  manifests/QL-Win/QuickLook/3.6.10.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen
