Repository microsoft/winget-pkgs, pull requests merged in 2020-09, with the labels that each got.

#3362 Microsoft.VisualStudioCodeInsiders_v1.49.19.b6d4fec371
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.19.b6d4fec371.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3360 Update FormatFactory to 5.4
  manifests/FreeTime/FormatFactory/5.4.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3339 Update and rename Mozilla/Firefox/Firefox_v80.0/80.0.yaml to Mozilla/Firefox/80.0.yaml
  manifests/Mozilla/Firefox/80.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3340 Update and rename Mozilla/Thunderbird/Thunderbird_v78.1.1/78.1.1.yaml to Mozilla/Thunderbird/78.1.1.yaml
  manifests/Mozilla/Thunderbird/78.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3350 Google Chrome version renamed to latest + update
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3351 Delete Outdated Google Chrome Manifest
  manifests/Google/Chrome/83.0.4103.116.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3358 Update WhatsApp to 2.2035.14
  manifests/WhatsApp/WhatsApp/2.2035.14.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3356 Add Blender 2.90.0
  manifests/BlenderFoundation/Blender/2.90.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3357 Add Postman 7.31.1
  manifests/Postman/Postman/7.31.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3361 NZXT CAM v4.11.0
  manifests/NZXT/CAM/4.11.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3363 Add NTLite 2.0.0.7618
  manifests/Nlitesoft/NTLite/2.0.0.7618.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3364 Add GoodSync 11.3.2.2
  manifests/SiberSystems/GoodSync/11.3.2.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3359 Update Uplay to 113.0.9220
  manifests/Ubisoft/Uplay/113.0.9220.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3369 AWS SAM CLI v1.1.0
  manifests/Amazon/SAM-CLI/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3371 Google Earth Pro v7.3.3 hash update
  manifests/Google/EarthPro/7.3.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3368 Add Glimpse 0.2.0
  manifests/Glimpse/Glimpse/0.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3370 Google BackupAndSync v3.50.3166.0017 / latest.yaml
  manifests/Google/BackupAndSync/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3379 mymoney 1.1.65
  manifests/LovettSoftware/MyMoney.Net/1.1.65.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3377 AnyDesk v6.0.8 / latest.yaml
  manifests/AnyDeskSoftwareGmbH/AnyDesk/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3336 Updated RunJS to Latest Version
  manifests/lukehaas/RunJS/1.11.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3375 Add Docker Desktop edge version 2.3.6.0.47622
  manifests/Docker/DockerDesktopEdge/2.3.6.0.47622.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3333 Include JabRef 5.1
  manifests/JabRef/JabRef/5.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3316 add Typora 0.9.95
  manifests/Typora/Typora/0.9.95.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3374 Add Unified Remote 3.7.0.2352
  manifests/UnifiedIntents/UnifiedRemote/3.7.0.2352.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3372 WizTree v3.35.yaml
  manifests/AntibodySoftware/WizTree/3.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3366 Add OpenSSL Light 1.1.1
  manifests/ShiningLight/OpenSSLLight/1.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3378 Update and rename Mozilla/Thunderbird/Thunderbird_v78.1.0/78.1.0.yaml to Mozilla/Thunderbird/78.1.0.yaml
  manifests/Mozilla/Thunderbird/78.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3349 ShareX v13.2.0
  manifests/ShareX/ShareX/13.2.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3314 Update Emacs-27.1. (Release Date: 2020-08-21 13:48)
  manifests/GNU/Emacs/27.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3380 Fix .xml file association
  manifests/Microsoft/XMLNotepad/2.8.0.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3382 Microsoft.VisualStudioCodeInsiders_v1.49.20.00754e4bab
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.20.00754e4bab.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3400 CrystalDiskInfo Shizuku Edition v8.8.2
  manifests/CrystalDewWorld/CrystalDiskInfoShizukuEdition/8.8.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3399 CrystalDiskInfo Kurei Kei Edition v8.8.2
  manifests/CrystalDewWorld/CrystalDiskInfoKureiKeiEdition/8.8.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3320 7+ Taskbar Tweaker v5.9.1 + Latest.yaml Suggestion
  manifests/rammichael/7+TaskbarTweaker/Latest.yaml
Labels: Needs SmartScreen Investigation, Needs: Attention, URL-Validation-Error, Validation-Completed, Validation-SmartScreen

#3407 Add isaaclevin.presencelight 3.0.19.yaml
  manifests/isaaclevin/presencelight/3.0.19.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3405 Nvidia RTX Voice v0.5.12.6
  manifests/Nvidia/RTXVoice/0.5.12.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3381 Create 2.01.yaml
  manifests/NirSoft/ShellExView/2.01.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3383 add RescueTime V2.16.3.1
  manifests/RescueTime/RescueTime/2.16.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3386 Add Opera 70.0.3728.144
  manifests/Opera/Opera/70.0.3728.144.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3387 Add Winzip 25.0
  manifests/Corel/WinZip/25.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3410 Microsoft.VisualStudioCodeInsiders_v1.49.21.8c9b4015fe
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.21.8c9b4015fe.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3404 Create 4.0.0.yaml
  manifests/RProject/Rtools/4.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3390 Add PostgreSQL 12.4.1.yaml
  manifests/PostgreSQL/PostgreSQL/12.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3403 Firefox v80.0.1
  manifests/Mozilla/Firefox/80.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3395 Created VMware Horizon Client 8.0.0-16531419.yaml
  manifests/VMware/HorizonClient/8.0.0-16531419.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3401 TrayStatus v4.4.0.0
  manifests/BinaryFortress/TrayStatus/4.4.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3398 CrystalDiskInfo v8.8.2
  manifests/CrystalDewWorld/CrystalDiskInfo/8.8.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3418 Add Paragon Backup & Recovery CE 17.9.3.4927
  manifests/Paragon/ParagonBackupRecoveryCE/17.9.3.4927.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3416 Create 1.21.0.yaml
  manifests/Microsoft/AzureDataStudio/1.21.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3413 Microsoft Edge Dev v86.0.622.3
  manifests/Microsoft/EdgeDev/86.0.622.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3409 Add Golang New Version 1.15.1
  manifests/Golang/Go/1.15.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3421 Microsoft.VisualStudioCodeInsiders_v1.49.22.e2f63c9013
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.22.e2f63c9013.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3425 Add Node.js 14.9.0
  manifests/OpenJS/NodeJS/14.9.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3424 Update and rename 5.33.yaml to 5.34.yaml
  manifests/Bandisoft/Honeyview/5.34.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3420 Update FormatFactory to 5.4.5
  manifests/FreeTime/FormatFactory/5.4.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3422 Twitch App v8.0.0.20200710
  manifests/Twitch/Twitch/8.0.0.20200710.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3408 Add Golang New Version 1.14.8
  manifests/Golang/Go/1.14.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3427 Microsoft.VisualStudioCodeInsiders_v1.49.23.45c70c29e5
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.23.45c70c29e5.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3426 Add Clementine 1.3.1
  manifests/Clementine/Clementine/1.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3428 Add files-uwp v.0.14.0
  manifests/Files-UWP/FilesUWP/0.14.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3432 Microsoft.VisualStudioCodeInsiders_v1.49.24.e4256dd1a0
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.24.e4256dd1a0.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3423 Create 5.0.yaml
  manifests/Ghostgum/GSview/5.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3402 Update OpenShell to 4.4.152
  manifests/Open-Shell/Open-Shell-Menu/4.4.152.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3391 Submitting Intuiter version 0.4.5.yaml
  manifests/Seonglae/Intuiter/0.4.5.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3389 Add nasm manifest
  manifests/NASM/NASM/2.15.05.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3384 majsoul-plus 2.0.0
  manifests/majsoulplus/majsoul-plus/2.0.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3315 Update clash for windows to v0.11.6
  manifests/Fndroid/ClashForWindows/0.11.6.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3242 Add bottom 0.4.6
  manifests/Clement/bottom/0.4.6.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3434 Create 0.2.0.yaml for x86 branch of Glimpse.
  manifests/Glimpse/Glimpse-x86/0.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3406 PowerToys 0.21.1 release
  manifests/Microsoft/PowerToys/0.21.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3429 TencentMeeting 1.9.0.448
  manifests/Tencent/TencentMeeting/1.9.0.448.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3430 QuickAppIde 2.6.2
  manifests/Huawei/QuickAppIde/2.6.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3439 Add Slack 4.9.0
  manifests/SlackTechnologies/Slack/4.9.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3437 Insomnia Designer 2020.3.3
  manifests/Insomnia/InsomniaDesigner/2020.3.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3436 Insomnia 2020.3.3
  manifests/Insomnia/Insomnia/2020.3.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3435 Update Netron to 4.4.9
  manifests/LutzRoeder/Netron/4.4.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3452 Add Vim v8.2.1584
  manifests/vim/vim/8.2.1584.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3451 Add Gource
  manifests/acaudwell/Gource/0.51.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3441 Add MKVToolNix v50.0.0
  manifests/MKVToolNix/MKVToolNix/50.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3450 Add Zoom v5.2.2
  manifests/Zoom/Zoom/5.2.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3442 Add MKVToolNix v49.0.0
  manifests/MKVToolNix/MKVToolNix/49.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3443 Add MKVToolNix v48.0.0
  manifests/MKVToolNix/MKVToolNix/48.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3444 Add MKVToolNix v47.0.0
  manifests/MKVToolNix/MKVToolNix/47.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3455 Update and rename 5.34.yaml to 5.35.yaml
  manifests/Bandisoft/Honeyview/5.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3449 Add GnuCash v4.1
  manifests/Gnucash/Gnucash/4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3448 Add Geogebraclassic v6.0.600.0
  manifests/GeoGebra/GeoGebraClassic/6.0.600.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3463 update linqpad 6.8.yaml to 6.9.15
  manifests/LINQPad/LINQPad/6.9.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3445 Add Coffee v1.0.4
  manifests/StevenCole/Coffee/1.0.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3447 Add Geometry v6.0.600.0
  manifests/GeoGebra/Geometry/6.0.600.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3461 Add CrystalDiskInfo v8.8.5
  manifests/CrystalDewWorld/CrystalDiskInfo/8.8.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3460 Add GPU-Z v2.34.0
  manifests/TechPowerUp/GPU-Z/2.34.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3446 Add GraphingCalculator v6.0.600.0
  manifests/GeoGebra/GraphingCalculator/6.0.600.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3457 Add Vivaldi v3.3.2022.36
  manifests/VivaldiTechnologies/Vivaldi/3.3.2022.36.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3474 Add Etcher v1.5.107
  manifests/Balena/Etcher/1.5.107.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3462 Add Certify SSL Manager v5.1.5.0
  manifests/CertifyTheWeb/CertifySSLManager/5.1.5.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3465 Update Netron to 4.5.0
  manifests/LutzRoeder/Netron/4.5.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3469 wechat-work 3.0.30.2006
  manifests/Tencent/wechat-work/3.0.30.2006.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3477 Add Docker Desktop edge version 2.3.6.1.47792
  manifests/Docker/DockerDesktopEdge/2.3.6.1.47792.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3478 Add new version of Bot Framework Composer: 1.1.1
  manifests/Microsoft/BotFrameworkComposer/1.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3481 Add Postman 7.32.0
  manifests/Postman/Postman/7.32.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3479 Add Potplayer v1.7.21289
  manifests/Daum/Potplayer/1.7.21289.yaml
Labels: Needs: Attention, URL-Validation-Error, Validation-Completed

#3438 Submitting Intuiter version 0.5.0.yaml
  manifests/Seonglae/Intuiter/0.5.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3476 Add PicoTorrent v0.20.0
  manifests/PicoTorrent/PicoTorrent/0.20.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3440 Add VSCodium 1.48.2
  manifests/VSCodium/VSCodium/1.48.2.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3466 Submitting guinget update version 0.1.2.
  manifests/DrewNaylor/guinget/0.1.2.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3453 Add bottom 0.4.7
  manifests/Clement/bottom/0.4.7.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3464 Add MCXStudio 0.9.9
  manifests/COTI/MCXStudio/0.9.9.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3459 Add Dopamine v2.0.4
  manifests/Digimezzo/Dopamine/2.0.4.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3475 Add PicoTorrent v0.19.0
  manifests/PicoTorrent/PicoTorrent/0.19.0.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3488 Microsoft.VisualStudioCodeInsiders_v1.49.25.e790b93138
  manifests/Microsoft/VisualStudioCodeInsiders/1.49.25.e790b93138.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3490 Switch fix for Skype-8.60.0.76.
  manifests/Microsoft/Skype/8.60.0.76.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3489 Add Skype-8.64.0.80.
  manifests/Microsoft/Skype/8.64.0.80.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3487 Add manifest file for PowerShell-Preview 7.1.0-Preview7
  manifests/Microsoft/PowerShell-Preview/7.1.0-preview.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3486 Add ImageMagick-7.0.10-29.
  manifests/ImageMagick/ImageMagick/7.0.10-29.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3485 Create 4.1.4.yaml
  manifests/PDFsam/PDFsam/4.1.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3484 Add GitHubCLI-0.12.0.
  manifests/GitHub/cli/0.12.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3492 Add Docker Desktop edge version 2.3.6.2.47842
  manifests/Docker/DockerDesktopEdge/2.3.6.2.47842.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3491 utaformatix 3.1
  manifests/oxygendioxide/utaformatix/3.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3498 update Accessibility Insights for Windows to 1.1.1334.2
  manifests/Microsoft/AccessibilityInsightsWindows/1.1.1334.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3497 Add Zulip-5.4.3.
  manifests/Zulip/Zulip/5.4.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3496 Add MusicBrainz Picard 2.4.4.yaml
  manifests/MusicBrainz/Picard/2.4.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3480 Add Inkscape v1.0.1
  manifests/Inkscape/Inkscape/1.0.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3495 Add iTunes-12.10.8.5.
  manifests/Apple/iTunes/12.10.8.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3501 Microsoft.VisualStudioCode_v1.49.0.e790b93138
  manifests/Microsoft/VisualStudioCode/1.49.0.e790b93138.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3502 Update 1.0.1.yaml
  manifests/Inkscape/Inkscape/1.0.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3500 Create 3.06.1.yaml
  manifests/Nullsoft/NSIS/3.06.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3509 Microsoft.VisualStudioCodeInsiders_v1.50.1.bc38b0accb
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.1.bc38b0accb.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3505 Add Golang New Version 1.14.9
  manifests/Golang/Go/1.14.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3504 Add Golang New Version 1.15.2
  manifests/Golang/Go/1.15.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3507 add Anki 2.1.33
  manifests/Anki/Anki/2.1.33.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3503 add KeePass 2.46.0.0
  manifests/DominikReichl/KeePass/2.46.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3514 Microsoft.VisualStudioCodeInsiders_v1.50.2.cca20eba89
  manifests/Microsoft/VisualStudioCodeInsiders/1.50.2.cca20eba89.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#3520 Switch fix for gpg4win-3.1.11.
  manifests/gnupg/Gpg4win/3.1.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3510 Add ShareX 13.2.1
  manifests/ShareX/ShareX/13.2.1.yaml
Labels: Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#3519 Switch fix for GnuPG-2.2.20.
  manifests/gnupg/GnuPG/2.2.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3518 Add GnuPG-2.2.23.
  manifests/gnupg/GnuPG/2.2.23.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3516 Update Netron to 4.5.1
  manifests/LutzRoeder/Netron/4.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3517 Add gpg4win-3.1.13.
  manifests/gnupg/Gpg4win/3.1.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3513 add xmind 10.2.1
  manifests/XMind/XMind2020/10.2.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3506 Add Belarc/Advisor-9.6.
  manifests/Belarc/Advisor/9.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3531 Create 7.5.1.yaml
  manifests/Hyne/TimberDesign/7.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3527 update SurfaceDuoEmu to 2020.806
  manifests/Microsoft/SurfaceDuoEmulator/2020.806.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3526 Fix spelling in Netron manifest
  manifests/LutzRoeder/Netron/4.5.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#3522 Add LibreOffice v7.0.1
  manifests/LibreOffice/LibreOffice/7.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3508 Create 3.1.8.29220.yaml
  manifests/Microsoft/dotnetruntime/3.1.8.29220.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3533 Add Puppet Agent v6.18.0
  manifests/Puppet/puppet-agent/6.18.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3546 Add Kate-20.08.1-1006.
  manifests/KDE/Kate/20.08.1-1006.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3539 add dji assistant 2 for aeroscope 2.0.1
  manifests/DJI/DJIAssistant2ForAeroScope/2.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3534 Add Puppet Bolt v2.27.0
  manifests/Puppet/puppet-bolt/2.27.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#3532 Add Ghostscript 9.53
  manifests/ArtifexSoftware/GhostScript/9.53.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
