Repository microsoft/winget-pkgs, pull requests merged in 2020-12, with the labels that each got.

#5043 Update Netron to 4.6.4
  manifests/LutzRoeder/Netron/4.6.4.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#5051 Add Listary 5.00.2843
  manifests/Bopsoft/Listary/5.00.2843.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5052 fixed HASH for CPUID.CPU-Z-1.94.8
  manifests/CPUID/CPU-Z/1.94.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5057 adding sketchup make 2017
  manifests/Trimble/SketchUpMake/17.2.2555.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5058 Add dbeaver 7.3.0
  manifests/DBeaver/DBeaver/7.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5060 Node.js Nightly version 16.0.0-20201130
  manifests/OpenJS/NodeJSNightly/16.0.0-20201130.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5071 Added AWS CLI version 2.1.4.
  manifests/Amazon/AWSCLI/2.1.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5050 added TechPowerUp.GPU-Z 2.36.0
  manifests/TechPowerUp/GPU-Z/2.36.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5118 Remove DockerDesktopInternal 2.4.0.1-48808
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48808.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5117 Remove DockerDesktopInternal 2.4.0.1-48801
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48801.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5131 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201112
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201112.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5127 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201106
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201106.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5126 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201103
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201103.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5114 Remove DockerDesktopInternal 2.4.0.1-48671
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48671.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5132 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201119
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201119.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5124 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201031
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201031.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5129 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201109
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201109.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5116 Remove DockerDesktopInternal 2.4.0.1-48747
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48747.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5119 Remove DockerDesktopInternal 2.4.0.1-48819
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48819.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5125 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201101
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5123 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201030
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201030.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5112 Remove DockerDesktopInternal 2.4.0.1-48573
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48573.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5120 Remove DockerDesktopInternal 2.4.0.1-48859
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48859.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5113 Remove DockerDesktopInternal 2.4.0.1-48597
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48597.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5128 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201107
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201107.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5111 Remove DockerDesktopInternal 2.4.0.0-48533
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48533.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5133 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201121
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201121.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5115 Remove DockerDesktopInternal 2.4.0.1-48736
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48736.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5108 Remove DockerDesktopInternal 2.4.0.0-48459
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48459.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5107 Remove DockerDesktopInternal 2.4.0.0-48440
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48440.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5109 Remove DockerDesktopInternal 2.4.0.0-48480
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48480.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5110 Remove DockerDesktopInternal 2.4.0.0-48506
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48506.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5105 Remove DockerDesktopInternal 2.4.0.0-48261
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48261.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5104 Remove DockerDesktopInternal 2.4.0.0-48231
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48231.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5103 Remove DockerDesktopEdgeInternal 2.4.3.0-49231
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49231.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5102 Remove DockerDesktopEdgeInternal 2.4.3.0-49158
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49158.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5106 Remove DockerDesktopInternal 2.4.0.0-48353
  manifests/Docker/DockerDesktopInternal/2.4.0.0-48353.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5101 Remove DockerDesktopEdgeInternal 2.4.3.0-49137
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49137.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5075 Remove DockerDesktopEdgeInternal 2.4.1.0-48078
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48078.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5077 Remove DockerDesktopEdgeInternal 2.4.1.0-48234
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48234.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5079 Remove DockerDesktopEdgeInternal 2.4.1.0-48350
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48350.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5078 Remove DockerDesktopEdgeInternal 2.4.1.0-48271
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48271.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5081 Remove DockerDesktopEdgeInternal 2.4.1.0-48466
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48466.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5076 Remove DockerDesktopEdgeInternal 2.4.1.0-48140
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48140.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5083 Remove DockerDesktopEdgeInternal 2.4.1.0-48516
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48516.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5084 Remove DockerDesktopEdgeInternal 2.4.1.0-48541
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48541.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5130 Remove manifest that no longer works for FileZilla Client Nightly version 3.51.0-20201111
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201111.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5085 Remove DockerDesktopEdgeInternal 2.4.1.0-48579
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48579.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5080 Remove DockerDesktopEdgeInternal 2.4.1.0-48453
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48453.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5082 Remove DockerDesktopEdgeInternal 2.4.1.0-48479
  manifests/Docker/DockerDesktopEdgeInternal/2.4.1.0-48479.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5098 Remove DockerDesktopEdgeInternal 2.4.3.0-49062
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49062.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5095 Remove DockerDesktopEdgeInternal 2.4.2.0-48909
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48909.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5097 Remove DockerDesktopEdgeInternal 2.4.3.0-49050
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49050.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5099 Remove DockerDesktopEdgeInternal 2.4.3.0-49099
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49099.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5093 Remove DockerDesktopEdgeInternal 2.4.2.0-48816
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48816.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5092 Remove DockerDesktopEdgeInternal 2.4.2.0-48805
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48805.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5096 Remove DockerDesktopEdgeInternal 2.4.2.0-48990
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48990.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5091 Remove DockerDesktopEdgeInternal 2.4.2.0-48751
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48751.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5090 Remove DockerDesktopEdgeInternal 2.4.2.0-48734
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48734.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5094 Remove DockerDesktopEdgeInternal 2.4.2.0-48818
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48818.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5088 Remove DockerDesktopEdgeInternal 2.4.2.0-48632
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48632.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5087 Remove DockerDesktopEdgeInternal 2.4.2.0-48621
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48621.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5089 Remove DockerDesktopEdgeInternal 2.4.2.0-48676
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48676.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5100 Remove DockerDesktopEdgeInternal 2.4.3.0-49104
  manifests/Docker/DockerDesktopEdgeInternal/2.4.3.0-49104.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5121 Remove DockerDesktopInternal 2.4.0.1-48928
  manifests/Docker/DockerDesktopInternal/2.4.0.1-48928.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5086 Remove DockerDesktopEdgeInternal 2.4.2.0-48619
  manifests/Docker/DockerDesktopEdgeInternal/2.4.2.0-48619.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5144 added autodesk fusion360
  manifests/Autodesk/Fusion360/1.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5145 Added PowerToys version 0.27.0.
  manifests/Microsoft/PowerToys/0.27.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5140 Added Dropbox version 110.4.458.
  manifests/Dropbox/Dropbox/110.4.458.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4997 VLC media player nightly version 4.0.0-20201124
  manifests/VideoLAN/VLCNightly/4.0.0-20201124.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4897 Add Open Shop Channel Downloader v1.2.10
  manifests/OpenShopChannel/Downloader/1.2.10.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#5139 Updated Minecraft Launcher to version 2.2.743.
  manifests/Mojang/MinecraftLauncher/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5141 Add Files v0.21.1
  manifests/Files-Community/Files/0.21.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5061 FileZilla Client Nightly version 3.51.0-20201130
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201130.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5138 Added Microsoft Edge version 87.0.664.52.
  manifests/Microsoft/Edge/87.0.664.52.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5063 chefdk 4.12.0
  manifests/chef/chefdk/4.12.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5134 FileZilla Client Nightly version 3.51.0-20201201
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201201.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5065 Add Docker Desktop edge version 2.5.3.50261
  manifests/Docker/DockerDesktopEdge/2.5.3.50261.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5072 speech-platform-runtime 10.0.0
  manifests/Microsoft/speech-platform-runtime/10.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5122 Node.js Nightly version 16.0.0-20201201
  manifests/OpenJS/NodeJSNightly/16.0.0-20201201.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5068 Added iTunes version 12.11.0.26.
  manifests/Apple/iTunes/12.11.0.26.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5064 picpick 5.1.3
  manifests/picpick/picpick/5.1.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5073 add Yinxiang 6.21.22.2498
  manifests/Evernote/Yinxiang/6.21.22.2498.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5069 Added Calibre version 5.6.0.
  manifests/calibre/calibre/5.6.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5021 Updated Ubisoft Connect to 116.2.0.10277
  manifests/Ubisoft/Connect/116.2.0.10277.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5146 Update Signal to 1.38.2
  manifests/Signal/Signal/1.38.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5162 Updated Spotify to version 1.1.47.684.
  manifests/Spotify/Spotify/latest.yaml
Labels: Attention, Azure-Pipeline-Passed, Validation-Completed

#5148 FileZilla Client Nightly version 3.51.0-20201202
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5149 Fiddler Everywhere Internal version 1.3.0-internal
  manifests/Telerik/FiddlerEverywhereInternal/1.3.0-internal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5151 Fiddler Everywhere version 1.3.0
  manifests/Telerik/FiddlerEverywhere/1.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5160 Updated Google Chrome to version 87.0.4280.88.
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5153 Microsoft OneDrive Internal Slow version 20.219.1029.0005
  manifests/Microsoft/OneDriveInternalSlow/20.219.1029.0005.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5155 Discord Canary version 0.0.291
  manifests/Discord/DiscordCanary/0.0.291.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5150 Fiddler Everywhere Insiders version 1.3.0-insiders
  manifests/Telerik/FiddlerEverywhereInsiders/1.3.0-insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5152 Node.js Nightly version 16.0.0-20201202
  manifests/OpenJS/NodeJSNightly/16.0.0-20201202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5154 Discord Development version 0.0.7789
  manifests/Discord/DiscordDevelopment/0.0.7789.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5156 Submitting PathCopyCopy version 19.0.yaml
  manifests/CLechasseur/PathCopyCopy/19.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5070 Added Rufus version 3.13.
  manifests/Rufus/Rufus/3.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5159 Memurai Developer v2.0.3
  manifests/Memurai/MemuraiDeveloper/2.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5137 Create 2.85.0.yaml
  manifests/Phoner/PhonerLite/2.85.0.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#5158 Add GnuCash v4.2
  manifests/Gnucash/Gnucash/4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5167 windowtop 4.1.3
  manifests/gileli121/windowtop/4.1.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5165 Node.js Nightly version 16.0.0-20201203
  manifests/OpenJS/NodeJSNightly/16.0.0-20201203.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5166 utools 1.3.4
  manifests/utools/utools/1.3.4.yaml
Labels: Attention, Azure-Pipeline-Passed, Validation-Completed

#5164 FileZilla Client Nightly version 3.51.0-20201203
  manifests/TimKosse/FileZillaClientNightly/3.51.0-20201203.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5168 - adds manifest for github cli 1.3.1
  manifests/GitHub/cli/1.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5177 Added GOG Galaxy 2.0.26.55
  manifests/GOG/Galaxy/2.0.26.55.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5176 Node.js Nightly version 16.0.0-20201204
  manifests/OpenJS/NodeJSNightly/16.0.0-20201204.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5169 Aimp
  manifests/AIMP/AIMP/4.70.2236.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5171 Create 7.5.0.0.yaml
  manifests/GiorgioTani/PeaZip/7.5.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5172 Add Java JRE 8.0.271
  manifests/Oracle/JavaRuntimeEnvironment/8.0.271.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5175 Oracle VM VirtualBox Test version 6.1.17-141652
  manifests/Oracle/VirtualBoxTest/6.1.17-141652.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4929 Add Mirantis.Lens 3.6.9
  manifests/Mirantis/Lens/3.6.9.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#4912 VLC media player nightly version 4.0.0-20201120
  manifests/VideoLAN/VLCNightly/4.0.0-20201120.yaml
Labels: Azure-Pipeline-Passed, Needs SmartScreen Investigation, Validation-Completed, Validation-SmartScreen

#5178 Added manifest for Joplin 1.4.19
  manifests/Joplin/Joplin/1.4.19.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5183 TencentMeeting 2.4.0.445
  manifests/Tencent/TencentMeeting/2.4.0.445.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5185 Added Microsoft Edge version 87.0.664.55.
  manifests/Microsoft/Edge/87.0.664.55.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5195 Added MKVToolNix 51.0.0
  manifests/MKVToolNix/MKVToolNix/51.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5186 Updated Google Chrome Beta to version 88.0.4324.27.
  manifests/Google/ChromeBeta/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5194 Added Dropbox version 111.4.472.
  manifests/Dropbox/Dropbox/111.4.472.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5184 Add manifest for Elaborate Bytes' Virtual CloneDrive
  manifests/ElaborateBytes/VirtualCloneDrive/5.5.2.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5187 Updated Google Drive File Stream to version 44.0.12.0.
  manifests/Google/DriveFileStream/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5188 Added AWS CLI version 2.1.7.
  manifests/Amazon/AWSCLI/2.1.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5189 Updated Amazon Workspaces Client to version 3.1.0.
  manifests/Amazon/WorkspacesClient/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5190 Added Anaconda3 version 2020.11.
  manifests/Anaconda/Anaconda3/2020.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5191 Added Plex Media Server version 1.21.0.3711
  manifests/Plex/PlexMediaServer/1.21.0.3711.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5192 Updated Quicken to version 27.1.30.14.
  manifests/Quicken/Quicken/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5196 Adding qmmp
  manifests/QmmpDevelopmentTeam/qmmp/1.4.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5207 Update latest.yaml
  manifests/Quicken/Quicken/latest.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5206 Update 12.0.40664.yaml
  manifests/Microsoft/VC++2013Redist-x86/12.0.40664.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5205 Update 12.0.40664.yaml
  manifests/Microsoft/VC++2013Redist-x64/12.0.40664.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5204 Update 11.0.61030.yaml
  manifests/Microsoft/VC++2012Redist-x86/11.0.61030.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5201 Update 10.0.40219.325.yaml
  manifests/Microsoft/VC++2010Redist-x64/10.0.40219.325.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5200 Update 9.0.30729.6161.yaml
  manifests/Microsoft/VC++2008Redist-x86/9.0.30729.6161.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5203 Update 11.0.61030.yaml
  manifests/Microsoft/VC++2012Redist-x64/11.0.61030.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5198 Update 8.0.61001.yaml
  manifests/Microsoft/VC++2005Redist-x86/8.0.61001.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5199 Update 9.0.30729.6161.yaml
  manifests/Microsoft/VC++2008Redist-x64/9.0.30729.6161.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5197 Update 8.0.61000.yaml
  manifests/Microsoft/VC++2005Redist-x64/8.0.61000.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5212 Added IntelliJ IDEA Community Edition
  manifests/JetBrains/IntelliJIDEA/Community/2020.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5214 Added IntelliJ IDEA Community Edition ProductCode
  manifests/JetBrains/IntelliJIDEA/Community/2020.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5215 Add BOINC 7.16.11
  manifests/UCBerkeley/BOINC/7.16.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5213 Added PyCharm Community Edition
  manifests/JetBrains/PyCharm/Community/2020.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5217 Added PyCharm Community Edition ProductCode
  manifests/JetBrains/PyCharm/Community/2020.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#5216 Fixed switches for Visual Studio Build Tools.
  manifests/Microsoft/VisualStudio/BuildTools/16.6.30128.74.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5218 Fix hash/version to match VoiceMeeter Banana download URL
  manifests/VB-Audio/VoiceMeeterBanana/2.0.5.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5219 matlabdrive 1.6.1.2
  manifests/mathworks/matlabdrive/1.6.1.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5220 Update MP3Tag 3.04a
  manifests/Mp3tag/Mp3tag/3.04a.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5227 GitHub Desktop Beta version 2.6.1-beta2
  manifests/GitHub/GitHubDesktopBeta/2.6.1-beta2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5226 Microsoft OneDrive Internal Fast version 20.244.1203.0001
  manifests/Microsoft/OneDriveInternalFast/20.244.1203.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#5225 Node.js Nightly version 16.0.0-20201207
  manifests/OpenJS/NodeJSNightly/16.0.0-20201207.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
