Repository microsoft/winget-pkgs, pull requests merged in 2021-11, with the labels that each got.

#33472 New version: xgi.houdoku version 2.6.0
  manifests/x/xgi/houdoku/2.6.0/xgi.houdoku.installer.yaml
  manifests/x/xgi/houdoku/2.6.0/xgi.houdoku.locale.en-US.yaml
  manifests/x/xgi/houdoku/2.6.0/xgi.houdoku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33470 New version: nvisionative.nvQuickSite version 2.1.2
  manifests/n/nvisionative/nvQuickSite/2.1.2/nvisionative.nvQuickSite.installer.yaml
  manifests/n/nvisionative/nvQuickSite/2.1.2/nvisionative.nvQuickSite.locale.en-US.yaml
  manifests/n/nvisionative/nvQuickSite/2.1.2/nvisionative.nvQuickSite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33488 Remove: ClashDotNet.ClashDotNet version 1.2.8
  manifests/c/ClashDotNet/ClashDotNet/1.2.8/ClashDotNet.ClashDotNet.installer.yaml
  manifests/c/ClashDotNet/ClashDotNet/1.2.8/ClashDotNet.ClashDotNet.locale.en-US.yaml
  manifests/c/ClashDotNet/ClashDotNet/1.2.8/ClashDotNet.ClashDotNet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33493 Change moniker to unofficial #33489
  manifests/g/GeekCorner/threema/2.2.0/GeekCorner.threema.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33492 Change moniker to unofficial #33489
  manifests/g/GeekCorner/threema/2.1.0/GeekCorner.threema.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33501 New version: Tencent.TencentDocs version 2.2.22
  manifests/t/Tencent/TencentDocs/2.2.22/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.2.22/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.2.22/Tencent.TencentDocs.locale.zh-CN.yaml
  manifests/t/Tencent/TencentDocs/2.2.22/Tencent.TencentDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33489 New package: Threema.Threema version 1.0.3
  manifests/t/Threema/Threema/1.0.3/Threema.Threema.installer.yaml
  manifests/t/Threema/Threema/1.0.3/Threema.Threema.locale.en-US.yaml
  manifests/t/Threema/Threema/1.0.3/Threema.Threema.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33477 New version: vim.vim version 8.2.3568
  manifests/v/vim/vim/8.2.3568/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3568/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3568/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33486 Modify: Tencent.COSBrowser version 2.8.2
  manifests/t/Tencent/COSBrowser/2.8.2/Tencent.COSBrowser.installer.yaml
  manifests/t/Tencent/COSBrowser/2.8.2/Tencent.COSBrowser.locale.en-US.yaml
  manifests/t/Tencent/COSBrowser/2.8.2/Tencent.COSBrowser.locale.zh-CN.yaml
  manifests/t/Tencent/COSBrowser/2.8.2/Tencent.COSBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33487 New version: Microsoft.PowerAutomateDesktop version 2.14.173.21294
  manifests/m/Microsoft/PowerAutomateDesktop/2.14.173.21294/Microsoft.PowerAutomateDesktop.installer.yaml
  manifests/m/Microsoft/PowerAutomateDesktop/2.14.173.21294/Microsoft.PowerAutomateDesktop.locale.en-US.yaml
  manifests/m/Microsoft/PowerAutomateDesktop/2.14.173.21294/Microsoft.PowerAutomateDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33478 ChemAxon.Marvin version 21.17.0
  manifests/c/ChemAxon/Marvin/21.17.0/ChemAxon.Marvin.installer.yaml
  manifests/c/ChemAxon/Marvin/21.17.0/ChemAxon.Marvin.locale.en-US.yaml
  manifests/c/ChemAxon/Marvin/21.17.0/ChemAxon.Marvin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33500 New version: RandomEngy.VidCoder version 6.42
  manifests/r/RandomEngy/VidCoder/6.42/RandomEngy.VidCoder.installer.yaml
  manifests/r/RandomEngy/VidCoder/6.42/RandomEngy.VidCoder.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/6.42/RandomEngy.VidCoder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33491 Change moniker to unofficial #33489
  manifests/g/GeekCorner/threema/2.0.0/GeekCorner.threema.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33499 New version: Jackett.Jackett version 0.19.116.0
  manifests/j/Jackett/Jackett/0.19.116.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.19.116.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.19.116.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33490 Metadata: GeekCorner.threema v1.6.0
  manifests/g/GeekCorner/threema/1.6.0/GeekCorner.threema.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33479 SpongeNobody.Clashy version 0.2.0
  manifests/s/SpongeNobody/Clashy/0.2.0/SpongeNobody.Clashy.installer.yaml
  manifests/s/SpongeNobody/Clashy/0.2.0/SpongeNobody.Clashy.locale.en-US.yaml
  manifests/s/SpongeNobody/Clashy/0.2.0/SpongeNobody.Clashy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33484 New version: quick123.quickredis version 2.4.1
  manifests/q/quick123/quickredis/2.4.1/quick123.quickredis.installer.yaml
  manifests/q/quick123/quickredis/2.4.1/quick123.quickredis.locale.en-US.yaml
  manifests/q/quick123/quickredis/2.4.1/quick123.quickredis.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33507 Remove: BraveSoftware.BraveBrowser-Nightly version 94.1.31.41
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.41/BraveSoftware.BraveBrowser-Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.41/BraveSoftware.BraveBrowser-Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.41/BraveSoftware.BraveBrowser-Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33508 Remove: BraveSoftware.BraveBrowser-Nightly version 94.1.31.44
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.44/BraveSoftware.BraveBrowser-Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.44/BraveSoftware.BraveBrowser-Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/94.1.31.44/BraveSoftware.BraveBrowser-Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33510 Add version: Joplin.Joplin version 2.5.10
  manifests/j/Joplin/Joplin/2.5.10/Joplin.Joplin.installer.yaml
  manifests/j/Joplin/Joplin/2.5.10/Joplin.Joplin.locale.en-US.yaml
  manifests/j/Joplin/Joplin/2.5.10/Joplin.Joplin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33511 SpongeNobody.Clashy version 0.2.1
  manifests/s/SpongeNobody/Clashy/0.2.1/SpongeNobody.Clashy.installer.yaml
  manifests/s/SpongeNobody/Clashy/0.2.1/SpongeNobody.Clashy.locale.en-US.yaml
  manifests/s/SpongeNobody/Clashy/0.2.1/SpongeNobody.Clashy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33506 Remove: BraveSoftware.BraveBrowser-Nightly version 93.1.31.8
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.8/BraveSoftware.BraveBrowser-Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.8/BraveSoftware.BraveBrowser-Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.8/BraveSoftware.BraveBrowser-Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33476 New version: dnGrep.dnGrep version 2.9.428.0
  manifests/d/dnGrep/dnGrep/2.9.428.0/dnGrep.dnGrep.installer.yaml
  manifests/d/dnGrep/dnGrep/2.9.428.0/dnGrep.dnGrep.locale.en-US.yaml
  manifests/d/dnGrep/dnGrep/2.9.428.0/dnGrep.dnGrep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33514 Discord.Discord.Development version 1.0.617
  manifests/d/Discord/Discord/Development/1.0.617/Discord.Discord.Development.installer.yaml
  manifests/d/Discord/Discord/Development/1.0.617/Discord.Discord.Development.locale.en-US.yaml
  manifests/d/Discord/Discord/Development/1.0.617/Discord.Discord.Development.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33509 New version: BraveSoftware.BraveBrowser.Beta version 95.1.32.87
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.87/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.87/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.87/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33519 Remove "New version: Dodgecoin.DodgecoinCore version 1.14.4"
  manifests/d/Dodgecoin/DodgecoinCore/1.14.4/Dodgecoin.DodgecoinCore.installer.yaml
  manifests/d/Dodgecoin/DodgecoinCore/1.14.4/Dodgecoin.DodgecoinCore.locale.en-US.yaml
  manifests/d/Dodgecoin/DodgecoinCore/1.14.4/Dodgecoin.DodgecoinCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33515 Microsoft.VisualStudioCode.Insiders_v1.62.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.62.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33520 DogecoinCoreproject.DogecoinCore version 1.14.3
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.3/DogecoinCoreproject.DogecoinCore.installer.yaml
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.3/DogecoinCoreproject.DogecoinCore.locale.en-US.yaml
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.3/DogecoinCoreproject.DogecoinCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#32168 Move BraveSoftware.BraveBrowser-Dev 94.1.31.56 to BraveSoftware.BraveBrowser.Dev 94.1.31.56
  manifests/b/BraveSoftware/BraveBrowser/Dev/94.1.31.56/BraveSoftware.BraveBrowser.Dev.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/94.1.31.56/BraveSoftware.BraveBrowser.Dev.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/94.1.31.56/BraveSoftware.BraveBrowser.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33521 Remove"Move: Dodgecoin.DodgecoinCore 1.14.3"
  manifests/d/Dodgecoin/DodgecoinCore/1.14.3/Dodgecoin.DodgecoinCore.installer.yaml
  manifests/d/Dodgecoin/DodgecoinCore/1.14.3/Dodgecoin.DodgecoinCore.locale.en-US.yaml
  manifests/d/Dodgecoin/DodgecoinCore/1.14.3/Dodgecoin.DodgecoinCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33516 New version: JetBrains.PHPStorm.EarlyAccess version 213.5449.28
  manifests/j/JetBrains/PHPStorm/EarlyAccess/213.5449.28/JetBrains.PHPStorm.EarlyAccess.installer.yaml
  manifests/j/JetBrains/PHPStorm/EarlyAccess/213.5449.28/JetBrains.PHPStorm.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/PHPStorm/EarlyAccess/213.5449.28/JetBrains.PHPStorm.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33469 New version: JohnMacFarlane.Pandoc version 2.16
  manifests/j/JohnMacFarlane/Pandoc/2.16/JohnMacFarlane.Pandoc.installer.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.16/JohnMacFarlane.Pandoc.locale.en-US.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.16/JohnMacFarlane.Pandoc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33527 Fixed license for Elasticsearch 7.13.2.
  manifests/e/Elastic/Elasticsearch/7.13.2/Elastic.Elasticsearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33526 Fixed license for Elasticsearch 7.13.1.
  manifests/e/Elastic/Elasticsearch/7.13.1/Elastic.Elasticsearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33537 New version: JetBrains.WebStorm.EAP version 213.5449.31
  manifests/j/JetBrains/WebStorm/EAP/213.5449.31/JetBrains.WebStorm.EAP.installer.yaml
  manifests/j/JetBrains/WebStorm/EAP/213.5449.31/JetBrains.WebStorm.EAP.locale.en-US.yaml
  manifests/j/JetBrains/WebStorm/EAP/213.5449.31/JetBrains.WebStorm.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33536 New version: dbeaver.dbeaver version 21.2.4
  manifests/d/dbeaver/dbeaver/21.2.4/dbeaver.dbeaver.installer.yaml
  manifests/d/dbeaver/dbeaver/21.2.4/dbeaver.dbeaver.locale.en-US.yaml
  manifests/d/dbeaver/dbeaver/21.2.4/dbeaver.dbeaver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33560 Remove Adobe.AdobeAcrobatReaderDC 20.013.20074 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.013.20074/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33556 Remove Adobe.AdobeAcrobatReaderDC 21.005.20058 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20058/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20058/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20058/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33555 Remove Adobe.AdobeAcrobatReaderDC 21.005.20060 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20060/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20060/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20060/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33552 Remove Adobe.AdobeAcrobatReaderDC 20.009.20063 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.009.20063/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33523 Added Elasticsearch version 7.15.1.
  manifests/e/Elastic/Elasticsearch/7.15.1/Elastic.Elasticsearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33534 Added Remote Desktop version 1.2.2600.0.
  manifests/m/Microsoft/RemoteDesktopClient/1.2.2600.0/Microsoft.RemoteDesktopClient.installer.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.2600.0/Microsoft.RemoteDesktopClient.locale.en-US.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.2600.0/Microsoft.RemoteDesktopClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33535 New version: BraveSoftware.BraveBrowser.Nightly version 95.1.33.50
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.50/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.50/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.50/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33538 DoltHub.Dolt version 0.32.2
  manifests/d/DoltHub/Dolt/0.32.2/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.32.2/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.32.2/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33475 New version: dorssel.usbipd-win version 1.1.1
  manifests/d/dorssel/usbipd-win/1.1.1/dorssel.usbipd-win.installer.yaml
  manifests/d/dorssel/usbipd-win/1.1.1/dorssel.usbipd-win.locale.en-US.yaml
  manifests/d/dorssel/usbipd-win/1.1.1/dorssel.usbipd-win.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33533 SpongeNobody.Clashy version 0.2.2
  manifests/s/SpongeNobody/Clashy/0.2.2/SpongeNobody.Clashy.installer.yaml
  manifests/s/SpongeNobody/Clashy/0.2.2/SpongeNobody.Clashy.locale.en-US.yaml
  manifests/s/SpongeNobody/Clashy/0.2.2/SpongeNobody.Clashy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33524 Added Beats winlogbeat version 7.15.1.
  manifests/e/Elastic/Winlogbeat/7.15.1/Elastic.Winlogbeat.installer.yaml
  manifests/e/Elastic/Winlogbeat/7.15.1/Elastic.Winlogbeat.locale.en-US.yaml
  manifests/e/Elastic/Winlogbeat/7.15.1/Elastic.Winlogbeat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33559 Remove Adobe.AdobeAcrobatReaderDC 21.001.20140 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.001.20140/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33562 Remove Adobe.AdobeAcrobatReaderDC 20.012.20048 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.012.20048/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33554 Remove Adobe.AdobeAcrobatReaderDC 21.007.20091 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20091/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20091/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20091/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33558 Remove Adobe.AdobeAcrobatReaderDC 21.001.20155 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.001.20155/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.001.20155/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.001.20155/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33561 Remove Adobe.AdobeAcrobatReaderDC 20.013.20064 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.013.20064/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33553 Remove Adobe.AdobeAcrobatReaderDC 20.012.20041 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.012.20041/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.012.20041/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/20.012.20041/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33531 New version: BinanceTech.Binance version 1.26.0
  manifests/b/BinanceTech/Binance/1.26.0/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.26.0/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.26.0/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33548 Move Adobe.AdobeAcrobatReaderDC 20.013.20064 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.013.20064/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33546 Move Adobe.AdobeAcrobatReaderDC 21.001.20140 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.001.20140/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33539 Add Adobe.Acrobat.Reader.64-Bit v21.007.20099
  manifests/a/Adobe/Acrobat/Reader/64-bit/21.007.20099/Adobe.Acrobat.Reader.64-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/64-bit/21.007.20099/Adobe.Acrobat.Reader.64-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/64-bit/21.007.20099/Adobe.Acrobat.Reader.64-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Attention

#33542 Move Adobe.AdobeAcrobatReaderDC 21.005.20060 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20060/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20060/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20060/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33551 Move Adobe.AdobeAcrobatReaderDC 20.009.20063 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.009.20063/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33540 Move Adobe.AdobeAcrobatReaderDC 21.007.20099 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20099/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20099/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20099/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33545 Move Adobe.AdobeAcrobatReaderDC 21.001.20155 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.001.20155/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.001.20155/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.001.20155/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33549 Move Adobe.AdobeAcrobatReaderDC 20.012.20048 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.012.20048/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33547 Move Adobe.AdobeAcrobatReaderDC 20.013.20074 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.013.20074/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33550 Move Adobe.AdobeAcrobatReaderDC 20.012.20041 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.012.20041/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.012.20041/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/20.012.20041/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33543 Move Adobe.AdobeAcrobatReaderDC 21.005.20058 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20058/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20058/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.005.20058/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#33557 Remove Adobe.AdobeAcrobatReaderDC 21.005.20048 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20048/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20048/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.005.20048/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33473 Microsoft.dotnet version 5.4.221.47606
  manifests/m/Microsoft/dotnet/5.4.221.47606/Microsoft.dotnet.installer.yaml
  manifests/m/Microsoft/dotnet/5.4.221.47606/Microsoft.dotnet.locale.en-US.yaml
  manifests/m/Microsoft/dotnet/5.4.221.47606/Microsoft.dotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33565 Remove Adobe.AdobeAcrobatReaderDC 21.007.20099 to Adobe.Acrobat.Reade…
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20099/Adobe.AdobeAcrobatReaderDC.installer.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20099/Adobe.AdobeAcrobatReaderDC.locale.en-US.yaml
  manifests/a/Adobe/AdobeAcrobatReaderDC/21.007.20099/Adobe.AdobeAcrobatReaderDC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33517 New version: JetBrains.RubyMine.EarlyAccess version 213.5449.19
  manifests/j/JetBrains/RubyMine/EarlyAccess/213.5449.19/JetBrains.RubyMine.EarlyAccess.installer.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/213.5449.19/JetBrains.RubyMine.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/213.5449.19/JetBrains.RubyMine.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#33541 Move Adobe.AdobeAcrobatReaderDC 21.007.20091 to Adobe.Acrobat.Reader.…
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20091/Adobe.Acrobat.Reader.32-bit.installer.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20091/Adobe.Acrobat.Reader.32-bit.locale.en-US.yaml
  manifests/a/Adobe/Acrobat/Reader/32-bit/21.007.20091/Adobe.Acrobat.Reader.32-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33567 New version: foxglove.studio version 0.21.0
  manifests/f/foxglove/studio/0.21.0/foxglove.studio.installer.yaml
  manifests/f/foxglove/studio/0.21.0/foxglove.studio.locale.en-US.yaml
  manifests/f/foxglove/studio/0.21.0/foxglove.studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33569 Emurasoft.EmEditor version 21.2.1
  manifests/e/Emurasoft/EmEditor/21.2.1/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/21.2.1/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/21.2.1/Emurasoft.EmEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33573 Revert "Automatic deletion of calibre.calibre 5.12.0"
  manifests/c/calibre/calibre/5.12.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/5.12.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/5.12.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33575 Add Geekbench 5.4.2
  manifests/p/PrimateLabs/Geekbench/5/5.4.2/PrimateLabs.Geekbench.5.installer.yaml
  manifests/p/PrimateLabs/Geekbench/5/5.4.2/PrimateLabs.Geekbench.5.locale.en-US.yaml
  manifests/p/PrimateLabs/Geekbench/5/5.4.2/PrimateLabs.Geekbench.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33576 Added Microsoft Edge Beta version 96.0.1054.8.
  manifests/m/Microsoft/Edge/Beta/96.0.1054.8/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/96.0.1054.8/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/96.0.1054.8/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33532 New version: ByteDance.JianyingPro version 2.3.0.5110
  manifests/b/ByteDance/JianyingPro/2.3.0.5110/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/2.3.0.5110/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/2.3.0.5110/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/2.3.0.5110/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33577 JanDeDobbeleer.OhMyPosh version 5.16.5
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33581 New version: Microsoft.azure-iot-explorer version 0.14.7
  manifests/m/Microsoft/azure-iot-explorer/0.14.7/Microsoft.azure-iot-explorer.installer.yaml
  manifests/m/Microsoft/azure-iot-explorer/0.14.7/Microsoft.azure-iot-explorer.locale.en-US.yaml
  manifests/m/Microsoft/azure-iot-explorer/0.14.7/Microsoft.azure-iot-explorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33580 New version: DebaucheeOpenSourceGroup.Barrier version 2.4.0
  manifests/d/DebaucheeOpenSourceGroup/Barrier/2.4.0/DebaucheeOpenSourceGroup.Barrier.installer.yaml
  manifests/d/DebaucheeOpenSourceGroup/Barrier/2.4.0/DebaucheeOpenSourceGroup.Barrier.locale.en-US.yaml
  manifests/d/DebaucheeOpenSourceGroup/Barrier/2.4.0/DebaucheeOpenSourceGroup.Barrier.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33578 Cockos.REAPER version 6.40
  manifests/c/Cockos/REAPER/6.40/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.40/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.40/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33591 New version: SandboxiePlus.SandboxieClassic version 5.53.3
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33592 New version: SandboxiePlus.SandboxiePlus version 0.9.8d
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#28466 cuiliang.quicker version 1.26.17.0
  manifests/c/cuiliang/quicker/1.26.17.0/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.26.17.0/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.26.17.0/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33589 New version: joncampbell123.DOSBox-X version 0.83.19
  manifests/j/joncampbell123/DOSBox-X/0.83.19/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.19/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.19/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33614 New version: Tetrate.func-e version 1.1.0
  manifests/t/Tetrate/func-e/1.1.0/Tetrate.func-e.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33594 Added Vim version 8.2.3570.
  manifests/v/vim/vim/8.2.3570/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3570/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3570/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33612 Add SteelSeries GG 11.1.0
  manifests/s/SteelSeries/GG/11.1.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/11.1.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/11.1.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33588 Added Skype version 8.78.
  manifests/m/Microsoft/Skype/8.78/Microsoft.Skype.installer.yaml
  manifests/m/Microsoft/Skype/8.78/Microsoft.Skype.locale.en-US.yaml
  manifests/m/Microsoft/Skype/8.78/Microsoft.Skype.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33587 New version: bornova.numara version 3.6.6
  manifests/b/bornova/numara/3.6.6/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.6.6/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.6.6/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33608 JanDeDobbeleer.OhMyPosh version 5.16.6
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33618 New version: LedgerHQ.LedgerLive version 2.34.4
  manifests/l/LedgerHQ/LedgerLive/2.34.4/LedgerHQ.LedgerLive.installer.yaml
  manifests/l/LedgerHQ/LedgerLive/2.34.4/LedgerHQ.LedgerLive.locale.en-US.yaml
  manifests/l/LedgerHQ/LedgerLive/2.34.4/LedgerHQ.LedgerLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33620 New version: stacks.stacks version 1.5.5
  manifests/s/stacks/stacks/1.5.5/stacks.stacks.installer.yaml
  manifests/s/stacks/stacks/1.5.5/stacks.stacks.locale.en-US.yaml
  manifests/s/stacks/stacks/1.5.5/stacks.stacks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33518 DogecoinCoreproject.DogecoinCore version 1.14.4
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.4/DogecoinCoreproject.DogecoinCore.installer.yaml
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.4/DogecoinCoreproject.DogecoinCore.locale.en-US.yaml
  manifests/d/DogecoinCoreproject/DogecoinCore/1.14.4/DogecoinCoreproject.DogecoinCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33617 New version: JetBrains.Hub version 21.1.13841
  manifests/j/JetBrains/Hub/21.1.13841/JetBrains.Hub.installer.yaml
  manifests/j/JetBrains/Hub/21.1.13841/JetBrains.Hub.locale.en-US.yaml
  manifests/j/JetBrains/Hub/21.1.13841/JetBrains.Hub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33621 Duplicate: Kakao.KakaoTalk version 3.3.3.2924
  manifests/k/Kakao/KakaoTalk/3.3.3.2924/Kakao.KakaoTalk.installer.yaml
  manifests/k/Kakao/KakaoTalk/3.3.3.2924/Kakao.KakaoTalk.locale.en-US.yaml
  manifests/k/Kakao/KakaoTalk/3.3.3.2924/Kakao.KakaoTalk.locale.ko-KR.yaml
  manifests/k/Kakao/KakaoTalk/3.3.3.2924/Kakao.KakaoTalk.yaml
Labels: Moderator-Approved

#33596 Tencent.qq-devtool version 0.3.4
  manifests/t/Tencent/qq-devtool/0.3.4/Tencent.qq-devtool.installer.yaml
  manifests/t/Tencent/qq-devtool/0.3.4/Tencent.qq-devtool.locale.en-US.yaml
  manifests/t/Tencent/qq-devtool/0.3.4/Tencent.qq-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33611 Kiwix.KiwixJS.Electron version 1.7.7-E
  manifests/k/Kiwix/KiwixJS/Electron/1.7.7-E/Kiwix.KiwixJS.Electron.installer.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.7-E/Kiwix.KiwixJS.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.7-E/Kiwix.KiwixJS.Electron.locale.en-US.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.7-E/Kiwix.KiwixJS.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33613 New version: BraveSoftware.BraveBrowser.Beta version 95.1.32.88
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.88/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.88/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.88/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33198 Microsoft.WindowsPCHealthCheck version 3.1.210929003
  manifests/m/Microsoft/WindowsPCHealthCheck/3.1.2109.29003/Microsoft.WindowsPCHealthCheck.installer.yaml
  manifests/m/Microsoft/WindowsPCHealthCheck/3.1.2109.29003/Microsoft.WindowsPCHealthCheck.locale.en-US.yaml
  manifests/m/Microsoft/WindowsPCHealthCheck/3.1.2109.29003/Microsoft.WindowsPCHealthCheck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33590 New version: RProject.R version 4.1.2
  manifests/r/RProject/R/4.1.2/RProject.R.installer.yaml
  manifests/r/RProject/R/4.1.2/RProject.R.locale.en-US.yaml
  manifests/r/RProject/R/4.1.2/RProject.R.locale.fr-FR.yaml
  manifests/r/RProject/R/4.1.2/RProject.R.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33582 Update: VMware.WorkstationPlayer version 16.2.0
  manifests/v/VMware/WorkstationPlayer/16.2.0/VMware.WorkstationPlayer.installer.yaml
  manifests/v/VMware/WorkstationPlayer/16.2.0/VMware.WorkstationPlayer.locale.en-US.yaml
  manifests/v/VMware/WorkstationPlayer/16.2.0/VMware.WorkstationPlayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33616 Submitting HttpMaster Professional 5.2.0
  manifests/b/Borvid/HttpMasterProfessional/5.2.0/Borvid.HttpMasterProfessional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33615 Submitting HttpMaster Express 5.2.0
  manifests/b/Borvid/HttpMasterExpress/5.2.0/Borvid.HttpMasterExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33609 New version: Jackett.Jackett version 0.19.124.0
  manifests/j/Jackett/Jackett/0.19.124.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.19.124.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.19.124.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33623 New version: AmanHarwara.Altus version 4.5.0
  manifests/a/AmanHarwara/Altus/4.5.0/AmanHarwara.Altus.installer.yaml
  manifests/a/AmanHarwara/Altus/4.5.0/AmanHarwara.Altus.locale.en-US.yaml
  manifests/a/AmanHarwara/Altus/4.5.0/AmanHarwara.Altus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33624 Updated Google Chrome Canary to version 97.0.4689.0.
  manifests/g/Google/Chrome/Canary/97.0.4689.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/97.0.4689.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/97.0.4689.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/97.0.4689.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#32996 New version: Surfshark.SurfsharkVPN version 3.1.0999
  manifests/s/Surfshark/SurfsharkVPN/3.0.2999/Surfshark.SurfsharkVPN.installer.yaml
  manifests/s/Surfshark/SurfsharkVPN/3.1.0999/Surfshark.SurfsharkVPN.installer.yaml
  manifests/s/Surfshark/SurfsharkVPN/3.1.0999/Surfshark.SurfsharkVPN.locale.en-US.yaml
  manifests/s/Surfshark/SurfsharkVPN/3.1.0999/Surfshark.SurfsharkVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29806 New: Thunder.Xmp version 6.1.7.810
  manifests/t/Thunder/Xmp/6.1.7.810/Thunder.Xmp.installer.yaml
  manifests/t/Thunder/Xmp/6.1.7.810/Thunder.Xmp.locale.en-US.yaml
  manifests/t/Thunder/Xmp/6.1.7.810/Thunder.Xmp.locale.zh-CN.yaml
  manifests/t/Thunder/Xmp/6.1.7.810/Thunder.Xmp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#29808 New: Glodon.CADReader version 5.14.3.77
  manifests/g/Glodon/CADReader/5.14.3.77/Glodon.CADReader.installer.yaml
  manifests/g/Glodon/CADReader/5.14.3.77/Glodon.CADReader.locale.en-US.yaml
  manifests/g/Glodon/CADReader/5.14.3.77/Glodon.CADReader.locale.zh-CN.yaml
  manifests/g/Glodon/CADReader/5.14.3.77/Glodon.CADReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#32308 Added BellSoft LibericaJDK Full 11.0.13.8
  manifests/b/BellSoft/LibericaJDK/11/Full/11.0.13.8/BellSoft.LibericaJDK.11.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33097 Waiver for BellSoft.LibericaJDK.11.Full
  manifests/b/BellSoft/LibericaJDK/11/Full/.validation
Labels: Moderator-Approved, Validation-Metadata

#32311 Added BellSoft LibericaJDK Full 17.0.1.12
  manifests/b/BellSoft/LibericaJDK/17/Full/17.0.1.12/BellSoft.LibericaJDK.17.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#32312 Added BellSoft LibericaJDK 17.0.1.12 17.0.1.12
  manifests/b/BellSoft/LibericaJDK/17/17.0.1.12/BellSoft.LibericaJDK.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#32309 Added BellSoft LibericaJDK 11.0.13.8 11.0.13.8
  manifests/b/BellSoft/LibericaJDK/11/11.0.13.8/BellSoft.LibericaJDK.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33096 Waiver for BellSoft.LibericaJDK.11
  manifests/b/BellSoft/LibericaJDK/11/.validation
Labels: Validation-Metadata

#33095 Waiver for BellSoft.LibericaJDK.17.Full
  manifests/b/BellSoft/LibericaJDK/17/Full/.validation
Labels: Validation-Metadata

#33485 Modify: LAIPIC.Perfoo version 1.0.0
  manifests/l/LAIPIC/Perfoo/1.0.0/LAIPIC.Perfoo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33482 Modify: 115.115 version 1.0.0.45
  manifests/1/115/115/1.0.0.45/115.115.installer.yaml
  manifests/1/115/115/1.0.0.45/115.115.locale.en-US.yaml
  manifests/1/115/115/1.0.0.45/115.115.locale.zh-CN.yaml
  manifests/1/115/115/1.0.0.45/115.115.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33094 Waiver for BellSoft.LibericaJDK.17
  manifests/b/BellSoft/LibericaJDK/17/.validation
Labels: Validation-Metadata

#33441 EddieWang.Sia-UI version 1.5.7
  manifests/e/EddieWang/Sia-UI/1.5.7/EddieWang.Sia-UI.installer.yaml
  manifests/e/EddieWang/Sia-UI/1.5.7/EddieWang.Sia-UI.locale.en-US.yaml
  manifests/e/EddieWang/Sia-UI/1.5.7/EddieWang.Sia-UI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33503 Add user scope for NetworkAdapterSummary v1.4.56.0
  manifests/r/RoyLFine/NetworkAdapterSummary/1.4.56.0/RoyLFine.NetworkAdapterSummary.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Policy-Test-1.2, Moderator-Approved, Needs-Attention

#33445 Updated Spotify to version 1.1.71.560.gc21c3367.
  manifests/s/Spotify/Spotify/1.1.71.560.gc21c3367/Spotify.Spotify.installer.yaml
  manifests/s/Spotify/Spotify/1.1.71.560.gc21c3367/Spotify.Spotify.locale.en-US.yaml
  manifests/s/Spotify/Spotify/1.1.71.560.gc21c3367/Spotify.Spotify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#33633 Modify: 115.115Chrome version 24.5.0.1
  manifests/1/115/115Chrome/24.5.0.1/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/24.5.0.1/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/24.5.0.1/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/24.5.0.1/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33634 Modify: 115.115Chrome version 24.4.0.2
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33628 Levitsky.FontBase version 2.16.9
  manifests/l/Levitsky/FontBase/2.16.9/Levitsky.FontBase.installer.yaml
  manifests/l/Levitsky/FontBase/2.16.9/Levitsky.FontBase.locale.en-US.yaml
  manifests/l/Levitsky/FontBase/2.16.9/Levitsky.FontBase.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33635 Modify: 115.115Chrome version 24.3.0.3
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33654 Change Version Number KDE.KDEConnect v21.08.2.760 -> v21.08.2
  manifests/k/KDE/KDEConnect/21.08.2/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.08.2/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.08.2/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33627 Added Mercurial version 5.9.3.
  manifests/m/Mercurial/Mercurial/5.9.3/Mercurial.Mercurial.installer.yaml
  manifests/m/Mercurial/Mercurial/5.9.3/Mercurial.Mercurial.locale.en-US.yaml
  manifests/m/Mercurial/Mercurial/5.9.3/Mercurial.Mercurial.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33632 Added Mozilla Firefox version 94.0.
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/94.0/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33658 Added Microsoft Edge Dev version 97.0.1060.2.
  manifests/m/Microsoft/Edge/Dev/97.0.1060.2/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/97.0.1060.2/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/97.0.1060.2/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33625 OpenMedia.4KVideoDownloader version 4.18.3.4530
  manifests/o/OpenMedia/4KVideoDownloader/4.18.3.4530/OpenMedia.4KVideoDownloader.installer.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.18.3.4530/OpenMedia.4KVideoDownloader.locale.en-US.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.18.3.4530/OpenMedia.4KVideoDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#21204 Improve YAML Parsing
  AUTHORING_MANIFESTS.md
  README.md
  Tools/YamlCreate.ps1
  doc/tools/YamlCreate.md
Labels: Validation-Merge-Conflict, Moderator-Approved, Project-File

#33629 PrestonN.FreeTube version 0.15.0
  manifests/p/PrestonN/FreeTube/0.15.0/PrestonN.FreeTube.installer.yaml
  manifests/p/PrestonN/FreeTube/0.15.0/PrestonN.FreeTube.locale.en-US.yaml
  manifests/p/PrestonN/FreeTube/0.15.0/PrestonN.FreeTube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33651 CMake 3.22.0: Add binary directory to PATH on install
  manifests/k/Kitware/CMake/3.22.0/Kitware.CMake.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33660 Updated Google Chrome Dev to version 97.0.4688.2.
  manifests/g/Google/Chrome/Dev/97.0.4688.2/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/97.0.4688.2/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/97.0.4688.2/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/97.0.4688.2/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33630 Added Octopus Deploy Server version 2021.1.7867.
  manifests/o/OctopusDeploy/Server/2021.1.7867/OctopusDeploy.Server.installer.yaml
  manifests/o/OctopusDeploy/Server/2021.1.7867/OctopusDeploy.Server.locale.en-US.yaml
  manifests/o/OctopusDeploy/Server/2021.1.7867/OctopusDeploy.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33659 Peppy.Osu! version 2021.1103.1
  manifests/p/Peppy/Osu!/2021.1103.1/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2021.1103.1/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2021.1103.1/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33631 Mp3tag.Mp3tag version 3.11
  manifests/m/Mp3tag/Mp3tag/3.11/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.11/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.11/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33682 Remove: TrackerSoftware.PDF-Tools version 9.2.357.0
  manifests/t/TrackerSoftware/PDF-Tools/9.2.357.0/TrackerSoftware.PDF-Tools.installer.yaml
  manifests/t/TrackerSoftware/PDF-Tools/9.2.357.0/TrackerSoftware.PDF-Tools.locale.en-US.yaml
  manifests/t/TrackerSoftware/PDF-Tools/9.2.357.0/TrackerSoftware.PDF-Tools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33679 New version: BraveSoftware.BraveBrowser.Nightly version 95.1.33.56
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.56/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.56/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/95.1.33.56/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33683 New version: HearthSim.HearthstoneDeckTracker version 1.16.6
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.6/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.6/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.6/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33684 New version: Jackett.Jackett version 0.19.138.0
  manifests/j/Jackett/Jackett/0.19.138.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.19.138.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.19.138.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33687 New version: mesonbuild.meson version 0.60.1
  manifests/m/mesonbuild/meson/0.60.1/mesonbuild.meson.installer.yaml
  manifests/m/mesonbuild/meson/0.60.1/mesonbuild.meson.locale.en-US.yaml
  manifests/m/mesonbuild/meson/0.60.1/mesonbuild.meson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33695 New version: JohnMacFarlane.Pandoc version 2.16.1
  manifests/j/JohnMacFarlane/Pandoc/2.16.1/JohnMacFarlane.Pandoc.installer.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.16.1/JohnMacFarlane.Pandoc.locale.en-US.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.16.1/JohnMacFarlane.Pandoc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33698 RyzenControllerTeam.RyzenController version 2.5.4
  manifests/r/RyzenControllerTeam/RyzenController/2.5.4/RyzenControllerTeam.RyzenController.installer.yaml
  manifests/r/RyzenControllerTeam/RyzenController/2.5.4/RyzenControllerTeam.RyzenController.locale.en-US.yaml
  manifests/r/RyzenControllerTeam/RyzenController/2.5.4/RyzenControllerTeam.RyzenController.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33694 New version: BraveSoftware.BraveBrowser.Beta version 95.1.32.90
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.90/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.90/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/95.1.32.90/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33700 JanDeDobbeleer.OhMyPosh version 5.17.0
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33677 New version: SonicVisualiser.SonicVisualiser version 4.4
  manifests/s/SonicVisualiser/SonicVisualiser/4.3/SonicVisualiser.SonicVisualiser.installer.yaml
  manifests/s/SonicVisualiser/SonicVisualiser/4.4/SonicVisualiser.SonicVisualiser.installer.yaml
  manifests/s/SonicVisualiser/SonicVisualiser/4.4/SonicVisualiser.SonicVisualiser.locale.en-US.yaml
  manifests/s/SonicVisualiser/SonicVisualiser/4.4/SonicVisualiser.SonicVisualiser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33680 New version: Cryptomator.Cryptomator version 1.6.2
  manifests/c/Cryptomator/Cryptomator/1.6.2/Cryptomator.Cryptomator.installer.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.2/Cryptomator.Cryptomator.locale.en-US.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.2/Cryptomator.Cryptomator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#33688 New version: Telegram.TelegramDesktop.Beta version 3.1.13
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.13/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.13/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.13/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
