Repository microsoft/winget-pkgs, pull requests merged in 2021-12, with the labels that each got.

#36504 New version: Eraser.Eraser version 6.2.2993
  manifests/e/Eraser/Eraser/6.2.2993/Eraser.Eraser.installer.yaml
  manifests/e/Eraser/Eraser/6.2.2993/Eraser.Eraser.locale.en-US.yaml
  manifests/e/Eraser/Eraser/6.2.2993/Eraser.Eraser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36499 Microsoft.PowerToys version 0.51.0
  manifests/m/Microsoft/PowerToys/0.51.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.51.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.51.0/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36529 New version: WinMerge.WinMerge version 2.16.16.0
  manifests/w/WinMerge/WinMerge/2.16.16.0/WinMerge.WinMerge.installer.yaml
  manifests/w/WinMerge/WinMerge/2.16.16.0/WinMerge.WinMerge.locale.en-US.yaml
  manifests/w/WinMerge/WinMerge/2.16.16.0/WinMerge.WinMerge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36487 New version: CrystalDewWorld.CrystalDiskInfo version 8.13.0
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.13.0/CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.13.0/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.13.0/CrystalDewWorld.CrystalDiskInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36490 New version: LogMeIn.GoToMeeting version 10.18.0.19932
  manifests/l/LogMeIn/GoToMeeting/10.18.0.19932/LogMeIn.GoToMeeting.installer.yaml
  manifests/l/LogMeIn/GoToMeeting/10.18.0.19932/LogMeIn.GoToMeeting.locale.en-US.yaml
  manifests/l/LogMeIn/GoToMeeting/10.18.0.19932/LogMeIn.GoToMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36538 New version: Balena.BalenaCLI version 12.55.1
  manifests/b/Balena/BalenaCLI/12.55.1/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/12.55.1/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/12.55.1/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36533 New version: Vromans.ChordPro version 5.985.0.1
  manifests/v/Vromans/ChordPro/5.985.0.1/Vromans.ChordPro.installer.yaml
  manifests/v/Vromans/ChordPro/5.985.0.1/Vromans.ChordPro.locale.en-US.yaml
  manifests/v/Vromans/ChordPro/5.985.0.1/Vromans.ChordPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36505 New version: bornova.numara version 3.7.2
  manifests/b/bornova/numara/3.7.2/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.7.2/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.7.2/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36550 mpv.net removal
  manifests/s/stax76/mpvdotnet/5.4.9.0/stax76.mpvdotnet.installer.yaml
  manifests/s/stax76/mpvdotnet/5.4.9.0/stax76.mpvdotnet.locale.en-US.yaml
  manifests/s/stax76/mpvdotnet/5.4.9.0/stax76.mpvdotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36540 New version: ElijahLopez.MusicCaster version 4.90.140
  manifests/e/ElijahLopez/MusicCaster/4.90.140/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.140/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.140/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36541 Add version: HearthSim.HearthstoneDeckTracker version 1.16.10
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.10/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.10/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.16.10/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36567 New version: Jackett.Jackett version 0.20.79.0
  manifests/j/Jackett/Jackett/0.20.79.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.79.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.79.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36553 New version: Bilibili.Livehime version 3.48.1.2704
  manifests/b/Bilibili/Livehime/3.48.1.2704/Bilibili.Livehime.installer.yaml
  manifests/b/Bilibili/Livehime/3.48.1.2704/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/3.48.1.2704/Bilibili.Livehime.locale.zh-CN.yaml
  manifests/b/Bilibili/Livehime/3.48.1.2704/Bilibili.Livehime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36281 Cyber.Cat.ADBAppControl version 1.7.1
  manifests/c/CyberCat/ADBAppControl/1.7.1/CyberCat.ADBAppControl.installer.yaml
  manifests/c/CyberCat/ADBAppControl/1.7.1/CyberCat.ADBAppControl.locale.en-US.yaml
  manifests/c/CyberCat/ADBAppControl/1.7.1/CyberCat.ADBAppControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36542 New version: Moonsworth.LunarClient version 2.9.1
  manifests/m/Moonsworth/LunarClient/2.9.1/Moonsworth.LunarClient.installer.yaml
  manifests/m/Moonsworth/LunarClient/2.9.1/Moonsworth.LunarClient.locale.en-US.yaml
  manifests/m/Moonsworth/LunarClient/2.9.1/Moonsworth.LunarClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36539 New version: ElectronCommunity.ElectronFiddle version 0.27.2
  manifests/e/ElectronCommunity/ElectronFiddle/0.27.2/ElectronCommunity.ElectronFiddle.installer.yaml
  manifests/e/ElectronCommunity/ElectronFiddle/0.27.2/ElectronCommunity.ElectronFiddle.locale.en-US.yaml
  manifests/e/ElectronCommunity/ElectronFiddle/0.27.2/ElectronCommunity.ElectronFiddle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36554 New version: BraveSoftware.BraveBrowser.Nightly version 96.1.35.1
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.1/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.1/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.1/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36570 New version: RicoSuter.NSwagStudio version 13.14.8.0
  manifests/r/RicoSuter/NSwagStudio/13.14.8.0/RicoSuter.NSwagStudio.installer.yaml
  manifests/r/RicoSuter/NSwagStudio/13.14.8.0/RicoSuter.NSwagStudio.locale.en-US.yaml
  manifests/r/RicoSuter/NSwagStudio/13.14.8.0/RicoSuter.NSwagStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36501 Lenovo.ThinInstaller version 1.3.0038
  manifests/l/Lenovo/ThinInstaller/1.3.0038/Lenovo.ThinInstaller.installer.yaml
  manifests/l/Lenovo/ThinInstaller/1.3.0038/Lenovo.ThinInstaller.locale.en-US.yaml
  manifests/l/Lenovo/ThinInstaller/1.3.0038/Lenovo.ThinInstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36571 cuiliang.quicker version 1.27.6
  manifests/c/cuiliang/quicker/1.27.6/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.6/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.6/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36556 New version: Plex.PlexMediaServer version 1.25.0.5282
  manifests/p/Plex/PlexMediaServer/1.25.0.5282/Plex.PlexMediaServer.installer.yaml
  manifests/p/Plex/PlexMediaServer/1.25.0.5282/Plex.PlexMediaServer.locale.en-US.yaml
  manifests/p/Plex/PlexMediaServer/1.25.0.5282/Plex.PlexMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36543 New version: vim.vim version 8.2.3709
  manifests/v/vim/vim/8.2.3709/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3709/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3709/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36566 New version: BraveSoftware.BraveBrowser.Beta version 96.1.34.49
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.49/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.49/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.49/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36561 New version: Google.Chrome.Canary version 98.0.4740.0
  manifests/g/Google/Chrome/Canary/98.0.4740.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/98.0.4740.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/98.0.4740.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/98.0.4740.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36575 cuiliang.quicker version 1.27.7
  manifests/c/cuiliang/quicker/1.27.7/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.7/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.7/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36578 New version: Jitsi.Meet version 2021.12.1
  manifests/j/Jitsi/Meet/2021.12.1/Jitsi.Meet.installer.yaml
  manifests/j/Jitsi/Meet/2021.12.1/Jitsi.Meet.locale.en-US.yaml
  manifests/j/Jitsi/Meet/2021.12.1/Jitsi.Meet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36579 New version: Telegram.TelegramDesktop.Beta version 3.2.8
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36580 cuiliang.quicker version 1.27.8
  manifests/c/cuiliang/quicker/1.27.8/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.8/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.8/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36464 New version: Nextcloud.NextcloudDesktop version 3.4.0
  manifests/n/Nextcloud/NextcloudDesktop/3.4.0.20211129/Nextcloud.NextcloudDesktop.installer.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.4.0.20211129/Nextcloud.NextcloudDesktop.locale.en-US.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.4.0.20211129/Nextcloud.NextcloudDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36460 New version: purocean.YankNote version 3.13.1
  manifests/p/purocean/YankNote/3.13.1/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.13.1/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.13.1/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36568 New version: joncampbell123.DOSBox-X version 0.83.20
  manifests/j/joncampbell123/DOSBox-X/0.83.20/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.20/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.20/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36581 New version: Lenovo.SystemUpdate version 5.07.0131
  manifests/l/Lenovo/SystemUpdate/5.07.0131/Lenovo.SystemUpdate.installer.yaml
  manifests/l/Lenovo/SystemUpdate/5.07.0131/Lenovo.SystemUpdate.locale.en-US.yaml
  manifests/l/Lenovo/SystemUpdate/5.07.0131/Lenovo.SystemUpdate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36466 New version: BitComet.BitComet version 1.84
  manifests/b/BitComet/BitComet/1.84/BitComet.BitComet.installer.yaml
  manifests/b/BitComet/BitComet/1.84/BitComet.BitComet.locale.en-US.yaml
  manifests/b/BitComet/BitComet/1.84/BitComet.BitComet.locale.zh-CN.yaml
  manifests/b/BitComet/BitComet/1.84/BitComet.BitComet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36577 New version: JetBrains.YouTrack version 21.4.34389
  manifests/j/JetBrains/YouTrack/21.4.34389/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/21.4.34389/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/21.4.34389/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36411 New version: OpenRPAApS.OpenRPA version 1.3.34.0
  manifests/o/OpenRPAApS/OpenRPA/1.3.34.0/OpenRPAApS.OpenRPA.installer.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.34.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.34.0/OpenRPAApS.OpenRPA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36582 Ruben2776.PicView version 1.6.5
  manifests/r/Ruben2776/PicView/1.6.5/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/1.6.5/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/1.6.5/Ruben2776.PicView.locale.zh-CN.yaml
  manifests/r/Ruben2776/PicView/1.6.5/Ruben2776.PicView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36585 New version: Qalculate.Qalculate version 3.22.0
  manifests/q/Qalculate/Qalculate/3.22.0/Qalculate.Qalculate.installer.yaml
  manifests/q/Qalculate/Qalculate/3.22.0/Qalculate.Qalculate.locale.en-US.yaml
  manifests/q/Qalculate/Qalculate/3.22.0/Qalculate.Qalculate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36583 New version: JetBrains.PyCharm.Community version 213.5744.248
  manifests/j/JetBrains/PyCharm/Community/213.5744.248/JetBrains.PyCharm.Community.installer.yaml
  manifests/j/JetBrains/PyCharm/Community/213.5744.248/JetBrains.PyCharm.Community.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Community/213.5744.248/JetBrains.PyCharm.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36584 New version: JetBrains.PyCharm.Professional version 213.5744.248
  manifests/j/JetBrains/PyCharm/Professional/213.5744.248/JetBrains.PyCharm.Professional.installer.yaml
  manifests/j/JetBrains/PyCharm/Professional/213.5744.248/JetBrains.PyCharm.Professional.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Professional/213.5744.248/JetBrains.PyCharm.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36478 New version: Igoravl.TfsCmdlets version 2.1.4+2594.1
  manifests/i/Igoravl/TfsCmdlets/2.1.4.2594/Igoravl.TfsCmdlets.installer.yaml
  manifests/i/Igoravl/TfsCmdlets/2.1.4.2594/Igoravl.TfsCmdlets.locale.en-US.yaml
  manifests/i/Igoravl/TfsCmdlets/2.1.4.2594/Igoravl.TfsCmdlets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36163 TexasInstruments.TI-SmartView.TI-83 version 5.5.0.2092
  manifests/t/TexasInstruments/TI-SmartView/TI-83/5.5.0.2092/TexasInstruments.TI-SmartView.TI-83.installer.yaml
  manifests/t/TexasInstruments/TI-SmartView/TI-83/5.5.0.2092/TexasInstruments.TI-SmartView.TI-83.locale.en-US.yaml
  manifests/t/TexasInstruments/TI-SmartView/TI-83/5.5.0.2092/TexasInstruments.TI-SmartView.TI-83.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#36506 New version: OSGeo.GeoServer version 2.20.1
  manifests/o/OSGeo/GeoServer/2.20.1/OSGeo.GeoServer.installer.yaml
  manifests/o/OSGeo/GeoServer/2.20.1/OSGeo.GeoServer.locale.en-US.yaml
  manifests/o/OSGeo/GeoServer/2.20.1/OSGeo.GeoServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36509 New version: libjpeg-turbo.libjpeg-turbo-gcc version 2.1.2
  manifests/l/libjpeg-turbo/libjpeg-turbo-gcc/2.1.2/libjpeg-turbo.libjpeg-turbo-gcc.installer.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo-gcc/2.1.2/libjpeg-turbo.libjpeg-turbo-gcc.locale.en-US.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo-gcc/2.1.2/libjpeg-turbo.libjpeg-turbo-gcc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36515 New version: SAGAUserGroupAssociation.SAGAGIS version 8.0.1
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.0.1/SAGAUserGroupAssociation.SAGAGIS.installer.yaml
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.0.1/SAGAUserGroupAssociation.SAGAGIS.locale.en-US.yaml
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.0.1/SAGAUserGroupAssociation.SAGAGIS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36516 New version: SBCL.SBCL version 2.1.10
  manifests/s/SBCL/SBCL/2.1.10/SBCL.SBCL.installer.yaml
  manifests/s/SBCL/SBCL/2.1.10/SBCL.SBCL.locale.en-US.yaml
  manifests/s/SBCL/SBCL/2.1.10/SBCL.SBCL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Policy-Test-1.8, Moderator-Approved, Needs-Attention

#36520 New version: NewBreedSoftware.TuxPaint version 0.9.27
  manifests/n/NewBreedSoftware/TuxPaint/0.9.27/NewBreedSoftware.TuxPaint.installer.yaml
  manifests/n/NewBreedSoftware/TuxPaint/0.9.27/NewBreedSoftware.TuxPaint.locale.en-US.yaml
  manifests/n/NewBreedSoftware/TuxPaint/0.9.27/NewBreedSoftware.TuxPaint.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36521 New version: VMPK.VMPK version 0.8.5
  manifests/v/VMPK/VMPK/0.8.5/VMPK.VMPK.installer.yaml
  manifests/v/VMPK/VMPK/0.8.5/VMPK.VMPK.locale.en-US.yaml
  manifests/v/VMPK/VMPK/0.8.5/VMPK.VMPK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36591 New version: OpenJS.NodeJS.LTS version 16.13.1
  manifests/o/OpenJS/NodeJS/LTS/16.13.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/16.13.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/16.13.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36589 New version: BraveSoftware.BraveBrowser.Nightly version 96.1.35.2
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.2/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.2/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.2/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36522 New version: UweDrechsel.vym version 2.8.20
  manifests/u/UweDrechsel/vym/2.8.20/UweDrechsel.vym.installer.yaml
  manifests/u/UweDrechsel/vym/2.8.20/UweDrechsel.vym.locale.en-US.yaml
  manifests/u/UweDrechsel/vym/2.8.20/UweDrechsel.vym.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#36532 Add version: Catacombae.HFSExplorer version 2021.10.9
  manifests/c/Catacombae/HFSExplorer/2021.10.9/Catacombae.HFSExplorer.installer.yaml
  manifests/c/Catacombae/HFSExplorer/2021.10.9/Catacombae.HFSExplorer.locale.en-US.yaml
  manifests/c/Catacombae/HFSExplorer/2021.10.9/Catacombae.HFSExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Policy-Test-2.7, Moderator-Approved, Needs-Attention

#36560 New version: CCTV.CBox version 5.0.1.0
  manifests/c/CCTV/CBox/5.0.1.0/CCTV.CBox.installer.yaml
  manifests/c/CCTV/CBox/5.0.1.0/CCTV.CBox.locale.en-US.yaml
  manifests/c/CCTV/CBox/5.0.1.0/CCTV.CBox.locale.zh-CN.yaml
  manifests/c/CCTV/CBox/5.0.1.0/CCTV.CBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#36594 New version: schild-report.schild-report version 2.5.117
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.installer.yaml
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.locale.en-US.yaml
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36592 Repair and Update: Mozilla.Firefox.Nightly version 96.0a1
  manifests/m/Mozilla/Firefox/Nightly/96.0a1/Mozilla.Firefox.Nightly.installer.yaml
  manifests/m/Mozilla/Firefox/Nightly/96.0a1/Mozilla.Firefox.Nightly.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/Nightly/96.0a1/Mozilla.Firefox.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36598 JanDeDobbeleer.OhMyPosh version 6.21.0
  manifests/j/JanDeDobbeleer/OhMyPosh/6.21.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.21.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.21.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36606 JanDeDobbeleer.OhMyPosh version 6.22.0
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36597 Lenovo.DockManager version 1.1.0.15
  manifests/l/Lenovo/DockManager/1.1.0.15/Lenovo.DockManager.installer.yaml
  manifests/l/Lenovo/DockManager/1.1.0.15/Lenovo.DockManager.locale.en-US.yaml
  manifests/l/Lenovo/DockManager/1.1.0.15/Lenovo.DockManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36601 New version: ElijahLopez.MusicCaster version 4.90.141
  manifests/e/ElijahLopez/MusicCaster/4.90.141/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.141/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.141/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36600 DoltHub.Dolt version 0.34.6
  manifests/d/DoltHub/Dolt/0.34.6/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.34.6/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.34.6/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36604 New version: OpenShopChannel.Downloader version 1.3.0
  manifests/o/OpenShopChannel/Downloader/1.3.0/OpenShopChannel.Downloader.installer.yaml
  manifests/o/OpenShopChannel/Downloader/1.3.0/OpenShopChannel.Downloader.locale.en-US.yaml
  manifests/o/OpenShopChannel/Downloader/1.3.0/OpenShopChannel.Downloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36609 JanDeDobbeleer.OhMyPosh version 6.22.1
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36599 New version: Daum.PotPlayer version 211118
  manifests/d/Daum/PotPlayer/211118/Daum.PotPlayer.installer.yaml
  manifests/d/Daum/PotPlayer/211118/Daum.PotPlayer.locale.en-US.yaml
  manifests/d/Daum/PotPlayer/211118/Daum.PotPlayer.locale.zh-CN.yaml
  manifests/d/Daum/PotPlayer/211118/Daum.PotPlayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36537 Waiver for AlexThuering.DVDStyler
  manifests/a/AlexThuering/DVDStyler/.validation
Labels: Moderator-Approved, Validation-Metadata

#36614 Remove: schild-report.schild-report version 2.5.117
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.installer.yaml
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.locale.en-US.yaml
  manifests/s/schild-report/schild-report/2.5.117/schild-report.schild-report.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36621 SocialchainInc.PiNetwork version 0.4.5
  manifests/s/SocialchainInc/PiNetwork/0.4.5/SocialchainInc.PiNetwork.installer.yaml
  manifests/s/SocialchainInc/PiNetwork/0.4.5/SocialchainInc.PiNetwork.locale.en-US.yaml
  manifests/s/SocialchainInc/PiNetwork/0.4.5/SocialchainInc.PiNetwork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36617 New version: xanderfrangos.twinkletray version 1.13.11
  manifests/x/xanderfrangos/twinkletray/1.13.11/xanderfrangos.twinkletray.installer.yaml
  manifests/x/xanderfrangos/twinkletray/1.13.11/xanderfrangos.twinkletray.locale.en-US.yaml
  manifests/x/xanderfrangos/twinkletray/1.13.11/xanderfrangos.twinkletray.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36618 Remove: Microsoft.MsGraphCLI version 0.1.7
  manifests/m/Microsoft/MsGraphCLI/0.1.7/Microsoft.MsGraphCLI.installer.yaml
  manifests/m/Microsoft/MsGraphCLI/0.1.7/Microsoft.MsGraphCLI.locale.en-US.yaml
  manifests/m/Microsoft/MsGraphCLI/0.1.7/Microsoft.MsGraphCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36615 New version: Google.Chrome.Canary version 98.0.4741.0
  manifests/g/Google/Chrome/Canary/98.0.4741.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/98.0.4741.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/98.0.4741.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/98.0.4741.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36622 Minor bug fixes
  Tools/YamlCreate.ps1
Labels: Moderator-Approved, Project-File

#36607 New version: XunLei.xunlei version 11.3.4.1850
  manifests/x/XunLei/xunlei/11.3.4.1850/XunLei.xunlei.installer.yaml
  manifests/x/XunLei/xunlei/11.3.4.1850/XunLei.xunlei.locale.en-US.yaml
  manifests/x/XunLei/xunlei/11.3.4.1850/XunLei.xunlei.locale.zh-CN.yaml
  manifests/x/XunLei/xunlei/11.3.4.1850/XunLei.xunlei.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36620 Lenovo.thin installer 1.3.0038
  manifests/l/Lenovo/ThinInstaller/1.3.0038/Lenovo.ThinInstaller.installer.yaml
  manifests/l/Lenovo/ThinInstaller/1.3.0038/Lenovo.ThinInstaller.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36636 New version: ZeroTier.ZeroTierOne version 1.8.4
  manifests/z/ZeroTier/ZeroTierOne/1.8.4/ZeroTier.ZeroTierOne.installer.yaml
  manifests/z/ZeroTier/ZeroTierOne/1.8.4/ZeroTier.ZeroTierOne.locale.en-US.yaml
  manifests/z/ZeroTier/ZeroTierOne/1.8.4/ZeroTier.ZeroTierOne.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36616 New version: Microsoft.Teams.Preview version 1.4.00.32771
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.installer.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.locale.en-US.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36705 JanDeDobbeleer.OhMyPosh version 6.22.2
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.22.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36692 New version: Amazon.AWSCLI version 2.4.4.0
  manifests/a/Amazon/AWSCLI/2.4.4.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.4.4.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.4.4.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36719 New version: Datadog.dd-trace-dotnet version 1.31.0
  manifests/d/Datadog/dd-trace-dotnet/1.31.0/Datadog.dd-trace-dotnet.installer.yaml
  manifests/d/Datadog/dd-trace-dotnet/1.31.0/Datadog.dd-trace-dotnet.locale.en-US.yaml
  manifests/d/Datadog/dd-trace-dotnet/1.31.0/Datadog.dd-trace-dotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36720 New version: Microsoft.AccessibilityInsights.Windows.Canary version 1.1.1796.01
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1796.01/Microsoft.AccessibilityInsights.Windows.Canary.installer.yaml
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1796.01/Microsoft.AccessibilityInsights.Windows.Canary.locale.en-US.yaml
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1796.01/Microsoft.AccessibilityInsights.Windows.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36718 New version: CongusBongus.CDogsSDL version 1.2.0
  manifests/c/CongusBongus/CDogsSDL/1.2.0/CongusBongus.CDogsSDL.installer.yaml
  manifests/c/CongusBongus/CDogsSDL/1.2.0/CongusBongus.CDogsSDL.locale.en-US.yaml
  manifests/c/CongusBongus/CDogsSDL/1.2.0/CongusBongus.CDogsSDL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36721 cuiliang.quicker version 1.27.10
  manifests/c/cuiliang/quicker/1.27.10/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.10/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.10/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36680 New version: OpenWhisperSystems.Signal version 5.25.0
  manifests/o/OpenWhisperSystems/Signal/5.25.0/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/5.25.0/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/5.25.0/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36677 Remove: SandboxiePlus.SandboxieClassic version 5.53.1
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.1/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.1/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.1/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36676 Remove: SandboxiePlus.SandboxieClassic version 5.53.2
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.2/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.2/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.2/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36678 Remove: SandboxiePlus.SandboxieClassic version 5.53.0
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.0/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.0/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.0/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36704 New version: Jackett.Jackett version 0.20.83.0
  manifests/j/Jackett/Jackett/0.20.83.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.83.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.83.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36674 Add version: Sandboxie.Classic version 5.51.6
  manifests/s/Sandboxie/Classic/5.51.6/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.51.6/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.51.6/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36671 Add version: Sandboxie.Classic version 5.53.2
  manifests/s/Sandboxie/Classic/5.53.2/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.53.2/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.53.2/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36670 Add version: Sandboxie.Classic version 5.53.3
  manifests/s/Sandboxie/Classic/5.53.3/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.53.3/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.53.3/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36675 Remove: SandboxiePlus.SandboxieClassic version 5.53.3
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.53.3/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36679 Remove: SandboxiePlus.SandboxieClassic version 5.51.6
  manifests/s/SandboxiePlus/SandboxieClassic/5.51.6/SandboxiePlus.SandboxieClassic.installer.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.51.6/SandboxiePlus.SandboxieClassic.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxieClassic/5.51.6/SandboxiePlus.SandboxieClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36667 Remove: SandboxiePlus.SandboxiePlus version 0.9.8
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36666 Remove: SandboxiePlus.SandboxiePlus version 0.9.6
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.6/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.6/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.6/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36664 Remove: SandboxiePlus.SandboxiePlus version 0.9.4
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.4/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.4/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.4/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36663 Remove: SandboxiePlus.SandboxiePlus version 0.9.3
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.3/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.3/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.3/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36673 Add version: Sandboxie.Classic version 5.53.0
  manifests/s/Sandboxie/Classic/5.53.0/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.53.0/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.53.0/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36668 Remove: SandboxiePlus.SandboxiePlus version 0.9.8b
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8b/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8b/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8b/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36660 Remove: SandboxiePlus.SandboxiePlus version 0.8.2
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.2/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.2/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.2/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36659 Remove: SandboxiePlus.SandboxiePlus version 0.7.5
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.5/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.5/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.5/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36662 Remove: SandboxiePlus.SandboxiePlus version 0.8.9
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.9/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.9/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.9/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36657 Remove: SandboxiePlus.SandboxiePlus version 0.7.1
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.1/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36658 Remove: SandboxiePlus.SandboxiePlus version 0.7.4
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.4/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.4/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.7.4/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36654 Add version: Sandboxie.Plus version 0.7.5
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36653 Add version: Sandboxie.Plus version 0.8.2
  manifests/s/Sandboxie/Plus/0.8.2/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.8.2/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.8.2/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36672 Add version: Sandboxie.Classic version 5.53.1
  manifests/s/Sandboxie/Classic/5.53.1/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.53.1/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.53.1/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36669 Remove: SandboxiePlus.SandboxiePlus version 0.9.8c
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8c/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8c/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8c/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36665 Remove: SandboxiePlus.SandboxiePlus version 0.9.5
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.5/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.5/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.5/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36661 Remove: SandboxiePlus.SandboxiePlus version 0.8.8
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.8/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.8/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.8.8/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36650 Add version: Sandboxie.Plus version 0.9.3
  manifests/s/Sandboxie/Plus/0.9.3/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.3/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.3/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36629 New version: Mirantis.Lens version 5.3.1-latest.20211130.1
  manifests/m/Mirantis/Lens/5.3.1-latest.20211130.1/Mirantis.Lens.installer.yaml
  manifests/m/Mirantis/Lens/5.3.1-latest.20211130.1/Mirantis.Lens.locale.en-US.yaml
  manifests/m/Mirantis/Lens/5.3.1-latest.20211130.1/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36625 New version: ZYROUGE.Yukino version 1.0.10-beta.0
  manifests/z/ZYROUGE/Yukino/1.0.10-beta.0/ZYROUGE.Yukino.installer.yaml
  manifests/z/ZYROUGE/Yukino/1.0.10-beta.0/ZYROUGE.Yukino.locale.en-US.yaml
  manifests/z/ZYROUGE/Yukino/1.0.10-beta.0/ZYROUGE.Yukino.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36624 New version: GrafanaLabs.GrafanaOSS version 8.3.0.0
  manifests/g/GrafanaLabs/GrafanaOSS/8.3.0.0/GrafanaLabs.GrafanaOSS.installer.yaml
  manifests/g/GrafanaLabs/GrafanaOSS/8.3.0.0/GrafanaLabs.GrafanaOSS.locale.en-US.yaml
  manifests/g/GrafanaLabs/GrafanaOSS/8.3.0.0/GrafanaLabs.GrafanaOSS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36641 Remove: SandboxiePlus.SandboxiePlus version 0.9.8d
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.installer.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.locale.en-US.yaml
  manifests/s/SandboxiePlus/SandboxiePlus/0.9.8d/SandboxiePlus.SandboxiePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36656 Add version: Sandboxie.Plus version 0.7.1
  manifests/s/Sandboxie/Plus/0.7.1/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.7.1/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.7.1/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36627 New version: Splawik.pytigon version 0.140
  manifests/s/Splawik/pytigon/0.140/Splawik.pytigon.installer.yaml
  manifests/s/Splawik/pytigon/0.140/Splawik.pytigon.locale.en-US.yaml
  manifests/s/Splawik/pytigon/0.140/Splawik.pytigon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36649 Add version: Sandboxie.Plus version 0.9.4
  manifests/s/Sandboxie/Plus/0.9.4/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.4/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.4/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36630 Remove: Mirantis.Lens.Alpha version 5.3.1-latest.20211130.1
  manifests/m/Mirantis/Lens/Alpha/5.3.1-latest.20211130.1/Mirantis.Lens.Alpha.installer.yaml
  manifests/m/Mirantis/Lens/Alpha/5.3.1-latest.20211130.1/Mirantis.Lens.Alpha.locale.en-US.yaml
  manifests/m/Mirantis/Lens/Alpha/5.3.1-latest.20211130.1/Mirantis.Lens.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36652 Add version: Sandboxie.Plus version 0.8.8
  manifests/s/Sandboxie/Plus/0.8.8/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.8.8/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.8.8/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36595 New version: Viber.Viber version 16.6.0.0
  manifests/v/Viber/Viber/16.6.0.0/Viber.Viber.installer.yaml
  manifests/v/Viber/Viber/16.6.0.0/Viber.Viber.locale.en-US.yaml
  manifests/v/Viber/Viber/16.6.0.0/Viber.Viber.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36612 Remove: schild-report.schild-report version 16.16.3
  manifests/s/schild-report/schild-report/16.16.3/schild-report.schild-report.installer.yaml
  manifests/s/schild-report/schild-report/16.16.3/schild-report.schild-report.locale.en-US.yaml
  manifests/s/schild-report/schild-report/16.16.3/schild-report.schild-report.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36647 Add version: Sandboxie.Plus version 0.9.6
  manifests/s/Sandboxie/Plus/0.9.6/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.6/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.6/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36683 M2Team.NanaZip version 1.0.88.0
  manifests/m/M2Team/NanaZip/1.0.88.0/M2Team.NanaZip.installer.yaml
  manifests/m/M2Team/NanaZip/1.0.88.0/M2Team.NanaZip.locale.en-US.yaml
  manifests/m/M2Team/NanaZip/1.0.88.0/M2Team.NanaZip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36644 Add version: Sandboxie.Plus version 0.9.8c
  manifests/s/Sandboxie/Plus/0.9.8c/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.8c/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.8c/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36710 New version: BraveSoftware.BraveBrowser.Beta version 96.1.34.50
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.50/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.50/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/96.1.34.50/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36711 New version: JanProchazka.dbgate version 4.4.2
  manifests/j/JanProchazka/dbgate/4.4.2/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/4.4.2/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/4.4.2/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36646 Add version: Sandboxie.Plus version 0.9.8
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36686 New version: vim.vim version 8.2.3717
  manifests/v/vim/vim/8.2.3717/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3717/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3717/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36639 New version: Sandboxie.Classic version 5.55.5
  manifests/s/Sandboxie/Classic/5.55.5/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.55.5/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.55.5/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36716 New version: BraveSoftware.BraveBrowser version 96.1.33.98
  manifests/b/BraveSoftware/BraveBrowser/96.1.33.98/BraveSoftware.BraveBrowser.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/96.1.33.98/BraveSoftware.BraveBrowser.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/96.1.33.98/BraveSoftware.BraveBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36640 Moving package: Sandboxie.Plus version 0.9.8d
  manifests/s/Sandboxie/Plus/0.9.8d/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.8d/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.8d/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36693 New version: BraveSoftware.BraveBrowser.Nightly version 96.1.35.3
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.3/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.3/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/96.1.35.3/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36608 New version: Zoom.Zoom.OutlookPlugin version 5.8.6
  manifests/z/Zoom/Zoom/OutlookPlugin/5.8.6/Zoom.Zoom.OutlookPlugin.installer.yaml
  manifests/z/Zoom/Zoom/OutlookPlugin/5.8.6/Zoom.Zoom.OutlookPlugin.locale.en-US.yaml
  manifests/z/Zoom/Zoom/OutlookPlugin/5.8.6/Zoom.Zoom.OutlookPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36682 New version: Tetrate.func-e version 1.1.1
  manifests/t/Tetrate/func-e/1.1.1/Tetrate.func-e.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36655 Add version: Sandboxie.Plus version 0.7.4
  manifests/s/Sandboxie/Plus/0.7.4/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.7.4/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.7.4/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36633 New package: sc0ty.SubSync version 0.17.0
  manifests/s/sc0ty/SubSync/0.17.0/sc0ty.SubSync.installer.yaml
  manifests/s/sc0ty/SubSync/0.17.0/sc0ty.SubSync.locale.en-US.yaml
  manifests/s/sc0ty/SubSync/0.17.0/sc0ty.SubSync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36642 New version: Sandboxie.Plus version 1.0.0.0.0
  manifests/s/Sandboxie/Plus/1.0.0.0.0/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.0.0.0.0/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.0.0.0.0/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36651 Add version: Sandboxie.Plus version 0.8.9
  manifests/s/Sandboxie/Plus/0.8.9/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.8.9/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.8.9/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36703 New version: Google.Chrome.Canary version 98.0.4742.0
  manifests/g/Google/Chrome/Canary/98.0.4742.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/98.0.4742.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/98.0.4742.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/98.0.4742.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36645 Add version: Sandboxie.Plus version 0.9.8b
  manifests/s/Sandboxie/Plus/0.9.8b/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.8b/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.8b/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36648 Add version: Sandboxie.Plus version 0.9.5
  manifests/s/Sandboxie/Plus/0.9.5/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.5/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.5/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Needs-Author-Feedback

#36715 LyonBros.Turtl version 0.7.2.5
  manifests/l/LyonBros/Turtl/0.7.2.5/LyonBros.Turtl.installer.yaml
  manifests/l/LyonBros/Turtl/0.7.2.5/LyonBros.Turtl.locale.en-US.yaml
  manifests/l/LyonBros/Turtl/0.7.2.5/LyonBros.Turtl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36712 Couchcoding.Logbert version 1.6.3.1
  manifests/c/Couchcoding/Logbert/1.6.3.1/Couchcoding.Logbert.installer.yaml
  manifests/c/Couchcoding/Logbert/1.6.3.1/Couchcoding.Logbert.locale.en-US.yaml
  manifests/c/Couchcoding/Logbert/1.6.3.1/Couchcoding.Logbert.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36714 LionelJouin.PiP-Tool version 1.1.2
  manifests/l/LionelJouin/PiP-Tool/1.1.2/LionelJouin.PiP-Tool.installer.yaml
  manifests/l/LionelJouin/PiP-Tool/1.1.2/LionelJouin.PiP-Tool.locale.en-US.yaml
  manifests/l/LionelJouin/PiP-Tool/1.1.2/LionelJouin.PiP-Tool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36723 cuiliang.quicker version 1.27.11
  manifests/c/cuiliang/quicker/1.27.11/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.11/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.11/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36726 New version: BraveSoftware.BraveBrowser.Dev version 96.1.34.51
  manifests/b/BraveSoftware/BraveBrowser/Dev/96.1.34.51/BraveSoftware.BraveBrowser.Dev.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/96.1.34.51/BraveSoftware.BraveBrowser.Dev.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/96.1.34.51/BraveSoftware.BraveBrowser.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36725 Spyder.Spyder version 5.2.0
  manifests/s/Spyder/Spyder/5.2.0/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.2.0/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.2.0/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36727 New version: Cryptomator.Cryptomator version 1.6.4
  manifests/c/Cryptomator/Cryptomator/1.6.4/Cryptomator.Cryptomator.installer.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.4/Cryptomator.Cryptomator.locale.en-US.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.4/Cryptomator.Cryptomator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36729 purocean.YankNote version 3.9.1
  manifests/p/purocean/YankNote/3.9.1/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.9.1/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.9.1/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36605 New version: schild-report.schild-report version 2.6.119
  manifests/s/schild-report/schild-report/2.6.0.119/schild-report.schild-report.installer.yaml
  manifests/s/schild-report/schild-report/2.6.0.119/schild-report.schild-report.locale.en-US.yaml
  manifests/s/schild-report/schild-report/2.6.0.119/schild-report.schild-report.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36463 New version: chrisant996.Clink version 1.2.49.90e388
  manifests/c/chrisant996/Clink/1.2.49.90e388/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.2.49.90e388/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.2.49.90e388/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36730 ZeroX-DG.SnippetStore version 0.2.11
  manifests/z/ZeroX-DG/SnippetStore/0.2.11/ZeroX-DG.SnippetStore.installer.yaml
  manifests/z/ZeroX-DG/SnippetStore/0.2.11/ZeroX-DG.SnippetStore.locale.en-US.yaml
  manifests/z/ZeroX-DG/SnippetStore/0.2.11/ZeroX-DG.SnippetStore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36635 New version: Mirantis.Lens version 5.3.2-latest.20211201.1
  manifests/m/Mirantis/Lens/5.3.2-latest.20211201.1/Mirantis.Lens.installer.yaml
  manifests/m/Mirantis/Lens/5.3.2-latest.20211201.1/Mirantis.Lens.locale.en-US.yaml
  manifests/m/Mirantis/Lens/5.3.2-latest.20211201.1/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
