Repository microsoft/winget-pkgs, pull requests merged in 2021-08, with the labels that each got.

#23260 Microsoft.dotnetRuntime.3-x64 version 3.1.17.30215
  manifests/m/Microsoft/dotnetRuntime/3-x64/3.1.17.30215/Microsoft.dotnetRuntime.3-x64.installer.yaml
  manifests/m/Microsoft/dotnetRuntime/3-x64/3.1.17.30215/Microsoft.dotnetRuntime.3-x64.locale.en-US.yaml
  manifests/m/Microsoft/dotnetRuntime/3-x64/3.1.17.30215/Microsoft.dotnetRuntime.3-x64.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23219 Update Moniker: Python.Python.3 version 3.4.1
  manifests/p/Python/Python/3/3.4.1150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.4.1150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.4.1150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23217 Update Moniker: Python.Python.3 version 3.3.5
  manifests/p/Python/Python/3/3.3.5150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.5150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.5150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23214 Update Moniker: Python.Python.3 version 3.3.2
  manifests/p/Python/Python/3/3.3.2150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.2150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.2150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23213 Update Moniker: Python.Python.3 version 3.3.1
  manifests/p/Python/Python/3/3.3.1150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.1150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.1150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23211 Update Moniker: Python.Python.3 version 3.2.5
  manifests/p/Python/Python/3/3.2.5150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.2.5150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.2.5150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23270 404 Not Found: KDE.KDEConnect version 21.04.3.663
  manifests/k/KDE/KDEConnect/21.04.3.663/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.3.663/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.3.663/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23215 Update Moniker: Python.Python.3 version 3.3.3
  manifests/p/Python/Python/3/3.3.3150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.3150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.3150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23212 Update Moniker: Python.Python.3 version 3.3.0
  manifests/p/Python/Python/3/3.3.150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23218 Update Moniker: Python.Python.3 version 3.4.0
  manifests/p/Python/Python/3/3.4.150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.4.150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.4.150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23261 the-sz.Doro version 2.16
  manifests/t/the-sz/Doro/2.16/the-sz.Doro.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Possible-Duplicate, Validation-Completed

#23291 Update Moniker: Microsoft.PowerShell.Preview version 7.2.0.3
  manifests/m/Microsoft/PowerShell/Preview/7.2.0.3/Microsoft.PowerShell.Preview.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23273 Update Moniker: Notepad++.Notepad++ version 7.8.6
  manifests/n/Notepad++/Notepad++/7.8.6/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23304 Remove old: faisalumair.udeler 1.8.2
  manifests/f/faisalumair/udeler/1.8.2/faisalumair.udeler.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23285 Update Moniker: RocketChat.RocketChat version 3.0.7
  manifests/r/RocketChat/RocketChat/3.0.7/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23274 Update Moniker: Notepad++.Notepad++ version 7.8.7
  manifests/n/Notepad++/Notepad++/7.8.7/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23286 Update Moniker: RocketChat.RocketChat version 3.1.0
  manifests/r/RocketChat/RocketChat/3.1.0/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23292 Update Moniker: Microsoft.PowerShell.Preview version 7.2.0.4
  manifests/m/Microsoft/PowerShell/Preview/7.2.0.4/Microsoft.PowerShell.Preview.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23296 Update Moniker: SublimeHQ.SublimeText.3 version 3.2.2
  manifests/s/SublimeHQ/SublimeText/3/3.2.2/SublimeHQ.SublimeText.3.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23191 Move: GottCode.FocusWriter 1.7.6
  manifests/g/GottCode/FocusWriter/1.7.6/GottCode.FocusWriter.installer.yaml
  manifests/g/GottCode/FocusWriter/1.7.6/GottCode.FocusWriter.locale.en-US.yaml
  manifests/g/GottCode/FocusWriter/1.7.6/GottCode.FocusWriter.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23301 Update Moniker: TechPowerUp.GPU-Z version 2.39.0
  manifests/t/TechPowerUp/GPU-Z/2.39.0/TechPowerUp.GPU-Z.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23268 Added KDE.KDEConnect version 21.04.3.668
  manifests/k/KDE/KDEConnect/21.04.3.668/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.3.668/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.3.668/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23252 MKVToolNix.MKVToolNix version 60.0.0
  manifests/m/MKVToolNix/MKVToolNix/60.0.0/MKVToolNix.MKVToolNix.installer.yaml
  manifests/m/MKVToolNix/MKVToolNix/60.0.0/MKVToolNix.MKVToolNix.locale.en-US.yaml
  manifests/m/MKVToolNix/MKVToolNix/60.0.0/MKVToolNix.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23297 DavidRios.Remindr version 1.4.11
  manifests/d/DavidRios/Remindr/1.4.11/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/1.4.11/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/1.4.11/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23300 LightyearVPN.LightyearVPN version 3.2.1
  manifests/l/LightyearVPN/LightyearVPN/3.2.1/LightyearVPN.LightyearVPN.installer.yaml
  manifests/l/LightyearVPN/LightyearVPN/3.2.1/LightyearVPN.LightyearVPN.locale.en-US.yaml
  manifests/l/LightyearVPN/LightyearVPN/3.2.1/LightyearVPN.LightyearVPN.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23299 TaiStudio.Sofia version 1.0.3
  manifests/t/TaiStudio/Sofia/1.0.3/TaiStudio.Sofia.installer.yaml
  manifests/t/TaiStudio/Sofia/1.0.3/TaiStudio.Sofia.locale.en-US.yaml
  manifests/t/TaiStudio/Sofia/1.0.3/TaiStudio.Sofia.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23255 Microsoft.dotnetRuntime.5-x86 version 5.0.8.30215
  manifests/m/Microsoft/dotnetRuntime/5-x86/5.0.8.30215/Microsoft.dotnetRuntime.5-x86.installer.yaml
  manifests/m/Microsoft/dotnetRuntime/5-x86/5.0.8.30215/Microsoft.dotnetRuntime.5-x86.locale.en-US.yaml
  manifests/m/Microsoft/dotnetRuntime/5-x86/5.0.8.30215/Microsoft.dotnetRuntime.5-x86.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23303 LeGitHubDeTai.AnimeBack version 8.0.5
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.5/LeGitHubDeTai.AnimeBack.installer.yaml
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.5/LeGitHubDeTai.AnimeBack.locale.en-US.yaml
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.5/LeGitHubDeTai.AnimeBack.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23266 Peppy.Osu! 2021.731.0
  manifests/p/Peppy/Osu!/2021.731.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2021.731.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2021.731.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23308 luapp.ToDo version 1.0.0
  manifests/l/luapp/ToDo/1.0.0/luapp.ToDo.installer.yaml
  manifests/l/luapp/ToDo/1.0.0/luapp.ToDo.locale.en-US.yaml
  manifests/l/luapp/ToDo/1.0.0/luapp.ToDo.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23313 gjthompson1.glue version 0.10.0
  manifests/g/gjthompson1/glue/0.10.0/gjthompson1.glue.installer.yaml
  manifests/g/gjthompson1/glue/0.10.0/gjthompson1.glue.locale.en-US.yaml
  manifests/g/gjthompson1/glue/0.10.0/gjthompson1.glue.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23310 AderitoNeto.AfterLife version 1.0.0
  manifests/a/AderitoNeto/AfterLife/1.0.0/AderitoNeto.AfterLife.installer.yaml
  manifests/a/AderitoNeto/AfterLife/1.0.0/AderitoNeto.AfterLife.locale.en-US.yaml
  manifests/a/AderitoNeto/AfterLife/1.0.0/AderitoNeto.AfterLife.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23306 ransome1.sleek version 1.0.9
  manifests/r/ransome1/sleek/1.0.9/ransome1.sleek.installer.yaml
  manifests/r/ransome1/sleek/1.0.9/ransome1.sleek.locale.en-US.yaml
  manifests/r/ransome1/sleek/1.0.9/ransome1.sleek.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23316 afractal.TwitterTron version 1.0.2
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.installer.yaml
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.locale.en-US.yaml
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23267 Add version: fotor.fotor 3.9.2
  manifests/f/fotor/fotor/3.9.2/fotor.fotor.installer.yaml
  manifests/f/fotor/fotor/3.9.2/fotor.fotor.locale.de-DE.yaml
  manifests/f/fotor/fotor/3.9.2/fotor.fotor.locale.en-US.yaml
  manifests/f/fotor/fotor/3.9.2/fotor.fotor.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23295 Update Moniker: SearchDeflector.SearchDeflector version 1.3.2
  manifests/s/SearchDeflector/SearchDeflector/1.3.2/SearchDeflector.SearchDeflector.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23277 Update Moniker: Notepad++.Notepad++ version 7.8.9
  manifests/n/Notepad++/Notepad++/7.8.9/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23283 Update Moniker: RocketChat.RocketChat version 2.17.9
  manifests/r/RocketChat/RocketChat/2.17.9/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23302 Update Moniker: TechPowerUp.GPU-Z version 2.40.0
  manifests/t/TechPowerUp/GPU-Z/2.40.0/TechPowerUp.GPU-Z.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23294 Update Moniker: Microsoft.PowerShell.Preview version 7.2.0.6
  manifests/m/Microsoft/PowerShell/Preview/7.2.0.6/Microsoft.PowerShell.Preview.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23298 Add Moniker: SublimeHQ.SublimeMerge version 1119
  manifests/s/SublimeHQ/SublimeMerge/1119/SublimeHQ.SublimeMerge.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23269 Update metadata/Update Architecture: flux.flux 4.120
  manifests/f/flux/flux/4.120/flux.flux.installer.yaml
  manifests/f/flux/flux/4.120/flux.flux.locale.en-US.yaml
  manifests/f/flux/flux/4.120/flux.flux.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23287 Update Moniker: RocketChat.RocketChat version 3.1.1
  manifests/r/RocketChat/RocketChat/3.1.1/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23272 Added Jackett.Jackett version 0.18.515.0
  manifests/j/Jackett/Jackett/0.18.515.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.515.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.515.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23253 Microsoft.dotnetRuntime.5-x64 version 5.0.8.30215
  manifests/m/Microsoft/dotnetRuntime/5-x64/5.0.8.30215/Microsoft.dotnetRuntime.5-x64.installer.yaml
  manifests/m/Microsoft/dotnetRuntime/5-x64/5.0.8.30215/Microsoft.dotnetRuntime.5-x64.locale.en-US.yaml
  manifests/m/Microsoft/dotnetRuntime/5-x64/5.0.8.30215/Microsoft.dotnetRuntime.5-x64.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23275 Update Moniker: Notepad++.Notepad++ version 7.8.8
  manifests/n/Notepad++/Notepad++/7.8.8/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23312 SebastianFelling.ToughCookies version 0.45.0
  manifests/s/SebastianFelling/ToughCookies/0.45.0/SebastianFelling.ToughCookies.installer.yaml
  manifests/s/SebastianFelling/ToughCookies/0.45.0/SebastianFelling.ToughCookies.locale.en-US.yaml
  manifests/s/SebastianFelling/ToughCookies/0.45.0/SebastianFelling.ToughCookies.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23284 Update Moniker: RocketChat.RocketChat version 3.0.5
  manifests/r/RocketChat/RocketChat/3.0.5/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23288 Update Moniker: RocketChat.RocketChat version 3.2.1
  manifests/r/RocketChat/RocketChat/3.2.1/RocketChat.RocketChat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23326 Remove: FreeSoftwareFoundation.LameXP 4.18
  manifests/f/FreeSoftwareFoundation/LameXP/4.18 Final-1 [Build #2240]/FreeSoftwareFoundation.LameXP.installer.yaml
  manifests/f/FreeSoftwareFoundation/LameXP/4.18 Final-1 [Build #2240]/FreeSoftwareFoundation.LameXP.locale.en-US.yaml
  manifests/f/FreeSoftwareFoundation/LameXP/4.18 Final-1 [Build #2240]/FreeSoftwareFoundation.LameXP.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23322 TheOtterlord.DeckMaster version 1.0.2
  manifests/t/TheOtterlord/DeckMaster/1.0.2/TheOtterlord.DeckMaster.installer.yaml
  manifests/t/TheOtterlord/DeckMaster/1.0.2/TheOtterlord.DeckMaster.locale.en-US.yaml
  manifests/t/TheOtterlord/DeckMaster/1.0.2/TheOtterlord.DeckMaster.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23323 Fabio286.antares version 0.2.1
  manifests/f/Fabio286/antares/0.2.1/Fabio286.antares.installer.yaml
  manifests/f/Fabio286/antares/0.2.1/Fabio286.antares.locale.en-US.yaml
  manifests/f/Fabio286/antares/0.2.1/Fabio286.antares.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23293 Update Moniker: Microsoft.PowerShell.Preview version 7.2.0.5
  manifests/m/Microsoft/PowerShell/Preview/7.2.0.5/Microsoft.PowerShell.Preview.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23265 VentisMedia.MediaMonkey5 version 5.0.1.2431
  manifests/v/VentisMedia/MediaMonkey/5/VentisMedia.MediaMonkey.installer.yaml
  manifests/v/VentisMedia/MediaMonkey/5/VentisMedia.MediaMonkey.locale.en-US.yaml
  manifests/v/VentisMedia/MediaMonkey/5/VentisMedia.MediaMonkey.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#23305 Move: FaisalUmair.Udeler 1.8.2
  manifests/f/FaisalUmair/Udeler/1.8.2/FaisalUmair.Udeler.installer.yaml
  manifests/f/FaisalUmair/Udeler/1.8.2/FaisalUmair.Udeler.locale.en-US.yaml
  manifests/f/FaisalUmair/Udeler/1.8.2/FaisalUmair.Udeler.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23276 Update metadata: fjsoft.MyPhoneExplorer 1.8.15
  manifests/f/fjsoft/MyPhoneExplorer/1.8.15/fjsoft.MyPhoneExplorer.installer.yaml
  manifests/f/fjsoft/MyPhoneExplorer/1.8.15/fjsoft.MyPhoneExplorer.locale.de-DE.yaml
  manifests/f/fjsoft/MyPhoneExplorer/1.8.15/fjsoft.MyPhoneExplorer.locale.en-US.yaml
  manifests/f/fjsoft/MyPhoneExplorer/1.8.15/fjsoft.MyPhoneExplorer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23307 ExpressLRS.ExpressLRS-Configurator version 1.0.1
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.0.1/ExpressLRS.ExpressLRS-Configurator.installer.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.0.1/ExpressLRS.ExpressLRS-Configurator.locale.en-US.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.0.1/ExpressLRS.ExpressLRS-Configurator.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23315 ozankaraali.PiTV version 1.0.2
  manifests/o/ozankaraali/PiTV/1.0.2/ozankaraali.PiTV.installer.yaml
  manifests/o/ozankaraali/PiTV/1.0.2/ozankaraali.PiTV.locale.en-US.yaml
  manifests/o/ozankaraali/PiTV/1.0.2/ozankaraali.PiTV.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23327 ARP/Update metadata: FreeMat.FreeMat 4.2
  manifests/f/FreeMat/FreeMat/4.2/FreeMat.FreeMat.installer.yaml
  manifests/f/FreeMat/FreeMat/4.2/FreeMat.FreeMat.locale.en-US.yaml
  manifests/f/FreeMat/FreeMat/4.2/FreeMat.FreeMat.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23289 GruberQuentin.stay-hydrated version 1.1.0
  manifests/g/GruberQuentin/stay-hydrated/1.1.0/GruberQuentin.stay-hydrated.installer.yaml
  manifests/g/GruberQuentin/stay-hydrated/1.1.0/GruberQuentin.stay-hydrated.locale.en-US.yaml
  manifests/g/GruberQuentin/stay-hydrated/1.1.0/GruberQuentin.stay-hydrated.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23318 JanProchazka.dbgate version 4.2.7
  manifests/j/JanProchazka/dbgate/4.2.7/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/4.2.7/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/4.2.7/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23319 ARP: Python.Python.3 version 3.4.3150
  manifests/p/Python/Python/3/3.4.3150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.4.3150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.4.3150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23317 Tenpi.Waifu2xGUI version 0.1.8
  manifests/t/Tenpi/Waifu2xGUI/0.1.8/Tenpi.Waifu2xGUI.installer.yaml
  manifests/t/Tenpi/Waifu2xGUI/0.1.8/Tenpi.Waifu2xGUI.locale.en-US.yaml
  manifests/t/Tenpi/Waifu2xGUI/0.1.8/Tenpi.Waifu2xGUI.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23329 JanDeDobbeleer.OhMyPosh version 3.171.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23320 losbiw.erin version 2.1.3
  manifests/l/losbiw/erin/2.1.3/losbiw.erin.installer.yaml
  manifests/l/losbiw/erin/2.1.3/losbiw.erin.locale.en-US.yaml
  manifests/l/losbiw/erin/2.1.3/losbiw.erin.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23309 Mingo.Mingo version 1.4.4
  manifests/m/Mingo/Mingo/1.4.4/Mingo.Mingo.installer.yaml
  manifests/m/Mingo/Mingo/1.4.4/Mingo.Mingo.locale.en-US.yaml
  manifests/m/Mingo/Mingo/1.4.4/Mingo.Mingo.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23314 HiroshiFuu.onecopy version 1.0.3
  manifests/h/HiroshiFuu/onecopy/1.0.3/HiroshiFuu.onecopy.installer.yaml
  manifests/h/HiroshiFuu/onecopy/1.0.3/HiroshiFuu.onecopy.locale.en-US.yaml
  manifests/h/HiroshiFuu/onecopy/1.0.3/HiroshiFuu.onecopy.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23258 Microsoft.dotnetRuntime.3-x86 version 3.1.17.30215
  manifests/m/Microsoft/dotnetRuntime/3-x86/3.1.17.30215/Microsoft.dotnetRuntime.3-x86.installer.yaml
  manifests/m/Microsoft/dotnetRuntime/3-x86/3.1.17.30215/Microsoft.dotnetRuntime.3-x86.locale.en-US.yaml
  manifests/m/Microsoft/dotnetRuntime/3-x86/3.1.17.30215/Microsoft.dotnetRuntime.3-x86.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23216 Update Moniker: Python.Python.3 version 3.3.4
  manifests/p/Python/Python/3/3.3.4150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.3.4150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.3.4150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23264 LINQPad5 to v5.44.02
  manifests/l/LINQPad/LINQPad/5/5.44.2/LINQPad.LINQPad.5.installer.yaml
  manifests/l/LINQPad/LINQPad/5/5.44.2/LINQPad.LINQPad.5.locale.en-US.yaml
  manifests/l/LINQPad/LINQPad/5/5.44.2/LINQPad.LINQPad.5.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23220 Update Moniker: Python.Python.3 version 3.4.2
  manifests/p/Python/Python/3/3.4.2150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.4.2150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.4.2150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23334 Move: FrancescoSorge.PasteIntoFile 2.0
  manifests/f/FrancescoSorge/PasteIntoFile/2.0/FrancescoSorge.PasteIntoFile.installer.yaml
  manifests/f/FrancescoSorge/PasteIntoFile/2.0/FrancescoSorge.PasteIntoFile.locale.en-US.yaml
  manifests/f/FrancescoSorge/PasteIntoFile/2.0/FrancescoSorge.PasteIntoFile.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Possible-Duplicate, Validation-Completed

#23335 Remove Microsoft.VisualStudio.2022.Community-Preview version 17.0.31423.177
  manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.31423.177/Microsoft.VisualStudio.2022.Community-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.31423.177/Microsoft.VisualStudio.2022.Community-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.31423.177/Microsoft.VisualStudio.2022.Community-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23333 Remove old: FrancescoSorge.paste-into-file
  manifests/f/FrancescoSorge/paste-into-file/2.0/FrancescoSorge.paste-into-file.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23332 Update metadata: FrancescoSorge.WinPower 0.1
  manifests/f/FrancescoSorge/WinPower/0.1/FrancescoSorge.WinPower.installer.yaml
  manifests/f/FrancescoSorge/WinPower/0.1/FrancescoSorge.WinPower.locale.en-US.yaml
  manifests/f/FrancescoSorge/WinPower/0.1/FrancescoSorge.WinPower.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23328 Metadata: tailscale.tailscale version 1.4.4
  manifests/t/tailscale/tailscale/1.4.4/Tailscale.Tailscale.yaml
  manifests/t/tailscale/tailscale/1.4.4/tailscale.tailscale.installer.yaml
  manifests/t/tailscale/tailscale/1.4.4/tailscale.tailscale.locale.en-US.yaml
  manifests/t/tailscale/tailscale/1.4.4/tailscale.tailscale.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23336 ARP/Update metadata: Foundry376.Mailspring
  manifests/f/Foundry376/Mailspring/1.9.1/Foundry376.Mailspring.installer.yaml
  manifests/f/Foundry376/Mailspring/1.9.1/Foundry376.Mailspring.locale.en-US.yaml
  manifests/f/Foundry376/Mailspring/1.9.1/Foundry376.Mailspring.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23343 ARP/Update metadata: FookesHolding.NoteTabLight 7.2
  manifests/f/FookesHolding/NoteTabLight/7.2/FookesHolding.NoteTabLight.installer.yaml
  manifests/f/FookesHolding/NoteTabLight/7.2/FookesHolding.NoteTabLight.locale.en-US.yaml
  manifests/f/FookesHolding/NoteTabLight/7.2/FookesHolding.NoteTabLight.yaml
  manifests/f/FookesHolding/NoteTabLight/NoteTab Light 7.2/FookesHolding.NoteTabLight.installer.yaml
  manifests/f/FookesHolding/NoteTabLight/NoteTab Light 7.2/FookesHolding.NoteTabLight.locale.en-US.yaml
  manifests/f/FookesHolding/NoteTabLight/NoteTab Light 7.2/FookesHolding.NoteTabLight.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23359 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/5.1.20.45210/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23354 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/6.1.21.20205/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23352 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/5.1.20.47915/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23360 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/6.1.21.10313/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23348 Fix version mismatch for Microsoft.VisualStudio.2019.Enterprise-Preview
  manifests/m/Microsoft/VisualStudio/2019/Enterprise-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Enterprise-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23358 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/6.1.21.15503/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23330 Update metadata/Add de-DE-Locale: FreeCAD.FreeCAD 0.19.2
  manifests/f/FreeCAD/FreeCAD/0.19.2/FreeCAD.FreeCAD.installer.yaml
  manifests/f/FreeCAD/FreeCAD/0.19.2/FreeCAD.FreeCAD.locale.de-DE.yaml
  manifests/f/FreeCAD/FreeCAD/0.19.2/FreeCAD.FreeCAD.locale.en-US.yaml
  manifests/f/FreeCAD/FreeCAD/0.19.2/FreeCAD.FreeCAD.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23345 Update: hello-efficiency-inc.raven-reader v1.0.64
  manifests/h/hello-efficiency-inc/raven-reader/1.0.64/hello-efficiency-inc.raven-reader.installer.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.64/hello-efficiency-inc.raven-reader.locale.en-US.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.64/hello-efficiency-inc.raven-reader.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23331 PaloAltoNetworks.GlobalProtect version 6.0.0
  manifests/p/PaloAltoNetworks/GlobalProtect/6.0.0/PaloAltoNetworks.GlobalProtect.installer.yaml
  manifests/p/PaloAltoNetworks/GlobalProtect/6.0.0/PaloAltoNetworks.GlobalProtect.locale.en-US.yaml
  manifests/p/PaloAltoNetworks/GlobalProtect/6.0.0/PaloAltoNetworks.GlobalProtect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23357 Fix version mismatch for Microsoft.VisualStudio.2019.Professional-Preview
  manifests/m/Microsoft/VisualStudio/2019/Professional-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Professional-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23311 aliceandbob-io.aliceandbob version 1.0.0-Beta1
  manifests/a/aliceandbob-io/aliceandbob/1.0.0-Beta1/aliceandbob-io.aliceandbob.installer.yaml
  manifests/a/aliceandbob-io/aliceandbob/1.0.0-Beta1/aliceandbob-io.aliceandbob.locale.en-US.yaml
  manifests/a/aliceandbob-io/aliceandbob/1.0.0-Beta1/aliceandbob-io.aliceandbob.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23355 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/5.1.20.27910/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23337 ARP: Python.Python.3 version 3.4.4150
  manifests/p/Python/Python/3/3.4.4150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.4.4150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.4.4150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23351 Fix version mismatch for Microsoft.VisualStudio.2019.Community-Preview
  manifests/m/Microsoft/VisualStudio/2019/Community-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Community-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23363 ARP/Update manifest: FontForge.FontForge 07-11-2020
  manifests/f/FontForge/FontForge/07-11-2020/FontForge.FontForge.installer.yaml
  manifests/f/FontForge/FontForge/07-11-2020/FontForge.FontForge.locale.en-US.yaml
  manifests/f/FontForge/FontForge/07-11-2020/FontForge.FontForge.yaml
  manifests/f/FontForge/FontForge/2020.11.07/FontForge.FontForge.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23349 Fix version mismatch for Microsoft.VisualStudio.2022.Enterprise-Preview
  manifests/m/Microsoft/VisualStudio/2022/Enterprise-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Enterprise-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Enterprise-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Enterprise-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23356 Fix version mismatch for Microsoft.VisualStudio.2022.Professional-Preview
  manifests/m/Microsoft/VisualStudio/2022/Professional-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Professional-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Professional-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional-Preview/17.0.0 Preview 2.1/Microsoft.VisualStudio.2022.Professional-Preview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23353 Fix version mismatch for Microsoft.dotnetPreview
  manifests/m/Microsoft/dotnetPreview/5.1.20.41709/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23367 Added ProductCode to Peppy.Osu!
  manifests/p/Peppy/Osu!/2021.731.0/Peppy.Osu!.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23321 BPMN-RPA Studio
  manifests/1/1ic/BPMN-RPAstudio/21.8.2/1ic.BPMN-RPAstudio.installer.yaml
  manifests/1/1ic/BPMN-RPAstudio/21.8.2/1ic.BPMN-RPAstudio.locale.en-US.yaml
  manifests/1/1ic/BPMN-RPAstudio/21.8.2/1ic.BPMN-RPAstudio.yaml
Labels: Azure-Pipeline-Passed, Internal-Error-Static-Scan, Moderator-Approved, Needs: Attention, Validation-Completed

#23368 ARP/Update metadata: FoldingAtHome.FoldingAtHome 7.6.21
  manifests/f/FoldingAtHome/FoldingAtHome/7.6.21/FoldingAtHome.FoldingAtHome.installer.yaml
  manifests/f/FoldingAtHome/FoldingAtHome/7.6.21/FoldingAtHome.FoldingAtHome.locale.en-US.yaml
  manifests/f/FoldingAtHome/FoldingAtHome/7.6.21/FoldingAtHome.FoldingAtHome.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23369 Add version: Fndroid.ClashForWindows 0.17.0
  manifests/f/Fndroid/ClashForWindows/0.17.0/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.17.0/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.17.0/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23366 CNRISTI.QuteMol version 0.4.1
  manifests/c/CNRISTI/QuteMol/0.4.1/CNRISTI.QuteMol.installer.yaml
  manifests/c/CNRISTI/QuteMol/0.4.1/CNRISTI.QuteMol.locale.en-US.yaml
  manifests/c/CNRISTI/QuteMol/0.4.1/CNRISTI.QuteMol.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23371 ARP/Update metadata: FlyByWireSimulations.FlyByWireSimulationsInstaller 1.2.0
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/1.2.0/FlyByWireSimulations.FlyByWireSimulationsInstaller.installer.yaml
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/1.2.0/FlyByWireSimulations.FlyByWireSimulationsInstaller.locale.en-US.yaml
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/1.2.0/FlyByWireSimulations.FlyByWireSimulationsInstaller.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23375 Add version: Firetrust.MailWasherPro 7.12.56
  manifests/f/Firetrust/MailWasherPro/7.12.56/Firetrust.MailWasherPro.installer.yaml
  manifests/f/Firetrust/MailWasherPro/7.12.56/Firetrust.MailWasherPro.locale.en-US.yaml
  manifests/f/Firetrust/MailWasherPro/7.12.56/Firetrust.MailWasherPro.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23379 Chia Blockchain Update to Version 1.2.3
  manifests/c/ChiaNetwork/GUIforChiaBlockchain/1.2.3/ChiaNetwork.GUIforChiaBlockchain.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23377 Add version: QL-Win.QuickLook 3.6.10.0
  manifests/q/QL-Win/QuickLook/3.6.10.0/QL-Win.QuickLook.installer.yaml
  manifests/q/QL-Win/QuickLook/3.6.10.0/QL-Win.QuickLook.locale.en-US.yaml
  manifests/q/QL-Win/QuickLook/3.6.10.0/QL-Win.QuickLook.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23388 Update: JetBrains.GoLand version 212.4746.93
  manifests/j/JetBrains/GoLand/212.4746.93/JetBrains.GoLand.installer.yaml
  manifests/j/JetBrains/GoLand/212.4746.93/JetBrains.GoLand.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/212.4746.93/JetBrains.GoLand.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23389 Update: JetBrains.Hub version 21.1.13492
  manifests/j/JetBrains/Hub/21.1.13492/JetBrains.Hub.installer.yaml
  manifests/j/JetBrains/Hub/21.1.13492/JetBrains.Hub.locale.en-US.yaml
  manifests/j/JetBrains/Hub/21.1.13492/JetBrains.Hub.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23392 Update: JetBrains.YouTrack version 21.3.22664
  manifests/j/JetBrains/YouTrack/21.3.22664/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/21.3.22664/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/21.3.22664/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23382 Kellojo.BudgetP version 1.2.0
  manifests/k/Kellojo/BudgetP/1.2.0/Kellojo.BudgetP.installer.yaml
  manifests/k/Kellojo/BudgetP/1.2.0/Kellojo.BudgetP.locale.en-US.yaml
  manifests/k/Kellojo/BudgetP/1.2.0/Kellojo.BudgetP.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23390 Update: JetBrains.PHPStorm version 212.4746.100
  manifests/j/JetBrains/PHPStorm/212.4746.100/JetBrains.PHPStorm.installer.yaml
  manifests/j/JetBrains/PHPStorm/212.4746.100/JetBrains.PHPStorm.locale.en-US.yaml
  manifests/j/JetBrains/PHPStorm/212.4746.100/JetBrains.PHPStorm.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23342 ARP: Python.Python.3 version 3.5.4150
  manifests/p/Python/Python/3/3.5.4150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.5.4150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.5.4150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23346 ARP: Python.Python.3 version 3.6.2150
  manifests/p/Python/Python/3/3.6.2150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.2150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.2150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23347 ARP: Python.Python.3 version 3.6.3150
  manifests/p/Python/Python/3/3.6.3150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.3150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.3150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23361 ARP: Python.Python.3 version 3.6.5150
  manifests/p/Python/Python/3/3.6.5150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.5150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.5150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23399 404 Not Found: Microsoft.SurfaceDuoEmulator version 2021.527.6
  manifests/m/Microsoft/SurfaceDuoEmulator/2021.527.6/Microsoft.SurfaceDuoEmulator.installer.yaml
  manifests/m/Microsoft/SurfaceDuoEmulator/2021.527.6/Microsoft.SurfaceDuoEmulator.locale.en-US.yaml
  manifests/m/Microsoft/SurfaceDuoEmulator/2021.527.6/Microsoft.SurfaceDuoEmulator.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23393 Update: AntSoftware.AntRenamer version 2.12.0
  manifests/a/AntSoftware/AntRenamer/2.12.0/AntSoftware.AntRenamer.installer.yaml
  manifests/a/AntSoftware/AntRenamer/2.12.0/AntSoftware.AntRenamer.locale.en-US.yaml
  manifests/a/AntSoftware/AntRenamer/2.12.0/AntSoftware.AntRenamer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23395 Microsoft.VisualStudioCode.Insiders_v1.59.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.59.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Manifest-Path-Error, Moderator-Approved, Needs-Author-Feedback, Needs: author feedback, Validation-Completed

#23394 ARP/Update metadata: Figma.fonthelper 1.0.9
  manifests/f/Figma/fonthelper/1.0.9.0/Figma.fonthelper.yaml
  manifests/f/Figma/fonthelper/1.0.9/Figma.fonthelper.installer.yaml
  manifests/f/Figma/fonthelper/1.0.9/Figma.fonthelper.locale.en-US.yaml
  manifests/f/Figma/fonthelper/1.0.9/Figma.fonthelper.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Retry-1, Validation-Completed

#23402 Added KDE.KDEConnect version 21.04.3.669
  manifests/k/KDE/KDEConnect/21.04.3.669/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.3.669/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.3.669/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Retry-1, Validation-Completed

#23404 Added vim.vim version 8.2.3273
  manifests/v/vim/vim/8.2.3273/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3273/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3273/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23445 404 Not Found: HPPrintingKorea.SamsungEasyDocumentCreator
  manifests/h/HPPrintingKorea/SamsungEasyDocumentCreator/2.02.53.00/HPPrintingKorea.SamsungEasyDocumentCreator.installer.yaml
  manifests/h/HPPrintingKorea/SamsungEasyDocumentCreator/2.02.53.00/HPPrintingKorea.SamsungEasyDocumentCreator.locale.en-US.yaml
  manifests/h/HPPrintingKorea/SamsungEasyDocumentCreator/2.02.53.00/HPPrintingKorea.SamsungEasyDocumentCreator.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23403 404 Not Found: KDE.KDEConnect version 21.04.3.664
  manifests/k/KDE/KDEConnect/21.04.3.664/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.3.664/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.3.664/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23448 Remove old: FSC-SOFT.VoiceMacro-Stable 1.4
  manifests/f/FSC-SOFT/VoiceMacro-Stable/1.4/FSC-SOFT.VoiceMacro-Stable.installer.yaml
  manifests/f/FSC-SOFT/VoiceMacro-Stable/1.4/FSC-SOFT.VoiceMacro-Stable.locale.en-US.yaml
  manifests/f/FSC-SOFT/VoiceMacro-Stable/1.4/FSC-SOFT.VoiceMacro-Stable.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23372 Update metadata: Flameshot.Flameshot 0.10.1
  manifests/f/Flameshot/Flameshot/0.10.1/Flameshot.Flameshot.installer.yaml
  manifests/f/Flameshot/Flameshot/0.10.1/Flameshot.Flameshot.locale.en-US.yaml
  manifests/f/Flameshot/Flameshot/0.10.1/Flameshot.Flameshot.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23446 Update metadata: FarManager.FarManager 3.0.5858
  manifests/f/FarManager/FarManager/3.0.5858/FarManager.FarManager.installer.yaml
  manifests/f/FarManager/FarManager/3.0.5858/FarManager.FarManager.locale.en-US.yaml
  manifests/f/FarManager/FarManager/3.0.5858/FarManager.FarManager.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23364 Cockos.REAPER version 6.33
  manifests/c/Cockos/REAPER/6.33/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.33/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.33/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23344 ARP: Python.Python.3 version 3.6.150
  manifests/p/Python/Python/3/3.6.150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23350 ARP: Python.Python.3 version 3.6.4150
  manifests/p/Python/Python/3/3.6.4150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.4150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.4150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23362 ARP: Python.Python.3 version 3.6.6150
  manifests/p/Python/Python/3/3.6.6150/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.6150/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.6150/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23384 TARIQ.developer-tools version 1.1.6
  manifests/t/TARIQ/developer-tools/1.1.6/TARIQ.developer-tools.installer.yaml
  manifests/t/TARIQ/developer-tools/1.1.6/TARIQ.developer-tools.locale.en-US.yaml
  manifests/t/TARIQ/developer-tools/1.1.6/TARIQ.developer-tools.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23401 Elgato Control Center 1.1.4.792
  manifests/e/Elgato/ControlCenter/1.1.4.792/Elgato.ControlCenter.installer.yaml
  manifests/e/Elgato/ControlCenter/1.1.4.792/Elgato.ControlCenter.locale.en-US.yaml
  manifests/e/Elgato/ControlCenter/1.1.4.792/Elgato.ControlCenter.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23405 Add version: FastStone.Capture 9.5
  manifests/f/FastStone/Capture/9.5/FastStone.Capture.installer.yaml
  manifests/f/FastStone/Capture/9.5/FastStone.Capture.locale.en-US.yaml
  manifests/f/FastStone/Capture/9.5/FastStone.Capture.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23406 Add version: FastStone.Capture 9.6
  manifests/f/FastStone/Capture/9.6/FastStone.Capture.installer.yaml
  manifests/f/FastStone/Capture/9.6/FastStone.Capture.locale.en-US.yaml
  manifests/f/FastStone/Capture/9.6/FastStone.Capture.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23407 ARP: FastStone.Viewer 7.5
  manifests/f/FastStone/Viewer/7.5/FastStone.Viewer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23447 Added Jackett version 0.18.518.0.
  manifests/j/Jackett/Jackett/0.18.518.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.518.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.518.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23341 ARP: Python.Python.3 version 3.5.3150
  manifests/p/Python/Python/3/3.5.3150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.5.3150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.5.3150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23338 ARP: Python.Python.3 version 3.5.150
  manifests/p/Python/Python/3/3.5.150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.5.150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.5.150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23453 Updated NordPassTeam.NordPass to version 4.7.13
  manifests/n/NordPassTeam/NordPass/4.7.13/NordPassTeam.NordPass.installer.yaml
  manifests/n/NordPassTeam/NordPass/4.7.13/NordPassTeam.NordPass.locale.en-US.yaml
  manifests/n/NordPassTeam/NordPass/4.7.13/NordPassTeam.NordPass.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23398 Update: Gridcoin.Client version 5.3.2
  manifests/g/Gridcoin/Client/5.3.2/Gridcoin.Client.installer.yaml
  manifests/g/Gridcoin/Client/5.3.2/Gridcoin.Client.locale.en-US.yaml
  manifests/g/Gridcoin/Client/5.3.2/Gridcoin.Client.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23444 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.9.1150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.9.1150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.9.1150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23439 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.8.6150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.8.6150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.8.6150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23438 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.7.7150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.7.7150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.7.7150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23431 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.5.2150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.5.2150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.5.2150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23429 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.6.3150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.3150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.3150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23422 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.6.5150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.5150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.5150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23409 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.6.8150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.6.8150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.6.8150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23442 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.8.1150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.8.1150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.8.1150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23455 Remove old: extendoffice.officetab 14.10
  manifests/e/extendoffice/officetab/14.10/extendoffice.officetab.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23408 Microsoft.VisualStudioCode.Insiders_v1.59.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.59.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#23440 Fix version mismatch for Python.Python.3
  manifests/p/Python/Python/3/3.7.8150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.7.8150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.7.8150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed
