Repository microsoft/winget-pkgs, pull requests merged in 2021-10, with the labels that each got.

#29094 Added DataGrip version 212.5457.16.
  manifests/j/JetBrains/DataGrip/212.5457.16/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/212.5457.16/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/212.5457.16/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#27363 New version: Baidu.BaiduNetdisk version 7.7.4
  manifests/b/Baidu/BaiduNetdisk/7.7.4/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.4/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.4/Baidu.BaiduNetdisk.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.4/Baidu.BaiduNetdisk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29095 Added IntelliJ IDEA Educational Edition version 212.5284.54.
  manifests/j/JetBrains/IntelliJIDEA/Edu/212.5284.54/JetBrains.IntelliJIDEA.Edu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#28868 WildfireGames.0AD version 0.0.25b
  manifests/w/WildfireGames/0AD/r25860-alpha/WildfireGames.0AD.installer.yaml
  manifests/w/WildfireGames/0AD/r25860-alpha/WildfireGames.0AD.locale.en-US.yaml
  manifests/w/WildfireGames/0AD/r25860-alpha/WildfireGames.0AD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29087 New version: Tencent.QQ version 9.5.1.27869
  manifests/t/Tencent/QQ/9.5.1.27869/Tencent.QQ.installer.yaml
  manifests/t/Tencent/QQ/9.5.1.27869/Tencent.QQ.locale.en-US.yaml
  manifests/t/Tencent/QQ/9.5.1.27869/Tencent.QQ.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/9.5.1.27869/Tencent.QQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#27842 New version: Baidu.BaiduNetdisk version 7.7.5
  manifests/b/Baidu/BaiduNetdisk/7.7.5/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.5/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.5/Baidu.BaiduNetdisk.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.5/Baidu.BaiduNetdisk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29110 New version: OpenWhisperSystems.Signal version 5.18.0
  manifests/o/OpenWhisperSystems/Signal/5.18.0/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/5.18.0/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/5.18.0/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29078 BitSum.Coreprio version 0.0.6.8
  manifests/b/BitSum/Coreprio/0.0.6.8/BitSum.Coreprio.installer.yaml
  manifests/b/BitSum/Coreprio/0.0.6.8/BitSum.Coreprio.locale.en-US.yaml
  manifests/b/BitSum/Coreprio/0.0.6.8/BitSum.Coreprio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29105 Scilab.Scilab version 6.1.1
  manifests/s/Scilab/Scilab/6.1.1/Scilab.Scilab.installer.yaml
  manifests/s/Scilab/Scilab/6.1.1/Scilab.Scilab.locale.en-US.yaml
  manifests/s/Scilab/Scilab/6.1.1/Scilab.Scilab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29135 Add BiglyBT 2.3.0.0
  manifests/b/BiglySoftware/BiglyBT/2.3.0.0/BiglySoftware.BiglyBT.installer.yaml
  manifests/b/BiglySoftware/BiglyBT/2.3.0.0/BiglySoftware.BiglyBT.locale.en-US.yaml
  manifests/b/BiglySoftware/BiglyBT/2.3.0.0/BiglySoftware.BiglyBT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29103 Loom.Loom version 0.100.3
  manifests/l/Loom/Loom/0.100.3/Loom.Loom.installer.yaml
  manifests/l/Loom/Loom/0.100.3/Loom.Loom.locale.en-US.yaml
  manifests/l/Loom/Loom/0.100.3/Loom.Loom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29113 New version: LibreOffice.LibreOffice version 7.2.1.2
  manifests/l/LibreOffice/LibreOffice/7.2.1.2/LibreOffice.LibreOffice.installer.yaml
  manifests/l/LibreOffice/LibreOffice/7.2.1.2/LibreOffice.LibreOffice.locale.en-US.yaml
  manifests/l/LibreOffice/LibreOffice/7.2.1.2/LibreOffice.LibreOffice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29138 Moving: XMind.XMind2020 version 11.0.2
  manifests/x/XMind/XMind2020/11.0.2/XMind.XMind2020.installer.yaml
  manifests/x/XMind/XMind2020/11.0.2/XMind.XMind2020.locale.en-US.yaml
  manifests/x/XMind/XMind2020/11.0.2/XMind.XMind2020.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29139 Moving: XMind.XMind2020 version 11.0.1
  manifests/x/XMind/XMind2020/11.0.1/XMind.XMind2020.installer.yaml
  manifests/x/XMind/XMind2020/11.0.1/XMind.XMind2020.locale.en-US.yaml
  manifests/x/XMind/XMind2020/11.0.1/XMind.XMind2020.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29140 Moving: XMind.XMind2020 version 10.2.1
  manifests/x/XMind/XMind2020/10.2.1/XMind.XMind2020.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29149 New version: Docker Desktop version 4.1.0
  manifests/d/Docker/DockerDesktop/4.1.0/Docker.DockerDesktop.installer.yaml
  manifests/d/Docker/DockerDesktop/4.1.0/Docker.DockerDesktop.locale.en-US.yaml
  manifests/d/Docker/DockerDesktop/4.1.0/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29151 Microsoft.VisualStudioCode.Insiders_v1.61.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.61.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29147 New version: Docker Desktop version 4.0.1
  manifests/d/Docker/DockerDesktop/4.0.1/Docker.DockerDesktop.installer.yaml
  manifests/d/Docker/DockerDesktop/4.0.1/Docker.DockerDesktop.locale.en-US.yaml
  manifests/d/Docker/DockerDesktop/4.0.1/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29134 New: Versa.MagiCut version 1.1.1
  manifests/v/Versa/MagiCut/1.1.1/Versa.MagiCut.installer.yaml
  manifests/v/Versa/MagiCut/1.1.1/Versa.MagiCut.locale.en-US.yaml
  manifests/v/Versa/MagiCut/1.1.1/Versa.MagiCut.locale.zh-CN.yaml
  manifests/v/Versa/MagiCut/1.1.1/Versa.MagiCut.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#29146 Moved: XMind.XMind version 10.2.1
  manifests/x/XMind/XMind/10.2.1/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/10.2.1/XMind.XMind.locale.en-US.yaml
  manifests/x/XMind/XMind/10.2.1/XMind.XMind.locale.zh-CN.yaml
  manifests/x/XMind/XMind/10.2.1/XMind.XMind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29193 New version: vim.vim version 8.2.3459
  manifests/v/vim/vim/8.2.3459/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3459/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3459/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29187 Update Netron to 5.2.6
  manifests/l/LutzRoeder/Netron/5.2.6/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.2.6/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.2.6/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29152 Added Microsoft Edge version 94.0.992.37.
  manifests/m/Microsoft/Edge/94.0.992.37/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/94.0.992.37/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/94.0.992.37/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29175 Added PrependPath install switch for Python 3 version 3.9.7.
  manifests/p/Python/Python/3/3.9.7150.0/Python.Python.3.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29174 Added AWS Command Line Interface version 2.2.43.0.
  manifests/a/Amazon/AWSCLI/2.2.43.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.2.43.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.2.43.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29196 New version: Jackett.Jackett version 0.18.875.0
  manifests/j/Jackett/Jackett/0.18.875.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.875.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.875.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29157 Updated Spotify to version 1.1.69.612.gb7409abc.
  manifests/s/Spotify/Spotify/1.1.69.612.gb7409abc/Spotify.Spotify.installer.yaml
  manifests/s/Spotify/Spotify/1.1.69.612.gb7409abc/Spotify.Spotify.locale.en-US.yaml
  manifests/s/Spotify/Spotify/1.1.69.612.gb7409abc/Spotify.Spotify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#29195 New version: OpenWhisperSystems.Signal.Beta version 5.19.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/5.19.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.19.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.19.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29142 New: XMind.XMind8 version 3.7.9.201912052356
  manifests/x/XMind/XMind8/3.7.9.201912052356/XMind.XMind8.installer.yaml
  manifests/x/XMind/XMind8/3.7.9.201912052356/XMind.XMind8.locale.en-US.yaml
  manifests/x/XMind/XMind8/3.7.9.201912052356/XMind.XMind8.locale.zh-CN.yaml
  manifests/x/XMind/XMind8/3.7.9.201912052356/XMind.XMind8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29141 Moved: XMind.XMind version 11.0.2
  manifests/x/XMind/XMind/11.0.2/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/11.0.2/XMind.XMind.locale.en-US.yaml
  manifests/x/XMind/XMind/11.0.2/XMind.XMind.locale.zh-CN.yaml
  manifests/x/XMind/XMind/11.0.2/XMind.XMind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29192 New version: PaulSori.mStreamServer version 5.6.1
  manifests/p/PaulSori/mStreamServer/5.6.1/PaulSori.mStreamServer.installer.yaml
  manifests/p/PaulSori/mStreamServer/5.6.1/PaulSori.mStreamServer.locale.en-US.yaml
  manifests/p/PaulSori/mStreamServer/5.6.1/PaulSori.mStreamServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29143 New: CCTV.CBox version 5.0.0.2
  manifests/c/CCTV/CBox/5.0.0.2/CCTV.CBox.installer.yaml
  manifests/c/CCTV/CBox/5.0.0.2/CCTV.CBox.locale.en-US.yaml
  manifests/c/CCTV/CBox/5.0.0.2/CCTV.CBox.locale.zh-CN.yaml
  manifests/c/CCTV/CBox/5.0.0.2/CCTV.CBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#29145 PhonerLite update 2.96
  manifests/p/Phoner/PhonerLite/2.96/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29190 New version: Logitech.Options 9.40.86
  manifests/l/Logitech/Options/9.40.86/Logitech.Options.installer.yaml
  manifests/l/Logitech/Options/9.40.86/Logitech.Options.locale.en-US.yaml
  manifests/l/Logitech/Options/9.40.86/Logitech.Options.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29101 GLab.GLab version 1.21.0
  manifests/g/GLab/GLab/1.21.0/GLab.GLab.installer.yaml
  manifests/g/GLab/GLab/1.21.0/GLab.GLab.locale.en-US.yaml
  manifests/g/GLab/GLab/1.21.0/GLab.GLab.yaml
Labels: Validation-Completed, Validation-Executable-Error, Moderator-Approved, Needs-Attention

#29104 StartAllBack 2.9.90
  manifests/s/StartIsBack/StartAllBack/2.9.90/StartIsBack.StartAllBack.installer.yaml
  manifests/s/StartIsBack/StartAllBack/2.9.90/StartIsBack.StartAllBack.locale.en-US.yaml
  manifests/s/StartIsBack/StartAllBack/2.9.90/StartIsBack.StartAllBack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#29184 PDFsam.PDFsam version 4.2.7.0
  manifests/p/PDFsam/PDFsam/4.2.7.0/PDFsam.PDFsam.installer.yaml
  manifests/p/PDFsam/PDFsam/4.2.7.0/PDFsam.PDFsam.locale.en-US.yaml
  manifests/p/PDFsam/PDFsam/4.2.7.0/PDFsam.PDFsam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29100 GLab.GLab version 1.21.1
  manifests/g/GLab/GLab/1.21.1/GLab.GLab.installer.yaml
  manifests/g/GLab/GLab/1.21.1/GLab.GLab.locale.en-US.yaml
  manifests/g/GLab/GLab/1.21.1/GLab.GLab.yaml
Labels: Validation-Completed, Validation-Executable-Error, Moderator-Approved, Needs-Attention

#29144 Moved: XMind.XMind version 11.0.1
  manifests/x/XMind/XMind/11.0.1/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/11.0.1/XMind.XMind.locale.en-US.yaml
  manifests/x/XMind/XMind/11.0.1/XMind.XMind.locale.zh-CN.yaml
  manifests/x/XMind/XMind/11.0.1/XMind.XMind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29158 Added Unity version 2021.1.23f1.
  manifests/u/UnityTechnologies/Unity/2021.1.23f1/UnityTechnologies.Unity.installer.yaml
  manifests/u/UnityTechnologies/Unity/2021.1.23f1/UnityTechnologies.Unity.locale.en-US.yaml
  manifests/u/UnityTechnologies/Unity/2021.1.23f1/UnityTechnologies.Unity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29194 New version: Microsoft.AccessibilityInsightsWindows.Canary version 1.1.1734.01
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1734.01/Microsoft.AccessibilityInsightsWindows.Canary.installer.yaml
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1734.01/Microsoft.AccessibilityInsightsWindows.Canary.locale.en-US.yaml
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1734.01/Microsoft.AccessibilityInsightsWindows.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29191 New version: Microsoft.AccessibilityInsightsWindows.Canary version 1.1.1733.01
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1733.01/Microsoft.AccessibilityInsightsWindows.Canary.installer.yaml
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1733.01/Microsoft.AccessibilityInsightsWindows.Canary.locale.en-US.yaml
  manifests/m/Microsoft/AccessibilityInsightsWindows/Canary/1.1.1733.01/Microsoft.AccessibilityInsightsWindows.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29137 New version: XMind.XMind version 11.1.0
  manifests/x/XMind/XMind/11.1.0/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/11.1.0/XMind.XMind.locale.en-US.yaml
  manifests/x/XMind/XMind/11.1.0/XMind.XMind.locale.zh-CN.yaml
  manifests/x/XMind/XMind/11.1.0/XMind.XMind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29130 New version: RedHat.Podman version 3.4.0
  manifests/r/RedHat/Podman/3.4.0/RedHat.Podman.installer.yaml
  manifests/r/RedHat/Podman/3.4.0/RedHat.Podman.locale.en-US.yaml
  manifests/r/RedHat/Podman/3.4.0/RedHat.Podman.yaml
Labels: Validation-Completed, Validation-Executable-Error, Moderator-Approved, Needs-Attention

#29202 New version: Baidu.BaiduNetdisk version 7.7.8
  manifests/b/Baidu/BaiduNetdisk/7.7.8/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.8/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.8/Baidu.BaiduNetdisk.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduNetdisk/7.7.8/Baidu.BaiduNetdisk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29201 Testing: Microsoft.ASPNetCore.5-x64 version 5.0.9.21365
  manifests/m/Microsoft/ASPNetCore/5-x64/5.0.9.21365/Microsoft.ASPNetCore.5-x64.installer.yaml
  manifests/m/Microsoft/ASPNetCore/5-x64/5.0.9.21365/Microsoft.ASPNetCore.5-x64.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29204 Added Jackett version 0.18.887.0.
  manifests/j/Jackett/Jackett/0.18.887.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.887.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.887.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29252 New version: RustemMussabekov.Raindrop version 5.4.8
  manifests/r/RustemMussabekov/Raindrop/5.4.8/RustemMussabekov.Raindrop.installer.yaml
  manifests/r/RustemMussabekov/Raindrop/5.4.8/RustemMussabekov.Raindrop.locale.en-US.yaml
  manifests/r/RustemMussabekov/Raindrop/5.4.8/RustemMussabekov.Raindrop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29250 JanDeDobbeleer.OhMyPosh version 5.7.0
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29249 Changed Inkscape upgradeBehavior to uninstallPrevious
  manifests/i/Inkscape/Inkscape/1.1.1/Inkscape.Inkscape.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29215 JanDeDobbeleer.OhMyPosh version 5.6.6
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29246 New version: JFrog.Conan version 1.40.3
  manifests/j/JFrog/Conan/1.40.3/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/1.40.3/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/1.40.3/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29245 Add version: hluk.CopyQ version 5.0.0
  manifests/h/hluk/CopyQ/v5.0.0/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/v5.0.0/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/v5.0.0/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29220 Update MadrasCheck.flow.locale.en-US.yaml
  manifests/m/MadrasCheck/flow/1.2.10/MadrasCheck.flow.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29225 New version: Cppcheck.Cppcheck version 2.6
  manifests/c/Cppcheck/Cppcheck/2.6/Cppcheck.Cppcheck.installer.yaml
  manifests/c/Cppcheck/Cppcheck/2.6/Cppcheck.Cppcheck.locale.en-US.yaml
  manifests/c/Cppcheck/Cppcheck/2.6/Cppcheck.Cppcheck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29244 New version: h3poteto.whalebird-desktop version 4.4.4
  manifests/h/h3poteto/whalebird-desktop/4.4.4/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/4.4.4/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/4.4.4/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29231 New version: Jackett.Jackett version 0.18.891.0
  manifests/j/Jackett/Jackett/0.18.891.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.891.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.891.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29234 New version: PaulSori.mStreamServer version 5.7.0
  manifests/p/PaulSori/mStreamServer/5.7.0/PaulSori.mStreamServer.installer.yaml
  manifests/p/PaulSori/mStreamServer/5.7.0/PaulSori.mStreamServer.locale.en-US.yaml
  manifests/p/PaulSori/mStreamServer/5.7.0/PaulSori.mStreamServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29242 New version: vim.vim version 8.2.3463
  manifests/v/vim/vim/8.2.3463/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3463/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3463/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29241 New version: tazzben.Assessment-Disaggregation version 1.4.1
  manifests/t/tazzben/Assessment-Disaggregation/1.4.1/tazzben.Assessment-Disaggregation.installer.yaml
  manifests/t/tazzben/Assessment-Disaggregation/1.4.1/tazzben.Assessment-Disaggregation.locale.en-US.yaml
  manifests/t/tazzben/Assessment-Disaggregation/1.4.1/tazzben.Assessment-Disaggregation.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29237 New version: skyjake.Lagrange version 1.7.1
  manifests/s/skyjake/Lagrange/1.7.1/skyjake.Lagrange.installer.yaml
  manifests/s/skyjake/Lagrange/1.7.1/skyjake.Lagrange.locale.en-US.yaml
  manifests/s/skyjake/Lagrange/1.7.1/skyjake.Lagrange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29238 New version: SnailDOS.SnailFM version 2.1.3
  manifests/s/SnailDOS/SnailFM/2.1.3/SnailDOS.SnailFM.installer.yaml
  manifests/s/SnailDOS/SnailFM/2.1.3/SnailDOS.SnailFM.locale.en-US.yaml
  manifests/s/SnailDOS/SnailFM/2.1.3/SnailDOS.SnailFM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29236 New version: rocksdanister.LivelyWallpaper version 1.7.2.2
  manifests/r/rocksdanister/LivelyWallpaper/1.7.2.2/rocksdanister.LivelyWallpaper.installer.yaml
  manifests/r/rocksdanister/LivelyWallpaper/1.7.2.2/rocksdanister.LivelyWallpaper.locale.en-US.yaml
  manifests/r/rocksdanister/LivelyWallpaper/1.7.2.2/rocksdanister.LivelyWallpaper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29232 New version: JGraph.Draw version 15.4.0
  manifests/j/JGraph/Draw/15.4.0/JGraph.Draw.installer.yaml
  manifests/j/JGraph/Draw/15.4.0/JGraph.Draw.locale.en-US.yaml
  manifests/j/JGraph/Draw/15.4.0/JGraph.Draw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29233 New version: Joplin.Joplin.Pre-release version 2.5.1
  manifests/j/Joplin/Joplin/Pre-release/2.5.1/Joplin.Joplin.Pre-release.installer.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.5.1/Joplin.Joplin.Pre-release.locale.en-US.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.5.1/Joplin.Joplin.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29235 New version: RivaFarabi.Deckboard version 1.9.97
  manifests/r/RivaFarabi/Deckboard/1.9.97/RivaFarabi.Deckboard.installer.yaml
  manifests/r/RivaFarabi/Deckboard/1.9.97/RivaFarabi.Deckboard.locale.en-US.yaml
  manifests/r/RivaFarabi/Deckboard/1.9.97/RivaFarabi.Deckboard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29240 New version: spluxx.Protoman version 0.4.1
  manifests/s/spluxx/Protoman/0.4.1/spluxx.Protoman.installer.yaml
  manifests/s/spluxx/Protoman/0.4.1/spluxx.Protoman.locale.en-US.yaml
  manifests/s/spluxx/Protoman/0.4.1/spluxx.Protoman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29229 New version: GDevelop.GDevelop version 5.0.0-beta119
  manifests/g/GDevelop/GDevelop/5.0.0-beta119/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.0.0-beta119/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.0.0-beta119/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29222 New version: Amazon.SAM-CLI version 1.33.0
  manifests/a/Amazon/SAM-CLI/1.33.0/Amazon.SAM-CLI.installer.yaml
  manifests/a/Amazon/SAM-CLI/1.33.0/Amazon.SAM-CLI.locale.en-US.yaml
  manifests/a/Amazon/SAM-CLI/1.33.0/Amazon.SAM-CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29239 New version: SomePythonThings.WingetUIStore version 0.4
  manifests/s/SomePythonThings/WingetUIStore/0.4/SomePythonThings.WingetUIStore.installer.yaml
  manifests/s/SomePythonThings/WingetUIStore/0.4/SomePythonThings.WingetUIStore.locale.en-US.yaml
  manifests/s/SomePythonThings/WingetUIStore/0.4/SomePythonThings.WingetUIStore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29247 New version: joncampbell123.DOSBox-X version dosbox-x-v0.83.18
  manifests/j/joncampbell123/DOSBox-X/0.83.18/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.18/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.18/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29219 Update Asana.Asana.locale.en-US.yaml
  manifests/a/Asana/Asana/1.3.0/Asana.Asana.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29214 CheckMAL.AppCheck version 2.5.51.9
  manifests/c/CheckMAL/AppCheck/2.5.51.9/CheckMAL.AppCheck.installer.yaml
  manifests/c/CheckMAL/AppCheck/2.5.51.9/CheckMAL.AppCheck.locale.en-US.yaml
  manifests/c/CheckMAL/AppCheck/2.5.51.9/CheckMAL.AppCheck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#28137 Create manifest for wkhtmltox
  manifests/w/wkhtmltopdf/wkhtmltox/0.12.6-1/wkhtmltopdf.wkhtmltox.installer.yaml
  manifests/w/wkhtmltopdf/wkhtmltox/0.12.6-1/wkhtmltopdf.wkhtmltox.locale.en-US.yaml
  manifests/w/wkhtmltopdf/wkhtmltox/0.12.6-1/wkhtmltopdf.wkhtmltox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29243 New version: WowUp.Wowup version 2.4.6
  manifests/w/WowUp/Wowup/2.4.6/WowUp.Wowup.installer.yaml
  manifests/w/WowUp/Wowup/2.4.6/WowUp.Wowup.locale.en-US.yaml
  manifests/w/WowUp/Wowup/2.4.6/WowUp.Wowup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29255 New: Microsoft.dotnetPreview version 6.1.21.46306
  manifests/m/Microsoft/dotnetPreview/6.1.21.46306/Microsoft.dotnetPreview.installer.yaml
  manifests/m/Microsoft/dotnetPreview/6.1.21.46306/Microsoft.dotnetPreview.locale.en-US.yaml
  manifests/m/Microsoft/dotnetPreview/6.1.21.46306/Microsoft.dotnetPreview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29221 Update Chatty.Chatty.locale.en-US.yaml
  manifests/c/Chatty/Chatty/0.15/Chatty.Chatty.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29218 Update VaclavSlavik.Poedit.locale.en-US.yaml
  manifests/v/VaclavSlavik/Poedit/3.0/VaclavSlavik.Poedit.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29230 New version: GitHub.Atom.Beta version 1.59.0-beta0
  manifests/g/GitHub/Atom/Beta/1.59.0-beta0/GitHub.Atom.Beta.installer.yaml
  manifests/g/GitHub/Atom/Beta/1.59.0-beta0/GitHub.Atom.Beta.locale.en-US.yaml
  manifests/g/GitHub/Atom/Beta/1.59.0-beta0/GitHub.Atom.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29216 Update KakaoEntertainmentCorp.MelonPlayer.locale.ko-KR.yaml
  manifests/k/KakaoEntertainmentCorp/MelonPlayer/1.0.7/KakaoEntertainmentCorp.MelonPlayer.locale.ko-KR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29223 New version: ChiaNetwork.GUIforChiaBlockchain version 1.2.9
  manifests/c/ChiaNetwork/GUIforChiaBlockchain/1.2.9/ChiaNetwork.GUIforChiaBlockchain.installer.yaml
  manifests/c/ChiaNetwork/GUIforChiaBlockchain/1.2.9/ChiaNetwork.GUIforChiaBlockchain.locale.en-US.yaml
  manifests/c/ChiaNetwork/GUIforChiaBlockchain/1.2.9/ChiaNetwork.GUIforChiaBlockchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29260 AltSnap 1.47
  manifests/a/AltSnap/AltSnap/1.47/AltSnap.AltSnap.installer.yaml
  manifests/a/AltSnap/AltSnap/1.47/AltSnap.AltSnap.locale.en-US.yaml
  manifests/a/AltSnap/AltSnap/1.47/AltSnap.AltSnap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29267 New version: dorssel.usbipd-win version 1.1.0
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.installer.yaml
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.locale.en-US.yaml
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29257 Added GrafanaLabs.GrafanaEnterprise version 8.1.5.0
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.1.5.0/GrafanaLabs.GrafanaEnterprise.installer.yaml
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.1.5.0/GrafanaLabs.GrafanaEnterprise.locale.en-US.yaml
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.1.5.0/GrafanaLabs.GrafanaEnterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29265 Submitting Microsoft TeamMate version 0.1.0-ci.102+Branch.main.Sha.f3…
  manifests/m/Microsoft/TeamMate/0.1.0.0/Microsoft.TeamMate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29266 Added Puppet Agent version 6.24.0
  manifests/p/Puppet/puppet-agent/6.24.0/Puppet.puppet-agent.installer.yaml
  manifests/p/Puppet/puppet-agent/6.24.0/Puppet.puppet-agent.locale.en-US.yaml
  manifests/p/Puppet/puppet-agent/6.24.0/Puppet.puppet-agent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29277 New version: vim.vim version 8.2.3469
  manifests/v/vim/vim/8.2.3469/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3469/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3469/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29272 Update: dorssel.usbipd-win version 1.1.0
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.installer.yaml
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.locale.en-US.yaml
  manifests/d/dorssel/usbipd-win/1.1.0/dorssel.usbipd-win.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29273 New version: h3poteto.whalebird-desktop version 4.4.5
  manifests/h/h3poteto/whalebird-desktop/4.4.5/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/4.4.5/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/4.4.5/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29274 New version: HandBrake.HandBrake version 1.4.2
  manifests/h/HandBrake/HandBrake/1.4.2/HandBrake.HandBrake.installer.yaml
  manifests/h/HandBrake/HandBrake/1.4.2/HandBrake.HandBrake.locale.en-US.yaml
  manifests/h/HandBrake/HandBrake/1.4.2/HandBrake.HandBrake.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29276 New version: OliverSchwendener.ueli version 8.17.1
  manifests/o/OliverSchwendener/ueli/8.17.1/OliverSchwendener.ueli.installer.yaml
  manifests/o/OliverSchwendener/ueli/8.17.1/OliverSchwendener.ueli.locale.en-US.yaml
  manifests/o/OliverSchwendener/ueli/8.17.1/OliverSchwendener.ueli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29275 New version: hello-efficiency-inc.raven-reader version 1.0.67
  manifests/h/hello-efficiency-inc/raven-reader/1.0.67/hello-efficiency-inc.raven-reader.installer.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.67/hello-efficiency-inc.raven-reader.locale.en-US.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.67/hello-efficiency-inc.raven-reader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29280 InstallerSwitches: Python.Python.3 version 3.9.6150.0
  manifests/p/Python/Python/3/3.9.6150.0/Python.Python.3.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29282 New version: Xunlei.xunlei version 11.3.1.1820
  manifests/x/XunLei/xunlei/11.3.1.1820/XunLei.xunlei.installer.yaml
  manifests/x/XunLei/xunlei/11.3.1.1820/XunLei.xunlei.locale.en-US.yaml
  manifests/x/XunLei/xunlei/11.3.1.1820/XunLei.xunlei.locale.zh-CN.yaml
  manifests/x/XunLei/xunlei/11.3.1.1820/XunLei.xunlei.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29270 New version: Buttercup.Buttercup version 2.11.0
  manifests/b/Buttercup/Buttercup/2.11.0/Buttercup.Buttercup.installer.yaml
  manifests/b/Buttercup/Buttercup/2.11.0/Buttercup.Buttercup.locale.en-US.yaml
  manifests/b/Buttercup/Buttercup/2.11.0/Buttercup.Buttercup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29284 Logitech.LogiTune version 2.200.202.0
  manifests/l/Logitech/LogiTune/2.200.202.0/Logitech.LogiTune.installer.yaml
  manifests/l/Logitech/LogiTune/2.200.202.0/Logitech.LogiTune.locale.en-US.yaml
  manifests/l/Logitech/LogiTune/2.200.202.0/Logitech.LogiTune.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29287 Fix spelling in Installer URL for Microsoft.AzureStorageExplorer version 1.21.1
  manifests/m/Microsoft/AzureStorageExplorer/1.21.1/Microsoft.AzureStorageExplorer.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29122 Update Microsoft.TeamsPreview to 1.4.00.26376
  manifests/m/Microsoft/TeamsPreview/1.4.00.26376/Microsoft.TeamsPreview.installer.yaml
  manifests/m/Microsoft/TeamsPreview/1.4.00.26376/Microsoft.TeamsPreview.locale.en-US.yaml
  manifests/m/Microsoft/TeamsPreview/1.4.00.26376/Microsoft.TeamsPreview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29119 Update Microsoft.TeamsExploration to 1.4.00.27319
  manifests/m/Microsoft/TeamsExploration/1.4.00.27319/Microsoft.TeamsExploration.installer.yaml
  manifests/m/Microsoft/TeamsExploration/1.4.00.27319/Microsoft.TeamsExploration.locale.en-US.yaml
  manifests/m/Microsoft/TeamsExploration/1.4.00.27319/Microsoft.TeamsExploration.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29120 Update Microsoft.Teams to 1.4.00.26376
  manifests/m/Microsoft/Teams/1.4.00.26376/Microsoft.Teams.installer.yaml
  manifests/m/Microsoft/Teams/1.4.00.26376/Microsoft.Teams.locale.en-US.yaml
  manifests/m/Microsoft/Teams/1.4.00.26376/Microsoft.Teams.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#29271 New version: dbeaver.dbeaver version 21.2.2
  manifests/d/dbeaver/dbeaver/21.2.2/dbeaver.dbeaver.installer.yaml
  manifests/d/dbeaver/dbeaver/21.2.2/dbeaver.dbeaver.locale.en-US.yaml
  manifests/d/dbeaver/dbeaver/21.2.2/dbeaver.dbeaver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29121 Update Microsoft.TeamsContinuousDeployment to 1.4.00.27369
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.27369/Microsoft.TeamsContinuousDeployment.installer.yaml
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.27369/Microsoft.TeamsContinuousDeployment.locale.en-US.yaml
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.27369/Microsoft.TeamsContinuousDeployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29300 New version: Jackett.Jackett version 0.18.896.0
  manifests/j/Jackett/Jackett/0.18.896.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.896.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.896.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29298 New version: CozyCloud.CozyDrive.Beta version 3.30.1-beta.3
  manifests/c/CozyCloud/CozyDrive/Beta/3.30.1-beta.3/CozyCloud.CozyDrive.Beta.installer.yaml
  manifests/c/CozyCloud/CozyDrive/Beta/3.30.1-beta.3/CozyCloud.CozyDrive.Beta.locale.en-US.yaml
  manifests/c/CozyCloud/CozyDrive/Beta/3.30.1-beta.3/CozyCloud.CozyDrive.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29303 New version: NexusMods.Vortex version 1.4.16
  manifests/n/NexusMods/Vortex/1.4.16/NexusMods.Vortex.installer.yaml
  manifests/n/NexusMods/Vortex/1.4.16/NexusMods.Vortex.locale.en-US.yaml
  manifests/n/NexusMods/Vortex/1.4.16/NexusMods.Vortex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29312 Fix: Treat warnings as non-fatal
  Tools/SandboxTest.ps1
Labels: Moderator-Approved, Project-File

#29313 Microsoft.VisualStudioCode.Insiders_v1.61.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.61.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29136 GSmartControl.GSmartControl version 1.1.3
  manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.installer.yaml
  manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.locale.en-US.yaml
  manifests/g/GSmartControl/GSmartControl/1.1.3/GSmartControl.GSmartControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#27270 New: ICBC.ICBCEBankAssist version 1.9.3.0
  manifests/i/ICBC/ICBCEBankAssist/1.9.3.0/ICBC.ICBCEBankAssist.installer.yaml
  manifests/i/ICBC/ICBCEBankAssist/1.9.3.0/ICBC.ICBCEBankAssist.locale.en-US.yaml
  manifests/i/ICBC/ICBCEBankAssist/1.9.3.0/ICBC.ICBCEBankAssist.locale.zh-CN.yaml
  manifests/i/ICBC/ICBCEBankAssist/1.9.3.0/ICBC.ICBCEBankAssist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Policy-Test-1.8, Moderator-Approved, Needs-Attention

#29377 New version: vim.vim version 8.2.3475
  manifests/v/vim/vim/8.2.3475/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3475/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3475/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29364 Add Windows Terminal 1.10.2714.0 Release
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.installer.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.en-US.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.fr-FR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.it-IT.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.ja-JP.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.ko-KR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.pt-BR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.ru-RU.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.zh-CN.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.locale.zh-TW.yaml
  manifests/m/Microsoft/WindowsTerminal/1.10.2714.0/Microsoft.WindowsTerminal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29365 Add Windows Terminal Preview 1.11.2731.0 Release
  manifests/m/Microsoft/WindowsTerminalPreview/1.11.2731.0/Microsoft.WindowsTerminalPreview.installer.yaml
  manifests/m/Microsoft/WindowsTerminalPreview/1.11.2731.0/Microsoft.WindowsTerminalPreview.locale.en-US.yaml
  manifests/m/Microsoft/WindowsTerminalPreview/1.11.2731.0/Microsoft.WindowsTerminalPreview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29368 New version: Python.Python.3 version 3.10.150.0
  manifests/p/Python/Python/3/3.10.150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.10.150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.10.150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29457 New version: brimdata.brim version 0.26.0
  manifests/b/brimdata/brim/0.26.0/brimdata.brim.installer.yaml
  manifests/b/brimdata/brim/0.26.0/brimdata.brim.locale.en-US.yaml
  manifests/b/brimdata/brim/0.26.0/brimdata.brim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29340 Removed non-working manifest for Visual Studio Team Explorer 2019 version 16.11.2.
  manifests/m/Microsoft/VisualStudio/2019/TeamExplorer/16.11.2/Microsoft.VisualStudio.2019.TeamExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29288 Delete manifests/a/AltDrag/AltDrag/1.46 directory
  manifests/a/AltDrag/AltDrag/1.46/AltDrag.AltDrag.installer.yaml
  manifests/a/AltDrag/AltDrag/1.46/AltDrag.AltDrag.locale.en-US.yaml
  manifests/a/AltDrag/AltDrag/1.46/AltDrag.AltDrag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29290 Added Microsoft Edge version 94.0.992.38.
  manifests/m/Microsoft/Edge/94.0.992.38/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/94.0.992.38/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/94.0.992.38/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#29431 Add version: BandicamCompany.Bandicam version 3.3.3.1209
  manifests/b/BandicamCompany/Bandicam/3.3.3.1209/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/3.3.3.1209/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/3.3.3.1209/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29428 Add version: BandicamCompany.Bandicam version 3.4.2.1258
  manifests/b/BandicamCompany/Bandicam/3.4.2.1258/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/3.4.2.1258/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/3.4.2.1258/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29427 Add version: BandicamCompany.Bandicam version 3.4.3.1263
  manifests/b/BandicamCompany/Bandicam/3.4.3.1263/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/3.4.3.1263/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/3.4.3.1263/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29424 Add version: BandicamCompany.Bandicam version 4.0.1.1339
  manifests/b/BandicamCompany/Bandicam/4.0.1.1339/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.0.1.1339/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.0.1.1339/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29420 Add version: BandicamCompany.Bandicam version 4.1.2.1385
  manifests/b/BandicamCompany/Bandicam/4.1.2.1385/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.2.1385/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.2.1385/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29419 Add version: BandicamCompany.Bandicam version 4.1.3.1400
  manifests/b/BandicamCompany/Bandicam/4.1.3.1400/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.3.1400/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.3.1400/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29415 Add version: BandicamCompany.Bandicam version 4.1.7.1424
  manifests/b/BandicamCompany/Bandicam/4.1.7.1424/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.7.1424/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.7.1424/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29411 Add version: BandicamCompany.Bandicam version 4.3.1.1490
  manifests/b/BandicamCompany/Bandicam/4.3.1.1490/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.3.1.1490/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.3.1.1490/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29412 Add version: BandicamCompany.Bandicam version 4.3.0.1479
  manifests/b/BandicamCompany/Bandicam/4.3.0.1479/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.3.0.1479/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.3.0.1479/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29406 Add version: BandicamCompany.Bandicam version 4.4.1.1539
  manifests/b/BandicamCompany/Bandicam/4.4.1.1539/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.4.1.1539/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.4.1.1539/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29401 Add version: BandicamCompany.Bandicam version 4.5.2.1602
  manifests/b/BandicamCompany/Bandicam/4.5.2.1602/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.2.1602/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.2.1602/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29399 Add version: BandicamCompany.Bandicam version 4.5.4.1624
  manifests/b/BandicamCompany/Bandicam/4.5.4.1624/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.4.1624/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.4.1624/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29398 Add version: BandicamCompany.Bandicam version 4.5.5.1632
  manifests/b/BandicamCompany/Bandicam/4.5.5.1632/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.5.1632/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.5.1632/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29397 Add version: BandicamCompany.Bandicam version 4.5.6.1646
  manifests/b/BandicamCompany/Bandicam/4.5.6.1646/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.6.1646/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.6.1646/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29400 Add version: BandicamCompany.Bandicam version 4.5.3.1608
  manifests/b/BandicamCompany/Bandicam/4.5.3.1608/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.3.1608/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.3.1608/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29392 Add version: BandicamCompany.Bandicam version 4.6.0.1683
  manifests/b/BandicamCompany/Bandicam/4.6.0.1683/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.0.1683/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.0.1683/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29416 Add version: BandicamCompany.Bandicam version 4.1.6.1423
  manifests/b/BandicamCompany/Bandicam/4.1.6.1423/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.6.1423/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.1.6.1423/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29423 Add version: BandicamCompany.Bandicam version 4.0.2.1352
  manifests/b/BandicamCompany/Bandicam/4.0.2.1352/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.0.2.1352/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.0.2.1352/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29391 Add version: BandicamCompany.Bandicam version 4.6.1.1688
  manifests/b/BandicamCompany/Bandicam/4.6.1.1688/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.1.1688/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.1.1688/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29390 Add version: BandicamCompany.Bandicam version 4.6.2.1699
  manifests/b/BandicamCompany/Bandicam/4.6.2.1699/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.2.1699/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.2.1699/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29379 Add Version: BandicamCompany.Bandicam v5.0.1.1799
  manifests/b/BandicamCompany/Bandicam/5.0.1.1799/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/5.0.1.1799/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/5.0.1.1799/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29380 Add version: BandicamCompany.Bandicam version 5.1.0.1822
  manifests/b/BandicamCompany/Bandicam/5.1.0.1822/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/5.1.0.1822/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/5.1.0.1822/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29395 Add version: BandicamCompany.Bandicam version 4.5.8.1673
  manifests/b/BandicamCompany/Bandicam/4.5.8.1673/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.8.1673/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.8.1673/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29394 Microsoft.VisualStudioCode.Insiders_v1.61.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.61.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29432 Add version: BandicamCompany.Bandicam version 3.3.2.1195
  manifests/b/BandicamCompany/Bandicam/3.3.2.1195/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/3.3.2.1195/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/3.3.2.1195/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29384 Add version: BandicamCompany.Bandicam version 4.6.4.1728
  manifests/b/BandicamCompany/Bandicam/4.6.4.1728/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.4.1728/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.6.4.1728/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29396 Add version: BandicamCompany.Bandicam version 4.5.7.1660
  manifests/b/BandicamCompany/Bandicam/4.5.7.1660/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.7.1660/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/4.5.7.1660/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29374 New version: ransome1.sleek version 1.1.2
  manifests/r/ransome1/sleek/1.1.2/ransome1.sleek.installer.yaml
  manifests/r/ransome1/sleek/1.1.2/ransome1.sleek.locale.en-US.yaml
  manifests/r/ransome1/sleek/1.1.2/ransome1.sleek.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29349 Fixed install arguments for Visual Studio Load Test Controller 2019 version 16.11.3.
  manifests/m/Microsoft/VisualStudio/2019/TestController/16.11.3/Microsoft.VisualStudio.2019.TestController.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29348 Fixed install arguments for Visual Studio Load Test Controller 2019 version 16.11.2.
  manifests/m/Microsoft/VisualStudio/2019/TestController/16.11.2/Microsoft.VisualStudio.2019.TestController.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29344 Fixed install arguments for Visual Studio Test Agent 2019 version 16.11.2.
  manifests/m/Microsoft/VisualStudio/2019/TestAgent/16.11.2/Microsoft.VisualStudio.2019.TestAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29330 Fixed install arguments for Visual Studio Enterprise 2019 version 16.11.1.
  manifests/m/Microsoft/VisualStudio/2019/Enterprise/16.11.1/Microsoft.VisualStudio.2019.Enterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29327 Fixed install arguments for Visual Studio Build Tools 2019 version 16.11.3.
  manifests/m/Microsoft/VisualStudio/2019/BuildTools/16.11.3/Microsoft.VisualStudio.2019.BuildTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
