Repository microsoft/winget-pkgs, pull requests merged in 2021-03, with the labels that each got.

#8160 Added Visual Studio Test Agent version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/TestAgent/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8159 Added Visual Studio Load Test Controller version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/TestController/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8158 Added Robo3T version 1.4.3.
  manifests/3T/Robo3T/1.4.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8133 Remove 404 Not Found manifest: RProject.R (4.0.3)
  manifests/RProject/R/4.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8135 Remove 404 Not Found manifest: Oracle.VirtualBoxTest (6.1.19-142777)
  manifests/Oracle/VirtualBoxTest/6.1.19-142777.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8136 Remove 404 Not Found manifest: Oracle.VirtualBoxTest (6.1.19-142733)
  manifests/Oracle/VirtualBoxTest/6.1.19-142733.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8139 Remove 404 Not Found manifest: MariaDB.Server (10.5.7)
  manifests/MariaDB/Server/10.5.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8140 Remove 404 Not Found manifest: LovettSoftware.MyMoney.Net (1.1.65.0)
  manifests/LovettSoftware/MyMoney.Net/1.1.65.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8138 Remove 404 Not Found manifest: Microsoft.XMLNotepad (2.8.0.23)
  manifests/Microsoft/XMLNotepad/2.8.0.23.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8134 Remove 404 Not Found manifest: Oracle.VirtualBoxTest (6.1.19-142894)
  manifests/Oracle/VirtualBoxTest/6.1.19-142894.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8137 Remove 404 Not Found manifest: Microsoft.XMLNotepad (2.8.0.24)
  manifests/Microsoft/XMLNotepad/2.8.0.24.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8132 Remove 404 Not Found manifest: TimKosse.FileZillaClientNightly (3.52.2-20210218)
  manifests/TimKosse/FileZillaClientNightly/3.52.2-20210218.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8157 Add BZFlag version 2.4.22.
  manifests/BZFlag/BZFlag/2.4.22.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8156 Copyright year update for FileBot
  manifests/FileBot/FileBot/4.9.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8155 Added Visual Studio Build Tools version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/BuildTools/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8154 Added Visual Studio Enterprise version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/Enterprise/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8151 Added Visual Studio Community version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/Community/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8148 Fix Url for iA.Writer
  manifests/iA/Writer/1.4.7655.28208.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8163 Update 0.24.0.yaml
  manifests/DCSS/DungeonCrawlStoneSoup/0.26.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8164 Add AXIS Camera Station Preview 0.2109.027
  manifests/AxisCommunications/AxisCameraStation-Preview/0.2109.027.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8162 stackless 3.7.5
  manifests/stackless/stackless/3.7.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8161 Added Windows WDK version 10.1.19041.645.
  manifests/Microsoft/WindowsWDK/10.1.19041.645.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8165 Add dbeaver 21.0.0
  manifests/DBeaver/DBeaver/21.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8168 Add Windows Terminal Preview 1.7 Release
  manifests/Microsoft/WindowsTerminalPreview/1.7.572.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8167 Add Windows Terminal 1.6 Release
  manifests/Microsoft/WindowsTerminal/1.6.10571.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8171 Add Sonos S1Controller 11.2.4
  manifests/Sonos/S1Controller/11.2.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8169 Add Docker Desktop stable version 3.2.0.61504
  manifests/Docker/DockerDesktop/3.2.0.61504.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8166 Add WireGuard 0.3.8
  manifests/WireGuard/WireGuard/0.3.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8176 Microsoft.VisualStudioCodeInsiders-System-x64_v1.54.23.e798986320
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.54.23.e798986320.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8177 Microsoft.VisualStudioCodeInsiders-User-x86_v1.54.23.e798986320
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.54.23.e798986320.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8178 Microsoft.VisualStudioCodeInsiders-User-x64_v1.54.21.e798986320
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.54.21.e798986320.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8179 Microsoft.VisualStudioCodeInsiders-System-x86_v1.54.24.e798986320
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.54.24.e798986320.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8172 Added TablePlus version 3.12.19.0.
  manifests/TablePlus/TablePlus/3.12.19.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#4961 FlashpointInfinity 9.0
  manifests/bluemaxima/FlashpointInfinity/9.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8180 webview2-evergreen 1.3.141.59
  manifests/Microsoft/webview2-evergreen/1.3.141.59.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8187 Added minikube version 1.18.0.
  manifests/Kubernetes/minikube/1.18.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8186 Added Azure Functions Core Tools version 3.0.3331.
  manifests/Microsoft/AzureFunctionsCoreTools/3.0.3331.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8184 Added Zoom version 5.5.4.
  manifests/Zoom/Zoom/5.5.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8190 Add Glass Cannon
  manifests/ChristianAviBulan/GlassCannon/0.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8189 Added IntelliJ IDEA Education Edition version 2020.3.3.
  manifests/JetBrains/IntelliJIDEA/Edu/2020.3.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8188 Added Certify SSL Manager version 5.3.3.0.
  manifests/CertifyTheWeb/CertifySSLManager/5.3.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8191 Added Private Internet Access version 2.7.0.
  manifests/PrivateInternetAccess/PrivateInternetAccess/2.7.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8201 Update Discord.DiscordDevelopment to 1.0.581
  manifests/Discord/DiscordDevelopment/1.0.581.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8200 Update Discord.DiscordPTB to 1.0.1002
  manifests/Discord/DiscordPTB/1.0.1002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8199 Update Microsoft.OneDrive to 21.030.0211.0002
  manifests/Microsoft/OneDrive/21.030.0211.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8198 Update Microsoft.OneDriveInternalFast to 21.041.0228.0001
  manifests/Microsoft/OneDriveInternalFast/21.041.0228.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8197 Update OpenJS.NodeJSNightly to 16.0.0-20210302
  manifests/OpenJS/NodeJSNightly/16.0.0-20210302.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8195 Update Telerik.FiddlerEverywhereBeta to 10.1.0-beta
  manifests/Telerik/FiddlerEverywhereBeta/10.1.0-beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8193 Update VideoLAN.VLCNightly to 4.0.0-20210302
  manifests/VideoLAN/VLCNightly/4.0.0-20210302.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8192 Added Firefox Developer Edition version 87.0b4.
  manifests/Mozilla/FirefoxDeveloperEdition/87.0b4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8202 Update Discord.DiscordCanary to 1.0.24
  manifests/Discord/DiscordCanary/1.0.24.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8196 Update Oracle.VirtualBoxTest to 6.1.19-142995
  manifests/Oracle/VirtualBoxTest/6.1.19-142995.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8212 Microsoft.VisualStudioCodeInsiders-System-x64_v1.54.24.42e27fe5cd
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.54.24.42e27fe5cd.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8213 Microsoft.VisualStudioCodeInsiders-User-x86_v1.54.24.42e27fe5cd
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.54.24.42e27fe5cd.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8214 Microsoft.VisualStudioCodeInsiders-User-x64_v1.54.22.42e27fe5cd
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.54.22.42e27fe5cd.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8217 Microsoft.VisualStudioCodeInsiders-System-x86_v1.54.25.42e27fe5cd
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.54.25.42e27fe5cd.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#8207 pandoc-plot v1.1.0
  manifests/LaurentPRenedeCotret/pandoc-plot/1.1.0.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#7874 Added JetBrains dotUltimate version 2020.3.3.
  manifests/JetBrains/dotUltimate/2020.3.3.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#8224 Update MabelTerm From 1.4.3-Snap7 To 1.4.4-Snap2
  manifests/MabelisYT/MabelTermSnap/1.4.4-Snap2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8152 Added Visual Studio Professional version 16.8.31019.35.
  manifests/Microsoft/VisualStudio/Professional/16.8.31019.35.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#8223 Add Osu! 2021.302.0
  manifests/Peppy/Osu!/2021.302.0.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#8233 Update Discord.DiscordDevelopment to 1.0.582
  manifests/Discord/DiscordDevelopment/1.0.582.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8232 Update Microsoft.OneDriveInsiders to 21.036.0221.0001
  manifests/Microsoft/OneDriveInsiders/21.036.0221.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8231 Update Microsoft.OneDriveInternalFast to 21.042.0301.0001
  manifests/Microsoft/OneDriveInternalFast/21.042.0301.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8230 Update Microsoft.OneDriveInternalSlow to 21.041.0228.0001
  manifests/Microsoft/OneDriveInternalSlow/21.041.0228.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8229 Update VideoLAN.VLCNightly to 4.0.0-20210303
  manifests/VideoLAN/VLCNightly/4.0.0-20210303.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8228 Update TimKosse.FileZillaClientNightly to 3.52.2-20210303
  manifests/TimKosse/FileZillaClientNightly/3.52.2-20210303.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8227 Update OpenJS.NodeJS to 15.11.0
  manifests/OpenJS/NodeJS/15.11.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8226 Update OpenJS.NodeJSNightly to 16.0.0-20210303
  manifests/OpenJS/NodeJSNightly/16.0.0-20210303.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8225 PhonerLite 2.89.0
  manifests/Phoner/PhonerLite/2.89.0.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#8234 Update Discord.DiscordCanary to 1.0.25
  manifests/Discord/DiscordCanary/1.0.25.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8235 Fix Url for TablePlus.TablePlus
  manifests/TablePlus/TablePlus/3.12.19.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8237 Update elgato.streamdeck to 4.9.3.13222
  manifests/elgato/streamdeck/4.9.3.13222.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8238 Update StandardNotes.StandardNotes to 3.6.1
  manifests/StandardNotes/StandardNotes/3.6.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8244 Added AutoHotkey version 1.1.33.04.
  manifests/Lexikos/AutoHotkey/1.1.33.04.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8253 UTF-8: manifests\MongoDB\Compass\Community\1.21.2.yaml
  manifests/MongoDB/Compass/Community/1.21.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8255 UTF-8: manifests\MongoDB\Compass\Isolated\1.21.2.yaml
  manifests/MongoDB/Compass/Isolated/1.21.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8254 UTF-8: manifests\MongoDB\Compass\Full\1.21.2.yaml
  manifests/MongoDB/Compass/Full/1.21.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8337 UTF-8: manifests\Zettlr\Zettlr\1.6.0.yaml
  manifests/Zettlr/Zettlr/1.6.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8335 UTF-8: manifests\wandersick\AeroZoom\4.0.0.7.yaml
  manifests/wandersick/AeroZoom/4.0.0.7.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8334 UTF-8: manifests\VivaldiTechnologies\Vivaldi\3.0.1874.38.yaml
  manifests/VivaldiTechnologies/Vivaldi/3.0.1874.38.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8246 UTF-8: manifests\JetBrains\IntelliJIDEA\Edu\2020.3.3.yaml
  manifests/JetBrains/IntelliJIDEA/Edu/2020.3.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8333 UTF-8: manifests\TonyPottier\ImageView\2.0.0.yaml
  manifests/TonyPottier/ImageView/2.0.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8332 UTF-8: manifests\thomasnordquist\MQTT-Explorer\0.3.5.yaml
  manifests/thomasnordquist/MQTT-Explorer/0.3.5.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8331 UTF-8: manifests\TheHandBrakeTeam\HandBrake\1.3.2.yaml
  manifests/TheHandBrakeTeam/HandBrake/1.3.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8330 UTF-8: manifests\TGRMNSoftware\BulkRenameUtility\3.3.1.0.yaml
  manifests/TGRMNSoftware/BulkRenameUtility/3.3.1.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8329 UTF-8: manifests\TeXworks\TeXworks\0.6.5.yaml
  manifests/TeXworks/TeXworks/0.6.5.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8328 UTF-8: manifests\Texmaker\Texmaker\5.0.4.yaml
  manifests/Texmaker/Texmaker/5.0.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8327 UTF-8: manifests\TeraTermProject\TeraTerm\4.105.yaml
  manifests/TeraTermProject/TeraTerm/4.105.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8326 UTF-8: manifests\Streamlabs\StreamlabsOBS\0.27.1.yaml
  manifests/Streamlabs/StreamlabsOBS/0.27.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8323 UTF-8: manifests\SMPlayer\SMPlayer\20.4.2.yaml
  manifests/SMPlayer/SMPlayer/20.4.2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8321 UTF-8: manifests\Rustlang\rust-msvc\1.43.1.yaml
  manifests/Rustlang/rust-msvc/1.43.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8322 UTF-8: manifests\SaltStack\SaltMinion\3002.5.yaml
  manifests/SaltStack/SaltMinion/3002.5.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8319 UTF-8: manifests\RStudio\RStudio\1.3.959.yaml
  manifests/RStudio/RStudio/1.3.959.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8320 UTF-8: manifests\Rustlang\rust-gnu\1.43.1.yaml
  manifests/Rustlang/rust-gnu/1.43.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8318 UTF-8: manifests\Renode\Renode\1.9.0.yaml
  manifests/Renode/Renode/1.9.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8316 UTF-8: manifests\Postbox\Postbox\7.0.46.yaml
  manifests/Postbox/Postbox/7.0.46.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8315 UTF-8: manifests\Postbox\Postbox\7.0.18.yaml
  manifests/Postbox/Postbox/7.0.18.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8314 UTF-8: manifests\Plex\Plexamp\3.0.3.yaml
  manifests/Plex/Plexamp/3.0.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8313 UTF-8: manifests\PicoTorrent\PicoTorrent\0.20.0.yaml
  manifests/PicoTorrent/PicoTorrent/0.20.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8312 UTF-8: manifests\PicoTorrent\PicoTorrent\0.19.0.yaml
  manifests/PicoTorrent/PicoTorrent/0.19.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8311 UTF-8: manifests\PicoTorrent\PicoTorrent\0.18.0.yaml
  manifests/PicoTorrent/PicoTorrent/0.18.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8310 UTF-8: manifests\OSGeo\QGIS\3.14.0.yaml
  manifests/OSGeo/QGIS/3.14.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8309 UTF-8: manifests\OSGeo\QGIS\3.12.3.yaml
  manifests/OSGeo/QGIS/3.12.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8307 UTF-8: manifests\NagleCode\PacketSender\7.0.6.yaml
  manifests/NagleCode/PacketSender/7.0.6.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8306 UTF-8: manifests\NagleCode\PacketSender\7.0.5.yaml
  manifests/NagleCode/PacketSender/7.0.5.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8340 Add Microsoft.Bicep 0.3.1
  manifests/Microsoft/bicep/0.3.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8305 UTF-8: manifests\NagleCode\PacketSender\6.2.3.yaml
  manifests/NagleCode/PacketSender/6.2.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8304 UTF-8: manifests\Mu\Mu\1.0.3.yaml
  manifests/Mu/Mu/1.0.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8303 UTF-8: manifests\Mozilla\FirefoxDeveloperEdition\87.0b4.yaml
  manifests/Mozilla/FirefoxDeveloperEdition/87.0b4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8302 UTF-8: manifests\LyX\LyX\2.3.4.4.yaml
  manifests/LyX/LyX/2.3.4.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8338 UTF-8: manifests\Zoom\Zoom\5.5.4.yaml
  manifests/Zoom/Zoom/5.5.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8300 UTF-8: manifests\Microsoft\Edge\88.0.705.81.yaml
  manifests/Microsoft/Edge/88.0.705.81.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8298 UTF-8: manifests\Microsoft\Teams\1.4.00.4167.yaml
  manifests/Microsoft/Teams/1.4.00.4167.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8299 UTF-8: manifests\Microsoft\EdgeBeta\89.0.774.39.yaml
  manifests/Microsoft/EdgeBeta/89.0.774.39.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8296 UTF-8: manifests\MIT\CertAid\2.2.6.yaml
  manifests/MIT/CertAid/2.2.6.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8293 UTF-8: manifests\MonoGame\MonoGame\3.7.1.0.yaml
  manifests/MonoGame/MonoGame/3.7.1.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8292 UTF-8: manifests\Mozilla\FirefoxDeveloperEdition\87.0b2.yaml
  manifests/Mozilla/FirefoxDeveloperEdition/87.0b2.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8289 UTF-8: manifests\Krisp\Krisp\1.14.3.yaml
  manifests/Krisp/Krisp/1.14.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8285 UTF-8: manifests\JohnMacFarlane\Pandoc\2.9.2.1.yaml
  manifests/JohnMacFarlane/Pandoc/2.9.2.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8286 UTF-8: manifests\Joplin\Joplin\1.0.216.yaml
  manifests/Joplin/Joplin/1.0.216.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8349 Added Visual Studio Test Agent version 16.9.31025.194.
  manifests/Microsoft/VisualStudio/TestAgent/16.9.31025.194.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8284 UTF-8: manifests\IsWiX\IsWiX\4.14.5.yaml
  manifests/IsWiX/IsWiX/4.14.5.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8283 UTF-8: manifests\isaaclevin\presencelight\2.0.49.yaml
  manifests/isaaclevin/presencelight/2.0.49.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8281 UTF-8: manifests\Google\IAPDesktop\2.12.511.yaml
  manifests/Google/IAPDesktop/2.12.511.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8280 UTF-8: manifests\Gauge\Gauge\1.0.6.yaml
  manifests/Gauge/Gauge/1.0.6.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8279 UTF-8: manifests\Files-UWP\FilesUWP\0.9.1.yaml
  manifests/Files-UWP/FilesUWP/0.9.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8348 Added Visual Studio Build Tools version 16.9.31025.194.
  manifests/Microsoft/VisualStudio/BuildTools/16.9.31025.194.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8278 UTF-8: manifests\Files-UWP\FilesUWP\0.9.0.yaml
  manifests/Files-UWP/FilesUWP/0.9.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8277 UTF-8: manifests\Files-UWP\FilesUWP\0.8.2.0.yaml
  manifests/Files-UWP/FilesUWP/0.8.2.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8274 UTF-8: manifests\DasKeyboard\DasKeyboard\3.2.6.yaml
  manifests/DasKeyboard/DasKeyboard/3.2.6.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8272 UTF-8: manifests\CompuPhase\Termite\3.4.yaml
  manifests/CompuPhase/Termite/3.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8271 UTF-8: manifests\CodeLite\CodeLite\14.0.0.yaml
  manifests/CodeLite/CodeLite/14.0.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8347 Added Visual Studio Enterprise version 16.9.31025.194.
  manifests/Microsoft/VisualStudio/Enterprise/16.9.31025.194.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8270 UTF-8: manifests\CertifyTheWeb\CertifySSLManager\5.3.3.0.yaml
  manifests/CertifyTheWeb/CertifySSLManager/5.3.3.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8273 UTF-8: manifests\Couchbase\ServerEnterprise\6.6.9213.yaml
  manifests/Couchbase/ServerEnterprise/6.6.9213.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8269 UTF-8: manifests\CertifyTheWeb\CertifySSLManager\5.3.2.0.yaml
  manifests/CertifyTheWeb/CertifySSLManager/5.3.2.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8268 UTF-8: manifests\canonical\Multipass\1.2.1.yaml
  manifests/canonical/Multipass/1.2.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8266 UTF-8: manifests\calibre\calibre\5.12.0.yaml
  manifests/calibre/calibre/5.12.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8265 UTF-8: manifests\calibre\calibre\4.19.0.yaml
  manifests/calibre/calibre/4.19.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8264 UTF-8: manifests\calibre\calibre\4.18.0.yaml
  manifests/calibre/calibre/4.18.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8263 UTF-8: manifests\BraveSoftware\BraveBrowser\1.21.70.yaml
  manifests/BraveSoftware/BraveBrowser/1.21.70.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8261 UTF-8: manifests\BraveSoftware\BraveBrowser\1.21.68.yaml
  manifests/BraveSoftware/BraveBrowser/1.21.68.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8262 UTF-8: manifests\BraveSoftware\BraveBrowser\1.21.69.yaml
  manifests/BraveSoftware/BraveBrowser/1.21.69.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8260 UTF-8: manifests\Bonnefon\Glogg\1.1.4.yaml
  manifests/Bonnefon/Glogg/1.1.4.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8259 UTF-8: manifests\BlueJeans\BlueJeans\2.26.436.0.yaml
  manifests/BlueJeans/BlueJeans/2.26.436.0.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8257 UTF-8: manifests\3T\Robo3T\1.4.3.yaml
  manifests/3T/Robo3T/1.4.3.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#8287 UTF-8: manifests\KKBOX\KKBOX\7.2.30.yaml
  manifests/KKBOX/KKBOX/7.2.30.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Needs: Attention, Validation-Completed

#8245 Added GitHub Desktop version 2.6.4.
  manifests/GitHub/GitHubDesktop/2.6.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#8240 Update Firetrust.MailWasherPro to 7.12.53
  manifests/Firetrust/MailWasherPro/7.12.53.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
