Repository microsoft/winget-pkgs, pull requests merged in 2021-05, with the labels that each got.

#11814 Added Microsoft Edge Beta version 91.0.864.11.
  manifests/m/Microsoft/EdgeBeta/91.0.864.11/Microsoft.EdgeBeta.installer.yaml
  manifests/m/Microsoft/EdgeBeta/91.0.864.11/Microsoft.EdgeBeta.locale.en-US.yaml
  manifests/m/Microsoft/EdgeBeta/91.0.864.11/Microsoft.EdgeBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11816 Added KDE Connect version 1.4.574.
  manifests/k/KDE/KDEConnect/1.4.574/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11815 Added Microsoft Edge Dev version 92.0.873.1.
  manifests/m/Microsoft/EdgeDev/92.0.873.1/Microsoft.EdgeDev.installer.yaml
  manifests/m/Microsoft/EdgeDev/92.0.873.1/Microsoft.EdgeDev.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDev/92.0.873.1/Microsoft.EdgeDev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11817 Microsoft.VisualStudioCode.Insiders_v1.56.8.4e185d8986
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.56.8.4e185d8986/Microsoft.VisualStudioCode.Insiders.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.56.8.4e185d8986/Microsoft.VisualStudioCode.Insiders.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.56.8.4e185d8986/Microsoft.VisualStudioCode.Insiders.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#11780 Added Octopus Tentacle version 6.0.599.
  manifests/o/OctopusDeploy/Tentacle/6.0.599/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.599/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.599/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#11791 Updated Spotify to version 1.1.58.820
  manifests/s/Spotify/Spotify/latest/Spotify.Spotify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11793 Added Jackett version 0.17.963.
  manifests/j/Jackett/Jackett/0.17.963/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11822 Added KDE Connect version 1.4.575.
  manifests/k/KDE/KDEConnect/1.4.575/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11821 Added PostgreSQL version 12.6.3.
  manifests/p/PostgreSQL/PostgreSQL/12.6.3/PostgreSQL.PostgreSQL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11820 Added Brave Browser version 1.24.82.
  manifests/b/BraveSoftware/BraveBrowser/1.24.82/BraveSoftware.BraveBrowser.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/1.24.82/BraveSoftware.BraveBrowser.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/1.24.82/BraveSoftware.BraveBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11819 Added Jackett version 0.17.966.
  manifests/j/Jackett/Jackett/0.17.966/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#11831 Added WebStorm version 2021.1.1.
  manifests/j/JetBrains/WebStorm/2021.1.1/JetBrains.WebStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11830 Added PHPStorm version 2021.1.2.
  manifests/j/JetBrains/PHPStorm/2021.1.2/JetBrains.PHPStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11829 Added IntelliJ IDEA Ultimate Edition version 2021.1.1.
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/2021.1.1/JetBrains.IntelliJIDEA.Ultimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11828 Added IntelliJ IDEA Community Edition version 2021.1.1.
  manifests/j/JetBrains/IntelliJIDEA/Community/2021.1.1/JetBrains.IntelliJIDEA.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11827 Added AWS Command Line Interface v2 version 2.2.1.
  manifests/a/Amazon/AWSCLI/2.2.1/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11826 Added Grafana Open Source version 7.5.5.
  manifests/g/GrafanaLabs/GrafanaOSS/7.5.5/GrafanaLabs.GrafanaOSS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11825 Added Grafana Enterprise version 7.5.5.
  manifests/g/GrafanaLabs/GrafanaEnterprise/7.5.5/GrafanaLabs.GrafanaEnterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11824 Added IAP Desktop version 2.16.595.
  manifests/g/Google/IAPDesktop/2.16.595/Google.IAPDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11823 Added Google Chrome Dev version 92.0.4491.6.
  manifests/g/Google/ChromeDev/92.0.4491.6/Google.ChromeDev.installer.yaml
  manifests/g/Google/ChromeDev/92.0.4491.6/Google.ChromeDev.locale.en-US.yaml
  manifests/g/Google/ChromeDev/92.0.4491.6/Google.ChromeDev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11833 Added ZeroTier version 1.6.5.0.
  manifests/z/zerotier/zerotier/1.6.5.0/zerotier.zerotier.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11832 Added Primecount version 7.0
  manifests/p/Primecount/Primecount/7.0/Primecount.Primecount.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11840 Manifest Update for OpenVPNTechnologies.OpenVPN v.2.5.2
  manifests/o/OpenVPNTechnologies/OpenVPN/2.5.2/OpenVPNTechnologies.OpenVPN.installer.yaml
  manifests/o/OpenVPNTechnologies/OpenVPN/2.5.2/OpenVPNTechnologies.OpenVPN.locale.en-US.yaml
  manifests/o/OpenVPNTechnologies/OpenVPN/2.5.2/OpenVPNTechnologies.OpenVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11851 Update TimKosse.FileZillaClientNightly to 3.53.1-20210501
  manifests/t/TimKosse/FileZillaClientNightly/3.53.1-20210501/TimKosse.FileZillaClientNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11850 Update Microsoft.TeamsContinuousDeployment to 1.4.00.12169
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.12169/Microsoft.TeamsContinuousDeployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11849 Update GitHub.GitHubDesktopBeta to 2.8.1-beta2
  manifests/g/GitHub/GitHubDesktopBeta/2.8.1-beta2/GitHub.GitHubDesktopBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11848 Update OpenJS.NodeJSNightly to 17.0.0-20210501
  manifests/o/OpenJS/NodeJSNightly/17.0.0-20210501/OpenJS.NodeJSNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11847 Update Zoom.Zoom to 5.6.5
  manifests/z/Zoom/Zoom/5.6.5/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11846 Update VideoLAN.VLC to 3.0.13
  manifests/v/VideoLAN/VLC/3.0.13/VideoLAN.VLC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11845 Update Microsoft.OneDriveInternalFast to 21.087.0429.0001
  manifests/m/Microsoft/OneDriveInternalFast/21.087.0429.0001/Microsoft.OneDriveInternalFast.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11844 Update Microsoft.TeamsExploration to 1.4.00.12119
  manifests/m/Microsoft/TeamsExploration/1.4.00.12119/Microsoft.TeamsExploration.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11842 Update Microsoft.OneDriveInternalSlow to 21.083.0425.0001
  manifests/m/Microsoft/OneDriveInternalSlow/21.083.0425.0001/Microsoft.OneDriveInternalSlow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11843 Update Oracle.VirtualBoxTest to 6.1.21-144078
  manifests/o/Oracle/VirtualBoxTest/6.1.21-144078/Oracle.VirtualBoxTest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11841 Update Microsoft.OneDrive to 21.073.0411.0002
  manifests/m/Microsoft/OneDrive/21.073.0411.0002/Microsoft.OneDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11858 Add hello-efficiency-inc.raven-reader v1.0.51
  manifests/h/hello-efficiency-inc/raven-reader/1.0.51/hello-efficiency-inc.raven-reader.installer.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.51/hello-efficiency-inc.raven-reader.locale.en-US.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.51/hello-efficiency-inc.raven-reader.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#11860 Manifest Update for XnSoft.XnViewMP v0.98.2
  manifests/x/XnSoft/XnViewMP/0.98.2/XnSoft.XnViewMP.installer.yaml
  manifests/x/XnSoft/XnViewMP/0.98.2/XnSoft.XnViewMP.locale.en-US.yaml
  manifests/x/XnSoft/XnViewMP/0.98.2/XnSoft.XnViewMP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11859 Add XnSoft.XnViewClassic v2.50
  manifests/x/XnSoft/XnViewClassic/2.50/XnSoft.XnViewClassic.installer.yaml
  manifests/x/XnSoft/XnViewClassic/2.50/XnSoft.XnViewClassic.locale.en-US.yaml
  manifests/x/XnSoft/XnViewClassic/2.50/XnSoft.XnViewClassic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11861 Manifest Update for IrfanSkiljan.IrfanView v4.57
  manifests/i/IrfanSkiljan/IrfanView/4.57/IrfanSkiljan.IrfanView.installer.yaml
  manifests/i/IrfanSkiljan/IrfanView/4.57/IrfanSkiljan.IrfanView.locale.en-US.yaml
  manifests/i/IrfanSkiljan/IrfanView/4.57/IrfanSkiljan.IrfanView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11862 Add CCleaner 5.79.8704
  manifests/p/Piriform/CCleaner/5.79.8704/Piriform.CCleaner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11857 Manifest Update for yang991178.fluent-reader v1.0.0
  manifests/y/yang991178/fluent-reader/1.0.0/yang991178.fluent-reader.installer.yaml
  manifests/y/yang991178/fluent-reader/1.0.0/yang991178.fluent-reader.locale.en-US.yaml
  manifests/y/yang991178/fluent-reader/1.0.0/yang991178.fluent-reader.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#11446 Added dotUltimate version 2021.1.2.
  manifests/j/JetBrains/dotUltimate/2021.1.2/JetBrains.dotUltimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11869 Added Octopus Tentacle version 6.0.603.
  manifests/o/OctopusDeploy/Tentacle/6.0.603/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.603/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.603/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11868 Added vim version 8.2.2820.
  manifests/v/vim/vim/8.2.2820/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.2820/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.2820/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11867 Add autoit version 3.3.14.5
  manifests/a/AutoIt/AutoIt/3.3.14.5/AutoIt.AutoIt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11866 Mono6.8.0.72
  manifests/m/Mono/Mono/6.8.0.72/Mono.Mono.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11878 Added Pidgin IM version 2.14.4.
  manifests/p/Pidgin/Pidgin/2.14.4/Pidgin.Pidgin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11877 Added Handbrake.Handbrake version 1.3.2.
  manifests/h/HandBrake/HandBrake/1.3.2/HandBrake.HandBrake.installer.yaml
  manifests/h/HandBrake/HandBrake/1.3.2/HandBrake.HandBrake.locale.en-US.yaml
  manifests/h/HandBrake/HandBrake/1.3.2/HandBrake.HandBrake.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11864 Diladele Web Filtering Proxy 1.1.0
  manifests/d/Diladele/WebProxy/1.1.0/Diladele.WebProxy.installer.yaml
  manifests/d/Diladele/WebProxy/1.1.0/Diladele.WebProxy.locale.en-US.yaml
  manifests/d/Diladele/WebProxy/1.1.0/Diladele.WebProxy.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Validation-Completed

#11876 Fixed Publisher for HandBrake version 1.3.3.
  manifests/h/HandBrake/HandBrake/1.3.3/HandBrake.HandBrake.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11873 Added RubyMine version 2021.1.1.
  manifests/j/JetBrains/RubyMine/2021.1.1/JetBrains.RubyMine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11872 Add VivaldiTechnologies.Vivaldi v3.8.2259.37
  manifests/v/VivaldiTechnologies/Vivaldi/3.8.2259.37/VivaldiTechnologies.Vivaldi.installer.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/3.8.2259.37/VivaldiTechnologies.Vivaldi.locale.en-US.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/3.8.2259.37/VivaldiTechnologies.Vivaldi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11871 Added Jackett version 0.17.972.
  manifests/j/Jackett/Jackett/0.17.972/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11870 Added KDE Connect version 1.4.576.
  manifests/k/KDE/KDEConnect/1.4.576/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11875 Removed duplicate manifest for Handbrake version 1.3.2.
  manifests/t/thehandbraketeam/handbrake/1.3.2/thehandbraketeam.handbrake.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11874 Removed duplicate manifest for Handbrake 1.3.3.
  manifests/t/thehandbraketeam/handbrake/1.3.3/thehandbraketeam.handbrake.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11880 Update Microsoft.TeamsContinuousDeployment to 1.4.00.12266
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.12266/Microsoft.TeamsContinuousDeployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11882 Update TimKosse.FileZillaClientNightly to 3.53.1-20210502
  manifests/t/TimKosse/FileZillaClientNightly/3.53.1-20210502/TimKosse.FileZillaClientNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11879 Dolt 0.26.2
  manifests/d/DoltHub/Dolt/0.26.2/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11883 Update OpenJS.NodeJSNightly to 17.0.0-20210502
  manifests/o/OpenJS/NodeJSNightly/17.0.0-20210502/OpenJS.NodeJSNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11881 Update Microsoft.TeamsExploration to 1.4.00.12216
  manifests/m/Microsoft/TeamsExploration/1.4.00.12216/Microsoft.TeamsExploration.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11894 Add Osu! 2021.502.0
  manifests/p/Peppy/Osu!/2021.502.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11897 music 1.3.1
  manifests/s/sunzongzheng/music/1.3.1/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11899 music 1.0.11
  manifests/s/sunzongzheng/music/1.0.11/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11900 music 1.0.12
  manifests/s/sunzongzheng/music/1.0.12/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11898 music 1.0.10
  manifests/s/sunzongzheng/music/1.0.10/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11901 Add qbittorrent 4.3.5
  manifests/q/qBittorrent/qBittorrent/4.3.5/qBittorrent.qBittorrent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11903 Add ProtonTechnologies.ProtonVPN v1.20.3
  manifests/p/ProtonTechnologies/ProtonVPN/1.20.3/ProtonTechnologies.ProtonVPN.installer.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/1.20.3/ProtonTechnologies.ProtonVPN.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/1.20.3/ProtonTechnologies.ProtonVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11904 Add dbeaver 21.0.4
  manifests/d/dbeaver/dbeaver/21.0.4/dbeaver.dbeaver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11907 Added Shotcut version 21.05.01.
  manifests/m/Meltytech/Shotcut/21.05.01/Meltytech.Shotcut.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11906 NVDA 2020.4
  manifests/n/NVAccess/NVDA/2020.4/NVAccess.NVDA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11905 Added Jackett version 0.17.996.
  manifests/j/Jackett/Jackett/0.17.996/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11909 Added Octopus Tentacle version 6.0.604.
  manifests/o/OctopusDeploy/Tentacle/6.0.604/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.604/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.0.604/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11908 Added Docker Desktop version 3.3.2.63878.
  manifests/d/Docker/DockerDesktop/3.3.2.63878/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11910 Added KDE Connect version 1.4.577.
  manifests/k/KDE/KDEConnect/1.4.577/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11911 Added x86 architecture for Google Chrome Beta version 68.94.27.
  manifests/g/Google/ChromeBeta/68.94.27/Google.ChromeBeta.installer.yaml
  manifests/g/Google/ChromeBeta/68.94.27/Google.ChromeBeta.locale.en-US.yaml
  manifests/g/Google/ChromeBeta/68.94.27/Google.ChromeBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11912 Manifest Update for qBittorrent.qBittorrent v4.3.5
  manifests/q/qBittorrent/qBittorrent/4.3.5/qBittorrent.qBittorrent.installer.yaml
  manifests/q/qBittorrent/qBittorrent/4.3.5/qBittorrent.qBittorrent.locale.en-US.yaml
  manifests/q/qBittorrent/qBittorrent/4.3.5/qBittorrent.qBittorrent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11915 Add Datronicsoft.SpacedeskDriver.Client v0.9.1015.0
  manifests/d/Datronicsoft/SpacedeskDriver/Client/0.9.1015.0/Datronicsoft.SpacedeskDriver.Client.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Client/0.9.1015.0/Datronicsoft.SpacedeskDriver.Client.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Client/0.9.1015.0/Datronicsoft.SpacedeskDriver.Client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11914 Add Datronicsoft.SpacedeskDriver.Server v0.9.1077.0
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1077.0/Datronicsoft.SpacedeskDriver.Server.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1077.0/Datronicsoft.SpacedeskDriver.Server.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1077.0/Datronicsoft.SpacedeskDriver.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11917 Removing old Visual Studio Code manifests
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.52.1.ea3859d4ba/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.53.0.8490d3dde4/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.53.1.5d424b828a/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.53.2.622cb03f7e/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.54.0.42e27fe5cd/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.54.1.f30a9b73e8/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.54.2.fd6f3bce67/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x64/1.54.3.2b9aebd535/Microsoft.VisualStudioCode.System-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.52.1.ea3859d4ba/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.53.0.8490d3dde4/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.53.1.5d424b828a/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.53.2.622cb03f7e/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.54.0.42e27fe5cd/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.54.1.f30a9b73e8/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.54.2.fd6f3bce67/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/System-x86/1.54.3.2b9aebd535/Microsoft.VisualStudioCode.System-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.52.1.ea3859d4ba/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.53.0.8490d3dde4/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.53.1.5d424b828a/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.53.2.622cb03f7e/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.54.0.42e27fe5cd/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.54.1.f30a9b73e8/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.54.2.fd6f3bce67/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x64/1.54.3.2b9aebd535/Microsoft.VisualStudioCode.User-x64.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.52.1.ea3859d4ba/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.53.0.8490d3dde4/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.53.1.5d424b828a/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.53.2.622cb03f7e/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.54.0.42e27fe5cd/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.54.1.f30a9b73e8/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.54.2.fd6f3bce67/Microsoft.VisualStudioCode.User-x86.yaml
  manifests/m/Microsoft/VisualStudioCode/User-x86/1.54.3.2b9aebd535/Microsoft.VisualStudioCode.User-x86.yaml
Labels: Needs: Attention, PullRequest-Error

#11919 Add Microsoft.Office v16.0.13929.20296
  manifests/m/Microsoft/Office/16.0.13929.20296/Microsoft.Office.installer.yaml
  manifests/m/Microsoft/Office/16.0.13929.20296/Microsoft.Office.locale.en-US.yaml
  manifests/m/Microsoft/Office/16.0.13929.20296/Microsoft.Office.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11922 Added WebEx Teams version 41.4.0.18629.
  manifests/c/Cisco/WebexTeams/41.4.0.18629/Cisco.WebexTeams.installer.yaml
  manifests/c/Cisco/WebexTeams/41.4.0.18629/Cisco.WebexTeams.locale.en-US.yaml
  manifests/c/Cisco/WebexTeams/41.4.0.18629/Cisco.WebexTeams.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11935 music 1.0.16
  manifests/s/sunzongzheng/music/1.0.16/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11932 music 1.0.14
  manifests/s/sunzongzheng/music/1.0.14/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11934 music 1.0.15
  manifests/s/sunzongzheng/music/1.0.15/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11931 music 1.0.13
  manifests/s/sunzongzheng/music/1.0.13/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11936 music 1.0.17
  manifests/s/sunzongzheng/music/1.0.17/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11925 Added Microsoft Edge Beta version 91.0.864.15.
  manifests/m/Microsoft/EdgeBeta/91.0.864.15/Microsoft.EdgeBeta.installer.yaml
  manifests/m/Microsoft/EdgeBeta/91.0.864.15/Microsoft.EdgeBeta.locale.en-US.yaml
  manifests/m/Microsoft/EdgeBeta/91.0.864.15/Microsoft.EdgeBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11937 music 1.0.18
  manifests/s/sunzongzheng/music/1.0.18/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11938 music 1.0.19
  manifests/s/sunzongzheng/music/1.0.19/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11939 music 1.0.22
  manifests/s/sunzongzheng/music/1.0.22/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11940 music 1.0.24
  manifests/s/sunzongzheng/music/1.0.24/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11941 music 1.0.25
  manifests/s/sunzongzheng/music/1.0.25/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11942 music 1.1.0
  manifests/s/sunzongzheng/music/1.1.0/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11943 music 1.1.1
  manifests/s/sunzongzheng/music/1.1.1/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11944 music 1.1.10
  manifests/s/sunzongzheng/music/1.1.10/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11945 music 1.1.11
  manifests/s/sunzongzheng/music/1.1.11/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11946 music 1.1.2
  manifests/s/sunzongzheng/music/1.1.2/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11947 music 1.1.3
  manifests/s/sunzongzheng/music/1.1.3/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11948 music 1.1.4
  manifests/s/sunzongzheng/music/1.1.4/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11949 music 1.1.5
  manifests/s/sunzongzheng/music/1.1.5/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11950 sunzongzheng.music 1.1.6
  manifests/s/sunzongzheng/music/1.1.6/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11951 sunzongzheng.music 1.1.7
  manifests/s/sunzongzheng/music/1.1.7/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11952 sunzongzheng.music 1.1.8
  manifests/s/sunzongzheng/music/1.1.8/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11953 sunzongzheng.music 1.1.9
  manifests/s/sunzongzheng/music/1.1.9/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11954 sunzongzheng.music 1.2.0
  manifests/s/sunzongzheng/music/1.2.0/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11955 sunzongzheng.music 1.3.0
  manifests/s/sunzongzheng/music/1.3.0/sunzongzheng.music.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11956 GitHub.GitLFS 2.10.0
  manifests/g/GitHub/GitLFS/2.10.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11959 GitHub.GitLFS 2.12.0
  manifests/g/GitHub/GitLFS/2.12.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11958 Markdown Monster 1.27.2
  manifests/w/WestWind/MarkdownMonster/1.27.2/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11960 GitHub.GitLFS 2.12.1
  manifests/g/GitHub/GitLFS/2.12.1/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11961 GitHub.GitLFS 2.13.1
  manifests/g/GitHub/GitLFS/2.13.1/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11962 GitHub.GitLFS 2.13.3
  manifests/g/GitHub/GitLFS/2.13.3/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11963 GitHub.GitLFS 2.6.0
  manifests/g/GitHub/GitLFS/2.6.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11965 GitHub.GitLFS 2.5.1
  manifests/g/GitHub/GitLFS/2.5.1/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11966 GitHub.GitLFS 2.5.0
  manifests/g/GitHub/GitLFS/2.5.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11968 GitHub.GitLFS 2.7.0
  manifests/g/GitHub/GitLFS/2.7.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11969 GitHub.GitLFS 2.7.1
  manifests/g/GitHub/GitLFS/2.7.1/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11970 GitHub.GitLFS 2.7.2
  manifests/g/GitHub/GitLFS/2.7.2/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11971 GitHub.GitLFS 2.8.0
  manifests/g/GitHub/GitLFS/2.8.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11972 GitHub.GitLFS 2.9.0
  manifests/g/GitHub/GitLFS/2.9.0/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11974 GitHub.GitLFS 2.9.2
  manifests/g/GitHub/GitLFS/2.9.2/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11976 Add c0re100.qBittorrent-Enhanced-Edition v4.3.5.10
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.5.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.5.10/c0re100.qBittorrent-Enhanced-Edition.locale.en-US.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.5.10/c0re100.qBittorrent-Enhanced-Edition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11977 Add MoonlightGameStreamingProject.Moonlight v3.1.2.0
  manifests/m/MoonlightGameStreamingProject/Moonlight/3.1.2.0/MoonlightGameStreamingProject.Moonlight.installer.yaml
  manifests/m/MoonlightGameStreamingProject/Moonlight/3.1.2.0/MoonlightGameStreamingProject.Moonlight.locale.en-US.yaml
  manifests/m/MoonlightGameStreamingProject/Moonlight/3.1.2.0/MoonlightGameStreamingProject.Moonlight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11978 Add ApacheFriends.Xampp v8.0.5-0
  manifests/a/ApacheFriends/Xampp/8.0.5-0/ApacheFriends.Xampp.installer.yaml
  manifests/a/ApacheFriends/Xampp/8.0.5-0/ApacheFriends.Xampp.locale.en-US.yaml
  manifests/a/ApacheFriends/Xampp/8.0.5-0/ApacheFriends.Xampp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11980 Microsoft.AccessibilityInsightsWindows 1.1.1562.01
  manifests/m/Microsoft/AccessibilityInsightsWindows/1.1.1562.01/Microsoft.AccessibilityInsightsWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11981 Add TeamViewer.TeamViewer v15.17.7
  manifests/t/TeamViewer/TeamViewer/15.17.7/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.17.7/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.17.7/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11983 Added Jackett version 0.17.1006.
  manifests/j/Jackett/Jackett/0.17.1006/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11985 Added Python version 3.9.5.
  manifests/p/Python/Python/3.9.5/Python.Python.installer.yaml
  manifests/p/Python/Python/3.9.5/Python.Python.locale.en-US.yaml
  manifests/p/Python/Python/3.9.5/Python.Python.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11987 Added KDE Connect version 1.4.578.
  manifests/k/KDE/KDEConnect/1.4.578/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11988 Added vim version 8.2.2831.
  manifests/v/vim/vim/8.2.2831/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.2831/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.2831/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11992 Removed duplicate manifest for WizTree version 3.37.
  manifests/a/AntibodySoftware/WizTree/latest/AntibodySoftware.WizTree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11986 Resolved formatting errors for Python version 3.9.4150.0.
  manifests/p/Python/Python/3.9.4150.0/Python.Python.installer.yaml
  manifests/p/Python/Python/3.9.4150.0/Python.Python.locale.en-US.yaml
  manifests/p/Python/Python/3.9.4150.0/Python.Python.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11993 Added Firefox Developer Edition version 89.0b7.
  manifests/m/Mozilla/FirefoxDeveloperEdition/89.0b7/Mozilla.FirefoxDeveloperEdition.installer.yaml
  manifests/m/Mozilla/FirefoxDeveloperEdition/89.0b7/Mozilla.FirefoxDeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/FirefoxDeveloperEdition/89.0b7/Mozilla.FirefoxDeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11984 Added GeoGebra CAS Calculator version 6.0.640.0.
  manifests/g/GeoGebra/GeoGebraCASCalculator/6.0.640.0/GeoGebra.GeoGebraCASCalculator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11982 Tunnelbear
  manifests/t/TunnelBear/TunnelBear/4.4.2.0/TunnelBear.TunnelBear.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11999 Update Microsoft.OneDriveInternalFast to 21.088.0502.0001
  manifests/m/Microsoft/OneDriveInternalFast/21.088.0502.0001/Microsoft.OneDriveInternalFast.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11995 Update OpenJS.NodeJS to 16.1.0
  manifests/o/OpenJS/NodeJS/16.1.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11998 Update OpenJS.NodeJSNightly to 17.0.0-20210504
  manifests/o/OpenJS/NodeJSNightly/17.0.0-20210504/OpenJS.NodeJSNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11997 Update Microsoft.TeamsContinuousDeployment to 1.4.00.12457
  manifests/m/Microsoft/TeamsContinuousDeployment/1.4.00.12457/Microsoft.TeamsContinuousDeployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12000 Update Zulip.Zulip to 5.7.0
  manifests/z/Zulip/Zulip/5.7.0/Zulip.Zulip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11994 Update TimKosse.FileZillaClientNightly to 3.53.1-20210504
  manifests/t/TimKosse/FileZillaClientNightly/3.53.1-20210504/TimKosse.FileZillaClientNightly.yaml
Labels: Azure-Pipeline-Passed, Internal-Error-Keyword-Policy, Validation-Completed

#12001 Update h3poteto.whalebird-desktop to 4.4.0
  manifests/h/h3poteto/whalebird-desktop/4.4.0/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12003 Change from binary file to UTF-8 for TunnelBear.TunnelBear
  manifests/t/TunnelBear/TunnelBear/4.4.2.0/TunnelBear.TunnelBear.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#11973 GitHub.GitLFS 2.9.1
  manifests/g/GitHub/GitLFS/2.9.1/GitHub.GitLFS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12005 Delete TeamViewer.TeamViewer latest
  manifests/t/TeamViewer/TeamViewer/latest/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12007 Add Lens 4.2.4
  manifests/m/Mirantis/Lens/4.2.4/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12010 404 Not Found: manifests\l\LutzRoeder\Netron\4.8.9\LutzRoeder.Netron.yaml
  manifests/l/LutzRoeder/Netron/4.8.9/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12014 404 Not Found: manifests\i\ImageMagick\ImageMagick\7.0.11-9\ImageMagick.ImageMagick.yaml
  manifests/i/ImageMagick/ImageMagick/7.0.11-9/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.0.11-9/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.0.11-9/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12018 404 Not Found: manifests\t\TimKosse\FileZillaClientNightly\3.53.1-20210426\TimKosse.FileZillaClientNightly.yaml
  manifests/t/TimKosse/FileZillaClientNightly/3.53.1-20210426/TimKosse.FileZillaClientNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#12009 404 Not Found: manifests\l\LMMS\LMMSNightly\1.3.0\LMMS.LMMSNightly.yaml
  manifests/l/LMMS/LMMSNightly/1.3.0/LMMS.LMMSNightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
