Repository microsoft/winget-pkgs, pull requests merged in 2021-09, with the labels that each got.

#26510 New version: HearthSim.HearthstoneDeckTracker version 1.15.3
  manifests/h/HearthSim/HearthstoneDeckTracker/1.15.3/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.15.3/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.15.3/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26508 New version: c0re100.qBittorrent-Enhanced-Edition version 4.3.8.10
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.8.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.8.10/c0re100.qBittorrent-Enhanced-Edition.locale.en-US.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.3.8.10/c0re100.qBittorrent-Enhanced-Edition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26504 SmartSoft.SmartFTP version 10.0.2910.0
  manifests/s/SmartSoft/SmartFTP/10.0.2910.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26496 New version: CameronSutter.Plottr version 2021.8.31
  manifests/c/CameronSutter/Plottr/2021.8.31/CameronSutter.Plottr.installer.yaml
  manifests/c/CameronSutter/Plottr/2021.8.31/CameronSutter.Plottr.locale.en-US.yaml
  manifests/c/CameronSutter/Plottr/2021.8.31/CameronSutter.Plottr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26507 New version: DoltHub.Dolt version 0.28.1
  manifests/d/DoltHub/Dolt/0.28.1/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.28.1/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.28.1/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26512 Added KDE.KDEConnect version 21.08.0.700
  manifests/k/KDE/KDEConnect/21.08.0.700/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.08.0.700/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.08.0.700/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26511 Added KDE.KDEConnect version 21.08.0.699
  manifests/k/KDE/KDEConnect/21.08.0.699/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.08.0.699/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.08.0.699/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26532 Microsoft.VisualStudioCode.Insiders_v1.60.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.60.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26520 Added Microsoft Edge Dev version 95.0.997.1.
  manifests/m/Microsoft/EdgeDev/95.0.997.1/Microsoft.EdgeDev.installer.yaml
  manifests/m/Microsoft/EdgeDev/95.0.997.1/Microsoft.EdgeDev.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDev/95.0.997.1/Microsoft.EdgeDev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26518 Added Node.js LTS version 14.17.6.
  manifests/o/OpenJS/NodeJSLTS/14.17.6/OpenJS.NodeJSLTS.installer.yaml
  manifests/o/OpenJS/NodeJSLTS/14.17.6/OpenJS.NodeJSLTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJSLTS/14.17.6/OpenJS.NodeJSLTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26534 Update: Sogou.SogouInput version 11.1.0.5032
  manifests/s/Sogou/SogouInput/11.1.0.5032/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/11.1.0.5032/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/11.1.0.5032/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/11.1.0.5032/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26540 Moving: alibaba.Teambition version 2.0.0
  manifests/a/alibaba/Teambition/2.0.0/alibaba.Teambition.installer.yaml
  manifests/a/alibaba/Teambition/2.0.0/alibaba.Teambition.locale.en-US.yaml
  manifests/a/alibaba/Teambition/2.0.0/alibaba.Teambition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26539 Moving: alibaba.DingTalkLite version 5.1.21-Release.516
  manifests/a/alibaba/DingTalkLite/5.1.21-Release.516/alibaba.DingTalkLite.installer.yaml
  manifests/a/alibaba/DingTalkLite/5.1.21-Release.516/alibaba.DingTalkLite.locale.en-US.yaml
  manifests/a/alibaba/DingTalkLite/5.1.21-Release.516/alibaba.DingTalkLite.locale.zh-CN.yaml
  manifests/a/alibaba/DingTalkLite/5.1.21-Release.516/alibaba.DingTalkLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26537 Moving: baidu.BaiduPinyin version 5.6.5624.0
  manifests/b/baidu/BaiduPinyin/5.6.5624.0/baidu.BaiduPinyin.installer.yaml
  manifests/b/baidu/BaiduPinyin/5.6.5624.0/baidu.BaiduPinyin.locale.en-US.yaml
  manifests/b/baidu/BaiduPinyin/5.6.5624.0/baidu.BaiduPinyin.locale.zh-CN.yaml
  manifests/b/baidu/BaiduPinyin/5.6.5624.0/baidu.BaiduPinyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26421 New version: Synology.ChatClient version 1.2.0-146
  manifests/s/Synology/ChatClient/1.2.0-146/Synology.ChatClient.installer.yaml
  manifests/s/Synology/ChatClient/1.2.0-146/Synology.ChatClient.locale.en-US.yaml
  manifests/s/Synology/ChatClient/1.2.0-146/Synology.ChatClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26545 New version: Telegram.TelegramDesktop version 3.0.0
  manifests/t/Telegram/TelegramDesktop/3.0/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/3.0/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/3.0/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26515 zokugun.MrCode version 1.59.1
  manifests/z/zokugun/MrCode/1.59.1+21241/zokugun.MrCode.installer.yaml
  manifests/z/zokugun/MrCode/1.59.1+21241/zokugun.MrCode.locale.en-US.yaml
  manifests/z/zokugun/MrCode/1.59.1+21241/zokugun.MrCode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26554 Moving: alibaba.yuque version 0.7.14
  manifests/a/alibaba/yuque/0.7.14/alibaba.yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26555 Moving: alibaba.yuque version 0.3.13
  manifests/a/alibaba/yuque/0.3.13/alibaba.yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26556 Moving: alibaba.yuque version 0.9.22
  manifests/a/alibaba/yuque/0.9.22/alibaba.yuque.installer.yaml
  manifests/a/alibaba/yuque/0.9.22/alibaba.yuque.locale.en-US.yaml
  manifests/a/alibaba/yuque/0.9.22/alibaba.yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26557 Moving: alibaba.yuque version 0.8.17
  manifests/a/alibaba/yuque/0.8.17/alibaba.yuque.installer.yaml
  manifests/a/alibaba/yuque/0.8.17/alibaba.yuque.locale.en-US.yaml
  manifests/a/alibaba/yuque/0.8.17/alibaba.yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26542 New version: BraveSoftware.BraveBrowser-Nightly version 93.1.31.11
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.11/BraveSoftware.BraveBrowser-Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.11/BraveSoftware.BraveBrowser-Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser-Nightly/93.1.31.11/BraveSoftware.BraveBrowser-Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26552 New version: GitHub.GitHubDesktop version 2.9.3
  manifests/g/GitHub/GitHubDesktop/2.9.3/GitHub.GitHubDesktop.installer.yaml
  manifests/g/GitHub/GitHubDesktop/2.9.3/GitHub.GitHubDesktop.locale.en-US.yaml
  manifests/g/GitHub/GitHubDesktop/2.9.3/GitHub.GitHubDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26551 ARP: Amazon.Chime version 4.39.10232.1
  manifests/a/Amazon/Chime/4.39.10232.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26546 New version: Telegram.TelegramDesktop.Beta version 2.9.14
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.14/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.14/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.14/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26544 New version: Telegram.TelegramDesktop.Beta version 2.9.13
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26548 New version: BraveSoftware.BraveBrowser-Beta version 93.1.30.59
  manifests/b/BraveSoftware/BraveBrowser-Beta/93.1.30.59/BraveSoftware.BraveBrowser-Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser-Beta/93.1.30.59/BraveSoftware.BraveBrowser-Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser-Beta/93.1.30.59/BraveSoftware.BraveBrowser-Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26553 Moving: alibaba.yuque version 0.8.13
  manifests/a/alibaba/yuque/0.8.13/alibaba.yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26577 Moving: alibaba.adrive version 2.2.4
  manifests/a/alibaba/adrive/2.2.4/alibaba.adrive.installer.yaml
  manifests/a/alibaba/adrive/2.2.4/alibaba.adrive.locale.en-US.yaml
  manifests/a/alibaba/adrive/2.2.4/alibaba.adrive.locale.zh-CN.yaml
  manifests/a/alibaba/adrive/2.2.4/alibaba.adrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26583 Moving: alibaba.lightproxy version 1.1.41
  manifests/a/alibaba/lightproxy/1.1.41/alibaba.lightproxy.installer.yaml
  manifests/a/alibaba/lightproxy/1.1.41/alibaba.lightproxy.locale.en-US.yaml
  manifests/a/alibaba/lightproxy/1.1.41/alibaba.lightproxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26568 ARP: Amazon.Chime version 4.35.10012.1
  manifests/a/Amazon/Chime/4.35.10012.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26582 New version: xgi.houdoku version 2.5.0
  manifests/x/xgi/houdoku/2.5.0/xgi.houdoku.installer.yaml
  manifests/x/xgi/houdoku/2.5.0/xgi.houdoku.locale.en-US.yaml
  manifests/x/xgi/houdoku/2.5.0/xgi.houdoku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26543 New version: Jackett.Jackett version 0.18.641.0
  manifests/j/Jackett/Jackett/0.18.641.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.641.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.641.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26565 ARP: Amazon.Chime version 4.37.10179.1
  manifests/a/Amazon/Chime/4.37.10179.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26563 ARP: Amazon.Chime version 4.39.10197.1
  manifests/a/Amazon/Chime/4.39.10197.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26369 SignatureSha256/FamilyName: LovettSoftware.MyMoney.Net version 1.1.71.0
  manifests/l/LovettSoftware/MyMoney/Net/1.1.71.0/LovettSoftware.MyMoney.Net.yaml
Labels: Validation-Completed, Needs: Attention, Validation-Executable-Error, Moderator-Approved

#26585 JanDeDobbeleer.OhMyPosh version 3.176.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26586 Microsoft.VisualStudioCode.Insiders_v1.60.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.60.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26572 IndigoByte.DrExplain version 6.2.1211
  manifests/i/IndigoByte/DrExplain/6.2.1211/IndigoByte.DrExplain.installer.yaml
  manifests/i/IndigoByte/DrExplain/6.2.1211/IndigoByte.DrExplain.locale.en-US.yaml
  manifests/i/IndigoByte/DrExplain/6.2.1211/IndigoByte.DrExplain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26564 ARP: Amazon.Chime version 4.38.10186.1
  manifests/a/Amazon/Chime/4.38.10186.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26587 Insynchq.Insync version 3.5.2.50118
  manifests/i/Insynchq/Insync/3.5.2.50118/Insynchq.Insync.installer.yaml
  manifests/i/Insynchq/Insync/3.5.2.50118/Insynchq.Insync.locale.en-US.yaml
  manifests/i/Insynchq/Insync/3.5.2.50118/Insynchq.Insync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26517 Updated Google Chrome to version 93.0.4577.63.
  manifests/g/Google/Chrome/93.0.4577.63/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/93.0.4577.63/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/93.0.4577.63/Google.Chrome.locale.nb-NO.yaml
  manifests/g/Google/Chrome/93.0.4577.63/Google.Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26588 Update: StrawberryMusicPlayer.Strawberry version 0.9.3
  manifests/s/StrawberryMusicPlayer/Strawberry/0.9.3/StrawberryMusicPlayer.Strawberry.installer.yaml
  manifests/s/StrawberryMusicPlayer/Strawberry/0.9.3/StrawberryMusicPlayer.Strawberry.locale.en-US.yaml
  manifests/s/StrawberryMusicPlayer/Strawberry/0.9.3/StrawberryMusicPlayer.Strawberry.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26589 Added AWS Command Line Interface version 2.2.34.0.
  manifests/a/Amazon/AWSCLI/2.2.34.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.2.34.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.2.34.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26503 Automattic.Simplenote version 2.17.0
  manifests/a/Automattic/Simplenote/2.17.0/Automattic.Simplenote.installer.yaml
  manifests/a/Automattic/Simplenote/2.17.0/Automattic.Simplenote.locale.en-US.yaml
  manifests/a/Automattic/Simplenote/2.17.0/Automattic.Simplenote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26549 Moved: Alibaba.DingTalkLite version 5.1.21-Release.516
  manifests/a/Alibaba/DingTalkLite/5.1.21-Release.516/Alibaba.DingTalkLite.installer.yaml
  manifests/a/Alibaba/DingTalkLite/5.1.21-Release.516/Alibaba.DingTalkLite.locale.en-US.yaml
  manifests/a/Alibaba/DingTalkLite/5.1.21-Release.516/Alibaba.DingTalkLite.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalkLite/5.1.21-Release.516/Alibaba.DingTalkLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26590 Update NelsonNumericalSoftware.Nelson version 0.5.2.3052 to match Control Panel
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.2.3052/NelsonNumericalSoftware.Nelson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26570 ARP: Amazon.Chime version 4.31.9473.1
  manifests/a/Amazon/Chime/4.31.9473.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26591 Update NelsonNumericalSoftware.Nelson version 0.5.4.3160 to match Control Panel
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.4.3160/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26592 Update NelsonNumericalSoftware.Nelson version 0.5.5.1197 to match Control Panel
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.5.1197/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26594 Update NelsonNumericalSoftware.Nelson version 0.5.7.1334 to match Control Panel
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.7.1334/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26566 ARP: Amazon.Chime version 4.37.10170.1
  manifests/a/Amazon/Chime/4.37.10170.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26602 Moving: alibaba.alipaydevelopmentassistant version 1.0.7
  manifests/a/alibaba/alipaydevelopmentassistant/1.0.7/alibaba.alipaydevelopmentassistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26597 Update bitwig.bitwig version 3.3.5.99629 to match Control Panel
  manifests/b/bitwig/bitwig/3.3.5.99629/bitwig.bitwig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26593 Update NelsonNumericalSoftware.Nelson version 0.5.6.1290 to match Control Panel
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.6.1290/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26596 Update bitwig.bitwig version 3.3.3.98257 to match Control Panel
  manifests/b/bitwig/bitwig/3.3.3.98257/bitwig.bitwig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26598 Update bitwig.bitwig version 3.3.6.99964 to match Control Panel
  manifests/b/bitwig/bitwig/3.3.6.99964/bitwig.bitwig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26595 Update bitwig.bitwig version 3.3.2.97993 to match Control Panel
  manifests/b/bitwig/bitwig/3.3.2.97993/bitwig.bitwig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26599 Update bitwig.bitwig version 3.3.7.100105 to match Control Panel
  manifests/b/bitwig/bitwig/3.3.7.100105/bitwig.bitwig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26608 Moving: alibaba.miniprogramstudio version 1.17.9
  manifests/a/alibaba/miniprogramstudio/1.17.9/alibaba.miniprogramstudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26609 Moving: alibaba.miniprogramstudio version 1.15.7
  manifests/a/alibaba/miniprogramstudio/1.15.7/alibaba.miniprogramstudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26603 New package: Paragon.HFS+ version 11.4.273
  manifests/p/Paragon/HFS+/11.4.273/Paragon.HFS+.installer.yaml
  manifests/p/Paragon/HFS+/11.4.273/Paragon.HFS+.locale.en-US.yaml
  manifests/p/Paragon/HFS+/11.4.273/Paragon.HFS+.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26607 Moving: alibaba.miniprogramstudio version 2.1.9
  manifests/a/alibaba/miniprogramstudio/2.1.9/alibaba.miniprogramstudio.installer.yaml
  manifests/a/alibaba/miniprogramstudio/2.1.9/alibaba.miniprogramstudio.locale.en-US.yaml
  manifests/a/alibaba/miniprogramstudio/2.1.9/alibaba.miniprogramstudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26610 Moving: alibaba.miniprogramstudio version 2.3.5
  manifests/a/alibaba/miniprogramstudio/2.3.5/alibaba.miniprogramstudio.installer.yaml
  manifests/a/alibaba/miniprogramstudio/2.3.5/alibaba.miniprogramstudio.locale.en-US.yaml
  manifests/a/alibaba/miniprogramstudio/2.3.5/alibaba.miniprogramstudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26615 Moving: alibaba.dingtalk version 6.0.26-Release.8200187
  manifests/a/alibaba/dingtalk/6.0.26-Release.8200187/alibaba.dingtalk.installer.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8200187/alibaba.dingtalk.locale.en-US.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8200187/alibaba.dingtalk.locale.zh-CN.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8200187/alibaba.dingtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26616 Moving: alibaba.dingtalk version 6.0.26-Release.8240887
  manifests/a/alibaba/dingtalk/6.0.26-Release.8240887/alibaba.dingtalk.installer.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8240887/alibaba.dingtalk.locale.en-US.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8240887/alibaba.dingtalk.locale.zh-CN.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.8240887/alibaba.dingtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26618 Moving: alibaba.dingtalk version 6.0.18-Release.6280687
  manifests/a/alibaba/dingtalk/6.0.18-Release.6280687/alibaba.dingtalk.installer.yaml
  manifests/a/alibaba/dingtalk/6.0.18-Release.6280687/alibaba.dingtalk.locale.en-US.yaml
  manifests/a/alibaba/dingtalk/6.0.18-Release.6280687/alibaba.dingtalk.locale.zh-CN.yaml
  manifests/a/alibaba/dingtalk/6.0.18-Release.6280687/alibaba.dingtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26567 ARP: Amazon.Chime version 4.35.10077.1
  manifests/a/Amazon/Chime/4.35.10077.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26584 Moving: alibaba.lightproxy version 1.1.40
  manifests/a/alibaba/lightproxy/1.1.40/alibaba.lightproxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26617 Moving: alibaba.dingtalk version 6.0.26-Release.9039987
  manifests/a/alibaba/dingtalk/6.0.26-Release.9039987/alibaba.dingtalk.installer.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.9039987/alibaba.dingtalk.locale.en-US.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.9039987/alibaba.dingtalk.locale.zh-CN.yaml
  manifests/a/alibaba/dingtalk/6.0.26-Release.9039987/alibaba.dingtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26628 ARP: Digimezzo.Dopamine version 2.0.5.4000
  manifests/d/Digimezzo/Dopamine/2.0.5.4000/Digimezzo.Dopamine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26627 ARP: Digimezzo.Dopamine version 2.0.3.4000
  manifests/d/Digimezzo/Dopamine/2.0.3.4000/Digimezzo.Dopamine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26623 ARP: Digimezzo.Dopamine version 2.0.1.4000
  manifests/d/Digimezzo/Dopamine/2.0.1.4000/Digimezzo.Dopamine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26601 Moved: Alibaba.LightProxy version 1.1.41
  manifests/a/Alibaba/LightProxy/1.1.41/Alibaba.LightProxy.installer.yaml
  manifests/a/Alibaba/LightProxy/1.1.41/Alibaba.LightProxy.locale.en-US.yaml
  manifests/a/Alibaba/LightProxy/1.1.41/Alibaba.LightProxy.locale.zh-CN.yaml
  manifests/a/Alibaba/LightProxy/1.1.41/Alibaba.LightProxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26604 Moved: Alibaba.AlipayDevelopmentAssistant version 1.0.7
  manifests/a/Alibaba/AlipayDevelopmentAssistant/1.0.7/Alibaba.AlipayDevelopmentAssistant.installer.yaml
  manifests/a/Alibaba/AlipayDevelopmentAssistant/1.0.7/Alibaba.AlipayDevelopmentAssistant.locale.en-US.yaml
  manifests/a/Alibaba/AlipayDevelopmentAssistant/1.0.7/Alibaba.AlipayDevelopmentAssistant.locale.zh-CN.yaml
  manifests/a/Alibaba/AlipayDevelopmentAssistant/1.0.7/Alibaba.AlipayDevelopmentAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26639 Update: Microsoft.VC++2013Redist-x86 12.0.30501.0
  manifests/m/Microsoft/VC++2013Redist-x86/12.0.30501.0/Microsoft.VC++2013Redist-x86.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26636 Update: Microsoft.VC++2013Redist-x86 12.0.40649.5
  manifests/m/Microsoft/VC++2013Redist-x86/12.0.40649.5/Microsoft.VC++2013Redist-x86.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26638 Update: Microsoft.VC++2013Redist-x86 12.0.40664.0
  manifests/m/Microsoft/VC++2013Redist-x86/12.0.40664.0/Microsoft.VC++2013Redist-x86.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26637 Update: Microsoft.VC++2013Redist-x86 12.0.40660.0
  manifests/m/Microsoft/VC++2013Redist-x86/12.0.40660.0/Microsoft.VC++2013Redist-x86.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26605 ARP: cocos.cocos-dashboard version 1.0.11.1819
  manifests/c/cocos/cocos-dashboard/1.0.11.1819/cocos.cocos-dashboard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26569 ARP: Amazon.Chime version 4.34.9941.1
  manifests/a/Amazon/Chime/4.34.9941.1/Amazon.Chime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26606 Added GoLand version 212.5080.74.
  manifests/j/JetBrains/GoLand/212.5080.74/JetBrains.GoLand.installer.yaml
  manifests/j/JetBrains/GoLand/212.5080.74/JetBrains.GoLand.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/212.5080.74/JetBrains.GoLand.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26576 Update: Microsoft.VC++2013Redist-x64 12.0.30501.0
  manifests/m/Microsoft/VC++2013Redist-x64/12.0.30501.0/Microsoft.VC++2013Redist-x64.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26573 Update: Microsoft.VC++2013Redist-x64 12.0.40664.0
  manifests/m/Microsoft/VC++2013Redist-x64/12.0.40664.0/Microsoft.VC++2013Redist-x64.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26571 Update: Microsoft.VC++2013Redist-x64 12.0.40649.5
  manifests/m/Microsoft/VC++2013Redist-x64/12.0.40649.5/Microsoft.VC++2013Redist-x64.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26642 Update: SaeraSoft.CaesiumPH version 0.9.5
  manifests/s/SaeraSoft/CaesiumPH/0.9.5/SaeraSoft.CaesiumPH.installer.yaml
  manifests/s/SaeraSoft/CaesiumPH/0.9.5/SaeraSoft.CaesiumPH.locale.en-US.yaml
  manifests/s/SaeraSoft/CaesiumPH/0.9.5/SaeraSoft.CaesiumPH.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26641 New version: purocean.YankNote version 3.6.0
  manifests/p/purocean/YankNote/3.6.0/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.6.0/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.6.0/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26624 Moved: Alibaba.DingTalk version 6.0.22-Release.7190187
  manifests/a/Alibaba/DingTalk/6.0.22-Release.7190187/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/6.0.22-Release.7190187/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/6.0.22-Release.7190187/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/6.0.22-Release.7190187/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26626 Moved: Alibaba.DingTalk version 6.0.26-Release.9039987
  manifests/a/Alibaba/DingTalk/6.0.26-Release.9039987/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.9039987/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.9039987/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.9039987/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26633 ARP: Mirantis.Lens version 5.0.0-latest.20210629.3
  manifests/m/Mirantis/Lens/5.0.0-latest.20210629.3/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26630 Recoupler.AudioBookConverter version 5.5.26
  manifests/r/Recoupler/AudioBookConverter/5.5.26/Recoupler.AudioBookConverter.installer.yaml
  manifests/r/Recoupler/AudioBookConverter/5.5.26/Recoupler.AudioBookConverter.locale.en-US.yaml
  manifests/r/Recoupler/AudioBookConverter/5.5.26/Recoupler.AudioBookConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26574 Update: Microsoft.VC++2013Redist-x64 12.0.40660.0
  manifests/m/Microsoft/VC++2013Redist-x64/12.0.40660.0/Microsoft.VC++2013Redist-x64.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26632 ARP: Mirantis.Lens version 5.0.2-latest.20210705.2
  manifests/m/Mirantis/Lens/5.0.2-latest.20210705.2/Mirantis.Lens.installer.yaml
  manifests/m/Mirantis/Lens/5.0.2-latest.20210705.2/Mirantis.Lens.locale.en-US.yaml
  manifests/m/Mirantis/Lens/5.0.2-latest.20210705.2/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26621 Moved: Alibaba.DingTalk version 6.0.26-Release.8200187
  manifests/a/Alibaba/DingTalk/6.0.26-Release.8200187/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.8200187/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.8200187/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/6.0.26-Release.8200187/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26645 Remove old: RARLab.WinRARBeta 6.02.1
  manifests/r/RARLab/WinRARBeta/6.02.1/RARLab.WinRARBeta.installer.yaml
  manifests/r/RARLab/WinRARBeta/6.02.1/RARLab.WinRARBeta.locale.en-US.yaml
  manifests/r/RARLab/WinRARBeta/6.02.1/RARLab.WinRARBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26311 New version: Trillian.Trillian version 6.5.0017
  manifests/t/Trillian/Trillian/6.5.0017/Trillian.Trillian.installer.yaml
  manifests/t/Trillian/Trillian/6.5.0017/Trillian.Trillian.locale.en-US.yaml
  manifests/t/Trillian/Trillian/6.5.0017/Trillian.Trillian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#26463 ARP: RealVNC.VNCViewer version 6.0.0.23442
  manifests/r/RealVNC/VNCViewer/6.0.0.23442/RealVNC.VNCViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#26499 Emurasoft.EmEditor version 21.1.0
  manifests/e/Emurasoft/EmEditor/21.1.0/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/21.1.0/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/21.1.0/Emurasoft.EmEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#26377 Python.Python.3 version 3.9.7150.0
  manifests/p/Python/Python/3/3.9.7150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.9.7150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.9.7150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#26622 Moved: Alibaba.DingTalk version 6.0.18-Release.6280687
  manifests/a/Alibaba/DingTalk/6.0.18-Release.6280687/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/6.0.18-Release.6280687/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/6.0.18-Release.6280687/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/6.0.18-Release.6280687/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26653 New version: Radmin.VPN version 1.1.4394
  manifests/r/Radmin/VPN/1.1.4394/Radmin.VPN.installer.yaml
  manifests/r/Radmin/VPN/1.1.4394/Radmin.VPN.locale.en-US.yaml
  manifests/r/Radmin/VPN/1.1.4394/Radmin.VPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26644 maximmax42.CustomRP version 1.11.6
  manifests/m/maximmax42/CustomRP/1.11.6/maximmax42.CustomRP.installer.yaml
  manifests/m/maximmax42/CustomRP/1.11.6/maximmax42.CustomRP.locale.en-US.yaml
  manifests/m/maximmax42/CustomRP/1.11.6/maximmax42.CustomRP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26652 Update: RabidViperProductions.AssaultCube version 1.2.0.2
  manifests/r/RabidViperProductions/AssaultCube/1.2.0.2/RabidViperProductions.AssaultCube.installer.yaml
  manifests/r/RabidViperProductions/AssaultCube/1.2.0.2/RabidViperProductions.AssaultCube.locale.en-US.yaml
  manifests/r/RabidViperProductions/AssaultCube/1.2.0.2/RabidViperProductions.AssaultCube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26664 boy1dr.SpleeterGui version 2.9.1
  manifests/b/boy1dr/SpleeterGui/2.9.1/boy1dr.SpleeterGui.installer.yaml
  manifests/b/boy1dr/SpleeterGui/2.9.1/boy1dr.SpleeterGui.locale.en-US.yaml
  manifests/b/boy1dr/SpleeterGui/2.9.1/boy1dr.SpleeterGui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26684 Added WestWind.MarkdownMonster version 2.0.12.0
  manifests/w/WestWind/MarkdownMonster/2.0.12.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.0.12.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.0.12.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26683 Added WestWind.MarkdownMonster version 2.0.11.0
  manifests/w/WestWind/MarkdownMonster/2.0.11.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.0.11.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.0.11.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26668 winpython.winpython-dot version 3.9.5.0
  manifests/w/winpython/winpython-dot/3.9.5.0/winpython.winpython-dot.installer.yaml
  manifests/w/winpython/winpython-dot/3.9.5.0/winpython.winpython-dot.locale.en-US.yaml
  manifests/w/winpython/winpython-dot/3.9.5.0/winpython.winpython-dot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26680 Added BlenderFoundation.Blender version 2.93.4
  manifests/b/BlenderFoundation/Blender/2.93.4/BlenderFoundation.Blender.installer.yaml
  manifests/b/BlenderFoundation/Blender/2.93.4/BlenderFoundation.Blender.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/2.93.4/BlenderFoundation.Blender.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26678 Added KDE.KDEConnect version 21.08.0.701
  manifests/k/KDE/KDEConnect/21.08.0.701/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.08.0.701/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.08.0.701/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26687 New version: JAMSoftware.Ultrasearch version 3.1.2
  manifests/j/JAMSoftware/Ultrasearch/3.1.2/JAMSoftware.Ultrasearch.installer.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.1.2/JAMSoftware.Ultrasearch.locale.de-DE.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.1.2/JAMSoftware.Ultrasearch.locale.en-US.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.1.2/JAMSoftware.Ultrasearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26685 New version: Wondershare.PDFelement version 8.2.13
  manifests/w/Wondershare/PDFelement/8.2.13/Wondershare.PDFelement.installer.yaml
  manifests/w/Wondershare/PDFelement/8.2.13/Wondershare.PDFelement.locale.en-US.yaml
  manifests/w/Wondershare/PDFelement/8.2.13/Wondershare.PDFelement.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26688 Added back x64 installer to Microsoft.PowerBI
  manifests/m/Microsoft/PowerBI/2.96.1061.0/Microsoft.PowerBI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26689 New version: jely2002.youtube-dl-gui version 2.3.1
  manifests/j/jely2002/youtube-dl-gui/2.3.1/jely2002.youtube-dl-gui.installer.yaml
  manifests/j/jely2002/youtube-dl-gui/2.3.1/jely2002.youtube-dl-gui.locale.en-US.yaml
  manifests/j/jely2002/youtube-dl-gui/2.3.1/jely2002.youtube-dl-gui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26691 New version: StandardNotes.StandardNotes version 3.8.21
  manifests/s/StandardNotes/StandardNotes/3.8.21/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.8.21/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.8.21/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26692 New version: Telegram.TelegramDesktop version 3.0.1
  manifests/t/Telegram/TelegramDesktop/3.0.1/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/3.0.1/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/3.0.1/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26698 Remove old: spyder.spyder 4.2.5
  manifests/s/spyder/spyder/4.2.5/spyder.spyder.installer.yaml
  manifests/s/spyder/spyder/4.2.5/spyder.spyder.locale.en-US.yaml
  manifests/s/spyder/spyder/4.2.5/spyder.spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26695 Remove old: spyder.spyder-lite 4.2.5
  manifests/s/spyder/spyder-lite/4.2.5/spyder.spyder-lite.installer.yaml
  manifests/s/spyder/spyder-lite/4.2.5/spyder.spyder-lite.locale.en-US.yaml
  manifests/s/spyder/spyder-lite/4.2.5/spyder.spyder-lite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26694 New version: DoltHub.Dolt version 0.28.2
  manifests/d/DoltHub/Dolt/0.28.2/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.28.2/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.28.2/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26690 New package: Stardock.Curtains version 1.19
  manifests/s/Stardock/Curtains/1.19/Stardock.Curtains.installer.yaml
  manifests/s/Stardock/Curtains/1.19/Stardock.Curtains.locale.en-US.yaml
  manifests/s/Stardock/Curtains/1.19/Stardock.Curtains.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26700 Remove old: spyder.spyder 5.1.1
  manifests/s/spyder/spyder/5.1.1/spyder.spyder.installer.yaml
  manifests/s/spyder/spyder/5.1.1/spyder.spyder.locale.en-US.yaml
  manifests/s/spyder/spyder/5.1.1/spyder.spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26699 Remove old: spyder.spyder 5.0.4
  manifests/s/spyder/spyder/5.0.4/spyder.spyder.installer.yaml
  manifests/s/spyder/spyder/5.0.4/spyder.spyder.locale.en-US.yaml
  manifests/s/spyder/spyder/5.0.4/spyder.spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26696 Remove old: spyder.spyder-lite 5.0.4
  manifests/s/spyder/spyder-lite/5.0.4/spyder.spyder-lite.installer.yaml
  manifests/s/spyder/spyder-lite/5.0.4/spyder.spyder-lite.locale.en-US.yaml
  manifests/s/spyder/spyder-lite/5.0.4/spyder.spyder-lite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26679 Added vim.vim version 8.2.3394
  manifests/v/vim/vim/8.2.3394/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3394/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3394/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26703 Moving: bytedance.bytedance-devtool version 3.0.6
  manifests/b/bytedance/bytedance-devtool/3.0.6/bytedance.bytedance-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26704 Moving: bytedance.bytedance-devtool version 3.0.4
  manifests/b/bytedance/bytedance-devtool/3.0.4/bytedance.bytedance-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26705 Moving: bytedance.bytedance-devtool version 3.1.3
  manifests/b/bytedance/bytedance-devtool/3.1.3/bytedance.bytedance-devtool.installer.yaml
  manifests/b/bytedance/bytedance-devtool/3.1.3/bytedance.bytedance-devtool.locale.en-US.yaml
  manifests/b/bytedance/bytedance-devtool/3.1.3/bytedance.bytedance-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26702 Moving: bytedance.bytedance-devtool version 3.0.9
  manifests/b/bytedance/bytedance-devtool/3.0.9/bytedance.bytedance-devtool.installer.yaml
  manifests/b/bytedance/bytedance-devtool/3.0.9/bytedance.bytedance-devtool.locale.en-US.yaml
  manifests/b/bytedance/bytedance-devtool/3.0.9/bytedance.bytedance-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26693 New version: SaladTechnologies.Salad version 0.5.6
  manifests/s/SaladTechnologies/Salad/0.5.6/SaladTechnologies.Salad.installer.yaml
  manifests/s/SaladTechnologies/Salad/0.5.6/SaladTechnologies.Salad.locale.en-US.yaml
  manifests/s/SaladTechnologies/Salad/0.5.6/SaladTechnologies.Salad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26709 Add version: Spyder.Spyder 5.0.5
  manifests/s/Spyder/Spyder/5.0.5/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.5/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.5/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26719 Add version: Spyder.Spyder 4.2.1
  manifests/s/Spyder/Spyder/4.2.1/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/4.2.1/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/4.2.1/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26712 Add version: Spyder.Spyder 5.0.2
  manifests/s/Spyder/Spyder/5.0.2/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.2/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.2/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26706 Add version: Spyder.Spyder 5.1.2
  manifests/s/Spyder/Spyder/5.1.2/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.1.2/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.1.2/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26720 Add version: Spyder.Spyder 4.2.0
  manifests/s/Spyder/Spyder/4.2.0/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/4.2.0/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/4.2.0/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26708 Add version: Spyder.Spyder 5.1.0
  manifests/s/Spyder/Spyder/5.1.0/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.1.0/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.1.0/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26716 Add version: Spyder.Spyder 4.2.4
  manifests/s/Spyder/Spyder/4.2.4/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/4.2.4/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/4.2.4/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26713 Add version: Spyder.Spyder 5.0.1
  manifests/s/Spyder/Spyder/5.0.1/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.1/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.1/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26717 Add version: Spyder.Spyder 4.2.3
  manifests/s/Spyder/Spyder/4.2.3/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/4.2.3/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/4.2.3/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26707 Add version: Spyder.Spyder 5.1.1
  manifests/s/Spyder/Spyder/5.1.1/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.1.1/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.1.1/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26715 Add version: Spyder.Spyder 4.2.5
  manifests/s/Spyder/Spyder/4.2.5/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/4.2.5/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/4.2.5/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26663 hluk.CopyQ version 4.1.0
  manifests/h/hluk/CopyQ/v4.1.0/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/v4.1.0/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/v4.1.0/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26710 Add version: Spyder.Spyder 5.0.4
  manifests/s/Spyder/Spyder/5.0.4/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.4/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.4/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26711 Add version: Spyder.Spyder 5.0.3
  manifests/s/Spyder/Spyder/5.0.3/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.3/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.3/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26714 Add version: Spyder.Spyder 5.0.0
  manifests/s/Spyder/Spyder/5.0.0/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.0.0/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.0.0/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26677 Added Jackett.Jackett version 0.18.643.0
  manifests/j/Jackett/Jackett/0.18.643.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.18.643.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.18.643.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26733 Moving: baidu.translate version 1.1.2
  manifests/b/baidu/translate/1.1.2/baidu.translate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26732 Moving: baidu.translate version 1.0.0
  manifests/b/baidu/translate/1.0.0/baidu.translate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26731 Moving: baidu.translate version 1.0.1
  manifests/b/baidu/translate/1.0.1/baidu.translate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26735 Moving: baidu.translate version 1.1.0
  manifests/b/baidu/translate/1.1.0/baidu.translate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26725 purocean.YankNote version 3.4.2
  manifests/p/purocean/YankNote/3.4.2/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.4.2/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.4.2/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#26726 purocean.YankNote version 3.3.7
  manifests/p/purocean/YankNote/3.3.7/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.3.7/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.3.7/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
