Repository microsoft/winget-pkgs, pull requests merged in 2021-02, with the labels that each got.

#6874 Added Puppet Bolt version 2.44.0.
  manifests/Puppet/puppet-bolt/2.44.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6877 Fixed incorrect version number for SharePoint Online Management Shell version 16.0.20912.12000.
  manifests/Microsoft/SharePointOnlineManagementShell/16.0.20912.12000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6873 Added MySQL version 8.0.23.
  manifests/Oracle/MySQL/8.0.23.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6872 Added Amazon Chime version 4.37.10179.
  manifests/Amazon/Chime/4.37.10179.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6871 Added AWS CLI version 2.1.22.
  manifests/Amazon/AWSCLI/2.1.22.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6869 Added Puppet Agent version 7.3.0.
  manifests/Puppet/puppet-agent/7.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6868 Added Cisco WebEx Meetings version 41.2.2.16.
  manifests/Cisco/CiscoWebexMeetings/41.2.2.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6867 Added 1Password for Windows version 7.6.791.
  manifests/AgileBits/1Password/7.6.791.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6866 Added Dropbox version 114.4.426.
  manifests/Dropbox/Dropbox/114.4.426.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6881 Updating Taozuhong.Kangaroo to 1.6.1.210131
  manifests/Taozuhong/Kangaroo/1.6.1.210131.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6880 Add Lenovo System Update 5.07.0113
  manifests/Lenovo/SystemUpdate/5.07.0113.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6879 add LibreOffice 7.0.4
  manifests/LibreOffice/LibreOffice/7.0.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6878 Update Netron to 4.7.5
  manifests/LutzRoeder/Netron/4.7.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6885 Added LLVM version 11.0.1.
  manifests/LLVM/LLVM/11.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6884 Add NuGet
  manifests/Microsoft/NuGet/5.8.1.7021.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6882 Add Dbeaver 7.3.4
  manifests/DBeaver/DBeaver/7.3.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6890 Fixed incorrect product code for Google Chrome.
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#6898 GitHub Desktop Beta version 2.6.3-beta2
  manifests/GitHub/GitHubDesktopBeta/2.6.3-beta2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6889 Fixed incorrect product code for Google Chrome Beta.
  manifests/Google/ChromeBeta/latest.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#6888 Updated Spotify to version 1.1.51.382.
  manifests/Spotify/Spotify/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6905 zoom outlook plugin version 5.5.12365
  manifests/Zoom/zoomoutlookplugin/5.5.12365.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6903 Use direct link for Wireshark version 3.2.2
  manifests/WiresharkFoundation/Wireshark/3.2.2.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6899 Typo Fix plex installer scope
  manifests/Plex/Plex/1.14.0.1340.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6902 Use direct link for Wireshark version 3.2.4
  manifests/WiresharkFoundation/Wireshark/3.2.4.Yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6901 Use direct link for Wireshark version 3.2.5
  manifests/WiresharkFoundation/Wireshark/3.2.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6892 Zoom version 5.5.0
  manifests/Zoom/Zoom/5.5.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6887 Added Salt Minion version 3002.2.
  manifests/SaltStack/SaltMinion/3002.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6894 VLC media player nightly version 4.0.0-20210201
  manifests/VideoLAN/VLCNightly/4.0.0-20210201.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6895 VLC media player version 3.0.12
  manifests/VideoLAN/VLC/3.0.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6897 Node.js Nightly version 16.0.0-20210201
  manifests/OpenJS/NodeJSNightly/16.0.0-20210201.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6886 Added Microsoft Edge Dev version 89.0.774.8.
  manifests/Microsoft/EdgeDev/89.0.774.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6883 Update maxto
  manifests/DigitalCreations/MaxTo/2.1.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6900 Use direct link for Rtools version 4.0.0
  manifests/RProject/Rtools/4.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6571 Altap Salamander 4.0 x64
  manifests/Altap/Salamander/4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6870 Added Microsoft Teams version 1.4.00.2781.
  manifests/Microsoft/Teams/1.4.00.2781.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6842 Switch URL to HTTPS for Tencent WeChat version 2.9.0.1000
  manifests/Tencent/WeChat/2.9.0.1000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6576 add NTWind WinSnap 5.2.9
  manifests/NTWindSoftware/WinSnap/5.2.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6574 add NTWind WindowSpace 2.6.3 x64
  manifests/NTWindSoftware/WindowSpace/2.6.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6804 Switch URL to HTTPS for Bulk Rename Utility version 3.3.1.0
  manifests/TGRMNSoftware/BulkRenameUtility/3.3.1.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6907 VisualStudioCode-User-x86
  manifests/Microsoft/VisualStudioCode-User-x86/1.52.1.ea3859d4ba.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6908 VisualStudioCode-User-x64
  manifests/Microsoft/VisualStudioCode-User-x64/1.52.1.ea3859d4ba.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6909 VisualStudioCode-System-x86
  manifests/Microsoft/VisualStudioCode-System-x86/1.52.1.ea3859d4ba.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6910 VisualStudioCode-System-x64
  manifests/Microsoft/VisualStudioCode-System-x64/1.52.1.ea3859d4ba.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6911 VisualStudioCodeInsiders-User-x86
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.53.1.5a52bc29d5.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6912 VisualStudioCodeInsiders-User-x64
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.53.1.5a52bc29d5.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6913 VisualStudioCodeInsiders-System-x86
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.53.1.5a52bc29d5.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6914 VisualStudioCodeInsiders-System-x64
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.53.1.5a52bc29d5.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Manifest-Only-Metadata, Validation-Completed

#6906 Add Workspace ONE Intelligent Hub 21.1.0.0
  manifests/VMware/IntelligentHub/21.1.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6916 Microsoft.VisualStudioCodeInsiders-System-x86_v1.53.2.b99487f416
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.53.2.b99487f416.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6915 Microsoft.VisualStudioCodeInsiders-User-x86_v1.53.2.b99487f416
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.53.2.b99487f416.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6917 Microsoft.VisualStudioCodeInsiders-System-x64_v1.53.2.b99487f416
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.53.2.b99487f416.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6918 Microsoft.VisualStudioCodeInsiders-User-x64_v1.53.2.b99487f416
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.53.2.b99487f416.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6920 Added ProductCode to Accessibility Insights for Windows version 1.1.1467.01.
  manifests/Microsoft/AccessibilityInsightsWindows/1.1.1467.01.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#6931 Microsoft.VisualStudioCodeInsiders-System-x64_v1.53.3.8d779a4fad
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.53.3.8d779a4fad.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6933 Microsoft.VisualStudioCodeInsiders-User-x86_v1.53.3.8d779a4fad
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.53.3.8d779a4fad.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6934 Microsoft.VisualStudioCodeInsiders-User-x64_v1.53.3.8d779a4fad
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.53.3.8d779a4fad.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6935 Microsoft.VisualStudioCodeInsiders-System-x86_v1.53.3.8d779a4fad
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.53.3.8d779a4fad.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6919 Added Visual Studio Enterprise (2019) version 16.8.30907.101.
  manifests/Microsoft/VisualStudio/Enterprise/16.8.30907.101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6941 Microsoft OneDrive Internal Fast version 21.021.0131.0001
  manifests/Microsoft/OneDriveInternalFast/21.021.0131.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6940 Node.js Nightly version 16.0.0-20210202
  manifests/OpenJS/NodeJSNightly/16.0.0-20210202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6939 Fiddler Everywhere version 1.5.1
  manifests/Telerik/FiddlerEverywhere/1.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6938 Fiddler Everywhere Insiders version 1.5.1-insiders
  manifests/Telerik/FiddlerEverywhereInsiders/1.5.1-insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6945 Add Mattermost Desktop 4.6.2
  manifests/Mattermost/MattermostDesktop/4.6.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6921 Added Surface Duo Emulator version 2021.114.2.
  manifests/Microsoft/SurfaceDuoEmulator/2021.114.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6943 Node.js version 15.8.0
  manifests/OpenJS/NodeJS/15.8.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6937 FileZilla Client Nightly version 3.52.2-20210202
  manifests/TimKosse/FileZillaClientNightly/3.52.2-20210202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6923 Added Plex Media Server version 1.21.2.3943.
  manifests/Plex/PlexMediaServer/1.21.2.3943.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6930 Added Waterfox Classic version 2021.01.01.
  manifests/Waterfox/Waterfox/2021.01.01.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6925 Added Pale Moon version 29.0.0.
  manifests/MoonchildProductions/PaleMoon/29.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6927 Microsoft.PowerToys version 0.31.1
  manifests/Microsoft/PowerToys/0.31.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6922 Added pgAdmin4 (x64) version 4.30.
  manifests/PostgreSQL/pgAdmin-x64/4.30.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6936 VLC media player nightly version 4.0.0-20210202
  manifests/VideoLAN/VLCNightly/4.0.0-20210202.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6947 Updating Google.Chrome to latest
  manifests/Google/Chrome/latest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6924 Added JetBrains Toolbox version 1.20.7939.
  manifests/JetBrains/Toolbox/1.20.7939.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6929 Added WebEx Meetings version 41.2.3.17.
  manifests/Cisco/CiscoWebexMeetings/41.2.3.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6951 Microsoft.VisualStudioCodeInsiders-System-x64_v1.53.4.e1c818a171
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.53.4.e1c818a171.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6953 Microsoft.VisualStudioCodeInsiders-User-x64_v1.53.4.e1c818a171
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.53.4.e1c818a171.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6952 Microsoft.VisualStudioCodeInsiders-User-x86_v1.53.4.e1c818a171
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.53.4.e1c818a171.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6954 Microsoft.VisualStudioCodeInsiders-System-x86_v1.53.4.e1c818a171
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.53.4.e1c818a171.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6949 Add Stretchly 1.4.0
  manifests/Stretchly/Stretchly/1.4.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6950 ungoogled-chromium 87.0.4280.141
  manifests/eloston/ungoogled-chromium/87.0.4280.141.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6956 Added LibreOffice version 7.1.0.3.
  manifests/LibreOffice/LibreOffice/7.1.0.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6959 Microsoft.VisualStudioCodeInsiders-User-x64_v1.53.5.8490d3dde4
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.53.5.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6958 Microsoft.VisualStudioCodeInsiders-User-x86_v1.53.5.8490d3dde4
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.53.5.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6960 Microsoft.VisualStudioCodeInsiders-System-x86_v1.53.5.8490d3dde4
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.53.5.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6961 Microsoft.VisualStudioCodeInsiders-System-x64_v1.53.5.8490d3dde4
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.53.5.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6955 Added AWS CLI version 2.1.23.
  manifests/Amazon/AWSCLI/2.1.23.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6932 Added MongoDB Server version 4.4.3.
  manifests/MongoDB/Server/4.4.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6972 add Questrade IQ Edge 6.2.15.235
  manifests/Questrade/IQEdge/6.2.15.235.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6969 Microsoft OneDrive Internal Fast version 21.022.0201.0001
  manifests/Microsoft/OneDriveInternalFast/21.022.0201.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6968 Node.js Nightly version 16.0.0-20210203
  manifests/OpenJS/NodeJSNightly/16.0.0-20210203.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6863 WeMod Beta version 7.0.1-beta07
  manifests/WeMod/WeModBeta/7.0.1-beta07.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6893 WeMod Beta version 7.0.1-beta09
  manifests/WeMod/WeModBeta/7.0.1-beta09.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6962 Added Firefox Developer Edition version 86.0b5.
  manifests/Mozilla/FirefoxDeveloperEdition/86.0b5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6963 Added Moonlight Client version 3.0.0.
  manifests/MoonlightGameStreamingProject/Moonlight/3.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6965 WeMod Beta version 7.0.1-beta10
  manifests/WeMod/WeModBeta/7.0.1-beta10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6964 Zoom version 5.5.1
  manifests/Zoom/Zoom/5.5.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6966 VLC media player nightly version 4.0.0-20210203
  manifests/VideoLAN/VLCNightly/4.0.0-20210203.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6970 Discord Development version 0.0.7803
  manifests/Discord/DiscordDevelopment/0.0.7803.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6983 Microsoft.VisualStudioCode-System-x86_v1.53.0.8490d3dde4
  manifests/Microsoft/VisualStudioCode-System-x86/1.53.0.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6984 Microsoft.VisualStudioCode-User-x64_v1.53.0.8490d3dde4
  manifests/Microsoft/VisualStudioCode-User-x64/1.53.0.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6985 Microsoft.VisualStudioCode-User-x86_v1.53.0.8490d3dde4
  manifests/Microsoft/VisualStudioCode-User-x86/1.53.0.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6986 Microsoft.VisualStudioCode-System-x64_v1.53.0.8490d3dde4
  manifests/Microsoft/VisualStudioCode-System-x64/1.53.0.8490d3dde4.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6982 - adds openjdk 8.0.282
  manifests/AdoptOpenJDK/OpenJDK/8.0.282.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6981 - adds manifest for openjdk 15.0.2.7
  manifests/AdoptOpenJDK/OpenJDK/15.0.2.7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6980 Added balenaEtcher version 1.5.116.
  manifests/Balena/Etcher/1.5.116.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6979 Added Dropbox version 115.4.601.
  manifests/Dropbox/Dropbox/115.4.601.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6978 Fixed incorrect product code for PowerToys version 0.31.1.
  manifests/Microsoft/PowerToys/0.31.1.yaml
Labels: Azure-Pipeline-Passed, Manifest-Only-Metadata, Validation-Completed

#7002 GitHub Desktop Beta version 2.6.3-beta3
  manifests/GitHub/GitHubDesktopBeta/2.6.3-beta3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7001 Microsoft OneDrive Insiders version 21.016.0124.0002
  manifests/Microsoft/OneDriveInsiders/21.016.0124.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7000 Microsoft OneDrive Internal Fast version 21.023.0202.0001
  manifests/Microsoft/OneDriveInternalFast/21.023.0202.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6988 Add Lagrange 1.1.1
  manifests/fi.skyjake/Lagrange/1.1.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6998 Node.js Nightly version 16.0.0-20210204
  manifests/OpenJS/NodeJSNightly/16.0.0-20210204.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6996 VLC media player nightly version 4.0.0-20210204
  manifests/VideoLAN/VLCNightly/4.0.0-20210204.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6975 uwphook 2.9
  manifests/brianlima/uwphook/2.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7003 add KeePassXC 2.6.4
  manifests/KeePassXCTeam/KeePassXC/2.6.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6993 Updated ZeroTier One to version 1.6.3.0.
  manifests/Zerotier/Zerotier/1.6.3.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7004 Submitting MabelTerm Version 1.4.1
  manifests/MabelisYT/MabelTerm/1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6976 Added Visual Studio Professional version 16.8 (16.8.30907.101).
  manifests/Microsoft/VisualStudio/Professional/16.8.30907.101.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6999 Microsoft OneDrive Internal Slow version 21.020.0128.0001
  manifests/Microsoft/OneDriveInternalSlow/21.020.0128.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7005 Microsoft.VisualStudioCodeInsiders-System-x64_v1.54.1.52838cf679
  manifests/Microsoft/VisualStudioCodeInsiders-System-x64/1.54.1.52838cf679.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#7006 Microsoft.VisualStudioCodeInsiders-User-x86_v1.54.1.52838cf679
  manifests/Microsoft/VisualStudioCodeInsiders-User-x86/1.54.1.52838cf679.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#7007 Microsoft.VisualStudioCodeInsiders-User-x64_v1.54.1.52838cf679
  manifests/Microsoft/VisualStudioCodeInsiders-User-x64/1.54.1.52838cf679.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#7008 Microsoft.VisualStudioCodeInsiders-System-x86_v1.54.1.52838cf679
  manifests/Microsoft/VisualStudioCodeInsiders-System-x86/1.54.1.52838cf679.yaml
Labels: Azure-Pipeline-Passed, MSFT-Verified, Validation-Completed

#6977 Added Microsoft Edge Beta version 89.0.774.18.
  manifests/Microsoft/EdgeBeta/89.0.774.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#6957 add SAGA GIS
  manifests/SAGAUserGroupAssociation/SAGAGIS/7.9.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7010 Added Microsoft Edge version 88.0.705.62.
  manifests/Microsoft/Edge/88.0.705.62.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7012 Added AWS CLI version 2.1.24.
  manifests/Amazon/AWSCLI/2.1.24.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7014 Microsoft.PowerToys version 0.31.2
  manifests/Microsoft/PowerToys/0.31.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7011 Added Unity Editor version 2020.2.3.
  manifests/UnityTechnologies/Unity/2020.2.3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7013 Added Mozilla Firefox version 85.0.1.
  manifests/Mozilla/Firefox/85.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7021 Node.js Nightly version 16.0.0-20210205
  manifests/OpenJS/NodeJSNightly/16.0.0-20210205.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7018 VLC media player nightly version 4.0.0-20210205
  manifests/VideoLAN/VLCNightly/4.0.0-20210205.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7019 Fix URL for VLC media player version 3.0.12
  manifests/VideoLAN/VLC/3.0.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7022 Microsoft OneDrive Internal Fast version 21.024.0203.0002
  manifests/Microsoft/OneDriveInternalFast/21.024.0203.0002.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7028 Hash Update For MabelTerm 1.4.1
  manifests/MabelisYT/MabelTerm/1.4.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7032 Update Netron to 4.7.6
  manifests/LutzRoeder/Netron/4.7.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7031 Added MabelTerm Snapshot
  manifests/MabelisYT/MabelTermSnap/1.4.2-Snap3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7034 Add Go 1.15.8
  manifests/Golang/Go/1.15.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7033 Add OpenSCAD 2021.01
  manifests/OpenSCAD/OpenSCAD/2021.01.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7036 Update To 1.4.2-Snap4 Snapshot MabelTerm
  manifests/MabelisYT/MabelTermSnap/1.4.2-Snap4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7037 Add OpenHashTab v3.0.1 update
  manifests/namazso/OpenHashTab/3.0.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7042 alterego 1.569
  manifests/plogue/alterego/1.569.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7041 Microsoft OneDrive Internal Fast version 21.025.0204.0001
  manifests/Microsoft/OneDriveInternalFast/21.025.0204.0001.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7040 Node.js Nightly version 16.0.0-20210206
  manifests/OpenJS/NodeJSNightly/16.0.0-20210206.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7038 VLC media player nightly version 4.0.0-20210206
  manifests/VideoLAN/VLCNightly/4.0.0-20210206.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7046 Fix URL for SAGA GIS version 7.9.0.0
  manifests/SAGAUserGroupAssociation/SAGAGIS/7.9.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7061 Remove manifest that no longer works for Oracle VM VirtualBox Development version 6.1.97-141967
  manifests/Oracle/VirtualBoxDevelopment/6.1.97-141967.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7059 Remove manifest that no longer works for Tor Browser version 10.0.8
  manifests/TorProject/TorBrowser/10.0.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#7057 Remove manifest that no longer works for pgAdmin4 version 4.22.0.0
  manifests/PostgreSQL/pgAdmin/4.22.0.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
