Repository microsoft/winget-pkgs, pull requests merged in 2021-07, with the labels that each got.

#19429 Added vim.vim version 8.2.3081
  manifests/v/vim/vim/8.2.3081/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.3081/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.3081/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19433 GitHub.cli version 1.12.1
  manifests/g/GitHub/cli/1.12.1/GitHub.cli.installer.yaml
  manifests/g/GitHub/cli/1.12.1/GitHub.cli.locale.en-US.yaml
  manifests/g/GitHub/cli/1.12.1/GitHub.cli.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19432 Added BraveSoftware.BraveBrowser version 91.1.26.74
  manifests/b/BraveSoftware/BraveBrowser/91.1.26.74/BraveSoftware.BraveBrowser.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/91.1.26.74/BraveSoftware.BraveBrowser.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/91.1.26.74/BraveSoftware.BraveBrowser.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19355 Renoise.Renoise version 3.3.2
  manifests/r/Renoise/Renoise/3.3.2/Renoise.Renoise.installer.yaml
  manifests/r/Renoise/Renoise/3.3.2/Renoise.Renoise.locale.en-US.yaml
  manifests/r/Renoise/Renoise/3.3.2/Renoise.Renoise.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19392 Added IntelliJ IDEA Ultimate Edition version 211.7628.21.
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/211.7628.21/JetBrains.IntelliJIDEA.Ultimate.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/211.7628.21/JetBrains.IntelliJIDEA.Ultimate.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/211.7628.21/JetBrains.IntelliJIDEA.Ultimate.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19391 Added IntelliJ IDEA Community Edition version 211.7628.21.
  manifests/j/JetBrains/IntelliJIDEA/Community/211.7628.21/JetBrains.IntelliJIDEA.Community.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/211.7628.21/JetBrains.IntelliJIDEA.Community.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/211.7628.21/JetBrains.IntelliJIDEA.Community.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19403 Add Mirantis.Lens 5.0.0
  manifests/m/Mirantis/Lens/5.0.0/Mirantis.Lens.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19405 Added WinSCP.WinSCP version 5.19.1
  manifests/w/WinSCP/WinSCP/5.19.1/WinSCP.WinSCP.installer.yaml
  manifests/w/WinSCP/WinSCP/5.19.1/WinSCP.WinSCP.locale.en-US.yaml
  manifests/w/WinSCP/WinSCP/5.19.1/WinSCP.WinSCP.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19411 UnityTechnologies.Unity version 2021.1.13f1
  manifests/u/UnityTechnologies/Unity/2021.1.13f1/UnityTechnologies.Unity.installer.yaml
  manifests/u/UnityTechnologies/Unity/2021.1.13f1/UnityTechnologies.Unity.locale.en-US.yaml
  manifests/u/UnityTechnologies/Unity/2021.1.13f1/UnityTechnologies.Unity.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19418 Added hello-efficiency-inc.raven-reader version 1.0.62
  manifests/h/hello-efficiency-inc/raven-reader/1.0.62/hello-efficiency-inc.raven-reader.installer.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.62/hello-efficiency-inc.raven-reader.locale.en-US.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.62/hello-efficiency-inc.raven-reader.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19424 Added Bitwarden.Bitwarden version 1.27.0
  manifests/b/Bitwarden/Bitwarden/1.27.0/Bitwarden.Bitwarden.installer.yaml
  manifests/b/Bitwarden/Bitwarden/1.27.0/Bitwarden.Bitwarden.locale.en-US.yaml
  manifests/b/Bitwarden/Bitwarden/1.27.0/Bitwarden.Bitwarden.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19356 Added Visual Studio Team Explorer 2019 version 16.10.31424.327.
  manifests/m/Microsoft/VisualStudio/2019/TeamExplorer/16.10.31424.327/Microsoft.VisualStudio.2019.TeamExplorer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19431 Added Amazon.SAM-CLI version 1.24.1
  manifests/a/Amazon/SAM-CLI/1.24.1/Amazon.SAM-CLI.installer.yaml
  manifests/a/Amazon/SAM-CLI/1.24.1/Amazon.SAM-CLI.locale.en-US.yaml
  manifests/a/Amazon/SAM-CLI/1.24.1/Amazon.SAM-CLI.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19435 Update Bandisoft.Bandizip SHA256
  manifests/b/Bandisoft/Bandizip/7.17/Bandisoft.Bandizip.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19444 Added KDE.KDEConnect version 21.04.2.636
  manifests/k/KDE/KDEConnect/21.04.2.636/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.2.636/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.2.636/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19443 Added Microsoft.Teams version 1.4.00.16575
  manifests/m/Microsoft/Teams/1.4.00.16575/Microsoft.Teams.installer.yaml
  manifests/m/Microsoft/Teams/1.4.00.16575/Microsoft.Teams.locale.en-US.yaml
  manifests/m/Microsoft/Teams/1.4.00.16575/Microsoft.Teams.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19439 Added Microsoft Edge Dev version 93.0.933.1.
  manifests/m/Microsoft/EdgeDev/93.0.933.1/Microsoft.EdgeDev.installer.yaml
  manifests/m/Microsoft/EdgeDev/93.0.933.1/Microsoft.EdgeDev.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDev/93.0.933.1/Microsoft.EdgeDev.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19393 Added Jabra Direct 5.5.39795
  manifests/j/Jabra/Direct/5.5.39795/Jabra.Direct.installer.yaml
  manifests/j/Jabra/Direct/5.5.39795/Jabra.Direct.locale.en-US.yaml
  manifests/j/Jabra/Direct/5.5.39795/Jabra.Direct.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19446 Changed installer to signed for vim.vim version 8.2.3081
  manifests/v/vim/vim/8.2.3081/vim.vim.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19445 404 Not Found: KDE.KDEConnect version 21.04.2.631
  manifests/k/KDE/KDEConnect/21.04.2.631/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.2.631/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.2.631/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19415 WilbertBerendsen.Frescobaldi version 3.1.3
  manifests/w/WilbertBerendsen/Frescobaldi/3.1.3/WilbertBerendsen.Frescobaldi.installer.yaml
  manifests/w/WilbertBerendsen/Frescobaldi/3.1.3/WilbertBerendsen.Frescobaldi.locale.en-US.yaml
  manifests/w/WilbertBerendsen/Frescobaldi/3.1.3/WilbertBerendsen.Frescobaldi.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19447 Add Signal version 5.7.1
  manifests/o/OpenWhisperSystems/Signal/5.7.1/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/5.7.1/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/5.7.1/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19448 Add Signal Beta version 5.8.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/5.8.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.8.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.8.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19449 Affine legal details about the project
  manifests/a/AltDrag/AltDrag/1.4/AltDrag.AltDrag.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19387 Fixed UpgradeBehavior for StrawberryPerl.StrawberryPerl v5.32.1001
  manifests/s/StrawberryPerl/StrawberryPerl/5.32.1001/StrawberryPerl.StrawberryPerl.installer.yaml
  manifests/s/StrawberryPerl/StrawberryPerl/5.32.1001/StrawberryPerl.StrawberryPerl.locale.en-US.yaml
  manifests/s/StrawberryPerl/StrawberryPerl/5.32.1001/StrawberryPerl.StrawberryPerl.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#18116 Added Metadata for SageMath.SageMath v9.2
  manifests/s/SageMath/SageMath/9.2/SageMath.SageMath.installer.yaml
  manifests/s/SageMath/SageMath/9.2/SageMath.SageMath.locale.en-US.yaml
  manifests/s/SageMath/SageMath/9.2/SageMath.SageMath.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19450 Added Octopus Deploy Tentacle version 6.1.763.
  manifests/o/OctopusDeploy/Tentacle/6.1.763/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.763/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.763/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19430 Added Amazon.SAM-CLI version 1.24.0
  manifests/a/Amazon/SAM-CLI/1.24.0/Amazon.SAM-CLI.installer.yaml
  manifests/a/Amazon/SAM-CLI/1.24.0/Amazon.SAM-CLI.locale.en-US.yaml
  manifests/a/Amazon/SAM-CLI/1.24.0/Amazon.SAM-CLI.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19441 Shotcut version 21.06.29
  manifests/m/Meltytech/Shotcut/21.06.29/Meltytech.Shotcut.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19453 Microsoft.VisualStudioCode.Insiders_v1.58.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.58.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19457 BBC iPlayer version 2.13.3
  manifests/b/BBC/iPlayer/2.13.3/BBC.iPlayer.installer.yaml
  manifests/b/BBC/iPlayer/2.13.3/BBC.iPlayer.locale.en-GB.yaml
  manifests/b/BBC/iPlayer/2.13.3/BBC.iPlayer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19451 Added balena-cli version 12.44.23.
  manifests/b/Balena/BalenaCLI/12.44.23/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/12.44.23/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/12.44.23/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19465 Ubisoft.Connect version 123.1.0.10526
  manifests/u/Ubisoft/Connect/123.1.0.10526/Ubisoft.Connect.installer.yaml
  manifests/u/Ubisoft/Connect/123.1.0.10526/Ubisoft.Connect.locale.en-US.yaml
  manifests/u/Ubisoft/Connect/123.1.0.10526/Ubisoft.Connect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19460 Microsoft.VisualStudioCode.Insiders_v1.58.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.58.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19463 Update BLC 3.2.0 -> 3.2.4
  manifests/b/Badlion/BadlionClient/3.2.4/Badlion.BadlionClient.installer.yaml
  manifests/b/Badlion/BadlionClient/3.2.4/Badlion.BadlionClient.locale.en-US.yaml
  manifests/b/Badlion/BadlionClient/3.2.4/Badlion.BadlionClient.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19476 Update SlackTechnologies.Slack.Beta v4.17.0-beta1 -> v4.18.0-beta1
  manifests/s/SlackTechnologies/Slack/Beta/4.18.0-beta1/SlackTechnologies.Slack.Beta.installer.yaml
  manifests/s/SlackTechnologies/Slack/Beta/4.18.0-beta1/SlackTechnologies.Slack.Beta.locale.en-US.yaml
  manifests/s/SlackTechnologies/Slack/Beta/4.18.0-beta1/SlackTechnologies.Slack.Beta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19419 Amarok.Amarok version 2.8.0
  manifests/k/KDE/Amarok/2.8.0/KDE.Amarok.installer.yaml
  manifests/k/KDE/Amarok/2.8.0/KDE.Amarok.locale.en-US.yaml
  manifests/k/KDE/Amarok/2.8.0/KDE.Amarok.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19467 TrackerSoftware.PDF-XChangeEditor version 9.0.354.0
  manifests/t/TrackerSoftware/PDF-XChangeEditor/9.0.354.0/TrackerSoftware.PDF-XChangeEditor.installer.yaml
  manifests/t/TrackerSoftware/PDF-XChangeEditor/9.0.354.0/TrackerSoftware.PDF-XChangeEditor.locale.en-US.yaml
  manifests/t/TrackerSoftware/PDF-XChangeEditor/9.0.354.0/TrackerSoftware.PDF-XChangeEditor.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19472 TrackerSoftware.PDF-Tools version 9.0.354.0
  manifests/t/TrackerSoftware/PDF-Tools/9.0.354.0/TrackerSoftware.PDF-Tools.installer.yaml
  manifests/t/TrackerSoftware/PDF-Tools/9.0.354.0/TrackerSoftware.PDF-Tools.locale.en-US.yaml
  manifests/t/TrackerSoftware/PDF-Tools/9.0.354.0/TrackerSoftware.PDF-Tools.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19475 TrackerSoftware.PDF-XChangePRO version 9.0.354.0
  manifests/t/TrackerSoftware/PDF-XChangePRO/9.0.354.0/TrackerSoftware.PDF-XChangePRO.installer.yaml
  manifests/t/TrackerSoftware/PDF-XChangePRO/9.0.354.0/TrackerSoftware.PDF-XChangePRO.locale.en-US.yaml
  manifests/t/TrackerSoftware/PDF-XChangePRO/9.0.354.0/TrackerSoftware.PDF-XChangePRO.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19490 Added GrafanaLabs.GrafanaEnterprise version 8.0.4.0
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.0.4.0/GrafanaLabs.GrafanaEnterprise.installer.yaml
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.0.4.0/GrafanaLabs.GrafanaEnterprise.locale.en-US.yaml
  manifests/g/GrafanaLabs/GrafanaEnterprise/8.0.4.0/GrafanaLabs.GrafanaEnterprise.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19489 Added GrafanaLabs.GrafanaOSS version 8.0.4.0
  manifests/g/GrafanaLabs/GrafanaOSS/8.0.4.0/GrafanaLabs.GrafanaOSS.installer.yaml
  manifests/g/GrafanaLabs/GrafanaOSS/8.0.4.0/GrafanaLabs.GrafanaOSS.locale.en-US.yaml
  manifests/g/GrafanaLabs/GrafanaOSS/8.0.4.0/GrafanaLabs.GrafanaOSS.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19479 Microsoft.PowerToys version 0.41.4
  manifests/m/Microsoft/PowerToys/0.41.4/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.41.4/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.41.4/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19459 Updated Viber.Viber to v15.6.0.3
  manifests/v/Viber/Viber/15.6.0.3/Viber.Viber.installer.yaml
  manifests/v/Viber/Viber/15.6.0.3/Viber.Viber.locale.en-US.yaml
  manifests/v/Viber/Viber/15.6.0.3/Viber.Viber.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19461 Deleted old Google.Chrome.Beta v68.104.49222
  manifests/g/Google/Chrome/Beta/68.104.49222/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/68.104.49222/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/68.104.49222/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19469 Manifest Update for RoonLabs.RoonServer v1.8
  manifests/r/RoonLabs/RoonServer/1.8 (build 795) stable/RoonLabs.RoonServer.installer.yaml
  manifests/r/RoonLabs/RoonServer/1.8 (build 795) stable/RoonLabs.RoonServer.locale.en-US.yaml
  manifests/r/RoonLabs/RoonServer/1.8 (build 795) stable/RoonLabs.RoonServer.yaml
  manifests/r/RoonLabs/RoonServer/latest/RoonLabs.RoonServer.installer.yaml
  manifests/r/RoonLabs/RoonServer/latest/RoonLabs.RoonServer.locale.en-US.yaml
  manifests/r/RoonLabs/RoonServer/latest/RoonLabs.RoonServer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19468 Manifest Update for RoonLabs.Roon v1.8
  manifests/r/RoonLabs/Roon/1.8 (build 795) stable/RoonLabs.Roon.installer.yaml
  manifests/r/RoonLabs/Roon/1.8 (build 795) stable/RoonLabs.Roon.locale.en-US.yaml
  manifests/r/RoonLabs/Roon/1.8 (build 795) stable/RoonLabs.Roon.yaml
  manifests/r/RoonLabs/Roon/latest/RoonLabs.Roon.installer.yaml
  manifests/r/RoonLabs/Roon/latest/RoonLabs.Roon.locale.en-US.yaml
  manifests/r/RoonLabs/Roon/latest/RoonLabs.Roon.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19473 Moved LINQPad.LINQPad.5
  manifests/l/LINQPad/LINQPad/5/5.43.00/LINQPad.LINQPad.5.installer.yaml
  manifests/l/LINQPad/LINQPad/5/5.43.00/LINQPad.LINQPad.5.locale.en-US.yaml
  manifests/l/LINQPad/LINQPad/5/5.43.00/LINQPad.LINQPad.5.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Possible-Duplicate, Validation-Completed

#19466 Manifest Update for RoonLabs.RoonBridge 1.7
  manifests/r/RoonLabs/RoonBridge/1.7 (build 571) stable/RoonLabs.RoonBridge.installer.yaml
  manifests/r/RoonLabs/RoonBridge/1.7 (build 571) stable/RoonLabs.RoonBridge.locale.en-US.yaml
  manifests/r/RoonLabs/RoonBridge/1.7 (build 571) stable/RoonLabs.RoonBridge.yaml
  manifests/r/RoonLabs/RoonBridge/latest/RoonLabs.RoonBridge.installer.yaml
  manifests/r/RoonLabs/RoonBridge/latest/RoonLabs.RoonBridge.locale.en-US.yaml
  manifests/r/RoonLabs/RoonBridge/latest/RoonLabs.RoonBridge.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Retry-1, Validation-Completed

#19464 Updated Dialpad.Dialpad to v19.4.1
  manifests/d/Dialpad/Dialpad/19.4.0/Dialpad.Dialpad.yaml
  manifests/d/Dialpad/Dialpad/19.4.1/Dialpad.Dialpad.installer.yaml
  manifests/d/Dialpad/Dialpad/19.4.1/Dialpad.Dialpad.locale.en-US.yaml
  manifests/d/Dialpad/Dialpad/19.4.1/Dialpad.Dialpad.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19477 Moved LINQPad.LINQPad.6
  manifests/l/LINQPad/LINQPad/6/6.13.13/LINQPad.LINQPad.6.installer.yaml
  manifests/l/LINQPad/LINQPad/6/6.13.13/LINQPad.LINQPad.6.locale.en-US.yaml
  manifests/l/LINQPad/LINQPad/6/6.13.13/LINQPad.LINQPad.6.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Possible-Duplicate, Validation-Completed

#19474 Removed old LINQPad.LINQPad5
  manifests/l/LINQPad/LINQPad5/latest/LINQPad.LINQPad5.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19478 Deleted old LINQPad.LINQPad6
  manifests/l/LINQPad/LINQPad6/latest/LINQPad.LINQPad6.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19481 Manifest Update for TunnelBear.TunnelBear v4.4.5.0
  manifests/t/TunnelBear/TunnelBear/4.4.5.0/TunnelBear.TunnelBear.installer.yaml
  manifests/t/TunnelBear/TunnelBear/4.4.5.0/TunnelBear.TunnelBear.locale.en-US.yaml
  manifests/t/TunnelBear/TunnelBear/4.4.5.0/TunnelBear.TunnelBear.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19483 Manifest Update for AdoptOpenJDK.OpenJDK.8 v8.0.292.10
  manifests/a/AdoptOpenJDK/OpenJDK/8/8.0.292.10/AdoptOpenJDK.OpenJDK.8.installer.yaml
  manifests/a/AdoptOpenJDK/OpenJDK/8/8.0.292.10/AdoptOpenJDK.OpenJDK.8.locale.en-US.yaml
  manifests/a/AdoptOpenJDK/OpenJDK/8/8.0.292.10/AdoptOpenJDK.OpenJDK.8.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19484 Manifest Update for AdoptOpenJDK.OpenJDK.11 v11.0.11.9
  manifests/a/AdoptOpenJDK/OpenJDK/11/11.0.11.9/AdoptOpenJDK.OpenJDK.11.installer.yaml
  manifests/a/AdoptOpenJDK/OpenJDK/11/11.0.11.9/AdoptOpenJDK.OpenJDK.11.locale.en-US.yaml
  manifests/a/AdoptOpenJDK/OpenJDK/11/11.0.11.9/AdoptOpenJDK.OpenJDK.11.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19495 Deleted old BitSum.ProcessLassoBeta
  manifests/b/BitSum/ProcessLassoBeta/10.1.0.42/BitSum.ProcessLassoBeta.installer.yaml
  manifests/b/BitSum/ProcessLassoBeta/10.1.0.42/BitSum.ProcessLassoBeta.locale.en-US.yaml
  manifests/b/BitSum/ProcessLassoBeta/10.1.0.42/BitSum.ProcessLassoBeta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19486 Removed non unattended WesternDigitalCorporation.WesternDigitalDashboard
  manifests/w/WesternDigitalCorporation/WesternDigitalDashboard/3.2.2.9/WesternDigitalCorporation.WesternDigitalDashboard.installer.yaml
  manifests/w/WesternDigitalCorporation/WesternDigitalDashboard/3.2.2.9/WesternDigitalCorporation.WesternDigitalDashboard.locale.en-US.yaml
  manifests/w/WesternDigitalCorporation/WesternDigitalDashboard/3.2.2.9/WesternDigitalCorporation.WesternDigitalDashboard.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19485 Removed non unattended WesternDigital.SanDiskSSDDashboard
  manifests/w/WesternDigital/SanDiskSSDDashboard/3.2.2.9/WesternDigital.SanDiskSSDDashboard.installer.yaml
  manifests/w/WesternDigital/SanDiskSSDDashboard/3.2.2.9/WesternDigital.SanDiskSSDDashboard.locale.en-US.yaml
  manifests/w/WesternDigital/SanDiskSSDDashboard/3.2.2.9/WesternDigital.SanDiskSSDDashboard.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19290 Added Python.Python.3 version 3.9.6150.0
  manifests/p/Python/Python/3/3.9.6150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.9.6150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.9.6150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19523 Added OctopusDeploy.Tentacle version 6.1.775
  manifests/o/OctopusDeploy/Tentacle/6.1.775/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.775/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.775/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19522 Added Microsoft.Edge version 91.0.864.64
  manifests/m/Microsoft/Edge/91.0.864.64/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/91.0.864.64/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/91.0.864.64/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19520 Added Tencent.TencentMeeting 2.11.4.417
  manifests/t/Tencent/TencentMeeting/2.11.4.417/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19492 Node.JS version 16.4.1
  manifests/o/OpenJS/NodeJS/16.4.1/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/16.4.1/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/16.4.1/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19381 Updated OpenRA installer with x86 architecture MinimumOS and a few more things
  manifests/o/OpenRA/OpenRA/20210321/OpenRA.OpenRA.installer.yaml
  manifests/o/OpenRA/OpenRA/20210321/OpenRA.OpenRA.locale.en-US.yaml
  manifests/o/OpenRA/OpenRA/20210321/OpenRA.OpenRA.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19320 Add ProductCode to Microsoft.VC++2010Redist-x86
  manifests/m/Microsoft/VC++2010Redist-x86/10.0.40219/Microsoft.VC++2010Redist-x86.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19319 Add ProductCode to Microsoft.VC++2008Redist-x86
  manifests/m/Microsoft/VC++2008Redist-x86/9.0.30729.6161/Microsoft.VC++2008Redist-x86.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19364 Updated Python.Python.3 version 3.9.2150.0
  manifests/p/Python/Python/3/3.9.2/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.9.2150.0/Python.Python.3.installer.yaml
  manifests/p/Python/Python/3/3.9.2150.0/Python.Python.3.locale.en-US.yaml
  manifests/p/Python/Python/3/3.9.2150.0/Python.Python.3.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19471 TrackerSoftware.PDF-XChangeStandard version 9.0.354.0
  manifests/t/TrackerSoftware/PDF-XChangeStandard/9.0.354.0/TrackerSoftware.PDF-XChangeStandard.installer.yaml
  manifests/t/TrackerSoftware/PDF-XChangeStandard/9.0.354.0/TrackerSoftware.PDF-XChangeStandard.locale.en-US.yaml
  manifests/t/TrackerSoftware/PDF-XChangeStandard/9.0.354.0/TrackerSoftware.PDF-XChangeStandard.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19499 e2eSoft.iVCam 6.2.2
  manifests/e/e2eSoft/iVCam/6.2.2/e2eSoft.iVCam.installer.yaml
  manifests/e/e2eSoft/iVCam/6.2.2/e2eSoft.iVCam.locale.en-US.yaml
  manifests/e/e2eSoft/iVCam/6.2.2/e2eSoft.iVCam.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19524 Updated Mirasoft.AnyVizCloudAdapter to Version 0.9.04
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.0.4/Mirasoft.AnyVizCloudAdapter.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19413 ChrisBagwell.SoX version 14.4.2
  manifests/c/ChrisBagwell/SoX/14.4.2/ChrisBagwell.SoX.installer.yaml
  manifests/c/ChrisBagwell/SoX/14.4.2/ChrisBagwell.SoX.locale.en-US.yaml
  manifests/c/ChrisBagwell/SoX/14.4.2/ChrisBagwell.SoX.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19370 FSN.TyperspeedSepia version 3.0
  manifests/f/FSN/TyperspeedSepia/3.0/FSN.TyperspeedSepia.installer.yaml
  manifests/f/FSN/TyperspeedSepia/3.0/FSN.TyperspeedSepia.locale.en-GB.yaml
  manifests/f/FSN/TyperspeedSepia/3.0/FSN.TyperspeedSepia.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19494 Moved BitSum.ProcessLasso.Beta
  manifests/b/BitSum/ProcessLasso/Beta/10.2.0.3/BitSum.ProcessLasso.Beta.installer.yaml
  manifests/b/BitSum/ProcessLasso/Beta/10.2.0.3/BitSum.ProcessLasso.Beta.locale.en-US.yaml
  manifests/b/BitSum/ProcessLasso/Beta/10.2.0.3/BitSum.ProcessLasso.Beta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19496 Manifest Update for BitSum.ProcessLasso v10.1.0.42
  manifests/b/BitSum/ProcessLasso/10.1.0.42/BitSum.ProcessLasso.installer.yaml
  manifests/b/BitSum/ProcessLasso/10.1.0.42/BitSum.ProcessLasso.locale.en-US.yaml
  manifests/b/BitSum/ProcessLasso/10.1.0.42/BitSum.ProcessLasso.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19480 Deleted not working Windscribe.Windscribe
  manifests/w/Windscribe/Windscribe/latest/Windscribe.Windscribe.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19482 Manifest Update for Surfshark.SurfsharkVPN v2.8.4999
  manifests/s/Surfshark/SurfsharkVPN/2.8.4999/Surfshark.SurfsharkVPN.installer.yaml
  manifests/s/Surfshark/SurfsharkVPN/2.8.4999/Surfshark.SurfsharkVPN.locale.en-US.yaml
  manifests/s/Surfshark/SurfsharkVPN/2.8.4999/Surfshark.SurfsharkVPN.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19270 Added Zoom.Zoom version 5.7.543
  manifests/z/Zoom/Zoom/5.7.543/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/5.7.543/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/5.7.543/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Internal-Error-Dynamic-Scan, Moderator-Approved, Needs: Attention, Retry-1, Validation-Completed

#19526 Microsoft.VisualStudioCode.Insiders_v1.58.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.58.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19525 Added Prowise.ProwisePresenter v1.0.0
  manifests/p/Prowise/ProwisePresenter/1.0.0/Prowise.ProwisePresenter.installer.yaml
  manifests/p/Prowise/ProwisePresenter/1.0.0/Prowise.ProwisePresenter.locale.en-GB.yaml
  manifests/p/Prowise/ProwisePresenter/1.0.0/Prowise.ProwisePresenter.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19528 Added Telegram.TelegramDesktop v2.8.4
  manifests/t/Telegram/TelegramDesktop/2.8.4/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/2.8.4/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/2.8.4/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19513 WiseCleaner.com.WiseCare365 version 5.7.1
  manifests/w/WiseCleaner/WiseCare365/5.7.1/WiseCleaner.WiseCare365.installer.yaml
  manifests/w/WiseCleaner/WiseCare365/5.7.1/WiseCleaner.WiseCare365.locale.en-US.yaml
  manifests/w/WiseCleaner/WiseCare365/5.7.1/WiseCleaner.WiseCare365.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19534 Added AWS Command Line Interface version 2.2.16.0.
  manifests/a/Amazon/AWSCLI/2.2.16.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.2.16.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.2.16.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19535 Added KDE Connect version 21.04.2.637.
  manifests/k/KDE/KDEConnect/21.04.2.637/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/21.04.2.637/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/21.04.2.637/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19533 OpenMedia.4KVideoDownloader version 4.16.4.4300
  manifests/o/OpenMedia/4KVideoDownloader/4.16.4.4300/OpenMedia.4KVideoDownloader.installer.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.16.4.4300/OpenMedia.4KVideoDownloader.locale.en-US.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.16.4.4300/OpenMedia.4KVideoDownloader.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19536 Eugeny.Tabby version 1.0.144
  manifests/e/Eugeny/Tabby/1.0.144/Eugeny.Tabby.installer.yaml
  manifests/e/Eugeny/Tabby/1.0.144/Eugeny.Tabby.locale.en-US.yaml
  manifests/e/Eugeny/Tabby/1.0.144/Eugeny.Tabby.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19530 JFrog.Conan version 1.38.0
  manifests/j/JFrog/Conan/1.38.0/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/1.38.0/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/1.38.0/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19541 Remove LightkeySources.Lightkey; doesn't seem to install the application - blocked on EULA prompt
  manifests/l/LightkeySources/Lightkey/1.0.0.0/LightkeySources.Lightkey.installer.yaml
  manifests/l/LightkeySources/Lightkey/1.0.0.0/LightkeySources.Lightkey.locale.en-US.yaml
  manifests/l/LightkeySources/Lightkey/1.0.0.0/LightkeySources.Lightkey.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19551 Remove Keybase.Keybase version 5.6.0-20200528221358+040af40287
  manifests/k/Keybase/Keybase/5.6.0-20200528221358+040af40287/Keybase.Keybase.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19549 Remove Keybase.Keybase version 5.4.2-20200424170113+7b0bbf1e3c
  manifests/k/Keybase/Keybase/5.4.2-20200424170113+7b0bbf1e3c/Keybase.Keybase.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19552 Remove Kitware.CMake version 3.20.0-rc5
  manifests/k/Kitware/CMake/3.20.0-rc5/Kitware.CMake.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19550 Remove Kitware.CMake version 3.20.0-rc2
  manifests/k/Kitware/CMake/3.20.0-rc2/Kitware.CMake.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19540 ARP: MaLuns.wallhaven-electron
  manifests/m/MaLuns/wallhaven-electron/1.0.0/MaLuns.wallhaven-electron.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19555 Duplicate: Kakao.KakaoTalk
  manifests/k/Kakao/KakaoTalk/3.2.9.2808/Kakao.KakaoTalk.installer.yaml
  manifests/k/Kakao/KakaoTalk/3.2.9.2808/Kakao.KakaoTalk.locale.ko-KR.yaml
  manifests/k/Kakao/KakaoTalk/3.2.9.2808/Kakao.KakaoTalk.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19547 ARP: KCSoftwares.KCSoftwaresDUMo
  manifests/k/KCSoftwares/KCSoftwaresDUMo/2.23.7.117/KCSoftwares.KCSoftwaresDUMo.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19542 ARP: MRidgers.Clink
  manifests/m/MRidgers/Clink/0.4.9/MRidgers.Clink.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19539 ARP: MacPaw.Encrypto
  manifests/m/MacPaw/Encrypto/1.0.1/MacPaw.Encrypto.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19543 ARP: Kuro.Mery
  manifests/k/Kuro/Mery/2.6.7/Kuro.Mery.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19544 ARP: Kuro.MeryBeta
  manifests/k/Kuro/MeryBeta/3.2.5/Kuro.MeryBeta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19546 ARP: KCSoftwares.SUMo
  manifests/k/KCSoftwares/SUMo/5.12.16.494/KCSoftwares.SUMo.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19548 ARP: Julialang.Julia
  manifests/j/Julialang/Julia/1.6.1/Julialang.Julia.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19554 ARP: Kakao.KakaoTalk
  manifests/k/Kakao/KakaoTalk/3.2.9.2815/Kakao.KakaoTalk.locale.ko-KR.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19553 ARP: Keybase.Keybase
  manifests/k/Keybase/Keybase/5.6.0.13/Keybase.Keybase.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19537 Microsoft.VisualStudioCode.Insiders_v1.58.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.58.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19563 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2020.1.4212/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19564 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2021.2.5495/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19566 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2021.2.5595/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19568 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2020.2.4593/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19570 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2021.1.5282/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19567 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2020.5.5163/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19571 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2020.3.4761/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19569 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2021.1.5425/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19572 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2021.1.5307/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19573 Remove Datalust.Seq
  manifests/d/Datalust/Seq/2020.1.4235/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19560 ARP: Google.DriveFileStream
  manifests/g/Google/DriveFileStream/48.0.13.0/Google.DriveFileStream.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19559 ARP: Google.Chrome
  manifests/g/Google/Chrome/91.0.4472.124/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/91.0.4472.124/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/91.0.4472.124/Google.Chrome.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19556 ARP: Google.Chrome.Canary
  manifests/g/Google/Chrome/Canary/93.0.4563.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/93.0.4563.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/93.0.4563.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19562 ARP: DrewNaylor.UXL-Launcher
  manifests/d/DrewNaylor/UXL-Launcher/4.0.0.0/DrewNaylor.UXL-Launcher.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19565 ARP: Datalust.Seq
  manifests/d/Datalust/Seq/6.0.5647.0/Datalust.Seq.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19578 Remove BrickLink.Studio
  manifests/b/BrickLink/Studio/2.2.3_1/BrickLink.Studio.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19577 Remove BrickLink.Studio
  manifests/b/BrickLink/Studio/2.1.5_7/BrickLink.Studio.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19579 Remove BrickLink.Studio
  manifests/b/BrickLink/Studio/2.1.10_5/BrickLink.Studio.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19576 Remove BrickLink.Studio
  manifests/b/BrickLink/Studio/2.2.4_5/BrickLink.Studio.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19580 ARP: BrickLink.Studio
  manifests/b/BrickLink/Studio/2.0/BrickLink.Studio.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19583 Microsoft.EdgeWebView2Runtime version 91.0.864.64
  manifests/m/Microsoft/EdgeWebView2Runtime/91.0.864.64/Microsoft.EdgeWebView2Runtime.installer.yaml
  manifests/m/Microsoft/EdgeWebView2Runtime/91.0.864.64/Microsoft.EdgeWebView2Runtime.locale.en-US.yaml
  manifests/m/Microsoft/EdgeWebView2Runtime/91.0.864.64/Microsoft.EdgeWebView2Runtime.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19251 ARP: Rawns.Reddit-Wallpaper-Changer
  manifests/r/Rawns/Reddit-Wallpaper-Changer/1.0.13/Rawns.Reddit-Wallpaper-Changer.yaml
Labels: Azure-Pipeline-Passed, Needs: Attention, Policy-Test-2.3, Validation-Completed

#19582 Microsoft.Office version 16.0.14131.20278
  manifests/m/Microsoft/Office/16.0.14131.20278/Microsoft.Office.installer.yaml
  manifests/m/Microsoft/Office/16.0.14131.20278/Microsoft.Office.locale.en-US.yaml
  manifests/m/Microsoft/Office/16.0.14131.20278/Microsoft.Office.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19585 ARP: HHDSoftware.FreeHexEditorNeo
  manifests/h/HHDSoftware/FreeHexEditorNeo/6.44.01.6234/HHDSoftware.FreeHexEditorNeo.installer.yaml
  manifests/h/HHDSoftware/FreeHexEditorNeo/6.44.01.6234/HHDSoftware.FreeHexEditorNeo.locale.en-US.yaml
  manifests/h/HHDSoftware/FreeHexEditorNeo/6.44.01.6234/HHDSoftware.FreeHexEditorNeo.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19587 ARP: hql287.manta
  manifests/h/hql287/manta/1.1.4/hql287.manta.installer.yaml
  manifests/h/hql287/manta/1.1.4/hql287.manta.locale.en-US.yaml
  manifests/h/hql287/manta/1.1.4/hql287.manta.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19592 ARP: Hirschmann.NotebookFanControl
  manifests/h/Hirschmann/NotebookFanControl/1.6.3.0/Hirschmann.NotebookFanControl.installer.yaml
  manifests/h/Hirschmann/NotebookFanControl/1.6.3.0/Hirschmann.NotebookFanControl.locale.en-US.yaml
  manifests/h/Hirschmann/NotebookFanControl/1.6.3.0/Hirschmann.NotebookFanControl.yaml
  manifests/h/Hirschmann/NotebookFanControl/1.6.3/Hirschmann.NotebookFanControl.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19589 HyperspaceDev.HyperspaceDesktop v1.1.4
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.4/HyperspaceDev.HyperspaceDesktop.installer.yaml
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.4/HyperspaceDev.HyperspaceDesktop.locale.en-US.yaml
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.4/HyperspaceDev.HyperspaceDesktop.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19575 Create FastCopy.IPMsg.yaml
  manifests/f/FastCopy/IPMsg/5.0.3/FastCopy.IPMsg.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19588 ARP: HyperspaceDev.HyperspaceDesktop
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.3/HyperspaceDev.HyperspaceDesktop.installer.yaml
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.3/HyperspaceDev.HyperspaceDesktop.locale.en-US.yaml
  manifests/h/HyperspaceDev/HyperspaceDesktop/1.1.3/HyperspaceDev.HyperspaceDesktop.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19527 Added CartamundiDigital.Fundels v3.0.10
  manifests/c/CartamundiDigital/Fundels/3.0.10/CartamundiDigital.Fundels.installer.yaml
  manifests/c/CartamundiDigital/Fundels/3.0.10/CartamundiDigital.Fundels.locale.en-US.yaml
  manifests/c/CartamundiDigital/Fundels/3.0.10/CartamundiDigital.Fundels.locale.nl-NL.yaml
  manifests/c/CartamundiDigital/Fundels/3.0.10/CartamundiDigital.Fundels.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19561 ARP: Elastic.Winlogbeat
  manifests/e/Elastic/Winlogbeat/7.13.1/Elastic.Winlogbeat.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19545 FSN.TyperspeedSepia version 3.0.5
  manifests/f/FSN/TyperspeedSepia/3.0.5/FSN.TyperspeedSepia.installer.yaml
  manifests/f/FSN/TyperspeedSepia/3.0.5/FSN.TyperspeedSepia.locale.en-GB.yaml
  manifests/f/FSN/TyperspeedSepia/3.0.5/FSN.TyperspeedSepia.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19586 ARP: HMSoft.HMNISEdit
  manifests/h/HMSoft/HMNISEdit/2.0.3/HMSoft.HMNISEdit.installer.yaml
  manifests/h/HMSoft/HMNISEdit/2.0.3/HMSoft.HMNISEdit.locale.en-US.yaml
  manifests/h/HMSoft/HMNISEdit/2.0.3/HMSoft.HMNISEdit.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19591 Updated TeamViewer.TeamViewerHost from v15.18.4 to v15.19.5
  manifests/t/TeamViewer/TeamViewerHost/15.18.4/TeamViewer.TeamViewerHost.installer.yaml
  manifests/t/TeamViewer/TeamViewerHost/15.19.5/TeamViewer.TeamViewerHost.installer.yaml
  manifests/t/TeamViewer/TeamViewerHost/15.19.5/TeamViewer.TeamViewerHost.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewerHost/15.19.5/TeamViewer.TeamViewerHost.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19605 SystweakSoftware.DuplicatePhotosFixerPro version 1.1.1086.12326
  manifests/s/SystweakSoftware/DuplicatePhotosFixerPro/1.1.1086.12326/SystweakSoftware.DuplicatePhotosFixerPro.installer.yaml
  manifests/s/SystweakSoftware/DuplicatePhotosFixerPro/1.1.1086.12326/SystweakSoftware.DuplicatePhotosFixerPro.locale.en-US.yaml
  manifests/s/SystweakSoftware/DuplicatePhotosFixerPro/1.1.1086.12326/SystweakSoftware.DuplicatePhotosFixerPro.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19590 Updated TeamViewer.TeamViewer from v15.19.3 to v15.19.5
  manifests/t/TeamViewer/TeamViewer/15.19.5/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.19.5/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.19.5/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Needs: Attention, Validation-Completed

#19599 Manifest Update for Greenshot.Greenshot
  manifests/g/Greenshot/Greenshot/1.2.10.6/Greenshot.Greenshot.installer.yaml
  manifests/g/Greenshot/Greenshot/1.2.10.6/Greenshot.Greenshot.locale.en-US.yaml
  manifests/g/Greenshot/Greenshot/1.2.10.6/Greenshot.Greenshot.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19595 ARP: HR.Crypter
  manifests/h/HR/Crypter/4.0.0/HR.Crypter.installer.yaml
  manifests/h/HR/Crypter/4.0.0/HR.Crypter.locale.en-US.yaml
  manifests/h/HR/Crypter/4.0.0/HR.Crypter.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19593 ARP: HakuNeko.HakuNeko
  manifests/h/HakuNeko/HakuNeko/6.1.7/HakuNeko.HakuNeko.installer.yaml
  manifests/h/HakuNeko/HakuNeko/6.1.7/HakuNeko.HakuNeko.locale.en-US.yaml
  manifests/h/HakuNeko/HakuNeko/6.1.7/HakuNeko.HakuNeko.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19603 ARP: SatisfactoryModding.SatisfactoryModManager
  manifests/s/SatisfactoryModding/SatisfactoryModManager/2.4.4/SatisfactoryModding.SatisfactoryModManager.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19597 ARP: HamsterRepublic.BobTheHamsterVGA
  manifests/h/HamsterRepublic/BobTheHamsterVGA/1.0/HamsterRepublic.BobTheHamsterVGA.installer.yaml
  manifests/h/HamsterRepublic/BobTheHamsterVGA/1.0/HamsterRepublic.BobTheHamsterVGA.locale.en-US.yaml
  manifests/h/HamsterRepublic/BobTheHamsterVGA/1.0/HamsterRepublic.BobTheHamsterVGA.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19604 SatisfactoryModding.SatisfactoryModManager v2.5.0
  manifests/s/SatisfactoryModding/SatisfactoryModManager/2.5.0/SatisfactoryModding.SatisfactoryModManager.installer.yaml
  manifests/s/SatisfactoryModding/SatisfactoryModManager/2.5.0/SatisfactoryModding.SatisfactoryModManager.locale.en-US.yaml
  manifests/s/SatisfactoryModding/SatisfactoryModManager/2.5.0/SatisfactoryModding.SatisfactoryModManager.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19598 ARP: HamsterRepublic.OHRRPGCE
  manifests/h/HamsterRepublic/OHRRPGCE/2020.05.02.11799/HamsterRepublic.OHRRPGCE.installer.yaml
  manifests/h/HamsterRepublic/OHRRPGCE/2020.05.02.11799/HamsterRepublic.OHRRPGCE.locale.en-US.yaml
  manifests/h/HamsterRepublic/OHRRPGCE/2020.05.02.11799/HamsterRepublic.OHRRPGCE.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19574 Upgrade from 1.44 to 1.45
  manifests/a/AltDrag/AltDrag/1.45/AltDrag.AltDrag.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19623 Updating LINE.LINE to version 7.0.3.2555
  manifests/l/LINE/LINE/7.0.3.2555/LINE.LINE.installer.yaml
  manifests/l/LINE/LINE/7.0.3.2555/LINE.LINE.locale.en-US.yaml
  manifests/l/LINE/LINE/7.0.3.2555/LINE.LINE.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed

#19622 Stardock.Start10 version 1.97
  manifests/s/Stardock/Start10/1.97/Stardock.Start10.installer.yaml
  manifests/s/Stardock/Start10/1.97/Stardock.Start10.locale.en-US.yaml
  manifests/s/Stardock/Start10/1.97/Stardock.Start10.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, Validation-Completed
