Repository microsoft/winget-pkgs, pull requests merged in 2022-08, with the labels that each got.

#68230 Update: Tencent.COSBrowser version 2.8.7
  manifests/t/Tencent/COSBrowser/2.8.7/Tencent.COSBrowser.installer.yaml
  manifests/t/Tencent/COSBrowser/2.8.7/Tencent.COSBrowser.locale.en-US.yaml
  manifests/t/Tencent/COSBrowser/2.8.7/Tencent.COSBrowser.locale.zh-CN.yaml
  manifests/t/Tencent/COSBrowser/2.8.7/Tencent.COSBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68267 Remove: Azul.Zulu.18 version 18.32.11
  manifests/a/Azul/Zulu/18/18.32.11/Azul.Zulu.18.installer.yaml
  manifests/a/Azul/Zulu/18/18.32.11/Azul.Zulu.18.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/18.32.11/Azul.Zulu.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68235 Update: Tencent.VooVMeeting version 3.9.1.512
  manifests/t/Tencent/VooVMeeting/3.9.1.512/Tencent.VooVMeeting.installer.yaml
  manifests/t/Tencent/VooVMeeting/3.9.1.512/Tencent.VooVMeeting.locale.en-US.yaml
  manifests/t/Tencent/VooVMeeting/3.9.1.512/Tencent.VooVMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/VooVMeeting/3.9.1.512/Tencent.VooVMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68153 New version: JetBrains.WebStorm version 222.3345.108
  manifests/j/JetBrains/WebStorm/222.3345.108/JetBrains.WebStorm.installer.yaml
  manifests/j/JetBrains/WebStorm/222.3345.108/JetBrains.WebStorm.locale.en-US.yaml
  manifests/j/JetBrains/WebStorm/222.3345.108/JetBrains.WebStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68149 New version: JetBrains.RubyMine version 222.3345.111
  manifests/j/JetBrains/RubyMine/222.3345.111/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/222.3345.111/JetBrains.RubyMine.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/222.3345.111/JetBrains.RubyMine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68233 Update: Tencent.QiDian version 5.3.0.19113
  manifests/t/Tencent/QiDian/5.3.0.19113/Tencent.QiDian.installer.yaml
  manifests/t/Tencent/QiDian/5.3.0.19113/Tencent.QiDian.locale.en-US.yaml
  manifests/t/Tencent/QiDian/5.3.0.19113/Tencent.QiDian.locale.zh-CN.yaml
  manifests/t/Tencent/QiDian/5.3.0.19113/Tencent.QiDian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68206 Update: Redisant.ZooKeeperAssistant version 1.0.8.4
  manifests/r/Redisant/ZooKeeperAssistant/1.0.8.4/Redisant.ZooKeeperAssistant.installer.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.8.4/Redisant.ZooKeeperAssistant.locale.en-US.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.8.4/Redisant.ZooKeeperAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.8.4/Redisant.ZooKeeperAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68180 Update: NetEase.MailMaster version 4.17.4.1011
  manifests/n/NetEase/MailMaster/4.17.4.1011/NetEase.MailMaster.installer.yaml
  manifests/n/NetEase/MailMaster/4.17.4.1011/NetEase.MailMaster.locale.en-US.yaml
  manifests/n/NetEase/MailMaster/4.17.4.1011/NetEase.MailMaster.locale.zh-CN.yaml
  manifests/n/NetEase/MailMaster/4.17.4.1011/NetEase.MailMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68134 New version: JetBrains.GoLand version 222.3345.118
  manifests/j/JetBrains/GoLand/222.3345.118/JetBrains.GoLand.installer.yaml
  manifests/j/JetBrains/GoLand/222.3345.118/JetBrains.GoLand.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/222.3345.118/JetBrains.GoLand.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68259 New version: Azul.Zulu.17.JRE version 17.36.13
  manifests/a/Azul/Zulu/17/JRE/17.36.13/Azul.Zulu.17.JRE.installer.yaml
  manifests/a/Azul/Zulu/17/JRE/17.36.13/Azul.Zulu.17.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/17/JRE/17.36.13/Azul.Zulu.17.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68193 Update: Oracle.VirtualBox version 6.1.36
  manifests/o/Oracle/VirtualBox/6.1.36/Oracle.VirtualBox.installer.yaml
  manifests/o/Oracle/VirtualBox/6.1.36/Oracle.VirtualBox.locale.en-US.yaml
  manifests/o/Oracle/VirtualBox/6.1.36/Oracle.VirtualBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68137 New version: JetBrains.IntelliJIDEA.Community version 222.3345.118
  manifests/j/JetBrains/IntelliJIDEA/Community/222.3345.118/JetBrains.IntelliJIDEA.Community.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/222.3345.118/JetBrains.IntelliJIDEA.Community.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/222.3345.118/JetBrains.IntelliJIDEA.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68122 New version: Flywheel.Local version 6.4.2
  manifests/f/Flywheel/Local/6.4.2/Flywheel.Local.installer.yaml
  manifests/f/Flywheel/Local/6.4.2/Flywheel.Local.locale.en-US.yaml
  manifests/f/Flywheel/Local/6.4.2/Flywheel.Local.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68276 Remove: Azul.Zulu.16 version 16.30.15
  manifests/a/Azul/Zulu/16/16.30.15/Azul.Zulu.16.installer.yaml
  manifests/a/Azul/Zulu/16/16.30.15/Azul.Zulu.16.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/16.30.15/Azul.Zulu.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68241 New version: VeyonSolutions.Veyon version 4.7.4
  manifests/v/VeyonSolutions/Veyon/4.7.4.0/VeyonSolutions.Veyon.installer.yaml
  manifests/v/VeyonSolutions/Veyon/4.7.4.0/VeyonSolutions.Veyon.locale.en-US.yaml
  manifests/v/VeyonSolutions/Veyon/4.7.4.0/VeyonSolutions.Veyon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68277 Remove: Azul.Zulu.16 version 16.32.15
  manifests/a/Azul/Zulu/16/16.32.15/Azul.Zulu.16.installer.yaml
  manifests/a/Azul/Zulu/16/16.32.15/Azul.Zulu.16.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/16.32.15/Azul.Zulu.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68132 New version: JetBrains.CLion version 222.3345.126
  manifests/j/JetBrains/CLion/222.3345.126/JetBrains.CLion.installer.yaml
  manifests/j/JetBrains/CLion/222.3345.126/JetBrains.CLion.locale.en-US.yaml
  manifests/j/JetBrains/CLion/222.3345.126/JetBrains.CLion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68138 New version: JetBrains.IntelliJIDEA.Edu version 221.6008.17
  manifests/j/JetBrains/IntelliJIDEA/Edu/221.6008.17/JetBrains.IntelliJIDEA.Edu.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Edu/221.6008.17/JetBrains.IntelliJIDEA.Edu.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Edu/221.6008.17/JetBrains.IntelliJIDEA.Edu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68256 New version: Azul.Zulu.17.JRE version 17.30.15
  manifests/a/Azul/Zulu/17/JRE/17.30.15/Azul.Zulu.17.JRE.installer.yaml
  manifests/a/Azul/Zulu/17/JRE/17.30.15/Azul.Zulu.17.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/17/JRE/17.30.15/Azul.Zulu.17.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68139 New version: JetBrains.IntelliJIDEA.Ultimate version 222.3345.118
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/222.3345.118/JetBrains.IntelliJIDEA.Ultimate.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/222.3345.118/JetBrains.IntelliJIDEA.Ultimate.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/222.3345.118/JetBrains.IntelliJIDEA.Ultimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68174 Update: Microsoft.PowerShell.Preview version 7.3.0.6
  manifests/m/Microsoft/PowerShell/Preview/7.3.0.6/Microsoft.PowerShell.Preview.installer.yaml
  manifests/m/Microsoft/PowerShell/Preview/7.3.0.6/Microsoft.PowerShell.Preview.locale.en-US.yaml
  manifests/m/Microsoft/PowerShell/Preview/7.3.0.6/Microsoft.PowerShell.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68182 New version: Nextcloud.NextcloudDesktop version 3.5.3
  manifests/n/Nextcloud/NextcloudDesktop/3.5.3.20220729/Nextcloud.NextcloudDesktop.installer.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.5.3.20220729/Nextcloud.NextcloudDesktop.locale.en-US.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.5.3.20220729/Nextcloud.NextcloudDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68222 Update: SteamGridDB.RomManager version 2.3.40
  manifests/s/SteamGridDB/RomManager/2.3.40/SteamGridDB.RomManager.installer.yaml
  manifests/s/SteamGridDB/RomManager/2.3.40/SteamGridDB.RomManager.locale.en-US.yaml
  manifests/s/SteamGridDB/RomManager/2.3.40/SteamGridDB.RomManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68257 New version: Azul.Zulu.17.JRE version 17.32.13
  manifests/a/Azul/Zulu/17/JRE/17.32.13/Azul.Zulu.17.JRE.installer.yaml
  manifests/a/Azul/Zulu/17/JRE/17.32.13/Azul.Zulu.17.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/17/JRE/17.32.13/Azul.Zulu.17.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68268 Money.Net version 2.0.0.8
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.8/LovettSoftware.MyMoney.Net.installer.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.8/LovettSoftware.MyMoney.Net.locale.en-US.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.8/LovettSoftware.MyMoney.Net.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68258 New version: Azul.Zulu.17.JRE version 17.34.19
  manifests/a/Azul/Zulu/17/JRE/17.34.19/Azul.Zulu.17.JRE.installer.yaml
  manifests/a/Azul/Zulu/17/JRE/17.34.19/Azul.Zulu.17.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/17/JRE/17.34.19/Azul.Zulu.17.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68195 Update: PaodingAI.PDFlux version 6.1.19
  manifests/p/PaodingAI/PDFlux/6.1.19/PaodingAI.PDFlux.installer.yaml
  manifests/p/PaodingAI/PDFlux/6.1.19/PaodingAI.PDFlux.locale.en-US.yaml
  manifests/p/PaodingAI/PDFlux/6.1.19/PaodingAI.PDFlux.locale.zh-CN.yaml
  manifests/p/PaodingAI/PDFlux/6.1.19/PaodingAI.PDFlux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68260 New version: Azul.Zulu.17.JRE version 17.36.15
  manifests/a/Azul/Zulu/17/JRE/17.36.15/Azul.Zulu.17.JRE.installer.yaml
  manifests/a/Azul/Zulu/17/JRE/17.36.15/Azul.Zulu.17.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/17/JRE/17.36.15/Azul.Zulu.17.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#67302 New version: JetBrains.DataGrip version 222.3345.126 [FP-O]
  manifests/j/JetBrains/DataGrip/222.3345.126/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/222.3345.126/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/222.3345.126/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68146 New version: JetBrains.RubyMine.EarlyAccess version 222.3345.94
  manifests/j/JetBrains/RubyMine/EarlyAccess/222.3345.94/JetBrains.RubyMine.EarlyAccess.installer.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/222.3345.94/JetBrains.RubyMine.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/222.3345.94/JetBrains.RubyMine.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68272 New version: OpenEducationFoundation.OpenBoard version 1.6.3
  manifests/o/OpenEducationFoundation/OpenBoard/1.6.3/OpenEducationFoundation.OpenBoard.installer.yaml
  manifests/o/OpenEducationFoundation/OpenBoard/1.6.3/OpenEducationFoundation.OpenBoard.locale.en-US.yaml
  manifests/o/OpenEducationFoundation/OpenBoard/1.6.3/OpenEducationFoundation.OpenBoard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68270 New version: Azul.Zulu.18.JRE version 18.30.11
  manifests/a/Azul/Zulu/18/JRE/18.30.11/Azul.Zulu.18.JRE.installer.yaml
  manifests/a/Azul/Zulu/18/JRE/18.30.11/Azul.Zulu.18.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JRE/18.30.11/Azul.Zulu.18.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68271 New version: Azul.Zulu.18.JRE version 18.32.11
  manifests/a/Azul/Zulu/18/JRE/18.32.11/Azul.Zulu.18.JRE.installer.yaml
  manifests/a/Azul/Zulu/18/JRE/18.32.11/Azul.Zulu.18.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JRE/18.32.11/Azul.Zulu.18.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68140 New version: JetBrains.PHPStorm.EarlyAccess version 222.3345.61
  manifests/j/JetBrains/PHPStorm/EarlyAccess/222.3345.61/JetBrains.PHPStorm.EarlyAccess.installer.yaml
  manifests/j/JetBrains/PHPStorm/EarlyAccess/222.3345.61/JetBrains.PHPStorm.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/PHPStorm/EarlyAccess/222.3345.61/JetBrains.PHPStorm.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68261 New package: Azul.Zulu.18.JDK version 18.28.13
  manifests/a/Azul/Zulu/18/JDK/18.28.13/Azul.Zulu.18.JDK.installer.yaml
  manifests/a/Azul/Zulu/18/JDK/18.28.13/Azul.Zulu.18.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JDK/18.28.13/Azul.Zulu.18.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68166 Update: KOOK.KOOK version 0.0.53.0
  manifests/k/KOOK/KOOK/0.0.53.0/KOOK.KOOK.installer.yaml
  manifests/k/KOOK/KOOK/0.0.53.0/KOOK.KOOK.locale.en-US.yaml
  manifests/k/KOOK/KOOK/0.0.53.0/KOOK.KOOK.locale.zh-CN.yaml
  manifests/k/KOOK/KOOK/0.0.53.0/KOOK.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68280 New version: Azul.Zulu.16.JRE version 16.32.15
  manifests/a/Azul/Zulu/16/JRE/16.32.15/Azul.Zulu.16.JRE.installer.yaml
  manifests/a/Azul/Zulu/16/JRE/16.32.15/Azul.Zulu.16.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JRE/16.32.15/Azul.Zulu.16.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68278 New package: Azul.Zulu.16.JRE version 16.28.11
  manifests/a/Azul/Zulu/16/JRE/16.28.11/Azul.Zulu.16.JRE.installer.yaml
  manifests/a/Azul/Zulu/16/JRE/16.28.11/Azul.Zulu.16.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JRE/16.28.11/Azul.Zulu.16.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68266 New version: Azul.Zulu.18.JDK version 18.32.11
  manifests/a/Azul/Zulu/18/JDK/18.32.11/Azul.Zulu.18.JDK.installer.yaml
  manifests/a/Azul/Zulu/18/JDK/18.32.11/Azul.Zulu.18.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JDK/18.32.11/Azul.Zulu.18.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68279 New version: Azul.Zulu.16.JRE version 16.30.15
  manifests/a/Azul/Zulu/16/JRE/16.30.15/Azul.Zulu.16.JRE.installer.yaml
  manifests/a/Azul/Zulu/16/JRE/16.30.15/Azul.Zulu.16.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JRE/16.30.15/Azul.Zulu.16.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68273 New package: Azul.Zulu.16.JDK version 16.28.11
  manifests/a/Azul/Zulu/16/JDK/16.28.11/Azul.Zulu.16.JDK.installer.yaml
  manifests/a/Azul/Zulu/16/JDK/16.28.11/Azul.Zulu.16.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JDK/16.28.11/Azul.Zulu.16.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68275 New version: Azul.Zulu.16.JDK version 16.32.15
  manifests/a/Azul/Zulu/16/JDK/16.32.15/Azul.Zulu.16.JDK.installer.yaml
  manifests/a/Azul/Zulu/16/JDK/16.32.15/Azul.Zulu.16.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JDK/16.32.15/Azul.Zulu.16.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68274 New version: Azul.Zulu.16.JDK version 16.30.15
  manifests/a/Azul/Zulu/16/JDK/16.30.15/Azul.Zulu.16.JDK.installer.yaml
  manifests/a/Azul/Zulu/16/JDK/16.30.15/Azul.Zulu.16.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/16/JDK/16.30.15/Azul.Zulu.16.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68269 New package: Azul.Zulu.18.JRE version 18.28.13
  manifests/a/Azul/Zulu/18/JRE/18.28.13/Azul.Zulu.18.JRE.installer.yaml
  manifests/a/Azul/Zulu/18/JRE/18.28.13/Azul.Zulu.18.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JRE/18.28.13/Azul.Zulu.18.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68264 New version: Azul.Zulu.18.JDK version 18.30.11
  manifests/a/Azul/Zulu/18/JDK/18.30.11/Azul.Zulu.18.JDK.installer.yaml
  manifests/a/Azul/Zulu/18/JDK/18.30.11/Azul.Zulu.18.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/18/JDK/18.30.11/Azul.Zulu.18.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68282 New version: Azul.Zulu.15.JDK version 15.28.13
  manifests/a/Azul/Zulu/15/JDK/15.28.13/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.28.13/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.28.13/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68281 New package: Azul.Zulu.15.JDK version 15.27.17
  manifests/a/Azul/Zulu/15/JDK/15.27.17/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.27.17/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.27.17/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68285 New version: Azul.Zulu.15.JDK version 15.32.15
  manifests/a/Azul/Zulu/15/JDK/15.32.15/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.32.15/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.32.15/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68286 New version: Azul.Zulu.15.JDK version 15.34.17
  manifests/a/Azul/Zulu/15/JDK/15.34.17/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.34.17/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.34.17/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68293 Remove: Azul.Zulu.15 version 15.42.15
  manifests/a/Azul/Zulu/15/15.42.15/Azul.Zulu.15.installer.yaml
  manifests/a/Azul/Zulu/15/15.42.15/Azul.Zulu.15.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/15.42.15/Azul.Zulu.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68292 Remove: Azul.Zulu.15 version 15.40.19
  manifests/a/Azul/Zulu/15/15.40.19/Azul.Zulu.15.installer.yaml
  manifests/a/Azul/Zulu/15/15.40.19/Azul.Zulu.15.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/15.40.19/Azul.Zulu.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68289 New version: Azul.Zulu.15.JDK version 15.40.19
  manifests/a/Azul/Zulu/15/JDK/15.40.19/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.40.19/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.40.19/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68288 New version: Azul.Zulu.15.JDK version 15.38.17
  manifests/a/Azul/Zulu/15/JDK/15.38.17/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.38.17/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.38.17/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68290 New version: Azul.Zulu.15.JDK version 15.42.15
  manifests/a/Azul/Zulu/15/JDK/15.42.15/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.42.15/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.42.15/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68287 New version: Azul.Zulu.15.JDK version 15.36.13
  manifests/a/Azul/Zulu/15/JDK/15.36.13/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.36.13/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.36.13/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68291 Remove: Azul.Zulu.15 version 15.38.17
  manifests/a/Azul/Zulu/15/15.38.17/Azul.Zulu.15.installer.yaml
  manifests/a/Azul/Zulu/15/15.38.17/Azul.Zulu.15.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/15.38.17/Azul.Zulu.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68100 New version: B3log.SiYuan version 2.1.4
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68284 New version: Azul.Zulu.15.JDK version 15.29.15
  manifests/a/Azul/Zulu/15/JDK/15.29.15/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.29.15/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.29.15/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68283 New version: Azul.Zulu.15.JDK version 15.28.51
  manifests/a/Azul/Zulu/15/JDK/15.28.51/Azul.Zulu.15.JDK.installer.yaml
  manifests/a/Azul/Zulu/15/JDK/15.28.51/Azul.Zulu.15.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JDK/15.28.51/Azul.Zulu.15.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68296 New version: Sandboxie.Classic version 5.57.7
  manifests/s/Sandboxie/Classic/5.57.7/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.57.7/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.57.7/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68232 Update: Tencent.EDU version 4.0.1.9
  manifests/t/Tencent/EDU/4.0.1.9/Tencent.EDU.installer.yaml
  manifests/t/Tencent/EDU/4.0.1.9/Tencent.EDU.locale.en-US.yaml
  manifests/t/Tencent/EDU/4.0.1.9/Tencent.EDU.locale.zh-CN.yaml
  manifests/t/Tencent/EDU/4.0.1.9/Tencent.EDU.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68262 New package: Canonical.Ubuntu.2204 version 2204.0.10.0
  manifests/c/Canonical/Ubuntu/2204/2204.0.10.0/Canonical.Ubuntu.2204.installer.yaml
  manifests/c/Canonical/Ubuntu/2204/2204.0.10.0/Canonical.Ubuntu.2204.locale.en-US.yaml
  manifests/c/Canonical/Ubuntu/2204/2204.0.10.0/Canonical.Ubuntu.2204.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68295 New version: Sandboxie.Plus version 1.2.7
  manifests/s/Sandboxie/Plus/1.2.7/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.2.7/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.2.7/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68301 JanDeDobbeleer.OhMyPosh version 8.25.0
  manifests/j/JanDeDobbeleer/OhMyPosh/8.25.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.25.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.25.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68299 r12f.DivoomGateway version 0.1.25.0
  manifests/r/r12f/DivoomGateway/0.1.25.0/r12f.DivoomGateway.installer.yaml
  manifests/r/r12f/DivoomGateway/0.1.25.0/r12f.DivoomGateway.locale.en-US.yaml
  manifests/r/r12f/DivoomGateway/0.1.25.0/r12f.DivoomGateway.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68300 Update version: ImageMagick.ImageMagick version 7.1.0.45
  manifests/i/ImageMagick/ImageMagick/7.1.0.45/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.45/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.45/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68297 r12f.DivoomCli version 0.1.25.0
  manifests/r/r12f/DivoomCli/0.1.25.0/r12f.DivoomCli.installer.yaml
  manifests/r/r12f/DivoomCli/0.1.25.0/r12f.DivoomCli.locale.en-US.yaml
  manifests/r/r12f/DivoomCli/0.1.25.0/r12f.DivoomCli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68307 New version: LibreWolf.LibreWolf version 103.0-3
  manifests/l/LibreWolf/LibreWolf/103.0-3/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/103.0-3/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/103.0-3/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68315 New version: Azul.Zulu.15.JRE version 15.42.15
  manifests/a/Azul/Zulu/15/JRE/15.42.15/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.42.15/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.42.15/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68316 Added Firefox Developer Edition version 104.0b4.
  manifests/m/Mozilla/Firefox/DeveloperEdition/104.0b4/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/104.0b4/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/104.0b4/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68303 Update: OpenJS.NodeJS.Nightly version 19.0.0
  manifests/o/OpenJS/NodeJS/Nightly/19.0.0/OpenJS.NodeJS.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68354 Remove: OpenSourcePhysics.Tracker version 6.0.6
  manifests/o/OpenSourcePhysics/Tracker/6.0.6/OpenSourcePhysics.Tracker.installer.yaml
  manifests/o/OpenSourcePhysics/Tracker/6.0.6/OpenSourcePhysics.Tracker.locale.en-US.yaml
  manifests/o/OpenSourcePhysics/Tracker/6.0.6/OpenSourcePhysics.Tracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68353 New version: OpenSourcePhysics.Tracker version 6.0.9
  manifests/o/OpenSourcePhysics/Tracker/6.0.9/OpenSourcePhysics.Tracker.installer.yaml
  manifests/o/OpenSourcePhysics/Tracker/6.0.9/OpenSourcePhysics.Tracker.locale.en-US.yaml
  manifests/o/OpenSourcePhysics/Tracker/6.0.9/OpenSourcePhysics.Tracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68350 New version: Azul.Zulu.13.JRE version 13.46.15
  manifests/a/Azul/Zulu/13/JRE/13.46.15/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.46.15/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.46.15/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68347 New version: Azul.Zulu.13.JRE version 13.40.15
  manifests/a/Azul/Zulu/13/JRE/13.40.15/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.40.15/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.40.15/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68348 New version: Azul.Zulu.13.JRE version 13.42.17
  manifests/a/Azul/Zulu/13/JRE/13.42.17/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.42.17/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.42.17/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68362 Update: Ximalaya.Ximalaya version 3.0.2
  manifests/x/Ximalaya/Ximalaya/3.0.2/Ximalaya.Ximalaya.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68346 New version: Azul.Zulu.13.JRE version 13.37.21
  manifests/a/Azul/Zulu/13/JRE/13.37.21/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.37.21/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.37.21/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68344 New version: Azul.Zulu.13.JRE version 13.35.17
  manifests/a/Azul/Zulu/13/JRE/13.35.17/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.35.17/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.35.17/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68343 New version: Azul.Zulu.13.JRE version 13.33.25
  manifests/a/Azul/Zulu/13/JRE/13.33.25/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.33.25/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.33.25/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68342 New version: Azul.Zulu.13.JRE version 13.31.11
  manifests/a/Azul/Zulu/13/JRE/13.31.11/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.31.11/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.31.11/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68359 New version: Redisant.RabbitMQAssistant version 1.0.3.0
  manifests/r/Redisant/RabbitMQAssistant/1.0.3.0/Redisant.RabbitMQAssistant.installer.yaml
  manifests/r/Redisant/RabbitMQAssistant/1.0.3.0/Redisant.RabbitMQAssistant.locale.en-US.yaml
  manifests/r/Redisant/RabbitMQAssistant/1.0.3.0/Redisant.RabbitMQAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/RabbitMQAssistant/1.0.3.0/Redisant.RabbitMQAssistant.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#68340 New package: Azul.Zulu.13.JRE version 13.28.11
  manifests/a/Azul/Zulu/13/JRE/13.28.11/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.28.11/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.28.11/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#68351 New version: Azul.Zulu.13.JRE version 13.48.19
  manifests/a/Azul/Zulu/13/JRE/13.48.19/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.48.19/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.48.19/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68339 Remove: Azul.Zulu.13 version 13.50.15
  manifests/a/Azul/Zulu/13/13.50.15/Azul.Zulu.13.installer.yaml
  manifests/a/Azul/Zulu/13/13.50.15/Azul.Zulu.13.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/13.50.15/Azul.Zulu.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68345 New version: Azul.Zulu.13.JRE version 13.35.51
  manifests/a/Azul/Zulu/13/JRE/13.35.51/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.35.51/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.35.51/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68349 New version: Azul.Zulu.13.JRE version 13.44.13
  manifests/a/Azul/Zulu/13/JRE/13.44.13/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.44.13/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.44.13/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68338 Remove: Azul.Zulu.13 version 13.48.19
  manifests/a/Azul/Zulu/13/13.48.19/Azul.Zulu.13.installer.yaml
  manifests/a/Azul/Zulu/13/13.48.19/Azul.Zulu.13.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/13.48.19/Azul.Zulu.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68336 Remove: Azul.Zulu.13 version 13.42.17
  manifests/a/Azul/Zulu/13/13.42.17/Azul.Zulu.13.installer.yaml
  manifests/a/Azul/Zulu/13/13.42.17/Azul.Zulu.13.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/13.42.17/Azul.Zulu.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68325 New version: Azul.Zulu.13.JDK version 13.31.11
  manifests/a/Azul/Zulu/13/JDK/13.31.11/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.31.11/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.31.11/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68328 New version: Azul.Zulu.13.JDK version 13.35.51
  manifests/a/Azul/Zulu/13/JDK/13.35.51/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.35.51/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.35.51/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68324 New version: Azul.Zulu.13.JDK version 13.29.9
  manifests/a/Azul/Zulu/13/JDK/13.29.9/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.29.9/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.29.9/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68329 New version: Azul.Zulu.13.JDK version 13.37.21
  manifests/a/Azul/Zulu/13/JDK/13.37.21/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.37.21/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.37.21/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68363 Modify: B3log.SiYuan version 2.1.4
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.1.4/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68352 New version: Azul.Zulu.13.JRE version 13.50.15
  manifests/a/Azul/Zulu/13/JRE/13.50.15/Azul.Zulu.13.JRE.installer.yaml
  manifests/a/Azul/Zulu/13/JRE/13.50.15/Azul.Zulu.13.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JRE/13.50.15/Azul.Zulu.13.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68335 New version: Azul.Zulu.13.JDK version 13.50.15
  manifests/a/Azul/Zulu/13/JDK/13.50.15/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.50.15/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.50.15/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68334 New version: Azul.Zulu.13.JDK version 13.48.19
  manifests/a/Azul/Zulu/13/JDK/13.48.19/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.48.19/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.48.19/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68333 New version: Azul.Zulu.13.JDK version 13.46.15
  manifests/a/Azul/Zulu/13/JDK/13.46.15/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.46.15/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.46.15/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68330 New version: Azul.Zulu.13.JDK version 13.40.15
  manifests/a/Azul/Zulu/13/JDK/13.40.15/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.40.15/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.40.15/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68323 New version: Azul.Zulu.13.JDK version 13.28.11
  manifests/a/Azul/Zulu/13/JDK/13.28.11/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.28.11/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.28.11/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68322 New package: Azul.Zulu.13.JDK version 13.27.9
  manifests/a/Azul/Zulu/13/JDK/13.27.9/Azul.Zulu.13.JDK.installer.yaml
  manifests/a/Azul/Zulu/13/JDK/13.27.9/Azul.Zulu.13.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/13/JDK/13.27.9/Azul.Zulu.13.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68317 Added AWS Command Line Interface version 2.7.20.0.
  manifests/a/Amazon/AWSCLI/2.7.20.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.7.20.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.7.20.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68318 Added Jackett version 0.20.1539.
  manifests/j/Jackett/Jackett/0.20.1539/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1539/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1539/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68311 New version: Azul.Zulu.15.JRE version 15.34.17
  manifests/a/Azul/Zulu/15/JRE/15.34.17/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.34.17/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.34.17/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68312 New version: Azul.Zulu.15.JRE version 15.36.13
  manifests/a/Azul/Zulu/15/JRE/15.36.13/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.36.13/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.36.13/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68313 New version: Azul.Zulu.15.JRE version 15.38.17
  manifests/a/Azul/Zulu/15/JRE/15.38.17/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.38.17/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.38.17/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68314 New version: Azul.Zulu.15.JRE version 15.40.19
  manifests/a/Azul/Zulu/15/JRE/15.40.19/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.40.19/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.40.19/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68310 New version: Azul.Zulu.15.JRE version 15.32.15
  manifests/a/Azul/Zulu/15/JRE/15.32.15/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.32.15/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.32.15/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68309 New version: Azul.Zulu.15.JRE version 15.29.15
  manifests/a/Azul/Zulu/15/JRE/15.29.15/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.29.15/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.29.15/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68306 New version: Azul.Zulu.15.JRE version 15.28.13
  manifests/a/Azul/Zulu/15/JRE/15.28.13/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.28.13/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.28.13/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68305 New package: Azul.Zulu.15.JRE version 15.27.17
  manifests/a/Azul/Zulu/15/JRE/15.27.17/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.27.17/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.27.17/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68320 SmartSoft.SmartFTP version 10.0.3004.0
  manifests/s/SmartSoft/SmartFTP/10.0.3004.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3004.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3004.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68308 New version: Azul.Zulu.15.JRE version 15.28.51
  manifests/a/Azul/Zulu/15/JRE/15.28.51/Azul.Zulu.15.JRE.installer.yaml
  manifests/a/Azul/Zulu/15/JRE/15.28.51/Azul.Zulu.15.JRE.locale.en-US.yaml
  manifests/a/Azul/Zulu/15/JRE/15.28.51/Azul.Zulu.15.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68321 New version: herrlichmedia.Agantty version 1.0.47
  manifests/h/herrlichmedia/Agantty/1.0.47/herrlichmedia.Agantty.installer.yaml
  manifests/h/herrlichmedia/Agantty/1.0.47/herrlichmedia.Agantty.locale.en-US.yaml
  manifests/h/herrlichmedia/Agantty/1.0.47/herrlichmedia.Agantty.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68357 Update to v0.9.5.0; Added additional locale 'de-DE'; Updated descript…
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.5.0/Mirasoft.AnyVizCloudAdapter.installer.yaml
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.5.0/Mirasoft.AnyVizCloudAdapter.locale.de-DE.yaml
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.5.0/Mirasoft.AnyVizCloudAdapter.locale.en-US.yaml
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.5.0/Mirasoft.AnyVizCloudAdapter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68361 New version: HydrologicEngineeringCenter.HEC-HMS version 4.10
  manifests/h/HydrologicEngineeringCenter/HEC-HMS/4.10/HydrologicEngineeringCenter.HEC-HMS.installer.yaml
  manifests/h/HydrologicEngineeringCenter/HEC-HMS/4.10/HydrologicEngineeringCenter.HEC-HMS.locale.en-US.yaml
  manifests/h/HydrologicEngineeringCenter/HEC-HMS/4.10/HydrologicEngineeringCenter.HEC-HMS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#67898 New package: GoLang.Go.1.18 version 1.18.4
  manifests/g/GoLang/Go/1/18/1.18.4/GoLang.Go.1.18.installer.yaml
  manifests/g/GoLang/Go/1/18/1.18.4/GoLang.Go.1.18.locale.en-US.yaml
  manifests/g/GoLang/Go/1/18/1.18.4/GoLang.Go.1.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#68364 New package: VladimirYakovlev.ElectronMail version 5.0.2
  manifests/v/VladimirYakovlev/ElectronMail/5.0.2/VladimirYakovlev.ElectronMail.installer.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.0.2/VladimirYakovlev.ElectronMail.locale.en-US.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.0.2/VladimirYakovlev.ElectronMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68365 Add Postman 9.25.2
  manifests/p/Postman/Postman/9.25.2/Postman.Postman.installer.yaml
  manifests/p/Postman/Postman/9.25.2/Postman.Postman.locale.en-US.yaml
  manifests/p/Postman/Postman/9.25.2/Postman.Postman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68036 Audient.Sono version 4.2.1.0
  manifests/a/Audient/Sono/4.2.1.0/Audient.Sono.installer.yaml
  manifests/a/Audient/Sono/4.2.1.0/Audient.Sono.locale.en-US.yaml
  manifests/a/Audient/Sono/4.2.1.0/Audient.Sono.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#68068 New version: RedHat.VirtViewer version 11.0.256
  manifests/r/RedHat/VirtViewer/11.0.256/RedHat.VirtViewer.installer.yaml
  manifests/r/RedHat/VirtViewer/11.0.256/RedHat.VirtViewer.locale.en-US.yaml
  manifests/r/RedHat/VirtViewer/11.0.256/RedHat.VirtViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#68027 New version: OSSEC.OSSECAgent version 3.7.0
  manifests/o/OSSEC/OSSECAgent/3.7.0/OSSEC.OSSECAgent.installer.yaml
  manifests/o/OSSEC/OSSECAgent/3.7.0/OSSEC.OSSECAgent.locale.en-US.yaml
  manifests/o/OSSEC/OSSECAgent/3.7.0/OSSEC.OSSECAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#68151 New Version : Ahlyab.UdemyCouponFetcher version 1.2.0
  manifests/a/Ahlyab/UdemyCouponFetcher/1.0.0/Ahlyab.UdemyCouponFetcher.installer.yaml
  manifests/a/Ahlyab/UdemyCouponFetcher/1.0.0/Ahlyab.UdemyCouponFetcher.locale.en-US.yaml
  manifests/a/Ahlyab/UdemyCouponFetcher/1.0.0/Ahlyab.UdemyCouponFetcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#68094 filips.FirefoxPWA version 2.0.1
  manifests/f/filips/FirefoxPWA/2.0.1/filips.FirefoxPWA.installer.yaml
  manifests/f/filips/FirefoxPWA/2.0.1/filips.FirefoxPWA.locale.en-US.yaml
  manifests/f/filips/FirefoxPWA/2.0.1/filips.FirefoxPWA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68319 New version: HP.HPCMSL version 1.6.6
  manifests/h/HP/HPCMSL/1.6.6/HP.HPCMSL.installer.yaml
  manifests/h/HP/HPCMSL/1.6.6/HP.HPCMSL.locale.en-US.yaml
  manifests/h/HP/HPCMSL/1.6.6/HP.HPCMSL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#68376 New version: FinalWire.AIDA64.Extreme version 6.75
  manifests/f/FinalWire/AIDA64/Extreme/6.75/FinalWire.AIDA64.Extreme.installer.yaml
  manifests/f/FinalWire/AIDA64/Extreme/6.75/FinalWire.AIDA64.Extreme.locale.en-US.yaml
  manifests/f/FinalWire/AIDA64/Extreme/6.75/FinalWire.AIDA64.Extreme.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68375 Update version: EclipseAdoptium.Temurin version 18.0.2.9
  manifests/e/EclipseAdoptium/Temurin/18/JDK/18.0.2.9/EclipseAdoptium.Temurin.18.JDK.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68377 New version: FinalWire.AIDA64.Engineer version 6.75
  manifests/f/FinalWire/AIDA64/Engineer/6.75/FinalWire.AIDA64.Engineer.installer.yaml
  manifests/f/FinalWire/AIDA64/Engineer/6.75/FinalWire.AIDA64.Engineer.locale.en-US.yaml
  manifests/f/FinalWire/AIDA64/Engineer/6.75/FinalWire.AIDA64.Engineer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68381 New version: trinsic.cli version 1.7.0
  manifests/t/trinsic/cli/1.7.0/trinsic.cli.installer.yaml
  manifests/t/trinsic/cli/1.7.0/trinsic.cli.locale.en-US.yaml
  manifests/t/trinsic/cli/1.7.0/trinsic.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68378 tastyworks.tastyworks version 1.23.0
  manifests/t/tastyworks/tastyworks/1.23.0/tastyworks.tastyworks.installer.yaml
  manifests/t/tastyworks/tastyworks/1.23.0/tastyworks.tastyworks.locale.en-US.yaml
  manifests/t/tastyworks/tastyworks/1.23.0/tastyworks.tastyworks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68385 New version: PolyMC.PolyMC version 1.4.1
  manifests/p/PolyMC/PolyMC/1.4.1/PolyMC.PolyMC.installer.yaml
  manifests/p/PolyMC/PolyMC/1.4.1/PolyMC.PolyMC.locale.en-US.yaml
  manifests/p/PolyMC/PolyMC/1.4.1/PolyMC.PolyMC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68170 Update: MasterPackager.MasterPackager version 22.3.8241.0
  manifests/m/MasterPackager/MasterPackager/22.3.8241.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/22.3.8241.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/22.3.8241.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Hash-Verification-Failed, Moderator-Approved

#68386 Update: PolyMC.PolyMC version 1.4.0
  manifests/p/PolyMC/PolyMC/1.4.0/PolyMC.PolyMC.installer.yaml
  manifests/p/PolyMC/PolyMC/1.4.0/PolyMC.PolyMC.locale.en-US.yaml
  manifests/p/PolyMC/PolyMC/1.4.0/PolyMC.PolyMC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68411 Remove: Azul.Zulu.11 version 11.48.21
  manifests/a/Azul/Zulu/11/11.48.21/Azul.Zulu.11.installer.yaml
  manifests/a/Azul/Zulu/11/11.48.21/Azul.Zulu.11.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/11.48.21/Azul.Zulu.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68413 Remove: Azul.Zulu.11 version 11.54.23
  manifests/a/Azul/Zulu/11/11.54.23/Azul.Zulu.11.installer.yaml
  manifests/a/Azul/Zulu/11/11.54.23/Azul.Zulu.11.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/11.54.23/Azul.Zulu.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68412 Remove: Azul.Zulu.11 version 11.50.19
  manifests/a/Azul/Zulu/11/11.50.19/Azul.Zulu.11.installer.yaml
  manifests/a/Azul/Zulu/11/11.50.19/Azul.Zulu.11.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/11.50.19/Azul.Zulu.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68414 Remove: Azul.Zulu.11 version 11.56.19
  manifests/a/Azul/Zulu/11/11.56.19/Azul.Zulu.11.installer.yaml
  manifests/a/Azul/Zulu/11/11.56.19/Azul.Zulu.11.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/11.56.19/Azul.Zulu.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68388 Update: PolyMC.PolyMC version 1.3.1
  manifests/p/PolyMC/PolyMC/1.3.1/PolyMC.PolyMC.installer.yaml
  manifests/p/PolyMC/PolyMC/1.3.1/PolyMC.PolyMC.locale.en-US.yaml
  manifests/p/PolyMC/PolyMC/1.3.1/PolyMC.PolyMC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68387 Update: PolyMC.PolyMC version 1.3.2
  manifests/p/PolyMC/PolyMC/1.3.2/PolyMC.PolyMC.installer.yaml
  manifests/p/PolyMC/PolyMC/1.3.2/PolyMC.PolyMC.locale.en-US.yaml
  manifests/p/PolyMC/PolyMC/1.3.2/PolyMC.PolyMC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68415 Remove: Azul.Zulu.11 version 11.58.17
  manifests/a/Azul/Zulu/11/11.58.17/Azul.Zulu.11.installer.yaml
  manifests/a/Azul/Zulu/11/11.58.17/Azul.Zulu.11.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/11.58.17/Azul.Zulu.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68394 New version: Azul.Zulu.11.JDK version 11.33.15
  manifests/a/Azul/Zulu/11/JDK/11.33.15/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.33.15/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.33.15/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68390 New package: Azul.Zulu.11.JDK version 11.2.3
  manifests/a/Azul/Zulu/11/JDK/11.2.3/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.2.3/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.2.3/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68389 Update: PolyMC.PolyMC version 1.3.0
  manifests/p/PolyMC/PolyMC/1.3.0/PolyMC.PolyMC.installer.yaml
  manifests/p/PolyMC/PolyMC/1.3.0/PolyMC.PolyMC.locale.en-US.yaml
  manifests/p/PolyMC/PolyMC/1.3.0/PolyMC.PolyMC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68391 New version: Azul.Zulu.11.JDK version 11.29.3
  manifests/a/Azul/Zulu/11/JDK/11.29.3/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.29.3/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.29.3/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68393 New version: Azul.Zulu.11.JDK version 11.31.11
  manifests/a/Azul/Zulu/11/JDK/11.31.11/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.31.11/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.31.11/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68396 New version: Azul.Zulu.11.JDK version 11.35.15
  manifests/a/Azul/Zulu/11/JDK/11.35.15/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.35.15/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.35.15/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68398 New version: Azul.Zulu.11.JDK version 11.39.15
  manifests/a/Azul/Zulu/11/JDK/11.39.15/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.39.15/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.39.15/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68392 New version: Azul.Zulu.11.JDK version 11.29.11
  manifests/a/Azul/Zulu/11/JDK/11.29.11/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.29.11/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.29.11/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68410 New version: Azul.Zulu.11.JDK version 11.58.17
  manifests/a/Azul/Zulu/11/JDK/11.58.17/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.58.17/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.58.17/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#68404 New version: Azul.Zulu.11.JDK version 11.50.19
  manifests/a/Azul/Zulu/11/JDK/11.50.19/Azul.Zulu.11.JDK.installer.yaml
  manifests/a/Azul/Zulu/11/JDK/11.50.19/Azul.Zulu.11.JDK.locale.en-US.yaml
  manifests/a/Azul/Zulu/11/JDK/11.50.19/Azul.Zulu.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
