Repository microsoft/winget-pkgs, pull requests merged in 2022-04, with the labels that each got.

#55781 New version: ScreamingFrog.SEOSpider version 16.7
  manifests/s/ScreamingFrog/SEOSpider/16.7/ScreamingFrog.SEOSpider.installer.yaml
  manifests/s/ScreamingFrog/SEOSpider/16.7/ScreamingFrog.SEOSpider.locale.en-US.yaml
  manifests/s/ScreamingFrog/SEOSpider/16.7/ScreamingFrog.SEOSpider.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56255 New version: SAGAUserGroupAssociation.SAGAGIS version 8.2.0.0
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.2.0.0/SAGAUserGroupAssociation.SAGAGIS.installer.yaml
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.2.0.0/SAGAUserGroupAssociation.SAGAGIS.locale.en-US.yaml
  manifests/s/SAGAUserGroupAssociation/SAGAGIS/8.2.0.0/SAGAUserGroupAssociation.SAGAGIS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Unapproved-URL, Moderator-Approved, Needs-Attention

#56298 New package: DisplayLink.GraphicsDriver version 10.2.6841.0
  manifests/d/DisplayLink/GraphicsDriver/10.2.6841.0/DisplayLink.GraphicsDriver.installer.yaml
  manifests/d/DisplayLink/GraphicsDriver/10.2.6841.0/DisplayLink.GraphicsDriver.locale.en-US.yaml
  manifests/d/DisplayLink/GraphicsDriver/10.2.6841.0/DisplayLink.GraphicsDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#56437 Update: KDE.Dolphin version 21.12.3
  manifests/k/KDE/Dolphin/21.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56466 Update: KDE.Kate version 21.12.3
  manifests/k/KDE/Kate/21.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56478 JanDeDobbeleer.OhMyPosh version 7.57.0
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56509 New version: Wondershare.MobileTrans version 3.6.2
  manifests/w/Wondershare/MobileTrans/3.6.2/Wondershare.MobileTrans.installer.yaml
  manifests/w/Wondershare/MobileTrans/3.6.2/Wondershare.MobileTrans.locale.en-US.yaml
  manifests/w/Wondershare/MobileTrans/3.6.2/Wondershare.MobileTrans.locale.zh-CN.yaml
  manifests/w/Wondershare/MobileTrans/3.6.2/Wondershare.MobileTrans.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56503 New version: XMind.XMind version 12.0.1
  manifests/x/XMind/XMind/12.0.1/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/12.0.1/XMind.XMind.locale.en-US.yaml
  manifests/x/XMind/XMind/12.0.1/XMind.XMind.locale.zh-CN.yaml
  manifests/x/XMind/XMind/12.0.1/XMind.XMind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56507 New version: Kingsoft.WPSOffice.CN version 11.1.0.11372
  manifests/k/Kingsoft/WPSOffice/CN/11.1.0.11372/Kingsoft.WPSOffice.CN.installer.yaml
  manifests/k/Kingsoft/WPSOffice/CN/11.1.0.11372/Kingsoft.WPSOffice.CN.locale.en-US.yaml
  manifests/k/Kingsoft/WPSOffice/CN/11.1.0.11372/Kingsoft.WPSOffice.CN.locale.zh-CN.yaml
  manifests/k/Kingsoft/WPSOffice/CN/11.1.0.11372/Kingsoft.WPSOffice.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56510 New version: Wondershare.UniConverter.13 version 13.6.1.18
  manifests/w/Wondershare/UniConverter/13/13.6.1.18/Wondershare.UniConverter.13.installer.yaml
  manifests/w/Wondershare/UniConverter/13/13.6.1.18/Wondershare.UniConverter.13.locale.en-US.yaml
  manifests/w/Wondershare/UniConverter/13/13.6.1.18/Wondershare.UniConverter.13.locale.zh-CN.yaml
  manifests/w/Wondershare/UniConverter/13/13.6.1.18/Wondershare.UniConverter.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56497 New version: pyfa.pyfa version 2.41.0
  manifests/p/pyfa/pyfa/2.41.0/pyfa.pyfa.installer.yaml
  manifests/p/pyfa/pyfa/2.41.0/pyfa.pyfa.locale.en-US.yaml
  manifests/p/pyfa/pyfa/2.41.0/pyfa.pyfa.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56465 New version: CiderCollective.Cider.Nightly version 1.4.1642
  manifests/c/CiderCollective/Cider/Nightly/1.4.1642/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.1642/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.1642/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56462 New version: calibre.calibre version 5.40.0
  manifests/c/calibre/calibre/5.40.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/5.40.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/5.40.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56463 New version: calibre.calibre.portable version 5.40.0.0
  manifests/c/calibre/calibre/portable/5.40.0.0/calibre.calibre.portable.installer.yaml
  manifests/c/calibre/calibre/portable/5.40.0.0/calibre.calibre.portable.locale.en-US.yaml
  manifests/c/calibre/calibre/portable/5.40.0.0/calibre.calibre.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56468 New version: OpenWhisperSystems.Signal.Beta version 5.38.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/5.38.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.38.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.38.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56501 New version: Wondershare.Anireel version 1.8.0
  manifests/w/Wondershare/Anireel/1.8.0/Wondershare.Anireel.installer.yaml
  manifests/w/Wondershare/Anireel/1.8.0/Wondershare.Anireel.locale.en-US.yaml
  manifests/w/Wondershare/Anireel/1.8.0/Wondershare.Anireel.locale.zh-CN.yaml
  manifests/w/Wondershare/Anireel/1.8.0/Wondershare.Anireel.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56451 New version: brimdata.brim version 0.29.0
  manifests/b/brimdata/brim/0.29.0/brimdata.brim.installer.yaml
  manifests/b/brimdata/brim/0.29.0/brimdata.brim.locale.en-US.yaml
  manifests/b/brimdata/brim/0.29.0/brimdata.brim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56482 New version: Fndroid.ClashForWindows version 0.19.14
  manifests/f/Fndroid/ClashForWindows/0.19.14/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.19.14/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.19.14/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56487 New version: Jackett.Jackett version 0.20.781.0
  manifests/j/Jackett/Jackett/0.20.781.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.781.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.781.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56483 New version: Foundry376.Mailspring version 1.10.2
  manifests/f/Foundry376/Mailspring/1.10.2/Foundry376.Mailspring.installer.yaml
  manifests/f/Foundry376/Mailspring/1.10.2/Foundry376.Mailspring.locale.en-US.yaml
  manifests/f/Foundry376/Mailspring/1.10.2/Foundry376.Mailspring.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56498 New version: tencent.tencentmeeting 3.6.6.477
  manifests/t/Tencent/TencentMeeting/3.6.6.477/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.6.6.477/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.6.6.477/Tencent.TencentMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeeting/3.6.6.477/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56485 New version: goatcorp.XIVLauncher version 6.2.22
  manifests/g/goatcorp/XIVLauncher/6.2.22/goatcorp.XIVLauncher.installer.yaml
  manifests/g/goatcorp/XIVLauncher/6.2.22/goatcorp.XIVLauncher.locale.en-US.yaml
  manifests/g/goatcorp/XIVLauncher/6.2.22/goatcorp.XIVLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56505 New version: 360.360Chrome.X version 21.0.1094.0
  manifests/3/360/360Chrome/X/21.0.1094.0/360.360Chrome.X.installer.yaml
  manifests/3/360/360Chrome/X/21.0.1094.0/360.360Chrome.X.locale.en-US.yaml
  manifests/3/360/360Chrome/X/21.0.1094.0/360.360Chrome.X.locale.zh-CN.yaml
  manifests/3/360/360Chrome/X/21.0.1094.0/360.360Chrome.X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56479 New version: CiderCollective.Cider.Nightly version 1.4.1644
  manifests/c/CiderCollective/Cider/Nightly/1.4.1644/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.1644/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.1644/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56480 New version: electerm.electerm version 1.20.10
  manifests/e/electerm/electerm/1.20.10/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.20.10/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.20.10/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56453 New version: UniversalMediaServer.UniversalMediaServer version 10.19.0
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.19.0/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.19.0/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.19.0/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56484 New version: foxglove.studio version 1.5.1
  manifests/f/foxglove/studio/1.5.1/foxglove.studio.installer.yaml
  manifests/f/foxglove/studio/1.5.1/foxglove.studio.locale.en-US.yaml
  manifests/f/foxglove/studio/1.5.1/foxglove.studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56513 ReleaseNotes: ByteDance.Feishu version 5.9.11
  manifests/b/ByteDance/Feishu/5.9.11/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/5.9.11/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.9.11/ByteDance.Feishu.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56467 New version: KristenMcWilliam.Nyrna version 2.4.1
  manifests/k/KristenMcWilliam/Nyrna/2.4.1/KristenMcWilliam.Nyrna.installer.yaml
  manifests/k/KristenMcWilliam/Nyrna/2.4.1/KristenMcWilliam.Nyrna.locale.en-US.yaml
  manifests/k/KristenMcWilliam/Nyrna/2.4.1/KristenMcWilliam.Nyrna.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56486 New version: Google.Chrome.Canary version 102.0.4977.0
  manifests/g/Google/Chrome/Canary/102.0.4977.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/102.0.4977.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/102.0.4977.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/102.0.4977.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56512 Add version: Sogou.SogouInput version 11.9.0.5687
  manifests/s/Sogou/SogouInput/11.9.0.5687/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/11.9.0.5687/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/11.9.0.5687/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/11.9.0.5687/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56504 New version: Catsxp.Catsxp version 100.2.4.2
  manifests/c/Catsxp/Catsxp/100.2.4.2/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.2/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.2/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.2/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56447 New version: antonreshetov.massCode version 1.3.1
  manifests/a/antonreshetov/massCode/1.3.1/antonreshetov.massCode.installer.yaml
  manifests/a/antonreshetov/massCode/1.3.1/antonreshetov.massCode.locale.en-US.yaml
  manifests/a/antonreshetov/massCode/1.3.1/antonreshetov.massCode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56461 New version: BetterCrewLink.BetterCrewLink version 2.9.5
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.5/BetterCrewLink.BetterCrewLink.installer.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.5/BetterCrewLink.BetterCrewLink.locale.en-US.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.5/BetterCrewLink.BetterCrewLink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56382 New version: Zoho.ZohoMail.Desktop version 1.4.1
  manifests/z/Zoho/ZohoMail/Desktop/1.4.1/Zoho.ZohoMail.Desktop.installer.yaml
  manifests/z/Zoho/ZohoMail/Desktop/1.4.1/Zoho.ZohoMail.Desktop.locale.en-US.yaml
  manifests/z/Zoho/ZohoMail/Desktop/1.4.1/Zoho.ZohoMail.Desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56495 New version: JetBrains.Toolbox version 1.23.11680
  manifests/j/JetBrains/Toolbox/1.23.11680/JetBrains.Toolbox.installer.yaml
  manifests/j/JetBrains/Toolbox/1.23.11680/JetBrains.Toolbox.locale.en-US.yaml
  manifests/j/JetBrains/Toolbox/1.23.11680/JetBrains.Toolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56500 Modify: B3log.SiYuan version 1.9.6
  manifests/b/B3log/SiYuan/1.9.6/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/1.9.6/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56469 Microsoft.VisualStudioCode.Insiders_v1.67.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.67.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56464 New version: chrisant996.Clink version 1.3.13.24b02e
  manifests/c/chrisant996/Clink/1.3.13.24b02e/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.3.13.24b02e/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.3.13.24b02e/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56499 New version: ByteDance.BytedanceMiniappIDE version 3.2.6
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.installer.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.locale.en-US.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.locale.zh-CN.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56481 Add version: Erlang.ErlangOTP version 24.3.3
  manifests/e/Erlang/ErlangOTP/24.3.3/Erlang.ErlangOTP.installer.yaml
  manifests/e/Erlang/ErlangOTP/24.3.3/Erlang.ErlangOTP.locale.en-US.yaml
  manifests/e/Erlang/ErlangOTP/24.3.3/Erlang.ErlangOTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56489 New version: JetBrains.GoLand.EarlyAccess version 221.5080.97
  manifests/j/JetBrains/GoLand/EarlyAccess/221.5080.97/JetBrains.GoLand.EarlyAccess.installer.yaml
  manifests/j/JetBrains/GoLand/EarlyAccess/221.5080.97/JetBrains.GoLand.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/EarlyAccess/221.5080.97/JetBrains.GoLand.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56518 Lenovo.SystemUpdate version 5.07.0136
  manifests/l/Lenovo/SystemUpdate/5.07.0136/Lenovo.SystemUpdate.installer.yaml
  manifests/l/Lenovo/SystemUpdate/5.07.0136/Lenovo.SystemUpdate.locale.en-US.yaml
  manifests/l/Lenovo/SystemUpdate/5.07.0136/Lenovo.SystemUpdate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56526 Update Netron to 5.6.7
  manifests/l/LutzRoeder/Netron/5.6.7/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.6.7/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.6.7/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56517 Added Visual Studio Build Tools 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/BuildTools/17.1.3/Microsoft.VisualStudio.2022.BuildTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56514 ReleaseNotes: AcFun.AcFunVirtualTool version 1.28.0.1326
  manifests/a/AcFun/AcFunVirtualTool/1.28.0.1326/AcFun.AcFunVirtualTool.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56491 New version: JetBrains.IntelliJIDEA.Edu version 213.7172.45
  manifests/j/JetBrains/IntelliJIDEA/Edu/213.7172.45/JetBrains.IntelliJIDEA.Edu.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Edu/213.7172.45/JetBrains.IntelliJIDEA.Edu.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Edu/213.7172.45/JetBrains.IntelliJIDEA.Edu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56494 New version: JetBrains.Rider version 213.7172.34
  manifests/j/JetBrains/Rider/213.7172.34/JetBrains.Rider.installer.yaml
  manifests/j/JetBrains/Rider/213.7172.34/JetBrains.Rider.locale.en-US.yaml
  manifests/j/JetBrains/Rider/213.7172.34/JetBrains.Rider.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56490 New version: JetBrains.IntelliJIDEA.Community.EAP version 221.5080.93
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/221.5080.93/JetBrains.IntelliJIDEA.Community.EAP.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/221.5080.93/JetBrains.IntelliJIDEA.Community.EAP.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/221.5080.93/JetBrains.IntelliJIDEA.Community.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56524 Added Visual Studio Load Test Controller 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/TestController/17.1.3/Microsoft.VisualStudio.2022.TestController.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56523 Added Visual Studio Test Agent 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/TestAgent/17.1.3/Microsoft.VisualStudio.2022.TestAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56521 Added Visual Studio Professional 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.1.3/Microsoft.VisualStudio.2022.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56525 Added Microsoft Edge Beta version 100.0.1185.27.
  manifests/m/Microsoft/Edge/Beta/100.0.1185.27/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/100.0.1185.27/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/100.0.1185.27/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56522 Added Visual Studio Team Explorer 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/TeamExplorer/17.1.3/Microsoft.VisualStudio.2022.TeamExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56492 New version: JetBrains.IntelliJIDEA.Ultimate.EAP version 221.5080.93
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/221.5080.93/JetBrains.IntelliJIDEA.Ultimate.EAP.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/221.5080.93/JetBrains.IntelliJIDEA.Ultimate.EAP.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/221.5080.93/JetBrains.IntelliJIDEA.Ultimate.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56520 Added Visual Studio Enterprise 2022 version 17.1.3.
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.1.3/Microsoft.VisualStudio.2022.Enterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56457 New version: acaudwell.Gource version gource-0.52
  manifests/a/acaudwell/Gource/0.52/acaudwell.Gource.installer.yaml
  manifests/a/acaudwell/Gource/0.52/acaudwell.Gource.locale.en-US.yaml
  manifests/a/acaudwell/Gource/0.52/acaudwell.Gource.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56488 New version: JetBrains.CLion.EAP version 221.5080.93
  manifests/j/JetBrains/CLion/EAP/221.5080.93/JetBrains.CLion.EAP.installer.yaml
  manifests/j/JetBrains/CLion/EAP/221.5080.93/JetBrains.CLion.EAP.locale.en-US.yaml
  manifests/j/JetBrains/CLion/EAP/221.5080.93/JetBrains.CLion.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56529 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#53651 Update: TUitTUWien.TUtoolbox version 2021.0.0.338
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.338/TUitTUWien.TUtoolbox.installer.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.338/TUitTUWien.TUtoolbox.locale.en-US.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.338/TUitTUWien.TUtoolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#53654 Update: TUitTUWien.TUtoolbox version 2021.0.0.369
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.369/TUitTUWien.TUtoolbox.installer.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.369/TUitTUWien.TUtoolbox.locale.en-US.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.369/TUitTUWien.TUtoolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#53649 Update: TUitTUWien.TUtoolbox version 2021.0.0.333
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.333/TUitTUWien.TUtoolbox.installer.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.333/TUitTUWien.TUtoolbox.locale.en-US.yaml
  manifests/t/TUitTUWien/TUtoolbox/2021.0.0.333/TUitTUWien.TUtoolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#53767 Update: WilliamKent.X2COPY version 2.1.1.0
  manifests/w/WilliamKent/X2COPY/2.1.1.0/WilliamKent.X2COPY.installer.yaml
  manifests/w/WilliamKent/X2COPY/2.1.1.0/WilliamKent.X2COPY.locale.en-US.yaml
  manifests/w/WilliamKent/X2COPY/2.1.1.0/WilliamKent.X2COPY.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56506 ReleaseNotesUrl: 360.360Chrome.X version 21.0.1090.0
  manifests/3/360/360Chrome/X/21.0.1090.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#52725 Remove: Piriform.CCleaner version 5.68.7820
  manifests/p/Piriform/CCleaner/5.68.7820/Piriform.CCleaner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#52727 Remove: Piriform.CCleaner version 5.69.7865
  manifests/p/Piriform/CCleaner/5.69.7865/Piriform.CCleaner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Attention

#53664 Remove: Tyrrrz.LightBulb version 2.2.0
  manifests/t/Tyrrrz/LightBulb/2.2.0/Tyrrrz.LightBulb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56535 New version: CrystalDewWorld.CrystalDiskInfo version 8.16.2
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.2/CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.2/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.2/CrystalDewWorld.CrystalDiskInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56533 Update: GnuCash.GnuCash version 4.10
  manifests/g/GnuCash/GnuCash/4.10/GnuCash.GnuCash.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56536 New version: Amazon.AWSCLI version 2.5.2.0
  manifests/a/Amazon/AWSCLI/2.5.2.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.5.2.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.5.2.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56537 New version: beekeeper-studio.beekeeper-studio version 3.3.7
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.7/beekeeper-studio.beekeeper-studio.installer.yaml
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.7/beekeeper-studio.beekeeper-studio.locale.en-US.yaml
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.7/beekeeper-studio.beekeeper-studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56540 New version: TeamViewer.TeamViewer version 15.28.8
  manifests/t/TeamViewer/TeamViewer/15.28.8/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.28.8/TeamViewer.TeamViewer.locale.de-DE.yaml
  manifests/t/TeamViewer/TeamViewer/15.28.8/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.28.8/TeamViewer.TeamViewer.locale.zh-CN.yaml
  manifests/t/TeamViewer/TeamViewer/15.28.8/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56543 New version: WestWind.MarkdownMonster version 2.4.7.0
  manifests/w/WestWind/MarkdownMonster/2.4.7.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.4.7.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.4.7.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56542 New version: CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition version 8.16.2
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.2/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.2/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.2/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56539 New version: TeamViewer.TeamViewer.Host version 15.28.8
  manifests/t/TeamViewer/TeamViewer/Host/15.28.8/TeamViewer.TeamViewer.Host.installer.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.28.8/TeamViewer.TeamViewer.Host.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.28.8/TeamViewer.TeamViewer.Host.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56559 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56558 Update: KDE.KDEConnect version 21.12.3
  manifests/k/KDE/KDEConnect/21.12.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56551 Update: KDE.umbrello version 21.12.3
  manifests/k/KDE/umbrello/21.12.3/KDE.umbrello.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56548 New version: MongoDB.Compass.Isolated version 1.31.0.0
  manifests/m/MongoDB/Compass/Isolated/1.31.0.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.31.0.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.31.0.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56549 New version: MongoDB.Compass.Readonly version 1.31.0.0
  manifests/m/MongoDB/Compass/Readonly/1.31.0.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.31.0.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.31.0.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56547 New version: MongoDB.Compass.Full version 1.31.0.0
  manifests/m/MongoDB/Compass/Full/1.31.0.0/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.31.0.0/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.31.0.0/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56550 New version: BetterCrewLink.BetterCrewLink version 2.9.6
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.6/BetterCrewLink.BetterCrewLink.installer.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.6/BetterCrewLink.BetterCrewLink.locale.en-US.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.6/BetterCrewLink.BetterCrewLink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56557 New version: beekeeper-studio.beekeeper-studio version 3.3.8
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.8/beekeeper-studio.beekeeper-studio.installer.yaml
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.8/beekeeper-studio.beekeeper-studio.locale.en-US.yaml
  manifests/b/beekeeper-studio/beekeeper-studio/3.3.8/beekeeper-studio.beekeeper-studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56566 New version: BlenderFoundation.Blender version 3.1.1
  manifests/b/BlenderFoundation/Blender/3.1.1/BlenderFoundation.Blender.installer.yaml
  manifests/b/BlenderFoundation/Blender/3.1.1/BlenderFoundation.Blender.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/3.1.1/BlenderFoundation.Blender.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56568 New version: BlenderFoundation.Blender version 3.1.2
  manifests/b/BlenderFoundation/Blender/3.1.2/BlenderFoundation.Blender.installer.yaml
  manifests/b/BlenderFoundation/Blender/3.1.2/BlenderFoundation.Blender.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/3.1.2/BlenderFoundation.Blender.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56546 New version: Opera.Opera version 85.0.4341.39
  manifests/o/Opera/Opera/85.0.4341.39/Opera.Opera.installer.yaml
  manifests/o/Opera/Opera/85.0.4341.39/Opera.Opera.locale.en-US.yaml
  manifests/o/Opera/Opera/85.0.4341.39/Opera.Opera.locale.nb-NO.yaml
  manifests/o/Opera/Opera/85.0.4341.39/Opera.Opera.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56613 Update: KDE.Kate version 21.12.3
  manifests/k/KDE/Kate/21.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56609 Update: OpenTTD.OpenTTD version 1.10.1
  manifests/o/OpenTTD/OpenTTD/1.10.1/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/1.10.1/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/1.10.1/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56603 OpenTTD.OpenTTD version 12.1
  manifests/o/OpenTTD/OpenTTD/12.1/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/12.1/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/12.1/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56590 New version: Google.Chrome.Canary version 102.0.4978.2
  manifests/g/Google/Chrome/Canary/102.0.4978.2/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/102.0.4978.2/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/102.0.4978.2/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/102.0.4978.2/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56605 Update: OpenTTD.OpenTTD version 12.0
  manifests/o/OpenTTD/OpenTTD/12.0/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/12.0/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/12.0/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56606 Update: OpenTTD.OpenTTD version 1.11.2
  manifests/o/OpenTTD/OpenTTD/1.11.2/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/1.11.2/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/1.11.2/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56602 Update: WildfireGames.0AD version r24937-alpha
  manifests/w/WildfireGames/0AD/r24937-alpha/WildfireGames.0AD.installer.yaml
  manifests/w/WildfireGames/0AD/r24937-alpha/WildfireGames.0AD.locale.en-US.yaml
  manifests/w/WildfireGames/0AD/r24937-alpha/WildfireGames.0AD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56585 PTRTECH.UVtools version 3.2.1
  manifests/p/PTRTECH/UVtools/3.2.1/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.2.1/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.2.1/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56575 Update: KDE.Dolphin version 21.12.3
  manifests/k/KDE/Dolphin/21.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56608 Update: OpenTTD.OpenTTD version 1.10.3
  manifests/o/OpenTTD/OpenTTD/1.10.3/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/1.10.3/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/1.10.3/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56607 Update: OpenTTD.OpenTTD version 1.11.1
  manifests/o/OpenTTD/OpenTTD/1.11.1/OpenTTD.OpenTTD.installer.yaml
  manifests/o/OpenTTD/OpenTTD/1.11.1/OpenTTD.OpenTTD.locale.en-US.yaml
  manifests/o/OpenTTD/OpenTTD/1.11.1/OpenTTD.OpenTTD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56627 New version: MongoDB.Shell version 1.3.1
  manifests/m/MongoDB/Shell/1.3.1/MongoDB.Shell.installer.yaml
  manifests/m/MongoDB/Shell/1.3.1/MongoDB.Shell.locale.en-US.yaml
  manifests/m/MongoDB/Shell/1.3.1/MongoDB.Shell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56626 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56625 New version: MongoDB.MongoDBCLI version 1.24.1
  manifests/m/MongoDB/MongoDBCLI/1.24.1/MongoDB.MongoDBCLI.installer.yaml
  manifests/m/MongoDB/MongoDBCLI/1.24.1/MongoDB.MongoDBCLI.locale.en-US.yaml
  manifests/m/MongoDB/MongoDBCLI/1.24.1/MongoDB.MongoDBCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56641 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56640 Update: KDE.KDEConnect version 21.12.3
  manifests/k/KDE/KDEConnect/21.12.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56644 New version: naaive.Orange version 0.5.0
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.installer.yaml
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.locale.en-US.yaml
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.locale.zh-CN.yaml
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56643 New version: MonkeysAudio.MonkeysAudio version 7.56
  manifests/m/MonkeysAudio/MonkeysAudio/7.56/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/7.56/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/7.56/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56633 Devolutions.RemoteDesktopManager version 2022.1.23.0
  manifests/d/Devolutions/RemoteDesktopManager/2022.1.23.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.1.23.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.1.23.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56632 Devolutions.RemoteDesktopManagerFree version 2022.1.23.0
  manifests/d/Devolutions/RemoteDesktopManagerFree/2022.1.23.0/Devolutions.RemoteDesktopManagerFree.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManagerFree/2022.1.23.0/Devolutions.RemoteDesktopManagerFree.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManagerFree/2022.1.23.0/Devolutions.RemoteDesktopManagerFree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56642 Update: KDE.umbrello version 21.12.3
  manifests/k/KDE/umbrello/21.12.3/KDE.umbrello.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56631 Added Microsoft Edge Dev version 101.0.1210.2.
  manifests/m/Microsoft/Edge/Dev/101.0.1210.2/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/101.0.1210.2/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/101.0.1210.2/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56630 Added Microsoft Edge WebView2 Runtime version 100.0.1185.29.
  manifests/m/Microsoft/EdgeWebView2Runtime/100.0.1185.29/Microsoft.EdgeWebView2Runtime.installer.yaml
  manifests/m/Microsoft/EdgeWebView2Runtime/100.0.1185.29/Microsoft.EdgeWebView2Runtime.locale.en-US.yaml
  manifests/m/Microsoft/EdgeWebView2Runtime/100.0.1185.29/Microsoft.EdgeWebView2Runtime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56618 New version: Wondershare.MobileTrans version 3.6.3
  manifests/w/Wondershare/MobileTrans/3.6.3/Wondershare.MobileTrans.installer.yaml
  manifests/w/Wondershare/MobileTrans/3.6.3/Wondershare.MobileTrans.locale.en-US.yaml
  manifests/w/Wondershare/MobileTrans/3.6.3/Wondershare.MobileTrans.locale.zh-CN.yaml
  manifests/w/Wondershare/MobileTrans/3.6.3/Wondershare.MobileTrans.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56592 New version: Tencent.VooVMeeting version 3.3.3.520
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.installer.yaml
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.locale.en-US.yaml
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56569 New version: RabidViperProductions.AssaultCube version 1.3.0.2
  manifests/r/RabidViperProductions/AssaultCube/1.3.0.2/RabidViperProductions.AssaultCube.installer.yaml
  manifests/r/RabidViperProductions/AssaultCube/1.3.0.2/RabidViperProductions.AssaultCube.locale.en-US.yaml
  manifests/r/RabidViperProductions/AssaultCube/1.3.0.2/RabidViperProductions.AssaultCube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56562 New version: CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition version 8.16.3
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56561 New version: CrystalDewWorld.CrystalDiskInfo version 8.16.3
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.3/CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.3/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/8.16.3/CrystalDewWorld.CrystalDiskInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56565 New version: deepnight.LDtk version 1.1.0
  manifests/d/deepnight/LDtk/1.1.0/deepnight.LDtk.installer.yaml
  manifests/d/deepnight/LDtk/1.1.0/deepnight.LDtk.locale.en-US.yaml
  manifests/d/deepnight/LDtk/1.1.0/deepnight.LDtk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56564 New version: AGSProjectTeam.AdventureGameStudio version 3.5.1.17
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.5.1.17/AGSProjectTeam.AdventureGameStudio.installer.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.5.1.17/AGSProjectTeam.AdventureGameStudio.locale.en-US.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.5.1.17/AGSProjectTeam.AdventureGameStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56567 New version: qutebrowser.qutebrowser version 2.5.0
  manifests/q/qutebrowser/qutebrowser/2.5.0/qutebrowser.qutebrowser.installer.yaml
  manifests/q/qutebrowser/qutebrowser/2.5.0/qutebrowser.qutebrowser.locale.en-US.yaml
  manifests/q/qutebrowser/qutebrowser/2.5.0/qutebrowser.qutebrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56541 New version: CrystalDewWorld.CrystalDiskInfo.ShizukuEdition version 8.16.3
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/8.16.3/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56570 Update: KDE.kmymoney version 5.1
  manifests/k/KDE/kmymoney/5.1/KDE.kmymoney.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56577 New version: Tencent.EDU version 3.0.4.70
  manifests/t/Tencent/EDU/3.0.4.70/Tencent.EDU.installer.yaml
  manifests/t/Tencent/EDU/3.0.4.70/Tencent.EDU.locale.en-US.yaml
  manifests/t/Tencent/EDU/3.0.4.70/Tencent.EDU.locale.zh-CN.yaml
  manifests/t/Tencent/EDU/3.0.4.70/Tencent.EDU.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56591 New version: joncampbell123.DOSBox-X version 0.83.24
  manifests/j/joncampbell123/DOSBox-X/0.83.24/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.24/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.24/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56619 New version: Wondershare.DemoCreator version 5.7.0.8
  manifests/w/Wondershare/DemoCreator/5.7.0.8/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/5.7.0.8/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/5.7.0.8/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/5.7.0.8/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56628 Added Jackett version 0.20.783.0.
  manifests/j/Jackett/Jackett/0.20.783.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.783.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.783.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56578 New version: Tencent.EDULite version 3.1.4.142
  manifests/t/Tencent/EDULite/3.1.4.142/Tencent.EDULite.installer.yaml
  manifests/t/Tencent/EDULite/3.1.4.142/Tencent.EDULite.locale.en-US.yaml
  manifests/t/Tencent/EDULite/3.1.4.142/Tencent.EDULite.locale.zh-CN.yaml
  manifests/t/Tencent/EDULite/3.1.4.142/Tencent.EDULite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56563 New version: Bethesda.Launcher version 1.84.0
  manifests/b/Bethesda/Launcher/1.84.0/Bethesda.Launcher.installer.yaml
  manifests/b/Bethesda/Launcher/1.84.0/Bethesda.Launcher.locale.en-US.yaml
  manifests/b/Bethesda/Launcher/1.84.0/Bethesda.Launcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56576 New version: RustemMussabekov.Raindrop version 5.4.24
  manifests/r/RustemMussabekov/Raindrop/5.4.24/RustemMussabekov.Raindrop.installer.yaml
  manifests/r/RustemMussabekov/Raindrop/5.4.24/RustemMussabekov.Raindrop.locale.en-US.yaml
  manifests/r/RustemMussabekov/Raindrop/5.4.24/RustemMussabekov.Raindrop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56574 New version: Baidu.BaiduTranslate version 1.5.0
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.installer.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.locale.en-US.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56650 Update: KDE.Dolphin version 21.12.3
  manifests/k/KDE/Dolphin/21.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56589 New version: gileli121.windowtop version 5.11.1
  manifests/g/gileli121/windowtop/5.11.1/gileli121.windowtop.installer.yaml
  manifests/g/gileli121/windowtop/5.11.1/gileli121.windowtop.locale.en-US.yaml
  manifests/g/gileli121/windowtop/5.11.1/gileli121.windowtop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56582 DoltHub.Dolt version 0.37.9
  manifests/d/DoltHub/Dolt/0.37.9/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.37.9/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.37.9/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56629 Added Microsoft Edge version 100.0.1185.29.
  manifests/m/Microsoft/Edge/100.0.1185.29/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/100.0.1185.29/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/100.0.1185.29/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/100.0.1185.29/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56588 New version: BetterCrewLink.BetterCrewLink version 2.9.7
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.7/BetterCrewLink.BetterCrewLink.installer.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.7/BetterCrewLink.BetterCrewLink.locale.en-US.yaml
  manifests/b/BetterCrewLink/BetterCrewLink/2.9.7/BetterCrewLink.BetterCrewLink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56688 Modify: Baidu.BaiduTranslate version 1.5.0
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.installer.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.locale.en-US.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.0/Baidu.BaiduTranslate.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56680 ReleaseNotes: ByteDance.BytedanceMiniappIDE version 3.2.6
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.installer.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.locale.en-US.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.2.6/ByteDance.BytedanceMiniappIDE.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56678 Modify: Woyun.wolai version 1.2.0
  manifests/w/Woyun/wolai/1.2.0/Woyun.wolai.installer.yaml
  manifests/w/Woyun/wolai/1.2.0/Woyun.wolai.locale.en-US.yaml
  manifests/w/Woyun/wolai/1.2.0/Woyun.wolai.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56677 Modify: Woyun.wolai version 1.2.1
  manifests/w/Woyun/wolai/1.2.1/Woyun.wolai.installer.yaml
  manifests/w/Woyun/wolai/1.2.1/Woyun.wolai.locale.en-US.yaml
  manifests/w/Woyun/wolai/1.2.1/Woyun.wolai.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56671 Update: KDE.Kate version 21.12.3
  manifests/k/KDE/Kate/21.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56676 Modify: Woyun.wolai version 1.2.2
  manifests/w/Woyun/wolai/1.2.2/Woyun.wolai.installer.yaml
  manifests/w/Woyun/wolai/1.2.2/Woyun.wolai.locale.en-US.yaml
  manifests/w/Woyun/wolai/1.2.2/Woyun.wolai.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56689 ReleaseNotes: Tencent.EDU version 3.0.4.70
  manifests/t/Tencent/EDU/3.0.4.70/Tencent.EDU.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56691 Modify: naaive.Orange version 0.4.0
  manifests/n/naaive/Orange/0.4.0/naaive.Orange.locale.en-US.yaml
  manifests/n/naaive/Orange/0.4.0/naaive.Orange.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56669 JanDeDobbeleer.OhMyPosh version 7.57.1
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.57.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56682 ReleaseNotes: naaive.Orange version 0.5.0
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.locale.en-US.yaml
  manifests/n/naaive/Orange/0.5.0/naaive.Orange.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56679 ReleaseNotesUrl: Tencent.VooVMeeting version 3.3.3.520
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.locale.en-US.yaml
  manifests/t/Tencent/VooVMeeting/3.3.3.520/Tencent.VooVMeeting.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56692 New version: blaadje.Todolist version 0.35.1
  manifests/b/blaadje/Todolist/0.35.1/blaadje.Todolist.installer.yaml
  manifests/b/blaadje/Todolist/0.35.1/blaadje.Todolist.locale.en-US.yaml
  manifests/b/blaadje/Todolist/0.35.1/blaadje.Todolist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56655 New version: bornova.numara version 3.11.8
  manifests/b/bornova/numara/3.11.8/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.11.8/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.11.8/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56651 DeskSoft.EarthView version 6.17.0
  manifests/d/DeskSoft/EarthView/6.17.0/DeskSoft.EarthView.installer.yaml
  manifests/d/DeskSoft/EarthView/6.17.0/DeskSoft.EarthView.locale.en-US.yaml
  manifests/d/DeskSoft/EarthView/6.17.0/DeskSoft.EarthView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56681 New version: Catsxp.Catsxp version 100.2.4.3
  manifests/c/Catsxp/Catsxp/100.2.4.3/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.3/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.3/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/100.2.4.3/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56648 WillowSoftware.AnvilStudio version 22.03.02
  manifests/w/WillowSoftware/AnvilStudio/22.03.02/WillowSoftware.AnvilStudio.installer.yaml
  manifests/w/WillowSoftware/AnvilStudio/22.03.02/WillowSoftware.AnvilStudio.locale.en-US.yaml
  manifests/w/WillowSoftware/AnvilStudio/22.03.02/WillowSoftware.AnvilStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56666 TfsCmdlets_2.3.0+2718.3
  manifests/i/Igoravl/TfsCmdlets/2.3.0.2718/Igoravl.TfsCmdlets.installer.yaml
  manifests/i/Igoravl/TfsCmdlets/2.3.0.2718/Igoravl.TfsCmdlets.locale.en-US.yaml
  manifests/i/Igoravl/TfsCmdlets/2.3.0.2718/Igoravl.TfsCmdlets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#56693 New version: MoonchildProductions.PaleMoon version 29.4.5.1
  manifests/m/MoonchildProductions/PaleMoon/29.4.5.1/MoonchildProductions.PaleMoon.installer.yaml
  manifests/m/MoonchildProductions/PaleMoon/29.4.5.1/MoonchildProductions.PaleMoon.locale.en-US.yaml
  manifests/m/MoonchildProductions/PaleMoon/29.4.5.1/MoonchildProductions.PaleMoon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
