Repository microsoft/winget-pkgs, pull requests merged in 2022-02, with the labels that each got.

#44109 Fixed ProductCode JetBrains.Rider version 213.6775.4
  manifests/j/JetBrains/Rider/213.6775.4/JetBrains.Rider.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44114 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44124 DoltHub.Dolt version 0.36.0
  manifests/d/DoltHub/Dolt/0.36.0/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.36.0/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.36.0/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44083 New version: JetBrains.PyCharm.Professional.EAP version 221.3427.103
  manifests/j/JetBrains/PyCharm/Professional/EAP/221.3427.103/JetBrains.PyCharm.Professional.EAP.installer.yaml
  manifests/j/JetBrains/PyCharm/Professional/EAP/221.3427.103/JetBrains.PyCharm.Professional.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Professional/EAP/221.3427.103/JetBrains.PyCharm.Professional.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44082 New version: JetBrains.PyCharm.Community.EAP version 221.3427.103
  manifests/j/JetBrains/PyCharm/Community/EAP/221.3427.103/JetBrains.PyCharm.Community.EAP.installer.yaml
  manifests/j/JetBrains/PyCharm/Community/EAP/221.3427.103/JetBrains.PyCharm.Community.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Community/EAP/221.3427.103/JetBrains.PyCharm.Community.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#43327 Xidicone.AgentSVN version 2.73
  manifests/x/Xidicone/AgentSVN/2.73/Xidicone.AgentSVN.installer.yaml
  manifests/x/Xidicone/AgentSVN/2.73/Xidicone.AgentSVN.locale.en-US.yaml
  manifests/x/Xidicone/AgentSVN/2.73/Xidicone.AgentSVN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#44079 Added JetBrains ReSharper version 2021.3.3.
  manifests/j/JetBrains/ReSharper/2021.3.3/JetBrains.ReSharper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44089 Moved: StefansTools.grepWin version 2.0.1098
  manifests/s/StefansTools/grepWin/2.0.1098/StefansTools.grepWin.installer.yaml
  manifests/s/StefansTools/grepWin/2.0.1098/StefansTools.grepWin.locale.en-US.yaml
  manifests/s/StefansTools/grepWin/2.0.1098/StefansTools.grepWin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44099 New version: Discord.Discord.Development version 1.0.643
  manifests/d/Discord/Discord/Development/1.0.643/Discord.Discord.Development.installer.yaml
  manifests/d/Discord/Discord/Development/1.0.643/Discord.Discord.Development.locale.en-US.yaml
  manifests/d/Discord/Discord/Development/1.0.643/Discord.Discord.Development.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44101 New version: JohnMacFarlane.Pandoc version 2.17.1.1
  manifests/j/JohnMacFarlane/Pandoc/2.17.1.1/JohnMacFarlane.Pandoc.installer.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.17.1.1/JohnMacFarlane.Pandoc.locale.en-US.yaml
  manifests/j/JohnMacFarlane/Pandoc/2.17.1.1/JohnMacFarlane.Pandoc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44104 New version: Microsoft.PowerToys version 0.55.0
  manifests/m/Microsoft/PowerToys/0.55.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.55.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.55.0/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44105 New version: OpenRPAApS.OpenRPA version 1.3.50.0
  manifests/o/OpenRPAApS/OpenRPA/1.3.50.0/OpenRPAApS.OpenRPA.installer.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.50.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.50.0/OpenRPAApS.OpenRPA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44107 Fixed ProductCode JetBrains.PHPStorm version 213.6777.58
  manifests/j/JetBrains/PHPStorm/213.6777.58/JetBrains.PHPStorm.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44095 Lenovo.DockManager version 1.1.1.17
  manifests/l/Lenovo/DockManager/1.1.1.17/Lenovo.DockManager.installer.yaml
  manifests/l/Lenovo/DockManager/1.1.1.17/Lenovo.DockManager.locale.en-US.yaml
  manifests/l/Lenovo/DockManager/1.1.1.17/Lenovo.DockManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44103 New version: Microsoft.Edge.Beta version 98.0.1108.39
  manifests/m/Microsoft/Edge/Beta/98.0.1108.39/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/98.0.1108.39/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/98.0.1108.39/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44080 Added dotUltimate version 2021.3.3.
  manifests/j/JetBrains/dotUltimate/2021.3.3/JetBrains.dotUltimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44112 New version: bornova.numara version 3.10.1
  manifests/b/bornova/numara/3.10.1/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.10.1/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.10.1/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44126 New version: Mirantis.Lens.Alpha version 5.4.0-alpha.0.20220131.1
  manifests/m/Mirantis/Lens/Alpha/5.4.0-alpha.0.20220131.1/Mirantis.Lens.Alpha.installer.yaml
  manifests/m/Mirantis/Lens/Alpha/5.4.0-alpha.0.20220131.1/Mirantis.Lens.Alpha.locale.en-US.yaml
  manifests/m/Mirantis/Lens/Alpha/5.4.0-alpha.0.20220131.1/Mirantis.Lens.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44136 New version: sbt.sbt version 1.6.2
  manifests/s/sbt/sbt/1.6.2/sbt.sbt.installer.yaml
  manifests/s/sbt/sbt/1.6.2/sbt.sbt.locale.en-US.yaml
  manifests/s/sbt/sbt/1.6.2/sbt.sbt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44065 Add version: Streamlink.Streamlink.TwitchGui version 2.0.0
  manifests/s/Streamlink/Streamlink/TwitchGui/v2.0.0/Streamlink.Streamlink.TwitchGui.installer.yaml
  manifests/s/Streamlink/Streamlink/TwitchGui/v2.0.0/Streamlink.Streamlink.TwitchGui.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/TwitchGui/v2.0.0/Streamlink.Streamlink.TwitchGui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44077 New version: PopcornTime.Popcorn-Time-Ru version 0.4.7
  manifests/p/PopcornTime/Popcorn-Time-Ru/0.4.7/PopcornTime.Popcorn-Time-Ru.installer.yaml
  manifests/p/PopcornTime/Popcorn-Time-Ru/0.4.7/PopcornTime.Popcorn-Time-Ru.locale.en-US.yaml
  manifests/p/PopcornTime/Popcorn-Time-Ru/0.4.7/PopcornTime.Popcorn-Time-Ru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44142 Microsoft.VisualStudioCode.Insiders_v1.64.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.64.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44143 New version: OpenRPAApS.OpenRPA version 1.3.51.0
  manifests/o/OpenRPAApS/OpenRPA/1.3.51.0/OpenRPAApS.OpenRPA.installer.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.51.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.3.51.0/OpenRPAApS.OpenRPA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44145 New version: RicoSuter.NSwagStudio version 13.15.6.0
  manifests/r/RicoSuter/NSwagStudio/13.15.6.0/RicoSuter.NSwagStudio.installer.yaml
  manifests/r/RicoSuter/NSwagStudio/13.15.6.0/RicoSuter.NSwagStudio.locale.en-US.yaml
  manifests/r/RicoSuter/NSwagStudio/13.15.6.0/RicoSuter.NSwagStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44138 New version: PawelPsztyc.AdvancedRestClient version 17.0.6
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.6/PawelPsztyc.AdvancedRestClient.installer.yaml
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.6/PawelPsztyc.AdvancedRestClient.locale.en-US.yaml
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.6/PawelPsztyc.AdvancedRestClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44144 New version: Plex.PlexMediaServer version 1.25.4.5487
  manifests/p/Plex/PlexMediaServer/1.25.4.5487/Plex.PlexMediaServer.installer.yaml
  manifests/p/Plex/PlexMediaServer/1.25.4.5487/Plex.PlexMediaServer.locale.en-US.yaml
  manifests/p/Plex/PlexMediaServer/1.25.4.5487/Plex.PlexMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44069 New version: Prometheus.WMIExporter version 0.18.0
  manifests/p/Prometheus/WMIExporter/0.18.0/Prometheus.WMIExporter.installer.yaml
  manifests/p/Prometheus/WMIExporter/0.18.0/Prometheus.WMIExporter.locale.en-US.yaml
  manifests/p/Prometheus/WMIExporter/0.18.0/Prometheus.WMIExporter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44151 New version: chrisant996.Clink version 1.3.5.f378c8
  manifests/c/chrisant996/Clink/1.3.5.f378c8/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.3.5.f378c8/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.3.5.f378c8/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#43818 New version: JetBrains.GoLand version 213.6777.51
  manifests/j/JetBrains/GoLand/213.6777.51/JetBrains.GoLand.installer.yaml
  manifests/j/JetBrains/GoLand/213.6777.51/JetBrains.GoLand.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/213.6777.51/JetBrains.GoLand.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44137 New version: WeMod.WeMod.Beta version 8.0.0-beta03
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta03/WeMod.WeMod.Beta.installer.yaml
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta03/WeMod.WeMod.Beta.locale.en-US.yaml
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta03/WeMod.WeMod.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44100 New version: JanProchazka.dbgate version 4.6.1
  manifests/j/JanProchazka/dbgate/4.6.1/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/4.6.1/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/4.6.1/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44078 New version: Prey.Prey version 1.9.17
  manifests/p/Prey/Prey/1.9.17/Prey.Prey.installer.yaml
  manifests/p/Prey/Prey/1.9.17/Prey.Prey.locale.en-US.yaml
  manifests/p/Prey/Prey/1.9.17/Prey.Prey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44128 New version: vim.vim version 8.2.4277
  manifests/v/vim/vim/8.2.4277/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.4277/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.4277/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44150 New version: Tutanota.Tutanota version 3.91.6
  manifests/t/Tutanota/Tutanota/3.91.6/Tutanota.Tutanota.installer.yaml
  manifests/t/Tutanota/Tutanota/3.91.6/Tutanota.Tutanota.locale.en-US.yaml
  manifests/t/Tutanota/Tutanota/3.91.6/Tutanota.Tutanota.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44127 New version: Telegram.TelegramDesktop version 3.5.0
  manifests/t/Telegram/TelegramDesktop/3.5.0/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/3.5.0/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/3.5.0/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44134 New version: Jackett.Jackett version 0.20.494.0
  manifests/j/Jackett/Jackett/0.20.494.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.494.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.494.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44156 GitHub.cli version 2.5.0
  manifests/g/GitHub/cli/2.5.0/GitHub.cli.installer.yaml
  manifests/g/GitHub/cli/2.5.0/GitHub.cli.locale.en-US.yaml
  manifests/g/GitHub/cli/2.5.0/GitHub.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44155 New version: Sohu.SHPlayer version 7.0.11.0
  manifests/s/Sohu/SHPlayer/7.0.11.0/Sohu.SHPlayer.installer.yaml
  manifests/s/Sohu/SHPlayer/7.0.11.0/Sohu.SHPlayer.locale.en-US.yaml
  manifests/s/Sohu/SHPlayer/7.0.11.0/Sohu.SHPlayer.locale.zh-CN.yaml
  manifests/s/Sohu/SHPlayer/7.0.11.0/Sohu.SHPlayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44169 Duplicate: BitSum.ParkControl version 1.6.0.10
  manifests/b/BitSum/ParkControl/1.6.0.10/BitSum.ParkControl.installer.yaml
  manifests/b/BitSum/ParkControl/1.6.0.10/BitSum.ParkControl.locale.en-US.yaml
  manifests/b/BitSum/ParkControl/1.6.0.10/BitSum.ParkControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44157 Microsoft.VisualStudioCode.Insiders_v1.64.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.64.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44158 Fix Scope for BinaryMark.BatchPhotoFace version 5.6
  manifests/b/BinaryMark/BatchPhotoFace/5.6/BinaryMark.BatchPhotoFace.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44160 Fix Scope for BinaryMark.BatchRegEx version 5.0
  manifests/b/BinaryMark/BatchRegEx/5.0/BinaryMark.BatchRegEx.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44162 For Scope for BinaryMark.BatchWordReplace version 5.6
  manifests/b/BinaryMark/BatchWordReplace/5.6/BinaryMark.BatchWordReplace.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44161 For Scope for BinaryMark.BatchTextFileEditor version 5.0
  manifests/b/BinaryMark/BatchTextFileEditor/5.0/BinaryMark.BatchTextFileEditor.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44164 New package: ForgQi.Biliup version 0.1.0
  manifests/f/ForgQi/Biliup/0.1.0/ForgQi.Biliup.installer.yaml
  manifests/f/ForgQi/Biliup/0.1.0/ForgQi.Biliup.locale.en-US.yaml
  manifests/f/ForgQi/Biliup/0.1.0/ForgQi.Biliup.locale.zh-CN.yaml
  manifests/f/ForgQi/Biliup/0.1.0/ForgQi.Biliup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44165 New version: LiskFoundation.LiskHub version 2.2.0
  manifests/l/LiskFoundation/LiskHub/2.2.0/LiskFoundation.LiskHub.installer.yaml
  manifests/l/LiskFoundation/LiskHub/2.2.0/LiskFoundation.LiskHub.locale.en-US.yaml
  manifests/l/LiskFoundation/LiskHub/2.2.0/LiskFoundation.LiskHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44167 Add Scope for BitSum.Coreprio version 0.0.6.8
  manifests/b/BitSum/Coreprio/0.0.6.8/BitSum.Coreprio.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44148 New version: Blade.Shadow version 5.0.1067
  manifests/b/Blade/Shadow/5.0.1067/Blade.Shadow.installer.yaml
  manifests/b/Blade/Shadow/5.0.1067/Blade.Shadow.locale.en-US.yaml
  manifests/b/Blade/Shadow/5.0.1067/Blade.Shadow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44170 Add Scope for CaffeineInc.Caffeine version 1.7.0.443
  manifests/c/CaffeineInc/Caffeine/1.7.0.443/CaffeineInc.Caffeine.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44175 New version: RicoSuter.NSwagStudio version 13.15.7.0
  manifests/r/RicoSuter/NSwagStudio/13.15.7.0/RicoSuter.NSwagStudio.installer.yaml
  manifests/r/RicoSuter/NSwagStudio/13.15.7.0/RicoSuter.NSwagStudio.locale.en-US.yaml
  manifests/r/RicoSuter/NSwagStudio/13.15.7.0/RicoSuter.NSwagStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44171 Add Scope for Cencit.Bas21 version 1.6.0
  manifests/c/Cencit/Bas21/1.6.0/Cencit.Bas21.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44173 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44174 Add version: OpenJS.NodeJS.LTS version 14.19.0
  manifests/o/OpenJS/NodeJS/LTS/14.19.0/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.19.0/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.19.0/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44159 New version: BraveSoftware.BraveBrowser.Dev version 98.1.36.81
  manifests/b/BraveSoftware/BraveBrowser/Dev/98.1.36.81/BraveSoftware.BraveBrowser.Dev.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/98.1.36.81/BraveSoftware.BraveBrowser.Dev.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Dev/98.1.36.81/BraveSoftware.BraveBrowser.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44009 PaulWoolcock.SyncOutlookandGooglecalendars.alpha version 2.9.2-alpha
  manifests/p/PaulWoolcock/SyncOutlookandGooglecalendars/alpha/2.9.2-alpha/PaulWoolcock.SyncOutlookandGooglecalendars.alpha.installer.yaml
  manifests/p/PaulWoolcock/SyncOutlookandGooglecalendars/alpha/2.9.2-alpha/PaulWoolcock.SyncOutlookandGooglecalendars.alpha.locale.en-US.yaml
  manifests/p/PaulWoolcock/SyncOutlookandGooglecalendars/alpha/2.9.2-alpha/PaulWoolcock.SyncOutlookandGooglecalendars.alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44197 Remove: Kiwix.KiwixJS.Electron version 1.7.5E
  manifests/k/Kiwix/KiwixJS/Electron/1.7.5E/Kiwix.KiwixJS.Electron.installer.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.5E/Kiwix.KiwixJS.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.5E/Kiwix.KiwixJS.Electron.locale.en-US.yaml
  manifests/k/Kiwix/KiwixJS/Electron/1.7.5E/Kiwix.KiwixJS.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44216 Remove: Microsoft.Teams.Preview version 1.4.00.11161
  manifests/m/Microsoft/Teams/Preview/1.4.00.11161/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44209 Remove Duplicate: Joplin.Joplin.Pre-release version 2.3.5
  manifests/j/Joplin/Joplin/Pre-release/2.3.5/Joplin.Joplin.Pre-release.installer.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.3.5/Joplin.Joplin.Pre-release.locale.en-US.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.3.5/Joplin.Joplin.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44207 Remove Duplicate: GeoGebra.GraphingCalculator version 6.0.683
  manifests/g/GeoGebra/GraphingCalculator/6.0.683/GeoGebra.GraphingCalculator.installer.yaml
  manifests/g/GeoGebra/GraphingCalculator/6.0.683/GeoGebra.GraphingCalculator.locale.en-US.yaml
  manifests/g/GeoGebra/GraphingCalculator/6.0.683/GeoGebra.GraphingCalculator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44205 Remove Duplicate: GeoGebra.Classic.5 version 5.0.683.0
  manifests/g/GeoGebra/Classic/5/5.0.683.0/GeoGebra.Classic.5.installer.yaml
  manifests/g/GeoGebra/Classic/5/5.0.683.0/GeoGebra.Classic.5.locale.en-US.yaml
  manifests/g/GeoGebra/Classic/5/5.0.683.0/GeoGebra.Classic.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44218 Remove: Microsoft.Teams.Preview version 1.4.00.26376
  manifests/m/Microsoft/Teams/Preview/1.4.00.26376/Microsoft.Teams.Preview.installer.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.26376/Microsoft.Teams.Preview.locale.en-US.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.26376/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44203 Remove Duplicate: GeoGebra.CalculatorSuite version 6.0.683
  manifests/g/GeoGebra/CalculatorSuite/6.0.683/GeoGebra.CalculatorSuite.installer.yaml
  manifests/g/GeoGebra/CalculatorSuite/6.0.683/GeoGebra.CalculatorSuite.locale.en-US.yaml
  manifests/g/GeoGebra/CalculatorSuite/6.0.683/GeoGebra.CalculatorSuite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44210 Remove Duplicate: Microsoft.WindowsTerminal.Preview version 1.10.2383.0
  manifests/m/Microsoft/WindowsTerminal/Preview/1.10.2383.0/Microsoft.WindowsTerminal.Preview.installer.yaml
  manifests/m/Microsoft/WindowsTerminal/Preview/1.10.2383.0/Microsoft.WindowsTerminal.Preview.locale.en-US.yaml
  manifests/m/Microsoft/WindowsTerminal/Preview/1.10.2383.0/Microsoft.WindowsTerminal.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44202 Remove Duplicate: ESET.Security version 15.0.18.0
  manifests/e/ESET/Security/15.0.18.0/ESET.Security.installer.yaml
  manifests/e/ESET/Security/15.0.18.0/ESET.Security.locale.en-US.yaml
  manifests/e/ESET/Security/15.0.18.0/ESET.Security.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44200 Remove Duplicate: Postman.Postman.Canary version 9.10.0-canary01
  manifests/p/Postman/Postman/Canary/9.10.0-canary01/Postman.Postman.Canary.installer.yaml
  manifests/p/Postman/Postman/Canary/9.10.0-canary01/Postman.Postman.Canary.locale.en-US.yaml
  manifests/p/Postman/Postman/Canary/9.10.0-canary01/Postman.Postman.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44220 Remove: Microsoft.Teams.Preview version 1.4.00.32771
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.installer.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.locale.en-US.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.32771/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44219 Remove: Microsoft.Teams.Preview version 1.4.00.29469
  manifests/m/Microsoft/Teams/Preview/1.4.00.29469/Microsoft.Teams.Preview.installer.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.29469/Microsoft.Teams.Preview.locale.en-US.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.29469/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44198 Fix InstallerUrl: Sandboxie.Plus version 0.9.8
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.9.8/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44193 New version: ClipTeam.ClipCC.Beta version 3.0.0-beta4
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta4/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta4/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta4/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44192 New version: ClipTeam.ClipCC.Beta version 3.0.0-beta3
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta3/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta3/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta3/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44194 New version: ClipTeam.ClipCC.Beta version 3.0.1-beta1
  manifests/c/ClipTeam/ClipCC/Beta/3.0.1-beta1/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.1-beta1/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.1-beta1/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44222 Remove: Microsoft.Teams.Preview version 1.4.00.8872
  manifests/m/Microsoft/Teams/Preview/1.4.00.8872/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44204 Remove Duplicate: GeoGebra.Classic version 6.0.683
  manifests/g/GeoGebra/Classic/6.0.683/GeoGebra.Classic.installer.yaml
  manifests/g/GeoGebra/Classic/6.0.683/GeoGebra.Classic.locale.en-US.yaml
  manifests/g/GeoGebra/Classic/6.0.683/GeoGebra.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44217 Remove: Microsoft.Teams.Preview version 1.4.00.22472
  manifests/m/Microsoft/Teams/Preview/1.4.00.22472/Microsoft.Teams.Preview.installer.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.22472/Microsoft.Teams.Preview.locale.en-US.yaml
  manifests/m/Microsoft/Teams/Preview/1.4.00.22472/Microsoft.Teams.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44196 New version: ClipTeam.ClipCC.Beta version 3.1.0-beta1
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta1/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta1/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta1/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44184 New package: B3log.SiYuan version 1.7.10
  manifests/b/B3log/SiYuan/1.7.10/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/1.7.10/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/1.7.10/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/1.7.10/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44188 New version: ClipTeam.ClipCC.Beta version 3.1.0-beta4
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta4/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta4/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta4/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44179 CodecGuide.K-LiteCodecPack.Mega version 16.8.0
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.8.0/CodecGuide.K-LiteCodecPack.Mega.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.8.0/CodecGuide.K-LiteCodecPack.Mega.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.8.0/CodecGuide.K-LiteCodecPack.Mega.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44176 CodecGuide.K-LiteCodecPack.Basic version 16.8.0
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.8.0/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.8.0/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.8.0/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44187 New version: ClipTeam.ClipCC.Beta version 3.1.0-beta3
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta3/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta3/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta3/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44185 New package: ClipTeam.ClipCC.Beta version 3.1.0-beta2
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta2/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta2/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta2/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44181 New version: GDevelop.GDevelop version 5.0.127
  manifests/g/GDevelop/GDevelop/5.0.127/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.0.127/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.0.127/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44191 New version: ClipTeam.ClipCC.Beta version 3.0.0-beta2
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta2/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta2/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.0-beta2/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44195 New Version: ClipTeam.ClipCC.Beta version 3.0.2-beta1
  manifests/c/ClipTeam/ClipCC/Beta/3.0.2-beta1/ClipTeam.ClipCC.Beta.installer.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.2-beta1/ClipTeam.ClipCC.Beta.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/Beta/3.0.2-beta1/ClipTeam.ClipCC.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44199 Fix InstallerUrl: GoLang.Go version 1.16.0
  manifests/g/GoLang/Go/1.16.0/GoLang.Go.installer.yaml
  manifests/g/GoLang/Go/1.16.0/GoLang.Go.locale.en-US.yaml
  manifests/g/GoLang/Go/1.16.0/GoLang.Go.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44212 Duplicate arm64 url: Microsoft.Edge v94.0.992.37
  manifests/m/Microsoft/Edge/94.0.992.37/Microsoft.Edge.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44226 Add version: Kitware.CMake version 3.21.5
  manifests/k/Kitware/CMake/3.21.5/Kitware.CMake.installer.yaml
  manifests/k/Kitware/CMake/3.21.5/Kitware.CMake.locale.en-US.yaml
  manifests/k/Kitware/CMake/3.21.5/Kitware.CMake.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#44177 CodecGuide.K-LiteCodecPack.Full version 16.8.0
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.8.0/CodecGuide.K-LiteCodecPack.Full.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.8.0/CodecGuide.K-LiteCodecPack.Full.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.8.0/CodecGuide.K-LiteCodecPack.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44227 New version: WeMod.WeMod.Beta version 8.0.0-beta04
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta04/WeMod.WeMod.Beta.installer.yaml
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta04/WeMod.WeMod.Beta.locale.en-US.yaml
  manifests/w/WeMod/WeMod/Beta/8.0.0-beta04/WeMod.WeMod.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44213 Remove: Typora.Typora version 1.0.3
  manifests/t/Typora/Typora/1.0.3/Typora.Typora.installer.yaml
  manifests/t/Typora/Typora/1.0.3/Typora.Typora.locale.en-US.yaml
  manifests/t/Typora/Typora/1.0.3/Typora.Typora.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44208 Remove Duplicate: Microsoft.VisualStudio.2019.Professional version 16.11.6
  manifests/m/Microsoft/VisualStudio/2019/Professional/16.11.6/Microsoft.VisualStudio.2019.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44231 Add version: ClipTeam.ClipCC version 3.0.0
  manifests/c/ClipTeam/ClipCC/3.0.0/ClipTeam.ClipCC.installer.yaml
  manifests/c/ClipTeam/ClipCC/3.0.0/ClipTeam.ClipCC.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/3.0.0/ClipTeam.ClipCC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44206 Remove Duplicate: GeoGebra.Geometry version 6.0.683
  manifests/g/GeoGebra/Geometry/6.0.683/GeoGebra.Geometry.installer.yaml
  manifests/g/GeoGebra/Geometry/6.0.683/GeoGebra.Geometry.locale.en-US.yaml
  manifests/g/GeoGebra/Geometry/6.0.683/GeoGebra.Geometry.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44230 Add version: ClipTeam.ClipCC version 3.0.1
  manifests/c/ClipTeam/ClipCC/3.0.1/ClipTeam.ClipCC.installer.yaml
  manifests/c/ClipTeam/ClipCC/3.0.1/ClipTeam.ClipCC.locale.en-US.yaml
  manifests/c/ClipTeam/ClipCC/3.0.1/ClipTeam.ClipCC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44224 New version: Google.Chrome.Dev version 99.0.4844.16
  manifests/g/Google/Chrome/Dev/99.0.4844.16/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/99.0.4844.16/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/99.0.4844.16/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/99.0.4844.16/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44211 Remove Duplicate: WinMerge.WinMerge.Beta version 2.16.16
  manifests/w/WinMerge/WinMerge/Beta/2.16.16/WinMerge.WinMerge.Beta.installer.yaml
  manifests/w/WinMerge/WinMerge/Beta/2.16.16/WinMerge.WinMerge.Beta.locale.en-US.yaml
  manifests/w/WinMerge/WinMerge/Beta/2.16.16/WinMerge.WinMerge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44225 New version: joncampbell123.DOSBox-X version 0.83.22
  manifests/j/joncampbell123/DOSBox-X/0.83.22/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.22/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.22/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44238 New version: JannisX11.Blockbench version 4.1.4
  manifests/j/JannisX11/Blockbench/4.1.4/JannisX11.Blockbench.installer.yaml
  manifests/j/JannisX11/Blockbench/4.1.4/JannisX11.Blockbench.locale.en-US.yaml
  manifests/j/JannisX11/Blockbench/4.1.4/JannisX11.Blockbench.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44241 Update: KDE.umbrello version 21.12.1
  manifests/k/KDE/umbrello/21.12.1/KDE.umbrello.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44186 New version: lostdesign.linked version 1.4.0
  manifests/l/lostdesign/linked/1.4.0/lostdesign.linked.installer.yaml
  manifests/l/lostdesign/linked/1.4.0/lostdesign.linked.locale.en-US.yaml
  manifests/l/lostdesign/linked/1.4.0/lostdesign.linked.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44245 New version: Microsoft.Edge.Dev version 99.0.1150.2
  manifests/m/Microsoft/Edge/Dev/99.0.1150.2/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/99.0.1150.2/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/99.0.1150.2/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44239 New version: JetBrains.CLion version 213.6777.58
  manifests/j/JetBrains/CLion/213.6777.58/JetBrains.CLion.installer.yaml
  manifests/j/JetBrains/CLion/213.6777.58/JetBrains.CLion.locale.en-US.yaml
  manifests/j/JetBrains/CLion/213.6777.58/JetBrains.CLion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44229 New version: Kopia.KopiaUI version 0.10.3
  manifests/k/Kopia/KopiaUI/0.10.3/Kopia.KopiaUI.installer.yaml
  manifests/k/Kopia/KopiaUI/0.10.3/Kopia.KopiaUI.locale.en-US.yaml
  manifests/k/Kopia/KopiaUI/0.10.3/Kopia.KopiaUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44234 Remove: AndrewsTech.Alpha-Video version 1.7
  manifests/a/AndrewsTech/Alpha-Video/1.7/AndrewsTech.Alpha-Video.installer.yaml
  manifests/a/AndrewsTech/Alpha-Video/1.7/AndrewsTech.Alpha-Video.locale.en-US.yaml
  manifests/a/AndrewsTech/Alpha-Video/1.7/AndrewsTech.Alpha-Video.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44252 New version: 64Gram.64Gram version 1.0.12
  manifests/6/64Gram/64Gram/1.0.12/64Gram.64Gram.installer.yaml
  manifests/6/64Gram/64Gram/1.0.12/64Gram.64Gram.locale.en-US.yaml
  manifests/6/64Gram/64Gram/1.0.12/64Gram.64Gram.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44248 New version: M2Team.NanaZip.Preview version 1.1.153.0
  manifests/m/M2Team/NanaZip/Preview/1.1.153.0/M2Team.NanaZip.Preview.installer.yaml
  manifests/m/M2Team/NanaZip/Preview/1.1.153.0/M2Team.NanaZip.Preview.locale.en-US.yaml
  manifests/m/M2Team/NanaZip/Preview/1.1.153.0/M2Team.NanaZip.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44247 New version: cawa-93.anime-library version 22.2.1-791
  manifests/c/cawa-93/anime-library/22.2.1-791/cawa-93.anime-library.installer.yaml
  manifests/c/cawa-93/anime-library/22.2.1-791/cawa-93.anime-library.locale.en-US.yaml
  manifests/c/cawa-93/anime-library/22.2.1-791/cawa-93.anime-library.locale.ru-RU.yaml
  manifests/c/cawa-93/anime-library/22.2.1-791/cawa-93.anime-library.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44246 New version: AutomatedLab.AutomatedLab version 5.41.0
  manifests/a/AutomatedLab/AutomatedLab/5.41.0/AutomatedLab.AutomatedLab.installer.yaml
  manifests/a/AutomatedLab/AutomatedLab/5.41.0/AutomatedLab.AutomatedLab.locale.en-US.yaml
  manifests/a/AutomatedLab/AutomatedLab/5.41.0/AutomatedLab.AutomatedLab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44251 New version: Sandboxie.Classic version 5.55.9
  manifests/s/Sandboxie/Classic/5.55.9/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.55.9/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.55.9/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44240 New version: WestWind.MarkdownMonster version 2.3.7.0
  manifests/w/WestWind/MarkdownMonster/2.3.7.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.3.7.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.3.7.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44237 New version: Elastic.Winlogbeat version 7.17.0
  manifests/e/Elastic/Winlogbeat/7.17.0/Elastic.Winlogbeat.installer.yaml
  manifests/e/Elastic/Winlogbeat/7.17.0/Elastic.Winlogbeat.locale.en-US.yaml
  manifests/e/Elastic/Winlogbeat/7.17.0/Elastic.Winlogbeat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44255 Update: KDE.KDEConnect version 21.12.1
  manifests/k/KDE/KDEConnect/21.12.1/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44260 Add version: OpenJS.NodeJS.LTS version 12.22.10
  manifests/o/OpenJS/NodeJS/LTS/12.22.10/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.10/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.10/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44244 Update: KDE.LabPlot version 2.8.2-1 build 656
  manifests/k/KDE/LabPlot/2.8.2-1/KDE.LabPlot.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44243 Update: KDE.kexi version 3.2-e6671f457 build 1124
  manifests/k/KDE/kexi/3.2-e6671f457/KDE.kexi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44250 New version: Sandboxie.Plus version 1.0.9
  manifests/s/Sandboxie/Plus/1.0.9/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.0.9/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.0.9/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#43902 DoltHub.Dolt version 0.35.10
  manifests/d/DoltHub/Dolt/0.35.10/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.35.10/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.35.10/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#44223 New version: Git.Git version 2.35.1.2
  manifests/g/Git/Git/2.35.1.2/Git.Git.installer.yaml
  manifests/g/Git/Git/2.35.1.2/Git.Git.locale.en-US.yaml
  manifests/g/Git/Git/2.35.1.2/Git.Git.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#44280 Update: e2eSoft.iVCam version 7.0.0
  manifests/e/e2eSoft/iVCam/7.0.0/e2eSoft.iVCam.installer.yaml
  manifests/e/e2eSoft/iVCam/7.0.0/e2eSoft.iVCam.locale.en-US.yaml
  manifests/e/e2eSoft/iVCam/7.0.0/e2eSoft.iVCam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44284 Microsoft.VisualStudioCode.Insiders_v1.64.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.64.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44256 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44257 New version: KirillOsenkov.MSBuildStructuredLogViewer version 2.1.627
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.627/KirillOsenkov.MSBuildStructuredLogViewer.installer.yaml
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.627/KirillOsenkov.MSBuildStructuredLogViewer.locale.en-US.yaml
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.627/KirillOsenkov.MSBuildStructuredLogViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44264 New version: PawelPsztyc.AdvancedRestClient version 17.0.7
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.7/PawelPsztyc.AdvancedRestClient.installer.yaml
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.7/PawelPsztyc.AdvancedRestClient.locale.en-US.yaml
  manifests/p/PawelPsztyc/AdvancedRestClient/17.0.7/PawelPsztyc.AdvancedRestClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44265 New version: vim.vim version 8.2.4282
  manifests/v/vim/vim/8.2.4282/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.4282/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.4282/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44270 Update: Xidicone.AgentGit version 1.85
  manifests/x/Xidicone/AgentGit/1.85/Xidicone.AgentGit.installer.yaml
  manifests/x/Xidicone/AgentGit/1.85/Xidicone.AgentGit.locale.en-US.yaml
  manifests/x/Xidicone/AgentGit/1.85/Xidicone.AgentGit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44281 New version: e2eSoft.iVCam version 7.0.1
  manifests/e/e2eSoft/iVCam/7.0.1/e2eSoft.iVCam.installer.yaml
  manifests/e/e2eSoft/iVCam/7.0.1/e2eSoft.iVCam.locale.en-US.yaml
  manifests/e/e2eSoft/iVCam/7.0.1/e2eSoft.iVCam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44273 New version: altair-graphql.altair version 4.4.0
  manifests/a/altair-graphql/altair/4.4.0/altair-graphql.altair.installer.yaml
  manifests/a/altair-graphql/altair/4.4.0/altair-graphql.altair.locale.en-US.yaml
  manifests/a/altair-graphql/altair/4.4.0/altair-graphql.altair.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44274 New version: Clement.bottom version 0.6.8
  manifests/c/Clement/bottom/0.6.8/Clement.bottom.installer.yaml
  manifests/c/Clement/bottom/0.6.8/Clement.bottom.locale.en-US.yaml
  manifests/c/Clement/bottom/0.6.8/Clement.bottom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44276 Update: Xidicone.ZeusIDE version 3.98y
  manifests/x/Xidicone/ZeusIDE/3.98y/Xidicone.ZeusIDE.installer.yaml
  manifests/x/Xidicone/ZeusIDE/3.98y/Xidicone.ZeusIDE.locale.en-US.yaml
  manifests/x/Xidicone/ZeusIDE/3.98y/Xidicone.ZeusIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44278 New version: MonkeysAudio.MonkeysAudio version 7.25
  manifests/m/MonkeysAudio/MonkeysAudio/7.23/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/7.25/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/7.25/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/7.25/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44285 New version: CertifyTheWeb.CertifySSLManager version 5.6.5
  manifests/c/CertifyTheWeb/CertifySSLManager/5.6.5/CertifyTheWeb.CertifySSLManager.installer.yaml
  manifests/c/CertifyTheWeb/CertifySSLManager/5.6.5/CertifyTheWeb.CertifySSLManager.locale.en-US.yaml
  manifests/c/CertifyTheWeb/CertifySSLManager/5.6.5/CertifyTheWeb.CertifySSLManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44286 New version: Jackett.Jackett version 0.20.497.0
  manifests/j/Jackett/Jackett/0.20.497.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.497.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.497.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44263 New version: Discord.Discord.Development version 1.0.644
  manifests/d/Discord/Discord/Development/1.0.644/Discord.Discord.Development.installer.yaml
  manifests/d/Discord/Discord/Development/1.0.644/Discord.Discord.Development.locale.en-US.yaml
  manifests/d/Discord/Discord/Development/1.0.644/Discord.Discord.Development.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44262 New version: Discord.Discord.Canary version 1.0.44
  manifests/d/Discord/Discord/Canary/1.0.44/Discord.Discord.Canary.installer.yaml
  manifests/d/Discord/Discord/Canary/1.0.44/Discord.Discord.Canary.locale.en-US.yaml
  manifests/d/Discord/Discord/Canary/1.0.44/Discord.Discord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44275 New version: HearthSim.HearthstoneDeckTracker version 1.17.4
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.4/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.4/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.4/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44289 Submitting HttpMaster Express 5.4.0
  manifests/b/Borvid/HttpMasterExpress/5.4.0/Borvid.HttpMasterExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44272 Update: Xidicone.ZeusLite version 3.97z
  manifests/x/Xidicone/ZeusLite/3.97z/Xidicone.ZeusLite.installer.yaml
  manifests/x/Xidicone/ZeusLite/3.97z/Xidicone.ZeusLite.locale.en-US.yaml
  manifests/x/Xidicone/ZeusLite/3.97z/Xidicone.ZeusLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44258 New version: maygo.tockler version 3.21.12
  manifests/m/maygo/tockler/3.21.12/maygo.tockler.installer.yaml
  manifests/m/maygo/tockler/3.21.12/maygo.tockler.locale.en-US.yaml
  manifests/m/maygo/tockler/3.21.12/maygo.tockler.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44290 Submitting HttpMaster Professional 5.4.0
  manifests/b/Borvid/HttpMasterProfessional/5.4.0/Borvid.HttpMasterProfessional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44287 Update: KDE.Kate version 21.12.1
  manifests/k/KDE/Kate/21.12.1/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44266 New version: WeMod.WeMod version 8.0.1
  manifests/w/WeMod/WeMod/8.0.1/WeMod.WeMod.installer.yaml
  manifests/w/WeMod/WeMod/8.0.1/WeMod.WeMod.locale.en-US.yaml
  manifests/w/WeMod/WeMod/8.0.1/WeMod.WeMod.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44277 Update: Xidicone.AgentSVN version 2.72
  manifests/x/Xidicone/AgentSVN/2.72/Xidicone.AgentSVN.installer.yaml
  manifests/x/Xidicone/AgentSVN/2.72/Xidicone.AgentSVN.locale.en-US.yaml
  manifests/x/Xidicone/AgentSVN/2.72/Xidicone.AgentSVN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44298 Flow-Launcher.Flow-Launcher version 1.9.2
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.2/Flow-Launcher.Flow-Launcher.installer.yaml
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.2/Flow-Launcher.Flow-Launcher.locale.en-US.yaml
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.2/Flow-Launcher.Flow-Launcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44300 New version: qishibo.AnotherRedisDesktopManager version 1.5.2
  manifests/q/qishibo/AnotherRedisDesktopManager/1.5.2/qishibo.AnotherRedisDesktopManager.installer.yaml
  manifests/q/qishibo/AnotherRedisDesktopManager/1.5.2/qishibo.AnotherRedisDesktopManager.locale.en-US.yaml
  manifests/q/qishibo/AnotherRedisDesktopManager/1.5.2/qishibo.AnotherRedisDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44305 New version: jeffvli.Sonixd version 0.12.1
  manifests/j/jeffvli/Sonixd/0.12.1/jeffvli.Sonixd.installer.yaml
  manifests/j/jeffvli/Sonixd/0.12.1/jeffvli.Sonixd.locale.en-US.yaml
  manifests/j/jeffvli/Sonixd/0.12.1/jeffvli.Sonixd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44307 New version: Microsoft.AccessibilityInsights.Windows.Canary version 1.1.1858.01
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1858.01/Microsoft.AccessibilityInsights.Windows.Canary.installer.yaml
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1858.01/Microsoft.AccessibilityInsights.Windows.Canary.locale.en-US.yaml
  manifests/m/Microsoft/AccessibilityInsights/Windows/Canary/1.1.1858.01/Microsoft.AccessibilityInsights.Windows.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44309 New version: Datadog.dd-trace-dotnet version 2.2.0
  manifests/d/Datadog/dd-trace-dotnet/2.2.0/Datadog.dd-trace-dotnet.installer.yaml
  manifests/d/Datadog/dd-trace-dotnet/2.2.0/Datadog.dd-trace-dotnet.locale.en-US.yaml
  manifests/d/Datadog/dd-trace-dotnet/2.2.0/Datadog.dd-trace-dotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44311 Diladele Web Filtering Proxy 2.0
  manifests/d/Diladele/WebProxy/2.0.0.0/Diladele.WebProxy.installer.yaml
  manifests/d/Diladele/WebProxy/2.0.0.0/Diladele.WebProxy.locale.en-US.yaml
  manifests/d/Diladele/WebProxy/2.0.0.0/Diladele.WebProxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44304 Added .cc3 file extension
  manifests/c/ClipTeam/ClipCC/Beta/3.1.0-beta4/ClipTeam.ClipCC.Beta.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44292 New version: Mobirise.Mobirise version 5.6.0
  manifests/m/Mobirise/Mobirise/5.6.0/Mobirise.Mobirise.installer.yaml
  manifests/m/Mobirise/Mobirise/5.6.0/Mobirise.Mobirise.locale.en-US.yaml
  manifests/m/Mobirise/Mobirise/5.6.0/Mobirise.Mobirise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
