Repository microsoft/winget-pkgs, pull requests merged in 2022-01, with the labels that each got.

#39567 Hash: Google.JapaneseIME version 2.25.3700.0
  manifests/g/Google/JapaneseIME/2.25.3700.0/Google.JapaneseIME.installer.yaml
  manifests/g/Google/JapaneseIME/2.25.3700.0/Google.JapaneseIME.locale.en-US.yaml
  manifests/g/Google/JapaneseIME/2.25.3700.0/Google.JapaneseIME.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39566 New version: Google.BackupAndSync version 3.57.4043.4118
  manifests/g/Google/BackupAndSync/3.57.3958.2866/Google.BackupAndSync.installer.yaml
  manifests/g/Google/BackupAndSync/3.57.3958.2866/Google.BackupAndSync.locale.en-US.yaml
  manifests/g/Google/BackupAndSync/3.57.3958.2866/Google.BackupAndSync.yaml
  manifests/g/Google/BackupAndSync/3.57.4043.4118/Google.BackupAndSync.installer.yaml
  manifests/g/Google/BackupAndSync/3.57.4043.4118/Google.BackupAndSync.locale.en-US.yaml
  manifests/g/Google/BackupAndSync/3.57.4043.4118/Google.BackupAndSync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#39571 New version: Notepad++.Notepad++ version 8.2
  manifests/n/Notepad++/Notepad++/8.2/Notepad++.Notepad++.installer.yaml
  manifests/n/Notepad++/Notepad++/8.2/Notepad++.Notepad++.locale.en-US.yaml
  manifests/n/Notepad++/Notepad++/8.2/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39581 WiresharkFoundation.Wireshark version 3.6.1.0
  manifests/w/WiresharkFoundation/Wireshark/3.6.1.0/WiresharkFoundation.Wireshark.installer.yaml
  manifests/w/WiresharkFoundation/Wireshark/3.6.1.0/WiresharkFoundation.Wireshark.locale.en-US.yaml
  manifests/w/WiresharkFoundation/Wireshark/3.6.1.0/WiresharkFoundation.Wireshark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39575 New version: ElijahLopez.MusicCaster version 4.90.154
  manifests/e/ElijahLopez/MusicCaster/4.90.154/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.154/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.154/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39577 New version: Plex.Plexamp version 3.9.0
  manifests/p/Plex/Plexamp/3.9.0/Plex.Plexamp.installer.yaml
  manifests/p/Plex/Plexamp/3.9.0/Plex.Plexamp.locale.en-US.yaml
  manifests/p/Plex/Plexamp/3.9.0/Plex.Plexamp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39572 Julialang.Julia version 1.7.1
  manifests/j/Julialang/Julia/1.7.1/Julialang.Julia.installer.yaml
  manifests/j/Julialang/Julia/1.7.1/Julialang.Julia.locale.en-US.yaml
  manifests/j/Julialang/Julia/1.7.1/Julialang.Julia.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39583 Update Microsoft.VisioViewer.yaml
  manifests/m/Microsoft/VisioViewer/16.0.4339.1001/Microsoft.VisioViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39585 New version: Jackett.Jackett version 0.20.222.0
  manifests/j/Jackett/Jackett/0.20.222.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.222.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.222.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39578 Update Netron to 5.4.9
  manifests/l/LutzRoeder/Netron/5.4.9/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.4.9/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.4.9/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39584 New version: ElijahLopez.MusicCaster version 4.90.155
  manifests/e/ElijahLopez/MusicCaster/4.90.155/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.155/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.155/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39586 Update HydrologicEngineeringCenter.HEC-RAS.locale.en-US.yaml
  manifests/h/HydrologicEngineeringCenter/HEC-RAS/6.1.0.0/HydrologicEngineeringCenter.HEC-RAS.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39595 New version: Google.Chrome.Canary version 99.0.4800.0
  manifests/g/Google/Chrome/Canary/99.0.4800.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4800.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4800.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4800.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39596 New version: joncampbell123.DOSBox-X version 0.83.21
  manifests/j/joncampbell123/DOSBox-X/0.83.21/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.21/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.21/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39609 New version: lyswhut.lx-music-desktop version 1.16.0
  manifests/l/lyswhut/lx-music-desktop/1.16.0/lyswhut.lx-music-desktop.installer.yaml
  manifests/l/lyswhut/lx-music-desktop/1.16.0/lyswhut.lx-music-desktop.locale.en-US.yaml
  manifests/l/lyswhut/lx-music-desktop/1.16.0/lyswhut.lx-music-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39611 remove 1.1.0.79
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.79/LovettSoftware.MyMoney.Net.installer.yaml
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.79/LovettSoftware.MyMoney.Net.locale.en-US.yaml
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.79/LovettSoftware.MyMoney.Net.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39610 new Money version 1.1.0.81
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.81/LovettSoftware.MyMoney.Net.installer.yaml
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.81/LovettSoftware.MyMoney.Net.locale.en-US.yaml
  manifests/l/LovettSoftware/MyMoney/Net/1.1.0.81/LovettSoftware.MyMoney.Net.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39597 New version: RandomEngy.VidCoder.Beta version 7.3
  manifests/r/RandomEngy/VidCoder/Beta/7.3/RandomEngy.VidCoder.Beta.installer.yaml
  manifests/r/RandomEngy/VidCoder/Beta/7.3/RandomEngy.VidCoder.Beta.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/Beta/7.3/RandomEngy.VidCoder.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39592 Add version: Waterfox.Waterfox version 91.4.2
  manifests/w/Waterfox/Waterfox/91.4.2/Waterfox.Waterfox.installer.yaml
  manifests/w/Waterfox/Waterfox/91.4.2/Waterfox.Waterfox.locale.en-US.yaml
  manifests/w/Waterfox/Waterfox/91.4.2/Waterfox.Waterfox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39591 New version: VivaldiTechnologies.Vivaldi.Snapshot version 5.1.2526.3
  manifests/v/VivaldiTechnologies/Vivaldi/Snapshot/5.1.2526.3/VivaldiTechnologies.Vivaldi.Snapshot.installer.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/Snapshot/5.1.2526.3/VivaldiTechnologies.Vivaldi.Snapshot.locale.en-US.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/Snapshot/5.1.2526.3/VivaldiTechnologies.Vivaldi.Snapshot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39590 New version: VivaldiTechnologies.Vivaldi version 5.0.2497.32
  manifests/v/VivaldiTechnologies/Vivaldi/5.0.2497.32/VivaldiTechnologies.Vivaldi.installer.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/5.0.2497.32/VivaldiTechnologies.Vivaldi.locale.en-US.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/5.0.2497.32/VivaldiTechnologies.Vivaldi.locale.nb-NO.yaml
  manifests/v/VivaldiTechnologies/Vivaldi/5.0.2497.32/VivaldiTechnologies.Vivaldi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39587 New version: Opera.OperaGX version 82.0.4227.50
  manifests/o/Opera/OperaGX/82.0.4227.50/Opera.OperaGX.installer.yaml
  manifests/o/Opera/OperaGX/82.0.4227.50/Opera.OperaGX.locale.en-US.yaml
  manifests/o/Opera/OperaGX/82.0.4227.50/Opera.OperaGX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39594 New version: Mozilla.Firefox.Beta version 96.0
  manifests/m/Mozilla/Firefox/Beta/96.0/Mozilla.Firefox.Beta.installer.yaml
  manifests/m/Mozilla/Firefox/Beta/96.0/Mozilla.Firefox.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/Beta/96.0/Mozilla.Firefox.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39589 New version: Opera.Opera.Beta version 83.0.4254.9
  manifests/o/Opera/Opera/Beta/83.0.4254.9/Opera.Opera.Beta.installer.yaml
  manifests/o/Opera/Opera/Beta/83.0.4254.9/Opera.Opera.Beta.locale.en-US.yaml
  manifests/o/Opera/Opera/Beta/83.0.4254.9/Opera.Opera.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39560 New package: EaseUS.PartitionMaster version 14.5
  manifests/e/EaseUS/PartitionMaster/14.5/EaseUS.PartitionMaster.installer.yaml
  manifests/e/EaseUS/PartitionMaster/14.5/EaseUS.PartitionMaster.locale.en-US.yaml
  manifests/e/EaseUS/PartitionMaster/14.5/EaseUS.PartitionMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39593 Update: Mozilla.Firefox.Beta version 95.0
  manifests/m/Mozilla/Firefox/Beta/95.0/Mozilla.Firefox.Beta.installer.yaml
  manifests/m/Mozilla/Firefox/Beta/95.0/Mozilla.Firefox.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/Beta/95.0/Mozilla.Firefox.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39588 New version: Opera.Opera version 82.0.4227.43
  manifests/o/Opera/Opera/82.0.4227.43/Opera.Opera.installer.yaml
  manifests/o/Opera/Opera/82.0.4227.43/Opera.Opera.locale.en-US.yaml
  manifests/o/Opera/Opera/82.0.4227.43/Opera.Opera.locale.nb-NO.yaml
  manifests/o/Opera/Opera/82.0.4227.43/Opera.Opera.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39569 New version: Guilded.Guilded version 1.0.9119474-release
  manifests/g/Guilded/Guilded/1.0.9119474-release/Guilded.Guilded.installer.yaml
  manifests/g/Guilded/Guilded/1.0.9119474-release/Guilded.Guilded.locale.en-US.yaml
  manifests/g/Guilded/Guilded/1.0.9119474-release/Guilded.Guilded.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39561 New version: EaseUS.PartitionMaster version 15.0
  manifests/e/EaseUS/PartitionMaster/15.0/EaseUS.PartitionMaster.installer.yaml
  manifests/e/EaseUS/PartitionMaster/15.0/EaseUS.PartitionMaster.locale.en-US.yaml
  manifests/e/EaseUS/PartitionMaster/15.0/EaseUS.PartitionMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39615 New version: Google.Chrome.Canary version 99.0.4801.0
  manifests/g/Google/Chrome/Canary/99.0.4801.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4801.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4801.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4801.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39640 New version: Google.Chrome.Canary version 99.0.4802.0
  manifests/g/Google/Chrome/Canary/99.0.4802.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4802.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4802.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4802.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39626 New version: jeffvli.Sonixd version 0.11.0
  manifests/j/jeffvli/Sonixd/0.11.0/jeffvli.Sonixd.installer.yaml
  manifests/j/jeffvli/Sonixd/0.11.0/jeffvli.Sonixd.locale.en-US.yaml
  manifests/j/jeffvli/Sonixd/0.11.0/jeffvli.Sonixd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39643 brackets-cont.brackets version 2.0.1
  manifests/b/brackets-cont/brackets/2.0.1/brackets-cont.brackets.installer.yaml
  manifests/b/brackets-cont/brackets/2.0.1/brackets-cont.brackets.locale.en-US.yaml
  manifests/b/brackets-cont/brackets/2.0.1/brackets-cont.brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39644 purocean.YankNote version 3.3.4
  manifests/p/purocean/YankNote/3.3.4/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.3.4/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.3.4/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39632 New version: Jackett.Jackett version 0.20.233.0
  manifests/j/Jackett/Jackett/0.20.233.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.233.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.233.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39642 cuiliang.quicker version 1.24.7
  manifests/c/cuiliang/quicker/1.24.7/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.24.7/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.24.7/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39646 Add version: hluk.CopyQ version 6.0.1
  manifests/h/hluk/CopyQ/6.0.1/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/6.0.1/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/6.0.1/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39613 Add version: hluk.CopyQ version 6.0.0
  manifests/h/hluk/CopyQ/6.0.0/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/6.0.0/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/6.0.0/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39648 New version: AmineMouafik.Ferdi version 5.6.7
  manifests/a/AmineMouafik/Ferdi/5.6.7/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.7/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.7/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39627 New version: valinet.ExplorerPatcher.Prerelease version 22000.376.40.21
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.376.40.21/valinet.ExplorerPatcher.Prerelease.installer.yaml
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.376.40.21/valinet.ExplorerPatcher.Prerelease.locale.en-US.yaml
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.376.40.21/valinet.ExplorerPatcher.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39625 New version: FlyByWireSimulations.FlyByWireSimulationsInstaller version 2.2.2
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/2.2.2/FlyByWireSimulations.FlyByWireSimulationsInstaller.installer.yaml
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/2.2.2/FlyByWireSimulations.FlyByWireSimulationsInstaller.locale.en-US.yaml
  manifests/f/FlyByWireSimulations/FlyByWireSimulationsInstaller/2.2.2/FlyByWireSimulations.FlyByWireSimulationsInstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39639 New version: DrakeetXu.PureWriter version 1.5.0
  manifests/d/DrakeetXu/PureWriter/1.5.0/DrakeetXu.PureWriter.installer.yaml
  manifests/d/DrakeetXu/PureWriter/1.5.0/DrakeetXu.PureWriter.locale.en-US.yaml
  manifests/d/DrakeetXu/PureWriter/1.5.0/DrakeetXu.PureWriter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39612 Flow-Launcher.Flow-Launcher version 1.9.1
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.1/Flow-Launcher.Flow-Launcher.installer.yaml
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.1/Flow-Launcher.Flow-Launcher.locale.en-US.yaml
  manifests/f/Flow-Launcher/Flow-Launcher/1.9.1/Flow-Launcher.Flow-Launcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39624 New version: wez.wezterm version 20220101-133340-7edc5b5a
  manifests/w/wez/wezterm/20220101-133340-7edc5b5a/wez.wezterm.installer.yaml
  manifests/w/wez/wezterm/20220101-133340-7edc5b5a/wez.wezterm.locale.en-US.yaml
  manifests/w/wez/wezterm/20220101-133340-7edc5b5a/wez.wezterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39616 New package: PolarGoose.CoffeeBean 4.0
  manifests/p/PolarGoose/CoffeeBean/4.0/PolarGoose.CoffeeBean.installer.yaml
  manifests/p/PolarGoose/CoffeeBean/4.0/PolarGoose.CoffeeBean.locale.en-US.yaml
  manifests/p/PolarGoose/CoffeeBean/4.0/PolarGoose.CoffeeBean.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39641 Nelson 0.5.12.1567
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.12.1567/NelsonNumericalSoftware.Nelson.installer.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.12.1567/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.5.12.1567/NelsonNumericalSoftware.Nelson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39654 New version: ByteDance.Feishu version 5.3.3
  manifests/b/ByteDance/Feishu/5.3.3/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/5.3.3/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.3.3/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/5.3.3/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39657 New version: Douyu.DouyuLive version 8.5.3.1
  manifests/d/Douyu/DouyuLive/8.5.3.1/Douyu.DouyuLive.installer.yaml
  manifests/d/Douyu/DouyuLive/8.5.3.1/Douyu.DouyuLive.locale.en-US.yaml
  manifests/d/Douyu/DouyuLive/8.5.3.1/Douyu.DouyuLive.locale.zh-CN.yaml
  manifests/d/Douyu/DouyuLive/8.5.3.1/Douyu.DouyuLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39656 Add version: ByteDance.Feishu version 5.1.5
  manifests/b/ByteDance/Feishu/5.1.5/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/5.1.5/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.1.5/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/5.1.5/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39659 New version: hello-efficiency-inc.raven-reader version 1.0.69
  manifests/h/hello-efficiency-inc/raven-reader/1.0.69/hello-efficiency-inc.raven-reader.installer.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.69/hello-efficiency-inc.raven-reader.locale.en-US.yaml
  manifests/h/hello-efficiency-inc/raven-reader/1.0.69/hello-efficiency-inc.raven-reader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39660 New version: Axure.AxureRP.10 version 10.0.0.3854
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.installer.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.locale.zh-CN.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39664 New version: maximmax42.CustomRP version 1.13
  manifests/m/maximmax42/CustomRP/1.13/maximmax42.CustomRP.installer.yaml
  manifests/m/maximmax42/CustomRP/1.13/maximmax42.CustomRP.locale.en-US.yaml
  manifests/m/maximmax42/CustomRP/1.13/maximmax42.CustomRP.locale.ru-RU.yaml
  manifests/m/maximmax42/CustomRP/1.13/maximmax42.CustomRP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39658 Add version: Douyu.DouyuLive version 8.5.2.2
  manifests/d/Douyu/DouyuLive/8.5.2.2/Douyu.DouyuLive.installer.yaml
  manifests/d/Douyu/DouyuLive/8.5.2.2/Douyu.DouyuLive.locale.en-US.yaml
  manifests/d/Douyu/DouyuLive/8.5.2.2/Douyu.DouyuLive.locale.zh-CN.yaml
  manifests/d/Douyu/DouyuLive/8.5.2.2/Douyu.DouyuLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39652 New version: GorillaDevs.GDLauncher version 1.1.21
  manifests/g/GorillaDevs/GDLauncher/1.1.21/GorillaDevs.GDLauncher.installer.yaml
  manifests/g/GorillaDevs/GDLauncher/1.1.21/GorillaDevs.GDLauncher.locale.en-US.yaml
  manifests/g/GorillaDevs/GDLauncher/1.1.21/GorillaDevs.GDLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39655 Add version: ByteDance.Feishu version 5.1.8
  manifests/b/ByteDance/Feishu/5.1.8/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/5.1.8/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.1.8/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/5.1.8/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39662 New version: Tencent.START version 0.11.0.7535
  manifests/t/Tencent/START/0.11.0.7535/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.7535/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.7535/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.7535/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39691 Add version: Tencent.START version 0.11.0.3848
  manifests/t/Tencent/START/0.11.0.3848/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.3848/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.3848/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.3848/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39688 Add version: Tencent.START version 0.11.0.4609
  manifests/t/Tencent/START/0.11.0.4609/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.4609/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.4609/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.4609/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39690 Add version: Tencent.START version 0.11.0.3890
  manifests/t/Tencent/START/0.11.0.3890/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.3890/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.3890/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.3890/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39666 New version: goatcorp.XIVLauncher version 6.1.11
  manifests/g/goatcorp/XIVLauncher/6.1.11/goatcorp.XIVLauncher.installer.yaml
  manifests/g/goatcorp/XIVLauncher/6.1.11/goatcorp.XIVLauncher.locale.en-US.yaml
  manifests/g/goatcorp/XIVLauncher/6.1.11/goatcorp.XIVLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39689 Add version: Tencent.START version 0.11.0.4240
  manifests/t/Tencent/START/0.11.0.4240/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.4240/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.4240/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.4240/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39675 New version: bornova.numara version 3.9.3
  manifests/b/bornova/numara/3.9.3/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.9.3/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.9.3/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39678 New version: chrisant996.Clink version 1.3.1.d30655
  manifests/c/chrisant996/Clink/1.3.1.d30655/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.3.1.d30655/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.3.1.d30655/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39681 New version: LeGitHubDeTai.AnimeBack version 8.0.9
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.9/LeGitHubDeTai.AnimeBack.installer.yaml
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.9/LeGitHubDeTai.AnimeBack.locale.en-US.yaml
  manifests/l/LeGitHubDeTai/AnimeBack/8.0.9/LeGitHubDeTai.AnimeBack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39680 New version: RuneLite.RuneLite version 2.3.0
  manifests/r/RuneLite/RuneLite/2.3.0/RuneLite.RuneLite.installer.yaml
  manifests/r/RuneLite/RuneLite/2.3.0/RuneLite.RuneLite.locale.en-US.yaml
  manifests/r/RuneLite/RuneLite/2.3.0/RuneLite.RuneLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39693 New version: Jackett.Jackett version 0.20.236.0
  manifests/j/Jackett/Jackett/0.20.236.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.236.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.236.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39679 New version: defi.defi version 2.8.3
  manifests/d/defi/defi/2.8.3/defi.defi.installer.yaml
  manifests/d/defi/defi/2.8.3/defi.defi.locale.en-US.yaml
  manifests/d/defi/defi/2.8.3/defi.defi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39669 FileVoyager.FileVoyager version 21.6.27.0
  manifests/f/FileVoyager/FileVoyager/21.6.27.0/FileVoyager.FileVoyager.installer.yaml
  manifests/f/FileVoyager/FileVoyager/21.6.27.0/FileVoyager.FileVoyager.locale.en-US.yaml
  manifests/f/FileVoyager/FileVoyager/21.6.27.0/FileVoyager.FileVoyager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39668 pit-ray.win-vind version 4.3.2
  manifests/p/pit-ray/win-vind/4.3.2/pit-ray.win-vind.installer.yaml
  manifests/p/pit-ray/win-vind/4.3.2/pit-ray.win-vind.locale.en-US.yaml
  manifests/p/pit-ray/win-vind/4.3.2/pit-ray.win-vind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39667 New version: Google.Chrome.Canary version 99.0.4803.0
  manifests/g/Google/Chrome/Canary/99.0.4804.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4804.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4804.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4804.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39695 New version: KoushikNaskar.InteractiveDataEditor version 2.9.3
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.9.3.0/KoushikNaskar.InteractiveDataEditor.installer.yaml
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.9.3.0/KoushikNaskar.InteractiveDataEditor.locale.en-US.yaml
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.9.3.0/KoushikNaskar.InteractiveDataEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39683 Modify: Tencent.Foxmail version 7.2.23.114
  manifests/t/Tencent/Foxmail/7.2.23.114/Tencent.Foxmail.installer.yaml
  manifests/t/Tencent/Foxmail/7.2.23.114/Tencent.Foxmail.locale.en-US.yaml
  manifests/t/Tencent/Foxmail/7.2.23.114/Tencent.Foxmail.locale.zh-CN.yaml
  manifests/t/Tencent/Foxmail/7.2.23.114/Tencent.Foxmail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39684 Add version: Tencent.START version 0.11.0.7058
  manifests/t/Tencent/START/0.11.0.7058/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.7058/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.7058/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.7058/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39687 Add version: Tencent.START version 0.11.0.6659
  manifests/t/Tencent/START/0.11.0.6659/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.6659/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.6659/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.6659/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39685 Modify: Tencent.START version 0.11.0.6459
  manifests/t/Tencent/START/0.11.0.6459/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.6459/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.6459/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.6459/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39686 Add version: Tencent.START version 0.11.0.6580
  manifests/t/Tencent/START/0.11.0.6580/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.6580/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.6580/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.6580/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39692 New version: BraveSoftware.BraveBrowser.Nightly version 97.1.36.10
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.10/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.10/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.10/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39714 purocean.YankNote version 3.3.3
  manifests/p/purocean/YankNote/3.3.3/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.3.3/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.3.3/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39713 cuiliang.quicker version 1.24.6
  manifests/c/cuiliang/quicker/1.24.6/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.24.6/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.24.6/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39703 New version: SnailDOS.SnailFM version 2.1.4
  manifests/s/SnailDOS/SnailFM/2.1.4/SnailDOS.SnailFM.installer.yaml
  manifests/s/SnailDOS/SnailFM/2.1.4/SnailDOS.SnailFM.locale.en-US.yaml
  manifests/s/SnailDOS/SnailFM/2.1.4/SnailDOS.SnailFM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39712 wherewhere.APKInstaller.Classic version 0.0.0
  manifests/w/wherewhere/APKInstaller/Classic/0.0.0/wherewhere.APKInstaller.Classic.installer.yaml
  manifests/w/wherewhere/APKInstaller/Classic/0.0.0/wherewhere.APKInstaller.Classic.locale.en-US.yaml
  manifests/w/wherewhere/APKInstaller/Classic/0.0.0/wherewhere.APKInstaller.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39711 New version: Riiid.pollapo version 0.0.30
  manifests/r/Riiid/pollapo/0.0.30/Riiid.pollapo.installer.yaml
  manifests/r/Riiid/pollapo/0.0.30/Riiid.pollapo.locale.en-US.yaml
  manifests/r/Riiid/pollapo/0.0.30/Riiid.pollapo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39718 Update: KDE.Kate version 21.12.0
  manifests/k/KDE/Kate/21.12.0/KDE.Kate.installer.yaml
  manifests/k/KDE/Kate/21.12.0/KDE.Kate.locale.en-US.yaml
  manifests/k/KDE/Kate/21.12.0/KDE.Kate.locale.it-IT.yaml
  manifests/k/KDE/Kate/21.12.0/KDE.Kate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39710 New version: qier222.yesplaymusic version 0.4.3
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39720 New version: AmineMouafik.Ferdi version 5.6.8
  manifests/a/AmineMouafik/Ferdi/5.6.8/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.8/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.8/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39719 Update: Oracle.MySQL version 8.0.27
  manifests/o/Oracle/MySQL/8.0.27/Oracle.MySQL.installer.yaml
  manifests/o/Oracle/MySQL/8.0.27/Oracle.MySQL.locale.en-US.yaml
  manifests/o/Oracle/MySQL/8.0.27/Oracle.MySQL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39716 Remove: Sandboxie.Plus version 1.0.6
  manifests/s/Sandboxie/Plus/1.0.6/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.0.6/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.0.6/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39722 cuiliang.quicker version 1.24.5
  manifests/c/cuiliang/quicker/1.24.5/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.24.5/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.24.5/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39721 purocean.YankNote version 3.3.2
  manifests/p/purocean/YankNote/3.3.2/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.3.2/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.3.2/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39723 Microsoft.VisualStudioCode.Insiders_v1.64.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.64.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39725 cuiliang.quicker version 1.24.4
  manifests/c/cuiliang/quicker/1.24.4/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.24.4/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.24.4/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39726 purocean.YankNote version 3.2.1
  manifests/p/purocean/YankNote/3.2.1/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.2.1/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.2.1/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39729 New version: ekvedaras.redis-gui version 1.2.8
  manifests/e/ekvedaras/redis-gui/1.2.8/ekvedaras.redis-gui.installer.yaml
  manifests/e/ekvedaras/redis-gui/1.2.8/ekvedaras.redis-gui.locale.en-US.yaml
  manifests/e/ekvedaras/redis-gui/1.2.8/ekvedaras.redis-gui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39730 New version: JohannesMillan.superProductivity version 7.9.2
  manifests/j/JohannesMillan/superProductivity/7.9.2/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/7.9.2/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/7.9.2/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#38022 New version: FlightGear.FlightGear version 2020.3.11
  manifests/f/FlightGear/FlightGear/2020.3.11/FlightGear.FlightGear.installer.yaml
  manifests/f/FlightGear/FlightGear/2020.3.11/FlightGear.FlightGear.locale.en-US.yaml
  manifests/f/FlightGear/FlightGear/2020.3.11/FlightGear.FlightGear.yaml
Labels: Validation-Completed, Validation-Unattended-Failed, Moderator-Approved

#39738 New version: JanProchazka.dbgate version 4.5.0
  manifests/j/JanProchazka/dbgate/4.5.0/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/4.5.0/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/4.5.0/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39737 New version: Google.Chrome.Canary version 99.0.4805.0
  manifests/g/Google/Chrome/Canary/99.0.4805.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4805.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4805.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4805.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39735 New version: ElijahLopez.MusicCaster version 4.90.156
  manifests/e/ElijahLopez/MusicCaster/4.90.156/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.156/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/4.90.156/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39734 New version: Balena.BalenaCLI version 13.1.3
  manifests/b/Balena/BalenaCLI/13.1.3/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/13.1.3/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/13.1.3/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39732 New version: Balena.BalenaCLI version 13.1.2
  manifests/b/Balena/BalenaCLI/13.1.2/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/13.1.2/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/13.1.2/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39731 New version: Billfish.Billfish version 2.4.0.4
  manifests/b/Billfish/Billfish/2.4.0.4/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.4.0.4/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.4.0.4/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.4.0.4/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39733 New version: BraveSoftware.BraveBrowser.Nightly version 97.1.36.11
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.11/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.11/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.11/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39724 PhonerLite update 2.98
  manifests/p/Phoner/PhonerLite/2.98/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39727 New version: Yuanli.uTools version 2.5.2
  manifests/y/Yuanli/uTools/2.5.2/Yuanli.uTools.installer.yaml
  manifests/y/Yuanli/uTools/2.5.2/Yuanli.uTools.locale.en-US.yaml
  manifests/y/Yuanli/uTools/2.5.2/Yuanli.uTools.locale.zh-CN.yaml
  manifests/y/Yuanli/uTools/2.5.2/Yuanli.uTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#38476 New version: TorProject.TorBrowser version 11.0.3
  manifests/t/TorProject/TorBrowser/11.0.3/TorProject.TorBrowser.installer.yaml
  manifests/t/TorProject/TorBrowser/11.0.3/TorProject.TorBrowser.locale.en-US.yaml
  manifests/t/TorProject/TorBrowser/11.0.3/TorProject.TorBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39133 Add version: Yuanli.uTools version 2.3.1
  manifests/y/Yuanli/uTools/2.3.1/Yuanli.uTools.installer.yaml
  manifests/y/Yuanli/uTools/2.3.1/Yuanli.uTools.locale.en-US.yaml
  manifests/y/Yuanli/uTools/2.3.1/Yuanli.uTools.locale.zh-CN.yaml
  manifests/y/Yuanli/uTools/2.3.1/Yuanli.uTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39756 New version: BraveSoftware.BraveBrowser.Nightly version 97.1.36.12
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.12/BraveSoftware.BraveBrowser.Nightly.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.12/BraveSoftware.BraveBrowser.Nightly.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Nightly/97.1.36.12/BraveSoftware.BraveBrowser.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39717 Add version: Tencent.WeChat version 3.1.0.72
  manifests/t/Tencent/WeChat/3.1.0.72/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.1.0.72/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.1.0.72/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.1.0.72/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39715 Add version: Tencent.WeChat version 3.2.1.112
  manifests/t/Tencent/WeChat/3.2.1.112/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.112/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.112/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.112/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39709 Add version: Tencent.WeChat version 3.2.1.121
  manifests/t/Tencent/WeChat/3.2.1.121/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.121/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.121/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.121/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39707 Add version: Tencent.WeChat version 3.2.1.141
  manifests/t/Tencent/WeChat/3.2.1.141/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.141/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.141/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.141/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39706 Add version: Tencent.WeChat version 3.2.1.151
  manifests/t/Tencent/WeChat/3.2.1.151/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.151/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.151/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.151/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39708 Add version: Tencent.WeChat version 3.2.1.127
  manifests/t/Tencent/WeChat/3.2.1.127/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.127/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.127/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.127/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39705 Add version: Tencent.WeChat version 3.2.1.154
  manifests/t/Tencent/WeChat/3.2.1.154/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.2.1.154/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.2.1.154/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.2.1.154/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39653 New version: Tencent.QQMusic version 18.46
  manifests/t/Tencent/QQMusic/18.46/Tencent.QQMusic.installer.yaml
  manifests/t/Tencent/QQMusic/18.46/Tencent.QQMusic.locale.en-US.yaml
  manifests/t/Tencent/QQMusic/18.46/Tencent.QQMusic.locale.zh-CN.yaml
  manifests/t/Tencent/QQMusic/18.46/Tencent.QQMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39701 Add version: Tencent.WeChat version 3.3.0.93
  manifests/t/Tencent/WeChat/3.3.0.93/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.3.0.93/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.3.0.93/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.3.0.93/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39700 Add version: Tencent.WeChat version 3.3.0.115
  manifests/t/Tencent/WeChat/3.3.0.115/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.3.0.115/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.3.0.115/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.3.0.115/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39699 Add version: Tencent.WeChat version 3.3.5.34
  manifests/t/Tencent/WeChat/3.3.5.34/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.3.5.34/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.3.5.34/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.3.5.34/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39698 Add version: Tencent.WeChat version 3.3.5.42
  manifests/t/Tencent/WeChat/3.3.5.42/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.3.5.42/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.3.5.42/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.3.5.42/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39651 New version: Tencent.QQMusic version 18.44
  manifests/t/Tencent/QQMusic/18.44/Tencent.QQMusic.installer.yaml
  manifests/t/Tencent/QQMusic/18.44/Tencent.QQMusic.locale.en-US.yaml
  manifests/t/Tencent/QQMusic/18.44/Tencent.QQMusic.locale.zh-CN.yaml
  manifests/t/Tencent/QQMusic/18.44/Tencent.QQMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39649 New version: Tencent.QQ version 9.5.4.28063
  manifests/t/Tencent/QQ/9.5.4.28063/Tencent.QQ.installer.yaml
  manifests/t/Tencent/QQ/9.5.4.28063/Tencent.QQ.locale.en-US.yaml
  manifests/t/Tencent/QQ/9.5.4.28063/Tencent.QQ.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/9.5.4.28063/Tencent.QQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39696 Modify: Tencent.WeChat version 3.4.0.38
  manifests/t/Tencent/WeChat/3.4.0.38/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.4.0.38/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.4.0.38/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.4.0.38/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39697 Modify: Tencent.WeChat version 3.3.5.50
  manifests/t/Tencent/WeChat/3.3.5.50/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.3.5.50/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.3.5.50/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.3.5.50/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39694 Modify: Tencent.WeChat version 3.4.5.27
  manifests/t/Tencent/WeChat/3.4.5.27/Tencent.WeChat.installer.yaml
  manifests/t/Tencent/WeChat/3.4.5.27/Tencent.WeChat.locale.en-US.yaml
  manifests/t/Tencent/WeChat/3.4.5.27/Tencent.WeChat.locale.zh-CN.yaml
  manifests/t/Tencent/WeChat/3.4.5.27/Tencent.WeChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39650 Add version: Tencent.QQ version 9.5.3.28008
  manifests/t/Tencent/QQ/9.5.3.28008/Tencent.QQ.installer.yaml
  manifests/t/Tencent/QQ/9.5.3.28008/Tencent.QQ.locale.en-US.yaml
  manifests/t/Tencent/QQ/9.5.3.28008/Tencent.QQ.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/9.5.3.28008/Tencent.QQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39485 Martevax.TitulkyCom version 1.003
  manifests/m/Martevax/TitulkyCom/1.003/Martevax.TitulkyCom.installer.yaml
  manifests/m/Martevax/TitulkyCom/1.003/Martevax.TitulkyCom.locale.cs-CZ.yaml
  manifests/m/Martevax/TitulkyCom/1.003/Martevax.TitulkyCom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39143 iQIYI.iQIYI version 8.12.148.5582
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.installer.yaml
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.locale.en-US.yaml
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.locale.zh-CN.yaml
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.locale.zh-HK.yaml
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.locale.zh-TW.yaml
  manifests/i/iQIYI/iQIYI/8.12.148.5582/iQIYI.iQIYI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39134 Add version: Yuanli.uTools version 2.3.0
  manifests/y/Yuanli/uTools/2.3.0/Yuanli.uTools.installer.yaml
  manifests/y/Yuanli/uTools/2.3.0/Yuanli.uTools.locale.en-US.yaml
  manifests/y/Yuanli/uTools/2.3.0/Yuanli.uTools.locale.zh-CN.yaml
  manifests/y/Yuanli/uTools/2.3.0/Yuanli.uTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Domain, Moderator-Approved, Needs-Attention

#39576 New version: AviSynth.AviSynthPlus version 3.7.1
  manifests/a/AviSynth/AviSynthPlus/3.7.1.3593/AviSynth.AviSynthPlus.installer.yaml
  manifests/a/AviSynth/AviSynthPlus/3.7.1.3593/AviSynth.AviSynthPlus.locale.en-US.yaml
  manifests/a/AviSynth/AviSynthPlus/3.7.1.3593/AviSynth.AviSynthPlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-No-Executables, Moderator-Approved, Needs-Attention

#39775 Modify: Billfish.Billfish version 2.1.1.12
  manifests/b/Billfish/Billfish/2.1.1.12/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.1.1.12/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.1.1.12/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.1.1.12/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39812 Add version: Billfish.Billfish version 1.0.835.301
  manifests/b/Billfish/Billfish/1.0.835.301/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/1.0.835.301/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/1.0.835.301/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/1.0.835.301/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39808 Add version: Billfish.Billfish version 1.4.2.0
  manifests/b/Billfish/Billfish/1.4.2.0/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/1.4.2.0/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/1.4.2.0/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/1.4.2.0/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39788 Add version: Billfish.Billfish version 2.0.6.8
  manifests/b/Billfish/Billfish/2.0.6.8/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.0.6.8/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.0.6.8/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.0.6.8/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39781 Add version: Billfish.Billfish version 2.0.9.11
  manifests/b/Billfish/Billfish/2.0.9.11/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.0.9.11/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.0.9.11/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.0.9.11/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39772 Add version: Billfish.Billfish version 2.2.0.10
  manifests/b/Billfish/Billfish/2.2.0.10/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.2.0.10/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.2.0.10/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.2.0.10/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39794 New version: h3poteto.whalebird-desktop version 4.5.0-beta.2
  manifests/h/h3poteto/whalebird-desktop/4.5.0-beta.2/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/4.5.0-beta.2/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/4.5.0-beta.2/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39769 New version: goatcorp.XIVLauncher version 6.1.12
  manifests/g/goatcorp/XIVLauncher/6.1.12/goatcorp.XIVLauncher.installer.yaml
  manifests/g/goatcorp/XIVLauncher/6.1.12/goatcorp.XIVLauncher.locale.en-US.yaml
  manifests/g/goatcorp/XIVLauncher/6.1.12/goatcorp.XIVLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39762 New version: dangeredwolf.ModernDeck version 9.3.0
  manifests/d/dangeredwolf/ModernDeck/9.3.0/dangeredwolf.ModernDeck.installer.yaml
  manifests/d/dangeredwolf/ModernDeck/9.3.0/dangeredwolf.ModernDeck.locale.en-US.yaml
  manifests/d/dangeredwolf/ModernDeck/9.3.0/dangeredwolf.ModernDeck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39761 cuiliang.quicker version 1.24.1
  manifests/c/cuiliang/quicker/1.24.1/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.24.1/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.24.1/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39825 New version: skyjake.Lagrange version 1.9.4
  manifests/s/skyjake/Lagrange/1.9.4/skyjake.Lagrange.installer.yaml
  manifests/s/skyjake/Lagrange/1.9.4/skyjake.Lagrange.locale.en-US.yaml
  manifests/s/skyjake/Lagrange/1.9.4/skyjake.Lagrange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39824 New version: Google.Chrome.Canary version 99.0.4806.0
  manifests/g/Google/Chrome/Canary/99.0.4806.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/99.0.4806.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/99.0.4806.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/99.0.4806.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39822 New version: BraveSoftware.BraveBrowser.Beta version 97.1.35.72
  manifests/b/BraveSoftware/BraveBrowser/Beta/97.1.35.72/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/97.1.35.72/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/97.1.35.72/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39829 CodecGuide.K-LiteCodecPack.Standard version 16.7.0
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/16.7.0/CodecGuide.K-LiteCodecPack.Standard.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/16.7.0/CodecGuide.K-LiteCodecPack.Standard.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/16.7.0/CodecGuide.K-LiteCodecPack.Standard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39828 CodecGuide.K-LiteCodecPack.Full version 16.7.0
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.7.0/CodecGuide.K-LiteCodecPack.Full.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.7.0/CodecGuide.K-LiteCodecPack.Full.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/16.7.0/CodecGuide.K-LiteCodecPack.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39827 CodecGuide.K-LiteCodecPack.Basic version 16.7.0
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.7.0/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.7.0/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/16.7.0/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39830 CodecGuide.K-LiteCodecPack.Mega version 16.7.0
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.7.0/CodecGuide.K-LiteCodecPack.Mega.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.7.0/CodecGuide.K-LiteCodecPack.Mega.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/16.7.0/CodecGuide.K-LiteCodecPack.Mega.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39759 purocean.YankNote version 3.2.0
  manifests/p/purocean/YankNote/3.2.0/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.2.0/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.2.0/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39823 New version: defi.defi version 2.8.4
  manifests/d/defi/defi/2.8.4/defi.defi.installer.yaml
  manifests/d/defi/defi/2.8.4/defi.defi.locale.en-US.yaml
  manifests/d/defi/defi/2.8.4/defi.defi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39826 tastyworks.tastyworks version 1.19.5
  manifests/t/tastyworks/tastyworks/1.19.5/tastyworks.tastyworks.installer.yaml
  manifests/t/tastyworks/tastyworks/1.19.5/tastyworks.tastyworks.locale.en-US.yaml
  manifests/t/tastyworks/tastyworks/1.19.5/tastyworks.tastyworks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#39789 Modify: Billfish.Billfish version 2.0.6.4
  manifests/b/Billfish/Billfish/2.0.6.4/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.0.6.4/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.0.6.4/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.0.6.4/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
