Repository microsoft/winget-pkgs, pull requests merged in 2022-09, with the labels that each got.

#72874 Normalize Crazybump.Crazybump 1.2.2
  manifests/c/Crazybump/Crazybump/1.2.2/Crazybump.Crazybump.installer.yaml
  manifests/c/Crazybump/Crazybump/1.2.2/Crazybump.Crazybump.locale.en-US.yaml
  manifests/c/Crazybump/Crazybump/1.2.2/Crazybump.Crazybump.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#76529 New version: Plex.PlexMediaServer version 1.28.2.6151
  manifests/p/Plex/PlexMediaServer/1.28.2.6151/Plex.PlexMediaServer.installer.yaml
  manifests/p/Plex/PlexMediaServer/1.28.2.6151/Plex.PlexMediaServer.locale.en-US.yaml
  manifests/p/Plex/PlexMediaServer/1.28.2.6151/Plex.PlexMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76552 New version: XmacsLabs.Mogan version 1.1.0
  manifests/x/XmacsLabs/Mogan/1.1.0/XmacsLabs.Mogan.installer.yaml
  manifests/x/XmacsLabs/Mogan/1.1.0/XmacsLabs.Mogan.locale.en-US.yaml
  manifests/x/XmacsLabs/Mogan/1.1.0/XmacsLabs.Mogan.locale.zh-CN.yaml
  manifests/x/XmacsLabs/Mogan/1.1.0/XmacsLabs.Mogan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76553 Ferdium.Ferdium.Nightly version 6.1.1-nightly.5
  manifests/f/Ferdium/Ferdium/Nightly/6.1.1-nightly.5/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.1.1-nightly.5/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.1.1-nightly.5/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76511 New version: foxglove.studio version 1.24.0
  manifests/f/foxglove/studio/1.24.0/foxglove.studio.installer.yaml
  manifests/f/foxglove/studio/1.24.0/foxglove.studio.locale.en-US.yaml
  manifests/f/foxglove/studio/1.24.0/foxglove.studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76512 New version: Git.Git version 2.37.3
  manifests/g/Git/Git/2.37.3/Git.Git.installer.yaml
  manifests/g/Git/Git/2.37.3/Git.Git.locale.en-US.yaml
  manifests/g/Git/Git/2.37.3/Git.Git.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76513 New version: HearthSim.HearthstoneDeckTracker version 1.18.17 [FP-O]
  manifests/h/HearthSim/HearthstoneDeckTracker/1.18.17/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.18.17/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.18.17/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76514 New version: Hibbiki.Chromium version 105.0.5195.54
  manifests/h/Hibbiki/Chromium/105.0.5195.54/Hibbiki.Chromium.installer.yaml
  manifests/h/Hibbiki/Chromium/105.0.5195.54/Hibbiki.Chromium.locale.en-US.yaml
  manifests/h/Hibbiki/Chromium/105.0.5195.54/Hibbiki.Chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76558 New version: Jackett.Jackett version 0.20.1821
  manifests/j/Jackett/Jackett/0.20.1821/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1821/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1821/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76515 New version: IPFS.IPFS-Desktop version 0.23.0
  manifests/i/IPFS/IPFS-Desktop/0.23.0/IPFS.IPFS-Desktop.installer.yaml
  manifests/i/IPFS/IPFS-Desktop/0.23.0/IPFS.IPFS-Desktop.locale.en-US.yaml
  manifests/i/IPFS/IPFS-Desktop/0.23.0/IPFS.IPFS-Desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76517 New version: jamaljsr.Polar version 1.4.0 [FP-D]
  manifests/j/jamaljsr/Polar/1.4.0/jamaljsr.Polar.installer.yaml
  manifests/j/jamaljsr/Polar/1.4.0/jamaljsr.Polar.locale.en-US.yaml
  manifests/j/jamaljsr/Polar/1.4.0/jamaljsr.Polar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76520 New version: JFrog.Conan version 1.52.0
  manifests/j/JFrog/Conan/1.52.0/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/1.52.0/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/1.52.0/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76522 Update: KDE.Dolphin version 22.08.0
  manifests/k/KDE/Dolphin/22.08.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76523 Update: KDE.Kate version 22.08.0
  manifests/k/KDE/Kate/22.08.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76525 New version: listen1.listen1 version 2.25.0
  manifests/l/listen1/listen1/2.25.0/listen1.listen1.installer.yaml
  manifests/l/listen1/listen1/2.25.0/listen1.listen1.locale.en-US.yaml
  manifests/l/listen1/listen1/2.25.0/listen1.listen1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76526 New version: Logseq.Logseq version 0.8.3
  manifests/l/Logseq/Logseq/0.8.3/Logseq.Logseq.installer.yaml
  manifests/l/Logseq/Logseq/0.8.3/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.8.3/Logseq.Logseq.locale.zh-CN.yaml
  manifests/l/Logseq/Logseq/0.8.3/Logseq.Logseq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76527 New version: MonkeysAudio.MonkeysAudio version 8.62
  manifests/m/MonkeysAudio/MonkeysAudio/8.62/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/8.62/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/8.62/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76528 New version: OctopusDeploy.Server version 2022.2.8011
  manifests/o/OctopusDeploy/Server/2022.2.8011/OctopusDeploy.Server.installer.yaml
  manifests/o/OctopusDeploy/Server/2022.2.8011/OctopusDeploy.Server.locale.en-US.yaml
  manifests/o/OctopusDeploy/Server/2022.2.8011/OctopusDeploy.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76531 New version: SnailDOS.SnailFM version 2.1.7
  manifests/s/SnailDOS/SnailFM/2.1.7/SnailDOS.SnailFM.installer.yaml
  manifests/s/SnailDOS/SnailFM/2.1.7/SnailDOS.SnailFM.locale.en-US.yaml
  manifests/s/SnailDOS/SnailFM/2.1.7/SnailDOS.SnailFM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76530 New version: SKAARHOJApS.SKAARHOJUpdater version 1.0.14
  manifests/s/SKAARHOJApS/SKAARHOJUpdater/1.0.14/SKAARHOJApS.SKAARHOJUpdater.installer.yaml
  manifests/s/SKAARHOJApS/SKAARHOJUpdater/1.0.14/SKAARHOJApS.SKAARHOJUpdater.locale.en-US.yaml
  manifests/s/SKAARHOJApS/SKAARHOJUpdater/1.0.14/SKAARHOJApS.SKAARHOJUpdater.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76532 New version: Spyder.Spyder version 5.3.3
  manifests/s/Spyder/Spyder/5.3.3/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.3.3/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.3.3/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76533 New version: stevencohn.OneMore version 4.19
  manifests/s/stevencohn/OneMore/4.19/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/4.19/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/4.19/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76534 New version: suse.RancherDesktop version 1.5.1
  manifests/s/suse/RancherDesktop/1.5.1/suse.RancherDesktop.installer.yaml
  manifests/s/suse/RancherDesktop/1.5.1/suse.RancherDesktop.locale.en-US.yaml
  manifests/s/suse/RancherDesktop/1.5.1/suse.RancherDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76535 New version: tagspaces.tagspaces version 4.5.2
  manifests/t/tagspaces/tagspaces/4.5.2/tagspaces.tagspaces.installer.yaml
  manifests/t/tagspaces/tagspaces/4.5.2/tagspaces.tagspaces.locale.en-US.yaml
  manifests/t/tagspaces/tagspaces/4.5.2/tagspaces.tagspaces.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76536 New version: TechSmith.Camtasia version 22.1.1.39848
  manifests/t/TechSmith/Camtasia/22.1.1.39848/TechSmith.Camtasia.installer.yaml
  manifests/t/TechSmith/Camtasia/22.1.1.39848/TechSmith.Camtasia.locale.en-US.yaml
  manifests/t/TechSmith/Camtasia/22.1.1.39848/TechSmith.Camtasia.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76537 New version: TechSmith.Snagit version 22.1.1.21427
  manifests/t/TechSmith/Snagit/22.1.1.21427/TechSmith.Snagit.installer.yaml
  manifests/t/TechSmith/Snagit/22.1.1.21427/TechSmith.Snagit.locale.en-US.yaml
  manifests/t/TechSmith/Snagit/22.1.1.21427/TechSmith.Snagit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76539 New version: Tenpi.Waifu2xGUI version 0.3.5
  manifests/t/Tenpi/Waifu2xGUI/0.3.5/Tenpi.Waifu2xGUI.installer.yaml
  manifests/t/Tenpi/Waifu2xGUI/0.3.5/Tenpi.Waifu2xGUI.locale.en-US.yaml
  manifests/t/Tenpi/Waifu2xGUI/0.3.5/Tenpi.Waifu2xGUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76542 New version: VladimirYakovlev.ElectronMail version 5.1.0
  manifests/v/VladimirYakovlev/ElectronMail/5.1.0/VladimirYakovlev.ElectronMail.installer.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.1.0/VladimirYakovlev.ElectronMail.locale.en-US.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.1.0/VladimirYakovlev.ElectronMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76543 New version: Waterfox.Waterfox version G4.1.5
  manifests/w/Waterfox/Waterfox/G4.1.5/Waterfox.Waterfox.installer.yaml
  manifests/w/Waterfox/Waterfox/G4.1.5/Waterfox.Waterfox.locale.en-US.yaml
  manifests/w/Waterfox/Waterfox/G4.1.5/Waterfox.Waterfox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76548 New version: xgi.houdoku version 2.9.3
  manifests/x/xgi/houdoku/2.9.3/xgi.houdoku.installer.yaml
  manifests/x/xgi/houdoku/2.9.3/xgi.houdoku.locale.en-US.yaml
  manifests/x/xgi/houdoku/2.9.3/xgi.houdoku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76549 New version: Xmake-io.Xmake version 2.7.1+202208260955
  manifests/x/Xmake-io/Xmake/2.7.1+202208260955/Xmake-io.Xmake.installer.yaml
  manifests/x/Xmake-io/Xmake/2.7.1+202208260955/Xmake-io.Xmake.locale.en-US.yaml
  manifests/x/Xmake-io/Xmake/2.7.1+202208260955/Xmake-io.Xmake.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76555 New version: CiderCollective.Cider version 1.5.6
  manifests/c/CiderCollective/Cider/1.5.6/CiderCollective.Cider.installer.yaml
  manifests/c/CiderCollective/Cider/1.5.6/CiderCollective.Cider.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/1.5.6/CiderCollective.Cider.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76471 New version: SomePythonThings.ElevenClock version 3.7.2
  manifests/s/SomePythonThings/ElevenClock/3.7.2/SomePythonThings.ElevenClock.installer.yaml
  manifests/s/SomePythonThings/ElevenClock/3.7.2/SomePythonThings.ElevenClock.locale.en-US.yaml
  manifests/s/SomePythonThings/ElevenClock/3.7.2/SomePythonThings.ElevenClock.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#75741 New version: Google.Chrome.Canary version 107.0.5272.0 [FP-D]
  manifests/g/Google/Chrome/Canary/107.0.5272.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/107.0.5272.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/107.0.5272.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/107.0.5272.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76538 New version: Telerik.Fiddler.Everywhere.Insiders version 3.4.1-insiders
  manifests/t/Telerik/Fiddler/Everywhere/Insiders/3.4.1-insiders/Telerik.Fiddler.Everywhere.Insiders.installer.yaml
  manifests/t/Telerik/Fiddler/Everywhere/Insiders/3.4.1-insiders/Telerik.Fiddler.Everywhere.Insiders.locale.en-US.yaml
  manifests/t/Telerik/Fiddler/Everywhere/Insiders/3.4.1-insiders/Telerik.Fiddler.Everywhere.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76556 New version: CiderCollective.Cider.Nightly version 1.5.7-beta.19
  manifests/c/CiderCollective/Cider/Nightly/1.5.7-beta.19/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.5.7-beta.19/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.5.7-beta.19/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#74759 New version: Element.Element version 1.11.4 [FP-D]
  manifests/e/Element/Element/1.11.4/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.4/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.4/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76547 New version: xanderfrangos.twinkletray version 1.14.7
  manifests/x/xanderfrangos/twinkletray/1.14.7/xanderfrangos.twinkletray.installer.yaml
  manifests/x/xanderfrangos/twinkletray/1.14.7/xanderfrangos.twinkletray.locale.en-US.yaml
  manifests/x/xanderfrangos/twinkletray/1.14.7/xanderfrangos.twinkletray.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76524 Update: KDE.KDEConnect version 22.08.0
  manifests/k/KDE/KDEConnect/22.08.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76521 Update: KDE.kile version 2.9.93 [FP-D]
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76519 New version: leezer3.OpenBVE version 1.8.4.1 [FP-D]
  manifests/l/leezer3/OpenBVE/1.8.4.1/leezer3.OpenBVE.installer.yaml
  manifests/l/leezer3/OpenBVE/1.8.4.1/leezer3.OpenBVE.locale.en-US.yaml
  manifests/l/leezer3/OpenBVE/1.8.4.1/leezer3.OpenBVE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76541 New version: UniversalMediaServer.UniversalMediaServer version 11.4.0
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.4.0/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.4.0/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.4.0/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76544 New version: WeakAuras.WeakAurasCompanion version 4.0.6
  manifests/w/WeakAuras/WeakAurasCompanion/4.0.6/WeakAuras.WeakAurasCompanion.installer.yaml
  manifests/w/WeakAuras/WeakAurasCompanion/4.0.6/WeakAuras.WeakAurasCompanion.locale.en-US.yaml
  manifests/w/WeakAuras/WeakAurasCompanion/4.0.6/WeakAuras.WeakAurasCompanion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76545 New version: WeMod.WeMod.Beta version 8.3.4-beta00
  manifests/w/WeMod/WeMod/Beta/8.3.4-beta00/WeMod.WeMod.Beta.installer.yaml
  manifests/w/WeMod/WeMod/Beta/8.3.4-beta00/WeMod.WeMod.Beta.locale.en-US.yaml
  manifests/w/WeMod/WeMod/Beta/8.3.4-beta00/WeMod.WeMod.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76546 New version: WeMod.WeMod version 8.3.3
  manifests/w/WeMod/WeMod/8.3.3/WeMod.WeMod.installer.yaml
  manifests/w/WeMod/WeMod/8.3.3/WeMod.WeMod.locale.en-US.yaml
  manifests/w/WeMod/WeMod/8.3.3/WeMod.WeMod.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76562 Wise Memory Optimizer version4.1.7
  manifests/w/WiseCleaner/WiseMemoryOptimizer/4.1.7/WiseCleaner.WiseMemoryOptimizer.installer.yaml
  manifests/w/WiseCleaner/WiseMemoryOptimizer/4.1.7/WiseCleaner.WiseMemoryOptimizer.locale.en-US.yaml
  manifests/w/WiseCleaner/WiseMemoryOptimizer/4.1.7/WiseCleaner.WiseMemoryOptimizer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76565 JanDeDobbeleer.OhMyPosh version 8.36.7
  manifests/j/JanDeDobbeleer/OhMyPosh/8.36.7/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.36.7/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.36.7/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76568 New version: BelgianGovernment.eIDViewer version 5.1.5998
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.installer.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.locale.en-US.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76575 Update: OpenJS.NodeJS.Nightly version 19.0.0
  manifests/o/OpenJS/NodeJS/Nightly/19.0.0/OpenJS.NodeJS.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76578 Update: VideoLAN.VLC.Nightly version 3.0.18
  manifests/v/VideoLAN/VLC/Nightly/3.0.18/VideoLAN.VLC.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76582 Added Microsoft Edge Dev version 106.0.1363.0.
  manifests/m/Microsoft/Edge/Dev/106.0.1363.0/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/106.0.1363.0/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/106.0.1363.0/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76576 Update: VideoLAN.VLC.Nightly version 4.0.0
  manifests/v/VideoLAN/VLC/Nightly/4.0.0/VideoLAN.VLC.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76584 Added AWS Command Line Interface version 2.7.28.
  manifests/a/Amazon/AWSCLI/2.7.28/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.7.28/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.7.28/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76581 Added Microsoft Edge Beta version 105.0.1343.23.
  manifests/m/Microsoft/Edge/Beta/105.0.1343.23/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/105.0.1343.23/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/105.0.1343.23/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76583 ALVR.ALVR version 18.2.3 `Documentations` field
  manifests/a/ALVR/ALVR/18.2.3/ALVR.ALVR.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76564 OBSProject.OBSStudio version 28.0.0
  manifests/o/OBSProject/OBSStudio/28.0.0/OBSProject.OBSStudio.installer.yaml
  manifests/o/OBSProject/OBSStudio/28.0.0/OBSProject.OBSStudio.locale.en-US.yaml
  manifests/o/OBSProject/OBSStudio/28.0.0/OBSProject.OBSStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76563 Add SteelSeries GG 23.0.0
  manifests/s/SteelSeries/GG/23.0.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/23.0.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/23.0.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76570 infinitepower18.WSASideloader version 1.3.6
  manifests/i/infinitepower18/WSASideloader/1.3.6/infinitepower18.WSASideloader.installer.yaml
  manifests/i/infinitepower18/WSASideloader/1.3.6/infinitepower18.WSASideloader.locale.en.yaml
  manifests/i/infinitepower18/WSASideloader/1.3.6/infinitepower18.WSASideloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76588 New version: yt-dlp.yt-dlp version 2022.09.01
  manifests/y/yt-dlp/yt-dlp/2022.09.01/yt-dlp.yt-dlp.installer.yaml
  manifests/y/yt-dlp/yt-dlp/2022.09.01/yt-dlp.yt-dlp.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/2022.09.01/yt-dlp.yt-dlp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#71053 New version: Governikus.AusweisApp2 version 1.24.0
  manifests/g/Governikus/AusweisApp2/1.24.0/Governikus.AusweisApp2.installer.yaml
  manifests/g/Governikus/AusweisApp2/1.24.0/Governikus.AusweisApp2.locale.de-DE.yaml
  manifests/g/Governikus/AusweisApp2/1.24.0/Governikus.AusweisApp2.locale.en-US.yaml
  manifests/g/Governikus/AusweisApp2/1.24.0/Governikus.AusweisApp2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76587 Wargaming.WorldOfWarshipsModStation version 2.1.0.2 `Documentations` / `Agreements`
  manifests/w/Wargaming/WorldOfWarshipsModStation/2.1.0.2/Wargaming.WorldOfWarshipsModStation.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76585 EpicGames.EpicGamesLauncher version 1.3.23.0 `Documentations` / `Agreements`
  manifests/e/EpicGames/EpicGamesLauncher/1.3.23.0/EpicGames.EpicGamesLauncher.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76595 Fix Agreements for Package
  manifests/v/Valve/Steam/2.10.91.91/Valve.Steam.installer.yaml
  manifests/v/Valve/Steam/2.10.91.91/Valve.Steam.locale.en-US.yaml
  manifests/v/Valve/Steam/2.10.91.91/Valve.Steam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76593 Fix Agreements for Package
  manifests/a/AIMP/AIMP/5.02.2370/AIMP.AIMP.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76591 Fix Agreements for Package
  manifests/a/AIMP/AIMP/5.00.2344/AIMP.AIMP.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76605 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseADCleaner/1.2.7/WiseCleaner.WiseADCleaner.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76590 Fix Agreements for Package
  manifests/a/AIMP/AIMP/4.70.2254/AIMP.AIMP.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76613 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseRegistryCleaner/10.8.2/WiseCleaner.WiseRegistryCleaner.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76606 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseCare365/6.3.3/WiseCleaner.WiseCare365.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76608 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseDiskCleaner/10.9.1/WiseCleaner.WiseDiskCleaner.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76612 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseProgramUninstaller/3.0.4/WiseCleaner.WiseProgramUninstaller.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76610 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseFolderHider/4.4.2/WiseCleaner.WiseFolderHider.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76603 Fix Agreements for Package
  manifests/w/Wacom/WacomTabletDriver/6.3.45-1/Wacom.WacomTabletDriver.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76609 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseDuplicateFinder/2.0.2/WiseCleaner.WiseDuplicateFinder.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76602 Fix Agreements for Package
  manifests/w/Wacom/WacomTabletDriver/6.3.44-3/Wacom.WacomTabletDriver.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76607 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseDataRecovery/6.1.2/WiseCleaner.WiseDataRecovery.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76611 Fix Agreements for Package
  manifests/w/WiseCleaner/WiseHotKey/1.2.8/WiseCleaner.WiseHotKey.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76604 Fix Agreements for Package
  manifests/w/Wacom/WacomTabletDriver/6.3.46-1/Wacom.WacomTabletDriver.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76597 Fix Agreements for Package
  manifests/f/FXHOME/HitFilmExpress/18.0.12407.12817/FXHOME.HitFilmExpress.installer.yaml
  manifests/f/FXHOME/HitFilmExpress/18.0.12407.12817/FXHOME.HitFilmExpress.locale.en-US.yaml
  manifests/f/FXHOME/HitFilmExpress/18.0.12407.12817/FXHOME.HitFilmExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76594 New Version: AIMP.AIMP 5.03.2398
  manifests/a/AIMP/AIMP/5.03.2398/AIMP.AIMP.installer.yaml
  manifests/a/AIMP/AIMP/5.03.2398/AIMP.AIMP.locale.en-US.yaml
  manifests/a/AIMP/AIMP/5.03.2398/AIMP.AIMP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76615 Fix Documentations for Package
  manifests/r/RStudio/quarto/1.1.165/RStudio.quarto.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76599 Fix Agreements for Package
  manifests/n/Novaquark/DualUniverse/Beta 1/Novaquark.DualUniverse.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76692 Make Multi-line Field Exclude ending Newline
  manifests/a/AcFun/AcFunVirtualTool/1.27.0.1292/AcFun.AcFunVirtualTool.installer.yaml
  manifests/a/AcFun/AcFunVirtualTool/1.27.0.1292/AcFun.AcFunVirtualTool.locale.en-US.yaml
  manifests/a/AcFun/AcFunVirtualTool/1.27.0.1292/AcFun.AcFunVirtualTool.locale.zh-CN.yaml
  manifests/a/AcFun/AcFunVirtualTool/1.27.0.1292/AcFun.AcFunVirtualTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#76623 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/13.0.2250.0/360.360Chrome.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76621 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/13.0.2220.0/360.360Chrome.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76619 Make Multi-line Field Exclude ending Newline
  manifests/1/115/115/1.0.3.6/115.115.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76620 Make Multi-line Field Exclude ending Newline
  manifests/1/115/115/1.0.4.6/115.115.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76646 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360CleanMaster/1.0.0.1020/360.360CleanMaster.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76633 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1032.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76631 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1020.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76628 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1010.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76635 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1040.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76641 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1070.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76638 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1050.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76640 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1060.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#74120 Remove Governikus.AusweisApp2 1.22.6
  manifests/g/Governikus/AusweisApp2/1.22.6/Governikus.AusweisApp2.installer.yaml
  manifests/g/Governikus/AusweisApp2/1.22.6/Governikus.AusweisApp2.locale.de-DE.yaml
  manifests/g/Governikus/AusweisApp2/1.22.6/Governikus.AusweisApp2.locale.en-US.yaml
  manifests/g/Governikus/AusweisApp2/1.22.6/Governikus.AusweisApp2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76657 Make Multi-line Field Exclude ending Newline
  manifests/6/64Gram/64Gram/1.0.16/64Gram.64Gram.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76644 Make Multi-line Field Exclude ending Newline
  manifests/3/360/360Chrome/X/21.0.1082.0/360.360Chrome.X.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76506 Update Line endings of Project Files
  .editorconfig
  CODE_OF_CONDUCT.md
  LICENSE
  Tools/SandboxTest.ps1
  Tools/cgmanifest.json
Labels: Moderator-Approved, Project-File

#76561 change URLs to current v1.2 schema
  AUTHORING_MANIFESTS.md
Labels: Moderator-Approved, Project-File

#76574 Mention `Documents`/`Agreements` instead of `Document`/`Agreement` field in docs
  doc/manifest/schema/1.1.0/defaultLocale.md
  doc/manifest/schema/1.1.0/locale.md
  doc/manifest/schema/1.1.0/singleton.md
  doc/manifest/schema/1.2.0/defaultLocale.md
  doc/manifest/schema/1.2.0/locale.md
  doc/manifest/schema/1.2.0/singleton.md
Labels: Moderator-Approved, Project-File

#76653 Fixed metadata for DataGrip version 2021.2.1.
  manifests/j/JetBrains/DataGrip/2021.2.1/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.2.1/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.2.1/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76684 Fixed metadata for RubyMine version 2022.1.
  manifests/j/JetBrains/RubyMine/2022.1/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.1/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76702 Make Multi-line Field Exclude ending Newline
  manifests/a/Alibaba/MiniProgramStudio/2.7.2/Alibaba.MiniProgramStudio.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76670 Fixed metadata for DataGrip version 2022.2.1.
  manifests/j/JetBrains/DataGrip/2022.2.1/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2022.2.1/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2022.2.1/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76655 Fixed metadata for DataGrip version 2021.2.3.
  manifests/j/JetBrains/DataGrip/2021.2.3/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.2.3/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.2.3/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76654 Fixed metadata for DataGrip version 2021.2.2.
  manifests/j/JetBrains/DataGrip/2021.2.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.2.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.2.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76651 Fixed metadata for DataGrip version 2021.1.3.
  manifests/j/JetBrains/DataGrip/2021.1.3/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.1.3/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.1.3/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76652 Fixed metadata for DataGrip version 2021.2.
  manifests/j/JetBrains/DataGrip/2021.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76659 Fixed metadata for DataGrip version 2021.3.1.
  manifests/j/JetBrains/DataGrip/2021.3.1/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.3.1/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.3.1/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76656 Fixed metadata for DataGrip version 2021.2.4.
  manifests/j/JetBrains/DataGrip/2021.2.4/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.2.4/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.2.4/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76676 Fixed metadata for RubyMine version 2021.2.1.
  manifests/j/JetBrains/RubyMine/2021.2.1/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.2.1/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76706 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/Dida/4.1.2.0/Appest.Dida.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76660 Fixed metadata for DataGrip version 2021.3.2.
  manifests/j/JetBrains/DataGrip/2021.3.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.3.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.3.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76662 Fixed metadata for DataGrip version 2021.3.4.
  manifests/j/JetBrains/DataGrip/2021.3.4/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2021.3.4/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2021.3.4/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76687 Fixed metadata for RubyMine version 2022.1.3.
  manifests/j/JetBrains/RubyMine/2022.1.3/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.1.3/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76689 Fixed metadata for RubyMine version 2022.2.1.
  manifests/j/JetBrains/RubyMine/2022.2.1/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.2.1/JetBrains.RubyMine.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/2022.2.1/JetBrains.RubyMine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76681 Fixed metadata for RubyMine version 2021.3.1.
  manifests/j/JetBrains/RubyMine/2021.3.1/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.3.1/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76685 Fixed metadata for RubyMine version 2022.1.1.
  manifests/j/JetBrains/RubyMine/2022.1.1/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.1.1/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76718 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.1.0/Appest.TickTick.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76648 Fixed metadata for DataGrip version 2020.3.2.
  manifests/j/JetBrains/DataGrip/2020.3.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2020.3.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2020.3.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76665 Fixed metadata for DataGrip version 2022.1.2.
  manifests/j/JetBrains/DataGrip/2022.1.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2022.1.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2022.1.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76701 Make Multi-line Field Exclude ending Newline
  manifests/a/Alibaba/LightProxy/1.1.41/Alibaba.LightProxy.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76675 Fixed metadata for RubyMine version 2021.2.
  manifests/j/JetBrains/RubyMine/2021.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76683 Fixed metadata for RubyMine version 2021.3.3.
  manifests/j/JetBrains/RubyMine/2021.3.3/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.3.3/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76688 Fixed metadata for RubyMine version 2022.2.
  manifests/j/JetBrains/RubyMine/2022.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76680 Fixed metadata for RubyMine version 2021.3.
  manifests/j/JetBrains/RubyMine/2021.3/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.3/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76674 Fixed metadata for RubyMine version 2021.1.3.
  manifests/j/JetBrains/RubyMine/2021.1.3/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.1.3/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76669 Fixed metadata for DataGrip version 2022.2.
  manifests/j/JetBrains/DataGrip/2022.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2022.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2022.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76677 Fixed metadata for RubyMine version 2021.2.2.
  manifests/j/JetBrains/RubyMine/2021.2.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.2.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76686 Fixed metadata for RubyMine version 2022.1.2.
  manifests/j/JetBrains/RubyMine/2022.1.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2022.1.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76673 Fixed metadata for RubyMine version 2021.1.2.
  manifests/j/JetBrains/RubyMine/2021.1.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.1.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76690 Make Multi-line Field Exclude ending Newline
  manifests/a/AcFun/AcFunVirtualTool/1.25.0.1173/AcFun.AcFunVirtualTool.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76671 Fixed metadata for DataGrip version 2022.2.2.
  manifests/j/JetBrains/DataGrip/2022.2.2/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2022.2.2/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2022.2.2/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76679 Make Multi-line Field Exclude ending Newline
  manifests/a/AcFun/AcFunVirtualTool/1.24.0.1125/AcFun.AcFunVirtualTool.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76731 Make Multi-line Field Exclude ending Newline
  manifests/a/Axure/AxureRP/10/10.0.0.3865/Axure.AxureRP.10.installer.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3865/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3865/Axure.AxureRP.10.locale.zh-CN.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3865/Axure.AxureRP.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, URL-Validation-Error, Moderator-Approved

#76730 Make Multi-line Field Exclude ending Newline
  manifests/a/Axure/AxureRP/10/10.0.0.3863/Axure.AxureRP.10.installer.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3863/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3863/Axure.AxureRP.10.locale.zh-CN.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3863/Axure.AxureRP.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, URL-Validation-Error, Moderator-Approved

#76728 Make Multi-line Field Exclude ending Newline
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.installer.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.locale.zh-CN.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3854/Axure.AxureRP.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, URL-Validation-Error, Moderator-Approved

#76735 Make Multi-line Field Exclude ending Newline
  manifests/b/B3log/SiYuan/1.8.0/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76724 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.3.6/Appest.TickTick.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76722 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.3.0/Appest.TickTick.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76720 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.2.0/Appest.TickTick.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76729 Make Multi-line Field Exclude ending Newline
  manifests/a/Axure/AxureRP/10/10.0.0.3857/Axure.AxureRP.10.installer.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3857/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3857/Axure.AxureRP.10.locale.zh-CN.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3857/Axure.AxureRP.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, URL-Validation-Error, Moderator-Approved

#76723 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.3.6/Appest.TickTick.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76721 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.3.0/Appest.TickTick.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76682 Fixed metadata for RubyMine version 2021.3.2.
  manifests/j/JetBrains/RubyMine/2021.3.2/JetBrains.RubyMine.installer.yaml
  manifests/j/JetBrains/RubyMine/2021.3.2/JetBrains.RubyMine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76739 Make Multi-line Field Exclude ending Newline
  manifests/b/B3log/SiYuan/1.8.5/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76740 Make Multi-line Field Exclude ending Newline
  manifests/b/B3log/SiYuan/1.8.6/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76717 Make Multi-line Field Exclude ending Newline
  manifests/a/Appest/TickTick/4.1.1.0/Appest.TickTick.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#76738 Make Multi-line Field Exclude ending Newline
  manifests/b/B3log/SiYuan/1.8.4/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
