Repository microsoft/winget-pkgs, pull requests merged in 2022-12, with the labels that each got.

#90141 New version: Google.Chrome.Canary version 110.0.5450.2
  manifests/g/Google/Chrome/Canary/110.0.5450.2/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/110.0.5450.2/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/110.0.5450.2/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/110.0.5450.2/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90129 Added Mozilla Firefox version 107.0.1.
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/107.0.1/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90157 Update: KDE.Dolphin version 22.08.3
  manifests/k/KDE/Dolphin/22.08.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90159 New version: sprout2000.Elephicon version 2.2.0
  manifests/s/sprout2000/Elephicon/2.2.0/sprout2000.Elephicon.installer.yaml
  manifests/s/sprout2000/Elephicon/2.2.0/sprout2000.Elephicon.locale.en-US.yaml
  manifests/s/sprout2000/Elephicon/2.2.0/sprout2000.Elephicon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90156 New version: sprout2000.LeafView version 2.3.0
  manifests/s/sprout2000/LeafView/2.3.0/sprout2000.LeafView.installer.yaml
  manifests/s/sprout2000/LeafView/2.3.0/sprout2000.LeafView.locale.en-US.yaml
  manifests/s/sprout2000/LeafView/2.3.0/sprout2000.LeafView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90161 New version: vim.vim version 9.0.0978
  manifests/v/vim/vim/9.0.0978/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0978/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0978/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90142 New version: JetBrains.Gateway version 2022.3
  manifests/j/JetBrains/Gateway/2022.3/JetBrains.Gateway.installer.yaml
  manifests/j/JetBrains/Gateway/2022.3/JetBrains.Gateway.locale.en-US.yaml
  manifests/j/JetBrains/Gateway/2022.3/JetBrains.Gateway.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90166 New version: Discord.Discord.Canary version 1.0.54
  manifests/d/Discord/Discord/Canary/1.0.54/Discord.Discord.Canary.installer.yaml
  manifests/d/Discord/Discord/Canary/1.0.54/Discord.Discord.Canary.locale.en-US.yaml
  manifests/d/Discord/Discord/Canary/1.0.54/Discord.Discord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90158 New version: OpenWhisperSystems.Signal.Beta version 6.0.0-beta.4
  manifests/o/OpenWhisperSystems/Signal/Beta/6.0.0-beta.4/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.0.0-beta.4/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.0.0-beta.4/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90122 Added Visual Studio Professional 2022 version 17.4.2.
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.4.2/Microsoft.VisualStudio.2022.Professional.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.4.2/Microsoft.VisualStudio.2022.Professional.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.4.2/Microsoft.VisualStudio.2022.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90121 Added Visual Studio Enterprise 2022 version 17.4.2.
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.4.2/Microsoft.VisualStudio.2022.Enterprise.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.4.2/Microsoft.VisualStudio.2022.Enterprise.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.4.2/Microsoft.VisualStudio.2022.Enterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90119 Added Visual Studio Build Tools 2022 version 17.4.2.
  manifests/m/Microsoft/VisualStudio/2022/BuildTools/17.4.2/Microsoft.VisualStudio.2022.BuildTools.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/BuildTools/17.4.2/Microsoft.VisualStudio.2022.BuildTools.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/BuildTools/17.4.2/Microsoft.VisualStudio.2022.BuildTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90125 Updated Visual Studio Load Test Controller 2022 to version 17.4.2.
  manifests/m/Microsoft/VisualStudio/2022/TestController/17.4.2/Microsoft.VisualStudio.2022.TestController.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/TestController/17.4.2/Microsoft.VisualStudio.2022.TestController.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/TestController/17.4.2/Microsoft.VisualStudio.2022.TestController.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90147 Update: o2sh.onefetch version 2.13.2
  manifests/o/o2sh/onefetch/2.13.2/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.13.2/o2sh.onefetch.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90146 Add version: o2sh.onefetch version 2.14.0
  manifests/o/o2sh/onefetch/2.14.0/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.14.0/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.14.0/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90144 Update: o2sh.onefetch version 2.14.2
  manifests/o/o2sh/onefetch/2.14.2/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.14.2/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.14.2/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90145 Update: o2sh.onefetch version 2.14.1
  manifests/o/o2sh/onefetch/2.14.1/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.14.1/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.14.1/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90150 Add version: o2sh.onefetch version 2.13.0
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90151 Update: o2sh.onefetch version 2.12.0
  manifests/o/o2sh/onefetch/2.12.0/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.12.0/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.12.0/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90171 Treesize Free update to 4.6.2
  manifests/j/JAMSoftware/TreeSize/Free/4.6.2/JAMSoftware.TreeSize.Free.installer.yaml
  manifests/j/JAMSoftware/TreeSize/Free/4.6.2/JAMSoftware.TreeSize.Free.locale.en-US.yaml
  manifests/j/JAMSoftware/TreeSize/Free/4.6.2/JAMSoftware.TreeSize.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90192 Microsoft.VisualStudioCode.Insiders_v1.74.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.74.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90188 Update: KDE.Okular version 22.08.3
  manifests/k/KDE/Okular/22.08.3/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90185 Update: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90097 New version: Cloudflare.cloudflared version 2022.11.1
  manifests/c/Cloudflare/cloudflared/2022.11.1/Cloudflare.cloudflared.installer.yaml
  manifests/c/Cloudflare/cloudflared/2022.11.1/Cloudflare.cloudflared.locale.en-US.yaml
  manifests/c/Cloudflare/cloudflared/2022.11.1/Cloudflare.cloudflared.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90189 New version: ProtonTechnologies.ProtonVPN version 2.2.1
  manifests/p/ProtonTechnologies/ProtonVPN/2.2.1/ProtonTechnologies.ProtonVPN.installer.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/2.2.1/ProtonTechnologies.ProtonVPN.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/2.2.1/ProtonTechnologies.ProtonVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90186 Update: KDE.Kate version 22.08.3
  manifests/k/KDE/Kate/22.08.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90170 Ferdium.Ferdium.Nightly version 6.2.2-nightly.1
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.1/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.1/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.1/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90198 New version: Lexikos.AutoHotkey version 1.1.36.00
  manifests/l/Lexikos/AutoHotkey/1.1.36.00/Lexikos.AutoHotkey.installer.yaml
  manifests/l/Lexikos/AutoHotkey/1.1.36.00/Lexikos.AutoHotkey.locale.en-US.yaml
  manifests/l/Lexikos/AutoHotkey/1.1.36.00/Lexikos.AutoHotkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90202 New version: Playnite.Playnite version 10.8
  manifests/p/Playnite/Playnite/10.8/Playnite.Playnite.installer.yaml
  manifests/p/Playnite/Playnite/10.8/Playnite.Playnite.locale.en-US.yaml
  manifests/p/Playnite/Playnite/10.8/Playnite.Playnite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90201 New version: OpenRPAApS.OpenRPA version 1.4.49.0
  manifests/o/OpenRPAApS/OpenRPA/1.4.49.0/OpenRPAApS.OpenRPA.installer.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.4.49.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.4.49.0/OpenRPAApS.OpenRPA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90153 New version: Amazon.AWSCLI version 2.9.3
  manifests/a/Amazon/AWSCLI/2.9.3/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.9.3/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.9.3/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90205 New version: Iterate.Cyberduck version 8.5.1.38745
  manifests/i/Iterate/Cyberduck/8.5.1.38745/Iterate.Cyberduck.installer.yaml
  manifests/i/Iterate/Cyberduck/8.5.1.38745/Iterate.Cyberduck.locale.en-US.yaml
  manifests/i/Iterate/Cyberduck/8.5.1.38745/Iterate.Cyberduck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90206 New version: JetBrains.GoLand version 2022.3
  manifests/j/JetBrains/GoLand/2022.3/JetBrains.GoLand.installer.yaml
  manifests/j/JetBrains/GoLand/2022.3/JetBrains.GoLand.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/2022.3/JetBrains.GoLand.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90167 Docker.DockerDesktop version 4.14.1
  manifests/d/Docker/DockerDesktop/4.14.1/Docker.DockerDesktop.installer.yaml
  manifests/d/Docker/DockerDesktop/4.14.1/Docker.DockerDesktop.locale.en-US.yaml
  manifests/d/Docker/DockerDesktop/4.14.1/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90134 New version: Hibbiki.Chromium version 108.0.5359.72
  manifests/h/Hibbiki/Chromium/108.0.5359.72/Hibbiki.Chromium.installer.yaml
  manifests/h/Hibbiki/Chromium/108.0.5359.72/Hibbiki.Chromium.locale.en-US.yaml
  manifests/h/Hibbiki/Chromium/108.0.5359.72/Hibbiki.Chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90183 New version: Tencent.QQMusic version 19.02
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.installer.yaml
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.locale.en-US.yaml
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.locale.zh-CN.yaml
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90180 New version: Bosyun.BoardMix version 1.3.2
  manifests/b/Bosyun/BoardMix/1.3.2/Bosyun.BoardMix.installer.yaml
  manifests/b/Bosyun/BoardMix/1.3.2/Bosyun.BoardMix.locale.en-US.yaml
  manifests/b/Bosyun/BoardMix/1.3.2/Bosyun.BoardMix.locale.zh-CN.yaml
  manifests/b/Bosyun/BoardMix/1.3.2/Bosyun.BoardMix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90105 New version: MonkeysAudio.MonkeysAudio version 8.99
  manifests/m/MonkeysAudio/MonkeysAudio/8.99/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/8.99/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/8.99/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90155 New version: chrisant996.Clink version 1.4.3.67deea
  manifests/c/chrisant996/Clink/1.4.3.67deea/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.4.3.67deea/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.4.3.67deea/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90207 Update: KDE.Kate version 22.08.3
  manifests/k/KDE/Kate/22.08.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90209 Added Firefox Developer Edition version 108.0b8.
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b8/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b8/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b8/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90054 New version: altair-graphql.altair version 5.0.6
  manifests/a/altair-graphql/altair/5.0.6/altair-graphql.altair.installer.yaml
  manifests/a/altair-graphql/altair/5.0.6/altair-graphql.altair.locale.en-US.yaml
  manifests/a/altair-graphql/altair/5.0.6/altair-graphql.altair.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90099 New version: G3G4X5X6.ultimate-cube version 6.6.12
  manifests/g/G3G4X5X6/ultimate-cube/6.6.12/G3G4X5X6.ultimate-cube.installer.yaml
  manifests/g/G3G4X5X6/ultimate-cube/6.6.12/G3G4X5X6.ultimate-cube.locale.en-US.yaml
  manifests/g/G3G4X5X6/ultimate-cube/6.6.12/G3G4X5X6.ultimate-cube.locale.zh-CN.yaml
  manifests/g/G3G4X5X6/ultimate-cube/6.6.12/G3G4X5X6.ultimate-cube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90098 New version: KOOK.KOOK version 0.60.0
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.installer.yaml
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.locale.en-US.yaml
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.locale.zh-CN.yaml
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90056 New version: Taozuhong.Kangaroo version 2.1.1.221201
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90152 HydrusNetwork.HydrusNetwork version v508
  manifests/h/HydrusNetwork/HydrusNetwork/v508/HydrusNetwork.HydrusNetwork.installer.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v508/HydrusNetwork.HydrusNetwork.locale.en-US.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v508/HydrusNetwork.HydrusNetwork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90213 CreativeTechnology.CreativeApp version 1.12.03.00
  manifests/c/CreativeTechnology/CreativeApp/1.12.03.00/CreativeTechnology.CreativeApp.installer.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.12.03.00/CreativeTechnology.CreativeApp.locale.en-US.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.12.03.00/CreativeTechnology.CreativeApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90057 New version: vassalengine.VASSAL version 3.6.8
  manifests/v/vassalengine/VASSAL/3.6.8/vassalengine.VASSAL.installer.yaml
  manifests/v/vassalengine/VASSAL/3.6.8/vassalengine.VASSAL.locale.en-US.yaml
  manifests/v/vassalengine/VASSAL/3.6.8/vassalengine.VASSAL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90212 CreativeTechnology.CreativeApp version 1.11.09.00
  manifests/c/CreativeTechnology/CreativeApp/1.11.09.00/CreativeTechnology.CreativeApp.installer.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.11.09.00/CreativeTechnology.CreativeApp.locale.en-US.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.11.09.00/CreativeTechnology.CreativeApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90226 New version: Iterate.MountainDuck version 4.13.0.20526
  manifests/i/Iterate/MountainDuck/4.13.0.20526/Iterate.MountainDuck.installer.yaml
  manifests/i/Iterate/MountainDuck/4.13.0.20526/Iterate.MountainDuck.locale.en-US.yaml
  manifests/i/Iterate/MountainDuck/4.13.0.20526/Iterate.MountainDuck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90236 New version: Youdao.YoudaoDict version 9.1.4.0
  manifests/y/Youdao/YoudaoDict/9.1.4.0/Youdao.YoudaoDict.installer.yaml
  manifests/y/Youdao/YoudaoDict/9.1.4.0/Youdao.YoudaoDict.locale.en-US.yaml
  manifests/y/Youdao/YoudaoDict/9.1.4.0/Youdao.YoudaoDict.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90232 New version: ElijahLopez.MusicCaster version 5.9.10
  manifests/e/ElijahLopez/MusicCaster/5.9.10/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.10/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.10/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90229 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90227 New version: JetBrains.DataGrip version 2022.3
  manifests/j/JetBrains/DataGrip/2022.3/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2022.3/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2022.3/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90238 New version: Sogou.SogouInput version 13.0.0.6738
  manifests/s/Sogou/SogouInput/13.0.0.6738/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/13.0.0.6738/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/13.0.0.6738/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/13.0.0.6738/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90242 New version: Apifox.Apifox version 2.2.10
  manifests/a/Apifox/Apifox/2.2.10/Apifox.Apifox.installer.yaml
  manifests/a/Apifox/Apifox/2.2.10/Apifox.Apifox.locale.en-US.yaml
  manifests/a/Apifox/Apifox/2.2.10/Apifox.Apifox.locale.zh-CN.yaml
  manifests/a/Apifox/Apifox/2.2.10/Apifox.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90244 New version: Apifox.Apifox version 2.2.13
  manifests/a/Apifox/Apifox/2.2.13/Apifox.Apifox.installer.yaml
  manifests/a/Apifox/Apifox/2.2.13/Apifox.Apifox.locale.en-US.yaml
  manifests/a/Apifox/Apifox/2.2.13/Apifox.Apifox.locale.zh-CN.yaml
  manifests/a/Apifox/Apifox/2.2.13/Apifox.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90243 New version: Apifox.Apifox version 2.2.11
  manifests/a/Apifox/Apifox/2.2.11/Apifox.Apifox.installer.yaml
  manifests/a/Apifox/Apifox/2.2.11/Apifox.Apifox.locale.en-US.yaml
  manifests/a/Apifox/Apifox/2.2.11/Apifox.Apifox.locale.zh-CN.yaml
  manifests/a/Apifox/Apifox/2.2.11/Apifox.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90233 New version: Wondershare.DemoCreator version 6.3.1
  manifests/w/Wondershare/DemoCreator/6.3.1/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/6.3.1/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/6.3.1/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/6.3.1/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90240 New version: IObit.AdvancedSystemCare version 16.1.0
  manifests/i/IObit/AdvancedSystemCare/16.0.1/IObit.AdvancedSystemCare.locale.en-US.yaml
  manifests/i/IObit/AdvancedSystemCare/16.1.0/IObit.AdvancedSystemCare.installer.yaml
  manifests/i/IObit/AdvancedSystemCare/16.1.0/IObit.AdvancedSystemCare.locale.en-US.yaml
  manifests/i/IObit/AdvancedSystemCare/16.1.0/IObit.AdvancedSystemCare.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90237 Update: EclipseAdoptium.Temurin.8.JDK version 8.0.302.8
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.302.8/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.302.8/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.302.8/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90230 Add version: EclipseAdoptium.Temurin.8.JDK version 8.0.342.7
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.342.7/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.342.7/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.342.7/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90228 Update: EclipseAdoptium.Temurin.8.JDK version 8.0.345.1
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.345.1/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.345.1/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.345.1/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90217 New package: miurahr.aqtinstall version 3.0.2
  manifests/m/miurahr/aqtinstall/3.0.2/miurahr.aqtinstall.installer.yaml
  manifests/m/miurahr/aqtinstall/3.0.2/miurahr.aqtinstall.locale.en-US.yaml
  manifests/m/miurahr/aqtinstall/3.0.2/miurahr.aqtinstall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90225 Update: EclipseAdoptium.Temurin.8.JRE version 8.0.302.8
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.302.8/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.302.8/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.302.8/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90221 Add version: EclipseAdoptium.Temurin.8.JRE version 8.0.342.7
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.342.7/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.342.7/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.342.7/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90218 New version: EclipseAdoptium.Temurin.8.JDK version 8.0.352.8
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.352.8/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.352.8/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.352.8/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90219 New version: EclipseAdoptium.Temurin.8.JRE version 8.0.352.8
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.352.8/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.352.8/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.352.8/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90214 New version: Google.AndroidStudio.Canary version 2022.2.1.9
  manifests/g/Google/AndroidStudio/Canary/2022.2.1.9/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2022.2.1.9/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2022.2.1.9/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90028 OpenBB-finance.OpenBBTerminal version 2.0.0
  manifests/o/OpenBB-finance/OpenBBTerminal/2.0.0/OpenBB-finance.OpenBBTerminal.installer.yaml
  manifests/o/OpenBB-finance/OpenBBTerminal/2.0.0/OpenBB-finance.OpenBBTerminal.locale.en-US.yaml
  manifests/o/OpenBB-finance/OpenBBTerminal/2.0.0/OpenBB-finance.OpenBBTerminal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90220 Update: EclipseAdoptium.Temurin.8.JRE version 8.0.345.1
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.345.1/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.345.1/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.345.1/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90033 DualitySoftware.DSClock version 5.0.1.5
  manifests/d/DualitySoftware/DSClock/5.0.1.5/DualitySoftware.DSClock.installer.yaml
  manifests/d/DualitySoftware/DSClock/5.0.1.5/DualitySoftware.DSClock.locale.en-US.yaml
  manifests/d/DualitySoftware/DSClock/5.0.1.5/DualitySoftware.DSClock.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Installation-Error

#90235 Update: EclipseAdoptium.Temurin.8.JDK version 8.0.312.7
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.312.7/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.312.7/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.312.7/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90223 Update: EclipseAdoptium.Temurin.8.JRE version 8.0.322.6
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.322.6/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.322.6/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.322.6/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90234 Update: EclipseAdoptium.Temurin.8.JDK version 8.0.322.6
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.322.6/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.322.6/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.322.6/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90215 New version: Google.AndroidStudio.Beta version 2022.1.1.16
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.16/Google.AndroidStudio.Beta.installer.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.16/Google.AndroidStudio.Beta.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.16/Google.AndroidStudio.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90224 Add version: EclipseAdoptium.Temurin.8.JRE version 8.0.312.7
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.312.7/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.312.7/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.312.7/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90245 New version: JetBrains.PHPStorm version 2022.2.4
  manifests/j/JetBrains/PHPStorm/2022.2.4/JetBrains.PHPStorm.installer.yaml
  manifests/j/JetBrains/PHPStorm/2022.2.4/JetBrains.PHPStorm.locale.en-US.yaml
  manifests/j/JetBrains/PHPStorm/2022.2.4/JetBrains.PHPStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90193 MuhammedKalkan.OpenLens version 6.2.4
  manifests/m/MuhammedKalkan/OpenLens/6.2.4/MuhammedKalkan.OpenLens.installer.yaml
  manifests/m/MuhammedKalkan/OpenLens/6.2.4/MuhammedKalkan.OpenLens.locale.en-US.yaml
  manifests/m/MuhammedKalkan/OpenLens/6.2.4/MuhammedKalkan.OpenLens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90080 IndigoByte.DrExplain version 6.5.1253
  manifests/i/IndigoByte/DrExplain/6.5.1253/IndigoByte.DrExplain.installer.yaml
  manifests/i/IndigoByte/DrExplain/6.5.1253/IndigoByte.DrExplain.locale.en-US.yaml
  manifests/i/IndigoByte/DrExplain/6.5.1253/IndigoByte.DrExplain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#89683 Modify: Spotify.Spotify version 1.1.99.878.g1e4ccc6e
  manifests/s/Spotify/Spotify/1.1.99.878.g1e4ccc6e/Spotify.Spotify.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Installation-Error

#90115 New Version: Astronomer.Astro version 1.8.3
  manifests/a/Astronomer/Astro/1.8.3/Astronomer.Astro.installer.yaml
  manifests/a/Astronomer/Astro/1.8.3/Astronomer.Astro.locale.en-US.yaml
  manifests/a/Astronomer/Astro/1.8.3/Astronomer.Astro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#88391 Latest vulkan-sdk version (1.3.231.1)
  manifests/k/KhronosGroup/VulkanSDK/1.3.231.1/KhronosGroup.VulkanSDK.installer.yaml
  manifests/k/KhronosGroup/VulkanSDK/1.3.231.1/KhronosGroup.VulkanSDK.locale.en-US.yaml
  manifests/k/KhronosGroup/VulkanSDK/1.3.231.1/KhronosGroup.VulkanSDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved, Waived-Validation-Unattended-Failed

#90257 New version: Google.Chrome.Canary version 110.0.5452.0
  manifests/g/Google/Chrome/Canary/110.0.5452.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/110.0.5452.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/110.0.5452.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/110.0.5452.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90250 New version: Google.Chrome.Beta version 109.0.5414.25
  manifests/g/Google/Chrome/Beta/109.0.5414.25/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/109.0.5414.25/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/109.0.5414.25/Google.Chrome.Beta.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Beta/109.0.5414.25/Google.Chrome.Beta.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Beta/109.0.5414.25/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90258 Update: KDE.KDEConnect version 22.08.3
  manifests/k/KDE/KDEConnect/22.08.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90252 New version: JetBrains.PyCharm.Professional version 2022.3
  manifests/j/JetBrains/PyCharm/Professional/2022.3/JetBrains.PyCharm.Professional.installer.yaml
  manifests/j/JetBrains/PyCharm/Professional/2022.3/JetBrains.PyCharm.Professional.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Professional/2022.3/JetBrains.PyCharm.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90259 New version: OpenWhisperSystems.Signal.Beta version 6.1.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/6.1.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.1.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.1.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90266 Update: KDE.Dolphin version 22.08.3
  manifests/k/KDE/Dolphin/22.08.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90270 New version: ElijahLopez.MusicCaster version 5.9.11
  manifests/e/ElijahLopez/MusicCaster/5.9.11/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.11/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.11/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90272 New version: vim.vim version 9.0.0984
  manifests/v/vim/vim/9.0.0984/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0984/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0984/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90269 New version: Unity.Unity.2021 version 2021.3.15f1
  manifests/u/Unity/Unity/2021/2021.3.15f1/Unity.Unity.2021.installer.yaml
  manifests/u/Unity/Unity/2021/2021.3.15f1/Unity.Unity.2021.locale.en-US.yaml
  manifests/u/Unity/Unity/2021/2021.3.15f1/Unity.Unity.2021.locale.zh-CN.yaml
  manifests/u/Unity/Unity/2021/2021.3.15f1/Unity.Unity.2021.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90264 Remove: o2sh.onefetch version 2.13.1
  manifests/o/o2sh/onefetch/2.13.1/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.13.1/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.13.1/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90283 ReleaseNotes: Tencent.QQMusic version 19.02
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.installer.yaml
  manifests/t/Tencent/QQMusic/19.02/Tencent.QQMusic.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90298 Remove: 7S2P.Effie version 2.2.5
  manifests/7/7S2P/Effie/2.2.5/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.2.5/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.2.5/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.2.5/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90297 Remove: 7S2P.Effie version 2.2.3
  manifests/7/7S2P/Effie/2.2.3/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.2.3/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.2.3/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.2.3/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90294 Remove: 7S2P.Effie version 2.1.15
  manifests/7/7S2P/Effie/2.1.15/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.1.15/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.1.15/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.1.15/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90299 Remove: 7S2P.Effie version 2.2.7
  manifests/7/7S2P/Effie/2.2.7/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.2.7/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.2.7/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.2.7/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90296 Remove: 7S2P.Effie version 2.1.19
  manifests/7/7S2P/Effie/2.1.19/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.1.19/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.1.19/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.1.19/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90301 Remove: 7S2P.Effie.CN version 2.1.21
  manifests/7/7S2P/Effie/CN/2.1.21/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.1.21/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.1.21/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.1.21/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90285 New version: PortSwigger.BurpSuite.Community version 2022.11.3
  manifests/p/PortSwigger/BurpSuite/Community/2022.11.3/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2022.11.3/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2022.11.3/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2022.11.3/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90263 Remove: o2sh.onefetch version 2.13.0
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.13.0/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90286 New version: PortSwigger.BurpSuite.Professional version 2022.11.3
  manifests/p/PortSwigger/BurpSuite/Professional/2022.11.3/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2022.11.3/PortSwigger.BurpSuite.Professional.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2022.11.3/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2022.11.3/PortSwigger.BurpSuite.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90292 Fix: DigiDNA.iMazing version 2.16.4.0
  manifests/d/DigiDNA/iMazing/2.16.4.0/DigiDNA.iMazing.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90291 New version: Catsxp.Catsxp version 108.2.12.1
  manifests/c/Catsxp/Catsxp/108.2.12.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/108.2.12.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/108.2.12.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/108.2.12.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90300 New version: 7S2P.Effie.CN version 2.2.11
  manifests/7/7S2P/Effie/CN/2.2.11/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.2.11/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.2.11/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.2.11/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90302 Remove: 7S2P.Effie.CN version 2.1.23
  manifests/7/7S2P/Effie/CN/2.1.23/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.1.23/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.1.23/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.1.23/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90281 fyr77.EnvyUpdate version 2.15
  manifests/f/fyr77/EnvyUpdate/2.15/fyr77.EnvyUpdate.installer.yaml
  manifests/f/fyr77/EnvyUpdate/2.15/fyr77.EnvyUpdate.locale.en-US.yaml
  manifests/f/fyr77/EnvyUpdate/2.15/fyr77.EnvyUpdate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90303 ReleaseNotes: Appest.TickTick version 4.3.4.0
  manifests/a/Appest/TickTick/4.3.4.0/Appest.TickTick.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90184 PTRTECH.UVtools version 3.9.0
  manifests/p/PTRTECH/UVtools/3.9.0/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.9.0/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.9.0/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90265 Remove: o2sh.onefetch version 2.13.2
  manifests/o/o2sh/onefetch/2.13.2/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.13.2/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.13.2/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90288 Fix: Wondershare.UBackit version 3.0.0.37
  manifests/w/Wondershare/UBackit/3.0.0.37/Wondershare.UBackit.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90290 New version: Kiraku.AudioJam version 1.12.0-199
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90138 TechSmith.Snagit.2023 version 23.0.1.23930
  manifests/t/TechSmith/Snagit/2023/23.0.1.23930/TechSmith.Snagit.2023.installer.yaml
  manifests/t/TechSmith/Snagit/2023/23.0.1.23930/TechSmith.Snagit.2023.locale.en-US.yaml
  manifests/t/TechSmith/Snagit/2023/23.0.1.23930/TechSmith.Snagit.2023.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90093 bitmediae-SolutionsGmbH.ITSClient version 3.0.2.0
  manifests/b/bitmediae-SolutionsGmbH/ITSClient/3.0.2.0/bitmediae-SolutionsGmbH.ITSClient.installer.yaml
  manifests/b/bitmediae-SolutionsGmbH/ITSClient/3.0.2.0/bitmediae-SolutionsGmbH.ITSClient.locale.de-DE.yaml
  manifests/b/bitmediae-SolutionsGmbH/ITSClient/3.0.2.0/bitmediae-SolutionsGmbH.ITSClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90315 New version: Jackett.Jackett version 0.20.2313
  manifests/j/Jackett/Jackett/0.20.2313/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2313/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2313/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90314 Update: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90320 Microsoft.VisualStudioCode.Insiders_v1.74.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.74.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90311 Update: KDE.Okular version 22.08.3
  manifests/k/KDE/Okular/22.08.3/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90305 ReleaseNotes: Tencent.TencentMeeting version 3.13.4.429
  manifests/t/Tencent/TencentMeeting/3.13.4.429/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.13.4.429/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.13.4.429/Tencent.TencentMeeting.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90310 Update: KDE.Kdenlive version 22.08.3
  manifests/k/KDE/Kdenlive/22.08.3/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90316 New version: Fndroid.ClashForWindows version 0.20.10
  manifests/f/Fndroid/ClashForWindows/0.20.10/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.10/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.10/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90306 ReleaseNotes: Tencent.TencentDocs version 2.4.2
  manifests/t/Tencent/TencentDocs/2.4.2/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.4.2/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.4.2/Tencent.TencentDocs.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90322 Update: KDE.Kate version 22.08.3
  manifests/k/KDE/Kate/22.08.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90275 Ferdium.Ferdium.Nightly version 6.2.2-nightly.2
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.2/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.2/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.2-nightly.2/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90330 New version: Google.Chrome.Canary version 110.0.5453.0
  manifests/g/Google/Chrome/Canary/110.0.5453.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/110.0.5453.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/110.0.5453.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/110.0.5453.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90247 New version: Tutanota.Tutanota version 3.105.4
  manifests/t/Tutanota/Tutanota/3.105.4/Tutanota.Tutanota.installer.yaml
  manifests/t/Tutanota/Tutanota/3.105.4/Tutanota.Tutanota.locale.en-US.yaml
  manifests/t/Tutanota/Tutanota/3.105.4/Tutanota.Tutanota.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90338 Added Firefox Developer Edition version 108.0b9.
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b9/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b9/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/108.0b9/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90328 New version: Logseq.Logseq version 0.8.12
  manifests/l/Logseq/Logseq/0.8.12/Logseq.Logseq.installer.yaml
  manifests/l/Logseq/Logseq/0.8.12/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.8.12/Logseq.Logseq.locale.zh-CN.yaml
  manifests/l/Logseq/Logseq/0.8.12/Logseq.Logseq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90345 Added Docker Desktop version 4.15.0.
  manifests/d/Docker/DockerDesktop/4.15.0/Docker.DockerDesktop.installer.yaml
  manifests/d/Docker/DockerDesktop/4.15.0/Docker.DockerDesktop.locale.en-US.yaml
  manifests/d/Docker/DockerDesktop/4.15.0/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90350 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90349 New version: GLab.GLab version 1.23.1
  manifests/g/GLab/GLab/1.23.1/GLab.GLab.installer.yaml
  manifests/g/GLab/GLab/1.23.1/GLab.GLab.locale.en-US.yaml
  manifests/g/GLab/GLab/1.23.1/GLab.GLab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90191 New version: WestWind.MarkdownMonster version 2.7.6.0
  manifests/w/WestWind/MarkdownMonster/2.7.6.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.7.6.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.7.6.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90216 Devolutions.RemoteDesktopManager version 2022.3.24.0
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.24.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.24.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.24.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90351 New version: MonkeysAudio.MonkeysAudio version 9.00
  manifests/m/MonkeysAudio/MonkeysAudio/9.00/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/9.00/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/9.00/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90369 New version: Google.Chrome version 108.0.5359.95
  manifests/g/Google/Chrome/108.0.5359.95/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/108.0.5359.95/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/108.0.5359.95/Google.Chrome.locale.nb-NO.yaml
  manifests/g/Google/Chrome/108.0.5359.95/Google.Chrome.locale.zh-CN.yaml
  manifests/g/Google/Chrome/108.0.5359.95/Google.Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90363 New version: JetBrains.YouTrack version 22.3.64281
  manifests/j/JetBrains/YouTrack/22.3.64281/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/22.3.64281/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/22.3.64281/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90368 New version: ElijahLopez.MusicCaster version 5.9.12
  manifests/e/ElijahLopez/MusicCaster/5.9.12/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.12/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.9.12/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90364 New version: Microsoft.AzureStorageExplorer version 1.27.0
  manifests/m/Microsoft/AzureStorageExplorer/1.27.0/Microsoft.AzureStorageExplorer.installer.yaml
  manifests/m/Microsoft/AzureStorageExplorer/1.27.0/Microsoft.AzureStorageExplorer.locale.en-US.yaml
  manifests/m/Microsoft/AzureStorageExplorer/1.27.0/Microsoft.AzureStorageExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90367 New version: Google.Chrome.Canary version 110.0.5454.0
  manifests/g/Google/Chrome/Canary/110.0.5454.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/110.0.5454.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/110.0.5454.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/110.0.5454.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90248 New version: NordPassTeam.NordPass version 4.33.11
  manifests/n/NordPassTeam/NordPass/4.33.11/NordPassTeam.NordPass.installer.yaml
  manifests/n/NordPassTeam/NordPass/4.33.11/NordPassTeam.NordPass.locale.en-US.yaml
  manifests/n/NordPassTeam/NordPass/4.33.11/NordPassTeam.NordPass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90377 Update: KDE.KDEConnect version 22.08.3
  manifests/k/KDE/KDEConnect/22.08.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90376 New version: Amazon.AWSCLI version 2.9.4
  manifests/a/Amazon/AWSCLI/2.9.4/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.9.4/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.9.4/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90375 DoltHub.Dolt version 0.51.9
  manifests/d/DoltHub/Dolt/0.51.9/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.51.9/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.51.9/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90372 New version: AntibodySoftware.WizTree version 4.12
  manifests/a/AntibodySoftware/WizTree/4.12/AntibodySoftware.WizTree.installer.yaml
  manifests/a/AntibodySoftware/WizTree/4.12/AntibodySoftware.WizTree.locale.en-US.yaml
  manifests/a/AntibodySoftware/WizTree/4.12/AntibodySoftware.WizTree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90308 New version: Alibaba.aDrive version 3.12.3
  manifests/a/Alibaba/aDrive/3.12.3/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/3.12.3/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/3.12.3/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/3.12.3/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90313 New version: Yuanli.uTools version 3.2.1
  manifests/y/Yuanli/uTools/3.2.1/Yuanli.uTools.installer.yaml
  manifests/y/Yuanli/uTools/3.2.1/Yuanli.uTools.locale.en-US.yaml
  manifests/y/Yuanli/uTools/3.2.1/Yuanli.uTools.locale.zh-CN.yaml
  manifests/y/Yuanli/uTools/3.2.1/Yuanli.uTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90307 ReleaseNotes: KOOK.KOOK version 0.60.0
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.locale.en-US.yaml
  manifests/k/KOOK/KOOK/0.60.0/KOOK.KOOK.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90268 New version: OBSProject.OBSStudio.Pre-release version 29.0.0-beta2
  manifests/o/OBSProject/OBSStudio/Pre-release/29.0.0-beta2/OBSProject.OBSStudio.Pre-release.installer.yaml
  manifests/o/OBSProject/OBSStudio/Pre-release/29.0.0-beta2/OBSProject.OBSStudio.Pre-release.locale.en-US.yaml
  manifests/o/OBSProject/OBSStudio/Pre-release/29.0.0-beta2/OBSProject.OBSStudio.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#90407 Update: KDE.Dolphin version 22.08.3
  manifests/k/KDE/Dolphin/22.08.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
