Repository microsoft/winget-pkgs, pull requests merged in 2022-07, with the labels that each got.

#64822 New version: Billfish.Billfish version 2.11.0.12
  manifests/b/Billfish/Billfish/2.11.0.12/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.11.0.12/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.11.0.12/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/2.11.0.12/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64875 Update: KDE.Dolphin version 22.04.2
  manifests/k/KDE/Dolphin/22.04.2/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64868 Modify: Shooter.SPlayerX version 4.9.4
  manifests/s/Shooter/SPlayerX/4.9.4/Shooter.SPlayerX.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64867 Modify: Shooter.SPlayer version 3.7.2437
  manifests/s/Shooter/SPlayer/3.7.2437/Shooter.SPlayer.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64887 JanDeDobbeleer.OhMyPosh version 8.8.1
  manifests/j/JanDeDobbeleer/OhMyPosh/8.8.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.8.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.8.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64859 ReleaseNotes: Baidu.BaiduNetdisk version 7.17.5
  manifests/b/Baidu/BaiduNetdisk/7.17.5/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.17.5/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.17.5/Baidu.BaiduNetdisk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64860 ReleaseNotes: Thunisoft.HuayuPY version 7.3.0.295
  manifests/t/Thunisoft/HuayuPY/7.3.0.295/Thunisoft.HuayuPY.installer.yaml
  manifests/t/Thunisoft/HuayuPY/7.3.0.295/Thunisoft.HuayuPY.locale.en-US.yaml
  manifests/t/Thunisoft/HuayuPY/7.3.0.295/Thunisoft.HuayuPY.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64862 Remove: Tencent.QMProxyAccelerator version 3.0.9604.134
  manifests/t/Tencent/QMProxyAccelerator/3.0.9604.134/Tencent.QMProxyAccelerator.installer.yaml
  manifests/t/Tencent/QMProxyAccelerator/3.0.9604.134/Tencent.QMProxyAccelerator.locale.en-US.yaml
  manifests/t/Tencent/QMProxyAccelerator/3.0.9604.134/Tencent.QMProxyAccelerator.locale.zh-CN.yaml
  manifests/t/Tencent/QMProxyAccelerator/3.0.9604.134/Tencent.QMProxyAccelerator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64864 New version: Wondershare.Anireel version 2.1.5
  manifests/w/Wondershare/Anireel/2.1.5/Wondershare.Anireel.installer.yaml
  manifests/w/Wondershare/Anireel/2.1.5/Wondershare.Anireel.locale.en-US.yaml
  manifests/w/Wondershare/Anireel/2.1.5/Wondershare.Anireel.locale.zh-CN.yaml
  manifests/w/Wondershare/Anireel/2.1.5/Wondershare.Anireel.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64865 New version: Appest.Dida version 4.2.5.0
  manifests/a/Appest/Dida/4.2.5.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/4.2.5.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/4.2.5.0/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/4.2.5.0/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64870 New version: Fndroid.ClashForWindows version 0.19.23
  manifests/f/Fndroid/ClashForWindows/0.19.23/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.19.23/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.19.23/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64889 Microsoft.VisualStudioCode.Insiders_v1.69.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.69.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64884 New version: Jackett.Jackett version 0.20.1261
  manifests/j/Jackett/Jackett/0.20.1261/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1261/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1261/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64882 New version: Youqu.ToDesk version 4.3.1.3
  manifests/y/Youqu/ToDesk/4.3.1.3/Youqu.ToDesk.installer.yaml
  manifests/y/Youqu/ToDesk/4.3.1.3/Youqu.ToDesk.locale.en-US.yaml
  manifests/y/Youqu/ToDesk/4.3.1.3/Youqu.ToDesk.locale.zh-CN.yaml
  manifests/y/Youqu/ToDesk/4.3.1.3/Youqu.ToDesk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64861 New version: Wondershare.DemoCreator version 6.0.0.48
  manifests/w/Wondershare/DemoCreator/6.0.0.48/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/6.0.0.48/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/6.0.0.48/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/6.0.0.48/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64873 New version: defi.defi version 2.15.0
  manifests/d/defi/defi/2.15.0/defi.defi.installer.yaml
  manifests/d/defi/defi/2.15.0/defi.defi.locale.en-US.yaml
  manifests/d/defi/defi/2.15.0/defi.defi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64874 New version: FengHe.FocusNote version 2.15.5-673
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.installer.yaml
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.locale.en-US.yaml
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.locale.zh-CN.yaml
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64878 New version: Tencent.TencentDocs version 2.3.8
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.locale.zh-CN.yaml
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64880 Toit.Jaguar version 1.2.8
  manifests/t/Toit/Jaguar/1.2.8/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.2.8/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.2.8/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64877 New version: OpenWhisperSystems.Signal version 5.48.0 [FP-O]
  manifests/o/OpenWhisperSystems/Signal/5.48.0/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/5.48.0/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/5.48.0/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64897 Update: KDE.Kate version 22.04.2
  manifests/k/KDE/Kate/22.04.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64894 New version: Douyu.DouyuLive version 8.5.6.2
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.installer.yaml
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.locale.en-US.yaml
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.locale.zh-CN.yaml
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64898 New version: StandardNotes.StandardNotes version 3.23.21
  manifests/s/StandardNotes/StandardNotes/3.23.21/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.23.21/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.23.21/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64905 Remove IObit.AdvancedSystemCare version 15.4.0.250
  manifests/i/IObit/AdvancedSystemCare/15.4.0.250/IObit.AdvancedSystemCare.installer.yaml
  manifests/i/IObit/AdvancedSystemCare/15.4.0.250/IObit.AdvancedSystemCare.locale.en-US.yaml
  manifests/i/IObit/AdvancedSystemCare/15.4.0.250/IObit.AdvancedSystemCare.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64899 Toit.Jaguar version 1.3.0
  manifests/t/Toit/Jaguar/1.3.0/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.3.0/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.3.0/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64901 Update JAMSoftware.Ultrasearch to 3.3.1
  manifests/j/JAMSoftware/Ultrasearch/3.3.1/JAMSoftware.Ultrasearch.installer.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.3.1/JAMSoftware.Ultrasearch.locale.de-DE.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.3.1/JAMSoftware.Ultrasearch.locale.en-US.yaml
  manifests/j/JAMSoftware/Ultrasearch/3.3.1/JAMSoftware.Ultrasearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64900 Update: JetBrains.PHPStorm version 221.5921.28
  manifests/j/JetBrains/PHPStorm/221.5921.28/JetBrains.PHPStorm.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64855 KuGou.gejigeji version 2.0.2.1268
  manifests/k/KuGou/gejigeji/2.0.2.1268/KuGou.gejigeji.installer.yaml
  manifests/k/KuGou/gejigeji/2.0.2.1268/KuGou.gejigeji.locale.en-US.yaml
  manifests/k/KuGou/gejigeji/2.0.2.1268/KuGou.gejigeji.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64883 ReleaseNotes: Youqu.ToDesk version 4.3.1.2
  manifests/y/Youqu/ToDesk/4.3.1.2/Youqu.ToDesk.installer.yaml
  manifests/y/Youqu/ToDesk/4.3.1.2/Youqu.ToDesk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64876 New version: OpenWhisperSystems.Signal.Beta version 5.49.0-beta.1 [FP-O]
  manifests/o/OpenWhisperSystems/Signal/Beta/5.49.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.49.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/5.49.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64902 Fix PackageVersion for IObit.AdvancedSystemCare
  manifests/i/IObit/AdvancedSystemCare/15.4.0/IObit.AdvancedSystemCare.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64914 Update Microsoft.VC++2015-2022Redist-x64 from 14.32.31326.0 to 14.32.31332.0
  manifests/m/Microsoft/VC++2015-2022Redist-x64/14.32.31332.0/Microsoft.VC++2015-2022Redist-x64.installer.yaml
  manifests/m/Microsoft/VC++2015-2022Redist-x64/14.32.31332.0/Microsoft.VC++2015-2022Redist-x64.locale.en-US.yaml
  manifests/m/Microsoft/VC++2015-2022Redist-x64/14.32.31332.0/Microsoft.VC++2015-2022Redist-x64.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64909 Added Firefox Developer Edition version 103.0b3.
  manifests/m/Mozilla/Firefox/DeveloperEdition/103.0b3/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/103.0b3/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/103.0b3/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64915 Update Microsoft.VC++2015-2022Redist-x86 from 14.32.31326.0 to 14.32.31332.0
  manifests/m/Microsoft/VC++2015-2022Redist-x86/14.32.31332.0/Microsoft.VC++2015-2022Redist-x86.installer.yaml
  manifests/m/Microsoft/VC++2015-2022Redist-x86/14.32.31332.0/Microsoft.VC++2015-2022Redist-x86.locale.en-US.yaml
  manifests/m/Microsoft/VC++2015-2022Redist-x86/14.32.31332.0/Microsoft.VC++2015-2022Redist-x86.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64854 New version: vim.vim version 9.0.0014
  manifests/v/vim/vim/9.0.0014/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0014/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0014/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64913 Updated Google Chrome Dev to version 105.0.5148.2.
  manifests/g/Google/Chrome/Dev/105.0.5148.2/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/105.0.5148.2/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/105.0.5148.2/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/105.0.5148.2/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64908 Testing: Added user scoped installers to Git version 2.37.0.
  manifests/g/Git/Git/2.37.0/Git.Git.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64911 Added Microsoft Edge version 103.0.1264.44.
  manifests/m/Microsoft/Edge/103.0.1264.44/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/103.0.1264.44/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/103.0.1264.44/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/103.0.1264.44/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64918 Added AutomatedLab version 5.43.0.
  manifests/a/AutomatedLab/AutomatedLab/5.43.0/AutomatedLab.AutomatedLab.installer.yaml
  manifests/a/AutomatedLab/AutomatedLab/5.43.0/AutomatedLab.AutomatedLab.locale.en-US.yaml
  manifests/a/AutomatedLab/AutomatedLab/5.43.0/AutomatedLab.AutomatedLab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64927 MFSTBot: Multiple Reviewers
  .github/fabricbot.json
Labels: Moderator-Approved, Author-Not-Authorized

#64923 New version: gileli121.windowtop version 5.13.1
  manifests/g/gileli121/windowtop/5.13.1/gileli121.windowtop.installer.yaml
  manifests/g/gileli121/windowtop/5.13.1/gileli121.windowtop.locale.en-US.yaml
  manifests/g/gileli121/windowtop/5.13.1/gileli121.windowtop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64925 New version: JinweiZhiguang.MasterGo version 1.1.0
  manifests/j/JinweiZhiguang/MasterGo/1.1.0/JinweiZhiguang.MasterGo.installer.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.1.0/JinweiZhiguang.MasterGo.locale.en-US.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.1.0/JinweiZhiguang.MasterGo.locale.zh-CN.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.1.0/JinweiZhiguang.MasterGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64926 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64929 New version: Tencent.TencentMeeting version 3.9.4.403
  manifests/t/Tencent/TencentMeeting/3.9.4.403/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.9.4.403/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.9.4.403/Tencent.TencentMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeeting/3.9.4.403/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64930 New version: PragmaTwice.proxinject version 0.3.1-pre
  manifests/p/PragmaTwice/proxinject/0.3.1-pre/PragmaTwice.proxinject.installer.yaml
  manifests/p/PragmaTwice/proxinject/0.3.1-pre/PragmaTwice.proxinject.locale.en-US.yaml
  manifests/p/PragmaTwice/proxinject/0.3.1-pre/PragmaTwice.proxinject.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64924 New version: JetBrains.GoLand.EarlyAccess version 222.3244.4
  manifests/j/JetBrains/GoLand/EarlyAccess/222.3244.4/JetBrains.GoLand.EarlyAccess.installer.yaml
  manifests/j/JetBrains/GoLand/EarlyAccess/222.3244.4/JetBrains.GoLand.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/EarlyAccess/222.3244.4/JetBrains.GoLand.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64935 ReleaseNotes: Douyu.DouyuLive version 8.5.6.2
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.installer.yaml
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.locale.en-US.yaml
  manifests/d/Douyu/DouyuLive/8.5.6.2/Douyu.DouyuLive.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64919 New version: tencent.qq 9.6.2.28755
  manifests/t/Tencent/QQ/9.6.2.28755/Tencent.QQ.installer.yaml
  manifests/t/Tencent/QQ/9.6.2.28755/Tencent.QQ.locale.en-US.yaml
  manifests/t/Tencent/QQ/9.6.2.28755/Tencent.QQ.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/9.6.2.28755/Tencent.QQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64937 Toit.Jaguar version 1.3.1
  manifests/t/Toit/Jaguar/1.3.1/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.3.1/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.3.1/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64936 New version: Catsxp.Catsxp version 103.2.7.1
  manifests/c/Catsxp/Catsxp/103.2.7.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/103.2.7.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/103.2.7.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/103.2.7.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64934 New version: Wondershare.WXRecovery version 3.5.5.1
  manifests/w/Wondershare/WXRecovery/3.5.5.1/Wondershare.WXRecovery.installer.yaml
  manifests/w/Wondershare/WXRecovery/3.5.5.1/Wondershare.WXRecovery.locale.en-US.yaml
  manifests/w/Wondershare/WXRecovery/3.5.5.1/Wondershare.WXRecovery.locale.zh-CN.yaml
  manifests/w/Wondershare/WXRecovery/3.5.5.1/Wondershare.WXRecovery.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64939 Ferdium.Ferdium version 6.0.0-nightly.84
  manifests/f/Ferdium/Ferdium/6.0.0-nightly.84/Ferdium.Ferdium.installer.yaml
  manifests/f/Ferdium/Ferdium/6.0.0-nightly.84/Ferdium.Ferdium.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/6.0.0-nightly.84/Ferdium.Ferdium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64938 JanDeDobbeleer.OhMyPosh version 8.9.2
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64955 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64952 New version: Google.Chrome.Canary version 105.0.5154.2
  manifests/g/Google/Chrome/Canary/105.0.5154.2/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/105.0.5154.2/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/105.0.5154.2/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/105.0.5154.2/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64954 Update: KDE.KDEConnect version 22.04.2
  manifests/k/KDE/KDEConnect/22.04.2/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64951 New version: vim.vim version 9.0.0022
  manifests/v/vim/vim/9.0.0022/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0022/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0022/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64967 ReleaseNotes: Tencent.TencentDocs version 2.3.8
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.3.8/Tencent.TencentDocs.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64965 Modify: HumbleBundle.HumbleApp version 1.1.1+341
  manifests/h/HumbleBundle/HumbleApp/1.1.1+341/HumbleBundle.HumbleApp.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64966 ReleaseNotes: FengHe.FocusNote version 2.15.5-673
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.installer.yaml
  manifests/f/FengHe/FocusNote/2.15.5-673/FengHe.FocusNote.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64964 Modify: Alibaba.Yuque version 1.1.4
  manifests/a/Alibaba/Yuque/1.1.4/Alibaba.Yuque.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64962 Modify: Kiraku.AudioJam version 1.7.0-130
  manifests/k/Kiraku/AudioJam/1.7.0-130/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.7.0-130/Kiraku.AudioJam.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64946 JanDeDobbeleer.OhMyPosh version 8.10.0
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64969 ReleaseNotes: ByteDance.Feishu version 5.14.9
  manifests/b/ByteDance/Feishu/5.14.9/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.14.9/ByteDance.Feishu.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64963 Modify: Alibaba.Teambition version 2.0.2
  manifests/a/Alibaba/Teambition/2.0.2/Alibaba.Teambition.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64972 Update: KDE.Dolphin version 22.04.2
  manifests/k/KDE/Dolphin/22.04.2/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64970 Update Netron to 5.9.0
  manifests/l/LutzRoeder/Netron/5.9.0/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.9.0/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.9.0/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64978 New version: Jackett.Jackett version 0.20.1263
  manifests/j/Jackett/Jackett/0.20.1263/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1263/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1263/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64968 New version: ByteDance.Feishu version 5.15.6
  manifests/b/ByteDance/Feishu/5.15.6/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/5.15.6/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/5.15.6/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/5.15.6/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64979 New version: Tencent.QiDian version 5.2.0.19006
  manifests/t/Tencent/QiDian/5.2.0.19006/Tencent.QiDian.installer.yaml
  manifests/t/Tencent/QiDian/5.2.0.19006/Tencent.QiDian.locale.en-US.yaml
  manifests/t/Tencent/QiDian/5.2.0.19006/Tencent.QiDian.locale.zh-CN.yaml
  manifests/t/Tencent/QiDian/5.2.0.19006/Tencent.QiDian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64971 New version: Wondershare.Anireel version 2.1.6
  manifests/w/Wondershare/Anireel/2.1.6/Wondershare.Anireel.installer.yaml
  manifests/w/Wondershare/Anireel/2.1.6/Wondershare.Anireel.locale.en-US.yaml
  manifests/w/Wondershare/Anireel/2.1.6/Wondershare.Anireel.locale.zh-CN.yaml
  manifests/w/Wondershare/Anireel/2.1.6/Wondershare.Anireel.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64980 Modify: Tencent.QQ version 9.6.2.28755
  manifests/t/Tencent/QQ/9.6.2.28755/Tencent.QQ.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64982 JanDeDobbeleer.OhMyPosh version 8.10.2
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.10.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64944 DoltHub.Dolt version 0.40.14
  manifests/d/DoltHub/Dolt/0.40.14/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.40.14/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.40.14/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64947 Cockos.REAPER version 6.62
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64974 New version: xanderfrangos.crushee version 2.4.1
  manifests/x/xanderfrangos/crushee/2.4.1/xanderfrangos.crushee.installer.yaml
  manifests/x/xanderfrangos/crushee/2.4.1/xanderfrangos.crushee.locale.en-US.yaml
  manifests/x/xanderfrangos/crushee/2.4.1/xanderfrangos.crushee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64973 New version: Redisant.KafkaAssistant version 1.0.9.1
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.installer.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.locale.en-US.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64957 New version: Mozilla.Thunderbird.Beta version 103.0b2
  manifests/m/Mozilla/Thunderbird/Beta/103.0b2/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/103.0b2/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/103.0b2/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64953 New version: joncampbell123.DOSBox-X version 0.84.1
  manifests/j/joncampbell123/DOSBox-X/0.84.1/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.84.1/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.84.1/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64942 DoltHub.Dolt version 0.40.13
  manifests/d/DoltHub/Dolt/0.40.13/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.40.13/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.40.13/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64985 New version: Google.Chrome.Canary version 105.0.5155.0
  manifests/g/Google/Chrome/Canary/105.0.5155.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/105.0.5155.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/105.0.5155.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/105.0.5155.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64986 Update: KDE.Kate version 22.04.2
  manifests/k/KDE/Kate/22.04.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64991 Moving: HexRays.IDA.Free version 7.7
  manifests/h/HexRays/IDA/Free/7.7/HexRays.IDA.Free.installer.yaml
  manifests/h/HexRays/IDA/Free/7.7/HexRays.IDA.Free.locale.en-US.yaml
  manifests/h/HexRays/IDA/Free/7.7/HexRays.IDA.Free.locale.zh-CN.yaml
  manifests/h/HexRays/IDA/Free/7.7/HexRays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64994 Moving: HexRays.IDA.Free version 7.0
  manifests/h/HexRays/IDA/Free/7.0/HexRays.IDA.Free.installer.yaml
  manifests/h/HexRays/IDA/Free/7.0/HexRays.IDA.Free.locale.en-US.yaml
  manifests/h/HexRays/IDA/Free/7.0/HexRays.IDA.Free.locale.zh-CN.yaml
  manifests/h/HexRays/IDA/Free/7.0/HexRays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64993 Moving: HexRays.IDA.Free version 7.6
  manifests/h/HexRays/IDA/Free/7.6/HexRays.IDA.Free.installer.yaml
  manifests/h/HexRays/IDA/Free/7.6/HexRays.IDA.Free.locale.en-US.yaml
  manifests/h/HexRays/IDA/Free/7.6/HexRays.IDA.Free.locale.zh-CN.yaml
  manifests/h/HexRays/IDA/Free/7.6/HexRays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64992 Moved: Hex-Rays.IDA.Free version 7.7
  manifests/h/Hex-Rays/IDA/Free/7.7/Hex-Rays.IDA.Free.installer.yaml
  manifests/h/Hex-Rays/IDA/Free/7.7/Hex-Rays.IDA.Free.locale.en-US.yaml
  manifests/h/Hex-Rays/IDA/Free/7.7/Hex-Rays.IDA.Free.locale.zh-CN.yaml
  manifests/h/Hex-Rays/IDA/Free/7.7/Hex-Rays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64956 New version: Microsoft.Bicep version 0.8.2.30886
  manifests/m/Microsoft/Bicep/0.8.2.30886/Microsoft.Bicep.installer.yaml
  manifests/m/Microsoft/Bicep/0.8.2.30886/Microsoft.Bicep.locale.en-US.yaml
  manifests/m/Microsoft/Bicep/0.8.2.30886/Microsoft.Bicep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64906 JanDeDobbeleer.OhMyPosh version 8.9.0
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.9.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64998 Modify: Tencent.TIM version 3.3.9.22051
  manifests/t/Tencent/TIM/3.3.9.22051/Tencent.TIM.installer.yaml
  manifests/t/Tencent/TIM/3.3.9.22051/Tencent.TIM.locale.en-US.yaml
  manifests/t/Tencent/TIM/3.3.9.22051/Tencent.TIM.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64999 Modify: Ruben2776.PicView version 1.6.6
  manifests/r/Ruben2776/PicView/1.6.6/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/1.6.6/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/1.6.6/Ruben2776.PicView.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65000 Moving: Sogou.QQPinyin version 6.6
  manifests/s/Sogou/QQPinyin/6.6/Sogou.QQPinyin.installer.yaml
  manifests/s/Sogou/QQPinyin/6.6/Sogou.QQPinyin.locale.en-US.yaml
  manifests/s/Sogou/QQPinyin/6.6/Sogou.QQPinyin.locale.zh-CN.yaml
  manifests/s/Sogou/QQPinyin/6.6/Sogou.QQPinyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64997 Moved: Hex-Rays.IDA.Free version 7.0
  manifests/h/Hex-Rays/IDA/Free/7.0/Hex-Rays.IDA.Free.installer.yaml
  manifests/h/Hex-Rays/IDA/Free/7.0/Hex-Rays.IDA.Free.locale.en-US.yaml
  manifests/h/Hex-Rays/IDA/Free/7.0/Hex-Rays.IDA.Free.locale.zh-CN.yaml
  manifests/h/Hex-Rays/IDA/Free/7.0/Hex-Rays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64995 Moved: Hex-Rays.IDA.Free version 7.6
  manifests/h/Hex-Rays/IDA/Free/7.6/Hex-Rays.IDA.Free.installer.yaml
  manifests/h/Hex-Rays/IDA/Free/7.6/Hex-Rays.IDA.Free.locale.en-US.yaml
  manifests/h/Hex-Rays/IDA/Free/7.6/Hex-Rays.IDA.Free.locale.zh-CN.yaml
  manifests/h/Hex-Rays/IDA/Free/7.6/Hex-Rays.IDA.Free.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#64996 New version: SatoshiLabs.trezor-suite version 22.6.5
  manifests/s/SatoshiLabs/trezor-suite/22.6.5/SatoshiLabs.trezor-suite.installer.yaml
  manifests/s/SatoshiLabs/trezor-suite/22.6.5/SatoshiLabs.trezor-suite.locale.en-US.yaml
  manifests/s/SatoshiLabs/trezor-suite/22.6.5/SatoshiLabs.trezor-suite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65001 Datronicsoft.SpacedeskDriver.Server version 0.9.1127.0
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1127.0/Datronicsoft.SpacedeskDriver.Server.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1127.0/Datronicsoft.SpacedeskDriver.Server.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/0.9.1127.0/Datronicsoft.SpacedeskDriver.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65012 New version: ChilliBits.ComposeGenerator version 1.9.0
  manifests/c/ChilliBits/ComposeGenerator/1.9.0/ChilliBits.ComposeGenerator.installer.yaml
  manifests/c/ChilliBits/ComposeGenerator/1.9.0/ChilliBits.ComposeGenerator.locale.de-DE.yaml
  manifests/c/ChilliBits/ComposeGenerator/1.9.0/ChilliBits.ComposeGenerator.locale.en-US.yaml
  manifests/c/ChilliBits/ComposeGenerator/1.9.0/ChilliBits.ComposeGenerator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65016 New version: Google.Chrome.Canary version 105.0.5157.0 [FP-O]
  manifests/g/Google/Chrome/Canary/105.0.5157.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/105.0.5157.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/105.0.5157.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/105.0.5157.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65011 New version: Chatty.Chatty version 0.19
  manifests/c/Chatty/Chatty/0.19/Chatty.Chatty.installer.yaml
  manifests/c/Chatty/Chatty/0.19/Chatty.Chatty.locale.en-US.yaml
  manifests/c/Chatty/Chatty/0.19/Chatty.Chatty.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65017 Update: KDE.Dolphin version 22.04.2
  manifests/k/KDE/Dolphin/22.04.2/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65022 New version: xanderfrangos.crushee version 2.4.2
  manifests/x/xanderfrangos/crushee/2.4.2/xanderfrangos.crushee.installer.yaml
  manifests/x/xanderfrangos/crushee/2.4.2/xanderfrangos.crushee.locale.en-US.yaml
  manifests/x/xanderfrangos/crushee/2.4.2/xanderfrangos.crushee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65026 New version: KOOK.KOOK version 0.0.52.1
  manifests/k/KOOK/KOOK/0.0.52.1/KOOK.KOOK.installer.yaml
  manifests/k/KOOK/KOOK/0.0.52.1/KOOK.KOOK.locale.en-US.yaml
  manifests/k/KOOK/KOOK/0.0.52.1/KOOK.KOOK.locale.zh-CN.yaml
  manifests/k/KOOK/KOOK/0.0.52.1/KOOK.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65025 ReleaseNotes: Redisant.KafkaAssistant version 1.0.9.1
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.locale.en-US.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.9.1/Redisant.KafkaAssistant.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65018 Update: KDE.KDEConnect version 22.04.2
  manifests/k/KDE/KDEConnect/22.04.2/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65013 New version: ChilliBits.Spice version 0.8.6
  manifests/c/ChilliBits/Spice/0.8.6/ChilliBits.Spice.installer.yaml
  manifests/c/ChilliBits/Spice/0.8.6/ChilliBits.Spice.locale.de-DE.yaml
  manifests/c/ChilliBits/Spice/0.8.6/ChilliBits.Spice.locale.en-US.yaml
  manifests/c/ChilliBits/Spice/0.8.6/ChilliBits.Spice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65023 New version: Jackett.Jackett version 0.20.1270
  manifests/j/Jackett/Jackett/0.20.1270/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1270/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1270/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65019 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65024 Update: KDE.Kate version 22.04.2
  manifests/k/KDE/Kate/22.04.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65015 New version: Fabio286.antares version 0.5.8
  manifests/f/Fabio286/antares/0.5.8/Fabio286.antares.installer.yaml
  manifests/f/Fabio286/antares/0.5.8/Fabio286.antares.locale.en-US.yaml
  manifests/f/Fabio286/antares/0.5.8/Fabio286.antares.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65027 JanDeDobbeleer.OhMyPosh version 8.11.0
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65021 New version: wangyu.BilibiliVideoDownload version 3.3.3
  manifests/w/wangyu/BilibiliVideoDownload/3.3.3/wangyu.BilibiliVideoDownload.installer.yaml
  manifests/w/wangyu/BilibiliVideoDownload/3.3.3/wangyu.BilibiliVideoDownload.locale.en-US.yaml
  manifests/w/wangyu/BilibiliVideoDownload/3.3.3/wangyu.BilibiliVideoDownload.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65030 SmartSoft.SmartFTP version 10.0.2999.0
  manifests/s/SmartSoft/SmartFTP/10.0.2999.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2999.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2999.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65006 New version: vim.vim version 9.0.0030
  manifests/v/vim/vim/9.0.0030/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0030/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0030/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65005 New version: TopalaSoftwareSolutions.SIW version 2022.05.21g
  manifests/t/TopalaSoftwareSolutions/SIW/2022.05.21g/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2022.05.21g/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2022.05.21g/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65020 New version: SomePythonThings.ElevenClock version 3.6.1
  manifests/s/SomePythonThings/ElevenClock/3.6.1/SomePythonThings.ElevenClock.installer.yaml
  manifests/s/SomePythonThings/ElevenClock/3.6.1/SomePythonThings.ElevenClock.locale.en-US.yaml
  manifests/s/SomePythonThings/ElevenClock/3.6.1/SomePythonThings.ElevenClock.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65002 Update LibreWolf.LibreWolf to v102.0-2
  manifests/l/LibreWolf/LibreWolf/102.0-2/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/102.0-2/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/102.0-2/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65014 New version: darktable.darktable version release-4.0.0
  manifests/d/darktable/darktable/4.0.0/darktable.darktable.installer.yaml
  manifests/d/darktable/darktable/4.0.0/darktable.darktable.locale.en-US.yaml
  manifests/d/darktable/darktable/4.0.0/darktable.darktable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65035 Update Velocidex.Velociraptor to 0.65.3
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.installer.yaml
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.locale.en-US.yaml
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65033 New version: ExpressLRS.ExpressLRS-Configurator version 1.4.2
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.4.2/ExpressLRS.ExpressLRS-Configurator.installer.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.4.2/ExpressLRS.ExpressLRS-Configurator.locale.en-US.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.4.2/ExpressLRS.ExpressLRS-Configurator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65032 Update Prey.Prey to 1.10.7
  manifests/p/Prey/Prey/1.10.7/Prey.Prey.installer.yaml
  manifests/p/Prey/Prey/1.10.7/Prey.Prey.locale.en-US.yaml
  manifests/p/Prey/Prey/1.10.7/Prey.Prey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65036 New version: xanderfrangos.crushee version 2.4.3
  manifests/x/xanderfrangos/crushee/2.4.3/xanderfrangos.crushee.installer.yaml
  manifests/x/xanderfrangos/crushee/2.4.3/xanderfrangos.crushee.locale.en-US.yaml
  manifests/x/xanderfrangos/crushee/2.4.3/xanderfrangos.crushee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65038 New version: Maxthon.Maxthon.6 version 6.1.3.3000
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.installer.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65037 Update stevencohn.OneMore to 4.18
  manifests/s/stevencohn/OneMore/4.18/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/4.18/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/4.18/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65034 New version: LaurentPRenedeCotret.pandoc-plot version 1.5.4
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.4/LaurentPRenedeCotret.pandoc-plot.installer.yaml
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.4/LaurentPRenedeCotret.pandoc-plot.locale.en-US.yaml
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.4/LaurentPRenedeCotret.pandoc-plot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65042 New version: Peppy.Osu! version 2022.704.0
  manifests/p/Peppy/Osu!/2022.704.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2022.704.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2022.704.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65040 JanDeDobbeleer.OhMyPosh version 8.11.1
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/8.11.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65041 New version: DupeGuru.DupeGuru version 4.3.0
  manifests/d/DupeGuru/DupeGuru/4.3.0/DupeGuru.DupeGuru.installer.yaml
  manifests/d/DupeGuru/DupeGuru/4.3.0/DupeGuru.DupeGuru.locale.en-US.yaml
  manifests/d/DupeGuru/DupeGuru/4.3.0/DupeGuru.DupeGuru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65082 New version: UniversalMediaServer.UniversalMediaServer version 11.1.1.1
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.1.1.1/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.1.1.1/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/11.1.1.1/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65083 New version: vcync.modV version 3.22.4
  manifests/v/vcync/modV/3.22.4/vcync.modV.installer.yaml
  manifests/v/vcync/modV/3.22.4/vcync.modV.locale.en-US.yaml
  manifests/v/vcync/modV/3.22.4/vcync.modV.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65054 New version: maximmax42.CustomRP version 1.15.1
  manifests/m/maximmax42/CustomRP/1.15.1/maximmax42.CustomRP.installer.yaml
  manifests/m/maximmax42/CustomRP/1.15.1/maximmax42.CustomRP.locale.en-US.yaml
  manifests/m/maximmax42/CustomRP/1.15.1/maximmax42.CustomRP.locale.ru-RU.yaml
  manifests/m/maximmax42/CustomRP/1.15.1/maximmax42.CustomRP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65081 New version: ProtonTechnologies.ProtonVPN version 2.0.1
  manifests/p/ProtonTechnologies/ProtonVPN/2.0.1/ProtonTechnologies.ProtonVPN.installer.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/2.0.1/ProtonTechnologies.ProtonVPN.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/2.0.1/ProtonTechnologies.ProtonVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65075 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65073 Update: KDE.Kate version 22.04.2
  manifests/k/KDE/Kate/22.04.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65070 New version: Flameshot.Flameshot version 12.1.0
  manifests/f/Flameshot/Flameshot/12.1.0/Flameshot.Flameshot.installer.yaml
  manifests/f/Flameshot/Flameshot/12.1.0/Flameshot.Flameshot.locale.en-US.yaml
  manifests/f/Flameshot/Flameshot/12.1.0/Flameshot.Flameshot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65066 Moving: Maxthon.Maxthon5 version 5.3.8.2000
  manifests/m/Maxthon/Maxthon5/5.3.8.2000/Maxthon.Maxthon5.installer.yaml
  manifests/m/Maxthon/Maxthon5/5.3.8.2000/Maxthon.Maxthon5.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon5/5.3.8.2000/Maxthon.Maxthon5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65067 Moved: Maxthon.Maxthon.5 version 5.3.8.2000
  manifests/m/Maxthon/Maxthon/5/5.3.8.2000/Maxthon.Maxthon.5.installer.yaml
  manifests/m/Maxthon/Maxthon/5/5.3.8.2000/Maxthon.Maxthon.5.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/5/5.3.8.2000/Maxthon.Maxthon.5.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/5/5.3.8.2000/Maxthon.Maxthon.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#65068 New version: Jackett.Jackett version 0.20.1274
  manifests/j/Jackett/Jackett/0.20.1274/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1274/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1274/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65076 New version: Thunisoft.HuayuPY version 7.3.0.296
  manifests/t/Thunisoft/HuayuPY/7.3.0.296/Thunisoft.HuayuPY.installer.yaml
  manifests/t/Thunisoft/HuayuPY/7.3.0.296/Thunisoft.HuayuPY.locale.en-US.yaml
  manifests/t/Thunisoft/HuayuPY/7.3.0.296/Thunisoft.HuayuPY.locale.zh-CN.yaml
  manifests/t/Thunisoft/HuayuPY/7.3.0.296/Thunisoft.HuayuPY.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65064 New version: electerm.electerm version 1.21.93
  manifests/e/electerm/electerm/1.21.93/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.21.93/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.21.93/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65063 Update Netron to 5.9.1
  manifests/l/LutzRoeder/Netron/5.9.1/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.9.1/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.9.1/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65078 New package: PaodingAI.Calliper version 1.1.44
  manifests/p/PaodingAI/Calliper/1.1.44/PaodingAI.Calliper.installer.yaml
  manifests/p/PaodingAI/Calliper/1.1.44/PaodingAI.Calliper.locale.en-US.yaml
  manifests/p/PaodingAI/Calliper/1.1.44/PaodingAI.Calliper.locale.zh-CN.yaml
  manifests/p/PaodingAI/Calliper/1.1.44/PaodingAI.Calliper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65085 CreativeTechnology.CreativeApp version 1.9.03.00
  manifests/c/CreativeTechnology/CreativeApp/1.9.03.00/CreativeTechnology.CreativeApp.installer.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.9.03.00/CreativeTechnology.CreativeApp.locale.en-US.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.9.03.00/CreativeTechnology.CreativeApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65084 CreativeTechnology.CreativeApp version 1.8.03.00
  manifests/c/CreativeTechnology/CreativeApp/1.8.03.00/CreativeTechnology.CreativeApp.installer.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.8.03.00/CreativeTechnology.CreativeApp.locale.en-US.yaml
  manifests/c/CreativeTechnology/CreativeApp/1.8.03.00/CreativeTechnology.CreativeApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65043 Add version: Velocidex.Velociraptor version 0.6.5-0
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.installer.yaml
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.locale.en-US.yaml
  manifests/v/Velocidex/Velociraptor/0.65.3/Velocidex.Velociraptor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#65088 New package: PaodingAI.Scriber version 1.0.19
  manifests/p/PaodingAI/Scriber/1.0.19/PaodingAI.Scriber.installer.yaml
  manifests/p/PaodingAI/Scriber/1.0.19/PaodingAI.Scriber.locale.en-US.yaml
  manifests/p/PaodingAI/Scriber/1.0.19/PaodingAI.Scriber.locale.zh-CN.yaml
  manifests/p/PaodingAI/Scriber/1.0.19/PaodingAI.Scriber.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65044 Adding CondaForge.Mambaforge
  manifests/c/CondaForge/Mambaforge/4.12.0-2/CondaForge.Mambaforge.installer.yaml
  manifests/c/CondaForge/Mambaforge/4.12.0-2/CondaForge.Mambaforge.locale.en-US.yaml
  manifests/c/CondaForge/Mambaforge/4.12.0-2/CondaForge.Mambaforge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65097 Add SteelSeries GG 20.1.0
  manifests/s/SteelSeries/GG/20.1.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/20.1.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/20.1.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65095 New version: quick123.quickredis version 2.7.1
  manifests/q/quick123/quickredis/2.7.1/quick123.quickredis.installer.yaml
  manifests/q/quick123/quickredis/2.7.1/quick123.quickredis.locale.en-US.yaml
  manifests/q/quick123/quickredis/2.7.1/quick123.quickredis.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65093 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65096 New package: Jidifudi.GT4T version 8.35.220703
  manifests/j/Jidifudi/GT4T/8.35.220703/Jidifudi.GT4T.installer.yaml
  manifests/j/Jidifudi/GT4T/8.35.220703/Jidifudi.GT4T.locale.en-US.yaml
  manifests/j/Jidifudi/GT4T/8.35.220703/Jidifudi.GT4T.locale.zh-CN.yaml
  manifests/j/Jidifudi/GT4T/8.35.220703/Jidifudi.GT4T.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#65089 New version: CiderCollective.Cider version 1.5.1-beta.290 [FP-O]
  manifests/c/CiderCollective/Cider/1.5.1-beta.290/CiderCollective.Cider.installer.yaml
  manifests/c/CiderCollective/Cider/1.5.1-beta.290/CiderCollective.Cider.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/1.5.1-beta.290/CiderCollective.Cider.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
