Repository microsoft/winget-pkgs, pull requests merged in 2022-11, with the labels that each got.

#86595 Add Microsoft Build of OpenJDK 11 Oct PSU
  manifests/m/Microsoft/OpenJDK/11/11.0.17.8/Microsoft.OpenJDK.11.installer.yaml
  manifests/m/Microsoft/OpenJDK/11/11.0.17.8/Microsoft.OpenJDK.11.locale.en-US.yaml
  manifests/m/Microsoft/OpenJDK/11/11.0.17.8/Microsoft.OpenJDK.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86696 Splashtop.SplashtopStreamer.Deployment version 3.5.2.2
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.2.2/Splashtop.SplashtopStreamer.Deployment.installer.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.2.2/Splashtop.SplashtopStreamer.Deployment.locale.en-US.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.2.2/Splashtop.SplashtopStreamer.Deployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86834 Python.Python.3.12 version 3.12.0a1
  manifests/p/Python/Python/3/12/3.12.0a1/Python.Python.3.12.installer.yaml
  manifests/p/Python/Python/3/12/3.12.0a1/Python.Python.3.12.locale.en-US.yaml
  manifests/p/Python/Python/3/12/3.12.0a1/Python.Python.3.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86860 Modify: Zoom.ZoomRooms version 5.12.2
  manifests/z/Zoom/ZoomRooms/5.12.2/Zoom.ZoomRooms.installer.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#86826 Python.Python.3.9 version 3.9.13
  manifests/p/Python/Python/3/9/3.9.13/Python.Python.3.9.installer.yaml
  manifests/p/Python/Python/3/9/3.9.13/Python.Python.3.9.locale.en-US.yaml
  manifests/p/Python/Python/3/9/3.9.13/Python.Python.3.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86988 Added Firefox Developer Edition version 107.0b7.
  manifests/m/Mozilla/Firefox/DeveloperEdition/107.0b7/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/107.0b7/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/107.0b7/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87027 New version: Taiko2k.TauonMusicBox version 7.4.3
  manifests/t/Taiko2k/TauonMusicBox/7.4.3/Taiko2k.TauonMusicBox.installer.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.4.3/Taiko2k.TauonMusicBox.locale.en-US.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.4.3/Taiko2k.TauonMusicBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87066 New version: Nvidia.GeForceNow version 2.0.46.112
  manifests/n/Nvidia/GeForceNow/2.0.46.112/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.46.112/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.46.112/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.46.112/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87056 Update: KDE.Kdenlive version 22.08.2
  manifests/k/KDE/Kdenlive/22.08.2/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87065 Update: KDE.Kate version 22.08.2
  manifests/k/KDE/Kate/22.08.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87068 Update: OpenJS.NodeJS.Nightly version 20.0.0
  manifests/o/OpenJS/NodeJS/Nightly/20.0.0/OpenJS.NodeJS.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87057 Update: KDE.Okular version 22.08.2
  manifests/k/KDE/Okular/22.08.2/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#87063 New version: Jackett.Jackett version 0.20.2182
  manifests/j/Jackett/Jackett/0.20.2182/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2182/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2182/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87074 Added Mozilla Firefox version 106.0.3.
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/106.0.3/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86894 TableClothProject.TableCloth version 0.5.4
  manifests/t/TableClothProject/TableCloth/0.5.4/TableClothProject.TableCloth.installer.yaml
  manifests/t/TableClothProject/TableCloth/0.5.4/TableClothProject.TableCloth.locale.ko-KR.yaml
  manifests/t/TableClothProject/TableCloth/0.5.4/TableClothProject.TableCloth.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86912 New version: Melvin-Abraham.Google-Assistant version 1.1.0
  manifests/m/Melvin-Abraham/Google-Assistant/1.1.0/Melvin-Abraham.Google-Assistant.installer.yaml
  manifests/m/Melvin-Abraham/Google-Assistant/1.1.0/Melvin-Abraham.Google-Assistant.locale.en-US.yaml
  manifests/m/Melvin-Abraham/Google-Assistant/1.1.0/Melvin-Abraham.Google-Assistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86882 TheDocumentFoundation.LibreOffice version 7.4.2.1
  manifests/t/TheDocumentFoundation/LibreOffice/7.4.2.1/TheDocumentFoundation.LibreOffice.installer.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.4.2.1/TheDocumentFoundation.LibreOffice.locale.en-US.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.4.2.1/TheDocumentFoundation.LibreOffice.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#87018 WiresharkFoundation.Wireshark version 4.0.1.0
  manifests/w/WiresharkFoundation/Wireshark/4.0.1.0/WiresharkFoundation.Wireshark.installer.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.0.1.0/WiresharkFoundation.Wireshark.locale.en-US.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.0.1.0/WiresharkFoundation.Wireshark.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#86790 Add version: Open-Shell.Open-Shell-Menu version 4.4.131 [FP-D]
  manifests/o/Open-Shell/Open-Shell-Menu/4.4.131/Open-Shell.Open-Shell-Menu.installer.yaml
  manifests/o/Open-Shell/Open-Shell-Menu/4.4.131/Open-Shell.Open-Shell-Menu.locale.en-US.yaml
  manifests/o/Open-Shell/Open-Shell-Menu/4.4.131/Open-Shell.Open-Shell-Menu.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#86947 New version: StandardNotes.StandardNotes version 3.23.260 [FP-O]
  manifests/s/StandardNotes/StandardNotes/3.23.260/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.23.260/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.23.260/StandardNotes.StandardNotes.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#86917 Add MarcinOtorowski.MSIXHero.3.0.0.0
  manifests/m/MarcinOtorowski/MSIXHero/3.0.0.0/MarcinOtorowski.MSIXHero.installer.yaml
  manifests/m/MarcinOtorowski/MSIXHero/3.0.0.0/MarcinOtorowski.MSIXHero.locale.de-DE.yaml
  manifests/m/MarcinOtorowski/MSIXHero/3.0.0.0/MarcinOtorowski.MSIXHero.locale.en-US.yaml
  manifests/m/MarcinOtorowski/MSIXHero/3.0.0.0/MarcinOtorowski.MSIXHero.locale.pl-PL.yaml
  manifests/m/MarcinOtorowski/MSIXHero/3.0.0.0/MarcinOtorowski.MSIXHero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86858 New version: AnyDeskSoftwareGmbH.AnyDesk version 7.1.6
  manifests/a/AnyDeskSoftwareGmbH/AnyDesk/7.1.6/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml
  manifests/a/AnyDeskSoftwareGmbH/AnyDesk/7.1.6/AnyDeskSoftwareGmbH.AnyDesk.locale.en-US.yaml
  manifests/a/AnyDeskSoftwareGmbH/AnyDesk/7.1.6/AnyDeskSoftwareGmbH.AnyDesk.locale.zh-CN.yaml
  manifests/a/AnyDeskSoftwareGmbH/AnyDesk/7.1.6/AnyDeskSoftwareGmbH.AnyDesk.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved, Needs-Attention

#86887 TheDocumentFoundation.LibreOffice.HelpPack version 7.4.2.1
  manifests/t/TheDocumentFoundation/LibreOffice/HelpPack/7.4.2.1/TheDocumentFoundation.LibreOffice.HelpPack.installer.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/HelpPack/7.4.2.1/TheDocumentFoundation.LibreOffice.HelpPack.locale.en-US.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/HelpPack/7.4.2.1/TheDocumentFoundation.LibreOffice.HelpPack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-No-Executables

#86925 FinalWire.AIDA64.Extreme version 6.80
  manifests/f/FinalWire/AIDA64/Extreme/6.80/FinalWire.AIDA64.Extreme.installer.yaml
  manifests/f/FinalWire/AIDA64/Extreme/6.80/FinalWire.AIDA64.Extreme.locale.en-US.yaml
  manifests/f/FinalWire/AIDA64/Extreme/6.80/FinalWire.AIDA64.Extreme.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86926 FinalWire.AIDA64.Engineer version 6.80
  manifests/f/FinalWire/AIDA64/Engineer/6.80/FinalWire.AIDA64.Engineer.installer.yaml
  manifests/f/FinalWire/AIDA64/Engineer/6.80/FinalWire.AIDA64.Engineer.locale.en-US.yaml
  manifests/f/FinalWire/AIDA64/Engineer/6.80/FinalWire.AIDA64.Engineer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86934 New version: KeePassXCTeam.KeePassXC version 2.7.4
  manifests/k/KeePassXCTeam/KeePassXC/2.7.4/KeePassXCTeam.KeePassXC.installer.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.4/KeePassXCTeam.KeePassXC.locale.en-US.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.4/KeePassXCTeam.KeePassXC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86939 New version: Lexikos.AutoHotkey version 1.1.35.00
  manifests/l/Lexikos/AutoHotkey/1.1.35.00/Lexikos.AutoHotkey.installer.yaml
  manifests/l/Lexikos/AutoHotkey/1.1.35.00/Lexikos.AutoHotkey.locale.en-US.yaml
  manifests/l/Lexikos/AutoHotkey/1.1.35.00/Lexikos.AutoHotkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86942 Update Zoom.Zoom to version 5.12.9638
  manifests/z/Zoom/Zoom/5.12.9638/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/5.12.9638/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/5.12.9638/Zoom.Zoom.locale.zh-CN.yaml
  manifests/z/Zoom/Zoom/5.12.9638/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86945 New version: c3er.mdview version 2.5.1
  manifests/c/c3er/mdview/2.5.1/c3er.mdview.installer.yaml
  manifests/c/c3er/mdview/2.5.1/c3er.mdview.locale.en-US.yaml
  manifests/c/c3er/mdview/2.5.1/c3er.mdview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87005 NordVPN.NordVPN version 7.1.2.0
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Unattended-Failed

#86950 New version: swiftyapp.swifty version 0.6.7
  manifests/s/swiftyapp/swifty/0.6.7/swiftyapp.swifty.installer.yaml
  manifests/s/swiftyapp/swifty/0.6.7/swiftyapp.swifty.locale.en-US.yaml
  manifests/s/swiftyapp/swifty/0.6.7/swiftyapp.swifty.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86961 Canva.Canva version 1.54.0
  manifests/c/Canva/Canva/1.54.0/Canva.Canva.installer.yaml
  manifests/c/Canva/Canva/1.54.0/Canva.Canva.locale.en-US.yaml
  manifests/c/Canva/Canva/1.54.0/Canva.Canva.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86992 New version: Tencent.WeixinDevTools version 1.06.2210310
  manifests/t/Tencent/WeixinDevTools/1.06.2210310/Tencent.WeixinDevTools.installer.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2210310/Tencent.WeixinDevTools.locale.en-US.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2210310/Tencent.WeixinDevTools.locale.zh-CN.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2210310/Tencent.WeixinDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86993 New version: 360.360SE version 13.1.6290.0
  manifests/3/360/360SE/13.1.6290.0/360.360SE.installer.yaml
  manifests/3/360/360SE/13.1.6290.0/360.360SE.locale.en-US.yaml
  manifests/3/360/360SE/13.1.6290.0/360.360SE.locale.zh-CN.yaml
  manifests/3/360/360SE/13.1.6290.0/360.360SE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86996 Added Microsoft Edge Beta version 107.0.1418.23.
  manifests/m/Microsoft/Edge/Beta/107.0.1418.23/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/107.0.1418.23/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/107.0.1418.23/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87148 New version: Jackett.Jackett version 0.20.2186
  manifests/j/Jackett/Jackett/0.20.2186/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2186/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2186/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87192 Update: OpenJS.NodeJS.Nightly version 20.0.0
  manifests/o/OpenJS/NodeJS/Nightly/20.0.0/OpenJS.NodeJS.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87182 Moved: DigitalScholar.Zotero version 6.0.13
  manifests/d/DigitalScholar/Zotero/6.0.13/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.13/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.13/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.13/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87185 Moved: DigitalScholar.Zotero version 6.0.9
  manifests/d/DigitalScholar/Zotero/6.0.9/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.9/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.9/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.9/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87199 Moved: DigitalScholar.Zotero version 6.0.4
  manifests/d/DigitalScholar/Zotero/6.0.4/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.4/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.4/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.4/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87184 Moved: DigitalScholar.Zotero version 6.0.10
  manifests/d/DigitalScholar/Zotero/6.0.10/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.10/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.10/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.10/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87183 Moved: DigitalScholar.Zotero version 6.0.12
  manifests/d/DigitalScholar/Zotero/6.0.12/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.12/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.12/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.12/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87187 Moved: DigitalScholar.Zotero version 6.0.7
  manifests/d/DigitalScholar/Zotero/6.0.7/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.7/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.7/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.7/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87198 Moved: DigitalScholar.Zotero version 6.0.5
  manifests/d/DigitalScholar/Zotero/6.0.5/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.5/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.5/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.5/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87137 Moved: DigitalScholar.Zotero version 6.0.15
  manifests/d/DigitalScholar/Zotero/6.0.15/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.15/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.15/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.15/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87197 Moved: DigitalScholar.Zotero version 6.0.6
  manifests/d/DigitalScholar/Zotero/6.0.6/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.6/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.6/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.6/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87169 Moving: Zotero.Zotero version 6.0.1
  manifests/z/Zotero/Zotero/6.0.1/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.1/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.1/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87172 Moving: Zotero.Zotero version 6.0.13
  manifests/z/Zotero/Zotero/6.0.13/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.13/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.13/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87171 Moving: Zotero.Zotero version 6.0.12
  manifests/z/Zotero/Zotero/6.0.12/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.12/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.12/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87168 Moving: Zotero.Zotero version 6.0
  manifests/z/Zotero/Zotero/6.0/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87167 Moving: Zotero.Zotero version 5.0.96.3
  manifests/z/Zotero/Zotero/5.0.96.3/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.96.3/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.96.3/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87163 Moving: Zotero.Zotero version 5.0.96.2
  manifests/z/Zotero/Zotero/5.0.96.2/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.96.2/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.96.2/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87164 New version: B3log.SiYuan version 2.4.8
  manifests/b/B3log/SiYuan/2.4.8/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.4.8/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.4.8/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.4.8/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87162 Moving: Zotero.Zotero version 5.0.96
  manifests/z/Zotero/Zotero/5.0.96/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.96/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.96/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87151 Moving: Zotero.Zotero version 5.0.87
  manifests/z/Zotero/Zotero/5.0.87/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.87/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.87/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87200 Moved: DigitalScholar.Zotero version 6.0.3
  manifests/d/DigitalScholar/Zotero/6.0.3/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.3/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.3/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.3/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved

#87207 Moving: tropy.tropy version 1.10.0
  manifests/t/tropy/tropy/1.10.0/tropy.tropy.installer.yaml
  manifests/t/tropy/tropy/1.10.0/tropy.tropy.locale.en-US.yaml
  manifests/t/tropy/tropy/1.10.0/tropy.tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87208 Moving: tropy.tropy version 1.11.0
  manifests/t/tropy/tropy/1.11.0/tropy.tropy.installer.yaml
  manifests/t/tropy/tropy/1.11.0/tropy.tropy.locale.en-US.yaml
  manifests/t/tropy/tropy/1.11.0/tropy.tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87180 Moving: Zotero.Zotero version 6.0.8
  manifests/z/Zotero/Zotero/6.0.8/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.8/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.8/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87179 Moving: Zotero.Zotero version 6.0.7
  manifests/z/Zotero/Zotero/6.0.7/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.7/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.7/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87210 Moving: tropy.tropy version 1.12.0
  manifests/t/tropy/tropy/1.12.0/tropy.tropy.installer.yaml
  manifests/t/tropy/tropy/1.12.0/tropy.tropy.locale.en-US.yaml
  manifests/t/tropy/tropy/1.12.0/tropy.tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87209 Moving: tropy.tropy version 1.11.1
  manifests/t/tropy/tropy/1.11.1/tropy.tropy.installer.yaml
  manifests/t/tropy/tropy/1.11.1/tropy.tropy.locale.en-US.yaml
  manifests/t/tropy/tropy/1.11.1/tropy.tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87211 Moving: tropy.tropy version 1.9.0
  manifests/t/tropy/tropy/1.9.0/tropy.tropy.installer.yaml
  manifests/t/tropy/tropy/1.9.0/tropy.tropy.locale.en-US.yaml
  manifests/t/tropy/tropy/1.9.0/tropy.tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87161 Moving: Zotero.Zotero version 5.0.95.1
  manifests/z/Zotero/Zotero/5.0.95.1/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.95.1/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.95.1/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87212 Moved: DigitalScholar.Zotero version 6.0.1
  manifests/d/DigitalScholar/Zotero/6.0.1/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.1/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.1/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.1/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87176 Moving: Zotero.Zotero version 6.0.4
  manifests/z/Zotero/Zotero/6.0.4/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.4/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.4/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87175 Moving: Zotero.Zotero version 6.0.3
  manifests/z/Zotero/Zotero/6.0.3/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.3/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.3/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87166 New version: B3log.SiYuan version 2.4.9
  manifests/b/B3log/SiYuan/2.4.9/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.4.9/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.4.9/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.4.9/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87160 Moving: Zotero.Zotero version 5.0.95
  manifests/z/Zotero/Zotero/5.0.95/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.95/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.95/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87213 Moved: DigitalScholar.Zotero version 6.0
  manifests/d/DigitalScholar/Zotero/6.0/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87153 Moving: Zotero.Zotero version 5.0.89
  manifests/z/Zotero/Zotero/5.0.89/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.89/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.89/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87181 Moving: Zotero.Zotero version 6.0.9
  manifests/z/Zotero/Zotero/6.0.9/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.9/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.9/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87154 Moving: Zotero.Zotero version 5.0.91
  manifests/z/Zotero/Zotero/5.0.91/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.91/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.91/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87155 Moving: Zotero.Zotero version 5.0.92
  manifests/z/Zotero/Zotero/5.0.92/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.92/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.92/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87174 Moving: Zotero.Zotero version 6.0.2
  manifests/z/Zotero/Zotero/6.0.2/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.2/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.2/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87152 Moving: Zotero.Zotero version 5.0.88
  manifests/z/Zotero/Zotero/5.0.88/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.88/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.88/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87178 Moving: Zotero.Zotero version 6.0.6
  manifests/z/Zotero/Zotero/6.0.6/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.6/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.6/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87156 Moving: Zotero.Zotero version 5.0.93
  manifests/z/Zotero/Zotero/5.0.93/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.93/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.93/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87177 Moving: Zotero.Zotero version 6.0.5
  manifests/z/Zotero/Zotero/6.0.5/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.5/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.5/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87157 New version: Youqu.ToDesk version 4.6.0.1
  manifests/y/Youqu/ToDesk/4.6.0.1/Youqu.ToDesk.installer.yaml
  manifests/y/Youqu/ToDesk/4.6.0.1/Youqu.ToDesk.locale.en-US.yaml
  manifests/y/Youqu/ToDesk/4.6.0.1/Youqu.ToDesk.locale.zh-CN.yaml
  manifests/y/Youqu/ToDesk/4.6.0.1/Youqu.ToDesk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87159 Moving: Zotero.Zotero version 5.0.94
  manifests/z/Zotero/Zotero/5.0.94/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/5.0.94/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/5.0.94/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87108 Update: Aiursoft.Kahla version 4.5.0
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.installer.yaml
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.locale.en-US.yaml
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87150 New version: sprout2000.LeafView version 2.2.9
  manifests/s/sprout2000/LeafView/2.2.9/sprout2000.LeafView.installer.yaml
  manifests/s/sprout2000/LeafView/2.2.9/sprout2000.LeafView.locale.en-US.yaml
  manifests/s/sprout2000/LeafView/2.2.9/sprout2000.LeafView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86994 New version: Sogou.SogouInput version 12.6.0.6630
  manifests/s/Sogou/SogouInput/12.6.0.6630/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/12.6.0.6630/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/12.6.0.6630/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/12.6.0.6630/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#87214 Moved: DigitalScholar.Tropy version 1.12.0
  manifests/d/DigitalScholar/Tropy/1.12.0/DigitalScholar.Tropy.installer.yaml
  manifests/d/DigitalScholar/Tropy/1.12.0/DigitalScholar.Tropy.locale.en-US.yaml
  manifests/d/DigitalScholar/Tropy/1.12.0/DigitalScholar.Tropy.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Tropy/1.12.0/DigitalScholar.Tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87215 Moved: DigitalScholar.Tropy version 1.11.1
  manifests/d/DigitalScholar/Tropy/1.11.1/DigitalScholar.Tropy.installer.yaml
  manifests/d/DigitalScholar/Tropy/1.11.1/DigitalScholar.Tropy.locale.en-US.yaml
  manifests/d/DigitalScholar/Tropy/1.11.1/DigitalScholar.Tropy.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Tropy/1.11.1/DigitalScholar.Tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87217 Moved: DigitalScholar.Tropy version 1.11.0
  manifests/d/DigitalScholar/Tropy/1.11.0/DigitalScholar.Tropy.installer.yaml
  manifests/d/DigitalScholar/Tropy/1.11.0/DigitalScholar.Tropy.locale.en-US.yaml
  manifests/d/DigitalScholar/Tropy/1.11.0/DigitalScholar.Tropy.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Tropy/1.11.0/DigitalScholar.Tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87173 Moving: Zotero.Zotero version 6.0.15
  manifests/z/Zotero/Zotero/6.0.15/Zotero.Zotero.installer.yaml
  manifests/z/Zotero/Zotero/6.0.15/Zotero.Zotero.locale.en-US.yaml
  manifests/z/Zotero/Zotero/6.0.15/Zotero.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87201 Moved: DigitalScholar.Zotero version 6.0.2
  manifests/d/DigitalScholar/Zotero/6.0.2/DigitalScholar.Zotero.installer.yaml
  manifests/d/DigitalScholar/Zotero/6.0.2/DigitalScholar.Zotero.locale.en-US.yaml
  manifests/d/DigitalScholar/Zotero/6.0.2/DigitalScholar.Zotero.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Zotero/6.0.2/DigitalScholar.Zotero.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#87218 Moved: DigitalScholar.Tropy version 1.10.0
  manifests/d/DigitalScholar/Tropy/1.10.0/DigitalScholar.Tropy.installer.yaml
  manifests/d/DigitalScholar/Tropy/1.10.0/DigitalScholar.Tropy.locale.en-US.yaml
  manifests/d/DigitalScholar/Tropy/1.10.0/DigitalScholar.Tropy.locale.zh-CN.yaml
  manifests/d/DigitalScholar/Tropy/1.10.0/DigitalScholar.Tropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86998 New version: Bisq.Bisq version 1.9.6
  manifests/b/Bisq/Bisq/1.9.6/Bisq.Bisq.installer.yaml
  manifests/b/Bisq/Bisq/1.9.6/Bisq.Bisq.locale.en-US.yaml
  manifests/b/Bisq/Bisq/1.9.6/Bisq.Bisq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86999 New version: JetBrains.Rider.EAP version 223.7255.82
  manifests/j/JetBrains/Rider/EAP/223.7255.82/JetBrains.Rider.EAP.installer.yaml
  manifests/j/JetBrains/Rider/EAP/223.7255.82/JetBrains.Rider.EAP.locale.en-US.yaml
  manifests/j/JetBrains/Rider/EAP/223.7255.82/JetBrains.Rider.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87001 Update: KDE.kdevelop version 5.6.2 [FP-O]
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87002 New version: Discord.Discord.Development version 1.0.678 [FP-O]
  manifests/d/Discord/Discord/Development/1.0.678/Discord.Discord.Development.installer.yaml
  manifests/d/Discord/Discord/Development/1.0.678/Discord.Discord.Development.locale.en-US.yaml
  manifests/d/Discord/Discord/Development/1.0.678/Discord.Discord.Development.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87006 New version: Google.AndroidStudio.Beta version 2022.1.1.14
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.14/Google.AndroidStudio.Beta.installer.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.14/Google.AndroidStudio.Beta.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.1.1.14/Google.AndroidStudio.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87007 New version: Google.Chrome.Canary version 109.0.5395.0 [FP-O]
  manifests/g/Google/Chrome/Canary/109.0.5395.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/109.0.5395.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/109.0.5395.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/109.0.5395.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87011 Add Microsoft Build of OpenJDK 17 Oct PSU
  manifests/m/Microsoft/OpenJDK/17/17.0.5.8/Microsoft.OpenJDK.17.installer.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.5.8/Microsoft.OpenJDK.17.locale.en-US.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.5.8/Microsoft.OpenJDK.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87012 New version: foxglove.studio version 1.30.0
  manifests/f/foxglove/studio/1.30.0/foxglove.studio.installer.yaml
  manifests/f/foxglove/studio/1.30.0/foxglove.studio.locale.en-US.yaml
  manifests/f/foxglove/studio/1.30.0/foxglove.studio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87013 Update: KDE.KDEConnect version 22.08.2 [FP-O]
  manifests/k/KDE/KDEConnect/22.08.2/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87017 New version: sprout2000.LeafView version 2.2.7
  manifests/s/sprout2000/LeafView/2.2.7/sprout2000.LeafView.installer.yaml
  manifests/s/sprout2000/LeafView/2.2.7/sprout2000.LeafView.locale.en-US.yaml
  manifests/s/sprout2000/LeafView/2.2.7/sprout2000.LeafView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87020 New version: BornToBeRoot.NETworkManager version 2022.10.31.0
  manifests/b/BornToBeRoot/NETworkManager/2022.10.31.0/BornToBeRoot.NETworkManager.installer.yaml
  manifests/b/BornToBeRoot/NETworkManager/2022.10.31.0/BornToBeRoot.NETworkManager.locale.en-US.yaml
  manifests/b/BornToBeRoot/NETworkManager/2022.10.31.0/BornToBeRoot.NETworkManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87024 New version: vim.vim version 9.0.0822
  manifests/v/vim/vim/9.0.0822/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.0822/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.0822/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87028 Update: KDE.Dolphin version 22.08.2
  manifests/k/KDE/Dolphin/22.08.2/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87044 Ferdium.Ferdium.Nightly version 6.2.1-nightly.35
  manifests/f/Ferdium/Ferdium/Nightly/6.2.1-nightly.35/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.1-nightly.35/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.1-nightly.35/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87046 New version: CondaForge.Miniforge3 version 22.9.0-1
  manifests/c/CondaForge/Miniforge3/22.9.0-1/CondaForge.Miniforge3.installer.yaml
  manifests/c/CondaForge/Miniforge3/22.9.0-1/CondaForge.Miniforge3.locale.en-US.yaml
  manifests/c/CondaForge/Miniforge3/22.9.0-1/CondaForge.Miniforge3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87048 New version: Taozuhong.Kangaroo version 2.0.0.221101
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87050 New version: iQIYI.iQIYI verison 9.10.167.6385
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.installer.yaml
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.locale.en-US.yaml
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.locale.zh-CN.yaml
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.locale.zh-HK.yaml
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.locale.zh-TW.yaml
  manifests/i/iQIYI/iQIYI/9.10.167.6385/iQIYI.iQIYI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87051 Money.Net version 2.0.1.4
  manifests/l/LovettSoftware/MyMoney/Net/2.0.1.4/LovettSoftware.MyMoney.Net.installer.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.1.4/LovettSoftware.MyMoney.Net.locale.en-US.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.1.4/LovettSoftware.MyMoney.Net.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87064 New version: Jellyfin.Server version 10.8.7
  manifests/j/Jellyfin/Server/10.8.7/Jellyfin.Server.installer.yaml
  manifests/j/Jellyfin/Server/10.8.7/Jellyfin.Server.locale.en-US.yaml
  manifests/j/Jellyfin/Server/10.8.7/Jellyfin.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87069 New version: Tencent.EDU version 4.1.2.12 [FP-O]
  manifests/t/Tencent/EDU/4.1.2.12/Tencent.EDU.installer.yaml
  manifests/t/Tencent/EDU/4.1.2.12/Tencent.EDU.locale.en-US.yaml
  manifests/t/Tencent/EDU/4.1.2.12/Tencent.EDU.locale.zh-CN.yaml
  manifests/t/Tencent/EDU/4.1.2.12/Tencent.EDU.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#85164 Modify: Apache.OpenOffice version 4.111.9808
  manifests/a/Apache/OpenOffice/4.111.9808/Apache.OpenOffice.installer.yaml
  manifests/a/Apache/OpenOffice/4.111.9808/Apache.OpenOffice.locale.en-US.yaml
  manifests/a/Apache/OpenOffice/4.111.9808/Apache.OpenOffice.locale.zh-CN.yaml
  manifests/a/Apache/OpenOffice/4.111.9808/Apache.OpenOffice.yaml
Labels: Retry-1, Moderator-Approved, Needs-Author-Feedback, Waived-Validation-Installation-Error, Waived-Validation-Unapproved-URL, Waived-Validation-Unattended-Failed

#87073 DoltHub.Dolt version 0.50.12
  manifests/d/DoltHub/Dolt/0.50.12/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.50.12/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.50.12/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87077 Update LibreWolf.LibreWolf to v106.0.3-1
  manifests/l/LibreWolf/LibreWolf/106.0.3-1/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/106.0.3-1/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/106.0.3-1/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87078 New version: alagrede.znote version 1.7.7
  manifests/a/alagrede/znote/1.7.7/alagrede.znote.installer.yaml
  manifests/a/alagrede/znote/1.7.7/alagrede.znote.locale.en-US.yaml
  manifests/a/alagrede/znote/1.7.7/alagrede.znote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87082 New version: gileli121.windowtop version 5.19.1
  manifests/g/gileli121/windowtop/5.19.1/gileli121.windowtop.installer.yaml
  manifests/g/gileli121/windowtop/5.19.1/gileli121.windowtop.locale.en-US.yaml
  manifests/g/gileli121/windowtop/5.19.1/gileli121.windowtop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87081 New version: FengHe.FocusNote version 2.16.1-678
  manifests/f/FengHe/FocusNote/2.16.1-678/FengHe.FocusNote.installer.yaml
  manifests/f/FengHe/FocusNote/2.16.1-678/FengHe.FocusNote.locale.en-US.yaml
  manifests/f/FengHe/FocusNote/2.16.1-678/FengHe.FocusNote.locale.zh-CN.yaml
  manifests/f/FengHe/FocusNote/2.16.1-678/FengHe.FocusNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87085 New version: Mozilla.Thunderbird.Beta version 107.0b3
  manifests/m/Mozilla/Thunderbird/Beta/107.0b3/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/107.0b3/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/107.0b3/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87086 New version: Wondershare.PDFelement.9 version 9.2.0
  manifests/w/Wondershare/PDFelement/9/9.2.0/Wondershare.PDFelement.9.installer.yaml
  manifests/w/Wondershare/PDFelement/9/9.2.0/Wondershare.PDFelement.9.locale.en-US.yaml
  manifests/w/Wondershare/PDFelement/9/9.2.0/Wondershare.PDFelement.9.locale.zh-CN.yaml
  manifests/w/Wondershare/PDFelement/9/9.2.0/Wondershare.PDFelement.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87058 New version: Principle.Lusun version 1.8.7
  manifests/p/Principle/Lusun/1.8.7/Principle.Lusun.installer.yaml
  manifests/p/Principle/Lusun/1.8.7/Principle.Lusun.locale.en-US.yaml
  manifests/p/Principle/Lusun/1.8.7/Principle.Lusun.locale.zh-CN.yaml
  manifests/p/Principle/Lusun/1.8.7/Principle.Lusun.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87080 New version: Element.Element version 1.11.13
  manifests/e/Element/Element/1.11.13/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.13/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.13/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87008 New version: JetBrains.YouTrack version 22.2.60480
  manifests/j/JetBrains/YouTrack/22.2.60480/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/22.2.60480/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/22.2.60480/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86997 Nelson v0.6.10.2496
  manifests/n/NelsonNumericalSoftware/Nelson/0.6.10.2496/NelsonNumericalSoftware.Nelson.installer.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.6.10.2496/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.6.10.2496/NelsonNumericalSoftware.Nelson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87047 New version: RProject.R version 4.2.2
  manifests/r/RProject/R/4.2.2/RProject.R.installer.yaml
  manifests/r/RProject/R/4.2.2/RProject.R.locale.en-US.yaml
  manifests/r/RProject/R/4.2.2/RProject.R.locale.fr-FR.yaml
  manifests/r/RProject/R/4.2.2/RProject.R.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87088 New version: Logseq.Logseq version 0.8.10
  manifests/l/Logseq/Logseq/0.8.10/Logseq.Logseq.installer.yaml
  manifests/l/Logseq/Logseq/0.8.10/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.8.10/Logseq.Logseq.locale.zh-CN.yaml
  manifests/l/Logseq/Logseq/0.8.10/Logseq.Logseq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87089 Toit.Jaguar version 1.7.4
  manifests/t/Toit/Jaguar/1.7.4/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.7.4/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.7.4/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87090 New version: Iterate.Cyberduck version 8.5.0.38556
  manifests/i/Iterate/Cyberduck/8.5.0.38556/Iterate.Cyberduck.installer.yaml
  manifests/i/Iterate/Cyberduck/8.5.0.38556/Iterate.Cyberduck.locale.en-US.yaml
  manifests/i/Iterate/Cyberduck/8.5.0.38556/Iterate.Cyberduck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87091 New version: Iterate.MountainDuck version 4.12.5.20230
  manifests/i/Iterate/MountainDuck/4.12.5.20230/Iterate.MountainDuck.installer.yaml
  manifests/i/Iterate/MountainDuck/4.12.5.20230/Iterate.MountainDuck.locale.en-US.yaml
  manifests/i/Iterate/MountainDuck/4.12.5.20230/Iterate.MountainDuck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87092 New version: LaurentPRenedeCotret.pandoc-plot version 1.5.5
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.5/LaurentPRenedeCotret.pandoc-plot.installer.yaml
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.5/LaurentPRenedeCotret.pandoc-plot.locale.en-US.yaml
  manifests/l/LaurentPRenedeCotret/pandoc-plot/1.5.5/LaurentPRenedeCotret.pandoc-plot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87094 Delete duplicated manifest of july-psu respin
  manifests/m/Microsoft/OpenJDK/17/17.0.4.1/Microsoft.OpenJDK.17.installer.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.4.1/Microsoft.OpenJDK.17.locale.en-US.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.4.1/Microsoft.OpenJDK.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87097 New version: GyDi.ClashVerge version 1.1.2
  manifests/g/GyDi/ClashVerge/1.1.2/GyDi.ClashVerge.installer.yaml
  manifests/g/GyDi/ClashVerge/1.1.2/GyDi.ClashVerge.locale.en-US.yaml
  manifests/g/GyDi/ClashVerge/1.1.2/GyDi.ClashVerge.locale.zh-CN.yaml
  manifests/g/GyDi/ClashVerge/1.1.2/GyDi.ClashVerge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87098 New version: Joplin.Joplin.Pre-release version 2.9.12
  manifests/j/Joplin/Joplin/Pre-release/2.9.12/Joplin.Joplin.Pre-release.installer.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.9.12/Joplin.Joplin.Pre-release.locale.en-US.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.9.12/Joplin.Joplin.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87101 Update ProcessExplorer to 17.0
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87272 Microsoft.VisualStudioCode_v1.73.0
  manifests/m/Microsoft/VisualStudioCode/1.73.0/Microsoft.VisualStudioCode.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/1.73.0/Microsoft.VisualStudioCode.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/1.73.0/Microsoft.VisualStudioCode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87106 New version: Facebook.Messenger version 167.0.413538549
  manifests/f/Facebook/Messenger/167.0.413538549/Facebook.Messenger.installer.yaml
  manifests/f/Facebook/Messenger/167.0.413538549/Facebook.Messenger.locale.en-US.yaml
  manifests/f/Facebook/Messenger/167.0.413538549/Facebook.Messenger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87112 New version: ExpressLRS.ExpressLRS-Configurator version 1.5.2
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.2/ExpressLRS.ExpressLRS-Configurator.installer.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.2/ExpressLRS.ExpressLRS-Configurator.locale.en-US.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.2/ExpressLRS.ExpressLRS-Configurator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87273 Revert version: TeamViewer.TeamViewer version 15.35.7 -> 15.35.5
  manifests/t/TeamViewer/TeamViewer/15.35.5/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.35.5/TeamViewer.TeamViewer.locale.de-DE.yaml
  manifests/t/TeamViewer/TeamViewer/15.35.5/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.35.5/TeamViewer.TeamViewer.locale.zh-CN.yaml
  manifests/t/TeamViewer/TeamViewer/15.35.5/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87109 New version: RemNote.RemNote version 1.8.50
  manifests/r/RemNote/RemNote/1.8.50/RemNote.RemNote.installer.yaml
  manifests/r/RemNote/RemNote/1.8.50/RemNote.RemNote.locale.en-US.yaml
  manifests/r/RemNote/RemNote/1.8.50/RemNote.RemNote.locale.zh-CN.yaml
  manifests/r/RemNote/RemNote/1.8.50/RemNote.RemNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87115 New version: ZeroTier.ZeroTierOne version 1.10.2
  manifests/z/ZeroTier/ZeroTierOne/1.10.2/ZeroTier.ZeroTierOne.installer.yaml
  manifests/z/ZeroTier/ZeroTierOne/1.10.2/ZeroTier.ZeroTierOne.locale.en-US.yaml
  manifests/z/ZeroTier/ZeroTierOne/1.10.2/ZeroTier.ZeroTierOne.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87116 New version: sprout2000.LeafView version 2.2.8
  manifests/s/sprout2000/LeafView/2.2.8/sprout2000.LeafView.installer.yaml
  manifests/s/sprout2000/LeafView/2.2.8/sprout2000.LeafView.locale.en-US.yaml
  manifests/s/sprout2000/LeafView/2.2.8/sprout2000.LeafView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87117 New version: sprout2000.Elephicon version 2.1.5
  manifests/s/sprout2000/Elephicon/2.1.5/sprout2000.Elephicon.installer.yaml
  manifests/s/sprout2000/Elephicon/2.1.5/sprout2000.Elephicon.locale.en-US.yaml
  manifests/s/sprout2000/Elephicon/2.1.5/sprout2000.Elephicon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#86794 New version: LinwoodCloud.Butterfly version 1.5.1
  manifests/l/LinwoodCloud/Butterfly/1.5.1/LinwoodCloud.Butterfly.installer.yaml
  manifests/l/LinwoodCloud/Butterfly/1.5.1/LinwoodCloud.Butterfly.locale.en-US.yaml
  manifests/l/LinwoodCloud/Butterfly/1.5.1/LinwoodCloud.Butterfly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87267 Microsoft.PowerToys version 0.64.0
  manifests/m/Microsoft/PowerToys/0.64.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.64.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.64.0/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#87093 New version: Google.Chrome.Dev version 109.0.5384.2
  manifests/g/Google/Chrome/Dev/109.0.5384.2/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/109.0.5384.2/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/109.0.5384.2/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/109.0.5384.2/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87118 New Version: LizardByte.Sunshine version 0.15.0
  manifests/l/LizardByte/Sunshine/0.15.0/LizardByte.Sunshine.installer.yaml
  manifests/l/LizardByte/Sunshine/0.15.0/LizardByte.Sunshine.locale.en-US.yaml
  manifests/l/LizardByte/Sunshine/0.15.0/LizardByte.Sunshine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87095 New version: Peppy.Osu! version 2022.1101.0
  manifests/p/Peppy/Osu!/2022.1101.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2022.1101.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2022.1101.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87096 AgileBits.1Password version 8.9.8
  manifests/a/AgileBits/1Password/8.9.8/AgileBits.1Password.installer.yaml
  manifests/a/AgileBits/1Password/8.9.8/AgileBits.1Password.locale.en-US.yaml
  manifests/a/AgileBits/1Password/8.9.8/AgileBits.1Password.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87318 New version: Jackett.Jackett version 0.20.2189
  manifests/j/Jackett/Jackett/0.20.2189/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2189/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2189/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87311 New version: Amazon.AWSCLI version 2.8.8
  manifests/a/Amazon/AWSCLI/2.8.8/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.8.8/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.8.8/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87026 ConnectWise.ConnectWiseManageClient64-bit version 22.2.1
  manifests/c/ConnectWise/ConnectWiseManageClient64-bit/22.2.1/ConnectWise.ConnectWiseManageClient64-bit.installer.yaml
  manifests/c/ConnectWise/ConnectWiseManageClient64-bit/22.2.1/ConnectWise.ConnectWiseManageClient64-bit.locale.en-US.yaml
  manifests/c/ConnectWise/ConnectWiseManageClient64-bit/22.2.1/ConnectWise.ConnectWiseManageClient64-bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#87379 OpenJS.NodeJS 14.7.0 -> OpenJS.NodeJS.14 14.7.0 [Delete Old]
  manifests/o/OpenJS/NodeJS/14.7.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/14.7.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/14.7.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error, Moderator-Approved, Needs-Attention
