Repository microsoft/winget-pkgs, pull requests merged in 2022-03, with the labels that each got.

#49586 New version: Sogou.SogouInput version 11.8.0.5496
  manifests/s/Sogou/SogouInput/11.8.0.5496/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/11.8.0.5496/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/11.8.0.5496/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/11.8.0.5496/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49596 New version: OctopusDeploy.Tentacle version 6.1.1330
  manifests/o/OctopusDeploy/Tentacle/6.1.1330/OctopusDeploy.Tentacle.installer.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.1330/OctopusDeploy.Tentacle.locale.en-US.yaml
  manifests/o/OctopusDeploy/Tentacle/6.1.1330/OctopusDeploy.Tentacle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49646 New version: Google.Chrome.Beta version 99.0.4844.51
  manifests/g/Google/Chrome/Beta/99.0.4844.51/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/99.0.4844.51/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/99.0.4844.51/Google.Chrome.Beta.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Beta/99.0.4844.51/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49664 DoltHub.Dolt version 0.37.2
  manifests/d/DoltHub/Dolt/0.37.2/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.37.2/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.37.2/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49628 Remove: cuiliang.quicker version 1.27.12
  manifests/c/cuiliang/quicker/1.27.12/cuiliang.quicker.installer.yaml
  manifests/c/cuiliang/quicker/1.27.12/cuiliang.quicker.locale.en-US.yaml
  manifests/c/cuiliang/quicker/1.27.12/cuiliang.quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49585 New version: Kiraku.AudioJam version 1.6.1-127
  manifests/k/Kiraku/AudioJam/1.6.1-127/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.6.1-127/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.6.1-127/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.6.1-127/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49660 New version: stromcon.emusak version 2.1.2
  manifests/s/stromcon/emusak/2.1.2/stromcon.emusak.installer.yaml
  manifests/s/stromcon/emusak/2.1.2/stromcon.emusak.locale.en-US.yaml
  manifests/s/stromcon/emusak/2.1.2/stromcon.emusak.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49662 New version: valinet.ExplorerPatcher.Prerelease version 22000.493.42.21
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.493.42.21/valinet.ExplorerPatcher.Prerelease.installer.yaml
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.493.42.21/valinet.ExplorerPatcher.Prerelease.locale.en-US.yaml
  manifests/v/valinet/ExplorerPatcher/Prerelease/22000.493.42.21/valinet.ExplorerPatcher.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49592 New version: B3log.SiYuan version 1.8.5
  manifests/b/B3log/SiYuan/1.8.5/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/1.8.5/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/1.8.5/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/1.8.5/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49641 New version: bornova.numara version 3.11.3
  manifests/b/bornova/numara/3.11.3/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.11.3/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.11.3/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49600 New version: h3poteto.whalebird-desktop version 4.5.2
  manifests/h/h3poteto/whalebird-desktop/4.5.2/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/4.5.2/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/4.5.2/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49503 New version: Tencent.TencentDocs version 2.2.34
  manifests/t/Tencent/TencentDocs/2.2.34/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.2.34/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.2.34/Tencent.TencentDocs.locale.zh-CN.yaml
  manifests/t/Tencent/TencentDocs/2.2.34/Tencent.TencentDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49651 New version: Nevcairiel.LAVFilters version 0.76.1
  manifests/n/Nevcairiel/LAVFilters/0.76.1/Nevcairiel.LAVFilters.installer.yaml
  manifests/n/Nevcairiel/LAVFilters/0.76.1/Nevcairiel.LAVFilters.locale.en-US.yaml
  manifests/n/Nevcairiel/LAVFilters/0.76.1/Nevcairiel.LAVFilters.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49665 Insynchq.Insync version 3.7.2.50318
  manifests/i/Insynchq/Insync/3.7.2.50318/Insynchq.Insync.installer.yaml
  manifests/i/Insynchq/Insync/3.7.2.50318/Insynchq.Insync.locale.en-US.yaml
  manifests/i/Insynchq/Insync/3.7.2.50318/Insynchq.Insync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49652 Microsoft.PowerToys version 0.56.1
  manifests/m/Microsoft/PowerToys/0.56.1/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.56.1/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.56.1/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36138 New version: Microsoft.XMLNotepad version 2.8.0.49
  manifests/m/Microsoft/XMLNotepad/2.8.0.49/Microsoft.XMLNotepad.installer.yaml
  manifests/m/Microsoft/XMLNotepad/2.8.0.49/Microsoft.XMLNotepad.locale.en-US.yaml
  manifests/m/Microsoft/XMLNotepad/2.8.0.49/Microsoft.XMLNotepad.yaml
Labels: Validation-Merge-Conflict, Moderator-Approved

#49667 New version: Balena.BalenaCLI version 13.3.0
  manifests/b/Balena/BalenaCLI/13.3.0/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/13.3.0/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/13.3.0/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49690 New version: ElijahLopez.MusicCaster version 5.2.5
  manifests/e/ElijahLopez/MusicCaster/5.2.5/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.2.5/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.2.5/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49691 2.1.6 removal of old software
  manifests/x/Xanthus58/XansBetterVanilla/2.1.6/Xanthus58.XansBetterVanilla.installer.yaml
  manifests/x/Xanthus58/XansBetterVanilla/2.1.6/Xanthus58.XansBetterVanilla.locale.en-US.yaml
  manifests/x/Xanthus58/XansBetterVanilla/2.1.6/Xanthus58.XansBetterVanilla.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49728 New version: BraveSoftware.BraveBrowser version 99.1.36.108
  manifests/b/BraveSoftware/BraveBrowser/99.1.36.108/BraveSoftware.BraveBrowser.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/99.1.36.108/BraveSoftware.BraveBrowser.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/99.1.36.108/BraveSoftware.BraveBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49706 New version: JetBrains.YouTrack version 22.1.43563
  manifests/j/JetBrains/YouTrack/22.1.43563/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/22.1.43563/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/22.1.43563/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49689 New version: Bilibili.Livehime version 4.15.1.2998
  manifests/b/Bilibili/Livehime/4.15.1.2998/Bilibili.Livehime.installer.yaml
  manifests/b/Bilibili/Livehime/4.15.1.2998/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.15.1.2998/Bilibili.Livehime.locale.zh-CN.yaml
  manifests/b/Bilibili/Livehime/4.15.1.2998/Bilibili.Livehime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49731 Kiwix.WikiMed version 1.9.2.0
  manifests/k/Kiwix/WikiMed/1.9.2.0/Kiwix.WikiMed.installer.yaml
  manifests/k/Kiwix/WikiMed/1.9.2.0/Kiwix.WikiMed.locale.en-GB.yaml
  manifests/k/Kiwix/WikiMed/1.9.2.0/Kiwix.WikiMed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49692 Removes 2.1.5
  manifests/x/Xanthus58/XansBetterVanilla/2.1.5/Xanthus58.XansBetterVanilla.installer.yaml
  manifests/x/Xanthus58/XansBetterVanilla/2.1.5/Xanthus58.XansBetterVanilla.locale.en-US.yaml
  manifests/x/Xanthus58/XansBetterVanilla/2.1.5/Xanthus58.XansBetterVanilla.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46006 Remove Old: JanDeDobbeleer.OhMyPosh version 3.162.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#49695 Update: KDE.Kate version 21.12.2
  manifests/k/KDE/Kate/21.12.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49730 Modify: Logtalk.Logtalk version 3.53.0
  manifests/l/Logtalk/Logtalk/3.53.0/Logtalk.Logtalk.installer.yaml
  manifests/l/Logtalk/Logtalk/3.53.0/Logtalk.Logtalk.locale.en-US.yaml
  manifests/l/Logtalk/Logtalk/3.53.0/Logtalk.Logtalk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49720 New version: electerm.electerm version 1.18.5
  manifests/e/electerm/electerm/1.18.5/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.18.5/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.18.5/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49711 New version: Alibaba.DingTalk version 6.3.25-Release.3019101
  manifests/a/Alibaba/DingTalk/6.3.25-Release.3019101/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/6.3.25-Release.3019101/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/6.3.25-Release.3019101/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/6.3.25-Release.3019101/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49729 New version: InTheLoop.LoopEmail.Beta version 6.19.1-beta.3
  manifests/i/InTheLoop/LoopEmail/Beta/6.19.1-beta.3/InTheLoop.LoopEmail.Beta.installer.yaml
  manifests/i/InTheLoop/LoopEmail/Beta/6.19.1-beta.3/InTheLoop.LoopEmail.Beta.locale.en-US.yaml
  manifests/i/InTheLoop/LoopEmail/Beta/6.19.1-beta.3/InTheLoop.LoopEmail.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49713 JanDeDobbeleer.OhMyPosh version 7.29.0
  manifests/j/JanDeDobbeleer/OhMyPosh/7.29.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.29.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.29.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35221 Remove Old: JanDeDobbeleer.OhMyPosh version 3.169.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#40071 Remove Old: JanDeDobbeleer.OhMyPosh version 3.166.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#40607 Remove Old: JanDeDobbeleer.OhMyPosh version 3.164.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.164.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.164.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.164.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49712 New version: Google.Chrome.Canary version 101.0.4917.0
  manifests/g/Google/Chrome/Canary/101.0.4917.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/101.0.4917.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/101.0.4917.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/101.0.4917.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#25452 Remove Old: JanDeDobbeleer.OhMyPosh version 3.171.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#49732 Kiwix.WikiMed.Electron version 1.9.2-E
  manifests/k/Kiwix/WikiMed/Electron/1.9.2-E/Kiwix.WikiMed.Electron.installer.yaml
  manifests/k/Kiwix/WikiMed/Electron/1.9.2-E/Kiwix.WikiMed.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/WikiMed/Electron/1.9.2-E/Kiwix.WikiMed.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#30250 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.10.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.10.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.10.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#29956 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.12.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.12.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.12.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#29957 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.11.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.11.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.11.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#26989 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.20.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.20.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.20.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Needs-Attention

#22582 Remove Old: JanDeDobbeleer.OhMyPosh version 3.171.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#49719 New version: BraveSoftware.BraveBrowser.Beta version 99.1.37.77
  manifests/b/BraveSoftware/BraveBrowser/Beta/99.1.37.77/BraveSoftware.BraveBrowser.Beta.installer.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/99.1.37.77/BraveSoftware.BraveBrowser.Beta.locale.en-US.yaml
  manifests/b/BraveSoftware/BraveBrowser/Beta/99.1.37.77/BraveSoftware.BraveBrowser.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35222 Remove Old: JanDeDobbeleer.OhMyPosh version 3.168.3
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35223 Remove Old: JanDeDobbeleer.OhMyPosh version 3.168.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#35224 Remove Old: JanDeDobbeleer.OhMyPosh version 3.168.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49725 JanDeDobbeleer.OhMyPosh version 7.30.0
  manifests/j/JanDeDobbeleer/OhMyPosh/7.30.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.30.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.30.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#40609 Remove Old: JanDeDobbeleer.OhMyPosh version 3.181.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#40630 Remove Old: JanDeDobbeleer.OhMyPosh version 3.181.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49726 Architecture & Tags: Eassos.DiskGenius version 5.4.2
  manifests/e/Eassos/DiskGenius/5.4.2/Eassos.DiskGenius.installer.yaml
  manifests/e/Eassos/DiskGenius/5.4.2/Eassos.DiskGenius.locale.en-US.yaml
  manifests/e/Eassos/DiskGenius/5.4.2/Eassos.DiskGenius.locale.zh-CN.yaml
  manifests/e/Eassos/DiskGenius/5.4.2/Eassos.DiskGenius.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46376 Remove Old: JanDeDobbeleer.OhMyPosh version 3.172.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46375 Remove Old: JanDeDobbeleer.OhMyPosh version 3.172.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49727 Modify: hackjutsu.Lepton version 1.10.0
  manifests/h/hackjutsu/Lepton/1.10.0/hackjutsu.Lepton.installer.yaml
  manifests/h/hackjutsu/Lepton/1.10.0/hackjutsu.Lepton.locale.en-US.yaml
  manifests/h/hackjutsu/Lepton/1.10.0/hackjutsu.Lepton.locale.zh-CN.yaml
  manifests/h/hackjutsu/Lepton/1.10.0/hackjutsu.Lepton.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46373 Remove Old: JanDeDobbeleer.OhMyPosh version 3.172.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.172.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35226 Remove Old: JanDeDobbeleer.OhMyPosh version 3.166.3
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.166.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#45079 Remove Old: JanDeDobbeleer.OhMyPosh version 3.176.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.176.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#40117 Remove Old: JanDeDobbeleer.OhMyPosh version 3.181.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.181.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35225 Remove Old: JanDeDobbeleer.OhMyPosh version 3.167.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.167.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.167.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.167.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#49694 Remove Old: JanDeDobbeleer.OhMyPosh version 5.0.0
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#37501 Remove Old: JanDeDobbeleer.OhMyPosh version 4.3.0
  manifests/j/JanDeDobbeleer/OhMyPosh/4.3.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.3.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.3.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35288 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20485 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#35274 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#44898 Remove Old: JanDeDobbeleer.OhMyPosh version 3.177.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.177.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.177.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.177.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35400 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46969 Remove Old: JanDeDobbeleer.OhMyPosh version 3.178.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.178.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.178.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.178.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36948 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#41642 Remove Old: JanDeDobbeleer.OhMyPosh version 3.180.3
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#49487 Remove Old: JanDeDobbeleer.OhMyPosh version 5.1.0
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49350 Remove Old: JanDeDobbeleer.OhMyPosh version 5.1.2
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46378 Remove Old: JanDeDobbeleer.OhMyPosh version 5.10.0
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved

#46377 Remove Old: JanDeDobbeleer.OhMyPosh version 3.171.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.171.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49721 Keboola.KeboolaCLI version 2.3.2
  manifests/k/Keboola/KeboolaCLI/2.3.2/Keboola.KeboolaCLI.installer.yaml
  manifests/k/Keboola/KeboolaCLI/2.3.2/Keboola.KeboolaCLI.locale.en-US.yaml
  manifests/k/Keboola/KeboolaCLI/2.3.2/Keboola.KeboolaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#42519 Remove Old: JanDeDobbeleer.OhMyPosh version 3.180.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#42520 Remove Old: JanDeDobbeleer.OhMyPosh version 3.180.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#35271 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#35275 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.6/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#47726 Remove Old: JanDeDobbeleer.OhMyPosh version 3.168.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.168.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36860 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36409 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.5/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35531 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.4.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.4.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.4.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35529 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#37289 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#29352 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.15.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.15.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.15.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Attention

#36818 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49668 New version: floating.frame version 0.5.0-beta.13
  manifests/f/floating/frame/0.5.0-beta.13/floating.frame.installer.yaml
  manifests/f/floating/frame/0.5.0-beta.13/floating.frame.locale.en-US.yaml
  manifests/f/floating/frame/0.5.0-beta.13/floating.frame.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36510 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36046 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Retry-1, Moderator-Approved

#34077 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.0.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.0.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.0.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49680 New version: Wasmer.Wasmer version 2.2.0
  manifests/w/Wasmer/Wasmer/2.2.0/Wasmer.Wasmer.installer.yaml
  manifests/w/Wasmer/Wasmer/2.2.0/Wasmer.Wasmer.locale.en-US.yaml
  manifests/w/Wasmer/Wasmer/2.2.0/Wasmer.Wasmer.locale.zh-CN.yaml
  manifests/w/Wasmer/Wasmer/2.2.0/Wasmer.Wasmer.yaml
Labels: Possible-Duplicate, Moderator-Approved

#49688 Architecture & Tags: Telerik.Fiddler.Classic version 5.0.20211.51073
  manifests/t/Telerik/Fiddler/Classic/5.0.20211.51073/Telerik.Fiddler.Classic.installer.yaml
  manifests/t/Telerik/Fiddler/Classic/5.0.20211.51073/Telerik.Fiddler.Classic.locale.en-US.yaml
  manifests/t/Telerik/Fiddler/Classic/5.0.20211.51073/Telerik.Fiddler.Classic.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49684 New version: ElijahLopez.MusicCaster version 5.2.4
  manifests/e/ElijahLopez/MusicCaster/5.2.4/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.2.4/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.2.4/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35220 Remove Old: JanDeDobbeleer.OhMyPosh version 3.169.1
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#34603 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#34449 Remove Old: JanDeDobbeleer.OhMyPosh version 3.169.3
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#35219 Remove Old: JanDeDobbeleer.OhMyPosh version 3.169.2
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.169.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#49687 Architecture: Tencent.COSBrowser version 2.8.5
  manifests/t/Tencent/COSBrowser/2.8.5/Tencent.COSBrowser.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#42604 Remove Old: JanDeDobbeleer.OhMyPosh version 3.162.3
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#29226 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.18.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.18.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.18.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#47745 Remove Old: JanDeDobbeleer.OhMyPosh version 3.162.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49462 Remove Old: JanDeDobbeleer.OhMyPosh version 3.159.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.159.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.159.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.159.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#46537 Remove Old: JanDeDobbeleer.OhMyPosh version 3.160.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.160.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.160.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.160.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36902 Remove Old: JanDeDobbeleer.OhMyPosh version 3.161.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.161.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.161.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.161.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#28816 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.19.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.19.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.19.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#45454 Remove Old: JanDeDobbeleer.OhMyPosh version 3.174.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.174.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.174.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.174.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36899 Remove Old: JanDeDobbeleer.OhMyPosh version 3.163.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.163.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.163.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.163.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#36901 Remove Old: JanDeDobbeleer.OhMyPosh version 3.162.4
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#49409 Remove Old: JanDeDobbeleer.OhMyPosh version 5.1.1
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.1.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#37714 Remove Old: JanDeDobbeleer.OhMyPosh version 4.2.0
  manifests/j/JanDeDobbeleer/OhMyPosh/4.2.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.2.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.2.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#49650 Remove Old: JanDeDobbeleer.OhMyPosh version 5.0.1
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.0.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved

#43922 Remove Old: JanDeDobbeleer.OhMyPosh version 3.180.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.180.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36904 Remove Old: JanDeDobbeleer.OhMyPosh version 5.10.1
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.10.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#37240 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.14.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36900 Remove Old: JanDeDobbeleer.OhMyPosh version 3.162.5
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.5/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.5/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.162.5/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#36883 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#45080 Remove Old: JanDeDobbeleer.OhMyPosh version 3.175.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.175.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.175.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.175.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#40072 Remove Old: JanDeDobbeleer.OhMyPosh version 4.0.0
  manifests/j/JanDeDobbeleer/OhMyPosh/4.0.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.0.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.0.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved

#36884 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.15.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.15.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.15.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#27510 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Internal-Error-Webhook

#36412 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20307 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.12.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#45849 Remove Old: JanDeDobbeleer.OhMyPosh version 3.173.0
  manifests/j/JanDeDobbeleer/OhMyPosh/3.173.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.173.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/3.173.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#37275 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.13.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36264 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.16.6/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#36213 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.17.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35472 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.5.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35795 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved

#36155 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.19.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.19.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.19.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35272 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36130 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.2.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20812 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.31.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.31.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.31.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20908 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Validation-Completed, Moderator-Approved

#37976 Remove Old: JanDeDobbeleer.OhMyPosh version 4.1.0
  manifests/j/JanDeDobbeleer/OhMyPosh/4.1.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.1.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/4.1.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35893 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.3.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20819 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.30.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.30.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.30.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Validation-Completed, Moderator-Approved

#20907 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.29.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20868 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.3.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.3.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.3.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20769 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20483 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.7.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved

#35279 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49645 Lenovo.ThinInstaller version 1.3.0039
  manifests/l/Lenovo/ThinInstaller/1.3.0039/Lenovo.ThinInstaller.installer.yaml
  manifests/l/Lenovo/ThinInstaller/1.3.0039/Lenovo.ThinInstaller.locale.en-US.yaml
  manifests/l/Lenovo/ThinInstaller/1.3.0039/Lenovo.ThinInstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35277 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.6.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#36210 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/5.18.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.18.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/5.18.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#21187 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.28.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.28.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.28.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#35249 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.37.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.37.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.37.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#27151 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.2.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#21646 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.27.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.27.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.27.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#49733 New version: Catsxp.Catsxp version 99.2.3.1
  manifests/c/Catsxp/Catsxp/99.2.3.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/99.2.3.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/99.2.3.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/99.2.3.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#20759 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.32.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#21664 Remove old version of JanDeDobbeleer.OhMyPosh
  manifests/j/JanDeDobbeleer/OhMyPosh/6.26.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.26.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/6.26.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
