Repository microsoft/winget-pkgs, pull requests merged in 2022-05, with the labels that each got.

#59299 New version: jerrod-lankford.google-voice-desktop-app version 1.3.0
  manifests/j/jerrod-lankford/google-voice-desktop-app/1.3.0/jerrod-lankford.google-voice-desktop-app.installer.yaml
  manifests/j/jerrod-lankford/google-voice-desktop-app/1.3.0/jerrod-lankford.google-voice-desktop-app.locale.en-US.yaml
  manifests/j/jerrod-lankford/google-voice-desktop-app/1.3.0/jerrod-lankford.google-voice-desktop-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59304 New version: vim.vim version 8.2.4850
  manifests/v/vim/vim/8.2.4850/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.4850/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.4850/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59307 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2074
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2074/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2074/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2074/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59311 JanDeDobbeleer.OhMyPosh version 7.76.0
  manifests/j/JanDeDobbeleer/OhMyPosh/7.76.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.76.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.76.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59308 Update: KDE.Dolphin version 22.04.0
  manifests/k/KDE/Dolphin/22.04.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59310 SmartSoft.SmartFTP version 10.0.2965.0
  manifests/s/SmartSoft/SmartFTP/10.0.2965.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2965.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2965.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59243 New version: CongusBongus.CDogsSDL version 1.3.0 [FP]
  manifests/c/CongusBongus/CDogsSDL/1.3.0/CongusBongus.CDogsSDL.installer.yaml
  manifests/c/CongusBongus/CDogsSDL/1.3.0/CongusBongus.CDogsSDL.locale.en-US.yaml
  manifests/c/CongusBongus/CDogsSDL/1.3.0/CongusBongus.CDogsSDL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59234 New version: naaive.Orange version 0.6.5 [FP]
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.installer.yaml
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.locale.en-US.yaml
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.locale.zh-CN.yaml
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59242 New version: Jackett.Jackett version 0.20.993.0 [FP]
  manifests/j/Jackett/Jackett/0.20.993.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.993.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.993.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59321 Removed non-working manifest for ImageMagick version 7.1.0.29.
  manifests/i/ImageMagick/ImageMagick/7.1.0.29/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.29/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.29/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59322 Removed non-working manifest for ImageMagick version 7.1.0.30.
  manifests/i/ImageMagick/ImageMagick/7.1.0.30/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.30/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.30/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59320 Added ImageMagick version 7.1.0.32.
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59317 Updated Google Chrome Canary to version 103.0.5036.0.
  manifests/g/Google/Chrome/Canary/103.0.5036.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/103.0.5036.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/103.0.5036.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/103.0.5036.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59315 CreativeTechnology.SoundBlasterCommand version 3.5.07.00
  manifests/c/CreativeTechnology/SoundBlasterCommand/3.5.07.00/CreativeTechnology.SoundBlasterCommand.installer.yaml
  manifests/c/CreativeTechnology/SoundBlasterCommand/3.5.07.00/CreativeTechnology.SoundBlasterCommand.locale.en-US.yaml
  manifests/c/CreativeTechnology/SoundBlasterCommand/3.5.07.00/CreativeTechnology.SoundBlasterCommand.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59319 Added dotUltimate version 2022.1.1.
  manifests/j/JetBrains/dotUltimate/2022.1.1/JetBrains.dotUltimate.installer.yaml
  manifests/j/JetBrains/dotUltimate/2022.1.1/JetBrains.dotUltimate.locale.en-US.yaml
  manifests/j/JetBrains/dotUltimate/2022.1.1/JetBrains.dotUltimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59318 Added JetBrains ReSharper version 2022.1.1.
  manifests/j/JetBrains/ReSharper/2022.1.1/JetBrains.ReSharper.installer.yaml
  manifests/j/JetBrains/ReSharper/2022.1.1/JetBrains.ReSharper.locale.en-US.yaml
  manifests/j/JetBrains/ReSharper/2022.1.1/JetBrains.ReSharper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59324 SmartSoft.SmartFTP version 10.0.2966.0
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59326 Updated KDE Connect to version 22.04.0, build 957.
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59338 Kiwix.KiwixJS version 1.9.9.0
  manifests/k/Kiwix/KiwixJS/1.9.9.0/Kiwix.KiwixJS.installer.yaml
  manifests/k/Kiwix/KiwixJS/1.9.9.0/Kiwix.KiwixJS.locale.en-GB.yaml
  manifests/k/Kiwix/KiwixJS/1.9.9.0/Kiwix.KiwixJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59335 Added msix installer: Microsoft.PowerShell version 7.2.3.0
  manifests/m/Microsoft/PowerShell/7.2.3.0/Microsoft.PowerShell.installer.yaml
  manifests/m/Microsoft/PowerShell/7.2.3.0/Microsoft.PowerShell.locale.en-US.yaml
  manifests/m/Microsoft/PowerShell/7.2.3.0/Microsoft.PowerShell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59345 Updated Google Chrome Canary to version 103.0.5038.0.
  manifests/g/Google/Chrome/Canary/103.0.5038.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/103.0.5038.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/103.0.5038.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/103.0.5038.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59347 Added Mozilla Firefox version 100.0.
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/100.0/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59060 New version: OpenWhisperSystems.Signal version 5.41.0 [FP]
  manifests/o/OpenWhisperSystems/Signal/5.41.0/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/5.41.0/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/5.41.0/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59124 New version: maximmax42.CustomRP version 1.14.10 [FP]
  manifests/m/maximmax42/CustomRP/1.14.10/maximmax42.CustomRP.installer.yaml
  manifests/m/maximmax42/CustomRP/1.14.10/maximmax42.CustomRP.locale.en-US.yaml
  manifests/m/maximmax42/CustomRP/1.14.10/maximmax42.CustomRP.locale.ru-RU.yaml
  manifests/m/maximmax42/CustomRP/1.14.10/maximmax42.CustomRP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59201 New version: Jackett.Jackett version 0.20.1001.0 [FP]
  manifests/j/Jackett/Jackett/0.20.1001.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1001.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1001.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59127 Update: KDE.kile version 2.9.93 [FP]
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59348 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2179
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2179/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2179/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2179/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59170 Update: KDE.kdevelop version 5.6.2 [FP]
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59181 Update: KDE.KDEConnect version 22.04.0 [FP]
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.installer.yaml
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.locale.en-US.yaml
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59228 Update: ImageMagick.ImageMagick version 7.1.0.32 [FP]
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.0.32/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#57607 Update: KDE.Dolphin version 22.04.0 [FP]
  manifests/k/KDE/Dolphin/22.04.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59200 New version: joncampbell123.DOSBox-X version 0.83.25 [FP]
  manifests/j/joncampbell123/DOSBox-X/0.83.25/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.25/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/0.83.25/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59198 New version: KaiHeiLa.KaiHeiLa version 0.0.51.2 [FP]
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.installer.yaml
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.locale.en-US.yaml
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.locale.zh-CN.yaml
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59331 PTRTECH.UVtools version 3.4.1
  manifests/p/PTRTECH/UVtools/3.4.1/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.4.1/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.4.1/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58372 New version: SomePythonThings.ElevenClock version 3.5.0 [FP]
  manifests/s/SomePythonThings/ElevenClock/3.5.0/SomePythonThings.ElevenClock.installer.yaml
  manifests/s/SomePythonThings/ElevenClock/3.5.0/SomePythonThings.ElevenClock.locale.en-US.yaml
  manifests/s/SomePythonThings/ElevenClock/3.5.0/SomePythonThings.ElevenClock.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59329 PTRTECH.UVtools version 3.4.0
  manifests/p/PTRTECH/UVtools/3.4.0/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.4.0/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.4.0/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58224 New version: dbeaver.dbeaver version 22.0.4 [FP]
  manifests/d/dbeaver/dbeaver/22.0.4/dbeaver.dbeaver.installer.yaml
  manifests/d/dbeaver/dbeaver/22.0.4/dbeaver.dbeaver.locale.en-US.yaml
  manifests/d/dbeaver/dbeaver/22.0.4/dbeaver.dbeaver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58377 Update: SmartSoft.SmartFTP version 10.0.2966.0 [FP]
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2966.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#58211 New version: vim.vim version 8.2.4853 [FP]
  manifests/v/vim/vim/8.2.4853/vim.vim.installer.yaml
  manifests/v/vim/vim/8.2.4853/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/8.2.4853/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58723 New version: Sandboxie.Classic version 5.55.20 [FP]
  manifests/s/Sandboxie/Classic/5.55.20/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.55.20/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.55.20/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58617 New version: Sandboxie.Plus version 1.0.20 [FP]
  manifests/s/Sandboxie/Plus/1.0.20/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.0.20/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.0.20/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59341 Graebert.ares mechanical.2023 22.0.1140
  manifests/g/Graebert/AresMechanical/2023/22.0.1140/Graebert.AresMechanical.2023.installer.yaml
  manifests/g/Graebert/AresMechanical/2023/22.0.1140/Graebert.AresMechanical.2023.locale.en-US.yaml
  manifests/g/Graebert/AresMechanical/2023/22.0.1140/Graebert.AresMechanical.2023.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58837 Yourkit.JavaProfiler version 2022.3
  manifests/y/Yourkit/JavaProfiler/2022.3.96/Yourkit.JavaProfiler.installer.yaml
  manifests/y/Yourkit/JavaProfiler/2022.3.96/Yourkit.JavaProfiler.locale.en-US.yaml
  manifests/y/Yourkit/JavaProfiler/2022.3.96/Yourkit.JavaProfiler.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59330 MindsetInnovationInc.Enowork version 0.6.1
  manifests/m/MindsetInnovationInc/Enowork/0.6.1/MindsetInnovationInc.Enowork.installer.yaml
  manifests/m/MindsetInnovationInc/Enowork/0.6.1/MindsetInnovationInc.Enowork.locale.en-US.yaml
  manifests/m/MindsetInnovationInc/Enowork/0.6.1/MindsetInnovationInc.Enowork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59337 Submitting Munixo Windows Client 5.0.73
  manifests/n/Novicon/Munixo/Client/5.0.73.15814/Novicon.Munixo.Client.installer.yaml
  manifests/n/Novicon/Munixo/Client/5.0.73.15814/Novicon.Munixo.Client.locale.de-DE.yaml
  manifests/n/Novicon/Munixo/Client/5.0.73.15814/Novicon.Munixo.Client.locale.en-US.yaml
  manifests/n/Novicon/Munixo/Client/5.0.73.15814/Novicon.Munixo.Client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59342 advancedfx.HLAE version 2.130.2
  manifests/a/advancedfx/HLAE/2.130.2/advancedfx.HLAE.installer.yaml
  manifests/a/advancedfx/HLAE/2.130.2/advancedfx.HLAE.locale.en-US.yaml
  manifests/a/advancedfx/HLAE/2.130.2/advancedfx.HLAE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59351 SmartSoft.SmartFTP version 10.0.2967.0
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59054 New version: Peppy.Osu! version 2022.501.0 [FP]
  manifests/p/Peppy/Osu!/2022.501.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2022.501.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2022.501.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59336 Updated Universal Cloud Adapter to Version 0.9.4.0
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.4.0/Mirasoft.AnyVizCloudAdapter.installer.yaml
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.4.0/Mirasoft.AnyVizCloudAdapter.locale.en-US.yaml
  manifests/m/Mirasoft/AnyVizCloudAdapter/0.9.4.0/Mirasoft.AnyVizCloudAdapter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59340 voidtools.Everything.Alpha version 1.5.0.1311
  manifests/v/voidtools/Everything/Alpha/1.5.0.1311/voidtools.Everything.Alpha.installer.yaml
  manifests/v/voidtools/Everything/Alpha/1.5.0.1311/voidtools.Everything.Alpha.locale.en-US.yaml
  manifests/v/voidtools/Everything/Alpha/1.5.0.1311/voidtools.Everything.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59343 Graebert.ares map.2023 22.0.1144
  manifests/g/Graebert/AresMap/2023/22.0.1144/Graebert.AresMap.2023.installer.yaml
  manifests/g/Graebert/AresMap/2023/22.0.1144/Graebert.AresMap.2023.locale.en-US.yaml
  manifests/g/Graebert/AresMap/2023/22.0.1144/Graebert.AresMap.2023.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59346 Submitting Lightburn 1.1.04
  manifests/l/LightburnSoftware/Lightburn/1.1.04/LightburnSoftware.Lightburn.installer.yaml
  manifests/l/LightburnSoftware/Lightburn/1.1.04/LightburnSoftware.Lightburn.locale.en-US.yaml
  manifests/l/LightburnSoftware/Lightburn/1.1.04/LightburnSoftware.Lightburn.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59357 Update: SmartSoft.SmartFTP version 10.0.2967.0
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2967.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59356 New version: Google.Chrome.Canary version 103.0.5039.0
  manifests/g/Google/Chrome/Canary/103.0.5039.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/103.0.5039.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/103.0.5039.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/103.0.5039.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59358 New version: Google.Chrome version 101.0.4951.54
  manifests/g/Google/Chrome/101.0.4951.54/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/101.0.4951.54/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/101.0.4951.54/Google.Chrome.locale.nb-NO.yaml
  manifests/g/Google/Chrome/101.0.4951.54/Google.Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59248 New package: HomeBank.HomeBank version 5.5.5
  manifests/h/HomeBank/HomeBank/5.5.5/HomeBank.HomeBank.installer.yaml
  manifests/h/HomeBank/HomeBank/5.5.5/HomeBank.HomeBank.locale.en-US.yaml
  manifests/h/HomeBank/HomeBank/5.5.5/HomeBank.HomeBank.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-1.8

#59231 New package: EdrawSoft.MindMaster version 9.1.2.177
  manifests/e/EdrawSoft/MindMaster/9.1.2.177/EdrawSoft.MindMaster.installer.yaml
  manifests/e/EdrawSoft/MindMaster/9.1.2.177/EdrawSoft.MindMaster.locale.en-US.yaml
  manifests/e/EdrawSoft/MindMaster/9.1.2.177/EdrawSoft.MindMaster.locale.zh-CN.yaml
  manifests/e/EdrawSoft/MindMaster/9.1.2.177/EdrawSoft.MindMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-1.2

#59048 Add version: TortoiseSVN.TortoiseSVN version 1.14.3.29387
  manifests/t/TortoiseSVN/TortoiseSVN/1.14.29387/TortoiseSVN.TortoiseSVN.installer.yaml
  manifests/t/TortoiseSVN/TortoiseSVN/1.14.29387/TortoiseSVN.TortoiseSVN.locale.en-US.yaml
  manifests/t/TortoiseSVN/TortoiseSVN/1.14.29387/TortoiseSVN.TortoiseSVN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#59042 New package: Wondershare.Mockitt.CN version 1.2.5
  manifests/w/Wondershare/Mockitt/CN/1.2.5/Wondershare.Mockitt.CN.installer.yaml
  manifests/w/Wondershare/Mockitt/CN/1.2.5/Wondershare.Mockitt.CN.locale.en-US.yaml
  manifests/w/Wondershare/Mockitt/CN/1.2.5/Wondershare.Mockitt.CN.locale.zh-CN.yaml
  manifests/w/Wondershare/Mockitt/CN/1.2.5/Wondershare.Mockitt.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#59365 Update: KDE.KDEConnect version 22.04.0
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59369 Update: KDE.Dolphin version 22.04.0
  manifests/k/KDE/Dolphin/22.04.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59366 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59380 Update Netron to 5.7.6
  manifests/l/LutzRoeder/Netron/5.7.6/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.7.6/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.7.6/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59381 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2180
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2180/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2180/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2180/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59382 Microsoft.VisualStudioCode.Insiders_v1.67.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.67.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59428 Oracle.JDK.18 version 18.0.1.1
  manifests/o/Oracle/JDK/18/18.0.1.1/Oracle.JDK.18.installer.yaml
  manifests/o/Oracle/JDK/18/18.0.1.1/Oracle.JDK.18.locale.en-US.yaml
  manifests/o/Oracle/JDK/18/18.0.1.1/Oracle.JDK.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59411 Update: KDE.Kate version 22.04.0
  manifests/k/KDE/Kate/22.04.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59430 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2182
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2182/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2182/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2182/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59402 New version: Google.Chrome.Canary version 103.0.5040.0
  manifests/g/Google/Chrome/Canary/103.0.5040.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/103.0.5040.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/103.0.5040.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/103.0.5040.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59401 New version: floating.frame version 0.5.0-beta.18
  manifests/f/floating/frame/0.5.0-beta.18/floating.frame.installer.yaml
  manifests/f/floating/frame/0.5.0-beta.18/floating.frame.locale.en-US.yaml
  manifests/f/floating/frame/0.5.0-beta.18/floating.frame.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59396 New version: calibre.calibre.portable version 5.42.0.0
  manifests/c/calibre/calibre/portable/5.42.0.0/calibre.calibre.portable.installer.yaml
  manifests/c/calibre/calibre/portable/5.42.0.0/calibre.calibre.portable.locale.en-US.yaml
  manifests/c/calibre/calibre/portable/5.42.0.0/calibre.calibre.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59399 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2181
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59409 New version: Joplin.Joplin.Pre-release version 2.8.6
  manifests/j/Joplin/Joplin/Pre-release/2.8.6/Joplin.Joplin.Pre-release.installer.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.8.6/Joplin.Joplin.Pre-release.locale.en-US.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.8.6/Joplin.Joplin.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59415 New version: msys2.msys2 version 20220503
  manifests/m/msys2/msys2/20220503/msys2.msys2.installer.yaml
  manifests/m/msys2/msys2/20220503/msys2.msys2.locale.en-US.yaml
  manifests/m/msys2/msys2/20220503/msys2.msys2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59425 New version: skyjake.Lagrange version 1.13.0
  manifests/s/skyjake/Lagrange/1.13.0/skyjake.Lagrange.installer.yaml
  manifests/s/skyjake/Lagrange/1.13.0/skyjake.Lagrange.locale.en-US.yaml
  manifests/s/skyjake/Lagrange/1.13.0/skyjake.Lagrange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59387 New version: calibre.calibre version 5.42.0 [FP-D]
  manifests/c/calibre/calibre/5.42.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/5.42.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/5.42.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59407 Update: joncampbell123.DOSBox-X version 0.83.25
  manifests/j/joncampbell123/DOSBox-X/0.83.25/joncampbell123.DOSBox-X.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59403 New version: Hibbiki.Chromium version 101.0.4951.54
  manifests/h/Hibbiki/Chromium/101.0.4951.54/Hibbiki.Chromium.installer.yaml
  manifests/h/Hibbiki/Chromium/101.0.4951.54/Hibbiki.Chromium.locale.en-US.yaml
  manifests/h/Hibbiki/Chromium/101.0.4951.54/Hibbiki.Chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59390 SmartSoft.SmartFTP version 10.0.2968.0
  manifests/s/SmartSoft/SmartFTP/10.0.2968.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2968.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.2968.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59432 New version: LedgerHQ.LedgerLive version 2.41.3
  manifests/l/LedgerHQ/LedgerLive/2.41.3/LedgerHQ.LedgerLive.installer.yaml
  manifests/l/LedgerHQ/LedgerLive/2.41.3/LedgerHQ.LedgerLive.locale.en-US.yaml
  manifests/l/LedgerHQ/LedgerLive/2.41.3/LedgerHQ.LedgerLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59438 BitRecover.AadhaarCardPasswordRemover version 3.0
  manifests/b/BitRecover/AadhaarCardPasswordRemover/3.0/BitRecover.AadhaarCardPasswordRemover.installer.yaml
  manifests/b/BitRecover/AadhaarCardPasswordRemover/3.0/BitRecover.AadhaarCardPasswordRemover.locale.en-US.yaml
  manifests/b/BitRecover/AadhaarCardPasswordRemover/3.0/BitRecover.AadhaarCardPasswordRemover.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59424 Update: Redisant.ZooKeeperAssistant version 1.0.7.5
  manifests/r/Redisant/ZooKeeperAssistant/1.0.7.5/Redisant.ZooKeeperAssistant.installer.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.7.5/Redisant.ZooKeeperAssistant.locale.en-US.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.7.5/Redisant.ZooKeeperAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/ZooKeeperAssistant/1.0.7.5/Redisant.ZooKeeperAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59440 New version: Cryptomator.Cryptomator version 1.6.9
  manifests/c/Cryptomator/Cryptomator/1.6.9/Cryptomator.Cryptomator.installer.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.9/Cryptomator.Cryptomator.locale.en-US.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.9/Cryptomator.Cryptomator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59439 JanDeDobbeleer.OhMyPosh version 7.77.0
  manifests/j/JanDeDobbeleer/OhMyPosh/7.77.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.77.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/7.77.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59368 OrbxSimulationSystems.OrbxCentral version 4.1.42
  manifests/o/OrbxSimulationSystems/OrbxCentral/4.1.42/OrbxSimulationSystems.OrbxCentral.installer.yaml
  manifests/o/OrbxSimulationSystems/OrbxCentral/4.1.42/OrbxSimulationSystems.OrbxCentral.locale.en-US.yaml
  manifests/o/OrbxSimulationSystems/OrbxCentral/4.1.42/OrbxSimulationSystems.OrbxCentral.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59419 Update: Redisant.KafkaAssistant version 1.0.6.3
  manifests/r/Redisant/KafkaAssistant/1.0.6.3/Redisant.KafkaAssistant.installer.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.6.3/Redisant.KafkaAssistant.locale.en-US.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.6.3/Redisant.KafkaAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/KafkaAssistant/1.0.6.3/Redisant.KafkaAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59431 New version: eMClient.eMClient version 9.0.1708
  manifests/e/eMClient/eMClient/9.0.1708.0/eMClient.eMClient.installer.yaml
  manifests/e/eMClient/eMClient/9.0.1708.0/eMClient.eMClient.locale.en-US.yaml
  manifests/e/eMClient/eMClient/9.0.1708.0/eMClient.eMClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59359 Mozilla.Firefox.ESR version 91.9.0
  manifests/m/Mozilla/Firefox/ESR/91.9.0/Mozilla.Firefox.ESR.installer.yaml
  manifests/m/Mozilla/Firefox/ESR/91.9.0/Mozilla.Firefox.ESR.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/ESR/91.9.0/Mozilla.Firefox.ESR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59433 New version: Nextcloud.NextcloudDesktop version 3.5.0
  manifests/n/Nextcloud/NextcloudDesktop/3.5.0.20220502/Nextcloud.NextcloudDesktop.installer.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.5.0.20220502/Nextcloud.NextcloudDesktop.locale.en-US.yaml
  manifests/n/Nextcloud/NextcloudDesktop/3.5.0.20220502/Nextcloud.NextcloudDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59442 Microsoft.VisualStudioCode.Insiders_v1.67.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.67.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59406 New version: JetBrains.MPS version MPS-213.7172.958
  manifests/j/JetBrains/MPS/MPS-213.7172.958/JetBrains.MPS.installer.yaml
  manifests/j/JetBrains/MPS/MPS-213.7172.958/JetBrains.MPS.locale.en-US.yaml
  manifests/j/JetBrains/MPS/MPS-213.7172.958/JetBrains.MPS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#59420 Update: Redisant.LittleTips version 1.0.2.0
  manifests/r/Redisant/LittleTips/1.0.2.0/Redisant.LittleTips.installer.yaml
  manifests/r/Redisant/LittleTips/1.0.2.0/Redisant.LittleTips.locale.en-US.yaml
  manifests/r/Redisant/LittleTips/1.0.2.0/Redisant.LittleTips.locale.zh-CN.yaml
  manifests/r/Redisant/LittleTips/1.0.2.0/Redisant.LittleTips.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59421 Update: Redisant.RedisAssistant version 1.1.5.2
  manifests/r/Redisant/RedisAssistant/1.1.5.2/Redisant.RedisAssistant.installer.yaml
  manifests/r/Redisant/RedisAssistant/1.1.5.2/Redisant.RedisAssistant.locale.en-US.yaml
  manifests/r/Redisant/RedisAssistant/1.1.5.2/Redisant.RedisAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/RedisAssistant/1.1.5.2/Redisant.RedisAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59443 Added Microsoft Build of OpenJDK with Hotspot 17 version 17.0.3.7.
  manifests/m/Microsoft/OpenJDK/17/17.0.3.7/Microsoft.OpenJDK.17.installer.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.3.7/Microsoft.OpenJDK.17.locale.en-US.yaml
  manifests/m/Microsoft/OpenJDK/17/17.0.3.7/Microsoft.OpenJDK.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59418 Update: Redisant.DataAssistant version 1.0.5.0
  manifests/r/Redisant/DataAssistant/1.0.5.0/Redisant.DataAssistant.installer.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.0/Redisant.DataAssistant.locale.en-US.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.0/Redisant.DataAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.0/Redisant.DataAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59416 BitRecover.WindowsLiveMailConverter version 7.5
  manifests/b/BitRecover/WindowsLiveMailConverter/7.5/BitRecover.WindowsLiveMailConverter.installer.yaml
  manifests/b/BitRecover/WindowsLiveMailConverter/7.5/BitRecover.WindowsLiveMailConverter.locale.en-US.yaml
  manifests/b/BitRecover/WindowsLiveMailConverter/7.5/BitRecover.WindowsLiveMailConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59354 CoreyButler.NVMforWindows version 1.1.9
  manifests/c/CoreyButler/NVMforWindows/1.1.9/CoreyButler.NVMforWindows.installer.yaml
  manifests/c/CoreyButler/NVMforWindows/1.1.9/CoreyButler.NVMforWindows.locale.en-US.yaml
  manifests/c/CoreyButler/NVMforWindows/1.1.9/CoreyButler.NVMforWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59246 Update: OpenWhisperSystems.Signal.Beta version 5.42.0-beta.1 [FP]
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59303 New version: mentebinaria.retoolkit version 2022.04
  manifests/m/mentebinaria/retoolkit/2022.04/mentebinaria.retoolkit.installer.yaml
  manifests/m/mentebinaria/retoolkit/2022.04/mentebinaria.retoolkit.locale.en-US.yaml
  manifests/m/mentebinaria/retoolkit/2022.04/mentebinaria.retoolkit.locale.zh-CN.yaml
  manifests/m/mentebinaria/retoolkit/2022.04/mentebinaria.retoolkit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#58988 New package: Nutstore.NutstoreLightApp version 2.0.3
  manifests/n/Nutstore/NutstoreLightApp/2.0.3/Nutstore.NutstoreLightApp.installer.yaml
  manifests/n/Nutstore/NutstoreLightApp/2.0.3/Nutstore.NutstoreLightApp.locale.en-US.yaml
  manifests/n/Nutstore/NutstoreLightApp/2.0.3/Nutstore.NutstoreLightApp.locale.zh-CN.yaml
  manifests/n/Nutstore/NutstoreLightApp/2.0.3/Nutstore.NutstoreLightApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#59446 Insynchq.Insync version 3.7.6.50356
  manifests/i/Insynchq/Insync/3.7.6.50356/Insynchq.Insync.installer.yaml
  manifests/i/Insynchq/Insync/3.7.6.50356/Insynchq.Insync.locale.en-US.yaml
  manifests/i/Insynchq/Insync/3.7.6.50356/Insynchq.Insync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59445 New version: Cryptomator.Cryptomator version 1.6.10
  manifests/c/Cryptomator/Cryptomator/1.6.10/Cryptomator.Cryptomator.installer.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.10/Cryptomator.Cryptomator.locale.en-US.yaml
  manifests/c/Cryptomator/Cryptomator/1.6.10/Cryptomator.Cryptomator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59453 New version: JFrog.Conan version 1.48.0
  manifests/j/JFrog/Conan/1.48.0/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/1.48.0/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/1.48.0/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59455 New version: skyjake.Lagrange version 1.13.2
  manifests/s/skyjake/Lagrange/1.13.2/skyjake.Lagrange.installer.yaml
  manifests/s/skyjake/Lagrange/1.13.2/skyjake.Lagrange.locale.en-US.yaml
  manifests/s/skyjake/Lagrange/1.13.2/skyjake.Lagrange.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59454 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59457 New version: Waterfox.Waterfox version G4.1.2
  manifests/w/Waterfox/Waterfox/G4.1.2/Waterfox.Waterfox.installer.yaml
  manifests/w/Waterfox/Waterfox/G4.1.2/Waterfox.Waterfox.locale.en-US.yaml
  manifests/w/Waterfox/Waterfox/G4.1.2/Waterfox.Waterfox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59448 Microsoft.PowerToys version 0.58.0
  manifests/m/Microsoft/PowerToys/0.58.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.58.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.58.0/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59183 upload Zheguisoft.zg_print version:6.2.0.5
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.installer.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.locale.en-US.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.locale.zh-CN.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Merge-Conflict, Moderator-Approved, Waived-Policy-Test-1.2

#59452 New version: h3poteto.whalebird-desktop version 4.6.0-beta.1
  manifests/h/h3poteto/whalebird-desktop/4.6.0-beta.1/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/4.6.0-beta.1/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/4.6.0-beta.1/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59451 New version: Canonical.Multipass version 1.9.0
  manifests/c/Canonical/Multipass/1.9.0+win/Canonical.Multipass.installer.yaml
  manifests/c/Canonical/Multipass/1.9.0+win/Canonical.Multipass.locale.en-US.yaml
  manifests/c/Canonical/Multipass/1.9.0+win/Canonical.Multipass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59383 Streamlink.Streamlink version 4.0.0
  manifests/s/Streamlink/Streamlink/4.0.0-1/Streamlink.Streamlink.installer.yaml
  manifests/s/Streamlink/Streamlink/4.0.0-1/Streamlink.Streamlink.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/4.0.0-1/Streamlink.Streamlink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59323 NickeManarin.ScreenToGif - Version 2.37
  manifests/n/NickeManarin/ScreenToGif/2.37/NickeManarin.ScreenToGif.installer.yaml
  manifests/n/NickeManarin/ScreenToGif/2.37/NickeManarin.ScreenToGif.locale.en-US.yaml
  manifests/n/NickeManarin/ScreenToGif/2.37/NickeManarin.ScreenToGif.locale.pt-BR.yaml
  manifests/n/NickeManarin/ScreenToGif/2.37/NickeManarin.ScreenToGif.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59456 New version: UMEZAWATakeshi.UtvideoCodecSuite version utvideo-23.0.1
  manifests/u/UMEZAWATakeshi/UtvideoCodecSuite/23.0.1/UMEZAWATakeshi.UtvideoCodecSuite.installer.yaml
  manifests/u/UMEZAWATakeshi/UtvideoCodecSuite/23.0.1/UMEZAWATakeshi.UtvideoCodecSuite.locale.en-US.yaml
  manifests/u/UMEZAWATakeshi/UtvideoCodecSuite/23.0.1/UMEZAWATakeshi.UtvideoCodecSuite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59460 Add ProductCode for BraveSoftware.BraveBrowser
  manifests/b/BraveSoftware/BraveBrowser/100.1.37.107/BraveSoftware.BraveBrowser.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59461 New version: HearthSim.HearthstoneDeckTracker version 1.17.14
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.14/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.14/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.17.14/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59459 Added ARP entries for Windows SDK version 10.0.22000.194.
  manifests/m/Microsoft/WindowsSDK/10.0.22000.194/Microsoft.WindowsSDK.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10.0.22000.194/Microsoft.WindowsSDK.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10.0.22000.194/Microsoft.WindowsSDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59464 Added ARP entries for Windows Assessment and Deployment Kit version 10.1.22000.1.
  manifests/m/Microsoft/WindowsADK/10.1.22000.1/Microsoft.WindowsADK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59449 New version: Google.Chrome.Canary version 103.0.5041.0 [FP-D]
  manifests/g/Google/Chrome/Canary/103.0.5041.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/103.0.5041.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/103.0.5041.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/103.0.5041.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#59468 Remove CiderCollective.Cider.Nightly version 1.4.5-alpha.2181
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2181/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59470 Remove CiderCollective.Cider.Nightly version 1.4.5-alpha.1916
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.1916/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.1916/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.1916/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59474 Remove LutzRoeder.Netron version 5.7.3
  manifests/l/LutzRoeder/Netron/5.7.3/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.7.3/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.7.3/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59469 Remove CiderCollective.Cider.Nightly version 1.4.5-alpha.2113
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2113/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59472 Remove Peppy.Osu! version 2022.418.0
  manifests/p/Peppy/Osu!/2022.418.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2022.418.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2022.418.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59475 Remove LutzRoeder.Netron version 5.7.2
  manifests/l/LutzRoeder/Netron/5.7.2/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/5.7.2/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/5.7.2/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59471 Remove Peppy.Osu! version 2022.424.1
  manifests/p/Peppy/Osu!/2022.424.1/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2022.424.1/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2022.424.1/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59466 New version: Prey.Prey version 1.9.24
  manifests/p/Prey/Prey/1.9.24/Prey.Prey.installer.yaml
  manifests/p/Prey/Prey/1.9.24/Prey.Prey.locale.en-US.yaml
  manifests/p/Prey/Prey/1.9.24/Prey.Prey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59473 New version: NordPassTeam.NordPass version 4.22.22
  manifests/n/NordPassTeam/NordPass/4.22.22/NordPassTeam.NordPass.installer.yaml
  manifests/n/NordPassTeam/NordPass/4.22.22/NordPassTeam.NordPass.locale.en-US.yaml
  manifests/n/NordPassTeam/NordPass/4.22.22/NordPassTeam.NordPass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59486 Remove: PeakstarTechnologies.AtlasVPN version 2.3.0.0
  manifests/p/PeakstarTechnologies/AtlasVPN/2.3.0.0/PeakstarTechnologies.AtlasVPN.installer.yaml
  manifests/p/PeakstarTechnologies/AtlasVPN/2.3.0.0/PeakstarTechnologies.AtlasVPN.locale.en-US.yaml
  manifests/p/PeakstarTechnologies/AtlasVPN/2.3.0.0/PeakstarTechnologies.AtlasVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59484 New version: EFF.Certbot version 1.27.0
  manifests/e/EFF/Certbot/1.27.0/EFF.Certbot.installer.yaml
  manifests/e/EFF/Certbot/1.27.0/EFF.Certbot.locale.en-US.yaml
  manifests/e/EFF/Certbot/1.27.0/EFF.Certbot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59483 New version: Guilded.Guilded version 1.0.9134613-release
  manifests/g/Guilded/Guilded/1.0.9134613-release/Guilded.Guilded.installer.yaml
  manifests/g/Guilded/Guilded/1.0.9134613-release/Guilded.Guilded.locale.en-US.yaml
  manifests/g/Guilded/Guilded/1.0.9134613-release/Guilded.Guilded.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59485 New version: Microsoft.AzureStorageExplorer version 1.24.0
  manifests/m/Microsoft/AzureStorageExplorer/1.24.0/Microsoft.AzureStorageExplorer.installer.yaml
  manifests/m/Microsoft/AzureStorageExplorer/1.24.0/Microsoft.AzureStorageExplorer.locale.en-US.yaml
  manifests/m/Microsoft/AzureStorageExplorer/1.24.0/Microsoft.AzureStorageExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59477 fixing rammichael.7+TaskbarTweaker installer URL has been declared as phishing URL by cloudflare
  manifests/r/rammichael/7+TaskbarTweaker/5.12.3/rammichael.7+TaskbarTweaker.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#59498 New version: Amazon.SAM-CLI version 1.48.0
  manifests/a/Amazon/SAM-CLI/1.48.0/Amazon.SAM-CLI.installer.yaml
  manifests/a/Amazon/SAM-CLI/1.48.0/Amazon.SAM-CLI.locale.en-US.yaml
  manifests/a/Amazon/SAM-CLI/1.48.0/Amazon.SAM-CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59499 New version: CiderCollective.Cider.Nightly version 1.4.5-alpha.2183
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2183/CiderCollective.Cider.Nightly.installer.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2183/CiderCollective.Cider.Nightly.locale.en-US.yaml
  manifests/c/CiderCollective/Cider/Nightly/1.4.5-alpha.2183/CiderCollective.Cider.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59500 Update: KDE.Dolphin version 22.04.0
  manifests/k/KDE/Dolphin/22.04.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59501 Update: KDE.KDEConnect version 22.04.0
  manifests/k/KDE/KDEConnect/22.04.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59502 Update: KDE.kile version 2.9.93
  manifests/k/KDE/kile/2.9.93/KDE.kile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59490 HiroSystems.Clarinet version 0.29.1
  manifests/h/HiroSystems/Clarinet/0.29.1/HiroSystems.Clarinet.installer.yaml
  manifests/h/HiroSystems/Clarinet/0.29.1/HiroSystems.Clarinet.locale.en-US.yaml
  manifests/h/HiroSystems/Clarinet/0.29.1/HiroSystems.Clarinet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59503 Microsoft.VisualStudioCode.Insiders_v1.67.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.67.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59522 ReleaseNotes: naaive.Orange version 0.6.5
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.locale.en-US.yaml
  manifests/n/naaive/Orange/0.6.5/naaive.Orange.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59523 ReleaseNotes: KaiHeiLa.KaiHeiLa version 0.0.51.2
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.locale.en-US.yaml
  manifests/k/KaiHeiLa/KaiHeiLa/0.0.51.2/KaiHeiLa.KaiHeiLa.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59525 ReleaseNotes: TominLab.WonderPen version 2.1.3
  manifests/t/TominLab/WonderPen/2.1.3/TominLab.WonderPen.installer.yaml
  manifests/t/TominLab/WonderPen/2.1.3/TominLab.WonderPen.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59510 Money.Net version 2.0.0.5
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.5/LovettSoftware.MyMoney.Net.installer.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.5/LovettSoftware.MyMoney.Net.locale.en-US.yaml
  manifests/l/LovettSoftware/MyMoney/Net/2.0.0.5/LovettSoftware.MyMoney.Net.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59513 Update: KDE.Kate version 22.04.0
  manifests/k/KDE/Kate/22.04.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59512 New version: Jackett.Jackett version 0.20.1008.0
  manifests/j/Jackett/Jackett/0.20.1008.0/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.1008.0/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.1008.0/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59489 Nushell.Nushell version 0.62.0
  manifests/n/Nushell/Nushell/0.62.0/Nushell.Nushell.installer.yaml
  manifests/n/Nushell/Nushell/0.62.0/Nushell.Nushell.locale.en-US.yaml
  manifests/n/Nushell/Nushell/0.62.0/Nushell.Nushell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59524 ReleaseNotes: XMind.XMind version 12.0.2
  manifests/x/XMind/XMind/12.0.2/XMind.XMind.installer.yaml
  manifests/x/XMind/XMind/12.0.2/XMind.XMind.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59530 New version: Mozilla.Thunderbird version 91.9.0
  manifests/m/Mozilla/Thunderbird/91.9.0/Mozilla.Thunderbird.installer.yaml
  manifests/m/Mozilla/Thunderbird/91.9.0/Mozilla.Thunderbird.locale.de-DE.yaml
  manifests/m/Mozilla/Thunderbird/91.9.0/Mozilla.Thunderbird.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/91.9.0/Mozilla.Thunderbird.locale.es-ES.yaml
  manifests/m/Mozilla/Thunderbird/91.9.0/Mozilla.Thunderbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59533 Microsoft.VisualStudioCode.Insiders_v1.67.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.67.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#59544 New version: Amazon.AWSCLI version 2.6.2.0
  manifests/a/Amazon/AWSCLI/2.6.2.0/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.6.2.0/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.6.2.0/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
