Repository microsoft/winget-pkgs, pull requests merged in 2023-01, with the labels that each got.

#92697 Modify: CentStudio.CentBrowser version 5.0.1002.295
  manifests/c/CentStudio/CentBrowser/5.0.1002.295/CentStudio.CentBrowser.installer.yaml
  manifests/c/CentStudio/CentBrowser/5.0.1002.295/CentStudio.CentBrowser.locale.en-US.yaml
  manifests/c/CentStudio/CentBrowser/5.0.1002.295/CentStudio.CentBrowser.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92694 New version: vim.vim version 9.0.1122
  manifests/v/vim/vim/9.0.1122/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1122/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1122/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92653 Modify: Cube.CubePlatform version 3.7.5.1
  manifests/c/Cube/CubePlatform/3.7.5.1/Cube.CubePlatform.installer.yaml
  manifests/c/Cube/CubePlatform/3.7.5.1/Cube.CubePlatform.locale.zh-CN.yaml
  manifests/c/Cube/CubePlatform/3.7.5.1/Cube.CubePlatform.locale.zh-HK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92662 NirSoft.AdvancedRun version 1.51
  manifests/n/NirSoft/AdvancedRun/1.51/NirSoft.AdvancedRun.installer.yaml
  manifests/n/NirSoft/AdvancedRun/1.51/NirSoft.AdvancedRun.locale.en-US.yaml
  manifests/n/NirSoft/AdvancedRun/1.51/NirSoft.AdvancedRun.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92681 Synology.DriveClient version 7.2.1.13271
  manifests/s/Synology/DriveClient/7.2.1.13271/Synology.DriveClient.installer.yaml
  manifests/s/Synology/DriveClient/7.2.1.13271/Synology.DriveClient.locale.en-US.yaml
  manifests/s/Synology/DriveClient/7.2.1.13271/Synology.DriveClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92676 New version: Joplin.Joplin.Pre-release version 2.10.3
  manifests/j/Joplin/Joplin/Pre-release/2.10.3/Joplin.Joplin.Pre-release.installer.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.10.3/Joplin.Joplin.Pre-release.locale.en-US.yaml
  manifests/j/Joplin/Joplin/Pre-release/2.10.3/Joplin.Joplin.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92677 New version: RandomEngy.VidCoder.Beta version 8.14
  manifests/r/RandomEngy/VidCoder/Beta/8.14/RandomEngy.VidCoder.Beta.installer.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.14/RandomEngy.VidCoder.Beta.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.14/RandomEngy.VidCoder.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92679 New version: Sandboxie.Classic version 5.61.4
  manifests/s/Sandboxie/Classic/5.61.4/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.61.4/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.61.4/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92680 New version: Sandboxie.Plus version 1.6.4
  manifests/s/Sandboxie/Plus/1.6.4/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.6.4/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.6.4/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92686 Update: KDE.KDEConnect version 22.12.0
  manifests/k/KDE/KDEConnect/22.12.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92692 New version: ThaUnknown.Miru version 3.5.2
  manifests/t/ThaUnknown/Miru/3.5.2/ThaUnknown.Miru.installer.yaml
  manifests/t/ThaUnknown/Miru/3.5.2/ThaUnknown.Miru.locale.en-US.yaml
  manifests/t/ThaUnknown/Miru/3.5.2/ThaUnknown.Miru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92693 Update: KDE.Dolphin version 22.12.0
  manifests/k/KDE/Dolphin/22.12.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92699 New version: Clement.bottom version 0.7.0
  manifests/c/Clement/bottom/0.7.0/Clement.bottom.installer.yaml
  manifests/c/Clement/bottom/0.7.0/Clement.bottom.locale.en-US.yaml
  manifests/c/Clement/bottom/0.7.0/Clement.bottom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92702 Update: KDE.Kate version 22.12.0
  manifests/k/KDE/Kate/22.12.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92703 New version: Jackett.Jackett version 0.20.2465
  manifests/j/Jackett/Jackett/0.20.2465/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2465/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2465/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92705 New version: Tauri.create-tauri-app version 2.7.5
  manifests/t/Tauri/create-tauri-app/2.7.5/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/2.7.5/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/2.7.5/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/2.7.5/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92706 New version: lyswhut.lx-music-desktop version 2.0.0
  manifests/l/lyswhut/lx-music-desktop/2.0.0/lyswhut.lx-music-desktop.installer.yaml
  manifests/l/lyswhut/lx-music-desktop/2.0.0/lyswhut.lx-music-desktop.locale.en-US.yaml
  manifests/l/lyswhut/lx-music-desktop/2.0.0/lyswhut.lx-music-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92707 New version: Tencent.TencentMeeting version 3.13.5.459
  manifests/t/Tencent/TencentMeeting/3.13.5.459/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.13.5.459/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.13.5.459/Tencent.TencentMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeeting/3.13.5.459/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92709 New version: Cocos.CocosDashboard version 1.2.3.2913
  manifests/c/Cocos/CocosDashboard/1.2.3.2913/Cocos.CocosDashboard.installer.yaml
  manifests/c/Cocos/CocosDashboard/1.2.3.2913/Cocos.CocosDashboard.locale.en-US.yaml
  manifests/c/Cocos/CocosDashboard/1.2.3.2913/Cocos.CocosDashboard.locale.zh-CN.yaml
  manifests/c/Cocos/CocosDashboard/1.2.3.2913/Cocos.CocosDashboard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92712 New version: Vercel.Hyper version 3.4.0
  manifests/v/Vercel/Hyper/3.4.0/Vercel.Hyper.installer.yaml
  manifests/v/Vercel/Hyper/3.4.0/Vercel.Hyper.locale.en-US.yaml
  manifests/v/Vercel/Hyper/3.4.0/Vercel.Hyper.locale.zh-CN.yaml
  manifests/v/Vercel/Hyper/3.4.0/Vercel.Hyper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92687 PTRTECH.UVtools version 3.9.5
  manifests/p/PTRTECH/UVtools/3.9.5/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.9.5/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.9.5/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92700 Update: KDE.Kdenlive version 22.12.0
  manifests/k/KDE/Kdenlive/22.12.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92701 Update: KDE.Okular version 22.12.0
  manifests/k/KDE/Okular/22.12.0/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92710 New version: alagrede.znote version 2.0.0
  manifests/a/alagrede/znote/2.0.0/alagrede.znote.installer.yaml
  manifests/a/alagrede/znote/2.0.0/alagrede.znote.locale.en-US.yaml
  manifests/a/alagrede/znote/2.0.0/alagrede.znote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92713 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92663 Fix some manifest fields for Rime.weasel
  manifests/r/Rime/Weasel/0.14.3/Rime.Weasel.installer.yaml
  manifests/r/Rime/Weasel/0.14.3/Rime.Weasel.locale.zh-Hant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92691 sylikc.JPEGView version 1.1.41
  manifests/s/sylikc/JPEGView/1.1.41/sylikc.JPEGView.installer.yaml
  manifests/s/sylikc/JPEGView/1.1.41/sylikc.JPEGView.locale.en-US.yaml
  manifests/s/sylikc/JPEGView/1.1.41/sylikc.JPEGView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92685 New version: Google.Chrome.Canary version 111.0.5512.0 [FP-O]
  manifests/g/Google/Chrome/Canary/111.0.5512.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/111.0.5512.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/111.0.5512.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/111.0.5512.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92720 New version: RuneLite.RuneLite version 2.6.0
  manifests/r/RuneLite/RuneLite/2.6.0/RuneLite.RuneLite.installer.yaml
  manifests/r/RuneLite/RuneLite/2.6.0/RuneLite.RuneLite.locale.en-US.yaml
  manifests/r/RuneLite/RuneLite/2.6.0/RuneLite.RuneLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92723 Update: KDE.KDEConnect version 22.12.0
  manifests/k/KDE/KDEConnect/22.12.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92724 New version: UniversalMediaServer.UniversalMediaServer version 13.0.1
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.0.1/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.0.1/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.0.1/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92728 Update: KDE.Dolphin version 22.12.0
  manifests/k/KDE/Dolphin/22.12.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92730 New version: ThaUnknown.Miru version 3.5.3
  manifests/t/ThaUnknown/Miru/3.5.3/ThaUnknown.Miru.installer.yaml
  manifests/t/ThaUnknown/Miru/3.5.3/ThaUnknown.Miru.locale.en-US.yaml
  manifests/t/ThaUnknown/Miru/3.5.3/ThaUnknown.Miru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92732 Update: KDE.Kdenlive version 22.12.0
  manifests/k/KDE/Kdenlive/22.12.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92733 Update: KDE.Okular version 22.12.0
  manifests/k/KDE/Okular/22.12.0/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92734 Update: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92736 Update: KDE.Kate version 22.12.0
  manifests/k/KDE/Kate/22.12.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92673 New version: Cencit.BAS21 1.7.1
  manifests/c/Cencit/BAS21/1.7.1/Cencit.BAS21.installer.yaml
  manifests/c/Cencit/BAS21/1.7.1/Cencit.BAS21.locale.en-US.yaml
  manifests/c/Cencit/BAS21/1.7.1/Cencit.BAS21.locale.nb-NO.yaml
  manifests/c/Cencit/BAS21/1.7.1/Cencit.BAS21.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92714 New version: RigsofRods.RigsofRods version 2022.12
  manifests/r/RigsofRods/RigsofRods/2022.12/RigsofRods.RigsofRods.installer.yaml
  manifests/r/RigsofRods/RigsofRods/2022.12/RigsofRods.RigsofRods.locale.en-US.yaml
  manifests/r/RigsofRods/RigsofRods/2022.12/RigsofRods.RigsofRods.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92729 New version: vim.vim version 9.0.1128
  manifests/v/vim/vim/9.0.1128/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1128/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1128/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92722 New version: Google.Chrome.Canary version 111.0.5513.0
  manifests/g/Google/Chrome/Canary/111.0.5513.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/111.0.5513.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/111.0.5513.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/111.0.5513.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92766 JanDeDobbeleer.OhMyPosh version 12.34.4
  manifests/j/JanDeDobbeleer/OhMyPosh/12.34.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.34.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.34.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92626 Bonnefon.glogg version 1.1.4
  manifests/b/Bonnefon/glogg/1.1.4/Bonnefon.glogg.installer.yaml
  manifests/b/Bonnefon/glogg/1.1.4/Bonnefon.glogg.locale.en-US.yaml
  manifests/b/Bonnefon/glogg/1.1.4/Bonnefon.glogg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92759 Hash mismatch: dbeaver.dbeaver 22.3.1
  manifests/d/dbeaver/dbeaver/22.3.1/dbeaver.dbeaver.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92762 Getscreenme.Dashboard.Beta 1.0.16
  manifests/g/Getscreenme/Dashboard/Beta/1.0.16/Getscreenme.Dashboard.Beta.installer.yaml
  manifests/g/Getscreenme/Dashboard/Beta/1.0.16/Getscreenme.Dashboard.Beta.locale.en-US.yaml
  manifests/g/Getscreenme/Dashboard/Beta/1.0.16/Getscreenme.Dashboard.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92717 Git.Git version 2.39.0.2
  manifests/g/Git/Git/2.39.0.2/Git.Git.installer.yaml
  manifests/g/Git/Git/2.39.0.2/Git.Git.locale.en-US.yaml
  manifests/g/Git/Git/2.39.0.2/Git.Git.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92805 New version: Jackett.Jackett version 0.20.2469
  manifests/j/Jackett/Jackett/0.20.2469/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2469/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2469/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92804 Ferdium.Ferdium.Nightly version 6.2.4-nightly.3
  manifests/f/Ferdium/Ferdium/Nightly/6.2.4-nightly.3/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.4-nightly.3/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.4-nightly.3/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92803 Update: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92802 Update: KDE.Okular version 22.12.0
  manifests/k/KDE/Okular/22.12.0/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92801 Update: KDE.Kdenlive version 22.12.0
  manifests/k/KDE/Kdenlive/22.12.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92807 Phoner.PhonerLite version 3.13
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92799 New version: Alibaba.QuarkCloudDrive version 2.5.4
  manifests/a/Alibaba/QuarkCloudDrive/2.5.4/Alibaba.QuarkCloudDrive.installer.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.4/Alibaba.QuarkCloudDrive.locale.en-US.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.4/Alibaba.QuarkCloudDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.4/Alibaba.QuarkCloudDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92795 New version: Foundry376.Mailspring version 1.10.8
  manifests/f/Foundry376/Mailspring/1.10.8/Foundry376.Mailspring.installer.yaml
  manifests/f/Foundry376/Mailspring/1.10.8/Foundry376.Mailspring.locale.en-US.yaml
  manifests/f/Foundry376/Mailspring/1.10.8/Foundry376.Mailspring.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92808 Update: KDE.Kate version 22.12.0
  manifests/k/KDE/Kate/22.12.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92792 Update: Kamyroll.Kamyroll-Tauri version 1.0.4
  manifests/k/Kamyroll/Kamyroll-Tauri/1.0.4/Kamyroll.Kamyroll-Tauri.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92789 PTRTECH.UVtools version 3.10.0
  manifests/p/PTRTECH/UVtools/3.10.0/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.10.0/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.10.0/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92788 Update Netron to 6.3.8
  manifests/l/LutzRoeder/Netron/6.3.8/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/6.3.8/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/6.3.8/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92787 New version: vim.vim version 9.0.1136
  manifests/v/vim/vim/9.0.1136/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1136/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1136/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92786 Update: KDE.Dolphin version 22.12.0
  manifests/k/KDE/Dolphin/22.12.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92751 ReleaseNotes: MoritzBunkus.MKVToolNix version 72.0.0
  manifests/m/MoritzBunkus/MKVToolNix/72.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/72.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/72.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92784 MoritzBunkus.MKVToolNix version 73.0.0
  manifests/m/MoritzBunkus/MKVToolNix/73.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/73.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/73.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/73.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92782 New version: StrawberryMusicPlayer.Strawberry version 1.0.12
  manifests/s/StrawberryMusicPlayer/Strawberry/1.0.12/StrawberryMusicPlayer.Strawberry.installer.yaml
  manifests/s/StrawberryMusicPlayer/Strawberry/1.0.12/StrawberryMusicPlayer.Strawberry.locale.en-US.yaml
  manifests/s/StrawberryMusicPlayer/Strawberry/1.0.12/StrawberryMusicPlayer.Strawberry.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92791 New version: WestWind.MarkdownMonster version 2.7.10.0
  manifests/w/WestWind/MarkdownMonster/2.7.10.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/2.7.10.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/2.7.10.0/WestWind.MarkdownMonster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92781 New version: RandomEngy.VidCoder.Beta version 8.15
  manifests/r/RandomEngy/VidCoder/Beta/8.15/RandomEngy.VidCoder.Beta.installer.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.15/RandomEngy.VidCoder.Beta.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.15/RandomEngy.VidCoder.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92773 Update: KDE.KDEConnect version 22.12.0
  manifests/k/KDE/KDEConnect/22.12.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92770 th-ch.YouTubeMusic version 1.19.0
  manifests/t/th-ch/YouTubeMusic/1.19.0/th-ch.YouTubeMusic.installer.yaml
  manifests/t/th-ch/YouTubeMusic/1.19.0/th-ch.YouTubeMusic.locale.en-US.yaml
  manifests/t/th-ch/YouTubeMusic/1.19.0/th-ch.YouTubeMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92780 TobySuggate.GitFiend version 0.38.3
  manifests/t/TobySuggate/GitFiend/0.38.3/TobySuggate.GitFiend.installer.yaml
  manifests/t/TobySuggate/GitFiend/0.38.3/TobySuggate.GitFiend.locale.en-US.yaml
  manifests/t/TobySuggate/GitFiend/0.38.3/TobySuggate.GitFiend.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92800 New version: B3log.SiYuan version 2.6.1
  manifests/b/B3log/SiYuan/2.6.1/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.6.1/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.6.1/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.6.1/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92764 New version: deepnight.LDtk version 1.2.0
  manifests/d/deepnight/LDtk/1.2.0/deepnight.LDtk.installer.yaml
  manifests/d/deepnight/LDtk/1.2.0/deepnight.LDtk.locale.en-US.yaml
  manifests/d/deepnight/LDtk/1.2.0/deepnight.LDtk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92768 Devolutions.RemoteDesktopManager version 2022.3.29.0
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.29.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.29.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.29.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92796 New version: TeamProwlarr.Prowlarr version 1.0.1.2220
  manifests/t/TeamProwlarr/Prowlarr/1.0.1/TeamProwlarr.Prowlarr.installer.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.0.1/TeamProwlarr.Prowlarr.locale.en-US.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.0.1/TeamProwlarr.Prowlarr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92763 New version: Balena.BalenaCLI version 15.0.0
  manifests/b/Balena/BalenaCLI/15.0.0/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/15.0.0/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/15.0.0/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92760 New version: TopalaSoftwareSolutions.SIW version 2023.01.02
  manifests/t/TopalaSoftwareSolutions/SIW/2023.01.02/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.01.02/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.01.02/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92758 InstantHousecall.InstantHousecall version 7.0.1.0
  manifests/i/InstantHousecall/InstantHousecall/7.0.1.0/InstantHousecall.InstantHousecall.installer.yaml
  manifests/i/InstantHousecall/InstantHousecall/7.0.1.0/InstantHousecall.InstantHousecall.locale.en-US.yaml
  manifests/i/InstantHousecall/InstantHousecall/7.0.1.0/InstantHousecall.InstantHousecall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92757 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92742 New version: Google.Chrome.Canary version 111.0.5515.0 [FP-O]
  manifests/g/Google/Chrome/Canary/111.0.5515.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/111.0.5515.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/111.0.5515.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/111.0.5515.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92752 New version: Alibaba.AliIM version 10.01.03C
  manifests/a/Alibaba/AliIM/10.01.03C/Alibaba.AliIM.installer.yaml
  manifests/a/Alibaba/AliIM/10.01.03C/Alibaba.AliIM.locale.en-US.yaml
  manifests/a/Alibaba/AliIM/10.01.03C/Alibaba.AliIM.locale.zh-CN.yaml
  manifests/a/Alibaba/AliIM/10.01.03C/Alibaba.AliIM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92750 New version: Thunder.Xmp version 6.2.5.610
  manifests/t/Thunder/Xmp/6.2.5.610/Thunder.Xmp.installer.yaml
  manifests/t/Thunder/Xmp/6.2.5.610/Thunder.Xmp.locale.en-US.yaml
  manifests/t/Thunder/Xmp/6.2.5.610/Thunder.Xmp.locale.zh-CN.yaml
  manifests/t/Thunder/Xmp/6.2.5.610/Thunder.Xmp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92771 StefansTools.grepWin version 2.0.1183
  manifests/s/StefansTools/grepWin/2.0.1183/StefansTools.grepWin.installer.yaml
  manifests/s/StefansTools/grepWin/2.0.1183/StefansTools.grepWin.locale.en-US.yaml
  manifests/s/StefansTools/grepWin/2.0.1183/StefansTools.grepWin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92743 New version: lyswhut.lx-music-desktop version 2.0.2 [FP-O]
  manifests/l/lyswhut/lx-music-desktop/2.0.2/lyswhut.lx-music-desktop.installer.yaml
  manifests/l/lyswhut/lx-music-desktop/2.0.2/lyswhut.lx-music-desktop.locale.en-US.yaml
  manifests/l/lyswhut/lx-music-desktop/2.0.2/lyswhut.lx-music-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92741 New version: GeoffreyChen.Paperlib version 2.1.4
  manifests/g/GeoffreyChen/Paperlib/2.1.4/GeoffreyChen.Paperlib.installer.yaml
  manifests/g/GeoffreyChen/Paperlib/2.1.4/GeoffreyChen.Paperlib.locale.en-US.yaml
  manifests/g/GeoffreyChen/Paperlib/2.1.4/GeoffreyChen.Paperlib.locale.zh-CN.yaml
  manifests/g/GeoffreyChen/Paperlib/2.1.4/GeoffreyChen.Paperlib.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92756 New version: ExpressLRS.ExpressLRS-Configurator version 1.5.5
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.5/ExpressLRS.ExpressLRS-Configurator.installer.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.5/ExpressLRS.ExpressLRS-Configurator.locale.en-US.yaml
  manifests/e/ExpressLRS/ExpressLRS-Configurator/1.5.5/ExpressLRS.ExpressLRS-Configurator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92749 New version: Nvidia.GeForceNow version 2.0.47.125
  manifests/n/Nvidia/GeForceNow/2.0.47.125/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.47.125/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.47.125/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.47.125/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92815 Microsoft.VisualStudioCode.Insiders_v1.75.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.75.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92809 New version: Tencent.TencentMeeting version 3.13.6.465
  manifests/t/Tencent/TencentMeeting/3.13.6.465/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.13.6.465/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.13.6.465/Tencent.TencentMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeeting/3.13.6.465/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92817 Added AWS Command Line Interface version 2.9.12.
  manifests/a/Amazon/AWSCLI/2.9.12/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.9.12/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.9.12/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92798 New package: williamnie.NetSend version 2.0.0
  manifests/w/williamnie/NetSend/2.0.0/williamnie.NetSend.installer.yaml
  manifests/w/williamnie/NetSend/2.0.0/williamnie.NetSend.locale.en-US.yaml
  manifests/w/williamnie/NetSend/2.0.0/williamnie.NetSend.locale.zh-CN.yaml
  manifests/w/williamnie/NetSend/2.0.0/williamnie.NetSend.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92744 Update: Coninfer.ECLiPSeCLP.7.1 version 7.1 #13
  manifests/c/Coninfer/ECLiPSeCLP/7/1/7.1 #13/Coninfer.ECLiPSeCLP.7.1.installer.yaml
  manifests/c/Coninfer/ECLiPSeCLP/7/1/7.1 #13/Coninfer.ECLiPSeCLP.7.1.locale.en-US.yaml
  manifests/c/Coninfer/ECLiPSeCLP/7/1/7.1 #13/Coninfer.ECLiPSeCLP.7.1.locale.zh-CN.yaml
  manifests/c/Coninfer/ECLiPSeCLP/7/1/7.1 #13/Coninfer.ECLiPSeCLP.7.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92818 New version: DrakeetXu.PureWriter version 1.7.1
  manifests/d/DrakeetXu/PureWriter/1.7.1/DrakeetXu.PureWriter.installer.yaml
  manifests/d/DrakeetXu/PureWriter/1.7.1/DrakeetXu.PureWriter.locale.en-US.yaml
  manifests/d/DrakeetXu/PureWriter/1.7.1/DrakeetXu.PureWriter.locale.zh-CN.yaml
  manifests/d/DrakeetXu/PureWriter/1.7.1/DrakeetXu.PureWriter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92822 New version: yt-dlp.yt-dlp version 2023.01.02
  manifests/y/yt-dlp/yt-dlp/2023.01.02/yt-dlp.yt-dlp.installer.yaml
  manifests/y/yt-dlp/yt-dlp/2023.01.02/yt-dlp.yt-dlp.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/2023.01.02/yt-dlp.yt-dlp.locale.zh-CN.yaml
  manifests/y/yt-dlp/yt-dlp/2023.01.02/yt-dlp.yt-dlp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92747 New package: zhanglun.Lettura version 0.1.0
  manifests/z/zhanglun/Lettura/0.1.0/zhanglun.Lettura.installer.yaml
  manifests/z/zhanglun/Lettura/0.1.0/zhanglun.Lettura.locale.en-US.yaml
  manifests/z/zhanglun/Lettura/0.1.0/zhanglun.Lettura.locale.zh-CN.yaml
  manifests/z/zhanglun/Lettura/0.1.0/zhanglun.Lettura.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92794 New package: ByteDance.XiguaVideo version 1.0.4
  manifests/b/ByteDance/XiguaVideo/1.0.4/ByteDance.XiguaVideo.installer.yaml
  manifests/b/ByteDance/XiguaVideo/1.0.4/ByteDance.XiguaVideo.locale.en-US.yaml
  manifests/b/ByteDance/XiguaVideo/1.0.4/ByteDance.XiguaVideo.locale.zh-CN.yaml
  manifests/b/ByteDance/XiguaVideo/1.0.4/ByteDance.XiguaVideo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#92754 New package: ByteDance.DouyinIM version 1.0.0
  manifests/b/ByteDance/DouyinIM/1.0.0/ByteDance.DouyinIM.installer.yaml
  manifests/b/ByteDance/DouyinIM/1.0.0/ByteDance.DouyinIM.locale.en-US.yaml
  manifests/b/ByteDance/DouyinIM/1.0.0/ByteDance.DouyinIM.locale.zh-CN.yaml
  manifests/b/ByteDance/DouyinIM/1.0.0/ByteDance.DouyinIM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#92819 Remove: TopalaSoftwareSolutions.SIW version 2022.11.03b
  manifests/t/TopalaSoftwareSolutions/SIW/2022.11.03b/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2022.11.03b/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2022.11.03b/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92430 Twingate.Client version 1.0.21.14067
  manifests/t/Twingate/Client/1.0.24.16856/Twingate.Client.installer.yaml
  manifests/t/Twingate/Client/1.0.24.16856/Twingate.Client.locale.en-US.yaml
  manifests/t/Twingate/Client/1.0.24.16856/Twingate.Client.yaml
Labels: Validation-Completed, Moderator-Approved

#92814 New package: Thunder.Thunder.Speed version 1.0.35.366
  manifests/t/Thunder/Thunder/Speed/1.0.35.366/Thunder.Thunder.Speed.installer.yaml
  manifests/t/Thunder/Thunder/Speed/1.0.35.366/Thunder.Thunder.Speed.locale.en-US.yaml
  manifests/t/Thunder/Thunder/Speed/1.0.35.366/Thunder.Thunder.Speed.locale.zh-CN.yaml
  manifests/t/Thunder/Thunder/Speed/1.0.35.366/Thunder.Thunder.Speed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#92811 New version: Thunder.Thunder version 11.3.20.2014
  manifests/t/Thunder/Thunder/11.3.20.2014/Thunder.Thunder.installer.yaml
  manifests/t/Thunder/Thunder/11.3.20.2014/Thunder.Thunder.locale.en-US.yaml
  manifests/t/Thunder/Thunder/11.3.20.2014/Thunder.Thunder.locale.zh-CN.yaml
  manifests/t/Thunder/Thunder/11.3.20.2014/Thunder.Thunder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#92810 New package: Thunder.Thunder version 11.3.19.2000
  manifests/t/Thunder/Thunder/11.3.19.2000/Thunder.Thunder.installer.yaml
  manifests/t/Thunder/Thunder/11.3.19.2000/Thunder.Thunder.locale.en-US.yaml
  manifests/t/Thunder/Thunder/11.3.19.2000/Thunder.Thunder.locale.zh-CN.yaml
  manifests/t/Thunder/Thunder/11.3.19.2000/Thunder.Thunder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#92670 New version: OpenDesignAlliance.ODAFileConverter 23.12
  manifests/o/OpenDesignAlliance/ODAFileConverter/23.12/OpenDesignAlliance.ODAFileConverter.installer.yaml
  manifests/o/OpenDesignAlliance/ODAFileConverter/23.12/OpenDesignAlliance.ODAFileConverter.locale.en-US.yaml
  manifests/o/OpenDesignAlliance/ODAFileConverter/23.12/OpenDesignAlliance.ODAFileConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92684 New version: chrisant996.Clink version 1.4.7.524e49
  manifests/c/chrisant996/Clink/1.4.7.524e49/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.4.7.524e49/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.4.7.524e49/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Installation-Error

#92704 New version: FontForge.FontForge version 20230101
  manifests/f/FontForge/FontForge/20230101/FontForge.FontForge.installer.yaml
  manifests/f/FontForge/FontForge/20230101/FontForge.FontForge.locale.en-US.yaml
  manifests/f/FontForge/FontForge/20230101/FontForge.FontForge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92715 TablePlus.TablePlus version 5.0.4
  manifests/t/TablePlus/TablePlus/5.0.4/TablePlus.TablePlus.installer.yaml
  manifests/t/TablePlus/TablePlus/5.0.4/TablePlus.TablePlus.locale.en-US.yaml
  manifests/t/TablePlus/TablePlus/5.0.4/TablePlus.TablePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92739 New version: Microsoft.PCManager version 1.2.6.4
  manifests/m/Microsoft/PCManager/1.2.6.4/Microsoft.PCManager.installer.yaml
  manifests/m/Microsoft/PCManager/1.2.6.4/Microsoft.PCManager.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/1.2.6.4/Microsoft.PCManager.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/1.2.6.4/Microsoft.PCManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92767 Insynchq.Insync version 3.8.4.50481
  manifests/i/Insynchq/Insync/3.8.4.50481/Insynchq.Insync.installer.yaml
  manifests/i/Insynchq/Insync/3.8.4.50481/Insynchq.Insync.locale.en-US.yaml
  manifests/i/Insynchq/Insync/3.8.4.50481/Insynchq.Insync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92821 Microsoft.Sysinternals.ProcessMonitor version 3.92
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92832 New version: Hydraulic.Conveyor version 6.0.0.0
  manifests/h/Hydraulic/Conveyor/6.0.0.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/6.0.0.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/6.0.0.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92824 New version: deepnight.LDtk version 1.2.1
  manifests/d/deepnight/LDtk/1.2.1/deepnight.LDtk.installer.yaml
  manifests/d/deepnight/LDtk/1.2.1/deepnight.LDtk.locale.en-US.yaml
  manifests/d/deepnight/LDtk/1.2.1/deepnight.LDtk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92823 New version: B3log.SiYuan version 2.6.2
  manifests/b/B3log/SiYuan/2.6.2/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.6.2/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.6.2/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.6.2/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92841 sylikc.JPEGView version 1.1.41.1
  manifests/s/sylikc/JPEGView/1.1.41.1/sylikc.JPEGView.installer.yaml
  manifests/s/sylikc/JPEGView/1.1.41.1/sylikc.JPEGView.locale.en-US.yaml
  manifests/s/sylikc/JPEGView/1.1.41.1/sylikc.JPEGView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92830 New version: RivaFarabi.Deckboard version 2.1.0
  manifests/r/RivaFarabi/Deckboard/2.1.0/RivaFarabi.Deckboard.installer.yaml
  manifests/r/RivaFarabi/Deckboard/2.1.0/RivaFarabi.Deckboard.locale.en-US.yaml
  manifests/r/RivaFarabi/Deckboard/2.1.0/RivaFarabi.Deckboard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92778 Update ALVR to 19.0.0
  manifests/a/ALVR/ALVR/19.0.0/ALVR.ALVR.installer.yaml
  manifests/a/ALVR/ALVR/19.0.0/ALVR.ALVR.locale.en-US.yaml
  manifests/a/ALVR/ALVR/19.0.0/ALVR.ALVR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92564 New version: Cybelsoft.DriversCloud version 11.2.7.0 [FP-D]
  manifests/c/Cybelsoft/DriversCloud/11.2.7.0/Cybelsoft.DriversCloud.installer.yaml
  manifests/c/Cybelsoft/DriversCloud/11.2.7.0/Cybelsoft.DriversCloud.locale.en-US.yaml
  manifests/c/Cybelsoft/DriversCloud/11.2.7.0/Cybelsoft.DriversCloud.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92839 New version: RandomEngy.VidCoder.Beta version 8.16
  manifests/r/RandomEngy/VidCoder/Beta/8.16/RandomEngy.VidCoder.Beta.installer.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.16/RandomEngy.VidCoder.Beta.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/Beta/8.16/RandomEngy.VidCoder.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92790 NVAccess.NVDA version 2022.4
  manifests/n/NVAccess/NVDA/2022.4/NVAccess.NVDA.installer.yaml
  manifests/n/NVAccess/NVDA/2022.4/NVAccess.NVDA.locale.en-US.yaml
  manifests/n/NVAccess/NVDA/2022.4/NVAccess.NVDA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92826 New version: nimblenote.nimblenote version 3.2.2
  manifests/n/nimblenote/nimblenote/3.2.2/nimblenote.nimblenote.installer.yaml
  manifests/n/nimblenote/nimblenote/3.2.2/nimblenote.nimblenote.locale.en-US.yaml
  manifests/n/nimblenote/nimblenote/3.2.2/nimblenote.nimblenote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92829 igoogolx.lux version 0.1.8
  manifests/i/igoogolx/lux/0.1.8/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.1.8/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.1.8/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92820 Added Bicep CLI version 0.13.1.58284
  manifests/m/Microsoft/Bicep/0.13.1.58284/Microsoft.Bicep.installer.yaml
  manifests/m/Microsoft/Bicep/0.13.1.58284/Microsoft.Bicep.locale.en-US.yaml
  manifests/m/Microsoft/Bicep/0.13.1.58284/Microsoft.Bicep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92895 Update: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92896 Update: KDE.Kate version 22.12.0 [FP-O]
  manifests/k/KDE/Kate/22.12.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92899 New version: Jackett.Jackett version 0.20.2480
  manifests/j/Jackett/Jackett/0.20.2480/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2480/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2480/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92863 Update: KDE.Dolphin version 22.12.0 [FP-O]
  manifests/k/KDE/Dolphin/22.12.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92862 New version: GitHub.cli version 2.21.2
  manifests/g/GitHub/cli/2.21.2/GitHub.cli.installer.yaml
  manifests/g/GitHub/cli/2.21.2/GitHub.cli.locale.en-US.yaml
  manifests/g/GitHub/cli/2.21.2/GitHub.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92857 New Package: Cyanfish.NAPS2.Prerelease version 7.01
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.1/Cyanfish.NAPS2.Prerelease.installer.yaml
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.1/Cyanfish.NAPS2.Prerelease.locale.en-US.yaml
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.1/Cyanfish.NAPS2.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92888 DoltHub.Dolt version 0.51.15
  manifests/d/DoltHub/Dolt/0.51.15/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.51.15/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.51.15/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92852 Update: KDE.KDEConnect version 22.12.0 [FP-O]
  manifests/k/KDE/KDEConnect/22.12.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92851 New version: Google.Chrome.Canary version 111.0.5517.0
  manifests/g/Google/Chrome/Canary/111.0.5517.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/111.0.5517.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/111.0.5517.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/111.0.5517.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92897 Update: KDE.Kdenlive version 22.12.0 [FP-O]
  manifests/k/KDE/Kdenlive/22.12.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92907 New version: purocean.YankNote version 3.47.0
  manifests/p/purocean/YankNote/3.47.0/purocean.YankNote.installer.yaml
  manifests/p/purocean/YankNote/3.47.0/purocean.YankNote.locale.en-US.yaml
  manifests/p/purocean/YankNote/3.47.0/purocean.YankNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92901 Fix: Lenovo.LeCloud version 2.501.25.0
  manifests/l/Lenovo/LeCloud/2.501.25.0/Lenovo.LeCloud.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92865 New version: vim.vim version 9.0.1140
  manifests/v/vim/vim/9.0.1140/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1140/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1140/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92898 Update: KDE.Okular version 22.12.0 [FP-O]
  manifests/k/KDE/Okular/22.12.0/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92893 2BrightSparks.SyncBackPro version 10.2.88.0
  manifests/2/2BrightSparks/SyncBackPro/10.2.88.0/2BrightSparks.SyncBackPro.installer.yaml
  manifests/2/2BrightSparks/SyncBackPro/10.2.88.0/2BrightSparks.SyncBackPro.locale.en-US.yaml
  manifests/2/2BrightSparks/SyncBackPro/10.2.88.0/2BrightSparks.SyncBackPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92910 New version: AutoHotkey.AutoHotkey version 2.0.2
  manifests/a/AutoHotkey/AutoHotkey/2.0.2/AutoHotkey.AutoHotkey.installer.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.2/AutoHotkey.AutoHotkey.locale.en-US.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.2/AutoHotkey.AutoHotkey.locale.zh-CN.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.2/AutoHotkey.AutoHotkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92911 Microsoft.VisualStudioCode.Insiders_v1.75.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.75.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92858 New Package: Cyanfish.NAPS2.Prerelease version 7.02
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.2/Cyanfish.NAPS2.Prerelease.installer.yaml
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.2/Cyanfish.NAPS2.Prerelease.locale.en-US.yaml
  manifests/c/Cyanfish/NAPS2/Prerelease/7.0.2/Cyanfish.NAPS2.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92914 New version: Google.Chrome.Canary version 111.0.5518.0
  manifests/g/Google/Chrome/Canary/111.0.5518.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/111.0.5518.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/111.0.5518.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/111.0.5518.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92840 Hashicorp.Vagrant version 2.3.3
  manifests/h/Hashicorp/Vagrant/2.3.3/Hashicorp.Vagrant.installer.yaml
  manifests/h/Hashicorp/Vagrant/2.3.3/Hashicorp.Vagrant.locale.en-US.yaml
  manifests/h/Hashicorp/Vagrant/2.3.3/Hashicorp.Vagrant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92919 Add version: Hydraulic.Conveyor version 2.0.0.0
  manifests/h/Hydraulic/Conveyor/2.0.0.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/2.0.0.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/2.0.0.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92918 Add version: Hydraulic.Conveyor version 2.1.0.0
  manifests/h/Hydraulic/Conveyor/2.1.0.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/2.1.0.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/2.1.0.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92913 Add version: Hydraulic.Conveyor version 4.1.1.0
  manifests/h/Hydraulic/Conveyor/4.1.1.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/4.1.1.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/4.1.1.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92916 Add version: Hydraulic.Conveyor version 4.0.0.0
  manifests/h/Hydraulic/Conveyor/4.0.0.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/4.0.0.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/4.0.0.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92912 Update Copyright for HashiCorp.Vagrant
  manifests/h/Hashicorp/Vagrant/2.3.4/Hashicorp.Vagrant.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92922 Normalize: JanDeDobbeleer.OhMyPosh version 12.24.0
  manifests/j/JanDeDobbeleer/OhMyPosh/12.24.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.24.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.24.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92915 Add version: Hydraulic.Conveyor version 4.1.0.0
  manifests/h/Hydraulic/Conveyor/4.1.0.0/Hydraulic.Conveyor.installer.yaml
  manifests/h/Hydraulic/Conveyor/4.1.0.0/Hydraulic.Conveyor.locale.en-US.yaml
  manifests/h/Hydraulic/Conveyor/4.1.0.0/Hydraulic.Conveyor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92923 Normalize: JanDeDobbeleer.OhMyPosh version 12.25.0
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92924 Normalize: JanDeDobbeleer.OhMyPosh version 12.25.1
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92921 Normalize: JanDeDobbeleer.OhMyPosh version 12.23.0
  manifests/j/JanDeDobbeleer/OhMyPosh/12.23.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.23.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.23.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92926 Normalize: JanDeDobbeleer.OhMyPosh version 12.25.3
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#92925 Normalize: JanDeDobbeleer.OhMyPosh version 12.25.2
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/12.25.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
