Repository microsoft/winget-pkgs, pull requests merged in 2023-08, with the labels that each got.

#113542 Update version: Anaconda.Anaconda3 version 2023.07
  manifests/a/Anaconda/Anaconda3/2023.07/Anaconda.Anaconda3.installer.yaml
  manifests/a/Anaconda/Anaconda3/2023.07/Anaconda.Anaconda3.locale.en-US.yaml
  manifests/a/Anaconda/Anaconda3/2023.07/Anaconda.Anaconda3.yaml
Labels: Validation-Completed, Retry-1

#113638 Update version: DuongDieuPhap.ImageGlass version 8.9.6.9
  manifests/d/DuongDieuPhap/ImageGlass/8.9.6.9/DuongDieuPhap.ImageGlass.installer.yaml
  manifests/d/DuongDieuPhap/ImageGlass/8.9.6.9/DuongDieuPhap.ImageGlass.locale.en-US.yaml
  manifests/d/DuongDieuPhap/ImageGlass/8.9.6.9/DuongDieuPhap.ImageGlass.yaml
Labels: Validation-Completed, Retry-1

#113652 Update version: Element.Element version 1.11.36
  manifests/e/Element/Element/1.11.36/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.36/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.36/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Domain

#113655 Update version: elvirbrk.notehighlight2016 version 3.7
  manifests/e/elvirbrk/notehighlight2016/3.7/elvirbrk.notehighlight2016.installer.yaml
  manifests/e/elvirbrk/notehighlight2016/3.7/elvirbrk.notehighlight2016.locale.en-US.yaml
  manifests/e/elvirbrk/notehighlight2016/3.7/elvirbrk.notehighlight2016.yaml
Labels: Validation-Completed, Retry-1

#113714 Moved: Microsoft.PCManager.CN version 3.4.2.0
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.es-ES.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.ja-JP.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.zh-TW.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#113656 Update version: eMClient.eMClient version 9.2.2038.0
  manifests/e/eMClient/eMClient/9.2.2038.0/eMClient.eMClient.installer.yaml
  manifests/e/eMClient/eMClient/9.2.2038.0/eMClient.eMClient.locale.en-US.yaml
  manifests/e/eMClient/eMClient/9.2.2038.0/eMClient.eMClient.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#113803 Add Obsidian.Obsidian 1.3.7
  manifests/o/Obsidian/Obsidian/1.3.7/Obsidian.Obsidian.installer.yaml
  manifests/o/Obsidian/Obsidian/1.3.7/Obsidian.Obsidian.locale.en-US.yaml
  manifests/o/Obsidian/Obsidian/1.3.7/Obsidian.Obsidian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113805 New version: GeoGebra.Classic version 6.0.793
  manifests/g/GeoGebra/Classic/6.0.793/GeoGebra.Classic.installer.yaml
  manifests/g/GeoGebra/Classic/6.0.793/GeoGebra.Classic.locale.en-US.yaml
  manifests/g/GeoGebra/Classic/6.0.793/GeoGebra.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113806 New version: ProjectEnv.ProjectEnvCli version 3.16.0
  manifests/p/ProjectEnv/ProjectEnvCli/3.16.0/ProjectEnv.ProjectEnvCli.installer.yaml
  manifests/p/ProjectEnv/ProjectEnvCli/3.16.0/ProjectEnv.ProjectEnvCli.locale.en-US.yaml
  manifests/p/ProjectEnv/ProjectEnvCli/3.16.0/ProjectEnv.ProjectEnvCli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113814 Remove Whitespace from Baidu.SwanIDE 4.1.1
  manifests/b/Baidu/SwanIDE/4.1.1/Baidu.SwanIDE.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113813 Remove Whitespace from Baidu.SwanIDE 4.7.1
  manifests/b/Baidu/SwanIDE/4.7.1/Baidu.SwanIDE.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113815 Update: behringer.XAIREdit version 1.7
  manifests/b/behringer/XAIREdit/1.7/behringer.XAIREdit.installer.yaml
  manifests/b/behringer/XAIREdit/1.7/behringer.XAIREdit.locale.en-US.yaml
  manifests/b/behringer/XAIREdit/1.7/behringer.XAIREdit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113818 Update: Tencent.WeType version 0.9.0.69
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113804 Update cURL v8.2.1
  manifests/c/cURL/cURL/8.2.1/cURL.cURL.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113822 Remove Whitespace from Mozilla.Thunderbird 102.13.0
  manifests/m/Mozilla/Thunderbird/102.13.0/Mozilla.Thunderbird.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113826 New version: Baidu.BaiduNetdisk version 7.31.1
  manifests/b/Baidu/BaiduNetdisk/7.31.1/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.31.1/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.31.1/Baidu.BaiduNetdisk.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduNetdisk/7.31.1/Baidu.BaiduNetdisk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113820 Remove Whitespace from Mozilla.Thunderbird 102.11.1
  manifests/m/Mozilla/Thunderbird/102.11.1/Mozilla.Thunderbird.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113828 New version: ByteDance.CapCut version 2.4.0.634
  manifests/b/ByteDance/CapCut/2.4.0.634/ByteDance.CapCut.installer.yaml
  manifests/b/ByteDance/CapCut/2.4.0.634/ByteDance.CapCut.locale.en-US.yaml
  manifests/b/ByteDance/CapCut/2.4.0.634/ByteDance.CapCut.locale.zh-CN.yaml
  manifests/b/ByteDance/CapCut/2.4.0.634/ByteDance.CapCut.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113827 New version: SweetScape.010Editor version 14.0
  manifests/s/SweetScape/010Editor/14.0/SweetScape.010Editor.installer.yaml
  manifests/s/SweetScape/010Editor/14.0/SweetScape.010Editor.locale.en-US.yaml
  manifests/s/SweetScape/010Editor/14.0/SweetScape.010Editor.locale.zh-CN.yaml
  manifests/s/SweetScape/010Editor/14.0/SweetScape.010Editor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113817 Remove Whitespace from zg_print 6.2.0.5
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113816 Remove Whitespace from Billfish.Billfish 2.6.0.11
  manifests/b/Billfish/Billfish/2.6.0.11/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/2.6.0.11/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/2.6.0.11/Billfish.Billfish.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#113832 Microsoft.VisualStudioCode.Insiders_v1.81.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.81.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113877 Update version: RussellBanks.Komac.Nightly version 1.10.0
  manifests/r/RussellBanks/Komac/Nightly/1.10.0/RussellBanks.Komac.Nightly.installer.yaml
  manifests/r/RussellBanks/Komac/Nightly/1.10.0/RussellBanks.Komac.Nightly.locale.en-US.yaml
  manifests/r/RussellBanks/Komac/Nightly/1.10.0/RussellBanks.Komac.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113881 Fix Release date for TeamSophia.SophiApp 1.0.95
  manifests/t/TeamSophia/SophiApp/1.0.95/TeamSophia.SophiApp.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113883 Updated Google Chrome Dev to version 117.0.5911.2.
  manifests/g/Google/Chrome/Dev/117.0.5911.2/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/117.0.5911.2/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/117.0.5911.2/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/117.0.5911.2/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113882 Updated Google Chrome Beta to version 116.0.5845.49.
  manifests/g/Google/Chrome/Beta/116.0.5845.49/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/116.0.5845.49/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/116.0.5845.49/Google.Chrome.Beta.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Beta/116.0.5845.49/Google.Chrome.Beta.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Beta/116.0.5845.49/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113934 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.44
  manifests/c/Cockos/REAPER/6.44/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.44/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.44/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113872 New version: Bin-Huang.Chatbox version 0.6.6
  manifests/b/Bin-Huang/Chatbox/0.6.6/Bin-Huang.Chatbox.installer.yaml
  manifests/b/Bin-Huang/Chatbox/0.6.6/Bin-Huang.Chatbox.locale.en-US.yaml
  manifests/b/Bin-Huang/Chatbox/0.6.6/Bin-Huang.Chatbox.locale.zh-CN.yaml
  manifests/b/Bin-Huang/Chatbox/0.6.6/Bin-Huang.Chatbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113925 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.35
  manifests/c/Cockos/REAPER/6.35/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.35/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.35/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113864 Moving: Kiraku.Neatify version 1.5.0-233
  manifests/k/Kiraku/Neatify/1.5.0-233/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/1.5.0-233/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/1.5.0-233/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/1.5.0-233/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113862 Moving: Kiraku.Neatify version 1.3.1-207
  manifests/k/Kiraku/Neatify/1.3.1-207/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/1.3.1-207/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/1.3.1-207/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/1.3.1-207/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113955 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.65
  manifests/c/Cockos/REAPER/6.65/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.65/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.65/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113863 Moving: Kiraku.Neatify version 1.3.2-208
  manifests/k/Kiraku/Neatify/1.3.2-208/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/1.3.2-208/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/1.3.2-208/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/1.3.2-208/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113909 Update: Aiursoft.Kahla version 4.5.0
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113899 Remove: Microsoft.Sysinternals.ZoomIt version 6.12
  manifests/m/Microsoft/Sysinternals/ZoomIt/6.12/Microsoft.Sysinternals.ZoomIt.installer.yaml
  manifests/m/Microsoft/Sysinternals/ZoomIt/6.12/Microsoft.Sysinternals.ZoomIt.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ZoomIt/6.12/Microsoft.Sysinternals.ZoomIt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113896 Remove: Microsoft.Sysinternals.ProcessMonitor version 3.92
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.92/Microsoft.Sysinternals.ProcessMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113894 Quote version in Mozilla.Firefox.ESR 91.0
  manifests/m/Mozilla/Firefox/ESR/91.0/Mozilla.Firefox.ESR.installer.yaml
  manifests/m/Mozilla/Firefox/ESR/91.0/Mozilla.Firefox.ESR.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/ESR/91.0/Mozilla.Firefox.ESR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113865 Moving: Kiraku.Neatify version 1.5.1-250
  manifests/k/Kiraku/Neatify/1.5.1-250/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/1.5.1-250/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/1.5.1-250/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/1.5.1-250/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113907 Update: Element.Element version 1.11.35
  manifests/e/Element/Element/1.11.35/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.35/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.35/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113801 New package: Mikrotik.Winbox version 3.39
  manifests/m/Mikrotik/Winbox/3.39/Mikrotik.Winbox.installer.yaml
  manifests/m/Mikrotik/Winbox/3.39/Mikrotik.Winbox.locale.en-US.yaml
  manifests/m/Mikrotik/Winbox/3.39/Mikrotik.Winbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113860 Moved: Kiraku.Mindbox version 1.5.2-253
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#113900 Remove: Microsoft.Sysinternals.RDCMan version 2.92
  manifests/m/Microsoft/Sysinternals/RDCMan/2.92/Microsoft.Sysinternals.RDCMan.installer.yaml
  manifests/m/Microsoft/Sysinternals/RDCMan/2.92/Microsoft.Sysinternals.RDCMan.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/RDCMan/2.92/Microsoft.Sysinternals.RDCMan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113901 Remove: Microsoft.Sysinternals.ProcessExplorer version 17.0
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessExplorer/17.0/Microsoft.Sysinternals.ProcessExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113904 Update: Element.Element version 1.11.31
  manifests/e/Element/Element/1.11.31/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.31/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.31/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113911 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.21
  manifests/c/Cockos/REAPER/6.21/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.21/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.21/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113913 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.23
  manifests/c/Cockos/REAPER/6.23/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.23/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.23/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113823 Remove Whitespace from Mozilla.Thunderbird 115.0
  manifests/m/Mozilla/Thunderbird/115.0/Mozilla.Thunderbird.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113861 Moved: Kiraku.Mindbox version 1.5.3-279
  manifests/k/Kiraku/Mindbox/1.5.3-279/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.5.3-279/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.5.3-279/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.5.3-279/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#113916 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.26
  manifests/c/Cockos/REAPER/6.26/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.26/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.26/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113895 Remove: Microsoft.Sysinternals.ProcessMonitor version 3.91
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.91/Microsoft.Sysinternals.ProcessMonitor.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.91/Microsoft.Sysinternals.ProcessMonitor.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.91/Microsoft.Sysinternals.ProcessMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113852 New version: Hellofont.Hellofont version 4.0.2
  manifests/h/Hellofont/Hellofont/4.0.2/Hellofont.Hellofont.installer.yaml
  manifests/h/Hellofont/Hellofont/4.0.2/Hellofont.Hellofont.locale.en-US.yaml
  manifests/h/Hellofont/Hellofont/4.0.2/Hellofont.Hellofont.locale.zh-CN.yaml
  manifests/h/Hellofont/Hellofont/4.0.2/Hellofont.Hellofont.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113906 Update: Element.Element version 1.11.34
  manifests/e/Element/Element/1.11.34/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.34/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.34/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113917 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.27
  manifests/c/Cockos/REAPER/6.27/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.27/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.27/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113849 New version: ByteDance.Lark version 6.9.11
  manifests/b/ByteDance/Lark/6.9.11/ByteDance.Lark.installer.yaml
  manifests/b/ByteDance/Lark/6.9.11/ByteDance.Lark.locale.en-US.yaml
  manifests/b/ByteDance/Lark/6.9.11/ByteDance.Lark.locale.zh-CN.yaml
  manifests/b/ByteDance/Lark/6.9.11/ByteDance.Lark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113841 Update Netron to 7.1.0
  manifests/l/LutzRoeder/Netron/7.1.0/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.1.0/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.1.0/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113958 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.68
  manifests/c/Cockos/REAPER/6.68/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.68/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.68/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113910 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.11
  manifests/c/Cockos/REAPER/6.11/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.11/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.11/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113957 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.67
  manifests/c/Cockos/REAPER/6.67/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.67/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.67/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113944 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.54
  manifests/c/Cockos/REAPER/6.54/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.54/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.54/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113866 Moving: Kiraku.Neatify version 1.5.2-253
  manifests/k/Kiraku/Neatify/1.5.2-253/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/1.5.2-253/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/1.5.2-253/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/1.5.2-253/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113851 New version: Appest.TickTick version 4.5.7.0
  manifests/a/Appest/TickTick/4.5.7.0/Appest.TickTick.installer.yaml
  manifests/a/Appest/TickTick/4.5.7.0/Appest.TickTick.locale.en-US.yaml
  manifests/a/Appest/TickTick/4.5.7.0/Appest.TickTick.locale.zh-CN.yaml
  manifests/a/Appest/TickTick/4.5.7.0/Appest.TickTick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113868 Moving: Kiraku.Neatify version 2.0.0-339
  manifests/k/Kiraku/Neatify/2.0.0-339/Kiraku.Neatify.installer.yaml
  manifests/k/Kiraku/Neatify/2.0.0-339/Kiraku.Neatify.locale.en-US.yaml
  manifests/k/Kiraku/Neatify/2.0.0-339/Kiraku.Neatify.locale.zh-CN.yaml
  manifests/k/Kiraku/Neatify/2.0.0-339/Kiraku.Neatify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113898 Remove: Microsoft.Sysinternals.ProcessMonitor version 3.94
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.94/Microsoft.Sysinternals.ProcessMonitor.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.94/Microsoft.Sysinternals.ProcessMonitor.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.94/Microsoft.Sysinternals.ProcessMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113871 New version: B3log.SiYuan version 2.9.8
  manifests/b/B3log/SiYuan/2.9.8/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.9.8/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.9.8/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.9.8/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113838 New version: NetEase.MailMaster version 4.19.4.1001
  manifests/n/NetEase/MailMaster/4.19.4.1001/NetEase.MailMaster.installer.yaml
  manifests/n/NetEase/MailMaster/4.19.4.1001/NetEase.MailMaster.locale.en-US.yaml
  manifests/n/NetEase/MailMaster/4.19.4.1001/NetEase.MailMaster.locale.zh-CN.yaml
  manifests/n/NetEase/MailMaster/4.19.4.1001/NetEase.MailMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113897 Remove: Microsoft.Sysinternals.ProcessMonitor version 3.93
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.93/Microsoft.Sysinternals.ProcessMonitor.installer.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.93/Microsoft.Sysinternals.ProcessMonitor.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/ProcessMonitor/3.93/Microsoft.Sysinternals.ProcessMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113902 Remove: Microsoft.Sysinternals.Autoruns version 14.09
  manifests/m/Microsoft/Sysinternals/Autoruns/14.09/Microsoft.Sysinternals.Autoruns.installer.yaml
  manifests/m/Microsoft/Sysinternals/Autoruns/14.09/Microsoft.Sysinternals.Autoruns.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/Autoruns/14.09/Microsoft.Sysinternals.Autoruns.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113915 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.25
  manifests/c/Cockos/REAPER/6.25/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.25/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.25/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113951 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.61
  manifests/c/Cockos/REAPER/6.61/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.61/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.61/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113952 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.62
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.62/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113996 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.08
  manifests/p/Phoner/PhonerLite/3.08/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.08/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.08/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113948 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.58
  manifests/c/Cockos/REAPER/6.58/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.58/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.58/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114006 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.17
  manifests/p/Phoner/PhonerLite/3.17/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.17/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.17/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113980 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.92.0
  manifests/p/Phoner/PhonerLite/2.92.0/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.92.0/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.92.0/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113984 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.96
  manifests/p/Phoner/PhonerLite/2.96/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.96/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.96/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114011 Update D:\Git\winget-pkgs\manifests\m\MoheshwarAmarnathBiswas\UsefulToolsForWindows\1.3
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.3/MoheshwarAmarnathBiswas.UsefulToolsForWindows.installer.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.3/MoheshwarAmarnathBiswas.UsefulToolsForWindows.locale.en-US.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.3/MoheshwarAmarnathBiswas.UsefulToolsForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114018 Update D:\Git\winget-pkgs\manifests\m\MoheshwarAmarnathBiswas\UsefulToolsForWindows\2.0
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.installer.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.locale.en-US.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114017 Update D:\Git\winget-pkgs\manifests\m\MoheshwarAmarnathBiswas\UsefulToolsForWindows\1.9
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.9/MoheshwarAmarnathBiswas.UsefulToolsForWindows.installer.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.9/MoheshwarAmarnathBiswas.UsefulToolsForWindows.locale.en-US.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.9/MoheshwarAmarnathBiswas.UsefulToolsForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114009 Update D:\Git\winget-pkgs\manifests\m\MoheshwarAmarnathBiswas\UsefulToolsForWindows\1.0
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.installer.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.locale.en-US.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/1.0/MoheshwarAmarnathBiswas.UsefulToolsForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113991 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.03
  manifests/p/Phoner/PhonerLite/3.03/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.03/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.03/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113994 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.06
  manifests/p/Phoner/PhonerLite/3.06/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.06/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.06/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113998 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.10
  manifests/p/Phoner/PhonerLite/3.10/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.10/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.10/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114020 Update D:\Git\winget-pkgs\manifests\m\MoheshwarAmarnathBiswas\UsefulToolsForWindows\2.2
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.2/MoheshwarAmarnathBiswas.UsefulToolsForWindows.installer.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.2/MoheshwarAmarnathBiswas.UsefulToolsForWindows.locale.en-US.yaml
  manifests/m/MoheshwarAmarnathBiswas/UsefulToolsForWindows/2.2/MoheshwarAmarnathBiswas.UsefulToolsForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113999 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.11
  manifests/p/Phoner/PhonerLite/3.11/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.11/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.11/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114002 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.13
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.13/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114003 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.14
  manifests/p/Phoner/PhonerLite/3.14/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.14/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.14/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114004 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.15
  manifests/p/Phoner/PhonerLite/3.15/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.15/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.15/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114005 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\3.16
  manifests/p/Phoner/PhonerLite/3.16/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/3.16/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/3.16/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114021 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.10.0
  manifests/s/stevencohn/OneMore/2.10.0/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.10.0/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.10.0/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114024 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.13
  manifests/s/stevencohn/OneMore/2.13/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.13/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.13/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114027 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.14.1
  manifests/s/stevencohn/OneMore/2.14.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.14.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.14.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114029 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.15.1
  manifests/s/stevencohn/OneMore/2.15.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.15.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.15.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114046 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.12.1
  manifests/s/stevencohn/OneMore/3.12.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.12.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.12.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114052 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.14
  manifests/s/stevencohn/OneMore/3.14/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.14/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.14/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114054 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.15.1
  manifests/s/stevencohn/OneMore/3.15.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.15.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.15.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113381 Add new version - WK.WKRadar 7.6.0.395
  manifests/w/WK/WKRadar/7.6.0.395/WK.WKRadar.installer.yaml
  manifests/w/WK/WKRadar/7.6.0.395/WK.WKRadar.locale.pt-BR.yaml
  manifests/w/WK/WKRadar/7.6.0.395/WK.WKRadar.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#114073 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.27
  manifests/s/stevencohn/OneMore/3.27/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.27/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.27/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114074 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.28
  manifests/s/stevencohn/OneMore/3.28/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.28/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.28/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114078 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.4.1
  manifests/s/stevencohn/OneMore/3.4.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.4.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.4.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114044 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.11.3
  manifests/s/stevencohn/OneMore/3.11.3/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.11.3/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.11.3/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114086 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.7
  manifests/s/stevencohn/OneMore/3.7/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.7/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.7/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114088 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.8
  manifests/s/stevencohn/OneMore/3.8/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.8/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.8/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113966 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.76
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114095 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.9.2
  manifests/s/stevencohn/OneMore/3.9.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.9.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.9.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114093 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.9
  manifests/s/stevencohn/OneMore/3.9/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.9/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.9/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114097 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.9.4
  manifests/s/stevencohn/OneMore/3.9.4/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.9.4/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.9.4/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113848 New version: Tencent.TencentMeetingRooms version 3.18.220.570
  manifests/t/Tencent/TencentMeetingRooms/3.18.220.570/Tencent.TencentMeetingRooms.installer.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.18.220.570/Tencent.TencentMeetingRooms.locale.en-US.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.18.220.570/Tencent.TencentMeetingRooms.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.18.220.570/Tencent.TencentMeetingRooms.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113545 Update version: AntiMicro.AntiMicro version 2.24-final
  manifests/a/AntiMicro/AntiMicro/2.24-final/AntiMicro.AntiMicro.installer.yaml
  manifests/a/AntiMicro/AntiMicro/2.24-final/AntiMicro.AntiMicro.locale.en-US.yaml
  manifests/a/AntiMicro/AntiMicro/2.24-final/AntiMicro.AntiMicro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate

#113870 Fix Bug in YamlCreate
  Tools/YamlCreate.ps1
Labels: Moderator-Approved, Project-File, Needs-Attention

#114056 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.16
  manifests/s/stevencohn/OneMore/3.16/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.16/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.16/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114062 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.19
  manifests/s/stevencohn/OneMore/3.19/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.19/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.19/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114055 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.15.2
  manifests/s/stevencohn/OneMore/3.15.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.15.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.15.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114068 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.20
  manifests/s/stevencohn/OneMore/3.20/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.20/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.20/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114079 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.4.2
  manifests/s/stevencohn/OneMore/3.4.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.4.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.4.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114076 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.30
  manifests/s/stevencohn/OneMore/3.30/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.30/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.30/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114067 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.19.5
  manifests/s/stevencohn/OneMore/3.19.5/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.19.5/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.19.5/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114072 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.26
  manifests/s/stevencohn/OneMore/3.26/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.26/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.26/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114060 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.18.2
  manifests/s/stevencohn/OneMore/3.18.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.18.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.18.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114059 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.18.1
  manifests/s/stevencohn/OneMore/3.18.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.18.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.18.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114034 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.19
  manifests/s/stevencohn/OneMore/2.19/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.19/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.19/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114036 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.19.2
  manifests/s/stevencohn/OneMore/2.19.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.19.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.19.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114110 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\4.17
  manifests/s/stevencohn/OneMore/4.17/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/4.17/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/4.17/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113981 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.93
  manifests/p/Phoner/PhonerLite/2.93/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.93/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.93/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113821 Remove Whitespace from Mozilla.Thunderbird 102.12.0
  manifests/m/Mozilla/Thunderbird/102.12.0/Mozilla.Thunderbird.installer.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#114118 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\4.7
  manifests/s/stevencohn/OneMore/4.7/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/4.7/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/4.7/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113888 Remove .validation file for XunLei.xunlei
  manifests/x/XunLei/xunlei/.validation
Labels: Moderator-Approved, Author-Not-Authorized, Needs-Attention

#113973 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.85.0
  manifests/p/Phoner/PhonerLite/2.85.0/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.85.0/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.85.0/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113935 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.45
  manifests/c/Cockos/REAPER/6.45/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.45/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.45/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113983 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.95
  manifests/p/Phoner/PhonerLite/2.95/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.95/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.95/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved

#113954 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.64
  manifests/c/Cockos/REAPER/6.64/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.64/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.64/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113929 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.39
  manifests/c/Cockos/REAPER/6.39/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.39/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.39/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113956 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.66
  manifests/c/Cockos/REAPER/6.66/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.66/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.66/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114057 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.17
  manifests/s/stevencohn/OneMore/3.17/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.17/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.17/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113787 Update: OSGeo.QGIS_LTR 3.28.9
  manifests/o/OSGeo/QGIS_LTR/3.28.9/OSGeo.QGIS_LTR.installer.yaml
  manifests/o/OSGeo/QGIS_LTR/3.28.9/OSGeo.QGIS_LTR.locale.en-US.yaml
  manifests/o/OSGeo/QGIS_LTR/3.28.9/OSGeo.QGIS_LTR.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#113789 Update JetBrains.Rider.installer.yaml for Rider 2023.1.4
  manifests/j/JetBrains/Rider/2023.1.4/JetBrains.Rider.installer.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#114149 New version: Element.Element 1.11.37
  manifests/e/Element/Element/1.11.37/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.37/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.37/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114043 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.11.2
  manifests/s/stevencohn/OneMore/3.11.2/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.11.2/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.11.2/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113985 Update D:\Git\winget-pkgs\manifests\p\Phoner\PhonerLite\2.97
  manifests/p/Phoner/PhonerLite/2.97/Phoner.PhonerLite.installer.yaml
  manifests/p/Phoner/PhonerLite/2.97/Phoner.PhonerLite.locale.en-US.yaml
  manifests/p/Phoner/PhonerLite/2.97/Phoner.PhonerLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114083 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.6
  manifests/s/stevencohn/OneMore/3.6/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.6/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.6/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#114032 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\2.17.1
  manifests/s/stevencohn/OneMore/2.17.1/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/2.17.1/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/2.17.1/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113959 Update D:\Git\winget-pkgs\manifests\c\Cockos\REAPER\6.69
  manifests/c/Cockos/REAPER/6.69/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.69/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.69/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113876 New version: Ruben2776.PicView version 1.9.5
  manifests/r/Ruben2776/PicView/1.9.5/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/1.9.5/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/1.9.5/Ruben2776.PicView.locale.zh-CN.yaml
  manifests/r/Ruben2776/PicView/1.9.5/Ruben2776.PicView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113886 New version: Docker.DockerCLI version 24.0.5
  manifests/d/Docker/DockerCLI/24.0.5/Docker.DockerCLI.installer.yaml
  manifests/d/Docker/DockerCLI/24.0.5/Docker.DockerCLI.locale.en-US.yaml
  manifests/d/Docker/DockerCLI/24.0.5/Docker.DockerCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113869 New version: Kangaroo 3.91.1.230801
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113776 New version: SomePythonThings.WingetUIStore version 2.0.3
  manifests/s/SomePythonThings/WingetUIStore/2.0.3/SomePythonThings.WingetUIStore.installer.yaml
  manifests/s/SomePythonThings/WingetUIStore/2.0.3/SomePythonThings.WingetUIStore.locale.en-US.yaml
  manifests/s/SomePythonThings/WingetUIStore/2.0.3/SomePythonThings.WingetUIStore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Installation-Error

#112787 New package: JeremyHu.Dust3D version 1.0.0-rc.9
  manifests/j/JeremyHu/Dust3D/1.0.0-rc.9/JeremyHu.Dust3D.installer.yaml
  manifests/j/JeremyHu/Dust3D/1.0.0-rc.9/JeremyHu.Dust3D.locale.en-US.yaml
  manifests/j/JeremyHu/Dust3D/1.0.0-rc.9/JeremyHu.Dust3D.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#113835 New version: nektos.act version 0.2.49
  manifests/n/nektos/act/0.2.49/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.49/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.49/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#113853 SagerNet.sing-box version 1.3.5
  manifests/s/SagerNet/sing-box/1.3.5/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.3.5/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.3.5/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#114058 Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\3.18
  manifests/s/stevencohn/OneMore/3.18/stevencohn.OneMore.installer.yaml
  manifests/s/stevencohn/OneMore/3.18/stevencohn.OneMore.locale.en-US.yaml
  manifests/s/stevencohn/OneMore/3.18/stevencohn.OneMore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#113880 Ares commander 24.1.2172
  manifests/g/Graebert/AresCommander/2024/24.1.2172/Graebert.AresCommander.2024.installer.yaml
  manifests/g/Graebert/AresCommander/2024/24.1.2172/Graebert.AresCommander.2024.locale.en-US.yaml
  manifests/g/Graebert/AresCommander/2024/24.1.2172/Graebert.AresCommander.2024.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
