Repository microsoft/winget-pkgs, pull requests merged in 2023-10, with the labels that each got.

#121516 New version: Jackett.Jackett version 0.21.946
  manifests/j/Jackett/Jackett/0.21.946/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.946/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.946/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121498 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121477 New version: Mp3tag.Mp3tag version 3.22b
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121478 New version: Tonec.InternetDownloadManager version 6.41.20
  manifests/t/Tonec/InternetDownloadManager/6.41.20/Tonec.InternetDownloadManager.installer.yaml
  manifests/t/Tonec/InternetDownloadManager/6.41.20/Tonec.InternetDownloadManager.locale.en-US.yaml
  manifests/t/Tonec/InternetDownloadManager/6.41.20/Tonec.InternetDownloadManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121615 Remove: Catsxp.Catsxp version 117.3.9.7
  manifests/c/Catsxp/Catsxp/117.3.9.7/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.7/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.7/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.7/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121614 Remove: Catsxp.Catsxp version 117.3.9.6
  manifests/c/Catsxp/Catsxp/117.3.9.6/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.6/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.6/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.6/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121611 Remove: Catsxp.Catsxp version 117.3.9.3
  manifests/c/Catsxp/Catsxp/117.3.9.3/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.3/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.3/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.3/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121612 Remove: Catsxp.Catsxp version 117.3.9.4
  manifests/c/Catsxp/Catsxp/117.3.9.4/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.4/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.4/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.4/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121450 New version: Facebook.Messenger version 196.0.0.4.210
  manifests/f/Facebook/Messenger/196.0.518282206/Facebook.Messenger.installer.yaml
  manifests/f/Facebook/Messenger/196.0.518282206/Facebook.Messenger.locale.en-US.yaml
  manifests/f/Facebook/Messenger/196.0.518282206/Facebook.Messenger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121451 Remove version: Facebook.Messenger version 187.0.478120702
  manifests/f/Facebook/Messenger/187.0.478120702/Facebook.Messenger.installer.yaml
  manifests/f/Facebook/Messenger/187.0.478120702/Facebook.Messenger.locale.en-US.yaml
  manifests/f/Facebook/Messenger/187.0.478120702/Facebook.Messenger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121678 New version: TheDocumentFoundation.LibreOffice version 7.6.2.1
  manifests/t/TheDocumentFoundation/LibreOffice/7.6.2.1/TheDocumentFoundation.LibreOffice.installer.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.6.2.1/TheDocumentFoundation.LibreOffice.locale.en-US.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.6.2.1/TheDocumentFoundation.LibreOffice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#120990 CloudNet 1.36.2.3
  manifests/c/cloudnet/cloudnet/1.36.2.3/cloudnet.cloudnet.installer.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.3/cloudnet.cloudnet.locale.zh-CN.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.3/cloudnet.cloudnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-2.5

#121260 New version: vim.vim.nightly version 9.0.1959
  manifests/v/vim/vim/nightly/9.0.1959/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1959/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1959/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121273 Add version: DenoLand.Deno version 1.33.3
  manifests/d/DenoLand/Deno/1.33.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.33.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.33.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121265 errata-ai.Vale version 2.29.1
  manifests/e/errata-ai/Vale/2.29.1/errata-ai.Vale.installer.yaml
  manifests/e/errata-ai/Vale/2.29.1/errata-ai.Vale.locale.en-US.yaml
  manifests/e/errata-ai/Vale/2.29.1/errata-ai.Vale.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121290 New version: Pylogmon.pot version 2.6.0
  manifests/p/Pylogmon/pot/2.6.0/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/2.6.0/Pylogmon.pot.locale.en-US.yaml
  manifests/p/Pylogmon/pot/2.6.0/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121377 Add version: DenoLand.Deno version 1.2.2
  manifests/d/DenoLand/Deno/1.2.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.2.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.2.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121373 Add version: DenoLand.Deno version 1.15.3
  manifests/d/DenoLand/Deno/1.15.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.15.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.15.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121371 Add version: DenoLand.Deno version 1.15.1
  manifests/d/DenoLand/Deno/1.15.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.15.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.15.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121315 Add version: DenoLand.Deno version 1.23.4
  manifests/d/DenoLand/Deno/1.23.4/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.23.4/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.23.4/DenoLand.Deno.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#121365 Add version: DenoLand.Deno version 1.13.2
  manifests/d/DenoLand/Deno/1.13.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.13.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.13.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121355 Add version: DenoLand.Deno version 1.11.0
  manifests/d/DenoLand/Deno/1.11.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.11.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.11.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121354 Add version: DenoLand.Deno version 1.10.3
  manifests/d/DenoLand/Deno/1.10.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.10.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.10.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121303 Add version: DenoLand.Deno version 1.26.2
  manifests/d/DenoLand/Deno/1.26.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.26.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.26.2/DenoLand.Deno.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#121352 Add version: DenoLand.Deno version 1.10.1
  manifests/d/DenoLand/Deno/1.10.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.10.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.10.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121350 Add version: DenoLand.Deno version 1.9.1
  manifests/d/DenoLand/Deno/1.9.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.9.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.9.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121344 Add version: DenoLand.Deno version 1.23.0
  manifests/d/DenoLand/Deno/1.23.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.23.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.23.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121343 Add version: DenoLand.Deno version 1.22.3
  manifests/d/DenoLand/Deno/1.22.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.22.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.22.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121342 Add version: DenoLand.Deno version 1.22.2
  manifests/d/DenoLand/Deno/1.22.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.22.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.22.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121328 Add version: DenoLand.Deno version 1.19.2
  manifests/d/DenoLand/Deno/1.19.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.19.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.19.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121336 Add version: DenoLand.Deno version 1.21.0
  manifests/d/DenoLand/Deno/1.21.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.21.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.21.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121384 Add version: DenoLand.Deno version 1.4.0
  manifests/d/DenoLand/Deno/1.4.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.4.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.4.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121387 Add version: DenoLand.Deno version 1.4.3
  manifests/d/DenoLand/Deno/1.4.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.4.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.4.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121386 Add version: DenoLand.Deno version 1.4.2
  manifests/d/DenoLand/Deno/1.4.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.4.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.4.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121388 Add version: DenoLand.Deno version 1.4.4
  manifests/d/DenoLand/Deno/1.4.4/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.4.4/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.4.4/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121389 Add version: DenoLand.Deno version 1.4.5
  manifests/d/DenoLand/Deno/1.4.5/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.4.5/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.4.5/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121391 Add version: DenoLand.Deno version 1.5.0
  manifests/d/DenoLand/Deno/1.5.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.5.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.5.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121396 Add version: DenoLand.Deno version 1.6.0
  manifests/d/DenoLand/Deno/1.6.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.6.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.6.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121401 Add version: DenoLand.Deno version 1.7.1
  manifests/d/DenoLand/Deno/1.7.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.7.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.7.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121404 Add version: DenoLand.Deno version 1.7.5
  manifests/d/DenoLand/Deno/1.7.5/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.7.5/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.7.5/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121415 Add version: DenoLand.Deno version 0.42.0
  manifests/d/DenoLand/Deno/0.42.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/0.42.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/0.42.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121402 Add version: DenoLand.Deno version 1.7.2
  manifests/d/DenoLand/Deno/1.7.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.7.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.7.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121418 Add version: DenoLand.Deno version 1.0.0-rc3
  manifests/d/DenoLand/Deno/1.0.0-rc3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.0.0-rc3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.0.0-rc3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121398 Add version: DenoLand.Deno version 1.6.2
  manifests/d/DenoLand/Deno/1.6.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.6.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.6.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121416 Add version: DenoLand.Deno version 1.0.0-rc1
  manifests/d/DenoLand/Deno/1.0.0-rc1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.0.0-rc1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.0.0-rc1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121425 Add version: DenoLand.Deno version 1.0.5
  manifests/d/DenoLand/Deno/1.0.5/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.0.5/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.0.5/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121426 Tgstation.Server version 5.16.1
  manifests/t/Tgstation/Server/5.16.1/Tgstation.Server.installer.yaml
  manifests/t/Tgstation/Server/5.16.1/Tgstation.Server.locale.en-US.yaml
  manifests/t/Tgstation/Server/5.16.1/Tgstation.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121421 Add version: DenoLand.Deno version 1.0.2
  manifests/d/DenoLand/Deno/1.0.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.0.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.0.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121427 Add version: DenoLand.Deno version 1.1.0
  manifests/d/DenoLand/Deno/1.1.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.1.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.1.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121429 Add version: DenoLand.Deno version 1.2.0
  manifests/d/DenoLand/Deno/1.2.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.2.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.2.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121378 Add version: DenoLand.Deno version 1.2.3
  manifests/d/DenoLand/Deno/1.2.3/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.2.3/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.2.3/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121428 Add version: DenoLand.Deno version 1.2.1
  manifests/d/DenoLand/Deno/1.2.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.2.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.2.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121431 Add version: DenoLand.Deno version 1.1.2
  manifests/d/DenoLand/Deno/1.1.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.1.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.1.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121382 Add version: DenoLand.Deno version 1.3.2
  manifests/d/DenoLand/Deno/1.3.2/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.3.2/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.3.2/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121432 Add version: DenoLand.Deno version 1.1.1
  manifests/d/DenoLand/Deno/1.1.1/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.1.1/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.1.1/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121363 Add version: DenoLand.Deno version 1.13.0
  manifests/d/DenoLand/Deno/1.13.0/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.13.0/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.13.0/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#121434 New version: PerfectWorld.PerfectWorldArena version 1.0.23093011
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23093011/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23093011/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23093011/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23093011/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121439 New version: Kiwix.Wikivoyage version 2.6.8.0
  manifests/k/Kiwix/Wikivoyage/2.6.8.0/Kiwix.Wikivoyage.installer.yaml
  manifests/k/Kiwix/Wikivoyage/2.6.8.0/Kiwix.Wikivoyage.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/2.6.8.0/Kiwix.Wikivoyage.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121440 New version: Kiwix.Wikivoyage.Electron version 2.6.8-E
  manifests/k/Kiwix/Wikivoyage/Electron/2.6.8-E/Kiwix.Wikivoyage.Electron.installer.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.6.8-E/Kiwix.Wikivoyage.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.6.8-E/Kiwix.Wikivoyage.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121441 New version: GiulioSorrentino.numeronesfortuneinavalonia version 2.0.1
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0.1/GiulioSorrentino.numeronesfortuneinavalonia.installer.yaml
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0.1/GiulioSorrentino.numeronesfortuneinavalonia.locale.en-US.yaml
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0.1/GiulioSorrentino.numeronesfortuneinavalonia.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121442 New version: GiulioSorrentino.Latorredibabele version 1.1.1
  manifests/g/GiulioSorrentino/Latorredibabele/1.1.1/GiulioSorrentino.Latorredibabele.installer.yaml
  manifests/g/GiulioSorrentino/Latorredibabele/1.1.1/GiulioSorrentino.Latorredibabele.locale.it-IT.yaml
  manifests/g/GiulioSorrentino/Latorredibabele/1.1.1/GiulioSorrentino.Latorredibabele.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121448 the-sz.PortScan version 1.95
  manifests/t/the-sz/PortScan/1.95/the-sz.PortScan.installer.yaml
  manifests/t/the-sz/PortScan/1.95/the-sz.PortScan.locale.en-US.yaml
  manifests/t/the-sz/PortScan/1.95/the-sz.PortScan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121446 New version: GiulioSorrentino.WinDateFrom version 4.1.1
  manifests/g/GiulioSorrentino/WinDateFrom/4.1.1/GiulioSorrentino.WinDateFrom.installer.yaml
  manifests/g/GiulioSorrentino/WinDateFrom/4.1.1/GiulioSorrentino.WinDateFrom.locale.en-US.yaml
  manifests/g/GiulioSorrentino/WinDateFrom/4.1.1/GiulioSorrentino.WinDateFrom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121452 Fix GnuCash installer URL
  manifests/g/GnuCash/GnuCash/5.4/GnuCash.GnuCash.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121454 Remove version: Microsoft.WindowsSDK.10.0.22621 version 10.0.22621.2
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121455 Delete manifests/m/Mozilla/Thunderbird/Beta/116.0b7 directory
  manifests/m/Mozilla/Thunderbird/Beta/116.0b7/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/116.0b7/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/116.0b7/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121456 Delete manifests/m/Mozilla/Thunderbird/Beta/117.0b1 directory
  manifests/m/Mozilla/Thunderbird/Beta/117.0b1/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/117.0b1/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/117.0b1/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121458 Delete manifests/m/Mozilla/Thunderbird/Beta/117.0b6 directory
  manifests/m/Mozilla/Thunderbird/Beta/117.0b6/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/117.0b6/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/117.0b6/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121459 Delete manifests/m/Mozilla/Thunderbird/Beta/118.0b1 directory
  manifests/m/Mozilla/Thunderbird/Beta/118.0b1/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b1/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b1/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121460 Delete manifests/m/Mozilla/Thunderbird/Beta/118.0b2 directory
  manifests/m/Mozilla/Thunderbird/Beta/118.0b2/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b2/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b2/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121462 New version: igoogolx.lux version 0.8.0
  manifests/i/igoogolx/lux/0.8.0/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.8.0/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.8.0/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121472 Libretro.RetroArch version 1.16.0.0
  manifests/l/Libretro/RetroArch/1.16.0.0/Libretro.RetroArch.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121463 ALCPU.CoreTemp version 1.18.1.0
  manifests/a/ALCPU/CoreTemp/1.18.1.0/ALCPU.CoreTemp.installer.yaml
  manifests/a/ALCPU/CoreTemp/1.18.1.0/ALCPU.CoreTemp.locale.en-US.yaml
  manifests/a/ALCPU/CoreTemp/1.18.1.0/ALCPU.CoreTemp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121473 New version: Brave.Brave.Dev version 117.1.59.104
  manifests/b/Brave/Brave/Dev/117.1.59.104/Brave.Brave.Dev.installer.yaml
  manifests/b/Brave/Brave/Dev/117.1.59.104/Brave.Brave.Dev.locale.en-US.yaml
  manifests/b/Brave/Brave/Dev/117.1.59.104/Brave.Brave.Dev.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Dev/117.1.59.104/Brave.Brave.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121433 New version: Microsoft.EdgeDriver version 117.0.2045.47
  manifests/m/Microsoft/EdgeDriver/117.0.2045.47/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/117.0.2045.47/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/117.0.2045.47/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/117.0.2045.47/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121492 New version: ElijahLopez.MusicCaster version 5.13.39
  manifests/e/ElijahLopez/MusicCaster/5.13.39/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.39/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.39/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121491 New version: igoogolx.lux version 0.8.1
  manifests/i/igoogolx/lux/0.8.1/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.8.1/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.8.1/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121489 New version: nektos.act version 0.2.52
  manifests/n/nektos/act/0.2.52/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.52/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.52/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121487 Fix Version: OpenSSL Light v3.0.11: Remove display version
  manifests/s/ShiningLight/OpenSSL/Light/3.0.11/ShiningLight.OpenSSL.Light.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121488 Fix Version: OpenSSL Light v3.1.3: Remove display version
  manifests/s/ShiningLight/OpenSSL/Light/3.1.3/ShiningLight.OpenSSL.Light.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121484 New version: electerm.electerm version 1.33.36
  manifests/e/electerm/electerm/1.33.36/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.33.36/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.33.36/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121486 Fix Version: OpenSSL Light v1.11.w: Remove display version
  manifests/s/ShiningLight/OpenSSL/Light/1.1.1w/ShiningLight.OpenSSL.Light.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121480 New version: Alibaba.QuarkCloudDrive version 2.5.54
  manifests/a/Alibaba/QuarkCloudDrive/2.5.54/Alibaba.QuarkCloudDrive.installer.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.54/Alibaba.QuarkCloudDrive.locale.en-US.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.54/Alibaba.QuarkCloudDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.54/Alibaba.QuarkCloudDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121475 Update FileBot to 5.1.1
  manifests/p/PointPlanck/FileBot/5.1.1/PointPlanck.FileBot.installer.yaml
  manifests/p/PointPlanck/FileBot/5.1.1/PointPlanck.FileBot.locale.en-US.yaml
  manifests/p/PointPlanck/FileBot/5.1.1/PointPlanck.FileBot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121474 New version: Catsxp.Catsxp version 118.3.10.1
  manifests/c/Catsxp/Catsxp/118.3.10.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/118.3.10.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/118.3.10.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/118.3.10.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121517 New version: PerfectWorld.PerfectWorldArena version 1.0.23100111
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23100111/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23100111/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23100111/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23100111/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121519 New version: chrisant996.Clink version 1.5.7
  manifests/c/chrisant996/Clink/1.5.7/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.5.7/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.5.7/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121521 New version: AquaSecurity.Trivy version 0.45.1
  manifests/a/AquaSecurity/Trivy/0.45.1/AquaSecurity.Trivy.installer.yaml
  manifests/a/AquaSecurity/Trivy/0.45.1/AquaSecurity.Trivy.locale.en-US.yaml
  manifests/a/AquaSecurity/Trivy/0.45.1/AquaSecurity.Trivy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121522 New version: Infracost.Infracost version 0.10.29
  manifests/i/Infracost/Infracost/0.10.29/Infracost.Infracost.installer.yaml
  manifests/i/Infracost/Infracost/0.10.29/Infracost.Infracost.locale.en-US.yaml
  manifests/i/Infracost/Infracost/0.10.29/Infracost.Infracost.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121525 eloston.ungoogled-chromium version 117.0.5938.132
  manifests/e/eloston/ungoogled-chromium/117.0.5938.132/eloston.ungoogled-chromium.installer.yaml
  manifests/e/eloston/ungoogled-chromium/117.0.5938.132/eloston.ungoogled-chromium.locale.en-US.yaml
  manifests/e/eloston/ungoogled-chromium/117.0.5938.132/eloston.ungoogled-chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121527 Update version: Brave.Brave.Nightly version 118.1.60.67
  manifests/b/Brave/Brave/Nightly/118.1.60.67/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/118.1.60.67/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/118.1.60.67/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/118.1.60.67/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121528 New version: commercialhaskell.stack version 2.13.1
  manifests/c/commercialhaskell/stack/2.13.1/commercialhaskell.stack.installer.yaml
  manifests/c/commercialhaskell/stack/2.13.1/commercialhaskell.stack.locale.en-US.yaml
  manifests/c/commercialhaskell/stack/2.13.1/commercialhaskell.stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121529 New version: Discord.Discord.Canary version 1.0.78
  manifests/d/Discord/Discord/Canary/1.0.78/Discord.Discord.Canary.installer.yaml
  manifests/d/Discord/Discord/Canary/1.0.78/Discord.Discord.Canary.locale.en-US.yaml
  manifests/d/Discord/Discord/Canary/1.0.78/Discord.Discord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121526 New version: Bitwarden.Bitwarden version 2023.9.1
  manifests/b/Bitwarden/Bitwarden/2023.9.1/Bitwarden.Bitwarden.installer.yaml
  manifests/b/Bitwarden/Bitwarden/2023.9.1/Bitwarden.Bitwarden.locale.en-US.yaml
  manifests/b/Bitwarden/Bitwarden/2023.9.1/Bitwarden.Bitwarden.locale.zh-CN.yaml
  manifests/b/Bitwarden/Bitwarden/2023.9.1/Bitwarden.Bitwarden.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121531 Update version: DoltHub.Dolt version 1.17.1
  manifests/d/DoltHub/Dolt/1.17.1/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.17.1/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.17.1/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121534 New version: Google.Chrome.Canary version 119.0.6041.0
  manifests/g/Google/Chrome/Canary/119.0.6041.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/119.0.6041.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/119.0.6041.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/119.0.6041.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121535 New version: Google.Chrome.Dev version 119.0.6034.6
  manifests/g/Google/Chrome/Dev/119.0.6034.6/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/119.0.6034.6/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/119.0.6034.6/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/119.0.6034.6/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121537 New version: HearthSim.HearthstoneDeckTracker version 1.22.6
  manifests/h/HearthSim/HearthstoneDeckTracker/1.22.6/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.22.6/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.22.6/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121538 New version: ImageMagick.ImageMagick version 7.1.1.19
  manifests/i/ImageMagick/ImageMagick/7.1.1.19/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.1.19/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.1.19/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121539 New version: IndigoByte.DrExplain version 6.6.1280
  manifests/i/IndigoByte/DrExplain/6.6.1280/IndigoByte.DrExplain.installer.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1280/IndigoByte.DrExplain.locale.en-US.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1280/IndigoByte.DrExplain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121541 the-sz.Newfield version 1.04
  manifests/t/the-sz/Newfield/1.04/the-sz.Newfield.installer.yaml
  manifests/t/the-sz/Newfield/1.04/the-sz.Newfield.locale.en-US.yaml
  manifests/t/the-sz/Newfield/1.04/the-sz.Newfield.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121544 Update version: KiCad.KiCad version 7.0.7
  manifests/k/KiCad/KiCad/7.0.7/KiCad.KiCad.installer.yaml
  manifests/k/KiCad/KiCad/7.0.7/KiCad.KiCad.locale.en-US.yaml
  manifests/k/KiCad/KiCad/7.0.7/KiCad.KiCad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121548 New version: Zettlr.Zettlr.Beta version 3.0.0-beta.7
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.7/Zettlr.Zettlr.Beta.installer.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.7/Zettlr.Zettlr.Beta.locale.en-US.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.7/Zettlr.Zettlr.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121549 New version: Zettlr.Zettlr.Beta version 3.0.0-beta.8
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.8/Zettlr.Zettlr.Beta.installer.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.8/Zettlr.Zettlr.Beta.locale.en-US.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.8/Zettlr.Zettlr.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121550 New version: Zettlr.Zettlr.Beta version 3.0.0-beta.6
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.6/Zettlr.Zettlr.Beta.installer.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.6/Zettlr.Zettlr.Beta.locale.en-US.yaml
  manifests/z/Zettlr/Zettlr/Beta/3.0.0-beta.6/Zettlr.Zettlr.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121552 New version: YuzuEmu.Yuzu.Mainline 1549
  manifests/y/YuzuEmu/Yuzu/Mainline/1549/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1549/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1549/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121551 New version: YuzuEmu.Yuzu.Mainline 1546
  manifests/y/YuzuEmu/Yuzu/Mainline/1546/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1546/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1546/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121558 New version: YuzuEmu.Yuzu.Mainline 1551
  manifests/y/YuzuEmu/Yuzu/Mainline/1551/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1551/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1551/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121559 New version: YuzuEmu.Yuzu.Mainline 1552
  manifests/y/YuzuEmu/Yuzu/Mainline/1552/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1552/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1552/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121560 New version: YuzuEmu.Yuzu.Mainline 1553
  manifests/y/YuzuEmu/Yuzu/Mainline/1553/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1553/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1553/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121561 New version: YuzuEmu.Yuzu.Mainline 1554
  manifests/y/YuzuEmu/Yuzu/Mainline/1554/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1554/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1554/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121563 New version: YuzuEmu.Yuzu.Mainline 1556
  manifests/y/YuzuEmu/Yuzu/Mainline/1556/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1556/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1556/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121564 New version: YuzuEmu.Yuzu.Mainline 1557
  manifests/y/YuzuEmu/Yuzu/Mainline/1557/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1557/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1557/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121565 New version: YuzuEmu.Yuzu.Mainline 1558
  manifests/y/YuzuEmu/Yuzu/Mainline/1558/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1558/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1558/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121567 New version: YuzuEmu.Yuzu.Mainline 1560
  manifests/y/YuzuEmu/Yuzu/Mainline/1560/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1560/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1560/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121566 New version: YuzuEmu.Yuzu.Mainline 1559
  manifests/y/YuzuEmu/Yuzu/Mainline/1559/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1559/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1559/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121569 New version: YuzuEmu.Yuzu.Mainline 1562
  manifests/y/YuzuEmu/Yuzu/Mainline/1562/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1562/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1562/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121570 New version: YuzuEmu.Yuzu.Mainline 1563
  manifests/y/YuzuEmu/Yuzu/Mainline/1563/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1563/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1563/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121571 New version: YuzuEmu.Yuzu.Mainline 1564
  manifests/y/YuzuEmu/Yuzu/Mainline/1564/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1564/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1564/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121572 New version: YuzuEmu.Yuzu.Mainline 1565
  manifests/y/YuzuEmu/Yuzu/Mainline/1565/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1565/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1565/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121575 New version: YuzuEmu.Yuzu.Mainline 1566
  manifests/y/YuzuEmu/Yuzu/Mainline/1566/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1566/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1566/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121576 New version: YuzuEmu.Yuzu.Mainline 1567
  manifests/y/YuzuEmu/Yuzu/Mainline/1567/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1567/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1567/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121577 New version: YuzuEmu.Yuzu.Mainline 1568
  manifests/y/YuzuEmu/Yuzu/Mainline/1568/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1568/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1568/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121579 New version: YuzuEmu.Yuzu.Mainline 1570
  manifests/y/YuzuEmu/Yuzu/Mainline/1570/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1570/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1570/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121580 New version: YuzuEmu.Yuzu.Mainline 1571
  manifests/y/YuzuEmu/Yuzu/Mainline/1571/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1571/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1571/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121581 New version: YuzuEmu.Yuzu.Mainline 1572
  manifests/y/YuzuEmu/Yuzu/Mainline/1572/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1572/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1572/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121582 New version: YuzuEmu.Yuzu.Mainline 1573
  manifests/y/YuzuEmu/Yuzu/Mainline/1573/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1573/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1573/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121583 New version: YuzuEmu.Yuzu.Mainline 1574
  manifests/y/YuzuEmu/Yuzu/Mainline/1574/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1574/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1574/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121585 New version: Squiid version 1.1.0
  manifests/i/ImaginaryInfinity/Squiid/1.1.0/ImaginaryInfinity.Squiid.installer.yaml
  manifests/i/ImaginaryInfinity/Squiid/1.1.0/ImaginaryInfinity.Squiid.locale.en-US.yaml
  manifests/i/ImaginaryInfinity/Squiid/1.1.0/ImaginaryInfinity.Squiid.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121589 New version: Redisant.MQTTAssistant version 1.1.4.2
  manifests/r/Redisant/MQTTAssistant/1.1.4.2/Redisant.MQTTAssistant.installer.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.2/Redisant.MQTTAssistant.locale.en-US.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.2/Redisant.MQTTAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.2/Redisant.MQTTAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121590 Update: EuSoft.Frhelper version 13.0.0.0
  manifests/e/EuSoft/Frhelper/13.0.0.0/EuSoft.Frhelper.installer.yaml
  manifests/e/EuSoft/Frhelper/13.0.0.0/EuSoft.Frhelper.locale.en-US.yaml
  manifests/e/EuSoft/Frhelper/13.0.0.0/EuSoft.Frhelper.locale.zh-CN.yaml
  manifests/e/EuSoft/Frhelper/13.0.0.0/EuSoft.Frhelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121591 ReleaseNotes: Tencent.TencentMeeting version 3.19.30.495
  manifests/t/Tencent/TencentMeeting/3.19.30.495/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.19.30.495/Tencent.TencentMeeting.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121592 Update: EuSoft.Dehelper version 13.0.0.0
  manifests/e/EuSoft/Dehelper/13.0.0.0/EuSoft.Dehelper.installer.yaml
  manifests/e/EuSoft/Dehelper/13.0.0.0/EuSoft.Dehelper.locale.en-US.yaml
  manifests/e/EuSoft/Dehelper/13.0.0.0/EuSoft.Dehelper.locale.zh-CN.yaml
  manifests/e/EuSoft/Dehelper/13.0.0.0/EuSoft.Dehelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121596 New version: vim.vim.nightly version 9.0.1968
  manifests/v/vim/vim/nightly/9.0.1968/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1968/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1968/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121598 PTRTECH.UVtools version 4.0.2
  manifests/p/PTRTECH/UVtools/4.0.2/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/4.0.2/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/4.0.2/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121599 New version: Ferdium.Ferdium.Nightly version 6.5.0-nightly.21
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.21/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.21/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.21/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121602 New version: dotPDNLLC.paintdotnet version 5.0.10
  manifests/d/dotPDNLLC/paintdotnet/5.0.10/dotPDNLLC.paintdotnet.installer.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.10/dotPDNLLC.paintdotnet.locale.en-US.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.10/dotPDNLLC.paintdotnet.locale.zh-CN.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.10/dotPDNLLC.paintdotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121605 New version: Google.Chrome.Canary version 119.0.6042.0
  manifests/g/Google/Chrome/Canary/119.0.6042.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/119.0.6042.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/119.0.6042.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/119.0.6042.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121610 New version: NetEase.YoudaoNote version 7.2.12
  manifests/n/NetEase/YoudaoNote/7.2.12/NetEase.YoudaoNote.installer.yaml
  manifests/n/NetEase/YoudaoNote/7.2.12/NetEase.YoudaoNote.locale.en-US.yaml
  manifests/n/NetEase/YoudaoNote/7.2.12/NetEase.YoudaoNote.locale.zh-CN.yaml
  manifests/n/NetEase/YoudaoNote/7.2.12/NetEase.YoudaoNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121616 Remove version: Microsoft.PCManager.CN version 1.2.6.3
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121618 Remove version: Microsoft.PCManager.CN version 1.2.7.2
  manifests/m/Microsoft/PCManager/CN/1.2.7.2/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.7.2/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.7.2/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.7.2/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121620 Remove version: Microsoft.PCManager.CN version 1.2.9.3
  manifests/m/Microsoft/PCManager/CN/1.2.9.3/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.3/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.3/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.3/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121621 Remove version: Microsoft.PCManager.CN version 1.2.9.7
  manifests/m/Microsoft/PCManager/CN/1.2.9.7/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.7/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.7/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.7/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#121622 Remove version: Microsoft.PCManager.CN version 3.0.0.2
  manifests/m/Microsoft/PCManager/CN/3.0.0.2/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/3.0.0.2/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/3.0.0.2/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/3.0.0.2/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#121423 New version: cURL.cURL version 8.3.0
  manifests/c/cURL/cURL/8.3.0/cURL.cURL.installer.yaml
  manifests/c/cURL/cURL/8.3.0/cURL.cURL.locale.en-US.yaml
  manifests/c/cURL/cURL/8.3.0/cURL.cURL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#121461 Delete manifests/m/Mozilla/Thunderbird/Beta/118.0b6 directory
  manifests/m/Mozilla/Thunderbird/Beta/118.0b6/Mozilla.Thunderbird.Beta.installer.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b6/Mozilla.Thunderbird.Beta.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/Beta/118.0b6/Mozilla.Thunderbird.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121623 Remove version: Microsoft.PCManager.CN version 3.2.2.0
  manifests/m/Microsoft/PCManager/CN/3.2.2.0/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.2.0/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.2.0/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.2.0/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121624 Remove version: Microsoft.PCManager.CN version 3.2.3.0
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.locale.es-ES.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.locale.ja-JP.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.locale.zh-TW.yaml
  manifests/m/Microsoft/PCManager/CN/3.2.3.0/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121626 Remove version: Microsoft.PCManager.CN version 3.4.2.0
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.es-ES.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.ja-JP.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.locale.zh-TW.yaml
  manifests/m/Microsoft/PCManager/CN/3.4.2.0/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#121686 Microsoft.VisualStudioCode_v1.82.3
  manifests/m/Microsoft/VisualStudioCode/1.82.3/Microsoft.VisualStudioCode.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/1.82.3/Microsoft.VisualStudioCode.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/1.82.3/Microsoft.VisualStudioCode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
