Repository microsoft/winget-pkgs, pull requests merged in 2023-03, with the labels that each got.

#98067 New version: Jackett.Jackett version 0.20.3411
  manifests/j/Jackett/Jackett/0.20.3411/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.3411/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.3411/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98069 Update: KDE.Kate version 22.12.2
  manifests/k/KDE/Kate/22.12.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98038 New version: Google.Chrome.Canary version 113.0.5624.0 [FP-O]
  manifests/g/Google/Chrome/Canary/113.0.5624.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/113.0.5624.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/113.0.5624.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/113.0.5624.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97959 New version: Amazon.SAM-CLI version 1.75.0
  manifests/a/Amazon/SAM-CLI/1.75.0/Amazon.SAM-CLI.installer.yaml
  manifests/a/Amazon/SAM-CLI/1.75.0/Amazon.SAM-CLI.locale.en-US.yaml
  manifests/a/Amazon/SAM-CLI/1.75.0/Amazon.SAM-CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98074 Add Kubernetes.kubectl 1.26.2
  manifests/k/Kubernetes/kubectl/1.26.2/Kubernetes.kubectl.installer.yaml
  manifests/k/Kubernetes/kubectl/1.26.2/Kubernetes.kubectl.locale.en-US.yaml
  manifests/k/Kubernetes/kubectl/1.26.2/Kubernetes.kubectl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97871 OpenAL.OpenAL version 1.1
  manifests/o/OpenAL/OpenAL/1.1/OpenAL.OpenAL.installer.yaml
  manifests/o/OpenAL/OpenAL/1.1/OpenAL.OpenAL.locale.en-US.yaml
  manifests/o/OpenAL/OpenAL/1.1/OpenAL.OpenAL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98048 New version: Datronicsoft.SpacedeskDriver.Server version 1.0.62.0
  manifests/d/Datronicsoft/SpacedeskDriver/Server/1.0.62.0/Datronicsoft.SpacedeskDriver.Server.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/1.0.62.0/Datronicsoft.SpacedeskDriver.Server.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/1.0.62.0/Datronicsoft.SpacedeskDriver.Server.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#98113 Delete manifests/n/NextDNS/NextDNS/Prerelease/3.0.0 directory
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.0/NextDNS.NextDNS.Prerelease.installer.yaml
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.0/NextDNS.NextDNS.Prerelease.locale.en-US.yaml
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.0/NextDNS.NextDNS.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98114 Delete manifests/n/NextDNS/NextDNS/Prerelease/3.0.4 directory
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.4/NextDNS.NextDNS.Prerelease.installer.yaml
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.4/NextDNS.NextDNS.Prerelease.locale.en-US.yaml
  manifests/n/NextDNS/NextDNS/Prerelease/3.0.4/NextDNS.NextDNS.Prerelease.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98115 Delete manifests/o/ONLYOFFICE/DesktopEditors/7.3.0.1 directory
  manifests/o/ONLYOFFICE/DesktopEditors/7.3.0.1/ONLYOFFICE.DesktopEditors.installer.yaml
  manifests/o/ONLYOFFICE/DesktopEditors/7.3.0.1/ONLYOFFICE.DesktopEditors.locale.en-US.yaml
  manifests/o/ONLYOFFICE/DesktopEditors/7.3.0.1/ONLYOFFICE.DesktopEditors.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98073 New package: daynix.UsbDk version 1.0.22
  manifests/d/daynix/UsbDk/1.0.22/daynix.UsbDk.installer.yaml
  manifests/d/daynix/UsbDk/1.0.22/daynix.UsbDk.locale.en-US.yaml
  manifests/d/daynix/UsbDk/1.0.22/daynix.UsbDk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#98101 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98108 New version: PortSwigger.BurpSuite.Professional version 2023.1.3
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98107 New version: PortSwigger.BurpSuite.Community version 2023.1.3
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98106 New version: RaspberryPiFoundation.RaspberryPiImager version 1.7.4
  manifests/r/RaspberryPiFoundation/RaspberryPiImager/1.7.4/RaspberryPiFoundation.RaspberryPiImager.installer.yaml
  manifests/r/RaspberryPiFoundation/RaspberryPiImager/1.7.4/RaspberryPiFoundation.RaspberryPiImager.locale.en-US.yaml
  manifests/r/RaspberryPiFoundation/RaspberryPiImager/1.7.4/RaspberryPiFoundation.RaspberryPiImager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98117 CPUID.CPU-Z version 2.05
  manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.installer.yaml
  manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.locale.zh-CN.yaml
  manifests/c/CPUID/CPU-Z/2.05/CPUID.CPU-Z.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98105 New version: Plex.Plex version 1.65.1
  manifests/p/Plex/Plex/1.65.1/Plex.Plex.installer.yaml
  manifests/p/Plex/Plex/1.65.1/Plex.Plex.locale.en-US.yaml
  manifests/p/Plex/Plex/1.65.1/Plex.Plex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98127 Microsoft.VisualStudioCode_v1.76.0
  manifests/m/Microsoft/VisualStudioCode/1.76.0/Microsoft.VisualStudioCode.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/1.76.0/Microsoft.VisualStudioCode.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/1.76.0/Microsoft.VisualStudioCode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97402 Guru3D.Afterburner version 4.6.5.Beta4
  manifests/g/Guru3D/Afterburner/4.6.5.Beta4/Guru3D.Afterburner.installer.yaml
  manifests/g/Guru3D/Afterburner/4.6.5.Beta4/Guru3D.Afterburner.locale.en-US.yaml
  manifests/g/Guru3D/Afterburner/4.6.5.Beta4/Guru3D.Afterburner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98121 Delete manifests/n/NextDNS/NextDNS/Prerelease directory
  manifests/n/NextDNS/NextDNS/Prerelease/.validation
Labels: Moderator-Approved, Author-Not-Authorized

#97920 New version: Nota.Gyazo version 4.6.1.0
  manifests/n/Nota/Gyazo/4.6.1.0/Nota.Gyazo.installer.yaml
  manifests/n/Nota/Gyazo/4.6.1.0/Nota.Gyazo.locale.en-US.yaml
  manifests/n/Nota/Gyazo/4.6.1.0/Nota.Gyazo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97923 New version: SomePythonThings.WingetUIStore version 1.6.2
  manifests/s/SomePythonThings/WingetUIStore/1.6.2/SomePythonThings.WingetUIStore.installer.yaml
  manifests/s/SomePythonThings/WingetUIStore/1.6.2/SomePythonThings.WingetUIStore.locale.en-US.yaml
  manifests/s/SomePythonThings/WingetUIStore/1.6.2/SomePythonThings.WingetUIStore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Installation-Error

#97952 New version: Python.Python.3.12 3.12.0a5
  manifests/p/Python/Python/3/12/3.12.0a5/Python.Python.3.12.installer.yaml
  manifests/p/Python/Python/3/12/3.12.0a5/Python.Python.3.12.locale.en-US.yaml
  manifests/p/Python/Python/3/12/3.12.0a5/Python.Python.3.12.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97953 New version: Alibaba.DingTalk version 7.0.10-Release.2279103
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97954 New version: B3log.SiYuan version 2.7.7
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97955 New version: Billfish.Billfish version 3.0.8.7
  manifests/b/Billfish/Billfish/3.0.8.7/Billfish.Billfish.installer.yaml
  manifests/b/Billfish/Billfish/3.0.8.7/Billfish.Billfish.locale.en-US.yaml
  manifests/b/Billfish/Billfish/3.0.8.7/Billfish.Billfish.locale.zh-CN.yaml
  manifests/b/Billfish/Billfish/3.0.8.7/Billfish.Billfish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97956 New version: Jigsaw.OutlineManager version manager-v1.14.0
  manifests/j/Jigsaw/OutlineManager/manager-v1.14.0/Jigsaw.OutlineManager.installer.yaml
  manifests/j/Jigsaw/OutlineManager/manager-v1.14.0/Jigsaw.OutlineManager.locale.en-US.yaml
  manifests/j/Jigsaw/OutlineManager/manager-v1.14.0/Jigsaw.OutlineManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97957 New version: KirillOsenkov.MSBuildStructuredLogViewer version 2.1.787
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.787/KirillOsenkov.MSBuildStructuredLogViewer.installer.yaml
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.787/KirillOsenkov.MSBuildStructuredLogViewer.locale.en-US.yaml
  manifests/k/KirillOsenkov/MSBuildStructuredLogViewer/2.1.787/KirillOsenkov.MSBuildStructuredLogViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97958 New version: Discord.Discord.Development version 1.0.711 [FP-D]
  manifests/d/Discord/Discord/Development/1.0.711/Discord.Discord.Development.installer.yaml
  manifests/d/Discord/Discord/Development/1.0.711/Discord.Discord.Development.locale.en-US.yaml
  manifests/d/Discord/Discord/Development/1.0.711/Discord.Discord.Development.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97960 New version: Astronomer.Astro version 1.11.0
  manifests/a/Astronomer/Astro/1.11.0/Astronomer.Astro.installer.yaml
  manifests/a/Astronomer/Astro/1.11.0/Astronomer.Astro.locale.en-US.yaml
  manifests/a/Astronomer/Astro/1.11.0/Astronomer.Astro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97963 New version: Wondershare.DemoCreator version 6.5.4
  manifests/w/Wondershare/DemoCreator/6.5.4/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/6.5.4/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/6.5.4/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/6.5.4/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97964 MuhammadFareezIqmal.IIUMSchedule version 1.1.1
  manifests/m/MuhammadFareezIqmal/IIUMSchedule/1.1.1/MuhammadFareezIqmal.IIUMSchedule.installer.yaml
  manifests/m/MuhammadFareezIqmal/IIUMSchedule/1.1.1/MuhammadFareezIqmal.IIUMSchedule.locale.en-US.yaml
  manifests/m/MuhammadFareezIqmal/IIUMSchedule/1.1.1/MuhammadFareezIqmal.IIUMSchedule.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97972 New version: Bilibili.Livehime version 4.38.1.4464 [FP-O]
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.installer.yaml
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.locale.zh-CN.yaml
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97974 Elk.Elk version 0.4.0
  manifests/e/Elk/Elk/0.4.0/Elk.Elk.installer.yaml
  manifests/e/Elk/Elk/0.4.0/Elk.Elk.locale.en-US.yaml
  manifests/e/Elk/Elk/0.4.0/Elk.Elk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97975 New version: c0re100.qBittorrent-Enhanced-Edition version 4.5.2.10
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.5.2.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.5.2.10/c0re100.qBittorrent-Enhanced-Edition.locale.en-US.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.5.2.10/c0re100.qBittorrent-Enhanced-Edition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97981 New version: GOG.Galaxy version 2.0.60.2
  manifests/g/GOG/Galaxy/2.0.60.2/GOG.Galaxy.installer.yaml
  manifests/g/GOG/Galaxy/2.0.60.2/GOG.Galaxy.locale.en-US.yaml
  manifests/g/GOG/Galaxy/2.0.60.2/GOG.Galaxy.locale.zh-CN.yaml
  manifests/g/GOG/Galaxy/2.0.60.2/GOG.Galaxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97987 octobuild.octobuild version 0.5.1
  manifests/o/octobuild/octobuild/0.5.1/octobuild.octobuild.installer.yaml
  manifests/o/octobuild/octobuild/0.5.1/octobuild.octobuild.locale.en-US.yaml
  manifests/o/octobuild/octobuild/0.5.1/octobuild.octobuild.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97994 New version: qbittorrent.qbittorrent 4.5.2
  manifests/q/qBittorrent/qBittorrent/4.5.2/qBittorrent.qBittorrent.installer.yaml
  manifests/q/qBittorrent/qBittorrent/4.5.2/qBittorrent.qBittorrent.locale.en-US.yaml
  manifests/q/qBittorrent/qBittorrent/4.5.2/qBittorrent.qBittorrent.locale.zh-CN.yaml
  manifests/q/qBittorrent/qBittorrent/4.5.2/qBittorrent.qBittorrent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97995 KurtZimmermann.TweakPower version 2.034
  manifests/k/KurtZimmermann/TweakPower/2.034/KurtZimmermann.TweakPower.installer.yaml
  manifests/k/KurtZimmermann/TweakPower/2.034/KurtZimmermann.TweakPower.locale.en-us.yaml
  manifests/k/KurtZimmermann/TweakPower/2.034/KurtZimmermann.TweakPower.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98033 Nelson 0.7.2.2774
  manifests/n/NelsonNumericalSoftware/Nelson/0.7.2.2774/NelsonNumericalSoftware.Nelson.installer.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.7.2.2774/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/0.7.2.2774/NelsonNumericalSoftware.Nelson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98036 the-sz.Banks version 1.03
  manifests/t/the-sz/Banks/1.03/the-sz.Banks.installer.yaml
  manifests/t/the-sz/Banks/1.03/the-sz.Banks.locale.en-US.yaml
  manifests/t/the-sz/Banks/1.03/the-sz.Banks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98041 Microsoft.VisualStudio.ConfigFinder version 1.0.47.55350
  manifests/m/Microsoft/VisualStudio/ConfigFinder/1.0.47.55350/Microsoft.VisualStudio.ConfigFinder.installer.yaml
  manifests/m/Microsoft/VisualStudio/ConfigFinder/1.0.47.55350/Microsoft.VisualStudio.ConfigFinder.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/ConfigFinder/1.0.47.55350/Microsoft.VisualStudio.ConfigFinder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-No-Executables

#98044 Citrix.Workspace version 23.2.0.38
  manifests/c/Citrix/Workspace/23.2.0.38/Citrix.Workspace.installer.yaml
  manifests/c/Citrix/Workspace/23.2.0.38/Citrix.Workspace.locale.en-US.yaml
  manifests/c/Citrix/Workspace/23.2.0.38/Citrix.Workspace.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98045 New version: defi.defi version 3.2.6
  manifests/d/defi/defi/3.2.6/defi.defi.installer.yaml
  manifests/d/defi/defi/3.2.6/defi.defi.locale.en-US.yaml
  manifests/d/defi/defi/3.2.6/defi.defi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98046 New version: Taozuhong.Kangaroo version 2.3.2.230301
  manifests/t/Taozuhong/Kangaroo/2.3.2.230301/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.2.230301/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.2.230301/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.2.230301/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98053 Cockos.REAPER version 6.76
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.76/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98056 New version: nektos.act version 0.2.43
  manifests/n/nektos/act/0.2.43/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.43/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.43/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98059 New version: Bosyun.BoardMix version 1.3.8
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.installer.yaml
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.locale.en-US.yaml
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.locale.zh-CN.yaml
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98062 Update: KDE.Kdenlive version 22.12.2
  manifests/k/KDE/Kdenlive/22.12.2/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98063 Update: KDE.Okular version 22.12.2
  manifests/k/KDE/Okular/22.12.2/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98065 Update version: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98076 New version: VladimirYakovlev.ElectronMail version 5.1.4
  manifests/v/VladimirYakovlev/ElectronMail/5.1.4/VladimirYakovlev.ElectronMail.installer.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.1.4/VladimirYakovlev.ElectronMail.locale.en-US.yaml
  manifests/v/VladimirYakovlev/ElectronMail/5.1.4/VladimirYakovlev.ElectronMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98083 * Renamed the TreeSize package to TreeSize.Trial (add rename)
  manifests/j/JAMSoftware/TreeSize/Trial/8.6.1/JAMSoftware.TreeSize.Trial.installer.yaml
  manifests/j/JAMSoftware/TreeSize/Trial/8.6.1/JAMSoftware.TreeSize.Trial.locale.en-US.yaml
  manifests/j/JAMSoftware/TreeSize/Trial/8.6.1/JAMSoftware.TreeSize.Trial.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate

#98085 * Renamed the TreeSize package to TreeSize.Trial (remove old)
  manifests/j/JAMSoftware/TreeSize/8.6.1/JAMSoftware.TreeSize.installer.yaml
  manifests/j/JAMSoftware/TreeSize/8.6.1/JAMSoftware.TreeSize.locale.en-US.yaml
  manifests/j/JAMSoftware/TreeSize/8.6.1/JAMSoftware.TreeSize.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98087 New version: Logseq.Logseq version 0.8.18
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.installer.yaml
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.locale.zh-CN.yaml
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98088 New version: OpenRPAApS.OpenRPA version 1.4.51.0
  manifests/o/OpenRPAApS/OpenRPA/1.4.51.0/OpenRPAApS.OpenRPA.installer.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.4.51.0/OpenRPAApS.OpenRPA.locale.en-US.yaml
  manifests/o/OpenRPAApS/OpenRPA/1.4.51.0/OpenRPAApS.OpenRPA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98089 New version: Prometheus.WMIExporter version 0.21.0
  manifests/p/Prometheus/WMIExporter/0.21.0/Prometheus.WMIExporter.installer.yaml
  manifests/p/Prometheus/WMIExporter/0.21.0/Prometheus.WMIExporter.locale.en-US.yaml
  manifests/p/Prometheus/WMIExporter/0.21.0/Prometheus.WMIExporter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98093 Added Mozilla Firefox version 110.0.1.
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/110.0.1/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98094 Added Microsoft Edge Beta version 111.0.1661.24.
  manifests/m/Microsoft/Edge/Beta/111.0.1661.24/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/111.0.1661.24/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/111.0.1661.24/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98095 Added Microsoft Edge Dev version 111.0.1660.14.
  manifests/m/Microsoft/Edge/Dev/111.0.1660.14/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/111.0.1660.14/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/111.0.1660.14/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98096 Added Firefox Developer Edition version 111.0b7.
  manifests/m/Mozilla/Firefox/DeveloperEdition/111.0b7/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/111.0b7/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/111.0b7/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98097 Toit.Jaguar version 1.9.4
  manifests/t/Toit/Jaguar/1.9.4/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.9.4/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.9.4/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98098 New version: jeffvli.Sonixd version 0.15.4
  manifests/j/jeffvli/Sonixd/0.15.4/jeffvli.Sonixd.installer.yaml
  manifests/j/jeffvli/Sonixd/0.15.4/jeffvli.Sonixd.locale.en-US.yaml
  manifests/j/jeffvli/Sonixd/0.15.4/jeffvli.Sonixd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98109 Use HTTP for bluemars.ClipX
  manifests/b/bluemars/ClipX/1.0.3.8/bluemars.ClipX.installer.yaml
  manifests/b/bluemars/ClipX/1.0.3.8/bluemars.ClipX.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98116 New version: REALiX.HWiNFO version 7.40
  manifests/r/REALiX/HWiNFO/7.40/REALiX.HWiNFO.installer.yaml
  manifests/r/REALiX/HWiNFO/7.40/REALiX.HWiNFO.locale.en-US.yaml
  manifests/r/REALiX/HWiNFO/7.40/REALiX.HWiNFO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98123 New version: HumbleBundle.HumbleApp version 1.1.7+405
  manifests/h/HumbleBundle/HumbleApp/1.1.7+405/HumbleBundle.HumbleApp.installer.yaml
  manifests/h/HumbleBundle/HumbleApp/1.1.7+405/HumbleBundle.HumbleApp.locale.en-US.yaml
  manifests/h/HumbleBundle/HumbleApp/1.1.7+405/HumbleBundle.HumbleApp.locale.zh-CN.yaml
  manifests/h/HumbleBundle/HumbleApp/1.1.7+405/HumbleBundle.HumbleApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98125 New version: OpenMedia.4KVideoDownloader version 4.23.2.5230
  manifests/o/OpenMedia/4KVideoDownloader/4.23.2.5230/OpenMedia.4KVideoDownloader.installer.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.23.2.5230/OpenMedia.4KVideoDownloader.locale.en-US.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.23.2.5230/OpenMedia.4KVideoDownloader.locale.zh-CN.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.23.2.5230/OpenMedia.4KVideoDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98126 New version: OpenMedia.4KYoutubetoMP3 version 4.8.2.5170
  manifests/o/OpenMedia/4KYoutubetoMP3/4.8.2.5170/OpenMedia.4KYoutubetoMP3.installer.yaml
  manifests/o/OpenMedia/4KYoutubetoMP3/4.8.2.5170/OpenMedia.4KYoutubetoMP3.locale.en-US.yaml
  manifests/o/OpenMedia/4KYoutubetoMP3/4.8.2.5170/OpenMedia.4KYoutubetoMP3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98131 Coder.Coder version 0.18.0
  manifests/c/Coder/Coder/0.18.0/Coder.Coder.installer.yaml
  manifests/c/Coder/Coder/0.18.0/Coder.Coder.locale.en-US.yaml
  manifests/c/Coder/Coder/0.18.0/Coder.Coder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98134 New version: bornova.numara version 3.18.4
  manifests/b/bornova/numara/3.18.4/bornova.numara.installer.yaml
  manifests/b/bornova/numara/3.18.4/bornova.numara.locale.en-US.yaml
  manifests/b/bornova/numara/3.18.4/bornova.numara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98135 New version: Google.Chrome.Canary version 113.0.5625.0
  manifests/g/Google/Chrome/Canary/113.0.5625.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/113.0.5625.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/113.0.5625.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/113.0.5625.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98133 New version: SteelSeries.GG version 33.0.0
  manifests/s/SteelSeries/GG/33.0.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/33.0.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/33.0.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98122 New version: WorkFlowy.WorkFlowy version 4.0.2302281415
  manifests/w/WorkFlowy/WorkFlowy/4.0.2302081114/WorkFlowy.WorkFlowy.installer.yaml
  manifests/w/WorkFlowy/WorkFlowy/4.0.2302081114/WorkFlowy.WorkFlowy.locale.en-US.yaml
  manifests/w/WorkFlowy/WorkFlowy/4.0.2302281415/WorkFlowy.WorkFlowy.installer.yaml
  manifests/w/WorkFlowy/WorkFlowy/4.0.2302281415/WorkFlowy.WorkFlowy.locale.en-US.yaml
  manifests/w/WorkFlowy/WorkFlowy/4.0.2302281415/WorkFlowy.WorkFlowy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98039 Update: KDE.KDEConnect version 22.12.2 [FP-O]
  manifests/k/KDE/KDEConnect/22.12.2/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#97996 KurtZimmermann.HDCleaner version 2.045
  manifests/k/KurtZimmermann/HDCleaner/2.045/KurtZimmermann.HDCleaner.installer.yaml
  manifests/k/KurtZimmermann/HDCleaner/2.045/KurtZimmermann.HDCleaner.locale.en-us.yaml
  manifests/k/KurtZimmermann/HDCleaner/2.045/KurtZimmermann.HDCleaner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#98119 New package: NextDNS.NextDNS.CLI version 1.39.4
  manifests/n/NextDNS/NextDNS/CLI/1.39.4/NextDNS.NextDNS.CLI.installer.yaml
  manifests/n/NextDNS/NextDNS/CLI/1.39.4/NextDNS.NextDNS.CLI.locale.en-US.yaml
  manifests/n/NextDNS/NextDNS/CLI/1.39.4/NextDNS.NextDNS.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#98112 New version: NextDNS.NextDNS.Desktop version 3.0.12
  manifests/n/NextDNS/NextDNS/Desktop/3.0.12/NextDNS.NextDNS.Desktop.installer.yaml
  manifests/n/NextDNS/NextDNS/Desktop/3.0.12/NextDNS.NextDNS.Desktop.locale.en-US.yaml
  manifests/n/NextDNS/NextDNS/Desktop/3.0.12/NextDNS.NextDNS.Desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-2.8, Waived-Validation-Domain

#98128 Microsoft.PowerToys version 0.68.0
  manifests/m/Microsoft/PowerToys/0.68.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.68.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.68.0/Microsoft.PowerToys.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#98152 New version: Serverless.Serverless version 3.28.0
  manifests/s/Serverless/Serverless/3.28.0/Serverless.Serverless.installer.yaml
  manifests/s/Serverless/Serverless/3.28.0/Serverless.Serverless.locale.en-US.yaml
  manifests/s/Serverless/Serverless/3.28.0/Serverless.Serverless.locale.zh-CN.yaml
  manifests/s/Serverless/Serverless/3.28.0/Serverless.Serverless.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#98208 ReleaseNotes: Wondershare.DemoCreator.CN version 6.5.0
  manifests/w/Wondershare/DemoCreator/CN/6.5.0/Wondershare.DemoCreator.CN.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/CN/6.5.0/Wondershare.DemoCreator.CN.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98204 ReleaseNotes: Billfish.Billfish version 3.0.7.8
  manifests/b/Billfish/Billfish/3.0.7.8/Billfish.Billfish.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98216 ReleaseNotes: KOOK.KOOK version 0.64.0
  manifests/k/KOOK/KOOK/0.64.0/KOOK.KOOK.locale.en-US.yaml
  manifests/k/KOOK/KOOK/0.64.0/KOOK.KOOK.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98211 ReleaseNotes: Wondershare.UniConverter.CN version 14.0.6.32
  manifests/w/Wondershare/UniConverter/CN/14.0.6.32/Wondershare.UniConverter.CN.installer.yaml
  manifests/w/Wondershare/UniConverter/CN/14.0.6.32/Wondershare.UniConverter.CN.locale.en-US.yaml
  manifests/w/Wondershare/UniConverter/CN/14.0.6.32/Wondershare.UniConverter.CN.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98200 ReleaseNotes: Alibaba.DingTalk version 7.0.10-Release.2239102
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2239102/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2239102/Alibaba.DingTalk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98196 ReleaseNotes: Alibaba.DingTalk version 7.0.10-Release.2279103
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2279103/Alibaba.DingTalk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98186 ReleaseDate: PortSwigger.BurpSuite.Professional version 2023.1.3
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.1.3/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98184 ReleaseNotes: ByteDance.JianyingPro version 3.8.0.9618
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98183 ReleaseNotes: 360.360Chrome version 13.5.2042.0
  manifests/3/360/360Chrome/13.5.2042.0/360.360Chrome.installer.yaml
  manifests/3/360/360Chrome/13.5.2042.0/360.360Chrome.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98172 ReleaseDate: PortSwigger.BurpSuite.Community version 2023.1.3
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.1.3/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98170 ReleaseNotes: TominLab.WonderPen version 2.2.5
  manifests/t/TominLab/WonderPen/2.2.5/TominLab.WonderPen.installer.yaml
  manifests/t/TominLab/WonderPen/2.2.5/TominLab.WonderPen.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98165 ReleaseNotes: Logseq.Logseq version 0.8.18
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.8.18/Logseq.Logseq.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98161 ReleaseNotes: Hugo.Hugo.Extended version 0.110.0
  manifests/h/Hugo/Hugo/Extended/0.110.0/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.110.0/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.110.0/Hugo.Hugo.Extended.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98159 ReleaseNotes: Hugo.Hugo version 0.110.0
  manifests/h/Hugo/Hugo/0.110.0/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.110.0/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.110.0/Hugo.Hugo.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98203 ReleaseNotes: EuSoft.Eudic version 13.0.0.0
  manifests/e/EuSoft/Eudic/13.0.0.0/EuSoft.Eudic.installer.yaml
  manifests/e/EuSoft/Eudic/13.0.0.0/EuSoft.Eudic.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98110 New version: AmanHarwara.Altus version 4.8.5 [FP-O]
  manifests/a/AmanHarwara/Altus/4.8.5/AmanHarwara.Altus.installer.yaml
  manifests/a/AmanHarwara/Altus/4.8.5/AmanHarwara.Altus.locale.en-US.yaml
  manifests/a/AmanHarwara/Altus/4.8.5/AmanHarwara.Altus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98132 New version: TheDocumentFoundation.LibreOffice version 7.5.1.2
  manifests/t/TheDocumentFoundation/LibreOffice/7.5.1.2/TheDocumentFoundation.LibreOffice.installer.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.5.1.2/TheDocumentFoundation.LibreOffice.locale.en-US.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/7.5.1.2/TheDocumentFoundation.LibreOffice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98140 New version: MediaArea.MediaInfo.GUI version 22.12
  manifests/m/MediaArea/MediaInfo/GUI/22.12/MediaArea.MediaInfo.GUI.installer.yaml
  manifests/m/MediaArea/MediaInfo/GUI/22.12/MediaArea.MediaInfo.GUI.locale.en-US.yaml
  manifests/m/MediaArea/MediaInfo/GUI/22.12/MediaArea.MediaInfo.GUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98219 New version: Jackett.Jackett version 0.20.3436
  manifests/j/Jackett/Jackett/0.20.3436/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.3436/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.3436/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98213 Update: KDE.Okular version 22.12.2
  manifests/k/KDE/Okular/22.12.2/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98146 DoltHub.Dolt version 0.54.0
  manifests/d/DoltHub/Dolt/0.54.0/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.54.0/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.54.0/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98220 DoltHub.Dolt version 0.54.1
  manifests/d/DoltHub/Dolt/0.54.1/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.54.1/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.54.1/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98149 New version: Sogou.SogouInput version 13.3.0.6965
  manifests/s/Sogou/SogouInput/13.3.0.6965/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/13.3.0.6965/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/13.3.0.6965/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/13.3.0.6965/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98150 New version: Logtalk.Logtalk version 3.63.0
  manifests/l/Logtalk/Logtalk/3.63.0/Logtalk.Logtalk.installer.yaml
  manifests/l/Logtalk/Logtalk/3.63.0/Logtalk.Logtalk.locale.en-US.yaml
  manifests/l/Logtalk/Logtalk/3.63.0/Logtalk.Logtalk.locale.zh-CN.yaml
  manifests/l/Logtalk/Logtalk/3.63.0/Logtalk.Logtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98153 New version: PerfectWorld.PerfectWorldArena version 1.0.23030211
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23030211/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23030211/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23030211/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23030211/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98154 New version: twpayne.chezmoi version 2.31.1
  manifests/t/twpayne/chezmoi/2.31.1/twpayne.chezmoi.installer.yaml
  manifests/t/twpayne/chezmoi/2.31.1/twpayne.chezmoi.locale.en-US.yaml
  manifests/t/twpayne/chezmoi/2.31.1/twpayne.chezmoi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98158 New version: Hugo.Hugo version 0.111.0
  manifests/h/Hugo/Hugo/0.111.0/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.111.0/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.111.0/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.111.0/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98157 SmartSoft.SmartFTP version 10.0.3069.0
  manifests/s/SmartSoft/SmartFTP/10.0.3069.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3069.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3069.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98162 New version: Hugo.Hugo.Extended version 0.111.0
  manifests/h/Hugo/Hugo/Extended/0.111.0/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.0/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.0/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.0/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98168 New version: Seewo.EasiNote version 5.2.2.9456
  manifests/s/Seewo/EasiNote/5.2.2.9456/Seewo.EasiNote.installer.yaml
  manifests/s/Seewo/EasiNote/5.2.2.9456/Seewo.EasiNote.locale.en-US.yaml
  manifests/s/Seewo/EasiNote/5.2.2.9456/Seewo.EasiNote.locale.zh-CN.yaml
  manifests/s/Seewo/EasiNote/5.2.2.9456/Seewo.EasiNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98169 New version: Alibaba.QuarkCloudDrive version 2.5.14
  manifests/a/Alibaba/QuarkCloudDrive/2.5.14/Alibaba.QuarkCloudDrive.installer.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.14/Alibaba.QuarkCloudDrive.locale.en-US.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.14/Alibaba.QuarkCloudDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/QuarkCloudDrive/2.5.14/Alibaba.QuarkCloudDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98181 New version: Highresolution.X-MouseButtonControl version 2.20.1
  manifests/h/Highresolution/X-MouseButtonControl/2.20.1/Highresolution.X-MouseButtonControl.installer.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.1/Highresolution.X-MouseButtonControl.locale.en-US.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.1/Highresolution.X-MouseButtonControl.locale.zh-CN.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.1/Highresolution.X-MouseButtonControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98182 Modify: Highresolution.X-MouseButtonControl version 2.20
  manifests/h/Highresolution/X-MouseButtonControl/2.20/Highresolution.X-MouseButtonControl.installer.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20/Highresolution.X-MouseButtonControl.locale.en-US.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20/Highresolution.X-MouseButtonControl.locale.zh-CN.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20/Highresolution.X-MouseButtonControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98187 Update: Tencent.WeiyunSync version 3.0 (3.0.0.629)
  manifests/t/Tencent/WeiyunSync/3.0/Tencent.WeiyunSync.installer.yaml
  manifests/t/Tencent/WeiyunSync/3.0/Tencent.WeiyunSync.locale.en-US.yaml
  manifests/t/Tencent/WeiyunSync/3.0/Tencent.WeiyunSync.locale.zh-CN.yaml
  manifests/t/Tencent/WeiyunSync/3.0/Tencent.WeiyunSync.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98188 New version: Kiraku.AudioJam version 1.13.5-279
  manifests/k/Kiraku/AudioJam/1.13.5-279/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.13.5-279/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.13.5-279/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.13.5-279/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98190 New version: Youku.Youku version 9.2.15.1001
  manifests/y/Youku/Youku/9.2.15.1001/Youku.Youku.installer.yaml
  manifests/y/Youku/Youku/9.2.15.1001/Youku.Youku.locale.en-US.yaml
  manifests/y/Youku/Youku/9.2.15.1001/Youku.Youku.locale.zh-CN.yaml
  manifests/y/Youku/Youku/9.2.15.1001/Youku.Youku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98191 New version: Catsxp.Catsxp version 111.3.3.1
  manifests/c/Catsxp/Catsxp/111.3.3.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/111.3.3.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/111.3.3.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/111.3.3.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98192 New version: Baidu.BaiduWenku version 1.2.0
  manifests/b/Baidu/BaiduWenku/1.2.0/Baidu.BaiduWenku.installer.yaml
  manifests/b/Baidu/BaiduWenku/1.2.0/Baidu.BaiduWenku.locale.en-US.yaml
  manifests/b/Baidu/BaiduWenku/1.2.0/Baidu.BaiduWenku.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduWenku/1.2.0/Baidu.BaiduWenku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98212 Update: KDE.Kdenlive version 22.12.2
  manifests/k/KDE/Kdenlive/22.12.2/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98215 Modify: Axure.AxureRP.10 version 10.0.0.3893
  manifests/a/Axure/AxureRP/10/10.0.0.3893/Axure.AxureRP.10.locale.en-US.yaml
  manifests/a/Axure/AxureRP/10/10.0.0.3893/Axure.AxureRP.10.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98195 New version: Appest.TickTick version 4.4.2.0
  manifests/a/Appest/TickTick/4.4.2.0/Appest.TickTick.installer.yaml
  manifests/a/Appest/TickTick/4.4.2.0/Appest.TickTick.locale.en-US.yaml
  manifests/a/Appest/TickTick/4.4.2.0/Appest.TickTick.locale.zh-CN.yaml
  manifests/a/Appest/TickTick/4.4.2.0/Appest.TickTick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98193 New version: Tencent.TencentMeetingRooms version 3.13.190.526
  manifests/t/Tencent/TencentMeetingRooms/3.13.190.526/Tencent.TencentMeetingRooms.installer.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.13.190.526/Tencent.TencentMeetingRooms.locale.en-US.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.13.190.526/Tencent.TencentMeetingRooms.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.13.190.526/Tencent.TencentMeetingRooms.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98199 New version: OctopusDeploy.Server version 2022.4.8488
  manifests/o/OctopusDeploy/Server/2022.4.8488/OctopusDeploy.Server.installer.yaml
  manifests/o/OctopusDeploy/Server/2022.4.8488/OctopusDeploy.Server.locale.en-US.yaml
  manifests/o/OctopusDeploy/Server/2022.4.8488/OctopusDeploy.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98228 ReleaseNotes: Bosyun.BoardMix version 1.3.8
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.installer.yaml
  manifests/b/Bosyun/BoardMix/1.3.8/Bosyun.BoardMix.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98201 New version: OpenWhisperSystems.Signal.Beta version 6.9.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/6.9.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.9.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/6.9.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98227 Update: KDE.Kate version 22.12.2
  manifests/k/KDE/Kate/22.12.2/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98205 ReleaseNotes: Qingfeng.HeyboxAccelerator version 1.1.23
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.23/Qingfeng.HeyboxAccelerator.locale.en-US.yaml
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.23/Qingfeng.HeyboxAccelerator.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98206 New version: Appest.Dida version 4.4.2.0
  manifests/a/Appest/Dida/4.4.2.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/4.4.2.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/4.4.2.0/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/4.4.2.0/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98207 Cockos.REAPER version 6.77
  manifests/c/Cockos/REAPER/6.77/Cockos.REAPER.installer.yaml
  manifests/c/Cockos/REAPER/6.77/Cockos.REAPER.locale.en-US.yaml
  manifests/c/Cockos/REAPER/6.77/Cockos.REAPER.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98214 New version: Ximalaya.Ximalaya version 3.3.4
  manifests/x/Ximalaya/Ximalaya/3.3.4/Ximalaya.Ximalaya.installer.yaml
  manifests/x/Ximalaya/Ximalaya/3.3.4/Ximalaya.Ximalaya.locale.en-US.yaml
  manifests/x/Ximalaya/Ximalaya/3.3.4/Ximalaya.Ximalaya.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98223 Modify: Alibaba.DingTalk version 7.0.10-Release.2219104
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2219104/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2219104/Alibaba.DingTalk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98226 ReleaseNotes: B3log.SiYuan version 2.7.7
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.7.7/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98230 ReleaseNotes: Bilibili.Livehime version 4.38.0.4419
  manifests/b/Bilibili/Livehime/4.38.0.4419/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.38.0.4419/Bilibili.Livehime.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98242 Remove: igoogolx.lux version 0.2.0
  manifests/i/igoogolx/lux/0.2.0/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.2.0/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.2.0/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98224 ReleaseNotes: Bilibili.Livehime version 4.38.1.4464
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.38.1.4464/Bilibili.Livehime.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98202 Fix: Alibaba.DingTalk version 7.0.10-Release.2189102
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2189102/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.10-Release.2189102/Alibaba.DingTalk.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98198 New version: Obsidian.Obsidian version 1.1.16
  manifests/o/Obsidian/Obsidian/1.1.16/Obsidian.Obsidian.installer.yaml
  manifests/o/Obsidian/Obsidian/1.1.16/Obsidian.Obsidian.locale.en-US.yaml
  manifests/o/Obsidian/Obsidian/1.1.16/Obsidian.Obsidian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98185 ReleaseNotes: Baidu.BaiduTranslate version 1.6.1
  manifests/b/Baidu/BaiduTranslate/1.6.1/Baidu.BaiduTranslate.installer.yaml
  manifests/b/Baidu/BaiduTranslate/1.6.1/Baidu.BaiduTranslate.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98276 Toit.Jaguar version 1.9.5
  manifests/t/Toit/Jaguar/1.9.5/Toit.Jaguar.installer.yaml
  manifests/t/Toit/Jaguar/1.9.5/Toit.Jaguar.locale.en-US.yaml
  manifests/t/Toit/Jaguar/1.9.5/Toit.Jaguar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98264 New version: Hugo.Hugo version 0.111.1
  manifests/h/Hugo/Hugo/0.111.1/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.111.1/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.111.1/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.111.1/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98265 New version: Hugo.Hugo.Extended version 0.111.1
  manifests/h/Hugo/Hugo/Extended/0.111.1/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.1/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.1/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.111.1/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98243 New version: HamsterBase.HamsterBase.Server version 0.6.3-beta
  manifests/h/HamsterBase/HamsterBase/Server/0.6.3-beta/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.3-beta/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.3-beta/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.3-beta/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98239 New version: HamsterBase.HamsterBase.Server version 0.6.0-beta
  manifests/h/HamsterBase/HamsterBase/Server/0.6.0-beta/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.0-beta/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.0-beta/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.0-beta/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98234 New version: HamsterBase.HamsterBase.Server version 0.4.2-beta
  manifests/h/HamsterBase/HamsterBase/Server/0.4.2-beta/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.4.2-beta/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.4.2-beta/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.4.2-beta/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98235 Moving: HamsterBase.HamsterBase version 0.3.0
  manifests/h/HamsterBase/HamsterBase/0.3.0/HamsterBase.HamsterBase.installer.yaml
  manifests/h/HamsterBase/HamsterBase/0.3.0/HamsterBase.HamsterBase.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/0.3.0/HamsterBase.HamsterBase.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/0.3.0/HamsterBase.HamsterBase.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98233 Moved: HamsterBase.HamsterBase.Server version 0.3.0
  manifests/h/HamsterBase/HamsterBase/Server/0.3.0/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.3.0/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.3.0/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.3.0/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#98237 New version: HamsterBase.HamsterBase.Server version 0.5.1-beta
  manifests/h/HamsterBase/HamsterBase/Server/0.5.1-beta/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.5.1-beta/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.5.1-beta/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.5.1-beta/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98240 New version: HamsterBase.HamsterBase.Server version 0.6.1-beta
  manifests/h/HamsterBase/HamsterBase/Server/0.6.1-beta/HamsterBase.HamsterBase.Server.installer.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.1-beta/HamsterBase.HamsterBase.Server.locale.en-US.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.1-beta/HamsterBase.HamsterBase.Server.locale.zh-CN.yaml
  manifests/h/HamsterBase/HamsterBase/Server/0.6.1-beta/HamsterBase.HamsterBase.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98174 New version: InfiniteRed.Reactotron.Pre-release version 3.0.0.1670
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.1670/InfiniteRed.Reactotron.Pre-release.installer.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.1670/InfiniteRed.Reactotron.Pre-release.locale.en-US.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.1670/InfiniteRed.Reactotron.Pre-release.locale.zh-CN.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.1670/InfiniteRed.Reactotron.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98246 New version: Youqu.ToDesk version 4.6.1.4
  manifests/y/Youqu/ToDesk/4.6.1.4/Youqu.ToDesk.installer.yaml
  manifests/y/Youqu/ToDesk/4.6.1.4/Youqu.ToDesk.locale.en-US.yaml
  manifests/y/Youqu/ToDesk/4.6.1.4/Youqu.ToDesk.locale.zh-CN.yaml
  manifests/y/Youqu/ToDesk/4.6.1.4/Youqu.ToDesk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#98175 New version: Dio.PureCodec version 20230222
  manifests/d/Dio/PureCodec/20230222/Dio.PureCodec.installer.yaml
  manifests/d/Dio/PureCodec/20230222/Dio.PureCodec.locale.en-US.yaml
  manifests/d/Dio/PureCodec/20230222/Dio.PureCodec.locale.zh-CN.yaml
  manifests/d/Dio/PureCodec/20230222/Dio.PureCodec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
