Repository microsoft/winget-pkgs, pull requests merged in 2023-09, with the labels that each got.

#118637 Microsoft.VisualStudioCode.Insiders_v1.82.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.82.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118659 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118661 New version: Jackett.Jackett version 0.21.719
  manifests/j/Jackett/Jackett/0.21.719/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.719/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.719/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118635 New version: vim.vim.nightly version 9.0.1833
  manifests/v/vim/vim/nightly/9.0.1833/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1833/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1833/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118632 ReleaseNotesUrl: Baidu.SwanIDE version 4.26.1
  manifests/b/Baidu/SwanIDE/4.26.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.26.1/Baidu.SwanIDE.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118666 Microsoft.VisualStudioCode.Insiders_v1.82.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.82.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118680 New version: Alibaba.AlibabaCloudCLI version 3.0.180
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.180/Alibaba.AlibabaCloudCLI.installer.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.180/Alibaba.AlibabaCloudCLI.locale.en-US.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.180/Alibaba.AlibabaCloudCLI.locale.zh-CN.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.180/Alibaba.AlibabaCloudCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118662 New version: Principle.Lusun version 2.2.4
  manifests/p/Principle/Lusun/2.2.4/Principle.Lusun.installer.yaml
  manifests/p/Principle/Lusun/2.2.4/Principle.Lusun.locale.en-US.yaml
  manifests/p/Principle/Lusun/2.2.4/Principle.Lusun.locale.zh-CN.yaml
  manifests/p/Principle/Lusun/2.2.4/Principle.Lusun.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118674 New version: Microsoft.EdgeDriver version 116.0.1938.69
  manifests/m/Microsoft/EdgeDriver/116.0.1938.69/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/116.0.1938.69/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/116.0.1938.69/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/116.0.1938.69/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118631 ReleaseNotes: Brave.Brave version 116.1.57.57
  manifests/b/Brave/Brave/116.1.57.57/Brave.Brave.installer.yaml
  manifests/b/Brave/Brave/116.1.57.57/Brave.Brave.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118649 New version: Hitencent.JisuPDF version 3.0.0.3018
  manifests/h/Hitencent/JisuPDF/3.0.0.3018/Hitencent.JisuPDF.installer.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3018/Hitencent.JisuPDF.locale.en-US.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3018/Hitencent.JisuPDF.locale.zh-CN.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3018/Hitencent.JisuPDF.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118676 New version: PortSwigger.BurpSuite.Professional version 2023.9.4
  manifests/p/PortSwigger/BurpSuite/Professional/2023.9.4/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.9.4/PortSwigger.BurpSuite.Professional.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.9.4/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.9.4/PortSwigger.BurpSuite.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118660 New version: Wondershare.Recoverit.CN version 8.0.0.7
  manifests/w/Wondershare/Recoverit/CN/8.0.0.7/Wondershare.Recoverit.CN.installer.yaml
  manifests/w/Wondershare/Recoverit/CN/8.0.0.7/Wondershare.Recoverit.CN.locale.en-US.yaml
  manifests/w/Wondershare/Recoverit/CN/8.0.0.7/Wondershare.Recoverit.CN.locale.zh-CN.yaml
  manifests/w/Wondershare/Recoverit/CN/8.0.0.7/Wondershare.Recoverit.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118653 New version: Seewo.EasiNote version 5.2.3.1507
  manifests/s/Seewo/EasiNote/5.2.3.1507/Seewo.EasiNote.installer.yaml
  manifests/s/Seewo/EasiNote/5.2.3.1507/Seewo.EasiNote.locale.en-US.yaml
  manifests/s/Seewo/EasiNote/5.2.3.1507/Seewo.EasiNote.locale.zh-CN.yaml
  manifests/s/Seewo/EasiNote/5.2.3.1507/Seewo.EasiNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118639 New version: Feixiang.Feixiang version 2.8.0
  manifests/f/Feixiang/Feixiang/2.8.0/Feixiang.Feixiang.installer.yaml
  manifests/f/Feixiang/Feixiang/2.8.0/Feixiang.Feixiang.locale.en-US.yaml
  manifests/f/Feixiang/Feixiang/2.8.0/Feixiang.Feixiang.locale.zh-CN.yaml
  manifests/f/Feixiang/Feixiang/2.8.0/Feixiang.Feixiang.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118626 New version: PaodingAI.Calliper version 1.1.68
  manifests/p/PaodingAI/Calliper/1.1.68/PaodingAI.Calliper.installer.yaml
  manifests/p/PaodingAI/Calliper/1.1.68/PaodingAI.Calliper.locale.en-US.yaml
  manifests/p/PaodingAI/Calliper/1.1.68/PaodingAI.Calliper.locale.zh-CN.yaml
  manifests/p/PaodingAI/Calliper/1.1.68/PaodingAI.Calliper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118650 New version: ByteDance.JianyingPro version 4.5.2.10484
  manifests/b/ByteDance/JianyingPro/4.5.2.10484/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.5.2.10484/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.5.2.10484/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.5.2.10484/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118675 New version: PortSwigger.BurpSuite.Community version 2023.9.4
  manifests/p/PortSwigger/BurpSuite/Community/2023.9.4/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.9.4/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.9.4/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.9.4/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118679 New version: Wondershare.PDFelement.10 version 10.0.4
  manifests/w/Wondershare/PDFelement/10/10.0.4/Wondershare.PDFelement.10.installer.yaml
  manifests/w/Wondershare/PDFelement/10/10.0.4/Wondershare.PDFelement.10.locale.en-US.yaml
  manifests/w/Wondershare/PDFelement/10/10.0.4/Wondershare.PDFelement.10.locale.zh-CN.yaml
  manifests/w/Wondershare/PDFelement/10/10.0.4/Wondershare.PDFelement.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118623 New version: CometNetwork.BitComet version 2.03
  manifests/c/CometNetwork/BitComet/2.03/CometNetwork.BitComet.installer.yaml
  manifests/c/CometNetwork/BitComet/2.03/CometNetwork.BitComet.locale.en-US.yaml
  manifests/c/CometNetwork/BitComet/2.03/CometNetwork.BitComet.locale.zh-CN.yaml
  manifests/c/CometNetwork/BitComet/2.03/CometNetwork.BitComet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118652 New version: Tencent.START version 0.11.0.14703
  manifests/t/Tencent/START/0.11.0.14703/Tencent.START.installer.yaml
  manifests/t/Tencent/START/0.11.0.14703/Tencent.START.locale.en-US.yaml
  manifests/t/Tencent/START/0.11.0.14703/Tencent.START.locale.zh-CN.yaml
  manifests/t/Tencent/START/0.11.0.14703/Tencent.START.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118651 New version: Kingsoft.KDocs version 3.9.2
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.installer.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.locale.en-US.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.locale.zh-CN.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118687 Use Special Markdown for Notes to highlight them
  CONTRIBUTING.md
  Moderation.md
  README.md
  Troubleshoot.md
  doc/manifest/schema/1.5.0/defaultLocale.md
  doc/manifest/schema/1.5.0/installer.md
  doc/manifest/schema/1.5.0/locale.md
  doc/manifest/schema/1.5.0/singleton.md
Labels: Moderator-Approved, Project-File, Needs-Attention

#118685 Microsoft.VisualStudioCode.Insiders_v1.82.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.82.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118713 Add WindowsWDK as a versioned package (22000)
  manifests/m/Microsoft/WindowsWDK/10/0/22000/10.1.22000.1/Microsoft.WindowsWDK.10.0.22000.installer.yaml
  manifests/m/Microsoft/WindowsWDK/10/0/22000/10.1.22000.1/Microsoft.WindowsWDK.10.0.22000.locale.en-US.yaml
  manifests/m/Microsoft/WindowsWDK/10/0/22000/10.1.22000.1/Microsoft.WindowsWDK.10.0.22000.yaml
Labels: Validation-Completed, Retry-1

#118636 Telegram.TelegramDesktop version 4.9.4
  manifests/t/Telegram/TelegramDesktop/4.9.4/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/4.9.4/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/4.9.4/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118692 New version: FreeCAD.FreeCAD version 0.21.1
  manifests/f/FreeCAD/FreeCAD/0.21.1/FreeCAD.FreeCAD.installer.yaml
  manifests/f/FreeCAD/FreeCAD/0.21.1/FreeCAD.FreeCAD.locale.de-DE.yaml
  manifests/f/FreeCAD/FreeCAD/0.21.1/FreeCAD.FreeCAD.locale.en-US.yaml
  manifests/f/FreeCAD/FreeCAD/0.21.1/FreeCAD.FreeCAD.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#118646 New version: Kangaroo v3.92.1.230901
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118656 Fix: Anki.Anki version 2.1.66
  manifests/a/Anki/Anki/2.1.66/Anki.Anki.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118200 New package: Danilov.Soundscape version 1.3.3
  manifests/d/Danilov/Soundscape/1.3.3/Danilov.Soundscape.installer.yaml
  manifests/d/Danilov/Soundscape/1.3.3/Danilov.Soundscape.locale.en-US.yaml
  manifests/d/Danilov/Soundscape/1.3.3/Danilov.Soundscape.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118665 New version: IVPN.IVPN version 3.12.0
  manifests/i/IVPN/IVPN/3.12.0/IVPN.IVPN.installer.yaml
  manifests/i/IVPN/IVPN/3.12.0/IVPN.IVPN.locale.en-US.yaml
  manifests/i/IVPN/IVPN/3.12.0/IVPN.IVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118667 New version: Microsoft.Azure.FunctionsCoreTools version 4.0.5312
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.5312/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.5312/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.5312/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118669 SagerNet.sing-box version 1.4.1
  manifests/s/SagerNet/sing-box/1.4.1/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.4.1/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.4.1/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118670 New version: Fndroid.ClashForWindows version 0.20.33
  manifests/f/Fndroid/ClashForWindows/0.20.33/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.33/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.33/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118577 Update version: Git.Git version 2.42.0
  manifests/g/Git/Git/2.42.0/Git.Git.installer.yaml
  manifests/g/Git/Git/2.42.0/Git.Git.locale.en-US.yaml
  manifests/g/Git/Git/2.42.0/Git.Git.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#118672 New version: argoproj.argocd version 2.8.2
  manifests/a/argoproj/argocd/2.8.2/argoproj.argocd.installer.yaml
  manifests/a/argoproj/argocd/2.8.2/argoproj.argocd.locale.en-US.yaml
  manifests/a/argoproj/argocd/2.8.2/argoproj.argocd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118684 Update version: Brave.Brave.Nightly version 116.1.59.62
  manifests/b/Brave/Brave/Nightly/116.1.59.62/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/116.1.59.62/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/116.1.59.62/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/116.1.59.62/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#118690 Added Firefox Developer Edition version 118.0b3.
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b3/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b3/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b3/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118633 Add Obsidian.Obsidian 1.4.5
  manifests/o/Obsidian/Obsidian/1.4.5/Obsidian.Obsidian.installer.yaml
  manifests/o/Obsidian/Obsidian/1.4.5/Obsidian.Obsidian.locale.en-US.yaml
  manifests/o/Obsidian/Obsidian/1.4.5/Obsidian.Obsidian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118694 New version: Google.Chrome.Dev version 118.0.5979.2
  manifests/g/Google/Chrome/Dev/118.0.5979.2/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/118.0.5979.2/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/118.0.5979.2/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/118.0.5979.2/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118696 New version: Pylogmon.pot version 2.0.0-beta.0
  manifests/p/Pylogmon/pot/2.0.0-beta.0/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/2.0.0-beta.0/Pylogmon.pot.locale.en-US.yaml
  manifests/p/Pylogmon/pot/2.0.0-beta.0/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118698 New version: JohnMacFarlane.Pandoc version 3.1.7
  manifests/j/JohnMacFarlane/Pandoc/3.1.7/JohnMacFarlane.Pandoc.installer.yaml
  manifests/j/JohnMacFarlane/Pandoc/3.1.7/JohnMacFarlane.Pandoc.locale.en-US.yaml
  manifests/j/JohnMacFarlane/Pandoc/3.1.7/JohnMacFarlane.Pandoc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118699 Update version: KDE.Cantor version 23.08.0
  manifests/k/KDE/Cantor/23.08.0/KDE.Cantor.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118700 Update version: KDE.Dolphin version 23.08.0
  manifests/k/KDE/Dolphin/23.08.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118701 Update version: KDE.Kate version 23.08.0
  manifests/k/KDE/Kate/23.08.0/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118702 Update version: KDE.KDEConnect version 23.08.0
  manifests/k/KDE/KDEConnect/23.08.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118697 Modrinth.ModrinthApp version 0.5.3
  manifests/m/Modrinth/ModrinthApp/0.5.3/Modrinth.ModrinthApp.installer.yaml
  manifests/m/Modrinth/ModrinthApp/0.5.3/Modrinth.ModrinthApp.locale.en-US.yaml
  manifests/m/Modrinth/ModrinthApp/0.5.3/Modrinth.ModrinthApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118703 Update version: KDE.Kdenlive version 23.08.0
  manifests/k/KDE/Kdenlive/23.08.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118704 Update version: KDE.Okular version 23.08.0
  manifests/k/KDE/Okular/23.08.0/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118705 Update version: Kingsoft.KDocs version 3.9.2
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.installer.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.locale.en-US.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.locale.zh-CN.yaml
  manifests/k/Kingsoft/KDocs/3.9.2/Kingsoft.KDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118708 New version: Microsoft.Edge version 116.0.1938.69
  manifests/m/Microsoft/Edge/116.0.1938.69/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/116.0.1938.69/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/116.0.1938.69/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/116.0.1938.69/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118714 Remove Microsoft.WDK version 10.1.19041.685
  manifests/m/Microsoft/WindowsWDK/10.1.19041.685/Microsoft.WindowsWDK.installer.yaml
  manifests/m/Microsoft/WindowsWDK/10.1.19041.685/Microsoft.WindowsWDK.locale.en-US.yaml
  manifests/m/Microsoft/WindowsWDK/10.1.19041.685/Microsoft.WindowsWDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118716 New version: OpenMedia.4KVideoDownloader version 4.27.0.5570
  manifests/o/OpenMedia/4KVideoDownloader/4.27.0.5570/OpenMedia.4KVideoDownloader.installer.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.27.0.5570/OpenMedia.4KVideoDownloader.locale.en-US.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.27.0.5570/OpenMedia.4KVideoDownloader.locale.zh-CN.yaml
  manifests/o/OpenMedia/4KVideoDownloader/4.27.0.5570/OpenMedia.4KVideoDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118717 New version: QuodLibet.QuodLibet version 4.6.0
  manifests/q/QuodLibet/QuodLibet/4.6.0/QuodLibet.QuodLibet.installer.yaml
  manifests/q/QuodLibet/QuodLibet/4.6.0/QuodLibet.QuodLibet.locale.en-US.yaml
  manifests/q/QuodLibet/QuodLibet/4.6.0/QuodLibet.QuodLibet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118718 New version: SaladTechnologies.Salad version 1.2.3
  manifests/s/SaladTechnologies/Salad/1.2.3/SaladTechnologies.Salad.installer.yaml
  manifests/s/SaladTechnologies/Salad/1.2.3/SaladTechnologies.Salad.locale.en-US.yaml
  manifests/s/SaladTechnologies/Salad/1.2.3/SaladTechnologies.Salad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118719 New version: DoltHub.Dolt version 1.13.6
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118721 Add installation notes to 230306 GDK.
  manifests/m/Microsoft/GDK/2303/230306/Microsoft.GDK.2303.installer.yaml
  manifests/m/Microsoft/GDK/2303/230306/Microsoft.GDK.2303.locale.en-US.yaml
  manifests/m/Microsoft/GDK/2303/230306/Microsoft.GDK.2303.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118724 Update version: Yuanli.uTools version 4.0.1
  manifests/y/Yuanli/uTools/4.0.1/Yuanli.uTools.installer.yaml
  manifests/y/Yuanli/uTools/4.0.1/Yuanli.uTools.locale.en-US.yaml
  manifests/y/Yuanli/uTools/4.0.1/Yuanli.uTools.locale.zh-CN.yaml
  manifests/y/Yuanli/uTools/4.0.1/Yuanli.uTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118725 New version: Zettlr.Zettlr version 3.0.0
  manifests/z/Zettlr/Zettlr/3.0.0/Zettlr.Zettlr.installer.yaml
  manifests/z/Zettlr/Zettlr/3.0.0/Zettlr.Zettlr.locale.en-US.yaml
  manifests/z/Zettlr/Zettlr/3.0.0/Zettlr.Zettlr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118726 Remove Microsoft.WDK version 10.1.22000.1
  manifests/m/Microsoft/WindowsWDK/10.1.22000.1/Microsoft.WindowsWDK.installer.yaml
  manifests/m/Microsoft/WindowsWDK/10.1.22000.1/Microsoft.WindowsWDK.locale.en-US.yaml
  manifests/m/Microsoft/WindowsWDK/10.1.22000.1/Microsoft.WindowsWDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118573 Add Guyutongxue.Vscch
  manifests/g/Guyutongxue/Vscch/4.0.8/Guyutongxue.Vscch.installer.yaml
  manifests/g/Guyutongxue/Vscch/4.0.8/Guyutongxue.Vscch.locale.zh-CN.yaml
  manifests/g/Guyutongxue/Vscch/4.0.8/Guyutongxue.Vscch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#118707 New package: Microsoft.LogParser version 2.2.10
  manifests/m/Microsoft/LogParser/2.2.10/Microsoft.LogParser.installer.yaml
  manifests/m/Microsoft/LogParser/2.2.10/Microsoft.LogParser.locale.en-US.yaml
  manifests/m/Microsoft/LogParser/2.2.10/Microsoft.LogParser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118686 New version: clouDr-f2e.rubick version 3.0.0
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118178 Update version: trzsz.tssh version 0.1.11
  manifests/t/trzsz/tssh/0.1.11/trzsz.tssh.installer.yaml
  manifests/t/trzsz/tssh/0.1.11/trzsz.tssh.locale.en-US.yaml
  manifests/t/trzsz/tssh/0.1.11/trzsz.tssh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#118723 New package: Microsoft.SBOMTool version 1.5.2
  manifests/m/Microsoft/SBOMTool/1.5.2/Microsoft.SBOMTool.installer.yaml
  manifests/m/Microsoft/SBOMTool/1.5.2/Microsoft.SBOMTool.locale.en-US.yaml
  manifests/m/Microsoft/SBOMTool/1.5.2/Microsoft.SBOMTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118681 New package: Microsoft.PowerBIDesktopReportServer version 2.117.984.0
  manifests/m/Microsoft/PowerBIDesktopReportServer/2.117.984.0/Microsoft.PowerBIDesktopReportServer.installer.yaml
  manifests/m/Microsoft/PowerBIDesktopReportServer/2.117.984.0/Microsoft.PowerBIDesktopReportServer.locale.en-US.yaml
  manifests/m/Microsoft/PowerBIDesktopReportServer/2.117.984.0/Microsoft.PowerBIDesktopReportServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118762 JanDeDobbeleer.OhMyPosh version 18.6.2
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118770 New version: Jackett.Jackett version 0.21.724
  manifests/j/Jackett/Jackett/0.21.724/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.724/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.724/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118825 JanDeDobbeleer.OhMyPosh version 18.6.3
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118765 New version: AutoHotkey.AutoHotkey version 2.0.7
  manifests/a/AutoHotkey/AutoHotkey/2.0.7/AutoHotkey.AutoHotkey.installer.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.7/AutoHotkey.AutoHotkey.locale.en-US.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.7/AutoHotkey.AutoHotkey.locale.zh-CN.yaml
  manifests/a/AutoHotkey/AutoHotkey/2.0.7/AutoHotkey.AutoHotkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118730 New version: Readdle.Spark version 3.8.1
  manifests/r/Readdle/Spark/3.8.1/Readdle.Spark.installer.yaml
  manifests/r/Readdle/Spark/3.8.1/Readdle.Spark.locale.en-US.yaml
  manifests/r/Readdle/Spark/3.8.1/Readdle.Spark.locale.zh-CN.yaml
  manifests/r/Readdle/Spark/3.8.1/Readdle.Spark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118781 Update Netron to 7.1.6
  manifests/l/LutzRoeder/Netron/7.1.6/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.1.6/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.1.6/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118818 New version: Jackett.Jackett version 0.21.733
  manifests/j/Jackett/Jackett/0.21.733/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.733/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.733/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118810 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118859 New version: Jackett.Jackett version 0.21.741
  manifests/j/Jackett/Jackett/0.21.741/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.741/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.741/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118852 New version: vim.vim.nightly version 9.0.1859
  manifests/v/vim/vim/nightly/9.0.1859/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1859/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1859/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118854 New version: Ferdium.Ferdium.Nightly version 6.5.0-nightly.6
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.6/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.6/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.6/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118877 JanDeDobbeleer.Aliae version 0.11.0
  manifests/j/JanDeDobbeleer/Aliae/0.11.0/JanDeDobbeleer.Aliae.installer.yaml
  manifests/j/JanDeDobbeleer/Aliae/0.11.0/JanDeDobbeleer.Aliae.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/Aliae/0.11.0/JanDeDobbeleer.Aliae.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118883 JanDeDobbeleer.OhMyPosh version 18.6.4
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.4/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.4/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.6.4/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118706 New version: DenoLand.Deno version 1.36.4
  manifests/d/DenoLand/Deno/1.36.4/DenoLand.Deno.installer.yaml
  manifests/d/DenoLand/Deno/1.36.4/DenoLand.Deno.locale.en-US.yaml
  manifests/d/DenoLand/Deno/1.36.4/DenoLand.Deno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118780 New version: Upscayl.Upscayl version 2.7.5
  manifests/u/Upscayl/Upscayl/2.7.5/Upscayl.Upscayl.installer.yaml
  manifests/u/Upscayl/Upscayl/2.7.5/Upscayl.Upscayl.locale.en-US.yaml
  manifests/u/Upscayl/Upscayl/2.7.5/Upscayl.Upscayl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118729 New version: Catsxp.Catsxp version 117.3.9.2
  manifests/c/Catsxp/Catsxp/117.3.9.2/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.2/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.2/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/117.3.9.2/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118916 New version: Jackett.Jackett version 0.21.747
  manifests/j/Jackett/Jackett/0.21.747/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.747/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.747/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118887 JanDeDobbeleer.OhMyPosh version 18.7.0
  manifests/j/JanDeDobbeleer/OhMyPosh/18.7.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.7.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.7.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118942 Added Firefox Developer Edition version 118.0b4.
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b4/Mozilla.Firefox.DeveloperEdition.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b4/Mozilla.Firefox.DeveloperEdition.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/118.0b4/Mozilla.Firefox.DeveloperEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118941 Added AWS Command Line Interface version 2.13.15.
  manifests/a/Amazon/AWSCLI/2.13.15/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.13.15/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.13.15/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118741 Update version: Apple.WindowsMigrationAssistant version 2.4.3.1
  manifests/a/Apple/WindowsMigrationAssistant/2.4.3.1/Apple.WindowsMigrationAssistant.installer.yaml
  manifests/a/Apple/WindowsMigrationAssistant/2.4.3.1/Apple.WindowsMigrationAssistant.locale.en-US.yaml
  manifests/a/Apple/WindowsMigrationAssistant/2.4.3.1/Apple.WindowsMigrationAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118732 New version: Baidu.BaiduPinyin version 6.0.3.44
  manifests/b/Baidu/BaiduPinyin/6.0.3.44/Baidu.BaiduPinyin.installer.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.3.44/Baidu.BaiduPinyin.locale.en-US.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.3.44/Baidu.BaiduPinyin.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.3.44/Baidu.BaiduPinyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118731 New version: iFlytek.iFlyNote version 3.1.1274
  manifests/i/iFlytek/iFlyNote/3.1.1274/iFlytek.iFlyNote.installer.yaml
  manifests/i/iFlytek/iFlyNote/3.1.1274/iFlytek.iFlyNote.locale.en-US.yaml
  manifests/i/iFlytek/iFlyNote/3.1.1274/iFlytek.iFlyNote.locale.zh-CN.yaml
  manifests/i/iFlytek/iFlyNote/3.1.1274/iFlytek.iFlyNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118728 Update: Posit.RStudio version 2023.06.2+561
  manifests/p/Posit/RStudio/2023.06.2+561/Posit.RStudio.installer.yaml
  manifests/p/Posit/RStudio/2023.06.2+561/Posit.RStudio.locale.en-US.yaml
  manifests/p/Posit/RStudio/2023.06.2+561/Posit.RStudio.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118727 New version: vim.vim.nightly version 9.0.1839
  manifests/v/vim/vim/nightly/9.0.1839/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1839/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1839/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#116567 Add version: Dio.PureCodec version 20230613
  manifests/d/Dio/PureCodec/20230613/Dio.PureCodec.installer.yaml
  manifests/d/Dio/PureCodec/20230613/Dio.PureCodec.locale.en-US.yaml
  manifests/d/Dio/PureCodec/20230613/Dio.PureCodec.locale.zh-CN.yaml
  manifests/d/Dio/PureCodec/20230613/Dio.PureCodec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118761 New version: PerfectWorld.PerfectWorldArena version 1.0.23090211
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23090211/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23090211/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23090211/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23090211/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118795 New version: UniversityOfEdinburgh.QuPath version 0.4.4
  manifests/u/UniversityOfEdinburgh/QuPath/0.4.4/UniversityOfEdinburgh.QuPath.installer.yaml
  manifests/u/UniversityOfEdinburgh/QuPath/0.4.4/UniversityOfEdinburgh.QuPath.locale.en-US.yaml
  manifests/u/UniversityOfEdinburgh/QuPath/0.4.4/UniversityOfEdinburgh.QuPath.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118794 New version: CodeSector.TeraCopy version 3.12
  manifests/c/CodeSector/TeraCopy/3.12/CodeSector.TeraCopy.installer.yaml
  manifests/c/CodeSector/TeraCopy/3.12/CodeSector.TeraCopy.locale.en-US.yaml
  manifests/c/CodeSector/TeraCopy/3.12/CodeSector.TeraCopy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118792 CPUID.HWMonitor version 1.52
  manifests/c/CPUID/HWMonitor/1.52/CPUID.HWMonitor.installer.yaml
  manifests/c/CPUID/HWMonitor/1.52/CPUID.HWMonitor.locale.en-US.yaml
  manifests/c/CPUID/HWMonitor/1.52/CPUID.HWMonitor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118786 Update version: KDE.KDEConnect version 23.08.0
  manifests/k/KDE/KDEConnect/23.08.0/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118787 Update version: KDE.Kdenlive version 23.08.0
  manifests/k/KDE/Kdenlive/23.08.0/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118784 Update version: KDE.Dolphin version 23.08.0
  manifests/k/KDE/Dolphin/23.08.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118783 Update version: KDE.Cantor version 23.08.0
  manifests/k/KDE/Cantor/23.08.0/KDE.Cantor.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118782 New version: joncampbell123.DOSBox-X version 2023.09.01
  manifests/j/joncampbell123/DOSBox-X/2023.09.01/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/2023.09.01/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/2023.09.01/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118779 New version: JabRef.JabRef version 5.10.60000
  manifests/j/JabRef/JabRef/5.10.60000/JabRef.JabRef.installer.yaml
  manifests/j/JabRef/JabRef/5.10.60000/JabRef.JabRef.locale.en-US.yaml
  manifests/j/JabRef/JabRef/5.10.60000/JabRef.JabRef.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118778 New version: HaxeFoundation.Haxe version 4.3.2
  manifests/h/HaxeFoundation/Haxe/4.3.2/HaxeFoundation.Haxe.installer.yaml
  manifests/h/HaxeFoundation/Haxe/4.3.2/HaxeFoundation.Haxe.locale.en-US.yaml
  manifests/h/HaxeFoundation/Haxe/4.3.2/HaxeFoundation.Haxe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118776 New version: DirSoft.ARPro version 17.0.1.976
  manifests/d/DirSoft/ARPro/17.0.1.976/DirSoft.ARPro.installer.yaml
  manifests/d/DirSoft/ARPro/17.0.1.976/DirSoft.ARPro.locale.en-US.yaml
  manifests/d/DirSoft/ARPro/17.0.1.976/DirSoft.ARPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118775 New version: GDevelop.GDevelop version 5.2.172
  manifests/g/GDevelop/GDevelop/5.2.172/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.2.172/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.2.172/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118774 Update version: DoltHub.Dolt version 1.13.6
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.13.6/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118773 New version: CozyCloud.CozyDrive.Beta version 3.39.0-beta.4
  manifests/c/CozyCloud/CozyDrive/Beta/3.39.0-beta.4/CozyCloud.CozyDrive.Beta.installer.yaml
  manifests/c/CozyCloud/CozyDrive/Beta/3.39.0-beta.4/CozyCloud.CozyDrive.Beta.locale.en-US.yaml
  manifests/c/CozyCloud/CozyDrive/Beta/3.39.0-beta.4/CozyCloud.CozyDrive.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118768 New version: monkeyWie.Gopeed version 1.3.9
  manifests/m/monkeyWie/Gopeed/1.3.9/monkeyWie.Gopeed.installer.yaml
  manifests/m/monkeyWie/Gopeed/1.3.9/monkeyWie.Gopeed.locale.en-US.yaml
  manifests/m/monkeyWie/Gopeed/1.3.9/monkeyWie.Gopeed.locale.zh-CN.yaml
  manifests/m/monkeyWie/Gopeed/1.3.9/monkeyWie.Gopeed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118769 New version: monkeyWie.Gopeed version 1.3.10
  manifests/m/monkeyWie/Gopeed/1.3.10/monkeyWie.Gopeed.installer.yaml
  manifests/m/monkeyWie/Gopeed/1.3.10/monkeyWie.Gopeed.locale.en-US.yaml
  manifests/m/monkeyWie/Gopeed/1.3.10/monkeyWie.Gopeed.locale.zh-CN.yaml
  manifests/m/monkeyWie/Gopeed/1.3.10/monkeyWie.Gopeed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118767 New version: RaoPics.RaoPics version 0.7.16
  manifests/r/RaoPics/RaoPics/0.7.16/RaoPics.RaoPics.installer.yaml
  manifests/r/RaoPics/RaoPics/0.7.16/RaoPics.RaoPics.locale.en-US.yaml
  manifests/r/RaoPics/RaoPics/0.7.16/RaoPics.RaoPics.locale.zh-CN.yaml
  manifests/r/RaoPics/RaoPics/0.7.16/RaoPics.RaoPics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118766 New version: squalou.google-chat-linux version 5.24.21-1
  manifests/s/squalou/google-chat-linux/5.24.21-1/squalou.google-chat-linux.installer.yaml
  manifests/s/squalou/google-chat-linux/5.24.21-1/squalou.google-chat-linux.locale.en-US.yaml
  manifests/s/squalou/google-chat-linux/5.24.21-1/squalou.google-chat-linux.locale.zh-CN.yaml
  manifests/s/squalou/google-chat-linux/5.24.21-1/squalou.google-chat-linux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118764 New version: igoogolx.lux version 0.4.0
  manifests/i/igoogolx/lux/0.4.0/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.4.0/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.4.0/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118763 New version: Patchdeck Agent version 2.9.0
  manifests/p/Patchdeck/Agent/2.9.0/Patchdeck.Agent.installer.yaml
  manifests/p/Patchdeck/Agent/2.9.0/Patchdeck.Agent.locale.en-US.yaml
  manifests/p/Patchdeck/Agent/2.9.0/Patchdeck.Agent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118797 New version: Brave.Brave.Dev version 116.1.58.111
  manifests/b/Brave/Brave/Dev/116.1.58.111/Brave.Brave.Dev.installer.yaml
  manifests/b/Brave/Brave/Dev/116.1.58.111/Brave.Brave.Dev.locale.en-US.yaml
  manifests/b/Brave/Brave/Dev/116.1.58.111/Brave.Brave.Dev.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Dev/116.1.58.111/Brave.Brave.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118789 PDFgear.PDFgear version 2.1.0
  manifests/p/PDFgear/PDFgear/2.1.0/PDFgear.PDFgear.installer.yaml
  manifests/p/PDFgear/PDFgear/2.1.0/PDFgear.PDFgear.locale.en-US.yaml
  manifests/p/PDFgear/PDFgear/2.1.0/PDFgear.PDFgear.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118798 New version: Redisant.RedisAssistant version 1.2.2.1
  manifests/r/Redisant/RedisAssistant/1.2.2.1/Redisant.RedisAssistant.installer.yaml
  manifests/r/Redisant/RedisAssistant/1.2.2.1/Redisant.RedisAssistant.locale.en-US.yaml
  manifests/r/Redisant/RedisAssistant/1.2.2.1/Redisant.RedisAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/RedisAssistant/1.2.2.1/Redisant.RedisAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118799 New version: BartoszCichecki.LenovoLegionToolkit version 2.16.2
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.16.2/BartoszCichecki.LenovoLegionToolkit.installer.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.16.2/BartoszCichecki.LenovoLegionToolkit.locale.en-US.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.16.2/BartoszCichecki.LenovoLegionToolkit.locale.zh-CN.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.16.2/BartoszCichecki.LenovoLegionToolkit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118800 New version: vim.vim.nightly version 9.0.1853
  manifests/v/vim/vim/nightly/9.0.1853/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.1853/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.1853/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118801 New version: Alibaba.aDrive version 4.9.5
  manifests/a/Alibaba/aDrive/4.9.5/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/4.9.5/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/4.9.5/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/4.9.5/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118802 New version: Authpass.Authpass version 1.9.9_1975
  manifests/a/Authpass/Authpass/1.9.9_1975/Authpass.Authpass.installer.yaml
  manifests/a/Authpass/Authpass/1.9.9_1975/Authpass.Authpass.locale.en-US.yaml
  manifests/a/Authpass/Authpass/1.9.9_1975/Authpass.Authpass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118803 New version: Ferdium.Ferdium.Nightly version 6.5.0-nightly.5
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.5/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.5/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.5.0-nightly.5/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118808 New version: CrystalDiskInfo.KureikeiEdtion 9.1.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118809 New version: CrystalDewWorld.CrystalDiskInfo.ShizukuEdition 9.1.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.1.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118806 eloston.ungoogled-chromium version 116.0.5845.141
  manifests/e/eloston/ungoogled-chromium/116.0.5845.141/eloston.ungoogled-chromium.installer.yaml
  manifests/e/eloston/ungoogled-chromium/116.0.5845.141/eloston.ungoogled-chromium.locale.en-US.yaml
  manifests/e/eloston/ungoogled-chromium/116.0.5845.141/eloston.ungoogled-chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118816 New version: abrignoni.iLEAPP version 1.18.7
  manifests/a/abrignoni/iLEAPP/1.18.7/abrignoni.iLEAPP.installer.yaml
  manifests/a/abrignoni/iLEAPP/1.18.7/abrignoni.iLEAPP.locale.en-US.yaml
  manifests/a/abrignoni/iLEAPP/1.18.7/abrignoni.iLEAPP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118826 Submitting HttpMaster Express 5.7.5
  manifests/b/Borvid/HttpMasterExpress/5.7.5/Borvid.HttpMasterExpress.installer.yaml
  manifests/b/Borvid/HttpMasterExpress/5.7.5/Borvid.HttpMasterExpress.locale.en-US.yaml
  manifests/b/Borvid/HttpMasterExpress/5.7.5/Borvid.HttpMasterExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118828 New version: sikalabs.slu version 0.69.0
  manifests/s/sikalabs/slu/0.69.0/sikalabs.slu.installer.yaml
  manifests/s/sikalabs/slu/0.69.0/sikalabs.slu.locale.en-US.yaml
  manifests/s/sikalabs/slu/0.69.0/sikalabs.slu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118827 Submitting HttpMaster Professional 5.7.5
  manifests/b/Borvid/HttpMasterProfessional/5.7.5/Borvid.HttpMasterProfessional.installer.yaml
  manifests/b/Borvid/HttpMasterProfessional/5.7.5/Borvid.HttpMasterProfessional.locale.en-US.yaml
  manifests/b/Borvid/HttpMasterProfessional/5.7.5/Borvid.HttpMasterProfessional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118814 New package: markmckinnon.lLeappGUI version 1.2
  manifests/m/markmckinnon/lLeappGUI/1.2/markmckinnon.lLeappGUI.installer.yaml
  manifests/m/markmckinnon/lLeappGUI/1.2/markmckinnon.lLeappGUI.locale.en-US.yaml
  manifests/m/markmckinnon/lLeappGUI/1.2/markmckinnon.lLeappGUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118811 New package: KatKoyn.KatKoynCore version 2.4
  manifests/k/KatKoyn/KatKoynCore/2.4/KatKoyn.KatKoynCore.installer.yaml
  manifests/k/KatKoyn/KatKoynCore/2.4/KatKoyn.KatKoynCore.locale.en-US.yaml
  manifests/k/KatKoyn/KatKoynCore/2.4/KatKoyn.KatKoynCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118820 New package: abrignoni.ALEAPP-cli version 3.1.8
  manifests/a/abrignoni/ALEAPP-cli/3.1.8/abrignoni.ALEAPP-cli.installer.yaml
  manifests/a/abrignoni/ALEAPP-cli/3.1.8/abrignoni.ALEAPP-cli.locale.en-US.yaml
  manifests/a/abrignoni/ALEAPP-cli/3.1.8/abrignoni.ALEAPP-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118834 New version: YuzuEmu.Yuzu.Mainline 1544
  manifests/y/YuzuEmu/Yuzu/Mainline/1544/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1544/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1544/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118831 New version: YuzuEmu.Yuzu.Mainline 1543
  manifests/y/YuzuEmu/Yuzu/Mainline/1543/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1543/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1543/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118830 New version: YuzuEmu.Yuzu.Mainline 1542
  manifests/y/YuzuEmu/Yuzu/Mainline/1542/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1542/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1542/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118832 Kiwix JS UWP 2.6.4.0
  manifests/k/Kiwix/KiwixJS/2.6.4.0/Kiwix.KiwixJS.installer.yaml
  manifests/k/Kiwix/KiwixJS/2.6.4.0/Kiwix.KiwixJS.locale.en-GB.yaml
  manifests/k/Kiwix/KiwixJS/2.6.4.0/Kiwix.KiwixJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118835 New version: YuzuEmu.Yuzu.Mainline 1545
  manifests/y/YuzuEmu/Yuzu/Mainline/1545/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1545/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1545/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118836 New version: Devolutions.RemoteDesktopManager version 2023.2.27.0
  manifests/d/Devolutions/RemoteDesktopManager/2023.2.27.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2023.2.27.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2023.2.27.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118840 New version: hluk.CopyQ version 7.1.0
  manifests/h/hluk/CopyQ/7.1.0/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/7.1.0/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/7.1.0/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118841 New package: Abdelrhman-AK.WinPaletter version 1.0.8.0
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.0/Abdelrhman-AK.WinPaletter.installer.yaml
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.0/Abdelrhman-AK.WinPaletter.locale.en-US.yaml
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.0/Abdelrhman-AK.WinPaletter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118842 New version: KuaiFan.DooTask version 0.31.8
  manifests/k/KuaiFan/DooTask/0.31.8/KuaiFan.DooTask.installer.yaml
  manifests/k/KuaiFan/DooTask/0.31.8/KuaiFan.DooTask.locale.en-US.yaml
  manifests/k/KuaiFan/DooTask/0.31.8/KuaiFan.DooTask.locale.zh-CN.yaml
  manifests/k/KuaiFan/DooTask/0.31.8/KuaiFan.DooTask.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118843 New version: VSCodium.VSCodium.Insiders version 1.82.0.23246
  manifests/v/VSCodium/VSCodium/Insiders/1.82.0.23246/VSCodium.VSCodium.Insiders.installer.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.82.0.23246/VSCodium.VSCodium.Insiders.locale.en-US.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.82.0.23246/VSCodium.VSCodium.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118845 New version: ThaUnknown.Miru version 4.3.14
  manifests/t/ThaUnknown/Miru/4.3.14/ThaUnknown.Miru.installer.yaml
  manifests/t/ThaUnknown/Miru/4.3.14/ThaUnknown.Miru.locale.en-US.yaml
  manifests/t/ThaUnknown/Miru/4.3.14/ThaUnknown.Miru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118846 New version: MCreator.MCreator version 2023.3.36712
  manifests/m/MCreator/MCreator/2023.3.36712/MCreator.MCreator.installer.yaml
  manifests/m/MCreator/MCreator/2023.3.36712/MCreator.MCreator.locale.en-US.yaml
  manifests/m/MCreator/MCreator/2023.3.36712/MCreator.MCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#118847 New version: SideQuestVR.SideQuest version 0.10.37
  manifests/s/SideQuestVR/SideQuest/0.10.37/SideQuestVR.SideQuest.installer.yaml
  manifests/s/SideQuestVR/SideQuest/0.10.37/SideQuestVR.SideQuest.locale.en-US.yaml
  manifests/s/SideQuestVR/SideQuest/0.10.37/SideQuestVR.SideQuest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118851 New version: Alist.Alist version 3.27.0
  manifests/a/Alist/Alist/3.27.0/Alist.Alist.installer.yaml
  manifests/a/Alist/Alist/3.27.0/Alist.Alist.locale.en-US.yaml
  manifests/a/Alist/Alist/3.27.0/Alist.Alist.locale.zh-CN.yaml
  manifests/a/Alist/Alist/3.27.0/Alist.Alist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118853 New version: NVAccess.NVDA version 2023.2
  manifests/n/NVAccess/NVDA/2023.2/NVAccess.NVDA.installer.yaml
  manifests/n/NVAccess/NVDA/2023.2/NVAccess.NVDA.locale.en-US.yaml
  manifests/n/NVAccess/NVDA/2023.2/NVAccess.NVDA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118855 New version: zufuliu.notepad2 version 4.23.08r4962
  manifests/z/zufuliu/notepad2/4.23.08r4962/zufuliu.notepad2.installer.yaml
  manifests/z/zufuliu/notepad2/4.23.08r4962/zufuliu.notepad2.locale.en-US.yaml
  manifests/z/zufuliu/notepad2/4.23.08r4962/zufuliu.notepad2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118857 New version: Kiraku.AudioJam version 2.0.0-366
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118858 New version: Kiraku.Mindbox version 2.2.0-381
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#118848 New package: KellyElton.Max.Backup version 0.1.3
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.installer.yaml
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.locale.en-US.yaml
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
