Repository microsoft/winget-pkgs, pull requests merged in 2023-07, with the labels that each got.

#111024 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111026 New version: Jackett.Jackett version 0.21.356
  manifests/j/Jackett/Jackett/0.21.356/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.356/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.356/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111063 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111064 New version: Jackett.Jackett version 0.21.361
  manifests/j/Jackett/Jackett/0.21.361/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.361/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.361/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111049 New package: KDE.Konsole.Nightly version 41
  manifests/k/KDE/Konsole/Nightly/41/KDE.Konsole.Nightly.installer.yaml
  manifests/k/KDE/Konsole/Nightly/41/KDE.Konsole.Nightly.locale.en-US.yaml
  manifests/k/KDE/Konsole/Nightly/41/KDE.Konsole.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111077 Remove: Adobe.Brackets version release-1.14.2
  manifests/a/Adobe/Brackets/release-1.14.2/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/release-1.14.2/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/release-1.14.2/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#107333 ES-DE.EmulationStation-DE version 2.0.1
  manifests/e/ES-DE/EmulationStation-DE/2.0.1/ES-DE.EmulationStation-DE.installer.yaml
  manifests/e/ES-DE/EmulationStation-DE/2.0.1/ES-DE.EmulationStation-DE.locale.en-US.yaml
  manifests/e/ES-DE/EmulationStation-DE/2.0.1/ES-DE.EmulationStation-DE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#111057 New version: vim.vim version 9.0.1672
  manifests/v/vim/vim/9.0.1672/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1672/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1672/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111056 New version: Muye.FlickerList version 4.4.1
  manifests/m/Muye/FlickerList/4.4.1/Muye.FlickerList.installer.yaml
  manifests/m/Muye/FlickerList/4.4.1/Muye.FlickerList.locale.en-US.yaml
  manifests/m/Muye/FlickerList/4.4.1/Muye.FlickerList.locale.zh-CN.yaml
  manifests/m/Muye/FlickerList/4.4.1/Muye.FlickerList.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111054 New version: Redisant.RedisantToolbox version 1.0.5.1
  manifests/r/Redisant/RedisantToolbox/1.0.5.1/Redisant.RedisantToolbox.installer.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.5.1/Redisant.RedisantToolbox.locale.en-US.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.5.1/Redisant.RedisantToolbox.locale.zh-CN.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.5.1/Redisant.RedisantToolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111058 Update: NetEase.CloudMusicXStudio version 1
  manifests/n/NetEase/CloudMusicXStudio/1/NetEase.CloudMusicXStudio.installer.yaml
  manifests/n/NetEase/CloudMusicXStudio/1/NetEase.CloudMusicXStudio.locale.en-US.yaml
  manifests/n/NetEase/CloudMusicXStudio/1/NetEase.CloudMusicXStudio.locale.zh-CN.yaml
  manifests/n/NetEase/CloudMusicXStudio/1/NetEase.CloudMusicXStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111055 New version: Tauri.create-tauri-app version 3.6.2
  manifests/t/Tauri/create-tauri-app/3.6.2/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/3.6.2/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/3.6.2/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/3.6.2/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111009 New version: IvanG.BrowserTamer version 3.1.4
  manifests/i/IvanG/BrowserTamer/3.1.4/IvanG.BrowserTamer.installer.yaml
  manifests/i/IvanG/BrowserTamer/3.1.4/IvanG.BrowserTamer.locale.en-US.yaml
  manifests/i/IvanG/BrowserTamer/3.1.4/IvanG.BrowserTamer.locale.zh-CN.yaml
  manifests/i/IvanG/BrowserTamer/3.1.4/IvanG.BrowserTamer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111012 New version: Highresolution.X-MouseButtonControl version 2.20.5
  manifests/h/Highresolution/X-MouseButtonControl/2.20.5/Highresolution.X-MouseButtonControl.installer.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.5/Highresolution.X-MouseButtonControl.locale.en-US.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.5/Highresolution.X-MouseButtonControl.locale.zh-CN.yaml
  manifests/h/Highresolution/X-MouseButtonControl/2.20.5/Highresolution.X-MouseButtonControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111033 New version: MPC-BE.MPC-BE version 1.6.8
  manifests/m/MPC-BE/MPC-BE/1.6.8/MPC-BE.MPC-BE.installer.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.8/MPC-BE.MPC-BE.locale.en-US.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.8/MPC-BE.MPC-BE.locale.zh-CN.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.8/MPC-BE.MPC-BE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#111021 Update Netron to 7.0.2
  manifests/l/LutzRoeder/Netron/7.0.2/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.0.2/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.0.2/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111008 New version: IvanG.BrowserTamer version 3.1.3
  manifests/i/IvanG/BrowserTamer/3.1.3/IvanG.BrowserTamer.installer.yaml
  manifests/i/IvanG/BrowserTamer/3.1.3/IvanG.BrowserTamer.locale.en-US.yaml
  manifests/i/IvanG/BrowserTamer/3.1.3/IvanG.BrowserTamer.locale.zh-CN.yaml
  manifests/i/IvanG/BrowserTamer/3.1.3/IvanG.BrowserTamer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111013 New version: Redisant.RedisAssistant version 1.2.1.3
  manifests/r/Redisant/RedisAssistant/1.2.1.3/Redisant.RedisAssistant.installer.yaml
  manifests/r/Redisant/RedisAssistant/1.2.1.3/Redisant.RedisAssistant.locale.en-US.yaml
  manifests/r/Redisant/RedisAssistant/1.2.1.3/Redisant.RedisAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/RedisAssistant/1.2.1.3/Redisant.RedisAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111014 Fix: Redisant.RedisAssistant version 1.2.1.2
  manifests/r/Redisant/RedisAssistant/1.2.1.2/Redisant.RedisAssistant.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111005 New version: Apifox.Apifox version 2.3.2
  manifests/a/Apifox/Apifox/2.3.2/Apifox.Apifox.installer.yaml
  manifests/a/Apifox/Apifox/2.3.2/Apifox.Apifox.locale.en-US.yaml
  manifests/a/Apifox/Apifox/2.3.2/Apifox.Apifox.locale.zh-CN.yaml
  manifests/a/Apifox/Apifox/2.3.2/Apifox.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111070 New version: listen1.listen1 version 2.28.0
  manifests/l/listen1/listen1/2.28.0/listen1.listen1.installer.yaml
  manifests/l/listen1/listen1/2.28.0/listen1.listen1.locale.en-US.yaml
  manifests/l/listen1/listen1/2.28.0/listen1.listen1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111004 New version: ByteDance.JianyingPro version 4.3.0.10225
  manifests/b/ByteDance/JianyingPro/4.3.0.10225/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.3.0.10225/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.3.0.10225/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.3.0.10225/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110997 New version: PIKCLOUD.PikPak version 1.5.2
  manifests/p/PIKCLOUD/PikPak/1.5.2/PIKCLOUD.PikPak.installer.yaml
  manifests/p/PIKCLOUD/PikPak/1.5.2/PIKCLOUD.PikPak.locale.en-US.yaml
  manifests/p/PIKCLOUD/PikPak/1.5.2/PIKCLOUD.PikPak.locale.zh-CN.yaml
  manifests/p/PIKCLOUD/PikPak/1.5.2/PIKCLOUD.PikPak.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111002 New version: OddLab.Cubox version 0.0.30
  manifests/o/OddLab/Cubox/0.0.30/OddLab.Cubox.installer.yaml
  manifests/o/OddLab/Cubox/0.0.30/OddLab.Cubox.locale.en-US.yaml
  manifests/o/OddLab/Cubox/0.0.30/OddLab.Cubox.locale.zh-CN.yaml
  manifests/o/OddLab/Cubox/0.0.30/OddLab.Cubox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111000 New version: ByteDance.DouyinIDE version 4.1.0
  manifests/b/ByteDance/DouyinIDE/4.1.0/ByteDance.DouyinIDE.installer.yaml
  manifests/b/ByteDance/DouyinIDE/4.1.0/ByteDance.DouyinIDE.locale.en-US.yaml
  manifests/b/ByteDance/DouyinIDE/4.1.0/ByteDance.DouyinIDE.locale.zh-CN.yaml
  manifests/b/ByteDance/DouyinIDE/4.1.0/ByteDance.DouyinIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110994 New version: calibre.calibre.portable version 6.22.0
  manifests/c/calibre/calibre/portable/6.22.0/calibre.calibre.portable.installer.yaml
  manifests/c/calibre/calibre/portable/6.22.0/calibre.calibre.portable.locale.en-US.yaml
  manifests/c/calibre/calibre/portable/6.22.0/calibre.calibre.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110996 Remove: calibre.calibre.portable version 6.21.0
  manifests/c/calibre/calibre/portable/6.21.0/calibre.calibre.portable.installer.yaml
  manifests/c/calibre/calibre/portable/6.21.0/calibre.calibre.portable.locale.en-US.yaml
  manifests/c/calibre/calibre/portable/6.21.0/calibre.calibre.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110993 New version: calibre.calibre version 6.22.0
  manifests/c/calibre/calibre/6.22.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/6.22.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/6.22.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110995 Remove: calibre.calibre version 6.21.0
  manifests/c/calibre/calibre/6.21.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/6.21.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/6.21.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111003 New version: Appest.Dida version 4.5.5.1
  manifests/a/Appest/Dida/4.5.5.1/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/4.5.5.1/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/4.5.5.1/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/4.5.5.1/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110998 New version: Microsoft.EdgeDriver version 114.0.1823.67
  manifests/m/Microsoft/EdgeDriver/114.0.1823.67/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/114.0.1823.67/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/114.0.1823.67/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/114.0.1823.67/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#110984 New version: PTRTECH.UVtools version 3.15.1
  manifests/p/PTRTECH/UVtools/3.15.1/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.15.1/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.15.1/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110979 Update Mrs4s.go-cqhttp.installer.yaml
  manifests/m/Mrs4s/go-cqhttp/1.0.0/Mrs4s.go-cqhttp.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110975 ViGEm.HidHide: add `ElevationRequirement: elevationRequired` to avoid…
  manifests/v/ViGEm/HidHide/1.2.128/ViGEm.HidHide.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110981 Wikivoyage by Kiwix 2.5.2-E Electron
  manifests/k/Kiwix/Wikivoyage/Electron/2.5.2-E/Kiwix.Wikivoyage.Electron.installer.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.5.2-E/Kiwix.Wikivoyage.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.5.2-E/Kiwix.Wikivoyage.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110980 Wikivoyage by Kiwix 2.5.2 UWP
  manifests/k/Kiwix/Wikivoyage/2.5.2.0/Kiwix.Wikivoyage.installer.yaml
  manifests/k/Kiwix/Wikivoyage/2.5.2.0/Kiwix.Wikivoyage.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/2.5.2.0/Kiwix.Wikivoyage.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110976 ViGEm.HidHide: add ElevationRequirement: elevationRequired to `1.2.98…
  manifests/v/ViGEm/HidHide/1.2.98/ViGEm.HidHide.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111044 eloston.ungoogled-chromium version 114.0.5735.199
  manifests/e/eloston/ungoogled-chromium/114.0.5735.199/eloston.ungoogled-chromium.installer.yaml
  manifests/e/eloston/ungoogled-chromium/114.0.5735.199/eloston.ungoogled-chromium.locale.en-US.yaml
  manifests/e/eloston/ungoogled-chromium/114.0.5735.199/eloston.ungoogled-chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111030 New version: Elgato.WaveLink version 1.8.1.476
  manifests/e/Elgato/WaveLink/1.8.1.476/Elgato.WaveLink.installer.yaml
  manifests/e/Elgato/WaveLink/1.8.1.476/Elgato.WaveLink.locale.en-US.yaml
  manifests/e/Elgato/WaveLink/1.8.1.476/Elgato.WaveLink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110973 Add MongoDB.Compass.Isolated 1.38.1.0
  manifests/m/MongoDB/Compass/Isolated/1.38.1.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.38.1.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.38.1.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110990 Add MongoDB.Compass.Readonly 1.38.2.0
  manifests/m/MongoDB/Compass/Readonly/1.38.2.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.38.2.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.38.2.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110991 Add MongoDB.Compass.Isolated 1.38.2.0
  manifests/m/MongoDB/Compass/Isolated/1.38.2.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.38.2.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.38.2.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110992 Add MongoDB.Compass.Full 1.38.2.0
  manifests/m/MongoDB/Compass/Full/1.38.2.0/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.38.2.0/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.38.2.0/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110948 New version: TeamViewer.TeamViewer.Host version 15.43.6
  manifests/t/TeamViewer/TeamViewer/Host/15.43.6/TeamViewer.TeamViewer.Host.installer.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.43.6/TeamViewer.TeamViewer.Host.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.43.6/TeamViewer.TeamViewer.Host.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110931 New version: Hugo.Hugo.Extended version 0.115.0
  manifests/h/Hugo/Hugo/Extended/0.115.0/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.115.0/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.115.0/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.115.0/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110971 Added AWS Command Line Interface version 2.12.5.
  manifests/a/Amazon/AWSCLI/2.12.5/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.12.5/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.12.5/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110933 New version: CrowTranslate.CrowTranslate version 2.10.6
  manifests/c/CrowTranslate/CrowTranslate/2.10.6/CrowTranslate.CrowTranslate.installer.yaml
  manifests/c/CrowTranslate/CrowTranslate/2.10.6/CrowTranslate.CrowTranslate.locale.en-US.yaml
  manifests/c/CrowTranslate/CrowTranslate/2.10.6/CrowTranslate.CrowTranslate.locale.zh-CN.yaml
  manifests/c/CrowTranslate/CrowTranslate/2.10.6/CrowTranslate.CrowTranslate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110932 New version: RaoPics.RaoPics version 0.6.5
  manifests/r/RaoPics/RaoPics/0.6.5/RaoPics.RaoPics.installer.yaml
  manifests/r/RaoPics/RaoPics/0.6.5/RaoPics.RaoPics.locale.en-US.yaml
  manifests/r/RaoPics/RaoPics/0.6.5/RaoPics.RaoPics.locale.zh-CN.yaml
  manifests/r/RaoPics/RaoPics/0.6.5/RaoPics.RaoPics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110930 New version: Hugo.Hugo version 0.115.0
  manifests/h/Hugo/Hugo/0.115.0/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.115.0/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.115.0/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.115.0/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110924 New version: PortSwigger.BurpSuite.Community version 2023.6.2
  manifests/p/PortSwigger/BurpSuite/Community/2023.6.2/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.6.2/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.6.2/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.6.2/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110920 New version: Tencent.QQ version 9.7.10.29074
  manifests/t/Tencent/QQ/9.7.10.29074/Tencent.QQ.installer.yaml
  manifests/t/Tencent/QQ/9.7.10.29074/Tencent.QQ.locale.en-US.yaml
  manifests/t/Tencent/QQ/9.7.10.29074/Tencent.QQ.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/9.7.10.29074/Tencent.QQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110921 New version: Tencent.TencentMeeting version 3.17.5.403
  manifests/t/Tencent/TencentMeeting/3.17.5.403/Tencent.TencentMeeting.installer.yaml
  manifests/t/Tencent/TencentMeeting/3.17.5.403/Tencent.TencentMeeting.locale.en-US.yaml
  manifests/t/Tencent/TencentMeeting/3.17.5.403/Tencent.TencentMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeeting/3.17.5.403/Tencent.TencentMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110925 New version: LukiLabs.Craft version 1.14.2
  manifests/l/LukiLabs/Craft/1.14.2/LukiLabs.Craft.installer.yaml
  manifests/l/LukiLabs/Craft/1.14.2/LukiLabs.Craft.locale.en-US.yaml
  manifests/l/LukiLabs/Craft/1.14.2/LukiLabs.Craft.locale.zh-CN.yaml
  manifests/l/LukiLabs/Craft/1.14.2/LukiLabs.Craft.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110915 New version: Brave.Brave.Nightly version 115.1.55.82
  manifests/b/Brave/Brave/Nightly/115.1.55.82/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/115.1.55.82/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/115.1.55.82/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/115.1.55.82/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110926 New version: Chocolatey.ChocolateyGUI version 2.1.0.0
  manifests/c/Chocolatey/ChocolateyGUI/2.1.0.0/Chocolatey.ChocolateyGUI.installer.yaml
  manifests/c/Chocolatey/ChocolateyGUI/2.1.0.0/Chocolatey.ChocolateyGUI.locale.en-US.yaml
  manifests/c/Chocolatey/ChocolateyGUI/2.1.0.0/Chocolatey.ChocolateyGUI.locale.zh-CN.yaml
  manifests/c/Chocolatey/ChocolateyGUI/2.1.0.0/Chocolatey.ChocolateyGUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110937 New version: ElijahLopez.MusicCaster version 5.13.35
  manifests/e/ElijahLopez/MusicCaster/5.13.35/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.35/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.35/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110917 Modify: Tencent.WeChat version 3.9.5.80
  manifests/t/Tencent/WeChat/3.9.5.80/Tencent.WeChat.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110919 New version: Tencent.TIM version 3.4.7.22085
  manifests/t/Tencent/TIM/3.4.7.22085/Tencent.TIM.installer.yaml
  manifests/t/Tencent/TIM/3.4.7.22085/Tencent.TIM.locale.en-US.yaml
  manifests/t/Tencent/TIM/3.4.7.22085/Tencent.TIM.locale.zh-CN.yaml
  manifests/t/Tencent/TIM/3.4.7.22085/Tencent.TIM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110922 New version: PortSwigger.BurpSuite.Professional version 2023.6.2
  manifests/p/PortSwigger/BurpSuite/Professional/2023.6.2/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.6.2/PortSwigger.BurpSuite.Professional.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.6.2/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2023.6.2/PortSwigger.BurpSuite.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110918 New version: Youku.Youku version 9.2.19.1001
  manifests/y/Youku/Youku/9.2.19.1001/Youku.Youku.installer.yaml
  manifests/y/Youku/Youku/9.2.19.1001/Youku.Youku.locale.en-US.yaml
  manifests/y/Youku/Youku/9.2.19.1001/Youku.Youku.locale.zh-CN.yaml
  manifests/y/Youku/Youku/9.2.19.1001/Youku.Youku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111075 Remove: TopalaSoftwareSolutions.SIW version 2023.05.17.5
  manifests/t/TopalaSoftwareSolutions/SIW/2023.05.17.5/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.05.17.5/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.05.17.5/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110929 New version: PerfectWorld.PerfectWorldArena version 1.0.23062913
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23062913/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23062913/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23062913/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23062913/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110913 New version: Appest.TickTick version 4.5.5.1
  manifests/a/Appest/TickTick/4.5.5.1/Appest.TickTick.installer.yaml
  manifests/a/Appest/TickTick/4.5.5.1/Appest.TickTick.locale.en-US.yaml
  manifests/a/Appest/TickTick/4.5.5.1/Appest.TickTick.locale.zh-CN.yaml
  manifests/a/Appest/TickTick/4.5.5.1/Appest.TickTick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110928 Fix: Chocolatey.ChocolateyGUI version 1.1.3.0
  manifests/c/Chocolatey/ChocolateyGUI/1.1.3.0/Chocolatey.ChocolateyGUI.installer.yaml
  manifests/c/Chocolatey/ChocolateyGUI/1.1.3.0/Chocolatey.ChocolateyGUI.locale.en-US.yaml
  manifests/c/Chocolatey/ChocolateyGUI/1.1.3.0/Chocolatey.ChocolateyGUI.locale.zh-CN.yaml
  manifests/c/Chocolatey/ChocolateyGUI/1.1.3.0/Chocolatey.ChocolateyGUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111065 Eigenmiao.Rickrack version 2.8.27
  manifests/e/Eigenmiao/Rickrack/2.8.27/Eigenmiao.Rickrack.installer.yaml
  manifests/e/Eigenmiao/Rickrack/2.8.27/Eigenmiao.Rickrack.locale.en-US.yaml
  manifests/e/Eigenmiao/Rickrack/2.8.27/Eigenmiao.Rickrack.locale.zh-CN.yaml
  manifests/e/Eigenmiao/Rickrack/2.8.27/Eigenmiao.Rickrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111066 New version: Fndroid.ClashForWindows version 0.20.27
  manifests/f/Fndroid/ClashForWindows/0.20.27/Fndroid.ClashForWindows.installer.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.27/Fndroid.ClashForWindows.locale.en-US.yaml
  manifests/f/Fndroid/ClashForWindows/0.20.27/Fndroid.ClashForWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111074 Update version: AdamMiskiewicz.GraphiQL version 0.7.2
  manifests/a/AdamMiskiewicz/GraphiQL/0.7.2/AdamMiskiewicz.GraphiQL.installer.yaml
  manifests/a/AdamMiskiewicz/GraphiQL/0.7.2/AdamMiskiewicz.GraphiQL.locale.en-US.yaml
  manifests/a/AdamMiskiewicz/GraphiQL/0.7.2/AdamMiskiewicz.GraphiQL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111071 Guru3D.Afterburner: set scope to machine
  manifests/g/Guru3D/Afterburner/4.6.5/Guru3D.Afterburner.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111081 Update version: agalwood.Motrix version 1.8.19
  manifests/a/agalwood/Motrix/1.8.19/agalwood.Motrix.installer.yaml
  manifests/a/agalwood/Motrix/1.8.19/agalwood.Motrix.locale.en-US.yaml
  manifests/a/agalwood/Motrix/1.8.19/agalwood.Motrix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111037 New version: Ferdium.Ferdium.Nightly version 6.4.1-nightly.3
  manifests/f/Ferdium/Ferdium/Nightly/6.4.1-nightly.3/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.4.1-nightly.3/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.4.1-nightly.3/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111051 SmartSoft.SmartFTP version 10.0.3135.0
  manifests/s/SmartSoft/SmartFTP/10.0.3135.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3135.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3135.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111050 New version: filips.FirefoxPWA version 2.6.2
  manifests/f/filips/FirefoxPWA/2.6.2/filips.FirefoxPWA.installer.yaml
  manifests/f/filips/FirefoxPWA/2.6.2/filips.FirefoxPWA.locale.en-US.yaml
  manifests/f/filips/FirefoxPWA/2.6.2/filips.FirefoxPWA.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#111025 New version: IndigoByte.DrExplain version 6.6.1271
  manifests/i/IndigoByte/DrExplain/6.6.1271/IndigoByte.DrExplain.installer.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1271/IndigoByte.DrExplain.locale.en-US.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1271/IndigoByte.DrExplain.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#111053 New version: Brave.Brave.Dev version 115.1.54.86
  manifests/b/Brave/Brave/Dev/115.1.54.86/Brave.Brave.Dev.installer.yaml
  manifests/b/Brave/Brave/Dev/115.1.54.86/Brave.Brave.Dev.locale.en-US.yaml
  manifests/b/Brave/Brave/Dev/115.1.54.86/Brave.Brave.Dev.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Dev/115.1.54.86/Brave.Brave.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111072 New version: gaphor.gaphor 2.19.1
  manifests/g/gaphor/gaphor/2.19.1/gaphor.gaphor.installer.yaml
  manifests/g/gaphor/gaphor/2.19.1/gaphor.gaphor.locale.en-US.yaml
  manifests/g/gaphor/gaphor/2.19.1/gaphor.gaphor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111006 New version: IvanG.BrowserTamer version 3.1.1
  manifests/i/IvanG/BrowserTamer/3.1.1/IvanG.BrowserTamer.installer.yaml
  manifests/i/IvanG/BrowserTamer/3.1.1/IvanG.BrowserTamer.locale.en-US.yaml
  manifests/i/IvanG/BrowserTamer/3.1.1/IvanG.BrowserTamer.locale.zh-CN.yaml
  manifests/i/IvanG/BrowserTamer/3.1.1/IvanG.BrowserTamer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110999 New version: AuraMarker.Lattics version 1.10.1
  manifests/a/AuraMarker/Lattics/1.10.1/AuraMarker.Lattics.installer.yaml
  manifests/a/AuraMarker/Lattics/1.10.1/AuraMarker.Lattics.locale.en-US.yaml
  manifests/a/AuraMarker/Lattics/1.10.1/AuraMarker.Lattics.locale.zh-CN.yaml
  manifests/a/AuraMarker/Lattics/1.10.1/AuraMarker.Lattics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110923 New version: ByteDance.Douyin version 2.5.0
  manifests/b/ByteDance/Douyin/2.5.0/ByteDance.Douyin.installer.yaml
  manifests/b/ByteDance/Douyin/2.5.0/ByteDance.Douyin.locale.en-US.yaml
  manifests/b/ByteDance/Douyin/2.5.0/ByteDance.Douyin.locale.zh-CN.yaml
  manifests/b/ByteDance/Douyin/2.5.0/ByteDance.Douyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110972 Add MongoDB.Compass.Readonly 1.38.1.0
  manifests/m/MongoDB/Compass/Readonly/1.38.1.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.38.1.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.38.1.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110949 New version: TeamViewer.TeamViewer version 15.43.6
  manifests/t/TeamViewer/TeamViewer/15.43.6/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.43.6/TeamViewer.TeamViewer.locale.de-DE.yaml
  manifests/t/TeamViewer/TeamViewer/15.43.6/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.43.6/TeamViewer.TeamViewer.locale.zh-CN.yaml
  manifests/t/TeamViewer/TeamViewer/15.43.6/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#110934 New version: 123.123pan version 1.0.111.0
  manifests/1/123/123pan/1.0.111.0/123.123pan.installer.yaml
  manifests/1/123/123pan/1.0.111.0/123.123pan.locale.en-US.yaml
  manifests/1/123/123pan/1.0.111.0/123.123pan.locale.zh-CN.yaml
  manifests/1/123/123pan/1.0.111.0/123.123pan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110914 New version: Brave.Brave.Beta version 115.1.54.84
  manifests/b/Brave/Brave/Beta/115.1.54.84/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/115.1.54.84/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/115.1.54.84/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/115.1.54.84/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110974 Add MongoDB.Compass.Full 1.38.1.0
  manifests/m/MongoDB/Compass/Full/1.38.1.0/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.38.1.0/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.38.1.0/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110977 New version: Mrs4s.go-cqhttp version 1.1.0
  manifests/m/Mrs4s/go-cqhttp/1.1.0/Mrs4s.go-cqhttp.installer.yaml
  manifests/m/Mrs4s/go-cqhttp/1.1.0/Mrs4s.go-cqhttp.locale.zh-CN.yaml
  manifests/m/Mrs4s/go-cqhttp/1.1.0/Mrs4s.go-cqhttp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110983 New version: Rclone.Rclone version 1.63.0
  manifests/r/Rclone/Rclone/1.63.0/Rclone.Rclone.installer.yaml
  manifests/r/Rclone/Rclone/1.63.0/Rclone.Rclone.locale.en-US.yaml
  manifests/r/Rclone/Rclone/1.63.0/Rclone.Rclone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110906 New version Docker.DockerDesktop version 4.21.0
  manifests/d/Docker/DockerDesktop/4.21.0/Docker.DockerDesktop.installer.yaml
  manifests/d/Docker/DockerDesktop/4.21.0/Docker.DockerDesktop.locale.en-US.yaml
  manifests/d/Docker/DockerDesktop/4.21.0/Docker.DockerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111016 New version: Taozuhong.Kangaroo v3.90.1
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111089 Update version: Aleab.Toastify version 1.11.2
  manifests/a/Aleab/Toastify/1.11.2/Aleab.Toastify.installer.yaml
  manifests/a/Aleab/Toastify/1.11.2/Aleab.Toastify.locale.en-US.yaml
  manifests/a/Aleab/Toastify/1.11.2/Aleab.Toastify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111087 Update version: Alacritty.Alacritty version 0.12.1
  manifests/a/Alacritty/Alacritty/0.12.1/Alacritty.Alacritty.installer.yaml
  manifests/a/Alacritty/Alacritty/0.12.1/Alacritty.Alacritty.locale.en-US.yaml
  manifests/a/Alacritty/Alacritty/0.12.1/Alacritty.Alacritty.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111083 Update version: Ahlyab.UdemyCouponFetcher version 1.2
  manifests/a/Ahlyab/UdemyCouponFetcher/1.2/Ahlyab.UdemyCouponFetcher.installer.yaml
  manifests/a/Ahlyab/UdemyCouponFetcher/1.2/Ahlyab.UdemyCouponFetcher.locale.en-US.yaml
  manifests/a/Ahlyab/UdemyCouponFetcher/1.2/Ahlyab.UdemyCouponFetcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111082 Update version: Ahlyab.PasswordChecker version 1.0.1
  manifests/a/Ahlyab/PasswordChecker/1.0.1/Ahlyab.PasswordChecker.installer.yaml
  manifests/a/Ahlyab/PasswordChecker/1.0.1/Ahlyab.PasswordChecker.locale.en-US.yaml
  manifests/a/Ahlyab/PasswordChecker/1.0.1/Ahlyab.PasswordChecker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111084 New version: Airsquared.Blobsaver version 3.5.1
  manifests/a/Airsquared/Blobsaver/3.5.1/Airsquared.Blobsaver.installer.yaml
  manifests/a/Airsquared/Blobsaver/3.5.1/Airsquared.Blobsaver.locale.en-US.yaml
  manifests/a/Airsquared/Blobsaver/3.5.1/Airsquared.Blobsaver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111090 Update version: AlekseyHoffman.Sigma-File-Manager version 1.7.0
  manifests/a/AlekseyHoffman/Sigma-File-Manager/1.7.0/AlekseyHoffman.Sigma-File-Manager.installer.yaml
  manifests/a/AlekseyHoffman/Sigma-File-Manager/1.7.0/AlekseyHoffman.Sigma-File-Manager.locale.en-US.yaml
  manifests/a/AlekseyHoffman/Sigma-File-Manager/1.7.0/AlekseyHoffman.Sigma-File-Manager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111085 Update version: Aiursoft.Kahla version 4.5.0
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.installer.yaml
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.locale.en-US.yaml
  manifests/a/Aiursoft/Kahla/4.5.0/Aiursoft.Kahla.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111088 Update version: alagrede.znote version 2.3.4
  manifests/a/alagrede/znote/2.3.4/alagrede.znote.installer.yaml
  manifests/a/alagrede/znote/2.3.4/alagrede.znote.locale.en-US.yaml
  manifests/a/alagrede/znote/2.3.4/alagrede.znote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111078 Update version: AdrienAllard.FileConverter version 1.2.3
  manifests/a/AdrienAllard/FileConverter/1.2.3/AdrienAllard.FileConverter.installer.yaml
  manifests/a/AdrienAllard/FileConverter/1.2.3/AdrienAllard.FileConverter.locale.en-US.yaml
  manifests/a/AdrienAllard/FileConverter/1.2.3/AdrienAllard.FileConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111091 Update version: alesimula.wsa_pacman version 1.4.1
  manifests/a/alesimula/wsa_pacman/1.4.1/alesimula.wsa_pacman.installer.yaml
  manifests/a/alesimula/wsa_pacman/1.4.1/alesimula.wsa_pacman.locale.en-US.yaml
  manifests/a/alesimula/wsa_pacman/1.4.1/alesimula.wsa_pacman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111086 New version: AivarAnnamaa.Thonny version 4.1.1
  manifests/a/AivarAnnamaa/Thonny/4.1.1/AivarAnnamaa.Thonny.installer.yaml
  manifests/a/AivarAnnamaa/Thonny/4.1.1/AivarAnnamaa.Thonny.locale.en-US.yaml
  manifests/a/AivarAnnamaa/Thonny/4.1.1/AivarAnnamaa.Thonny.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110830 New version: rocksdanister.LivelyWallpaper 2.0.7.0
  manifests/r/rocksdanister/LivelyWallpaper/2.0.7.0/rocksdanister.LivelyWallpaper.installer.yaml
  manifests/r/rocksdanister/LivelyWallpaper/2.0.7.0/rocksdanister.LivelyWallpaper.locale.en-US.yaml
  manifests/r/rocksdanister/LivelyWallpaper/2.0.7.0/rocksdanister.LivelyWallpaper.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#111095 Add AGSProjectTeam.AdventureGameStudio 3.6.0.50
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.50/AGSProjectTeam.AdventureGameStudio.installer.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.50/AGSProjectTeam.AdventureGameStudio.locale.en-US.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.50/AGSProjectTeam.AdventureGameStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111036 New version: MikeFarah.yq version 4.34.1
  manifests/m/MikeFarah/yq/4.34.1/MikeFarah.yq.installer.yaml
  manifests/m/MikeFarah/yq/4.34.1/MikeFarah.yq.locale.en-US.yaml
  manifests/m/MikeFarah/yq/4.34.1/MikeFarah.yq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111035 New version: Ablaze.Floorp version 10.15.0
  manifests/a/Ablaze/Floorp/10.15.0/Ablaze.Floorp.installer.yaml
  manifests/a/Ablaze/Floorp/10.15.0/Ablaze.Floorp.locale.en-US.yaml
  manifests/a/Ablaze/Floorp/10.15.0/Ablaze.Floorp.locale.ja-JP.yaml
  manifests/a/Ablaze/Floorp/10.15.0/Ablaze.Floorp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111094 TopalaSoftwareSolutions.SIW version 2023.06.21.1
  manifests/t/TopalaSoftwareSolutions/SIW/2023.06.21.1/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.06.21.1/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.06.21.1/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111039 New package: AquaSecurity.Trivy version 0.43.0
  manifests/a/AquaSecurity/Trivy/0.43.0/AquaSecurity.Trivy.installer.yaml
  manifests/a/AquaSecurity/Trivy/0.43.0/AquaSecurity.Trivy.locale.en-US.yaml
  manifests/a/AquaSecurity/Trivy/0.43.0/AquaSecurity.Trivy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111042 New version: DirSoft.ARPro version 17.0.1.968
  manifests/d/DirSoft/ARPro/17.0.1.968/DirSoft.ARPro.installer.yaml
  manifests/d/DirSoft/ARPro/17.0.1.968/DirSoft.ARPro.locale.en-US.yaml
  manifests/d/DirSoft/ARPro/17.0.1.968/DirSoft.ARPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111047 New version: MullvadVPN.MullvadVPN version 2023.4.0
  manifests/m/MullvadVPN/MullvadVPN/2023.4.0/MullvadVPN.MullvadVPN.installer.yaml
  manifests/m/MullvadVPN/MullvadVPN/2023.4.0/MullvadVPN.MullvadVPN.locale.en-US.yaml
  manifests/m/MullvadVPN/MullvadVPN/2023.4.0/MullvadVPN.MullvadVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111067 New version: KuaiFan.DooTask version 0.27.85
  manifests/k/KuaiFan/DooTask/0.27.85/KuaiFan.DooTask.installer.yaml
  manifests/k/KuaiFan/DooTask/0.27.85/KuaiFan.DooTask.locale.en-US.yaml
  manifests/k/KuaiFan/DooTask/0.27.85/KuaiFan.DooTask.locale.zh-CN.yaml
  manifests/k/KuaiFan/DooTask/0.27.85/KuaiFan.DooTask.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110955 New version: StephanDilly.gitui version 0.23.0
  manifests/s/StephanDilly/gitui/0.23.0/StephanDilly.gitui.installer.yaml
  manifests/s/StephanDilly/gitui/0.23.0/StephanDilly.gitui.locale.en-US.yaml
  manifests/s/StephanDilly/gitui/0.23.0/StephanDilly.gitui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110947 New package: GiulioSorrentino.CBriscola.WPF version 0.6
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6/GiulioSorrentino.CBriscola.WPF.installer.yaml
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6/GiulioSorrentino.CBriscola.WPF.locale.en-US.yaml
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6/GiulioSorrentino.CBriscola.WPF.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111048 New version: Unity.Unity Hub version 3.5.0
  manifests/u/Unity/UnityHub/3.5.0/Unity.UnityHub.installer.yaml
  manifests/u/Unity/UnityHub/3.5.0/Unity.UnityHub.locale.en-US.yaml
  manifests/u/Unity/UnityHub/3.5.0/Unity.UnityHub.locale.zh-CN.yaml
  manifests/u/Unity/UnityHub/3.5.0/Unity.UnityHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111046 New package: GiulioSorrentino.numeronesfortuneinavalonia version 2.0
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0/GiulioSorrentino.numeronesfortuneinavalonia.installer.yaml
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0/GiulioSorrentino.numeronesfortuneinavalonia.locale.en-US.yaml
  manifests/g/GiulioSorrentino/numeronesfortuneinavalonia/2.0/GiulioSorrentino.numeronesfortuneinavalonia.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#111073 New version: Adamant.Messenger version 4.0.0
  manifests/a/Adamant/Messenger/4.0.0/Adamant.Messenger.installer.yaml
  manifests/a/Adamant/Messenger/4.0.0/Adamant.Messenger.locale.en-US.yaml
  manifests/a/Adamant/Messenger/4.0.0/Adamant.Messenger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111020 New Version: Astronomer.Astro version 1.16.2
  manifests/a/Astronomer/Astro/1.16.2/Astronomer.Astro.installer.yaml
  manifests/a/Astronomer/Astro/1.16.2/Astronomer.Astro.locale.en-US.yaml
  manifests/a/Astronomer/Astro/1.16.2/Astronomer.Astro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111032 New version: FutureScholars.Paperlib version 2.2.3
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.installer.yaml
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.locale.en-US.yaml
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.locale.zh-CN.yaml
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111034 Vr photo converter 2.0
  manifests/j/Japplis/VRPhotoConverter/2.0/Japplis.VRPhotoConverter.installer.yaml
  manifests/j/Japplis/VRPhotoConverter/2.0/Japplis.VRPhotoConverter.locale.en-US.yaml
  manifests/j/Japplis/VRPhotoConverter/2.0/Japplis.VRPhotoConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111019 Zoom.Zoom version 5.15.2.18096
  manifests/z/Zoom/Zoom/5.15.2.18096/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/5.15.2.18096/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/5.15.2.18096/Zoom.Zoom.locale.zh-CN.yaml
  manifests/z/Zoom/Zoom/5.15.2.18096/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110965 Ant Commander Pro version 4.0
  manifests/j/Japplis/AntCommander/Pro/4.0/Japplis.AntCommander.Pro.installer.yaml
  manifests/j/Japplis/AntCommander/Pro/4.0/Japplis.AntCommander.Pro.locale.en-US.yaml
  manifests/j/Japplis/AntCommander/Pro/4.0/Japplis.AntCommander.Pro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110961 JIAYOU.FSWT version 1.0.0.0
  manifests/j/JIAYOU/FSWT/1.0.0.0/JIAYOU.FSWT.installer.yaml
  manifests/j/JIAYOU/FSWT/1.0.0.0/JIAYOU.FSWT.locale.en-US.yaml
  manifests/j/JIAYOU/FSWT/1.0.0.0/JIAYOU.FSWT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110943 Added uwscr 0.12.0
  manifests/s/stuncloud/uwscr/0.12.0/stuncloud.uwscr.installer.yaml
  manifests/s/stuncloud/uwscr/0.12.0/stuncloud.uwscr.locale.ja-JP.yaml
  manifests/s/stuncloud/uwscr/0.12.0/stuncloud.uwscr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110953 Update 0xGingi-Browser to 114.0.5735.199
  manifests/0/0xGingi/Browser/114.0.5735.199/0xGingi.Browser.installer.yaml
  manifests/0/0xGingi/Browser/114.0.5735.199/0xGingi.Browser.locale.en-US.yaml
  manifests/0/0xGingi/Browser/114.0.5735.199/0xGingi.Browser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111080 Update version: afractal.TwitterTron version 1.0.2
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.installer.yaml
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.locale.en-US.yaml
  manifests/a/afractal/TwitterTron/1.0.2/afractal.TwitterTron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111069 Add version: AutoHotkey.AutoHotkey version 1.1.37.00
  manifests/a/AutoHotkey/AutoHotkey/1.1.37.00/AutoHotkey.AutoHotkey.installer.yaml
  manifests/a/AutoHotkey/AutoHotkey/1.1.37.00/AutoHotkey.AutoHotkey.locale.en-US.yaml
  manifests/a/AutoHotkey/AutoHotkey/1.1.37.00/AutoHotkey.AutoHotkey.locale.zh-CN.yaml
  manifests/a/AutoHotkey/AutoHotkey/1.1.37.00/AutoHotkey.AutoHotkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#111015 New version: GyDi.ClashVerge version 1.3.3
  manifests/g/GyDi/ClashVerge/1.3.3/GyDi.ClashVerge.installer.yaml
  manifests/g/GyDi/ClashVerge/1.3.3/GyDi.ClashVerge.locale.en-US.yaml
  manifests/g/GyDi/ClashVerge/1.3.3/GyDi.ClashVerge.locale.zh-CN.yaml
  manifests/g/GyDi/ClashVerge/1.3.3/GyDi.ClashVerge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#111052 OpenJS.NodeJS.Nightly version 21.0.0-nightly202307011936160c31
  manifests/o/OpenJS/NodeJS/Nightly/21.0.0-nightly202307011936160c31/OpenJS.NodeJS.Nightly.installer.yaml
  manifests/o/OpenJS/NodeJS/Nightly/21.0.0-nightly202307011936160c31/OpenJS.NodeJS.Nightly.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/Nightly/21.0.0-nightly202307011936160c31/OpenJS.NodeJS.Nightly.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/Nightly/21.0.0-nightly202307011936160c31/OpenJS.NodeJS.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111099 New version: JetBrains.QodanaCLI version 2023.1.6
  manifests/j/JetBrains/QodanaCLI/2023.1.6/JetBrains.QodanaCLI.installer.yaml
  manifests/j/JetBrains/QodanaCLI/2023.1.6/JetBrains.QodanaCLI.locale.en-US.yaml
  manifests/j/JetBrains/QodanaCLI/2023.1.6/JetBrains.QodanaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110970 New version: Optimate.OptimateSOLIDWORKSPlugin version 0.7.0
  manifests/o/Optimate/OptimateSOLIDWORKSPlugin/0.7.0/Optimate.OptimateSOLIDWORKSPlugin.installer.yaml
  manifests/o/Optimate/OptimateSOLIDWORKSPlugin/0.7.0/Optimate.OptimateSOLIDWORKSPlugin.locale.en-US.yaml
  manifests/o/Optimate/OptimateSOLIDWORKSPlugin/0.7.0/Optimate.OptimateSOLIDWORKSPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-No-Executables

#110896 RubyInstallerTeam.RubyWithDevKit.3.2 version 3.2.2-1
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.2-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.2-1/RubyInstallerTeam.RubyWithDevKit.3.2.locale.en-US.yaml
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.2-1/RubyInstallerTeam.RubyWithDevKit.3.2.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#110877 Add March 2023 GDK Update 4.
  manifests/m/Microsoft/GDK/2303/230304/Microsoft.GDK.2303.installer.yaml
  manifests/m/Microsoft/GDK/2303/230304/Microsoft.GDK.2303.locale.en-US.yaml
  manifests/m/Microsoft/GDK/2303/230304/Microsoft.GDK.2303.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#110893 RubyInstallerTeam.RubyWithDevKit.3.2 version 3.2.1-1
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.1-1/RubyInstallerTeam.RubyWithDevKit.3.2.installer.yaml
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.1-1/RubyInstallerTeam.RubyWithDevKit.3.2.locale.en-US.yaml
  manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.1-1/RubyInstallerTeam.RubyWithDevKit.3.2.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#111059 KDE.LabPlot version 2.10.0
  manifests/k/KDE/LabPlot/2.10.0/KDE.LabPlot.installer.yaml
  manifests/k/KDE/LabPlot/2.10.0/KDE.LabPlot.locale.en-US.yaml
  manifests/k/KDE/LabPlot/2.10.0/KDE.LabPlot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111100 Added AWS Command Line Interface version 2.12.6.
  manifests/a/Amazon/AWSCLI/2.12.6/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.12.6/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.12.6/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111102 Updated Google Chrome Dev to version 116.0.5845.14.
  manifests/g/Google/Chrome/Dev/116.0.5845.14/Google.Chrome.Dev.installer.yaml
  manifests/g/Google/Chrome/Dev/116.0.5845.14/Google.Chrome.Dev.locale.en-US.yaml
  manifests/g/Google/Chrome/Dev/116.0.5845.14/Google.Chrome.Dev.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Dev/116.0.5845.14/Google.Chrome.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111101 Added Microsoft Edge version 114.0.1823.67.
  manifests/m/Microsoft/Edge/114.0.1823.67/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/114.0.1823.67/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/114.0.1823.67/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/114.0.1823.67/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111104 New version: KRTirtho.Spotube version 3.0.0
  manifests/k/KRTirtho/Spotube/3.0.0/KRTirtho.Spotube.installer.yaml
  manifests/k/KRTirtho/Spotube/3.0.0/KRTirtho.Spotube.locale.en-US.yaml
  manifests/k/KRTirtho/Spotube/3.0.0/KRTirtho.Spotube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111103 New version: Citrix.Workspace version 23.5.1.83
  manifests/c/Citrix/Workspace/23.5.1.83/Citrix.Workspace.installer.yaml
  manifests/c/Citrix/Workspace/23.5.1.83/Citrix.Workspace.locale.en-US.yaml
  manifests/c/Citrix/Workspace/23.5.1.83/Citrix.Workspace.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111105 JanDeDobbeleer.OhMyPosh version 17.6.0
  manifests/j/JanDeDobbeleer/OhMyPosh/17.6.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/17.6.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/17.6.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111107 MoritzBunkus.MKVToolNix version 78.0.0
  manifests/m/MoritzBunkus/MKVToolNix/78.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/78.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/78.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/78.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111109 New version: mikf.gallery-dl version 1.25.7
  manifests/m/mikf/gallery-dl/1.25.7/mikf.gallery-dl.installer.yaml
  manifests/m/mikf/gallery-dl/1.25.7/mikf.gallery-dl.locale.en-US.yaml
  manifests/m/mikf/gallery-dl/1.25.7/mikf.gallery-dl.locale.zh-CN.yaml
  manifests/m/mikf/gallery-dl/1.25.7/mikf.gallery-dl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111111 ReleaseNotes: FutureScholars.Paperlib version 2.2.2
  manifests/f/FutureScholars/Paperlib/2.2.2/FutureScholars.Paperlib.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111110 ReleaseNotes: FutureScholars.Paperlib version 2.2.3
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.installer.yaml
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.locale.en-US.yaml
  manifests/f/FutureScholars/Paperlib/2.2.3/FutureScholars.Paperlib.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111146 New version: Jackett.Jackett version 0.21.364
  manifests/j/Jackett/Jackett/0.21.364/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.364/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.364/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111150 Microsoft.VisualStudioCode.Insiders_v1.80.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.80.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111157 New version: pnpm.pnpm version 8.6.6
  manifests/p/pnpm/pnpm/8.6.6/pnpm.pnpm.installer.yaml
  manifests/p/pnpm/pnpm/8.6.6/pnpm.pnpm.locale.en-US.yaml
  manifests/p/pnpm/pnpm/8.6.6/pnpm.pnpm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111173 New version: HomeBank.HomeBank version 5.6.5
  manifests/h/HomeBank/HomeBank/5.6.5/HomeBank.HomeBank.installer.yaml
  manifests/h/HomeBank/HomeBank/5.6.5/HomeBank.HomeBank.locale.en-US.yaml
  manifests/h/HomeBank/HomeBank/5.6.5/HomeBank.HomeBank.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111174 Fix automatic removal of Help-Wanted label
  .github/policies/labelManagement.issueUpdated.yml
Labels: Moderator-Approved, Project-File, Needs-Attention

#111177 Update: REALiX.HWiNFO version 7.50
  manifests/r/REALiX/HWiNFO/7.50/REALiX.HWiNFO.installer.yaml
  manifests/r/REALiX/HWiNFO/7.50/REALiX.HWiNFO.locale.en-US.yaml
  manifests/r/REALiX/HWiNFO/7.50/REALiX.HWiNFO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111171 New version: YuzuEmu.Yuzu.Mainline version 1484
  manifests/y/YuzuEmu/Yuzu/Mainline/1484/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1484/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1484/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111166 New version: YuzuEmu.Yuzu.Mainline version 1479
  manifests/y/YuzuEmu/Yuzu/Mainline/1479/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1479/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1479/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111164 New version: YuzuEmu.Yuzu.Mainline version 1477
  manifests/y/YuzuEmu/Yuzu/Mainline/1477/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1477/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1477/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#111170 New version: YuzuEmu.Yuzu.Mainline version 1483
  manifests/y/YuzuEmu/Yuzu/Mainline/1483/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1483/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1483/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
