Repository microsoft/winget-pkgs, pull requests merged in 2023-05, with the labels that each got.

#103940 New version: mikf.gallery-dl version 1.25.3
  manifests/m/mikf/gallery-dl/1.25.3/mikf.gallery-dl.installer.yaml
  manifests/m/mikf/gallery-dl/1.25.3/mikf.gallery-dl.locale.en-US.yaml
  manifests/m/mikf/gallery-dl/1.25.3/mikf.gallery-dl.locale.zh-CN.yaml
  manifests/m/mikf/gallery-dl/1.25.3/mikf.gallery-dl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103943 Remove: yetone.OpenAITranslator version 0.0.31
  manifests/y/yetone/OpenAITranslator/0.0.31/yetone.OpenAITranslator.installer.yaml
  manifests/y/yetone/OpenAITranslator/0.0.31/yetone.OpenAITranslator.locale.en-US.yaml
  manifests/y/yetone/OpenAITranslator/0.0.31/yetone.OpenAITranslator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103942 New version: yetone.OpenAITranslator version 0.0.39
  manifests/y/yetone/OpenAITranslator/0.0.39/yetone.OpenAITranslator.installer.yaml
  manifests/y/yetone/OpenAITranslator/0.0.39/yetone.OpenAITranslator.locale.en-US.yaml
  manifests/y/yetone/OpenAITranslator/0.0.39/yetone.OpenAITranslator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103941 New version: Qingfeng.HeyboxAccelerator version 1.1.28
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.28/Qingfeng.HeyboxAccelerator.installer.yaml
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.28/Qingfeng.HeyboxAccelerator.locale.en-US.yaml
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.28/Qingfeng.HeyboxAccelerator.locale.zh-CN.yaml
  manifests/q/Qingfeng/HeyboxAccelerator/1.1.28/Qingfeng.HeyboxAccelerator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103825 New version: PerfectWorld.PerfectWorldArena version 1.0.23042811
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23042811/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23042811/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23042811/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23042811/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103827 New version: Apifox.Apifox version 2.2.37
  manifests/a/Apifox/Apifox/2.2.37/Apifox.Apifox.installer.yaml
  manifests/a/Apifox/Apifox/2.2.37/Apifox.Apifox.locale.en-US.yaml
  manifests/a/Apifox/Apifox/2.2.37/Apifox.Apifox.locale.zh-CN.yaml
  manifests/a/Apifox/Apifox/2.2.37/Apifox.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103960 Deleting. It look like URL is not found. CoolPlayLin.MOliGeek
  manifests/c/CoolPlayLin/MOliGeek/1.0.0.6/CoolPlayLin.MOliGeek.installer.yaml
  manifests/c/CoolPlayLin/MOliGeek/1.0.0.6/CoolPlayLin.MOliGeek.locale.en-US.yaml
  manifests/c/CoolPlayLin/MOliGeek/1.0.0.6/CoolPlayLin.MOliGeek.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103832 New version: vivo.OfficeKit version 2.0.4.0
  manifests/v/vivo/OfficeKit/2.0.4.0/vivo.OfficeKit.installer.yaml
  manifests/v/vivo/OfficeKit/2.0.4.0/vivo.OfficeKit.locale.en-US.yaml
  manifests/v/vivo/OfficeKit/2.0.4.0/vivo.OfficeKit.locale.zh-CN.yaml
  manifests/v/vivo/OfficeKit/2.0.4.0/vivo.OfficeKit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103959 New version: Jackett.Jackett version 0.20.4032
  manifests/j/Jackett/Jackett/0.20.4032/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.4032/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.4032/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103957 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103949 New version: jftuga.less version 632
  manifests/j/jftuga/less/632/jftuga.less.installer.yaml
  manifests/j/jftuga/less/632/jftuga.less.locale.en-US.yaml
  manifests/j/jftuga/less/632/jftuga.less.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103933 Revert "Updating Manifest to Malwarebytes.Malwarebytes 4.5.27.262"
  manifests/m/Malwarebytes/Malwarebytes/4.5.24.248/Malwarebytes.Malwarebytes.installer.yaml
  manifests/m/Malwarebytes/Malwarebytes/4.5.24.248/Malwarebytes.Malwarebytes.locale.en-US.yaml
  manifests/m/Malwarebytes/Malwarebytes/4.5.24.248/Malwarebytes.Malwarebytes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103935 MaxBQb.BulkStartStop version 1.0.3
  manifests/m/MaxBQb/BulkStartStop/1.0.3/MaxBQb.BulkStartStop.installer.yaml
  manifests/m/MaxBQb/BulkStartStop/1.0.3/MaxBQb.BulkStartStop.locale.en-US.yaml
  manifests/m/MaxBQb/BulkStartStop/1.0.3/MaxBQb.BulkStartStop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103931 Rufus.Rufus update to 4.0
  manifests/r/Rufus/Rufus/4.0/Rufus.Rufus.installer.yaml
  manifests/r/Rufus/Rufus/4.0/Rufus.Rufus.locale.en-US.yaml
  manifests/r/Rufus/Rufus/4.0/Rufus.Rufus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103953 SmartSoft.SmartFTP version 10.0.3099.0
  manifests/s/SmartSoft/SmartFTP/10.0.3099.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3099.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3099.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104001 Remove NordVPN.NordVPN 6.39.6.0 to NordSecurity.NordVPN 6.39.6.0
  manifests/n/NordVPN/NordVPN/6.39.6.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.39.6.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.39.6.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104003 Remove NordVPN.NordVPN 6.41.11.0 to NordSecurity.NordVPN 6.41.11.0
  manifests/n/NordVPN/NordVPN/6.41.11.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.41.11.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.41.11.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103998 Remove Nord.NordLocker 3.6.0.0 to NordSecurity.NordLocker 3.6.0.0
  manifests/n/Nord/NordLocker/3.6.0.0/Nord.NordLocker.installer.yaml
  manifests/n/Nord/NordLocker/3.6.0.0/Nord.NordLocker.locale.en-US.yaml
  manifests/n/Nord/NordLocker/3.6.0.0/Nord.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104004 Remove NordVPN.NordVPN 6.43.5.0 to NordSecurity.NordVPN 6.43.5.0
  manifests/n/NordVPN/NordVPN/6.43.5.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.43.5.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.43.5.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103966 New Version: Windscribe.Windscribe 2.6.14
  manifests/w/Windscribe/Windscribe/2.6.14/Windscribe.Windscribe.installer.yaml
  manifests/w/Windscribe/Windscribe/2.6.14/Windscribe.Windscribe.locale.en-US.yaml
  manifests/w/Windscribe/Windscribe/2.6.14/Windscribe.Windscribe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104002 Remove NordVPN.NordVPN 6.40.5.0 to NordSecurity.NordVPN 6.40.5.0
  manifests/n/NordVPN/NordVPN/6.40.5.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.40.5.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.40.5.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104008 Remove NordVPN.NordVPN 6.46.5.0 to NordSecurity.NordVPN 6.46.5.0
  manifests/n/NordVPN/NordVPN/6.46.5.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.46.5.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.46.5.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104010 Remove NordVPN.NordVPN 6.48.10.0 to NordSecurity.NordVPN 6.48.10.0
  manifests/n/NordVPN/NordVPN/6.48.10.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.48.10.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.48.10.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104007 Remove NordVPN.NordVPN 6.45.8.0 to NordSecurity.NordVPN 6.45.8.0
  manifests/n/NordVPN/NordVPN/6.45.8.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.45.8.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.45.8.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104012 Remove NordVPN.NordVPN 7.1.2.0 to NordSecurity.NordVPN 7.1.2.0
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.1.2.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104011 Remove NordVPN.NordVPN 7.1.1.0 to NordSecurity.NordVPN 7.1.1.0
  manifests/n/NordVPN/NordVPN/7.1.1.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.1.1.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.1.1.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104006 Remove NordVPN.NordVPN 6.45.10.0 to NordSecurity.NordVPN 6.45.10.0
  manifests/n/NordVPN/NordVPN/6.45.10.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.45.10.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.45.10.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103997 Remove Nord.NordLocker 3.1.0.0 to NordSecurity.NordLocker 3.1.0.0
  manifests/n/Nord/NordLocker/3.1.0.0/Nord.NordLocker.installer.yaml
  manifests/n/Nord/NordLocker/3.1.0.0/Nord.NordLocker.locale.en-US.yaml
  manifests/n/Nord/NordLocker/3.1.0.0/Nord.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103995 Remove Nord.NordLocker 2.2.16.0 to NordSecurity.NordLocker 2.2.16.0
  manifests/n/Nord/NordLocker/2.2.16.0/Nord.NordLocker.installer.yaml
  manifests/n/Nord/NordLocker/2.2.16.0/Nord.NordLocker.locale.en-US.yaml
  manifests/n/Nord/NordLocker/2.2.16.0/Nord.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103996 Remove Nord.NordLocker 3.0.0.0 to NordSecurity.NordLocker 3.0.0.0
  manifests/n/Nord/NordLocker/3.0.0.0/Nord.NordLocker.installer.yaml
  manifests/n/Nord/NordLocker/3.0.0.0/Nord.NordLocker.locale.en-US.yaml
  manifests/n/Nord/NordLocker/3.0.0.0/Nord.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104005 Remove NordVPN.NordVPN 6.44.5.0 to NordSecurity.NordVPN 6.44.5.0
  manifests/n/NordVPN/NordVPN/6.44.5.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.44.5.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.44.5.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104013 Remove NordVPN.NordVPN 7.2.2.0 to NordSecurity.NordVPN 7.2.2.0
  manifests/n/NordVPN/NordVPN/7.2.2.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.2.2.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.2.2.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104014 Remove NordVPN.NordVPN 7.2.6.0 to NordSecurity.NordVPN 7.2.6.0
  manifests/n/NordVPN/NordVPN/7.2.6.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.2.6.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.2.6.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103946 Agent SVN Version 2.75
  manifests/x/Xidicone/AgentSVN/2.75/Xidicone.AgentSVN.installer.yaml
  manifests/x/Xidicone/AgentSVN/2.75/Xidicone.AgentSVN.locale.en-US.yaml
  manifests/x/Xidicone/AgentSVN/2.75/Xidicone.AgentSVN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103970 New version: tailscale.tailscale version 1.40.0
  manifests/t/tailscale/tailscale/1.40.0/tailscale.tailscale.installer.yaml
  manifests/t/tailscale/tailscale/1.40.0/tailscale.tailscale.locale.en-US.yaml
  manifests/t/tailscale/tailscale/1.40.0/tailscale.tailscale.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104000 Remove NordVPN.NordVPN 6.38.15.0 to NordSecurity.NordVPN 6.38.15.0
  manifests/n/NordVPN/NordVPN/6.38.15.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/6.38.15.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/6.38.15.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103988 Move NordVPN.NordVPN 6.48.10.0 to NordSecurity.NordVPN 6.48.10.0
  manifests/n/NordSecurity/NordVPN/6.48.10.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.48.10.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.48.10.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103987 Move NordVPN.NordVPN 6.47.13.0 to NordSecurity.NordVPN 6.47.13.0
  manifests/n/NordSecurity/NordVPN/6.47.13.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.47.13.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.47.13.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103835 Moved: vivo.OfficeKit version 2.0.3.0
  manifests/v/vivo/OfficeKit/2.0.3.0/vivo.OfficeKit.installer.yaml
  manifests/v/vivo/OfficeKit/2.0.3.0/vivo.OfficeKit.locale.en-US.yaml
  manifests/v/vivo/OfficeKit/2.0.3.0/vivo.OfficeKit.locale.zh-CN.yaml
  manifests/v/vivo/OfficeKit/2.0.3.0/vivo.OfficeKit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#103993 Move NordVPN.NordVPN 7.3.9.0 to NordSecurity.NordVPN 7.3.9.0
  manifests/n/NordSecurity/NordVPN/7.3.9.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/7.3.9.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/7.3.9.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#103992 Move NordVPN.NordVPN 7.2.6.0 to NordSecurity.NordVPN 7.2.6.0
  manifests/n/NordSecurity/NordVPN/7.2.6.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/7.2.6.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/7.2.6.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103986 Move NordVPN.NordVPN 6.46.5.0 to NordSecurity.NordVPN 6.46.5.0
  manifests/n/NordSecurity/NordVPN/6.46.5.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.46.5.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.46.5.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104015 Add version: Audacity.Audacity version 3.2.5
  manifests/a/Audacity/Audacity/3.2.5/Audacity.Audacity.installer.yaml
  manifests/a/Audacity/Audacity/3.2.5/Audacity.Audacity.locale.en-US.yaml
  manifests/a/Audacity/Audacity/3.2.5/Audacity.Audacity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#102739 New version: 3CX.Softphone version 18.12.425
  manifests/3/3CX/Softphone/18.12.425/3CX.Softphone.installer.yaml
  manifests/3/3CX/Softphone/18.12.425/3CX.Softphone.locale.en-US.yaml
  manifests/3/3CX/Softphone/18.12.425/3CX.Softphone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104018 New version: TeamViewer.TeamViewer.Host version 15.41.8
  manifests/t/TeamViewer/TeamViewer/Host/15.41.8/TeamViewer.TeamViewer.Host.installer.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.41.8/TeamViewer.TeamViewer.Host.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/Host/15.41.8/TeamViewer.TeamViewer.Host.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104019 Update version: jftuga.less version 632
  manifests/j/jftuga/less/632/jftuga.less.installer.yaml
  manifests/j/jftuga/less/632/jftuga.less.locale.en-US.yaml
  manifests/j/jftuga/less/632/jftuga.less.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103971 New version: WinFsp.WinFsp version 2.0.23075
  manifests/w/WinFsp/WinFsp/2.0.23075/WinFsp.WinFsp.installer.yaml
  manifests/w/WinFsp/WinFsp/2.0.23075/WinFsp.WinFsp.locale.en-US.yaml
  manifests/w/WinFsp/WinFsp/2.0.23075/WinFsp.WinFsp.yaml
  manifests/w/WinFsp/WinFsp/2.0/WinFsp.WinFsp.locale.en-US.yaml
  manifests/w/WinFsp/WinFsp/2.0/WinFsp.WinFsp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103958 Updating-Details- Headwindsim.HeadwindInstaller 1.3.2
  manifests/h/Headwindsim/HeadwindInstaller/1.3.2/Headwindsim.HeadwindInstaller.installer.yaml
  manifests/h/Headwindsim/HeadwindInstaller/1.3.2/Headwindsim.HeadwindInstaller.locale.en-US.yaml
  manifests/h/Headwindsim/HeadwindInstaller/1.3.2/Headwindsim.HeadwindInstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103849 Add zig 0.10.1
  manifests/z/zig/zig/0.10.1/zig.zig.installer.yaml
  manifests/z/zig/zig/0.10.1/zig.zig.locale.en-US.yaml
  manifests/z/zig/zig/0.10.1/zig.zig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103868 New version: LinwoodDev.Flow.Nightly version 0.1.2
  manifests/l/LinwoodDev/Flow/Nightly/0.1.2/LinwoodDev.Flow.Nightly.installer.yaml
  manifests/l/LinwoodDev/Flow/Nightly/0.1.2/LinwoodDev.Flow.Nightly.locale.en-US.yaml
  manifests/l/LinwoodDev/Flow/Nightly/0.1.2/LinwoodDev.Flow.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103876 New App: tummychow.git-absorb
  manifests/t/tummychow/git-absorb/0.6.10/tummychow.git-absorb.installer.yaml
  manifests/t/tummychow/git-absorb/0.6.10/tummychow.git-absorb.locale.en-US.yaml
  manifests/t/tummychow/git-absorb/0.6.10/tummychow.git-absorb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103841 Bug fixes and added features to simple Chess program.
  manifests/s/SpencerSoft/Chess/1.0.0/SpencerSoft.Chess.installer.yaml
Labels: Validation-Completed, Retry-1

#103964 New Version: VMware.WorkstationPlayer version 17.0.2.21581411
  manifests/v/VMware/WorkstationPlayer/17.0.2/VMware.WorkstationPlayer.installer.yaml
  manifests/v/VMware/WorkstationPlayer/17.0.2/VMware.WorkstationPlayer.locale.en-US.yaml
  manifests/v/VMware/WorkstationPlayer/17.0.2/VMware.WorkstationPlayer.yaml
Labels: Validation-Completed, Moderator-Approved

#103965 New Version: VMware.WorkstationPro version 17.0.2.21581411
  manifests/v/VMware/WorkstationPro/17.0.2/VMware.WorkstationPro.installer.yaml
  manifests/v/VMware/WorkstationPro/17.0.2/VMware.WorkstationPro.locale.en-US.yaml
  manifests/v/VMware/WorkstationPro/17.0.2/VMware.WorkstationPro.yaml
Labels: Validation-Completed, Moderator-Approved

#103732 Uncrustify.Uncrustify version 0.76.0
  manifests/u/Uncrustify/Uncrustify/0.76.0/Uncrustify.Uncrustify.installer.yaml
  manifests/u/Uncrustify/Uncrustify/0.76.0/Uncrustify.Uncrustify.locale.en-US.yaml
  manifests/u/Uncrustify/Uncrustify/0.76.0/Uncrustify.Uncrustify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Unapproved-URL

#103990 Move NordVPN.NordVPN 7.1.2.0 to NordSecurity.NordVPN 7.1.2.0
  manifests/n/NordSecurity/NordVPN/7.1.2.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/7.1.2.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/7.1.2.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103991 Move NordVPN.NordVPN 7.2.2.0 to NordSecurity.NordVPN 7.2.2.0
  manifests/n/NordSecurity/NordVPN/7.2.2.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/7.2.2.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/7.2.2.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103956 Lapce.Lapce version 0.2.7
  manifests/l/Lapce/Lapce/0.2.7/Lapce.Lapce.installer.yaml
  manifests/l/Lapce/Lapce/0.2.7/Lapce.Lapce.locale.en-US.yaml
  manifests/l/Lapce/Lapce/0.2.7/Lapce.Lapce.locale.zh-CN.yaml
  manifests/l/Lapce/Lapce/0.2.7/Lapce.Lapce.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#103989 Move NordVPN.NordVPN 7.1.1.0 to NordSecurity.NordVPN 7.1.1.0
  manifests/n/NordSecurity/NordVPN/7.1.1.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/7.1.1.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/7.1.1.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#103973 Move Nord.NordLocker 3.0.0.0 to NordSecurity.NordLocker 3.0.0.0
  manifests/n/NordSecurity/NordLocker/3.0.0.0/NordSecurity.NordLocker.installer.yaml
  manifests/n/NordSecurity/NordLocker/3.0.0.0/NordSecurity.NordLocker.locale.en-US.yaml
  manifests/n/NordSecurity/NordLocker/3.0.0.0/NordSecurity.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#104025 New package: sikalabs.slu version 0.66.0
  manifests/s/sikalabs/slu/0.66.0/sikalabs.slu.installer.yaml
  manifests/s/sikalabs/slu/0.66.0/sikalabs.slu.locale.en-US.yaml
  manifests/s/sikalabs/slu/0.66.0/sikalabs.slu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#103980 Move NordVPN.NordVPN 6.40.5.0 to NordSecurity.NordVPN 6.40.5.0
  manifests/n/NordSecurity/NordVPN/6.40.5.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.40.5.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.40.5.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103974 Move Nord.NordLocker 3.1.0.0 to NordSecurity.NordLocker 3.1.0.0
  manifests/n/NordSecurity/NordLocker/3.1.0.0/NordSecurity.NordLocker.installer.yaml
  manifests/n/NordSecurity/NordLocker/3.1.0.0/NordSecurity.NordLocker.locale.en-US.yaml
  manifests/n/NordSecurity/NordLocker/3.1.0.0/NordSecurity.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103972 Move Nord.NordLocker 2.2.16.0 to NordSecurity.NordLocker 2.2.16.0
  manifests/n/NordSecurity/NordLocker/2.2.16.0/NordSecurity.NordLocker.installer.yaml
  manifests/n/NordSecurity/NordLocker/2.2.16.0/NordSecurity.NordLocker.locale.en-US.yaml
  manifests/n/NordSecurity/NordLocker/2.2.16.0/NordSecurity.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103982 Move NordVPN.NordVPN 6.43.5.0 to NordSecurity.NordVPN 6.43.5.0
  manifests/n/NordSecurity/NordVPN/6.43.5.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.43.5.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.43.5.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103985 Move NordVPN.NordVPN 6.45.8.0 to NordSecurity.NordVPN 6.45.8.0
  manifests/n/NordSecurity/NordVPN/6.45.8.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.45.8.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.45.8.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103981 Move NordVPN.NordVPN 6.41.11.0 to NordSecurity.NordVPN 6.41.11.0
  manifests/n/NordSecurity/NordVPN/6.41.11.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.41.11.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.41.11.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103983 Move NordVPN.NordVPN 6.44.5.0 to NordSecurity.NordVPN 6.44.5.0
  manifests/n/NordSecurity/NordVPN/6.44.5.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.44.5.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.44.5.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103979 Move NordVPN.NordVPN 6.39.6.0 to NordSecurity.NordVPN 6.39.6.0
  manifests/n/NordSecurity/NordVPN/6.39.6.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.39.6.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.39.6.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103977 Move NordPassTeam.NordPass 5.1.12 to NordSecurity.NordPass 5.1.12
  manifests/n/NordSecurity/NordPass/5.1.12/NordSecurity.NordPass.installer.yaml
  manifests/n/NordSecurity/NordPass/5.1.12/NordSecurity.NordPass.locale.en-US.yaml
  manifests/n/NordSecurity/NordPass/5.1.12/NordSecurity.NordPass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Waived-Validation-Domain

#103978 Move NordVPN.NordVPN 6.38.15.0 to NordSecurity.NordVPN 6.38.15.0
  manifests/n/NordSecurity/NordVPN/6.38.15.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.38.15.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.38.15.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Waived-Validation-Domain

#104031 Remove Nord.NordLocker 3.7.0.0 to NordSecurity.NordLocker 3.7.0.0
  manifests/n/Nord/NordLocker/3.7.0.0/Nord.NordLocker.installer.yaml
  manifests/n/Nord/NordLocker/3.7.0.0/Nord.NordLocker.locale.en-US.yaml
  manifests/n/Nord/NordLocker/3.7.0.0/Nord.NordLocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#104030 Remove NordVPN.NordVPN 7.3.9.0 to NordSecurity.NordVPN 7.3.9.0
  manifests/n/NordVPN/NordVPN/7.3.9.0/NordVPN.NordVPN.installer.yaml
  manifests/n/NordVPN/NordVPN/7.3.9.0/NordVPN.NordVPN.locale.en-US.yaml
  manifests/n/NordVPN/NordVPN/7.3.9.0/NordVPN.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#104028 errata-ai.Vale version 2.25.2
  manifests/e/errata-ai/Vale/2.25.2/errata-ai.Vale.installer.yaml
  manifests/e/errata-ai/Vale/2.25.2/errata-ai.Vale.locale.en-US.yaml
  manifests/e/errata-ai/Vale/2.25.2/errata-ai.Vale.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#104026 SmartSoft.SmartFTP version 10.0.3100.0
  manifests/s/SmartSoft/SmartFTP/10.0.3100.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3100.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3100.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#103994 Move NordVPN.NordVPN 6.37.5.0 to NordSecurity.NordVPN 6.37.5.0
  manifests/n/NordSecurity/NordVPN/6.37.5.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.37.5.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.37.5.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Waived-Validation-Domain

#103984 Move NordVPN.NordVPN 6.45.10.0 to NordSecurity.NordVPN 6.45.10.0
  manifests/n/NordSecurity/NordVPN/6.45.10.0/NordSecurity.NordVPN.installer.yaml
  manifests/n/NordSecurity/NordVPN/6.45.10.0/NordSecurity.NordVPN.locale.en-US.yaml
  manifests/n/NordSecurity/NordVPN/6.45.10.0/NordSecurity.NordVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#103854 Add Scope and ElevationRequirement filips.FirefoxPWA
  manifests/f/filips/FirefoxPWA/2.5.0/filips.FirefoxPWA.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#104042 SABnzbdTeam.SABnzbd version 4.0.1
  manifests/s/SABnzbdTeam/SABnzbd/4.0.1/SABnzbdTeam.SABnzbd.installer.yaml
  manifests/s/SABnzbdTeam/SABnzbd/4.0.1/SABnzbdTeam.SABnzbd.locale.en-US.yaml
  manifests/s/SABnzbdTeam/SABnzbd/4.0.1/SABnzbdTeam.SABnzbd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104045 MoritzBunkus.MKVToolNix version 76.0.0
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104046 DEVCOM.JetBrainsMonoNerdFont version 3.0.0
  manifests/d/DEVCOM/JetBrainsMonoNerdFont/3.0.0/DEVCOM.JetBrainsMonoNerdFont.installer.yaml
  manifests/d/DEVCOM/JetBrainsMonoNerdFont/3.0.0/DEVCOM.JetBrainsMonoNerdFont.locale.en-US.yaml
  manifests/d/DEVCOM/JetBrainsMonoNerdFont/3.0.0/DEVCOM.JetBrainsMonoNerdFont.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104020 New version: TeamViewer.TeamViewer version 15.41.8
  manifests/t/TeamViewer/TeamViewer/15.41.8/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.41.8/TeamViewer.TeamViewer.locale.de-DE.yaml
  manifests/t/TeamViewer/TeamViewer/15.41.8/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.41.8/TeamViewer.TeamViewer.locale.zh-CN.yaml
  manifests/t/TeamViewer/TeamViewer/15.41.8/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#104055 Changing UpgradeBehaviour
  manifests/c/CodeIndustry/MasterPdfEditor/5.9.40/CodeIndustry.MasterPdfEditor.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104053 Remove: yetone.OpenAITranslator version 0.0.33
  manifests/y/yetone/OpenAITranslator/0.0.33/yetone.OpenAITranslator.installer.yaml
  manifests/y/yetone/OpenAITranslator/0.0.33/yetone.OpenAITranslator.locale.en-US.yaml
  manifests/y/yetone/OpenAITranslator/0.0.33/yetone.OpenAITranslator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104057 New version: Brave.Brave.Nightly version 113.1.53.10
  manifests/b/Brave/Brave/Nightly/113.1.53.10/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/113.1.53.10/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/113.1.53.10/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/113.1.53.10/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104062 ReleaseNotes: MoritzBunkus.MKVToolNix version 76.0.0
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/76.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104060 New version: dynobo.NormCap version 0.4.1
  manifests/d/dynobo/NormCap/0.4.1/dynobo.NormCap.installer.yaml
  manifests/d/dynobo/NormCap/0.4.1/dynobo.NormCap.locale.en-US.yaml
  manifests/d/dynobo/NormCap/0.4.1/dynobo.NormCap.locale.zh-CN.yaml
  manifests/d/dynobo/NormCap/0.4.1/dynobo.NormCap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104061 New version: tangshimin.MuJing version 2.0.4
  manifests/t/tangshimin/MuJing/2.0.4/tangshimin.MuJing.installer.yaml
  manifests/t/tangshimin/MuJing/2.0.4/tangshimin.MuJing.locale.en-US.yaml
  manifests/t/tangshimin/MuJing/2.0.4/tangshimin.MuJing.locale.zh-CN.yaml
  manifests/t/tangshimin/MuJing/2.0.4/tangshimin.MuJing.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104067 Remove: Alphayama.PowerIAST version 1.0
  manifests/a/Alphayama/PowerIAST/1.0/Alphayama.PowerIAST.installer.yaml
  manifests/a/Alphayama/PowerIAST/1.0/Alphayama.PowerIAST.locale.en-US.yaml
  manifests/a/Alphayama/PowerIAST/1.0/Alphayama.PowerIAST.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104069 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.5.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.5.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.5.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104074 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.4.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.4.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.4.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104076 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.6.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.6.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.6.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104073 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.3.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.3.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.3.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104079 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.8.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.8.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.8.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104081 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.10.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.10.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.10.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104083 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.8.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.8.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.8.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104082 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.7.0.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.7.0.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.7.0.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104075 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.5.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.5.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.5.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104084 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.8.1/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.8.1/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.8.1/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104080 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.9.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.9.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.9.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104088 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104071 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.1.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.1.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.1.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#104070 Remove AmineMouafik.Ferdi * Repo is 404
  manifests/a/AmineMouafik/Ferdi/5.6.0.0/AmineMouafik.Ferdi.installer.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.0.0/AmineMouafik.Ferdi.locale.en-US.yaml
  manifests/a/AmineMouafik/Ferdi/5.6.0.0/AmineMouafik.Ferdi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104059 New version: vim.vim version 9.0.1504
  manifests/v/vim/vim/9.0.1504/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1504/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1504/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104096 New version: StandardNotes.StandardNotes version 3.153.7
  manifests/s/StandardNotes/StandardNotes/3.153.7/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.7/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.7/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104101 New version: StandardNotes.StandardNotes version 3.153.12
  manifests/s/StandardNotes/StandardNotes/3.153.12/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.12/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.12/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104099 New version: StandardNotes.StandardNotes version 3.153.9
  manifests/s/StandardNotes/StandardNotes/3.153.9/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.9/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.9/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104100 New version: StandardNotes.StandardNotes version 3.153.11
  manifests/s/StandardNotes/StandardNotes/3.153.11/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.11/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.11/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104021 Microsoft.VisualStudio.2022.Enterprise version 17.5.5
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.5.5/Microsoft.VisualStudio.2022.Enterprise.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.5.5/Microsoft.VisualStudio.2022.Enterprise.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Enterprise/17.5.5/Microsoft.VisualStudio.2022.Enterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104022 Microsoft.VisualStudio.2022.Community version 17.5.5
  manifests/m/Microsoft/VisualStudio/2022/Community/17.5.5/Microsoft.VisualStudio.2022.Community.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/17.5.5/Microsoft.VisualStudio.2022.Community.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/17.5.5/Microsoft.VisualStudio.2022.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104098 New version: StandardNotes.StandardNotes version 3.153.8
  manifests/s/StandardNotes/StandardNotes/3.153.8/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.8/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.8/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104023 Microsoft.VisualStudio.2022.Professional version 17.5.5
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.5.5/Microsoft.VisualStudio.2022.Professional.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.5.5/Microsoft.VisualStudio.2022.Professional.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/17.5.5/Microsoft.VisualStudio.2022.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104109 New version: StandardNotes.StandardNotes version 3.154.1
  manifests/s/StandardNotes/StandardNotes/3.154.1/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.154.1/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.154.1/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104106 New version: StandardNotes.StandardNotes version 3.153.13
  manifests/s/StandardNotes/StandardNotes/3.153.13/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.13/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.153.13/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104108 New version: StandardNotes.StandardNotes version 3.154.0
  manifests/s/StandardNotes/StandardNotes/3.154.0/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.154.0/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.154.0/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104116 Added Microsoft Edge version 112.0.1722.68.
  manifests/m/Microsoft/Edge/112.0.1722.68/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/112.0.1722.68/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/112.0.1722.68/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/112.0.1722.68/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104118 Added Microsoft Edge Dev version 114.0.1807.6.
  manifests/m/Microsoft/Edge/Dev/114.0.1807.6/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/114.0.1807.6/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/114.0.1807.6/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104136 Update: the-sz.SpyEx version 1.37
  manifests/t/the-sz/SpyEx/1.37/the-sz.SpyEx.installer.yaml
  manifests/t/the-sz/SpyEx/1.37/the-sz.SpyEx.locale.en-US.yaml
  manifests/t/the-sz/SpyEx/1.37/the-sz.SpyEx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104128 Update: TrueHumanDesign.Diffinity version 0.9.4
  manifests/t/TrueHumanDesign/Diffinity/0.9.4/TrueHumanDesign.Diffinity.installer.yaml
  manifests/t/TrueHumanDesign/Diffinity/0.9.4/TrueHumanDesign.Diffinity.locale.en-US.yaml
  manifests/t/TrueHumanDesign/Diffinity/0.9.4/TrueHumanDesign.Diffinity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104133 Remove: the-sz.Trion version 1.15
  manifests/t/the-sz/Trion/1.15/the-sz.Trion.installer.yaml
  manifests/t/the-sz/Trion/1.15/the-sz.Trion.locale.en-US.yaml
  manifests/t/the-sz/Trion/1.15/the-sz.Trion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104124 Update: Yubico.Authenticator version 5.0.4
  manifests/y/Yubico/Authenticator/5.0.4/Yubico.Authenticator.installer.yaml
  manifests/y/Yubico/Authenticator/5.0.4/Yubico.Authenticator.locale.en-US.yaml
  manifests/y/Yubico/Authenticator/5.0.4/Yubico.Authenticator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104130 New version: TopalaSoftwareSolutions.SIW version 2023.04.24c
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24c/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24c/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24c/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104135 Update: the-sz.Temple version 1.21
  manifests/t/the-sz/Temple/1.21/the-sz.Temple.installer.yaml
  manifests/t/the-sz/Temple/1.21/the-sz.Temple.locale.en-US.yaml
  manifests/t/the-sz/Temple/1.21/the-sz.Temple.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104123 Update: Yubico.Authenticator version 5.0.5
  manifests/y/Yubico/Authenticator/5.0.5/Yubico.Authenticator.installer.yaml
  manifests/y/Yubico/Authenticator/5.0.5/Yubico.Authenticator.locale.en-US.yaml
  manifests/y/Yubico/Authenticator/5.0.5/Yubico.Authenticator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104154 Remove: Nilesoft.Shell version 1.8.0.0
  manifests/n/Nilesoft/Shell/1.8.0.0/Nilesoft.Shell.installer.yaml
  manifests/n/Nilesoft/Shell/1.8.0.0/Nilesoft.Shell.locale.en-US.yaml
  manifests/n/Nilesoft/Shell/1.8.0.0/Nilesoft.Shell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104143 Update: SecureMixLLC.GlassWire version 3.3.501
  manifests/s/SecureMixLLC/GlassWire/3.3.501/SecureMixLLC.GlassWire.installer.yaml
  manifests/s/SecureMixLLC/GlassWire/3.3.501/SecureMixLLC.GlassWire.locale.en-US.yaml
  manifests/s/SecureMixLLC/GlassWire/3.3.501/SecureMixLLC.GlassWire.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104127 Update: Trimble.SketchUp.Pro.2022 version 22.0.354
  manifests/t/Trimble/SketchUp/Pro/2022/22.0.354/Trimble.SketchUp.Pro.2022.installer.yaml
  manifests/t/Trimble/SketchUp/Pro/2022/22.0.354/Trimble.SketchUp.Pro.2022.locale.en-US.yaml
  manifests/t/Trimble/SketchUp/Pro/2022/22.0.354/Trimble.SketchUp.Pro.2022.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104138 CloudImperiumGames.RSILauncher version 1.6.6
  manifests/c/CloudImperiumGames/RSILauncher/1.6.6/CloudImperiumGames.RSILauncher.installer.yaml
  manifests/c/CloudImperiumGames/RSILauncher/1.6.6/CloudImperiumGames.RSILauncher.locale.en-US.yaml
  manifests/c/CloudImperiumGames/RSILauncher/1.6.6/CloudImperiumGames.RSILauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104149 Update: Romcenter.Romcenter version 4.1.1
  manifests/r/Romcenter/Romcenter/4.1.1/Romcenter.Romcenter.installer.yaml
  manifests/r/Romcenter/Romcenter/4.1.1/Romcenter.Romcenter.locale.en-US.yaml
  manifests/r/Romcenter/Romcenter/4.1.1/Romcenter.Romcenter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104144 Update: SatoshiLabs.TrezorBridge version 2.0.27
  manifests/s/SatoshiLabs/TrezorBridge/2.0.27/SatoshiLabs.TrezorBridge.installer.yaml
  manifests/s/SatoshiLabs/TrezorBridge/2.0.27/SatoshiLabs.TrezorBridge.locale.en-US.yaml
  manifests/s/SatoshiLabs/TrezorBridge/2.0.27/SatoshiLabs.TrezorBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104150 Update: PPSSPPTeam.PPSSPP version 1.11.3.0
  manifests/p/PPSSPPTeam/PPSSPP/1.11.3.0/PPSSPPTeam.PPSSPP.installer.yaml
  manifests/p/PPSSPPTeam/PPSSPP/1.11.3.0/PPSSPPTeam.PPSSPP.locale.en-US.yaml
  manifests/p/PPSSPPTeam/PPSSPP/1.11.3.0/PPSSPPTeam.PPSSPP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104132 Update: the-sz.Yale version 1.25
  manifests/t/the-sz/Yale/1.25/the-sz.Yale.installer.yaml
  manifests/t/the-sz/Yale/1.25/the-sz.Yale.locale.en-US.yaml
  manifests/t/the-sz/Yale/1.25/the-sz.Yale.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#104155 Remove: Nilesoft.Shell version 1.7.0.0
  manifests/n/Nilesoft/Shell/1.7.0.0/Nilesoft.Shell.installer.yaml
  manifests/n/Nilesoft/Shell/1.7.0.0/Nilesoft.Shell.locale.en-US.yaml
  manifests/n/Nilesoft/Shell/1.7.0.0/Nilesoft.Shell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104156 Update: NathanMoinvaziri.ExtractNow version 4.8.3.0
  manifests/n/NathanMoinvaziri/ExtractNow/4.8.3.0/NathanMoinvaziri.ExtractNow.installer.yaml
  manifests/n/NathanMoinvaziri/ExtractNow/4.8.3.0/NathanMoinvaziri.ExtractNow.locale.en-US.yaml
  manifests/n/NathanMoinvaziri/ExtractNow/4.8.3.0/NathanMoinvaziri.ExtractNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104117 Added Microsoft Edge Beta version 113.0.1774.27.
  manifests/m/Microsoft/Edge/Beta/113.0.1774.27/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/113.0.1774.27/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/113.0.1774.27/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104152 Update: Passcovery.PasscoverySuite version 23.3.48.4062
  manifests/p/Passcovery/PasscoverySuite/23.3.48.4062/Passcovery.PasscoverySuite.installer.yaml
  manifests/p/Passcovery/PasscoverySuite/23.3.48.4062/Passcovery.PasscoverySuite.locale.en-US.yaml
  manifests/p/Passcovery/PasscoverySuite/23.3.48.4062/Passcovery.PasscoverySuite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104166 Remove: HiBitSoftware.StartUpManager version 2.5.15.100
  manifests/h/HiBitSoftware/StartUpManager/2.5.15.100/HiBitSoftware.StartUpManager.installer.yaml
  manifests/h/HiBitSoftware/StartUpManager/2.5.15.100/HiBitSoftware.StartUpManager.locale.en-US.yaml
  manifests/h/HiBitSoftware/StartUpManager/2.5.15.100/HiBitSoftware.StartUpManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104163 Remove: TopalaSoftwareSolutions.SIW version 2023.04.24b
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24b/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24b/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.04.24b/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104160 Update: InstantHousecall.InstantHousecall version 7.0.2.0
  manifests/i/InstantHousecall/InstantHousecall/7.0.2.0/InstantHousecall.InstantHousecall.installer.yaml
  manifests/i/InstantHousecall/InstantHousecall/7.0.2.0/InstantHousecall.InstantHousecall.locale.en-US.yaml
  manifests/i/InstantHousecall/InstantHousecall/7.0.2.0/InstantHousecall.InstantHousecall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104158 JanDeDobbeleer.OhMyPosh version 15.4.1
  manifests/j/JanDeDobbeleer/OhMyPosh/15.4.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/15.4.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/15.4.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104141 Add Geekbench 6.0.3
  manifests/p/PrimateLabs/Geekbench/6/6.0.3/PrimateLabs.Geekbench.6.installer.yaml
  manifests/p/PrimateLabs/Geekbench/6/6.0.3/PrimateLabs.Geekbench.6.locale.en-US.yaml
  manifests/p/PrimateLabs/Geekbench/6/6.0.3/PrimateLabs.Geekbench.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104168 Update: HiBitSoftware.HiBitUninstaller version 3.1.20.300
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.20.300/HiBitSoftware.HiBitUninstaller.installer.yaml
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.20.300/HiBitSoftware.HiBitUninstaller.locale.en-US.yaml
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.20.300/HiBitSoftware.HiBitUninstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104167 Update: HiBitSoftware.StartUpManager version 2.6.10.100
  manifests/h/HiBitSoftware/StartUpManager/2.6.10.100/HiBitSoftware.StartUpManager.installer.yaml
  manifests/h/HiBitSoftware/StartUpManager/2.6.10.100/HiBitSoftware.StartUpManager.locale.en-US.yaml
  manifests/h/HiBitSoftware/StartUpManager/2.6.10.100/HiBitSoftware.StartUpManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104092 New version: YuzuEmu.Yuzu.Mainline version 1413
  manifests/y/YuzuEmu/Yuzu/Mainline/1413/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1413/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1413/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104091 New version: YuzuEmu.Yuzu.Mainline version 1412
  manifests/y/YuzuEmu/Yuzu/Mainline/1412/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1412/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1412/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104090 New version: YuzuEmu.Yuzu.Mainline version 1411
  manifests/y/YuzuEmu/Yuzu/Mainline/1411/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1411/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1411/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104178 Remove NordPassTeam.NordPass 5.1.12 to NordSecurity.NordPass 5.1.12
  manifests/n/NordPassTeam/NordPass/5.1.12/NordPassTeam.NordPass.installer.yaml
  manifests/n/NordPassTeam/NordPass/5.1.12/NordPassTeam.NordPass.locale.en-US.yaml
  manifests/n/NordPassTeam/NordPass/5.1.12/NordPassTeam.NordPass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104065 New version: rocksdanister.LivelyWallpaper version 2.0.6.5
  manifests/r/rocksdanister/LivelyWallpaper/2.0.6.5/rocksdanister.LivelyWallpaper.installer.yaml
  manifests/r/rocksdanister/LivelyWallpaper/2.0.6.5/rocksdanister.LivelyWallpaper.locale.en-US.yaml
  manifests/r/rocksdanister/LivelyWallpaper/2.0.6.5/rocksdanister.LivelyWallpaper.yaml
Labels: Validation-Completed, Retry-1

#104182 Remove Alibaba.aDrive version 3.1.0
  manifests/a/Alibaba/aDrive/3.1.0/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/3.1.0/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/3.1.0/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/3.1.0/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#104184 Remove Alibaba.aDrive version 3.10.0
  manifests/a/Alibaba/aDrive/3.10.0/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/3.10.0/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/3.10.0/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/3.10.0/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
