Repository microsoft/winget-pkgs, pull requests merged in 2023-11, with the labels that each got.

#124386 New version: blacktop.ipswd 3.1.411
  manifests/b/blacktop/ipswd/3.1.411/blacktop.ipswd.installer.yaml
  manifests/b/blacktop/ipswd/3.1.411/blacktop.ipswd.locale.en-US.yaml
  manifests/b/blacktop/ipswd/3.1.411/blacktop.ipswd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124385 New version: blacktop.ipsw 3.1.411
  manifests/b/blacktop/ipsw/3.1.411/blacktop.ipsw.installer.yaml
  manifests/b/blacktop/ipsw/3.1.411/blacktop.ipsw.locale.en-US.yaml
  manifests/b/blacktop/ipsw/3.1.411/blacktop.ipsw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124351 New version: EdrawSoft.MindMaster version 10.9.3.466
  manifests/e/EdrawSoft/MindMaster/10.9.3.466/EdrawSoft.MindMaster.installer.yaml
  manifests/e/EdrawSoft/MindMaster/10.9.3.466/EdrawSoft.MindMaster.locale.en-US.yaml
  manifests/e/EdrawSoft/MindMaster/10.9.3.466/EdrawSoft.MindMaster.locale.zh-CN.yaml
  manifests/e/EdrawSoft/MindMaster/10.9.3.466/EdrawSoft.MindMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124346 New version: DuckDuckGo.DesktopBrowser version 0.56.1.0
  manifests/d/DuckDuckGo/DesktopBrowser/0.56.1.0/DuckDuckGo.DesktopBrowser.installer.yaml
  manifests/d/DuckDuckGo/DesktopBrowser/0.56.1.0/DuckDuckGo.DesktopBrowser.locale.en-US.yaml
  manifests/d/DuckDuckGo/DesktopBrowser/0.56.1.0/DuckDuckGo.DesktopBrowser.locale.zh-CN.yaml
  manifests/d/DuckDuckGo/DesktopBrowser/0.56.1.0/DuckDuckGo.DesktopBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124024 Update README.md
  README.md
Labels: Moderator-Approved, Project-File, Needs-Attention

#124372 New version: Microsoft.PowerToys version 0.75.1
  manifests/m/Microsoft/PowerToys/0.75.1/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.75.1/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.75.1/Microsoft.PowerToys.yaml
Labels: Validation-Completed, Retry-1

#124412 New version: Jackett.Jackett version 0.21.1116
  manifests/j/Jackett/Jackett/0.21.1116/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1116/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1116/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124411 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124262 New version: Appest.Dida version 5.0.0.0
  manifests/a/Appest/Dida/5.0.0.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/5.0.0.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/5.0.0.0/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/5.0.0.0/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124432 JanDeDobbeleer.OhMyPosh version 18.20.0
  manifests/j/JanDeDobbeleer/OhMyPosh/18.20.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.20.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.20.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124436 JanDeDobbeleer.OhMyPosh version 18.21.0
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124447 JanDeDobbeleer.OhMyPosh version 18.21.1
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.21.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124455 JanDeDobbeleer.OhMyPosh version 18.22.0
  manifests/j/JanDeDobbeleer/OhMyPosh/18.22.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.22.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.22.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124015 New version: zyedidia.micro version 2.0.13
  manifests/z/zyedidia/micro/2.0.13/zyedidia.micro.installer.yaml
  manifests/z/zyedidia/micro/2.0.13/zyedidia.micro.locale.en-US.yaml
  manifests/z/zyedidia/micro/2.0.13/zyedidia.micro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124177 Sigil-Ebook.PageEdit version 2.0.2
  manifests/s/Sigil-Ebook/PageEdit/2.0.2/Sigil-Ebook.PageEdit.installer.yaml
  manifests/s/Sigil-Ebook/PageEdit/2.0.2/Sigil-Ebook.PageEdit.locale.en-US.yaml
  manifests/s/Sigil-Ebook/PageEdit/2.0.2/Sigil-Ebook.PageEdit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Executable-Error, Moderator-Approved, Waived-Validation-Executable-Error

#124456 New version: ViGEm.HidHide version 1.4.181
  manifests/v/ViGEm/HidHide/1.4.181/ViGEm.HidHide.installer.yaml
  manifests/v/ViGEm/HidHide/1.4.181/ViGEm.HidHide.locale.en-US.yaml
  manifests/v/ViGEm/HidHide/1.4.181/ViGEm.HidHide.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124423 New version: darktable.darktable version 4.4.2
  manifests/d/darktable/darktable/4.4.2/darktable.darktable.installer.yaml
  manifests/d/darktable/darktable/4.4.2/darktable.darktable.locale.en-US.yaml
  manifests/d/darktable/darktable/4.4.2/darktable.darktable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124125 add Commands for sops
  manifests/s/SecretsOPerationS/SOPS/3.8.0/SecretsOPerationS.SOPS.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#123951 New version: Grammarly.Grammarly version 1.0.49.1113
  manifests/g/Grammarly/Grammarly/1.0.49.1113/Grammarly.Grammarly.installer.yaml
  manifests/g/Grammarly/Grammarly/1.0.49.1113/Grammarly.Grammarly.locale.en-US.yaml
  manifests/g/Grammarly/Grammarly/1.0.49.1113/Grammarly.Grammarly.locale.zh-CN.yaml
  manifests/g/Grammarly/Grammarly/1.0.49.1113/Grammarly.Grammarly.yaml
Labels: Validation-Completed, Retry-1

#123948 Update LibreWolf.LibreWolf to v119.0-7
  manifests/l/LibreWolf/LibreWolf/119.0-7/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/119.0-7/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/119.0-7/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#123928 eve 0.3.3 bump2
  manifests/c/CCPGames/EVEOnline/0.3.3/CCPGames.EVEOnline.installer.yaml
  manifests/c/CCPGames/EVEOnline/0.3.3/CCPGames.EVEOnline.locale.en-US.yaml
  manifests/c/CCPGames/EVEOnline/0.3.3/CCPGames.EVEOnline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123890 New version: Tencent.WeType version 0.9.3.151
  manifests/t/Tencent/WeType/0.9.3.151/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.3.151/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.3.151/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123783 HiBitSoftware.HiBitUninstaller version 3.1.70
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.70/HiBitSoftware.HiBitUninstaller.installer.yaml
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.70/HiBitSoftware.HiBitUninstaller.locale.en-US.yaml
  manifests/h/HiBitSoftware/HiBitUninstaller/3.1.70/HiBitSoftware.HiBitUninstaller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123781 New version: MillerPuckette.PureData version 0.54-1
  manifests/m/MillerPuckette/PureData/0.54-1/MillerPuckette.PureData.installer.yaml
  manifests/m/MillerPuckette/PureData/0.54-1/MillerPuckette.PureData.locale.en-US.yaml
  manifests/m/MillerPuckette/PureData/0.54-1/MillerPuckette.PureData.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123269 New version: RARLab.WinRAR version 6.24.0
  manifests/r/RARLab/WinRAR/6.24.0/RARLab.WinRAR.installer.yaml
  manifests/r/RARLab/WinRAR/6.24.0/RARLab.WinRAR.locale.de.yaml
  manifests/r/RARLab/WinRAR/6.24.0/RARLab.WinRAR.locale.en.yaml
  manifests/r/RARLab/WinRAR/6.24.0/RARLab.WinRAR.yaml
Labels: Validation-Completed, Retry-1

#115276 Add version: Anaconda.Miniconda3 version py310_23.5.2-0
  manifests/a/Anaconda/Miniconda3/py310_23.5.2-0/Anaconda.Miniconda3.installer.yaml
  manifests/a/Anaconda/Miniconda3/py310_23.5.2-0/Anaconda.Miniconda3.locale.en-US.yaml
  manifests/a/Anaconda/Miniconda3/py310_23.5.2-0/Anaconda.Miniconda3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#123131 Please add Gnu IceCat
  manifests/i/Icecat/Icecat/115.4.0esr/Icecat.Icecat.installer.yaml
  manifests/i/Icecat/Icecat/115.4.0esr/Icecat.Icecat.locale.en-US.yaml
  manifests/i/Icecat/Icecat/115.4.0esr/Icecat.Icecat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Unattended-Failed

#124130 New version: radj307.volume-control version 6.4.0
  manifests/r/radj307/volume-control/6.4.0/radj307.volume-control.installer.yaml
  manifests/r/radj307/volume-control/6.4.0/radj307.volume-control.locale.en-US.yaml
  manifests/r/radj307/volume-control/6.4.0/radj307.volume-control.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#124126 New version: yt-dlp.yt-dlp.nightly version 2023.10.28.155411
  manifests/y/yt-dlp/yt-dlp/nightly/2023.10.28.155411/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2023.10.28.155411/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2023.10.28.155411/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124025 New version: jumppad.jumppad version 0.5.53
  manifests/j/jumppad/jumppad/0.5.53/jumppad.jumppad.installer.yaml
  manifests/j/jumppad/jumppad/0.5.53/jumppad.jumppad.locale.en-US.yaml
  manifests/j/jumppad/jumppad/0.5.53/jumppad.jumppad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#124020 Add version: sebescudie.GammaLauncher version 5.2.0
  manifests/s/sebescudie/GammaLauncher/5.2.0/sebescudie.GammaLauncher.installer.yaml
  manifests/s/sebescudie/GammaLauncher/5.2.0/sebescudie.GammaLauncher.locale.en-US.yaml
  manifests/s/sebescudie/GammaLauncher/5.2.0/sebescudie.GammaLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124019 Fix (PackageVersion): StefansTools.grepWin version 2.0.12
  manifests/s/StefansTools/grepWin/2.0.12/StefansTools.grepWin.installer.yaml
  manifests/s/StefansTools/grepWin/2.0.12/StefansTools.grepWin.locale.en-US.yaml
  manifests/s/StefansTools/grepWin/2.0.12/StefansTools.grepWin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124013 New version: Upscayl.Upscayl version 2.9.1
  manifests/u/Upscayl/Upscayl/2.9.1/Upscayl.Upscayl.installer.yaml
  manifests/u/Upscayl/Upscayl/2.9.1/Upscayl.Upscayl.locale.en-US.yaml
  manifests/u/Upscayl/Upscayl/2.9.1/Upscayl.Upscayl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123998 New version: Ablaze.Floorp version 11.5.1
  manifests/a/Ablaze/Floorp/11.5.1/Ablaze.Floorp.installer.yaml
  manifests/a/Ablaze/Floorp/11.5.1/Ablaze.Floorp.locale.en-US.yaml
  manifests/a/Ablaze/Floorp/11.5.1/Ablaze.Floorp.locale.ja-JP.yaml
  manifests/a/Ablaze/Floorp/11.5.1/Ablaze.Floorp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123997 ElectronicArts.EADesktop version 13.52.0.5565
  manifests/e/ElectronicArts/EADesktop/13.52.0.5565/ElectronicArts.EADesktop.installer.yaml
  manifests/e/ElectronicArts/EADesktop/13.52.0.5565/ElectronicArts.EADesktop.locale.en-US.yaml
  manifests/e/ElectronicArts/EADesktop/13.52.0.5565/ElectronicArts.EADesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123990 Update version: JetBrains.IntelliJIDEA.Ultimate version 2023.2.4
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/2023.2.4/JetBrains.IntelliJIDEA.Ultimate.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/2023.2.4/JetBrains.IntelliJIDEA.Ultimate.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/2023.2.4/JetBrains.IntelliJIDEA.Ultimate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123987 remove: Microsoft.Azd version 1.4.400
  manifests/m/Microsoft/Azd/1.4.400/Microsoft.Azd.installer.yaml
  manifests/m/Microsoft/Azd/1.4.400/Microsoft.Azd.locale.en-US.yaml
  manifests/m/Microsoft/Azd/1.4.400/Microsoft.Azd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123986 Update Moniker: dbrgn.tealdeer 1.6.1
  manifests/d/dbrgn/tealdeer/1.6.1/dbrgn.tealdeer.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#123980 New version: MusicBee.MusicBee version 3.5.8698
  manifests/m/MusicBee/MusicBee/3.5.8698/MusicBee.MusicBee.installer.yaml
  manifests/m/MusicBee/MusicBee/3.5.8698/MusicBee.MusicBee.locale.en-US.yaml
  manifests/m/MusicBee/MusicBee/3.5.8698/MusicBee.MusicBee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123982 New version: LibreWolf.LibreWolf version 119.0-5
  manifests/l/LibreWolf/LibreWolf/119.0-5/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/119.0-5/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/119.0-5/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#123975 New package: EagleDynamics.DCSWorldOpenBeta version 2.9
  manifests/e/EagleDynamics/DCSWorldOpenBeta/2.9/EagleDynamics.DCSWorldOpenBeta.installer.yaml
  manifests/e/EagleDynamics/DCSWorldOpenBeta/2.9/EagleDynamics.DCSWorldOpenBeta.locale.en-US.yaml
  manifests/e/EagleDynamics/DCSWorldOpenBeta/2.9/EagleDynamics.DCSWorldOpenBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#123974 New version: LLVM.LLVM version 17.0.3
  manifests/l/LLVM/LLVM/17.0.3/LLVM.LLVM.installer.yaml
  manifests/l/LLVM/LLVM/17.0.3/LLVM.LLVM.locale.de-DE.yaml
  manifests/l/LLVM/LLVM/17.0.3/LLVM.LLVM.locale.en-US.yaml
  manifests/l/LLVM/LLVM/17.0.3/LLVM.LLVM.locale.zh-CN.yaml
  manifests/l/LLVM/LLVM/17.0.3/LLVM.LLVM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123973 New version: Xiaoyaoyixia.KOOK version 0.76.1
  manifests/x/Xiaoyaoyixia/KOOK/0.76.1/Xiaoyaoyixia.KOOK.installer.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.76.1/Xiaoyaoyixia.KOOK.locale.en-US.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.76.1/Xiaoyaoyixia.KOOK.locale.zh-CN.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.76.1/Xiaoyaoyixia.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123972 New version: OneKey.OneKey version 4.14.0
  manifests/o/OneKey/OneKey/4.14.0/OneKey.OneKey.installer.yaml
  manifests/o/OneKey/OneKey/4.14.0/OneKey.OneKey.locale.en-US.yaml
  manifests/o/OneKey/OneKey/4.14.0/OneKey.OneKey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123970 New version: electerm.electerm version 1.34.38
  manifests/e/electerm/electerm/1.34.38/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.34.38/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.34.38/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123968 New package: CCPGames.EVEOnline version 0.4.0
  manifests/c/CCPGames/EVEOnline/0.4.0/CCPGames.EVEOnline.installer.yaml
  manifests/c/CCPGames/EVEOnline/0.4.0/CCPGames.EVEOnline.locale.en-US.yaml
  manifests/c/CCPGames/EVEOnline/0.4.0/CCPGames.EVEOnline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123961 New version: Wasmer.Wasmer version 4.2.3
  manifests/w/Wasmer/Wasmer/4.2.3/Wasmer.Wasmer.installer.yaml
  manifests/w/Wasmer/Wasmer/4.2.3/Wasmer.Wasmer.locale.en-US.yaml
  manifests/w/Wasmer/Wasmer/4.2.3/Wasmer.Wasmer.locale.zh-CN.yaml
  manifests/w/Wasmer/Wasmer/4.2.3/Wasmer.Wasmer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#123959 New version: Redisant.KafkaAssistant version 1.2.7.3
  manifests/r/Redisant/KafkaAssistant/1.2.7.3/Redisant.KafkaAssistant.installer.yaml
  manifests/r/Redisant/KafkaAssistant/1.2.7.3/Redisant.KafkaAssistant.locale.en-US.yaml
  manifests/r/Redisant/KafkaAssistant/1.2.7.3/Redisant.KafkaAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/KafkaAssistant/1.2.7.3/Redisant.KafkaAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124334 New version: Zidoro.Pomatez version 1.3.1
  manifests/z/Zidoro/Pomatez/1.3.1/Zidoro.Pomatez.installer.yaml
  manifests/z/Zidoro/Pomatez/1.3.1/Zidoro.Pomatez.locale.en-US.yaml
  manifests/z/Zidoro/Pomatez/1.3.1/Zidoro.Pomatez.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123413 New package: K1DBO.slice-master-6000 version 0.11.0g
  manifests/k/K1DBO/slice-master-6000/0.11.0g/K1DBO.slice-master-6000.installer.yaml
  manifests/k/K1DBO/slice-master-6000/0.11.0g/K1DBO.slice-master-6000.locale.en-US.yaml
  manifests/k/K1DBO/slice-master-6000/0.11.0g/K1DBO.slice-master-6000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123957 New version: 5E.5EClient version 7.1.27
  manifests/5/5E/5EClient/7.1.27/5E.5EClient.installer.yaml
  manifests/5/5E/5EClient/7.1.27/5E.5EClient.locale.en-US.yaml
  manifests/5/5E/5EClient/7.1.27/5E.5EClient.locale.zh-CN.yaml
  manifests/5/5E/5EClient/7.1.27/5E.5EClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124169 New package: WatchGuard.MobileVPNwithSSLclient version 12.10
  manifests/w/WatchGuard/MobileVPNWithSSLClient/12.10/WatchGuard.MobileVPNWithSSLClient.installer.yaml
  manifests/w/WatchGuard/MobileVPNWithSSLClient/12.10/WatchGuard.MobileVPNWithSSLClient.locale.en-US.yaml
  manifests/w/WatchGuard/MobileVPNWithSSLClient/12.10/WatchGuard.MobileVPNWithSSLClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124131 New version: chrisant996.Clink version 1.5.12
  manifests/c/chrisant996/Clink/1.5.12/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.5.12/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.5.12/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#124136 New version: cURL.cURL version 8.4.0.6
  manifests/c/cURL/cURL/8.4.0.6/cURL.cURL.installer.yaml
  manifests/c/cURL/cURL/8.4.0.6/cURL.cURL.locale.en-US.yaml
  manifests/c/cURL/cURL/8.4.0.6/cURL.cURL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124143 New version: ProtonTechnologies.ProtonVPN version 3.2.4
  manifests/p/ProtonTechnologies/ProtonVPN/3.2.4/ProtonTechnologies.ProtonVPN.installer.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/3.2.4/ProtonTechnologies.ProtonVPN.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonVPN/3.2.4/ProtonTechnologies.ProtonVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124153 New version: tumic0.GPXSee version 13.9
  manifests/t/tumic0/GPXSee/13.9/tumic0.GPXSee.installer.yaml
  manifests/t/tumic0/GPXSee/13.9/tumic0.GPXSee.locale.en-US.yaml
  manifests/t/tumic0/GPXSee/13.9/tumic0.GPXSee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124155 New version: igoogolx.lux version 0.9.3
  manifests/i/igoogolx/lux/0.9.3/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/0.9.3/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/0.9.3/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124160 New version: LinwoodCloud.Butterfly.Nightly version 2.0.0-beta.13
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-beta.13/LinwoodCloud.Butterfly.Nightly.installer.yaml
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-beta.13/LinwoodCloud.Butterfly.Nightly.locale.en-US.yaml
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-beta.13/LinwoodCloud.Butterfly.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Executable-Error, Moderator-Approved, Waived-Validation-Executable-Error

#124162 New version: Spicetify.Spicetify version 2.25.2
  manifests/s/Spicetify/Spicetify/2.25.2/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.25.2/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.25.2/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124161 CorvusSKK 3.2.2
  manifests/n/nathancorvussolis/corvusskk/3.2.2/nathancorvussolis.corvusskk.installer.yaml
  manifests/n/nathancorvussolis/corvusskk/3.2.2/nathancorvussolis.corvusskk.locale.en-US.yaml
  manifests/n/nathancorvussolis/corvusskk/3.2.2/nathancorvussolis.corvusskk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124166 TechPowerUp.GPU-Z version 2.55.0
  manifests/t/TechPowerUp/GPU-Z/2.55.0/TechPowerUp.GPU-Z.installer.yaml
  manifests/t/TechPowerUp/GPU-Z/2.55.0/TechPowerUp.GPU-Z.locale.en-US.yaml
  manifests/t/TechPowerUp/GPU-Z/2.55.0/TechPowerUp.GPU-Z.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124142 New package: BellSoft.LibericaJRE.18 version 18.0.2.1+1
  manifests/b/BellSoft/LibericaJRE/18/18.0.2.1+1/BellSoft.LibericaJRE.18.installer.yaml
  manifests/b/BellSoft/LibericaJRE/18/18.0.2.1+1/BellSoft.LibericaJRE.18.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/18/18.0.2.1+1/BellSoft.LibericaJRE.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124139 New package: BellSoft.LibericaJRE.20 version 20.0.2.10
  manifests/b/BellSoft/LibericaJRE/20/20.0.2.10/BellSoft.LibericaJRE.20.installer.yaml
  manifests/b/BellSoft/LibericaJRE/20/20.0.2.10/BellSoft.LibericaJRE.20.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/20/20.0.2.10/BellSoft.LibericaJRE.20.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124517 New version: Jackett.Jackett version 0.21.1119
  manifests/j/Jackett/Jackett/0.21.1119/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1119/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1119/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124514 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124284 Fix: Add AppsAndFeaturesEntries for Microsoft.WindowsSDK.10.0.22621
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.1.22621.2428/Microsoft.WindowsSDK.10.0.22621.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Shell-Execute, Needs-Manual-Merge

#124141 New package: BellSoft.LibericaJRE.19 version 19.0.2.9
  manifests/b/BellSoft/LibericaJRE/19/19.0.2.9/BellSoft.LibericaJRE.19.installer.yaml
  manifests/b/BellSoft/LibericaJRE/19/19.0.2.9/BellSoft.LibericaJRE.19.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/19/19.0.2.9/BellSoft.LibericaJRE.19.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Domain

#124146 New package: BellSoft.LibericaJRE.15 version 15.0.2+10
  manifests/b/BellSoft/LibericaJRE/15/15.0.2+10/BellSoft.LibericaJRE.15.installer.yaml
  manifests/b/BellSoft/LibericaJRE/15/15.0.2+10/BellSoft.LibericaJRE.15.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/15/15.0.2+10/BellSoft.LibericaJRE.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124147 New package: BellSoft.LibericaJRE.14 version 14.0.2+13
  manifests/b/BellSoft/LibericaJRE/14/14.0.2+13/BellSoft.LibericaJRE.14.installer.yaml
  manifests/b/BellSoft/LibericaJRE/14/14.0.2+13/BellSoft.LibericaJRE.14.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/14/14.0.2+13/BellSoft.LibericaJRE.14.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124145 New package: BellSoft.LibericaJRE.16 version 16.0.2+7
  manifests/b/BellSoft/LibericaJRE/16/16.0.2+7/BellSoft.LibericaJRE.16.installer.yaml
  manifests/b/BellSoft/LibericaJRE/16/16.0.2+7/BellSoft.LibericaJRE.16.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/16/16.0.2+7/BellSoft.LibericaJRE.16.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124148 New package: BellSoft.LibericaJRE.13 version 13.0.2+9
  manifests/b/BellSoft/LibericaJRE/13/13.0.2+9/BellSoft.LibericaJRE.13.installer.yaml
  manifests/b/BellSoft/LibericaJRE/13/13.0.2+9/BellSoft.LibericaJRE.13.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/13/13.0.2+9/BellSoft.LibericaJRE.13.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124144 New package: BellSoft.LibericaJRE.17 version 17.0.9+11
  manifests/b/BellSoft/LibericaJRE/17/17.0.9+11/BellSoft.LibericaJRE.17.installer.yaml
  manifests/b/BellSoft/LibericaJRE/17/17.0.9+11/BellSoft.LibericaJRE.17.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/17/17.0.9+11/BellSoft.LibericaJRE.17.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124149 New package: BellSoft.LibericaJRE.11 version 11.0.21+10
  manifests/b/BellSoft/LibericaJRE/11/11.0.21+10/BellSoft.LibericaJRE.11.installer.yaml
  manifests/b/BellSoft/LibericaJRE/11/11.0.21+10/BellSoft.LibericaJRE.11.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/11/11.0.21+10/BellSoft.LibericaJRE.11.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124150 New package: BellSoft.LibericaJRE.8 version 8u392+9
  manifests/b/BellSoft/LibericaJRE/8/8u392+9/BellSoft.LibericaJRE.8.installer.yaml
  manifests/b/BellSoft/LibericaJRE/8/8u392+9/BellSoft.LibericaJRE.8.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/8/8u392+9/BellSoft.LibericaJRE.8.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124138 New package: BellSoft.LibericaJRE.21 version 21.0.1.12
  manifests/b/BellSoft/LibericaJRE/21/21.0.1.12/BellSoft.LibericaJRE.21.installer.yaml
  manifests/b/BellSoft/LibericaJRE/21/21.0.1.12/BellSoft.LibericaJRE.21.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/21/21.0.1.12/BellSoft.LibericaJRE.21.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124170 New package: BellSoft.LibericaJRE.20.Full version 20.0.2+10
  manifests/b/BellSoft/LibericaJRE/20/Full/20.0.2+10/BellSoft.LibericaJRE.20.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/20/Full/20.0.2+10/BellSoft.LibericaJRE.20.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/20/Full/20.0.2+10/BellSoft.LibericaJRE.20.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124175 New package: BellSoft.LibericaJRE.15.Full version 15.0.2+10
  manifests/b/BellSoft/LibericaJRE/15/Full/15.0.2+10/BellSoft.LibericaJRE.15.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/15/Full/15.0.2+10/BellSoft.LibericaJRE.15.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/15/Full/15.0.2+10/BellSoft.LibericaJRE.15.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124171 New package: BellSoft.LibericaJRE.19.Full version 19.0.2+9
  manifests/b/BellSoft/LibericaJRE/19/Full/19.0.2+9/BellSoft.LibericaJRE.19.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/19/Full/19.0.2+9/BellSoft.LibericaJRE.19.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/19/Full/19.0.2+9/BellSoft.LibericaJRE.19.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124174 New package: BellSoft.LibericaJRE.16.Full version 16.0.2+7
  manifests/b/BellSoft/LibericaJRE/16/Full/16.0.2+7/BellSoft.LibericaJRE.16.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/16/Full/16.0.2+7/BellSoft.LibericaJRE.16.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/16/Full/16.0.2+7/BellSoft.LibericaJRE.16.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124181 New version: tldr-pages.tlrc 1.7.1
  manifests/t/tldr-pages/tlrc/1.7.1/tldr-pages.tlrc.installer.yaml
  manifests/t/tldr-pages/tlrc/1.7.1/tldr-pages.tlrc.locale.en-US.yaml
  manifests/t/tldr-pages/tlrc/1.7.1/tldr-pages.tlrc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error

#124172 New package: BellSoft.LibericaJRE.18.Full version 18.0.2.1+1
  manifests/b/BellSoft/LibericaJRE/18/Full/18.0.2.1+1/BellSoft.LibericaJRE.18.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/18/Full/18.0.2.1+1/BellSoft.LibericaJRE.18.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/18/Full/18.0.2.1+1/BellSoft.LibericaJRE.18.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124173 New package: BellSoft.LibericaJRE.17.Full version 17.0.9+11
  manifests/b/BellSoft/LibericaJRE/17/Full/17.0.9+11/BellSoft.LibericaJRE.17.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/17/Full/17.0.9+11/BellSoft.LibericaJRE.17.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/17/Full/17.0.9+11/BellSoft.LibericaJRE.17.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Domain

#124176 New package: BellSoft.LibericaJRE.14.Full version 14.0.2+13
  manifests/b/BellSoft/LibericaJRE/14/Full/14.0.2+13/BellSoft.LibericaJRE.14.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/14/Full/14.0.2+13/BellSoft.LibericaJRE.14.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/14/Full/14.0.2+13/BellSoft.LibericaJRE.14.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124185 New version: c3er.mdview version 3.0.1
  manifests/c/c3er/mdview/3.0.1/c3er.mdview.installer.yaml
  manifests/c/c3er/mdview/3.0.1/c3er.mdview.locale.en-US.yaml
  manifests/c/c3er/mdview/3.0.1/c3er.mdview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124186 New version: twpayne.chezmoi 2.40.4
  manifests/t/twpayne/chezmoi/2.40.4/twpayne.chezmoi.installer.yaml
  manifests/t/twpayne/chezmoi/2.40.4/twpayne.chezmoi.locale.en-US.yaml
  manifests/t/twpayne/chezmoi/2.40.4/twpayne.chezmoi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124187 CloudNet 1.36.2.7
  manifests/c/cloudnet/cloudnet/1.36.2.7/cloudnet.cloudnet.installer.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.7/cloudnet.cloudnet.locale.zh-CN.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.7/cloudnet.cloudnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124188 BytecodeAlliance.Wasmtime.Portable version 14.0.2
  manifests/b/BytecodeAlliance/Wasmtime/Portable/14.0.2/BytecodeAlliance.Wasmtime.Portable.installer.yaml
  manifests/b/BytecodeAlliance/Wasmtime/Portable/14.0.2/BytecodeAlliance.Wasmtime.Portable.locale.en-US.yaml
  manifests/b/BytecodeAlliance/Wasmtime/Portable/14.0.2/BytecodeAlliance.Wasmtime.Portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124180 New package: BellSoft.LibericaJRE.8.Full version 8u392+9
  manifests/b/BellSoft/LibericaJRE/8/Full/8u392+9/BellSoft.LibericaJRE.8.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/8/Full/8u392+9/BellSoft.LibericaJRE.8.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/8/Full/8u392+9/BellSoft.LibericaJRE.8.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124179 New package: BellSoft.LibericaJRE.11.Full version 11.0.21+10
  manifests/b/BellSoft/LibericaJRE/11/Full/11.0.21+10/BellSoft.LibericaJRE.11.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/11/Full/11.0.21+10/BellSoft.LibericaJRE.11.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/11/Full/11.0.21+10/BellSoft.LibericaJRE.11.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124183 TopalaSoftwareSolutions.SIW version 2023.10.29.0
  manifests/t/TopalaSoftwareSolutions/SIW/2023.10.29.0/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.10.29.0/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.10.29.0/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124189 Add version: rink-turksma.IntunePrepTool version '1.2.5.3'
  manifests/r/rink-turksma/IntunePrepTool/'1.2.5.3'/rink-turksma.IntunePrepTool.installer.yaml
  manifests/r/rink-turksma/IntunePrepTool/'1.2.5.3'/rink-turksma.IntunePrepTool.locale.en-US.yaml
  manifests/r/rink-turksma/IntunePrepTool/'1.2.5.3'/rink-turksma.IntunePrepTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124190 Updated Version to 7.18.4.0 for Garmin Express
  manifests/g/Garmin/Express/7.18.4.0/Garmin.Express.installer.yaml
  manifests/g/Garmin/Express/7.18.4.0/Garmin.Express.locale.en-US.yaml
  manifests/g/Garmin/Express/7.18.4.0/Garmin.Express.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124168 New package: BellSoft.LibericaJRE.21.Full version 21.0.1+12
  manifests/b/BellSoft/LibericaJRE/21/Full/21.0.1+12/BellSoft.LibericaJRE.21.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/21/Full/21.0.1+12/BellSoft.LibericaJRE.21.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/21/Full/21.0.1+12/BellSoft.LibericaJRE.21.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124192 MoritzBunkus.MKVToolNix version 80.0.0
  manifests/m/MoritzBunkus/MKVToolNix/80.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/80.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/80.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/80.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124178 New package: BellSoft.LibericaJRE.13.Full version 13.0.2+9
  manifests/b/BellSoft/LibericaJRE/13/Full/13.0.2+9/BellSoft.LibericaJRE.13.Full.installer.yaml
  manifests/b/BellSoft/LibericaJRE/13/Full/13.0.2+9/BellSoft.LibericaJRE.13.Full.locale.en-US.yaml
  manifests/b/BellSoft/LibericaJRE/13/Full/13.0.2+9/BellSoft.LibericaJRE.13.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#124194 New version: restic.restic version 0.16.2
  manifests/r/restic/restic/0.16.2/restic.restic.installer.yaml
  manifests/r/restic/restic/0.16.2/restic.restic.locale.en-US.yaml
  manifests/r/restic/restic/0.16.2/restic.restic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124201 EpicGames.EpicGamesLauncher version 1.3.82.0
  manifests/e/EpicGames/EpicGamesLauncher/1.3.82.0/EpicGames.EpicGamesLauncher.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124195 New version: NVAccess.NVDA version 2023.3
  manifests/n/NVAccess/NVDA/2023.3/NVAccess.NVDA.installer.yaml
  manifests/n/NVAccess/NVDA/2023.3/NVAccess.NVDA.locale.en-US.yaml
  manifests/n/NVAccess/NVDA/2023.3/NVAccess.NVDA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124207 SagerNet.sing-box version 1.5.5
  manifests/s/SagerNet/sing-box/1.5.5/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.5.5/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.5.5/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124255 New version: WestWind.MarkdownMonster version 3.0.9.0
  manifests/w/WestWind/MarkdownMonster/3.0.9.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/3.0.9.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/3.0.9.0/WestWind.MarkdownMonster.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#124256 New version: WestWind.MarkdownMonster version 3.0.10.0
  manifests/w/WestWind/MarkdownMonster/3.0.10.0/WestWind.MarkdownMonster.installer.yaml
  manifests/w/WestWind/MarkdownMonster/3.0.10.0/WestWind.MarkdownMonster.locale.en-US.yaml
  manifests/w/WestWind/MarkdownMonster/3.0.10.0/WestWind.MarkdownMonster.yaml
Labels: Validation-Completed, Retry-1

#124310 New version: Coder.Coder version 2.3.3
  manifests/c/Coder/Coder/2.3.3/Coder.Coder.installer.yaml
  manifests/c/Coder/Coder/2.3.3/Coder.Coder.locale.en-US.yaml
  manifests/c/Coder/Coder/2.3.3/Coder.Coder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#124304 New version: c0re100.qBittorrent-Enhanced-Edition version 4.6.0.10
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.0.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.0.10/c0re100.qBittorrent-Enhanced-Edition.locale.en-US.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.0.10/c0re100.qBittorrent-Enhanced-Edition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124302 New version: MasterPackager.MasterPackagerDev version 1.0.6
  manifests/m/MasterPackager/MasterPackagerDev/1.0.6/MasterPackager.MasterPackagerDev.installer.yaml
  manifests/m/MasterPackager/MasterPackagerDev/1.0.6/MasterPackager.MasterPackagerDev.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackagerDev/1.0.6/MasterPackager.MasterPackagerDev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124299 New version: Mullvad.Browser version 13.0.1
  manifests/m/Mullvad/Browser/13.0.1/Mullvad.Browser.installer.yaml
  manifests/m/Mullvad/Browser/13.0.1/Mullvad.Browser.locale.en-US.yaml
  manifests/m/Mullvad/Browser/13.0.1/Mullvad.Browser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124298 New version: jumppad.jumppad version 0.5.56
  manifests/j/jumppad/jumppad/0.5.56/jumppad.jumppad.installer.yaml
  manifests/j/jumppad/jumppad/0.5.56/jumppad.jumppad.locale.en-US.yaml
  manifests/j/jumppad/jumppad/0.5.56/jumppad.jumppad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#124296 New version: CodecGuide.K-LiteCodecPack.Full version 17.9.0
  manifests/c/CodecGuide/K-LiteCodecPack/Full/17.9.0/CodecGuide.K-LiteCodecPack.Full.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/17.9.0/CodecGuide.K-LiteCodecPack.Full.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/17.9.0/CodecGuide.K-LiteCodecPack.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124295 New version: CodecGuide.K-LiteCodecPack.Mega version 17.9.0
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/17.9.0/CodecGuide.K-LiteCodecPack.Mega.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/17.9.0/CodecGuide.K-LiteCodecPack.Mega.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/17.9.0/CodecGuide.K-LiteCodecPack.Mega.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124292 New version: CodecGuide.K-LiteCodecPack.Basic version 17.9.0
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/17.9.0/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/17.9.0/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/17.9.0/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124291 New version: Streamlink.Streamlink version 6.3.1-1
  manifests/s/Streamlink/Streamlink/6.3.1-1/Streamlink.Streamlink.installer.yaml
  manifests/s/Streamlink/Streamlink/6.3.1-1/Streamlink.Streamlink.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/6.3.1-1/Streamlink.Streamlink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124293 New version: CodecGuide.K-LiteCodecPack.Standard version 17.9.0
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/17.9.0/CodecGuide.K-LiteCodecPack.Standard.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/17.9.0/CodecGuide.K-LiteCodecPack.Standard.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/17.9.0/CodecGuide.K-LiteCodecPack.Standard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124290 New version: Streamlink.Streamlink version 6.3.0-1
  manifests/s/Streamlink/Streamlink/6.3.0-1/Streamlink.Streamlink.installer.yaml
  manifests/s/Streamlink/Streamlink/6.3.0-1/Streamlink.Streamlink.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/6.3.0-1/Streamlink.Streamlink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124287 New version: Ablaze.Floorp.Daylight version 20231029210622
  manifests/a/Ablaze/Floorp/Daylight/20231029210622/Ablaze.Floorp.Daylight.installer.yaml
  manifests/a/Ablaze/Floorp/Daylight/20231029210622/Ablaze.Floorp.Daylight.locale.en-US.yaml
  manifests/a/Ablaze/Floorp/Daylight/20231029210622/Ablaze.Floorp.Daylight.locale.ja-JP.yaml
  manifests/a/Ablaze/Floorp/Daylight/20231029210622/Ablaze.Floorp.Daylight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124289 New version: valinet.ExplorerPatcher version 22621.2428.59.1
  manifests/v/valinet/ExplorerPatcher/22621.2428.59.1/valinet.ExplorerPatcher.installer.yaml
  manifests/v/valinet/ExplorerPatcher/22621.2428.59.1/valinet.ExplorerPatcher.locale.en-US.yaml
  manifests/v/valinet/ExplorerPatcher/22621.2428.59.1/valinet.ExplorerPatcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124285 HERE.OLPCLI version 16.2.61
  manifests/h/HERE/OLPCLI/16.2.61/HERE.OLPCLI.installer.yaml
  manifests/h/HERE/OLPCLI/16.2.61/HERE.OLPCLI.locale.en-US.yaml
  manifests/h/HERE/OLPCLI/16.2.61/HERE.OLPCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124254 Submitting Studio-CLI version 23.9.0
  manifests/w/WindRiver/studio-cli/23.9.0/WindRiver.studio-cli.installer.yaml
  manifests/w/WindRiver/studio-cli/23.9.0/WindRiver.studio-cli.locale.en-US.yaml
  manifests/w/WindRiver/studio-cli/23.9.0/WindRiver.studio-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124280 New version: AILight.AILZ80ASM version 1.0.10
  manifests/a/AILight/AILZ80ASM/1.0.10/AILight.AILZ80ASM.installer.yaml
  manifests/a/AILight/AILZ80ASM/1.0.10/AILight.AILZ80ASM.locale.ja-JP.yaml
  manifests/a/AILight/AILZ80ASM/1.0.10/AILight.AILZ80ASM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#124266 Update Gitkraken.cli 1.1.2
  manifests/g/GitKraken/cli/1.1.2/GitKraken.cli.installer.yaml
  manifests/g/GitKraken/cli/1.1.2/GitKraken.cli.locale.en-US.yaml
  manifests/g/GitKraken/cli/1.1.2/GitKraken.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124263 New version: Tencent.WeType version 0.9.2.82
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124260 Telegram.TelegramDesktop version 4.11.1
  manifests/t/Telegram/TelegramDesktop/4.11.1/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/4.11.1/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/4.11.1/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124259 New version: Pylogmon.pot version 2.6.7
  manifests/p/Pylogmon/pot/2.6.7/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/2.6.7/Pylogmon.pot.locale.en-US.yaml
  manifests/p/Pylogmon/pot/2.6.7/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124258 New version: NetSarangComputer.PortX Version 2.2.5
  manifests/n/NetSarangComputer/PortX/2.2.5/NetSarangComputer.PortX.installer.yaml
  manifests/n/NetSarangComputer/PortX/2.2.5/NetSarangComputer.PortX.locale.en-US.yaml
  manifests/n/NetSarangComputer/PortX/2.2.5/NetSarangComputer.PortX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#124349 New version: GyDi.ClashVerge version 1.3.8
  manifests/g/GyDi/ClashVerge/1.3.8/GyDi.ClashVerge.installer.yaml
  manifests/g/GyDi/ClashVerge/1.3.8/GyDi.ClashVerge.locale.en-US.yaml
  manifests/g/GyDi/ClashVerge/1.3.8/GyDi.ClashVerge.locale.zh-CN.yaml
  manifests/g/GyDi/ClashVerge/1.3.8/GyDi.ClashVerge.yaml
Labels: Validation-Completed, Retry-1

#124347 New version: Coldlake.StellarPlayer version 2.23.2030.22
  manifests/c/Coldlake/StellarPlayer/2.23.2030.22/Coldlake.StellarPlayer.installer.yaml
  manifests/c/Coldlake/StellarPlayer/2.23.2030.22/Coldlake.StellarPlayer.locale.en-US.yaml
  manifests/c/Coldlake/StellarPlayer/2.23.2030.22/Coldlake.StellarPlayer.locale.zh-CN.yaml
  manifests/c/Coldlake/StellarPlayer/2.23.2030.22/Coldlake.StellarPlayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124348 New version: B3log.SiYuan version 2.10.13
  manifests/b/B3log/SiYuan/2.10.13/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.10.13/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.10.13/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.10.13/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124345 New version: Tencent.TranSmart version Alpha0.10.11
  manifests/t/Tencent/TranSmart/Alpha0.10.11/Tencent.TranSmart.installer.yaml
  manifests/t/Tencent/TranSmart/Alpha0.10.11/Tencent.TranSmart.locale.en-US.yaml
  manifests/t/Tencent/TranSmart/Alpha0.10.11/Tencent.TranSmart.locale.zh-CN.yaml
  manifests/t/Tencent/TranSmart/Alpha0.10.11/Tencent.TranSmart.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124460 New version: eTeks.SweetHome3D version 7.2
  manifests/e/eTeks/SweetHome3D/7.2/eTeks.SweetHome3D.installer.yaml
  manifests/e/eTeks/SweetHome3D/7.2/eTeks.SweetHome3D.locale.en-US.yaml
  manifests/e/eTeks/SweetHome3D/7.2/eTeks.SweetHome3D.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124344 New version: Bilibili.Livehime version 4.54.0.5325
  manifests/b/Bilibili/Livehime/4.54.0.5325/Bilibili.Livehime.installer.yaml
  manifests/b/Bilibili/Livehime/4.54.0.5325/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.54.0.5325/Bilibili.Livehime.locale.zh-CN.yaml
  manifests/b/Bilibili/Livehime/4.54.0.5325/Bilibili.Livehime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124343 New version: Hesan.He3 version 2.0.0
  manifests/h/Hesan/He3/2.0.0/Hesan.He3.installer.yaml
  manifests/h/Hesan/He3/2.0.0/Hesan.He3.locale.en-US.yaml
  manifests/h/Hesan/He3/2.0.0/Hesan.He3.locale.zh-CN.yaml
  manifests/h/Hesan/He3/2.0.0/Hesan.He3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124464 New package: hmatuschek.kochmorse version 3.5.0
  manifests/h/hmatuschek/kochmorse/3.5.0/hmatuschek.kochmorse.installer.yaml
  manifests/h/hmatuschek/kochmorse/3.5.0/hmatuschek.kochmorse.locale.en-US.yaml
  manifests/h/hmatuschek/kochmorse/3.5.0/hmatuschek.kochmorse.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124265 Submitting CAT CLI version 0.22.0.12.
  manifests/d/DataTools/CATCLI/0.22.0.12/DataTools.CATCLI.installer.yaml
  manifests/d/DataTools/CATCLI/0.22.0.12/DataTools.CATCLI.locale.en-US.yaml
  manifests/d/DataTools/CATCLI/0.22.0.12/DataTools.CATCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124342 New version: 115.115 version 2.0.6.6
  manifests/1/115/115/2.0.6.6/115.115.installer.yaml
  manifests/1/115/115/2.0.6.6/115.115.locale.en-US.yaml
  manifests/1/115/115/2.0.6.6/115.115.locale.zh-CN.yaml
  manifests/1/115/115/2.0.6.6/115.115.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124316 New version: rdimitrov.tuf-client 0.0.6
  manifests/r/rdimitrov/tuf-client/0.0.6/rdimitrov.tuf-client.installer.yaml
  manifests/r/rdimitrov/tuf-client/0.0.6/rdimitrov.tuf-client.locale.en-US.yaml
  manifests/r/rdimitrov/tuf-client/0.0.6/rdimitrov.tuf-client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124341 New version: Brave.Brave.Nightly version 119.1.62.12
  manifests/b/Brave/Brave/Nightly/119.1.62.12/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/119.1.62.12/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/119.1.62.12/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/119.1.62.12/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124340 New version: Hugo.Hugo version 0.120.1
  manifests/h/Hugo/Hugo/0.120.1/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.120.1/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.120.1/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.120.1/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124338 New version: Hugo.Hugo.Extended version 0.120.0
  manifests/h/Hugo/Hugo/Extended/0.120.0/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.0/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.0/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.0/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124339 New version: Hugo.Hugo.Extended version 0.120.1
  manifests/h/Hugo/Hugo/Extended/0.120.1/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.1/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.1/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.120.1/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124330 New version: IPEP.Scantailor-Experimental version 0.2023.10.24
  manifests/i/IPEP/Scantailor-Experimental/0.2023.10.30/IPEP.Scantailor-Experimental.installer.yaml
  manifests/i/IPEP/Scantailor-Experimental/0.2023.10.30/IPEP.Scantailor-Experimental.locale.en-US.yaml
  manifests/i/IPEP/Scantailor-Experimental/0.2023.10.30/IPEP.Scantailor-Experimental.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124337 New version: Hugo.Hugo version 0.120.0
  manifests/h/Hugo/Hugo/0.120.0/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.120.0/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.120.0/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.120.0/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124327 New version: HydrusNetwork.HydrusNetwork version v549
  manifests/h/HydrusNetwork/HydrusNetwork/v549/HydrusNetwork.HydrusNetwork.installer.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v549/HydrusNetwork.HydrusNetwork.locale.en-US.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v549/HydrusNetwork.HydrusNetwork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124325 SagerNet.sing-box version 1.6.0
  manifests/s/SagerNet/sing-box/1.6.0/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.6.0/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.6.0/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124321 BlenderFoundation.Blender.LTS version 3.3.12
  manifests/b/BlenderFoundation/Blender/LTS/3.3.12/BlenderFoundation.Blender.LTS.installer.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.12/BlenderFoundation.Blender.LTS.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.12/BlenderFoundation.Blender.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124324 New version: Typst.Typst version 0.9.0
  manifests/t/Typst/Typst/0.9.0/Typst.Typst.installer.yaml
  manifests/t/Typst/Typst/0.9.0/Typst.Typst.locale.en-US.yaml
  manifests/t/Typst/Typst/0.9.0/Typst.Typst.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Executable-Error, Moderator-Approved, Waived-Validation-Executable-Error

#124322 KDE.Krita version 5.2.0
  manifests/k/KDE/Krita/5.2.0/KDE.Krita.installer.yaml
  manifests/k/KDE/Krita/5.2.0/KDE.Krita.locale.en-US.yaml
  manifests/k/KDE/Krita/5.2.0/KDE.Krita.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124319 BlenderFoundation.Blender.LTS version 3.3.10
  manifests/b/BlenderFoundation/Blender/LTS/3.3.10/BlenderFoundation.Blender.LTS.installer.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.10/BlenderFoundation.Blender.LTS.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.10/BlenderFoundation.Blender.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124318 New version: pit-ray.win-vind version 5.5.0
  manifests/p/pit-ray/win-vind/5.5.0/pit-ray.win-vind.installer.yaml
  manifests/p/pit-ray/win-vind/5.5.0/pit-ray.win-vind.locale.en-US.yaml
  manifests/p/pit-ray/win-vind/5.5.0/pit-ray.win-vind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124320 BlenderFoundation.Blender.LTS version 3.3.11
  manifests/b/BlenderFoundation/Blender/LTS/3.3.11/BlenderFoundation.Blender.LTS.installer.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.11/BlenderFoundation.Blender.LTS.locale.en-US.yaml
  manifests/b/BlenderFoundation/Blender/LTS/3.3.11/BlenderFoundation.Blender.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#124350 New version: BytecodeAlliance.Wasmtime version 14.0.3
  manifests/b/BytecodeAlliance/Wasmtime/14.0.3/BytecodeAlliance.Wasmtime.installer.yaml
  manifests/b/BytecodeAlliance/Wasmtime/14.0.3/BytecodeAlliance.Wasmtime.locale.en-US.yaml
  manifests/b/BytecodeAlliance/Wasmtime/14.0.3/BytecodeAlliance.Wasmtime.locale.zh-CN.yaml
  manifests/b/BytecodeAlliance/Wasmtime/14.0.3/BytecodeAlliance.Wasmtime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124355 New version: Kiwix.Wikivoyage version 2.7.6.0
  manifests/k/Kiwix/Wikivoyage/2.7.6.0/Kiwix.Wikivoyage.installer.yaml
  manifests/k/Kiwix/Wikivoyage/2.7.6.0/Kiwix.Wikivoyage.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/2.7.6.0/Kiwix.Wikivoyage.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#124357 New version: Kiwix.Wikivoyage.Electron version 2.7.6-E
  manifests/k/Kiwix/Wikivoyage/Electron/2.7.6-E/Kiwix.Wikivoyage.Electron.installer.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.7.6-E/Kiwix.Wikivoyage.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.7.6-E/Kiwix.Wikivoyage.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
