Repository microsoft/winget-pkgs, pull requests merged in 2023-04, with the labels that each got.

#101252 JanDeDobbeleer.OhMyPosh version 14.24.0
  manifests/j/JanDeDobbeleer/OhMyPosh/14.24.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.24.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.24.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101316 Update: KDE.Kate version 22.12.3
  manifests/k/KDE/Kate/22.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101315 New version: Jackett.Jackett version 0.20.3739
  manifests/j/Jackett/Jackett/0.20.3739/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.3739/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.3739/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101314 Update version: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101313 Update: KDE.Okular version 22.12.3
  manifests/k/KDE/Okular/22.12.3/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101312 Update: KDE.Kdenlive version 22.12.3
  manifests/k/KDE/Kdenlive/22.12.3/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101298 Update: KDE.Dolphin version 22.12.3
  manifests/k/KDE/Dolphin/22.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101295 Fix: Wondershare.PDFelement.CN version 9.0.14
  manifests/w/Wondershare/PDFelement/CN/9.0.14/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101296 Fix: Wondershare.PDFelement.CN version 9.0.12
  manifests/w/Wondershare/PDFelement/CN/9.0.12/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101293 Fix: Wondershare.PDFelement.CN version 9.2.1
  manifests/w/Wondershare/PDFelement/CN/9.2.1/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101283 ReleaseNotes: Ximalaya.Ximalaya version 3.3.7
  manifests/x/Ximalaya/Ximalaya/3.3.7/Ximalaya.Ximalaya.installer.yaml
  manifests/x/Ximalaya/Ximalaya/3.3.7/Ximalaya.Ximalaya.locale.en-US.yaml
  manifests/x/Ximalaya/Ximalaya/3.3.7/Ximalaya.Ximalaya.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101280 ReleaseNotes: Alibaba.Yuque version 2.6.4
  manifests/a/Alibaba/Yuque/2.6.4/Alibaba.Yuque.installer.yaml
  manifests/a/Alibaba/Yuque/2.6.4/Alibaba.Yuque.locale.en-US.yaml
  manifests/a/Alibaba/Yuque/2.6.4/Alibaba.Yuque.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101285 ReleaseNotes: Tencent.TranSmart version Alpha0.9.5
  manifests/t/Tencent/TranSmart/Alpha0.9.5/Tencent.TranSmart.locale.en-US.yaml
  manifests/t/Tencent/TranSmart/Alpha0.9.5/Tencent.TranSmart.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101277 ReleaseNotes: Cube.CubePlatform version 3.7.6.1
  manifests/c/Cube/CubePlatform/3.7.6.1/Cube.CubePlatform.installer.yaml
  manifests/c/Cube/CubePlatform/3.7.6.1/Cube.CubePlatform.locale.en-US.yaml
  manifests/c/Cube/CubePlatform/3.7.6.1/Cube.CubePlatform.locale.zh-CN.yaml
  manifests/c/Cube/CubePlatform/3.7.6.1/Cube.CubePlatform.locale.zh-HK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101275 ReleaseNotes: Sohu.SHPlayer version 7.0.22.0
  manifests/s/Sohu/SHPlayer/7.0.22.0/Sohu.SHPlayer.installer.yaml
  manifests/s/Sohu/SHPlayer/7.0.22.0/Sohu.SHPlayer.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101273 ReleaseNotes: Wondershare.Recoverit version 11.5.3.8
  manifests/w/Wondershare/Recoverit/11.5.3.8/Wondershare.Recoverit.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101269 ReleaseNotes: Appest.Dida version 4.4.4.0
  manifests/a/Appest/Dida/4.4.4.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/4.4.4.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/4.4.4.0/Appest.Dida.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101267 ReleaseNotes: 7S2P.Effie.CN version 2.6.1
  manifests/7/7S2P/Effie/CN/2.6.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.6.1/7S2P.Effie.CN.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101323 Ferdium.Ferdium.Nightly version 6.2.7-nightly.1
  manifests/f/Ferdium/Ferdium/Nightly/6.2.7-nightly.1/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.7-nightly.1/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.2.7-nightly.1/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101291 Fix: Wondershare.PDFelement.CN version 9.3.2
  manifests/w/Wondershare/PDFelement/CN/9.3.2/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101290 Fix: Wondershare.PDFelement.CN version 9.3.3
  manifests/w/Wondershare/PDFelement/CN/9.3.3/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101288 Fix: Wondershare.PDFelement.CN version 9.4.1
  manifests/w/Wondershare/PDFelement/CN/9.4.1/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101194 New version: VSCodium.VSCodium.Insiders version 1.78.0.23090
  manifests/v/VSCodium/VSCodium/Insiders/1.78.0.23090/VSCodium.VSCodium.Insiders.installer.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.78.0.23090/VSCodium.VSCodium.Insiders.locale.en-US.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.78.0.23090/VSCodium.VSCodium.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101243 Update: Swift.Toolchain.5.8
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101329 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101376 New version: Jackett.Jackett version 0.20.3756
  manifests/j/Jackett/Jackett/0.20.3756/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.3756/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.3756/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101369 Add Zip/Portable installers for Telegram
  manifests/t/Telegram/TelegramDesktop/4.7.1/Telegram.TelegramDesktop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101284 SmartSoft.SmartFTP version 10.0.3084.0
  manifests/s/SmartSoft/SmartFTP/10.0.3084.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3084.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3084.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101385 Update: KDE.kdevelop version 5.6.2 [FP-O]
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101347 Update: KDE.KDEConnect version 22.12.3
  manifests/k/KDE/KDEConnect/22.12.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101357 Update: KDE.Dolphin version 22.12.3
  manifests/k/KDE/Dolphin/22.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101370 Update: KDE.Kdenlive version 22.12.3
  manifests/k/KDE/Kdenlive/22.12.3/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101371 Update: KDE.Okular version 22.12.3
  manifests/k/KDE/Okular/22.12.3/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101372 Update: KDE.Kate version 22.12.3
  manifests/k/KDE/Kate/22.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101393 New version: Peppy.Osu! version 2023.403.0
  manifests/p/Peppy/Osu!/2023.403.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2023.403.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2023.403.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101339 New version: Google.Chrome.Canary version 114.0.5690.0 [FP-O]
  manifests/g/Google/Chrome/Canary/114.0.5690.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/114.0.5690.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/114.0.5690.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/114.0.5690.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101338 Change URLs to HTTPS - TheDocumentFoundation.LibreOffice
  manifests/t/TheDocumentFoundation/LibreOffice/7.5.2.2/TheDocumentFoundation.LibreOffice.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101394 JanDeDobbeleer.OhMyPosh version 14.25.0
  manifests/j/JanDeDobbeleer/OhMyPosh/14.25.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.25.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.25.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101414 Remove: 7S2P.Effie version 2.4.5
  manifests/7/7S2P/Effie/2.4.5/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.4.5/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.4.5/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.4.5/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101413 Remove: 7S2P.Effie version 2.4.3
  manifests/7/7S2P/Effie/2.4.3/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/2.4.3/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/2.4.3/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/2.4.3/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101411 Remove: 7S2P.Effie.CN version 2.5.1
  manifests/7/7S2P/Effie/CN/2.5.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.5.1/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.5.1/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.5.1/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101410 Remove: 7S2P.Effie.CN version 2.4.5
  manifests/7/7S2P/Effie/CN/2.4.5/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.4.5/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.4.5/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.4.5/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101409 Remove: 7S2P.Effie.CN version 2.4.3
  manifests/7/7S2P/Effie/CN/2.4.3/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.4.3/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.4.3/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.4.3/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101408 Remove: 7S2P.Effie.CN version 2.3.1
  manifests/7/7S2P/Effie/CN/2.3.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.3.1/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.3.1/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.3.1/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101407 Remove: 7S2P.Effie.CN version 2.2.19
  manifests/7/7S2P/Effie/CN/2.2.19/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.2.19/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.2.19/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.2.19/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101406 ReleaseNotes: Microsoft.PCManager.CN version 1.2.6.3
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.6.3/Microsoft.PCManager.CN.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101427 Microsoft.VisualStudioCode.Insiders_v1.78.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.78.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101412 Remove: 7S2P.Effie.CN version 2.5.3
  manifests/7/7S2P/Effie/CN/2.5.3/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/2.5.3/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/2.5.3/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/2.5.3/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101332 Emurasoft.EmEditor version 22.2.9
  manifests/e/Emurasoft/EmEditor/22.2.9/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/22.2.9/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/22.2.9/Emurasoft.EmEditor.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#101345 Emurasoft.EmEditor version 22.2.10
  manifests/e/Emurasoft/EmEditor/22.2.10/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/22.2.10/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/22.2.10/Emurasoft.EmEditor.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#101437 Added AWS Command Line Interface version 2.11.8.
  manifests/a/Amazon/AWSCLI/2.11.8/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.11.8/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.11.8/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101383 Make `PortableCommandAlias` optional in YamlCreate
  Tools/YamlCreate.ps1
Labels: Moderator-Approved, Project-File

#101395 Update to ZoomOutlookPlugin 5.14.0
  manifests/z/Zoom/ZoomOutlookPlugin/5.14.0/Zoom.ZoomOutlookPlugin.installer.yaml
  manifests/z/Zoom/ZoomOutlookPlugin/5.14.0/Zoom.ZoomOutlookPlugin.locale.en-US.yaml
  manifests/z/Zoom/ZoomOutlookPlugin/5.14.0/Zoom.ZoomOutlookPlugin.locale.zh-CN.yaml
  manifests/z/Zoom/ZoomOutlookPlugin/5.14.0/Zoom.ZoomOutlookPlugin.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#101322 New package: koalaman.shellcheck version 0.9.0
  manifests/k/koalaman/shellcheck/0.9.0/koalaman.shellcheck.installer.yaml
  manifests/k/koalaman/shellcheck/0.9.0/koalaman.shellcheck.locale.en-US.yaml
  manifests/k/koalaman/shellcheck/0.9.0/koalaman.shellcheck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#101032 New version: Elgato.CameraHub version 1.6.1.999
  manifests/e/Elgato/CameraHub/1.6.1.999/Elgato.CameraHub.installer.yaml
  manifests/e/Elgato/CameraHub/1.6.1.999/Elgato.CameraHub.locale.en-US.yaml
  manifests/e/Elgato/CameraHub/1.6.1.999/Elgato.CameraHub.yaml
Labels: Validation-Completed, Moderator-Approved

#101446 New version: Microsoft.ServiceFabricRuntime version 9.1.1583.9590
  manifests/m/Microsoft/ServiceFabricRuntime/9.1.1583.9590/Microsoft.ServiceFabricRuntime.installer.yaml
  manifests/m/Microsoft/ServiceFabricRuntime/9.1.1583.9590/Microsoft.ServiceFabricRuntime.locale.en-US.yaml
  manifests/m/Microsoft/ServiceFabricRuntime/9.1.1583.9590/Microsoft.ServiceFabricRuntime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#101430 New version: VSCodium.VSCodium version 1.77.0.23093
  manifests/v/VSCodium/VSCodium/1.77.0.23093/VSCodium.VSCodium.installer.yaml
  manifests/v/VSCodium/VSCodium/1.77.0.23093/VSCodium.VSCodium.locale.en-US.yaml
  manifests/v/VSCodium/VSCodium/1.77.0.23093/VSCodium.VSCodium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101444 Coder.Coder version 0.21.3
  manifests/c/Coder/Coder/0.21.3/Coder.Coder.installer.yaml
  manifests/c/Coder/Coder/0.21.3/Coder.Coder.locale.en-US.yaml
  manifests/c/Coder/Coder/0.21.3/Coder.Coder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101160 New version: Microsoft.Edge version 111.0.1661.62
  manifests/m/Microsoft/Edge/111.0.1661.62/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/111.0.1661.62/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/111.0.1661.62/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/111.0.1661.62/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101225 New version: Wondershare.DemoCreator version 6.6.2
  manifests/w/Wondershare/DemoCreator/6.6.2/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/6.6.2/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/6.6.2/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/6.6.2/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101264 New version: Catsxp.Catsxp version 112.3.4.1
  manifests/c/Catsxp/Catsxp/112.3.4.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/112.3.4.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/112.3.4.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/112.3.4.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101265 New version: 360.360SE version 14.1.1043.0
  manifests/3/360/360SE/14.1.1043.0/360.360SE.installer.yaml
  manifests/3/360/360SE/14.1.1043.0/360.360SE.locale.en-US.yaml
  manifests/3/360/360SE/14.1.1043.0/360.360SE.locale.zh-CN.yaml
  manifests/3/360/360SE/14.1.1043.0/360.360SE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101268 New version: Muye.FlickerList version 4.2.0
  manifests/m/Muye/FlickerList/4.2.0/Muye.FlickerList.installer.yaml
  manifests/m/Muye/FlickerList/4.2.0/Muye.FlickerList.locale.en-US.yaml
  manifests/m/Muye/FlickerList/4.2.0/Muye.FlickerList.locale.zh-CN.yaml
  manifests/m/Muye/FlickerList/4.2.0/Muye.FlickerList.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101270 New version: PerfectWorld.PerfectWorldArena version 1.0.23033111
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23033111/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23033111/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23033111/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23033111/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101271 New version: Youqu.ToDesk version 4.6.2.1
  manifests/y/Youqu/ToDesk/4.6.2.1/Youqu.ToDesk.installer.yaml
  manifests/y/Youqu/ToDesk/4.6.2.1/Youqu.ToDesk.locale.en-US.yaml
  manifests/y/Youqu/ToDesk/4.6.2.1/Youqu.ToDesk.locale.zh-CN.yaml
  manifests/y/Youqu/ToDesk/4.6.2.1/Youqu.ToDesk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97032 New package: Redisant.DataAssistant version 1.0.5.1
  manifests/r/Redisant/DataAssistant/1.0.5.1/Redisant.DataAssistant.installer.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.1/Redisant.DataAssistant.locale.en-US.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.1/Redisant.DataAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/DataAssistant/1.0.5.1/Redisant.DataAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101272 New version: ByteDance.Feishu version 6.1.5
  manifests/b/ByteDance/Feishu/6.1.5/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/6.1.5/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/6.1.5/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/6.1.5/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101274 New version: Kingsoft.KDocs version 3.8.2
  manifests/k/Kingsoft/KDocs/3.8.2/Kingsoft.KDocs.installer.yaml
  manifests/k/Kingsoft/KDocs/3.8.2/Kingsoft.KDocs.locale.en-US.yaml
  manifests/k/Kingsoft/KDocs/3.8.2/Kingsoft.KDocs.locale.zh-CN.yaml
  manifests/k/Kingsoft/KDocs/3.8.2/Kingsoft.KDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101276 New version: Wondershare.PDFelement.9 version 9.5.0
  manifests/w/Wondershare/PDFelement/9/9.5.0/Wondershare.PDFelement.9.installer.yaml
  manifests/w/Wondershare/PDFelement/9/9.5.0/Wondershare.PDFelement.9.locale.en-US.yaml
  manifests/w/Wondershare/PDFelement/9/9.5.0/Wondershare.PDFelement.9.locale.zh-CN.yaml
  manifests/w/Wondershare/PDFelement/9/9.5.0/Wondershare.PDFelement.9.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101278 Fix: Tencent.TencentVideo version 11.64.4506.0
  manifests/t/Tencent/TencentVideo/11.64.4506.0/Tencent.TencentVideo.installer.yaml
  manifests/t/Tencent/TencentVideo/11.64.4506.0/Tencent.TencentVideo.locale.en-US.yaml
  manifests/t/Tencent/TencentVideo/11.64.4506.0/Tencent.TencentVideo.locale.zh-CN.yaml
  manifests/t/Tencent/TencentVideo/11.64.4506.0/Tencent.TencentVideo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101279 Fix: Tencent.TencentVideo version 11.64.3075.0
  manifests/t/Tencent/TencentVideo/11.64.3075.0/Tencent.TencentVideo.installer.yaml
  manifests/t/Tencent/TencentVideo/11.64.3075.0/Tencent.TencentVideo.locale.en-US.yaml
  manifests/t/Tencent/TencentVideo/11.64.3075.0/Tencent.TencentVideo.locale.zh-CN.yaml
  manifests/t/Tencent/TencentVideo/11.64.3075.0/Tencent.TencentVideo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101281 New version: Microsoft.PCManager.CN version 1.2.9.2
  manifests/m/Microsoft/PCManager/CN/1.2.9.2/Microsoft.PCManager.CN.installer.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.2/Microsoft.PCManager.CN.locale.en-US.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.2/Microsoft.PCManager.CN.locale.zh-CN.yaml
  manifests/m/Microsoft/PCManager/CN/1.2.9.2/Microsoft.PCManager.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101286 Fix: Wondershare.PDFelement.CN version 9.4.7
  manifests/w/Wondershare/PDFelement/CN/9.4.7/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101287 Fix: Wondershare.PDFelement.CN version 9.4.5
  manifests/w/Wondershare/PDFelement/CN/9.4.5/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101292 Fix: Wondershare.PDFelement.CN version 9.3.0
  manifests/w/Wondershare/PDFelement/CN/9.3.0/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101294 Fix: Wondershare.PDFelement.CN version 9.1.4
  manifests/w/Wondershare/PDFelement/CN/9.1.4/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101297 Fix: Wondershare.PDFelement.CN version 9.0.9
  manifests/w/Wondershare/PDFelement/CN/9.0.9/Wondershare.PDFelement.CN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101301 Moving: Maxthon.Maxthon.6 version 6.1.3.3000
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.installer.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.3.3000/Maxthon.Maxthon.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101453 Remove Microsoft.ServiceFabricExplorer 18.9.2701
  manifests/m/Microsoft/ServiceFabricExplorer/18.9.2701/Microsoft.ServiceFabricExplorer.installer.yaml
  manifests/m/Microsoft/ServiceFabricExplorer/18.9.2701/Microsoft.ServiceFabricExplorer.locale.en-US.yaml
  manifests/m/Microsoft/ServiceFabricExplorer/18.9.2701/Microsoft.ServiceFabricExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101308 GLab.GLab version 1.27.0
  manifests/g/GLab/GLab/1.27.0/GLab.GLab.installer.yaml
  manifests/g/GLab/GLab/1.27.0/GLab.GLab.locale.en-US.yaml
  manifests/g/GLab/GLab/1.27.0/GLab.GLab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101307 New version: Maxthon.Maxthon version 7.0.0.2000
  manifests/m/Maxthon/Maxthon/7.0.0.2000/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/7.0.0.2000/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/7.0.0.2000/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/7.0.0.2000/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101305 Moved: Maxthon.Maxthon version 6.2.0.1000
  manifests/m/Maxthon/Maxthon/6.2.0.1000/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.1000/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.1000/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.1000/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved

#101304 Moved: Maxthon.Maxthon version 6.2.0.2000
  manifests/m/Maxthon/Maxthon/6.2.0.2000/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.2000/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.2000/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/6.2.0.2000/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved

#101302 Moving: Maxthon.Maxthon.6 version 6.1.2.3000
  manifests/m/Maxthon/Maxthon/6/6.1.2.3000/Maxthon.Maxthon.6.installer.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.2.3000/Maxthon.Maxthon.6.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/6/6.1.2.3000/Maxthon.Maxthon.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101311 uvncbvba.UltraVnc version 1.4.0.9
  manifests/u/uvncbvba/UltraVnc/1.4.0.9/uvncbvba.UltraVnc.installer.yaml
  manifests/u/uvncbvba/UltraVnc/1.4.0.9/uvncbvba.UltraVnc.locale.en-US.yaml
  manifests/u/uvncbvba/UltraVnc/1.4.0.9/uvncbvba.UltraVnc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101317 New version: katahiromz.RisohEditor version 5.7.4 [FP-O]
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.installer.yaml
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.locale.en-US.yaml
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.locale.zh-CN.yaml
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101318 Pylogmon.pot version 0.1.9
  manifests/p/Pylogmon/pot/0.1.9/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/0.1.9/Pylogmon.pot.locale.zh-CN.yaml
  manifests/p/Pylogmon/pot/0.1.9/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101320 Pylogmon.pot version 0.1.10
  manifests/p/Pylogmon/pot/0.1.10/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/0.1.10/Pylogmon.pot.locale.zh-CN.yaml
  manifests/p/Pylogmon/pot/0.1.10/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101321 New version: IrfanSkiljan.IrfanView version 4.62
  manifests/i/IrfanSkiljan/IrfanView/4.62/IrfanSkiljan.IrfanView.installer.yaml
  manifests/i/IrfanSkiljan/IrfanView/4.62/IrfanSkiljan.IrfanView.locale.en-US.yaml
  manifests/i/IrfanSkiljan/IrfanView/4.62/IrfanSkiljan.IrfanView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101327 Add AGSProjectTeam.AdventureGameStudio 3.6.0.47
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.47/AGSProjectTeam.AdventureGameStudio.installer.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.47/AGSProjectTeam.AdventureGameStudio.locale.en-US.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.47/AGSProjectTeam.AdventureGameStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101328 dotpdnllc.paintdotnet 5.0.2 not avaliable anymore.
  manifests/d/dotPDNLLC/paintdotnet/5.0.2/dotPDNLLC.paintdotnet.installer.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.2/dotPDNLLC.paintdotnet.locale.en-US.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.2/dotPDNLLC.paintdotnet.locale.zh-CN.yaml
  manifests/d/dotPDNLLC/paintdotnet/5.0.2/dotPDNLLC.paintdotnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101330 XnSoft.XnConvert version 1.96.0
  manifests/x/XnSoft/XnConvert/1.96.0/XnSoft.XnConvert.installer.yaml
  manifests/x/XnSoft/XnConvert/1.96.0/XnSoft.XnConvert.locale.en-US.yaml
  manifests/x/XnSoft/XnConvert/1.96.0/XnSoft.XnConvert.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101331 New version: clouDr-f2e.rubick version 2.1.10 [FP-O]
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101333 electerm.electerm version 1.25.30
  manifests/e/electerm/electerm/1.25.30/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.25.30/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.25.30/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101334 MuhammedKalkan.OpenLens version 6.4.13
  manifests/m/MuhammedKalkan/OpenLens/6.4.13/MuhammedKalkan.OpenLens.installer.yaml
  manifests/m/MuhammedKalkan/OpenLens/6.4.13/MuhammedKalkan.OpenLens.locale.en-US.yaml
  manifests/m/MuhammedKalkan/OpenLens/6.4.13/MuhammedKalkan.OpenLens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101335 New version: Notion.Notion version 2.0.41
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101336 joncampbell123.DOSBox-X version 2023.03.31
  manifests/j/joncampbell123/DOSBox-X/2023.03.31/joncampbell123.DOSBox-X.installer.yaml
  manifests/j/joncampbell123/DOSBox-X/2023.03.31/joncampbell123.DOSBox-X.locale.en-US.yaml
  manifests/j/joncampbell123/DOSBox-X/2023.03.31/joncampbell123.DOSBox-X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101342 New version: TedZyzsdy.NegativeEncoder version 5.0.7
  manifests/t/TedZyzsdy/NegativeEncoder/5.0.7/TedZyzsdy.NegativeEncoder.installer.yaml
  manifests/t/TedZyzsdy/NegativeEncoder/5.0.7/TedZyzsdy.NegativeEncoder.locale.en-US.yaml
  manifests/t/TedZyzsdy/NegativeEncoder/5.0.7/TedZyzsdy.NegativeEncoder.locale.zh-CN.yaml
  manifests/t/TedZyzsdy/NegativeEncoder/5.0.7/TedZyzsdy.NegativeEncoder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101343 New version: Hesan.He3 version 1.3.0
  manifests/h/Hesan/He3/1.3.0/Hesan.He3.installer.yaml
  manifests/h/Hesan/He3/1.3.0/Hesan.He3.locale.en-US.yaml
  manifests/h/Hesan/He3/1.3.0/Hesan.He3.locale.zh-CN.yaml
  manifests/h/Hesan/He3/1.3.0/Hesan.He3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101344 New version: Muye.FlickerList version 4.2.1
  manifests/m/Muye/FlickerList/4.2.1/Muye.FlickerList.installer.yaml
  manifests/m/Muye/FlickerList/4.2.1/Muye.FlickerList.locale.en-US.yaml
  manifests/m/Muye/FlickerList/4.2.1/Muye.FlickerList.locale.zh-CN.yaml
  manifests/m/Muye/FlickerList/4.2.1/Muye.FlickerList.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101349 New version: Cocos.CocosDashboard version 1.3.1.3117
  manifests/c/Cocos/CocosDashboard/1.3.1.3117/Cocos.CocosDashboard.installer.yaml
  manifests/c/Cocos/CocosDashboard/1.3.1.3117/Cocos.CocosDashboard.locale.en-US.yaml
  manifests/c/Cocos/CocosDashboard/1.3.1.3117/Cocos.CocosDashboard.locale.zh-CN.yaml
  manifests/c/Cocos/CocosDashboard/1.3.1.3117/Cocos.CocosDashboard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101348 Update: ZeroInstall.ZeroInstall version 2.24.6
  manifests/z/ZeroInstall/ZeroInstall/2.24.6/ZeroInstall.ZeroInstall.installer.yaml
  manifests/z/ZeroInstall/ZeroInstall/2.24.6/ZeroInstall.ZeroInstall.locale.en-US.yaml
  manifests/z/ZeroInstall/ZeroInstall/2.24.6/ZeroInstall.ZeroInstall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101352 New version: SteamGridDB.RomManager version 2.3.51 [FP-O]
  manifests/s/SteamGridDB/RomManager/2.3.51/SteamGridDB.RomManager.installer.yaml
  manifests/s/SteamGridDB/RomManager/2.3.51/SteamGridDB.RomManager.locale.en-US.yaml
  manifests/s/SteamGridDB/RomManager/2.3.51/SteamGridDB.RomManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101351 New version: altair-graphql.altair version 5.0.21 [FP-O]
  manifests/a/altair-graphql/altair/5.0.21/altair-graphql.altair.installer.yaml
  manifests/a/altair-graphql/altair/5.0.21/altair-graphql.altair.locale.en-US.yaml
  manifests/a/altair-graphql/altair/5.0.21/altair-graphql.altair.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101354 New version: Mobatek.MobaXterm version 23.1.0.5058
  manifests/m/Mobatek/MobaXterm/23.1.0.5058/Mobatek.MobaXterm.installer.yaml
  manifests/m/Mobatek/MobaXterm/23.1.0.5058/Mobatek.MobaXterm.locale.en-US.yaml
  manifests/m/Mobatek/MobaXterm/23.1.0.5058/Mobatek.MobaXterm.locale.zh-CN.yaml
  manifests/m/Mobatek/MobaXterm/23.1.0.5058/Mobatek.MobaXterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101368 VideoLAN.x264 version 3106
  manifests/v/VideoLAN/x264/3106/VideoLAN.x264.installer.yaml
  manifests/v/VideoLAN/x264/3106/VideoLAN.x264.locale.en-US.yaml
  manifests/v/VideoLAN/x264/3106/VideoLAN.x264.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101378 New version: Taiko2k.TauonMusicBox version 7.6.3
  manifests/t/Taiko2k/TauonMusicBox/7.6.3/Taiko2k.TauonMusicBox.installer.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.6.3/Taiko2k.TauonMusicBox.locale.en-US.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.6.3/Taiko2k.TauonMusicBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101379 Add version: hluk.CopyQ version 7.0.0
  manifests/h/hluk/CopyQ/7.0.0/hluk.CopyQ.installer.yaml
  manifests/h/hluk/CopyQ/7.0.0/hluk.CopyQ.locale.en-US.yaml
  manifests/h/hluk/CopyQ/7.0.0/hluk.CopyQ.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101380 Ruben2776.PicView version 1.7.6
  manifests/r/Ruben2776/PicView/1.7.6/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/1.7.6/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/1.7.6/Ruben2776.PicView.locale.zh-CN.yaml
  manifests/r/Ruben2776/PicView/1.7.6/Ruben2776.PicView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#101439 Update: KDE.kdevelop version 5.6.2
  manifests/k/KDE/kdevelop/5.6.2/KDE.kdevelop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101426 New version: Jackett.Jackett version 0.20.3767
  manifests/j/Jackett/Jackett/0.20.3767/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.3767/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.3767/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101384 Slonopotamus.Stevedore version 0.12.0
  manifests/s/Slonopotamus/Stevedore/0.12.0/Slonopotamus.Stevedore.installer.yaml
  manifests/s/Slonopotamus/Stevedore/0.12.0/Slonopotamus.Stevedore.locale.en-US.yaml
  manifests/s/Slonopotamus/Stevedore/0.12.0/Slonopotamus.Stevedore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101386 New version: junegunn.fzf version 0.39.0
  manifests/j/junegunn/fzf/0.39.0/junegunn.fzf.installer.yaml
  manifests/j/junegunn/fzf/0.39.0/junegunn.fzf.locale.en-US.yaml
  manifests/j/junegunn/fzf/0.39.0/junegunn.fzf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101388 New version: ChilliBits.Spice version 0.14.2
  manifests/c/ChilliBits/Spice/0.14.2/ChilliBits.Spice.installer.yaml
  manifests/c/ChilliBits/Spice/0.14.2/ChilliBits.Spice.locale.en-US.yaml
  manifests/c/ChilliBits/Spice/0.14.2/ChilliBits.Spice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101389 New version: TopalaSoftwareSolutions.SIW version 2023.02.04q
  manifests/t/TopalaSoftwareSolutions/SIW/2023.02.04q/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.02.04q/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2023.02.04q/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101390 New version: ImageMagick.ImageMagick version 7.1.1.6
  manifests/i/ImageMagick/ImageMagick/7.1.1.6/ImageMagick.ImageMagick.installer.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.1.6/ImageMagick.ImageMagick.locale.en-US.yaml
  manifests/i/ImageMagick/ImageMagick/7.1.1.6/ImageMagick.ImageMagick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101397 New version: LN-Zap.zap version 0.7.7-beta
  manifests/l/LN-Zap/zap/0.7.7-beta/LN-Zap.zap.installer.yaml
  manifests/l/LN-Zap/zap/0.7.7-beta/LN-Zap.zap.locale.en-US.yaml
  manifests/l/LN-Zap/zap/0.7.7-beta/LN-Zap.zap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101398 New version: Google.Chrome.Canary version 114.0.5692.0 [FP-O]
  manifests/g/Google/Chrome/Canary/114.0.5692.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/114.0.5692.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/114.0.5692.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/114.0.5692.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101399 Update: KDE.KDEConnect version 22.12.3
  manifests/k/KDE/KDEConnect/22.12.3/KDE.KDEConnect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101400 New version: Hesan.He3 version 1.3.1
  manifests/h/Hesan/He3/1.3.1/Hesan.He3.installer.yaml
  manifests/h/Hesan/He3/1.3.1/Hesan.He3.locale.en-US.yaml
  manifests/h/Hesan/He3/1.3.1/Hesan.He3.locale.zh-CN.yaml
  manifests/h/Hesan/He3/1.3.1/Hesan.He3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101401 Update: KDE.Dolphin version 22.12.3
  manifests/k/KDE/Dolphin/22.12.3/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101457 New version: Muye.FlickerList version 4.2.2
  manifests/m/Muye/FlickerList/4.2.2/Muye.FlickerList.installer.yaml
  manifests/m/Muye/FlickerList/4.2.2/Muye.FlickerList.locale.en-US.yaml
  manifests/m/Muye/FlickerList/4.2.2/Muye.FlickerList.locale.zh-CN.yaml
  manifests/m/Muye/FlickerList/4.2.2/Muye.FlickerList.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101402 New version: LukasBach.Yana version 1.0.16
  manifests/l/LukasBach/Yana/1.0.16/LukasBach.Yana.installer.yaml
  manifests/l/LukasBach/Yana/1.0.16/LukasBach.Yana.locale.en-US.yaml
  manifests/l/LukasBach/Yana/1.0.16/LukasBach.Yana.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101403 huanghongxun.HelloMinecraftLauncher version 3.5.4.232
  manifests/h/huanghongxun/HelloMinecraftLauncher/3.5.4.232/huanghongxun.HelloMinecraftLauncher.installer.yaml
  manifests/h/huanghongxun/HelloMinecraftLauncher/3.5.4.232/huanghongxun.HelloMinecraftLauncher.locale.zh-CN.yaml
  manifests/h/huanghongxun/HelloMinecraftLauncher/3.5.4.232/huanghongxun.HelloMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101415 Pylogmon.pot version 0.1.11
  manifests/p/Pylogmon/pot/0.1.11/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/0.1.11/Pylogmon.pot.locale.zh-CN.yaml
  manifests/p/Pylogmon/pot/0.1.11/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101417 New version: Peppy.Osu! version 2023.403.1
  manifests/p/Peppy/Osu!/2023.403.1/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2023.403.1/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2023.403.1/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101455 New version: Hesan.He3 version 1.3.2
  manifests/h/Hesan/He3/1.3.2/Hesan.He3.installer.yaml
  manifests/h/Hesan/He3/1.3.2/Hesan.He3.locale.en-US.yaml
  manifests/h/Hesan/He3/1.3.2/Hesan.He3.locale.zh-CN.yaml
  manifests/h/Hesan/He3/1.3.2/Hesan.He3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101456 New version: JLC.LCEDA version 6.5.28
  manifests/j/JLC/LCEDA/6.5.28/JLC.LCEDA.installer.yaml
  manifests/j/JLC/LCEDA/6.5.28/JLC.LCEDA.locale.en-US.yaml
  manifests/j/JLC/LCEDA/6.5.28/JLC.LCEDA.locale.zh-CN.yaml
  manifests/j/JLC/LCEDA/6.5.28/JLC.LCEDA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101459 New version: Tencent.TencentMeetingRooms version 3.14.200.563
  manifests/t/Tencent/TencentMeetingRooms/3.14.200.563/Tencent.TencentMeetingRooms.installer.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.14.200.563/Tencent.TencentMeetingRooms.locale.en-US.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.14.200.563/Tencent.TencentMeetingRooms.locale.zh-CN.yaml
  manifests/t/Tencent/TencentMeetingRooms/3.14.200.563/Tencent.TencentMeetingRooms.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101319 Graebert.ares commnder.2024 24.0.1114
  manifests/g/Graebert/AresCommander/2024/24.0.1114/Graebert.AresCommander.2024.installer.yaml
  manifests/g/Graebert/AresCommander/2024/24.0.1114/Graebert.AresCommander.2024.locale.en-US.yaml
  manifests/g/Graebert/AresCommander/2024/24.0.1114/Graebert.AresCommander.2024.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101418 Hashicorp.Terraform 1.4.4
  manifests/h/Hashicorp/Terraform/1.4.4/Hashicorp.Terraform.installer.yaml
  manifests/h/Hashicorp/Terraform/1.4.4/Hashicorp.Terraform.locale.en-US.yaml
  manifests/h/Hashicorp/Terraform/1.4.4/Hashicorp.Terraform.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101419 Update: KDE.Kdenlive version 22.12.3
  manifests/k/KDE/Kdenlive/22.12.3/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101421 Update: KDE.Okular version 22.12.3
  manifests/k/KDE/Okular/22.12.3/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101422 Update version: Neovim.Neovim.Nightly version 0.9.0
  manifests/n/Neovim/Neovim/Nightly/0.9.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101423 Update: KDE.Kate version 22.12.3
  manifests/k/KDE/Kate/22.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101428 PathofBuildingCommunity.PathofBuildingCommunity version 2.26.1
  manifests/p/PathofBuildingCommunity/PathofBuildingCommunity/2.26.1/PathofBuildingCommunity.PathofBuildingCommunity.installer.yaml
  manifests/p/PathofBuildingCommunity/PathofBuildingCommunity/2.26.1/PathofBuildingCommunity.PathofBuildingCommunity.locale.en-US.yaml
  manifests/p/PathofBuildingCommunity/PathofBuildingCommunity/2.26.1/PathofBuildingCommunity.PathofBuildingCommunity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101434 StarlaneStudios.Surrealist version 1.6.3
  manifests/s/StarlaneStudios/Surrealist/1.6.3/StarlaneStudios.Surrealist.installer.yaml
  manifests/s/StarlaneStudios/Surrealist/1.6.3/StarlaneStudios.Surrealist.locale.en-US.yaml
  manifests/s/StarlaneStudios/Surrealist/1.6.3/StarlaneStudios.Surrealist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101435 Devolutions.RemoteDesktopManager version 2023.1.20.0
  manifests/d/Devolutions/RemoteDesktopManager/2023.1.20.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2023.1.20.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2023.1.20.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#101440 New version: aliyunpan 0.2.7
  manifests/t/tickstep/aliyunpan/0.2.7/tickstep.aliyunpan.installer.yaml
  manifests/t/tickstep/aliyunpan/0.2.7/tickstep.aliyunpan.locale.en-US.yaml
  manifests/t/tickstep/aliyunpan/0.2.7/tickstep.aliyunpan.locale.zh-CN.yaml
  manifests/t/tickstep/aliyunpan/0.2.7/tickstep.aliyunpan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101441 New version: HTTPToolKit.HTTPToolKit version 1.12.5
  manifests/h/HTTPToolKit/HTTPToolKit/1.12.5/HTTPToolKit.HTTPToolKit.installer.yaml
  manifests/h/HTTPToolKit/HTTPToolKit/1.12.5/HTTPToolKit.HTTPToolKit.locale.en-US.yaml
  manifests/h/HTTPToolKit/HTTPToolKit/1.12.5/HTTPToolKit.HTTPToolKit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101442 New version: JFrog.Conan version 2.0.3
  manifests/j/JFrog/Conan/2.0.3/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/2.0.3/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/2.0.3/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101443 New version: Prey.Prey version 1.11.3
  manifests/p/Prey/Prey/1.11.3/Prey.Prey.installer.yaml
  manifests/p/Prey/Prey/1.11.3/Prey.Prey.locale.en-US.yaml
  manifests/p/Prey/Prey/1.11.3/Prey.Prey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101452 New version: Kubernetes.minikube version 1.30.0
  manifests/k/Kubernetes/minikube/1.30.0/Kubernetes.minikube.installer.yaml
  manifests/k/Kubernetes/minikube/1.30.0/Kubernetes.minikube.locale.en-US.yaml
  manifests/k/Kubernetes/minikube/1.30.0/Kubernetes.minikube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101445 New version: Fedora.CoreOS.butane version 0.18.0
  manifests/f/Fedora/CoreOS/butane/0.18.0/Fedora.CoreOS.butane.installer.yaml
  manifests/f/Fedora/CoreOS/butane/0.18.0/Fedora.CoreOS.butane.locale.en-US.yaml
  manifests/f/Fedora/CoreOS/butane/0.18.0/Fedora.CoreOS.butane.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101463 Add version: katahiromz.RisohEditor version 5.7.3
  manifests/k/katahiromz/RisohEditor/5.7.3/katahiromz.RisohEditor.installer.yaml
  manifests/k/katahiromz/RisohEditor/5.7.3/katahiromz.RisohEditor.locale.en-US.yaml
  manifests/k/katahiromz/RisohEditor/5.7.3/katahiromz.RisohEditor.locale.zh-CN.yaml
  manifests/k/katahiromz/RisohEditor/5.7.3/katahiromz.RisohEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101374 Update Initex.Proxifier
  manifests/i/Initex/Proxifier/4.11/Initex.Proxifier.installer.yaml
  manifests/i/Initex/Proxifier/4.11/Initex.Proxifier.locale.en-US.yaml
  manifests/i/Initex/Proxifier/4.11/Initex.Proxifier.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101458 New version: THS.THS.Hevo version 8.9.1.4
  manifests/t/THS/THS/Hevo/8.9.1.4/THS.THS.Hevo.installer.yaml
  manifests/t/THS/THS/Hevo/8.9.1.4/THS.THS.Hevo.locale.en-US.yaml
  manifests/t/THS/THS/Hevo/8.9.1.4/THS.THS.Hevo.locale.zh-CN.yaml
  manifests/t/THS/THS/Hevo/8.9.1.4/THS.THS.Hevo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#97894 Genymobile.scrcpy version 1.25
  manifests/g/Genymobile/scrcpy/1.25/Genymobile.scrcpy.installer.yaml
  manifests/g/Genymobile/scrcpy/1.25/Genymobile.scrcpy.locale.en-US.yaml
  manifests/g/Genymobile/scrcpy/1.25/Genymobile.scrcpy.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#101462 ReleaseNotes: katahiromz.RisohEditor version 5.7.4
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.installer.yaml
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.locale.en-US.yaml
  manifests/k/katahiromz/RisohEditor/5.7.4/katahiromz.RisohEditor.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#101460 New version: Tencent.TencentDocs version 2.4.17
  manifests/t/Tencent/TencentDocs/2.4.17/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.4.17/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.4.17/Tencent.TencentDocs.locale.zh-CN.yaml
  manifests/t/Tencent/TencentDocs/2.4.17/Tencent.TencentDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
