Repository microsoft/winget-pkgs, pull requests merged in 2023-06, with the labels that each got.

#108426 New version: SKDataAS.ORMCore version 202330051
  manifests/s/SKDataAS/ORMCore/202330051/SKDataAS.ORMCore.installer.yaml
  manifests/s/SKDataAS/ORMCore/202330051/SKDataAS.ORMCore.locale.en-US.yaml
  manifests/s/SKDataAS/ORMCore/202330051/SKDataAS.ORMCore.yaml
Labels: Validation-Completed, Retry-1

#108454 New version: TeamViewer.TeamViewer version 15.42.6
  manifests/t/TeamViewer/TeamViewer/15.42.6/TeamViewer.TeamViewer.installer.yaml
  manifests/t/TeamViewer/TeamViewer/15.42.6/TeamViewer.TeamViewer.locale.de-DE.yaml
  manifests/t/TeamViewer/TeamViewer/15.42.6/TeamViewer.TeamViewer.locale.en-US.yaml
  manifests/t/TeamViewer/TeamViewer/15.42.6/TeamViewer.TeamViewer.locale.zh-CN.yaml
  manifests/t/TeamViewer/TeamViewer/15.42.6/TeamViewer.TeamViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#108468 infinitepower18.WSASystemControl version 1.0.1
  manifests/i/infinitepower18/WSASystemControl/1.0.1/infinitepower18.WSASystemControl.installer.yaml
  manifests/i/infinitepower18/WSASystemControl/1.0.1/infinitepower18.WSASystemControl.locale.en-US.yaml
  manifests/i/infinitepower18/WSASystemControl/1.0.1/infinitepower18.WSASystemControl.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108495 Updating to SiberSystems.Roboform 9.4.8.8
  manifests/s/SiberSystems/RoboForm/9.4.8.8/SiberSystems.RoboForm.installer.yaml
  manifests/s/SiberSystems/RoboForm/9.4.8.8/SiberSystems.RoboForm.locale.en-US.yaml
  manifests/s/SiberSystems/RoboForm/9.4.8.8/SiberSystems.RoboForm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108496 Ferdium.Ferdium.Nightly version 6.3.0-nightly.15
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.15/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.15/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.15/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108503 Update Splashtop.SplashtopBusiness version 3.5.800.0
  manifests/s/Splashtop/SplashtopBusiness/3.5.800.0/Splashtop.SplashtopBusiness.installer.yaml
  manifests/s/Splashtop/SplashtopBusiness/3.5.800.0/Splashtop.SplashtopBusiness.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108507 Fix Upgrade Behavior for Splashtop.SplashtopStreamer.Deployment 3.5.8.0
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.installer.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.locale.en-US.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108337 New package: Posit.rig version 0.5.3
  manifests/p/Posit/rig/0.5.3/Posit.rig.installer.yaml
  manifests/p/Posit/rig/0.5.3/Posit.rig.locale.en-US.yaml
  manifests/p/Posit/rig/0.5.3/Posit.rig.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108508 OpenJS.NodeJS version 20.2.0
  manifests/o/OpenJS/NodeJS/20.2.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/20.2.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/20.2.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/20.2.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108509 Update: OSGeo.QGIS_LTR 3.28.7
  manifests/o/OSGeo/QGIS_LTR/3.28.7/OSGeo.QGIS_LTR.installer.yaml
  manifests/o/OSGeo/QGIS_LTR/3.28.7/OSGeo.QGIS_LTR.locale.en-US.yaml
  manifests/o/OSGeo/QGIS_LTR/3.28.7/OSGeo.QGIS_LTR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108512 Sidero.talosctl version 1.4.5
  manifests/s/Sidero/talosctl/1.4.5/Sidero.talosctl.installer.yaml
  manifests/s/Sidero/talosctl/1.4.5/Sidero.talosctl.locale.en-US.yaml
  manifests/s/Sidero/talosctl/1.4.5/Sidero.talosctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108515 Update Krisp.Krisp to 2.19.2
  manifests/k/Krisp/Krisp/2.19.2/Krisp.Krisp.installer.yaml
  manifests/k/Krisp/Krisp/2.19.2/Krisp.Krisp.locale.en-US.yaml
  manifests/k/Krisp/Krisp/2.19.2/Krisp.Krisp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108497 redream.redream version 1.5.0
  manifests/r/redream/redream/1.5.0/redream.redream.installer.yaml
  manifests/r/redream/redream/1.5.0/redream.redream.locale.en-US.yaml
  manifests/r/redream/redream/1.5.0/redream.redream.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108516 Update Krisp.Krisp to 2.18.6
  manifests/k/Krisp/Krisp/2.18.6/Krisp.Krisp.installer.yaml
  manifests/k/Krisp/Krisp/2.18.6/Krisp.Krisp.locale.en-US.yaml
  manifests/k/Krisp/Krisp/2.18.6/Krisp.Krisp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108522 Solidigm.StorageTool version 1.8
  manifests/s/Solidigm/StorageTool/1.8/Solidigm.StorageTool.installer.yaml
  manifests/s/Solidigm/StorageTool/1.8/Solidigm.StorageTool.locale.en-US.yaml
  manifests/s/Solidigm/StorageTool/1.8/Solidigm.StorageTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108523 Update LibreWolf.LibreWolf to v113.0.2-1
  manifests/l/LibreWolf/LibreWolf/113.0.2-1/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/113.0.2-1/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/113.0.2-1/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108524 SurgeSynthTeam.SurgeXT version 1.2.3
  manifests/s/SurgeSynthTeam/SurgeXT/1.2.3/SurgeSynthTeam.SurgeXT.installer.yaml
  manifests/s/SurgeSynthTeam/SurgeXT/1.2.3/SurgeSynthTeam.SurgeXT.locale.en-US.yaml
  manifests/s/SurgeSynthTeam/SurgeXT/1.2.3/SurgeSynthTeam.SurgeXT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108530 CPUID.CPU-Z.ASR version 2.05
  manifests/c/CPUID/CPU-Z/ASR/2.05/CPUID.CPU-Z.ASR.installer.yaml
  manifests/c/CPUID/CPU-Z/ASR/2.05/CPUID.CPU-Z.ASR.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/ASR/2.05/CPUID.CPU-Z.ASR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108529 CPUID.CPU-Z.AORUS version 2.05
  manifests/c/CPUID/CPU-Z/AORUS/2.05/CPUID.CPU-Z.AORUS.installer.yaml
  manifests/c/CPUID/CPU-Z/AORUS/2.05/CPUID.CPU-Z.AORUS.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/AORUS/2.05/CPUID.CPU-Z.AORUS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108537 New version: CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition version 9.0.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108538 New version: CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.9.0.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/ShizukuEdition/9.0.1/CrystalDewWorld.CrystalDiskInfo.ShizukuEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108539 Wikivoyage by Kiwix UWP 2.4.9.0
  manifests/k/Kiwix/Wikivoyage/2.4.9.0/Kiwix.Wikivoyage.installer.yaml
  manifests/k/Kiwix/Wikivoyage/2.4.9.0/Kiwix.Wikivoyage.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/2.4.9.0/Kiwix.Wikivoyage.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108540 Wikivoyage by Kiwix 2.4.9-E
  manifests/k/Kiwix/Wikivoyage/Electron/2.4.9-E/Kiwix.Wikivoyage.Electron.installer.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.4.9-E/Kiwix.Wikivoyage.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/Wikivoyage/Electron/2.4.9-E/Kiwix.Wikivoyage.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108542 Update version: ChilliBits.Spice version 0.15.3
  manifests/c/ChilliBits/Spice/0.15.3/ChilliBits.Spice.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108543 New version: SteelSeries.GG version 39.0.0
  manifests/s/SteelSeries/GG/39.0.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/39.0.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/39.0.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108544 PTRTECH.UVtools version 3.14.0
  manifests/p/PTRTECH/UVtools/3.14.0/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.14.0/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.14.0/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108546 New version: dundee.gdu version 5.24.0
  manifests/d/dundee/gdu/5.24.0/dundee.gdu.installer.yaml
  manifests/d/dundee/gdu/5.24.0/dundee.gdu.locale.en-US.yaml
  manifests/d/dundee/gdu/5.24.0/dundee.gdu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108545 Microsoft.VisualStudioCode.Insiders_v1.79.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.79.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108554 New version: Appest.TickTick version 4.5.1.0
  manifests/a/Appest/TickTick/4.5.1.0/Appest.TickTick.installer.yaml
  manifests/a/Appest/TickTick/4.5.1.0/Appest.TickTick.locale.en-US.yaml
  manifests/a/Appest/TickTick/4.5.1.0/Appest.TickTick.locale.zh-CN.yaml
  manifests/a/Appest/TickTick/4.5.1.0/Appest.TickTick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108555 New version: Brave.Brave.Nightly version 114.1.54.22
  manifests/b/Brave/Brave/Nightly/114.1.54.22/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/114.1.54.22/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/114.1.54.22/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/114.1.54.22/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108556 New version: ByteDance.Lark version 6.5.9
  manifests/b/ByteDance/Lark/6.5.9/ByteDance.Lark.installer.yaml
  manifests/b/ByteDance/Lark/6.5.9/ByteDance.Lark.locale.en-US.yaml
  manifests/b/ByteDance/Lark/6.5.9/ByteDance.Lark.locale.zh-CN.yaml
  manifests/b/ByteDance/Lark/6.5.9/ByteDance.Lark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108557 New version: DigiDNA.iMazing version 2.17.3.0
  manifests/d/DigiDNA/iMazing/2.17.3.0/DigiDNA.iMazing.installer.yaml
  manifests/d/DigiDNA/iMazing/2.17.3.0/DigiDNA.iMazing.locale.en-US.yaml
  manifests/d/DigiDNA/iMazing/2.17.3.0/DigiDNA.iMazing.locale.zh-CN.yaml
  manifests/d/DigiDNA/iMazing/2.17.3.0/DigiDNA.iMazing.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108558 New version: Brave.Brave version 114.1.52.117
  manifests/b/Brave/Brave/114.1.52.117/Brave.Brave.installer.yaml
  manifests/b/Brave/Brave/114.1.52.117/Brave.Brave.locale.en-US.yaml
  manifests/b/Brave/Brave/114.1.52.117/Brave.Brave.locale.zh-CN.yaml
  manifests/b/Brave/Brave/114.1.52.117/Brave.Brave.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108559 New version: Hesan.He3 version 1.3.13
  manifests/h/Hesan/He3/1.3.13/Hesan.He3.installer.yaml
  manifests/h/Hesan/He3/1.3.13/Hesan.He3.locale.en-US.yaml
  manifests/h/Hesan/He3/1.3.13/Hesan.He3.locale.zh-CN.yaml
  manifests/h/Hesan/He3/1.3.13/Hesan.He3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108560 New version: YouXiao.YXCalendar version 2.3.5.28
  manifests/y/YouXiao/YXCalendar/2.3.5.28/YouXiao.YXCalendar.installer.yaml
  manifests/y/YouXiao/YXCalendar/2.3.5.28/YouXiao.YXCalendar.locale.en-US.yaml
  manifests/y/YouXiao/YXCalendar/2.3.5.28/YouXiao.YXCalendar.locale.zh-CN.yaml
  manifests/y/YouXiao/YXCalendar/2.3.5.28/YouXiao.YXCalendar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108562 New version: Wondershare.UBackit version 4.0.8.6
  manifests/w/Wondershare/UBackit/4.0.8.6/Wondershare.UBackit.installer.yaml
  manifests/w/Wondershare/UBackit/4.0.8.6/Wondershare.UBackit.locale.en-US.yaml
  manifests/w/Wondershare/UBackit/4.0.8.6/Wondershare.UBackit.locale.zh-CN.yaml
  manifests/w/Wondershare/UBackit/4.0.8.6/Wondershare.UBackit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108565 HydrusNetwork.HydrusNetwork version v530
  manifests/h/HydrusNetwork/HydrusNetwork/v530/HydrusNetwork.HydrusNetwork.installer.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v530/HydrusNetwork.HydrusNetwork.locale.en-US.yaml
  manifests/h/HydrusNetwork/HydrusNetwork/v530/HydrusNetwork.HydrusNetwork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108567 ShiningLight.OpenSSL.Light version 3.0.9
  manifests/s/ShiningLight/OpenSSL/Light/3.0.9/ShiningLight.OpenSSL.Light.installer.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.0.9/ShiningLight.OpenSSL.Light.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.0.9/ShiningLight.OpenSSL.Light.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108569 DoltHub.Dolt version 1.2.2
  manifests/d/DoltHub/Dolt/1.2.2/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.2.2/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.2.2/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108570 ShiningLight.OpenSSL.Light version 3.1.1
  manifests/s/ShiningLight/OpenSSL/Light/3.1.1/ShiningLight.OpenSSL.Light.installer.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.1.1/ShiningLight.OpenSSL.Light.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.1.1/ShiningLight.OpenSSL.Light.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108564 New version: vim.vim version 9.0.1595
  manifests/v/vim/vim/9.0.1595/vim.vim.installer.yaml
  manifests/v/vim/vim/9.0.1595/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.0.1595/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108577 Remove ShiningLight.OpenSSL version 3.0.8
  manifests/s/ShiningLight/OpenSSL/3.0.8/ShiningLight.OpenSSL.installer.yaml
  manifests/s/ShiningLight/OpenSSL/3.0.8/ShiningLight.OpenSSL.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/3.0.8/ShiningLight.OpenSSL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108579 Remove ShiningLight.OpenSSL.Light version 3.0.8
  manifests/s/ShiningLight/OpenSSL/Light/3.0.8/ShiningLight.OpenSSL.Light.installer.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.0.8/ShiningLight.OpenSSL.Light.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/Light/3.0.8/ShiningLight.OpenSSL.Light.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108571 ShiningLight.OpenSSL version 3.1.1
  manifests/s/ShiningLight/OpenSSL/3.1.1/ShiningLight.OpenSSL.installer.yaml
  manifests/s/ShiningLight/OpenSSL/3.1.1/ShiningLight.OpenSSL.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/3.1.1/ShiningLight.OpenSSL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108535 CPUID.CPU-Z.ROG version 2.05
  manifests/c/CPUID/CPU-Z/ROG/2.05/CPUID.CPU-Z.ROG.installer.yaml
  manifests/c/CPUID/CPU-Z/ROG/2.05/CPUID.CPU-Z.ROG.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/ROG/2.05/CPUID.CPU-Z.ROG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108534 CPUID.CPU-Z.PHANTOM version 2.05
  manifests/c/CPUID/CPU-Z/PHANTOM/2.05/CPUID.CPU-Z.PHANTOM.installer.yaml
  manifests/c/CPUID/CPU-Z/PHANTOM/2.05/CPUID.CPU-Z.PHANTOM.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/PHANTOM/2.05/CPUID.CPU-Z.PHANTOM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108533 CPUID.CPU-Z.MSI version 2.05
  manifests/c/CPUID/CPU-Z/MSI/2.05/CPUID.CPU-Z.MSI.installer.yaml
  manifests/c/CPUID/CPU-Z/MSI/2.05/CPUID.CPU-Z.MSI.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/MSI/2.05/CPUID.CPU-Z.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108536 CPUID.CPU-Z.TAICHI version 2.05
  manifests/c/CPUID/CPU-Z/TAICHI/2.05/CPUID.CPU-Z.TAICHI.installer.yaml
  manifests/c/CPUID/CPU-Z/TAICHI/2.05/CPUID.CPU-Z.TAICHI.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/TAICHI/2.05/CPUID.CPU-Z.TAICHI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108532 CPUID.CPU-Z.GBT version 2.05
  manifests/c/CPUID/CPU-Z/GBT/2.05/CPUID.CPU-Z.GBT.installer.yaml
  manifests/c/CPUID/CPU-Z/GBT/2.05/CPUID.CPU-Z.GBT.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/GBT/2.05/CPUID.CPU-Z.GBT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108531 CPUID.CPU-Z.CM version 2.05
  manifests/c/CPUID/CPU-Z/CM/2.05/CPUID.CPU-Z.CM.installer.yaml
  manifests/c/CPUID/CPU-Z/CM/2.05/CPUID.CPU-Z.CM.locale.en-US.yaml
  manifests/c/CPUID/CPU-Z/CM/2.05/CPUID.CPU-Z.CM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108582 ReleaseNotes: ByteDance.Lark version 6.4.5
  manifests/b/ByteDance/Lark/6.4.5/ByteDance.Lark.locale.en-US.yaml
  manifests/b/ByteDance/Lark/6.4.5/ByteDance.Lark.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108584 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108585 New version: Jackett.Jackett version 0.21.95
  manifests/j/Jackett/Jackett/0.21.95/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.95/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.95/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108586 Update version: AndreWiethoff.ExactAudioCopy version 1.6
  manifests/a/AndreWiethoff/ExactAudioCopy/1.6/AndreWiethoff.ExactAudioCopy.installer.yaml
  manifests/a/AndreWiethoff/ExactAudioCopy/1.6/AndreWiethoff.ExactAudioCopy.locale.en-US.yaml
  manifests/a/AndreWiethoff/ExactAudioCopy/1.6/AndreWiethoff.ExactAudioCopy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108581 New version: nektos.act version 0.2.46
  manifests/n/nektos/act/0.2.46/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.46/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.46/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108600 New version: YuzuEmu.Yuzu.Mainline version 1453
  manifests/y/YuzuEmu/Yuzu/Mainline/1453/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1453/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1453/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108591 New version: Pylogmon.pot version 0.5.0
  manifests/p/Pylogmon/pot/0.5.0/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/0.5.0/Pylogmon.pot.locale.zh-CN.yaml
  manifests/p/Pylogmon/pot/0.5.0/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108606 New version: StandardNotes.StandardNotes version 3.160.16
  manifests/s/StandardNotes/StandardNotes/3.160.16/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.16/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.16/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108609 New version: StandardNotes.StandardNotes version 3.160.19
  manifests/s/StandardNotes/StandardNotes/3.160.19/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.19/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.19/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108607 New version: StandardNotes.StandardNotes version 3.160.17
  manifests/s/StandardNotes/StandardNotes/3.160.17/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.17/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.17/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108610 Fix Upgrade Behavior for Splashtop.SplashtopStreamer.Deployment.MSI 3.5.8.0
  manifests/s/Splashtop/SplashtopStreamer/Deployment/MSI/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.MSI.installer.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/MSI/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.MSI.locale.en-US.yaml
  manifests/s/Splashtop/SplashtopStreamer/Deployment/MSI/3.5.8.0/Splashtop.SplashtopStreamer.Deployment.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108601 New version: Google.AndroidStudio.Beta version 2022.3.1.15
  manifests/g/Google/AndroidStudio/Beta/2022.3.1.15/Google.AndroidStudio.Beta.installer.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.3.1.15/Google.AndroidStudio.Beta.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Beta/2022.3.1.15/Google.AndroidStudio.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108604 New version: Google.AndroidStudio version 2022.2.1.19
  manifests/g/Google/AndroidStudio/2022.2.1.19/Google.AndroidStudio.installer.yaml
  manifests/g/Google/AndroidStudio/2022.2.1.19/Google.AndroidStudio.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/2022.2.1.19/Google.AndroidStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108608 New version: StandardNotes.StandardNotes version 3.160.18
  manifests/s/StandardNotes/StandardNotes/3.160.18/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.18/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.160.18/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108602 New version: Google.AndroidStudio.Canary version 2023.1.1.5
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.5/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.5/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.5/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108603 New version: Google.AndroidStudio.Canary version 2023.1.1.6
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.6/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.6/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2023.1.1.6/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108599 New version: YuzuEmu.Yuzu.Mainline version 1452
  manifests/y/YuzuEmu/Yuzu/Mainline/1452/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1452/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1452/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108632 Fix Moniker for Youdao.YoudaoDict 10.0.3.0
  manifests/y/Youdao/YoudaoDict/10.0.3.0/Youdao.YoudaoDict.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108493 Update Asus.ArmouryCrate
  manifests/a/Asus/ArmouryCrate/5.6.3.0/Asus.ArmouryCrate.installer.yaml
  manifests/a/Asus/ArmouryCrate/5.6.3.0/Asus.ArmouryCrate.locale.en-US.yaml
  manifests/a/Asus/ArmouryCrate/5.6.3.0/Asus.ArmouryCrate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108319 add Zheguisoft.zg_print new version:6.2.0.5
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.installer.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.locale.en-US.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.locale.zh-CN.yaml
  manifests/z/Zheguisoft/zg_print/6.2.0.5/Zheguisoft.zg_print.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Policy-Test-1.2

#108129 adjust version: Parsec 150 87c
  manifests/p/Parsec/Parsec/150-87c/Parsec.Parsec.installer.yaml
  manifests/p/Parsec/Parsec/150-87c/Parsec.Parsec.locale.en-US.yaml
  manifests/p/Parsec/Parsec/150-87c/Parsec.Parsec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108547 Separate WindowsSDK into Versioned Packages (17763)
  manifests/m/Microsoft/WindowsSDK/10/0/17763/10.0.17736.0/Microsoft.WindowsSDK.10.0.17763.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/17763/10.0.17736.0/Microsoft.WindowsSDK.10.0.17763.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/17763/10.0.17736.0/Microsoft.WindowsSDK.10.0.17763.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108549 Separate WindowsSDK into Versioned Packages (19041)
  manifests/m/Microsoft/WindowsSDK/10/0/19041/10.0.19041.685/Microsoft.WindowsSDK.10.0.19041.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/19041/10.0.19041.685/Microsoft.WindowsSDK.10.0.19041.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/19041/10.0.19041.685/Microsoft.WindowsSDK.10.0.19041.yaml
Labels: Validation-Completed, Retry-1

#108548 Separate WindowsSDK into Versioned Packages (18362)
  manifests/m/Microsoft/WindowsSDK/10/0/18362/10.0.18362.0/Microsoft.WindowsSDK.10.0.18362.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/18362/10.0.18362.0/Microsoft.WindowsSDK.10.0.18362.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/18362/10.0.18362.0/Microsoft.WindowsSDK.10.0.18362.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108551 Separate WindowsSDK into Versioned Packages (22000)
  manifests/m/Microsoft/WindowsSDK/10/0/22000/10.0.22000.832/Microsoft.WindowsSDK.10.0.22000.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22000/10.0.22000.832/Microsoft.WindowsSDK.10.0.22000.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22000/10.0.22000.832/Microsoft.WindowsSDK.10.0.22000.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108553 Separate WindowsSDK into Versioned Packages (22621)
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.installer.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.locale.en-US.yaml
  manifests/m/Microsoft/WindowsSDK/10/0/22621/10.0.22621.2/Microsoft.WindowsSDK.10.0.22621.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108572 New version: Serverless.Serverless version 3.32.0
  manifests/s/Serverless/Serverless/3.32.0/Serverless.Serverless.installer.yaml
  manifests/s/Serverless/Serverless/3.32.0/Serverless.Serverless.locale.en-US.yaml
  manifests/s/Serverless/Serverless/3.32.0/Serverless.Serverless.locale.zh-CN.yaml
  manifests/s/Serverless/Serverless/3.32.0/Serverless.Serverless.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108578 ShiningLight.OpenSSL version 3.0.9
  manifests/s/ShiningLight/OpenSSL/3.0.9/ShiningLight.OpenSSL.installer.yaml
  manifests/s/ShiningLight/OpenSSL/3.0.9/ShiningLight.OpenSSL.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/3.0.9/ShiningLight.OpenSSL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108593 Remove: IPIP.BestTrace version 3.9.1
  manifests/i/IPIP/BestTrace/3.9.1/IPIP.BestTrace.installer.yaml
  manifests/i/IPIP/BestTrace/3.9.1/IPIP.BestTrace.locale.en-US.yaml
  manifests/i/IPIP/BestTrace/3.9.1/IPIP.BestTrace.locale.zh-CN.yaml
  manifests/i/IPIP/BestTrace/3.9.1/IPIP.BestTrace.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108598 Update Rufus.Rufus to 4.1
  manifests/r/Rufus/Rufus/4.1/Rufus.Rufus.installer.yaml
  manifests/r/Rufus/Rufus/4.1/Rufus.Rufus.locale.en-US.yaml
  manifests/r/Rufus/Rufus/4.1/Rufus.Rufus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#108614 Added AWS Command Line Interface version 2.11.24.
  manifests/a/Amazon/AWSCLI/2.11.24/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.11.24/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.11.24/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108615 Added GitHub CLI version 2.30.0.
  manifests/g/GitHub/cli/2.30.0/GitHub.cli.installer.yaml
  manifests/g/GitHub/cli/2.30.0/GitHub.cli.locale.en-US.yaml
  manifests/g/GitHub/cli/2.30.0/GitHub.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108617 Added Microsoft Edge Dev version 115.0.1880.1.
  manifests/m/Microsoft/Edge/Dev/115.0.1880.1/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/115.0.1880.1/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/115.0.1880.1/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108618 Updated Google Chrome Beta to version 115.0.5790.13.
  manifests/g/Google/Chrome/Beta/115.0.5790.13/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/115.0.5790.13/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/115.0.5790.13/Google.Chrome.Beta.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Beta/115.0.5790.13/Google.Chrome.Beta.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Beta/115.0.5790.13/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108621 ElectronicArts.EADesktop version 12.198.0.5455
  manifests/e/ElectronicArts/EADesktop/12.198.0.5455/ElectronicArts.EADesktop.installer.yaml
  manifests/e/ElectronicArts/EADesktop/12.198.0.5455/ElectronicArts.EADesktop.locale.en-US.yaml
  manifests/e/ElectronicArts/EADesktop/12.198.0.5455/ElectronicArts.EADesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108583 UWSCR 0.11.2
  manifests/s/stuncloud/uwscr/0.11.2/stuncloud.uwscr.installer.yaml
  manifests/s/stuncloud/uwscr/0.11.2/stuncloud.uwscr.locale.ja-JP.yaml
  manifests/s/stuncloud/uwscr/0.11.2/stuncloud.uwscr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108587 sandreas.tone version 0.1.5
  manifests/s/sandreas/tone/0.1.5/sandreas.tone.installer.yaml
  manifests/s/sandreas/tone/0.1.5/sandreas.tone.locale.en-US.yaml
  manifests/s/sandreas/tone/0.1.5/sandreas.tone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#108588 cyanreg.cyanrip version 0.9.0
  manifests/c/cyanreg/cyanrip/0.9.0/cyanreg.cyanrip.installer.yaml
  manifests/c/cyanreg/cyanrip/0.9.0/cyanreg.cyanrip.locale.en-US.yaml
  manifests/c/cyanreg/cyanrip/0.9.0/cyanreg.cyanrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108596 New package: Jaeger
  manifests/j/jaegertracing/jaeger/1.45/jaegertracing.jaeger.installer.yaml
  manifests/j/jaegertracing/jaeger/1.45/jaegertracing.jaeger.locale.en-US.yaml
  manifests/j/jaegertracing/jaeger/1.45/jaegertracing.jaeger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108605 CleverFiles.DiskDrill5.2.817.0 version 5.2.817.0
  manifests/c/CleverFiles/DiskDrill5/2/817/0/5.2.817.0/CleverFiles.DiskDrill5.2.817.0.installer.yaml
  manifests/c/CleverFiles/DiskDrill5/2/817/0/5.2.817.0/CleverFiles.DiskDrill5.2.817.0.locale.en-US.yaml
  manifests/c/CleverFiles/DiskDrill5/2/817/0/5.2.817.0/CleverFiles.DiskDrill5.2.817.0.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108657 OpenBB-finance.OpenBBTerminal version 3.0.1
  manifests/o/OpenBB-finance/OpenBBTerminal/3.0.1/OpenBB-finance.OpenBBTerminal.installer.yaml
  manifests/o/OpenBB-finance/OpenBBTerminal/3.0.1/OpenBB-finance.OpenBBTerminal.locale.en-US.yaml
  manifests/o/OpenBB-finance/OpenBBTerminal/3.0.1/OpenBB-finance.OpenBBTerminal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108653 PsiphonInc.Psiphon version 179.20230601074002
  manifests/p/PsiphonInc/Psiphon/179.20230601074002/PsiphonInc.Psiphon.installer.yaml
  manifests/p/PsiphonInc/Psiphon/179.20230601074002/PsiphonInc.Psiphon.locale.en-US.yaml
  manifests/p/PsiphonInc/Psiphon/179.20230601074002/PsiphonInc.Psiphon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108647 Orange-OpenSource.Hurl version 3.0.1
  manifests/o/Orange-OpenSource/Hurl/3.0.1/Orange-OpenSource.Hurl.installer.yaml
  manifests/o/Orange-OpenSource/Hurl/3.0.1/Orange-OpenSource.Hurl.locale.en-US.yaml
  manifests/o/Orange-OpenSource/Hurl/3.0.1/Orange-OpenSource.Hurl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108648 Add Stoplight.Prism 5.0.1
  manifests/s/Stoplight/Prism/5.0.1/Stoplight.Prism.installer.yaml
  manifests/s/Stoplight/Prism/5.0.1/Stoplight.Prism.locale.en-US.yaml
  manifests/s/Stoplight/Prism/5.0.1/Stoplight.Prism.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108650 Add Bitwarden CLI 2023.5.0
  manifests/b/Bitwarden/CLI/2023.5.0/Bitwarden.CLI.installer.yaml
  manifests/b/Bitwarden/CLI/2023.5.0/Bitwarden.CLI.locale.en-US.yaml
  manifests/b/Bitwarden/CLI/2023.5.0/Bitwarden.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108646 New version: univrsal.tuna version 1.9.6
  manifests/u/univrsal/tuna/1.9.6/univrsal.tuna.installer.yaml
  manifests/u/univrsal/tuna/1.9.6/univrsal.tuna.locale.en-US.yaml
  manifests/u/univrsal/tuna/1.9.6/univrsal.tuna.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108643 Add version: univrsal.input-overlay version 5.0.3
  manifests/u/univrsal/input-overlay/5.0.3/univrsal.input-overlay.installer.yaml
  manifests/u/univrsal/input-overlay/5.0.3/univrsal.input-overlay.locale.en-US.yaml
  manifests/u/univrsal/input-overlay/5.0.3/univrsal.input-overlay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108642 New version: univrsal.input-overlay version 5.0.4
  manifests/u/univrsal/input-overlay/5.0.4/univrsal.input-overlay.installer.yaml
  manifests/u/univrsal/input-overlay/5.0.4/univrsal.input-overlay.locale.en-US.yaml
  manifests/u/univrsal/input-overlay/5.0.4/univrsal.input-overlay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108641 New version: univrsal.scrab version 1.2.0
  manifests/u/univrsal/scrab/1.2.0/univrsal.scrab.installer.yaml
  manifests/u/univrsal/scrab/1.2.0/univrsal.scrab.locale.en-US.yaml
  manifests/u/univrsal/scrab/1.2.0/univrsal.scrab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108640 Update: univrsal.scrab version 1.1
  manifests/u/univrsal/scrab/1.1/univrsal.scrab.installer.yaml
  manifests/u/univrsal/scrab/1.1/univrsal.scrab.locale.en-US.yaml
  manifests/u/univrsal/scrab/1.1/univrsal.scrab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108637 Update: ThomasJames.Tajpi version 2.98
  manifests/t/ThomasJames/Tajpi/2.98/ThomasJames.Tajpi.installer.yaml
  manifests/t/ThomasJames/Tajpi/2.98/ThomasJames.Tajpi.locale.en-US.yaml
  manifests/t/ThomasJames/Tajpi/2.98/ThomasJames.Tajpi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108625 New version: Google.AndroidStudio version 2022.2.1.20
  manifests/g/Google/AndroidStudio/2022.2.1.20/Google.AndroidStudio.installer.yaml
  manifests/g/Google/AndroidStudio/2022.2.1.20/Google.AndroidStudio.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/2022.2.1.20/Google.AndroidStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108628 Update: BelgianGovernment.eIDViewer version 5.1.6019
  manifests/b/BelgianGovernment/eIDViewer/5.1.6019/BelgianGovernment.eIDViewer.installer.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.6019/BelgianGovernment.eIDViewer.locale.en-US.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.6019/BelgianGovernment.eIDViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108629 Update: BelgianGovernment.eIDViewer version 5.1.5998
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.installer.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.locale.en-US.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5998/BelgianGovernment.eIDViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108630 Update: BelgianGovernment.eIDViewer version 5.1.5886
  manifests/b/BelgianGovernment/eIDViewer/5.1.5886/BelgianGovernment.eIDViewer.installer.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5886/BelgianGovernment.eIDViewer.locale.nl-BE.yaml
  manifests/b/BelgianGovernment/eIDViewer/5.1.5886/BelgianGovernment.eIDViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108631 Update: Youdao.YoudaoDict version 8.10.4.0
  manifests/y/Youdao/YoudaoDict/8.10.4.0/Youdao.YoudaoDict.installer.yaml
  manifests/y/Youdao/YoudaoDict/8.10.4.0/Youdao.YoudaoDict.locale.en-US.yaml
  manifests/y/Youdao/YoudaoDict/8.10.4.0/Youdao.YoudaoDict.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108669 Microsoft.VisualStudioCode.Insiders_v1.79.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.79.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108636 New package: Microsoft.SQLServer.2017.Developer version 14.0.1000.169
  manifests/m/Microsoft/SQLServer/2017/Developer/14.0.1000.169/Microsoft.SQLServer.2017.Developer.installer.yaml
  manifests/m/Microsoft/SQLServer/2017/Developer/14.0.1000.169/Microsoft.SQLServer.2017.Developer.locale.en-US.yaml
  manifests/m/Microsoft/SQLServer/2017/Developer/14.0.1000.169/Microsoft.SQLServer.2017.Developer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#108526 New version CrystalDewWorld.CrystalDiskInfo version 9.0.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.0.1/CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.0.1/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.0.1/CrystalDewWorld.CrystalDiskInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108622 Bitwarden.Bitwarden version 2023.5.0
  manifests/b/Bitwarden/Bitwarden/2023.5.0/Bitwarden.Bitwarden.installer.yaml
  manifests/b/Bitwarden/Bitwarden/2023.5.0/Bitwarden.Bitwarden.locale.en-US.yaml
  manifests/b/Bitwarden/Bitwarden/2023.5.0/Bitwarden.Bitwarden.locale.zh-CN.yaml
  manifests/b/Bitwarden/Bitwarden/2023.5.0/Bitwarden.Bitwarden.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108623 New version voidtools.Everything.Alpha version 1.5.0.1349a
  manifests/v/voidtools/Everything/Alpha/1.5.0.1349a/voidtools.Everything.Alpha.installer.yaml
  manifests/v/voidtools/Everything/Alpha/1.5.0.1349a/voidtools.Everything.Alpha.locale.en-US.yaml
  manifests/v/voidtools/Everything/Alpha/1.5.0.1349a/voidtools.Everything.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108645 Add version: univrsal.input-overlay version 5.0.1
  manifests/u/univrsal/input-overlay/5.0.1/univrsal.input-overlay.installer.yaml
  manifests/u/univrsal/input-overlay/5.0.1/univrsal.input-overlay.locale.en-US.yaml
  manifests/u/univrsal/input-overlay/5.0.1/univrsal.input-overlay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108666 the-sz.Lacey version 2.86
  manifests/t/the-sz/Lacey/2.86/the-sz.Lacey.installer.yaml
  manifests/t/the-sz/Lacey/2.86/the-sz.Lacey.locale.en-US.yaml
  manifests/t/the-sz/Lacey/2.86/the-sz.Lacey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108670 DoltHub.Dolt version 1.2.3
  manifests/d/DoltHub/Dolt/1.2.3/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.2.3/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.2.3/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108671 SmartSoft.SmartFTP version 10.0.3118.0
  manifests/s/SmartSoft/SmartFTP/10.0.3118.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3118.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3118.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108624 Slonopotamus.Stevedore version 0.16.0
  manifests/s/Slonopotamus/Stevedore/0.16.0/Slonopotamus.Stevedore.installer.yaml
  manifests/s/Slonopotamus/Stevedore/0.16.0/Slonopotamus.Stevedore.locale.en-US.yaml
  manifests/s/Slonopotamus/Stevedore/0.16.0/Slonopotamus.Stevedore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108672 New version: Panic.PlaydateSDK version 2.0.0-beta.4
  manifests/p/Panic/PlaydateSDK/2.0.0-beta.4/Panic.PlaydateSDK.installer.yaml
  manifests/p/Panic/PlaydateSDK/2.0.0-beta.4/Panic.PlaydateSDK.locale.en-US.yaml
  manifests/p/Panic/PlaydateSDK/2.0.0-beta.4/Panic.PlaydateSDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#108652 Add Obsidian.Obsidian 1.3.5
  manifests/o/Obsidian/Obsidian/1.3.5/Obsidian.Obsidian.installer.yaml
  manifests/o/Obsidian/Obsidian/1.3.5/Obsidian.Obsidian.locale.en-US.yaml
  manifests/o/Obsidian/Obsidian/1.3.5/Obsidian.Obsidian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108662 Submitting ART version 1.20.0
  manifests/a/ART/ART/1.20.0.0/ART.ART.installer.yaml
  manifests/a/ART/ART/1.20.0.0/ART.ART.locale.en-US.yaml
  manifests/a/ART/ART/1.20.0.0/ART.ART.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-2.3, Waived-Validation-Domain

#108655 Add fossa cli 3.8.0.
  manifests/f/FOSSA/FOSSA-cli/3.8.0/FOSSA.FOSSA-cli.installer.yaml
  manifests/f/FOSSA/FOSSA-cli/3.8.0/FOSSA.FOSSA-cli.locale.en-US.yaml
  manifests/f/FOSSA/FOSSA-cli/3.8.0/FOSSA.FOSSA-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#108708 Microsoft.VisualStudioCode.Insiders_v1.79.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.79.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108739 Update version: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108724 Update Dependencies for Swift.Toolchain
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.8.0/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108740 New version: Jackett.Jackett version 0.21.97
  manifests/j/Jackett/Jackett/0.21.97/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.97/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.97/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108745 Microsoft.VisualStudioCode.Insiders_v1.79.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.79.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108728 Update Dependencies for Swift.Toolchain
  manifests/s/Swift/Toolchain/5.4.2/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.4.2/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.4.2/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108725 Update Dependencies for Swift.Toolchain
  manifests/s/Swift/Toolchain/5.7.3/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.7.3/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.7.3/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108726 Update Dependencies for Swift.Toolchain
  manifests/s/Swift/Toolchain/5.6.1/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.6.1/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.6.1/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108727 Update Dependencies for Swift.Toolchain
  manifests/s/Swift/Toolchain/5.5/Swift.Toolchain.installer.yaml
  manifests/s/Swift/Toolchain/5.5/Swift.Toolchain.locale.en-US.yaml
  manifests/s/Swift/Toolchain/5.5/Swift.Toolchain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108749 Microsoft.VisualStudioCode.Insiders_v1.79.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.79.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108737 7zip.7zip: Added `/S` silent mode switch only for exe installers (#108155)
  manifests/7/7zip/7zip/22.01/7zip.7zip.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108592 Metadata: MSYS2.MSYS2 version 20230318
  manifests/m/MSYS2/MSYS2/20230318/MSYS2.MSYS2.locale.en-US.yaml
  manifests/m/MSYS2/MSYS2/20230318/MSYS2.MSYS2.locale.zh-CN.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108659 Microsoft.PowerToys version 0.70.1
  manifests/m/Microsoft/PowerToys/0.70.1/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.70.1/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.70.1/Microsoft.PowerToys.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108409 Add Tencent.WeType version 0.9.0.69
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.0.69/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108778 New version: VSCodium.VSCodium.Insiders version 1.79.0.23152
  manifests/v/VSCodium/VSCodium/Insiders/1.79.0.23152/VSCodium.VSCodium.Insiders.installer.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.79.0.23152/VSCodium.VSCodium.Insiders.locale.en-US.yaml
  manifests/v/VSCodium/VSCodium/Insiders/1.79.0.23152/VSCodium.VSCodium.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108779 New version: ElijahLopez.MusicCaster version 5.13.24
  manifests/e/ElijahLopez/MusicCaster/5.13.24/ElijahLopez.MusicCaster.installer.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.24/ElijahLopez.MusicCaster.locale.en-US.yaml
  manifests/e/ElijahLopez/MusicCaster/5.13.24/ElijahLopez.MusicCaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108721 Ferdium.Ferdium.Nightly version 6.3.0-nightly.17
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.17/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.17/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.3.0-nightly.17/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108716 New version: GDevelop.GDevelop version 5.1.164
  manifests/g/GDevelop/GDevelop/5.1.164/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.1.164/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.1.164/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108696 New version: Brave.Brave.Beta version 114.1.53.76
  manifests/b/Brave/Brave/Beta/114.1.53.76/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/114.1.53.76/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/114.1.53.76/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/114.1.53.76/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108684 New version: Kingsoft.KDocs version 3.8.6
  manifests/k/Kingsoft/KDocs/3.8.6/Kingsoft.KDocs.installer.yaml
  manifests/k/Kingsoft/KDocs/3.8.6/Kingsoft.KDocs.locale.en-US.yaml
  manifests/k/Kingsoft/KDocs/3.8.6/Kingsoft.KDocs.locale.zh-CN.yaml
  manifests/k/Kingsoft/KDocs/3.8.6/Kingsoft.KDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108683 New version: PortSwigger.BurpSuite.Community version 2023.5.2
  manifests/p/PortSwigger/BurpSuite/Community/2023.5.2/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.5.2/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.5.2/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2023.5.2/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108619 Mozilla.Firefox 113.0.2: add Tamil installer, update manifest
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.installer.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/113.0.2/Mozilla.Firefox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#108635 Update: Microsoft.AzureCLI version 2.41.0
  manifests/m/Microsoft/AzureCLI/2.41.0/Microsoft.AzureCLI.installer.yaml
  manifests/m/Microsoft/AzureCLI/2.41.0/Microsoft.AzureCLI.locale.en-US.yaml
  manifests/m/Microsoft/AzureCLI/2.41.0/Microsoft.AzureCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108638 Update: TikzEdt.TikzEdtBeta version 0.2.3
  manifests/t/TikzEdt/TikzEdtBeta/0.2.3/TikzEdt.TikzEdtBeta.installer.yaml
  manifests/t/TikzEdt/TikzEdtBeta/0.2.3/TikzEdt.TikzEdtBeta.locale.en-US.yaml
  manifests/t/TikzEdt/TikzEdtBeta/0.2.3/TikzEdt.TikzEdtBeta.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#108709 New version: HeroicGamesLauncher.HeroicGamesLauncher version 2.8.0
  manifests/h/HeroicGamesLauncher/HeroicGamesLauncher/2.8.0/HeroicGamesLauncher.HeroicGamesLauncher.installer.yaml
  manifests/h/HeroicGamesLauncher/HeroicGamesLauncher/2.8.0/HeroicGamesLauncher.HeroicGamesLauncher.locale.en-US.yaml
  manifests/h/HeroicGamesLauncher/HeroicGamesLauncher/2.8.0/HeroicGamesLauncher.HeroicGamesLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108714 New version: Genymobile.Genymotion version 3.4.0
  manifests/g/Genymobile/Genymotion/3.4.0/Genymobile.Genymotion.installer.yaml
  manifests/g/Genymobile/Genymotion/3.4.0/Genymobile.Genymotion.locale.en-US.yaml
  manifests/g/Genymobile/Genymotion/3.4.0/Genymobile.Genymotion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108717 New version: Gather.Gather version 0.7.7
  manifests/g/Gather/Gather/0.7.7/Gather.Gather.installer.yaml
  manifests/g/Gather/Gather/0.7.7/Gather.Gather.locale.en-US.yaml
  manifests/g/Gather/Gather/0.7.7/Gather.Gather.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108718 New version: Gajim.Gajim version 1.8.0
  manifests/g/Gajim/Gajim/1.8.0/Gajim.Gajim.installer.yaml
  manifests/g/Gajim/Gajim/1.8.0/Gajim.Gajim.locale.en-US.yaml
  manifests/g/Gajim/Gajim/1.8.0/Gajim.Gajim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108720 New version: Fly-io.flyctl version 0.1.24
  manifests/f/Fly-io/flyctl/0.1.24/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.1.24/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.1.24/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#108735 New version: dail8859.NotepadNext version 0.6.3
  manifests/d/dail8859/NotepadNext/0.6.3/dail8859.NotepadNext.installer.yaml
  manifests/d/dail8859/NotepadNext/0.6.3/dail8859.NotepadNext.locale.en-US.yaml
  manifests/d/dail8859/NotepadNext/0.6.3/dail8859.NotepadNext.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
