Repository microsoft/winget-pkgs, pull requests merged in 2023-02, with the labels that each got.

#94750 New package: Spicetify.Spicetify version 2.16.0
  manifests/s/Spicetify/Spicetify/2.16.0/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.16.0/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.16.0/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Retry-1

#95153 New version: Alist.Alist version 3.9.2
  manifests/a/Alist/Alist/3.9.2/Alist.Alist.installer.yaml
  manifests/a/Alist/Alist/3.9.2/Alist.Alist.locale.en-US.yaml
  manifests/a/Alist/Alist/3.9.2/Alist.Alist.locale.zh-CN.yaml
  manifests/a/Alist/Alist/3.9.2/Alist.Alist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#95152 New package: Nefarius.nefcon version 1.7.2
  manifests/n/Nefarius/nefcon/1.7.2/Nefarius.nefcon.installer.yaml
  manifests/n/Nefarius/nefcon/1.7.2/Nefarius.nefcon.locale.en-US.yaml
  manifests/n/Nefarius/nefcon/1.7.2/Nefarius.nefcon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95255 fix spelling/typos [docs]
  doc/manifest/schema/1.4.0/installer.md
Labels: Project-File

#76760 Make Multi-line Field Exclude ending Newline
  manifests/b/Baidu/SwanIDE/3.49.1/Baidu.SwanIDE.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95127 New version: Facebook.Messenger version 176.0.442527159
  manifests/f/Facebook/Messenger/176.0.442527159/Facebook.Messenger.installer.yaml
  manifests/f/Facebook/Messenger/176.0.442527159/Facebook.Messenger.locale.en-US.yaml
  manifests/f/Facebook/Messenger/176.0.442527159/Facebook.Messenger.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#72538 Update ByteDance.BytedanceMiniappIDE 3.1.6
  manifests/b/ByteDance/BytedanceMiniappIDE/3.1.6/ByteDance.BytedanceMiniappIDE.installer.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.1.6/ByteDance.BytedanceMiniappIDE.locale.en-US.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.1.6/ByteDance.BytedanceMiniappIDE.locale.zh-CN.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.1.6/ByteDance.BytedanceMiniappIDE.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#94753 New package: rhysd.actionlint version 1.6.23
  manifests/r/rhysd/actionlint/1.6.23/rhysd.actionlint.installer.yaml
  manifests/r/rhysd/actionlint/1.6.23/rhysd.actionlint.locale.en-US.yaml
  manifests/r/rhysd/actionlint/1.6.23/rhysd.actionlint.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies

#95013 New package: asciinema.agg version 1.3.0
  manifests/a/asciinema/agg/1.3.0/asciinema.agg.installer.yaml
  manifests/a/asciinema/agg/1.3.0/asciinema.agg.locale.en-US.yaml
  manifests/a/asciinema/agg/1.3.0/asciinema.agg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95020 New version: yelosan.PH-UKL.HanoQRTY version 1.0.3.40
  manifests/y/yelosan/PH-UKL/HanoQRTY/1.0.3.40/yelosan.PH-UKL.HanoQRTY.installer.yaml
  manifests/y/yelosan/PH-UKL/HanoQRTY/1.0.3.40/yelosan.PH-UKL.HanoQRTY.locale.en-US.yaml
  manifests/y/yelosan/PH-UKL/HanoQRTY/1.0.3.40/yelosan.PH-UKL.HanoQRTY.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate

#94791 New package: dandavison.delta version 0.15.1
  manifests/d/dandavison/delta/0.15.1/dandavison.delta.installer.yaml
  manifests/d/dandavison/delta/0.15.1/dandavison.delta.locale.en-US.yaml
  manifests/d/dandavison/delta/0.15.1/dandavison.delta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Moderator-Approved

#76757 Make Multi-line Field Exclude ending Newline
  manifests/b/Baidu/BaiduTranslate/1.4.0/Baidu.BaiduTranslate.locale.zh-CN.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#77000 Make Multi-line Field Exclude ending Newline
  manifests/h/Hellofont/Hellofont/3.0.2/Hellofont.Hellofont.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#77619 Make Multi-line Field Exclude ending Newline
  manifests/t/TTKN/CNKIExpress/0.1.16/TTKN.CNKIExpress.locale.zh-CN.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#77652 Make Multi-line Field Exclude ending Newline
  manifests/t/TTKN/CNKIExpress/0.1.19/TTKN.CNKIExpress.locale.zh-CN.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#83441 New version: TTKN.CNKIExpress version 0.2.29 [FP-O]
  manifests/t/TTKN/CNKIExpress/0.2.29/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.29/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.29/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.29/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#87359 New version: TTKN.CNKIExpress version 0.2.30 [FP-D]
  manifests/t/TTKN/CNKIExpress/0.2.30/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.30/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.30/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.30/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#87864 New version: Hellofont.Hellofont version 3.0.5
  manifests/h/Hellofont/Hellofont/3.0.5/Hellofont.Hellofont.installer.yaml
  manifests/h/Hellofont/Hellofont/3.0.5/Hellofont.Hellofont.locale.en-US.yaml
  manifests/h/Hellofont/Hellofont/3.0.5/Hellofont.Hellofont.locale.zh-CN.yaml
  manifests/h/Hellofont/Hellofont/3.0.5/Hellofont.Hellofont.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved

#87891 [Zip][Portable] New package: Alibaba.AlibabaCloudCLI version 3.0.134
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.134/Alibaba.AlibabaCloudCLI.installer.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.134/Alibaba.AlibabaCloudCLI.locale.en-US.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.134/Alibaba.AlibabaCloudCLI.locale.zh-CN.yaml
  manifests/a/Alibaba/AlibabaCloudCLI/3.0.134/Alibaba.AlibabaCloudCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Moderator-Approved

#94693 Add version: Baidu.SwanIDE version 4.10.1
  manifests/b/Baidu/SwanIDE/4.10.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.10.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.10.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.10.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved

#95106 PTRTECH.UVtools version 3.11.1
  manifests/p/PTRTECH/UVtools/3.11.1/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.11.1/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.11.1/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error, Retry-1, Moderator-Approved

#95126 Update: KDE.Okular version 22.12.1 [FP-O]
  manifests/k/KDE/Okular/22.12.1/KDE.Okular.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved

#95133 New version: Google.Chrome.Canary version 112.0.5572.0 [FP-O]
  manifests/g/Google/Chrome/Canary/112.0.5572.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/112.0.5572.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/112.0.5572.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/112.0.5572.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Moderator-Approved

#95310 Remove: ByteDance.BytedanceMiniappIDE waiver
  manifests/b/ByteDance/BytedanceMiniappIDE/.validation
Labels: Validation-Completed, Author-Not-Authorized

#71174 Update: Tencent.qq-devtool version 0.3.1
  manifests/t/Tencent/qq-devtool/0.3.1/Tencent.qq-devtool.installer.yaml
  manifests/t/Tencent/qq-devtool/0.3.1/Tencent.qq-devtool.locale.en-US.yaml
  manifests/t/Tencent/qq-devtool/0.3.1/Tencent.qq-devtool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#87327 [Zip][Portable] New package: Gyan.FFmpeg version 5.1.2
  manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.installer.yaml
  manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/5.1.2/Gyan.FFmpeg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Waived-Validation-Executable-Error

#95165 New version: JetBrains.WebStorm version 2022.3.2
  manifests/j/JetBrains/WebStorm/2022.3.2/JetBrains.WebStorm.installer.yaml
  manifests/j/JetBrains/WebStorm/2022.3.2/JetBrains.WebStorm.locale.en-US.yaml
  manifests/j/JetBrains/WebStorm/2022.3.2/JetBrains.WebStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95168 New version: Notepad++.Notepad++ version 8.4.9
  manifests/n/Notepad++/Notepad++/8.4.9/Notepad++.Notepad++.installer.yaml
  manifests/n/Notepad++/Notepad++/8.4.9/Notepad++.Notepad++.locale.en-US.yaml
  manifests/n/Notepad++/Notepad++/8.4.9/Notepad++.Notepad++.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95169 Devolutions.RemoteDesktopManager version 2022.3.32.0
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.32.0/Devolutions.RemoteDesktopManager.installer.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.32.0/Devolutions.RemoteDesktopManager.locale.en-US.yaml
  manifests/d/Devolutions/RemoteDesktopManager/2022.3.32.0/Devolutions.RemoteDesktopManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95171 Momento.cli version 0.28.1
  manifests/m/Momento/cli/0.28.1/Momento.cli.installer.yaml
  manifests/m/Momento/cli/0.28.1/Momento.cli.locale.en-US.yaml
  manifests/m/Momento/cli/0.28.1/Momento.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95173 Add Scope: Machine to PowerShell 7.2.8.0 installer manifest
  manifests/m/Microsoft/PowerShell/7.2.8.0/Microsoft.PowerShell.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, PullRequest-Error, Internal-Error-Dynamic-Scan

#95187 Specify Scope: machine to powershell 7.3.101.0 installer manifest
  manifests/m/Microsoft/PowerShell/Preview/7.3.101.0/Microsoft.PowerShell.Preview.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95189 Momento.cli version 0.28.2
  manifests/m/Momento/cli/0.28.2/Momento.cli.installer.yaml
  manifests/m/Momento/cli/0.28.2/Momento.cli.locale.en-US.yaml
  manifests/m/Momento/cli/0.28.2/Momento.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95195 Remove: ranpha.LavFiltersMegamix 0.77.1.2
  manifests/r/ranpha/LavFiltersMegamix/0.77.1.2/ranpha.LavFiltersMegamix.installer.yaml
  manifests/r/ranpha/LavFiltersMegamix/0.77.1.2/ranpha.LavFiltersMegamix.locale.en-US.yaml
  manifests/r/ranpha/LavFiltersMegamix/0.77.1.2/ranpha.LavFiltersMegamix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95196 Remove: ranpha.LavFiltersMegamix 0.77.1-1
  manifests/r/ranpha/LavFiltersMegamix/0.77.1-1/ranpha.LavFiltersMegamix.installer.yaml
  manifests/r/ranpha/LavFiltersMegamix/0.77.1-1/ranpha.LavFiltersMegamix.locale.en-US.yaml
  manifests/r/ranpha/LavFiltersMegamix/0.77.1-1/ranpha.LavFiltersMegamix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95199 Nushell.Nushell version 0.75.0
  manifests/n/Nushell/Nushell/0.75.0/Nushell.Nushell.installer.yaml
  manifests/n/Nushell/Nushell/0.75.0/Nushell.Nushell.locale.en-US.yaml
  manifests/n/Nushell/Nushell/0.75.0/Nushell.Nushell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Shell-Execute

#95200 Momento.cli version 0.29.0
  manifests/m/Momento/cli/0.29.0/Momento.cli.installer.yaml
  manifests/m/Momento/cli/0.29.0/Momento.cli.locale.en-US.yaml
  manifests/m/Momento/cli/0.29.0/Momento.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95203 Delete the manifests for Visual Studio 2019 Community Preview
  manifests/m/Microsoft/VisualStudio/2019/Community-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Community-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2019/Community-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Community-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2019/Community-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Community-Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95204 Delete the manifests for Visual Studio 2019 Professional Preview
  manifests/m/Microsoft/VisualStudio/2019/Professional-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Professional-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2019/Professional-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Professional-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2019/Professional-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Professional-Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95205 Delete the manifests for Visual Studio 2019 Enterprise Preview
  manifests/m/Microsoft/VisualStudio/2019/Enterprise-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Enterprise-Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2019/Enterprise-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Enterprise-Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2019/Enterprise-Preview/16.11.0 Preview 3.0/Microsoft.VisualStudio.2019.Enterprise-Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95206 Delete the manifests for Visual Studio 2019 Community.
  manifests/m/Microsoft/VisualStudio/2019/Community/16.11.23/Microsoft.VisualStudio.2019.Community.installer.yaml
  manifests/m/Microsoft/VisualStudio/2019/Community/16.11.23/Microsoft.VisualStudio.2019.Community.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2019/Community/16.11.23/Microsoft.VisualStudio.2019.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95123 New version: Nvidia.GeForceNow version 2.0.48.108
  manifests/n/Nvidia/GeForceNow/2.0.48.108/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.48.108/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.48.108/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.48.108/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95128 New version: bloznelis.typioca version 2.0.8
  manifests/b/bloznelis/typioca/2.0.8/bloznelis.typioca.installer.yaml
  manifests/b/bloznelis/typioca/2.0.8/bloznelis.typioca.locale.en-US.yaml
  manifests/b/bloznelis/typioca/2.0.8/bloznelis.typioca.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#95138 New version: Element.Element version 1.11.22 [FP-O]
  manifests/e/Element/Element/1.11.22/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.22/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.22/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95139 New version: PDFsam.PDFsam version 5.0.2.0 [FP-O]
  manifests/p/PDFsam/PDFsam/5.0.2.0/PDFsam.PDFsam.installer.yaml
  manifests/p/PDFsam/PDFsam/5.0.2.0/PDFsam.PDFsam.locale.en-US.yaml
  manifests/p/PDFsam/PDFsam/5.0.2.0/PDFsam.PDFsam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95140 FarManager.FarManager version 3.0.6060
  manifests/f/FarManager/FarManager/3.0.6060/FarManager.FarManager.installer.yaml
  manifests/f/FarManager/FarManager/3.0.6060/FarManager.FarManager.locale.en-US.yaml
  manifests/f/FarManager/FarManager/3.0.6060/FarManager.FarManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95142 New package: Rclone.Rclone version 1.61.1
  manifests/r/Rclone/Rclone/1.61.1/Rclone.Rclone.installer.yaml
  manifests/r/Rclone/Rclone/1.61.1/Rclone.Rclone.locale.en-US.yaml
  manifests/r/Rclone/Rclone/1.61.1/Rclone.Rclone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Validation-Executable-Error, Waived-Validation-Executable-Error

#95144 ReleaseNotes: 115.115Chrome version 25.0.5.4
  manifests/1/115/115Chrome/25.0.5.4/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/25.0.5.4/115.115Chrome.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95146 ReleaseNotes: NetEase.MailMaster version 4.18.1.1006
  manifests/n/NetEase/MailMaster/4.18.1.1006/NetEase.MailMaster.installer.yaml
  manifests/n/NetEase/MailMaster/4.18.1.1006/NetEase.MailMaster.locale.en-US.yaml
  manifests/n/NetEase/MailMaster/4.18.1.1006/NetEase.MailMaster.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95147 New version: Xmind.Xmind version 22.11.3656
  manifests/x/Xmind/Xmind/22.11.3656/Xmind.Xmind.installer.yaml
  manifests/x/Xmind/Xmind/22.11.3656/Xmind.Xmind.locale.en-US.yaml
  manifests/x/Xmind/Xmind/22.11.3656/Xmind.Xmind.locale.zh-CN.yaml
  manifests/x/Xmind/Xmind/22.11.3656/Xmind.Xmind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95149 New version: SandroMani.gImageReader version 3.4.1
  manifests/s/SandroMani/gImageReader/3.4.1/SandroMani.gImageReader.installer.yaml
  manifests/s/SandroMani/gImageReader/3.4.1/SandroMani.gImageReader.locale.en-US.yaml
  manifests/s/SandroMani/gImageReader/3.4.1/SandroMani.gImageReader.locale.zh-CN.yaml
  manifests/s/SandroMani/gImageReader/3.4.1/SandroMani.gImageReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95151 Fix: YSTYLE.kaf-cli version 1.2.10
  manifests/y/YSTYLE/kaf-cli/1.2.10/YSTYLE.kaf-cli.installer.yaml
  manifests/y/YSTYLE/kaf-cli/1.2.10/YSTYLE.kaf-cli.locale.en-US.yaml
  manifests/y/YSTYLE/kaf-cli/1.2.10/YSTYLE.kaf-cli.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95156 Add version: LLVM.LLVM version 15.0.6
  manifests/l/LLVM/LLVM/15.0.6/LLVM.LLVM.installer.yaml
  manifests/l/LLVM/LLVM/15.0.6/LLVM.LLVM.locale.de-DE.yaml
  manifests/l/LLVM/LLVM/15.0.6/LLVM.LLVM.locale.en-US.yaml
  manifests/l/LLVM/LLVM/15.0.6/LLVM.LLVM.locale.zh-CN.yaml
  manifests/l/LLVM/LLVM/15.0.6/LLVM.LLVM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error, Internal-Error-Dynamic-Scan, Retry-1

#95157 DoltHub.Dolt version 0.52.16
  manifests/d/DoltHub/Dolt/0.52.16/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.52.16/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.52.16/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95160 Add version: Microsoft.PowerShell version 7.2.9.0
  manifests/m/Microsoft/PowerShell/7.2.9.0/Microsoft.PowerShell.installer.yaml
  manifests/m/Microsoft/PowerShell/7.2.9.0/Microsoft.PowerShell.locale.en-US.yaml
  manifests/m/Microsoft/PowerShell/7.2.9.0/Microsoft.PowerShell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95166 New version: JetBrains.YouTrack version 22.3.65369
  manifests/j/JetBrains/YouTrack/22.3.65369/JetBrains.YouTrack.installer.yaml
  manifests/j/JetBrains/YouTrack/22.3.65369/JetBrains.YouTrack.locale.en-US.yaml
  manifests/j/JetBrains/YouTrack/22.3.65369/JetBrains.YouTrack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95167 JanDeDobbeleer.OhMyPosh version 14.0.2
  manifests/j/JanDeDobbeleer/OhMyPosh/14.0.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.0.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/14.0.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95208 AzureDataStudios 1.41.1 winget manifests
  manifests/m/Microsoft/AzureDataStudio/1.41.1/Microsoft.AzureDataStudio.installer.yaml
  manifests/m/Microsoft/AzureDataStudio/1.41.1/Microsoft.AzureDataStudio.locale.en-US.yaml
  manifests/m/Microsoft/AzureDataStudio/1.41.1/Microsoft.AzureDataStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95212 New version: Taozuhong.Kangaroo version 2.3.1.230201
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95213 Add quick-lint-js version 2.11.0.0
  manifests/q/quick-lint/quick-lint-js/2.11.0.0/quick-lint.quick-lint-js.installer.yaml
  manifests/q/quick-lint/quick-lint-js/2.11.0.0/quick-lint.quick-lint-js.locale.en-US.yaml
  manifests/q/quick-lint/quick-lint-js/2.11.0.0/quick-lint.quick-lint-js.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95215 New version: pnpm.pnpm version 7.26.3
  manifests/p/pnpm/pnpm/7.26.3/pnpm.pnpm.installer.yaml
  manifests/p/pnpm/pnpm/7.26.3/pnpm.pnpm.locale.en-US.yaml
  manifests/p/pnpm/pnpm/7.26.3/pnpm.pnpm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95220 New version: altair-graphql.altair version 5.0.14
  manifests/a/altair-graphql/altair/5.0.14/altair-graphql.altair.installer.yaml
  manifests/a/altair-graphql/altair/5.0.14/altair-graphql.altair.locale.en-US.yaml
  manifests/a/altair-graphql/altair/5.0.14/altair-graphql.altair.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95224 New version: Glodon.CADReader.CN version 5.18.0.90
  manifests/g/Glodon/CADReader/CN/5.18.0.90/Glodon.CADReader.CN.installer.yaml
  manifests/g/Glodon/CADReader/CN/5.18.0.90/Glodon.CADReader.CN.locale.en-US.yaml
  manifests/g/Glodon/CADReader/CN/5.18.0.90/Glodon.CADReader.CN.locale.zh-CN.yaml
  manifests/g/Glodon/CADReader/CN/5.18.0.90/Glodon.CADReader.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95227 Update: KDE.Kdenlive version 22.12.1
  manifests/k/KDE/Kdenlive/22.12.1/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95229 New version: TTKN.CNKIExpress version 0.2.23
  manifests/t/TTKN/CNKIExpress/0.2.23/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.23/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.23/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.23/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95230 New version: TTKN.CNKIExpress version 0.2.24
  manifests/t/TTKN/CNKIExpress/0.2.24/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.24/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.24/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.24/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95233 New version: TTKN.CNKIExpress version 0.2.27
  manifests/t/TTKN/CNKIExpress/0.2.27/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.27/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.27/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.27/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95234 New version: TTKN.CNKIExpress version 0.2.28
  manifests/t/TTKN/CNKIExpress/0.2.28/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.28/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.28/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.28/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95236 New version: TTKN.CNKIExpress version 0.2.31
  manifests/t/TTKN/CNKIExpress/0.2.31/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.31/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.31/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.31/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95237 New version: Jackett.Jackett version 0.20.2814
  manifests/j/Jackett/Jackett/0.20.2814/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.20.2814/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.20.2814/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95238 Add version: Baidu.SwanIDE version 4.9.2
  manifests/b/Baidu/SwanIDE/4.9.2/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.9.2/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.9.2/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.9.2/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95242 Add version: Baidu.SwanIDE version 4.7.1
  manifests/b/Baidu/SwanIDE/4.7.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.7.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.7.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.7.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95243 Add version: Baidu.SwanIDE version 4.6.1
  manifests/b/Baidu/SwanIDE/4.6.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.6.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.6.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.6.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95244 Add version: Baidu.SwanIDE version 4.5.1
  manifests/b/Baidu/SwanIDE/4.5.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.5.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.5.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.5.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95245 Add version: Baidu.SwanIDE version 4.4.1
  manifests/b/Baidu/SwanIDE/4.4.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.4.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.4.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.4.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95246 Add version: Baidu.SwanIDE version 4.3.1
  manifests/b/Baidu/SwanIDE/4.3.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.3.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.3.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.3.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95207 New version: Openstreetmap.Josm version 18646
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.installer.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.bg-BG.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.ca-ES.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.cs-CZ.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.da-DK.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.de-DE.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.en-US.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.es-ES.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.et-EE.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.fi-FI.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.fr-FR.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.gl-ES.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.he-IL.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.hu-HU.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.it-IT.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.ja-JP.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.ko-KR.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.nl-NL.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.pl-PL.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.pt-PT.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.ru-RU.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.sr-Latn-RS.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.uk-UA.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.zh-CN.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.locale.zh-TW.yaml
  manifests/o/OpenStreetMap/Josm/18646/OpenStreetMap.Josm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95231 New version: TTKN.CNKIExpress version 0.2.25
  manifests/t/TTKN/CNKIExpress/0.2.25/TTKN.CNKIExpress.installer.yaml
  manifests/t/TTKN/CNKIExpress/0.2.25/TTKN.CNKIExpress.locale.en-US.yaml
  manifests/t/TTKN/CNKIExpress/0.2.25/TTKN.CNKIExpress.locale.zh-CN.yaml
  manifests/t/TTKN/CNKIExpress/0.2.25/TTKN.CNKIExpress.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95239 Add version: Baidu.SwanIDE version 4.9.1
  manifests/b/Baidu/SwanIDE/4.9.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.9.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.9.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.9.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95248 Modify: Baidu.BaiduTranslate version 1.5.4
  manifests/b/Baidu/BaiduTranslate/1.5.4/Baidu.BaiduTranslate.installer.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.4/Baidu.BaiduTranslate.locale.en-US.yaml
  manifests/b/Baidu/BaiduTranslate/1.5.4/Baidu.BaiduTranslate.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95249 Add version: Baidu.BaiduWenku version 1.1.5
  manifests/b/Baidu/BaiduWenku/1.1.5/Baidu.BaiduWenku.installer.yaml
  manifests/b/Baidu/BaiduWenku/1.1.5/Baidu.BaiduWenku.locale.en-US.yaml
  manifests/b/Baidu/BaiduWenku/1.1.5/Baidu.BaiduWenku.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduWenku/1.1.5/Baidu.BaiduWenku.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95247 New version: Microsoft.Bicep version 0.14.6.61914
  manifests/m/Microsoft/Bicep/0.14.6.61914/Microsoft.Bicep.installer.yaml
  manifests/m/Microsoft/Bicep/0.14.6.61914/Microsoft.Bicep.locale.en-US.yaml
  manifests/m/Microsoft/Bicep/0.14.6.61914/Microsoft.Bicep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95210 PTRTECH.UVtools version 3.11.2
  manifests/p/PTRTECH/UVtools/3.11.2/PTRTECH.UVtools.installer.yaml
  manifests/p/PTRTECH/UVtools/3.11.2/PTRTECH.UVtools.locale.en-US.yaml
  manifests/p/PTRTECH/UVtools/3.11.2/PTRTECH.UVtools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95252 Update: KDE.Dolphin version 22.12.1
  manifests/k/KDE/Dolphin/22.12.1/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95256 New version: JetBrains.RubyMine.EarlyAccess version 231.5920.15
  manifests/j/JetBrains/RubyMine/EarlyAccess/231.5920.15/JetBrains.RubyMine.EarlyAccess.installer.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/231.5920.15/JetBrains.RubyMine.EarlyAccess.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/EarlyAccess/231.5920.15/JetBrains.RubyMine.EarlyAccess.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95257 Update: KDE.Kate version 22.12.1
  manifests/k/KDE/Kate/22.12.1/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95258 New version: Riiid.pollapo version 0.0.60
  manifests/r/Riiid/pollapo/0.0.60/Riiid.pollapo.installer.yaml
  manifests/r/Riiid/pollapo/0.0.60/Riiid.pollapo.locale.en-US.yaml
  manifests/r/Riiid/pollapo/0.0.60/Riiid.pollapo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95259 New version: stnkl.EverythingToolbar version 1.0.1
  manifests/s/stnkl/EverythingToolbar/1.0.1/stnkl.EverythingToolbar.installer.yaml
  manifests/s/stnkl/EverythingToolbar/1.0.1/stnkl.EverythingToolbar.locale.en-US.yaml
  manifests/s/stnkl/EverythingToolbar/1.0.1/stnkl.EverythingToolbar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95260 New version: Wondershare.Recoverit version 11.0.2.12
  manifests/w/Wondershare/Recoverit/11.0.2.12/Wondershare.Recoverit.installer.yaml
  manifests/w/Wondershare/Recoverit/11.0.2.12/Wondershare.Recoverit.locale.en-US.yaml
  manifests/w/Wondershare/Recoverit/11.0.2.12/Wondershare.Recoverit.locale.zh-CN.yaml
  manifests/w/Wondershare/Recoverit/11.0.2.12/Wondershare.Recoverit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95262 Add version: Baidu.SwanIDE version 4.2.3
  manifests/b/Baidu/SwanIDE/4.2.3/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.2.3/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.2.3/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.2.3/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95263 Add version: Baidu.SwanIDE version 4.2.2
  manifests/b/Baidu/SwanIDE/4.2.2/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.2.2/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.2.2/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.2.2/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95265 Add version: Baidu.SwanIDE version 4.1.1
  manifests/b/Baidu/SwanIDE/4.1.1/Baidu.SwanIDE.installer.yaml
  manifests/b/Baidu/SwanIDE/4.1.1/Baidu.SwanIDE.locale.en-US.yaml
  manifests/b/Baidu/SwanIDE/4.1.1/Baidu.SwanIDE.locale.zh-CN.yaml
  manifests/b/Baidu/SwanIDE/4.1.1/Baidu.SwanIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95269 New version: Baidu.BaiduSIAssistant version 1.6.0
  manifests/b/Baidu/BaiduSIAssistant/1.6.0/Baidu.BaiduSIAssistant.installer.yaml
  manifests/b/Baidu/BaiduSIAssistant/1.6.0/Baidu.BaiduSIAssistant.locale.en-US.yaml
  manifests/b/Baidu/BaiduSIAssistant/1.6.0/Baidu.BaiduSIAssistant.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduSIAssistant/1.6.0/Baidu.BaiduSIAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95272 New version: libjpeg-turbo.libjpeg-turbo.GCC version 2.1.5
  manifests/l/libjpeg-turbo/libjpeg-turbo/GCC/2.1.5/libjpeg-turbo.libjpeg-turbo.GCC.installer.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/GCC/2.1.5/libjpeg-turbo.libjpeg-turbo.GCC.locale.en-US.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/GCC/2.1.5/libjpeg-turbo.libjpeg-turbo.GCC.locale.zh-CN.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/GCC/2.1.5/libjpeg-turbo.libjpeg-turbo.GCC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95273 Fix: libjpeg-turbo.libjpeg-turbo.GCC version 2.1.4
  manifests/l/libjpeg-turbo/libjpeg-turbo/GCC/2.1.4/libjpeg-turbo.libjpeg-turbo.GCC.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95275 New version: Grammarly.Grammarly version 1.0.24.360
  manifests/g/Grammarly/Grammarly/1.0.24.360/Grammarly.Grammarly.installer.yaml
  manifests/g/Grammarly/Grammarly/1.0.24.360/Grammarly.Grammarly.locale.en-US.yaml
  manifests/g/Grammarly/Grammarly/1.0.24.360/Grammarly.Grammarly.locale.zh-CN.yaml
  manifests/g/Grammarly/Grammarly/1.0.24.360/Grammarly.Grammarly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95277 New version: B3log.SiYuan version 2.7.2
  manifests/b/B3log/SiYuan/2.7.2/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.7.2/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.7.2/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.7.2/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95278 New version: Tencent.TencentDocs version 2.4.9
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.locale.zh-CN.yaml
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95279 Remove: Kamyroll.Kamyroll-Tauri version 1.0.4
  manifests/k/Kamyroll/Kamyroll-Tauri/1.0.4/Kamyroll.Kamyroll-Tauri.installer.yaml
  manifests/k/Kamyroll/Kamyroll-Tauri/1.0.4/Kamyroll.Kamyroll-Tauri.locale.en-US.yaml
  manifests/k/Kamyroll/Kamyroll-Tauri/1.0.4/Kamyroll.Kamyroll-Tauri.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95286 Add version: Alibaba.DingTalk version 7.0.0-Release.2019102
  manifests/a/Alibaba/DingTalk/7.0.0-Release.2019102/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/7.0.0-Release.2019102/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.0.0-Release.2019102/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/7.0.0-Release.2019102/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95271 New version: libjpeg-turbo.libjpeg-turbo.VC version 2.1.5
  manifests/l/libjpeg-turbo/libjpeg-turbo/VC/2.1.5/libjpeg-turbo.libjpeg-turbo.VC.installer.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/VC/2.1.5/libjpeg-turbo.libjpeg-turbo.VC.locale.en-US.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/VC/2.1.5/libjpeg-turbo.libjpeg-turbo.VC.locale.zh-CN.yaml
  manifests/l/libjpeg-turbo/libjpeg-turbo/VC/2.1.5/libjpeg-turbo.libjpeg-turbo.VC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#88069 [Zip] New Package: PolarGoose.ShowWhatProcessLocksFile 3.0
  manifests/p/PolarGoose/ShowWhatProcessLocksFile/3.0/PolarGoose.ShowWhatProcessLocksFile.installer.yaml
  manifests/p/PolarGoose/ShowWhatProcessLocksFile/3.0/PolarGoose.ShowWhatProcessLocksFile.locale.en-US.yaml
  manifests/p/PolarGoose/ShowWhatProcessLocksFile/3.0/PolarGoose.ShowWhatProcessLocksFile.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Retry-1

#95064 acrosync.DuplicacyWeb version 1.6.3
  manifests/a/acrosync/DuplicacyWeb/1.6.3/acrosync.DuplicacyWeb.installer.yaml
  manifests/a/acrosync/DuplicacyWeb/1.6.3/acrosync.DuplicacyWeb.locale.en-US.yaml
  manifests/a/acrosync/DuplicacyWeb/1.6.3/acrosync.DuplicacyWeb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95312 Betterbird.Betterbird version 102.7.1-bb29
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.installer.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.de.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.en-US.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.es-AR.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.fr.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.it.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.nl.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.locale.pt-BR.yaml
  manifests/b/Betterbird/Betterbird/102.7.1-bb29/Betterbird.Betterbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95416 fix spelling/typos in schema docs
  doc/manifest/schema/1.4.0/singleton.md
Labels: Project-File

#95216 New version: JetBrains.PHPStorm version 2022.3.2
  manifests/j/JetBrains/PHPStorm/2022.3.2/JetBrains.PHPStorm.installer.yaml
  manifests/j/JetBrains/PHPStorm/2022.3.2/JetBrains.PHPStorm.locale.en-US.yaml
  manifests/j/JetBrains/PHPStorm/2022.3.2/JetBrains.PHPStorm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#87890 [Zip][Portable] New package: tp7.Sushi version 0.5.1
  manifests/t/tp7/Sushi/0.5.1/tp7.Sushi.installer.yaml
  manifests/t/tp7/Sushi/0.5.1/tp7.Sushi.locale.en-US.yaml
  manifests/t/tp7/Sushi/0.5.1/tp7.Sushi.locale.zh-CN.yaml
  manifests/t/tp7/Sushi/0.5.1/tp7.Sushi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Retry-1, Waived-Policy-Test-2.7, Waived-Validation-Executable-Error

#95506 New version: VMware.WorkstationPlayer version 17.0.1
  manifests/v/VMware/WorkstationPlayer/17.0.1/VMware.WorkstationPlayer.installer.yaml
  manifests/v/VMware/WorkstationPlayer/17.0.1/VMware.WorkstationPlayer.locale.en-US.yaml
  manifests/v/VMware/WorkstationPlayer/17.0.1/VMware.WorkstationPlayer.yaml
Labels: Binary-Validation-Error

#88066 [Zip][Portable] BurntSushi.ripgrep.MSVC 13.0.0
  manifests/b/BurntSushi/ripgrep/MSVC/13.0.0/BurntSushi.ripgrep.MSVC.installer.yaml
  manifests/b/BurntSushi/ripgrep/MSVC/13.0.0/BurntSushi.ripgrep.MSVC.locale.en-US.yaml
  manifests/b/BurntSushi/ripgrep/MSVC/13.0.0/BurntSushi.ripgrep.MSVC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#95507 New version: VMware.WorkstationPro version 17.0.1
  manifests/v/VMware/WorkstationPro/17.0.1/VMware.WorkstationPro.installer.yaml
  manifests/v/VMware/WorkstationPro/17.0.1/VMware.WorkstationPro.locale.en-US.yaml
  manifests/v/VMware/WorkstationPro/17.0.1/VMware.WorkstationPro.yaml
Labels: Binary-Validation-Error

#88067 [Zip][Portable] BurntSushi.ripgrep.GNU 13.0.0
  manifests/b/BurntSushi/ripgrep/GNU/13.0.0/BurntSushi.ripgrep.GNU.installer.yaml
  manifests/b/BurntSushi/ripgrep/GNU/13.0.0/BurntSushi.ripgrep.GNU.locale.en-US.yaml
  manifests/b/BurntSushi/ripgrep/GNU/13.0.0/BurntSushi.ripgrep.GNU.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#95315 New version: JetBrains.CLion.EAP version 231.6471.1
  manifests/j/JetBrains/CLion/EAP/231.6471.1/JetBrains.CLion.EAP.installer.yaml
  manifests/j/JetBrains/CLion/EAP/231.6471.1/JetBrains.CLion.EAP.locale.en-US.yaml
  manifests/j/JetBrains/CLion/EAP/231.6471.1/JetBrains.CLion.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#88068 [Zip][Portable] New Package: paolosalvatory.ServiceBusExplorer 5.0.14
  manifests/p/paolosalvatori/ServiceBusExplorer/5.0.14/paolosalvatori.ServiceBusExplorer.installer.yaml
  manifests/p/paolosalvatori/ServiceBusExplorer/5.0.14/paolosalvatori.ServiceBusExplorer.locale.en-US.yaml
  manifests/p/paolosalvatori/ServiceBusExplorer/5.0.14/paolosalvatori.ServiceBusExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Policy-Test-2.7, Waived-Policy-Test-2.7

#95316 DoltHub.Dolt version 0.52.17
  manifests/d/DoltHub/Dolt/0.52.17/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/0.52.17/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/0.52.17/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#88070 [Zip] New Package: SamuelTulach.VirusTotalUploader 0.1.9
  manifests/s/SamuelTulach/VirusTotalUploader/0.1.9/SamuelTulach.VirusTotalUploader.installer.yaml
  manifests/s/SamuelTulach/VirusTotalUploader/0.1.9/SamuelTulach.VirusTotalUploader.locale.en-US.yaml
  manifests/s/SamuelTulach/VirusTotalUploader/0.1.9/SamuelTulach.VirusTotalUploader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Retry-1

#95319 New Version: VMware.HorizonClient version 8.8.0.33776
  manifests/v/VMware/HorizonClient/8.8.0.33776/VMware.HorizonClient.installer.yaml
  manifests/v/VMware/HorizonClient/8.8.0.33776/VMware.HorizonClient.locale.en-US.yaml
  manifests/v/VMware/HorizonClient/8.8.0.33776/VMware.HorizonClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#88139 [Zip][Portable] New package: Gyan.FFmpeg.Shared version 5.1.2
  manifests/g/Gyan/FFmpeg/Shared/5.1.2/Gyan.FFmpeg.Shared.installer.yaml
  manifests/g/Gyan/FFmpeg/Shared/5.1.2/Gyan.FFmpeg.Shared.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/Shared/5.1.2/Gyan.FFmpeg.Shared.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/Shared/5.1.2/Gyan.FFmpeg.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, URL-Validation-Error, .zip, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#88295 [Zip][Portable] New package: Hugo.Hugo version 0.105.0
  manifests/h/Hugo/Hugo/0.105.0/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.105.0/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.105.0/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.105.0/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Validation-Executable-Error, Waived-Validation-Executable-Error

#88296 [Zip][Portable] New package: Hugo.Hugo.Extended version 0.105.0
  manifests/h/Hugo/Hugo/Extended/0.105.0/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.105.0/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.105.0/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.105.0/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#95320 New version: Patchdeck Agent version 2.4.0
  manifests/p/Patchdeck/Agent/2.4.0/Patchdeck.Agent.installer.yaml
  manifests/p/Patchdeck/Agent/2.4.0/Patchdeck.Agent.locale.en-US.yaml
  manifests/p/Patchdeck/Agent/2.4.0/Patchdeck.Agent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#94708 New package: sharkdp.hyperfine version 1.15.0
  manifests/s/sharkdp/hyperfine/1.15.0/sharkdp.hyperfine.installer.yaml
  manifests/s/sharkdp/hyperfine/1.15.0/sharkdp.hyperfine.locale.en-US.yaml
  manifests/s/sharkdp/hyperfine/1.15.0/sharkdp.hyperfine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Waived-Validation-Executable-Error

#90319 [Zip][Inno] New package: MPC-BE.MPC-BE version 1.6.5.3
  manifests/m/MPC-BE/MPC-BE/1.6.5.3/MPC-BE.MPC-BE.installer.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.5.3/MPC-BE.MPC-BE.locale.en-US.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.5.3/MPC-BE.MPC-BE.locale.zh-CN.yaml
  manifests/m/MPC-BE/MPC-BE/1.6.5.3/MPC-BE.MPC-BE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Retry-1

#94786 New package: codehex.Neo-cowsay version 2.0.4
  manifests/c/codehex/Neo-cowsay/2.0.4/codehex.Neo-cowsay.installer.yaml
  manifests/c/codehex/Neo-cowsay/2.0.4/codehex.Neo-cowsay.locale.en-US.yaml
  manifests/c/codehex/Neo-cowsay/2.0.4/codehex.Neo-cowsay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Retry-1

#94788 New package: gokcehan.lf version r28
  manifests/g/gokcehan/lf/r28/gokcehan.lf.installer.yaml
  manifests/g/gokcehan/lf/r28/gokcehan.lf.locale.en-US.yaml
  manifests/g/gokcehan/lf/r28/gokcehan.lf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Retry-1

#94790 New package: dundee.gdu version 5.21.1
  manifests/d/dundee/gdu/5.21.1/dundee.gdu.installer.yaml
  manifests/d/dundee/gdu/5.21.1/dundee.gdu.locale.en-US.yaml
  manifests/d/dundee/gdu/5.21.1/dundee.gdu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Retry-1

#94710 JesseDuffield.Lazydocker version 0.20.0
  manifests/j/JesseDuffield/Lazydocker/0.20.0/JesseDuffield.Lazydocker.installer.yaml
  manifests/j/JesseDuffield/Lazydocker/0.20.0/JesseDuffield.Lazydocker.locale.en-US.yaml
  manifests/j/JesseDuffield/Lazydocker/0.20.0/JesseDuffield.Lazydocker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Retry-1

#94810 New package: RHash.RHash version 1.4.3
  manifests/r/RHash/RHash/1.4.3/RHash.RHash.installer.yaml
  manifests/r/RHash/RHash/1.4.3/RHash.RHash.locale.en-US.yaml
  manifests/r/RHash/RHash/1.4.3/RHash.RHash.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Validation-Unapproved-URL, Retry-1, Waived-Validation-Unapproved-URL

#94714 New package: sharkdp.fd version 8.6.0
  manifests/s/sharkdp/fd/8.6.0/sharkdp.fd.installer.yaml
  manifests/s/sharkdp/fd/8.6.0/sharkdp.fd.locale.en-US.yaml
  manifests/s/sharkdp/fd/8.6.0/sharkdp.fd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Internal-Error-Dynamic-Scan, Validation-Executable-Error, Retry-1, Waived-Validation-Executable-Error

#94759 New package: twpayne.chezmoi version 2.29.4
  manifests/t/twpayne/chezmoi/2.29.4/twpayne.chezmoi.installer.yaml
  manifests/t/twpayne/chezmoi/2.29.4/twpayne.chezmoi.locale.en-US.yaml
  manifests/t/twpayne/chezmoi/2.29.4/twpayne.chezmoi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, .zip, Dependencies, Retry-1

#87998 Modify: ByteDance.BytedanceMiniappIDE version 3.3.7-1
  manifests/b/ByteDance/BytedanceMiniappIDE/3.3.7-1/ByteDance.BytedanceMiniappIDE.installer.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.3.7-1/ByteDance.BytedanceMiniappIDE.locale.en-US.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.3.7-1/ByteDance.BytedanceMiniappIDE.locale.zh-CN.yaml
  manifests/b/ByteDance/BytedanceMiniappIDE/3.3.7-1/ByteDance.BytedanceMiniappIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#95325 CloudImperiumGames.RSILauncher version 1.6.3
  manifests/c/CloudImperiumGames/RSILauncher/1.6.3/CloudImperiumGames.RSILauncher.installer.yaml
  manifests/c/CloudImperiumGames/RSILauncher/1.6.3/CloudImperiumGames.RSILauncher.locale.en-US.yaml
  manifests/c/CloudImperiumGames/RSILauncher/1.6.3/CloudImperiumGames.RSILauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95327 New version: chrisant996.Clink version 1.4.15.439299
  manifests/c/chrisant996/Clink/1.4.15.439299/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.4.15.439299/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.4.15.439299/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95329 New version: JanProchazka.dbgate version 5.2.2
  manifests/j/JanProchazka/dbgate/5.2.2/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/5.2.2/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/5.2.2/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95333 KurtZimmermann.HDCleaner version 2.043
  manifests/k/KurtZimmermann/HDCleaner/2.043/KurtZimmermann.HDCleaner.installer.yaml
  manifests/k/KurtZimmermann/HDCleaner/2.043/KurtZimmermann.HDCleaner.locale.en-us.yaml
  manifests/k/KurtZimmermann/HDCleaner/2.043/KurtZimmermann.HDCleaner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95334 Add Postman.Postman 10.9.0
  manifests/p/Postman/Postman/10.9.0/Postman.Postman.installer.yaml
  manifests/p/Postman/Postman/10.9.0/Postman.Postman.locale.en-US.yaml
  manifests/p/Postman/Postman/10.9.0/Postman.Postman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95339 New Version: Robware.RVTools version 4.3.2
  manifests/r/Robware/RVTools/4.3.2/Robware.RVTools.installer.yaml
  manifests/r/Robware/RVTools/4.3.2/Robware.RVTools.locale.en-US.yaml
  manifests/r/Robware/RVTools/4.3.2/Robware.RVTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95129 IDMComputerSolutions,Inc.UltraEdit version 29.2.34
  manifests/i/IDMComputerSolutions,Inc/UltraEdit/29.2.34/IDMComputerSolutions,Inc.UltraEdit.installer.yaml
  manifests/i/IDMComputerSolutions,Inc/UltraEdit/29.2.34/IDMComputerSolutions,Inc.UltraEdit.locale.en-US.yaml
  manifests/i/IDMComputerSolutions,Inc/UltraEdit/29.2.34/IDMComputerSolutions,Inc.UltraEdit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95131 OleksisFraga.PythonLauncher version 2.0.0.1
  manifests/o/OleksisFraga/PythonLauncher/2.0.0.1/OleksisFraga.PythonLauncher.installer.yaml
  manifests/o/OleksisFraga/PythonLauncher/2.0.0.1/OleksisFraga.PythonLauncher.locale.en-US.yaml
  manifests/o/OleksisFraga/PythonLauncher/2.0.0.1/OleksisFraga.PythonLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95135 New package: SophiApp version 1.0.94
  manifests/t/TeamSophia/SophiApp/1.0.94/TeamSophia.SophiApp.installer.yaml
  manifests/t/TeamSophia/SophiApp/1.0.94/TeamSophia.SophiApp.locale.en-US.yaml
  manifests/t/TeamSophia/SophiApp/1.0.94/TeamSophia.SophiApp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#95403 Update: Hitencent.JisuPDFToWord version 2.0 (2.0.6.2)
  manifests/h/Hitencent/JisuPDFToWord/2.0/Hitencent.JisuPDFToWord.installer.yaml
  manifests/h/Hitencent/JisuPDFToWord/2.0/Hitencent.JisuPDFToWord.locale.en-US.yaml
  manifests/h/Hitencent/JisuPDFToWord/2.0/Hitencent.JisuPDFToWord.locale.zh-CN.yaml
  manifests/h/Hitencent/JisuPDFToWord/2.0/Hitencent.JisuPDFToWord.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95404 ReleaseNotes: Tencent.TencentDocs version 2.4.9
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.installer.yaml
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.locale.en-US.yaml
  manifests/t/Tencent/TencentDocs/2.4.9/Tencent.TencentDocs.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95405 ReleaseNotes: Wondershare.Recoverit version 11.0.2.12
  manifests/w/Wondershare/Recoverit/11.0.2.12/Wondershare.Recoverit.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan

#95407 New version: Tauri.create-tauri-app version 2.7.9
  manifests/t/Tauri/create-tauri-app/2.7.9/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/2.7.9/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/2.7.9/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/2.7.9/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95411 Update LibreWolf.LibreWolf to v109.0.1-2
  manifests/l/LibreWolf/LibreWolf/109.0.1-2/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/109.0.1-2/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/109.0.1-2/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95412 Added AWS Command Line Interface version 2.9.20.
  manifests/a/Amazon/AWSCLI/2.9.20/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.9.20/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.9.20/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95413 Microsoft.Azd version 0.5.0.3
  manifests/m/Microsoft/Azd/0.5.0.3/Microsoft.Azd.installer.yaml
  manifests/m/Microsoft/Azd/0.5.0.3/Microsoft.Azd.locale.en-US.yaml
  manifests/m/Microsoft/Azd/0.5.0.3/Microsoft.Azd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95417 New version: OpenJS.NodeJS version 19.6.0
  manifests/o/OpenJS/NodeJS/19.6.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/19.6.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/19.6.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/19.6.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95418 Coder.Coder version 0.16.0
  manifests/c/Coder/Coder/0.16.0/Coder.Coder.installer.yaml
  manifests/c/Coder/Coder/0.16.0/Coder.Coder.locale.en-US.yaml
  manifests/c/Coder/Coder/0.16.0/Coder.Coder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#95421 New Version: Astronomer.Astro version 1.10.0
  manifests/a/Astronomer/Astro/1.10.0/Astronomer.Astro.installer.yaml
  manifests/a/Astronomer/Astro/1.10.0/Astronomer.Astro.locale.en-US.yaml
  manifests/a/Astronomer/Astro/1.10.0/Astronomer.Astro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1

#95423 Add DisplayVersion to Microsoft.VisualStudio.2017.BuildTools 15.9.51
  manifests/m/Microsoft/VisualStudio/2017/BuildTools/15.9.51/Microsoft.VisualStudio.2017.BuildTools.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed
