Repository microsoft/winget-pkgs, pull requests merged in 2023-12, with the labels that each got.

#128313 New version: Ubisoft.Connect version 148.1.10975
  manifests/u/Ubisoft/Connect/148.1.10975/Ubisoft.Connect.installer.yaml
  manifests/u/Ubisoft/Connect/148.1.10975/Ubisoft.Connect.locale.en-US.yaml
  manifests/u/Ubisoft/Connect/148.1.10975/Ubisoft.Connect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#128542 New version: o2sh.onefetch version 2.19.0
  manifests/o/o2sh/onefetch/2.19.0/o2sh.onefetch.installer.yaml
  manifests/o/o2sh/onefetch/2.19.0/o2sh.onefetch.locale.en-US.yaml
  manifests/o/o2sh/onefetch/2.19.0/o2sh.onefetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#128706 New version: Readdle.Spark version 3.10.6
  manifests/r/Readdle/Spark/3.10.6/Readdle.Spark.installer.yaml
  manifests/r/Readdle/Spark/3.10.6/Readdle.Spark.locale.en-US.yaml
  manifests/r/Readdle/Spark/3.10.6/Readdle.Spark.locale.zh-CN.yaml
  manifests/r/Readdle/Spark/3.10.6/Readdle.Spark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128707 New version: Figma.FigmaAgent version 116.15.4
  manifests/f/Figma/FigmaAgent/116.15.4/Figma.FigmaAgent.installer.yaml
  manifests/f/Figma/FigmaAgent/116.15.4/Figma.FigmaAgent.locale.en-US.yaml
  manifests/f/Figma/FigmaAgent/116.15.4/Figma.FigmaAgent.locale.zh-CN.yaml
  manifests/f/Figma/FigmaAgent/116.15.4/Figma.FigmaAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128710 New version: squalou.google-chat-linux version 5.27.22-2
  manifests/s/squalou/google-chat-linux/5.27.22-2/squalou.google-chat-linux.installer.yaml
  manifests/s/squalou/google-chat-linux/5.27.22-2/squalou.google-chat-linux.locale.en-US.yaml
  manifests/s/squalou/google-chat-linux/5.27.22-2/squalou.google-chat-linux.locale.zh-CN.yaml
  manifests/s/squalou/google-chat-linux/5.27.22-2/squalou.google-chat-linux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128552 New version: VirtusLab.ScalaCLI version 1.1.0
  manifests/v/VirtusLab/ScalaCLI/1.1.0/VirtusLab.ScalaCLI.installer.yaml
  manifests/v/VirtusLab/ScalaCLI/1.1.0/VirtusLab.ScalaCLI.locale.en-US.yaml
  manifests/v/VirtusLab/ScalaCLI/1.1.0/VirtusLab.ScalaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error

#128145 New package: DaCosySheeep.FactDownloader version 1.0
  manifests/d/DaCosySheeep/FactDownloader/1.0/DaCosySheeep.FactDownloader.installer.yaml
  manifests/d/DaCosySheeep/FactDownloader/1.0/DaCosySheeep.FactDownloader.locale.en-GB.yaml
  manifests/d/DaCosySheeep/FactDownloader/1.0/DaCosySheeep.FactDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#128485 add binbat/whipinto
  manifests/b/binbat/whipinto/0.2.0/binbat.whipinto.installer.yaml
  manifests/b/binbat/whipinto/0.2.0/binbat.whipinto.locale.en-US.yaml
  manifests/b/binbat/whipinto/0.2.0/binbat.whipinto.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#128623 v2rayN 5.39
  manifests/2/2dust/v2rayN/5.39/2dust.v2rayN.installer.yaml
  manifests/2/2dust/v2rayN/5.39/2dust.v2rayN.locale.zh-CN.yaml
  manifests/2/2dust/v2rayN/5.39/2dust.v2rayN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error

#128720 Migrate WinGetSVC pipeline to 1ES
  DevOpsPipelineDefinitions/publish-pipeline.yaml
  DevOpsPipelineDefinitions/rebuild-pipeline.yaml
  DevOpsPipelineDefinitions/rebuild-rest-pipeline.yaml
  DevOpsPipelineDefinitions/validation-pipeline.yaml
Labels: Moderator-Approved, Project-File, Needs-Attention

#128647 New package: OpenTofu.Tofu.Beta version 1.6.0-beta1
  manifests/o/OpenTofu/Tofu/Beta/1.6.0-beta1/OpenTofu.Tofu.Beta.installer.yaml
  manifests/o/OpenTofu/Tofu/Beta/1.6.0-beta1/OpenTofu.Tofu.Beta.locale.en-US.yaml
  manifests/o/OpenTofu/Tofu/Beta/1.6.0-beta1/OpenTofu.Tofu.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error

#128792 Revert "Migrate WinGetSVC pipeline to 1ES"
  DevOpsPipelineDefinitions/publish-pipeline.yaml
  DevOpsPipelineDefinitions/rebuild-pipeline.yaml
  DevOpsPipelineDefinitions/rebuild-rest-pipeline.yaml
  DevOpsPipelineDefinitions/validation-pipeline.yaml
Labels: Project-File, Needs-Attention

#128742 New version: Jackett.Jackett version 0.21.1289
  manifests/j/Jackett/Jackett/0.21.1289/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1289/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1289/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128727 New Version: SoftFever.OrcaSlicer V1.8.0
  manifests/s/SoftFever/OrcaSlicer/1.8.0/SoftFever.OrcaSlicer.installer.yaml
  manifests/s/SoftFever/OrcaSlicer/1.8.0/SoftFever.OrcaSlicer.locale.en-US.yaml
  manifests/s/SoftFever/OrcaSlicer/1.8.0/SoftFever.OrcaSlicer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128734 New version: Microsoft.EdgeDriver version 119.0.2151.97
  manifests/m/Microsoft/EdgeDriver/119.0.2151.97/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/119.0.2151.97/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/119.0.2151.97/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/119.0.2151.97/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128738 New version: PerfectWorld.PerfectWorldArena version 1.0.23120111
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120111/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120111/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120111/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120111/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128743 New version: GodotEngine.GodotEngine version 4.2
  manifests/g/GodotEngine/GodotEngine/4.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/4.2/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/4.2/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128745 Remove Post On Screen version 1.0
  manifests/j/Japplis/PostOnScreen/1.0/Japplis.PostOnScreen.installer.yaml
  manifests/j/Japplis/PostOnScreen/1.0/Japplis.PostOnScreen.locale.en-US.yaml
  manifests/j/Japplis/PostOnScreen/1.0/Japplis.PostOnScreen.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128747 Remove Toolbox version 5.5
  manifests/j/Japplis/Toolbox/5.5/Japplis.Toolbox.installer.yaml
  manifests/j/Japplis/Toolbox/5.5/Japplis.Toolbox.locale.en-US.yaml
  manifests/j/Japplis/Toolbox/5.5/Japplis.Toolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128749 Remove Watch version 1.6
  manifests/j/Japplis/Watch/1.6/Japplis.Watch.installer.yaml
  manifests/j/Japplis/Watch/1.6/Japplis.Watch.locale.en-US.yaml
  manifests/j/Japplis/Watch/1.6/Japplis.Watch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128761 New Version RuneLite.RuneLite 2.6.10
  manifests/r/RuneLite/RuneLite/2.6.10/RuneLite.RuneLite.installer.yaml
  manifests/r/RuneLite/RuneLite/2.6.10/RuneLite.RuneLite.locale.en-US.yaml
  manifests/r/RuneLite/RuneLite/2.6.10/RuneLite.RuneLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128755 New version: Huawei.Welink version 7.35.3
  manifests/h/Huawei/Welink/7.35.3/Huawei.Welink.installer.yaml
  manifests/h/Huawei/Welink/7.35.3/Huawei.Welink.locale.en-US.yaml
  manifests/h/Huawei/Welink/7.35.3/Huawei.Welink.locale.zh-CN.yaml
  manifests/h/Huawei/Welink/7.35.3/Huawei.Welink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128763 New version: 360.360SE version 15.1.1350.64
  manifests/3/360/360SE/15.1.1350.64/360.360SE.installer.yaml
  manifests/3/360/360SE/15.1.1350.64/360.360SE.locale.en-US.yaml
  manifests/3/360/360SE/15.1.1350.64/360.360SE.locale.zh-CN.yaml
  manifests/3/360/360SE/15.1.1350.64/360.360SE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128764 New version: Seewo.SeewoPincoGroup version 1.2.37.1665
  manifests/s/Seewo/SeewoPincoGroup/1.2.37.1665/Seewo.SeewoPincoGroup.installer.yaml
  manifests/s/Seewo/SeewoPincoGroup/1.2.37.1665/Seewo.SeewoPincoGroup.locale.en-US.yaml
  manifests/s/Seewo/SeewoPincoGroup/1.2.37.1665/Seewo.SeewoPincoGroup.locale.zh-CN.yaml
  manifests/s/Seewo/SeewoPincoGroup/1.2.37.1665/Seewo.SeewoPincoGroup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128785 New version: DirSoft.ARPro version 17.0.1.1088
  manifests/d/DirSoft/ARPro/17.0.1.1088/DirSoft.ARPro.installer.yaml
  manifests/d/DirSoft/ARPro/17.0.1.1088/DirSoft.ARPro.locale.en-US.yaml
  manifests/d/DirSoft/ARPro/17.0.1.1088/DirSoft.ARPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#128779 Adding Agente Milvus Core version 102.0.0.0.
  manifests/m/Milvus/AgenteMilvusCore/102.0.0.0/Milvus.AgenteMilvusCore.installer.yaml
  manifests/m/Milvus/AgenteMilvusCore/102.0.0.0/Milvus.AgenteMilvusCore.locale.pt-BR.yaml
  manifests/m/Milvus/AgenteMilvusCore/102.0.0.0/Milvus.AgenteMilvusCore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128782 New version: SublimeHQ.SublimeText.4 version 4.0.0.416900
  manifests/s/SublimeHQ/SublimeText/4/4.0.0.416900/SublimeHQ.SublimeText.4.installer.yaml
  manifests/s/SublimeHQ/SublimeText/4/4.0.0.416900/SublimeHQ.SublimeText.4.locale.en-US.yaml
  manifests/s/SublimeHQ/SublimeText/4/4.0.0.416900/SublimeHQ.SublimeText.4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128776 New version: CologneCodeCompany.XYplorerPortable version 25.20.0100
  manifests/c/CologneCodeCompany/XYplorerPortable/25.20.0100/CologneCodeCompany.XYplorerPortable.installer.yaml
  manifests/c/CologneCodeCompany/XYplorerPortable/25.20.0100/CologneCodeCompany.XYplorerPortable.locale.en-US.yaml
  manifests/c/CologneCodeCompany/XYplorerPortable/25.20.0100/CologneCodeCompany.XYplorerPortable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128760 New version: Tencent.WeCom version 4.1.13.6002
  manifests/t/Tencent/WeCom/4.1.13.6002/Tencent.WeCom.installer.yaml
  manifests/t/Tencent/WeCom/4.1.13.6002/Tencent.WeCom.locale.en-US.yaml
  manifests/t/Tencent/WeCom/4.1.13.6002/Tencent.WeCom.locale.zh-CN.yaml
  manifests/t/Tencent/WeCom/4.1.13.6002/Tencent.WeCom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#126209 TechNobo.TcNoAccountSwitcher version 4
  manifests/t/TechNobo/TcNoAccountSwitcher/4/TechNobo.TcNoAccountSwitcher.installer.yaml
  manifests/t/TechNobo/TcNoAccountSwitcher/4/TechNobo.TcNoAccountSwitcher.locale.en-US.yaml
  manifests/t/TechNobo/TcNoAccountSwitcher/4/TechNobo.TcNoAccountSwitcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#128565 New package: mitmproxy.mitmproxy version 10.1.5
  manifests/m/mitmproxy/mitmproxy/10.1.5/mitmproxy.mitmproxy.installer.yaml
  manifests/m/mitmproxy/mitmproxy/10.1.5/mitmproxy.mitmproxy.locale.en-US.yaml
  manifests/m/mitmproxy/mitmproxy/10.1.5/mitmproxy.mitmproxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-2.7

#128795 JanDeDobbeleer.OhMyPosh version 18.28.0
  manifests/j/JanDeDobbeleer/OhMyPosh/18.28.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.28.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.28.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128780 New version: MathiasSvensson.MultiCommander version 13.1.0.2955
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.installer.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.locale.en-US.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128668 Version Update: Henry++.simplewall version 3.7.6
  manifests/h/Henry++/simplewall/3.7.6/Henry++.simplewall.installer.yaml
  manifests/h/Henry++/simplewall/3.7.6/Henry++.simplewall.locale.en-US.yaml
  manifests/h/Henry++/simplewall/3.7.6/Henry++.simplewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-No-Executables

#128637 New package: WHONET.AMRInterpretationEngine version 23.6.21
  manifests/w/WHONET/AMRInterpretationEngine/23.6.21/WHONET.AMRInterpretationEngine.installer.yaml
  manifests/w/WHONET/AMRInterpretationEngine/23.6.21/WHONET.AMRInterpretationEngine.locale.en-US.yaml
  manifests/w/WHONET/AMRInterpretationEngine/23.6.21/WHONET.AMRInterpretationEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#128781 Update Microsoft.Skype.installer.yaml 8.109: Add `DisplayVersion`
  manifests/m/Microsoft/Skype/8.109/Microsoft.Skype.installer.yaml
  manifests/m/Microsoft/Skype/8.109/Microsoft.Skype.locale.en-US.yaml
  manifests/m/Microsoft/Skype/8.109/Microsoft.Skype.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128770 Update metadata: OpenJS.NodeJS version 21.1.0
  manifests/o/OpenJS/NodeJS/21.1.0/OpenJS.NodeJS.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128756 JanDeDobbeleer.OhMyPosh version 18.27.1
  manifests/j/JanDeDobbeleer/OhMyPosh/18.27.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.27.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/18.27.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128844 New version: Jackett.Jackett version 0.21.1293
  manifests/j/Jackett/Jackett/0.21.1293/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1293/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1293/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129007 New version: Jackett.Jackett version 0.21.1298
  manifests/j/Jackett/Jackett/0.21.1298/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1298/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1298/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128990 JanDeDobbeleer.OhMyPosh version 19.1.1
  manifests/j/JanDeDobbeleer/OhMyPosh/19.1.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.1.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.1.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128853 JanDeDobbeleer.OhMyPosh version 19.0.0
  manifests/j/JanDeDobbeleer/OhMyPosh/19.0.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.0.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.0.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129159 New version: 360.360Ent version 13.1.2002.362
  manifests/3/360/360Ent/13.1.2002.362/360.360Ent.installer.yaml
  manifests/3/360/360Ent/13.1.2002.362/360.360Ent.locale.en-US.yaml
  manifests/3/360/360Ent/13.1.2002.362/360.360Ent.locale.zh-CN.yaml
  manifests/3/360/360Ent/13.1.2002.362/360.360Ent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129034 New version: FutureScholars.Paperlib version 2.2.7
  manifests/f/FutureScholars/Paperlib/2.2.7/FutureScholars.Paperlib.installer.yaml
  manifests/f/FutureScholars/Paperlib/2.2.7/FutureScholars.Paperlib.locale.en-US.yaml
  manifests/f/FutureScholars/Paperlib/2.2.7/FutureScholars.Paperlib.locale.zh-CN.yaml
  manifests/f/FutureScholars/Paperlib/2.2.7/FutureScholars.Paperlib.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129156 New version: ByteDance.Feishu version 7.6.8
  manifests/b/ByteDance/Feishu/7.6.8/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/7.6.8/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/7.6.8/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/7.6.8/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129155 New version: Baidu.TeraBox version 1.26.0
  manifests/b/Baidu/TeraBox/1.26.0/Baidu.TeraBox.installer.yaml
  manifests/b/Baidu/TeraBox/1.26.0/Baidu.TeraBox.locale.en-US.yaml
  manifests/b/Baidu/TeraBox/1.26.0/Baidu.TeraBox.locale.zh-CN.yaml
  manifests/b/Baidu/TeraBox/1.26.0/Baidu.TeraBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129139 New version: StandardNotes.StandardNotes version 3.183.1
  manifests/s/StandardNotes/StandardNotes/3.183.1/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.1/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.1/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129136 New version: StandardNotes.StandardNotes version 3.182.4
  manifests/s/StandardNotes/StandardNotes/3.182.4/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.4/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.4/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129135 New version: StandardNotes.StandardNotes version 3.182.3
  manifests/s/StandardNotes/StandardNotes/3.182.3/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.3/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.3/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129132 New version: StandardNotes.StandardNotes version 3.182.0
  manifests/s/StandardNotes/StandardNotes/3.182.0/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.0/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.0/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129142 New version: StandardNotes.StandardNotes version 3.183.4
  manifests/s/StandardNotes/StandardNotes/3.183.4/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.4/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.4/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129143 New version: StandardNotes.StandardNotes version 3.183.5
  manifests/s/StandardNotes/StandardNotes/3.183.5/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.5/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.5/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129133 New version: StandardNotes.StandardNotes version 3.182.1
  manifests/s/StandardNotes/StandardNotes/3.182.1/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.1/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.182.1/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129140 New version: StandardNotes.StandardNotes version 3.183.2
  manifests/s/StandardNotes/StandardNotes/3.183.2/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.2/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.2/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129141 New version: StandardNotes.StandardNotes version 3.183.3
  manifests/s/StandardNotes/StandardNotes/3.183.3/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.3/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.3/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129138 New version: StandardNotes.StandardNotes version 3.183.0
  manifests/s/StandardNotes/StandardNotes/3.183.0/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.0/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.183.0/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129167 Improve how YamlCreate writes to files
  Tools/YamlCreate.ps1
Labels: Moderator-Approved, Project-File, Needs-Attention

#129172 Address YamlCreate PR Comments
  Tools/YamlCreate.ps1
Labels: Moderator-Approved, Project-File, Needs-Attention

#129176 New version: Microsoft.PowerToys version 0.76.0
  manifests/m/Microsoft/PowerToys/0.76.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.76.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.76.0/Microsoft.PowerToys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128834 New version: tecwindow.SoundTranscriber version 1.3.2
  manifests/t/tecwindow/SoundTranscriber/1.3.2/tecwindow.SoundTranscriber.installer.yaml
  manifests/t/tecwindow/SoundTranscriber/1.3.2/tecwindow.SoundTranscriber.locale.en-US.yaml
  manifests/t/tecwindow/SoundTranscriber/1.3.2/tecwindow.SoundTranscriber.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#123449 New version: tangshimin.MuJing version 2.1.6
  manifests/t/tangshimin/MuJing/2.1.6/tangshimin.MuJing.installer.yaml
  manifests/t/tangshimin/MuJing/2.1.6/tangshimin.MuJing.locale.en-US.yaml
  manifests/t/tangshimin/MuJing/2.1.6/tangshimin.MuJing.locale.zh-CN.yaml
  manifests/t/tangshimin/MuJing/2.1.6/tangshimin.MuJing.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error

#128469 Rubberduck.Rubberduck version 2.5.9.6316
  manifests/r/Rubberduck/Rubberduck/2.5.9.6316/Rubberduck.Rubberduck.installer.yaml
  manifests/r/Rubberduck/Rubberduck/2.5.9.6316/Rubberduck.Rubberduck.locale.en-US.yaml
  manifests/r/Rubberduck/Rubberduck/2.5.9.6316/Rubberduck.Rubberduck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128488 New version: IndigoByte.DrExplain version 6.6.1283
  manifests/i/IndigoByte/DrExplain/6.6.1283/IndigoByte.DrExplain.installer.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1283/IndigoByte.DrExplain.locale.en-US.yaml
  manifests/i/IndigoByte/DrExplain/6.6.1283/IndigoByte.DrExplain.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128686 Create WinGet package for October 2023 GDK Update 1
  manifests/m/Microsoft/GDK/2310/231001/Microsoft.GDK.2310.installer.yaml
  manifests/m/Microsoft/GDK/2310/231001/Microsoft.GDK.2310.locale.en-US.yaml
  manifests/m/Microsoft/GDK/2310/231001/Microsoft.GDK.2310.locale.ja-JP.yaml
  manifests/m/Microsoft/GDK/2310/231001/Microsoft.GDK.2310.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128719 New version: Ferdium.Ferdium.Nightly version 6.6.1-nightly.14
  manifests/f/Ferdium/Ferdium/Nightly/6.6.1-nightly.14/Ferdium.Ferdium.Nightly.installer.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.6.1-nightly.14/Ferdium.Ferdium.Nightly.locale.en-US.yaml
  manifests/f/Ferdium/Ferdium/Nightly/6.6.1-nightly.14/Ferdium.Ferdium.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128722 New version: vim.vim.nightly version 9.0.2138
  manifests/v/vim/vim/nightly/9.0.2138/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.2138/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.2138/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128735 New version: Grammarly.Grammarly version 1.0.54.1209
  manifests/g/Grammarly/Grammarly/1.0.54.1209/Grammarly.Grammarly.installer.yaml
  manifests/g/Grammarly/Grammarly/1.0.54.1209/Grammarly.Grammarly.locale.en-US.yaml
  manifests/g/Grammarly/Grammarly/1.0.54.1209/Grammarly.Grammarly.locale.zh-CN.yaml
  manifests/g/Grammarly/Grammarly/1.0.54.1209/Grammarly.Grammarly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128740 New version: Taozuhong.Kangaroo 3.99.2
  manifests/t/Taozuhong/Kangaroo/3.99.2.231201/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.99.2.231201/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.99.2.231201/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.99.2.231201/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128739 New version: Pylogmon.pot version 2.7.1
  manifests/p/Pylogmon/pot/2.7.1/Pylogmon.pot.installer.yaml
  manifests/p/Pylogmon/pot/2.7.1/Pylogmon.pot.locale.en-US.yaml
  manifests/p/Pylogmon/pot/2.7.1/Pylogmon.pot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128741 Microsoft.VisualStudioCode.Insiders_v1.85.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.85.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.85.0/Microsoft.VisualStudioCode.Insiders.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.85.0/Microsoft.VisualStudioCode.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128744 New version: OliverBetz.ExifTool version 12.70
  manifests/o/OliverBetz/ExifTool/12.70/OliverBetz.ExifTool.installer.yaml
  manifests/o/OliverBetz/ExifTool/12.70/OliverBetz.ExifTool.locale.en-US.yaml
  manifests/o/OliverBetz/ExifTool/12.70/OliverBetz.ExifTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128753 New version: Alibaba.Yuque version 3.2.3
  manifests/a/Alibaba/Yuque/3.2.3/Alibaba.Yuque.installer.yaml
  manifests/a/Alibaba/Yuque/3.2.3/Alibaba.Yuque.locale.en-US.yaml
  manifests/a/Alibaba/Yuque/3.2.3/Alibaba.Yuque.locale.zh-CN.yaml
  manifests/a/Alibaba/Yuque/3.2.3/Alibaba.Yuque.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128752 New version: Wondershare.PDFelement.10 version 10.1.10
  manifests/w/Wondershare/PDFelement/10/10.1.10/Wondershare.PDFelement.10.installer.yaml
  manifests/w/Wondershare/PDFelement/10/10.1.10/Wondershare.PDFelement.10.locale.en-US.yaml
  manifests/w/Wondershare/PDFelement/10/10.1.10/Wondershare.PDFelement.10.locale.zh-CN.yaml
  manifests/w/Wondershare/PDFelement/10/10.1.10/Wondershare.PDFelement.10.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128762 New version: Appest.Dida version 5.0.2.0
  manifests/a/Appest/Dida/5.0.2.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/5.0.2.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/5.0.2.0/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/5.0.2.0/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128768 New version: CologneCodeCompany.XYplorer version 25.20.0100
  manifests/c/CologneCodeCompany/XYplorer/25.20.0100/CologneCodeCompany.XYplorer.installer.yaml
  manifests/c/CologneCodeCompany/XYplorer/25.20.0100/CologneCodeCompany.XYplorer.locale.en-US.yaml
  manifests/c/CologneCodeCompany/XYplorer/25.20.0100/CologneCodeCompany.XYplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128730 binbat add whepfrom
  manifests/b/binbat/whepfrom/0.2.0/binbat.whepfrom.installer.yaml
  manifests/b/binbat/whepfrom/0.2.0/binbat.whepfrom.locale.en-US.yaml
  manifests/b/binbat/whepfrom/0.2.0/binbat.whepfrom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#128549 New package: StarFinanz.StarMoney14Deluxe
  manifests/s/StarFinanz/StarMoney14Deluxe/14/StarFinanz.StarMoney14Deluxe.installer.yaml
  manifests/s/StarFinanz/StarMoney14Deluxe/14/StarFinanz.StarMoney14Deluxe.locale.de-DE.yaml
  manifests/s/StarFinanz/StarMoney14Deluxe/14/StarFinanz.StarMoney14Deluxe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-1.8

#128815 New version: TeamIDE.TeamIDE version 2.5.6
  manifests/t/TeamIDE/TeamIDE/2.5.6/TeamIDE.TeamIDE.installer.yaml
  manifests/t/TeamIDE/TeamIDE/2.5.6/TeamIDE.TeamIDE.locale.en-US.yaml
  manifests/t/TeamIDE/TeamIDE/2.5.6/TeamIDE.TeamIDE.locale.zh-CN.yaml
  manifests/t/TeamIDE/TeamIDE/2.5.6/TeamIDE.TeamIDE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128814 New version: Mobatek.MobaXterm version 23.5.0.5182
  manifests/m/Mobatek/MobaXterm/23.5.0.5182/Mobatek.MobaXterm.installer.yaml
  manifests/m/Mobatek/MobaXterm/23.5.0.5182/Mobatek.MobaXterm.locale.en-US.yaml
  manifests/m/Mobatek/MobaXterm/23.5.0.5182/Mobatek.MobaXterm.locale.zh-CN.yaml
  manifests/m/Mobatek/MobaXterm/23.5.0.5182/Mobatek.MobaXterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128813 Add AGSProjectTeam.AdventureGameStudio 3.6.0.54
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.54/AGSProjectTeam.AdventureGameStudio.installer.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.54/AGSProjectTeam.AdventureGameStudio.locale.en-US.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.0.54/AGSProjectTeam.AdventureGameStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128812 New version: Tencent.QQ.NT version 9.9.6.19189
  manifests/t/Tencent/QQ/NT/9.9.6.19189/Tencent.QQ.NT.installer.yaml
  manifests/t/Tencent/QQ/NT/9.9.6.19189/Tencent.QQ.NT.locale.en-US.yaml
  manifests/t/Tencent/QQ/NT/9.9.6.19189/Tencent.QQ.NT.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/NT/9.9.6.19189/Tencent.QQ.NT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128811 New version: Baidu.BaiduNetdisk version 7.35.1
  manifests/b/Baidu/BaiduNetdisk/7.35.1/Baidu.BaiduNetdisk.installer.yaml
  manifests/b/Baidu/BaiduNetdisk/7.35.1/Baidu.BaiduNetdisk.locale.en-US.yaml
  manifests/b/Baidu/BaiduNetdisk/7.35.1/Baidu.BaiduNetdisk.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduNetdisk/7.35.1/Baidu.BaiduNetdisk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128809 New version: ButterflyEffect.Monica version 1.2.1
  manifests/b/ButterflyEffect/Monica/1.2.1/ButterflyEffect.Monica.installer.yaml
  manifests/b/ButterflyEffect/Monica/1.2.1/ButterflyEffect.Monica.locale.en-US.yaml
  manifests/b/ButterflyEffect/Monica/1.2.1/ButterflyEffect.Monica.locale.zh-CN.yaml
  manifests/b/ButterflyEffect/Monica/1.2.1/ButterflyEffect.Monica.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128808 New version: Brave.Brave.Nightly version 120.1.63.5
  manifests/b/Brave/Brave/Nightly/120.1.63.5/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.5/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.5/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.5/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128804 New version: ownCloud.ownCloudDesktop version 5.2.0.12726
  manifests/o/ownCloud/ownCloudDesktop/5.2.0.12726/ownCloud.ownCloudDesktop.installer.yaml
  manifests/o/ownCloud/ownCloudDesktop/5.2.0.12726/ownCloud.ownCloudDesktop.locale.en-US.yaml
  manifests/o/ownCloud/ownCloudDesktop/5.2.0.12726/ownCloud.ownCloudDesktop.locale.zh-CN.yaml
  manifests/o/ownCloud/ownCloudDesktop/5.2.0.12726/ownCloud.ownCloudDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128802 New version: ByteDance.StreamingTool version 6.6.3
  manifests/b/ByteDance/StreamingTool/6.6.3/ByteDance.StreamingTool.installer.yaml
  manifests/b/ByteDance/StreamingTool/6.6.3/ByteDance.StreamingTool.locale.en-US.yaml
  manifests/b/ByteDance/StreamingTool/6.6.3/ByteDance.StreamingTool.locale.zh-CN.yaml
  manifests/b/ByteDance/StreamingTool/6.6.3/ByteDance.StreamingTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128801 New version: DoltHub.Dolt version 1.29.0
  manifests/d/DoltHub/Dolt/1.29.0/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.29.0/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.29.0/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128793 New version: LinwoodCloud.Butterfly.Nightly version 2.0.0-rc.0
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-rc.0/LinwoodCloud.Butterfly.Nightly.installer.yaml
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-rc.0/LinwoodCloud.Butterfly.Nightly.locale.en-US.yaml
  manifests/l/LinwoodCloud/Butterfly/Nightly/2.0.0-rc.0/LinwoodCloud.Butterfly.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#128790 eloston.ungoogled-chromium version 119.0.6045.199
  manifests/e/eloston/ungoogled-chromium/119.0.6045.199/eloston.ungoogled-chromium.installer.yaml
  manifests/e/eloston/ungoogled-chromium/119.0.6045.199/eloston.ungoogled-chromium.locale.en-US.yaml
  manifests/e/eloston/ungoogled-chromium/119.0.6045.199/eloston.ungoogled-chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128789 New version: OwlPlug.OwlPlug version 1.25.0
  manifests/o/OwlPlug/OwlPlug/1.25.0/OwlPlug.OwlPlug.installer.yaml
  manifests/o/OwlPlug/OwlPlug/1.25.0/OwlPlug.OwlPlug.locale.en-US.yaml
  manifests/o/OwlPlug/OwlPlug/1.25.0/OwlPlug.OwlPlug.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128712 New package: prefix-dev.pixi version 0.9.1
  manifests/p/prefix-dev/pixi/0.9.1/prefix-dev.pixi.installer.yaml
  manifests/p/prefix-dev/pixi/0.9.1/prefix-dev.pixi.locale.en-US.yaml
  manifests/p/prefix-dev/pixi/0.9.1/prefix-dev.pixi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#128772 Update metadata: OpenJS.NodeJS version 21.3.0
  manifests/o/OpenJS/NodeJS/21.3.0/OpenJS.NodeJS.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128774 New version: JetBrains.QodanaCLI version 2023.2.9
  manifests/j/JetBrains/QodanaCLI/2023.2.9/JetBrains.QodanaCLI.installer.yaml
  manifests/j/JetBrains/QodanaCLI/2023.2.9/JetBrains.QodanaCLI.locale.en-US.yaml
  manifests/j/JetBrains/QodanaCLI/2023.2.9/JetBrains.QodanaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128777 New version: Treexy.DriverFusion version 11.1.0.2
  manifests/t/Treexy/DriverFusion/11.1.0.2/Treexy.DriverFusion.installer.yaml
  manifests/t/Treexy/DriverFusion/11.1.0.2/Treexy.DriverFusion.locale.en-US.yaml
  manifests/t/Treexy/DriverFusion/11.1.0.2/Treexy.DriverFusion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128783 New version: VGN.VHUB version 2.3.15
  manifests/v/VGN/VHUB/2.3.15/VGN.VHUB.installer.yaml
  manifests/v/VGN/VHUB/2.3.15/VGN.VHUB.locale.en-US.yaml
  manifests/v/VGN/VHUB/2.3.15/VGN.VHUB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128784 New version: yt-dlp.yt-dlp.nightly version 2023.11.29.232714
  manifests/y/yt-dlp/yt-dlp/nightly/2023.11.29.232714/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2023.11.29.232714/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2023.11.29.232714/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128788 New version: gaphor.gaphor 2.22.1
  manifests/g/gaphor/gaphor/2.22.1/gaphor.gaphor.installer.yaml
  manifests/g/gaphor/gaphor/2.22.1/gaphor.gaphor.locale.en-US.yaml
  manifests/g/gaphor/gaphor/2.22.1/gaphor.gaphor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128787 New version: YuzuEmu.Yuzu.Mainline version 1638
  manifests/y/YuzuEmu/Yuzu/Mainline/1638/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1638/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1638/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#128817 New version: Wondershare.DemoCreator version 7.0.1
  manifests/w/Wondershare/DemoCreator/7.0.1/Wondershare.DemoCreator.installer.yaml
  manifests/w/Wondershare/DemoCreator/7.0.1/Wondershare.DemoCreator.locale.en-US.yaml
  manifests/w/Wondershare/DemoCreator/7.0.1/Wondershare.DemoCreator.locale.zh-CN.yaml
  manifests/w/Wondershare/DemoCreator/7.0.1/Wondershare.DemoCreator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#128819 New version: BartoszCichecki.LenovoLegionToolkit version 2.17.0
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.17.0/BartoszCichecki.LenovoLegionToolkit.installer.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.17.0/BartoszCichecki.LenovoLegionToolkit.locale.en-US.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.17.0/BartoszCichecki.LenovoLegionToolkit.locale.zh-CN.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.17.0/BartoszCichecki.LenovoLegionToolkit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128820 New version: 7S2P.Effie.CN version 3.0.11
  manifests/7/7S2P/Effie/CN/3.0.11/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.0.11/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.0.11/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.0.11/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128824 Add Bruno.Bruno 1.3.0
  manifests/b/Bruno/Bruno/1.3.0/Bruno.Bruno.installer.yaml
  manifests/b/Bruno/Bruno/1.3.0/Bruno.Bruno.locale.en-US.yaml
  manifests/b/Bruno/Bruno/1.3.0/Bruno.Bruno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128831 New version: vim.vim.nightly version 9.0.2143
  manifests/v/vim/vim/nightly/9.0.2143/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.2143/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.2143/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128835 New version: twpayne.chezmoi 2.42.2
  manifests/t/twpayne/chezmoi/2.42.2/twpayne.chezmoi.installer.yaml
  manifests/t/twpayne/chezmoi/2.42.2/twpayne.chezmoi.locale.en-US.yaml
  manifests/t/twpayne/chezmoi/2.42.2/twpayne.chezmoi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128832 Remove extra version of TechNobo.TcNoAccountSwitcher
  manifests/t/TechNobo/TcNoAccountSwitcher/2023-07-05_00/TechNobo.TcNoAccountSwitcher.installer.yaml
  manifests/t/TechNobo/TcNoAccountSwitcher/2023-07-05_00/TechNobo.TcNoAccountSwitcher.locale.en-US.yaml
  manifests/t/TechNobo/TcNoAccountSwitcher/2023-07-05_00/TechNobo.TcNoAccountSwitcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128840 New version: PerfectWorld.PerfectWorldArena version 1.0.23120211
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120211/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120211/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120211/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.23120211/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128841 New version: InfiniteRed.Reactotron.Pre-release version 3.0.0.2277
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.2277/InfiniteRed.Reactotron.Pre-release.installer.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.2277/InfiniteRed.Reactotron.Pre-release.locale.en-US.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.2277/InfiniteRed.Reactotron.Pre-release.locale.zh-CN.yaml
  manifests/i/InfiniteRed/Reactotron/Pre-release/3.0.0.2277/InfiniteRed.Reactotron.Pre-release.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128839 New version: Google.GoogleDrive version 84.0.10.0
  manifests/g/Google/GoogleDrive/84.0.10.0/Google.GoogleDrive.installer.yaml
  manifests/g/Google/GoogleDrive/84.0.10.0/Google.GoogleDrive.locale.en-US.yaml
  manifests/g/Google/GoogleDrive/84.0.10.0/Google.GoogleDrive.locale.zh-CN.yaml
  manifests/g/Google/GoogleDrive/84.0.10.0/Google.GoogleDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128843 New version: Hashicorp.Terraform.Alpha version 1.7.0-alpha20231130
  manifests/h/Hashicorp/Terraform/Alpha/1.7.0-alpha20231130/Hashicorp.Terraform.Alpha.installer.yaml
  manifests/h/Hashicorp/Terraform/Alpha/1.7.0-alpha20231130/Hashicorp.Terraform.Alpha.locale.en-US.yaml
  manifests/h/Hashicorp/Terraform/Alpha/1.7.0-alpha20231130/Hashicorp.Terraform.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128837 New package: Ecks1337.RyuSAK version 1.6.3
  manifests/e/Ecks1337/RyuSAK/1.6.3/Ecks1337.RyuSAK.installer.yaml
  manifests/e/Ecks1337/RyuSAK/1.6.3/Ecks1337.RyuSAK.locale.en-US.yaml
  manifests/e/Ecks1337/RyuSAK/1.6.3/Ecks1337.RyuSAK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128848 New package: LilithGames.Dislyte version 0.0.2
  manifests/l/LilithGames/Dislyte/0.0.2/LilithGames.Dislyte.installer.yaml
  manifests/l/LilithGames/Dislyte/0.0.2/LilithGames.Dislyte.locale.en-US.yaml
  manifests/l/LilithGames/Dislyte/0.0.2/LilithGames.Dislyte.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128854 New package: DXAtlas.SSTVTools version 1.0
  manifests/d/dxatlas/SSTVTools/1.0/dxatlas.SSTVTools.installer.yaml
  manifests/d/dxatlas/SSTVTools/1.0/dxatlas.SSTVTools.locale.en-US.yaml
  manifests/d/dxatlas/SSTVTools/1.0/dxatlas.SSTVTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128860 New version: GPSoftware.DirectoryOpus version 12.33
  manifests/g/GPSoftware/DirectoryOpus/12.33/GPSoftware.DirectoryOpus.installer.yaml
  manifests/g/GPSoftware/DirectoryOpus/12.33/GPSoftware.DirectoryOpus.locale.en-US.yaml
  manifests/g/GPSoftware/DirectoryOpus/12.33/GPSoftware.DirectoryOpus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128861 CloudNet 1.36.2.13
  manifests/c/cloudnet/cloudnet/1.36.2.13/cloudnet.cloudnet.installer.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.13/cloudnet.cloudnet.locale.zh-CN.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.13/cloudnet.cloudnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128864 New version: Sandboxie.Classic version 5.67.3
  manifests/s/Sandboxie/Classic/5.67.3/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.67.3/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.67.3/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128865 New version: Sandboxie.Plus version 1.12.3
  manifests/s/Sandboxie/Plus/1.12.3/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.12.3/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.12.3/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128866 New version: th-ch.YouTubeMusic version 3.0.1
  manifests/t/th-ch/YouTubeMusic/3.0.1/th-ch.YouTubeMusic.installer.yaml
  manifests/t/th-ch/YouTubeMusic/3.0.1/th-ch.YouTubeMusic.locale.en-US.yaml
  manifests/t/th-ch/YouTubeMusic/3.0.1/th-ch.YouTubeMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128868 New version: OpenWhisperSystems.Signal version 6.40.0
  manifests/o/OpenWhisperSystems/Signal/6.40.0/OpenWhisperSystems.Signal.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/6.40.0/OpenWhisperSystems.Signal.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/6.40.0/OpenWhisperSystems.Signal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128965 Fix KDE.Filelight 23.08.3 404 error
  manifests/k/KDE/Filelight/23.08.3/KDE.Filelight.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128947 New version: YuzuEmu.Yuzu.Mainline version 1639
  manifests/y/YuzuEmu/Yuzu/Mainline/1639/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1639/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1639/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128948 New version: c0re100.qBittorrent-Enhanced-Edition version 4.6.2.10
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.2.10/c0re100.qBittorrent-Enhanced-Edition.installer.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.2.10/c0re100.qBittorrent-Enhanced-Edition.locale.en-US.yaml
  manifests/c/c0re100/qBittorrent-Enhanced-Edition/4.6.2.10/c0re100.qBittorrent-Enhanced-Edition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128959 MoritzBunkus.MKVToolNix version 81.0.0
  manifests/m/MoritzBunkus/MKVToolNix/81.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/81.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/81.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/81.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128960 New version: th-ch.YouTubeMusic version 3.0.2
  manifests/t/th-ch/YouTubeMusic/3.0.2/th-ch.YouTubeMusic.installer.yaml
  manifests/t/th-ch/YouTubeMusic/3.0.2/th-ch.YouTubeMusic.locale.en-US.yaml
  manifests/t/th-ch/YouTubeMusic/3.0.2/th-ch.YouTubeMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129038 New version: vim.vim.nightly version 9.0.2146
  manifests/v/vim/vim/nightly/9.0.2146/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.0.2146/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.0.2146/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129030 New version: Tautulli.Tautulli version 2.13.3.1
  manifests/t/Tautulli/Tautulli/2.13.3.1/Tautulli.Tautulli.installer.yaml
  manifests/t/Tautulli/Tautulli/2.13.3.1/Tautulli.Tautulli.locale.en-US.yaml
  manifests/t/Tautulli/Tautulli/2.13.3.1/Tautulli.Tautulli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129027 New version: Upscayl.Upscayl version 2.9.4
  manifests/u/Upscayl/Upscayl/2.9.4/Upscayl.Upscayl.installer.yaml
  manifests/u/Upscayl/Upscayl/2.9.4/Upscayl.Upscayl.locale.en-US.yaml
  manifests/u/Upscayl/Upscayl/2.9.4/Upscayl.Upscayl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129024 New version: YuzuEmu.Yuzu.Mainline version 1640
  manifests/y/YuzuEmu/Yuzu/Mainline/1640/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1640/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1640/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#128991 Update Nilesoft Shell to 1.9.10
  manifests/n/Nilesoft/Shell/1.9.10/Nilesoft.Shell.installer.yaml
  manifests/n/Nilesoft/Shell/1.9.10/Nilesoft.Shell.locale.en-US.yaml
  manifests/n/Nilesoft/Shell/1.9.10/Nilesoft.Shell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129000 New version: NitrokeyGmbH.Nitropy version 0.4.43
  manifests/n/NitrokeyGmbH/Nitropy/0.4.43/NitrokeyGmbH.Nitropy.installer.yaml
  manifests/n/NitrokeyGmbH/Nitropy/0.4.43/NitrokeyGmbH.Nitropy.locale.en-US.yaml
  manifests/n/NitrokeyGmbH/Nitropy/0.4.43/NitrokeyGmbH.Nitropy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129003 New version: LiErHeXun.Quicker version 1.40.17.0
  manifests/l/LiErHeXun/Quicker/1.40.17.0/LiErHeXun.Quicker.installer.yaml
  manifests/l/LiErHeXun/Quicker/1.40.17.0/LiErHeXun.Quicker.locale.en-US.yaml
  manifests/l/LiErHeXun/Quicker/1.40.17.0/LiErHeXun.Quicker.locale.zh-CN.yaml
  manifests/l/LiErHeXun/Quicker/1.40.17.0/LiErHeXun.Quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129005 New version: monkeyWie.Gopeed version 1.5.1
  manifests/m/monkeyWie/Gopeed/1.5.1/monkeyWie.Gopeed.installer.yaml
  manifests/m/monkeyWie/Gopeed/1.5.1/monkeyWie.Gopeed.locale.en-US.yaml
  manifests/m/monkeyWie/Gopeed/1.5.1/monkeyWie.Gopeed.locale.zh-CN.yaml
  manifests/m/monkeyWie/Gopeed/1.5.1/monkeyWie.Gopeed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129004 New version: Maxthon.Maxthon version 7.1.7.8000
  manifests/m/Maxthon/Maxthon/7.1.7.8000/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/7.1.7.8000/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/7.1.7.8000/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/7.1.7.8000/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129012 Add version: AppFlowy.AppFlowy version 0.2.4
  manifests/a/AppFlowy/AppFlowy/0.2.4/AppFlowy.AppFlowy.installer.yaml
  manifests/a/AppFlowy/AppFlowy/0.2.4/AppFlowy.AppFlowy.locale.en-US.yaml
  manifests/a/AppFlowy/AppFlowy/0.2.4/AppFlowy.AppFlowy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129008 solemnwarning.rehex version 0.60.1
  manifests/s/solemnwarning/rehex/0.60.1/solemnwarning.rehex.installer.yaml
  manifests/s/solemnwarning/rehex/0.60.1/solemnwarning.rehex.locale.en-US.yaml
  manifests/s/solemnwarning/rehex/0.60.1/solemnwarning.rehex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129014 New package: CueLang.Cue version 0.6.0
  manifests/c/CueLang/Cue/0.6.0/CueLang.Cue.installer.yaml
  manifests/c/CueLang/Cue/0.6.0/CueLang.Cue.locale.en-US.yaml
  manifests/c/CueLang/Cue/0.6.0/CueLang.Cue.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129020 New package: Magicsplat.TclTk version 1.13.0
  manifests/m/Magicsplat/TclTk/1.13.0/Magicsplat.TclTk.installer.yaml
  manifests/m/Magicsplat/TclTk/1.13.0/Magicsplat.TclTk.locale.en-US.yaml
  manifests/m/Magicsplat/TclTk/1.13.0/Magicsplat.TclTk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Unapproved-URL

#129126 New version: OliverSchwendener.ueli version 8.27.0
  manifests/o/OliverSchwendener/ueli/8.27.0/OliverSchwendener.ueli.installer.yaml
  manifests/o/OliverSchwendener/ueli/8.27.0/OliverSchwendener.ueli.locale.en-US.yaml
  manifests/o/OliverSchwendener/ueli/8.27.0/OliverSchwendener.ueli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129161 New version: ImageLine.FLStudio version 21.2.1.3859
  manifests/i/ImageLine/FLStudio/21.2.1.3859/ImageLine.FLStudio.installer.yaml
  manifests/i/ImageLine/FLStudio/21.2.1.3859/ImageLine.FLStudio.locale.en-US.yaml
  manifests/i/ImageLine/FLStudio/21.2.1.3859/ImageLine.FLStudio.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#128847 Update LibreWolf.LibreWolf to v120.0.1-1
  manifests/l/LibreWolf/LibreWolf/120.0.1-1/LibreWolf.LibreWolf.installer.yaml
  manifests/l/LibreWolf/LibreWolf/120.0.1-1/LibreWolf.LibreWolf.locale.en-US.yaml
  manifests/l/LibreWolf/LibreWolf/120.0.1-1/LibreWolf.LibreWolf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Domain

#129124 SagerNet.sing-box version 1.7.2
  manifests/s/SagerNet/sing-box/1.7.2/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.7.2/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.7.2/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129123 delete old version of GamaAlpha
  manifests/g/GamaPlatform/GamaAlpha/1.9.3-ca4a0ca/GamaPlatform.GamaAlpha.installer.yaml
  manifests/g/GamaPlatform/GamaAlpha/1.9.3-ca4a0ca/GamaPlatform.GamaAlpha.locale.en-US.yaml
  manifests/g/GamaPlatform/GamaAlpha/1.9.3-ca4a0ca/GamaPlatform.GamaAlpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129145 New version: 2dust.v2rayN version 6.31
  manifests/2/2dust/v2rayN/6.31/2dust.v2rayN.installer.yaml
  manifests/2/2dust/v2rayN/6.31/2dust.v2rayN.locale.zh-CN.yaml
  manifests/2/2dust/v2rayN/6.31/2dust.v2rayN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#129146 New version: Splashtop.SplashtopBusiness version 3.6.200.0
  manifests/s/Splashtop/SplashtopBusiness/3.6.200.0/Splashtop.SplashtopBusiness.installer.yaml
  manifests/s/Splashtop/SplashtopBusiness/3.6.200.0/Splashtop.SplashtopBusiness.locale.en-US.yaml
  manifests/s/Splashtop/SplashtopBusiness/3.6.200.0/Splashtop.SplashtopBusiness.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129147 Fix KDE.Kdenlive URL 23.08.3
  manifests/k/KDE/Kdenlive/23.08.3/KDE.Kdenlive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129149 update xnview classic 2.51.5
  manifests/x/XnSoft/XnView/Classic/2.51.5/XnSoft.XnView.Classic.installer.yaml
  manifests/x/XnSoft/XnView/Classic/2.51.5/XnSoft.XnView.Classic.locale.en-US.yaml
  manifests/x/XnSoft/XnView/Classic/2.51.5/XnSoft.XnView.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129151 Add Bruno.Bruno 1.3.1
  manifests/b/Bruno/Bruno/1.3.1/Bruno.Bruno.installer.yaml
  manifests/b/Bruno/Bruno/1.3.1/Bruno.Bruno.locale.en-US.yaml
  manifests/b/Bruno/Bruno/1.3.1/Bruno.Bruno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129154 KurtZimmermann.RegCool version 1.348
  manifests/k/KurtZimmermann/RegCool/1.348/KurtZimmermann.RegCool.installer.yaml
  manifests/k/KurtZimmermann/RegCool/1.348/KurtZimmermann.RegCool.locale.en-us.yaml
  manifests/k/KurtZimmermann/RegCool/1.348/KurtZimmermann.RegCool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129162 New version: IVPN.IVPN version 3.13.4
  manifests/i/IVPN/IVPN/3.13.4/IVPN.IVPN.installer.yaml
  manifests/i/IVPN/IVPN/3.13.4/IVPN.IVPN.locale.en-US.yaml
  manifests/i/IVPN/IVPN/3.13.4/IVPN.IVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129164 New version: Nethermind.Nethermind version 1.23.0
  manifests/n/Nethermind/Nethermind/1.23.0/Nethermind.Nethermind.installer.yaml
  manifests/n/Nethermind/Nethermind/1.23.0/Nethermind.Nethermind.locale.en-US.yaml
  manifests/n/Nethermind/Nethermind/1.23.0/Nethermind.Nethermind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129165 matchmycolor.Colibri version 23.2.0.12171
  manifests/m/matchmycolor/Colibri/23.2.0.12171/matchmycolor.Colibri.installer.yaml
  manifests/m/matchmycolor/Colibri/23.2.0.12171/matchmycolor.Colibri.locale.en-US.yaml
  manifests/m/matchmycolor/Colibri/23.2.0.12171/matchmycolor.Colibri.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
