Repository microsoft/winget-pkgs, pull requests merged in 2024-06, with the labels that each got.

#155919 Create WinGet package for March 2024 GDK Update 2
  manifests/m/Microsoft/GDK/2403/240302/Microsoft.GDK.2403.installer.yaml
  manifests/m/Microsoft/GDK/2403/240302/Microsoft.GDK.2403.locale.en-US.yaml
  manifests/m/Microsoft/GDK/2403/240302/Microsoft.GDK.2403.locale.ja-JP.yaml
  manifests/m/Microsoft/GDK/2403/240302/Microsoft.GDK.2403.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#155923 New version: rink-turksma.IntunePrepTool version 1.4.7.0
  manifests/r/rink-turksma/IntunePrepTool/1.4.7.0/rink-turksma.IntunePrepTool.installer.yaml
  manifests/r/rink-turksma/IntunePrepTool/1.4.7.0/rink-turksma.IntunePrepTool.locale.en-US.yaml
  manifests/r/rink-turksma/IntunePrepTool/1.4.7.0/rink-turksma.IntunePrepTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, New-Manifest

#155928 New version: Google.AndroidStudio.Canary version 2024.1.2.3
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.3/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.3/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.3/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#155929 New version: Google.AndroidStudio.Canary version 2024.1.2.4
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.4/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.4/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.2.4/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, New-Manifest

#155931 Fix: 7zip.7zip version 24.05
  manifests/7/7zip/7zip/24.05/7zip.7zip.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155933 New version: schollz.croc version 10.0.7
  manifests/s/schollz/croc/10.0.7/schollz.croc.installer.yaml
  manifests/s/schollz/croc/10.0.7/schollz.croc.locale.en-US.yaml
  manifests/s/schollz/croc/10.0.7/schollz.croc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#155936 Modify: calibre.calibre version 7.11.0
  manifests/c/calibre/calibre/7.11.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/7.11.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/7.11.0/calibre.calibre.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155937 Modify: calibre.calibre version 7.10.0
  manifests/c/calibre/calibre/7.10.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/7.10.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/7.10.0/calibre.calibre.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155938 Modify: calibre.calibre version 7.9.0
  manifests/c/calibre/calibre/7.9.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/7.9.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/7.9.0/calibre.calibre.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155939 Modify: calibre.calibre version 7.8.0
  manifests/c/calibre/calibre/7.8.0/calibre.calibre.installer.yaml
  manifests/c/calibre/calibre/7.8.0/calibre.calibre.locale.en-US.yaml
  manifests/c/calibre/calibre/7.8.0/calibre.calibre.locale.zh-CN.yaml
  manifests/c/calibre/calibre/7.8.0/calibre.calibre.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155941 New version: AssetRipper.AssetRipper version 1.0.15
  manifests/a/AssetRipper/AssetRipper/1.0.15/AssetRipper.AssetRipper.installer.yaml
  manifests/a/AssetRipper/AssetRipper/1.0.15/AssetRipper.AssetRipper.locale.en-US.yaml
  manifests/a/AssetRipper/AssetRipper/1.0.15/AssetRipper.AssetRipper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#155943 New version: Google.Chrome.Canary version 127.0.6514.0
  manifests/g/Google/Chrome/Canary/127.0.6514.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/127.0.6514.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/127.0.6514.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/127.0.6514.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/127.0.6514.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#155944 Add new version: Taozuhong.Kangaroo v5.0.0.240601
  manifests/t/Taozuhong/Kangaroo/5.0.0.240601/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/5.0.0.240601/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/5.0.0.240601/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/5.0.0.240601/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#155945 New version: Emurasoft.EmEditor version 24.2.1
  manifests/e/Emurasoft/EmEditor/24.2.1/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/24.2.1/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/24.2.1/Emurasoft.EmEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#155720 New version: Unity.Unity.2021 version 2021.3.39f1
  manifests/u/Unity/Unity/2021/2021.3.39f1/Unity.Unity.2021.installer.yaml
  manifests/u/Unity/Unity/2021/2021.3.39f1/Unity.Unity.2021.locale.en-US.yaml
  manifests/u/Unity/Unity/2021/2021.3.39f1/Unity.Unity.2021.locale.zh-CN.yaml
  manifests/u/Unity/Unity/2021/2021.3.39f1/Unity.Unity.2021.yaml
Labels: Validation-Completed, Internal-Error-Dynamic-Scan, Retry-1, Needs-Attention, Validation-Retry

#155719 New version: Unity.Unity.2022 version 2022.3.31f1
  manifests/u/Unity/Unity/2022/2022.3.31f1/Unity.Unity.2022.installer.yaml
  manifests/u/Unity/Unity/2022/2022.3.31f1/Unity.Unity.2022.locale.en-US.yaml
  manifests/u/Unity/Unity/2022/2022.3.31f1/Unity.Unity.2022.locale.zh-CN.yaml
  manifests/u/Unity/Unity/2022/2022.3.31f1/Unity.Unity.2022.yaml
Labels: Validation-Completed, Retry-1

#156135 JanDeDobbeleer.OhMyPosh version 21.1.0
  manifests/j/JanDeDobbeleer/OhMyPosh/21.1.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/21.1.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/21.1.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#145045 Remove: Julialang.Julia.LTS version 1.6.7
  manifests/j/Julialang/Julia/LTS/1.6.7/Julialang.Julia.LTS.installer.yaml
  manifests/j/Julialang/Julia/LTS/1.6.7/Julialang.Julia.LTS.locale.en-US.yaml
  manifests/j/Julialang/Julia/LTS/1.6.7/Julialang.Julia.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Last-Version-Remaining

#156183 New version: Jackett.Jackett version 0.21.2943
  manifests/j/Jackett/Jackett/0.21.2943/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.2943/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.2943/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156335 Microsoft.VisualStudioCode.Insiders.CLI_v1.90.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.90.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156363 JanDeDobbeleer.OhMyPosh version 21.2.0
  manifests/j/JanDeDobbeleer/OhMyPosh/21.2.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/21.2.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/21.2.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156334 Microsoft.VisualStudioCode.Insiders_v1.90.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.90.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156316 Remove luyuhuang.DWords2 0.2.3 to LuyuHuang.DWords2 0.2.3
  manifests/l/luyuhuang/DWords2/0.2.3/luyuhuang.DWords2.installer.yaml
  manifests/l/luyuhuang/DWords2/0.2.3/luyuhuang.DWords2.locale.en-US.yaml
  manifests/l/luyuhuang/DWords2/0.2.3/luyuhuang.DWords2.locale.zh-CN.yaml
  manifests/l/luyuhuang/DWords2/0.2.3/luyuhuang.DWords2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156310 Remove luyuhuang.DWords2 0.2.0 to LuyuHuang.DWords2 0.2.0
  manifests/l/luyuhuang/DWords2/0.2.0/luyuhuang.DWords2.installer.yaml
  manifests/l/luyuhuang/DWords2/0.2.0/luyuhuang.DWords2.locale.en-US.yaml
  manifests/l/luyuhuang/DWords2/0.2.0/luyuhuang.DWords2.locale.zh-CN.yaml
  manifests/l/luyuhuang/DWords2/0.2.0/luyuhuang.DWords2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156298 Remove qier222.yesplaymusic 0.4.4 to qier222.YesPlayMusic 0.4.4
  manifests/q/qier222/yesplaymusic/0.4.4/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.4/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.4/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156296 Remove qier222.yesplaymusic 0.4.3 to qier222.YesPlayMusic 0.4.3
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.3/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156282 Remove qier222.yesplaymusic 0.3.6 to qier222.YesPlayMusic 0.3.6
  manifests/q/qier222/yesplaymusic/0.3.6/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.6/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.6/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156280 Remove qier222.yesplaymusic 0.3.5 to qier222.YesPlayMusic 0.3.5
  manifests/q/qier222/yesplaymusic/0.3.5/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.5/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.5/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156284 Remove qier222.yesplaymusic 0.3.7 to qier222.YesPlayMusic 0.3.7
  manifests/q/qier222/yesplaymusic/0.3.7/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.7/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.7/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156300 Remove qier222.yesplaymusic 0.4.5 to qier222.YesPlayMusic 0.4.5
  manifests/q/qier222/yesplaymusic/0.4.5/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.5/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.5/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156302 Remove qier222.yesplaymusic 0.4.6 to qier222.YesPlayMusic 0.4.6
  manifests/q/qier222/yesplaymusic/0.4.6/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.6/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.6/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156375 Modify: voidtools.Everything version 1.4.1.1022
  manifests/v/voidtools/Everything/1.4.1.1022/voidtools.Everything.installer.yaml
  manifests/v/voidtools/Everything/1.4.1.1022/voidtools.Everything.locale.en-US.yaml
  manifests/v/voidtools/Everything/1.4.1.1022/voidtools.Everything.locale.zh-CN.yaml
  manifests/v/voidtools/Everything/1.4.1.1022/voidtools.Everything.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156373 Modify: voidtools.Everything.Lite version 1.4.1.1024
  manifests/v/voidtools/Everything/Lite/1.4.1.1024/voidtools.Everything.Lite.installer.yaml
  manifests/v/voidtools/Everything/Lite/1.4.1.1024/voidtools.Everything.Lite.locale.en-US.yaml
  manifests/v/voidtools/Everything/Lite/1.4.1.1024/voidtools.Everything.Lite.locale.zh-CN.yaml
  manifests/v/voidtools/Everything/Lite/1.4.1.1024/voidtools.Everything.Lite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156294 Remove qier222.yesplaymusic 0.4.2 to qier222.YesPlayMusic 0.4.2
  manifests/q/qier222/yesplaymusic/0.4.2/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.2/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.2/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156288 Remove qier222.yesplaymusic 0.3.9 to qier222.YesPlayMusic 0.3.9
  manifests/q/qier222/yesplaymusic/0.3.9/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.9/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.9/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156292 Remove qier222.yesplaymusic 0.4.1 to qier222.YesPlayMusic 0.4.1
  manifests/q/qier222/yesplaymusic/0.4.1/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.1/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.1/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156290 Remove qier222.yesplaymusic 0.4.0 to qier222.YesPlayMusic 0.4.0
  manifests/q/qier222/yesplaymusic/0.4.0/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.4.0/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.4.0/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156374 Modify: voidtools.Everything version 1.4.1.1023
  manifests/v/voidtools/Everything/1.4.1.1023/voidtools.Everything.installer.yaml
  manifests/v/voidtools/Everything/1.4.1.1023/voidtools.Everything.locale.en-US.yaml
  manifests/v/voidtools/Everything/1.4.1.1023/voidtools.Everything.locale.zh-CN.yaml
  manifests/v/voidtools/Everything/1.4.1.1023/voidtools.Everything.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156286 Remove qier222.yesplaymusic 0.3.8 to qier222.YesPlayMusic 0.3.8
  manifests/q/qier222/yesplaymusic/0.3.8/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.8/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.8/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156306 Remove luyuhuang.DWords2 0.0.3 to LuyuHuang.DWords2 0.0.3
  manifests/l/luyuhuang/DWords2/0.0.3/luyuhuang.DWords2.installer.yaml
  manifests/l/luyuhuang/DWords2/0.0.3/luyuhuang.DWords2.locale.en-US.yaml
  manifests/l/luyuhuang/DWords2/0.0.3/luyuhuang.DWords2.locale.zh-CN.yaml
  manifests/l/luyuhuang/DWords2/0.0.3/luyuhuang.DWords2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156314 Remove luyuhuang.DWords2 0.2.2 to LuyuHuang.DWords2 0.2.2
  manifests/l/luyuhuang/DWords2/0.2.2/luyuhuang.DWords2.installer.yaml
  manifests/l/luyuhuang/DWords2/0.2.2/luyuhuang.DWords2.locale.en-US.yaml
  manifests/l/luyuhuang/DWords2/0.2.2/luyuhuang.DWords2.locale.zh-CN.yaml
  manifests/l/luyuhuang/DWords2/0.2.2/luyuhuang.DWords2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156356 Update: Alibaba.Yuque version 3.4.3
  manifests/a/Alibaba/Yuque/3.4.3/Alibaba.Yuque.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156276 Remove qier222.yesplaymusic 0.3.3 to qier222.YesPlayMusic 0.3.3
  manifests/q/qier222/yesplaymusic/0.3.3/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.3/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.3/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156270 Remove qier222.yesplaymusic 0.3.0 to qier222.YesPlayMusic 0.3.0
  manifests/q/qier222/yesplaymusic/0.3.0/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.0/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.0/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156264 Remove qier222.yesplaymusic 0.2.3 to qier222.YesPlayMusic 0.2.3
  manifests/q/qier222/yesplaymusic/0.2.3/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.2.3/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.2.3/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156260 Remove qier222.yesplaymusic 0.2.1 to qier222.YesPlayMusic 0.2.1
  manifests/q/qier222/yesplaymusic/0.2.1/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.2.1/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.2.1/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156262 Remove qier222.yesplaymusic 0.2.2 to qier222.YesPlayMusic 0.2.2
  manifests/q/qier222/yesplaymusic/0.2.2/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.2.2/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.2.2/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156257 Move PDQ.Deploy 19.3.559.0 to PDQ.PDQDeploy 19.3.559.0
  manifests/p/PDQ/PDQDeploy/19.3.559.0/PDQ.PDQDeploy.installer.yaml
  manifests/p/PDQ/PDQDeploy/19.3.559.0/PDQ.PDQDeploy.locale.en-US.yaml
  manifests/p/PDQ/PDQDeploy/19.3.559.0/PDQ.PDQDeploy.locale.zh-CN.yaml
  manifests/p/PDQ/PDQDeploy/19.3.559.0/PDQ.PDQDeploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#156256 Remove PDQ.Deploy 19.3.553.0 to PDQ.PDQDeploy 19.3.553.0
  manifests/p/PDQ/Deploy/19.3.553.0/PDQ.Deploy.installer.yaml
  manifests/p/PDQ/Deploy/19.3.553.0/PDQ.Deploy.locale.en-US.yaml
  manifests/p/PDQ/Deploy/19.3.553.0/PDQ.Deploy.locale.zh-CN.yaml
  manifests/p/PDQ/Deploy/19.3.553.0/PDQ.Deploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156258 Remove PDQ.Deploy 19.3.559.0 to PDQ.PDQDeploy 19.3.559.0
  manifests/p/PDQ/Deploy/19.3.559.0/PDQ.Deploy.installer.yaml
  manifests/p/PDQ/Deploy/19.3.559.0/PDQ.Deploy.locale.en-US.yaml
  manifests/p/PDQ/Deploy/19.3.559.0/PDQ.Deploy.locale.zh-CN.yaml
  manifests/p/PDQ/Deploy/19.3.559.0/PDQ.Deploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156278 Remove qier222.yesplaymusic 0.3.4 to qier222.YesPlayMusic 0.3.4
  manifests/q/qier222/yesplaymusic/0.3.4/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.4/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.4/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156272 Remove qier222.yesplaymusic 0.3.1 to qier222.YesPlayMusic 0.3.1
  manifests/q/qier222/yesplaymusic/0.3.1/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.1/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.1/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156274 Remove qier222.yesplaymusic 0.3.2 to qier222.YesPlayMusic 0.3.2
  manifests/q/qier222/yesplaymusic/0.3.2/qier222.yesplaymusic.installer.yaml
  manifests/q/qier222/yesplaymusic/0.3.2/qier222.yesplaymusic.locale.en-US.yaml
  manifests/q/qier222/yesplaymusic/0.3.2/qier222.yesplaymusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156254 Remove PDQ.Deploy 19.3.538.0 to PDQ.PDQDeploy 19.3.538.0
  manifests/p/PDQ/Deploy/19.3.538.0/PDQ.Deploy.installer.yaml
  manifests/p/PDQ/Deploy/19.3.538.0/PDQ.Deploy.locale.en-US.yaml
  manifests/p/PDQ/Deploy/19.3.538.0/PDQ.Deploy.locale.zh-CN.yaml
  manifests/p/PDQ/Deploy/19.3.538.0/PDQ.Deploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156253 Move PDQ.Deploy 19.3.538.0 to PDQ.PDQDeploy 19.3.538.0
  manifests/p/PDQ/PDQDeploy/19.3.538.0/PDQ.PDQDeploy.installer.yaml
  manifests/p/PDQ/PDQDeploy/19.3.538.0/PDQ.PDQDeploy.locale.en-US.yaml
  manifests/p/PDQ/PDQDeploy/19.3.538.0/PDQ.PDQDeploy.locale.zh-CN.yaml
  manifests/p/PDQ/PDQDeploy/19.3.538.0/PDQ.PDQDeploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#156308 Remove luyuhuang.DWords2 0.1.0 to LuyuHuang.DWords2 0.1.0
  manifests/l/luyuhuang/DWords2/0.1.0/luyuhuang.DWords2.installer.yaml
  manifests/l/luyuhuang/DWords2/0.1.0/luyuhuang.DWords2.locale.en-US.yaml
  manifests/l/luyuhuang/DWords2/0.1.0/luyuhuang.DWords2.locale.zh-CN.yaml
  manifests/l/luyuhuang/DWords2/0.1.0/luyuhuang.DWords2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156370 New version: CentStudio.CentBrowser version 5.1.1130.122
  manifests/c/CentStudio/CentBrowser/5.1.1130.122/CentStudio.CentBrowser.installer.yaml
  manifests/c/CentStudio/CentBrowser/5.1.1130.122/CentStudio.CentBrowser.locale.en-US.yaml
  manifests/c/CentStudio/CentBrowser/5.1.1130.122/CentStudio.CentBrowser.locale.zh-CN.yaml
  manifests/c/CentStudio/CentBrowser/5.1.1130.122/CentStudio.CentBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156353 New version: LukiLabs.Craft version 1.38.0
  manifests/l/LukiLabs/Craft/1.38.0/LukiLabs.Craft.installer.yaml
  manifests/l/LukiLabs/Craft/1.38.0/LukiLabs.Craft.locale.en-US.yaml
  manifests/l/LukiLabs/Craft/1.38.0/LukiLabs.Craft.locale.zh-CN.yaml
  manifests/l/LukiLabs/Craft/1.38.0/LukiLabs.Craft.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156348 New version: Google.Chrome.Canary version 127.0.6517.0
  manifests/g/Google/Chrome/Canary/127.0.6517.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/127.0.6517.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/127.0.6517.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/127.0.6517.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/127.0.6517.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156342 New version: 7S2P.Effie.CN version 3.9.1
  manifests/7/7S2P/Effie/CN/3.9.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.9.1/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.9.1/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.9.1/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156251 New version: Tauri.create-tauri-app version 4.0.0
  manifests/t/Tauri/create-tauri-app/4.0.0/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/4.0.0/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/4.0.0/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/4.0.0/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156325 New version: Huawei.Welink version 7.41.3
  manifests/h/Huawei/Welink/7.41.3/Huawei.Welink.installer.yaml
  manifests/h/Huawei/Welink/7.41.3/Huawei.Welink.locale.en-US.yaml
  manifests/h/Huawei/Welink/7.41.3/Huawei.Welink.locale.zh-CN.yaml
  manifests/h/Huawei/Welink/7.41.3/Huawei.Welink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156323 New version: Hitencent.JisuPDF version 3.0.0.3030
  manifests/h/Hitencent/JisuPDF/3.0.0.3030/Hitencent.JisuPDF.installer.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3030/Hitencent.JisuPDF.locale.en-US.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3030/Hitencent.JisuPDF.locale.zh-CN.yaml
  manifests/h/Hitencent/JisuPDF/3.0.0.3030/Hitencent.JisuPDF.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156324 New version: Lenovo.SLBrowser version 9.0.3.5211
  manifests/l/Lenovo/SLBrowser/9.0.3.5211/Lenovo.SLBrowser.installer.yaml
  manifests/l/Lenovo/SLBrowser/9.0.3.5211/Lenovo.SLBrowser.locale.en-US.yaml
  manifests/l/Lenovo/SLBrowser/9.0.3.5211/Lenovo.SLBrowser.locale.zh-CN.yaml
  manifests/l/Lenovo/SLBrowser/9.0.3.5211/Lenovo.SLBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156219 New version: Hugo.Hugo version 0.126.3
  manifests/h/Hugo/Hugo/0.126.3/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.126.3/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.126.3/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.126.3/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156225 New version: MoritzBunkus.MKVToolNix version 85.0.0 (85.0)
  manifests/m/MoritzBunkus/MKVToolNix/85.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/85.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/85.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/85.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156218 New version: Hugo.Hugo.Extended version 0.126.3
  manifests/h/Hugo/Hugo/Extended/0.126.3/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.126.3/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.126.3/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.126.3/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156336 New version: Kingsoft.WPSOffice version 12.2.0.17119
  manifests/k/Kingsoft/WPSOffice/12.2.0.17119/Kingsoft.WPSOffice.installer.yaml
  manifests/k/Kingsoft/WPSOffice/12.2.0.17119/Kingsoft.WPSOffice.locale.en-US.yaml
  manifests/k/Kingsoft/WPSOffice/12.2.0.17119/Kingsoft.WPSOffice.locale.zh-CN.yaml
  manifests/k/Kingsoft/WPSOffice/12.2.0.17119/Kingsoft.WPSOffice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156127 New version: IBM.Semeru.21.JDK version 21.0.3.9
  manifests/i/IBM/Semeru/21/JDK/21.0.3.9/IBM.Semeru.21.JDK.installer.yaml
  manifests/i/IBM/Semeru/21/JDK/21.0.3.9/IBM.Semeru.21.JDK.locale.en-US.yaml
  manifests/i/IBM/Semeru/21/JDK/21.0.3.9/IBM.Semeru.21.JDK.locale.zh-CN.yaml
  manifests/i/IBM/Semeru/21/JDK/21.0.3.9/IBM.Semeru.21.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156192 New version: HelmutBuhler.8GadgetPack version 37.0.0
  manifests/h/HelmutBuhler/8GadgetPack/37.0.0/HelmutBuhler.8GadgetPack.installer.yaml
  manifests/h/HelmutBuhler/8GadgetPack/37.0.0/HelmutBuhler.8GadgetPack.locale.en-US.yaml
  manifests/h/HelmutBuhler/8GadgetPack/37.0.0/HelmutBuhler.8GadgetPack.locale.zh-CN.yaml
  manifests/h/HelmutBuhler/8GadgetPack/37.0.0/HelmutBuhler.8GadgetPack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#156149 New version: Google.Chrome.Canary version 127.0.6516.0
  manifests/g/Google/Chrome/Canary/127.0.6516.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/127.0.6516.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/127.0.6516.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/127.0.6516.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/127.0.6516.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156317 New version: iQIYI.iQIYI version 12.4.5.8126
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.installer.yaml
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.locale.en-US.yaml
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.locale.zh-CN.yaml
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.locale.zh-HK.yaml
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.locale.zh-TW.yaml
  manifests/i/iQIYI/iQIYI/12.4.5.8126/iQIYI.iQIYI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156220 New version: FutureScholars.Paperlib version 3.1.3
  manifests/f/FutureScholars/Paperlib/3.1.3/FutureScholars.Paperlib.installer.yaml
  manifests/f/FutureScholars/Paperlib/3.1.3/FutureScholars.Paperlib.locale.en-US.yaml
  manifests/f/FutureScholars/Paperlib/3.1.3/FutureScholars.Paperlib.locale.zh-CN.yaml
  manifests/f/FutureScholars/Paperlib/3.1.3/FutureScholars.Paperlib.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156128 New version: IBM.Semeru.21.JRE version 21.0.3.9
  manifests/i/IBM/Semeru/21/JRE/21.0.3.9/IBM.Semeru.21.JRE.installer.yaml
  manifests/i/IBM/Semeru/21/JRE/21.0.3.9/IBM.Semeru.21.JRE.locale.en-US.yaml
  manifests/i/IBM/Semeru/21/JRE/21.0.3.9/IBM.Semeru.21.JRE.locale.zh-CN.yaml
  manifests/i/IBM/Semeru/21/JRE/21.0.3.9/IBM.Semeru.21.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156208 New version: Mailbird.Mailbird version 3.0.14 (3.0.14.0)
  manifests/m/Mailbird/Mailbird/3.0.14/Mailbird.Mailbird.installer.yaml
  manifests/m/Mailbird/Mailbird/3.0.14/Mailbird.Mailbird.locale.en-US.yaml
  manifests/m/Mailbird/Mailbird/3.0.14/Mailbird.Mailbird.locale.zh-CN.yaml
  manifests/m/Mailbird/Mailbird/3.0.14/Mailbird.Mailbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156355 New version: viarotel.Escrcpy version 1.19.2
  manifests/v/viarotel/Escrcpy/1.19.2/viarotel.Escrcpy.installer.yaml
  manifests/v/viarotel/Escrcpy/1.19.2/viarotel.Escrcpy.locale.en-US.yaml
  manifests/v/viarotel/Escrcpy/1.19.2/viarotel.Escrcpy.locale.zh-CN.yaml
  manifests/v/viarotel/Escrcpy/1.19.2/viarotel.Escrcpy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156121 New version: DominikReichl.KeePass version 2.57.0 (2.57)
  manifests/d/DominikReichl/KeePass/2.57.0/DominikReichl.KeePass.installer.yaml
  manifests/d/DominikReichl/KeePass/2.57.0/DominikReichl.KeePass.locale.en-US.yaml
  manifests/d/DominikReichl/KeePass/2.57.0/DominikReichl.KeePass.locale.zh-CN.yaml
  manifests/d/DominikReichl/KeePass/2.57.0/DominikReichl.KeePass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156364 New version: Alibaba.UCCloudDrive version 1.5.0
  manifests/a/Alibaba/UCCloudDrive/1.5.0/Alibaba.UCCloudDrive.installer.yaml
  manifests/a/Alibaba/UCCloudDrive/1.5.0/Alibaba.UCCloudDrive.locale.en-US.yaml
  manifests/a/Alibaba/UCCloudDrive/1.5.0/Alibaba.UCCloudDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/UCCloudDrive/1.5.0/Alibaba.UCCloudDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156365 New version: AngryMiao.AMMaster version 1.2.2
  manifests/a/AngryMiao/AMMaster/1.2.2/AngryMiao.AMMaster.installer.yaml
  manifests/a/AngryMiao/AMMaster/1.2.2/AngryMiao.AMMaster.locale.en-US.yaml
  manifests/a/AngryMiao/AMMaster/1.2.2/AngryMiao.AMMaster.locale.zh-CN.yaml
  manifests/a/AngryMiao/AMMaster/1.2.2/AngryMiao.AMMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156152 New version: Ollama.Ollama version 0.1.40
  manifests/o/Ollama/Ollama/0.1.40/Ollama.Ollama.installer.yaml
  manifests/o/Ollama/Ollama/0.1.40/Ollama.Ollama.locale.en-US.yaml
  manifests/o/Ollama/Ollama/0.1.40/Ollama.Ollama.locale.zh-CN.yaml
  manifests/o/Ollama/Ollama/0.1.40/Ollama.Ollama.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156352 New version: Bandisoft.BandiView version 7.03 (25087)
  manifests/b/Bandisoft/BandiView/7.03/Bandisoft.BandiView.installer.yaml
  manifests/b/Bandisoft/BandiView/7.03/Bandisoft.BandiView.locale.en-US.yaml
  manifests/b/Bandisoft/BandiView/7.03/Bandisoft.BandiView.locale.zh-CN.yaml
  manifests/b/Bandisoft/BandiView/7.03/Bandisoft.BandiView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156119 New version: Julialang.Juliaup version 1.14.8.0
  manifests/j/Julialang/Juliaup/1.14.8.0/Julialang.Juliaup.installer.yaml
  manifests/j/Julialang/Juliaup/1.14.8.0/Julialang.Juliaup.locale.en-US.yaml
  manifests/j/Julialang/Juliaup/1.14.8.0/Julialang.Juliaup.locale.zh-CN.yaml
  manifests/j/Julialang/Juliaup/1.14.8.0/Julialang.Juliaup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#156319 Modify: iQIYI.GeePlayer version 5.7.0.5500
  manifests/i/iQIYI/GeePlayer/5.7.0.5500/iQIYI.GeePlayer.installer.yaml
  manifests/i/iQIYI/GeePlayer/5.7.0.5500/iQIYI.GeePlayer.locale.en-US.yaml
  manifests/i/iQIYI/GeePlayer/5.7.0.5500/iQIYI.GeePlayer.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156178 Modify: Bopsoft.Listary version 6.3
  manifests/b/Bopsoft/Listary/6.3/Bopsoft.Listary.installer.yaml
  manifests/b/Bopsoft/Listary/6.3/Bopsoft.Listary.locale.en-US.yaml
  manifests/b/Bopsoft/Listary/6.3/Bopsoft.Listary.locale.zh-CN.yaml
  manifests/b/Bopsoft/Listary/6.3/Bopsoft.Listary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156172 Modify: SpecialK.SpecialK version 24.5.13
  manifests/s/SpecialK/SpecialK/24.5.13/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/24.5.13/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/24.5.13/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/24.5.13/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156173 Modify: Mailbird.Mailbird version 3.0.13
  manifests/m/Mailbird/Mailbird/3.0.13/Mailbird.Mailbird.installer.yaml
  manifests/m/Mailbird/Mailbird/3.0.13/Mailbird.Mailbird.locale.en-US.yaml
  manifests/m/Mailbird/Mailbird/3.0.13/Mailbird.Mailbird.locale.zh-CN.yaml
  manifests/m/Mailbird/Mailbird/3.0.13/Mailbird.Mailbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156169 Modify: Sky.SkyGo version 24.1.3.0
  manifests/s/Sky/SkyGo/24.1.3.0/Sky.SkyGo.installer.yaml
  manifests/s/Sky/SkyGo/24.1.3.0/Sky.SkyGo.locale.de-DE.yaml
  manifests/s/Sky/SkyGo/24.1.3.0/Sky.SkyGo.locale.en-GB.yaml
  manifests/s/Sky/SkyGo/24.1.3.0/Sky.SkyGo.locale.zh-CN.yaml
  manifests/s/Sky/SkyGo/24.1.3.0/Sky.SkyGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156061 Modify: OpenJS.NodeJS.LTS version 20.12.1
  manifests/o/OpenJS/NodeJS/LTS/20.12.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.12.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.12.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.12.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156072 Update: GnuPG.GnuPG version 2.4.5
  manifests/g/GnuPG/GnuPG/2.4.5/GnuPG.GnuPG.installer.yaml
  manifests/g/GnuPG/GnuPG/2.4.5/GnuPG.GnuPG.locale.en-US.yaml
  manifests/g/GnuPG/GnuPG/2.4.5/GnuPG.GnuPG.locale.zh-CN.yaml
  manifests/g/GnuPG/GnuPG/2.4.5/GnuPG.GnuPG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156060 Modify: OpenJS.NodeJS.LTS version 20.11.1
  manifests/o/OpenJS/NodeJS/LTS/20.11.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.11.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.11.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.11.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156088 Modify: GeoGebra.GraphingCalculator version 6.0.843
  manifests/g/GeoGebra/GraphingCalculator/6.0.843/GeoGebra.GraphingCalculator.installer.yaml
  manifests/g/GeoGebra/GraphingCalculator/6.0.843/GeoGebra.GraphingCalculator.locale.en-US.yaml
  manifests/g/GeoGebra/GraphingCalculator/6.0.843/GeoGebra.GraphingCalculator.locale.zh-CN.yaml
  manifests/g/GeoGebra/GraphingCalculator/6.0.843/GeoGebra.GraphingCalculator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156037 Modify: OpenJS.NodeJS.LTS version 12.22.6
  manifests/o/OpenJS/NodeJS/LTS/12.22.6/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.6/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.6/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.6/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156084 Modify: GeoGebra.CalculatorSuite version 6.0.843
  manifests/g/GeoGebra/CalculatorSuite/6.0.843/GeoGebra.CalculatorSuite.installer.yaml
  manifests/g/GeoGebra/CalculatorSuite/6.0.843/GeoGebra.CalculatorSuite.locale.en-US.yaml
  manifests/g/GeoGebra/CalculatorSuite/6.0.843/GeoGebra.CalculatorSuite.locale.zh-CN.yaml
  manifests/g/GeoGebra/CalculatorSuite/6.0.843/GeoGebra.CalculatorSuite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156035 Modify: OpenJS.NodeJS.LTS version 12.22.4
  manifests/o/OpenJS/NodeJS/LTS/12.22.4/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.4/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.4/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.4/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156040 Modify: OpenJS.NodeJS.LTS version 12.22.11
  manifests/o/OpenJS/NodeJS/LTS/12.22.11/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.11/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.11/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.11/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156021 Modify: OpenJS.NodeJS.LTS version 6.11.5
  manifests/o/OpenJS/NodeJS/LTS/6.11.5/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.11.5/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.11.5/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.11.5/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156023 Modify: OpenJS.NodeJS.LTS version 6.12.2
  manifests/o/OpenJS/NodeJS/LTS/6.12.2/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.12.2/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.12.2/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/6.12.2/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156032 Modify: OpenJS.NodeJS.LTS version 12.20.1
  manifests/o/OpenJS/NodeJS/LTS/12.20.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.20.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.20.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.20.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156027 Modify: OpenJS.NodeJS.LTS version 8.11.3
  manifests/o/OpenJS/NodeJS/LTS/8.11.3/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/8.11.3/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/8.11.3/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/8.11.3/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155977 Modify: OpenJS.NodeJS version 21.6.0
  manifests/o/OpenJS/NodeJS/21.6.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.6.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.6.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.6.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156043 Modify: OpenJS.NodeJS.LTS version 14.20.0
  manifests/o/OpenJS/NodeJS/LTS/14.20.0/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.20.0/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.20.0/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.20.0/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156047 Modify: OpenJS.NodeJS.LTS version 18.17.1
  manifests/o/OpenJS/NodeJS/LTS/18.17.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.17.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.17.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.17.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155980 Modify: OpenJS.NodeJS version 21.7.0
  manifests/o/OpenJS/NodeJS/21.7.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.7.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.7.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.7.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155975 Modify: OpenJS.NodeJS version 21.3.0
  manifests/o/OpenJS/NodeJS/21.3.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.3.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.3.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.3.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155982 Modify: OpenJS.NodeJS version 21.7.2
  manifests/o/OpenJS/NodeJS/21.7.2/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.7.2/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.7.2/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.7.2/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156086 Modify: GeoGebra.CASCalculator version 6.0.843
  manifests/g/GeoGebra/CASCalculator/6.0.843/GeoGebra.CASCalculator.installer.yaml
  manifests/g/GeoGebra/CASCalculator/6.0.843/GeoGebra.CASCalculator.locale.en-US.yaml
  manifests/g/GeoGebra/CASCalculator/6.0.843/GeoGebra.CASCalculator.locale.zh-CN.yaml
  manifests/g/GeoGebra/CASCalculator/6.0.843/GeoGebra.CASCalculator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155981 Modify: OpenJS.NodeJS version 21.7.1
  manifests/o/OpenJS/NodeJS/21.7.1/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.7.1/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.7.1/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.7.1/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156036 Modify: OpenJS.NodeJS.LTS version 12.22.5
  manifests/o/OpenJS/NodeJS/LTS/12.22.5/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.5/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.5/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.5/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156065 Modify: OpenJS.NodeJS.LTS version 20.14.0
  manifests/o/OpenJS/NodeJS/LTS/20.14.0/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.14.0/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.14.0/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/20.14.0/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#156049 Modify: OpenJS.NodeJS.LTS version 18.18.1
  manifests/o/OpenJS/NodeJS/LTS/18.18.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156033 Modify: OpenJS.NodeJS.LTS version 12.22.2
  manifests/o/OpenJS/NodeJS/LTS/12.22.2/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.2/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.2/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/12.22.2/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156045 Modify: OpenJS.NodeJS.LTS version 16.20.1
  manifests/o/OpenJS/NodeJS/LTS/16.20.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/16.20.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/16.20.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/16.20.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156030 Modify: OpenJS.NodeJS.LTS version 10.16.1
  manifests/o/OpenJS/NodeJS/LTS/10.16.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/10.16.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/10.16.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/10.16.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156371 Update: Seewo.EasiClass version 1.0.0.2 (2.1.22.6393)
  manifests/s/Seewo/EasiClass/1.0.0.2/Seewo.EasiClass.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156041 Modify: OpenJS.NodeJS.LTS version 14.17.2
  manifests/o/OpenJS/NodeJS/LTS/14.17.2/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.17.2/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.17.2/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/14.17.2/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155967 Modify: OpenJS.NodeJS version 22.2.0
  manifests/o/OpenJS/NodeJS/22.2.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/22.2.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/22.2.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/22.2.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155968 Modify: OpenJS.NodeJS version 22.1.0
  manifests/o/OpenJS/NodeJS/22.1.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/22.1.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/22.1.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/22.1.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155983 Modify: OpenJS.NodeJS version 21.7.3
  manifests/o/OpenJS/NodeJS/21.7.3/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/21.7.3/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/21.7.3/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/21.7.3/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155971 Modify: OpenJS.NodeJS version 20.6.1
  manifests/o/OpenJS/NodeJS/20.6.1/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/20.6.1/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/20.6.1/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/20.6.1/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155970 Modify: OpenJS.NodeJS version 20.5.1
  manifests/o/OpenJS/NodeJS/20.5.1/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/20.5.1/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/20.5.1/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/20.5.1/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#155972 Modify: OpenJS.NodeJS version 20.7.0
  manifests/o/OpenJS/NodeJS/20.7.0/OpenJS.NodeJS.installer.yaml
  manifests/o/OpenJS/NodeJS/20.7.0/OpenJS.NodeJS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/20.7.0/OpenJS.NodeJS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/20.7.0/OpenJS.NodeJS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156106 New package: Julialang.Juliaup version 1.13.0.0
  manifests/j/Julialang/Juliaup/1.13.0.0/Julialang.Juliaup.installer.yaml
  manifests/j/Julialang/Juliaup/1.13.0.0/Julialang.Juliaup.locale.en-US.yaml
  manifests/j/Julialang/Juliaup/1.13.0.0/Julialang.Juliaup.locale.zh-CN.yaml
  manifests/j/Julialang/Juliaup/1.13.0.0/Julialang.Juliaup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#156074 New version: Google.Chrome.Canary version 127.0.6515.0
  manifests/g/Google/Chrome/Canary/127.0.6515.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/127.0.6515.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/127.0.6515.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/127.0.6515.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/127.0.6515.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156066 New version: Schniz.fnm version 1.37.0
  manifests/s/Schniz/fnm/1.37.0/Schniz.fnm.installer.yaml
  manifests/s/Schniz/fnm/1.37.0/Schniz.fnm.locale.en-US.yaml
  manifests/s/Schniz/fnm/1.37.0/Schniz.fnm.locale.zh-CN.yaml
  manifests/s/Schniz/fnm/1.37.0/Schniz.fnm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156093 New version: GeoGebra.Classic version 6.0.843
  manifests/g/GeoGebra/Classic/6.0.843/GeoGebra.Classic.installer.yaml
  manifests/g/GeoGebra/Classic/6.0.843/GeoGebra.Classic.locale.en-US.yaml
  manifests/g/GeoGebra/Classic/6.0.843/GeoGebra.Classic.locale.zh-CN.yaml
  manifests/g/GeoGebra/Classic/6.0.843/GeoGebra.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156056 Modify: OpenJS.NodeJS.LTS version 18.20.3
  manifests/o/OpenJS/NodeJS/LTS/18.20.3/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.3/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.3/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.3/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156054 Modify: OpenJS.NodeJS.LTS version 18.20.1
  manifests/o/OpenJS/NodeJS/LTS/18.20.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.20.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156050 Modify: OpenJS.NodeJS.LTS version 18.18.2
  manifests/o/OpenJS/NodeJS/LTS/18.18.2/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.2/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.2/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.18.2/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156052 Modify: OpenJS.NodeJS.LTS version 18.19.1
  manifests/o/OpenJS/NodeJS/LTS/18.19.1/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.19.1/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.19.1/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/18.19.1/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#156069 New version: lyswhut.lx-music-desktop version 2.8.0
  manifests/l/lyswhut/lx-music-desktop/2.8.0/lyswhut.lx-music-desktop.installer.yaml
  manifests/l/lyswhut/lx-music-desktop/2.8.0/lyswhut.lx-music-desktop.locale.en-US.yaml
  manifests/l/lyswhut/lx-music-desktop/2.8.0/lyswhut.lx-music-desktop.locale.zh-CN.yaml
  manifests/l/lyswhut/lx-music-desktop/2.8.0/lyswhut.lx-music-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156238 New version: RobertFFrasca.PDFKeeper version 9.1.5
  manifests/r/RobertFFrasca/PDFKeeper/9.1.5/RobertFFrasca.PDFKeeper.installer.yaml
  manifests/r/RobertFFrasca/PDFKeeper/9.1.5/RobertFFrasca.PDFKeeper.locale.en-US.yaml
  manifests/r/RobertFFrasca/PDFKeeper/9.1.5/RobertFFrasca.PDFKeeper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156237 New version: 64Gram.64Gram version 1.1.26
  manifests/6/64Gram/64Gram/1.1.26/64Gram.64Gram.installer.yaml
  manifests/6/64Gram/64Gram/1.1.26/64Gram.64Gram.locale.en-US.yaml
  manifests/6/64Gram/64Gram/1.1.26/64Gram.64Gram.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156243 TopalaSoftwareSolutions.SIW version 2024.05.26.2
  manifests/t/TopalaSoftwareSolutions/SIW/2024.05.26.2/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2024.05.26.2/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2024.05.26.2/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156246 eloston.ungoogled-chromium version 125.0.6422.141
  manifests/e/eloston/ungoogled-chromium/125.0.6422.141/eloston.ungoogled-chromium.installer.yaml
  manifests/e/eloston/ungoogled-chromium/125.0.6422.141/eloston.ungoogled-chromium.locale.en-US.yaml
  manifests/e/eloston/ungoogled-chromium/125.0.6422.141/eloston.ungoogled-chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156248 New version: Nikse.SubtitleEdit version 4.06
  manifests/n/Nikse/SubtitleEdit/4.06/Nikse.SubtitleEdit.installer.yaml
  manifests/n/Nikse/SubtitleEdit/4.06/Nikse.SubtitleEdit.locale.en-US.yaml
  manifests/n/Nikse/SubtitleEdit/4.06/Nikse.SubtitleEdit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156332 New version: VCVRack.VCVRack version 2.5.2
  manifests/v/VCVRack/VCVRack/2.5.2/VCVRack.VCVRack.installer.yaml
  manifests/v/VCVRack/VCVRack/2.5.2/VCVRack.VCVRack.locale.en-US.yaml
  manifests/v/VCVRack/VCVRack/2.5.2/VCVRack.VCVRack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156344 New version: AquaSecurity.Trivy version 0.52.0
  manifests/a/AquaSecurity/Trivy/0.52.0/AquaSecurity.Trivy.installer.yaml
  manifests/a/AquaSecurity/Trivy/0.52.0/AquaSecurity.Trivy.locale.en-US.yaml
  manifests/a/AquaSecurity/Trivy/0.52.0/AquaSecurity.Trivy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156339 New version: CodecGuide.K-LiteCodecPack.Basic version 18.3.5
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.3.5/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.3.5/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.3.5/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#156346 New version: KRTirtho.Spotube version 3.7.0
  manifests/k/KRTirtho/Spotube/3.7.0/KRTirtho.Spotube.installer.yaml
  manifests/k/KRTirtho/Spotube/3.7.0/KRTirtho.Spotube.locale.en-US.yaml
  manifests/k/KRTirtho/Spotube/3.7.0/KRTirtho.Spotube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156345 New version: Jellyfin.Server version 10.9.4
  manifests/j/Jellyfin/Server/10.9.4/Jellyfin.Server.installer.yaml
  manifests/j/Jellyfin/Server/10.9.4/Jellyfin.Server.locale.en-US.yaml
  manifests/j/Jellyfin/Server/10.9.4/Jellyfin.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156351 New version: ORASProject.ORAS version 1.2.0
  manifests/o/ORASProject/ORAS/1.2.0/ORASProject.ORAS.installer.yaml
  manifests/o/ORASProject/ORAS/1.2.0/ORASProject.ORAS.locale.en-US.yaml
  manifests/o/ORASProject/ORAS/1.2.0/ORASProject.ORAS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156359 Version Update: TeamProwlarr.Prowlarr version 1.18.0
  manifests/t/TeamProwlarr/Prowlarr/1.18.0/TeamProwlarr.Prowlarr.installer.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.18.0/TeamProwlarr.Prowlarr.locale.en-US.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.18.0/TeamProwlarr.Prowlarr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156360 Version Update: Morpheus.Bazarr version 1.4.3
  manifests/m/Morpheus/Bazarr/1.4.2/Morpheus.Bazarr.locale.en-US.yaml
  manifests/m/Morpheus/Bazarr/1.4.3/Morpheus.Bazarr.installer.yaml
  manifests/m/Morpheus/Bazarr/1.4.3/Morpheus.Bazarr.locale.en-US.yaml
  manifests/m/Morpheus/Bazarr/1.4.3/Morpheus.Bazarr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156361 New version: 34u.MultiBaseCSProfessional version 5.1.205
  manifests/3/34u/MultiBaseCSProfessional/5.1.205/34u.MultiBaseCSProfessional.installer.yaml
  manifests/3/34u/MultiBaseCSProfessional/5.1.205/34u.MultiBaseCSProfessional.locale.de-DE.yaml
  manifests/3/34u/MultiBaseCSProfessional/5.1.205/34u.MultiBaseCSProfessional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156362 New version: 34u.MultiBaseCSServer version 5.1.205
  manifests/3/34u/MultiBaseCSServer/5.1.205/34u.MultiBaseCSServer.installer.yaml
  manifests/3/34u/MultiBaseCSServer/5.1.205/34u.MultiBaseCSServer.locale.de-DE.yaml
  manifests/3/34u/MultiBaseCSServer/5.1.205/34u.MultiBaseCSServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156368 New version: IVPN.IVPN version 3.14.14
  manifests/i/IVPN/IVPN/3.14.14/IVPN.IVPN.installer.yaml
  manifests/i/IVPN/IVPN/3.14.14/IVPN.IVPN.locale.en-US.yaml
  manifests/i/IVPN/IVPN/3.14.14/IVPN.IVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156358 New version: 34u.MultiBaseCSHome version 5.1.205
  manifests/3/34u/MultiBaseCSHome/5.1.205/34u.MultiBaseCSHome.installer.yaml
  manifests/3/34u/MultiBaseCSHome/5.1.205/34u.MultiBaseCSHome.locale.de-DE.yaml
  manifests/3/34u/MultiBaseCSHome/5.1.205/34u.MultiBaseCSHome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156369 New version: DuckDB.cli version 1.0.0
  manifests/d/DuckDB/cli/1.0.0/DuckDB.cli.installer.yaml
  manifests/d/DuckDB/cli/1.0.0/DuckDB.cli.locale.en-US.yaml
  manifests/d/DuckDB/cli/1.0.0/DuckDB.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156153 New version: Spicetify.Spicetify version 2.36.12
  manifests/s/Spicetify/Spicetify/2.36.12/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.36.12/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.36.12/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#156156 New version: MediaArea.MediaInfo version 24.05
  manifests/m/MediaArea/MediaInfo/24.05/MediaArea.MediaInfo.installer.yaml
  manifests/m/MediaArea/MediaInfo/24.05/MediaArea.MediaInfo.locale.en-US.yaml
  manifests/m/MediaArea/MediaInfo/24.05/MediaArea.MediaInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
