Repository microsoft/winget-pkgs, pull requests merged in 2024-09, with the labels that each got.

#171012 New version: vim.vim.nightly version 9.1.0707
  manifests/v/vim/vim/nightly/9.1.0707/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0707/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0707/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#170780 New version: Tencent.COSCLI version 1.0.1
  manifests/t/Tencent/COSCLI/1.0.1/Tencent.COSCLI.installer.yaml
  manifests/t/Tencent/COSCLI/1.0.1/Tencent.COSCLI.locale.en-US.yaml
  manifests/t/Tencent/COSCLI/1.0.1/Tencent.COSCLI.locale.zh-CN.yaml
  manifests/t/Tencent/COSCLI/1.0.1/Tencent.COSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#170903 Package Fix: Added apps and features for floorp 11.17.8
  manifests/a/Ablaze/Floorp/11.17.8/Ablaze.Floorp.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#171035 New version: Jackett.Jackett version 0.22.545
  manifests/j/Jackett/Jackett/0.22.545/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.545/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.545/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#170892 Move Trillian.Trillian 6.5.0.17 to CeruleanStudios.Trillian 6.5.0.17
  manifests/c/CeruleanStudios/Trillian/6.5.0.17/CeruleanStudios.Trillian.installer.yaml
  manifests/c/CeruleanStudios/Trillian/6.5.0.17/CeruleanStudios.Trillian.locale.en-US.yaml
  manifests/c/CeruleanStudios/Trillian/6.5.0.17/CeruleanStudios.Trillian.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Manifest-Version-Deprecated, New-Package, New-Manifest, Manifest-Metadata-Consistency

#171094 New version: vim.vim.nightly version 9.1.0708
  manifests/v/vim/vim/nightly/9.1.0708/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0708/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0708/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171124 New version: Jackett.Jackett version 0.22.549
  manifests/j/Jackett/Jackett/0.22.549/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.549/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.549/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171132 Update dbeaver.dbeaver.installer.yaml
  manifests/d/dbeaver/dbeaver/24.1.5/dbeaver.dbeaver.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171150 JanDeDobbeleer.OhMyPosh version 23.10.0
  manifests/j/JanDeDobbeleer/OhMyPosh/23.10.0/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/23.10.0/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/23.10.0/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171261 New version: CodecGuide.K-LiteCodecPack.Basic version 18.5.5
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.5.5/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.5.5/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.5.5/CodecGuide.K-LiteCodecPack.Basic.locale.zh-CN.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.5.5/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171255 Move clouDr-f2e.rubick 4.2.2 to Rubick.Rubick 4.2.2
  manifests/r/Rubick/Rubick/4.2.2/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.2.2/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.2.2/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171250 Remove clouDr-f2e.rubick 4.1.5 to Rubick.Rubick 4.1.5
  manifests/c/clouDr-f2e/rubick/4.1.5/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/4.1.5/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/4.1.5/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171034 New version: Baulk.Baulk version 5.0.1.1086 (5.0.1)
  manifests/b/Baulk/Baulk/5.0.1.1086/Baulk.Baulk.installer.yaml
  manifests/b/Baulk/Baulk/5.0.1.1086/Baulk.Baulk.locale.en-US.yaml
  manifests/b/Baulk/Baulk/5.0.1.1086/Baulk.Baulk.locale.zh-CN.yaml
  manifests/b/Baulk/Baulk/5.0.1.1086/Baulk.Baulk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171110 New version: vivo.OfficeKit version 3.6.10.0 (3.6.10)
  manifests/v/vivo/OfficeKit/3.6.10.0/vivo.OfficeKit.installer.yaml
  manifests/v/vivo/OfficeKit/3.6.10.0/vivo.OfficeKit.locale.en-US.yaml
  manifests/v/vivo/OfficeKit/3.6.10.0/vivo.OfficeKit.locale.zh-CN.yaml
  manifests/v/vivo/OfficeKit/3.6.10.0/vivo.OfficeKit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171015 New version: Maxthon.Maxthon version 7.2.2.4000
  manifests/m/Maxthon/Maxthon/7.2.2.4000/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.4000/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.4000/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.4000/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171251 Move clouDr-f2e.rubick 4.1.6 to Rubick.Rubick 4.1.6
  manifests/r/Rubick/Rubick/4.1.6/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.1.6/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.1.6/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#170956 New version: Julialang.Juliaup version 1.17.5.0
  manifests/j/Julialang/Juliaup/1.17.5.0/Julialang.Juliaup.installer.yaml
  manifests/j/Julialang/Juliaup/1.17.5.0/Julialang.Juliaup.locale.en-US.yaml
  manifests/j/Julialang/Juliaup/1.17.5.0/Julialang.Juliaup.locale.zh-CN.yaml
  manifests/j/Julialang/Juliaup/1.17.5.0/Julialang.Juliaup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171230 Remove clouDr-f2e.rubick 2.4.0 to Rubick.Rubick 2.4.0
  manifests/c/clouDr-f2e/rubick/2.4.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.4.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.4.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171232 Remove clouDr-f2e.rubick 2.4.2 to Rubick.Rubick 2.4.2
  manifests/c/clouDr-f2e/rubick/2.4.2/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.4.2/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.4.2/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171233 Move clouDr-f2e.rubick 2.4.4 to Rubick.Rubick 2.4.4
  manifests/r/Rubick/Rubick/2.4.4/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/2.4.4/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/2.4.4/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171234 Remove clouDr-f2e.rubick 2.4.4 to Rubick.Rubick 2.4.4
  manifests/c/clouDr-f2e/rubick/2.4.4/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.4.4/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.4.4/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171037 New version: Google.Chrome.Canary version 130.0.6691.0
  manifests/g/Google/Chrome/Canary/130.0.6691.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/130.0.6691.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/130.0.6691.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/130.0.6691.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/130.0.6691.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171004 New version: Ollama.Ollama version 0.3.9
  manifests/o/Ollama/Ollama/0.3.9/Ollama.Ollama.installer.yaml
  manifests/o/Ollama/Ollama/0.3.9/Ollama.Ollama.locale.en-US.yaml
  manifests/o/Ollama/Ollama/0.3.9/Ollama.Ollama.locale.zh-CN.yaml
  manifests/o/Ollama/Ollama/0.3.9/Ollama.Ollama.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171113 New version: 360.360SE version 15.3.6142.64
  manifests/3/360/360SE/15.3.6142.64/360.360SE.installer.yaml
  manifests/3/360/360SE/15.3.6142.64/360.360SE.locale.en-US.yaml
  manifests/3/360/360SE/15.3.6142.64/360.360SE.locale.zh-CN.yaml
  manifests/3/360/360SE/15.3.6142.64/360.360SE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171237 Move clouDr-f2e.rubick 3.0.1 to Rubick.Rubick 3.0.1
  manifests/r/Rubick/Rubick/3.0.1/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.0.1/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.0.1/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171239 Move clouDr-f2e.rubick 3.1.0 to Rubick.Rubick 3.1.0
  manifests/r/Rubick/Rubick/3.1.0/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.1.0/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.1.0/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171236 Remove clouDr-f2e.rubick 3.0.0 to Rubick.Rubick 3.0.0
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.0.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171249 Move clouDr-f2e.rubick 4.1.5 to Rubick.Rubick 4.1.5
  manifests/r/Rubick/Rubick/4.1.5/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.1.5/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.1.5/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171140 New version: Google.Chrome.Canary version 130.0.6693.0
  manifests/g/Google/Chrome/Canary/130.0.6693.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/130.0.6693.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/130.0.6693.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/130.0.6693.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/130.0.6693.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171222 Remove clouDr-f2e.rubick 2.2.1 to Rubick.Rubick 2.2.1
  manifests/c/clouDr-f2e/rubick/2.2.1/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.2.1/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.2.1/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171153 New version: Tencent.QQ.NT version 9.9.15.27597 (9.9.15.240902)
  manifests/t/Tencent/QQ/NT/9.9.15.27597/Tencent.QQ.NT.installer.yaml
  manifests/t/Tencent/QQ/NT/9.9.15.27597/Tencent.QQ.NT.locale.en-US.yaml
  manifests/t/Tencent/QQ/NT/9.9.15.27597/Tencent.QQ.NT.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/NT/9.9.15.27597/Tencent.QQ.NT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171240 Remove clouDr-f2e.rubick 3.1.0 to Rubick.Rubick 3.1.0
  manifests/c/clouDr-f2e/rubick/3.1.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.1.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.1.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171216 Remove clouDr-f2e.rubick 2.1.2 to Rubick.Rubick 2.1.2
  manifests/c/clouDr-f2e/rubick/2.1.2/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.1.2/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.1.2/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171212 Remove clouDr-f2e.rubick 2.0.9 to Rubick.Rubick 2.0.9
  manifests/c/clouDr-f2e/rubick/2.0.9/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.9/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.9/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171202 Remove clouDr-f2e.rubick 2.0.2 to Rubick.Rubick 2.0.2
  manifests/c/clouDr-f2e/rubick/2.0.2/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.2/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.2/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171194 Remove clouDr-f2e.rubick 2.0.1-beta.17 to Rubick.Rubick 2.0.1-beta.17
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.17/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.17/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.17/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171190 Remove clouDr-f2e.rubick 2.0.1-beta.15 to Rubick.Rubick 2.0.1-beta.15
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.15/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.15/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.15/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171188 Remove clouDr-f2e.rubick 2.0.1-beta.13 to Rubick.Rubick 2.0.1-beta.13
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.13/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.13/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.13/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171115 New version: Alibaba.aDrive version 6.2.0
  manifests/a/Alibaba/aDrive/6.2.0/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/6.2.0/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/6.2.0/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/6.2.0/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171208 Remove clouDr-f2e.rubick 2.0.4-beta.1 to Rubick.Rubick 2.0.4-beta.1
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.1/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.1/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.1/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171180 Remove clouDr-f2e.rubick 0.0.6 to Rubick.Rubick 0.0.6
  manifests/c/clouDr-f2e/rubick/0.0.6/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/0.0.6/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/0.0.6/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171123 New package: Wondershare.Ani3D version 1.0.2.26
  manifests/w/Wondershare/Ani3D/1.0.2.26/Wondershare.Ani3D.installer.yaml
  manifests/w/Wondershare/Ani3D/1.0.2.26/Wondershare.Ani3D.locale.en-US.yaml
  manifests/w/Wondershare/Ani3D/1.0.2.26/Wondershare.Ani3D.locale.zh-CN.yaml
  manifests/w/Wondershare/Ani3D/1.0.2.26/Wondershare.Ani3D.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171204 Remove clouDr-f2e.rubick 2.0.3-beta.3 to Rubick.Rubick 2.0.3-beta.3
  manifests/c/clouDr-f2e/rubick/2.0.3-beta.3/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.3-beta.3/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.3-beta.3/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171038 New package: NetEase.DD version 1.0.0.1
  manifests/n/NetEase/DD/1.0.0.1/NetEase.DD.installer.yaml
  manifests/n/NetEase/DD/1.0.0.1/NetEase.DD.locale.en-US.yaml
  manifests/n/NetEase/DD/1.0.0.1/NetEase.DD.locale.zh-CN.yaml
  manifests/n/NetEase/DD/1.0.0.1/NetEase.DD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171070 New package: 360.360AlbumViewer version 1.0.1.1080
  manifests/3/360/360AlbumViewer/1.0.1.1080/360.360AlbumViewer.installer.yaml
  manifests/3/360/360AlbumViewer/1.0.1.1080/360.360AlbumViewer.locale.en-US.yaml
  manifests/3/360/360AlbumViewer/1.0.1.1080/360.360AlbumViewer.locale.zh-CN.yaml
  manifests/3/360/360AlbumViewer/1.0.1.1080/360.360AlbumViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171210 Remove clouDr-f2e.rubick 2.0.4-beta.3 to Rubick.Rubick 2.0.4-beta.3
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.3/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.3/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4-beta.3/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171178 Remove clouDr-f2e.rubick 0.0.3-beta.6 to Rubick.Rubick 0.0.3-beta.6
  manifests/c/clouDr-f2e/rubick/0.0.3-beta.6/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/0.0.3-beta.6/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/0.0.3-beta.6/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171238 Remove clouDr-f2e.rubick 3.0.1 to Rubick.Rubick 3.0.1
  manifests/c/clouDr-f2e/rubick/3.0.1/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.0.1/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.0.1/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171117 New package: Wondershare.Mockitt version 6.0.0
  manifests/w/Wondershare/Mockitt/6.0.0/Wondershare.Mockitt.installer.yaml
  manifests/w/Wondershare/Mockitt/6.0.0/Wondershare.Mockitt.locale.en-US.yaml
  manifests/w/Wondershare/Mockitt/6.0.0/Wondershare.Mockitt.locale.zh-CN.yaml
  manifests/w/Wondershare/Mockitt/6.0.0/Wondershare.Mockitt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171135 New package: Wondershare.UniConverter.15 version 15.6.1.25 (15.6.1)
  manifests/w/Wondershare/UniConverter/15/15.6.1.25/Wondershare.UniConverter.15.installer.yaml
  manifests/w/Wondershare/UniConverter/15/15.6.1.25/Wondershare.UniConverter.15.locale.en-US.yaml
  manifests/w/Wondershare/UniConverter/15/15.6.1.25/Wondershare.UniConverter.15.locale.zh-CN.yaml
  manifests/w/Wondershare/UniConverter/15/15.6.1.25/Wondershare.UniConverter.15.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#171133 New package: Wondershare.AniSmall version 1.0.7.64
  manifests/w/Wondershare/AniSmall/1.0.7.64/Wondershare.AniSmall.installer.yaml
  manifests/w/Wondershare/AniSmall/1.0.7.64/Wondershare.AniSmall.locale.en-US.yaml
  manifests/w/Wondershare/AniSmall/1.0.7.64/Wondershare.AniSmall.locale.zh-CN.yaml
  manifests/w/Wondershare/AniSmall/1.0.7.64/Wondershare.AniSmall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171192 Remove clouDr-f2e.rubick 2.0.1-beta.16 to Rubick.Rubick 2.0.1-beta.16
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.16/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.16/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.16/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#170942 New version: Google.Chrome.Canary version 130.0.6690.0
  manifests/g/Google/Chrome/Canary/130.0.6690.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/130.0.6690.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/130.0.6690.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/130.0.6690.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/130.0.6690.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#171245 Move clouDr-f2e.rubick 3.2.3 to Rubick.Rubick 3.2.3
  manifests/r/Rubick/Rubick/3.2.3/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.2.3/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.2.3/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171072 New package: 360.360DesktopLite version 11.0.0.2061
  manifests/3/360/360DesktopLite/11.0.0.2061/360.360DesktopLite.installer.yaml
  manifests/3/360/360DesktopLite/11.0.0.2061/360.360DesktopLite.locale.en-US.yaml
  manifests/3/360/360DesktopLite/11.0.0.2061/360.360DesktopLite.locale.zh-CN.yaml
  manifests/3/360/360DesktopLite/11.0.0.2061/360.360DesktopLite.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171258 Remove clouDr-f2e.rubick 4.2.4 to Rubick.Rubick 4.2.4
  manifests/c/clouDr-f2e/rubick/4.2.4/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/4.2.4/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/4.2.4/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171139 New version: EaseUS.PartitionMaster version 19.0
  manifests/e/EaseUS/PartitionMaster/19.0/EaseUS.PartitionMaster.installer.yaml
  manifests/e/EaseUS/PartitionMaster/19.0/EaseUS.PartitionMaster.locale.en-US.yaml
  manifests/e/EaseUS/PartitionMaster/19.0/EaseUS.PartitionMaster.locale.zh-CN.yaml
  manifests/e/EaseUS/PartitionMaster/19.0/EaseUS.PartitionMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171069 New version: OpenAudible.OpenAudible version 4.4.5
  manifests/o/OpenAudible/OpenAudible/4.4.5/OpenAudible.OpenAudible.installer.yaml
  manifests/o/OpenAudible/OpenAudible/4.4.5/OpenAudible.OpenAudible.locale.en-US.yaml
  manifests/o/OpenAudible/OpenAudible/4.4.5/OpenAudible.OpenAudible.locale.zh-CN.yaml
  manifests/o/OpenAudible/OpenAudible/4.4.5/OpenAudible.OpenAudible.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171138 New version: Bandisoft.BandiView version 7.07 (26754)
  manifests/b/Bandisoft/BandiView/7.07/Bandisoft.BandiView.installer.yaml
  manifests/b/Bandisoft/BandiView/7.07/Bandisoft.BandiView.locale.en-US.yaml
  manifests/b/Bandisoft/BandiView/7.07/Bandisoft.BandiView.locale.zh-CN.yaml
  manifests/b/Bandisoft/BandiView/7.07/Bandisoft.BandiView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171247 Move clouDr-f2e.rubick 4.1.3 to Rubick.Rubick 4.1.3
  manifests/r/Rubick/Rubick/4.1.3/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.1.3/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.1.3/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171160 New version: Telerik.Fiddler.Everywhere version 5.16.0
  manifests/t/Telerik/Fiddler/Everywhere/5.16.0/Telerik.Fiddler.Everywhere.installer.yaml
  manifests/t/Telerik/Fiddler/Everywhere/5.16.0/Telerik.Fiddler.Everywhere.locale.en-US.yaml
  manifests/t/Telerik/Fiddler/Everywhere/5.16.0/Telerik.Fiddler.Everywhere.locale.zh-CN.yaml
  manifests/t/Telerik/Fiddler/Everywhere/5.16.0/Telerik.Fiddler.Everywhere.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171252 Remove clouDr-f2e.rubick 4.1.6 to Rubick.Rubick 4.1.6
  manifests/c/clouDr-f2e/rubick/4.1.6/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/4.1.6/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/4.1.6/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171263 New version: CodecGuide.K-LiteCodecPack.Mega version 18.5.5
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.5.5/CodecGuide.K-LiteCodecPack.Mega.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.5.5/CodecGuide.K-LiteCodecPack.Mega.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.5.5/CodecGuide.K-LiteCodecPack.Mega.locale.zh-CN.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.5.5/CodecGuide.K-LiteCodecPack.Mega.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171086 New version: Google.Chrome.Canary version 130.0.6692.0
  manifests/g/Google/Chrome/Canary/130.0.6692.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/130.0.6692.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/130.0.6692.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/130.0.6692.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/130.0.6692.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171262 New version: CodecGuide.K-LiteCodecPack.Full version 18.5.5
  manifests/c/CodecGuide/K-LiteCodecPack/Full/18.5.5/CodecGuide.K-LiteCodecPack.Full.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/18.5.5/CodecGuide.K-LiteCodecPack.Full.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/18.5.5/CodecGuide.K-LiteCodecPack.Full.locale.zh-CN.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Full/18.5.5/CodecGuide.K-LiteCodecPack.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171167 New version: Thunder.Thunder version 12.0.14.2604
  manifests/t/Thunder/Thunder/12.0.14.2604/Thunder.Thunder.installer.yaml
  manifests/t/Thunder/Thunder/12.0.14.2604/Thunder.Thunder.locale.en-US.yaml
  manifests/t/Thunder/Thunder/12.0.14.2604/Thunder.Thunder.locale.zh-CN.yaml
  manifests/t/Thunder/Thunder/12.0.14.2604/Thunder.Thunder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171292 Remove version: foldynl.QLog version 0.35.2
  manifests/f/foldynl/QLog/0.35.2/foldynl.QLog.installer.yaml
  manifests/f/foldynl/QLog/0.35.2/foldynl.QLog.locale.en-US.yaml
  manifests/f/foldynl/QLog/0.35.2/foldynl.QLog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171291 Remove version: GiulioSorrentino.WinDateFrom version 4.6.1
  manifests/g/GiulioSorrentino/WinDateFrom/4.6.1/GiulioSorrentino.WinDateFrom.installer.yaml
  manifests/g/GiulioSorrentino/WinDateFrom/4.6.1/GiulioSorrentino.WinDateFrom.locale.en-US.yaml
  manifests/g/GiulioSorrentino/WinDateFrom/4.6.1/GiulioSorrentino.WinDateFrom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171116 New version: sigoden.Dufs version 0.42.0
  manifests/s/sigoden/Dufs/0.42.0/sigoden.Dufs.installer.yaml
  manifests/s/sigoden/Dufs/0.42.0/sigoden.Dufs.locale.en-US.yaml
  manifests/s/sigoden/Dufs/0.42.0/sigoden.Dufs.locale.zh-CN.yaml
  manifests/s/sigoden/Dufs/0.42.0/sigoden.Dufs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171091 New version: Evernote.Evernote version 10.103.5
  manifests/e/Evernote/Evernote/10.103.5/Evernote.Evernote.installer.yaml
  manifests/e/Evernote/Evernote/10.103.5/Evernote.Evernote.locale.en-US.yaml
  manifests/e/Evernote/Evernote/10.103.5/Evernote.Evernote.locale.zh-CN.yaml
  manifests/e/Evernote/Evernote/10.103.5/Evernote.Evernote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#171206 Remove clouDr-f2e.rubick 2.0.4 to Rubick.Rubick 2.0.4
  manifests/c/clouDr-f2e/rubick/2.0.4/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.4/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171200 Remove clouDr-f2e.rubick 2.0.1-beta.9 to Rubick.Rubick 2.0.1-beta.9
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.9/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.9/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.9/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171257 Move clouDr-f2e.rubick 4.2.4 to Rubick.Rubick 4.2.4
  manifests/r/Rubick/Rubick/4.2.4/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.2.4/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.2.4/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171031 New package: THS.Futures version 4.18.1.1
  manifests/t/THS/Futures/4.18.1.1/THS.Futures.installer.yaml
  manifests/t/THS/Futures/4.18.1.1/THS.Futures.locale.en-US.yaml
  manifests/t/THS/Futures/4.18.1.1/THS.Futures.locale.zh-CN.yaml
  manifests/t/THS/Futures/4.18.1.1/THS.Futures.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171246 Remove clouDr-f2e.rubick 3.2.3 to Rubick.Rubick 3.2.3
  manifests/c/clouDr-f2e/rubick/3.2.3/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.2.3/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.2.3/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171256 Remove clouDr-f2e.rubick 4.2.2 to Rubick.Rubick 4.2.2
  manifests/c/clouDr-f2e/rubick/4.2.2/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/4.2.2/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/4.2.2/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171275 New version: SVZsoft.GEDKeeper version 3.7.0
  manifests/s/SVZsoft/GEDKeeper/3.7.0/SVZsoft.GEDKeeper.installer.yaml
  manifests/s/SVZsoft/GEDKeeper/3.7.0/SVZsoft.GEDKeeper.locale.en-US.yaml
  manifests/s/SVZsoft/GEDKeeper/3.7.0/SVZsoft.GEDKeeper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171277 Remove version: Redisant.MQTTAssistant version 1.1.4.4
  manifests/r/Redisant/MQTTAssistant/1.1.4.4/Redisant.MQTTAssistant.installer.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.4/Redisant.MQTTAssistant.locale.en-US.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.4/Redisant.MQTTAssistant.locale.zh-CN.yaml
  manifests/r/Redisant/MQTTAssistant/1.1.4.4/Redisant.MQTTAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171228 Remove clouDr-f2e.rubick 2.3.0 to Rubick.Rubick 2.3.0
  manifests/c/clouDr-f2e/rubick/2.3.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.3.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.3.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171157 Update version: Freeplane.Freeplane version 1.11.14
  manifests/f/Freeplane/Freeplane/1.11.14/Freeplane.Freeplane.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171170 New version: seerge.g-helper version 0.187
  manifests/s/seerge/g-helper/0.187/seerge.g-helper.installer.yaml
  manifests/s/seerge/g-helper/0.187/seerge.g-helper.locale.en-US.yaml
  manifests/s/seerge/g-helper/0.187/seerge.g-helper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171163 New version: Freeplane.Freeplane version 1.12.5
  manifests/f/Freeplane/Freeplane/1.12.5/Freeplane.Freeplane.installer.yaml
  manifests/f/Freeplane/Freeplane/1.12.5/Freeplane.Freeplane.locale.en-US.yaml
  manifests/f/Freeplane/Freeplane/1.12.5/Freeplane.Freeplane.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171241 Move clouDr-f2e.rubick 3.1.1 to Rubick.Rubick 3.1.1
  manifests/r/Rubick/Rubick/3.1.1/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.1.1/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.1.1/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171231 Move clouDr-f2e.rubick 2.4.2 to Rubick.Rubick 2.4.2
  manifests/r/Rubick/Rubick/2.4.2/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/2.4.2/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/2.4.2/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171220 Remove clouDr-f2e.rubick 2.2.0 to Rubick.Rubick 2.2.0
  manifests/c/clouDr-f2e/rubick/2.2.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.2.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.2.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171214 Remove clouDr-f2e.rubick 2.1.10 to Rubick.Rubick 2.1.10
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.1.10/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171218 Remove clouDr-f2e.rubick 2.1.6 to Rubick.Rubick 2.1.6
  manifests/c/clouDr-f2e/rubick/2.1.6/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.1.6/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.1.6/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171013 New version: Catsxp.Catsxp version 128.4.9.1
  manifests/c/Catsxp/Catsxp/128.4.9.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/128.4.9.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/128.4.9.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/128.4.9.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#171242 Remove clouDr-f2e.rubick 3.1.1 to Rubick.Rubick 3.1.1
  manifests/c/clouDr-f2e/rubick/3.1.1/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.1.1/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.1.1/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171176 Remove clouDr-f2e.rubick 0.0.12 to Rubick.Rubick 0.0.12
  manifests/c/clouDr-f2e/rubick/0.0.12/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/0.0.12/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/0.0.12/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171198 Remove clouDr-f2e.rubick 2.0.1-beta.8 to Rubick.Rubick 2.0.1-beta.8
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.8/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.8/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.8/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171184 Remove clouDr-f2e.rubick 2.0.1-beta.11 to Rubick.Rubick 2.0.1-beta.11
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.11/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.11/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.11/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171043 New package: VidJuice.UniTube version 6.9.0
  manifests/v/VidJuice/UniTube/6.9.0/VidJuice.UniTube.installer.yaml
  manifests/v/VidJuice/UniTube/6.9.0/VidJuice.UniTube.locale.en-US.yaml
  manifests/v/VidJuice/UniTube/6.9.0/VidJuice.UniTube.locale.zh-CN.yaml
  manifests/v/VidJuice/UniTube/6.9.0/VidJuice.UniTube.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171186 Remove clouDr-f2e.rubick 2.0.1-beta.12 to Rubick.Rubick 2.0.1-beta.12
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.12/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.12/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.12/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171032 New package: THS.HXSmart version 1.0.2.5
  manifests/t/THS/HXSmart/1.0.2.5/THS.HXSmart.installer.yaml
  manifests/t/THS/HXSmart/1.0.2.5/THS.HXSmart.locale.en-US.yaml
  manifests/t/THS/HXSmart/1.0.2.5/THS.HXSmart.locale.zh-CN.yaml
  manifests/t/THS/HXSmart/1.0.2.5/THS.HXSmart.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#171296 Remove version: gileli121.windowtop version 5.22.10
  manifests/g/gileli121/windowtop/5.22.10/gileli121.windowtop.installer.yaml
  manifests/g/gileli121/windowtop/5.22.10/gileli121.windowtop.locale.en-US.yaml
  manifests/g/gileli121/windowtop/5.22.10/gileli121.windowtop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171166 New version: tangshimin.MuJing version 2.5.0
  manifests/t/tangshimin/MuJing/2.5.0/tangshimin.MuJing.installer.yaml
  manifests/t/tangshimin/MuJing/2.5.0/tangshimin.MuJing.locale.en-US.yaml
  manifests/t/tangshimin/MuJing/2.5.0/tangshimin.MuJing.locale.zh-CN.yaml
  manifests/t/tangshimin/MuJing/2.5.0/tangshimin.MuJing.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171243 Move clouDr-f2e.rubick 3.2.0 to Rubick.Rubick 3.2.0
  manifests/r/Rubick/Rubick/3.2.0/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.2.0/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.2.0/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171265 New package: CISDI.Qingtui version 3.31.0
  manifests/c/CISDI/Qingtui/3.31.0/CISDI.Qingtui.installer.yaml
  manifests/c/CISDI/Qingtui/3.31.0/CISDI.Qingtui.locale.en-US.yaml
  manifests/c/CISDI/Qingtui/3.31.0/CISDI.Qingtui.locale.zh-CN.yaml
  manifests/c/CISDI/Qingtui/3.31.0/CISDI.Qingtui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171264 New version: CodecGuide.K-LiteCodecPack.Standard version 18.5.5
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.5.5/CodecGuide.K-LiteCodecPack.Standard.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.5.5/CodecGuide.K-LiteCodecPack.Standard.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.5.5/CodecGuide.K-LiteCodecPack.Standard.locale.zh-CN.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.5.5/CodecGuide.K-LiteCodecPack.Standard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171111 New version: KDE.Kdenlive version 24.08.0
  manifests/k/KDE/Kdenlive/24.08.0/KDE.Kdenlive.installer.yaml
  manifests/k/KDE/Kdenlive/24.08.0/KDE.Kdenlive.locale.en-US.yaml
  manifests/k/KDE/Kdenlive/24.08.0/KDE.Kdenlive.locale.zh-CN.yaml
  manifests/k/KDE/Kdenlive/24.08.0/KDE.Kdenlive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#171293 Remove version: foldynl.QLog version 0.36.0
  manifests/f/foldynl/QLog/0.36.0/foldynl.QLog.installer.yaml
  manifests/f/foldynl/QLog/0.36.0/foldynl.QLog.locale.en-US.yaml
  manifests/f/foldynl/QLog/0.36.0/foldynl.QLog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171120 New package: Wondershare.Virbo version 1.5.22
  manifests/w/Wondershare/Virbo/1.5.22/Wondershare.Virbo.installer.yaml
  manifests/w/Wondershare/Virbo/1.5.22/Wondershare.Virbo.locale.en-US.yaml
  manifests/w/Wondershare/Virbo/1.5.22/Wondershare.Virbo.locale.zh-CN.yaml
  manifests/w/Wondershare/Virbo/1.5.22/Wondershare.Virbo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171290 Remove version: maygo.tockler version 3.20.12
  manifests/m/maygo/tockler/3.20.12/maygo.tockler.installer.yaml
  manifests/m/maygo/tockler/3.20.12/maygo.tockler.locale.en-US.yaml
  manifests/m/maygo/tockler/3.20.12/maygo.tockler.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171040 New version: foldynl.QLog version 0.38.0
  manifests/f/foldynl/QLog/0.38.0/foldynl.QLog.installer.yaml
  manifests/f/foldynl/QLog/0.38.0/foldynl.QLog.locale.en-US.yaml
  manifests/f/foldynl/QLog/0.38.0/foldynl.QLog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171284 Remove version: LutzRoeder.Netron version 7.8.3
  manifests/l/LutzRoeder/Netron/7.8.3/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.8.3/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.8.3/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171048 Remove version: Maltego.Maltego version 4.7.0
  manifests/m/Maltego/Maltego/4.7.0/Maltego.Maltego.installer.yaml
  manifests/m/Maltego/Maltego/4.7.0/Maltego.Maltego.locale.en-US.yaml
  manifests/m/Maltego/Maltego/4.7.0/Maltego.Maltego.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171294 Remove version: foldynl.QLog version 0.37.1
  manifests/f/foldynl/QLog/0.37.1/foldynl.QLog.installer.yaml
  manifests/f/foldynl/QLog/0.37.1/foldynl.QLog.locale.en-US.yaml
  manifests/f/foldynl/QLog/0.37.1/foldynl.QLog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171253 Move clouDr-f2e.rubick 4.2.1 to Rubick.Rubick 4.2.1
  manifests/r/Rubick/Rubick/4.2.1/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/4.2.1/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/4.2.1/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#171276 Remove version: SVZsoft.GEDKeeper version 3.2.0
  manifests/s/SVZsoft/GEDKeeper/3.2.0/SVZsoft.GEDKeeper.installer.yaml
  manifests/s/SVZsoft/GEDKeeper/3.2.0/SVZsoft.GEDKeeper.locale.en-US.yaml
  manifests/s/SVZsoft/GEDKeeper/3.2.0/SVZsoft.GEDKeeper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171226 Remove clouDr-f2e.rubick 2.2.7 to Rubick.Rubick 2.2.7
  manifests/c/clouDr-f2e/rubick/2.2.7/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.2.7/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.2.7/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171273 Remove version: Taozuhong.Kangaroo version 2.99.3.230602
  manifests/t/Taozuhong/Kangaroo/2.99.3.230602/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.99.3.230602/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.99.3.230602/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.99.3.230602/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171272 Remove version: Taozuhong.Kangaroo version 1.10.2.220701
  manifests/t/Taozuhong/Kangaroo/1.10.2.220701/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/1.10.2.220701/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/1.10.2.220701/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/1.10.2.220701/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171224 Remove clouDr-f2e.rubick 2.2.2 to Rubick.Rubick 2.2.2
  manifests/c/clouDr-f2e/rubick/2.2.2/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.2.2/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.2.2/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171196 Remove clouDr-f2e.rubick 2.0.1-beta.19 to Rubick.Rubick 2.0.1-beta.19
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.19/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.19/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/2.0.1-beta.19/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171286 Remove version: Joplin.Joplin version 3.0.13
  manifests/j/Joplin/Joplin/3.0.13/Joplin.Joplin.installer.yaml
  manifests/j/Joplin/Joplin/3.0.13/Joplin.Joplin.locale.en-US.yaml
  manifests/j/Joplin/Joplin/3.0.13/Joplin.Joplin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171297 Remove version: chrisant996.Clink version 1.6.19
  manifests/c/chrisant996/Clink/1.6.19/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.6.19/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.6.19/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171298 Remove version: calibre.calibre.portable version 7.16.0.0
  manifests/c/calibre/calibre/portable/7.16.0.0/calibre.calibre.portable.installer.yaml
  manifests/c/calibre/calibre/portable/7.16.0.0/calibre.calibre.portable.locale.en-US.yaml
  manifests/c/calibre/calibre/portable/7.16.0.0/calibre.calibre.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171172 New version: clsid2.mpc-hc version 2.3.5
  manifests/c/clsid2/mpc-hc/2.3.5/clsid2.mpc-hc.installer.yaml
  manifests/c/clsid2/mpc-hc/2.3.5/clsid2.mpc-hc.locale.en-US.yaml
  manifests/c/clsid2/mpc-hc/2.3.5/clsid2.mpc-hc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171102 New version: Ryujinx.Ryujinx.Ava version 1.1.1385
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1385/Ryujinx.Ryujinx.Ava.installer.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1385/Ryujinx.Ryujinx.Ava.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1385/Ryujinx.Ryujinx.Ava.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171299 Remove version: Bitwarden.CLI version 2024.7.0
  manifests/b/Bitwarden/CLI/2024.7.0/Bitwarden.CLI.installer.yaml
  manifests/b/Bitwarden/CLI/2024.7.0/Bitwarden.CLI.locale.en-US.yaml
  manifests/b/Bitwarden/CLI/2024.7.0/Bitwarden.CLI.locale.pt-BR.yaml
  manifests/b/Bitwarden/CLI/2024.7.0/Bitwarden.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171301 Remove version: Arks-Layer.PSO2Tweaker version 6.2.1.4
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.4/Arks-Layer.PSO2Tweaker.installer.yaml
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.4/Arks-Layer.PSO2Tweaker.locale.en-US.yaml
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.4/Arks-Layer.PSO2Tweaker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171244 Remove clouDr-f2e.rubick 3.2.0 to Rubick.Rubick 3.2.0
  manifests/c/clouDr-f2e/rubick/3.2.0/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/3.2.0/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/3.2.0/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171288 New version: Google.Chrome.EXE version 128.0.6613.120
  manifests/g/Google/Chrome/EXE/128.0.6613.120/Google.Chrome.EXE.installer.yaml
  manifests/g/Google/Chrome/EXE/128.0.6613.120/Google.Chrome.EXE.locale.en-US.yaml
  manifests/g/Google/Chrome/EXE/128.0.6613.120/Google.Chrome.EXE.locale.nb-NO.yaml
  manifests/g/Google/Chrome/EXE/128.0.6613.120/Google.Chrome.EXE.locale.zh-CN.yaml
  manifests/g/Google/Chrome/EXE/128.0.6613.120/Google.Chrome.EXE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171289 New version: Google.Chrome version 128.0.6613.120
  manifests/g/Google/Chrome/128.0.6613.120/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/128.0.6613.120/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/128.0.6613.120/Google.Chrome.locale.nb-NO.yaml
  manifests/g/Google/Chrome/128.0.6613.120/Google.Chrome.locale.zh-CN.yaml
  manifests/g/Google/Chrome/128.0.6613.120/Google.Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171295 New Version: DanielMcGuireCorporation.MathBotCLI 3.4.0
  manifests/d/DanielMcGuireCorporation/MathBotCLI/3.4.0/DanielMcGuireCorporation.MathBotCLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171300 New version: Arks-Layer.PSO2Tweaker version 6.2.1.5
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.5/Arks-Layer.PSO2Tweaker.installer.yaml
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.5/Arks-Layer.PSO2Tweaker.locale.en-US.yaml
  manifests/a/Arks-Layer/PSO2Tweaker/6.2.1.5/Arks-Layer.PSO2Tweaker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171207 Move clouDr-f2e.rubick 2.0.4-beta.1 to Rubick.Rubick 2.0.4-beta.1
  manifests/r/Rubick/Rubick/2.0.4-beta.1/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/2.0.4-beta.1/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/2.0.4-beta.1/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#171205 Move clouDr-f2e.rubick 2.0.4 to Rubick.Rubick 2.0.4
  manifests/r/Rubick/Rubick/2.0.4/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/2.0.4/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/2.0.4/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved, Manifest-Version-Deprecated, New-Package

#171235 Move clouDr-f2e.rubick 3.0.0 to Rubick.Rubick 3.0.0
  manifests/r/Rubick/Rubick/3.0.0/Rubick.Rubick.installer.yaml
  manifests/r/Rubick/Rubick/3.0.0/Rubick.Rubick.locale.en-US.yaml
  manifests/r/Rubick/Rubick/3.0.0/Rubick.Rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved, New-Package

#171136 New package: Wondershare.Virbo.CN version 1.5.22
  manifests/w/Wondershare/Virbo/CN/1.5.22/Wondershare.Virbo.CN.installer.yaml
  manifests/w/Wondershare/Virbo/CN/1.5.22/Wondershare.Virbo.CN.locale.en-US.yaml
  manifests/w/Wondershare/Virbo/CN/1.5.22/Wondershare.Virbo.CN.locale.zh-CN.yaml
  manifests/w/Wondershare/Virbo/CN/1.5.22/Wondershare.Virbo.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#171041 New version: Maltego.Maltego version 4.8.0
  manifests/m/Maltego/Maltego/4.8.0/Maltego.Maltego.installer.yaml
  manifests/m/Maltego/Maltego/4.8.0/Maltego.Maltego.locale.en-US.yaml
  manifests/m/Maltego/Maltego/4.8.0/Maltego.Maltego.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#171152 New version: Opera.Opera version 113.0.5230.55
  manifests/o/Opera/Opera/113.0.5230.55/Opera.Opera.installer.yaml
  manifests/o/Opera/Opera/113.0.5230.55/Opera.Opera.locale.en-US.yaml
  manifests/o/Opera/Opera/113.0.5230.55/Opera.Opera.locale.nb-NO.yaml
  manifests/o/Opera/Opera/113.0.5230.55/Opera.Opera.locale.zh-CN.yaml
  manifests/o/Opera/Opera/113.0.5230.55/Opera.Opera.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#171350 New version: Jackett.Jackett version 0.22.554
  manifests/j/Jackett/Jackett/0.22.554/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.554/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.554/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171357 New package: Digola.DoorControl version 4.9
  manifests/d/Digola/DoorControl/4.9/Digola.DoorControl.installer.yaml
  manifests/d/Digola/DoorControl/4.9/Digola.DoorControl.locale.en-US.yaml
  manifests/d/Digola/DoorControl/4.9/Digola.DoorControl.locale.zh-CN.yaml
  manifests/d/Digola/DoorControl/4.9/Digola.DoorControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171356 New package: Digola.NooG version 5.1
  manifests/d/Digola/NooG/5.1/Digola.NooG.installer.yaml
  manifests/d/Digola/NooG/5.1/Digola.NooG.locale.en-US.yaml
  manifests/d/Digola/NooG/5.1/Digola.NooG.locale.zh-CN.yaml
  manifests/d/Digola/NooG/5.1/Digola.NooG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171351 New package: Digola.LockCursorTools version 9.0
  manifests/d/Digola/LockCursorTools/9.0/Digola.LockCursorTools.installer.yaml
  manifests/d/Digola/LockCursorTools/9.0/Digola.LockCursorTools.locale.en-US.yaml
  manifests/d/Digola/LockCursorTools/9.0/Digola.LockCursorTools.locale.zh-CN.yaml
  manifests/d/Digola/LockCursorTools/9.0/Digola.LockCursorTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#171355 New version: jeffvli.Feishin version 0.8.0
  manifests/j/jeffvli/Feishin/0.8.0/jeffvli.Feishin.installer.yaml
  manifests/j/jeffvli/Feishin/0.8.0/jeffvli.Feishin.locale.en-US.yaml
  manifests/j/jeffvli/Feishin/0.8.0/jeffvli.Feishin.locale.zh-CN.yaml
  manifests/j/jeffvli/Feishin/0.8.0/jeffvli.Feishin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171343 New version: B3log.SiYuan version 3.1.5
  manifests/b/B3log/SiYuan/3.1.5/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/3.1.5/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/3.1.5/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/3.1.5/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171344 New version: Huawei.Welink version 7.44.5
  manifests/h/Huawei/Welink/7.44.5/Huawei.Welink.installer.yaml
  manifests/h/Huawei/Welink/7.44.5/Huawei.Welink.locale.en-US.yaml
  manifests/h/Huawei/Welink/7.44.5/Huawei.Welink.locale.zh-CN.yaml
  manifests/h/Huawei/Welink/7.44.5/Huawei.Welink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171335 New version: Wondershare.MobileTrans version 4.5.21
  manifests/w/Wondershare/MobileTrans/4.5.21/Wondershare.MobileTrans.installer.yaml
  manifests/w/Wondershare/MobileTrans/4.5.21/Wondershare.MobileTrans.locale.en-US.yaml
  manifests/w/Wondershare/MobileTrans/4.5.21/Wondershare.MobileTrans.locale.zh-CN.yaml
  manifests/w/Wondershare/MobileTrans/4.5.21/Wondershare.MobileTrans.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171317 New version: Google.Chrome.Canary version 130.0.6694.0
  manifests/g/Google/Chrome/Canary/130.0.6694.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/130.0.6694.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/130.0.6694.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/130.0.6694.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/130.0.6694.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#171306 New version: XMediaRecode.XMediaRecode version 3.6.0.0
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.0/XMediaRecode.XMediaRecode.installer.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.0/XMediaRecode.XMediaRecode.locale.en-US.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.0/XMediaRecode.XMediaRecode.locale.zh-CN.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.0/XMediaRecode.XMediaRecode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171333 New version: Termius.Termius version 9.5.0
  manifests/t/Termius/Termius/9.5.0/Termius.Termius.installer.yaml
  manifests/t/Termius/Termius/9.5.0/Termius.Termius.locale.en-US.yaml
  manifests/t/Termius/Termius/9.5.0/Termius.Termius.locale.zh-CN.yaml
  manifests/t/Termius/Termius/9.5.0/Termius.Termius.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171327 New version: den4b.Colors version 3.2
  manifests/d/den4b/Colors/3.2/den4b.Colors.installer.yaml
  manifests/d/den4b/Colors/3.2/den4b.Colors.locale.en-US.yaml
  manifests/d/den4b/Colors/3.2/den4b.Colors.locale.zh-CN.yaml
  manifests/d/den4b/Colors/3.2/den4b.Colors.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#171377 Remove MapTiler.MapTilerDesktop 13.2 to MapTiler.MapTilerEngine 13.2
  manifests/m/MapTiler/MapTilerDesktop/13.2/MapTiler.MapTilerDesktop.installer.yaml
  manifests/m/MapTiler/MapTilerDesktop/13.2/MapTiler.MapTilerDesktop.locale.en-US.yaml
  manifests/m/MapTiler/MapTilerDesktop/13.2/MapTiler.MapTilerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171371 Remove MapTiler.MapTilerDesktop 11.3 to MapTiler.MapTilerEngine 11.3
  manifests/m/MapTiler/MapTilerDesktop/11.3/MapTiler.MapTilerDesktop.installer.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.3/MapTiler.MapTilerDesktop.locale.en-US.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.3/MapTiler.MapTilerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171379 Remove MapTiler.MapTilerDesktop 13.3 to MapTiler.MapTilerEngine 13.3
  manifests/m/MapTiler/MapTilerDesktop/13.3/MapTiler.MapTilerDesktop.installer.yaml
  manifests/m/MapTiler/MapTilerDesktop/13.3/MapTiler.MapTilerDesktop.locale.en-US.yaml
  manifests/m/MapTiler/MapTilerDesktop/13.3/MapTiler.MapTilerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171369 Remove MapTiler.MapTilerDesktop 11.2.1 to MapTiler.MapTilerEngine 11.2.1
  manifests/m/MapTiler/MapTilerDesktop/11.2.1/MapTiler.MapTilerDesktop.installer.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.2.1/MapTiler.MapTilerDesktop.locale.en-US.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.2.1/MapTiler.MapTilerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#171365 Remove MapTiler.MapTilerDesktop 11.1 to MapTiler.MapTilerEngine 11.1
  manifests/m/MapTiler/MapTilerDesktop/11.1/MapTiler.MapTilerDesktop.installer.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.1/MapTiler.MapTilerDesktop.locale.en-US.yaml
  manifests/m/MapTiler/MapTilerDesktop/11.1/MapTiler.MapTilerDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
