Repository microsoft/winget-pkgs, pull requests merged in 2024-02, with the labels that each got.

#137389 New version: blacktop.ipsw 3.1.452
  manifests/b/blacktop/ipsw/3.1.452/blacktop.ipsw.installer.yaml
  manifests/b/blacktop/ipsw/3.1.452/blacktop.ipsw.locale.en-US.yaml
  manifests/b/blacktop/ipsw/3.1.452/blacktop.ipsw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137390 New version: blacktop.ipswd 3.1.452
  manifests/b/blacktop/ipswd/3.1.452/blacktop.ipswd.installer.yaml
  manifests/b/blacktop/ipswd/3.1.452/blacktop.ipswd.locale.en-US.yaml
  manifests/b/blacktop/ipswd/3.1.452/blacktop.ipswd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137355 New version: JetBrains.DataGrip version 2023.3.4
  manifests/j/JetBrains/DataGrip/2023.3.4/JetBrains.DataGrip.installer.yaml
  manifests/j/JetBrains/DataGrip/2023.3.4/JetBrains.DataGrip.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/2023.3.4/JetBrains.DataGrip.locale.zh-CN.yaml
  manifests/j/JetBrains/DataGrip/2023.3.4/JetBrains.DataGrip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137356 New version: Vivaldi.Vivaldi version 6.5.3206.59
  manifests/v/Vivaldi/Vivaldi/6.5.3206.59/Vivaldi.Vivaldi.installer.yaml
  manifests/v/Vivaldi/Vivaldi/6.5.3206.59/Vivaldi.Vivaldi.locale.en-US.yaml
  manifests/v/Vivaldi/Vivaldi/6.5.3206.59/Vivaldi.Vivaldi.locale.zh-CN.yaml
  manifests/v/Vivaldi/Vivaldi/6.5.3206.59/Vivaldi.Vivaldi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137361 SmartSoft.SmartFTP version 10.0.3201.0
  manifests/s/SmartSoft/SmartFTP/10.0.3201.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3201.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3201.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137362 New version: Kingston.SSDManager version 1.5.3.6
  manifests/k/Kingston/SSDManager/1.5.3.6/Kingston.SSDManager.installer.yaml
  manifests/k/Kingston/SSDManager/1.5.3.6/Kingston.SSDManager.locale.en-US.yaml
  manifests/k/Kingston/SSDManager/1.5.3.6/Kingston.SSDManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137364 Update Display Version for Zoom.Zoom version 5.17.5.31030
  manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137366 New version: blacktop.ipsw 3.1.451
  manifests/b/blacktop/ipsw/3.1.451/blacktop.ipsw.installer.yaml
  manifests/b/blacktop/ipsw/3.1.451/blacktop.ipsw.locale.en-US.yaml
  manifests/b/blacktop/ipsw/3.1.451/blacktop.ipsw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137367 New version: blacktop.ipswd 3.1.451
  manifests/b/blacktop/ipswd/3.1.451/blacktop.ipswd.installer.yaml
  manifests/b/blacktop/ipswd/3.1.451/blacktop.ipswd.locale.en-US.yaml
  manifests/b/blacktop/ipswd/3.1.451/blacktop.ipswd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137372 New version: Hashicorp.Packer version 1.10.1
  manifests/h/Hashicorp/Packer/1.10.1/Hashicorp.Packer.installer.yaml
  manifests/h/Hashicorp/Packer/1.10.1/Hashicorp.Packer.locale.en-US.yaml
  manifests/h/Hashicorp/Packer/1.10.1/Hashicorp.Packer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137376 New version: Brave.Brave version 121.1.62.156
  manifests/b/Brave/Brave/121.1.62.156/Brave.Brave.installer.yaml
  manifests/b/Brave/Brave/121.1.62.156/Brave.Brave.locale.en-US.yaml
  manifests/b/Brave/Brave/121.1.62.156/Brave.Brave.locale.zh-CN.yaml
  manifests/b/Brave/Brave/121.1.62.156/Brave.Brave.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137377 New version: Logtalk.Logtalk version 3.74.0
  manifests/l/Logtalk/Logtalk/3.74.0/Logtalk.Logtalk.installer.yaml
  manifests/l/Logtalk/Logtalk/3.74.0/Logtalk.Logtalk.locale.en-US.yaml
  manifests/l/Logtalk/Logtalk/3.74.0/Logtalk.Logtalk.locale.zh-CN.yaml
  manifests/l/Logtalk/Logtalk/3.74.0/Logtalk.Logtalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137384 New version: DoltHub.Dolt version 1.32.5
  manifests/d/DoltHub/Dolt/1.32.5/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.32.5/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.32.5/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137378 New version: Vivaldi.Vivaldi.Snapshot version 6.6.3256.4
  manifests/v/Vivaldi/Vivaldi/Snapshot/6.6.3256.4/Vivaldi.Vivaldi.Snapshot.installer.yaml
  manifests/v/Vivaldi/Vivaldi/Snapshot/6.6.3256.4/Vivaldi.Vivaldi.Snapshot.locale.en-US.yaml
  manifests/v/Vivaldi/Vivaldi/Snapshot/6.6.3256.4/Vivaldi.Vivaldi.Snapshot.locale.zh-CN.yaml
  manifests/v/Vivaldi/Vivaldi/Snapshot/6.6.3256.4/Vivaldi.Vivaldi.Snapshot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137260 New version: Zoom.Zoom version 5.17.7.31859
  manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.locale.zh-CN.yaml
  manifests/z/Zoom/Zoom/5.17.7.31859/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137394 New version: aquaproj.aqua 2.23.0
  manifests/a/aquaproj/aqua/2.23.0/aquaproj.aqua.installer.yaml
  manifests/a/aquaproj/aqua/2.23.0/aquaproj.aqua.locale.en-US.yaml
  manifests/a/aquaproj/aqua/2.23.0/aquaproj.aqua.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137353 New version: Nota.Gyazo version 5.4.2
  manifests/n/Nota/Gyazo/5.4.2/Nota.Gyazo.installer.yaml
  manifests/n/Nota/Gyazo/5.4.2/Nota.Gyazo.locale.en-US.yaml
  manifests/n/Nota/Gyazo/5.4.2/Nota.Gyazo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137352 New version: buchen.portfolio version 0.67.2
  manifests/b/buchen/portfolio/0.67.2/buchen.portfolio.installer.yaml
  manifests/b/buchen/portfolio/0.67.2/buchen.portfolio.locale.de-DE.yaml
  manifests/b/buchen/portfolio/0.67.2/buchen.portfolio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137351 New version: goreleaser.nfpm 2.35.3
  manifests/g/goreleaser/nfpm/2.35.3/goreleaser.nfpm.installer.yaml
  manifests/g/goreleaser/nfpm/2.35.3/goreleaser.nfpm.locale.en-US.yaml
  manifests/g/goreleaser/nfpm/2.35.3/goreleaser.nfpm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137349 Update PackageVersion: sylikc.JPEGView version 1.1.41.0
  manifests/s/sylikc/JPEGView/1.1.41.0/sylikc.JPEGView.installer.yaml
  manifests/s/sylikc/JPEGView/1.1.41.0/sylikc.JPEGView.locale.en-US.yaml
  manifests/s/sylikc/JPEGView/1.1.41.0/sylikc.JPEGView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137348 Update PackageVersion: sylikc.JPEGView version 1.1.43.0
  manifests/s/sylikc/JPEGView/1.1.43.0/sylikc.JPEGView.installer.yaml
  manifests/s/sylikc/JPEGView/1.1.43.0/sylikc.JPEGView.locale.en-US.yaml
  manifests/s/sylikc/JPEGView/1.1.43.0/sylikc.JPEGView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137345 Add version: Microsoft.WindowsTerminal version 1.18.10301.0
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.installer.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.en-US.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.fr-FR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.it-IT.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.ja-JP.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.ko-KR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.pt-BR.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.ru-RU.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.zh-CN.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.locale.zh-TW.yaml
  manifests/m/Microsoft/WindowsTerminal/1.18.10301.0/Microsoft.WindowsTerminal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137343 Update PackageVersion: sylikc.JPEGView version 1.2.45.0
  manifests/s/sylikc/JPEGView/1.2.45.0/sylikc.JPEGView.installer.yaml
  manifests/s/sylikc/JPEGView/1.2.45.0/sylikc.JPEGView.locale.en-US.yaml
  manifests/s/sylikc/JPEGView/1.2.45.0/sylikc.JPEGView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137342 New version: Peppy.Osu! version 2024.131.0
  manifests/p/Peppy/Osu!/2024.131.0/Peppy.Osu!.installer.yaml
  manifests/p/Peppy/Osu!/2024.131.0/Peppy.Osu!.locale.en-US.yaml
  manifests/p/Peppy/Osu!/2024.131.0/Peppy.Osu!.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-No-Executables

#137344 New version: GNU.Wget2 version 2.1.0
  manifests/g/GNU/Wget2/2.1.0/GNU.Wget2.installer.yaml
  manifests/g/GNU/Wget2/2.1.0/GNU.Wget2.locale.en-US.yaml
  manifests/g/GNU/Wget2/2.1.0/GNU.Wget2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137337 New version: shirowanisan.COEIROINK version 2.3.3
  manifests/s/shirowanisan/COEIROINK/2.3.3/shirowanisan.COEIROINK.installer.yaml
  manifests/s/shirowanisan/COEIROINK/2.3.3/shirowanisan.COEIROINK.locale.en-US.yaml
  manifests/s/shirowanisan/COEIROINK/2.3.3/shirowanisan.COEIROINK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137334 New version: SWI-Prolog.SWI-Prolog version 9.2.0
  manifests/s/SWI-Prolog/SWI-Prolog/9.2.0/SWI-Prolog.SWI-Prolog.installer.yaml
  manifests/s/SWI-Prolog/SWI-Prolog/9.2.0/SWI-Prolog.SWI-Prolog.locale.en-US.yaml
  manifests/s/SWI-Prolog/SWI-Prolog/9.2.0/SWI-Prolog.SWI-Prolog.locale.zh-CN.yaml
  manifests/s/SWI-Prolog/SWI-Prolog/9.2.0/SWI-Prolog.SWI-Prolog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137314 added a user scope install to Microsoft.OpenJDK.17 version 17.0.10.7
  manifests/m/Microsoft/OpenJDK/17/17.0.10.7/Microsoft.OpenJDK.17.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137333 New version: Reqable.Reqable version 2.6.1
  manifests/r/Reqable/Reqable/2.6.1/Reqable.Reqable.installer.yaml
  manifests/r/Reqable/Reqable/2.6.1/Reqable.Reqable.locale.en-US.yaml
  manifests/r/Reqable/Reqable/2.6.1/Reqable.Reqable.locale.zh-CN.yaml
  manifests/r/Reqable/Reqable/2.6.1/Reqable.Reqable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137296 Add MongoDB.Compass.Readonly 1.42.0.0
  manifests/m/MongoDB/Compass/Readonly/1.42.0.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.42.0.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.42.0.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137289 New version: BleuBleu.FamiStudio version 4.1.0
  manifests/b/BleuBleu/FamiStudio/4.1.0/BleuBleu.FamiStudio.installer.yaml
  manifests/b/BleuBleu/FamiStudio/4.1.0/BleuBleu.FamiStudio.locale.en-US.yaml
  manifests/b/BleuBleu/FamiStudio/4.1.0/BleuBleu.FamiStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137300 New version: BleuBleu.FamiStudio version 4.1.2
  manifests/b/BleuBleu/FamiStudio/4.1.2/BleuBleu.FamiStudio.installer.yaml
  manifests/b/BleuBleu/FamiStudio/4.1.2/BleuBleu.FamiStudio.locale.en-US.yaml
  manifests/b/BleuBleu/FamiStudio/4.1.2/BleuBleu.FamiStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137397 New version: PerfectWorld.PerfectWorldArena version 1.0.24020111
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24020111/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24020111/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24020111/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24020111/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137006 New package: SimonG4ELI.SDR-Radio.Beta version 3.3-b3195
  manifests/s/SimonG4ELI/SDR-Radio/Beta/3.3-b3195/SimonG4ELI.SDR-Radio.Beta.installer.yaml
  manifests/s/SimonG4ELI/SDR-Radio/Beta/3.3-b3195/SimonG4ELI.SDR-Radio.Beta.locale.en-US.yaml
  manifests/s/SimonG4ELI/SDR-Radio/Beta/3.3-b3195/SimonG4ELI.SDR-Radio.Beta.yaml
Labels: Validation-Completed

#137339 New version: Fort.Firewall version 3.11.0
  manifests/f/Fort/Firewall/3.11.0/Fort.Firewall.installer.yaml
  manifests/f/Fort/Firewall/3.11.0/Fort.Firewall.locale.en-US.yaml
  manifests/f/Fort/Firewall/3.11.0/Fort.Firewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137316 New version: DuongDieuPhap.ImageGlass version 9.0.10.201
  manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.installer.yaml
  manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.locale.en-US.yaml
  manifests/d/DuongDieuPhap/ImageGlass/9.0.10.201/DuongDieuPhap.ImageGlass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Installation-Error

#137400 New version: cURL.cURL version 8.6.0.1
  manifests/c/cURL/cURL/8.6.0.1/cURL.cURL.installer.yaml
  manifests/c/cURL/cURL/8.6.0.1/cURL.cURL.locale.en-US.yaml
  manifests/c/cURL/cURL/8.6.0.1/cURL.cURL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137052 New version: JetBrains.WebStorm.EAP version 241.9959.35
  manifests/j/JetBrains/WebStorm/EAP/241.9959.35/JetBrains.WebStorm.EAP.installer.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.9959.35/JetBrains.WebStorm.EAP.locale.en-US.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.9959.35/JetBrains.WebStorm.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.9959.35/JetBrains.WebStorm.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137335 New version: zhanglun.Lettura version 0.1.15
  manifests/z/zhanglun/Lettura/0.1.15/zhanglun.Lettura.installer.yaml
  manifests/z/zhanglun/Lettura/0.1.15/zhanglun.Lettura.locale.en-US.yaml
  manifests/z/zhanglun/Lettura/0.1.15/zhanglun.Lettura.locale.zh-CN.yaml
  manifests/z/zhanglun/Lettura/0.1.15/zhanglun.Lettura.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#137340 New version: shirowanisan.COEIROINK.GPU version 2.3.3
  manifests/s/shirowanisan/COEIROINK/GPU/2.3.3/shirowanisan.COEIROINK.GPU.installer.yaml
  manifests/s/shirowanisan/COEIROINK/GPU/2.3.3/shirowanisan.COEIROINK.GPU.locale.en-US.yaml
  manifests/s/shirowanisan/COEIROINK/GPU/2.3.3/shirowanisan.COEIROINK.GPU.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Shell-Execute, 1GB+

#137354 Update: GNU.Nano version 2.7.5
  manifests/g/GNU/Nano/2.7.5/GNU.Nano.installer.yaml
  manifests/g/GNU/Nano/2.7.5/GNU.Nano.locale.en-US.yaml
  manifests/g/GNU/Nano/2.7.5/GNU.Nano.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137402 New version: Ryujinx.Ryujinx version 1.1.1154
  manifests/r/Ryujinx/Ryujinx/1.1.1154/Ryujinx.Ryujinx.installer.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1154/Ryujinx.Ryujinx.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1154/Ryujinx.Ryujinx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137403 New version: Ryujinx.Ryujinx.Ava version 1.1.1154
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1154/Ryujinx.Ryujinx.Ava.installer.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1154/Ryujinx.Ryujinx.Ava.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1154/Ryujinx.Ryujinx.Ava.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137408 New version: XmacsLabs.Mogan version 1.2.4
  manifests/x/XmacsLabs/Mogan/1.2.4/XmacsLabs.Mogan.installer.yaml
  manifests/x/XmacsLabs/Mogan/1.2.4/XmacsLabs.Mogan.locale.en-US.yaml
  manifests/x/XmacsLabs/Mogan/1.2.4/XmacsLabs.Mogan.locale.zh-CN.yaml
  manifests/x/XmacsLabs/Mogan/1.2.4/XmacsLabs.Mogan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137410 ReleaseNotes: Ruben2776.PicView version 2.2.1
  manifests/r/Ruben2776/PicView/2.2.1/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/2.2.1/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/2.2.1/Ruben2776.PicView.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137312 New package: vcmi.vcmi version 1.4.5
  manifests/v/vcmi/vcmi/1.4.5/vcmi.vcmi.installer.yaml
  manifests/v/vcmi/vcmi/1.4.5/vcmi.vcmi.locale.en-US.yaml
  manifests/v/vcmi/vcmi/1.4.5/vcmi.vcmi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137415 New version: Nostalgia-09.AeroChat version 1.0.1-rc.7
  manifests/n/Nostalgia-09/AeroChat/1.0.1-rc.7/Nostalgia-09.AeroChat.installer.yaml
  manifests/n/Nostalgia-09/AeroChat/1.0.1-rc.7/Nostalgia-09.AeroChat.locale.en-US.yaml
  manifests/n/Nostalgia-09/AeroChat/1.0.1-rc.7/Nostalgia-09.AeroChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137416 New version: Jackett.Jackett version 0.21.1658
  manifests/j/Jackett/Jackett/0.21.1658/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1658/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1658/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137421 New version: Xiaoyaoyixia.KOOK version 0.80.0
  manifests/x/Xiaoyaoyixia/KOOK/0.80.0/Xiaoyaoyixia.KOOK.installer.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.80.0/Xiaoyaoyixia.KOOK.locale.en-US.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.80.0/Xiaoyaoyixia.KOOK.locale.zh-CN.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.80.0/Xiaoyaoyixia.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137423 New version: junegunn.fzf version 0.46.1
  manifests/j/junegunn/fzf/0.46.1/junegunn.fzf.installer.yaml
  manifests/j/junegunn/fzf/0.46.1/junegunn.fzf.locale.en-US.yaml
  manifests/j/junegunn/fzf/0.46.1/junegunn.fzf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137424 New version: EdrawSoft.EdrawMax version 13.0.3.1082
  manifests/e/EdrawSoft/EdrawMax/13.0.3.1082/EdrawSoft.EdrawMax.installer.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.3.1082/EdrawSoft.EdrawMax.locale.en-US.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.3.1082/EdrawSoft.EdrawMax.locale.zh-CN.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.3.1082/EdrawSoft.EdrawMax.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137425 New version: chrisant996.Clink version 1.6.3
  manifests/c/chrisant996/Clink/1.6.3/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.6.3/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.6.3/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137426 New version: AppFlowy.AppFlowy version 0.4.4
  manifests/a/AppFlowy/AppFlowy/0.4.4/AppFlowy.AppFlowy.installer.yaml
  manifests/a/AppFlowy/AppFlowy/0.4.4/AppFlowy.AppFlowy.locale.en-US.yaml
  manifests/a/AppFlowy/AppFlowy/0.4.4/AppFlowy.AppFlowy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137427 JTL WAWI 1.8.11.1
  manifests/j/JTL/Wawi/1.8.11.1/JTL.Wawi.installer.yaml
  manifests/j/JTL/Wawi/1.8.11.1/JTL.Wawi.locale.de-DE.yaml
  manifests/j/JTL/Wawi/1.8.11.1/JTL.Wawi.locale.en-US.yaml
  manifests/j/JTL/Wawi/1.8.11.1/JTL.Wawi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137420 New version: Brave.Brave.Beta version 121.1.63.141
  manifests/b/Brave/Brave/Beta/121.1.63.141/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/121.1.63.141/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/121.1.63.141/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/121.1.63.141/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137441 New version: MilosParipovic.OneCommander version 3.67.0.0
  manifests/m/MilosParipovic/OneCommander/3.67.0.0/MilosParipovic.OneCommander.installer.yaml
  manifests/m/MilosParipovic/OneCommander/3.67.0.0/MilosParipovic.OneCommander.locale.en-US.yaml
  manifests/m/MilosParipovic/OneCommander/3.67.0.0/MilosParipovic.OneCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137435 New version: JinweiZhiguang.MasterGo version 1.7.7
  manifests/j/JinweiZhiguang/MasterGo/1.7.7/JinweiZhiguang.MasterGo.installer.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.7/JinweiZhiguang.MasterGo.locale.en-US.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.7/JinweiZhiguang.MasterGo.locale.zh-CN.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.7/JinweiZhiguang.MasterGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137442 added KaiKramer.KeyStoreExplorer version 5.5.3
  manifests/k/KaiKramer/KeyStoreExplorer/5.5.3/KaiKramer.KeyStoreExplorer.installer.yaml
  manifests/k/KaiKramer/KeyStoreExplorer/5.5.3/KaiKramer.KeyStoreExplorer.locale.en-US.yaml
  manifests/k/KaiKramer/KeyStoreExplorer/5.5.3/KaiKramer.KeyStoreExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137455 Remove version: MathiasSvensson.MultiCommander version 13.1.0.2955
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.installer.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.locale.en-US.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.1.0.2955/MathiasSvensson.MultiCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback

#137467 Remove version: MonkeysAudio.MonkeysAudio version 1.019
  manifests/m/MonkeysAudio/MonkeysAudio/1.019/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.019/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.019/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137465 Remove version: MonkeysAudio.MonkeysAudio version 1.022
  manifests/m/MonkeysAudio/MonkeysAudio/1.022/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.022/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.022/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137468 Remove version: MonkeysAudio.MonkeysAudio version 1.023
  manifests/m/MonkeysAudio/MonkeysAudio/1.023/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.023/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.023/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137469 Remove version: MonkeysAudio.MonkeysAudio version 9.04
  manifests/m/MonkeysAudio/MonkeysAudio/9.04/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/9.04/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/9.04/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137463 Remove version: MonkeysAudio.MonkeysAudio version 1.028
  manifests/m/MonkeysAudio/MonkeysAudio/1.028/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.028/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.028/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137475 Remove version: MonkeysAudio.MonkeysAudio version 1.026
  manifests/m/MonkeysAudio/MonkeysAudio/1.026/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.026/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.026/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137096 Add version: TravisLane.SteamArtManager version 1.4.0
  manifests/t/TravisLane/SteamArtManager/1.4.0/TravisLane.SteamArtManager.installer.yaml
  manifests/t/TravisLane/SteamArtManager/1.4.0/TravisLane.SteamArtManager.locale.en-US.yaml
  manifests/t/TravisLane/SteamArtManager/1.4.0/TravisLane.SteamArtManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#137105 New version: TravisLane.SteamArtManager version 2.1.2
  manifests/t/TravisLane/SteamArtManager/2.1.2/TravisLane.SteamArtManager.installer.yaml
  manifests/t/TravisLane/SteamArtManager/2.1.2/TravisLane.SteamArtManager.locale.en-US.yaml
  manifests/t/TravisLane/SteamArtManager/2.1.2/TravisLane.SteamArtManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137114 New version: TravisLane.SteamArtManager version 2.8.0
  manifests/t/TravisLane/SteamArtManager/2.8.0/TravisLane.SteamArtManager.installer.yaml
  manifests/t/TravisLane/SteamArtManager/2.8.0/TravisLane.SteamArtManager.locale.en-US.yaml
  manifests/t/TravisLane/SteamArtManager/2.8.0/TravisLane.SteamArtManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Shell-Execute

#137109 New version: TravisLane.SteamArtManager version 2.6.0
  manifests/t/TravisLane/SteamArtManager/2.6.0/TravisLane.SteamArtManager.installer.yaml
  manifests/t/TravisLane/SteamArtManager/2.6.0/TravisLane.SteamArtManager.locale.en-US.yaml
  manifests/t/TravisLane/SteamArtManager/2.6.0/TravisLane.SteamArtManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137162 New version: JetBrains.TeamCity version 2023.11.3
  manifests/j/JetBrains/TeamCity/2023.11.3/JetBrains.TeamCity.installer.yaml
  manifests/j/JetBrains/TeamCity/2023.11.3/JetBrains.TeamCity.locale.en-US.yaml
  manifests/j/JetBrains/TeamCity/2023.11.3/JetBrains.TeamCity.locale.zh-CN.yaml
  manifests/j/JetBrains/TeamCity/2023.11.3/JetBrains.TeamCity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, Waived-Validation-Unattended-Failed, 1GB+

#137243 New version: Tencent.QQ.NT version 9.9.7.21217
  manifests/t/Tencent/QQ/NT/9.9.7.21217/Tencent.QQ.NT.installer.yaml
  manifests/t/Tencent/QQ/NT/9.9.7.21217/Tencent.QQ.NT.locale.en-US.yaml
  manifests/t/Tencent/QQ/NT/9.9.7.21217/Tencent.QQ.NT.locale.zh-CN.yaml
  manifests/t/Tencent/QQ/NT/9.9.7.21217/Tencent.QQ.NT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137249 Add version: errata-ai.Vale version v3.0.7
  manifests/e/errata-ai/Vale/v3.0.7/errata-ai.Vale.installer.yaml
  manifests/e/errata-ai/Vale/v3.0.7/errata-ai.Vale.locale.en-US.yaml
  manifests/e/errata-ai/Vale/v3.0.7/errata-ai.Vale.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137255 New version: Jackett.Jackett version 0.21.1650
  manifests/j/Jackett/Jackett/0.21.1650/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1650/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1650/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137311 New version: Dio.PureCodec version 20240131
  manifests/d/Dio/PureCodec/20240131/Dio.PureCodec.installer.yaml
  manifests/d/Dio/PureCodec/20240131/Dio.PureCodec.locale.en-US.yaml
  manifests/d/Dio/PureCodec/20240131/Dio.PureCodec.locale.zh-CN.yaml
  manifests/d/Dio/PureCodec/20240131/Dio.PureCodec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137430 Microsoft.VisualStudioCode.Insiders_v1.86.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.86.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#137290 New Version : Odamex.odamex 10.4.0 7 eb6 b595
  manifests/o/Odamex/Odamex/10.4.0/Odamex.Odamex.installer.yaml
  manifests/o/Odamex/Odamex/10.4.0/Odamex.Odamex.locale.en-US.yaml
  manifests/o/Odamex/Odamex/10.4.0/Odamex.Odamex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137446 New version: Taiko2k.TauonMusicBox version 7.7.0
  manifests/t/Taiko2k/TauonMusicBox/7.7.0/Taiko2k.TauonMusicBox.installer.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.7.0/Taiko2k.TauonMusicBox.locale.en-US.yaml
  manifests/t/Taiko2k/TauonMusicBox/7.7.0/Taiko2k.TauonMusicBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137454 New Version: H3poteto.whalebird desktop v6.0.0 beta.2 511 d6312
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.2/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.2/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.2/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137457 New version: h3poteto.whalebird-desktop version v6.0.0-beta.1
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.1/h3poteto.whalebird-desktop.installer.yaml
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.1/h3poteto.whalebird-desktop.locale.en-US.yaml
  manifests/h/h3poteto/whalebird-desktop/v6.0.0-beta.1/h3poteto.whalebird-desktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137472 Remove version: MonkeysAudio.MonkeysAudio version 1.017
  manifests/m/MonkeysAudio/MonkeysAudio/1.017/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.017/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.017/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137470 Remove version: MonkeysAudio.MonkeysAudio version 1.018
  manifests/m/MonkeysAudio/MonkeysAudio/1.018/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.018/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.018/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137471 Remove version: MonkeysAudio.MonkeysAudio version 1.020
  manifests/m/MonkeysAudio/MonkeysAudio/1.020/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.020/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.020/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137474 Remove version: MonkeysAudio.MonkeysAudio version 1.024
  manifests/m/MonkeysAudio/MonkeysAudio/1.024/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.024/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.024/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137141 New package: JonatanHeyman.Heynote version 1.6.0
  manifests/j/JonatanHeyman/Heynote/1.6.0/JonatanHeyman.Heynote.installer.yaml
  manifests/j/JonatanHeyman/Heynote/1.6.0/JonatanHeyman.Heynote.locale.en-US.yaml
  manifests/j/JonatanHeyman/Heynote/1.6.0/JonatanHeyman.Heynote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137473 Remove version: MonkeysAudio.MonkeysAudio version 1.029
  manifests/m/MonkeysAudio/MonkeysAudio/1.029/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.029/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.029/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#135223 Fix DisplayVersion of CUDA Toolkit
  manifests/n/Nvidia/CUDA/12.3.2/Nvidia.CUDA.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Shell-Execute

#135567 the-sz.Homedale version 2.10
  manifests/t/the-sz/Homedale/2.10/the-sz.Homedale.installer.yaml
  manifests/t/the-sz/Homedale/2.10/the-sz.Homedale.locale.en-US.yaml
  manifests/t/the-sz/Homedale/2.10/the-sz.Homedale.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137462 Remove version: MonkeysAudio.MonkeysAudio version 1.027
  manifests/m/MonkeysAudio/MonkeysAudio/1.027/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.027/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.027/MonkeysAudio.MonkeysAudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137461 Remove version: MonkeysAudio.MonkeysAudio version 1.034
  manifests/m/MonkeysAudio/MonkeysAudio/1.034/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.034/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.034/MonkeysAudio.MonkeysAudio.yaml
Labels: Validation-Completed, Moderator-Approved

#137431 Microsoft.VisualStudioCode.Insiders.CLI_v1.86.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.86.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137409 ReleaseNotes: tangshimin.MuJing version 2.2.16
  manifests/t/tangshimin/MuJing/2.2.16/tangshimin.MuJing.installer.yaml
  manifests/t/tangshimin/MuJing/2.2.16/tangshimin.MuJing.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137160 New version: BlueBubbles.BlueBubbles version 1.12.0
  manifests/b/BlueBubbles/BlueBubbles/1.12.0/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.0/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.0/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Attention, Waived-Validation-Installation-Error

#137165 New version: BlueBubbles.BlueBubbles version 1.12.2
  manifests/b/BlueBubbles/BlueBubbles/1.12.2/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.2/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.2/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Needs-Author-Feedback

#137171 New version: BlueBubbles.BlueBubbles version 1.12.6
  manifests/b/BlueBubbles/BlueBubbles/1.12.6/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.6/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.6/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Needs-Author-Feedback, Waived-Validation-Installation-Error

#137166 New version: BlueBubbles.BlueBubbles version 1.12.4
  manifests/b/BlueBubbles/BlueBubbles/1.12.4/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.4/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.4/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Waived-Validation-Installation-Error

#137172 New version: BlueBubbles.BlueBubbles version 1.12.7
  manifests/b/BlueBubbles/BlueBubbles/1.12.7/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.7/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.7/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Waived-Validation-Installation-Error

#137460 Remove version: MonkeysAudio.MonkeysAudio version 1.030
  manifests/m/MonkeysAudio/MonkeysAudio/1.030/MonkeysAudio.MonkeysAudio.installer.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.030/MonkeysAudio.MonkeysAudio.locale.en-US.yaml
  manifests/m/MonkeysAudio/MonkeysAudio/1.030/MonkeysAudio.MonkeysAudio.yaml
Labels: Validation-Completed, Needs-Attention

#137459 Add DisplayVersion for StefansTools.grepWin version 2.0.15
  manifests/s/StefansTools/grepWin/2.0.15/StefansTools.grepWin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137476 New version: MathiasSvensson.MultiCommander version 13.5.0.2983
  manifests/m/MathiasSvensson/MultiCommander/13.5.0.2983/MathiasSvensson.MultiCommander.installer.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.5.0.2983/MathiasSvensson.MultiCommander.locale.en-US.yaml
  manifests/m/MathiasSvensson/MultiCommander/13.5.0.2983/MathiasSvensson.MultiCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137477 New version: MedalB.V.Medal version 4.2309.0
  manifests/m/MedalB/V/Medal/4.2309.0/MedalB.V.Medal.installer.yaml
  manifests/m/MedalB/V/Medal/4.2309.0/MedalB.V.Medal.locale.en-US.yaml
  manifests/m/MedalB/V/Medal/4.2309.0/MedalB.V.Medal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137481 New version: f4exb.sdrangel version 7.17.3
  manifests/f/f4exb/sdrangel/7.17.3/f4exb.sdrangel.installer.yaml
  manifests/f/f4exb/sdrangel/7.17.3/f4exb.sdrangel.locale.en-US.yaml
  manifests/f/f4exb/sdrangel/7.17.3/f4exb.sdrangel.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137484 New version: OK1ZIA.Tucnak version 4.55
  manifests/o/OK1ZIA/Tucnak/4.55/OK1ZIA.Tucnak.installer.yaml
  manifests/o/OK1ZIA/Tucnak/4.55/OK1ZIA.Tucnak.locale.en-US.yaml
  manifests/o/OK1ZIA/Tucnak/4.55/OK1ZIA.Tucnak.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137101 Add version: TravisLane.SteamArtManager version 1.4.4
  manifests/t/TravisLane/SteamArtManager/1.4.4/TravisLane.SteamArtManager.installer.yaml
  manifests/t/TravisLane/SteamArtManager/1.4.4/TravisLane.SteamArtManager.locale.en-US.yaml
  manifests/t/TravisLane/SteamArtManager/1.4.4/TravisLane.SteamArtManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1

#137167 New version: BlueBubbles.BlueBubbles version 1.12.5
  manifests/b/BlueBubbles/BlueBubbles/1.12.5/BlueBubbles.BlueBubbles.installer.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.5/BlueBubbles.BlueBubbles.locale.en-US.yaml
  manifests/b/BlueBubbles/BlueBubbles/1.12.5/BlueBubbles.BlueBubbles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Needs-Author-Feedback, Waived-Validation-Installation-Error

#137433 Microsoft.VisualStudioCode.CLI_v1.86.0 cli
  manifests/m/Microsoft/VisualStudioCode/CLI/1.86.0/Microsoft.VisualStudioCode.CLI.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/CLI/1.86.0/Microsoft.VisualStudioCode.CLI.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/CLI/1.86.0/Microsoft.VisualStudioCode.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137444 New version: ov version 0.33.2
  manifests/n/noborus/ov/0.33.2/noborus.ov.installer.yaml
  manifests/n/noborus/ov/0.33.2/noborus.ov.locale.en-US.yaml
  manifests/n/noborus/ov/0.33.2/noborus.ov.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137482 New version: foldynl.QLog version 0.31.0
  manifests/f/foldynl/QLog/0.31.0/foldynl.QLog.installer.yaml
  manifests/f/foldynl/QLog/0.31.0/foldynl.QLog.locale.en-US.yaml
  manifests/f/foldynl/QLog/0.31.0/foldynl.QLog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137485 New version: Log4OM2.Log4OM2 version 2.31.0.0
  manifests/l/Log4OM2/Log4OM2/2.31.0.0/Log4OM2.Log4OM2.installer.yaml
  manifests/l/Log4OM2/Log4OM2/2.31.0.0/Log4OM2.Log4OM2.locale.en-US.yaml
  manifests/l/Log4OM2/Log4OM2/2.31.0.0/Log4OM2.Log4OM2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137492 Microsoft.VisualStudioCode.Insiders_v1.87.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.87.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.87.0/Microsoft.VisualStudioCode.Insiders.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.87.0/Microsoft.VisualStudioCode.Insiders.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137488 New version: Reqable.Reqable version 2.6.2
  manifests/r/Reqable/Reqable/2.6.2/Reqable.Reqable.installer.yaml
  manifests/r/Reqable/Reqable/2.6.2/Reqable.Reqable.locale.en-US.yaml
  manifests/r/Reqable/Reqable/2.6.2/Reqable.Reqable.locale.zh-CN.yaml
  manifests/r/Reqable/Reqable/2.6.2/Reqable.Reqable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137066 Use Repair-WinGetPackageManager as a fallback install method
  Tools/SandboxTest.ps1
Labels: Moderator-Approved, Project-File

#137490 New package: TheZDaemonTeam.ZDaemon version 1.10.24
  manifests/t/TheZDaemonTeam/ZDaemon/1.10.24/TheZDaemonTeam.ZDaemon.installer.yaml
  manifests/t/TheZDaemonTeam/ZDaemon/1.10.24/TheZDaemonTeam.ZDaemon.locale.en-US.yaml
  manifests/t/TheZDaemonTeam/ZDaemon/1.10.24/TheZDaemonTeam.ZDaemon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137417 Update version: Amazon.Kindle version 2.3.0.70673
  manifests/a/Amazon/Kindle/2.3.0.70673/Amazon.Kindle.installer.yaml
  manifests/a/Amazon/Kindle/2.3.0.70673/Amazon.Kindle.locale.en-US.yaml
  manifests/a/Amazon/Kindle/2.3.0.70673/Amazon.Kindle.yaml
Labels: Validation-Completed, Moderator-Approved

#137204 New version: Microsoft.PowerToys version 0.78.0
  manifests/m/Microsoft/PowerToys/0.78.0/Microsoft.PowerToys.installer.yaml
  manifests/m/Microsoft/PowerToys/0.78.0/Microsoft.PowerToys.locale.en-US.yaml
  manifests/m/Microsoft/PowerToys/0.78.0/Microsoft.PowerToys.yaml
Labels: Validation-Completed, Retry-1

#137494 New version: JetBrains.RubyMine.EAP version 241.10840.7
  manifests/j/JetBrains/RubyMine/EAP/241.10840.7/JetBrains.RubyMine.EAP.installer.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.10840.7/JetBrains.RubyMine.EAP.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.10840.7/JetBrains.RubyMine.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.10840.7/JetBrains.RubyMine.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137496 ReleaseNotes: JetBrains.Gateway version 2023.3.3
  manifests/j/JetBrains/Gateway/2023.3.3/JetBrains.Gateway.installer.yaml
  manifests/j/JetBrains/Gateway/2023.3.3/JetBrains.Gateway.locale.en-US.yaml
  manifests/j/JetBrains/Gateway/2023.3.3/JetBrains.Gateway.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137491 New package: KrassyK1LZ.DXLogNet version 2.5.54
  manifests/k/KrassyK1LZ/DXLogNet/2.5.54/KrassyK1LZ.DXLogNet.installer.yaml
  manifests/k/KrassyK1LZ/DXLogNet/2.5.54/KrassyK1LZ.DXLogNet.locale.en-US.yaml
  manifests/k/KrassyK1LZ/DXLogNet/2.5.54/KrassyK1LZ.DXLogNet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137505 Revert "Update Display Version for Zoom.Zoom version 5.17.5.31030"
  manifests/z/Zoom/Zoom/5.17.5.31030/Zoom.Zoom.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137534 Remove version: Microsoft.Edge.Beta version 118.0.2088.11
  manifests/m/Microsoft/Edge/Beta/118.0.2088.11/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.11/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.11/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137532 Remove version: Microsoft.Edge.Beta version 118.0.2088.41
  manifests/m/Microsoft/Edge/Beta/118.0.2088.41/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.41/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.41/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137531 Remove version: Microsoft.Edge.Beta version 119.0.2151.12
  manifests/m/Microsoft/Edge/Beta/119.0.2151.12/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/119.0.2151.12/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/119.0.2151.12/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137530 Remove version: Microsoft.Edge.Beta version 117.0.2045.27
  manifests/m/Microsoft/Edge/Beta/117.0.2045.27/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/117.0.2045.27/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/117.0.2045.27/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137533 Remove version: Microsoft.Edge.Beta version 118.0.2088.24
  manifests/m/Microsoft/Edge/Beta/118.0.2088.24/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.24/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.24/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137527 Remove version: Microsoft.Edge.Dev version 119.0.2132.0
  manifests/m/Microsoft/Edge/Dev/119.0.2132.0/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2132.0/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2132.0/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137528 Remove version: Microsoft.Edge.Beta version 118.0.2088.27
  manifests/m/Microsoft/Edge/Beta/118.0.2088.27/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.27/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/118.0.2088.27/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137525 Remove version: Microsoft.Edge.Dev version 119.0.2109.1
  manifests/m/Microsoft/Edge/Dev/119.0.2109.1/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2109.1/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2109.1/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137524 Remove version: Microsoft.Edge.Dev version 120.0.2165.1
  manifests/m/Microsoft/Edge/Dev/120.0.2165.1/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/120.0.2165.1/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/120.0.2165.1/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137523 Remove version: Microsoft.Edge.Dev version 119.0.2116.0
  manifests/m/Microsoft/Edge/Dev/119.0.2116.0/Microsoft.Edge.Dev.installer.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2116.0/Microsoft.Edge.Dev.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Dev/119.0.2116.0/Microsoft.Edge.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137520 Remove version: Microsoft.Edge version 108.0.1462.54
  manifests/m/Microsoft/Edge/108.0.1462.54/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/108.0.1462.54/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/108.0.1462.54/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/108.0.1462.54/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137521 Remove version: Microsoft.Edge version 109.0.1518.70
  manifests/m/Microsoft/Edge/109.0.1518.70/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/109.0.1518.70/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/109.0.1518.70/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/109.0.1518.70/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137515 Remove version: Microsoft.Edge version 109.0.1518.61
  manifests/m/Microsoft/Edge/109.0.1518.61/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/109.0.1518.61/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/109.0.1518.61/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/109.0.1518.61/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#137517 New version: JetBrains.Writerside.EAP version 233.14389
  manifests/j/JetBrains/Writerside/EAP/233.14389/JetBrains.Writerside.EAP.installer.yaml
  manifests/j/JetBrains/Writerside/EAP/233.14389/JetBrains.Writerside.EAP.locale.en-US.yaml
  manifests/j/JetBrains/Writerside/EAP/233.14389/JetBrains.Writerside.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/Writerside/EAP/233.14389/JetBrains.Writerside.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137329 New version: aliyunpan 0.2.9
  manifests/t/tickstep/aliyunpan/0.2.9/tickstep.aliyunpan.installer.yaml
  manifests/t/tickstep/aliyunpan/0.2.9/tickstep.aliyunpan.locale.en-US.yaml
  manifests/t/tickstep/aliyunpan/0.2.9/tickstep.aliyunpan.locale.zh-CN.yaml
  manifests/t/tickstep/aliyunpan/0.2.9/tickstep.aliyunpan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137487 New version: Mikrotik.Winbox version 3.40
  manifests/m/Mikrotik/Winbox/3.40/Mikrotik.Winbox.installer.yaml
  manifests/m/Mikrotik/Winbox/3.40/Mikrotik.Winbox.locale.en-US.yaml
  manifests/m/Mikrotik/Winbox/3.40/Mikrotik.Winbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137493 Microsoft.VisualStudioCode.Insiders.CLI_v1.87.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.87.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.87.0/Microsoft.VisualStudioCode.Insiders.CLI.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.87.0/Microsoft.VisualStudioCode.Insiders.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#137510 New version: alexx2000.DoubleCommander version 1.0.11
  manifests/a/alexx2000/DoubleCommander/1.0.11/alexx2000.DoubleCommander.installer.yaml
  manifests/a/alexx2000/DoubleCommander/1.0.11/alexx2000.DoubleCommander.locale.en-US.yaml
  manifests/a/alexx2000/DoubleCommander/1.0.11/alexx2000.DoubleCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137513 Remove version: Microsoft.Edge version 109.0.1518.55
  manifests/m/Microsoft/Edge/109.0.1518.55/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/109.0.1518.55/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/109.0.1518.55/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/109.0.1518.55/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137518 Remove version: Microsoft.Edge version 108.0.1462.76
  manifests/m/Microsoft/Edge/108.0.1462.76/Microsoft.Edge.installer.yaml
  manifests/m/Microsoft/Edge/108.0.1462.76/Microsoft.Edge.locale.en-US.yaml
  manifests/m/Microsoft/Edge/108.0.1462.76/Microsoft.Edge.locale.nb-NO.yaml
  manifests/m/Microsoft/Edge/108.0.1462.76/Microsoft.Edge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137552 Fix Maltego.Maltego to only have primary ARP entry
  manifests/m/Maltego/Maltego/4.5.0/Maltego.Maltego.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137391 New version: vim.vim.nightly version 9.1.0067
  manifests/v/vim/vim/nightly/9.1.0067/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0067/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0067/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137519 New version: TheDocumentFoundation.LibreOffice version 24.2.0.3
  manifests/t/TheDocumentFoundation/LibreOffice/24.2.0.3/TheDocumentFoundation.LibreOffice.installer.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/24.2.0.3/TheDocumentFoundation.LibreOffice.locale.en-US.yaml
  manifests/t/TheDocumentFoundation/LibreOffice/24.2.0.3/TheDocumentFoundation.LibreOffice.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137535 New version: Telegram.TelegramDesktop version 4.14.12
  manifests/t/Telegram/TelegramDesktop/4.14.12/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/4.14.12/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/4.14.12/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137536 New version: StandardNotes.StandardNotes version 3.187.3
  manifests/s/StandardNotes/StandardNotes/3.187.3/StandardNotes.StandardNotes.installer.yaml
  manifests/s/StandardNotes/StandardNotes/3.187.3/StandardNotes.StandardNotes.locale.en-US.yaml
  manifests/s/StandardNotes/StandardNotes/3.187.3/StandardNotes.StandardNotes.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137543 the-sz.Spencer version 1.32
  manifests/t/the-sz/Spencer/1.32/the-sz.Spencer.installer.yaml
  manifests/t/the-sz/Spencer/1.32/the-sz.Spencer.locale.en-US.yaml
  manifests/t/the-sz/Spencer/1.32/the-sz.Spencer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137565 Aserto.Topaz.v0.30.30
  manifests/a/Aserto/Topaz/0.30.30/Aserto.Topaz.installer.yaml
  manifests/a/Aserto/Topaz/0.30.30/Aserto.Topaz.locale.en-US.yaml
  manifests/a/Aserto/Topaz/0.30.30/Aserto.Topaz.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137569 New version: Xmind.Xmind version 24.1.13311
  manifests/x/Xmind/Xmind/24.1.13311/Xmind.Xmind.installer.yaml
  manifests/x/Xmind/Xmind/24.1.13311/Xmind.Xmind.locale.en-US.yaml
  manifests/x/Xmind/Xmind/24.1.13311/Xmind.Xmind.locale.zh-CN.yaml
  manifests/x/Xmind/Xmind/24.1.13311/Xmind.Xmind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137553 Remove duplicate AppsAndFEaturesEntries from opentrack.opentrack as it's overriden at installer level
  manifests/o/opentrack/opentrack/2022.3.2/opentrack.opentrack.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137570 New version: DoltHub.Dolt version 1.32.6
  manifests/d/DoltHub/Dolt/1.32.6/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.32.6/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.32.6/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#137551 NTKERNEL.WireSockVPNClient version 1.2.37
  manifests/n/NTKERNEL/WireSockVPNClient/1.2.37/NTKERNEL.WireSockVPNClient.installer.yaml
  manifests/n/NTKERNEL/WireSockVPNClient/1.2.37/NTKERNEL.WireSockVPNClient.locale.en-US.yaml
  manifests/n/NTKERNEL/WireSockVPNClient/1.2.37/NTKERNEL.WireSockVPNClient.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#137547 NTKERNEL.WireSockVPNGateway version 1.1.4
  manifests/n/NTKERNEL/WireSockVPNGateway/1.1.4/NTKERNEL.WireSockVPNGateway.installer.yaml
  manifests/n/NTKERNEL/WireSockVPNGateway/1.1.4/NTKERNEL.WireSockVPNGateway.locale.en-US.yaml
  manifests/n/NTKERNEL/WireSockVPNGateway/1.1.4/NTKERNEL.WireSockVPNGateway.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved
