Repository microsoft/winget-pkgs, pull requests merged in 2024-01, with the labels that each got.

#132297 New version: Jackett.Jackett version 0.21.1468
  manifests/j/Jackett/Jackett/0.21.1468/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1468/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1468/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132350 JanDeDobbeleer.OhMyPosh version 19.3.1
  manifests/j/JanDeDobbeleer/OhMyPosh/19.3.1/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.3.1/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/19.3.1/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132381 New package: Fort.Firewall version 3.10.6
  manifests/f/Fort/Firewall/3.10.6/Fort.Firewall.installer.yaml
  manifests/f/Fort/Firewall/3.10.6/Fort.Firewall.locale.en-US.yaml
  manifests/f/Fort/Firewall/3.10.6/Fort.Firewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#115971 Update version: oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1 version 1.1.0
  manifests/o/oxygendioxide/Deepvocal-Hitsuboku-Kumi-CHN-dv1/1.1.0/oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1.installer.yaml
  manifests/o/oxygendioxide/Deepvocal-Hitsuboku-Kumi-CHN-dv1/1.1.0/oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1.locale.en-US.yaml
  manifests/o/oxygendioxide/Deepvocal-Hitsuboku-Kumi-CHN-dv1/1.1.0/oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Waived-Validation-Executable-Error, Waived-Validation-No-Executables, 1GB+

#132191 New version: Datronicsoft.SpacedeskDriver.Server version 2.1.0.6
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.0.6/Datronicsoft.SpacedeskDriver.Server.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.0.6/Datronicsoft.SpacedeskDriver.Server.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.0.6/Datronicsoft.SpacedeskDriver.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132187 New version: Proton.ProtonDrive version 1.4.6
  manifests/p/Proton/ProtonDrive/1.4.6/Proton.ProtonDrive.installer.yaml
  manifests/p/Proton/ProtonDrive/1.4.6/Proton.ProtonDrive.locale.en-US.yaml
  manifests/p/Proton/ProtonDrive/1.4.6/Proton.ProtonDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132186 New version: Sogou.SogouInput version 13.13.0.8820
  manifests/s/Sogou/SogouInput/13.13.0.8820/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/13.13.0.8820/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/13.13.0.8820/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/13.13.0.8820/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132184 Ant Commander Pro version 4.4
  manifests/j/Japplis/AntCommander/Pro/4.4/Japplis.AntCommander.Pro.installer.yaml
  manifests/j/Japplis/AntCommander/Pro/4.4/Japplis.AntCommander.Pro.locale.en-US.yaml
  manifests/j/Japplis/AntCommander/Pro/4.4/Japplis.AntCommander.Pro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132182 SmartSoft.SmartFTP version 10.0.3192.0
  manifests/s/SmartSoft/SmartFTP/10.0.3192.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3192.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3192.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132179 New version: Baidu.BaiduPinyin version 6.1.0.16
  manifests/b/Baidu/BaiduPinyin/6.1.0.16/Baidu.BaiduPinyin.installer.yaml
  manifests/b/Baidu/BaiduPinyin/6.1.0.16/Baidu.BaiduPinyin.locale.en-US.yaml
  manifests/b/Baidu/BaiduPinyin/6.1.0.16/Baidu.BaiduPinyin.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduPinyin/6.1.0.16/Baidu.BaiduPinyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132177 New version: Casey.Just version 1.21.0
  manifests/c/Casey/Just/1.21.0/Casey.Just.installer.yaml
  manifests/c/Casey/Just/1.21.0/Casey.Just.locale.en-US.yaml
  manifests/c/Casey/Just/1.21.0/Casey.Just.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132171 New version: DW.Spectrum.Client version 5.1.1.37512
  manifests/d/DW/Spectrum/Client/5.1.1.37512/DW.Spectrum.Client.installer.yaml
  manifests/d/DW/Spectrum/Client/5.1.1.37512/DW.Spectrum.Client.locale.en-US.yaml
  manifests/d/DW/Spectrum/Client/5.1.1.37512/DW.Spectrum.Client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132167 Add JGraph.Draw 22.1.16
  manifests/j/JGraph/Draw/22.1.16/JGraph.Draw.installer.yaml
  manifests/j/JGraph/Draw/22.1.16/JGraph.Draw.locale.en-US.yaml
  manifests/j/JGraph/Draw/22.1.16/JGraph.Draw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132164 New version: Nexova.UpdateHub version 2.3.4
  manifests/n/Nexova/UpdateHub/2.3.4/Nexova.UpdateHub.installer.yaml
  manifests/n/Nexova/UpdateHub/2.3.4/Nexova.UpdateHub.locale.en-US.yaml
  manifests/n/Nexova/UpdateHub/2.3.4/Nexova.UpdateHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132163 New version: DoltHub.Dolt version 1.30.3
  manifests/d/DoltHub/Dolt/1.30.3/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.30.3/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.30.3/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132142 New version: Microsoft.Azure.Kubelogin version 0.1.0
  manifests/m/Microsoft/Azure/Kubelogin/0.1.0/Microsoft.Azure.Kubelogin.installer.yaml
  manifests/m/Microsoft/Azure/Kubelogin/0.1.0/Microsoft.Azure.Kubelogin.locale.en-US.yaml
  manifests/m/Microsoft/Azure/Kubelogin/0.1.0/Microsoft.Azure.Kubelogin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132018 update `Miller.Miller` to `6.10.0`
  manifests/m/Miller/Miller/6.10.0/Miller.Miller.installer.yaml
  manifests/m/Miller/Miller/6.10.0/Miller.Miller.locale.en-US.yaml
  manifests/m/Miller/Miller/6.10.0/Miller.Miller.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#132192 New version: CI010.XMinecraftLauncher version 0.39.3.691
  manifests/c/CI010/XMinecraftLauncher/0.39.3.691/CI010.XMinecraftLauncher.installer.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.3.691/CI010.XMinecraftLauncher.locale.zh-CN.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.3.691/CI010.XMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132193 New version: 7S2P.Effie.CN version 3.0.13
  manifests/7/7S2P/Effie/CN/3.0.13/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.0.13/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.0.13/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.0.13/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132194 New version: Micron Storage Executive version 9.09.092023.03
  manifests/m/MicronTechnology/MicronStorageExecutive/9.09.092023.03/MicronTechnology.MicronStorageExecutive.installer.yaml
  manifests/m/MicronTechnology/MicronStorageExecutive/9.09.092023.03/MicronTechnology.MicronStorageExecutive.locale.en-US.yaml
  manifests/m/MicronTechnology/MicronStorageExecutive/9.09.092023.03/MicronTechnology.MicronStorageExecutive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132196 New version: MyCloudGame.AirGameServer version 1.6.8-x64
  manifests/m/MyCloudGame/AirGameServer/1.6.8-x64/MyCloudGame.AirGameServer.installer.yaml
  manifests/m/MyCloudGame/AirGameServer/1.6.8-x64/MyCloudGame.AirGameServer.locale.en-US.yaml
  manifests/m/MyCloudGame/AirGameServer/1.6.8-x64/MyCloudGame.AirGameServer.locale.zh-CN.yaml
  manifests/m/MyCloudGame/AirGameServer/1.6.8-x64/MyCloudGame.AirGameServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132197 New version: MyCloudGame.AirGamePlay version 1.6.8-x64
  manifests/m/MyCloudGame/AirGamePlay/1.6.8-x64/MyCloudGame.AirGamePlay.installer.yaml
  manifests/m/MyCloudGame/AirGamePlay/1.6.8-x64/MyCloudGame.AirGamePlay.locale.en-US.yaml
  manifests/m/MyCloudGame/AirGamePlay/1.6.8-x64/MyCloudGame.AirGamePlay.locale.zh-CN.yaml
  manifests/m/MyCloudGame/AirGamePlay/1.6.8-x64/MyCloudGame.AirGamePlay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132236 New version: Infracost.Infracost version 0.10.31
  manifests/i/Infracost/Infracost/0.10.31/Infracost.Infracost.installer.yaml
  manifests/i/Infracost/Infracost/0.10.31/Infracost.Infracost.locale.en-US.yaml
  manifests/i/Infracost/Infracost/0.10.31/Infracost.Infracost.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132234 New version: AquaSecurity.Trivy version 0.48.1
  manifests/a/AquaSecurity/Trivy/0.48.1/AquaSecurity.Trivy.installer.yaml
  manifests/a/AquaSecurity/Trivy/0.48.1/AquaSecurity.Trivy.locale.en-US.yaml
  manifests/a/AquaSecurity/Trivy/0.48.1/AquaSecurity.Trivy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132231 New version: Gramps.Gramps version 5.1.6
  manifests/g/Gramps/Gramps/5.1.6/Gramps.Gramps.installer.yaml
  manifests/g/Gramps/Gramps/5.1.6/Gramps.Gramps.locale.en-US.yaml
  manifests/g/Gramps/Gramps/5.1.6/Gramps.Gramps.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132229 New version: TuxGuitar.TuxGuitar version 1.6.0
  manifests/t/TuxGuitar/TuxGuitar/1.6.0/TuxGuitar.TuxGuitar.installer.yaml
  manifests/t/TuxGuitar/TuxGuitar/1.6.0/TuxGuitar.TuxGuitar.locale.en-US.yaml
  manifests/t/TuxGuitar/TuxGuitar/1.6.0/TuxGuitar.TuxGuitar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132227 Version Update: TeamProwlarr.Prowlarr version 1.11.4
  manifests/t/TeamProwlarr/Prowlarr/1.11.4/TeamProwlarr.Prowlarr.installer.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.11.4/TeamProwlarr.Prowlarr.locale.en-US.yaml
  manifests/t/TeamProwlarr/Prowlarr/1.11.4/TeamProwlarr.Prowlarr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#131131 New version: mlocati.GetText version 0.21
  manifests/m/mlocati/GetText/0.21/mlocati.GetText.installer.yaml
  manifests/m/mlocati/GetText/0.21/mlocati.GetText.locale.en-US.yaml
  manifests/m/mlocati/GetText/0.21/mlocati.GetText.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132226 New version: electerm.electerm version 1.37.106
  manifests/e/electerm/electerm/1.37.106/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.37.106/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.37.106/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132223 New version: DuongDieuPhap.ImageGlass version 9.0.9.1230
  manifests/d/DuongDieuPhap/ImageGlass/9.0.9.1230/DuongDieuPhap.ImageGlass.installer.yaml
  manifests/d/DuongDieuPhap/ImageGlass/9.0.9.1230/DuongDieuPhap.ImageGlass.locale.en-US.yaml
  manifests/d/DuongDieuPhap/ImageGlass/9.0.9.1230/DuongDieuPhap.ImageGlass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132219 Update Microsoft.EdgeWebView2Runtime: add ProductCode
  manifests/m/Microsoft/EdgeWebView2Runtime/119.0.2151.58/Microsoft.EdgeWebView2Runtime.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback

#132208 New version: Streetwriters.Notesnook version 2.6.13
  manifests/s/Streetwriters/Notesnook/2.6.13/Streetwriters.Notesnook.installer.yaml
  manifests/s/Streetwriters/Notesnook/2.6.13/Streetwriters.Notesnook.locale.en-US.yaml
  manifests/s/Streetwriters/Notesnook/2.6.13/Streetwriters.Notesnook.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132207 New version: Mobatek.MobaXterm version 23.6.0.5186
  manifests/m/Mobatek/MobaXterm/23.6.0.5186/Mobatek.MobaXterm.installer.yaml
  manifests/m/Mobatek/MobaXterm/23.6.0.5186/Mobatek.MobaXterm.locale.en-US.yaml
  manifests/m/Mobatek/MobaXterm/23.6.0.5186/Mobatek.MobaXterm.locale.zh-CN.yaml
  manifests/m/Mobatek/MobaXterm/23.6.0.5186/Mobatek.MobaXterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132204 New version: DoltHub.Dolt version 1.30.4
  manifests/d/DoltHub/Dolt/1.30.4/DoltHub.Dolt.installer.yaml
  manifests/d/DoltHub/Dolt/1.30.4/DoltHub.Dolt.locale.en-US.yaml
  manifests/d/DoltHub/Dolt/1.30.4/DoltHub.Dolt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132200 New version: JPEXS.FFDec version 20.1.0
  manifests/j/JPEXS/FFDec/20.1.0/JPEXS.FFDec.installer.yaml
  manifests/j/JPEXS/FFDec/20.1.0/JPEXS.FFDec.locale.en-US.yaml
  manifests/j/JPEXS/FFDec/20.1.0/JPEXS.FFDec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132198 New package: Line6.Line6Central version 1.00
  manifests/l/Line6/Line6Central/1.00/Line6.Line6Central.installer.yaml
  manifests/l/Line6/Line6Central/1.00/Line6.Line6Central.locale.en-US.yaml
  manifests/l/Line6/Line6Central/1.00/Line6.Line6Central.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132237 New version: buchen.portfolio version 0.67.0
  manifests/b/buchen/portfolio/0.67.0/buchen.portfolio.installer.yaml
  manifests/b/buchen/portfolio/0.67.0/buchen.portfolio.locale.de-DE.yaml
  manifests/b/buchen/portfolio/0.67.0/buchen.portfolio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132240 New version: th-ch.YouTubeMusic version 3.2.0
  manifests/t/th-ch/YouTubeMusic/3.2.0/th-ch.YouTubeMusic.installer.yaml
  manifests/t/th-ch/YouTubeMusic/3.2.0/th-ch.YouTubeMusic.locale.en-US.yaml
  manifests/t/th-ch/YouTubeMusic/3.2.0/th-ch.YouTubeMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132241 New version: AgileStudio.33ZiMu version 1.0.0
  manifests/a/AgileStudio/33ZiMu/1.0.0/AgileStudio.33ZiMu.installer.yaml
  manifests/a/AgileStudio/33ZiMu/1.0.0/AgileStudio.33ZiMu.locale.en-US.yaml
  manifests/a/AgileStudio/33ZiMu/1.0.0/AgileStudio.33ZiMu.locale.zh-CN.yaml
  manifests/a/AgileStudio/33ZiMu/1.0.0/AgileStudio.33ZiMu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132243 New version: yt-dlp.yt-dlp version 2023.12.30
  manifests/y/yt-dlp/yt-dlp/2023.12.30/yt-dlp.yt-dlp.installer.yaml
  manifests/y/yt-dlp/yt-dlp/2023.12.30/yt-dlp.yt-dlp.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/2023.12.30/yt-dlp.yt-dlp.locale.zh-CN.yaml
  manifests/y/yt-dlp/yt-dlp/2023.12.30/yt-dlp.yt-dlp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132244 New version: rcmaehl.MSEdgeRedirect version 0.7.5.3
  manifests/r/rcmaehl/MSEdgeRedirect/0.7.5.3/rcmaehl.MSEdgeRedirect.installer.yaml
  manifests/r/rcmaehl/MSEdgeRedirect/0.7.5.3/rcmaehl.MSEdgeRedirect.locale.en-US.yaml
  manifests/r/rcmaehl/MSEdgeRedirect/0.7.5.3/rcmaehl.MSEdgeRedirect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132254 New version: 5E.5EClient version 7.1.34
  manifests/5/5E/5EClient/7.1.34/5E.5EClient.installer.yaml
  manifests/5/5E/5EClient/7.1.34/5E.5EClient.locale.en-US.yaml
  manifests/5/5E/5EClient/7.1.34/5E.5EClient.locale.zh-CN.yaml
  manifests/5/5E/5EClient/7.1.34/5E.5EClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132257 New version: Spicetify.Spicetify version 2.29.0
  manifests/s/Spicetify/Spicetify/2.29.0/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.29.0/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.29.0/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132263 New version: Taozuhong.Kangaroo 4.0.0
  manifests/t/Taozuhong/Kangaroo/4.0.0.240101/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/4.0.0.240101/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/4.0.0.240101/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/4.0.0.240101/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132262 New version: th-ch.YouTubeMusic version 3.2.1
  manifests/t/th-ch/YouTubeMusic/3.2.1/th-ch.YouTubeMusic.installer.yaml
  manifests/t/th-ch/YouTubeMusic/3.2.1/th-ch.YouTubeMusic.locale.en-US.yaml
  manifests/t/th-ch/YouTubeMusic/3.2.1/th-ch.YouTubeMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132277 SagerNet.sing-box version 1.7.6
  manifests/s/SagerNet/sing-box/1.7.6/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.7.6/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.7.6/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132278 SagerNet.sing-box version 1.7.7
  manifests/s/SagerNet/sing-box/1.7.7/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.7.7/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.7.7/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132281 New version: Spicetify.Spicetify version 2.29.1
  manifests/s/Spicetify/Spicetify/2.29.1/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.29.1/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.29.1/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132422 New package: GoXLR-on-Linux.GoXLR-Utility version 1.0.3
  manifests/g/GoXLR-on-Linux/GoXLR-Utility/1.0.3/GoXLR-on-Linux.GoXLR-Utility.installer.yaml
  manifests/g/GoXLR-on-Linux/GoXLR-Utility/1.0.3/GoXLR-on-Linux.GoXLR-Utility.locale.en-GB.yaml
  manifests/g/GoXLR-on-Linux/GoXLR-Utility/1.0.3/GoXLR-on-Linux.GoXLR-Utility.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132402 New package: QuadSpinner.Gaea version 1.3.2.7
  manifests/q/QuadSpinner/Gaea/1.3.2.7/QuadSpinner.Gaea.installer.yaml
  manifests/q/QuadSpinner/Gaea/1.3.2.7/QuadSpinner.Gaea.locale.en-US.yaml
  manifests/q/QuadSpinner/Gaea/1.3.2.7/QuadSpinner.Gaea.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132425 Lint Community Scripts
  Tools/PRTest.ps1
  Tools/SandboxTest.ps1
  Tools/WingetVersionManager.ps1
  Tools/YamlCreate.ps1
Labels: Moderator-Approved

#131290 Remove Microsoft.AppInstaller version 1.21.3421
  manifests/m/Microsoft/AppInstaller/1.21.3421/Microsoft.AppInstaller.installer.yaml
  manifests/m/Microsoft/AppInstaller/1.21.3421/Microsoft.AppInstaller.locale.en-US.yaml
  manifests/m/Microsoft/AppInstaller/1.21.3421/Microsoft.AppInstaller.yaml
Labels: Internal-Error-Manifest, Moderator-Approved, Needs-Attention

#107311 New version: Levminer.Authme version 4.1.0
  manifests/l/Levminer/Authme/4.1.0/Levminer.Authme.installer.yaml
  manifests/l/Levminer/Authme/4.1.0/Levminer.Authme.locale.en-US.yaml
  manifests/l/Levminer/Authme/4.1.0/Levminer.Authme.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved

#22900 Readded package: Aurora.Aurora version v0.8.1
  manifests/a/Aurora/Aurora/v0.8.1/Aurora.Aurora.installer.yaml
  manifests/a/Aurora/Aurora/v0.8.1/Aurora.Aurora.locale.en-US.yaml
  manifests/a/Aurora/Aurora/v0.8.1/Aurora.Aurora.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Moderator-Approved, Waived-Validation-Unattended-Failed, Validation-Missing-Dependency

#132284 New version: Gyan.FFmpeg version 6.1.1
  manifests/g/Gyan/FFmpeg/6.1.1/Gyan.FFmpeg.installer.yaml
  manifests/g/Gyan/FFmpeg/6.1.1/Gyan.FFmpeg.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/6.1.1/Gyan.FFmpeg.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/6.1.1/Gyan.FFmpeg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132285 New version: Gyan.FFmpeg.Shared version 6.1.1
  manifests/g/Gyan/FFmpeg/Shared/6.1.1/Gyan.FFmpeg.Shared.installer.yaml
  manifests/g/Gyan/FFmpeg/Shared/6.1.1/Gyan.FFmpeg.Shared.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/Shared/6.1.1/Gyan.FFmpeg.Shared.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/Shared/6.1.1/Gyan.FFmpeg.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132286 New version: zhanglun.Lettura version 0.1.12
  manifests/z/zhanglun/Lettura/0.1.12/zhanglun.Lettura.installer.yaml
  manifests/z/zhanglun/Lettura/0.1.12/zhanglun.Lettura.locale.en-US.yaml
  manifests/z/zhanglun/Lettura/0.1.12/zhanglun.Lettura.locale.zh-CN.yaml
  manifests/z/zhanglun/Lettura/0.1.12/zhanglun.Lettura.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#111429 New package: jayhuang75.med version 0.6.2
  manifests/j/jayhuang75/med/0.6.2/jayhuang75.med.installer.yaml
  manifests/j/jayhuang75/med/0.6.2/jayhuang75.med.locale.en-US.yaml
  manifests/j/jayhuang75/med/0.6.2/jayhuang75.med.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Dependencies, Waived-Validation-Executable-Error

#132340 DEVCOM.LuaJIT version 2.1.19714
  manifests/d/DEVCOM/LuaJIT/2.1.19714/DEVCOM.LuaJIT.installer.yaml
  manifests/d/DEVCOM/LuaJIT/2.1.19714/DEVCOM.LuaJIT.locale.en-US.yaml
  manifests/d/DEVCOM/LuaJIT/2.1.19714/DEVCOM.LuaJIT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132341 FileVoyager.FileVoyager version 24.1.1.0
  manifests/f/FileVoyager/FileVoyager/24.1.1.0/FileVoyager.FileVoyager.installer.yaml
  manifests/f/FileVoyager/FileVoyager/24.1.1.0/FileVoyager.FileVoyager.locale.en-US.yaml
  manifests/f/FileVoyager/FileVoyager/24.1.1.0/FileVoyager.FileVoyager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132347 New version: Gyan.FFmpeg.Essentials version 6.1.1
  manifests/g/Gyan/FFmpeg/Essentials/6.1.1/Gyan.FFmpeg.Essentials.installer.yaml
  manifests/g/Gyan/FFmpeg/Essentials/6.1.1/Gyan.FFmpeg.Essentials.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/Essentials/6.1.1/Gyan.FFmpeg.Essentials.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132349 New version: defi.defi version 4.0.8
  manifests/d/defi/defi/4.0.8/defi.defi.installer.yaml
  manifests/d/defi/defi/4.0.8/defi.defi.locale.en-US.yaml
  manifests/d/defi/defi/4.0.8/defi.defi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132356 Update version: B3log.SiYuan version 2.11.4
  manifests/b/B3log/SiYuan/2.11.4/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.11.4/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.11.4/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.11.4/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132360 New version: AppbyTroye.KoodoReader version 1.6.1
  manifests/a/AppbyTroye/KoodoReader/1.6.1/AppbyTroye.KoodoReader.installer.yaml
  manifests/a/AppbyTroye/KoodoReader/1.6.1/AppbyTroye.KoodoReader.locale.en-US.yaml
  manifests/a/AppbyTroye/KoodoReader/1.6.1/AppbyTroye.KoodoReader.locale.zh-CN.yaml
  manifests/a/AppbyTroye/KoodoReader/1.6.1/AppbyTroye.KoodoReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132363 New version: clouDr-f2e.rubick version 4.2.1
  manifests/c/clouDr-f2e/rubick/4.2.1/clouDr-f2e.rubick.installer.yaml
  manifests/c/clouDr-f2e/rubick/4.2.1/clouDr-f2e.rubick.locale.en-US.yaml
  manifests/c/clouDr-f2e/rubick/4.2.1/clouDr-f2e.rubick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132378 Update version: KeePassXCTeam.KeePassXC version 2.7.6
  manifests/k/KeePassXCTeam/KeePassXC/2.7.6/KeePassXCTeam.KeePassXC.installer.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.6/KeePassXCTeam.KeePassXC.locale.en-US.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.6/KeePassXCTeam.KeePassXC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132382 New version: CI010.XMinecraftLauncher version 0.39.5.695
  manifests/c/CI010/XMinecraftLauncher/0.39.5.695/CI010.XMinecraftLauncher.installer.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.5.695/CI010.XMinecraftLauncher.locale.zh-CN.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.5.695/CI010.XMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132383 New version: B3log.SiYuan version 2.12.0
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.installer.yaml
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.locale.zh-CN.yaml
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132387 Remove version: ManuelLaggner.tinyMediaManager version v4
  manifests/m/ManuelLaggner/tinyMediaManager/v4/ManuelLaggner.tinyMediaManager.installer.yaml
  manifests/m/ManuelLaggner/tinyMediaManager/v4/ManuelLaggner.tinyMediaManager.locale.en-US.yaml
  manifests/m/ManuelLaggner/tinyMediaManager/v4/ManuelLaggner.tinyMediaManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132390 New version: Ruben2776.PicView version 2.2
  manifests/r/Ruben2776/PicView/2.2/Ruben2776.PicView.installer.yaml
  manifests/r/Ruben2776/PicView/2.2/Ruben2776.PicView.locale.en-US.yaml
  manifests/r/Ruben2776/PicView/2.2/Ruben2776.PicView.locale.zh-CN.yaml
  manifests/r/Ruben2776/PicView/2.2/Ruben2776.PicView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132391 New version: Appest.Dida version 5.0.4.0
  manifests/a/Appest/Dida/5.0.4.0/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/5.0.4.0/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/5.0.4.0/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/5.0.4.0/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132393 New version: Tencent.WeixinDevTools version 1.06.2312070
  manifests/t/Tencent/WeixinDevTools/1.06.2312070/Tencent.WeixinDevTools.installer.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2312070/Tencent.WeixinDevTools.locale.en-US.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2312070/Tencent.WeixinDevTools.locale.zh-CN.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2312070/Tencent.WeixinDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132392 New version: THS.THS.Hevo version 9.4.1.3
  manifests/t/THS/THS/Hevo/9.4.1.3/THS.THS.Hevo.installer.yaml
  manifests/t/THS/THS/Hevo/9.4.1.3/THS.THS.Hevo.locale.en-US.yaml
  manifests/t/THS/THS/Hevo/9.4.1.3/THS.THS.Hevo.locale.zh-CN.yaml
  manifests/t/THS/THS/Hevo/9.4.1.3/THS.THS.Hevo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132396 Wiesemann-Theis.USB-Redirector version 3.72
  manifests/w/Wiesemann-Theis/USB-Redirector/3.72/Wiesemann-Theis.USB-Redirector.installer.yaml
  manifests/w/Wiesemann-Theis/USB-Redirector/3.72/Wiesemann-Theis.USB-Redirector.locale.de-DE.yaml
  manifests/w/Wiesemann-Theis/USB-Redirector/3.72/Wiesemann-Theis.USB-Redirector.locale.en-US.yaml
  manifests/w/Wiesemann-Theis/USB-Redirector/3.72/Wiesemann-Theis.USB-Redirector.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132406 New version: tumic0.GPXSee version 13.14
  manifests/t/tumic0/GPXSee/13.14/tumic0.GPXSee.installer.yaml
  manifests/t/tumic0/GPXSee/13.14/tumic0.GPXSee.locale.en-US.yaml
  manifests/t/tumic0/GPXSee/13.14/tumic0.GPXSee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132404 New version: CI010.XMinecraftLauncher version 0.39.7.698
  manifests/c/CI010/XMinecraftLauncher/0.39.7.698/CI010.XMinecraftLauncher.installer.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.7.698/CI010.XMinecraftLauncher.locale.zh-CN.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.7.698/CI010.XMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132403 New version: Wondershare.MobileTrans version 4.5.4
  manifests/w/Wondershare/MobileTrans/4.5.4/Wondershare.MobileTrans.installer.yaml
  manifests/w/Wondershare/MobileTrans/4.5.4/Wondershare.MobileTrans.locale.en-US.yaml
  manifests/w/Wondershare/MobileTrans/4.5.4/Wondershare.MobileTrans.locale.zh-CN.yaml
  manifests/w/Wondershare/MobileTrans/4.5.4/Wondershare.MobileTrans.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132400 New version: CI010.XMinecraftLauncher version 0.39.6.697
  manifests/c/CI010/XMinecraftLauncher/0.39.6.697/CI010.XMinecraftLauncher.installer.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.6.697/CI010.XMinecraftLauncher.locale.zh-CN.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.6.697/CI010.XMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132401 New version: sebescudie.GammaLauncher version 5.2.2
  manifests/s/sebescudie/GammaLauncher/5.2.2/sebescudie.GammaLauncher.installer.yaml
  manifests/s/sebescudie/GammaLauncher/5.2.2/sebescudie.GammaLauncher.locale.en-US.yaml
  manifests/s/sebescudie/GammaLauncher/5.2.2/sebescudie.GammaLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132407 Remove version: tumic0.GPXSee version 13.11
  manifests/t/tumic0/GPXSee/13.11/tumic0.GPXSee.installer.yaml
  manifests/t/tumic0/GPXSee/13.11/tumic0.GPXSee.locale.en-US.yaml
  manifests/t/tumic0/GPXSee/13.11/tumic0.GPXSee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132408 New version: tumic0.GPXSee version 13.13
  manifests/t/tumic0/GPXSee/13.13/tumic0.GPXSee.installer.yaml
  manifests/t/tumic0/GPXSee/13.13/tumic0.GPXSee.locale.en-US.yaml
  manifests/t/tumic0/GPXSee/13.13/tumic0.GPXSee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132414 New version: Huawei.Welink version 7.36.7
  manifests/h/Huawei/Welink/7.36.7/Huawei.Welink.installer.yaml
  manifests/h/Huawei/Welink/7.36.7/Huawei.Welink.locale.en-US.yaml
  manifests/h/Huawei/Welink/7.36.7/Huawei.Welink.locale.zh-CN.yaml
  manifests/h/Huawei/Welink/7.36.7/Huawei.Welink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132415 New version: JinweiZhiguang.MasterGo version 1.7.5
  manifests/j/JinweiZhiguang/MasterGo/1.7.5/JinweiZhiguang.MasterGo.installer.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.5/JinweiZhiguang.MasterGo.locale.en-US.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.5/JinweiZhiguang.MasterGo.locale.zh-CN.yaml
  manifests/j/JinweiZhiguang/MasterGo/1.7.5/JinweiZhiguang.MasterGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132420 New version: chylex.DiscordHistoryTracker version 40.0
  manifests/c/chylex/DiscordHistoryTracker/40.0/chylex.DiscordHistoryTracker.installer.yaml
  manifests/c/chylex/DiscordHistoryTracker/40.0/chylex.DiscordHistoryTracker.locale.en-US.yaml
  manifests/c/chylex/DiscordHistoryTracker/40.0/chylex.DiscordHistoryTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132429 New version: JanProchazka.dbgate version 5.2.7
  manifests/j/JanProchazka/dbgate/5.2.7/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/5.2.7/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/5.2.7/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132416 New version: DEVCOM.LuaJIT version 2.1.1703358377
  manifests/d/DEVCOM/LuaJIT/2.1.1703358377/DEVCOM.LuaJIT.installer.yaml
  manifests/d/DEVCOM/LuaJIT/2.1.1703358377/DEVCOM.LuaJIT.locale.en-US.yaml
  manifests/d/DEVCOM/LuaJIT/2.1.1703358377/DEVCOM.LuaJIT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132424 New version: Sandboxie.Plus version 1.12.6
  manifests/s/Sandboxie/Plus/1.12.6/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/1.12.6/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/1.12.6/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132423 New version: Sandboxie.Classic version 5.67.6
  manifests/s/Sandboxie/Classic/5.67.6/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.67.6/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.67.6/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132445 Remove: Yandex.PuntoSwitcher version 4.4.4.489
  manifests/y/Yandex/PuntoSwitcher/4.4.4.489/Yandex.PuntoSwitcher.installer.yaml
  manifests/y/Yandex/PuntoSwitcher/4.4.4.489/Yandex.PuntoSwitcher.locale.en-US.yaml
  manifests/y/Yandex/PuntoSwitcher/4.4.4.489/Yandex.PuntoSwitcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132438 New version: EdrawSoft.EdrawMax version 13.0.2.1071
  manifests/e/EdrawSoft/EdrawMax/13.0.2.1071/EdrawSoft.EdrawMax.installer.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.2.1071/EdrawSoft.EdrawMax.locale.en-US.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.2.1071/EdrawSoft.EdrawMax.locale.zh-CN.yaml
  manifests/e/EdrawSoft/EdrawMax/13.0.2.1071/EdrawSoft.EdrawMax.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132437 New version: Brave.Brave.Nightly version 120.1.63.87
  manifests/b/Brave/Brave/Nightly/120.1.63.87/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.87/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.87/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.87/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132458 Remove: 360.360File version 1.0.0.1130
  manifests/3/360/360File/1.0.0.1130/360.360File.installer.yaml
  manifests/3/360/360File/1.0.0.1130/360.360File.locale.en-US.yaml
  manifests/3/360/360File/1.0.0.1130/360.360File.locale.zh-CN.yaml
  manifests/3/360/360File/1.0.0.1130/360.360File.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132457 the-sz.PortScan version 1.97
  manifests/t/the-sz/PortScan/1.97/the-sz.PortScan.installer.yaml
  manifests/t/the-sz/PortScan/1.97/the-sz.PortScan.locale.en-US.yaml
  manifests/t/the-sz/PortScan/1.97/the-sz.PortScan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132453 Update: Neovim.Neovim.Nightly version 0.10.0
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.installer.yaml
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.locale.en-US.yaml
  manifests/n/Neovim/Neovim/Nightly/0.10.0/Neovim.Neovim.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132456 Update: KellyElton.Max.Backup version 0.1.3
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.installer.yaml
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.locale.en-US.yaml
  manifests/k/KellyElton/Max/Backup/0.1.3/KellyElton.Max.Backup.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132450 Remove: NHNCorporation.Dooray!Drive version 1.0.1.23
  manifests/n/NHNCorporation/Dooray!Drive/1.0.1.23/NHNCorporation.Dooray!Drive.installer.yaml
  manifests/n/NHNCorporation/Dooray!Drive/1.0.1.23/NHNCorporation.Dooray!Drive.locale.en-US.yaml
  manifests/n/NHNCorporation/Dooray!Drive/1.0.1.23/NHNCorporation.Dooray!Drive.locale.ko-KR.yaml
  manifests/n/NHNCorporation/Dooray!Drive/1.0.1.23/NHNCorporation.Dooray!Drive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132434 SmartSoft.SmartFTP version 10.0.3193.0
  manifests/s/SmartSoft/SmartFTP/10.0.3193.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3193.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3193.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132449 Add x64 version of Dooray
  manifests/n/NHNCorporation/Dooray!Drive/1.0.1.24/NHNCorporation.Dooray!Drive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132431 Fix DisplayVersion for JetBrains.DataGrip 2023.3.2
  manifests/j/JetBrains/DataGrip/2023.3.2/JetBrains.DataGrip.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132462 Add version: Minio.Server version 2024.01.01
  manifests/m/Minio/Server/2024.01.01/Minio.Server.installer.yaml
  manifests/m/Minio/Server/2024.01.01/Minio.Server.locale.en-US.yaml
  manifests/m/Minio/Server/2024.01.01/Minio.Server.yaml
  manifests/m/Minio/Server/latest/Minio.Server.installer.yaml
  manifests/m/Minio/Server/latest/Minio.Server.locale.en-US.yaml
  manifests/m/Minio/Server/latest/Minio.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback

#132339 New version: Ryochan7.DS4Windows version 3.3.3
  manifests/r/Ryochan7/DS4Windows/3.3.3/Ryochan7.DS4Windows.installer.yaml
  manifests/r/Ryochan7/DS4Windows/3.3.3/Ryochan7.DS4Windows.locale.en-US.yaml
  manifests/r/Ryochan7/DS4Windows/3.3.3/Ryochan7.DS4Windows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132338 New version: ManuelLaggner.tinyMediaManager version v5
  manifests/m/ManuelLaggner/tinyMediaManager/v5/ManuelLaggner.tinyMediaManager.installer.yaml
  manifests/m/ManuelLaggner/tinyMediaManager/v5/ManuelLaggner.tinyMediaManager.locale.en-US.yaml
  manifests/m/ManuelLaggner/tinyMediaManager/v5/ManuelLaggner.tinyMediaManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132333 New version: Microsoft.RemoteDesktopClient version 1.2.4763.0
  manifests/m/Microsoft/RemoteDesktopClient/1.2.4763.0/Microsoft.RemoteDesktopClient.installer.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.4763.0/Microsoft.RemoteDesktopClient.locale.en-US.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.4763.0/Microsoft.RemoteDesktopClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132325 New version: CI010.XMinecraftLauncher version 0.39.4.693
  manifests/c/CI010/XMinecraftLauncher/0.39.4.693/CI010.XMinecraftLauncher.installer.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.4.693/CI010.XMinecraftLauncher.locale.zh-CN.yaml
  manifests/c/CI010/XMinecraftLauncher/0.39.4.693/CI010.XMinecraftLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132319 New version: Dio.PureCodec version 20231231
  manifests/d/Dio/PureCodec/20231231/Dio.PureCodec.installer.yaml
  manifests/d/Dio/PureCodec/20231231/Dio.PureCodec.locale.en-US.yaml
  manifests/d/Dio/PureCodec/20231231/Dio.PureCodec.locale.zh-CN.yaml
  manifests/d/Dio/PureCodec/20231231/Dio.PureCodec.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132330 New version: Brave.Brave.Nightly version 120.1.63.84
  manifests/b/Brave/Brave/Nightly/120.1.63.84/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.84/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.84/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/120.1.63.84/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132316 CloudNet 1.36.2.17
  manifests/c/cloudnet/cloudnet/1.36.2.17/cloudnet.cloudnet.installer.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.17/cloudnet.cloudnet.locale.zh-CN.yaml
  manifests/c/cloudnet/cloudnet/1.36.2.17/cloudnet.cloudnet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132315 KurtZimmermann.RegCool version 1.353
  manifests/k/KurtZimmermann/RegCool/1.353/KurtZimmermann.RegCool.installer.yaml
  manifests/k/KurtZimmermann/RegCool/1.353/KurtZimmermann.RegCool.locale.en-us.yaml
  manifests/k/KurtZimmermann/RegCool/1.353/KurtZimmermann.RegCool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132313 New version: junegunn.fzf version 0.45.0
  manifests/j/junegunn/fzf/0.45.0/junegunn.fzf.installer.yaml
  manifests/j/junegunn/fzf/0.45.0/junegunn.fzf.locale.en-US.yaml
  manifests/j/junegunn/fzf/0.45.0/junegunn.fzf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132436 New package: Robware.RVTools version 4.5.1
  manifests/r/Robware/RVTools/4.5.1/Robware.RVTools.installer.yaml
  manifests/r/Robware/RVTools/4.5.1/Robware.RVTools.locale.en-US.yaml
  manifests/r/Robware/RVTools/4.5.1/Robware.RVTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132066 remove-old-package WHONET.AMRInterpretationEngine
  manifests/w/WHONET/AMRInterpretationEngine/23.12.21/WHONET.AMRInterpretationEngine.installer.yaml
  manifests/w/WHONET/AMRInterpretationEngine/23.12.21/WHONET.AMRInterpretationEngine.locale.en-US.yaml
  manifests/w/WHONET/AMRInterpretationEngine/23.12.21/WHONET.AMRInterpretationEngine.yaml
Labels: Validation-Completed, Internal-Error-Manifest, Needs-Attention

#132318 New package: Wiimm.ISO version 3.05a
  manifests/w/Wiimm/ISO/3.05a/Wiimm.ISO.installer.yaml
  manifests/w/Wiimm/ISO/3.05a/Wiimm.ISO.locale.en-US.yaml
  manifests/w/Wiimm/ISO/3.05a/Wiimm.ISO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#131721 Remove: Google.Chrome version 120.0.6099.110
  manifests/g/Google/Chrome/120.0.6099.110/Google.Chrome.installer.yaml
  manifests/g/Google/Chrome/120.0.6099.110/Google.Chrome.locale.en-US.yaml
  manifests/g/Google/Chrome/120.0.6099.110/Google.Chrome.locale.nb-NO.yaml
  manifests/g/Google/Chrome/120.0.6099.110/Google.Chrome.locale.zh-CN.yaml
  manifests/g/Google/Chrome/120.0.6099.110/Google.Chrome.yaml
Labels: Validation-Completed

#132189 Remove version: Proton.ProtonDrive version 1.4.4
  manifests/p/Proton/ProtonDrive/1.4.4/Proton.ProtonDrive.installer.yaml
  manifests/p/Proton/ProtonDrive/1.4.4/Proton.ProtonDrive.locale.en-US.yaml
  manifests/p/Proton/ProtonDrive/1.4.4/Proton.ProtonDrive.yaml
Labels: Validation-Completed

#132417 New version: Vendicated.Vencord.Canary version 1.3.1
  manifests/v/Vendicated/Vencord/Canary/1.3.1/Vendicated.Vencord.Canary.installer.yaml
  manifests/v/Vendicated/Vencord/Canary/1.3.1/Vendicated.Vencord.Canary.locale.en-US.yaml
  manifests/v/Vendicated/Vencord/Canary/1.3.1/Vendicated.Vencord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132418 New version: Vendicated.Vencord.PTB version 1.3.1
  manifests/v/Vendicated/Vencord/PTB/1.3.1/Vendicated.Vencord.PTB.installer.yaml
  manifests/v/Vendicated/Vencord/PTB/1.3.1/Vendicated.Vencord.PTB.locale.en-US.yaml
  manifests/v/Vendicated/Vencord/PTB/1.3.1/Vendicated.Vencord.PTB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#129009 New package: BRL-CAD.brlcad version 7.36.0
  manifests/b/BRL-CAD/brlcad/7.36.0/BRL-CAD.brlcad.installer.yaml
  manifests/b/BRL-CAD/brlcad/7.36.0/BRL-CAD.brlcad.locale.en-US.yaml
  manifests/b/BRL-CAD/brlcad/7.36.0/BRL-CAD.brlcad.yaml
Labels: Validation-Completed

#131252 Remove D:\Git\winget-pkgs\manifests\b\Bitvise\SSH\Client\9.31
  manifests/b/Bitvise/SSH/Client/9.31/Bitvise.SSH.Client.installer.yaml
  manifests/b/Bitvise/SSH/Client/9.31/Bitvise.SSH.Client.locale.en-US.yaml
  manifests/b/Bitvise/SSH/Client/9.31/Bitvise.SSH.Client.yaml
Labels: Validation-Completed, Moderator-Approved

#132397 New package: Envoy49.go-spotify-cli version 1.0.41, X64
  manifests/e/Envoy49/go-spotify-cli/1.0.41/Envoy49.go-spotify-cli.installer.yaml
  manifests/e/Envoy49/go-spotify-cli/1.0.41/Envoy49.go-spotify-cli.locale.en-US.yaml
  manifests/e/Envoy49/go-spotify-cli/1.0.41/Envoy49.go-spotify-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132523 Update manifest: Python.Python.3.13 version 3.13.0a2
  manifests/p/Python/Python/3/13/3.13.0a2/Python.Python.3.13.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132527 Microsoft.VisualStudioCode.Insiders_v1.86.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.86.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132522 ReleaseNotes: B3log.SiYuan version 2.12.0
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.locale.en-US.yaml
  manifests/b/B3log/SiYuan/2.12.0/B3log.SiYuan.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132525 ReleaseNotes: B3log.SiYuan version 2.11.4
  manifests/b/B3log/SiYuan/2.11.4/B3log.SiYuan.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132504 Update version: Frontesque.scrcpy+ version 2.0.2
  manifests/f/Frontesque/scrcpy+/2.0.2/Frontesque.scrcpy+.installer.yaml
  manifests/f/Frontesque/scrcpy+/2.0.2/Frontesque.scrcpy+.locale.en-US.yaml
  manifests/f/Frontesque/scrcpy+/2.0.2/Frontesque.scrcpy+.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132499 Remove vesion Taozuhong.Kangaroo 2.3.1.230201
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.3.1.230201/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132498 Remove vesion Taozuhong.Kangaroo 2.1.1.221201
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.1.1.221201/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132494 Remove vesion Taozuhong.Kangaroo 3.91.1.230801
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.91.1.230801/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132497 Remove vesion Taozuhong.Kangaroo 2.0.0.221101
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/2.0.0.221101/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132546 Fix: Wondershare.Filmora version 13.0.60.5095
  manifests/w/Wondershare/Filmora/13.0.60.5095/Wondershare.Filmora.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132495 Remove vesion Taozuhong.Kangaroo 3.92.1.230901
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.92.1.230901/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132493 Remove vesion Taozuhong.Kangaroo 3.90.120701
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/3.90.1.230701/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132491 Update version: ACEStudio.ACEStudio version 1.8.3
  manifests/a/ACEStudio/ACEStudio/1.8.3/ACEStudio.ACEStudio.installer.yaml
  manifests/a/ACEStudio/ACEStudio/1.8.3/ACEStudio.ACEStudio.locale.en-US.yaml
  manifests/a/ACEStudio/ACEStudio/1.8.3/ACEStudio.ACEStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132490 New version: vim.vim.nightly version 9.1.0
  manifests/v/vim/vim/nightly/9.1.0/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132481 New version: AdGuard.AdGuardHome version 0.107.43
  manifests/a/AdGuard/AdGuardHome/0.107.43/AdGuard.AdGuardHome.installer.yaml
  manifests/a/AdGuard/AdGuardHome/0.107.43/AdGuard.AdGuardHome.locale.en-US.yaml
  manifests/a/AdGuard/AdGuardHome/0.107.43/AdGuard.AdGuardHome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132479 New version: NextDNS.NextDNS.CLI version 1.41.0
  manifests/n/NextDNS/NextDNS/CLI/1.41.0/NextDNS.NextDNS.CLI.installer.yaml
  manifests/n/NextDNS/NextDNS/CLI/1.41.0/NextDNS.NextDNS.CLI.locale.en-US.yaml
  manifests/n/NextDNS/NextDNS/CLI/1.41.0/NextDNS.NextDNS.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132478 Update version: Tribler.Tribler version 7.13.1
  manifests/t/Tribler/Tribler/7.13.1/Tribler.Tribler.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132477 New version: PurpleI2P.i2pd version 2.50.1
  manifests/p/PurpleI2P/i2pd/2.50.1/PurpleI2P.i2pd.installer.yaml
  manifests/p/PurpleI2P/i2pd/2.50.1/PurpleI2P.i2pd.locale.en-US.yaml
  manifests/p/PurpleI2P/i2pd/2.50.1/PurpleI2P.i2pd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132476 SmartSoft.SmartFTP version 10.0.3194.0
  manifests/s/SmartSoft/SmartFTP/10.0.3194.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3194.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3194.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132460 New version: Fly-io.flyctl version 0.1.136
  manifests/f/Fly-io/flyctl/0.1.136/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.1.136/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.1.136/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132439 New version: MoritzBunkus.MKVToolNix version 82.0
  manifests/m/MoritzBunkus/MKVToolNix/82.0.0/MoritzBunkus.MKVToolNix.installer.yaml
  manifests/m/MoritzBunkus/MKVToolNix/82.0.0/MoritzBunkus.MKVToolNix.locale.en-US.yaml
  manifests/m/MoritzBunkus/MKVToolNix/82.0.0/MoritzBunkus.MKVToolNix.locale.zh-CN.yaml
  manifests/m/MoritzBunkus/MKVToolNix/82.0.0/MoritzBunkus.MKVToolNix.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#131674 Fix ARP detection: FNMT.ConfiguradorFNMT version 4.0.4
  manifests/f/FNMT/ConfiguradorFNMT/4.0.4/FNMT.ConfiguradorFNMT.installer.yaml
  manifests/f/FNMT/ConfiguradorFNMT/4.0.4/FNMT.ConfiguradorFNMT.locale.es-ES.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Unattended-Failed

#131549 New version: Baidu.BaiduPinyin version 6.0.5.113
  manifests/b/Baidu/BaiduPinyin/6.0.5.113/Baidu.BaiduPinyin.installer.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.5.113/Baidu.BaiduPinyin.locale.en-US.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.5.113/Baidu.BaiduPinyin.locale.zh-CN.yaml
  manifests/b/Baidu/BaiduPinyin/6.0.5.113/Baidu.BaiduPinyin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132507 New version: electerm.electerm version 1.37.110
  manifests/e/electerm/electerm/1.37.110/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.37.110/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.37.110/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132508 New version: 7S2P.Effie version 3.1.1
  manifests/7/7S2P/Effie/3.1.1/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/3.1.1/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/3.1.1/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/3.1.1/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132509 New version: 7S2P.Effie.CN version 3.1.1
  manifests/7/7S2P/Effie/CN/3.1.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.1.1/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.1.1/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.1.1/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#132510 New version: ByteDance.StreamingTool version 6.8.4
  manifests/b/ByteDance/StreamingTool/6.8.4/ByteDance.StreamingTool.installer.yaml
  manifests/b/ByteDance/StreamingTool/6.8.4/ByteDance.StreamingTool.locale.en-US.yaml
  manifests/b/ByteDance/StreamingTool/6.8.4/ByteDance.StreamingTool.locale.zh-CN.yaml
  manifests/b/ByteDance/StreamingTool/6.8.4/ByteDance.StreamingTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132511 New version: Bilibili.Livehime version 4.58.1.6234
  manifests/b/Bilibili/Livehime/4.58.1.6234/Bilibili.Livehime.installer.yaml
  manifests/b/Bilibili/Livehime/4.58.1.6234/Bilibili.Livehime.locale.en-US.yaml
  manifests/b/Bilibili/Livehime/4.58.1.6234/Bilibili.Livehime.locale.zh-CN.yaml
  manifests/b/Bilibili/Livehime/4.58.1.6234/Bilibili.Livehime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132513 New version: Sohu.SHPlayer version 7.1.6.0
  manifests/s/Sohu/SHPlayer/7.1.6.0/Sohu.SHPlayer.installer.yaml
  manifests/s/Sohu/SHPlayer/7.1.6.0/Sohu.SHPlayer.locale.en-US.yaml
  manifests/s/Sohu/SHPlayer/7.1.6.0/Sohu.SHPlayer.locale.zh-CN.yaml
  manifests/s/Sohu/SHPlayer/7.1.6.0/Sohu.SHPlayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132512 New version: Nutstore.Nutstore version 7.1.2
  manifests/n/Nutstore/Nutstore/7.1.2/Nutstore.Nutstore.installer.yaml
  manifests/n/Nutstore/Nutstore/7.1.2/Nutstore.Nutstore.locale.en-US.yaml
  manifests/n/Nutstore/Nutstore/7.1.2/Nutstore.Nutstore.locale.zh-CN.yaml
  manifests/n/Nutstore/Nutstore/7.1.2/Nutstore.Nutstore.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#132514 New version: Tencent.WeixinDevTools version 1.06.2401020
  manifests/t/Tencent/WeixinDevTools/1.06.2401020/Tencent.WeixinDevTools.installer.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2401020/Tencent.WeixinDevTools.locale.en-US.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2401020/Tencent.WeixinDevTools.locale.zh-CN.yaml
  manifests/t/Tencent/WeixinDevTools/1.06.2401020/Tencent.WeixinDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
