Repository microsoft/winget-pkgs, pull requests merged in 2024-03, with the labels that each got.

#141318 New package: Microsoft.MediaCreationTool version 10.0.22621.2714
  manifests/m/Microsoft/MediaCreationTool/10.0.22621.2714/Microsoft.MediaCreationTool.installer.yaml
  manifests/m/Microsoft/MediaCreationTool/10.0.22621.2714/Microsoft.MediaCreationTool.locale.en-US.yaml
  manifests/m/Microsoft/MediaCreationTool/10.0.22621.2714/Microsoft.MediaCreationTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#141497 Remove: htrb.ngraph-gtk version 6.09.07
  manifests/h/htrb/ngraph-gtk/6.09.07/htrb.ngraph-gtk.installer.yaml
  manifests/h/htrb/ngraph-gtk/6.09.07/htrb.ngraph-gtk.locale.en-US.yaml
  manifests/h/htrb/ngraph-gtk/6.09.07/htrb.ngraph-gtk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141504 New Version: Astronomer.Astro version 1.24.1
  manifests/a/Astronomer/Astro/1.24.1/Astronomer.Astro.installer.yaml
  manifests/a/Astronomer/Astro/1.24.1/Astronomer.Astro.locale.en-US.yaml
  manifests/a/Astronomer/Astro/1.24.1/Astronomer.Astro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141507 New version: Ubisoft Connect 150.1.11037 Installer
  manifests/u/Ubisoft/Connect/150.1.0.11037/Ubisoft.Connect.installer.yaml
  manifests/u/Ubisoft/Connect/150.1.0.11037/Ubisoft.Connect.locale.en-US.yaml
  manifests/u/Ubisoft/Connect/150.1.0.11037/Ubisoft.Connect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141508 New version: abbodi1406.vcredist version 0.78.0
  manifests/a/abbodi1406/vcredist/0.78.0/abbodi1406.vcredist.installer.yaml
  manifests/a/abbodi1406/vcredist/0.78.0/abbodi1406.vcredist.locale.en-US.yaml
  manifests/a/abbodi1406/vcredist/0.78.0/abbodi1406.vcredist.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141511 New version: taers232c.GAMADV-XTD3 version 6.71.05
  manifests/t/taers232c/GAMADV-XTD3/6.71.05/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.05/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.05/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141512 New version: Upscayl.Upscayl version 2.10.0
  manifests/u/Upscayl/Upscayl/2.10.0/Upscayl.Upscayl.installer.yaml
  manifests/u/Upscayl/Upscayl/2.10.0/Upscayl.Upscayl.locale.en-US.yaml
  manifests/u/Upscayl/Upscayl/2.10.0/Upscayl.Upscayl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141522 Aserto.Topaz.v0.31.4
  manifests/a/Aserto/Topaz/0.31.4/Aserto.Topaz.installer.yaml
  manifests/a/Aserto/Topaz/0.31.4/Aserto.Topaz.locale.en-US.yaml
  manifests/a/Aserto/Topaz/0.31.4/Aserto.Topaz.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Manifest

#141525 New version: Google.Chrome.Canary version 124.0.6330.0
  manifests/g/Google/Chrome/Canary/124.0.6330.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/124.0.6330.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/124.0.6330.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/124.0.6330.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/124.0.6330.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141526 New version: JetBrains.GoLand.EAP version 241.14024.16
  manifests/j/JetBrains/GoLand/EAP/241.14024.16/JetBrains.GoLand.EAP.installer.yaml
  manifests/j/JetBrains/GoLand/EAP/241.14024.16/JetBrains.GoLand.EAP.locale.en-US.yaml
  manifests/j/JetBrains/GoLand/EAP/241.14024.16/JetBrains.GoLand.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/GoLand/EAP/241.14024.16/JetBrains.GoLand.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141459 New version: Perimeter81Ltd.Perimeter81Ltd version 10.4.3.1672
  manifests/p/Perimeter81Ltd/Perimeter81Ltd/10.4.3.1672/Perimeter81Ltd.Perimeter81Ltd.installer.yaml
  manifests/p/Perimeter81Ltd/Perimeter81Ltd/10.4.3.1672/Perimeter81Ltd.Perimeter81Ltd.locale.en-US.yaml
  manifests/p/Perimeter81Ltd/Perimeter81Ltd/10.4.3.1672/Perimeter81Ltd.Perimeter81Ltd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#141461 New Version: GodotEngine.GodotEngine version 2.1.3
  manifests/g/GodotEngine/GodotEngine/2.1.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.3/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.3/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141469 New Version: GodotEngine.GodotEngine version 2.1.5
  manifests/g/GodotEngine/GodotEngine/2.1.5/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.5/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.5/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141471 New Version: GodotEngine.GodotEngine version 3.1
  manifests/g/GodotEngine/GodotEngine/3.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/3.1/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Version-Parameter-Mismatch, New-Manifest

#141472 New version: YuzuEmu.Yuzu.Mainline version 1730
  manifests/y/YuzuEmu/Yuzu/Mainline/1730/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1730/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1730/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141473 New Version: GodotEngine.GodotEngine version 3.1.1
  manifests/g/GodotEngine/GodotEngine/3.1.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.1/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.1/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141475 New version: JetBrains.RubyMine.EAP version 241.14024.10
  manifests/j/JetBrains/RubyMine/EAP/241.14024.10/JetBrains.RubyMine.EAP.installer.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.14024.10/JetBrains.RubyMine.EAP.locale.en-US.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.14024.10/JetBrains.RubyMine.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/RubyMine/EAP/241.14024.10/JetBrains.RubyMine.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141476 New version: Readdle.Spark version 3.14.3 (3.14.3.67453)
  manifests/r/Readdle/Spark/3.14.3/Readdle.Spark.installer.yaml
  manifests/r/Readdle/Spark/3.14.3/Readdle.Spark.locale.en-US.yaml
  manifests/r/Readdle/Spark/3.14.3/Readdle.Spark.locale.zh-CN.yaml
  manifests/r/Readdle/Spark/3.14.3/Readdle.Spark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141478 New Version: GodotEngine.GodotEngine version 3.1.2
  manifests/g/GodotEngine/GodotEngine/3.1.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.2/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.2/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141477 New Version: GodotEngine.GodotEngine version 2.1.6
  manifests/g/GodotEngine/GodotEngine/2.1.6/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.6/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.6/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141486 Remove version: Tencent.WeType version 0.9.2.85
  manifests/t/Tencent/WeType/0.9.2.85/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.2.85/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.2.85/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141487 Remove version: Tencent.WeType version 0.9.2.82
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.installer.yaml
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.locale.zh-CN.yaml
  manifests/t/Tencent/WeType/0.9.2.82/Tencent.WeType.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141485 New version: isaaclevin.presencelight version 5.8.4
  manifests/i/isaaclevin/presencelight/5.8.4/isaaclevin.presencelight.installer.yaml
  manifests/i/isaaclevin/presencelight/5.8.4/isaaclevin.presencelight.locale.en-US.yaml
  manifests/i/isaaclevin/presencelight/5.8.4/isaaclevin.presencelight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141489 New version: 7S2P.Effie version 3.6.3
  manifests/7/7S2P/Effie/3.6.3/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/3.6.3/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/3.6.3/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/3.6.3/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141488 Update Stoplight.Studio 2.10.0's installer URL
  manifests/s/Stoplight/Studio/2.10.0/Stoplight.Studio.installer.yaml
  manifests/s/Stoplight/Studio/2.10.0/Stoplight.Studio.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141491 New version: Google.Chrome.Beta version 123.0.6312.22
  manifests/g/Google/Chrome/Beta/123.0.6312.22/Google.Chrome.Beta.installer.yaml
  manifests/g/Google/Chrome/Beta/123.0.6312.22/Google.Chrome.Beta.locale.en-US.yaml
  manifests/g/Google/Chrome/Beta/123.0.6312.22/Google.Chrome.Beta.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Beta/123.0.6312.22/Google.Chrome.Beta.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Beta/123.0.6312.22/Google.Chrome.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141490 New version: 7S2P.Effie.CN version 3.6.3
  manifests/7/7S2P/Effie/CN/3.6.3/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.6.3/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.6.3/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.6.3/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141492 New version: JetBrains.DataGrip.EAP version 241.14024.11
  manifests/j/JetBrains/DataGrip/EAP/241.14024.11/JetBrains.DataGrip.EAP.installer.yaml
  manifests/j/JetBrains/DataGrip/EAP/241.14024.11/JetBrains.DataGrip.EAP.locale.en-US.yaml
  manifests/j/JetBrains/DataGrip/EAP/241.14024.11/JetBrains.DataGrip.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/DataGrip/EAP/241.14024.11/JetBrains.DataGrip.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141496 New version: GIGABYTE.GigabyteControlCenter version 24.02.07.01
  manifests/g/GIGABYTE/GigabyteControlCenter/24.02.07.01/GIGABYTE.GigabyteControlCenter.installer.yaml
  manifests/g/GIGABYTE/GigabyteControlCenter/24.02.07.01/GIGABYTE.GigabyteControlCenter.locale.en-US.yaml
  manifests/g/GIGABYTE/GigabyteControlCenter/24.02.07.01/GIGABYTE.GigabyteControlCenter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141580 ReleaseNotes: PIKCLOUD.PikPak version 2.2.9
  manifests/p/PIKCLOUD/PikPak/2.2.9/PIKCLOUD.PikPak.locale.en-US.yaml
  manifests/p/PIKCLOUD/PikPak/2.2.9/PIKCLOUD.PikPak.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141579 ReleaseNotes: 5E.5EClient version 7.1.38
  manifests/5/5E/5EClient/7.1.38/5E.5EClient.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141562 New version: iFlytek.iFlyIME version 3.0.1736
  manifests/i/iFlytek/iFlyIME/3.0.1736/iFlytek.iFlyIME.installer.yaml
  manifests/i/iFlytek/iFlyIME/3.0.1736/iFlytek.iFlyIME.locale.en-US.yaml
  manifests/i/iFlytek/iFlyIME/3.0.1736/iFlytek.iFlyIME.locale.zh-CN.yaml
  manifests/i/iFlytek/iFlyIME/3.0.1736/iFlytek.iFlyIME.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141563 New version: Taozuhong.Kangaroo v4.98.1
  manifests/t/Taozuhong/Kangaroo/4.98.1.240301/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/4.98.1.240301/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/4.98.1.240301/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/4.98.1.240301/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141597 New version: HiroSystems.Clarinet version 2.3.0
  manifests/h/HiroSystems/Clarinet/2.3.0/HiroSystems.Clarinet.installer.yaml
  manifests/h/HiroSystems/Clarinet/2.3.0/HiroSystems.Clarinet.locale.en-US.yaml
  manifests/h/HiroSystems/Clarinet/2.3.0/HiroSystems.Clarinet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141594 New version: PortSwigger.BurpSuite.Community version 2024.1.1.4
  manifests/p/PortSwigger/BurpSuite/Community/2024.1.1.4/PortSwigger.BurpSuite.Community.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2024.1.1.4/PortSwigger.BurpSuite.Community.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2024.1.1.4/PortSwigger.BurpSuite.Community.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Community/2024.1.1.4/PortSwigger.BurpSuite.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141593 New version: PortSwigger.BurpSuite.Professional version 2024.1.1.4
  manifests/p/PortSwigger/BurpSuite/Professional/2024.1.1.4/PortSwigger.BurpSuite.Professional.installer.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2024.1.1.4/PortSwigger.BurpSuite.Professional.locale.en-US.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2024.1.1.4/PortSwigger.BurpSuite.Professional.locale.zh-CN.yaml
  manifests/p/PortSwigger/BurpSuite/Professional/2024.1.1.4/PortSwigger.BurpSuite.Professional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141592 New version: JetBrains.WebStorm.EAP version 241.14024.30
  manifests/j/JetBrains/WebStorm/EAP/241.14024.30/JetBrains.WebStorm.EAP.installer.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.14024.30/JetBrains.WebStorm.EAP.locale.en-US.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.14024.30/JetBrains.WebStorm.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/WebStorm/EAP/241.14024.30/JetBrains.WebStorm.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141591 New version: JetBrains.PyCharm.Professional.EAP version 241.14024.28
  manifests/j/JetBrains/PyCharm/Professional/EAP/241.14024.28/JetBrains.PyCharm.Professional.EAP.installer.yaml
  manifests/j/JetBrains/PyCharm/Professional/EAP/241.14024.28/JetBrains.PyCharm.Professional.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Professional/EAP/241.14024.28/JetBrains.PyCharm.Professional.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/PyCharm/Professional/EAP/241.14024.28/JetBrains.PyCharm.Professional.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141590 New version: JetBrains.PyCharm.Community.EAP version 241.14024.28
  manifests/j/JetBrains/PyCharm/Community/EAP/241.14024.28/JetBrains.PyCharm.Community.EAP.installer.yaml
  manifests/j/JetBrains/PyCharm/Community/EAP/241.14024.28/JetBrains.PyCharm.Community.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PyCharm/Community/EAP/241.14024.28/JetBrains.PyCharm.Community.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/PyCharm/Community/EAP/241.14024.28/JetBrains.PyCharm.Community.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141588 New version: ButterflyEffect.Monica version 2.0.0
  manifests/b/ButterflyEffect/Monica/2.0.0/ButterflyEffect.Monica.installer.yaml
  manifests/b/ButterflyEffect/Monica/2.0.0/ButterflyEffect.Monica.locale.en-US.yaml
  manifests/b/ButterflyEffect/Monica/2.0.0/ButterflyEffect.Monica.locale.zh-CN.yaml
  manifests/b/ButterflyEffect/Monica/2.0.0/ButterflyEffect.Monica.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141586 New version: Treexy.OmnifyHotspot version 5.1.0.0
  manifests/t/Treexy/OmnifyHotspot/5.1.0.0/Treexy.OmnifyHotspot.installer.yaml
  manifests/t/Treexy/OmnifyHotspot/5.1.0.0/Treexy.OmnifyHotspot.locale.en-US.yaml
  manifests/t/Treexy/OmnifyHotspot/5.1.0.0/Treexy.OmnifyHotspot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141583 Add MongoDB.Compass.Isolated 1.42.2.0
  manifests/m/MongoDB/Compass/Isolated/1.42.2.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.42.2.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.42.2.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141578 New version: Google.Chrome.Canary version 124.0.6331.0
  manifests/g/Google/Chrome/Canary/124.0.6331.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/124.0.6331.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/124.0.6331.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/124.0.6331.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/124.0.6331.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141577 New version: 7S2P.Effie.CN version 3.7.1
  manifests/7/7S2P/Effie/CN/3.7.1/7S2P.Effie.CN.installer.yaml
  manifests/7/7S2P/Effie/CN/3.7.1/7S2P.Effie.CN.locale.en-US.yaml
  manifests/7/7S2P/Effie/CN/3.7.1/7S2P.Effie.CN.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/CN/3.7.1/7S2P.Effie.CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141576 New version: 7S2P.Effie version 3.7.1
  manifests/7/7S2P/Effie/3.7.1/7S2P.Effie.installer.yaml
  manifests/7/7S2P/Effie/3.7.1/7S2P.Effie.locale.en-US.yaml
  manifests/7/7S2P/Effie/3.7.1/7S2P.Effie.locale.zh-CN.yaml
  manifests/7/7S2P/Effie/3.7.1/7S2P.Effie.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141575 Update version: GIMP.GIMP version 2.10.36
  manifests/g/GIMP/GIMP/2.10.36/GIMP.GIMP.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141572 Remeha.service tool 7.3.31.0 9dee46a4 4f8c 4f9d b1d5 5501aa7d1e25
  manifests/r/Remeha/ServiceTool/7.3.20.0/Remeha.ServiceTool.installer.yaml
  manifests/r/Remeha/ServiceTool/7.3.20.0/Remeha.ServiceTool.locale.en-US.yaml
  manifests/r/Remeha/ServiceTool/7.3.20.0/Remeha.ServiceTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141571 Fix version number of Lazarus 3.0
  manifests/l/Lazarus/Lazarus/3.0/Lazarus.Lazarus.installer.yaml
  manifests/l/Lazarus/Lazarus/3.0/Lazarus.Lazarus.locale.en-US.yaml
  manifests/l/Lazarus/Lazarus/3.0/Lazarus.Lazarus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141570 New version: Corsair.iCUE.5 version 5.12.97
  manifests/c/Corsair/iCUE/5/5.12.97/Corsair.iCUE.5.installer.yaml
  manifests/c/Corsair/iCUE/5/5.12.97/Corsair.iCUE.5.locale.en-US.yaml
  manifests/c/Corsair/iCUE/5/5.12.97/Corsair.iCUE.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141567 New version: taers232c.GAMADV-XTD3 version 6.71.07
  manifests/t/taers232c/GAMADV-XTD3/6.71.07/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.07/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.07/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141565 New version: Jackett.Jackett version 0.21.1897
  manifests/j/Jackett/Jackett/0.21.1897/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1897/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1897/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141568 New version: JohnMacFarlane.Pandoc version 3.1.12.2
  manifests/j/JohnMacFarlane/Pandoc/3.1.12.2/JohnMacFarlane.Pandoc.installer.yaml
  manifests/j/JohnMacFarlane/Pandoc/3.1.12.2/JohnMacFarlane.Pandoc.locale.en-US.yaml
  manifests/j/JohnMacFarlane/Pandoc/3.1.12.2/JohnMacFarlane.Pandoc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141569 New version: RProject.R version 4.3.3
  manifests/r/RProject/R/4.3.3/RProject.R.installer.yaml
  manifests/r/RProject/R/4.3.3/RProject.R.locale.en-US.yaml
  manifests/r/RProject/R/4.3.3/RProject.R.locale.zh-CN.yaml
  manifests/r/RProject/R/4.3.3/RProject.R.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141596 New package: LacunaSoftware.WebPKI version 2.12.3.0
  manifests/l/LacunaSoftware/WebPKI/2.12.3.0/LacunaSoftware.WebPKI.installer.yaml
  manifests/l/LacunaSoftware/WebPKI/2.12.3.0/LacunaSoftware.WebPKI.locale.en-US.yaml
  manifests/l/LacunaSoftware/WebPKI/2.12.3.0/LacunaSoftware.WebPKI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141587 New version: 115.115 version 2.0.8.5
  manifests/1/115/115/2.0.8.5/115.115.installer.yaml
  manifests/1/115/115/2.0.8.5/115.115.locale.en-US.yaml
  manifests/1/115/115/2.0.8.5/115.115.locale.zh-CN.yaml
  manifests/1/115/115/2.0.8.5/115.115.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141400 Publish ACS CLI version 2.14.0
  manifests/s/Splunk/ACS/2.14.0/Splunk.ACS.installer.yaml
  manifests/s/Splunk/ACS/2.14.0/Splunk.ACS.locale.en-US.yaml
  manifests/s/Splunk/ACS/2.14.0/Splunk.ACS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141479 New version: Streamlink.Streamlink version 6.6.1-1
  manifests/s/Streamlink/Streamlink/6.6.1-1/Streamlink.Streamlink.installer.yaml
  manifests/s/Streamlink/Streamlink/6.6.1-1/Streamlink.Streamlink.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/6.6.1-1/Streamlink.Streamlink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141480 New version: Streamlink.Streamlink version 6.6.2-1
  manifests/s/Streamlink/Streamlink/6.6.2-1/Streamlink.Streamlink.installer.yaml
  manifests/s/Streamlink/Streamlink/6.6.2-1/Streamlink.Streamlink.locale.en-US.yaml
  manifests/s/Streamlink/Streamlink/6.6.2-1/Streamlink.Streamlink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141494 New version: Logseq.Logseq version 0.10.7
  manifests/l/Logseq/Logseq/0.10.7/Logseq.Logseq.installer.yaml
  manifests/l/Logseq/Logseq/0.10.7/Logseq.Logseq.locale.en-US.yaml
  manifests/l/Logseq/Logseq/0.10.7/Logseq.Logseq.locale.zh-CN.yaml
  manifests/l/Logseq/Logseq/0.10.7/Logseq.Logseq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141481 New version: OliverBetz.ExifTool version 12.77
  manifests/o/OliverBetz/ExifTool/12.77/OliverBetz.ExifTool.installer.yaml
  manifests/o/OliverBetz/ExifTool/12.77/OliverBetz.ExifTool.locale.en-US.yaml
  manifests/o/OliverBetz/ExifTool/12.77/OliverBetz.ExifTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141539 New version: Reqable.Reqable version 2.8.0
  manifests/r/Reqable/Reqable/2.8.0/Reqable.Reqable.installer.yaml
  manifests/r/Reqable/Reqable/2.8.0/Reqable.Reqable.locale.en-US.yaml
  manifests/r/Reqable/Reqable/2.8.0/Reqable.Reqable.locale.zh-CN.yaml
  manifests/r/Reqable/Reqable/2.8.0/Reqable.Reqable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141540 New version: VSCodium.VSCodium version 1.87.0.24060
  manifests/v/VSCodium/VSCodium/1.87.0.24060/VSCodium.VSCodium.installer.yaml
  manifests/v/VSCodium/VSCodium/1.87.0.24060/VSCodium.VSCodium.locale.en-US.yaml
  manifests/v/VSCodium/VSCodium/1.87.0.24060/VSCodium.VSCodium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141545 Microsoft.VisualStudioCode.Insiders_v1.88.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.88.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141551 New version: PerfectWorld.PerfectWorldArena version 1.0.24030111
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030111/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030111/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030111/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030111/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141553 New version: yt-dlp.yt-dlp.nightly version 2024.02.29.232658
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.29.232658/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.29.232658/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.29.232658/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141554 New version: taers232c.GAMADV-XTD3 version 6.71.06
  manifests/t/taers232c/GAMADV-XTD3/6.71.06/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.06/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.71.06/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141561 New version: Alibaba.aDrive version 4.13.0
  manifests/a/Alibaba/aDrive/4.13.0/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/4.13.0/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/4.13.0/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/4.13.0/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141606 New version: ButterflyEffect.Monica version 2.0.1
  manifests/b/ButterflyEffect/Monica/2.0.1/ButterflyEffect.Monica.installer.yaml
  manifests/b/ButterflyEffect/Monica/2.0.1/ButterflyEffect.Monica.locale.en-US.yaml
  manifests/b/ButterflyEffect/Monica/2.0.1/ButterflyEffect.Monica.locale.zh-CN.yaml
  manifests/b/ButterflyEffect/Monica/2.0.1/ButterflyEffect.Monica.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141607 New version: Tarma.PublishOrPerish version 8.11.4583.8827
  manifests/t/Tarma/PublishOrPerish/8.11.4583.8827/Tarma.PublishOrPerish.installer.yaml
  manifests/t/Tarma/PublishOrPerish/8.11.4583.8827/Tarma.PublishOrPerish.locale.en-US.yaml
  manifests/t/Tarma/PublishOrPerish/8.11.4583.8827/Tarma.PublishOrPerish.locale.zh-CN.yaml
  manifests/t/Tarma/PublishOrPerish/8.11.4583.8827/Tarma.PublishOrPerish.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141546 Microsoft.VisualStudioCode.Insiders.CLI_v1.88.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.88.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141086 Remove: SAPIEN.PowerShellStudio version 5.8.236.0
  manifests/s/SAPIEN/PowerShellStudio/5.8.236.0/SAPIEN.PowerShellStudio.installer.yaml
  manifests/s/SAPIEN/PowerShellStudio/5.8.236.0/SAPIEN.PowerShellStudio.locale.en-US.yaml
  manifests/s/SAPIEN/PowerShellStudio/5.8.236.0/SAPIEN.PowerShellStudio.locale.zh-CN.yaml
  manifests/s/SAPIEN/PowerShellStudio/5.8.236.0/SAPIEN.PowerShellStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Last-Version-Remaining

#141320 Update version: Aserto.DSLoad version 0.30.5
  manifests/a/Aserto/DSLoad/0.30.5/Aserto.DSLoad.installer.yaml
  manifests/a/Aserto/DSLoad/0.30.5/Aserto.DSLoad.locale.en-US.yaml
  manifests/a/Aserto/DSLoad/0.30.5/Aserto.DSLoad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141605 Remove version: Joplin.Joplin version 2.14.16
  manifests/j/Joplin/Joplin/2.14.16/Joplin.Joplin.installer.yaml
  manifests/j/Joplin/Joplin/2.14.16/Joplin.Joplin.locale.en-US.yaml
  manifests/j/Joplin/Joplin/2.14.16/Joplin.Joplin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141609 Microsoft.VisualStudioCode.Insiders_v1.88.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.88.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#140686 New version: vim.vim.nightly version 9.1.0128
  manifests/v/vim/vim/nightly/9.1.0128/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0128/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0128/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#140835 New version: nkdAgility.AzureDevOpsMigrationTools.Preview version 15.0.0-Preview.324
  manifests/n/nkdAgility/AzureDevOpsMigrationTools/Preview/15.0.0-Preview.324/nkdAgility.AzureDevOpsMigrationTools.Preview.installer.yaml
  manifests/n/nkdAgility/AzureDevOpsMigrationTools/Preview/15.0.0-Preview.324/nkdAgility.AzureDevOpsMigrationTools.Preview.locale.en-US.yaml
  manifests/n/nkdAgility/AzureDevOpsMigrationTools/Preview/15.0.0-Preview.324/nkdAgility.AzureDevOpsMigrationTools.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#141634 Microsoft.VisualStudioCode.Insiders_v1.88.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.88.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141660 [Metadata]: Notion.Notion version 2.0.21
  manifests/n/Notion/Notion/2.0.21/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.21/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.21/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#141661 [Metadata]: Notion.Notion version 2.0.23
  manifests/n/Notion/Notion/2.0.23/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.23/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.23/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141662 [Metadata]: Notion.Notion version 2.0.28
  manifests/n/Notion/Notion/2.0.28/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.28/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.28/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback

#141663 [Metadata]: Notion.Notion version 2.0.32
  manifests/n/Notion/Notion/2.0.32/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.32/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.32/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141664 [Metadata]: Notion.Notion version 2.0.34
  manifests/n/Notion/Notion/2.0.34/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.34/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.34/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141665 [Metadata]: Notion.Notion version 2.0.39
  manifests/n/Notion/Notion/2.0.39/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.39/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.39/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141666 [Metadata]: Notion.Notion version 2.0.41
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.41/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141667 [Metadata]: Notion.Notion version 2.0.47
  manifests/n/Notion/Notion/2.0.47/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.47/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.47/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141668 [Metadata]: Notion.Notion version 2.0.8
  manifests/n/Notion/Notion/2.0.8/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.8/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.8/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141669 [Metadata]: Notion.Notion version 2.0.9
  manifests/n/Notion/Notion/2.0.9/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.9/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.9/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141670 [Metadata]: Notion.Notion version 3.2.1
  manifests/n/Notion/Notion/3.2.1/Notion.Notion.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141671 New version: Hugo.Hugo version 0.123.7
  manifests/h/Hugo/Hugo/0.123.7/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.123.7/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.123.7/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.123.7/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Manifest

#141683 New version: CCPGames.EVEOnline version 1.2.11
  manifests/c/CCPGames/EVEOnline/1.2.11/CCPGames.EVEOnline.installer.yaml
  manifests/c/CCPGames/EVEOnline/1.2.11/CCPGames.EVEOnline.locale.en-US.yaml
  manifests/c/CCPGames/EVEOnline/1.2.11/CCPGames.EVEOnline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141685 New version: CCPGames.EVEOnline version 1.2.9
  manifests/c/CCPGames/EVEOnline/1.2.9/CCPGames.EVEOnline.installer.yaml
  manifests/c/CCPGames/EVEOnline/1.2.9/CCPGames.EVEOnline.locale.en-US.yaml
  manifests/c/CCPGames/EVEOnline/1.2.9/CCPGames.EVEOnline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141684 New version: CCPGames.EVEOnline version 1.2.10
  manifests/c/CCPGames/EVEOnline/1.2.10/CCPGames.EVEOnline.installer.yaml
  manifests/c/CCPGames/EVEOnline/1.2.10/CCPGames.EVEOnline.locale.en-US.yaml
  manifests/c/CCPGames/EVEOnline/1.2.10/CCPGames.EVEOnline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141687 New version: Microsoft.EdgeDriver version 122.0.2365.66
  manifests/m/Microsoft/EdgeDriver/122.0.2365.66/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/122.0.2365.66/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/122.0.2365.66/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/122.0.2365.66/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141688 New version: PerfectWorld.PerfectWorldArena version 1.0.24030211
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030211/PerfectWorld.PerfectWorldArena.installer.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030211/PerfectWorld.PerfectWorldArena.locale.en-US.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030211/PerfectWorld.PerfectWorldArena.locale.zh-CN.yaml
  manifests/p/PerfectWorld/PerfectWorldArena/1.0.24030211/PerfectWorld.PerfectWorldArena.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141690 New version: Microsoft.Azure.StorageExplorer version 1.33.0
  manifests/m/Microsoft/Azure/StorageExplorer/1.33.0/Microsoft.Azure.StorageExplorer.installer.yaml
  manifests/m/Microsoft/Azure/StorageExplorer/1.33.0/Microsoft.Azure.StorageExplorer.locale.en-US.yaml
  manifests/m/Microsoft/Azure/StorageExplorer/1.33.0/Microsoft.Azure.StorageExplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Needs-Review, New-Manifest

#141694 New version: cURL.cURL version 8.6.0.3
  manifests/c/cURL/cURL/8.6.0.3/cURL.cURL.installer.yaml
  manifests/c/cURL/cURL/8.6.0.3/cURL.cURL.locale.en-US.yaml
  manifests/c/cURL/cURL/8.6.0.3/cURL.cURL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141616 New version: MasterPackager.MasterPackagerDev version 1.0.9
  manifests/m/MasterPackager/MasterPackagerDev/1.0.9/MasterPackager.MasterPackagerDev.installer.yaml
  manifests/m/MasterPackager/MasterPackagerDev/1.0.9/MasterPackager.MasterPackagerDev.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackagerDev/1.0.9/MasterPackager.MasterPackagerDev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141619 Update 'ChronoplexSoftware.MyFamilyTree' to '14.0.4.0'
  manifests/c/ChronoplexSoftware/MyFamilyTree/14.0.4.0/ChronoplexSoftware.MyFamilyTree.installer.yaml
  manifests/c/ChronoplexSoftware/MyFamilyTree/14.0.4.0/ChronoplexSoftware.MyFamilyTree.locale.en-US.yaml
  manifests/c/ChronoplexSoftware/MyFamilyTree/14.0.4.0/ChronoplexSoftware.MyFamilyTree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141621 New version: Joplin.Joplin version 2.14.17
  manifests/j/Joplin/Joplin/2.14.17/Joplin.Joplin.installer.yaml
  manifests/j/Joplin/Joplin/2.14.17/Joplin.Joplin.locale.en-US.yaml
  manifests/j/Joplin/Joplin/2.14.17/Joplin.Joplin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141624 New version: YuzuEmu.Yuzu.Mainline version 1731
  manifests/y/YuzuEmu/Yuzu/Mainline/1731/YuzuEmu.Yuzu.Mainline.installer.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1731/YuzuEmu.Yuzu.Mainline.locale.en-US.yaml
  manifests/y/YuzuEmu/Yuzu/Mainline/1731/YuzuEmu.Yuzu.Mainline.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141625 New version: Abdelrhman-AK.WinPaletter version 1.0.8.6
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.6/Abdelrhman-AK.WinPaletter.installer.yaml
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.6/Abdelrhman-AK.WinPaletter.locale.en-US.yaml
  manifests/a/Abdelrhman-AK/WinPaletter/1.0.8.6/Abdelrhman-AK.WinPaletter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141626 New version: Tauri.create-tauri-app version 3.13.9
  manifests/t/Tauri/create-tauri-app/3.13.9/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/3.13.9/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/3.13.9/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/3.13.9/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141659 [Metadata]: Notion.Notion version 2.0.18
  manifests/n/Notion/Notion/2.0.18/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.18/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.18/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141658 [Metadata]: Notion.Notion version 2.0.17
  manifests/n/Notion/Notion/2.0.17/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.17/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.17/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141675 ReleaseNotes: 115.115 version 2.0.8.5
  manifests/1/115/115/2.0.8.5/115.115.locale.en-US.yaml
  manifests/1/115/115/2.0.8.5/115.115.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141654 [Metadata]: Notion.Notion version 2.0.11
  manifests/n/Notion/Notion/2.0.11/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.11/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.11/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141657 [Metadata]: Notion.Notion version 2.0.16
  manifests/n/Notion/Notion/2.0.16/Notion.Notion.installer.yaml
  manifests/n/Notion/Notion/2.0.16/Notion.Notion.locale.en-US.yaml
  manifests/n/Notion/Notion/2.0.16/Notion.Notion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141644 New version: Google.Chrome.Canary version 124.0.6332.0
  manifests/g/Google/Chrome/Canary/124.0.6332.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/124.0.6332.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/124.0.6332.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/124.0.6332.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/124.0.6332.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#140926 New version: xavidop.cxcli 1.175.0
  manifests/x/xavidop/cxcli/1.175.0/xavidop.cxcli.installer.yaml
  manifests/x/xavidop/cxcli/1.175.0/xavidop.cxcli.locale.en-US.yaml
  manifests/x/xavidop/cxcli/1.175.0/xavidop.cxcli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#140958 New version: Tauri.create-tauri-app version 3.13.6
  manifests/t/Tauri/create-tauri-app/3.13.6/Tauri.create-tauri-app.installer.yaml
  manifests/t/Tauri/create-tauri-app/3.13.6/Tauri.create-tauri-app.locale.en-US.yaml
  manifests/t/Tauri/create-tauri-app/3.13.6/Tauri.create-tauri-app.locale.zh-CN.yaml
  manifests/t/Tauri/create-tauri-app/3.13.6/Tauri.create-tauri-app.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141115 New version: evilmartians.lefthook version 1.6.3
  manifests/e/evilmartians/lefthook/1.6.3/evilmartians.lefthook.installer.yaml
  manifests/e/evilmartians/lefthook/1.6.3/evilmartians.lefthook.locale.en-US.yaml
  manifests/e/evilmartians/lefthook/1.6.3/evilmartians.lefthook.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141141 New version: GiulioSorrentino.CBriscola.WPF version 0.6.7
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6.7/GiulioSorrentino.CBriscola.WPF.installer.yaml
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6.7/GiulioSorrentino.CBriscola.WPF.locale.en-US.yaml
  manifests/g/GiulioSorrentino/CBriscola/WPF/0.6.7/GiulioSorrentino.CBriscola.WPF.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141061 New version: vim.vim.nightly version 9.1.0139
  manifests/v/vim/vim/nightly/9.1.0139/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0139/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0139/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141343 GiulioSorrentino.CBriscola.Avalonia version 0.7.8
  manifests/g/GiulioSorrentino/CBriscola/Avalonia/0.7.8/GiulioSorrentino.CBriscola.Avalonia.installer.yaml
  manifests/g/GiulioSorrentino/CBriscola/Avalonia/0.7.8/GiulioSorrentino.CBriscola.Avalonia.locale.en-US.yaml
  manifests/g/GiulioSorrentino/CBriscola/Avalonia/0.7.8/GiulioSorrentino.CBriscola.Avalonia.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141367 New version: Fedora.CoreOS.butane version 0.20.0
  manifests/f/Fedora/CoreOS/butane/0.20.0/Fedora.CoreOS.butane.installer.yaml
  manifests/f/Fedora/CoreOS/butane/0.20.0/Fedora.CoreOS.butane.locale.en-US.yaml
  manifests/f/Fedora/CoreOS/butane/0.20.0/Fedora.CoreOS.butane.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141418 Add ARM64 installer for `AdGuard.dnsproxy`
  manifests/a/AdGuard/dnsproxy/0.65.2/AdGuard.dnsproxy.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error

#141410 New version: Jackett.Jackett version 0.21.1888
  manifests/j/Jackett/Jackett/0.21.1888/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1888/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1888/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141431 New version: igoogolx.itun2socks version 1.0.1
  manifests/i/igoogolx/itun2socks/1.0.1/igoogolx.itun2socks.installer.yaml
  manifests/i/igoogolx/itun2socks/1.0.1/igoogolx.itun2socks.locale.en-US.yaml
  manifests/i/igoogolx/itun2socks/1.0.1/igoogolx.itun2socks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141451 New Version: GodotEngine.GodotEngine version 2.0.1
  manifests/g/GodotEngine/GodotEngine/2.0.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.1/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.1/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error, New-Manifest

#141453 New Version: GodotEngine.GodotEngine version 2.0.2
  manifests/g/GodotEngine/GodotEngine/2.0.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.2/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.2/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error, New-Manifest

#141452 New version: prefix-dev.pixi version 0.15.2
  manifests/p/prefix-dev/pixi/0.15.2/prefix-dev.pixi.installer.yaml
  manifests/p/prefix-dev/pixi/0.15.2/prefix-dev.pixi.locale.en-US.yaml
  manifests/p/prefix-dev/pixi/0.15.2/prefix-dev.pixi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error, New-Manifest

#141455 New Version: GodotEngine.GodotEngine version 2.0.3
  manifests/g/GodotEngine/GodotEngine/2.0.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.3/GodotEngine.GodotEngine.locale.en-US.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.3/GodotEngine.GodotEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error, New-Manifest

#141493 New version: JetBrains.FleetLauncher.Preview version 1.31.99
  manifests/j/JetBrains/FleetLauncher/Preview/1.31.99/JetBrains.FleetLauncher.Preview.installer.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.31.99/JetBrains.FleetLauncher.Preview.locale.en-US.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.31.99/JetBrains.FleetLauncher.Preview.locale.zh-CN.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.31.99/JetBrains.FleetLauncher.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Validation-Executable-Error, New-Manifest

#141548 New version: vim.vim.nightly version 9.1.0145
  manifests/v/vim/vim/nightly/9.1.0145/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0145/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0145/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141599 New version: Baxi.ServiceTool version 7.3.31.0
  manifests/b/Baxi/ServiceTool/7.3.31.0/Baxi.ServiceTool.installer.yaml
  manifests/b/Baxi/ServiceTool/7.3.31.0/Baxi.ServiceTool.locale.en-US.yaml
  manifests/b/Baxi/ServiceTool/7.3.31.0/Baxi.ServiceTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-1.2, Waived-Validation-Domain, New-Manifest

#141560 New version: nektos.act version 0.2.60
  manifests/n/nektos/act/0.2.60/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.60/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.60/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141610 New version: Lazarus.Lazarus version 3.2
  manifests/l/Lazarus/Lazarus/3.2/Lazarus.Lazarus.installer.yaml
  manifests/l/Lazarus/Lazarus/3.2/Lazarus.Lazarus.locale.en-US.yaml
  manifests/l/Lazarus/Lazarus/3.2/Lazarus.Lazarus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141611 Update 'Wargaming.GameCenter' to 24.00.00.5034
  manifests/w/Wargaming/GameCenter/24.0.0.5034/Wargaming.GameCenter.installer.yaml
  manifests/w/Wargaming/GameCenter/24.0.0.5034/Wargaming.GameCenter.locale.en-US.yaml
  manifests/w/Wargaming/GameCenter/24.0.0.5034/Wargaming.GameCenter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#141613 New version: CodecGuide.K-LiteCodecPack.Standard version 18.1.5
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.1.5/CodecGuide.K-LiteCodecPack.Standard.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.1.5/CodecGuide.K-LiteCodecPack.Standard.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Standard/18.1.5/CodecGuide.K-LiteCodecPack.Standard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141614 New version: CodecGuide.K-LiteCodecPack.Mega version 18.1.5
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.1.5/CodecGuide.K-LiteCodecPack.Mega.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.1.5/CodecGuide.K-LiteCodecPack.Mega.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Mega/18.1.5/CodecGuide.K-LiteCodecPack.Mega.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141615 New version: CodecGuide.K-LiteCodecPack.Basic version 18.1.5
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.1.5/CodecGuide.K-LiteCodecPack.Basic.installer.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.1.5/CodecGuide.K-LiteCodecPack.Basic.locale.en-US.yaml
  manifests/c/CodecGuide/K-LiteCodecPack/Basic/18.1.5/CodecGuide.K-LiteCodecPack.Basic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#140374 GiulioSorrentino.numeronesoeminformations version 1.1.1
  manifests/g/GiulioSorrentino/numeronesoeminformations/1.1.1/GiulioSorrentino.numeronesoeminformations.installer.yaml
  manifests/g/GiulioSorrentino/numeronesoeminformations/1.1.1/GiulioSorrentino.numeronesoeminformations.locale.en-US.yaml
  manifests/g/GiulioSorrentino/numeronesoeminformations/1.1.1/GiulioSorrentino.numeronesoeminformations.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#140470 New version: eza-community.eza version 0.18.4
  manifests/e/eza-community/eza/0.18.4/eza-community.eza.installer.yaml
  manifests/e/eza-community/eza/0.18.4/eza-community.eza.locale.en-US.yaml
  manifests/e/eza-community/eza/0.18.4/eza-community.eza.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#140829 New version: SagerNet.sing-box version 1.8.6
  manifests/s/SagerNet/sing-box/1.8.6/SagerNet.sing-box.installer.yaml
  manifests/s/SagerNet/sing-box/1.8.6/SagerNet.sing-box.locale.en-US.yaml
  manifests/s/SagerNet/sing-box/1.8.6/SagerNet.sing-box.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#140924 New version: taers232c.GAMADV-XTD3 version 6.70.06
  manifests/t/taers232c/GAMADV-XTD3/6.70.06/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.70.06/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.70.06/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141695 New version: dustinblackman.oatmeal 0.12.5
  manifests/d/dustinblackman/oatmeal/0.12.5/dustinblackman.oatmeal.installer.yaml
  manifests/d/dustinblackman/oatmeal/0.12.5/dustinblackman.oatmeal.locale.en-US.yaml
  manifests/d/dustinblackman/oatmeal/0.12.5/dustinblackman.oatmeal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141604 New package: BDRThermea.ServiceTool version 7.3.31.0
  manifests/b/BDRThermea/ServiceTool/7.3.31.0/BDRThermea.ServiceTool.installer.yaml
  manifests/b/BDRThermea/ServiceTool/7.3.31.0/BDRThermea.ServiceTool.locale.en-US.yaml
  manifests/b/BDRThermea/ServiceTool/7.3.31.0/BDRThermea.ServiceTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Policy-Test-1.2, Waived-Validation-Domain, New-Package

#141514 New Package: gnif.LookingGlass version B6
  manifests/g/gnif/LookingGlass/B6/gnif.LookingGlass.installer.yaml
  manifests/g/gnif/LookingGlass/B6/gnif.LookingGlass.locale.en-US.yaml
  manifests/g/gnif/LookingGlass/B6/gnif.LookingGlass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Waived-Validation-Executable-Error, New-Package

#141601 New package: Brotje.ServiceTool version 7.3.31.0
  manifests/b/Brotje/ServiceTool/7.3.31.0/Brotje.ServiceTool.installer.yaml
  manifests/b/Brotje/ServiceTool/7.3.31.0/Brotje.ServiceTool.locale.en-US.yaml
  manifests/b/Brotje/ServiceTool/7.3.31.0/Brotje.ServiceTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Waived-Policy-Test-1.2, Waived-Validation-Domain, New-Package

#141672 New version: Hugo.Hugo.Extended version 0.123.7
  manifests/h/Hugo/Hugo/Extended/0.123.7/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.123.7/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.123.7/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.123.7/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141710 New version: Jackett.Jackett version 0.21.1915
  manifests/j/Jackett/Jackett/0.21.1915/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1915/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1915/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141704 Update Netron to 7.5.1
  manifests/l/LutzRoeder/Netron/7.5.1/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.5.1/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.5.1/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#141837 Moved: Proton.ProtonMailBridge version 2.1.3
  manifests/p/Proton/ProtonMailBridge/2.1.3/Proton.ProtonMailBridge.installer.yaml
  manifests/p/Proton/ProtonMailBridge/2.1.3/Proton.ProtonMailBridge.locale.en-US.yaml
  manifests/p/Proton/ProtonMailBridge/2.1.3/Proton.ProtonMailBridge.locale.zh-CN.yaml
  manifests/p/Proton/ProtonMailBridge/2.1.3/Proton.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#141838 Moved: Proton.ProtonMailBridge version 2.3.0
  manifests/p/Proton/ProtonMailBridge/2.3.0/Proton.ProtonMailBridge.installer.yaml
  manifests/p/Proton/ProtonMailBridge/2.3.0/Proton.ProtonMailBridge.locale.en-US.yaml
  manifests/p/Proton/ProtonMailBridge/2.3.0/Proton.ProtonMailBridge.locale.zh-CN.yaml
  manifests/p/Proton/ProtonMailBridge/2.3.0/Proton.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#141839 Moved: Proton.ProtonMailBridge version 3.1.3
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.installer.yaml
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.locale.en-US.yaml
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.locale.zh-CN.yaml
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#141833 Moving: ProtonTechnologies.ProtonMailBridge version 2.1.3
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.1.3/ProtonTechnologies.ProtonMailBridge.installer.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.1.3/ProtonTechnologies.ProtonMailBridge.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.1.3/ProtonTechnologies.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141834 Moving: ProtonTechnologies.ProtonMailBridge version 2.3.0
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.3.0/ProtonTechnologies.ProtonMailBridge.installer.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.3.0/ProtonTechnologies.ProtonMailBridge.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/2.3.0/ProtonTechnologies.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141835 Moving: ProtonTechnologies.ProtonMailBridge version 3.1.3
  manifests/p/ProtonTechnologies/ProtonMailBridge/3.1.3/ProtonTechnologies.ProtonMailBridge.installer.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/3.1.3/ProtonTechnologies.ProtonMailBridge.locale.en-US.yaml
  manifests/p/ProtonTechnologies/ProtonMailBridge/3.1.3/ProtonTechnologies.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#141896 Fix: Proton.ProtonMailBridge version 3.1.3
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.locale.en-US.yaml
  manifests/p/Proton/ProtonMailBridge/3.1.3/Proton.ProtonMailBridge.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#141892 New version: Jackett.Jackett version 0.21.1932
  manifests/j/Jackett/Jackett/0.21.1932/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.1932/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.1932/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
