Repository microsoft/winget-pkgs, pull requests merged in 2024-07, with the labels that each got.

#159683 Remove version: VGN.VHUB version 2.3.21
  manifests/v/VGN/VHUB/2.3.21/VGN.VHUB.installer.yaml
  manifests/v/VGN/VHUB/2.3.21/VGN.VHUB.locale.en-US.yaml
  manifests/v/VGN/VHUB/2.3.21/VGN.VHUB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, No-Recent-Activity, Needs-Author-Feedback, Highest-Version-Remaining

#159682 Remove version: Voicemod.Voicemod version 2.40.1.0
  manifests/v/Voicemod/Voicemod/2.40.1.0/Voicemod.Voicemod.installer.yaml
  manifests/v/Voicemod/Voicemod/2.40.1.0/Voicemod.Voicemod.locale.en-US.yaml
  manifests/v/Voicemod/Voicemod/2.40.1.0/Voicemod.Voicemod.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Highest-Version-Remaining

#159695 Remove version: V.MAILLE.EduPython version 3.1
  manifests/v/V/MAILLE/EduPython/3.1/V.MAILLE.EduPython.installer.yaml
  manifests/v/V/MAILLE/EduPython/3.1/V.MAILLE.EduPython.locale.en-US.yaml
  manifests/v/V/MAILLE/EduPython/3.1/V.MAILLE.EduPython.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Highest-Version-Remaining

#160771 Update: FutureScholars.Paperlib version 3.1.2
  manifests/f/FutureScholars/Paperlib/3.1.2/FutureScholars.Paperlib.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160769 Update: FutureScholars.Paperlib version 3.1.5
  manifests/f/FutureScholars/Paperlib/3.1.5/FutureScholars.Paperlib.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160782 New version: MichaelTippach.ASIO4ALL version 2.16
  manifests/m/MichaelTippach/ASIO4ALL/2.16/MichaelTippach.ASIO4ALL.installer.yaml
  manifests/m/MichaelTippach/ASIO4ALL/2.16/MichaelTippach.ASIO4ALL.locale.en-US.yaml
  manifests/m/MichaelTippach/ASIO4ALL/2.16/MichaelTippach.ASIO4ALL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160783 New version: Kuro.Mery.Beta version 3.7.2
  manifests/k/Kuro/Mery/Beta/3.7.2/Kuro.Mery.Beta.installer.yaml
  manifests/k/Kuro/Mery/Beta/3.7.2/Kuro.Mery.Beta.locale.ja-JP.yaml
  manifests/k/Kuro/Mery/Beta/3.7.2/Kuro.Mery.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160949 Add MongoDB.Compass.Isolated 1.43.4.0
  manifests/m/MongoDB/Compass/Isolated/1.43.4.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.43.4.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.43.4.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160947 Add MongoDB.Compass.Full 1.43.4.0
  manifests/m/MongoDB/Compass/Full/1.43.4.0/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.43.4.0/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.43.4.0/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160950 Moved: XMediaRecode.XMediaRecode version 3.5.9.6
  manifests/x/XMediaRecode/XMediaRecode/3.5.9.6/XMediaRecode.XMediaRecode.installer.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.5.9.6/XMediaRecode.XMediaRecode.locale.en-US.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.5.9.6/XMediaRecode.XMediaRecode.locale.zh-CN.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.5.9.6/XMediaRecode.XMediaRecode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#160951 Moving: XMediaRecode64bit.XMediaRecode64bit version 3.5.9.6
  manifests/x/XMediaRecode64bit/XMediaRecode64bit/3.5.9.6/XMediaRecode64bit.XMediaRecode64bit.installer.yaml
  manifests/x/XMediaRecode64bit/XMediaRecode64bit/3.5.9.6/XMediaRecode64bit.XMediaRecode64bit.locale.en-US.yaml
  manifests/x/XMediaRecode64bit/XMediaRecode64bit/3.5.9.6/XMediaRecode64bit.XMediaRecode64bit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160955 New version: JetBrains.IntelliJIDEA.Community.EAP version 242.19533.56
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/242.19533.56/JetBrains.IntelliJIDEA.Community.EAP.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/242.19533.56/JetBrains.IntelliJIDEA.Community.EAP.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/242.19533.56/JetBrains.IntelliJIDEA.Community.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/IntelliJIDEA/Community/EAP/242.19533.56/JetBrains.IntelliJIDEA.Community.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160954 New version: BartoszCichecki.LenovoLegionToolkit version 2.23.0
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.23.0/BartoszCichecki.LenovoLegionToolkit.installer.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.23.0/BartoszCichecki.LenovoLegionToolkit.locale.en-US.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.23.0/BartoszCichecki.LenovoLegionToolkit.locale.zh-CN.yaml
  manifests/b/BartoszCichecki/LenovoLegionToolkit/2.23.0/BartoszCichecki.LenovoLegionToolkit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160956 New version: JetBrains.IntelliJIDEA.Ultimate.EAP version 242.19533.56
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/242.19533.56/JetBrains.IntelliJIDEA.Ultimate.EAP.installer.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/242.19533.56/JetBrains.IntelliJIDEA.Ultimate.EAP.locale.en-US.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/242.19533.56/JetBrains.IntelliJIDEA.Ultimate.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/IntelliJIDEA/Ultimate/EAP/242.19533.56/JetBrains.IntelliJIDEA.Ultimate.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160952 Add MongoDB.Compass.Readonly 1.43.4.0
  manifests/m/MongoDB/Compass/Readonly/1.43.4.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.43.4.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.43.4.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160957 Add version: Derailed.k9s version v0.32.5
  manifests/d/Derailed/k9s/v0.32.5/Derailed.k9s.installer.yaml
  manifests/d/Derailed/k9s/v0.32.5/Derailed.k9s.locale.en-US.yaml
  manifests/d/Derailed/k9s/v0.32.5/Derailed.k9s.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160958 New version: Microsoft.DevProxy version 0.19.1
  manifests/m/Microsoft/DevProxy/0.19.1/Microsoft.DevProxy.installer.yaml
  manifests/m/Microsoft/DevProxy/0.19.1/Microsoft.DevProxy.locale.en-US.yaml
  manifests/m/Microsoft/DevProxy/0.19.1/Microsoft.DevProxy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160959 New version: EdgeTX.Companion version 2.10.2
  manifests/e/EdgeTX/Companion/2.10.2/EdgeTX.Companion.installer.yaml
  manifests/e/EdgeTX/Companion/2.10.2/EdgeTX.Companion.locale.en-US.yaml
  manifests/e/EdgeTX/Companion/2.10.2/EdgeTX.Companion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160946 New package: Microsoft.DotNet.AspNetCore.2_2 version 2.2.207
  manifests/m/Microsoft/DotNet/AspNetCore/2_2/2.2.207/Microsoft.DotNet.AspNetCore.2_2.installer.yaml
  manifests/m/Microsoft/DotNet/AspNetCore/2_2/2.2.207/Microsoft.DotNet.AspNetCore.2_2.locale.en-US.yaml
  manifests/m/Microsoft/DotNet/AspNetCore/2_2/2.2.207/Microsoft.DotNet.AspNetCore.2_2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Review, New-Package

#160960 New version: AquaSecurity.Trivy version 0.53.0
  manifests/a/AquaSecurity/Trivy/0.53.0/AquaSecurity.Trivy.installer.yaml
  manifests/a/AquaSecurity/Trivy/0.53.0/AquaSecurity.Trivy.locale.en-US.yaml
  manifests/a/AquaSecurity/Trivy/0.53.0/AquaSecurity.Trivy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160962 New version: Tohrusky.Final2x version 2024-07-01
  manifests/t/Tohrusky/Final2x/2024-07-01/Tohrusky.Final2x.installer.yaml
  manifests/t/Tohrusky/Final2x/2024-07-01/Tohrusky.Final2x.locale.en-US.yaml
  manifests/t/Tohrusky/Final2x/2024-07-01/Tohrusky.Final2x.locale.zh-CN.yaml
  manifests/t/Tohrusky/Final2x/2024-07-01/Tohrusky.Final2x.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160964 Modify: KeePassXCTeam.KeePassXC version 2.7.9
  manifests/k/KeePassXCTeam/KeePassXC/2.7.9/KeePassXCTeam.KeePassXC.installer.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.9/KeePassXCTeam.KeePassXC.locale.en-US.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.9/KeePassXCTeam.KeePassXC.locale.zh-CN.yaml
  manifests/k/KeePassXCTeam/KeePassXC/2.7.9/KeePassXCTeam.KeePassXC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160917 New version: EclipseAdoptium.Temurin.20.JRE version 20.0.2.9
  manifests/e/EclipseAdoptium/Temurin/20/JRE/20.0.2.9/EclipseAdoptium.Temurin.20.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JRE/20.0.2.9/EclipseAdoptium.Temurin.20.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JRE/20.0.2.9/EclipseAdoptium.Temurin.20.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JRE/20.0.2.9/EclipseAdoptium.Temurin.20.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160973 Moved: FlorianHeidenreich.Mp3tag version 3.26
  manifests/f/FlorianHeidenreich/Mp3tag/3.26/FlorianHeidenreich.Mp3tag.installer.yaml
  manifests/f/FlorianHeidenreich/Mp3tag/3.26/FlorianHeidenreich.Mp3tag.locale.en-US.yaml
  manifests/f/FlorianHeidenreich/Mp3tag/3.26/FlorianHeidenreich.Mp3tag.locale.zh-CN.yaml
  manifests/f/FlorianHeidenreich/Mp3tag/3.26/FlorianHeidenreich.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#160974 Moving: Mp3tag.Mp3tag version 3.26
  manifests/m/Mp3tag/Mp3tag/3.26/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.26/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.26/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160966 Remove: Mp3tag.Mp3tag version 3.18
  manifests/m/Mp3tag/Mp3tag/3.18/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.18/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.18/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160967 Remove: Mp3tag.Mp3tag version 3.19
  manifests/m/Mp3tag/Mp3tag/3.19/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.19/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.19/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#160969 Remove: Mp3tag.Mp3tag version 3.22b
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.22b/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#160968 Remove: Mp3tag.Mp3tag version 3.21
  manifests/m/Mp3tag/Mp3tag/3.21/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.21/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.21/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#160970 Remove: Mp3tag.Mp3tag version 3.23
  manifests/m/Mp3tag/Mp3tag/3.23/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.23/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.23/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#160918 Modify: CodeSector.TeraCopy version 3.17
  manifests/c/CodeSector/TeraCopy/3.17/CodeSector.TeraCopy.installer.yaml
  manifests/c/CodeSector/TeraCopy/3.17/CodeSector.TeraCopy.locale.en-US.yaml
  manifests/c/CodeSector/TeraCopy/3.17/CodeSector.TeraCopy.locale.zh-CN.yaml
  manifests/c/CodeSector/TeraCopy/3.17/CodeSector.TeraCopy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160972 Remove: Mp3tag.Mp3tag version 3.25
  manifests/m/Mp3tag/Mp3tag/3.25/Mp3tag.Mp3tag.installer.yaml
  manifests/m/Mp3tag/Mp3tag/3.25/Mp3tag.Mp3tag.locale.en-US.yaml
  manifests/m/Mp3tag/Mp3tag/3.25/Mp3tag.Mp3tag.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback

#160919 New version: Huawei.IdeaShare version 7.03.1.01
  manifests/h/Huawei/IdeaShare/7.03.1.01/Huawei.IdeaShare.installer.yaml
  manifests/h/Huawei/IdeaShare/7.03.1.01/Huawei.IdeaShare.locale.en-US.yaml
  manifests/h/Huawei/IdeaShare/7.03.1.01/Huawei.IdeaShare.locale.zh-CN.yaml
  manifests/h/Huawei/IdeaShare/7.03.1.01/Huawei.IdeaShare.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160921 New version: Zoom.Zoom version 6.1.41705 (6.1.1.41705)
  manifests/z/Zoom/Zoom/6.1.41705/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/6.1.41705/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/6.1.41705/Zoom.Zoom.locale.zh-CN.yaml
  manifests/z/Zoom/Zoom/6.1.41705/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160922 New version: Balena.Etcher version 1.19.21
  manifests/b/Balena/Etcher/1.19.21/Balena.Etcher.installer.yaml
  manifests/b/Balena/Etcher/1.19.21/Balena.Etcher.locale.en-US.yaml
  manifests/b/Balena/Etcher/1.19.21/Balena.Etcher.locale.zh-CN.yaml
  manifests/b/Balena/Etcher/1.19.21/Balena.Etcher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Manifest, Manifest-Metadata-Consistency

#160923 New version: Alibaba.QuarkCloudDrive version 3.4.0
  manifests/a/Alibaba/QuarkCloudDrive/3.4.0/Alibaba.QuarkCloudDrive.installer.yaml
  manifests/a/Alibaba/QuarkCloudDrive/3.4.0/Alibaba.QuarkCloudDrive.locale.en-US.yaml
  manifests/a/Alibaba/QuarkCloudDrive/3.4.0/Alibaba.QuarkCloudDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/QuarkCloudDrive/3.4.0/Alibaba.QuarkCloudDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160924 New version: Docker.DockerCLI version 27.0.3
  manifests/d/Docker/DockerCLI/27.0.3/Docker.DockerCLI.installer.yaml
  manifests/d/Docker/DockerCLI/27.0.3/Docker.DockerCLI.locale.en-US.yaml
  manifests/d/Docker/DockerCLI/27.0.3/Docker.DockerCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160925 New version: Evernote.Evernote version 10.94.3
  manifests/e/Evernote/Evernote/10.94.3/Evernote.Evernote.installer.yaml
  manifests/e/Evernote/Evernote/10.94.3/Evernote.Evernote.locale.en-US.yaml
  manifests/e/Evernote/Evernote/10.94.3/Evernote.Evernote.locale.zh-CN.yaml
  manifests/e/Evernote/Evernote/10.94.3/Evernote.Evernote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160928 Update Gitkraken.cli 1.2.1
  manifests/g/GitKraken/cli/2.1.0/GitKraken.cli.installer.yaml
  manifests/g/GitKraken/cli/2.1.0/GitKraken.cli.locale.en-US.yaml
  manifests/g/GitKraken/cli/2.1.0/GitKraken.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest, Manifest-Metadata-Consistency

#160926 New version: LukiLabs.Craft version 1.39.0
  manifests/l/LukiLabs/Craft/1.39.0/LukiLabs.Craft.installer.yaml
  manifests/l/LukiLabs/Craft/1.39.0/LukiLabs.Craft.locale.en-US.yaml
  manifests/l/LukiLabs/Craft/1.39.0/LukiLabs.Craft.locale.zh-CN.yaml
  manifests/l/LukiLabs/Craft/1.39.0/LukiLabs.Craft.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160929 New version: AdGuard.AdGuard version 7.17.4712.0
  manifests/a/AdGuard/AdGuard/7.17.4712.0/AdGuard.AdGuard.installer.yaml
  manifests/a/AdGuard/AdGuard/7.17.4712.0/AdGuard.AdGuard.locale.en-US.yaml
  manifests/a/AdGuard/AdGuard/7.17.4712.0/AdGuard.AdGuard.locale.zh-CN.yaml
  manifests/a/AdGuard/AdGuard/7.17.4712.0/AdGuard.AdGuard.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160931 New version: KDE.Krita version 5.2.3.100 (5.2.3)
  manifests/k/KDE/Krita/5.2.3.100/KDE.Krita.installer.yaml
  manifests/k/KDE/Krita/5.2.3.100/KDE.Krita.locale.en-US.yaml
  manifests/k/KDE/Krita/5.2.3.100/KDE.Krita.locale.zh-CN.yaml
  manifests/k/KDE/Krita/5.2.3.100/KDE.Krita.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, New-Manifest, Manifest-Metadata-Consistency

#160933 Modify: KDE.Krita version 4.4.3.0
  manifests/k/KDE/Krita/4.4.3.0/KDE.Krita.installer.yaml
  manifests/k/KDE/Krita/4.4.3.0/KDE.Krita.locale.en-US.yaml
  manifests/k/KDE/Krita/4.4.3.0/KDE.Krita.locale.zh-CN.yaml
  manifests/k/KDE/Krita/4.4.3.0/KDE.Krita.yaml
  manifests/k/KDE/Krita/4.4.3/KDE.Krita.installer.yaml
  manifests/k/KDE/Krita/4.4.3/KDE.Krita.locale.en-US.yaml
  manifests/k/KDE/Krita/4.4.3/KDE.Krita.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, New-Manifest, Manifest-Metadata-Consistency

#160965 New version: JetBrains.PhpStorm.EAP version 242.19533.60
  manifests/j/JetBrains/PhpStorm/EAP/242.19533.60/JetBrains.PhpStorm.EAP.installer.yaml
  manifests/j/JetBrains/PhpStorm/EAP/242.19533.60/JetBrains.PhpStorm.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PhpStorm/EAP/242.19533.60/JetBrains.PhpStorm.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/PhpStorm/EAP/242.19533.60/JetBrains.PhpStorm.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160977 Add Bruno.Bruno 1.20.0
  manifests/b/Bruno/Bruno/1.20.0/Bruno.Bruno.installer.yaml
  manifests/b/Bruno/Bruno/1.20.0/Bruno.Bruno.locale.en-US.yaml
  manifests/b/Bruno/Bruno/1.20.0/Bruno.Bruno.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160891 Remove version: ZAP.ZAP version 2.13.0
  manifests/z/ZAP/ZAP/2.13.0/ZAP.ZAP.installer.yaml
  manifests/z/ZAP/ZAP/2.13.0/ZAP.ZAP.locale.en-US.yaml
  manifests/z/ZAP/ZAP/2.13.0/ZAP.ZAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160890 Modify: EclipseAdoptium.Temurin.8.JDK version 8.0.412.8
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.412.8/EclipseAdoptium.Temurin.8.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.412.8/EclipseAdoptium.Temurin.8.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.412.8/EclipseAdoptium.Temurin.8.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JDK/8.0.412.8/EclipseAdoptium.Temurin.8.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160892 Modify: EclipseAdoptium.Temurin.11.JDK version 11.0.23.9
  manifests/e/EclipseAdoptium/Temurin/11/JDK/11.0.23.9/EclipseAdoptium.Temurin.11.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/11/JDK/11.0.23.9/EclipseAdoptium.Temurin.11.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/11/JDK/11.0.23.9/EclipseAdoptium.Temurin.11.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/11/JDK/11.0.23.9/EclipseAdoptium.Temurin.11.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160894 New version: Appest.Dida version 6.0.0.1
  manifests/a/Appest/Dida/6.0.0.1/Appest.Dida.installer.yaml
  manifests/a/Appest/Dida/6.0.0.1/Appest.Dida.locale.en-US.yaml
  manifests/a/Appest/Dida/6.0.0.1/Appest.Dida.locale.zh-CN.yaml
  manifests/a/Appest/Dida/6.0.0.1/Appest.Dida.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160893 New version: Alibaba.DingTalk version 7.6.0-Release.62810810
  manifests/a/Alibaba/DingTalk/7.6.0-Release.62810810/Alibaba.DingTalk.installer.yaml
  manifests/a/Alibaba/DingTalk/7.6.0-Release.62810810/Alibaba.DingTalk.locale.en-US.yaml
  manifests/a/Alibaba/DingTalk/7.6.0-Release.62810810/Alibaba.DingTalk.locale.zh-CN.yaml
  manifests/a/Alibaba/DingTalk/7.6.0-Release.62810810/Alibaba.DingTalk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160895 Modify: EclipseAdoptium.Temurin.16.JDK version 16.0.2.7
  manifests/e/EclipseAdoptium/Temurin/16/JDK/16.0.2.7/EclipseAdoptium.Temurin.16.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/16/JDK/16.0.2.7/EclipseAdoptium.Temurin.16.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/16/JDK/16.0.2.7/EclipseAdoptium.Temurin.16.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/16/JDK/16.0.2.7/EclipseAdoptium.Temurin.16.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160896 Modify: EclipseAdoptium.Temurin.17.JDK version 17.0.11.9
  manifests/e/EclipseAdoptium/Temurin/17/JDK/17.0.11.9/EclipseAdoptium.Temurin.17.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/17/JDK/17.0.11.9/EclipseAdoptium.Temurin.17.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/17/JDK/17.0.11.9/EclipseAdoptium.Temurin.17.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/17/JDK/17.0.11.9/EclipseAdoptium.Temurin.17.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160903 New version: 2BrightSparks.SyncBackPro version 11.3.35.0
  manifests/2/2BrightSparks/SyncBackPro/11.3.35.0/2BrightSparks.SyncBackPro.installer.yaml
  manifests/2/2BrightSparks/SyncBackPro/11.3.35.0/2BrightSparks.SyncBackPro.locale.en-US.yaml
  manifests/2/2BrightSparks/SyncBackPro/11.3.35.0/2BrightSparks.SyncBackPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160901 New version: 2BrightSparks.SyncBackFree version 11.3.35.0
  manifests/2/2BrightSparks/SyncBackFree/11.3.35.0/2BrightSparks.SyncBackFree.installer.yaml
  manifests/2/2BrightSparks/SyncBackFree/11.3.35.0/2BrightSparks.SyncBackFree.locale.en-US.yaml
  manifests/2/2BrightSparks/SyncBackFree/11.3.35.0/2BrightSparks.SyncBackFree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160902 New version: 2BrightSparks.SyncBackSE version 11.3.35.0
  manifests/2/2BrightSparks/SyncBackSE/11.3.35.0/2BrightSparks.SyncBackSE.installer.yaml
  manifests/2/2BrightSparks/SyncBackSE/11.3.35.0/2BrightSparks.SyncBackSE.locale.en-US.yaml
  manifests/2/2BrightSparks/SyncBackSE/11.3.35.0/2BrightSparks.SyncBackSE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160900 Modify: EclipseAdoptium.Temurin.21.JDK version 21.0.3.9
  manifests/e/EclipseAdoptium/Temurin/21/JDK/21.0.3.9/EclipseAdoptium.Temurin.21.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JDK/21.0.3.9/EclipseAdoptium.Temurin.21.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JDK/21.0.3.9/EclipseAdoptium.Temurin.21.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JDK/21.0.3.9/EclipseAdoptium.Temurin.21.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160898 Modify: EclipseAdoptium.Temurin.19.JDK version 19.0.2.7
  manifests/e/EclipseAdoptium/Temurin/19/JDK/19.0.2.7/EclipseAdoptium.Temurin.19.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JDK/19.0.2.7/EclipseAdoptium.Temurin.19.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JDK/19.0.2.7/EclipseAdoptium.Temurin.19.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JDK/19.0.2.7/EclipseAdoptium.Temurin.19.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160905 Modify: EclipseAdoptium.Temurin.8.JRE version 8.0.412.8
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.412.8/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.412.8/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.412.8/EclipseAdoptium.Temurin.8.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.412.8/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160906 New version: Google.Chrome.Canary version 128.0.6569.0
  manifests/g/Google/Chrome/Canary/128.0.6569.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/128.0.6569.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/128.0.6569.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/128.0.6569.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/128.0.6569.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160899 Modify: EclipseAdoptium.Temurin.20.JDK version 20.0.2.9
  manifests/e/EclipseAdoptium/Temurin/20/JDK/20.0.2.9/EclipseAdoptium.Temurin.20.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JDK/20.0.2.9/EclipseAdoptium.Temurin.20.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JDK/20.0.2.9/EclipseAdoptium.Temurin.20.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/20/JDK/20.0.2.9/EclipseAdoptium.Temurin.20.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160976 New package: OverlayedDev.Overlayed version 0.3.0
  manifests/o/OverlayedDev/Overlayed/0.3.0/OverlayedDev.Overlayed.installer.yaml
  manifests/o/OverlayedDev/Overlayed/0.3.0/OverlayedDev.Overlayed.locale.en-US.yaml
  manifests/o/OverlayedDev/Overlayed/0.3.0/OverlayedDev.Overlayed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160904 New package: EclipseAdoptium.Temurin.22.JDK version 22.0.1.8
  manifests/e/EclipseAdoptium/Temurin/22/JDK/22.0.1.8/EclipseAdoptium.Temurin.22.JDK.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JDK/22.0.1.8/EclipseAdoptium.Temurin.22.JDK.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JDK/22.0.1.8/EclipseAdoptium.Temurin.22.JDK.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JDK/22.0.1.8/EclipseAdoptium.Temurin.22.JDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160912 Modify: EclipseAdoptium.Temurin.19.JRE version 19.0.2.7
  manifests/e/EclipseAdoptium/Temurin/19/JRE/19.0.2.7/EclipseAdoptium.Temurin.19.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JRE/19.0.2.7/EclipseAdoptium.Temurin.19.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JRE/19.0.2.7/EclipseAdoptium.Temurin.19.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/19/JRE/19.0.2.7/EclipseAdoptium.Temurin.19.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160914 New version: EclipseAdoptium.Temurin.21.JRE version 21.0.3.9
  manifests/e/EclipseAdoptium/Temurin/21/JRE/21.0.3.9/EclipseAdoptium.Temurin.21.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JRE/21.0.3.9/EclipseAdoptium.Temurin.21.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JRE/21.0.3.9/EclipseAdoptium.Temurin.21.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/21/JRE/21.0.3.9/EclipseAdoptium.Temurin.21.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160916 New version: Appest.TickTick version 6.0.0.1
  manifests/a/Appest/TickTick/6.0.0.1/Appest.TickTick.installer.yaml
  manifests/a/Appest/TickTick/6.0.0.1/Appest.TickTick.locale.en-US.yaml
  manifests/a/Appest/TickTick/6.0.0.1/Appest.TickTick.locale.zh-CN.yaml
  manifests/a/Appest/TickTick/6.0.0.1/Appest.TickTick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160978 New version: OneWare.OneWareStudio version 0.17.5.0
  manifests/o/OneWare/OneWareStudio/0.17.5.0/OneWare.OneWareStudio.installer.yaml
  manifests/o/OneWare/OneWareStudio/0.17.5.0/OneWare.OneWareStudio.locale.en-US.yaml
  manifests/o/OneWare/OneWareStudio/0.17.5.0/OneWare.OneWareStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160979 New version: Emurasoft.EmEditor version 24.3.1
  manifests/e/Emurasoft/EmEditor/24.3.1/Emurasoft.EmEditor.installer.yaml
  manifests/e/Emurasoft/EmEditor/24.3.1/Emurasoft.EmEditor.locale.en-US.yaml
  manifests/e/Emurasoft/EmEditor/24.3.1/Emurasoft.EmEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160855 Remove version: Kiraku.AudioJam version 1.12.0-199
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.12.0-199/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160857 Remove version: Kiraku.AudioJam version 2.1.1-383
  manifests/k/Kiraku/AudioJam/2.1.1-383/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.1.1-383/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.1.1-383/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.1.1-383/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160856 Remove version: Kiraku.AudioJam version 1.15.5-299
  manifests/k/Kiraku/AudioJam/1.15.5-299/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-299/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-299/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-299/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160860 Remove version: Kiraku.Mindbox version 2.3.0-388
  manifests/k/Kiraku/Mindbox/2.3.0-388/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/2.3.0-388/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/2.3.0-388/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/2.3.0-388/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160859 Remove version: Kiraku.Mindbox version 1.3.2-208
  manifests/k/Kiraku/Mindbox/1.3.2-208/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.3.2-208/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.3.2-208/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.3.2-208/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160858 Remove version: Kiraku.AudioJam version 1.17.5-356
  manifests/k/Kiraku/AudioJam/1.17.5-356/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.17.5-356/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.17.5-356/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.17.5-356/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160862 Remove version: Kiraku.Mindbox version 1.5.1-250
  manifests/k/Kiraku/Mindbox/1.5.1-250/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.5.1-250/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.5.1-250/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.5.1-250/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160864 Remove version: Kiraku.Mindbox version 2.5.3-560
  manifests/k/Kiraku/Mindbox/2.5.3-560/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/2.5.3-560/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/2.5.3-560/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/2.5.3-560/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160866 Remove version: Kiraku.Mindbox version 2.6.0-563
  manifests/k/Kiraku/Mindbox/2.6.0-563/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/2.6.0-563/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/2.6.0-563/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/2.6.0-563/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160861 Remove version: Kiraku.Mindbox version 1.5.2-253
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.5.2-253/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160869 Remove version: Kiraku.Mindbox version 1.3.1-207
  manifests/k/Kiraku/Mindbox/1.3.1-207/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.3.1-207/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.3.1-207/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.3.1-207/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160865 Remove version: Kiraku.Mindbox version 2.2.0-381
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/2.2.0-381/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160868 Remove version: Kiraku.Mindbox version 1.5.0-233
  manifests/k/Kiraku/Mindbox/1.5.0-233/Kiraku.Mindbox.installer.yaml
  manifests/k/Kiraku/Mindbox/1.5.0-233/Kiraku.Mindbox.locale.en-US.yaml
  manifests/k/Kiraku/Mindbox/1.5.0-233/Kiraku.Mindbox.locale.zh-CN.yaml
  manifests/k/Kiraku/Mindbox/1.5.0-233/Kiraku.Mindbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160873 Remove version: Kiwix.WikiMed version 2.5.0.0
  manifests/k/Kiwix/WikiMed/2.5.0.0/Kiwix.WikiMed.installer.yaml
  manifests/k/Kiwix/WikiMed/2.5.0.0/Kiwix.WikiMed.locale.en-GB.yaml
  manifests/k/Kiwix/WikiMed/2.5.0.0/Kiwix.WikiMed.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160872 Remove version: Kiwix.WikiMed.Electron version 2.5.0-E
  manifests/k/Kiwix/WikiMed/Electron/2.5.0-E/Kiwix.WikiMed.Electron.installer.yaml
  manifests/k/Kiwix/WikiMed/Electron/2.5.0-E/Kiwix.WikiMed.Electron.locale.en-GB.yaml
  manifests/k/Kiwix/WikiMed/Electron/2.5.0-E/Kiwix.WikiMed.Electron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160874 New version: nektos.act version 0.2.64
  manifests/n/nektos/act/0.2.64/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.64/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.64/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160875 New version: Fastfetch-cli.Fastfetch version 2.17.1
  manifests/f/Fastfetch-cli/Fastfetch/2.17.1/Fastfetch-cli.Fastfetch.installer.yaml
  manifests/f/Fastfetch-cli/Fastfetch/2.17.1/Fastfetch-cli.Fastfetch.locale.en-US.yaml
  manifests/f/Fastfetch-cli/Fastfetch/2.17.1/Fastfetch-cli.Fastfetch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160915 New package: EclipseAdoptium.Temurin.22.JRE version 22.0.1.8
  manifests/e/EclipseAdoptium/Temurin/22/JRE/22.0.1.8/EclipseAdoptium.Temurin.22.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JRE/22.0.1.8/EclipseAdoptium.Temurin.22.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JRE/22.0.1.8/EclipseAdoptium.Temurin.22.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/22/JRE/22.0.1.8/EclipseAdoptium.Temurin.22.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160876 Remove version: KoushikNaskar.InteractiveDataEditor version 2.13.0.0
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.13.0.0/KoushikNaskar.InteractiveDataEditor.installer.yaml
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.13.0.0/KoushikNaskar.InteractiveDataEditor.locale.en-US.yaml
  manifests/k/KoushikNaskar/InteractiveDataEditor/2.13.0.0/KoushikNaskar.InteractiveDataEditor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160879 Update Netron to 7.7.6
  manifests/l/LutzRoeder/Netron/7.7.6/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/7.7.6/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/7.7.6/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160881 Remove version: 360.360Chrome.X version 21.0.1090.0
  manifests/3/360/360Chrome/X/21.0.1090.0/360.360Chrome.X.installer.yaml
  manifests/3/360/360Chrome/X/21.0.1090.0/360.360Chrome.X.locale.en-US.yaml
  manifests/3/360/360Chrome/X/21.0.1090.0/360.360Chrome.X.locale.zh-CN.yaml
  manifests/3/360/360Chrome/X/21.0.1090.0/360.360Chrome.X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160880 86boxmanager
  manifests/8/86Box/86BoxManager/1.7.4/86Box.86BoxManager.installer.yaml
  manifests/8/86Box/86BoxManager/1.7.4/86Box.86BoxManager.locale.en-US.yaml
  manifests/8/86Box/86BoxManager/1.7.4/86Box.86BoxManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160827 New version: OddLab.Cubox version 0.2.4
  manifests/o/OddLab/Cubox/0.2.4/OddLab.Cubox.installer.yaml
  manifests/o/OddLab/Cubox/0.2.4/OddLab.Cubox.locale.en-US.yaml
  manifests/o/OddLab/Cubox/0.2.4/OddLab.Cubox.locale.zh-CN.yaml
  manifests/o/OddLab/Cubox/0.2.4/OddLab.Cubox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160854 Remove version: Kiraku.AudioJam version 1.17.3-352
  manifests/k/Kiraku/AudioJam/1.17.3-352/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.17.3-352/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.17.3-352/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.17.3-352/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160853 Remove version: Kiraku.AudioJam version 1.15.5-296
  manifests/k/Kiraku/AudioJam/1.15.5-296/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-296/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-296/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.15.5-296/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160852 Remove version: Kiraku.AudioJam version 1.15.2-291
  manifests/k/Kiraku/AudioJam/1.15.2-291/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.15.2-291/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.15.2-291/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.15.2-291/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160851 Remove version: Kiraku.AudioJam version 1.13.1-270
  manifests/k/Kiraku/AudioJam/1.13.1-270/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.13.1-270/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.13.1-270/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.13.1-270/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160850 Remove version: Kiraku.AudioJam version 1.17.1-335
  manifests/k/Kiraku/AudioJam/1.17.1-335/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.17.1-335/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.17.1-335/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.17.1-335/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160846 Remove version: Kiraku.AudioJam version 2.0.1-370
  manifests/k/Kiraku/AudioJam/2.0.1-370/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.0.1-370/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.0.1-370/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.0.1-370/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160849 Remove version: Kiraku.AudioJam version 1.13.2-276
  manifests/k/Kiraku/AudioJam/1.13.2-276/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.13.2-276/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.13.2-276/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.13.2-276/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160848 Remove version: Kiraku.AudioJam version 2.7.0-525
  manifests/k/Kiraku/AudioJam/2.7.0-525/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.7.0-525/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.7.0-525/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.7.0-525/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160847 Remove version: Kiraku.AudioJam version 1.12.1-200
  manifests/k/Kiraku/AudioJam/1.12.1-200/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.12.1-200/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.12.1-200/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.12.1-200/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160841 Remove version: Kiraku.AudioJam version 2.3.2-399
  manifests/k/Kiraku/AudioJam/2.3.2-399/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.3.2-399/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.3.2-399/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.3.2-399/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160842 Remove version: Kiraku.AudioJam version 1.13.0-267
  manifests/k/Kiraku/AudioJam/1.13.0-267/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.13.0-267/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.13.0-267/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.13.0-267/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160839 Remove version: Kiraku.AudioJam version 1.11.3-190
  manifests/k/Kiraku/AudioJam/1.11.3-190/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.11.3-190/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.11.3-190/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.11.3-190/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160836 Remove version: Kiraku.AudioJam version 2.0.0-366
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.0.0-366/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160837 Remove version: Kiraku.AudioJam version 2.3.0-395
  manifests/k/Kiraku/AudioJam/2.3.0-395/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.3.0-395/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.3.0-395/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.3.0-395/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160835 Remove version: Kiraku.AudioJam version 2.0.3-375
  manifests/k/Kiraku/AudioJam/2.0.3-375/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.0.3-375/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.0.3-375/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.0.3-375/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160833 Remove version: Kiraku.AudioJam version 1.17.2-338
  manifests/k/Kiraku/AudioJam/1.17.2-338/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.17.2-338/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.17.2-338/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.17.2-338/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160834 Remove version: Kiraku.AudioJam version 2.0.2-372
  manifests/k/Kiraku/AudioJam/2.0.2-372/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.0.2-372/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.0.2-372/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.0.2-372/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160832 Remove version: Kiraku.AudioJam version 1.10.0-165
  manifests/k/Kiraku/AudioJam/1.10.0-165/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.10.0-165/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.10.0-165/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.10.0-165/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160830 Remove version: Kiraku.AudioJam version 1.16.1-322
  manifests/k/Kiraku/AudioJam/1.16.1-322/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/1.16.1-322/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/1.16.1-322/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/1.16.1-322/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160829 Remove version: Kiraku.AudioJam version 2.7.1-527
  manifests/k/Kiraku/AudioJam/2.7.1-527/Kiraku.AudioJam.installer.yaml
  manifests/k/Kiraku/AudioJam/2.7.1-527/Kiraku.AudioJam.locale.en-US.yaml
  manifests/k/Kiraku/AudioJam/2.7.1-527/Kiraku.AudioJam.locale.zh-CN.yaml
  manifests/k/Kiraku/AudioJam/2.7.1-527/Kiraku.AudioJam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160793 New version: xpipe-io.xpipe version 10.0.2
  manifests/x/xpipe-io/xpipe/10.0.2/xpipe-io.xpipe.installer.yaml
  manifests/x/xpipe-io/xpipe/10.0.2/xpipe-io.xpipe.locale.en-US.yaml
  manifests/x/xpipe-io/xpipe/10.0.2/xpipe-io.xpipe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#160794 New version: Microsoft.DevHome version 0.1501.533.0
  manifests/m/Microsoft/DevHome/0.1501.533.0/Microsoft.DevHome.installer.yaml
  manifests/m/Microsoft/DevHome/0.1501.533.0/Microsoft.DevHome.locale.en-US.yaml
  manifests/m/Microsoft/DevHome/0.1501.533.0/Microsoft.DevHome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160800 New version: taers232c.GAMADV-XTD3 version 6.77.03
  manifests/t/taers232c/GAMADV-XTD3/6.77.03/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.77.03/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.77.03/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160804 New version: DigitalOcean.Doctl version 1.108.0
  manifests/d/DigitalOcean/Doctl/1.108.0/DigitalOcean.Doctl.installer.yaml
  manifests/d/DigitalOcean/Doctl/1.108.0/DigitalOcean.Doctl.locale.en-US.yaml
  manifests/d/DigitalOcean/Doctl/1.108.0/DigitalOcean.Doctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160805 New version: Google.Chrome.Canary version 128.0.6568.0
  manifests/g/Google/Chrome/Canary/128.0.6568.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/128.0.6568.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/128.0.6568.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/128.0.6568.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/128.0.6568.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160810 New version: Giuspen.Cherrytree version 1.1.4.0
  manifests/g/Giuspen/Cherrytree/1.1.4.0/Giuspen.Cherrytree.installer.yaml
  manifests/g/Giuspen/Cherrytree/1.1.4.0/Giuspen.Cherrytree.locale.en-US.yaml
  manifests/g/Giuspen/Cherrytree/1.1.4.0/Giuspen.Cherrytree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160811 Remove version: Giuspen.Cherrytree version 1.1.3.0
  manifests/g/Giuspen/Cherrytree/1.1.3.0/Giuspen.Cherrytree.installer.yaml
  manifests/g/Giuspen/Cherrytree/1.1.3.0/Giuspen.Cherrytree.locale.en-US.yaml
  manifests/g/Giuspen/Cherrytree/1.1.3.0/Giuspen.Cherrytree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Highest-Version-Remaining

#160812 New version: ThaUnknown.Miru version 5.1.8
  manifests/t/ThaUnknown/Miru/5.1.8/ThaUnknown.Miru.installer.yaml
  manifests/t/ThaUnknown/Miru/5.1.8/ThaUnknown.Miru.locale.en-US.yaml
  manifests/t/ThaUnknown/Miru/5.1.8/ThaUnknown.Miru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160818 Microsoft.winfile version 10.3.0.0
  manifests/m/Microsoft/winfile/10.3.0.0/Microsoft.winfile.installer.yaml
  manifests/m/Microsoft/winfile/10.3.0.0/Microsoft.winfile.locale.en-US.yaml
  manifests/m/Microsoft/winfile/10.3.0.0/Microsoft.winfile.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160819 New version: MilosParipovic.OneCommander version 3.86.1 (3.86.1.0)
  manifests/m/MilosParipovic/OneCommander/3.86.1/MilosParipovic.OneCommander.installer.yaml
  manifests/m/MilosParipovic/OneCommander/3.86.1/MilosParipovic.OneCommander.locale.en-US.yaml
  manifests/m/MilosParipovic/OneCommander/3.86.1/MilosParipovic.OneCommander.locale.zh-CN.yaml
  manifests/m/MilosParipovic/OneCommander/3.86.1/MilosParipovic.OneCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160821 Remove version: Kaedei.Dandanplay version 15.2.0
  manifests/k/Kaedei/Dandanplay/15.2.0/Kaedei.Dandanplay.installer.yaml
  manifests/k/Kaedei/Dandanplay/15.2.0/Kaedei.Dandanplay.locale.en-US.yaml
  manifests/k/Kaedei/Dandanplay/15.2.0/Kaedei.Dandanplay.locale.zh-CN.yaml
  manifests/k/Kaedei/Dandanplay/15.2.0/Kaedei.Dandanplay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160823 Remove version: Kaedei.Dandanplay version 15.3.1
  manifests/k/Kaedei/Dandanplay/15.3.1/Kaedei.Dandanplay.installer.yaml
  manifests/k/Kaedei/Dandanplay/15.3.1/Kaedei.Dandanplay.locale.en-US.yaml
  manifests/k/Kaedei/Dandanplay/15.3.1/Kaedei.Dandanplay.locale.zh-CN.yaml
  manifests/k/Kaedei/Dandanplay/15.3.1/Kaedei.Dandanplay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160820 Remove version: Kaedei.Dandanplay version 15.4.0
  manifests/k/Kaedei/Dandanplay/15.4.0/Kaedei.Dandanplay.installer.yaml
  manifests/k/Kaedei/Dandanplay/15.4.0/Kaedei.Dandanplay.locale.en-US.yaml
  manifests/k/Kaedei/Dandanplay/15.4.0/Kaedei.Dandanplay.locale.zh-CN.yaml
  manifests/k/Kaedei/Dandanplay/15.4.0/Kaedei.Dandanplay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160822 Remove version: Kaedei.Dandanplay version 15.3.0
  manifests/k/Kaedei/Dandanplay/15.3.0/Kaedei.Dandanplay.installer.yaml
  manifests/k/Kaedei/Dandanplay/15.3.0/Kaedei.Dandanplay.locale.en-US.yaml
  manifests/k/Kaedei/Dandanplay/15.3.0/Kaedei.Dandanplay.locale.zh-CN.yaml
  manifests/k/Kaedei/Dandanplay/15.3.0/Kaedei.Dandanplay.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160746 New version: TablePlus.TablePlus version 6.1.0
  manifests/t/TablePlus/TablePlus/6.1.0/TablePlus.TablePlus.installer.yaml
  manifests/t/TablePlus/TablePlus/6.1.0/TablePlus.TablePlus.locale.en-US.yaml
  manifests/t/TablePlus/TablePlus/6.1.0/TablePlus.TablePlus.locale.zh-CN.yaml
  manifests/t/TablePlus/TablePlus/6.1.0/TablePlus.TablePlus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160752 Remove version: OVRASTeam.OpenVR-AdvancedSettings version 5.8.9
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.9/OVRASTeam.OpenVR-AdvancedSettings.installer.yaml
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.9/OVRASTeam.OpenVR-AdvancedSettings.locale.en-US.yaml
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.9/OVRASTeam.OpenVR-AdvancedSettings.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160753 Remove version: OVRASTeam.OpenVR-AdvancedSettings version 5.8.6
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.6/OVRASTeam.OpenVR-AdvancedSettings.installer.yaml
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.6/OVRASTeam.OpenVR-AdvancedSettings.locale.en-US.yaml
  manifests/o/OVRASTeam/OpenVR-AdvancedSettings/5.8.6/OVRASTeam.OpenVR-AdvancedSettings.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160754 MoonlightGameStreamingProject.Moonlight version 6.0.1.0
  manifests/m/MoonlightGameStreamingProject/Moonlight/6.0.1.0/MoonlightGameStreamingProject.Moonlight.installer.yaml
  manifests/m/MoonlightGameStreamingProject/Moonlight/6.0.1.0/MoonlightGameStreamingProject.Moonlight.locale.en-US.yaml
  manifests/m/MoonlightGameStreamingProject/Moonlight/6.0.1.0/MoonlightGameStreamingProject.Moonlight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#160760 New version: DW.Spectrum.Client version 5.1.4.38659
  manifests/d/DW/Spectrum/Client/5.1.4.38659/DW.Spectrum.Client.installer.yaml
  manifests/d/DW/Spectrum/Client/5.1.4.38659/DW.Spectrum.Client.locale.en-US.yaml
  manifests/d/DW/Spectrum/Client/5.1.4.38659/DW.Spectrum.Client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160761 New version: DWANGO.OpenToonz.Nightly version 2024.05.04
  manifests/d/DWANGO/OpenToonz/Nightly/2024.05.04/DWANGO.OpenToonz.Nightly.installer.yaml
  manifests/d/DWANGO/OpenToonz/Nightly/2024.05.04/DWANGO.OpenToonz.Nightly.locale.en-US.yaml
  manifests/d/DWANGO/OpenToonz/Nightly/2024.05.04/DWANGO.OpenToonz.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160762 New version: UniversalMediaServer.UniversalMediaServer version 14.1.0
  manifests/u/UniversalMediaServer/UniversalMediaServer/14.1.0/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/14.1.0/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/14.1.0/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160774 Remove version: eat-pray-ai.yutu version v0.8.0
  manifests/e/eat-pray-ai/yutu/v0.8.0/eat-pray-ai.yutu.installer.yaml
  manifests/e/eat-pray-ai/yutu/v0.8.0/eat-pray-ai.yutu.locale.en-US.yaml
  manifests/e/eat-pray-ai/yutu/v0.8.0/eat-pray-ai.yutu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160773 New version: eat-pray-ai.yutu version 0.9.1
  manifests/e/eat-pray-ai/yutu/0.9.1/eat-pray-ai.yutu.installer.yaml
  manifests/e/eat-pray-ai/yutu/0.9.1/eat-pray-ai.yutu.locale.en-US.yaml
  manifests/e/eat-pray-ai/yutu/0.9.1/eat-pray-ai.yutu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160777 Remove version: eat-pray-ai.yutu version 0.8.2
  manifests/e/eat-pray-ai/yutu/0.8.2/eat-pray-ai.yutu.installer.yaml
  manifests/e/eat-pray-ai/yutu/0.8.2/eat-pray-ai.yutu.locale.en-US.yaml
  manifests/e/eat-pray-ai/yutu/0.8.2/eat-pray-ai.yutu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160776 Remove version: eat-pray-ai.yutu version 0.8.5
  manifests/e/eat-pray-ai/yutu/0.8.5/eat-pray-ai.yutu.installer.yaml
  manifests/e/eat-pray-ai/yutu/0.8.5/eat-pray-ai.yutu.locale.en-US.yaml
  manifests/e/eat-pray-ai/yutu/0.8.5/eat-pray-ai.yutu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160778 Remove version: eat-pray-ai.yutu version 0.8.1
  manifests/e/eat-pray-ai/yutu/0.8.1/eat-pray-ai.yutu.installer.yaml
  manifests/e/eat-pray-ai/yutu/0.8.1/eat-pray-ai.yutu.locale.en-US.yaml
  manifests/e/eat-pray-ai/yutu/0.8.1/eat-pray-ai.yutu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160816 EXEMSI.MSIWrapper version 11.0.53.0
  manifests/e/EXEMSI/MSIWrapper/11.0.53.0/EXEMSI.MSIWrapper.installer.yaml
  manifests/e/EXEMSI/MSIWrapper/11.0.53.0/EXEMSI.MSIWrapper.locale.en-US.yaml
  manifests/e/EXEMSI/MSIWrapper/11.0.53.0/EXEMSI.MSIWrapper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160779 New version: Bin-Huang.Chatbox version 1.3.14
  manifests/b/Bin-Huang/Chatbox/1.3.14/Bin-Huang.Chatbox.installer.yaml
  manifests/b/Bin-Huang/Chatbox/1.3.14/Bin-Huang.Chatbox.locale.en-US.yaml
  manifests/b/Bin-Huang/Chatbox/1.3.14/Bin-Huang.Chatbox.locale.zh-CN.yaml
  manifests/b/Bin-Huang/Chatbox/1.3.14/Bin-Huang.Chatbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160784 New version: FutureScholars.Paperlib version 3.1.6
  manifests/f/FutureScholars/Paperlib/3.1.6/FutureScholars.Paperlib.installer.yaml
  manifests/f/FutureScholars/Paperlib/3.1.6/FutureScholars.Paperlib.locale.en-US.yaml
  manifests/f/FutureScholars/Paperlib/3.1.6/FutureScholars.Paperlib.locale.zh-CN.yaml
  manifests/f/FutureScholars/Paperlib/3.1.6/FutureScholars.Paperlib.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#160785 New version: appmakes.Typora version 1.9.5
  manifests/a/appmakes/Typora/1.9.5/appmakes.Typora.installer.yaml
  manifests/a/appmakes/Typora/1.9.5/appmakes.Typora.locale.en-US.yaml
  manifests/a/appmakes/Typora/1.9.5/appmakes.Typora.locale.zh-CN.yaml
  manifests/a/appmakes/Typora/1.9.5/appmakes.Typora.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160786 New version: DuckStudio.FufuTools version 1.3.3
  manifests/d/DuckStudio/FufuTools/1.3.3/DuckStudio.FufuTools.installer.yaml
  manifests/d/DuckStudio/FufuTools/1.3.3/DuckStudio.FufuTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuTools/1.3.3/DuckStudio.FufuTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160791 New version: BeyondATC.Client version 1.0.48
  manifests/b/BeyondATC/Client/1.0.48/BeyondATC.Client.installer.yaml
  manifests/b/BeyondATC/Client/1.0.48/BeyondATC.Client.locale.en-US.yaml
  manifests/b/BeyondATC/Client/1.0.48/BeyondATC.Client.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160787 Nelson v1.6.0.4208
  manifests/n/NelsonNumericalSoftware/Nelson/1.6.0.4208/NelsonNumericalSoftware.Nelson.installer.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/1.6.0.4208/NelsonNumericalSoftware.Nelson.locale.en-US.yaml
  manifests/n/NelsonNumericalSoftware/Nelson/1.6.0.4208/NelsonNumericalSoftware.Nelson.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160789 New version: Anki.Anki version 24.06.3
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160792 New version: AsciidocFX.AsciidocFX version 1.8.10
  manifests/a/AsciidocFX/AsciidocFX/1.8.10/AsciidocFX.AsciidocFX.installer.yaml
  manifests/a/AsciidocFX/AsciidocFX/1.8.10/AsciidocFX.AsciidocFX.locale.en-US.yaml
  manifests/a/AsciidocFX/AsciidocFX/1.8.10/AsciidocFX.AsciidocFX.locale.zh-CN.yaml
  manifests/a/AsciidocFX/AsciidocFX/1.8.10/AsciidocFX.AsciidocFX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#160759 New package: SoftMaker.FreeOffice.2024 version 1.0.6075
  manifests/s/SoftMaker/FreeOffice/2024/1.0.6075/SoftMaker.FreeOffice.2024.installer.yaml
  manifests/s/SoftMaker/FreeOffice/2024/1.0.6075/SoftMaker.FreeOffice.2024.locale.en-US.yaml
  manifests/s/SoftMaker/FreeOffice/2024/1.0.6075/SoftMaker.FreeOffice.2024.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#160717 Remove version: WiresharkFoundation.Wireshark version 4.2.3
  manifests/w/WiresharkFoundation/Wireshark/4.2.3/WiresharkFoundation.Wireshark.installer.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.3/WiresharkFoundation.Wireshark.locale.en-US.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.3/WiresharkFoundation.Wireshark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160719 Remove version: WiresharkFoundation.Wireshark version 4.2.2
  manifests/w/WiresharkFoundation/Wireshark/4.2.2/WiresharkFoundation.Wireshark.installer.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.2/WiresharkFoundation.Wireshark.locale.en-US.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.2/WiresharkFoundation.Wireshark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#160718 Remove version: WiresharkFoundation.Wireshark version 4.2.4
  manifests/w/WiresharkFoundation/Wireshark/4.2.4/WiresharkFoundation.Wireshark.installer.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.4/WiresharkFoundation.Wireshark.locale.en-US.yaml
  manifests/w/WiresharkFoundation/Wireshark/4.2.4/WiresharkFoundation.Wireshark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#160729 New version: Taozuhong.Kangaroo v5.1.0
  manifests/t/Taozuhong/Kangaroo/5.1.0.240701/Taozuhong.Kangaroo.installer.yaml
  manifests/t/Taozuhong/Kangaroo/5.1.0.240701/Taozuhong.Kangaroo.locale.en-US.yaml
  manifests/t/Taozuhong/Kangaroo/5.1.0.240701/Taozuhong.Kangaroo.locale.zh-CN.yaml
  manifests/t/Taozuhong/Kangaroo/5.1.0.240701/Taozuhong.Kangaroo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
