Repository microsoft/winget-pkgs, pull requests merged in 2024-05, with the labels that each got.

#151698 New version: Google.Chrome.EXE version 124.0.6367.119
  manifests/g/Google/Chrome/EXE/124.0.6367.119/Google.Chrome.EXE.installer.yaml
  manifests/g/Google/Chrome/EXE/124.0.6367.119/Google.Chrome.EXE.locale.en-US.yaml
  manifests/g/Google/Chrome/EXE/124.0.6367.119/Google.Chrome.EXE.locale.nb-NO.yaml
  manifests/g/Google/Chrome/EXE/124.0.6367.119/Google.Chrome.EXE.locale.zh-CN.yaml
  manifests/g/Google/Chrome/EXE/124.0.6367.119/Google.Chrome.EXE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151712 New version: LGUG2Z.komorebi version 0.1.25
  manifests/l/LGUG2Z/komorebi/0.1.25/LGUG2Z.komorebi.installer.yaml
  manifests/l/LGUG2Z/komorebi/0.1.25/LGUG2Z.komorebi.locale.en-US.yaml
  manifests/l/LGUG2Z/komorebi/0.1.25/LGUG2Z.komorebi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151714 New version: ART.ART version 1.21.3
  manifests/a/ART/ART/1.21.3/ART.ART.installer.yaml
  manifests/a/ART/ART/1.21.3/ART.ART.locale.en-US.yaml
  manifests/a/ART/ART/1.21.3/ART.ART.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151715 Remove version: ART.ART version 1.21.0
  manifests/a/ART/ART/1.21.0/ART.ART.installer.yaml
  manifests/a/ART/ART/1.21.0/ART.ART.locale.en-US.yaml
  manifests/a/ART/ART/1.21.0/ART.ART.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151717 Remove version: Giuspen.Cherrytree version 1.0.4.0
  manifests/g/Giuspen/Cherrytree/1.0.4.0/Giuspen.Cherrytree.installer.yaml
  manifests/g/Giuspen/Cherrytree/1.0.4.0/Giuspen.Cherrytree.locale.en-US.yaml
  manifests/g/Giuspen/Cherrytree/1.0.4.0/Giuspen.Cherrytree.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151719 Remove version: RawTherapee.RawTherapee version 5.8
  manifests/r/RawTherapee/RawTherapee/5.8/RawTherapee.RawTherapee.installer.yaml
  manifests/r/RawTherapee/RawTherapee/5.8/RawTherapee.RawTherapee.locale.en-US.yaml
  manifests/r/RawTherapee/RawTherapee/5.8/RawTherapee.RawTherapee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151718 New version: RawTherapee.RawTherapee version 5.10
  manifests/r/RawTherapee/RawTherapee/5.10/RawTherapee.RawTherapee.installer.yaml
  manifests/r/RawTherapee/RawTherapee/5.10/RawTherapee.RawTherapee.locale.en-US.yaml
  manifests/r/RawTherapee/RawTherapee/5.10/RawTherapee.RawTherapee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151720 Remove version: RawTherapee.RawTherapee version 5.9
  manifests/r/RawTherapee/RawTherapee/5.9/RawTherapee.RawTherapee.installer.yaml
  manifests/r/RawTherapee/RawTherapee/5.9/RawTherapee.RawTherapee.locale.en-US.yaml
  manifests/r/RawTherapee/RawTherapee/5.9/RawTherapee.RawTherapee.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151725 Update: ElectronicArts.EADesktop version 13.188.0.5701
  manifests/e/ElectronicArts/EADesktop/13.188.0.5701/ElectronicArts.EADesktop.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151747 New version: electerm.electerm version 1.38.80
  manifests/e/electerm/electerm/1.38.80/electerm.electerm.installer.yaml
  manifests/e/electerm/electerm/1.38.80/electerm.electerm.locale.en-US.yaml
  manifests/e/electerm/electerm/1.38.80/electerm.electerm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151745 New version: Fly-io.flyctl version 0.2.45
  manifests/f/Fly-io/flyctl/0.2.45/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.2.45/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.2.45/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151764 Microsoft.VisualStudioCode.Insiders_v1.89.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.89.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151716 Remove version: ART.ART version 1.21.1
  manifests/a/ART/ART/1.21.1/ART.ART.installer.yaml
  manifests/a/ART/ART/1.21.1/ART.ART.locale.en-US.yaml
  manifests/a/ART/ART/1.21.1/ART.ART.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Attention

#151796 New version: Skrepysh.mineSquid version 3.2
  manifests/s/Skrepysh/mineSquid/3.2/Skrepysh.mineSquid.installer.yaml
  manifests/s/Skrepysh/mineSquid/3.2/Skrepysh.mineSquid.locale.ru-RU.yaml
  manifests/s/Skrepysh/mineSquid/3.2/Skrepysh.mineSquid.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151759 New version: nektos.act version 0.2.62
  manifests/n/nektos/act/0.2.62/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.62/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.62/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151766 Modify: TheBrowserCompany.Arc version 1.0.1.24682
  manifests/t/TheBrowserCompany/Arc/1.0.1.24682/TheBrowserCompany.Arc.installer.yaml
  manifests/t/TheBrowserCompany/Arc/1.0.1.24682/TheBrowserCompany.Arc.locale.en-US.yaml
  manifests/t/TheBrowserCompany/Arc/1.0.1.24682/TheBrowserCompany.Arc.locale.zh-CN.yaml
  manifests/t/TheBrowserCompany/Arc/1.0.1.24682/TheBrowserCompany.Arc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151767 New version: junegunn.fzf version 0.51.0
  manifests/j/junegunn/fzf/0.51.0/junegunn.fzf.installer.yaml
  manifests/j/junegunn/fzf/0.51.0/junegunn.fzf.locale.en-US.yaml
  manifests/j/junegunn/fzf/0.51.0/junegunn.fzf.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151769 New version: Alex313031.Thorium version 123.0.6312.133
  manifests/a/Alex313031/Thorium/123.0.6312.133/Alex313031.Thorium.installer.yaml
  manifests/a/Alex313031/Thorium/123.0.6312.133/Alex313031.Thorium.locale.en-US.yaml
  manifests/a/Alex313031/Thorium/123.0.6312.133/Alex313031.Thorium.locale.zh-CN.yaml
  manifests/a/Alex313031/Thorium/123.0.6312.133/Alex313031.Thorium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#151773 New version: PIKCLOUD.PikPak version 2.4.1 (2.4.1.4218)
  manifests/p/PIKCLOUD/PikPak/2.4.1/PIKCLOUD.PikPak.installer.yaml
  manifests/p/PIKCLOUD/PikPak/2.4.1/PIKCLOUD.PikPak.locale.en-US.yaml
  manifests/p/PIKCLOUD/PikPak/2.4.1/PIKCLOUD.PikPak.locale.zh-CN.yaml
  manifests/p/PIKCLOUD/PikPak/2.4.1/PIKCLOUD.PikPak.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151762 New package: BlueMail.BlueMail version 1.140.28
  manifests/b/BlueMail/BlueMail/1.140.28/BlueMail.BlueMail.installer.yaml
  manifests/b/BlueMail/BlueMail/1.140.28/BlueMail.BlueMail.locale.en-US.yaml
  manifests/b/BlueMail/BlueMail/1.140.28/BlueMail.BlueMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#151779 Modify: WinMerge.WinMerge version 2.16.40
  manifests/w/WinMerge/WinMerge/2.16.40/WinMerge.WinMerge.installer.yaml
  manifests/w/WinMerge/WinMerge/2.16.40/WinMerge.WinMerge.locale.en-US.yaml
  manifests/w/WinMerge/WinMerge/2.16.40/WinMerge.WinMerge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151752 Remove: Zype.Compass version 1.0.0
  manifests/z/Zype/Compass/1.0.0/Zype.Compass.installer.yaml
  manifests/z/Zype/Compass/1.0.0/Zype.Compass.locale.en-US.yaml
  manifests/z/Zype/Compass/1.0.0/Zype.Compass.locale.zh-CN.yaml
  manifests/z/Zype/Compass/1.0.0/Zype.Compass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151782 New version: Sinew.Enpass version 6.10.2.1665
  manifests/s/Sinew/Enpass/6.10.2.1665/Sinew.Enpass.installer.yaml
  manifests/s/Sinew/Enpass/6.10.2.1665/Sinew.Enpass.locale.en-US.yaml
  manifests/s/Sinew/Enpass/6.10.2.1665/Sinew.Enpass.locale.zh-CN.yaml
  manifests/s/Sinew/Enpass/6.10.2.1665/Sinew.Enpass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151783 Modify: WinMerge.WinMerge version 2.16.38
  manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.installer.yaml
  manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.locale.en-US.yaml
  manifests/w/WinMerge/WinMerge/2.16.38/WinMerge.WinMerge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151786 New version: Google.Chrome.Canary version 126.0.6451.0
  manifests/g/Google/Chrome/Canary/126.0.6451.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/126.0.6451.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/126.0.6451.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/126.0.6451.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/126.0.6451.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151799 New package SolidWorks.eDrawings
  manifests/s/SolidWorks/eDrawings/32.20.0065/SolidWorks.eDrawings.installer.yaml
  manifests/s/SolidWorks/eDrawings/32.20.0065/SolidWorks.eDrawings.locale.en-US.yaml
  manifests/s/SolidWorks/eDrawings/32.20.0065/SolidWorks.eDrawings.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#151789 SmartSoft.SmartFTP version 10.0.3226.0
  manifests/s/SmartSoft/SmartFTP/10.0.3226.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3226.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3226.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151795 Update: Everything Cli to es 1.1.0.27
  manifests/v/voidtools/Everything/Cli/1.1.0.27/voidtools.Everything.Cli.installer.yaml
  manifests/v/voidtools/Everything/Cli/1.1.0.27/voidtools.Everything.Cli.locale.en-US.yaml
  manifests/v/voidtools/Everything/Cli/1.1.0.27/voidtools.Everything.Cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#151798 Edit: Everything Cli es 1.1.0.26
  manifests/v/voidtools/Everything/Cli/1.1.0.26/voidtools.Everything.Cli.installer.yaml
  manifests/v/voidtools/Everything/Cli/1.1.0.26/voidtools.Everything.Cli.locale.en-US.yaml
  manifests/v/voidtools/Everything/Cli/1.1.0.26/voidtools.Everything.Cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151746 New version: Balena.BalenaCLI version 18.2.2
  manifests/b/Balena/BalenaCLI/18.2.2/Balena.BalenaCLI.installer.yaml
  manifests/b/Balena/BalenaCLI/18.2.2/Balena.BalenaCLI.locale.en-US.yaml
  manifests/b/Balena/BalenaCLI/18.2.2/Balena.BalenaCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151751 New version: Rem0o.FanControl version 188
  manifests/r/Rem0o/FanControl/188/Rem0o.FanControl.installer.yaml
  manifests/r/Rem0o/FanControl/188/Rem0o.FanControl.locale.en-US.yaml
  manifests/r/Rem0o/FanControl/188/Rem0o.FanControl.locale.zh-CN.yaml
  manifests/r/Rem0o/FanControl/188/Rem0o.FanControl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151801 [metadata]: GodotEngine.GodotEngine version 2.1
  manifests/g/GodotEngine/GodotEngine/2.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151810 [metadata]: GodotEngine.GodotEngine version 3.0
  manifests/g/GodotEngine/GodotEngine/3.0/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Version-Parameter-Mismatch

#151811 [metadata]: GodotEngine.GodotEngine version 3.0.1
  manifests/g/GodotEngine/GodotEngine/3.0.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151813 [metadata]: GodotEngine.GodotEngine version 3.0.3
  manifests/g/GodotEngine/GodotEngine/3.0.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151812 [metadata]: GodotEngine.GodotEngine version 3.0.2
  manifests/g/GodotEngine/GodotEngine/3.0.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151814 [metadata]: GodotEngine.GodotEngine version 3.0.4
  manifests/g/GodotEngine/GodotEngine/3.0.4/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.4/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151815 [metadata]: GodotEngine.GodotEngine version 3.0.5
  manifests/g/GodotEngine/GodotEngine/3.0.5/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.5/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151817 [metadata]: GodotEngine.GodotEngine version 3.1
  manifests/g/GodotEngine/GodotEngine/3.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151818 [metadata]: GodotEngine.GodotEngine version 3.1.1
  manifests/g/GodotEngine/GodotEngine/3.1.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151820 [metadata]: GodotEngine.GodotEngine version 3.2
  manifests/g/GodotEngine/GodotEngine/3.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151816 [metadata]: GodotEngine.GodotEngine version 3.0.6
  manifests/g/GodotEngine/GodotEngine/3.0.6/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.0.6/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151822 [metadata]: GodotEngine.GodotEngine version 3.2.2
  manifests/g/GodotEngine/GodotEngine/3.2.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.2.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151823 [metadata]: GodotEngine.GodotEngine version 3.2.3
  manifests/g/GodotEngine/GodotEngine/3.2.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.2.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151821 [metadata]: GodotEngine.GodotEngine version 3.2.1
  manifests/g/GodotEngine/GodotEngine/3.2.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.2.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151825 [metadata]: GodotEngine.GodotEngine version 3.3
  manifests/g/GodotEngine/GodotEngine/3.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151830 [metadata]: GodotEngine.GodotEngine version 3.4
  manifests/g/GodotEngine/GodotEngine/3.4/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151826 [metadata]: GodotEngine.GodotEngine version 3.3.1
  manifests/g/GodotEngine/GodotEngine/3.3.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.3.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151828 [metadata]: GodotEngine.GodotEngine version 3.3.3
  manifests/g/GodotEngine/GodotEngine/3.3.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.3.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151819 [metadata]: GodotEngine.GodotEngine version 3.1.2
  manifests/g/GodotEngine/GodotEngine/3.1.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.1.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151831 [metadata]: GodotEngine.GodotEngine version 3.4.1
  manifests/g/GodotEngine/GodotEngine/3.4.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151829 [metadata]: GodotEngine.GodotEngine version 3.3.4
  manifests/g/GodotEngine/GodotEngine/3.3.4/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.3.4/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151833 [metadata]: GodotEngine.GodotEngine version 3.4.3
  manifests/g/GodotEngine/GodotEngine/3.4.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151832 [metadata]: GodotEngine.GodotEngine version 3.4.2
  manifests/g/GodotEngine/GodotEngine/3.4.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151835 [metadata]: GodotEngine.GodotEngine version 3.4.5
  manifests/g/GodotEngine/GodotEngine/3.4.5/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4.5/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151842 [metadata]: GodotEngine.GodotEngine version 4.0.2
  manifests/g/GodotEngine/GodotEngine/4.0.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/4.0.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151841 [metadata]: GodotEngine.GodotEngine version 4.0.1
  manifests/g/GodotEngine/GodotEngine/4.0.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/4.0.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151838 [metadata]: GodotEngine.GodotEngine version 3.5.2
  manifests/g/GodotEngine/GodotEngine/3.5.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.5.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151840 [metadata]: GodotEngine.GodotEngine version 4.0
  manifests/g/GodotEngine/GodotEngine/4.0/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/4.0/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151837 [metadata]: GodotEngine.GodotEngine version 3.5.1
  manifests/g/GodotEngine/GodotEngine/3.5.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.5.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151802 [metadata]: GodotEngine.GodotEngine version 2.1.1
  manifests/g/GodotEngine/GodotEngine/2.1.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151806 [metadata]: GodotEngine.GodotEngine version 2.1.5
  manifests/g/GodotEngine/GodotEngine/2.1.5/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.5/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151804 [metadata]: GodotEngine.GodotEngine version 2.1.3
  manifests/g/GodotEngine/GodotEngine/2.1.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151803 [metadata]: GodotEngine.GodotEngine version 2.1.2
  manifests/g/GodotEngine/GodotEngine/2.1.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151834 [metadata]: GodotEngine.GodotEngine version 3.4.4
  manifests/g/GodotEngine/GodotEngine/3.4.4/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.4.4/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151808 [metadata]: GodotEngine.GodotEngine version 2.1.6
  manifests/g/GodotEngine/GodotEngine/2.1.6/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.6/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151805 [metadata]: GodotEngine.GodotEngine version 2.1.4
  manifests/g/GodotEngine/GodotEngine/2.1.4/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.1.4/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151721 New version: LGUG2Z.komokana version 0.1.4
  manifests/l/LGUG2Z/komokana/0.1.4/LGUG2Z.komokana.installer.yaml
  manifests/l/LGUG2Z/komokana/0.1.4/LGUG2Z.komokana.locale.en-US.yaml
  manifests/l/LGUG2Z/komokana/0.1.4/LGUG2Z.komokana.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151743 New package: srevinsaju.guiscrcpy.PySide2 version 2023.01.01
  manifests/s/srevinsaju/guiscrcpy/PySide2/2023.01.01/srevinsaju.guiscrcpy.PySide2.installer.yaml
  manifests/s/srevinsaju/guiscrcpy/PySide2/2023.01.01/srevinsaju.guiscrcpy.PySide2.locale.en-US.yaml
  manifests/s/srevinsaju/guiscrcpy/PySide2/2023.01.01/srevinsaju.guiscrcpy.PySide2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#151765 Microsoft.VisualStudioCode.Insiders.CLI_v1.89.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.89.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151807 New version: Grammarly.Grammarly version 1.2.75.1386
  manifests/g/Grammarly/Grammarly/1.2.75.1386/Grammarly.Grammarly.installer.yaml
  manifests/g/Grammarly/Grammarly/1.2.75.1386/Grammarly.Grammarly.locale.en-US.yaml
  manifests/g/Grammarly/Grammarly/1.2.75.1386/Grammarly.Grammarly.locale.zh-CN.yaml
  manifests/g/Grammarly/Grammarly/1.2.75.1386/Grammarly.Grammarly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest, Manifest-Metadata-Consistency

#151768 New version: OpenTofu.Tofu version 1.7.0
  manifests/o/OpenTofu/Tofu/1.7.0/OpenTofu.Tofu.installer.yaml
  manifests/o/OpenTofu/Tofu/1.7.0/OpenTofu.Tofu.locale.en-US.yaml
  manifests/o/OpenTofu/Tofu/1.7.0/OpenTofu.Tofu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151845 [metadata]: GodotEngine.GodotEngine version 4.0.3
  manifests/g/GodotEngine/GodotEngine/4.0.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Manifest-Version-Deprecated

#151741 New package: srevinsaju.guiscrcpy.PyQt5 version 2023.01.01
  manifests/s/srevinsaju/guiscrcpy/PyQt5/2023.01.01/srevinsaju.guiscrcpy.PyQt5.installer.yaml
  manifests/s/srevinsaju/guiscrcpy/PyQt5/2023.01.01/srevinsaju.guiscrcpy.PyQt5.locale.en-US.yaml
  manifests/s/srevinsaju/guiscrcpy/PyQt5/2023.01.01/srevinsaju.guiscrcpy.PyQt5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Attention, New-Package

#151703 LMStudio.LMStudio version 0.2.21
  manifests/l/LMStudio/LMStudio/0.2.21/LMStudio.LMStudio.installer.yaml
  manifests/l/LMStudio/LMStudio/0.2.21/LMStudio.LMStudio.locale.en-US.yaml
  manifests/l/LMStudio/LMStudio/0.2.21/LMStudio.LMStudio.yaml
Labels: Validation-Completed

#148219 New version: Microsoft.VisualStudio.2022.Community version 17.9.5
  manifests/m/Microsoft/VisualStudio/2022/Community/17.9.5/Microsoft.VisualStudio.2022.Community.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/17.9.5/Microsoft.VisualStudio.2022.Community.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/17.9.5/Microsoft.VisualStudio.2022.Community.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Needs-Review, New-Manifest

#151839 [metadata]: GodotEngine.GodotEngine version 3.5.3
  manifests/g/GodotEngine/GodotEngine/3.5.3/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.5.3/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151836 [metadata]: GodotEngine.GodotEngine version 3.5
  manifests/g/GodotEngine/GodotEngine/3.5/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/3.5/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151850 [metadata]: GodotEngine.GodotEngine version 4.1.2
  manifests/g/GodotEngine/GodotEngine/4.1.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151852 [metadata]: GodotEngine.GodotEngine version 4.2
  manifests/g/GodotEngine/GodotEngine/4.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151861 [metadata]: GodotEngine.GodotEngine.Mono version 4.2.2
  manifests/g/GodotEngine/GodotEngine/Mono/4.2.2/GodotEngine.GodotEngine.Mono.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151860 [metadata]: GodotEngine.GodotEngine.Mono version 4.2.1
  manifests/g/GodotEngine/GodotEngine/Mono/4.2.1/GodotEngine.GodotEngine.Mono.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151854 [metadata]: GodotEngine.GodotEngine version 4.2.2
  manifests/g/GodotEngine/GodotEngine/4.2.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151853 [metadata]: GodotEngine.GodotEngine version 4.2.1
  manifests/g/GodotEngine/GodotEngine/4.2.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151824 New version: WHONET.WHONET version 23.17.1
  manifests/w/WHONET/WHONET/23.17.1/WHONET.WHONET.installer.yaml
  manifests/w/WHONET/WHONET/23.17.1/WHONET.WHONET.locale.en-US.yaml
  manifests/w/WHONET/WHONET/23.17.1/WHONET.WHONET.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151862 [metadata]: GodotEngine.GodotEngine version 2.0
  manifests/g/GodotEngine/GodotEngine/2.0/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151863 [metadata]: GodotEngine.GodotEngine version 2.0.1
  manifests/g/GodotEngine/GodotEngine/2.0.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151864 [metadata]: GodotEngine.GodotEngine version 2.0.2
  manifests/g/GodotEngine/GodotEngine/2.0.2/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.2/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151844 New version: filips.FirefoxPWA version 2.12.0
  manifests/f/filips/FirefoxPWA/2.12.0/filips.FirefoxPWA.installer.yaml
  manifests/f/filips/FirefoxPWA/2.12.0/filips.FirefoxPWA.locale.en-US.yaml
  manifests/f/filips/FirefoxPWA/2.12.0/filips.FirefoxPWA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151871 New version: Ryujinx.Ryujinx.Ava version 1.1.1296
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1296/Ryujinx.Ryujinx.Ava.installer.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1296/Ryujinx.Ryujinx.Ava.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1296/Ryujinx.Ryujinx.Ava.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151870 New version: Ryujinx.Ryujinx version 1.1.1296
  manifests/r/Ryujinx/Ryujinx/1.1.1296/Ryujinx.Ryujinx.installer.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1296/Ryujinx.Ryujinx.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1296/Ryujinx.Ryujinx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151781 New version: Discord.Discord version 1.0.9144
  manifests/d/Discord/Discord/1.0.9144/Discord.Discord.installer.yaml
  manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.en-US.yaml
  manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.pt-BR.yaml
  manifests/d/Discord/Discord/1.0.9144/Discord.Discord.locale.zh-CN.yaml
  manifests/d/Discord/Discord/1.0.9144/Discord.Discord.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151843 New version: aislx.FlameLauncher version 1.0.6
  manifests/a/aislx/FlameLauncher/1.0.6/aislx.FlameLauncher.installer.yaml
  manifests/a/aislx/FlameLauncher/1.0.6/aislx.FlameLauncher.locale.en-US.yaml
  manifests/a/aislx/FlameLauncher/1.0.6/aislx.FlameLauncher.yaml
Labels: Validation-Completed, Moderator-Approved

#151881 Update version: MongoDB.MongoDBAtlasCLI version 1.22.0
  manifests/m/MongoDB/MongoDBAtlasCLI/1.22.0/MongoDB.MongoDBAtlasCLI.installer.yaml
  manifests/m/MongoDB/MongoDBAtlasCLI/1.22.0/MongoDB.MongoDBAtlasCLI.locale.en-US.yaml
  manifests/m/MongoDB/MongoDBAtlasCLI/1.22.0/MongoDB.MongoDBAtlasCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151882 New version: UniversalMediaServer.UniversalMediaServer version 13.10.0
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.10.0/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.10.0/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/13.10.0/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151887 New version: taers232c.GAMADV-XTD3 version 6.75.02
  manifests/t/taers232c/GAMADV-XTD3/6.75.02/taers232c.GAMADV-XTD3.installer.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.75.02/taers232c.GAMADV-XTD3.locale.en-US.yaml
  manifests/t/taers232c/GAMADV-XTD3/6.75.02/taers232c.GAMADV-XTD3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151896 New version: Google.Chrome.Canary version 126.0.6452.0
  manifests/g/Google/Chrome/Canary/126.0.6452.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/126.0.6452.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/126.0.6452.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/126.0.6452.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/126.0.6452.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151898 Update Adobe.Acrobat.Pro.installer.yaml
  manifests/a/Adobe/Acrobat/Pro/24.002.20687/Adobe.Acrobat.Pro.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151900 SmartSoft.SmartFTP version 10.0.3227.0
  manifests/s/SmartSoft/SmartFTP/10.0.3227.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3227.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3227.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151906 New version: Sidero.talosctl version 1.7.1
  manifests/s/Sidero/talosctl/1.7.1/Sidero.talosctl.installer.yaml
  manifests/s/Sidero/talosctl/1.7.1/Sidero.talosctl.locale.en-US.yaml
  manifests/s/Sidero/talosctl/1.7.1/Sidero.talosctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151904 New version: Posit.Quarto version 1.4.554
  manifests/p/Posit/Quarto/1.4.554/Posit.Quarto.installer.yaml
  manifests/p/Posit/Quarto/1.4.554/Posit.Quarto.locale.en-US.yaml
  manifests/p/Posit/Quarto/1.4.554/Posit.Quarto.locale.zh-CN.yaml
  manifests/p/Posit/Quarto/1.4.554/Posit.Quarto.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#149483 Microsoft.VisualStudio.2022.Professional.Preview version 17.10.0
  manifests/m/Microsoft/VisualStudio/2022/Professional/Preview/17.10.0/Microsoft.VisualStudio.2022.Professional.Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/Preview/17.10.0/Microsoft.VisualStudio.2022.Professional.Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Professional/Preview/17.10.0/Microsoft.VisualStudio.2022.Professional.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#149484 Microsoft.VisualStudio.2022.Community.Preview version 17.10.0
  manifests/m/Microsoft/VisualStudio/2022/Community/Preview/17.10.0/Microsoft.VisualStudio.2022.Community.Preview.installer.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/Preview/17.10.0/Microsoft.VisualStudio.2022.Community.Preview.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudio/2022/Community/Preview/17.10.0/Microsoft.VisualStudio.2022.Community.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151724 New version: NewReleases.NewReleasesCLI version 0.1.16
  manifests/n/NewReleases/NewReleasesCLI/0.1.16/NewReleases.NewReleasesCLI.installer.yaml
  manifests/n/NewReleases/NewReleasesCLI/0.1.16/NewReleases.NewReleasesCLI.locale.en-US.yaml
  manifests/n/NewReleases/NewReleasesCLI/0.1.16/NewReleases.NewReleasesCLI.locale.zh-CN.yaml
  manifests/n/NewReleases/NewReleasesCLI/0.1.16/NewReleases.NewReleasesCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151729 New version: Nushell.Nushell version 0.93.0
  manifests/n/Nushell/Nushell/0.93.0/Nushell.Nushell.installer.yaml
  manifests/n/Nushell/Nushell/0.93.0/Nushell.Nushell.locale.en-US.yaml
  manifests/n/Nushell/Nushell/0.93.0/Nushell.Nushell.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151846 Update aislx.FlameLauncher.locale.en-US.yaml
  manifests/a/aislx/FlameLauncher/1.0.4/aislx.FlameLauncher.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#151866 New version: Sandboxie.Classic version 5.68.7
  manifests/s/Sandboxie/Classic/5.68.7/Sandboxie.Classic.installer.yaml
  manifests/s/Sandboxie/Classic/5.68.7/Sandboxie.Classic.locale.en-US.yaml
  manifests/s/Sandboxie/Classic/5.68.7/Sandboxie.Classic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151868 [metadata]: GodotEngine.GodotEngine version 2.0.4.1
  manifests/g/GodotEngine/GodotEngine/2.0.4.1/GodotEngine.GodotEngine.installer.yaml
  manifests/g/GodotEngine/GodotEngine/2.0.4.1/GodotEngine.GodotEngine.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151869 New version: Mozilla.Thunderbird version 115.10.2
  manifests/m/Mozilla/Thunderbird/115.10.2/Mozilla.Thunderbird.installer.yaml
  manifests/m/Mozilla/Thunderbird/115.10.2/Mozilla.Thunderbird.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/115.10.2/Mozilla.Thunderbird.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/115.10.2/Mozilla.Thunderbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#151872 New version: Hugo.Hugo.Extended version 0.125.5
  manifests/h/Hugo/Hugo/Extended/0.125.5/Hugo.Hugo.Extended.installer.yaml
  manifests/h/Hugo/Hugo/Extended/0.125.5/Hugo.Hugo.Extended.locale.en-US.yaml
  manifests/h/Hugo/Hugo/Extended/0.125.5/Hugo.Hugo.Extended.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/Extended/0.125.5/Hugo.Hugo.Extended.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151873 New version: Hugo.Hugo version 0.125.5
  manifests/h/Hugo/Hugo/0.125.5/Hugo.Hugo.installer.yaml
  manifests/h/Hugo/Hugo/0.125.5/Hugo.Hugo.locale.en-US.yaml
  manifests/h/Hugo/Hugo/0.125.5/Hugo.Hugo.locale.zh-CN.yaml
  manifests/h/Hugo/Hugo/0.125.5/Hugo.Hugo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151874 New version: Microsoft.RemoteDesktopClient version 1.2.5405.0
  manifests/m/Microsoft/RemoteDesktopClient/1.2.5405.0/Microsoft.RemoteDesktopClient.installer.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.5405.0/Microsoft.RemoteDesktopClient.locale.en-US.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.5405.0/Microsoft.RemoteDesktopClient.locale.zh-CN.yaml
  manifests/m/Microsoft/RemoteDesktopClient/1.2.5405.0/Microsoft.RemoteDesktopClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151876 New version: Brave.Brave version 124.1.65.126
  manifests/b/Brave/Brave/124.1.65.126/Brave.Brave.installer.yaml
  manifests/b/Brave/Brave/124.1.65.126/Brave.Brave.locale.en-US.yaml
  manifests/b/Brave/Brave/124.1.65.126/Brave.Brave.locale.zh-CN.yaml
  manifests/b/Brave/Brave/124.1.65.126/Brave.Brave.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151877 New version: Figma.FigmaAgent version 116.18.6
  manifests/f/Figma/FigmaAgent/116.18.6/Figma.FigmaAgent.installer.yaml
  manifests/f/Figma/FigmaAgent/116.18.6/Figma.FigmaAgent.locale.en-US.yaml
  manifests/f/Figma/FigmaAgent/116.18.6/Figma.FigmaAgent.locale.zh-CN.yaml
  manifests/f/Figma/FigmaAgent/116.18.6/Figma.FigmaAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151875 Update: Mozilla.Firefox.DeveloperEdition version 126.0 (126.0b8)
  manifests/m/Mozilla/Firefox/DeveloperEdition/126.0/Mozilla.Firefox.DeveloperEdition.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151879 New version: solemnwarning.rehex version 0.61.1
  manifests/s/solemnwarning/rehex/0.61.1/solemnwarning.rehex.installer.yaml
  manifests/s/solemnwarning/rehex/0.61.1/solemnwarning.rehex.locale.en-US.yaml
  manifests/s/solemnwarning/rehex/0.61.1/solemnwarning.rehex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151481 New package: gif.ski version 1.14.4
  manifests/i/ImageOptim/gifski/1.14.4/ImageOptim.gifski.installer.yaml
  manifests/i/ImageOptim/gifski/1.14.4/ImageOptim.gifski.locale.en-US.yaml
  manifests/i/ImageOptim/gifski/1.14.4/ImageOptim.gifski.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Package

#151787 Update version: RoyalApps.RoyalTS.V7 version 7.02.50424.0
  manifests/r/RoyalApps/RoyalTS/V7/7.02.50424.0/RoyalApps.RoyalTS.V7.installer.yaml
  manifests/r/RoyalApps/RoyalTS/V7/7.02.50424.0/RoyalApps.RoyalTS.V7.locale.en-US.yaml
  manifests/r/RoyalApps/RoyalTS/V7/7.02.50424.0/RoyalApps.RoyalTS.V7.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, New-Manifest

#151914 New version: Google.AndroidStudio.Canary version 2024.1.1.5
  manifests/g/Google/AndroidStudio/Canary/2024.1.1.5/Google.AndroidStudio.Canary.installer.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.1.5/Google.AndroidStudio.Canary.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/Canary/2024.1.1.5/Google.AndroidStudio.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#151921 New version: gaphor.gaphor 2.25.1
  manifests/g/gaphor/gaphor/2.25.1/gaphor.gaphor.installer.yaml
  manifests/g/gaphor/gaphor/2.25.1/gaphor.gaphor.locale.en-US.yaml
  manifests/g/gaphor/gaphor/2.25.1/gaphor.gaphor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151922 New version: Piriform.CCleaner.ProTrial version 6.22
  manifests/p/Piriform/CCleaner/ProTrial/6.22/Piriform.CCleaner.ProTrial.installer.yaml
  manifests/p/Piriform/CCleaner/ProTrial/6.22/Piriform.CCleaner.ProTrial.locale.en-US.yaml
  manifests/p/Piriform/CCleaner/ProTrial/6.22/Piriform.CCleaner.ProTrial.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, New-Manifest

#151923 Modify: Piriform.CCleaner.ProTrial version 6.23
  manifests/p/Piriform/CCleaner/ProTrial/6.23/Piriform.CCleaner.ProTrial.installer.yaml
  manifests/p/Piriform/CCleaner/ProTrial/6.23/Piriform.CCleaner.ProTrial.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback

#150730 SpikeHD.swerve version 1.2.0
  manifests/s/SpikeHD/swerve/1.2.0/SpikeHD.swerve.installer.yaml
  manifests/s/SpikeHD/swerve/1.2.0/SpikeHD.swerve.locale.en-US.yaml
  manifests/s/SpikeHD/swerve/1.2.0/SpikeHD.swerve.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#151925 New version: Jackett.Jackett version 0.21.2526
  manifests/j/Jackett/Jackett/0.21.2526/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.21.2526/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.21.2526/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151928 New version: Hashicorp.Terraform.Alpha version 1.9.0-alpha20240501
  manifests/h/Hashicorp/Terraform/Alpha/1.9.0-alpha20240501/Hashicorp.Terraform.Alpha.installer.yaml
  manifests/h/Hashicorp/Terraform/Alpha/1.9.0-alpha20240501/Hashicorp.Terraform.Alpha.locale.en-US.yaml
  manifests/h/Hashicorp/Terraform/Alpha/1.9.0-alpha20240501/Hashicorp.Terraform.Alpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151930 New version: Evernote.Evernote version 10.86.8
  manifests/e/Evernote/Evernote/10.86.8/Evernote.Evernote.installer.yaml
  manifests/e/Evernote/Evernote/10.86.8/Evernote.Evernote.locale.en-US.yaml
  manifests/e/Evernote/Evernote/10.86.8/Evernote.Evernote.locale.zh-CN.yaml
  manifests/e/Evernote/Evernote/10.86.8/Evernote.Evernote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151931 New version: Fort.Firewall version 3.12.6
  manifests/f/Fort/Firewall/3.12.6/Fort.Firewall.installer.yaml
  manifests/f/Fort/Firewall/3.12.6/Fort.Firewall.locale.en-US.yaml
  manifests/f/Fort/Firewall/3.12.6/Fort.Firewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151936 New Version: Telegram.TelegramDesktop version 5.0.0
  manifests/t/Telegram/TelegramDesktop/5.0.0/Telegram.TelegramDesktop.installer.yaml
  manifests/t/Telegram/TelegramDesktop/5.0.0/Telegram.TelegramDesktop.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/5.0.0/Telegram.TelegramDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151933 TreeSize v9.1.4
  manifests/j/JAMSoftware/TreeSize/9.1.4/JAMSoftware.TreeSize.installer.yaml
  manifests/j/JAMSoftware/TreeSize/9.1.4/JAMSoftware.TreeSize.locale.en-US.yaml
  manifests/j/JAMSoftware/TreeSize/9.1.4/JAMSoftware.TreeSize.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151937 Add AGSProjectTeam.AdventureGameStudio 3.6.1.24
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.1.24/AGSProjectTeam.AdventureGameStudio.installer.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.1.24/AGSProjectTeam.AdventureGameStudio.locale.en-US.yaml
  manifests/a/AGSProjectTeam/AdventureGameStudio/3.6.1.24/AGSProjectTeam.AdventureGameStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151938 New version: Ryujinx.Ryujinx.Ava version 1.1.1297
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1297/Ryujinx.Ryujinx.Ava.installer.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1297/Ryujinx.Ryujinx.Ava.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1297/Ryujinx.Ryujinx.Ava.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151939 New version: Ryujinx.Ryujinx version 1.1.1297
  manifests/r/Ryujinx/Ryujinx/1.1.1297/Ryujinx.Ryujinx.installer.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1297/Ryujinx.Ryujinx.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1297/Ryujinx.Ryujinx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151934 New version: JetBrains.FleetLauncher.Preview version 1.34.94
  manifests/j/JetBrains/FleetLauncher/Preview/1.34.94/JetBrains.FleetLauncher.Preview.installer.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.34.94/JetBrains.FleetLauncher.Preview.locale.en-US.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.34.94/JetBrains.FleetLauncher.Preview.locale.zh-CN.yaml
  manifests/j/JetBrains/FleetLauncher/Preview/1.34.94/JetBrains.FleetLauncher.Preview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151800 New version: Unity.Unity.2022 version 2022.3.27f1
  manifests/u/Unity/Unity/2022/2022.3.27f1/Unity.Unity.2022.installer.yaml
  manifests/u/Unity/Unity/2022/2022.3.27f1/Unity.Unity.2022.locale.en-US.yaml
  manifests/u/Unity/Unity/2022/2022.3.27f1/Unity.Unity.2022.locale.zh-CN.yaml
  manifests/u/Unity/Unity/2022/2022.3.27f1/Unity.Unity.2022.yaml
Labels: Validation-Completed, Retry-1

#151955 Removed Files: Victora.HDD-SSD
  manifests/v/Victora/HDD-SSD/5.37/Victora.HDD-SSD.installer.yaml
  manifests/v/Victora/HDD-SSD/5.37/Victora.HDD-SSD.locale.en-US.yaml
  manifests/v/Victora/HDD-SSD/5.37/Victora.HDD-SSD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Highest-Version-Remaining

#151949 Microsoft.DotNet.Framework.DeveloperPack_4: Treat codes 1641 & 3010 as success
  manifests/m/Microsoft/DotNet/Framework/DeveloperPack_4/4.8.1/Microsoft.DotNet.Framework.DeveloperPack_4.installer.yaml
  manifests/m/Microsoft/DotNet/Framework/DeveloperPack_4/4.8.1/Microsoft.DotNet.Framework.DeveloperPack_4.locale.en-US.yaml
  manifests/m/Microsoft/DotNet/Framework/DeveloperPack_4/4.8.1/Microsoft.DotNet.Framework.DeveloperPack_4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Review

#151952 feat(permission): Cancel the requirement of Neovim.Neovim.Nightly
  Tools/Auth.csv
Labels: Project-File, Needs-Attention

#151927 New package: kelteseth.ScreenPlay.Beta version 0.15.1-beta1
  manifests/k/kelteseth/ScreenPlay/Beta/0.15.1-beta1/kelteseth.ScreenPlay.Beta.installer.yaml
  manifests/k/kelteseth/ScreenPlay/Beta/0.15.1-beta1/kelteseth.ScreenPlay.Beta.locale.en-US.yaml
  manifests/k/kelteseth/ScreenPlay/Beta/0.15.1-beta1/kelteseth.ScreenPlay.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#151970 New Package: Victoria.Victoria
  manifests/v/Victoria/Victoria/5.37/Victoria.Victoria.installer.yaml
  manifests/v/Victoria/Victoria/5.37/Victoria.Victoria.locale.en-US.yaml
  manifests/v/Victoria/Victoria/5.37/Victoria.Victoria.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#151973 Microsoft.VisualStudioCode.CLI_v1.89.0 cli
  manifests/m/Microsoft/VisualStudioCode/CLI/1.89.0/Microsoft.VisualStudioCode.CLI.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/CLI/1.89.0/Microsoft.VisualStudioCode.CLI.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/CLI/1.89.0/Microsoft.VisualStudioCode.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#151978 Microsoft.VisualStudioCode.Insiders.CLI_v1.90.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.90.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.90.0/Microsoft.VisualStudioCode.Insiders.CLI.locale.en-US.yaml
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.90.0/Microsoft.VisualStudioCode.Insiders.CLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151536 n0-computer.sendme version 0.6.0
  manifests/n/n0-computer/sendme/0.6.0/n0-computer.sendme.installer.yaml
  manifests/n/n0-computer/sendme/0.6.0/n0-computer.sendme.locale.en-US.yaml
  manifests/n/n0-computer/sendme/0.6.0/n0-computer.sendme.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151944 New version: Anydo.Anydo version 5.0.69
  manifests/a/Anydo/Anydo/5.0.69/Anydo.Anydo.installer.yaml
  manifests/a/Anydo/Anydo/5.0.69/Anydo.Anydo.locale.en-US.yaml
  manifests/a/Anydo/Anydo/5.0.69/Anydo.Anydo.locale.zh-CN.yaml
  manifests/a/Anydo/Anydo/5.0.69/Anydo.Anydo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151946 Add MongoDB.Compass.Full 1.43.0.0
  manifests/m/MongoDB/Compass/Full/1.43.0.0/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.43.0.0/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.43.0.0/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151948 Add MongoDB.Compass.Readonly 1.43.0.0
  manifests/m/MongoDB/Compass/Readonly/1.43.0.0/MongoDB.Compass.Readonly.installer.yaml
  manifests/m/MongoDB/Compass/Readonly/1.43.0.0/MongoDB.Compass.Readonly.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Readonly/1.43.0.0/MongoDB.Compass.Readonly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151947 Add MongoDB.Compass.Isolated 1.43.0.0
  manifests/m/MongoDB/Compass/Isolated/1.43.0.0/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.43.0.0/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.43.0.0/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151951 New version: Elsevier.MendeleyReferenceManager version 2.114.0
  manifests/e/Elsevier/MendeleyReferenceManager/2.114.0/Elsevier.MendeleyReferenceManager.installer.yaml
  manifests/e/Elsevier/MendeleyReferenceManager/2.114.0/Elsevier.MendeleyReferenceManager.locale.en-US.yaml
  manifests/e/Elsevier/MendeleyReferenceManager/2.114.0/Elsevier.MendeleyReferenceManager.locale.zh-CN.yaml
  manifests/e/Elsevier/MendeleyReferenceManager/2.114.0/Elsevier.MendeleyReferenceManager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151954 Remove version: Datronicsoft.SpacedeskDriver.Server version 2.1.15.0
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.15.0/Datronicsoft.SpacedeskDriver.Server.installer.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.15.0/Datronicsoft.SpacedeskDriver.Server.locale.en-US.yaml
  manifests/d/Datronicsoft/SpacedeskDriver/Server/2.1.15.0/Datronicsoft.SpacedeskDriver.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#151953 New version: Hibbiki.Chromium version 124.0.6367.119
  manifests/h/Hibbiki/Chromium/124.0.6367.119/Hibbiki.Chromium.installer.yaml
  manifests/h/Hibbiki/Chromium/124.0.6367.119/Hibbiki.Chromium.locale.en-US.yaml
  manifests/h/Hibbiki/Chromium/124.0.6367.119/Hibbiki.Chromium.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#151958 New version: YoYoGames.GameMaker.Studio.2 version 2024.4.0.137
  manifests/y/YoYoGames/GameMaker/Studio/2/2024.4.0.137/YoYoGames.GameMaker.Studio.2.installer.yaml
  manifests/y/YoYoGames/GameMaker/Studio/2/2024.4.0.137/YoYoGames.GameMaker.Studio.2.locale.en-US.yaml
  manifests/y/YoYoGames/GameMaker/Studio/2/2024.4.0.137/YoYoGames.GameMaker.Studio.2.locale.zh-CN.yaml
  manifests/y/YoYoGames/GameMaker/Studio/2/2024.4.0.137/YoYoGames.GameMaker.Studio.2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
