Repository microsoft/winget-pkgs, pull requests merged in 2024-10, with the labels that each got.

#175394 New version: AmN.yasb version 1.2.4
  manifests/a/AmN/yasb/1.2.4/AmN.yasb.installer.yaml
  manifests/a/AmN/yasb/1.2.4/AmN.yasb.locale.en-US.yaml
  manifests/a/AmN/yasb/1.2.4/AmN.yasb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175869 New version: OpenMedia.4KYoutubetoMP3 version 5.6.1.133
  manifests/o/OpenMedia/4KYoutubetoMP3/5.6.1.133/OpenMedia.4KYoutubetoMP3.installer.yaml
  manifests/o/OpenMedia/4KYoutubetoMP3/5.6.1.133/OpenMedia.4KYoutubetoMP3.locale.en-US.yaml
  manifests/o/OpenMedia/4KYoutubetoMP3/5.6.1.133/OpenMedia.4KYoutubetoMP3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#175899 New version: Discord.Discord version 1.0.9165
  manifests/d/Discord/Discord/1.0.9165/Discord.Discord.installer.yaml
  manifests/d/Discord/Discord/1.0.9165/Discord.Discord.locale.en-US.yaml
  manifests/d/Discord/Discord/1.0.9165/Discord.Discord.locale.pt-BR.yaml
  manifests/d/Discord/Discord/1.0.9165/Discord.Discord.locale.zh-CN.yaml
  manifests/d/Discord/Discord/1.0.9165/Discord.Discord.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175898 Update: Posit.Positron version 2024.09.0 (2024.09.0-103)
  manifests/p/Posit/Positron/2024.09.0/Posit.Positron.installer.yaml
  manifests/p/Posit/Positron/2024.09.0/Posit.Positron.locale.en-US.yaml
  manifests/p/Posit/Positron/2024.09.0/Posit.Positron.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175901 New version: ElementLabs.LMStudio version 0.3.3
  manifests/e/ElementLabs/LMStudio/0.3.3/ElementLabs.LMStudio.installer.yaml
  manifests/e/ElementLabs/LMStudio/0.3.3/ElementLabs.LMStudio.locale.en-US.yaml
  manifests/e/ElementLabs/LMStudio/0.3.3/ElementLabs.LMStudio.locale.zh-CN.yaml
  manifests/e/ElementLabs/LMStudio/0.3.3/ElementLabs.LMStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#175900 New version: Microsoft.Edge.Beta version 130.0.2849.13
  manifests/m/Microsoft/Edge/Beta/130.0.2849.13/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/130.0.2849.13/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/130.0.2849.13/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175904 New version: stnkl.EverythingToolbar version 1.5.1
  manifests/s/stnkl/EverythingToolbar/1.5.1/stnkl.EverythingToolbar.installer.yaml
  manifests/s/stnkl/EverythingToolbar/1.5.1/stnkl.EverythingToolbar.locale.en-US.yaml
  manifests/s/stnkl/EverythingToolbar/1.5.1/stnkl.EverythingToolbar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175905 New version: stnkl.EverythingToolbar.Beta version 1.5.1
  manifests/s/stnkl/EverythingToolbar/Beta/1.5.1/stnkl.EverythingToolbar.Beta.installer.yaml
  manifests/s/stnkl/EverythingToolbar/Beta/1.5.1/stnkl.EverythingToolbar.Beta.locale.en-US.yaml
  manifests/s/stnkl/EverythingToolbar/Beta/1.5.1/stnkl.EverythingToolbar.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175906 New version: Discord.Discord.Canary version 1.0.455
  manifests/d/Discord/Discord/Canary/1.0.455/Discord.Discord.Canary.installer.yaml
  manifests/d/Discord/Discord/Canary/1.0.455/Discord.Discord.Canary.locale.en-US.yaml
  manifests/d/Discord/Discord/Canary/1.0.455/Discord.Discord.Canary.locale.zh-CN.yaml
  manifests/d/Discord/Discord/Canary/1.0.455/Discord.Discord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175907 New version: Google.Chrome.Canary version 131.0.6749.0
  manifests/g/Google/Chrome/Canary/131.0.6749.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/131.0.6749.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/131.0.6749.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/131.0.6749.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/131.0.6749.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175908 New version: Gather.Gather version 1.14.0
  manifests/g/Gather/Gather/1.14.0/Gather.Gather.installer.yaml
  manifests/g/Gather/Gather/1.14.0/Gather.Gather.locale.en-US.yaml
  manifests/g/Gather/Gather/1.14.0/Gather.Gather.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175916 New version: Microsoft.Promptflow version 1.16.0
  manifests/m/Microsoft/Promptflow/1.16.0/Microsoft.Promptflow.installer.yaml
  manifests/m/Microsoft/Promptflow/1.16.0/Microsoft.Promptflow.locale.en-US.yaml
  manifests/m/Microsoft/Promptflow/1.16.0/Microsoft.Promptflow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest, Manifest-Metadata-Consistency

#175915 New version: Fort.Firewall version 3.13.13
  manifests/f/Fort/Firewall/3.13.13/Fort.Firewall.installer.yaml
  manifests/f/Fort/Firewall/3.13.13/Fort.Firewall.locale.en-US.yaml
  manifests/f/Fort/Firewall/3.13.13/Fort.Firewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#175918 New version: PDQ.PDQInventory version 19.3.615.0
  manifests/p/PDQ/PDQInventory/19.3.615.0/PDQ.PDQInventory.installer.yaml
  manifests/p/PDQ/PDQInventory/19.3.615.0/PDQ.PDQInventory.locale.en-US.yaml
  manifests/p/PDQ/PDQInventory/19.3.615.0/PDQ.PDQInventory.locale.zh-CN.yaml
  manifests/p/PDQ/PDQInventory/19.3.615.0/PDQ.PDQInventory.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175917 New version: PDQ.PDQDeploy version 19.3.615.0
  manifests/p/PDQ/PDQDeploy/19.3.615.0/PDQ.PDQDeploy.installer.yaml
  manifests/p/PDQ/PDQDeploy/19.3.615.0/PDQ.PDQDeploy.locale.en-US.yaml
  manifests/p/PDQ/PDQDeploy/19.3.615.0/PDQ.PDQDeploy.locale.zh-CN.yaml
  manifests/p/PDQ/PDQDeploy/19.3.615.0/PDQ.PDQDeploy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175920 Update: Microsoft.Skype version 8.129 (8.129.0.202)
  manifests/m/Microsoft/Skype/8.129/Microsoft.Skype.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#175925 Modify: Gyan.FFmpeg version 7.1
  manifests/g/Gyan/FFmpeg/7.1/Gyan.FFmpeg.installer.yaml
  manifests/g/Gyan/FFmpeg/7.1/Gyan.FFmpeg.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/7.1/Gyan.FFmpeg.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/7.1/Gyan.FFmpeg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175926 Modify: Gyan.FFmpeg.Shared version 7.1
  manifests/g/Gyan/FFmpeg/Shared/7.1/Gyan.FFmpeg.Shared.installer.yaml
  manifests/g/Gyan/FFmpeg/Shared/7.1/Gyan.FFmpeg.Shared.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/Shared/7.1/Gyan.FFmpeg.Shared.locale.zh-CN.yaml
  manifests/g/Gyan/FFmpeg/Shared/7.1/Gyan.FFmpeg.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175929 New version: Gajim.Gajim version 1.9.5
  manifests/g/Gajim/Gajim/1.9.5/Gajim.Gajim.installer.yaml
  manifests/g/Gajim/Gajim/1.9.5/Gajim.Gajim.locale.en-US.yaml
  manifests/g/Gajim/Gajim/1.9.5/Gajim.Gajim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175927 New version: Gyan.FFmpeg.Essentials version 7.1
  manifests/g/Gyan/FFmpeg/Essentials/7.1/Gyan.FFmpeg.Essentials.installer.yaml
  manifests/g/Gyan/FFmpeg/Essentials/7.1/Gyan.FFmpeg.Essentials.locale.en-US.yaml
  manifests/g/Gyan/FFmpeg/Essentials/7.1/Gyan.FFmpeg.Essentials.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175937 New version: Mamba.Micromamba version 2.0.1-0
  manifests/m/Mamba/Micromamba/2.0.1-0/Mamba.Micromamba.installer.yaml
  manifests/m/Mamba/Micromamba/2.0.1-0/Mamba.Micromamba.locale.en-US.yaml
  manifests/m/Mamba/Micromamba/2.0.1-0/Mamba.Micromamba.locale.zh-CN.yaml
  manifests/m/Mamba/Micromamba/2.0.1-0/Mamba.Micromamba.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#175968 JanDeDobbeleer.OhMyPosh version 23.15.3
  manifests/j/JanDeDobbeleer/OhMyPosh/23.15.3/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/23.15.3/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/23.15.3/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175632 Add ARP: WorksMobile.NAVERWORKS 4.0.4.1
  manifests/w/WorksMobile/NAVERWORKS/4.0.4.1/WorksMobile.NAVERWORKS.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#175939 New version: Zen-Team.Zen-Browser version 1.0.1-a.7
  manifests/z/Zen-Team/Zen-Browser/1.0.1-a.7/Zen-Team.Zen-Browser.installer.yaml
  manifests/z/Zen-Team/Zen-Browser/1.0.1-a.7/Zen-Team.Zen-Browser.locale.en-US.yaml
  manifests/z/Zen-Team/Zen-Browser/1.0.1-a.7/Zen-Team.Zen-Browser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175940 New version: LiveKit.LiveKitCLI version 2.2.0
  manifests/l/LiveKit/LiveKitCLI/2.2.0/LiveKit.LiveKitCLI.installer.yaml
  manifests/l/LiveKit/LiveKitCLI/2.2.0/LiveKit.LiveKitCLI.locale.en-US.yaml
  manifests/l/LiveKit/LiveKitCLI/2.2.0/LiveKit.LiveKitCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175943 New version: nektos.act version 0.2.68
  manifests/n/nektos/act/0.2.68/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.68/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.68/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175942 New version: AuraMarker.Lattics version 2.0.1
  manifests/a/AuraMarker/Lattics/2.0.1/AuraMarker.Lattics.installer.yaml
  manifests/a/AuraMarker/Lattics/2.0.1/AuraMarker.Lattics.locale.en-US.yaml
  manifests/a/AuraMarker/Lattics/2.0.1/AuraMarker.Lattics.locale.zh-CN.yaml
  manifests/a/AuraMarker/Lattics/2.0.1/AuraMarker.Lattics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175944 OlegShparber.Zeal: add moniker
  manifests/o/OlegShparber/Zeal/0.7.2/OlegShparber.Zeal.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175947 New version: Casey.Just version 1.36.0
  manifests/c/Casey/Just/1.36.0/Casey.Just.installer.yaml
  manifests/c/Casey/Just/1.36.0/Casey.Just.locale.en-US.yaml
  manifests/c/Casey/Just/1.36.0/Casey.Just.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest, Manifest-Metadata-Consistency

#175945 New version: StartIsBack.StartAllBack version 3.8.9
  manifests/s/StartIsBack/StartAllBack/3.8.9/StartIsBack.StartAllBack.installer.yaml
  manifests/s/StartIsBack/StartAllBack/3.8.9/StartIsBack.StartAllBack.locale.en-US.yaml
  manifests/s/StartIsBack/StartAllBack/3.8.9/StartIsBack.StartAllBack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175949 New version: Postman.Postman version 11.15.0
  manifests/p/Postman/Postman/11.15.0/Postman.Postman.installer.yaml
  manifests/p/Postman/Postman/11.15.0/Postman.Postman.locale.en-US.yaml
  manifests/p/Postman/Postman/11.15.0/Postman.Postman.locale.zh-CN.yaml
  manifests/p/Postman/Postman/11.15.0/Postman.Postman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175952 Remove version: Stackers.Stack version 3.18.1
  manifests/s/Stackers/Stack/3.18.1/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.18.1/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.18.1/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#175954 Remove version: Stackers.Stack version 3.32.0
  manifests/s/Stackers/Stack/3.32.0/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.32.0/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.32.0/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175953 Remove version: Stackers.Stack version 3.12.11
  manifests/s/Stackers/Stack/3.12.11/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.12.11/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.12.11/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175958 Remove version: Stackers.Stack version 3.18.0
  manifests/s/Stackers/Stack/3.18.0/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.18.0/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.18.0/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175956 Remove version: Stackers.Stack version 3.13.3
  manifests/s/Stackers/Stack/3.13.3/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.13.3/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.13.3/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175957 Remove version: Stackers.Stack version 3.3.0
  manifests/s/Stackers/Stack/3.3.0/Stackers.Stack.installer.yaml
  manifests/s/Stackers/Stack/3.3.0/Stackers.Stack.locale.en-US.yaml
  manifests/s/Stackers/Stack/3.3.0/Stackers.Stack.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175960 New version: Jackett.Jackett version 0.22.698
  manifests/j/Jackett/Jackett/0.22.698/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.698/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.698/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#175963 New version: NordSecurity.NordLayer version 3.3.7.0 (3.3.7)
  manifests/n/NordSecurity/NordLayer/3.3.7.0/NordSecurity.NordLayer.installer.yaml
  manifests/n/NordSecurity/NordLayer/3.3.7.0/NordSecurity.NordLayer.locale.en-US.yaml
  manifests/n/NordSecurity/NordLayer/3.3.7.0/NordSecurity.NordLayer.locale.zh-CN.yaml
  manifests/n/NordSecurity/NordLayer/3.3.7.0/NordSecurity.NordLayer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Manifest

#175970 New version: Fly-io.flyctl version 0.3.13
  manifests/f/Fly-io/flyctl/0.3.13/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.3.13/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.3.13/Fly-io.flyctl.locale.ko-KR.yaml
  manifests/f/Fly-io/flyctl/0.3.13/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175971 New version: yt-dlp.yt-dlp.nightly version 2024.09.30.232929
  manifests/y/yt-dlp/yt-dlp/nightly/2024.09.30.232929/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.09.30.232929/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.09.30.232929/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175650 Yamaha.SYNCROOM version 2.0.4
  manifests/y/Yamaha/SYNCROOM/2.0.4/Yamaha.SYNCROOM.installer.yaml
  manifests/y/Yamaha/SYNCROOM/2.0.4/Yamaha.SYNCROOM.locale.en-US.yaml
  manifests/y/Yamaha/SYNCROOM/2.0.4/Yamaha.SYNCROOM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#175964 New package: Unity.TuanjieHub version 1.2.0
  manifests/u/Unity/TuanjieHub/1.2.0/Unity.TuanjieHub.installer.yaml
  manifests/u/Unity/TuanjieHub/1.2.0/Unity.TuanjieHub.locale.en-US.yaml
  manifests/u/Unity/TuanjieHub/1.2.0/Unity.TuanjieHub.locale.zh-CN.yaml
  manifests/u/Unity/TuanjieHub/1.2.0/Unity.TuanjieHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#175987 New package: Adobe.Connect.MSI version 24.9.149
  manifests/a/Adobe/Connect/MSI/24.9.149/Adobe.Connect.MSI.installer.yaml
  manifests/a/Adobe/Connect/MSI/24.9.149/Adobe.Connect.MSI.locale.en-US.yaml
  manifests/a/Adobe/Connect/MSI/24.9.149/Adobe.Connect.MSI.locale.zh-CN.yaml
  manifests/a/Adobe/Connect/MSI/24.9.149/Adobe.Connect.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#175988 Add version: Adobe.Connect.MSI version 24.8.120
  manifests/a/Adobe/Connect/MSI/24.8.120/Adobe.Connect.MSI.installer.yaml
  manifests/a/Adobe/Connect/MSI/24.8.120/Adobe.Connect.MSI.locale.en-US.yaml
  manifests/a/Adobe/Connect/MSI/24.8.120/Adobe.Connect.MSI.locale.zh-CN.yaml
  manifests/a/Adobe/Connect/MSI/24.8.120/Adobe.Connect.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#175992 New package: Mozilla.Thunderbird.MSIX version 128.2.0
  manifests/m/Mozilla/Thunderbird/MSIX/128.2.0/Mozilla.Thunderbird.MSIX.installer.yaml
  manifests/m/Mozilla/Thunderbird/MSIX/128.2.0/Mozilla.Thunderbird.MSIX.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/MSIX/128.2.0/Mozilla.Thunderbird.MSIX.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/MSIX/128.2.0/Mozilla.Thunderbird.MSIX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176029 New package: Mozilla.Thunderbird.hu version 128.2.0
  manifests/m/Mozilla/Thunderbird/hu/128.2.0/Mozilla.Thunderbird.hu.installer.yaml
  manifests/m/Mozilla/Thunderbird/hu/128.2.0/Mozilla.Thunderbird.hu.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/hu/128.2.0/Mozilla.Thunderbird.hu.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/hu/128.2.0/Mozilla.Thunderbird.hu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176041 New package: Mozilla.Thunderbird.ms version 128.2.0
  manifests/m/Mozilla/Thunderbird/ms/128.2.0/Mozilla.Thunderbird.ms.installer.yaml
  manifests/m/Mozilla/Thunderbird/ms/128.2.0/Mozilla.Thunderbird.ms.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ms/128.2.0/Mozilla.Thunderbird.ms.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ms/128.2.0/Mozilla.Thunderbird.ms.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176031 New package: Mozilla.Thunderbird.id version 128.2.0
  manifests/m/Mozilla/Thunderbird/id/128.2.0/Mozilla.Thunderbird.id.installer.yaml
  manifests/m/Mozilla/Thunderbird/id/128.2.0/Mozilla.Thunderbird.id.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/id/128.2.0/Mozilla.Thunderbird.id.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/id/128.2.0/Mozilla.Thunderbird.id.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176042 New package: Mozilla.Thunderbird.nb-NO version 128.2.0
  manifests/m/Mozilla/Thunderbird/nb-NO/128.2.0/Mozilla.Thunderbird.nb-NO.installer.yaml
  manifests/m/Mozilla/Thunderbird/nb-NO/128.2.0/Mozilla.Thunderbird.nb-NO.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/nb-NO/128.2.0/Mozilla.Thunderbird.nb-NO.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/nb-NO/128.2.0/Mozilla.Thunderbird.nb-NO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176044 New package: Mozilla.Thunderbird.nn-NO version 128.2.0
  manifests/m/Mozilla/Thunderbird/nn-NO/128.2.0/Mozilla.Thunderbird.nn-NO.installer.yaml
  manifests/m/Mozilla/Thunderbird/nn-NO/128.2.0/Mozilla.Thunderbird.nn-NO.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/nn-NO/128.2.0/Mozilla.Thunderbird.nn-NO.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/nn-NO/128.2.0/Mozilla.Thunderbird.nn-NO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176043 New package: Mozilla.Thunderbird.nl version 128.2.0
  manifests/m/Mozilla/Thunderbird/nl/128.2.0/Mozilla.Thunderbird.nl.installer.yaml
  manifests/m/Mozilla/Thunderbird/nl/128.2.0/Mozilla.Thunderbird.nl.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/nl/128.2.0/Mozilla.Thunderbird.nl.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/nl/128.2.0/Mozilla.Thunderbird.nl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#175974 Fix: Alibaba.aDrive version 6.1.0
  manifests/a/Alibaba/aDrive/6.1.0/Alibaba.aDrive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175973 Fix: Alibaba.aDrive version 6.0.0
  manifests/a/Alibaba/aDrive/6.0.0/Alibaba.aDrive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#176045 New package: Mozilla.Thunderbird.pa-IN version 128.2.0
  manifests/m/Mozilla/Thunderbird/pa-IN/128.2.0/Mozilla.Thunderbird.pa-IN.installer.yaml
  manifests/m/Mozilla/Thunderbird/pa-IN/128.2.0/Mozilla.Thunderbird.pa-IN.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/pa-IN/128.2.0/Mozilla.Thunderbird.pa-IN.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/pa-IN/128.2.0/Mozilla.Thunderbird.pa-IN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#175976 New version: Brave.Brave.Beta version 129.1.71.102
  manifests/b/Brave/Brave/Beta/129.1.71.102/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/129.1.71.102/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/129.1.71.102/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/129.1.71.102/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175977 New version: Alibaba.aDrive version 6.4.2
  manifests/a/Alibaba/aDrive/6.4.2/Alibaba.aDrive.installer.yaml
  manifests/a/Alibaba/aDrive/6.4.2/Alibaba.aDrive.locale.en-US.yaml
  manifests/a/Alibaba/aDrive/6.4.2/Alibaba.aDrive.locale.zh-CN.yaml
  manifests/a/Alibaba/aDrive/6.4.2/Alibaba.aDrive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#175978 Fix: Alibaba.aDrive version 6.3.2
  manifests/a/Alibaba/aDrive/6.3.2/Alibaba.aDrive.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175979 New version: Google.Chrome.Canary version 131.0.6750.0
  manifests/g/Google/Chrome/Canary/131.0.6750.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/131.0.6750.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/131.0.6750.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/131.0.6750.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/131.0.6750.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175983 New version: AmyXun.AxGlyph version 2.5981
  manifests/a/AmyXun/AxGlyph/2.5981/AmyXun.AxGlyph.installer.yaml
  manifests/a/AmyXun/AxGlyph/2.5981/AmyXun.AxGlyph.locale.en-US.yaml
  manifests/a/AmyXun/AxGlyph/2.5981/AmyXun.AxGlyph.locale.zh-CN.yaml
  manifests/a/AmyXun/AxGlyph/2.5981/AmyXun.AxGlyph.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175981 New version: PBH-BTN.PeerBanHelper version 6.4.1
  manifests/p/PBH-BTN/PeerBanHelper/6.4.1/PBH-BTN.PeerBanHelper.installer.yaml
  manifests/p/PBH-BTN/PeerBanHelper/6.4.1/PBH-BTN.PeerBanHelper.locale.en-US.yaml
  manifests/p/PBH-BTN/PeerBanHelper/6.4.1/PBH-BTN.PeerBanHelper.locale.zh-CN.yaml
  manifests/p/PBH-BTN/PeerBanHelper/6.4.1/PBH-BTN.PeerBanHelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175982 New version: AmyXun.AxMath version 2.7061
  manifests/a/AmyXun/AxMath/2.7061/AmyXun.AxMath.installer.yaml
  manifests/a/AmyXun/AxMath/2.7061/AmyXun.AxMath.locale.en-US.yaml
  manifests/a/AmyXun/AxMath/2.7061/AmyXun.AxMath.locale.zh-CN.yaml
  manifests/a/AmyXun/AxMath/2.7061/AmyXun.AxMath.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175984 Update: THS.THS version 9.30.70
  manifests/t/THS/THS/9.30.70/THS.THS.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175990 Modify: Adobe.Connect version 2024.9.149
  manifests/a/Adobe/Connect/2024.9.149/Adobe.Connect.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#175986 New version: NexusMods.Vortex version 1.12.5
  manifests/n/NexusMods/Vortex/1.12.5/NexusMods.Vortex.installer.yaml
  manifests/n/NexusMods/Vortex/1.12.5/NexusMods.Vortex.locale.en-US.yaml
  manifests/n/NexusMods/Vortex/1.12.5/NexusMods.Vortex.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175991 New version: Zettlr.Zettlr version 3.2.2
  manifests/z/Zettlr/Zettlr/3.2.2/Zettlr.Zettlr.installer.yaml
  manifests/z/Zettlr/Zettlr/3.2.2/Zettlr.Zettlr.locale.en-US.yaml
  manifests/z/Zettlr/Zettlr/3.2.2/Zettlr.Zettlr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175993 Add architecture: NAVER.Whale version 3.28.266.11
  manifests/n/NAVER/Whale/3.28.266.11/NAVER.Whale.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#176015 New version: Sentry.sentry-cli version 2.36.5
  manifests/s/Sentry/sentry-cli/2.36.5/Sentry.sentry-cli.installer.yaml
  manifests/s/Sentry/sentry-cli/2.36.5/Sentry.sentry-cli.locale.en-US.yaml
  manifests/s/Sentry/sentry-cli/2.36.5/Sentry.sentry-cli.locale.zh-CN.yaml
  manifests/s/Sentry/sentry-cli/2.36.5/Sentry.sentry-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#176010 New version: KDE.Krita version 5.2.6.0 (5.2.6)
  manifests/k/KDE/Krita/5.2.6.0/KDE.Krita.installer.yaml
  manifests/k/KDE/Krita/5.2.6.0/KDE.Krita.locale.en-US.yaml
  manifests/k/KDE/Krita/5.2.6.0/KDE.Krita.locale.zh-CN.yaml
  manifests/k/KDE/Krita/5.2.6.0/KDE.Krita.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#175994 New version: xpipe-io.xpipe version 12.0
  manifests/x/xpipe-io/xpipe/12.0/xpipe-io.xpipe.installer.yaml
  manifests/x/xpipe-io/xpipe/12.0/xpipe-io.xpipe.locale.en-US.yaml
  manifests/x/xpipe-io/xpipe/12.0/xpipe-io.xpipe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#176048 New package: Mozilla.Thunderbird.pt-PT version 128.2.0
  manifests/m/Mozilla/Thunderbird/pt-PT/128.2.0/Mozilla.Thunderbird.pt-PT.installer.yaml
  manifests/m/Mozilla/Thunderbird/pt-PT/128.2.0/Mozilla.Thunderbird.pt-PT.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/pt-PT/128.2.0/Mozilla.Thunderbird.pt-PT.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/pt-PT/128.2.0/Mozilla.Thunderbird.pt-PT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176049 New package: Mozilla.Thunderbird.rm version 128.2.0
  manifests/m/Mozilla/Thunderbird/rm/128.2.0/Mozilla.Thunderbird.rm.installer.yaml
  manifests/m/Mozilla/Thunderbird/rm/128.2.0/Mozilla.Thunderbird.rm.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/rm/128.2.0/Mozilla.Thunderbird.rm.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/rm/128.2.0/Mozilla.Thunderbird.rm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176054 New package: Mozilla.Thunderbird.sq version 128.2.0
  manifests/m/Mozilla/Thunderbird/sq/128.2.0/Mozilla.Thunderbird.sq.installer.yaml
  manifests/m/Mozilla/Thunderbird/sq/128.2.0/Mozilla.Thunderbird.sq.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/sq/128.2.0/Mozilla.Thunderbird.sq.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/sq/128.2.0/Mozilla.Thunderbird.sq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176059 New package: Mozilla.Thunderbird.tr version 128.2.0
  manifests/m/Mozilla/Thunderbird/tr/128.2.0/Mozilla.Thunderbird.tr.installer.yaml
  manifests/m/Mozilla/Thunderbird/tr/128.2.0/Mozilla.Thunderbird.tr.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/tr/128.2.0/Mozilla.Thunderbird.tr.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/tr/128.2.0/Mozilla.Thunderbird.tr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176057 New package: Mozilla.Thunderbird.sv-SE version 128.2.0
  manifests/m/Mozilla/Thunderbird/sv-SE/128.2.0/Mozilla.Thunderbird.sv-SE.installer.yaml
  manifests/m/Mozilla/Thunderbird/sv-SE/128.2.0/Mozilla.Thunderbird.sv-SE.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/sv-SE/128.2.0/Mozilla.Thunderbird.sv-SE.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/sv-SE/128.2.0/Mozilla.Thunderbird.sv-SE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176063 New package: Mozilla.Thunderbird.vi version 128.2.0
  manifests/m/Mozilla/Thunderbird/vi/128.2.0/Mozilla.Thunderbird.vi.installer.yaml
  manifests/m/Mozilla/Thunderbird/vi/128.2.0/Mozilla.Thunderbird.vi.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/vi/128.2.0/Mozilla.Thunderbird.vi.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/vi/128.2.0/Mozilla.Thunderbird.vi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176053 New package: Mozilla.Thunderbird.sl version 128.2.0
  manifests/m/Mozilla/Thunderbird/sl/128.2.0/Mozilla.Thunderbird.sl.installer.yaml
  manifests/m/Mozilla/Thunderbird/sl/128.2.0/Mozilla.Thunderbird.sl.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/sl/128.2.0/Mozilla.Thunderbird.sl.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/sl/128.2.0/Mozilla.Thunderbird.sl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176060 New package: Mozilla.Thunderbird.uk version 128.2.0
  manifests/m/Mozilla/Thunderbird/uk/128.2.0/Mozilla.Thunderbird.uk.installer.yaml
  manifests/m/Mozilla/Thunderbird/uk/128.2.0/Mozilla.Thunderbird.uk.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/uk/128.2.0/Mozilla.Thunderbird.uk.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/uk/128.2.0/Mozilla.Thunderbird.uk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176070 Modify: Mozilla.Thunderbird version 128.2.0
  manifests/m/Mozilla/Thunderbird/128.2.0/Mozilla.Thunderbird.installer.yaml
  manifests/m/Mozilla/Thunderbird/128.2.0/Mozilla.Thunderbird.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/128.2.0/Mozilla.Thunderbird.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#176066 New version: ProjectEnv.ProjectEnvCli version v3.19.0
  manifests/p/ProjectEnv/ProjectEnvCli/v3.19.0/ProjectEnv.ProjectEnvCli.installer.yaml
  manifests/p/ProjectEnv/ProjectEnvCli/v3.19.0/ProjectEnv.ProjectEnvCli.locale.en-US.yaml
  manifests/p/ProjectEnv/ProjectEnvCli/v3.19.0/ProjectEnv.ProjectEnvCli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#176068 New version: Ryujinx.Ryujinx.Ava version 1.1.1403
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1403/Ryujinx.Ryujinx.Ava.installer.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1403/Ryujinx.Ryujinx.Ava.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/Ava/1.1.1403/Ryujinx.Ryujinx.Ava.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#176005 New package: Mozilla.Thunderbird.da version 128.2.0
  manifests/m/Mozilla/Thunderbird/da/128.2.0/Mozilla.Thunderbird.da.installer.yaml
  manifests/m/Mozilla/Thunderbird/da/128.2.0/Mozilla.Thunderbird.da.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/da/128.2.0/Mozilla.Thunderbird.da.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/da/128.2.0/Mozilla.Thunderbird.da.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176007 New package: Mozilla.Thunderbird.dsb version 128.2.0
  manifests/m/Mozilla/Thunderbird/dsb/128.2.0/Mozilla.Thunderbird.dsb.installer.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.2.0/Mozilla.Thunderbird.dsb.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.2.0/Mozilla.Thunderbird.dsb.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.2.0/Mozilla.Thunderbird.dsb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176016 New package: Mozilla.Thunderbird.es-ES version 128.2.0
  manifests/m/Mozilla/Thunderbird/es-ES/128.2.0/Mozilla.Thunderbird.es-ES.installer.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.2.0/Mozilla.Thunderbird.es-ES.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.2.0/Mozilla.Thunderbird.es-ES.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.2.0/Mozilla.Thunderbird.es-ES.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176019 New package: Mozilla.Thunderbird.eu version 128.2.0
  manifests/m/Mozilla/Thunderbird/eu/128.2.0/Mozilla.Thunderbird.eu.installer.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.2.0/Mozilla.Thunderbird.eu.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.2.0/Mozilla.Thunderbird.eu.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.2.0/Mozilla.Thunderbird.eu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176032 New package: Mozilla.Thunderbird.is version 128.2.0
  manifests/m/Mozilla/Thunderbird/is/128.2.0/Mozilla.Thunderbird.is.installer.yaml
  manifests/m/Mozilla/Thunderbird/is/128.2.0/Mozilla.Thunderbird.is.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/is/128.2.0/Mozilla.Thunderbird.is.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/is/128.2.0/Mozilla.Thunderbird.is.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176027 New package: Mozilla.Thunderbird.hr version 128.2.0
  manifests/m/Mozilla/Thunderbird/hr/128.2.0/Mozilla.Thunderbird.hr.installer.yaml
  manifests/m/Mozilla/Thunderbird/hr/128.2.0/Mozilla.Thunderbird.hr.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/hr/128.2.0/Mozilla.Thunderbird.hr.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/hr/128.2.0/Mozilla.Thunderbird.hr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176033 New package: Mozilla.Thunderbird.it version 128.2.0
  manifests/m/Mozilla/Thunderbird/it/128.2.0/Mozilla.Thunderbird.it.installer.yaml
  manifests/m/Mozilla/Thunderbird/it/128.2.0/Mozilla.Thunderbird.it.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/it/128.2.0/Mozilla.Thunderbird.it.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/it/128.2.0/Mozilla.Thunderbird.it.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176039 New package: Mozilla.Thunderbird.lt version 128.2.0
  manifests/m/Mozilla/Thunderbird/lt/128.2.0/Mozilla.Thunderbird.lt.installer.yaml
  manifests/m/Mozilla/Thunderbird/lt/128.2.0/Mozilla.Thunderbird.lt.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/lt/128.2.0/Mozilla.Thunderbird.lt.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/lt/128.2.0/Mozilla.Thunderbird.lt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176038 New package: Mozilla.Thunderbird.ko version 128.2.0
  manifests/m/Mozilla/Thunderbird/ko/128.2.0/Mozilla.Thunderbird.ko.installer.yaml
  manifests/m/Mozilla/Thunderbird/ko/128.2.0/Mozilla.Thunderbird.ko.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ko/128.2.0/Mozilla.Thunderbird.ko.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ko/128.2.0/Mozilla.Thunderbird.ko.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176046 New package: Mozilla.Thunderbird.pl version 128.2.0
  manifests/m/Mozilla/Thunderbird/pl/128.2.0/Mozilla.Thunderbird.pl.installer.yaml
  manifests/m/Mozilla/Thunderbird/pl/128.2.0/Mozilla.Thunderbird.pl.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/pl/128.2.0/Mozilla.Thunderbird.pl.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/pl/128.2.0/Mozilla.Thunderbird.pl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176040 New package: Mozilla.Thunderbird.lv version 128.2.0
  manifests/m/Mozilla/Thunderbird/lv/128.2.0/Mozilla.Thunderbird.lv.installer.yaml
  manifests/m/Mozilla/Thunderbird/lv/128.2.0/Mozilla.Thunderbird.lv.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/lv/128.2.0/Mozilla.Thunderbird.lv.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/lv/128.2.0/Mozilla.Thunderbird.lv.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176028 New package: Mozilla.Thunderbird.hsb version 128.2.0
  manifests/m/Mozilla/Thunderbird/hsb/128.2.0/Mozilla.Thunderbird.hsb.installer.yaml
  manifests/m/Mozilla/Thunderbird/hsb/128.2.0/Mozilla.Thunderbird.hsb.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/hsb/128.2.0/Mozilla.Thunderbird.hsb.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/hsb/128.2.0/Mozilla.Thunderbird.hsb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176026 New package: Mozilla.Thunderbird.he version 128.2.0
  manifests/m/Mozilla/Thunderbird/he/128.2.0/Mozilla.Thunderbird.he.installer.yaml
  manifests/m/Mozilla/Thunderbird/he/128.2.0/Mozilla.Thunderbird.he.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/he/128.2.0/Mozilla.Thunderbird.he.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/he/128.2.0/Mozilla.Thunderbird.he.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176000 New package: Mozilla.Thunderbird.br version 128.2.0
  manifests/m/Mozilla/Thunderbird/br/128.2.0/Mozilla.Thunderbird.br.installer.yaml
  manifests/m/Mozilla/Thunderbird/br/128.2.0/Mozilla.Thunderbird.br.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/br/128.2.0/Mozilla.Thunderbird.br.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/br/128.2.0/Mozilla.Thunderbird.br.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176023 New package: Mozilla.Thunderbird.ga-IE version 128.2.0
  manifests/m/Mozilla/Thunderbird/ga-IE/128.2.0/Mozilla.Thunderbird.ga-IE.installer.yaml
  manifests/m/Mozilla/Thunderbird/ga-IE/128.2.0/Mozilla.Thunderbird.ga-IE.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ga-IE/128.2.0/Mozilla.Thunderbird.ga-IE.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ga-IE/128.2.0/Mozilla.Thunderbird.ga-IE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176034 New package: Mozilla.Thunderbird.ja version 128.2.0
  manifests/m/Mozilla/Thunderbird/ja/128.2.0/Mozilla.Thunderbird.ja.installer.yaml
  manifests/m/Mozilla/Thunderbird/ja/128.2.0/Mozilla.Thunderbird.ja.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ja/128.2.0/Mozilla.Thunderbird.ja.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ja/128.2.0/Mozilla.Thunderbird.ja.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176067 New version: Ryujinx.Ryujinx version 1.1.1403
  manifests/r/Ryujinx/Ryujinx/1.1.1403/Ryujinx.Ryujinx.installer.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1403/Ryujinx.Ryujinx.locale.en-US.yaml
  manifests/r/Ryujinx/Ryujinx/1.1.1403/Ryujinx.Ryujinx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#176195 New version: Google.QuickShare version 1.0.1939.4
  manifests/g/Google/QuickShare/1.0.1939.4/Google.QuickShare.installer.yaml
  manifests/g/Google/QuickShare/1.0.1939.4/Google.QuickShare.locale.en-US.yaml
  manifests/g/Google/QuickShare/1.0.1939.4/Google.QuickShare.locale.zh-CN.yaml
  manifests/g/Google/QuickShare/1.0.1939.4/Google.QuickShare.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#175672 New package: CodeLyokoGames.KolossusLauncher version 1.7.0-1
  manifests/c/CodeLyokoGames/KolossusLauncher/1.7.0-1/CodeLyokoGames.KolossusLauncher.installer.yaml
  manifests/c/CodeLyokoGames/KolossusLauncher/1.7.0-1/CodeLyokoGames.KolossusLauncher.locale.en-US.yaml
  manifests/c/CodeLyokoGames/KolossusLauncher/1.7.0-1/CodeLyokoGames.KolossusLauncher.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#175332 New version: Unity.Unity.2022 version 2022.3.48f1
  manifests/u/Unity/Unity/2022/2022.3.48f1/Unity.Unity.2022.installer.yaml
  manifests/u/Unity/Unity/2022/2022.3.48f1/Unity.Unity.2022.locale.en-US.yaml
  manifests/u/Unity/Unity/2022/2022.3.48f1/Unity.Unity.2022.locale.zh-CN.yaml
  manifests/u/Unity/Unity/2022/2022.3.48f1/Unity.Unity.2022.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#175489 New version: JetBrains.Rider.EAP version 243.16718.44
  manifests/j/JetBrains/Rider/EAP/243.16718.44/JetBrains.Rider.EAP.installer.yaml
  manifests/j/JetBrains/Rider/EAP/243.16718.44/JetBrains.Rider.EAP.locale.en-US.yaml
  manifests/j/JetBrains/Rider/EAP/243.16718.44/JetBrains.Rider.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/Rider/EAP/243.16718.44/JetBrains.Rider.EAP.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved, Validation-Retry

#175896 New version: WK.WKRadar version 7.12.0.0
  manifests/w/WK/WKRadar/7.12.0.0/WK.WKRadar.installer.yaml
  manifests/w/WK/WKRadar/7.12.0.0/WK.WKRadar.locale.pt-BR.yaml
  manifests/w/WK/WKRadar/7.12.0.0/WK.WKRadar.yaml
Labels: Validation-Completed, Retry-1

#175634 New version: LinwoodCloud.Butterfly version 2.2.0
  manifests/l/LinwoodCloud/Butterfly/2.2.0/LinwoodCloud.Butterfly.installer.yaml
  manifests/l/LinwoodCloud/Butterfly/2.2.0/LinwoodCloud.Butterfly.locale.en-US.yaml
  manifests/l/LinwoodCloud/Butterfly/2.2.0/LinwoodCloud.Butterfly.yaml
Labels: Validation-Completed, Moderator-Approved

#175967 New version: advaith.CurrencyConverterPowerToys version 1.3.0
  manifests/a/advaith/CurrencyConverterPowerToys/1.3.0/advaith.CurrencyConverterPowerToys.installer.yaml
  manifests/a/advaith/CurrencyConverterPowerToys/1.3.0/advaith.CurrencyConverterPowerToys.locale.en-US.yaml
  manifests/a/advaith/CurrencyConverterPowerToys/1.3.0/advaith.CurrencyConverterPowerToys.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#175995 New package: Mozilla.Thunderbird.af version 128.2.0
  manifests/m/Mozilla/Thunderbird/af/128.2.0/Mozilla.Thunderbird.af.installer.yaml
  manifests/m/Mozilla/Thunderbird/af/128.2.0/Mozilla.Thunderbird.af.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/af/128.2.0/Mozilla.Thunderbird.af.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/af/128.2.0/Mozilla.Thunderbird.af.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#175996 New package: Mozilla.Thunderbird.ar version 128.2.0
  manifests/m/Mozilla/Thunderbird/ar/128.2.0/Mozilla.Thunderbird.ar.installer.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.2.0/Mozilla.Thunderbird.ar.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.2.0/Mozilla.Thunderbird.ar.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.2.0/Mozilla.Thunderbird.ar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#175997 New package: Mozilla.Thunderbird.ast-ES version 128.2.0
  manifests/m/Mozilla/Thunderbird/ast-ES/128.2.0/Mozilla.Thunderbird.ast-ES.installer.yaml
  manifests/m/Mozilla/Thunderbird/ast-ES/128.2.0/Mozilla.Thunderbird.ast-ES.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ast-ES/128.2.0/Mozilla.Thunderbird.ast-ES.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ast-ES/128.2.0/Mozilla.Thunderbird.ast-ES.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176006 New package: Mozilla.Thunderbird.de version 128.2.0
  manifests/m/Mozilla/Thunderbird/de/128.2.0/Mozilla.Thunderbird.de.installer.yaml
  manifests/m/Mozilla/Thunderbird/de/128.2.0/Mozilla.Thunderbird.de.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/de/128.2.0/Mozilla.Thunderbird.de.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/de/128.2.0/Mozilla.Thunderbird.de.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176001 New package: Mozilla.Thunderbird.ca version 128.2.0
  manifests/m/Mozilla/Thunderbird/ca/128.2.0/Mozilla.Thunderbird.ca.installer.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.2.0/Mozilla.Thunderbird.ca.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.2.0/Mozilla.Thunderbird.ca.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.2.0/Mozilla.Thunderbird.ca.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176004 New package: Mozilla.Thunderbird.cy version 128.2.0
  manifests/m/Mozilla/Thunderbird/cy/128.2.0/Mozilla.Thunderbird.cy.installer.yaml
  manifests/m/Mozilla/Thunderbird/cy/128.2.0/Mozilla.Thunderbird.cy.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/cy/128.2.0/Mozilla.Thunderbird.cy.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/cy/128.2.0/Mozilla.Thunderbird.cy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176008 New version: JetBrains.TeamCity version 2024.07.3
  manifests/j/JetBrains/TeamCity/2024.07.3/JetBrains.TeamCity.installer.yaml
  manifests/j/JetBrains/TeamCity/2024.07.3/JetBrains.TeamCity.locale.en-US.yaml
  manifests/j/JetBrains/TeamCity/2024.07.3/JetBrains.TeamCity.locale.zh-CN.yaml
  manifests/j/JetBrains/TeamCity/2024.07.3/JetBrains.TeamCity.yaml
Labels: Validation-Completed, Moderator-Approved

#175999 New package: Mozilla.Thunderbird.bg version 128.2.0
  manifests/m/Mozilla/Thunderbird/bg/128.2.0/Mozilla.Thunderbird.bg.installer.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.2.0/Mozilla.Thunderbird.bg.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.2.0/Mozilla.Thunderbird.bg.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.2.0/Mozilla.Thunderbird.bg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Package

#176003 New package: Mozilla.Thunderbird.cs version 128.2.0
  manifests/m/Mozilla/Thunderbird/cs/128.2.0/Mozilla.Thunderbird.cs.installer.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.2.0/Mozilla.Thunderbird.cs.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.2.0/Mozilla.Thunderbird.cs.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.2.0/Mozilla.Thunderbird.cs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Package

#176009 New package: Mozilla.Thunderbird.el version 128.2.0
  manifests/m/Mozilla/Thunderbird/el/128.2.0/Mozilla.Thunderbird.el.installer.yaml
  manifests/m/Mozilla/Thunderbird/el/128.2.0/Mozilla.Thunderbird.el.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/el/128.2.0/Mozilla.Thunderbird.el.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/el/128.2.0/Mozilla.Thunderbird.el.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176014 New package: Mozilla.Thunderbird.es-AR version 128.2.0
  manifests/m/Mozilla/Thunderbird/es-AR/128.2.0/Mozilla.Thunderbird.es-AR.installer.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.2.0/Mozilla.Thunderbird.es-AR.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.2.0/Mozilla.Thunderbird.es-AR.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.2.0/Mozilla.Thunderbird.es-AR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176012 New package: Mozilla.Thunderbird.en-GB version 128.2.0
  manifests/m/Mozilla/Thunderbird/en-GB/128.2.0/Mozilla.Thunderbird.en-GB.installer.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.2.0/Mozilla.Thunderbird.en-GB.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.2.0/Mozilla.Thunderbird.en-GB.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.2.0/Mozilla.Thunderbird.en-GB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176017 New package: Mozilla.Thunderbird.es-MX version 128.2.0
  manifests/m/Mozilla/Thunderbird/es-MX/128.2.0/Mozilla.Thunderbird.es-MX.installer.yaml
  manifests/m/Mozilla/Thunderbird/es-MX/128.2.0/Mozilla.Thunderbird.es-MX.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/es-MX/128.2.0/Mozilla.Thunderbird.es-MX.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/es-MX/128.2.0/Mozilla.Thunderbird.es-MX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176011 New package: Mozilla.Thunderbird.en-CA version 128.2.0
  manifests/m/Mozilla/Thunderbird/en-CA/128.2.0/Mozilla.Thunderbird.en-CA.installer.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.2.0/Mozilla.Thunderbird.en-CA.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.2.0/Mozilla.Thunderbird.en-CA.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.2.0/Mozilla.Thunderbird.en-CA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176018 New package: Mozilla.Thunderbird.et version 128.2.0
  manifests/m/Mozilla/Thunderbird/et/128.2.0/Mozilla.Thunderbird.et.installer.yaml
  manifests/m/Mozilla/Thunderbird/et/128.2.0/Mozilla.Thunderbird.et.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/et/128.2.0/Mozilla.Thunderbird.et.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/et/128.2.0/Mozilla.Thunderbird.et.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176020 New package: Mozilla.Thunderbird.fi version 128.2.0
  manifests/m/Mozilla/Thunderbird/fi/128.2.0/Mozilla.Thunderbird.fi.installer.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.2.0/Mozilla.Thunderbird.fi.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.2.0/Mozilla.Thunderbird.fi.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.2.0/Mozilla.Thunderbird.fi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176021 New package: Mozilla.Thunderbird.fr version 128.2.0
  manifests/m/Mozilla/Thunderbird/fr/128.2.0/Mozilla.Thunderbird.fr.installer.yaml
  manifests/m/Mozilla/Thunderbird/fr/128.2.0/Mozilla.Thunderbird.fr.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/fr/128.2.0/Mozilla.Thunderbird.fr.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/fr/128.2.0/Mozilla.Thunderbird.fr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176025 New package: Mozilla.Thunderbird.gl version 128.2.0
  manifests/m/Mozilla/Thunderbird/gl/128.2.0/Mozilla.Thunderbird.gl.installer.yaml
  manifests/m/Mozilla/Thunderbird/gl/128.2.0/Mozilla.Thunderbird.gl.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/gl/128.2.0/Mozilla.Thunderbird.gl.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/gl/128.2.0/Mozilla.Thunderbird.gl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176024 New package: Mozilla.Thunderbird.gd version 128.2.0
  manifests/m/Mozilla/Thunderbird/gd/128.2.0/Mozilla.Thunderbird.gd.installer.yaml
  manifests/m/Mozilla/Thunderbird/gd/128.2.0/Mozilla.Thunderbird.gd.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/gd/128.2.0/Mozilla.Thunderbird.gd.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/gd/128.2.0/Mozilla.Thunderbird.gd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176036 New package: Mozilla.Thunderbird.kab version 128.2.0
  manifests/m/Mozilla/Thunderbird/kab/128.2.0/Mozilla.Thunderbird.kab.installer.yaml
  manifests/m/Mozilla/Thunderbird/kab/128.2.0/Mozilla.Thunderbird.kab.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/kab/128.2.0/Mozilla.Thunderbird.kab.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/kab/128.2.0/Mozilla.Thunderbird.kab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176030 New package: Mozilla.Thunderbird.hy-AM version 128.2.0
  manifests/m/Mozilla/Thunderbird/hy-AM/128.2.0/Mozilla.Thunderbird.hy-AM.installer.yaml
  manifests/m/Mozilla/Thunderbird/hy-AM/128.2.0/Mozilla.Thunderbird.hy-AM.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/hy-AM/128.2.0/Mozilla.Thunderbird.hy-AM.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/hy-AM/128.2.0/Mozilla.Thunderbird.hy-AM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176022 New package: Mozilla.Thunderbird.fy-NL version 128.2.0
  manifests/m/Mozilla/Thunderbird/fy-NL/128.2.0/Mozilla.Thunderbird.fy-NL.installer.yaml
  manifests/m/Mozilla/Thunderbird/fy-NL/128.2.0/Mozilla.Thunderbird.fy-NL.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/fy-NL/128.2.0/Mozilla.Thunderbird.fy-NL.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/fy-NL/128.2.0/Mozilla.Thunderbird.fy-NL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176050 New package: Mozilla.Thunderbird.ro version 128.2.0
  manifests/m/Mozilla/Thunderbird/ro/128.2.0/Mozilla.Thunderbird.ro.installer.yaml
  manifests/m/Mozilla/Thunderbird/ro/128.2.0/Mozilla.Thunderbird.ro.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ro/128.2.0/Mozilla.Thunderbird.ro.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ro/128.2.0/Mozilla.Thunderbird.ro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved, New-Package

#176002 New version: DigiDNA.iMazing version 2.18.1.0 (2.18.1)
  manifests/d/DigiDNA/iMazing/2.18.1.0/DigiDNA.iMazing.installer.yaml
  manifests/d/DigiDNA/iMazing/2.18.1.0/DigiDNA.iMazing.locale.en-US.yaml
  manifests/d/DigiDNA/iMazing/2.18.1.0/DigiDNA.iMazing.locale.zh-CN.yaml
  manifests/d/DigiDNA/iMazing/2.18.1.0/DigiDNA.iMazing.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#176096 New version: Microsoft.TimeTravelDebugging version 1.11.429.0
  manifests/m/Microsoft/TimeTravelDebugging/1.11.429.0/Microsoft.TimeTravelDebugging.installer.yaml
  manifests/m/Microsoft/TimeTravelDebugging/1.11.429.0/Microsoft.TimeTravelDebugging.locale.en-US.yaml
  manifests/m/Microsoft/TimeTravelDebugging/1.11.429.0/Microsoft.TimeTravelDebugging.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#176051 New package: Mozilla.Thunderbird.ru version 128.2.0
  manifests/m/Mozilla/Thunderbird/ru/128.2.0/Mozilla.Thunderbird.ru.installer.yaml
  manifests/m/Mozilla/Thunderbird/ru/128.2.0/Mozilla.Thunderbird.ru.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ru/128.2.0/Mozilla.Thunderbird.ru.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ru/128.2.0/Mozilla.Thunderbird.ru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, New-Package

#176062 New package: Mozilla.Thunderbird.uz version 128.2.0
  manifests/m/Mozilla/Thunderbird/uz/128.2.0/Mozilla.Thunderbird.uz.installer.yaml
  manifests/m/Mozilla/Thunderbird/uz/128.2.0/Mozilla.Thunderbird.uz.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/uz/128.2.0/Mozilla.Thunderbird.uz.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/uz/128.2.0/Mozilla.Thunderbird.uz.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176055 New package: Mozilla.Thunderbird.sr version 128.2.0
  manifests/m/Mozilla/Thunderbird/sr/128.2.0/Mozilla.Thunderbird.sr.installer.yaml
  manifests/m/Mozilla/Thunderbird/sr/128.2.0/Mozilla.Thunderbird.sr.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/sr/128.2.0/Mozilla.Thunderbird.sr.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/sr/128.2.0/Mozilla.Thunderbird.sr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176115 Add version: Mozilla.Thunderbird.be version 128.1.1
  manifests/m/Mozilla/Thunderbird/be/128.1.1/Mozilla.Thunderbird.be.installer.yaml
  manifests/m/Mozilla/Thunderbird/be/128.1.1/Mozilla.Thunderbird.be.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/be/128.1.1/Mozilla.Thunderbird.be.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/be/128.1.1/Mozilla.Thunderbird.be.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176116 Add version: Mozilla.Thunderbird.bg version 128.1.1
  manifests/m/Mozilla/Thunderbird/bg/128.1.1/Mozilla.Thunderbird.bg.installer.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.1.1/Mozilla.Thunderbird.bg.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.1.1/Mozilla.Thunderbird.bg.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/bg/128.1.1/Mozilla.Thunderbird.bg.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176120 Add version: Mozilla.Thunderbird.cs version 128.1.1
  manifests/m/Mozilla/Thunderbird/cs/128.1.1/Mozilla.Thunderbird.cs.installer.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.1.1/Mozilla.Thunderbird.cs.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.1.1/Mozilla.Thunderbird.cs.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/cs/128.1.1/Mozilla.Thunderbird.cs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176119 Add version: Mozilla.Thunderbird.ca version 128.1.1
  manifests/m/Mozilla/Thunderbird/ca/128.1.1/Mozilla.Thunderbird.ca.installer.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.1.1/Mozilla.Thunderbird.ca.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.1.1/Mozilla.Thunderbird.ca.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ca/128.1.1/Mozilla.Thunderbird.ca.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176113 Add version: Mozilla.Thunderbird.ar version 128.1.1
  manifests/m/Mozilla/Thunderbird/ar/128.1.1/Mozilla.Thunderbird.ar.installer.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.1.1/Mozilla.Thunderbird.ar.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.1.1/Mozilla.Thunderbird.ar.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ar/128.1.1/Mozilla.Thunderbird.ar.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176129 Add version: Mozilla.Thunderbird.en-GB version 128.1.1
  manifests/m/Mozilla/Thunderbird/en-GB/128.1.1/Mozilla.Thunderbird.en-GB.installer.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.1.1/Mozilla.Thunderbird.en-GB.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.1.1/Mozilla.Thunderbird.en-GB.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/en-GB/128.1.1/Mozilla.Thunderbird.en-GB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176117 Add version: Mozilla.Thunderbird.br version 128.1.1
  manifests/m/Mozilla/Thunderbird/br/128.1.1/Mozilla.Thunderbird.br.installer.yaml
  manifests/m/Mozilla/Thunderbird/br/128.1.1/Mozilla.Thunderbird.br.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/br/128.1.1/Mozilla.Thunderbird.br.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/br/128.1.1/Mozilla.Thunderbird.br.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176130 Add version: Mozilla.Thunderbird.es-AR version 128.1.1
  manifests/m/Mozilla/Thunderbird/es-AR/128.1.1/Mozilla.Thunderbird.es-AR.installer.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.1.1/Mozilla.Thunderbird.es-AR.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.1.1/Mozilla.Thunderbird.es-AR.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/es-AR/128.1.1/Mozilla.Thunderbird.es-AR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176128 Add version: Mozilla.Thunderbird.en-CA version 128.1.1
  manifests/m/Mozilla/Thunderbird/en-CA/128.1.1/Mozilla.Thunderbird.en-CA.installer.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.1.1/Mozilla.Thunderbird.en-CA.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.1.1/Mozilla.Thunderbird.en-CA.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/en-CA/128.1.1/Mozilla.Thunderbird.en-CA.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#176136 Add version: Mozilla.Thunderbird.eu version 128.1.1
  manifests/m/Mozilla/Thunderbird/eu/128.1.1/Mozilla.Thunderbird.eu.installer.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.1.1/Mozilla.Thunderbird.eu.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.1.1/Mozilla.Thunderbird.eu.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/eu/128.1.1/Mozilla.Thunderbird.eu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Possible-Duplicate, Moderator-Approved, New-Manifest

#176124 Add version: Mozilla.Thunderbird.de version 128.1.1
  manifests/m/Mozilla/Thunderbird/de/128.1.1/Mozilla.Thunderbird.de.installer.yaml
  manifests/m/Mozilla/Thunderbird/de/128.1.1/Mozilla.Thunderbird.de.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/de/128.1.1/Mozilla.Thunderbird.de.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/de/128.1.1/Mozilla.Thunderbird.de.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176137 Add version: Mozilla.Thunderbird.fi version 128.1.1
  manifests/m/Mozilla/Thunderbird/fi/128.1.1/Mozilla.Thunderbird.fi.installer.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.1.1/Mozilla.Thunderbird.fi.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.1.1/Mozilla.Thunderbird.fi.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/fi/128.1.1/Mozilla.Thunderbird.fi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176125 Add version: Mozilla.Thunderbird.dsb version 128.1.1
  manifests/m/Mozilla/Thunderbird/dsb/128.1.1/Mozilla.Thunderbird.dsb.installer.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.1.1/Mozilla.Thunderbird.dsb.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.1.1/Mozilla.Thunderbird.dsb.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/dsb/128.1.1/Mozilla.Thunderbird.dsb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176114 Add version: Mozilla.Thunderbird.ast version 128.1.1
  manifests/m/Mozilla/Thunderbird/ast/128.1.1/Mozilla.Thunderbird.ast.installer.yaml
  manifests/m/Mozilla/Thunderbird/ast/128.1.1/Mozilla.Thunderbird.ast.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ast/128.1.1/Mozilla.Thunderbird.ast.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ast/128.1.1/Mozilla.Thunderbird.ast.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176132 Add version: Mozilla.Thunderbird.es-ES version 128.1.1
  manifests/m/Mozilla/Thunderbird/es-ES/128.1.1/Mozilla.Thunderbird.es-ES.installer.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.1.1/Mozilla.Thunderbird.es-ES.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.1.1/Mozilla.Thunderbird.es-ES.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/es-ES/128.1.1/Mozilla.Thunderbird.es-ES.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176123 Add version: Mozilla.Thunderbird.da version 128.1.1
  manifests/m/Mozilla/Thunderbird/da/128.1.1/Mozilla.Thunderbird.da.installer.yaml
  manifests/m/Mozilla/Thunderbird/da/128.1.1/Mozilla.Thunderbird.da.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/da/128.1.1/Mozilla.Thunderbird.da.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/da/128.1.1/Mozilla.Thunderbird.da.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#176112 Add version: Mozilla.Thunderbird.af version 128.1.1
  manifests/m/Mozilla/Thunderbird/af/128.1.1/Mozilla.Thunderbird.af.installer.yaml
  manifests/m/Mozilla/Thunderbird/af/128.1.1/Mozilla.Thunderbird.af.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/af/128.1.1/Mozilla.Thunderbird.af.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/af/128.1.1/Mozilla.Thunderbird.af.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package
