Repository microsoft/winget-pkgs, pull requests merged in 2025-01, with the labels that each got.

#204519 New version: vim.vim.nightly version 9.1.0983
  manifests/v/vim/vim/nightly/9.1.0983/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.0983/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.0983/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204499 New version: Netbird.Netbird version 0.35.2
  manifests/n/Netbird/Netbird/0.35.2/Netbird.Netbird.installer.yaml
  manifests/n/Netbird/Netbird/0.35.2/Netbird.Netbird.locale.en-US.yaml
  manifests/n/Netbird/Netbird/0.35.2/Netbird.Netbird.locale.zh-CN.yaml
  manifests/n/Netbird/Netbird/0.35.2/Netbird.Netbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204426 New version: xemu-project.xemu version 0.7.142
  manifests/x/xemu-project/xemu/0.7.142/xemu-project.xemu.installer.yaml
  manifests/x/xemu-project/xemu/0.7.142/xemu-project.xemu.locale.en-US.yaml
  manifests/x/xemu-project/xemu/0.7.142/xemu-project.xemu.locale.zh-CN.yaml
  manifests/x/xemu-project/xemu/0.7.142/xemu-project.xemu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204463 New package: StefanLobbenmeier.youtube-dl-gui version 2.5.4
  manifests/s/StefanLobbenmeier/youtube-dl-gui/2.5.4/StefanLobbenmeier.youtube-dl-gui.installer.yaml
  manifests/s/StefanLobbenmeier/youtube-dl-gui/2.5.4/StefanLobbenmeier.youtube-dl-gui.locale.en-US.yaml
  manifests/s/StefanLobbenmeier/youtube-dl-gui/2.5.4/StefanLobbenmeier.youtube-dl-gui.yaml
Labels: Validation-Completed, Moderator-Approved, Needs-CLA

#204541 JanDeDobbeleer.Aliae version 0.26.3
  manifests/j/JanDeDobbeleer/Aliae/0.26.3/JanDeDobbeleer.Aliae.installer.yaml
  manifests/j/JanDeDobbeleer/Aliae/0.26.3/JanDeDobbeleer.Aliae.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/Aliae/0.26.3/JanDeDobbeleer.Aliae.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204599 New version: HydraLauncher.Hydra version 3.1.5
  manifests/h/HydraLauncher/Hydra/3.1.5/HydraLauncher.Hydra.installer.yaml
  manifests/h/HydraLauncher/Hydra/3.1.5/HydraLauncher.Hydra.locale.en-US.yaml
  manifests/h/HydraLauncher/Hydra/3.1.5/HydraLauncher.Hydra.locale.zh-CN.yaml
  manifests/h/HydraLauncher/Hydra/3.1.5/HydraLauncher.Hydra.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204602 Update: Adobe.CreativeCloud version 6.4.0.361
  manifests/a/Adobe/CreativeCloud/6.4.0.361/Adobe.CreativeCloud.installer.yaml
  manifests/a/Adobe/CreativeCloud/6.4.0.361/Adobe.CreativeCloud.locale.en-US.yaml
  manifests/a/Adobe/CreativeCloud/6.4.0.361/Adobe.CreativeCloud.locale.zh-CN.yaml
  manifests/a/Adobe/CreativeCloud/6.4.0.361/Adobe.CreativeCloud.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#204579 New version: SpecialK.SpecialK version 25.1.1.1
  manifests/s/SpecialK/SpecialK/25.1.1.1/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.1/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.1/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.1/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204587 the-sz.Lacey version 3.00
  manifests/t/the-sz/Lacey/3.00/the-sz.Lacey.installer.yaml
  manifests/t/the-sz/Lacey/3.00/the-sz.Lacey.locale.en-US.yaml
  manifests/t/the-sz/Lacey/3.00/the-sz.Lacey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204525 New version: Nickvision.Parabolic version 2024.12.2
  manifests/n/Nickvision/Parabolic/2024.12.2/Nickvision.Parabolic.installer.yaml
  manifests/n/Nickvision/Parabolic/2024.12.2/Nickvision.Parabolic.locale.en-US.yaml
  manifests/n/Nickvision/Parabolic/2024.12.2/Nickvision.Parabolic.locale.zh-CN.yaml
  manifests/n/Nickvision/Parabolic/2024.12.2/Nickvision.Parabolic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204560 New version: MikeFarah.yq version 4.44.6
  manifests/m/MikeFarah/yq/4.44.6/MikeFarah.yq.installer.yaml
  manifests/m/MikeFarah/yq/4.44.6/MikeFarah.yq.locale.en-US.yaml
  manifests/m/MikeFarah/yq/4.44.6/MikeFarah.yq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204573 New version: igoogolx.itun2socks version 1.23.1
  manifests/i/igoogolx/itun2socks/1.23.1/igoogolx.itun2socks.installer.yaml
  manifests/i/igoogolx/itun2socks/1.23.1/igoogolx.itun2socks.locale.en-US.yaml
  manifests/i/igoogolx/itun2socks/1.23.1/igoogolx.itun2socks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204558 New version: Infracost.Infracost version 0.10.40
  manifests/i/Infracost/Infracost/0.10.40/Infracost.Infracost.installer.yaml
  manifests/i/Infracost/Infracost/0.10.40/Infracost.Infracost.locale.en-US.yaml
  manifests/i/Infracost/Infracost/0.10.40/Infracost.Infracost.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204555 New version: Gitleaks.Gitleaks version 8.21.4
  manifests/g/Gitleaks/Gitleaks/8.21.4/Gitleaks.Gitleaks.installer.yaml
  manifests/g/Gitleaks/Gitleaks/8.21.4/Gitleaks.Gitleaks.locale.en-US.yaml
  manifests/g/Gitleaks/Gitleaks/8.21.4/Gitleaks.Gitleaks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204561 New version: YS-L.csvlens version 0.11.0
  manifests/y/YS-L/csvlens/0.11.0/YS-L.csvlens.installer.yaml
  manifests/y/YS-L/csvlens/0.11.0/YS-L.csvlens.locale.en-US.yaml
  manifests/y/YS-L/csvlens/0.11.0/YS-L.csvlens.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204556 New version: Gitleaks.Gitleaks version 8.22.0
  manifests/g/Gitleaks/Gitleaks/8.22.0/Gitleaks.Gitleaks.installer.yaml
  manifests/g/Gitleaks/Gitleaks/8.22.0/Gitleaks.Gitleaks.locale.en-US.yaml
  manifests/g/Gitleaks/Gitleaks/8.22.0/Gitleaks.Gitleaks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204522 New version: ppy.osu version 2025.101.0
  manifests/p/ppy/osu/2025.101.0/ppy.osu.installer.yaml
  manifests/p/ppy/osu/2025.101.0/ppy.osu.locale.en-US.yaml
  manifests/p/ppy/osu/2025.101.0/ppy.osu.locale.ja-JP.yaml
  manifests/p/ppy/osu/2025.101.0/ppy.osu.locale.zh-CN.yaml
  manifests/p/ppy/osu/2025.101.0/ppy.osu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204542 New version: igoogolx.itun2socks version 1.23.0
  manifests/i/igoogolx/itun2socks/1.23.0/igoogolx.itun2socks.installer.yaml
  manifests/i/igoogolx/itun2socks/1.23.0/igoogolx.itun2socks.locale.en-US.yaml
  manifests/i/igoogolx/itun2socks/1.23.0/igoogolx.itun2socks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204559 New version: MikeFarah.yq version 4.44.5
  manifests/m/MikeFarah/yq/4.44.5/MikeFarah.yq.installer.yaml
  manifests/m/MikeFarah/yq/4.44.5/MikeFarah.yq.locale.en-US.yaml
  manifests/m/MikeFarah/yq/4.44.5/MikeFarah.yq.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204538 New version: Xiaoyaoyixia.KOOK version 0.91.2
  manifests/x/Xiaoyaoyixia/KOOK/0.91.2/Xiaoyaoyixia.KOOK.installer.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.2/Xiaoyaoyixia.KOOK.locale.en-US.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.2/Xiaoyaoyixia.KOOK.locale.zh-CN.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.2/Xiaoyaoyixia.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204544 New version: Google.Chrome.Canary version 133.0.6931.0
  manifests/g/Google/Chrome/Canary/133.0.6931.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/133.0.6931.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/133.0.6931.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/133.0.6931.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/133.0.6931.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204554 New version: Gitleaks.Gitleaks version 8.21.3
  manifests/g/Gitleaks/Gitleaks/8.21.3/Gitleaks.Gitleaks.installer.yaml
  manifests/g/Gitleaks/Gitleaks/8.21.3/Gitleaks.Gitleaks.locale.en-US.yaml
  manifests/g/Gitleaks/Gitleaks/8.21.3/Gitleaks.Gitleaks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204576 Remove version: igoogolx.lux version 1.25.0
  manifests/i/igoogolx/lux/1.25.0/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/1.25.0/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/1.25.0/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204496 New version: Valve.SteamLink version 1.3.12
  manifests/v/Valve/SteamLink/1.3.12/Valve.SteamLink.installer.yaml
  manifests/v/Valve/SteamLink/1.3.12/Valve.SteamLink.locale.en-US.yaml
  manifests/v/Valve/SteamLink/1.3.12/Valve.SteamLink.yaml
  manifests/v/Valve/SteamLink/1.3.8/Valve.SteamLink.installer.yaml
  manifests/v/Valve/SteamLink/1.3.8/Valve.SteamLink.locale.en-US.yaml
  manifests/v/Valve/SteamLink/1.3.8/Valve.SteamLink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204535 New version: SpecialK.SpecialK version 25.1.1
  manifests/s/SpecialK/SpecialK/25.1.1/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.1.1/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.1.1/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.1.1/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204575 New version: igoogolx.lux version 1.26.0
  manifests/i/igoogolx/lux/1.26.0/igoogolx.lux.installer.yaml
  manifests/i/igoogolx/lux/1.26.0/igoogolx.lux.locale.en-US.yaml
  manifests/i/igoogolx/lux/1.26.0/igoogolx.lux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204527 New version: Blix.BlueMail version 1.140.65
  manifests/b/Blix/BlueMail/1.140.65/Blix.BlueMail.installer.yaml
  manifests/b/Blix/BlueMail/1.140.65/Blix.BlueMail.locale.en-US.yaml
  manifests/b/Blix/BlueMail/1.140.65/Blix.BlueMail.locale.zh-CN.yaml
  manifests/b/Blix/BlueMail/1.140.65/Blix.BlueMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204557 New version: Gitleaks.Gitleaks version 8.22.1
  manifests/g/Gitleaks/Gitleaks/8.22.1/Gitleaks.Gitleaks.installer.yaml
  manifests/g/Gitleaks/Gitleaks/8.22.1/Gitleaks.Gitleaks.locale.en-US.yaml
  manifests/g/Gitleaks/Gitleaks/8.22.1/Gitleaks.Gitleaks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204489 Modify: Valve.SteamCMD version 2.2.95.35
  manifests/v/Valve/SteamCMD/2.2.95.35/Valve.SteamCMD.installer.yaml
  manifests/v/Valve/SteamCMD/2.2.95.35/Valve.SteamCMD.locale.en-US.yaml
  manifests/v/Valve/SteamCMD/2.2.95.35/Valve.SteamCMD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204533 New version: Jackett.Jackett version 0.22.1177
  manifests/j/Jackett/Jackett/0.22.1177/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1177/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1177/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204574 Remove version: igoogolx.itun2socks version 1.22.4
  manifests/i/igoogolx/itun2socks/1.22.4/igoogolx.itun2socks.installer.yaml
  manifests/i/igoogolx/itun2socks/1.22.4/igoogolx.itun2socks.locale.en-US.yaml
  manifests/i/igoogolx/itun2socks/1.22.4/igoogolx.itun2socks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204524 New version: WinsiderSS.SystemInformer.Canary version 3.2.25001.123
  manifests/w/WinsiderSS/SystemInformer/Canary/3.2.25001.123/WinsiderSS.SystemInformer.Canary.installer.yaml
  manifests/w/WinsiderSS/SystemInformer/Canary/3.2.25001.123/WinsiderSS.SystemInformer.Canary.locale.en-US.yaml
  manifests/w/WinsiderSS/SystemInformer/Canary/3.2.25001.123/WinsiderSS.SystemInformer.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204595 New version: Google.Chrome.Canary version 133.0.6932.0
  manifests/g/Google/Chrome/Canary/133.0.6932.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/133.0.6932.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/133.0.6932.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/133.0.6932.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/133.0.6932.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204583 New version: SpecialK.SpecialK version 25.1.1.2
  manifests/s/SpecialK/SpecialK/25.1.1.2/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.2/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.2/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.1.1.2/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204492 Remove: Devicetree.dtc version 1.6.1
  manifests/d/Devicetree/dtc/1.6.1/Devicetree.dtc.installer.yaml
  manifests/d/Devicetree/dtc/1.6.1/Devicetree.dtc.locale.en-US.yaml
  manifests/d/Devicetree/dtc/1.6.1/Devicetree.dtc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204603 New version: LiErHeXun.Quicker version 1.43.57.0
  manifests/l/LiErHeXun/Quicker/1.43.57.0/LiErHeXun.Quicker.installer.yaml
  manifests/l/LiErHeXun/Quicker/1.43.57.0/LiErHeXun.Quicker.locale.en-US.yaml
  manifests/l/LiErHeXun/Quicker/1.43.57.0/LiErHeXun.Quicker.locale.zh-CN.yaml
  manifests/l/LiErHeXun/Quicker/1.43.57.0/LiErHeXun.Quicker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204605 New version: YACReader.YACReader version 9.15.0
  manifests/y/YACReader/YACReader/9.15.0/YACReader.YACReader.installer.yaml
  manifests/y/YACReader/YACReader/9.15.0/YACReader.YACReader.locale.en-US.yaml
  manifests/y/YACReader/YACReader/9.15.0/YACReader.YACReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#203896 New version: iFileSpace.iFile version 2.5.6
  manifests/i/iFileSpace/iFile/2.5.6/iFileSpace.iFile.installer.yaml
  manifests/i/iFileSpace/iFile/2.5.6/iFileSpace.iFile.locale.en-US.yaml
  manifests/i/iFileSpace/iFile/2.5.6/iFileSpace.iFile.locale.zh-CN.yaml
  manifests/i/iFileSpace/iFile/2.5.6/iFileSpace.iFile.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204550 New version: ZhaoKeli.FastGestures version 2.2.34
  manifests/z/ZhaoKeli/FastGestures/2.2.34/ZhaoKeli.FastGestures.installer.yaml
  manifests/z/ZhaoKeli/FastGestures/2.2.34/ZhaoKeli.FastGestures.locale.en-US.yaml
  manifests/z/ZhaoKeli/FastGestures/2.2.34/ZhaoKeli.FastGestures.locale.zh-CN.yaml
  manifests/z/ZhaoKeli/FastGestures/2.2.34/ZhaoKeli.FastGestures.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204617 New version: Jackett.Jackett version 0.22.1182
  manifests/j/Jackett/Jackett/0.22.1182/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1182/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1182/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204647 New version: DimitriVanHeesch.Doxygen version 1.13.1
  manifests/d/DimitriVanHeesch/Doxygen/1.13.1/DimitriVanHeesch.Doxygen.installer.yaml
  manifests/d/DimitriVanHeesch/Doxygen/1.13.1/DimitriVanHeesch.Doxygen.locale.en-US.yaml
  manifests/d/DimitriVanHeesch/Doxygen/1.13.1/DimitriVanHeesch.Doxygen.locale.zh-CN.yaml
  manifests/d/DimitriVanHeesch/Doxygen/1.13.1/DimitriVanHeesch.Doxygen.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#203385 Remove manifests/p/PurpleI2P/i2pd/2.32.0
  manifests/p/PurpleI2P/i2pd/2.32.0/PurpleI2P.i2pd.installer.yaml
  manifests/p/PurpleI2P/i2pd/2.32.0/PurpleI2P.i2pd.locale.en-US.yaml
  manifests/p/PurpleI2P/i2pd/2.32.0/PurpleI2P.i2pd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204636 New version: Xiaoyaoyixia.KOOK version 0.91.3
  manifests/x/Xiaoyaoyixia/KOOK/0.91.3/Xiaoyaoyixia.KOOK.installer.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.3/Xiaoyaoyixia.KOOK.locale.en-US.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.3/Xiaoyaoyixia.KOOK.locale.zh-CN.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.91.3/Xiaoyaoyixia.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204630 New version: GDevelop.GDevelop version 5.5.220
  manifests/g/GDevelop/GDevelop/5.5.220/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.5.220/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.5.220/GDevelop.GDevelop.locale.zh-CN.yaml
  manifests/g/GDevelop/GDevelop/5.5.220/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204623 New version: ByteDance.Feishu version 7.34.6
  manifests/b/ByteDance/Feishu/7.34.6/ByteDance.Feishu.installer.yaml
  manifests/b/ByteDance/Feishu/7.34.6/ByteDance.Feishu.locale.en-US.yaml
  manifests/b/ByteDance/Feishu/7.34.6/ByteDance.Feishu.locale.zh-CN.yaml
  manifests/b/ByteDance/Feishu/7.34.6/ByteDance.Feishu.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204611 New version: NetEase.YoudaoPokeClass version 2.15.4
  manifests/n/NetEase/YoudaoPokeClass/2.15.4/NetEase.YoudaoPokeClass.installer.yaml
  manifests/n/NetEase/YoudaoPokeClass/2.15.4/NetEase.YoudaoPokeClass.locale.en-US.yaml
  manifests/n/NetEase/YoudaoPokeClass/2.15.4/NetEase.YoudaoPokeClass.locale.zh-CN.yaml
  manifests/n/NetEase/YoudaoPokeClass/2.15.4/NetEase.YoudaoPokeClass.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204629 New version: Brave.Brave.Beta version 132.1.74.41
  manifests/b/Brave/Brave/Beta/132.1.74.41/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/132.1.74.41/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/132.1.74.41/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/132.1.74.41/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204620 New version: Maxthon.Maxthon version 7.2.2.6200
  manifests/m/Maxthon/Maxthon/7.2.2.6200/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.6200/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.6200/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.6200/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204612 New version: ZhipuAI.ChatGLM version 1.0.72
  manifests/z/ZhipuAI/ChatGLM/1.0.72/ZhipuAI.ChatGLM.installer.yaml
  manifests/z/ZhipuAI/ChatGLM/1.0.72/ZhipuAI.ChatGLM.locale.en-US.yaml
  manifests/z/ZhipuAI/ChatGLM/1.0.72/ZhipuAI.ChatGLM.locale.zh-CN.yaml
  manifests/z/ZhipuAI/ChatGLM/1.0.72/ZhipuAI.ChatGLM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204642 New version: Sentry.sentry-cli version 2.40.0
  manifests/s/Sentry/sentry-cli/2.40.0/Sentry.sentry-cli.installer.yaml
  manifests/s/Sentry/sentry-cli/2.40.0/Sentry.sentry-cli.locale.en-US.yaml
  manifests/s/Sentry/sentry-cli/2.40.0/Sentry.sentry-cli.locale.zh-CN.yaml
  manifests/s/Sentry/sentry-cli/2.40.0/Sentry.sentry-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204632 New version: Ximalaya.XimalayaLive version 4.62.911
  manifests/x/Ximalaya/XimalayaLive/4.62.911/Ximalaya.XimalayaLive.installer.yaml
  manifests/x/Ximalaya/XimalayaLive/4.62.911/Ximalaya.XimalayaLive.locale.en-US.yaml
  manifests/x/Ximalaya/XimalayaLive/4.62.911/Ximalaya.XimalayaLive.locale.zh-CN.yaml
  manifests/x/Ximalaya/XimalayaLive/4.62.911/Ximalaya.XimalayaLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204655 New package: ChuyuTeam.DISM++ version 10.1.1002.2
  manifests/c/ChuyuTeam/DISM++/10.1.1002.2/ChuyuTeam.DISM++.installer.yaml
  manifests/c/ChuyuTeam/DISM++/10.1.1002.2/ChuyuTeam.DISM++.locale.en-US.yaml
  manifests/c/ChuyuTeam/DISM++/10.1.1002.2/ChuyuTeam.DISM++.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#204634 New version: Huawei.IdeaShare version 7.06.1.01
  manifests/h/Huawei/IdeaShare/7.06.1.01/Huawei.IdeaShare.installer.yaml
  manifests/h/Huawei/IdeaShare/7.06.1.01/Huawei.IdeaShare.locale.en-US.yaml
  manifests/h/Huawei/IdeaShare/7.06.1.01/Huawei.IdeaShare.locale.zh-CN.yaml
  manifests/h/Huawei/IdeaShare/7.06.1.01/Huawei.IdeaShare.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204631 New version: Meitu.ColorByte.Pro version 6.14.2
  manifests/m/Meitu/ColorByte/Pro/6.14.2/Meitu.ColorByte.Pro.installer.yaml
  manifests/m/Meitu/ColorByte/Pro/6.14.2/Meitu.ColorByte.Pro.locale.en-US.yaml
  manifests/m/Meitu/ColorByte/Pro/6.14.2/Meitu.ColorByte.Pro.locale.zh-CN.yaml
  manifests/m/Meitu/ColorByte/Pro/6.14.2/Meitu.ColorByte.Pro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204653 Update: KDE.Konsole version 25.03.70 (3789)
  manifests/k/KDE/Konsole/25.03.70/KDE.Konsole.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204662 New version: GDevelop.GDevelop version 5.5.221
  manifests/g/GDevelop/GDevelop/5.5.221/GDevelop.GDevelop.installer.yaml
  manifests/g/GDevelop/GDevelop/5.5.221/GDevelop.GDevelop.locale.en-US.yaml
  manifests/g/GDevelop/GDevelop/5.5.221/GDevelop.GDevelop.locale.zh-CN.yaml
  manifests/g/GDevelop/GDevelop/5.5.221/GDevelop.GDevelop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204415 Update Pokemon Trading Card Game Live
  manifests/t/ThePokemonCompany/PokemonTCGLive/1.21.0.2/ThePokemonCompany.PokemonTCGLive.locale.en-US.yaml
  manifests/t/ThePokemonCompany/PokemonTCGLive/1.21.0.2/ThePokemonCompany.PokemonTCGLive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#200909 update_manifest_installer_comptabilite_annuelle.exe
  manifests/g/GaetanSencie/Comptabiliteannuelle/1.7.0.0/GaetanSencie.Comptabiliteannuelle.installer.yaml
  manifests/g/GaetanSencie/Comptabiliteannuelle/1.7.0.0/GaetanSencie.Comptabiliteannuelle.locale.fr-BE.yaml
  manifests/g/GaetanSencie/Comptabiliteannuelle/1.7.0.0/GaetanSencie.Comptabiliteannuelle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#204444 New package: DBeaverCorp.DBeaverEnterpriseEdition version 24.3.0
  manifests/d/DBeaverCorp/DBeaverEnterpriseEdition/24.3.0/DBeaverCorp.DBeaverEnterpriseEdition.installer.yaml
  manifests/d/DBeaverCorp/DBeaverEnterpriseEdition/24.3.0/DBeaverCorp.DBeaverEnterpriseEdition.locale.en-US.yaml
  manifests/d/DBeaverCorp/DBeaverEnterpriseEdition/24.3.0/DBeaverCorp.DBeaverEnterpriseEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#204537 New package: Bose.Updater version 7.1.13.5323
  manifests/b/Bose/Updater/7.1.13.5323/Bose.Updater.installer.yaml
  manifests/b/Bose/Updater/7.1.13.5323/Bose.Updater.locale.en-US.yaml
  manifests/b/Bose/Updater/7.1.13.5323/Bose.Updater.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#204570 New version: Giorgiotani.Peazip version 10.2.0
  manifests/g/Giorgiotani/Peazip/10.2.0/Giorgiotani.Peazip.installer.yaml
  manifests/g/Giorgiotani/Peazip/10.2.0/Giorgiotani.Peazip.locale.en-US.yaml
  manifests/g/Giorgiotani/Peazip/10.2.0/Giorgiotani.Peazip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204569 New package: PaulPacifico.ShutterEncoder version 18.6
  manifests/p/PaulPacifico/ShutterEncoder/18.6/PaulPacifico.ShutterEncoder.installer.yaml
  manifests/p/PaulPacifico/ShutterEncoder/18.6/PaulPacifico.ShutterEncoder.locale.en-US.yaml
  manifests/p/PaulPacifico/ShutterEncoder/18.6/PaulPacifico.ShutterEncoder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#204577 New version: Dystroy.broot version 1.44.4
  manifests/d/Dystroy/broot/1.44.4/Dystroy.broot.installer.yaml
  manifests/d/Dystroy/broot/1.44.4/Dystroy.broot.locale.en-US.yaml
  manifests/d/Dystroy/broot/1.44.4/Dystroy.broot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204689 Standardize formatting of manifests/1/115/115Chrome/26.0.1.15
  manifests/1/115/115Chrome/26.0.1.15/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.1.15/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.1.15/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.1.15/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204686 Standardize formatting of manifests/1/115/115Chrome/25.0.4.1
  manifests/1/115/115Chrome/25.0.4.1/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/25.0.4.1/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/25.0.4.1/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/25.0.4.1/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204683 Standardize formatting of manifests/1/115/115Chrome/25.0.0.3
  manifests/1/115/115Chrome/25.0.0.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/25.0.0.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/25.0.0.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/25.0.0.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204680 Standardize formatting of manifests/1/115/115Chrome/24.3.0.3
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/24.3.0.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204670 New version: Foundry376.Mailspring version 1.15.0
  manifests/f/Foundry376/Mailspring/1.15.0/Foundry376.Mailspring.installer.yaml
  manifests/f/Foundry376/Mailspring/1.15.0/Foundry376.Mailspring.locale.en-US.yaml
  manifests/f/Foundry376/Mailspring/1.15.0/Foundry376.Mailspring.locale.zh-CN.yaml
  manifests/f/Foundry376/Mailspring/1.15.0/Foundry376.Mailspring.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204618 New package: rejetto.hfs version 0.55.0
  manifests/r/rejetto/hfs/0.55.0/rejetto.hfs.installer.yaml
  manifests/r/rejetto/hfs/0.55.0/rejetto.hfs.locale.en-US.yaml
  manifests/r/rejetto/hfs/0.55.0/rejetto.hfs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#204684 Standardize formatting of manifests/1/115/115Chrome/25.0.1.0
  manifests/1/115/115Chrome/25.0.1.0/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/25.0.1.0/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/25.0.1.0/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/25.0.1.0/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204681 Standardize formatting of manifests/1/115/115Chrome/24.4.0.2
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/24.4.0.2/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204691 Standardize formatting of manifests/1/115/115Chrome/26.0.3.3
  manifests/1/115/115Chrome/26.0.3.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.3.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.3.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.3.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204692 Standardize formatting of manifests/1/115/115Chrome/26.0.5.3
  manifests/1/115/115Chrome/26.0.5.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.5.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.5.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.5.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204694 Standardize formatting of manifests/1/115/115Chrome/26.0.7.2
  manifests/1/115/115Chrome/26.0.7.2/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.7.2/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.7.2/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.7.2/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204693 Standardize formatting of manifests/1/115/115Chrome/26.0.6.6
  manifests/1/115/115Chrome/26.0.6.6/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.6.6/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.6.6/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.6.6/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204695 Standardize formatting of manifests/1/115/115Chrome/27.0.1.6
  manifests/1/115/115Chrome/27.0.1.6/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.1.6/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.1.6/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.1.6/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204696 Standardize formatting of manifests/1/115/115Chrome/27.0.2.7
  manifests/1/115/115Chrome/27.0.2.7/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.2.7/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.2.7/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.2.7/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204697 Standardize formatting of manifests/1/115/115Chrome/27.0.3.7
  manifests/1/115/115Chrome/27.0.3.7/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.3.7/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.3.7/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.3.7/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204698 Standardize formatting of manifests/1/115/115Chrome/27.0.5.7
  manifests/1/115/115Chrome/27.0.5.7/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.5.7/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.5.7/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.5.7/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204699 Standardize formatting of manifests/1/115/115Chrome/27.0.6.3
  manifests/1/115/115Chrome/27.0.6.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.6.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.6.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.6.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204585 New version: LGUG2Z.komorebi version 0.1.32
  manifests/l/LGUG2Z/komorebi/0.1.32/LGUG2Z.komorebi.installer.yaml
  manifests/l/LGUG2Z/komorebi/0.1.32/LGUG2Z.komorebi.locale.en-US.yaml
  manifests/l/LGUG2Z/komorebi/0.1.32/LGUG2Z.komorebi.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, New-Manifest

#204571 New package: anatawa12.ALCOM version 1.0.0
  manifests/a/anatawa12/ALCOM/1.0.0/anatawa12.ALCOM.installer.yaml
  manifests/a/anatawa12/ALCOM/1.0.0/anatawa12.ALCOM.locale.en-US.yaml
  manifests/a/anatawa12/ALCOM/1.0.0/anatawa12.ALCOM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Package

#204601 New version: AmN.yasb version 1.5.2
  manifests/a/AmN/yasb/1.5.2/AmN.yasb.installer.yaml
  manifests/a/AmN/yasb/1.5.2/AmN.yasb.locale.en-US.yaml
  manifests/a/AmN/yasb/1.5.2/AmN.yasb.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#204596 New version: Squiid version 1.2.0
  manifests/i/ImaginaryInfinity/Squiid/1.2.0/ImaginaryInfinity.Squiid.installer.yaml
  manifests/i/ImaginaryInfinity/Squiid/1.2.0/ImaginaryInfinity.Squiid.locale.en-US.yaml
  manifests/i/ImaginaryInfinity/Squiid/1.2.0/ImaginaryInfinity.Squiid.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204609 New version: Mixxx.Mixxx version 2.5.0
  manifests/m/Mixxx/Mixxx/2.5.0/Mixxx.Mixxx.installer.yaml
  manifests/m/Mixxx/Mixxx/2.5.0/Mixxx.Mixxx.locale.en-US.yaml
  manifests/m/Mixxx/Mixxx/2.5.0/Mixxx.Mixxx.locale.zh-CN.yaml
  manifests/m/Mixxx/Mixxx/2.5.0/Mixxx.Mixxx.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Highest-Version-Removal

#204625 New version: Dystroy.broot version 1.44.5
  manifests/d/Dystroy/broot/1.44.5/Dystroy.broot.installer.yaml
  manifests/d/Dystroy/broot/1.44.5/Dystroy.broot.locale.en-US.yaml
  manifests/d/Dystroy/broot/1.44.5/Dystroy.broot.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204640 New version: KLayout.KLayout version 0.29.10
  manifests/k/KLayout/KLayout/0.29.10/KLayout.KLayout.installer.yaml
  manifests/k/KLayout/KLayout/0.29.10/KLayout.KLayout.locale.en-US.yaml
  manifests/k/KLayout/KLayout/0.29.10/KLayout.KLayout.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204652 New version: CheckMAL.AppCheck version 3.1.39.3
  manifests/c/CheckMAL/AppCheck/3.1.38.1/CheckMAL.AppCheck.installer.yaml
  manifests/c/CheckMAL/AppCheck/3.1.39.3/CheckMAL.AppCheck.installer.yaml
  manifests/c/CheckMAL/AppCheck/3.1.39.3/CheckMAL.AppCheck.locale.en-US.yaml
  manifests/c/CheckMAL/AppCheck/3.1.39.3/CheckMAL.AppCheck.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204341 New version: WebalexEU.WinBGP version 1.1.1
  manifests/w/WebalexEU/WinBGP/1.1.1/WebalexEU.WinBGP.installer.yaml
  manifests/w/WebalexEU/WinBGP/1.1.1/WebalexEU.WinBGP.locale.en-US.yaml
  manifests/w/WebalexEU/WinBGP/1.1.1/WebalexEU.WinBGP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#204658 New version: SpecialK.SpecialK version 25.1.2.1
  manifests/s/SpecialK/SpecialK/25.1.2.1/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.1.2.1/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.1.2.1/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.1.2.1/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204659 TopalaSoftwareSolutions.SIW version 2025.01.02.0
  manifests/t/TopalaSoftwareSolutions/SIW/2025.01.02.0/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2025.01.02.0/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2025.01.02.0/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#204700 Standardize formatting of manifests/1/115/115Chrome/27.0.7.5
  manifests/1/115/115Chrome/27.0.7.5/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.7.5/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.7.5/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.7.5/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204701 Standardize formatting of manifests/1/115/115Chrome/27.0.8.1
  manifests/1/115/115Chrome/27.0.8.1/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.8.1/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.8.1/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.8.1/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204702 Standardize formatting of manifests/1/115/115Chrome/27.0.8.2
  manifests/1/115/115Chrome/27.0.8.2/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.8.2/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.8.2/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.8.2/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204665 New package: FactSetResearchSystemsInc.FactSetWorkstation version 2016.59.083.011
  manifests/f/FactSetResearchSystemsInc/FactSetWorkstation/2016.59.083.011/FactSetResearchSystemsInc.FactSetWorkstation.installer.yaml
  manifests/f/FactSetResearchSystemsInc/FactSetWorkstation/2016.59.083.011/FactSetResearchSystemsInc.FactSetWorkstation.locale.en-US.yaml
  manifests/f/FactSetResearchSystemsInc/FactSetWorkstation/2016.59.083.011/FactSetResearchSystemsInc.FactSetWorkstation.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#204703 Standardize formatting of manifests/1/115/115Chrome/27.0.9.3
  manifests/1/115/115Chrome/27.0.9.3/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/27.0.9.3/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/27.0.9.3/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/27.0.9.3/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204666 New package: NetsoftHoldingsLLC.Hubstaff version 1.6.29
  manifests/n/NetsoftHoldingsLLC/Hubstaff/1.6.29/NetsoftHoldingsLLC.Hubstaff.installer.yaml
  manifests/n/NetsoftHoldingsLLC/Hubstaff/1.6.29/NetsoftHoldingsLLC.Hubstaff.locale.en-US.yaml
  manifests/n/NetsoftHoldingsLLC/Hubstaff/1.6.29/NetsoftHoldingsLLC.Hubstaff.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#204704 Standardize formatting of manifests/1/1zilc/FishingFunds/4.7.6
  manifests/1/1zilc/FishingFunds/4.7.6/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/4.7.6/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/4.7.6/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#204706 Standardize formatting of manifests/1/1zilc/FishingFunds/5.0.1
  manifests/1/1zilc/FishingFunds/5.0.1/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/5.0.1/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/5.0.1/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204707 Standardize formatting of manifests/1/1zilc/FishingFunds/5.1.0
  manifests/1/1zilc/FishingFunds/5.1.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/5.1.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/5.1.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204711 Standardize formatting of manifests/1/1zilc/FishingFunds/5.4.1
  manifests/1/1zilc/FishingFunds/5.4.1/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/5.4.1/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/5.4.1/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204708 Standardize formatting of manifests/1/1zilc/FishingFunds/5.2.0
  manifests/1/1zilc/FishingFunds/5.2.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/5.2.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/5.2.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204712 Standardize formatting of manifests/1/1zilc/FishingFunds/5.5.0
  manifests/1/1zilc/FishingFunds/5.5.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/5.5.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/5.5.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204740 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.650.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.650.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.650.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.650.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#204737 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.463.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.463.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.463.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.463.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#204736 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.398.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.398.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.398.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.398.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204731 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.295.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.295.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.295.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.295.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204730 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.279.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.279.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.279.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.279.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204727 Standardize formatting of manifests/3/3ll3d00d/beqdesigner/0.11.5
  manifests/3/3ll3d00d/beqdesigner/0.11.5/3ll3d00d.beqdesigner.installer.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.5/3ll3d00d.beqdesigner.locale.en-US.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.5/3ll3d00d.beqdesigner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204734 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.331.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.331.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.331.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.331.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204732 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.312.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.312.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.312.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.312.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204725 Standardize formatting of manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.20
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.20/3ll3d00d.beqdesigner.installer.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.20/3ll3d00d.beqdesigner.locale.en-US.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.20/3ll3d00d.beqdesigner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204728 Standardize formatting of manifests/3/3ll3d00d/beqdesigner/0.9.5
  manifests/3/3ll3d00d/beqdesigner/0.9.5/3ll3d00d.beqdesigner.installer.yaml
  manifests/3/3ll3d00d/beqdesigner/0.9.5/3ll3d00d.beqdesigner.locale.en-US.yaml
  manifests/3/3ll3d00d/beqdesigner/0.9.5/3ll3d00d.beqdesigner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204719 Standardize formatting of manifests/1/1zilc/FishingFunds/6.2.0
  manifests/1/1zilc/FishingFunds/6.2.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/6.2.0/1zilc.FishingFunds.locale.en-US.yaml
  manifests/1/1zilc/FishingFunds/6.2.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/6.2.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204720 Standardize formatting of manifests/1/1zilc/FishingFunds/6.2.2
  manifests/1/1zilc/FishingFunds/6.2.2/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/6.2.2/1zilc.FishingFunds.locale.en-US.yaml
  manifests/1/1zilc/FishingFunds/6.2.2/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/6.2.2/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204726 Standardize formatting of manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.22
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.22/3ll3d00d.beqdesigner.installer.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.22/3ll3d00d.beqdesigner.locale.en-US.yaml
  manifests/3/3ll3d00d/beqdesigner/0.11.0-beta.22/3ll3d00d.beqdesigner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204724 Standardize formatting of manifests/1/1zilc/FishingFunds/8.3.0
  manifests/1/1zilc/FishingFunds/8.3.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/8.3.0/1zilc.FishingFunds.locale.en-US.yaml
  manifests/1/1zilc/FishingFunds/8.3.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/8.3.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204721 Standardize formatting of manifests/1/1zilc/FishingFunds/7.3.0
  manifests/1/1zilc/FishingFunds/7.3.0/1zilc.FishingFunds.installer.yaml
  manifests/1/1zilc/FishingFunds/7.3.0/1zilc.FishingFunds.locale.en-US.yaml
  manifests/1/1zilc/FishingFunds/7.3.0/1zilc.FishingFunds.locale.zh-CN.yaml
  manifests/1/1zilc/FishingFunds/7.3.0/1zilc.FishingFunds.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204675 Version Update: Morpheus.Bazarr version 1.5.1
  manifests/m/Morpheus/Bazarr/1.5.0/Morpheus.Bazarr.locale.en-US.yaml
  manifests/m/Morpheus/Bazarr/1.5.1/Morpheus.Bazarr.installer.yaml
  manifests/m/Morpheus/Bazarr/1.5.1/Morpheus.Bazarr.locale.en-US.yaml
  manifests/m/Morpheus/Bazarr/1.5.1/Morpheus.Bazarr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#204741 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.677.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.677.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.677.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.677.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204742 Standardize formatting of manifests/a/Anki/Anki/2.1.26
  manifests/a/Anki/Anki/2.1.26/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.26/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.26/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204743 Standardize formatting of manifests/a/Anki/Anki/2.1.28
  manifests/a/Anki/Anki/2.1.28/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.28/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.28/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204677 New version: Brave.Brave.Nightly version 132.1.75.142
  manifests/b/Brave/Brave/Nightly/132.1.75.142/Brave.Brave.Nightly.installer.yaml
  manifests/b/Brave/Brave/Nightly/132.1.75.142/Brave.Brave.Nightly.locale.en-US.yaml
  manifests/b/Brave/Brave/Nightly/132.1.75.142/Brave.Brave.Nightly.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Nightly/132.1.75.142/Brave.Brave.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204679 New version: KDE.Okular version 24.12.1 (24.12-5712)
  manifests/k/KDE/Okular/24.12.1/KDE.Okular.installer.yaml
  manifests/k/KDE/Okular/24.12.1/KDE.Okular.locale.en-US.yaml
  manifests/k/KDE/Okular/24.12.1/KDE.Okular.locale.zh-CN.yaml
  manifests/k/KDE/Okular/24.12.1/KDE.Okular.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#204738 Standardize formatting of manifests/a/Amazon/SessionManagerPlugin/1.2.553.0
  manifests/a/Amazon/SessionManagerPlugin/1.2.553.0/Amazon.SessionManagerPlugin.installer.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.553.0/Amazon.SessionManagerPlugin.locale.en-US.yaml
  manifests/a/Amazon/SessionManagerPlugin/1.2.553.0/Amazon.SessionManagerPlugin.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204746 Standardize formatting of manifests/a/Anki/Anki/2.1.43
  manifests/a/Anki/Anki/2.1.43/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.43/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.43/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204748 Standardize formatting of manifests/a/Anki/Anki/2.1.45
  manifests/a/Anki/Anki/2.1.45/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.45/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.45/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204744 Standardize formatting of manifests/a/Anki/Anki/2.1.33
  manifests/a/Anki/Anki/2.1.33/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.33/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.33/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204745 Standardize formatting of manifests/a/Anki/Anki/2.1.40
  manifests/a/Anki/Anki/2.1.40/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.40/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.40/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204690 Standardize formatting of manifests/1/115/115Chrome/26.0.2.5
  manifests/1/115/115Chrome/26.0.2.5/115.115Chrome.installer.yaml
  manifests/1/115/115Chrome/26.0.2.5/115.115Chrome.locale.en-US.yaml
  manifests/1/115/115Chrome/26.0.2.5/115.115Chrome.locale.zh-CN.yaml
  manifests/1/115/115Chrome/26.0.2.5/115.115Chrome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204749 Standardize formatting of manifests/a/Anki/Anki/2.1.46
  manifests/a/Anki/Anki/2.1.46/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.46/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.46/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204752 Standardize formatting of manifests/a/Anki/Anki/2.1.49
  manifests/a/Anki/Anki/2.1.49/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.49/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.49/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204750 Standardize formatting of manifests/a/Anki/Anki/2.1.47
  manifests/a/Anki/Anki/2.1.47/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.47/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.47/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204757 Standardize formatting of manifests/a/Anki/Anki/2.1.54
  manifests/a/Anki/Anki/2.1.54/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.54/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.54/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204759 Standardize formatting of manifests/a/Anki/Anki/2.1.56
  manifests/a/Anki/Anki/2.1.56/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.56/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.56/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204761 Standardize formatting of manifests/a/Anki/Anki/2.1.61
  manifests/a/Anki/Anki/2.1.61/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.61/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.61/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204762 Standardize formatting of manifests/a/Anki/Anki/2.1.63
  manifests/a/Anki/Anki/2.1.63/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.63/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.63/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204764 Standardize formatting of manifests/a/Anki/Anki/2.1.65
  manifests/a/Anki/Anki/2.1.65/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.65/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.65/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204765 Standardize formatting of manifests/a/Anki/Anki/2.1.66
  manifests/a/Anki/Anki/2.1.66/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/2.1.66/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/2.1.66/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204766 Standardize formatting of manifests/a/Anki/Anki/23.10.1
  manifests/a/Anki/Anki/23.10.1/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/23.10.1/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/23.10.1/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204767 Standardize formatting of manifests/a/Anki/Anki/23.10
  manifests/a/Anki/Anki/23.10/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/23.10/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/23.10/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204769 Standardize formatting of manifests/a/Anki/Anki/23.12
  manifests/a/Anki/Anki/23.12/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/23.12/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/23.12/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204773 Standardize formatting of manifests/a/Anki/Anki/24.06.2
  manifests/a/Anki/Anki/24.06.2/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/24.06.2/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/24.06.2/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204774 Standardize formatting of manifests/a/Anki/Anki/24.06.3
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/24.06.3/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204777 Standardize formatting of manifests/a/AntoineAflalo/SoundSwitch/5.0.4.31153
  manifests/a/AntoineAflalo/SoundSwitch/5.0.4.31153/AntoineAflalo.SoundSwitch.installer.yaml
  manifests/a/AntoineAflalo/SoundSwitch/5.0.4.31153/AntoineAflalo.SoundSwitch.locale.en-US.yaml
  manifests/a/AntoineAflalo/SoundSwitch/5.0.4.31153/AntoineAflalo.SoundSwitch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204775 Standardize formatting of manifests/a/Anki/Anki/24.06
  manifests/a/Anki/Anki/24.06/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/24.06/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/24.06/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204776 Standardize formatting of manifests/a/Anki/Anki/24.11
  manifests/a/Anki/Anki/24.11/Anki.Anki.installer.yaml
  manifests/a/Anki/Anki/24.11/Anki.Anki.locale.en-US.yaml
  manifests/a/Anki/Anki/24.11/Anki.Anki.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204781 Standardize formatting of manifests/a/AntoineAflalo/SoundSwitch/6.1.0.19729
  manifests/a/AntoineAflalo/SoundSwitch/6.1.0.19729/AntoineAflalo.SoundSwitch.installer.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.1.0.19729/AntoineAflalo.SoundSwitch.locale.en-US.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.1.0.19729/AntoineAflalo.SoundSwitch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204790 Standardize formatting of manifests/a/AntoineAflalo/SoundSwitch/6.4.0.0
  manifests/a/AntoineAflalo/SoundSwitch/6.4.0.0/AntoineAflalo.SoundSwitch.installer.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.4.0.0/AntoineAflalo.SoundSwitch.locale.en-US.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.4.0.0/AntoineAflalo.SoundSwitch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#204794 Standardize formatting of manifests/a/AntoineAflalo/SoundSwitch/6.5.3.0
  manifests/a/AntoineAflalo/SoundSwitch/6.5.3.0/AntoineAflalo.SoundSwitch.installer.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.5.3.0/AntoineAflalo.SoundSwitch.locale.en-US.yaml
  manifests/a/AntoineAflalo/SoundSwitch/6.5.3.0/AntoineAflalo.SoundSwitch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
