Repository microsoft/winget-pkgs, pull requests merged in 2025-09, with the labels that each got.

#287816 New version: DefangLabs.Defang 2.1.1
  manifests/d/DefangLabs/Defang/2.1.1/DefangLabs.Defang.installer.yaml
  manifests/d/DefangLabs/Defang/2.1.1/DefangLabs.Defang.locale.en-US.yaml
  manifests/d/DefangLabs/Defang/2.1.1/DefangLabs.Defang.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#288460 New version: DefangLabs.Defang 2.1.2
  manifests/d/DefangLabs/Defang/2.1.2/DefangLabs.Defang.installer.yaml
  manifests/d/DefangLabs/Defang/2.1.2/DefangLabs.Defang.locale.en-US.yaml
  manifests/d/DefangLabs/Defang/2.1.2/DefangLabs.Defang.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288668 New version: activescott.lessmsi version 2.8.0
  manifests/a/activescott/lessmsi/2.8.0/activescott.lessmsi.installer.yaml
  manifests/a/activescott/lessmsi/2.8.0/activescott.lessmsi.locale.en-US.yaml
  manifests/a/activescott/lessmsi/2.8.0/activescott.lessmsi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288801 New version: Abelssoft.YouTubeSongDownloader version 2025.25.09
  manifests/a/Abelssoft/YouTubeSongDownloader/2025.25.09/Abelssoft.YouTubeSongDownloader.installer.yaml
  manifests/a/Abelssoft/YouTubeSongDownloader/2025.25.09/Abelssoft.YouTubeSongDownloader.locale.en-US.yaml
  manifests/a/Abelssoft/YouTubeSongDownloader/2025.25.09/Abelssoft.YouTubeSongDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#287982 New version: ABB.e-Design version 1.15.0.0006
  manifests/a/ABB/e-Design/1.15.0.0006/ABB.e-Design.installer.yaml
  manifests/a/ABB/e-Design/1.15.0.0006/ABB.e-Design.locale.en-US.yaml
  manifests/a/ABB/e-Design/1.15.0.0006/ABB.e-Design.locale.zh-CN.yaml
  manifests/a/ABB/e-Design/1.15.0.0006/ABB.e-Design.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288300 New version: xpipe-io.xpipe version 18.3
  manifests/x/xpipe-io/xpipe/18.3/xpipe-io.xpipe.installer.yaml
  manifests/x/xpipe-io/xpipe/18.3/xpipe-io.xpipe.locale.en-US.yaml
  manifests/x/xpipe-io/xpipe/18.3/xpipe-io.xpipe.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288308 New version: xpipe-io.xpipe.portable version 18.3
  manifests/x/xpipe-io/xpipe/portable/18.3/xpipe-io.xpipe.portable.installer.yaml
  manifests/x/xpipe-io/xpipe/portable/18.3/xpipe-io.xpipe.portable.locale.en-US.yaml
  manifests/x/xpipe-io/xpipe/portable/18.3/xpipe-io.xpipe.portable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288784 New version: Lolle2000la.ImageSort version 2.14.4.0
  manifests/l/Lolle2000la/ImageSort/2.14.4.0/Lolle2000la.ImageSort.installer.yaml
  manifests/l/Lolle2000la/ImageSort/2.14.4.0/Lolle2000la.ImageSort.locale.de-DE.yaml
  manifests/l/Lolle2000la/ImageSort/2.14.4.0/Lolle2000la.ImageSort.locale.en-US.yaml
  manifests/l/Lolle2000la/ImageSort/2.14.4.0/Lolle2000la.ImageSort.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288806 New version: Ant Commander Pro version 5.6
  manifests/j/Japplis/AntCommander/Pro/5.6/Japplis.AntCommander.Pro.installer.yaml
  manifests/j/Japplis/AntCommander/Pro/5.6/Japplis.AntCommander.Pro.locale.en-US.yaml
  manifests/j/Japplis/AntCommander/Pro/5.6/Japplis.AntCommander.Pro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288831 Package update: TwintailTeam.TTL 1.1.2
  manifests/t/TwintailTeam/TTL/1.1.2/TwintailTeam.TTL.installer.yaml
  manifests/t/TwintailTeam/TTL/1.1.2/TwintailTeam.TTL.locale.en-US.yaml
  manifests/t/TwintailTeam/TTL/1.1.2/TwintailTeam.TTL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288754 New version: Google.GoogleUpdater version 141.0.7376.0
  manifests/g/Google/GoogleUpdater/141.0.7376.0/Google.GoogleUpdater.installer.yaml
  manifests/g/Google/GoogleUpdater/141.0.7376.0/Google.GoogleUpdater.locale.en-US.yaml
  manifests/g/Google/GoogleUpdater/141.0.7376.0/Google.GoogleUpdater.locale.zh-CN.yaml
  manifests/g/Google/GoogleUpdater/141.0.7376.0/Google.GoogleUpdater.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288877 New version: LobeHub.LobeHub version 1.120.4
  manifests/l/LobeHub/LobeHub/1.120.4/LobeHub.LobeHub.installer.yaml
  manifests/l/LobeHub/LobeHub/1.120.4/LobeHub.LobeHub.locale.en-US.yaml
  manifests/l/LobeHub/LobeHub/1.120.4/LobeHub.LobeHub.locale.zh-CN.yaml
  manifests/l/LobeHub/LobeHub/1.120.4/LobeHub.LobeHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288775 New version: Insco.FaFaRunner version 2.5.6
  manifests/i/Insco/FaFaRunner/2.5.6/Insco.FaFaRunner.installer.yaml
  manifests/i/Insco/FaFaRunner/2.5.6/Insco.FaFaRunner.locale.en-US.yaml
  manifests/i/Insco/FaFaRunner/2.5.6/Insco.FaFaRunner.locale.zh-CN.yaml
  manifests/i/Insco/FaFaRunner/2.5.6/Insco.FaFaRunner.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288886 New version: NetEase.MailMaster version 5.4.3.1012
  manifests/n/NetEase/MailMaster/5.4.3.1012/NetEase.MailMaster.installer.yaml
  manifests/n/NetEase/MailMaster/5.4.3.1012/NetEase.MailMaster.locale.en-US.yaml
  manifests/n/NetEase/MailMaster/5.4.3.1012/NetEase.MailMaster.locale.zh-CN.yaml
  manifests/n/NetEase/MailMaster/5.4.3.1012/NetEase.MailMaster.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288786 New version: mikf.gallery-dl.Nightly version 2025.08.31
  manifests/m/mikf/gallery-dl/Nightly/2025.08.31/mikf.gallery-dl.Nightly.installer.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.08.31/mikf.gallery-dl.Nightly.locale.en-US.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.08.31/mikf.gallery-dl.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288837 New version: vim.vim.nightly version 9.1.1723
  manifests/v/vim/vim/nightly/9.1.1723/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.1723/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.1723/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288901 New version: LobeHub.LobeHub version 1.120.5
  manifests/l/LobeHub/LobeHub/1.120.5/LobeHub.LobeHub.installer.yaml
  manifests/l/LobeHub/LobeHub/1.120.5/LobeHub.LobeHub.locale.en-US.yaml
  manifests/l/LobeHub/LobeHub/1.120.5/LobeHub.LobeHub.locale.zh-CN.yaml
  manifests/l/LobeHub/LobeHub/1.120.5/LobeHub.LobeHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288890 New package: AceBIT.PasswordDepotEnterpriseServer.18 version 18.1.0
  manifests/a/AceBIT/PasswordDepotEnterpriseServer/18/18.1.0/AceBIT.PasswordDepotEnterpriseServer.18.installer.yaml
  manifests/a/AceBIT/PasswordDepotEnterpriseServer/18/18.1.0/AceBIT.PasswordDepotEnterpriseServer.18.locale.en-US.yaml
  manifests/a/AceBIT/PasswordDepotEnterpriseServer/18/18.1.0/AceBIT.PasswordDepotEnterpriseServer.18.locale.zh-CN.yaml
  manifests/a/AceBIT/PasswordDepotEnterpriseServer/18/18.1.0/AceBIT.PasswordDepotEnterpriseServer.18.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#285795 New version: vim.vim version 9.1.1663
  manifests/v/vim/vim/9.1.1663/vim.vim.installer.yaml
  manifests/v/vim/vim/9.1.1663/vim.vim.locale.en-US.yaml
  manifests/v/vim/vim/9.1.1663/vim.vim.locale.zh-CN.yaml
  manifests/v/vim/vim/9.1.1663/vim.vim.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#284810 New package: PentaLogix.ViewMate version 11.24.50
  manifests/p/PentaLogix/ViewMate/11.24.50/PentaLogix.ViewMate.installer.yaml
  manifests/p/PentaLogix/ViewMate/11.24.50/PentaLogix.ViewMate.locale.en-US.yaml
  manifests/p/PentaLogix/ViewMate/11.24.50/PentaLogix.ViewMate.yaml
Labels: Validation-Unattended-Failed, Moderator-Approved, Needs-Attention, Needs-Manual-Merge

#288919 Update: Seafuture.NetpasEstimatorTramper version 5.2 (5.2.7.6)
  manifests/s/Seafuture/NetpasEstimatorTramper/5.2/Seafuture.NetpasEstimatorTramper.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#287017 New version: MartiCliment.UniGetUI version 3.3.2
  manifests/m/MartiCliment/UniGetUI/3.3.2/MartiCliment.UniGetUI.installer.yaml
  manifests/m/MartiCliment/UniGetUI/3.3.2/MartiCliment.UniGetUI.locale.en-US.yaml
  manifests/m/MartiCliment/UniGetUI/3.3.2/MartiCliment.UniGetUI.yaml
Labels: Azure-Pipeline-Passed, Validation-No-Executables, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#288568 Update version: yt-dlp.FFmpeg.Shared version N-120424-g03b9180fe3-20250731
  manifests/y/yt-dlp/FFmpeg/Shared/N-120424-g03b9180fe3-20250731/yt-dlp.FFmpeg.Shared.installer.yaml
  manifests/y/yt-dlp/FFmpeg/Shared/N-120424-g03b9180fe3-20250731/yt-dlp.FFmpeg.Shared.locale.en-US.yaml
  manifests/y/yt-dlp/FFmpeg/Shared/N-120424-g03b9180fe3-20250731/yt-dlp.FFmpeg.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Executable-Error, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#288569 Update version: yt-dlp.FFmpeg.Shared version N-120063-g5bcff199d9-20250630
  manifests/y/yt-dlp/FFmpeg/Shared/N-120063-g5bcff199d9-20250630/yt-dlp.FFmpeg.Shared.installer.yaml
  manifests/y/yt-dlp/FFmpeg/Shared/N-120063-g5bcff199d9-20250630/yt-dlp.FFmpeg.Shared.locale.en-US.yaml
  manifests/y/yt-dlp/FFmpeg/Shared/N-120063-g5bcff199d9-20250630/yt-dlp.FFmpeg.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Executable-Error, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#288781 New version: XTLS.Xray-core version 25.8.31
  manifests/x/XTLS/Xray-core/25.8.31/XTLS.Xray-core.installer.yaml
  manifests/x/XTLS/Xray-core/25.8.31/XTLS.Xray-core.locale.en-US.yaml
  manifests/x/XTLS/Xray-core/25.8.31/XTLS.Xray-core.yaml
Labels: Azure-Pipeline-Passed, Policy-Test-2.7, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#288958 New version: OpenAgentPlatform.Dive version 0.9.4
  manifests/o/OpenAgentPlatform/Dive/0.9.4/OpenAgentPlatform.Dive.installer.yaml
  manifests/o/OpenAgentPlatform/Dive/0.9.4/OpenAgentPlatform.Dive.locale.en-US.yaml
  manifests/o/OpenAgentPlatform/Dive/0.9.4/OpenAgentPlatform.Dive.locale.zh-CN.yaml
  manifests/o/OpenAgentPlatform/Dive/0.9.4/OpenAgentPlatform.Dive.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#286412 Update NDI.NDITools to 6.2.1.0
  manifests/n/NDI/NDITools/6.2.1.0/NDI.NDITools.installer.yaml
  manifests/n/NDI/NDITools/6.2.1.0/NDI.NDITools.locale.en-US.yaml
  manifests/n/NDI/NDITools/6.2.1.0/NDI.NDITools.yaml
Labels: Retry-1, Moderator-Approved, Needs-Attention, Needs-Manual-Merge

#288913 New version: Bandisoft.BandiView version 7.21 (30568)
  manifests/b/Bandisoft/BandiView/7.21/Bandisoft.BandiView.installer.yaml
  manifests/b/Bandisoft/BandiView/7.21/Bandisoft.BandiView.locale.en-US.yaml
  manifests/b/Bandisoft/BandiView/7.21/Bandisoft.BandiView.locale.zh-CN.yaml
  manifests/b/Bandisoft/BandiView/7.21/Bandisoft.BandiView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288903 TeraTermProject.teraterm version 4.105
  manifests/t/TeraTermProject/teraterm/4.105/TeraTermProject.teraterm.installer.yaml
  manifests/t/TeraTermProject/teraterm/4.105/TeraTermProject.teraterm.locale.en-US.yaml
  manifests/t/TeraTermProject/teraterm/4.105/TeraTermProject.teraterm.locale.ja-JP.yaml
  manifests/t/TeraTermProject/teraterm/4.105/TeraTermProject.teraterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288880 New version: Revopoint.RevoScan.MetroX version 5.6.9.274
  manifests/r/Revopoint/RevoScan/MetroX/5.6.9.274/Revopoint.RevoScan.MetroX.installer.yaml
  manifests/r/Revopoint/RevoScan/MetroX/5.6.9.274/Revopoint.RevoScan.MetroX.locale.en-US.yaml
  manifests/r/Revopoint/RevoScan/MetroX/5.6.9.274/Revopoint.RevoScan.MetroX.locale.zh-CN.yaml
  manifests/r/Revopoint/RevoScan/MetroX/5.6.9.274/Revopoint.RevoScan.MetroX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288982 Submitting HttpMaster PRO 6.2.1
  manifests/b/Borvid/HttpMasterProfessional/6.2.1/Borvid.HttpMasterProfessional.installer.yaml
  manifests/b/Borvid/HttpMasterProfessional/6.2.1/Borvid.HttpMasterProfessional.locale.en-US.yaml
  manifests/b/Borvid/HttpMasterProfessional/6.2.1/Borvid.HttpMasterProfessional.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Attention, Needs-Manual-Merge, New-Manifest

#288923 Update version: GitButler.GitButler version 0.15.17
  manifests/g/GitButler/GitButler/0.15.17/GitButler.GitButler.installer.yaml
  manifests/g/GitButler/GitButler/0.15.17/GitButler.GitButler.locale.en-US.yaml
  manifests/g/GitButler/GitButler/0.15.17/GitButler.GitButler.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288931 Update: KDE.Kapman version master (731)
  manifests/k/KDE/Kapman/master/KDE.Kapman.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288867 New Version: sourcegit-scm.SourceGit version 2025.33
  manifests/s/sourcegit-scm/SourceGit/2025.33/sourcegit-scm.SourceGit.installer.yaml
  manifests/s/sourcegit-scm/SourceGit/2025.33/sourcegit-scm.SourceGit.locale.en-US.yaml
  manifests/s/sourcegit-scm/SourceGit/2025.33/sourcegit-scm.SourceGit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288986 Update: KDE.Dolphin version 25.08.0 (25.08-6325)
  manifests/k/KDE/Dolphin/25.08.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved

#288905 TeraTermProject.teraterm version 4.107
  manifests/t/TeraTermProject/teraterm/4.107/TeraTermProject.teraterm.installer.yaml
  manifests/t/TeraTermProject/teraterm/4.107/TeraTermProject.teraterm.locale.en-US.yaml
  manifests/t/TeraTermProject/teraterm/4.107/TeraTermProject.teraterm.locale.ja-JP.yaml
  manifests/t/TeraTermProject/teraterm/4.107/TeraTermProject.teraterm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288879 Update version: B-trust.BISS version 3.44
  manifests/b/B-trust/BISS/3.44/B-trust.BISS.installer.yaml
  manifests/b/B-trust/BISS/3.44/B-trust.BISS.locale.en-US.yaml
  manifests/b/B-trust/BISS/3.44/B-trust.BISS.locale.ru-RU.yaml
  manifests/b/B-trust/BISS/3.44/B-trust.BISS.locale.zh-CN.yaml
  manifests/b/B-trust/BISS/3.44/B-trust.BISS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289019 Remove version: yt-dlp.yt-dlp.nightly version 2025.06.30.233919
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.30.233919/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.30.233919/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.30.233919/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288992 Update manifest: ClashVergeRev.ClashVergeRev version 2.4.1
  manifests/c/ClashVergeRev/ClashVergeRev/2.4.1/ClashVergeRev.ClashVergeRev.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289012 New version: JFrog.Conan version 2.20.0
  manifests/j/JFrog/Conan/2.20.0/JFrog.Conan.installer.yaml
  manifests/j/JFrog/Conan/2.20.0/JFrog.Conan.locale.en-US.yaml
  manifests/j/JFrog/Conan/2.20.0/JFrog.Conan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#288866 New version: TGRMNSoftware.BulkRenameUtility version 4.1.0.0
  manifests/t/TGRMNSoftware/BulkRenameUtility/4.1.0.0/TGRMNSoftware.BulkRenameUtility.installer.yaml
  manifests/t/TGRMNSoftware/BulkRenameUtility/4.1.0.0/TGRMNSoftware.BulkRenameUtility.locale.en-US.yaml
  manifests/t/TGRMNSoftware/BulkRenameUtility/4.1.0.0/TGRMNSoftware.BulkRenameUtility.locale.zh-CN.yaml
  manifests/t/TGRMNSoftware/BulkRenameUtility/4.1.0.0/TGRMNSoftware.BulkRenameUtility.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289018 Remove version: yt-dlp.yt-dlp.nightly version 2025.06.29.233002
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.29.233002/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.29.233002/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.06.29.233002/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289016 Remove version: yt-dlp.yt-dlp.nightly version 2025.07.08.233037
  manifests/y/yt-dlp/yt-dlp/nightly/2025.07.08.233037/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.07.08.233037/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.07.08.233037/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289057 Update: Mozilla.Firefox.DeveloperEdition.ach version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ach/143.0/Mozilla.Firefox.DeveloperEdition.ach.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ach/143.0/Mozilla.Firefox.DeveloperEdition.ach.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289118 Update: Mozilla.Firefox.DeveloperEdition.mk version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/mk/143.0/Mozilla.Firefox.DeveloperEdition.mk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289124 Update: Mozilla.Firefox.DeveloperEdition.nl version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nl/143.0/Mozilla.Firefox.DeveloperEdition.nl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289138 Update: Mozilla.Firefox.DeveloperEdition.sl version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sl/143.0/Mozilla.Firefox.DeveloperEdition.sl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289049 Remove version: Google.Chrome.Canary version 141.0.7363.0
  manifests/g/Google/Chrome/Canary/141.0.7363.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/141.0.7363.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/141.0.7363.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/141.0.7363.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/141.0.7363.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289089 Update: Mozilla.Firefox.DeveloperEdition.fi version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fi/143.0/Mozilla.Firefox.DeveloperEdition.fi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289061 Update: Mozilla.Firefox.DeveloperEdition.ast version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ast/143.0/Mozilla.Firefox.DeveloperEdition.ast.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289091 Update: Mozilla.Firefox.DeveloperEdition.fur version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fur/143.0/Mozilla.Firefox.DeveloperEdition.fur.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289156 Update: Mozilla.Firefox.DeveloperEdition.xh version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/xh/143.0/Mozilla.Firefox.DeveloperEdition.xh.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288899 New version: Jackett.Jackett version 0.22.2390
  manifests/j/Jackett/Jackett/0.22.2390/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.2390/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.2390/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#288998 New version: PCTI.Docman.GP version 10.2.255.3
  manifests/p/PCTI/Docman/GP/10.2.255.3/PCTI.Docman.GP.installer.yaml
  manifests/p/PCTI/Docman/GP/10.2.255.3/PCTI.Docman.GP.locale.en-US.yaml
  manifests/p/PCTI/Docman/GP/10.2.255.3/PCTI.Docman.GP.locale.zh-CN.yaml
  manifests/p/PCTI/Docman/GP/10.2.255.3/PCTI.Docman.GP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Manifest

#289113 Update: Mozilla.Firefox.DeveloperEdition.kn version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kn/143.0/Mozilla.Firefox.DeveloperEdition.kn.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288916 New version: HaiYing.AionUi version 1.1.6
  manifests/h/HaiYing/AionUi/1.1.6/HaiYing.AionUi.installer.yaml
  manifests/h/HaiYing/AionUi/1.1.6/HaiYing.AionUi.locale.en-US.yaml
  manifests/h/HaiYing/AionUi/1.1.6/HaiYing.AionUi.locale.zh-CN.yaml
  manifests/h/HaiYing/AionUi/1.1.6/HaiYing.AionUi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289062 Update: Mozilla.Firefox.DeveloperEdition.az version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/az/143.0/Mozilla.Firefox.DeveloperEdition.az.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289084 Update: Mozilla.Firefox.DeveloperEdition.es-MX version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-MX/143.0/Mozilla.Firefox.DeveloperEdition.es-MX.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289097 Update: Mozilla.Firefox.DeveloperEdition.gu-IN version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/gu-IN/143.0/Mozilla.Firefox.DeveloperEdition.gu-IN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288927 New version: HulubuluSoftware.AdvancedRenamer version 4.16
  manifests/h/HulubuluSoftware/AdvancedRenamer/4.16/HulubuluSoftware.AdvancedRenamer.installer.yaml
  manifests/h/HulubuluSoftware/AdvancedRenamer/4.16/HulubuluSoftware.AdvancedRenamer.locale.en-US.yaml
  manifests/h/HulubuluSoftware/AdvancedRenamer/4.16/HulubuluSoftware.AdvancedRenamer.locale.zh-CN.yaml
  manifests/h/HulubuluSoftware/AdvancedRenamer/4.16/HulubuluSoftware.AdvancedRenamer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289077 New version: PeterPawlowski.foobar2000 version 2.25
  manifests/p/PeterPawlowski/foobar2000/2.25/PeterPawlowski.foobar2000.installer.yaml
  manifests/p/PeterPawlowski/foobar2000/2.25/PeterPawlowski.foobar2000.locale.en-US.yaml
  manifests/p/PeterPawlowski/foobar2000/2.25/PeterPawlowski.foobar2000.locale.zh-CN.yaml
  manifests/p/PeterPawlowski/foobar2000/2.25/PeterPawlowski.foobar2000.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288969 Update: KDE.Filelight version 25.08.0 (25.08-1861)
  manifests/k/KDE/Filelight/25.08.0/KDE.Filelight.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288962 New version: Zoom.Zoom version 6.5.14128 (6.5.12.14128)
  manifests/z/Zoom/Zoom/6.5.14128/Zoom.Zoom.installer.yaml
  manifests/z/Zoom/Zoom/6.5.14128/Zoom.Zoom.locale.en-US.yaml
  manifests/z/Zoom/Zoom/6.5.14128/Zoom.Zoom.locale.zh-CN.yaml
  manifests/z/Zoom/Zoom/6.5.14128/Zoom.Zoom.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289143 Update: Mozilla.Firefox.DeveloperEdition.szl version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/szl/143.0/Mozilla.Firefox.DeveloperEdition.szl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289110 Update: Mozilla.Firefox.DeveloperEdition.kab version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/143.0/Mozilla.Firefox.DeveloperEdition.kab.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289135 Update: Mozilla.Firefox.DeveloperEdition.sco version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sco/143.0/Mozilla.Firefox.DeveloperEdition.sco.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289059 Update: Mozilla.Firefox.DeveloperEdition.an version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/an/143.0/Mozilla.Firefox.DeveloperEdition.an.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289090 Update: Mozilla.Firefox.DeveloperEdition.fr version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fr/143.0/Mozilla.Firefox.DeveloperEdition.fr.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289072 Update: Mozilla.Firefox.DeveloperEdition.cy version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/cy/143.0/Mozilla.Firefox.DeveloperEdition.cy.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289010 New version: Nethermind.Nethermind version 1.33.0
  manifests/n/Nethermind/Nethermind/1.33.0/Nethermind.Nethermind.installer.yaml
  manifests/n/Nethermind/Nethermind/1.33.0/Nethermind.Nethermind.locale.en-US.yaml
  manifests/n/Nethermind/Nethermind/1.33.0/Nethermind.Nethermind.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288918 New version: Opera.OperaGX version 121.0.5600.47
  manifests/o/Opera/OperaGX/121.0.5600.47/Opera.OperaGX.installer.yaml
  manifests/o/Opera/OperaGX/121.0.5600.47/Opera.OperaGX.locale.en-US.yaml
  manifests/o/Opera/OperaGX/121.0.5600.47/Opera.OperaGX.locale.zh-CN.yaml
  manifests/o/Opera/OperaGX/121.0.5600.47/Opera.OperaGX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288930 Update: KDE.Granatier version master (755)
  manifests/k/KDE/Granatier/master/KDE.Granatier.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288960 New version: Tencent.QQMusic version 21.80
  manifests/t/Tencent/QQMusic/21.80/Tencent.QQMusic.installer.yaml
  manifests/t/Tencent/QQMusic/21.80/Tencent.QQMusic.locale.en-US.yaml
  manifests/t/Tencent/QQMusic/21.80/Tencent.QQMusic.locale.zh-CN.yaml
  manifests/t/Tencent/QQMusic/21.80/Tencent.QQMusic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#289045 Update manifest: Auslogics.BitReplica version 2.6.0.2
  manifests/a/Auslogics/BitReplica/2.6.0.2/Auslogics.BitReplica.installer.yaml
  manifests/a/Auslogics/BitReplica/2.6.0.2/Auslogics.BitReplica.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289066 Update: Mozilla.Firefox.DeveloperEdition.br version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/br/143.0/Mozilla.Firefox.DeveloperEdition.br.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289189 New version: Google.Chrome.Canary version 141.0.7389.0
  manifests/g/Google/Chrome/Canary/141.0.7389.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/141.0.7389.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/141.0.7389.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/141.0.7389.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/141.0.7389.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288944 Update: KDE.Klines version master (714)
  manifests/k/KDE/Klines/master/KDE.Klines.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288860 New version: EEO.ClassIn version 6.0.3.2341
  manifests/e/EEO/ClassIn/6.0.3.2341/EEO.ClassIn.installer.yaml
  manifests/e/EEO/ClassIn/6.0.3.2341/EEO.ClassIn.locale.en-US.yaml
  manifests/e/EEO/ClassIn/6.0.3.2341/EEO.ClassIn.locale.zh-CN.yaml
  manifests/e/EEO/ClassIn/6.0.3.2341/EEO.ClassIn.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#289125 Update: Mozilla.Firefox.DeveloperEdition.nn-NO version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nn-NO/143.0/Mozilla.Firefox.DeveloperEdition.nn-NO.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289150 Update: Mozilla.Firefox.DeveloperEdition.trs version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/trs/143.0/Mozilla.Firefox.DeveloperEdition.trs.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289103 Update: Mozilla.Firefox.DeveloperEdition.hy-AM version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hy-AM/143.0/Mozilla.Firefox.DeveloperEdition.hy-AM.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288856 New version: Forkgram.Forkgram version 6.1.0
  manifests/f/Forkgram/Forkgram/6.1.0/Forkgram.Forkgram.installer.yaml
  manifests/f/Forkgram/Forkgram/6.1.0/Forkgram.Forkgram.locale.en-US.yaml
  manifests/f/Forkgram/Forkgram/6.1.0/Forkgram.Forkgram.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288924 New version: Microsoft.VisualStudioCode.Insiders version 1.104.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.104.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#288957 New version: HearthSim.HearthstoneDeckTracker version 1.46.13
  manifests/h/HearthSim/HearthstoneDeckTracker/1.46.13/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.46.13/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.46.13/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289200 Remove version: NirSoft.WifiInfoView version 2.96
  manifests/n/NirSoft/WifiInfoView/2.96/NirSoft.WifiInfoView.installer.yaml
  manifests/n/NirSoft/WifiInfoView/2.96/NirSoft.WifiInfoView.locale.en-US.yaml
  manifests/n/NirSoft/WifiInfoView/2.96/NirSoft.WifiInfoView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289069 Update: Mozilla.Firefox.DeveloperEdition.ca version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ca/143.0/Mozilla.Firefox.DeveloperEdition.ca.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289213 Update: KDE.NeoChat version 25.08.0 (25.08-13077)
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289032 New version: Snijderlab.Annotator version 1.2.1
  manifests/s/Snijderlab/Annotator/1.2.1/Snijderlab.Annotator.installer.yaml
  manifests/s/Snijderlab/Annotator/1.2.1/Snijderlab.Annotator.locale.en-US.yaml
  manifests/s/Snijderlab/Annotator/1.2.1/Snijderlab.Annotator.locale.zh-CN.yaml
  manifests/s/Snijderlab/Annotator/1.2.1/Snijderlab.Annotator.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288878 New version: Nvidia.GeForceNow version 2.0.77.162
  manifests/n/Nvidia/GeForceNow/2.0.77.162/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.77.162/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.77.162/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.77.162/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289076 Update: Mozilla.Firefox.DeveloperEdition.el version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/el/143.0/Mozilla.Firefox.DeveloperEdition.el.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289154 Update: Mozilla.Firefox.DeveloperEdition.uz version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/uz/143.0/Mozilla.Firefox.DeveloperEdition.uz.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288888 Update version: Oven-sh.Bun.Profile version 1.2.21
  manifests/o/Oven-sh/Bun/Profile/1.2.21/Oven-sh.Bun.Profile.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289028 New version: Sidero.omnictl version 1.1.3
  manifests/s/Sidero/omnictl/1.1.3/Sidero.omnictl.installer.yaml
  manifests/s/Sidero/omnictl/1.1.3/Sidero.omnictl.locale.en-US.yaml
  manifests/s/Sidero/omnictl/1.1.3/Sidero.omnictl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289197 New version: Sidero.talosctl version 1.11.0
  manifests/s/Sidero/talosctl/1.11.0/Sidero.talosctl.installer.yaml
  manifests/s/Sidero/talosctl/1.11.0/Sidero.talosctl.locale.en-US.yaml
  manifests/s/Sidero/talosctl/1.11.0/Sidero.talosctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289216 Remove MSI Version of DuoSecurity.Duo2FAAuthenticationforWindows
  manifests/d/DuoSecurity/Duo2FAAuthenticationforWindows/MSI/5.0.0.312/DuoSecurity.Duo2FAAuthenticationforWindows.MSI.installer.yaml
  manifests/d/DuoSecurity/Duo2FAAuthenticationforWindows/MSI/5.0.0.312/DuoSecurity.Duo2FAAuthenticationforWindows.MSI.locale.en-US.yaml
  manifests/d/DuoSecurity/Duo2FAAuthenticationforWindows/MSI/5.0.0.312/DuoSecurity.Duo2FAAuthenticationforWindows.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289218 New version: GAM-Team.gam version 7.20.02
  manifests/g/GAM-Team/gam/7.20.02/GAM-Team.gam.installer.yaml
  manifests/g/GAM-Team/gam/7.20.02/GAM-Team.gam.locale.en-US.yaml
  manifests/g/GAM-Team/gam/7.20.02/GAM-Team.gam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289104 Update: Mozilla.Firefox.DeveloperEdition.ia version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ia/143.0/Mozilla.Firefox.DeveloperEdition.ia.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289148 Update: Mozilla.Firefox.DeveloperEdition.tl version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/tl/143.0/Mozilla.Firefox.DeveloperEdition.tl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289065 Update: Mozilla.Firefox.DeveloperEdition.bn version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bn/143.0/Mozilla.Firefox.DeveloperEdition.bn.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289211 Remove version: BandicamCompany.Bandicam2024 version 7.1.7.2462
  manifests/b/BandicamCompany/Bandicam2024/7.1.7.2462/BandicamCompany.Bandicam2024.installer.yaml
  manifests/b/BandicamCompany/Bandicam2024/7.1.7.2462/BandicamCompany.Bandicam2024.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam2024/7.1.7.2462/BandicamCompany.Bandicam2024.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289011 New version: 3TSoftwareLabs.Studio3T version 2025.15.1
  manifests/3/3TSoftwareLabs/Studio3T/2025.15.1/3TSoftwareLabs.Studio3T.installer.yaml
  manifests/3/3TSoftwareLabs/Studio3T/2025.15.1/3TSoftwareLabs.Studio3T.locale.en-US.yaml
  manifests/3/3TSoftwareLabs/Studio3T/2025.15.1/3TSoftwareLabs.Studio3T.locale.zh-CN.yaml
  manifests/3/3TSoftwareLabs/Studio3T/2025.15.1/3TSoftwareLabs.Studio3T.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#288941 Update: KDE.Kiriki version master (679)
  manifests/k/KDE/Kiriki/master/KDE.Kiriki.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289229 Remove version: BandicamCompany.Bandicut version 4.1.0.2526
  manifests/b/BandicamCompany/Bandicut/4.1.0.2526/BandicamCompany.Bandicut.installer.yaml
  manifests/b/BandicamCompany/Bandicut/4.1.0.2526/BandicamCompany.Bandicut.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicut/4.1.0.2526/BandicamCompany.Bandicut.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289261 New version: SST.opencode version 0.6.3
  manifests/s/SST/opencode/0.6.3/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.6.3/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.6.3/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.6.3/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289255 Update version: GrafanaLabs.Grafana.Enterprise version 12.0.2
  manifests/g/GrafanaLabs/Grafana/Enterprise/12.0.2/GrafanaLabs.Grafana.Enterprise.installer.yaml
  manifests/g/GrafanaLabs/Grafana/Enterprise/12.0.2/GrafanaLabs.Grafana.Enterprise.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289257 Update version: GrafanaLabs.Grafana.Enterprise version 12.0.1
  manifests/g/GrafanaLabs/Grafana/Enterprise/12.0.1/GrafanaLabs.Grafana.Enterprise.installer.yaml
  manifests/g/GrafanaLabs/Grafana/Enterprise/12.0.1/GrafanaLabs.Grafana.Enterprise.locale.en-US.yaml
  manifests/g/GrafanaLabs/Grafana/Enterprise/12.0.1/GrafanaLabs.Grafana.Enterprise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289267 Remove version: eask.cli version 0.11.5 (Auto)
  manifests/e/eask/cli/0.11.5/eask.cli.installer.yaml
  manifests/e/eask/cli/0.11.5/eask.cli.locale.en-US.yaml
  manifests/e/eask/cli/0.11.5/eask.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289236 New version: AtomicJar.Testcontainers version 1.22.0
  manifests/a/AtomicJar/Testcontainers/1.21.0/AtomicJar.Testcontainers.locale.en-US.yaml
  manifests/a/AtomicJar/Testcontainers/1.22.0/AtomicJar.Testcontainers.installer.yaml
  manifests/a/AtomicJar/Testcontainers/1.22.0/AtomicJar.Testcontainers.locale.en-US.yaml
  manifests/a/AtomicJar/Testcontainers/1.22.0/AtomicJar.Testcontainers.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#284471 New package: FujiApple.Claptrap version 0.3.0
  manifests/f/FujiApple/Claptrap/0.3.0/FujiApple.Claptrap.installer.yaml
  manifests/f/FujiApple/Claptrap/0.3.0/FujiApple.Claptrap.locale.en-US.yaml
  manifests/f/FujiApple/Claptrap/0.3.0/FujiApple.Claptrap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#288929 Update: KDE.Bovo version master (697)
  manifests/k/KDE/Bovo/master/KDE.Bovo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289079 Update: Mozilla.Firefox.DeveloperEdition.en-GB version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/en-GB/143.0/Mozilla.Firefox.DeveloperEdition.en-GB.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#286705 New version: sjzar.Chatlog version 0.0.23
  manifests/s/sjzar/Chatlog/0.0.23/sjzar.Chatlog.installer.yaml
  manifests/s/sjzar/Chatlog/0.0.23/sjzar.Chatlog.locale.en-US.yaml
  manifests/s/sjzar/Chatlog/0.0.23/sjzar.Chatlog.locale.zh-CN.yaml
  manifests/s/sjzar/Chatlog/0.0.23/sjzar.Chatlog.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289060 Update: Mozilla.Firefox.DeveloperEdition.ar version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ar/143.0/Mozilla.Firefox.DeveloperEdition.ar.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289153 Update: Mozilla.Firefox.DeveloperEdition.ur version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ur/143.0/Mozilla.Firefox.DeveloperEdition.ur.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288959 New version: Surfshark.Surfshark version 6.1.0.999
  manifests/s/Surfshark/Surfshark/6.1.0.999/Surfshark.Surfshark.installer.yaml
  manifests/s/Surfshark/Surfshark/6.1.0.999/Surfshark.Surfshark.locale.en-US.yaml
  manifests/s/Surfshark/Surfshark/6.1.0.999/Surfshark.Surfshark.locale.zh-CN.yaml
  manifests/s/Surfshark/Surfshark/6.1.0.999/Surfshark.Surfshark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289038 New version: zkSNACKs.WasabiWallet version 2.7.0
  manifests/z/zkSNACKs/WasabiWallet/2.7.0/zkSNACKs.WasabiWallet.installer.yaml
  manifests/z/zkSNACKs/WasabiWallet/2.7.0/zkSNACKs.WasabiWallet.locale.en-US.yaml
  manifests/z/zkSNACKs/WasabiWallet/2.7.0/zkSNACKs.WasabiWallet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289305 New version: LobeHub.LobeHub version 1.120.7
  manifests/l/LobeHub/LobeHub/1.120.7/LobeHub.LobeHub.installer.yaml
  manifests/l/LobeHub/LobeHub/1.120.7/LobeHub.LobeHub.locale.en-US.yaml
  manifests/l/LobeHub/LobeHub/1.120.7/LobeHub.LobeHub.locale.zh-CN.yaml
  manifests/l/LobeHub/LobeHub/1.120.7/LobeHub.LobeHub.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289250 New version: Digiexam.Digiexam version 15.0.25.0
  manifests/d/Digiexam/Digiexam/15.0.25.0/Digiexam.Digiexam.installer.yaml
  manifests/d/Digiexam/Digiexam/15.0.25.0/Digiexam.Digiexam.locale.en-US.yaml
  manifests/d/Digiexam/Digiexam/15.0.25.0/Digiexam.Digiexam.locale.zh-CN.yaml
  manifests/d/Digiexam/Digiexam/15.0.25.0/Digiexam.Digiexam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289106 Update: Mozilla.Firefox.DeveloperEdition.is version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/is/143.0/Mozilla.Firefox.DeveloperEdition.is.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288912 New version: GAM-Team.gam version 7.20.00
  manifests/g/GAM-Team/gam/7.20.00/GAM-Team.gam.installer.yaml
  manifests/g/GAM-Team/gam/7.20.00/GAM-Team.gam.locale.en-US.yaml
  manifests/g/GAM-Team/gam/7.20.00/GAM-Team.gam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Manifest

#289040 New version: JanProchazka.dbgate version 6.6.3
  manifests/j/JanProchazka/dbgate/6.6.3/JanProchazka.dbgate.installer.yaml
  manifests/j/JanProchazka/dbgate/6.6.3/JanProchazka.dbgate.locale.en-US.yaml
  manifests/j/JanProchazka/dbgate/6.6.3/JanProchazka.dbgate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#289316 New version: Microsoft.VisualStudioCode.Insiders version 1.104.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.104.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288954 Update: KDE.Picmi version master (671)
  manifests/k/KDE/Picmi/master/KDE.Picmi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#288914 New version: Alibaba.UC version 1.1.0.12
  manifests/a/Alibaba/UC/1.1.0.12/Alibaba.UC.installer.yaml
  manifests/a/Alibaba/UC/1.1.0.12/Alibaba.UC.locale.en-US.yaml
  manifests/a/Alibaba/UC/1.1.0.12/Alibaba.UC.locale.zh-CN.yaml
  manifests/a/Alibaba/UC/1.1.0.12/Alibaba.UC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289005 New version: NewRelic.InfrastructureAgent version 1.67.3
  manifests/n/NewRelic/InfrastructureAgent/1.67.3/NewRelic.InfrastructureAgent.installer.yaml
  manifests/n/NewRelic/InfrastructureAgent/1.67.3/NewRelic.InfrastructureAgent.locale.en-US.yaml
  manifests/n/NewRelic/InfrastructureAgent/1.67.3/NewRelic.InfrastructureAgent.locale.zh-CN.yaml
  manifests/n/NewRelic/InfrastructureAgent/1.67.3/NewRelic.InfrastructureAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289111 Update: Mozilla.Firefox.DeveloperEdition.kk version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kk/143.0/Mozilla.Firefox.DeveloperEdition.kk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289071 Update: Mozilla.Firefox.DeveloperEdition.cs version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/cs/143.0/Mozilla.Firefox.DeveloperEdition.cs.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289093 Update: Mozilla.Firefox.DeveloperEdition.ga-IE version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ga-IE/143.0/Mozilla.Firefox.DeveloperEdition.ga-IE.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289120 Update: Mozilla.Firefox.DeveloperEdition.ms version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ms/143.0/Mozilla.Firefox.DeveloperEdition.ms.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289192 Remove version: Mozilla.Firefox.MSIX.Nightly version 144.2508.2221.0
  manifests/m/Mozilla/Firefox/MSIX/Nightly/144.2508.2221.0/Mozilla.Firefox.MSIX.Nightly.installer.yaml
  manifests/m/Mozilla/Firefox/MSIX/Nightly/144.2508.2221.0/Mozilla.Firefox.MSIX.Nightly.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/MSIX/Nightly/144.2508.2221.0/Mozilla.Firefox.MSIX.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289201 Remove version: NirSoft.SearchMyFiles version 3.31
  manifests/n/NirSoft/SearchMyFiles/3.31/NirSoft.SearchMyFiles.installer.yaml
  manifests/n/NirSoft/SearchMyFiles/3.31/NirSoft.SearchMyFiles.locale.en-US.yaml
  manifests/n/NirSoft/SearchMyFiles/3.31/NirSoft.SearchMyFiles.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289198 New version: vim.vim.nightly version 9.1.1725
  manifests/v/vim/vim/nightly/9.1.1725/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.1725/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.1725/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289134 Update: Mozilla.Firefox.DeveloperEdition.sc version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sc/143.0/Mozilla.Firefox.DeveloperEdition.sc.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289323 New version: HonhimW.Ratisui version 0.6.0
  manifests/h/HonhimW/Ratisui/0.6.0/HonhimW.Ratisui.installer.yaml
  manifests/h/HonhimW/Ratisui/0.6.0/HonhimW.Ratisui.locale.en-US.yaml
  manifests/h/HonhimW/Ratisui/0.6.0/HonhimW.Ratisui.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289321 Update: KDE.Dolphin version 25.08.0 (25.08-6346)
  manifests/k/KDE/Dolphin/25.08.0/KDE.Dolphin.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289348 New version: Opera.OperaAir version 120.0.5543.211
  manifests/o/Opera/OperaAir/120.0.5543.211/Opera.OperaAir.installer.yaml
  manifests/o/Opera/OperaAir/120.0.5543.211/Opera.OperaAir.locale.en-US.yaml
  manifests/o/Opera/OperaAir/120.0.5543.211/Opera.OperaAir.locale.zh-CN.yaml
  manifests/o/Opera/OperaAir/120.0.5543.211/Opera.OperaAir.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289114 Update: Mozilla.Firefox.DeveloperEdition.ko version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/143.0/Mozilla.Firefox.DeveloperEdition.ko.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289359 New version: MicaForEveryone.MicaForEveryone version 2.0.5.0
  manifests/m/MicaForEveryone/MicaForEveryone/2.0.5.0/MicaForEveryone.MicaForEveryone.installer.yaml
  manifests/m/MicaForEveryone/MicaForEveryone/2.0.5.0/MicaForEveryone.MicaForEveryone.locale.en-US.yaml
  manifests/m/MicaForEveryone/MicaForEveryone/2.0.5.0/MicaForEveryone.MicaForEveryone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#289096 Update: Mozilla.Firefox.DeveloperEdition.gn version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/gn/143.0/Mozilla.Firefox.DeveloperEdition.gn.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#288607 New package: w1hkj.flwkey version 1.2.3
  manifests/w/w1hkj/flwkey/1.2.3/w1hkj.flwkey.installer.yaml
  manifests/w/w1hkj/flwkey/1.2.3/w1hkj.flwkey.locale.en-US.yaml
  manifests/w/w1hkj/flwkey/1.2.3/w1hkj.flwkey.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#289063 Update: Mozilla.Firefox.DeveloperEdition.be version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/be/143.0/Mozilla.Firefox.DeveloperEdition.be.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289191 Remove version: mikf.gallery-dl.Nightly version 2025.08.13
  manifests/m/mikf/gallery-dl/Nightly/2025.08.13/mikf.gallery-dl.Nightly.installer.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.08.13/mikf.gallery-dl.Nightly.locale.en-US.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.08.13/mikf.gallery-dl.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289240 Update version: Microsoft.ServiceFabricSDK version 8.0.2707.1
  manifests/m/Microsoft/ServiceFabricSDK/8.0.2707.1/Microsoft.ServiceFabricSDK.installer.yaml
  manifests/m/Microsoft/ServiceFabricSDK/8.0.2707.1/Microsoft.ServiceFabricSDK.locale.en-US.yaml
  manifests/m/Microsoft/ServiceFabricSDK/8.0.2707.1/Microsoft.ServiceFabricSDK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289253 Update version: Ezoa.ECHOOF version 0.1.1
  manifests/e/Ezoa/ECHOOF/0.1.1/Ezoa.ECHOOF.installer.yaml
  manifests/e/Ezoa/ECHOOF/0.1.1/Ezoa.ECHOOF.locale.en-US.yaml
  manifests/e/Ezoa/ECHOOF/0.1.1/Ezoa.ECHOOF.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#289094 Update: Mozilla.Firefox.DeveloperEdition.gd version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/gd/143.0/Mozilla.Firefox.DeveloperEdition.gd.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#288977 azqr version 2.7.7-preview.2
  manifests/m/Microsoft/Azure/QuickReview/2.7.7-preview.2/Microsoft.Azure.QuickReview.installer.yaml
  manifests/m/Microsoft/Azure/QuickReview/2.7.7-preview.2/Microsoft.Azure.QuickReview.locale.en-US.yaml
  manifests/m/Microsoft/Azure/QuickReview/2.7.7-preview.2/Microsoft.Azure.QuickReview.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289360 New version: CameronSutter.Plottr version 2025.9.2
  manifests/c/CameronSutter/Plottr/2025.9.2/CameronSutter.Plottr.installer.yaml
  manifests/c/CameronSutter/Plottr/2025.9.2/CameronSutter.Plottr.locale.en-US.yaml
  manifests/c/CameronSutter/Plottr/2025.9.2/CameronSutter.Plottr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289382 New version: Invantive.InvantiveSupportAssistant version 25.0.5
  manifests/i/Invantive/InvantiveSupportAssistant/25.0.5/Invantive.InvantiveSupportAssistant.installer.yaml
  manifests/i/Invantive/InvantiveSupportAssistant/25.0.5/Invantive.InvantiveSupportAssistant.locale.en-US.yaml
  manifests/i/Invantive/InvantiveSupportAssistant/25.0.5/Invantive.InvantiveSupportAssistant.locale.zh-CN.yaml
  manifests/i/Invantive/InvantiveSupportAssistant/25.0.5/Invantive.InvantiveSupportAssistant.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#289159 Update: Mozilla.Firefox.DeveloperEdition.zh-TW version 143.0 (143.0b7)
  manifests/m/Mozilla/Firefox/DeveloperEdition/zh-TW/143.0/Mozilla.Firefox.DeveloperEdition.zh-TW.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#289025 CubeSoft.CubePDFUtility version 4.3.0
  manifests/c/CubeSoft/CubePDFUtility/4.3.0/CubeSoft.CubePDFUtility.installer.yaml
  manifests/c/CubeSoft/CubePDFUtility/4.3.0/CubeSoft.CubePDFUtility.locale.en-US.yaml
  manifests/c/CubeSoft/CubePDFUtility/4.3.0/CubeSoft.CubePDFUtility.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
