Repository microsoft/winget-pkgs, pull requests merged in 2025-03, with the labels that each got.

#233640 New version: JetBrains.MPS version 2024.3.1
  manifests/j/JetBrains/MPS/2024.3.1/JetBrains.MPS.installer.yaml
  manifests/j/JetBrains/MPS/2024.3.1/JetBrains.MPS.locale.en-US.yaml
  manifests/j/JetBrains/MPS/2024.3.1/JetBrains.MPS.locale.zh-CN.yaml
  manifests/j/JetBrains/MPS/2024.3.1/JetBrains.MPS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233644 Update: KDE.Konsole version 25.03.70 (3900)
  manifests/k/KDE/Konsole/25.03.70/KDE.Konsole.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#233645 New version: jsdelivr.Globalping version 1.5.0
  manifests/j/jsdelivr/Globalping/1.5.0/jsdelivr.Globalping.installer.yaml
  manifests/j/jsdelivr/Globalping/1.5.0/jsdelivr.Globalping.locale.en-US.yaml
  manifests/j/jsdelivr/Globalping/1.5.0/jsdelivr.Globalping.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233653 New version: Microsoft.Edge.Beta version 134.0.3124.39
  manifests/m/Microsoft/Edge/Beta/134.0.3124.39/Microsoft.Edge.Beta.installer.yaml
  manifests/m/Microsoft/Edge/Beta/134.0.3124.39/Microsoft.Edge.Beta.locale.en-US.yaml
  manifests/m/Microsoft/Edge/Beta/134.0.3124.39/Microsoft.Edge.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233654 New version: CommandLine.Wave version 0.11.1
  manifests/c/CommandLine/Wave/0.11.1/CommandLine.Wave.installer.yaml
  manifests/c/CommandLine/Wave/0.11.1/CommandLine.Wave.locale.en-US.yaml
  manifests/c/CommandLine/Wave/0.11.1/CommandLine.Wave.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233651 New version: HiroSystems.Clarinet version 2.15.1
  manifests/h/HiroSystems/Clarinet/2.15.1/HiroSystems.Clarinet.installer.yaml
  manifests/h/HiroSystems/Clarinet/2.15.1/HiroSystems.Clarinet.locale.en-US.yaml
  manifests/h/HiroSystems/Clarinet/2.15.1/HiroSystems.Clarinet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233656 New version: Formlabs.PreForm version 3.45.1.488
  manifests/f/Formlabs/PreForm/3.45.1.488/Formlabs.PreForm.installer.yaml
  manifests/f/Formlabs/PreForm/3.45.1.488/Formlabs.PreForm.locale.en-US.yaml
  manifests/f/Formlabs/PreForm/3.45.1.488/Formlabs.PreForm.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233659 New version: Fork.Fork version 2.6.1
  manifests/f/Fork/Fork/2.6.1/Fork.Fork.installer.yaml
  manifests/f/Fork/Fork/2.6.1/Fork.Fork.locale.en-US.yaml
  manifests/f/Fork/Fork/2.6.1/Fork.Fork.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233662 New version: Figma.FigmaAgent version 125.1.5
  manifests/f/Figma/FigmaAgent/125.1.5/Figma.FigmaAgent.installer.yaml
  manifests/f/Figma/FigmaAgent/125.1.5/Figma.FigmaAgent.locale.en-US.yaml
  manifests/f/Figma/FigmaAgent/125.1.5/Figma.FigmaAgent.locale.zh-CN.yaml
  manifests/f/Figma/FigmaAgent/125.1.5/Figma.FigmaAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233671 Adding Arm64 to ElementLabs.LMStudio.installer.yaml
  manifests/e/ElementLabs/LMStudio/0.3.10/ElementLabs.LMStudio.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233665 New version: Google.Chrome.Canary version 135.0.7042.0
  manifests/g/Google/Chrome/Canary/135.0.7042.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/135.0.7042.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/135.0.7042.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/135.0.7042.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/135.0.7042.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233666 New version: AdGuard.AdGuardHome version 0.107.57
  manifests/a/AdGuard/AdGuardHome/0.107.57/AdGuard.AdGuardHome.installer.yaml
  manifests/a/AdGuard/AdGuardHome/0.107.57/AdGuard.AdGuardHome.locale.en-US.yaml
  manifests/a/AdGuard/AdGuardHome/0.107.57/AdGuard.AdGuardHome.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233668 New version: Min.Min version 1.34.1
  manifests/m/Min/Min/1.34.1/Min.Min.installer.yaml
  manifests/m/Min/Min/1.34.1/Min.Min.locale.en-US.yaml
  manifests/m/Min/Min/1.34.1/Min.Min.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233672 New version: matchmycolor.ColibriAlpha version 25.0.0.14357
  manifests/m/matchmycolor/ColibriAlpha/25.0.0.14357/matchmycolor.ColibriAlpha.installer.yaml
  manifests/m/matchmycolor/ColibriAlpha/25.0.0.14357/matchmycolor.ColibriAlpha.locale.en-US.yaml
  manifests/m/matchmycolor/ColibriAlpha/25.0.0.14357/matchmycolor.ColibriAlpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233675 New version: CodeF0x.ffzap version 1.1.0
  manifests/c/CodeF0x/ffzap/1.1.0/CodeF0x.ffzap.installer.yaml
  manifests/c/CodeF0x/ffzap/1.1.0/CodeF0x.ffzap.locale.en-US.yaml
  manifests/c/CodeF0x/ffzap/1.1.0/CodeF0x.ffzap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233674 Update: Codeium.Windsurf version 1.94.0 (1.3.10)
  manifests/c/Codeium/Windsurf/1.94.0/Codeium.Windsurf.installer.yaml
  manifests/c/Codeium/Windsurf/1.94.0/Codeium.Windsurf.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233676 Update: KDE.Kaidan version master (4723)
  manifests/k/KDE/Kaidan/master/KDE.Kaidan.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233480 New package: ibttf.InterviewCoder version 1.0.17
  manifests/i/ibttf/InterviewCoder/1.0.17/ibttf.InterviewCoder.installer.yaml
  manifests/i/ibttf/InterviewCoder/1.0.17/ibttf.InterviewCoder.locale.en-US.yaml
  manifests/i/ibttf/InterviewCoder/1.0.17/ibttf.InterviewCoder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#233667 New version: git-cola.git-cola version 4.12.0
  manifests/g/git-cola/git-cola/4.12.0/git-cola.git-cola.installer.yaml
  manifests/g/git-cola/git-cola/4.12.0/git-cola.git-cola.locale.en-US.yaml
  manifests/g/git-cola/git-cola/4.12.0/git-cola.git-cola.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233685 New version: yt-dlp.yt-dlp.nightly version 2025.02.28.232826
  manifests/y/yt-dlp/yt-dlp/nightly/2025.02.28.232826/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.02.28.232826/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.02.28.232826/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#232343 New version: MongoDB.Server version 8.0.5
  manifests/m/MongoDB/Server/8.0.5/MongoDB.Server.installer.yaml
  manifests/m/MongoDB/Server/8.0.5/MongoDB.Server.locale.en-US.yaml
  manifests/m/MongoDB/Server/8.0.5/MongoDB.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233657 New version: KDE.KDiff3 version 1.12.1
  manifests/k/KDE/KDiff3/1.12.1/KDE.KDiff3.installer.yaml
  manifests/k/KDE/KDiff3/1.12.1/KDE.KDiff3.locale.en-US.yaml
  manifests/k/KDE/KDiff3/1.12.1/KDE.KDiff3.locale.zh-CN.yaml
  manifests/k/KDE/KDiff3/1.12.1/KDE.KDiff3.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233681 New version: Spicetify.Spicetify version 2.39.5
  manifests/s/Spicetify/Spicetify/2.39.5/Spicetify.Spicetify.installer.yaml
  manifests/s/Spicetify/Spicetify/2.39.5/Spicetify.Spicetify.locale.en-US.yaml
  manifests/s/Spicetify/Spicetify/2.39.5/Spicetify.Spicetify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233649 New package: UpNotePte.Ltd.UpNote version 9.10.0
  manifests/u/UpNotePte/Ltd/UpNote/9.10.0/UpNotePte.Ltd.UpNote.installer.yaml
  manifests/u/UpNotePte/Ltd/UpNote/9.10.0/UpNotePte.Ltd.UpNote.locale.en-US.yaml
  manifests/u/UpNotePte/Ltd/UpNote/9.10.0/UpNotePte.Ltd.UpNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#233833 New version: Jackett.Jackett version 0.22.1463
  manifests/j/Jackett/Jackett/0.22.1463/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1463/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1463/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233832 New version: Fly-io.flyctl version 0.3.87
  manifests/f/Fly-io/flyctl/0.3.87/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.3.87/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.3.87/Fly-io.flyctl.locale.ko-KR.yaml
  manifests/f/Fly-io/flyctl/0.3.87/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233842 Delete manifests/v/vedantmgoyal/sheltasks-cli/1.0.0 directory
  manifests/v/vedantmgoyal/sheltasks-cli/1.0.0/vedantmgoyal.sheltasks-cli.installer.yaml
  manifests/v/vedantmgoyal/sheltasks-cli/1.0.0/vedantmgoyal.sheltasks-cli.locale.en-US.yaml
  manifests/v/vedantmgoyal/sheltasks-cli/1.0.0/vedantmgoyal.sheltasks-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233845 Remove: Element.Element version 1.11.94
  manifests/e/Element/Element/1.11.94/Element.Element.installer.yaml
  manifests/e/Element/Element/1.11.94/Element.Element.locale.en-US.yaml
  manifests/e/Element/Element/1.11.94/Element.Element.locale.zh-CN.yaml
  manifests/e/Element/Element/1.11.94/Element.Element.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233846 Update: KDE.Kate version 24.12.3 (24.12-9105)
  manifests/k/KDE/Kate/24.12.3/KDE.Kate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233570 New version: THS.THS version 9.40.40
  manifests/t/THS/THS/9.40.40/THS.THS.installer.yaml
  manifests/t/THS/THS/9.40.40/THS.THS.locale.en-US.yaml
  manifests/t/THS/THS/9.40.40/THS.THS.locale.zh-CN.yaml
  manifests/t/THS/THS/9.40.40/THS.THS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233612 Update: KDE.Blinken version 25.03.70 (591)
  manifests/k/KDE/Blinken/25.03.70/KDE.Blinken.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233669 New version: ThaUnknown.Miru version 5.5.10
  manifests/t/ThaUnknown/Miru/5.5.10/ThaUnknown.Miru.installer.yaml
  manifests/t/ThaUnknown/Miru/5.5.10/ThaUnknown.Miru.locale.en-US.yaml
  manifests/t/ThaUnknown/Miru/5.5.10/ThaUnknown.Miru.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233696 New version: CrystalDewWorld.CrystalDiskInfo version 9.6.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.6.1/CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.6.1/CrystalDewWorld.CrystalDiskInfo.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.6.1/CrystalDewWorld.CrystalDiskInfo.locale.zh-CN.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.6.1/CrystalDewWorld.CrystalDiskInfo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233688 New version: Taozuhong.KangarooMultiple 6.4.1.0301
  manifests/t/Taozuhong/KangarooMultiple/6.4.1.0301/Taozuhong.KangarooMultiple.installer.yaml
  manifests/t/Taozuhong/KangarooMultiple/6.4.1.0301/Taozuhong.KangarooMultiple.locale.en-US.yaml
  manifests/t/Taozuhong/KangarooMultiple/6.4.1.0301/Taozuhong.KangarooMultiple.locale.zh-CN.yaml
  manifests/t/Taozuhong/KangarooMultiple/6.4.1.0301/Taozuhong.KangarooMultiple.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233697 New version: CrystalDewWorld.CrystalDiskInfo.AoiEdition version 9.6.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.AoiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.AoiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.AoiEdition.locale.zh-CN.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.AoiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233695 New version: Catsxp.Catsxp version 134.5.3.1
  manifests/c/Catsxp/Catsxp/134.5.3.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/134.5.3.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/134.5.3.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/134.5.3.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233702 Update: KDE.Kontact version master (1694)
  manifests/k/KDE/Kontact/master/KDE.Kontact.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233704 Remove version: BrettMayson.HEMTT version 1.14.4
  manifests/b/BrettMayson/HEMTT/1.14.4/BrettMayson.HEMTT.installer.yaml
  manifests/b/BrettMayson/HEMTT/1.14.4/BrettMayson.HEMTT.locale.en-US.yaml
  manifests/b/BrettMayson/HEMTT/1.14.4/BrettMayson.HEMTT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233703 New version: SpecialK.SpecialK version 25.2.29
  manifests/s/SpecialK/SpecialK/25.2.29/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.2.29/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.2.29/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.2.29/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233710 Fix: Figma.Figma version 125.0.7
  manifests/f/Figma/Figma/125.0.7/Figma.Figma.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233709 New version: ClashVergeRev.ClashVergeRev version 2.1.2
  manifests/c/ClashVergeRev/ClashVergeRev/2.1.2/ClashVergeRev.ClashVergeRev.installer.yaml
  manifests/c/ClashVergeRev/ClashVergeRev/2.1.2/ClashVergeRev.ClashVergeRev.locale.en-US.yaml
  manifests/c/ClashVergeRev/ClashVergeRev/2.1.2/ClashVergeRev.ClashVergeRev.locale.zh-CN.yaml
  manifests/c/ClashVergeRev/ClashVergeRev/2.1.2/ClashVergeRev.ClashVergeRev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233711 Fix: Figma.Figma version 125.0.8
  manifests/f/Figma/Figma/125.0.8/Figma.Figma.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233705 New version: CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition version 9.6.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.en-US.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.locale.zh-CN.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/KureiKeiEdition/9.6.1/CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233745 New version: Microsoft.NuGet version 6.13.2
  manifests/m/Microsoft/NuGet/6.13.2/Microsoft.NuGet.installer.yaml
  manifests/m/Microsoft/NuGet/6.13.2/Microsoft.NuGet.locale.en-US.yaml
  manifests/m/Microsoft/NuGet/6.13.2/Microsoft.NuGet.locale.zh-CN.yaml
  manifests/m/Microsoft/NuGet/6.13.2/Microsoft.NuGet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233729 New version: Posit.Positron version 2025.03.0 (2025.03.0-97)
  manifests/p/Posit/Positron/2025.03.0/Posit.Positron.installer.yaml
  manifests/p/Posit/Positron/2025.03.0/Posit.Positron.locale.en-US.yaml
  manifests/p/Posit/Positron/2025.03.0/Posit.Positron.locale.zh-CN.yaml
  manifests/p/Posit/Positron/2025.03.0/Posit.Positron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233768 Modify: ByteDance.JianyingPro version 3.1.0.8712 (Auto)
  manifests/b/ByteDance/JianyingPro/3.1.0.8712/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8712/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8712/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8712/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8712/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233767 Modify: ByteDance.JianyingPro version 3.1.0.8702 (Auto)
  manifests/b/ByteDance/JianyingPro/3.1.0.8702/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8702/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8702/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8702/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.1.0.8702/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233772 Modify: ByteDance.JianyingPro version 3.3.0.9035 (Auto)
  manifests/b/ByteDance/JianyingPro/3.3.0.9035/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.3.0.9035/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.3.0.9035/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.3.0.9035/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.3.0.9035/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233778 Modify: ByteDance.JianyingPro version 3.6.0.9326 (Auto)
  manifests/b/ByteDance/JianyingPro/3.6.0.9326/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.6.0.9326/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.6.0.9326/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.6.0.9326/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.6.0.9326/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233781 Modify: ByteDance.JianyingPro version 3.7.0.9494 (Auto)
  manifests/b/ByteDance/JianyingPro/3.7.0.9494/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.7.0.9494/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.7.0.9494/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.7.0.9494/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.7.0.9494/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233779 Modify: ByteDance.JianyingPro version 3.6.5.9422 (Auto)
  manifests/b/ByteDance/JianyingPro/3.6.5.9422/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.6.5.9422/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.6.5.9422/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.6.5.9422/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.6.5.9422/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233776 Modify: ByteDance.JianyingPro version 3.5.0.9238 (Auto)
  manifests/b/ByteDance/JianyingPro/3.5.0.9238/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.5.0.9238/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.5.0.9238/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.5.0.9238/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.5.0.9238/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233785 Modify: ByteDance.JianyingPro version 3.8.0.9618 (Auto)
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.8.0.9618/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233786 Modify: ByteDance.JianyingPro version 3.9.0.9723 (Auto)
  manifests/b/ByteDance/JianyingPro/3.9.0.9723/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.9.0.9723/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.9.0.9723/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.9.0.9723/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.9.0.9723/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233788 Modify: ByteDance.JianyingPro version 4.0.1.9886 (Auto)
  manifests/b/ByteDance/JianyingPro/4.0.1.9886/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.0.1.9886/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.0.1.9886/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.0.1.9886/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.0.1.9886/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233784 Modify: ByteDance.JianyingPro version 3.7.3.9535 (Auto)
  manifests/b/ByteDance/JianyingPro/3.7.3.9535/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/3.7.3.9535/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/3.7.3.9535/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/3.7.3.9535/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/3.7.3.9535/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233787 Modify: ByteDance.JianyingPro version 4.0.0.9841 (Auto)
  manifests/b/ByteDance/JianyingPro/4.0.0.9841/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.0.0.9841/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.0.0.9841/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.0.0.9841/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.0.0.9841/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233789 Modify: ByteDance.JianyingPro version 4.1.0.10000 (Auto)
  manifests/b/ByteDance/JianyingPro/4.1.0.10000/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.1.0.10000/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.1.0.10000/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.1.0.10000/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.1.0.10000/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233796 Modify: ByteDance.JianyingPro version 4.5.1.10461 (Auto)
  manifests/b/ByteDance/JianyingPro/4.5.1.10461/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.5.1.10461/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.5.1.10461/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.5.1.10461/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.5.1.10461/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233793 Modify: ByteDance.JianyingPro version 4.3.1.10241 (Auto)
  manifests/b/ByteDance/JianyingPro/4.3.1.10241/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.3.1.10241/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.3.1.10241/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.3.1.10241/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.3.1.10241/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233795 Modify: ByteDance.JianyingPro version 4.5.0.10453 (Auto)
  manifests/b/ByteDance/JianyingPro/4.5.0.10453/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.5.0.10453/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.5.0.10453/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.5.0.10453/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.5.0.10453/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233794 Modify: ByteDance.JianyingPro version 4.4.0.10337 (Auto)
  manifests/b/ByteDance/JianyingPro/4.4.0.10337/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.4.0.10337/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.4.0.10337/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.4.0.10337/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.4.0.10337/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233798 Modify: ByteDance.JianyingPro version 4.6.0.10562 (Auto)
  manifests/b/ByteDance/JianyingPro/4.6.0.10562/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.6.0.10562/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.6.0.10562/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.6.0.10562/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.6.0.10562/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233799 Modify: ByteDance.JianyingPro version 4.6.1.10576 (Auto)
  manifests/b/ByteDance/JianyingPro/4.6.1.10576/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.6.1.10576/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.6.1.10576/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.6.1.10576/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.6.1.10576/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233801 Modify: ByteDance.JianyingPro version 4.7.2.10739 (Auto)
  manifests/b/ByteDance/JianyingPro/4.7.2.10739/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.7.2.10739/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.7.2.10739/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.7.2.10739/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.7.2.10739/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233802 Modify: ByteDance.JianyingPro version 4.8.0.10791 (Auto)
  manifests/b/ByteDance/JianyingPro/4.8.0.10791/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.8.0.10791/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.8.0.10791/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.8.0.10791/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.8.0.10791/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233803 Modify: ByteDance.JianyingPro version 4.9.0.10872 (Auto)
  manifests/b/ByteDance/JianyingPro/4.9.0.10872/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/4.9.0.10872/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/4.9.0.10872/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/4.9.0.10872/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/4.9.0.10872/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233807 Modify: ByteDance.JianyingPro version 5.4.0.11246 (Auto)
  manifests/b/ByteDance/JianyingPro/5.4.0.11246/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.4.0.11246/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.4.0.11246/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.4.0.11246/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.4.0.11246/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233806 Modify: ByteDance.JianyingPro version 5.3.0.11154 (Auto)
  manifests/b/ByteDance/JianyingPro/5.3.0.11154/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.3.0.11154/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.3.0.11154/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.3.0.11154/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.3.0.11154/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233812 Modify: ByteDance.JianyingPro version 5.9.0.11632 (Auto)
  manifests/b/ByteDance/JianyingPro/5.9.0.11632/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.9.0.11632/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.9.0.11632/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.9.0.11632/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.9.0.11632/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233809 Modify: ByteDance.JianyingPro version 5.6.0.11423 (Auto)
  manifests/b/ByteDance/JianyingPro/5.6.0.11423/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.6.0.11423/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.6.0.11423/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.6.0.11423/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.6.0.11423/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233805 Modify: ByteDance.JianyingPro version 5.1.0.11009 (Auto)
  manifests/b/ByteDance/JianyingPro/5.1.0.11009/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.1.0.11009/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.1.0.11009/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.1.0.11009/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.1.0.11009/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233810 Modify: ByteDance.JianyingPro version 5.7.0.11480 (Auto)
  manifests/b/ByteDance/JianyingPro/5.7.0.11480/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.7.0.11480/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.7.0.11480/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.7.0.11480/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.7.0.11480/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233811 Modify: ByteDance.JianyingPro version 5.8.0.11586 (Auto)
  manifests/b/ByteDance/JianyingPro/5.8.0.11586/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.8.0.11586/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.8.0.11586/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.8.0.11586/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.8.0.11586/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233808 Modify: ByteDance.JianyingPro version 5.5.0.11332 (Auto)
  manifests/b/ByteDance/JianyingPro/5.5.0.11332/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/5.5.0.11332/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/5.5.0.11332/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/5.5.0.11332/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/5.5.0.11332/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233813 Modify: ByteDance.JianyingPro version 6.0.0.11756 (Auto)
  manifests/b/ByteDance/JianyingPro/6.0.0.11756/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.0.0.11756/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.0.0.11756/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.0.0.11756/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.0.0.11756/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233814 Modify: ByteDance.JianyingPro version 6.0.1.11779 (Auto)
  manifests/b/ByteDance/JianyingPro/6.0.1.11779/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.0.1.11779/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.0.1.11779/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.0.1.11779/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.0.1.11779/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233816 Modify: ByteDance.JianyingPro version 6.1.0.11925 (Auto)
  manifests/b/ByteDance/JianyingPro/6.1.0.11925/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11925/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11925/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11925/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11925/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233818 Modify: ByteDance.JianyingPro version 6.3.0.12011 (Auto)
  manifests/b/ByteDance/JianyingPro/6.3.0.12011/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.3.0.12011/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.3.0.12011/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.3.0.12011/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.3.0.12011/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233821 Modify: ByteDance.JianyingPro version 7.0.0.12369 (Auto)
  manifests/b/ByteDance/JianyingPro/7.0.0.12369/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12369/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12369/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12369/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12369/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233817 Modify: ByteDance.JianyingPro version 6.1.0.11946 (Auto)
  manifests/b/ByteDance/JianyingPro/6.1.0.11946/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11946/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11946/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11946/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.1.0.11946/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233819 Modify: ByteDance.JianyingPro version 6.6.0.12145 (Auto)
  manifests/b/ByteDance/JianyingPro/6.6.0.12145/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.6.0.12145/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.6.0.12145/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.6.0.12145/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.6.0.12145/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233824 Modify: ByteDance.JianyingPro version 7.2.0.12468 (Auto)
  manifests/b/ByteDance/JianyingPro/7.2.0.12468/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12468/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12468/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12468/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12468/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233820 Modify: ByteDance.JianyingPro version 6.8.0.12267 (Auto)
  manifests/b/ByteDance/JianyingPro/6.8.0.12267/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/6.8.0.12267/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/6.8.0.12267/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/6.8.0.12267/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/6.8.0.12267/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233822 Modify: ByteDance.JianyingPro version 7.0.0.12374 (Auto)
  manifests/b/ByteDance/JianyingPro/7.0.0.12374/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12374/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12374/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12374/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.0.0.12374/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233825 Modify: ByteDance.JianyingPro version 7.2.0.12475 (Auto)
  manifests/b/ByteDance/JianyingPro/7.2.0.12475/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12475/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12475/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12475/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.2.0.12475/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233823 Modify: ByteDance.JianyingPro version 7.1.0.12382 (Auto)
  manifests/b/ByteDance/JianyingPro/7.1.0.12382/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.1.0.12382/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.1.0.12382/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.1.0.12382/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.1.0.12382/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233826 Modify: ByteDance.JianyingPro version 7.3.0.12489 (Auto)
  manifests/b/ByteDance/JianyingPro/7.3.0.12489/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.3.0.12489/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.3.0.12489/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.3.0.12489/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.3.0.12489/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233827 Modify: ByteDance.JianyingPro version 7.4.0.12544 (Auto)
  manifests/b/ByteDance/JianyingPro/7.4.0.12544/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.4.0.12544/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.4.0.12544/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.4.0.12544/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.4.0.12544/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233828 Modify: ByteDance.JianyingPro version 7.5.0.12565 (Auto)
  manifests/b/ByteDance/JianyingPro/7.5.0.12565/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.5.0.12565/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.5.0.12565/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.5.0.12565/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.5.0.12565/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233829 Modify: ByteDance.JianyingPro version 7.6.0.12636 (Auto)
  manifests/b/ByteDance/JianyingPro/7.6.0.12636/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.6.0.12636/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.6.0.12636/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.6.0.12636/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.6.0.12636/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233830 Modify: ByteDance.JianyingPro version 7.7.0.12666 (Auto)
  manifests/b/ByteDance/JianyingPro/7.7.0.12666/ByteDance.JianyingPro.installer.yaml
  manifests/b/ByteDance/JianyingPro/7.7.0.12666/ByteDance.JianyingPro.locale.en-US.yaml
  manifests/b/ByteDance/JianyingPro/7.7.0.12666/ByteDance.JianyingPro.locale.zh-CN.yaml
  manifests/b/ByteDance/JianyingPro/7.7.0.12666/ByteDance.JianyingPro.locale.zh-TW.yaml
  manifests/b/ByteDance/JianyingPro/7.7.0.12666/ByteDance.JianyingPro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233834 New version: RProject.R version 4.4.3
  manifests/r/RProject/R/4.4.3/RProject.R.installer.yaml
  manifests/r/RProject/R/4.4.3/RProject.R.locale.en-US.yaml
  manifests/r/RProject/R/4.4.3/RProject.R.locale.zh-CN.yaml
  manifests/r/RProject/R/4.4.3/RProject.R.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233837 Update: KDE.Kaidan version master (4732)
  manifests/k/KDE/Kaidan/master/KDE.Kaidan.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233836 New version: InfiniteRed.Reactotron version 3.7.7
  manifests/i/InfiniteRed/Reactotron/3.7.7/InfiniteRed.Reactotron.installer.yaml
  manifests/i/InfiniteRed/Reactotron/3.7.7/InfiniteRed.Reactotron.locale.en-US.yaml
  manifests/i/InfiniteRed/Reactotron/3.7.7/InfiniteRed.Reactotron.locale.zh-CN.yaml
  manifests/i/InfiniteRed/Reactotron/3.7.7/InfiniteRed.Reactotron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233839 New version: Google.Chrome.Canary version 135.0.7043.0
  manifests/g/Google/Chrome/Canary/135.0.7043.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/135.0.7043.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/135.0.7043.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/135.0.7043.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/135.0.7043.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233838 New version: Tencent.VooVMeeting version 3.30.0.510
  manifests/t/Tencent/VooVMeeting/3.30.0.510/Tencent.VooVMeeting.installer.yaml
  manifests/t/Tencent/VooVMeeting/3.30.0.510/Tencent.VooVMeeting.locale.en-US.yaml
  manifests/t/Tencent/VooVMeeting/3.30.0.510/Tencent.VooVMeeting.locale.zh-CN.yaml
  manifests/t/Tencent/VooVMeeting/3.30.0.510/Tencent.VooVMeeting.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233841 New version: TianZhen.NeatChat version 1.1.14
  manifests/t/TianZhen/NeatChat/1.1.14/TianZhen.NeatChat.installer.yaml
  manifests/t/TianZhen/NeatChat/1.1.14/TianZhen.NeatChat.locale.en-US.yaml
  manifests/t/TianZhen/NeatChat/1.1.14/TianZhen.NeatChat.locale.zh-CN.yaml
  manifests/t/TianZhen/NeatChat/1.1.14/TianZhen.NeatChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233854 Update: LLVM.LLVM version 19.1.7
  manifests/l/LLVM/LLVM/19.1.7/LLVM.LLVM.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233840 Update: KDE.Elisa version 25.03.70 (3703)
  manifests/k/KDE/Elisa/25.03.70/KDE.Elisa.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233855 Remove version: AnyDesk.AnyDesk.MSI version 9.0.2
  manifests/a/AnyDesk/AnyDesk/MSI/9.0.2/AnyDesk.AnyDesk.MSI.installer.yaml
  manifests/a/AnyDesk/AnyDesk/MSI/9.0.2/AnyDesk.AnyDesk.MSI.locale.en-US.yaml
  manifests/a/AnyDesk/AnyDesk/MSI/9.0.2/AnyDesk.AnyDesk.MSI.locale.zh-CN.yaml
  manifests/a/AnyDesk/AnyDesk/MSI/9.0.2/AnyDesk.AnyDesk.MSI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233857 Remove version: AppByTroye.KoodoReader version 1.7.8
  manifests/a/AppByTroye/KoodoReader/1.7.8/AppByTroye.KoodoReader.installer.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.8/AppByTroye.KoodoReader.locale.en-US.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.8/AppByTroye.KoodoReader.locale.zh-CN.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.8/AppByTroye.KoodoReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233858 Remove version: AppByTroye.KoodoReader version 1.7.9
  manifests/a/AppByTroye/KoodoReader/1.7.9/AppByTroye.KoodoReader.installer.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.9/AppByTroye.KoodoReader.locale.en-US.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.9/AppByTroye.KoodoReader.locale.zh-CN.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.9/AppByTroye.KoodoReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233856 Remove version: AppByTroye.KoodoReader version 1.7.7
  manifests/a/AppByTroye/KoodoReader/1.7.7/AppByTroye.KoodoReader.installer.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.7/AppByTroye.KoodoReader.locale.en-US.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.7/AppByTroye.KoodoReader.locale.zh-CN.yaml
  manifests/a/AppByTroye/KoodoReader/1.7.7/AppByTroye.KoodoReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233693 New version: AuraMarker.Lattics version 2.4.3
  manifests/a/AuraMarker/Lattics/2.4.3/AuraMarker.Lattics.installer.yaml
  manifests/a/AuraMarker/Lattics/2.4.3/AuraMarker.Lattics.locale.en-US.yaml
  manifests/a/AuraMarker/Lattics/2.4.3/AuraMarker.Lattics.locale.zh-CN.yaml
  manifests/a/AuraMarker/Lattics/2.4.3/AuraMarker.Lattics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233732 New version: BtbN.FFmpeg.GPL.6.1 version 6.1.2-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/GPL/6/1/6.1.2-20250228/BtbN.FFmpeg.GPL.6.1.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/6/1/6.1.2-20250228/BtbN.FFmpeg.GPL.6.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/6/1/6.1.2-20250228/BtbN.FFmpeg.GPL.6.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/6/1/6.1.2-20250228/BtbN.FFmpeg.GPL.6.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233713 New version: Figma.Figma version 125.1.5
  manifests/f/Figma/Figma/125.1.5/Figma.Figma.installer.yaml
  manifests/f/Figma/Figma/125.1.5/Figma.Figma.locale.en-US.yaml
  manifests/f/Figma/Figma/125.1.5/Figma.Figma.locale.zh-CN.yaml
  manifests/f/Figma/Figma/125.1.5/Figma.Figma.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233737 New version: BtbN.FFmpeg.LGPL version N-118579-gbb87d19cd9-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/LGPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.LGPL.installer.yaml
  manifests/b/BtbN/FFmpeg/LGPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.LGPL.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/LGPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.LGPL.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/LGPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.LGPL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233733 New version: BtbN.FFmpeg.GPL.7.1 version 7.1-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/GPL/7/1/7.1-20250228/BtbN.FFmpeg.GPL.7.1.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/7/1/7.1-20250228/BtbN.FFmpeg.GPL.7.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/7/1/7.1-20250228/BtbN.FFmpeg.GPL.7.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/7/1/7.1-20250228/BtbN.FFmpeg.GPL.7.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233739 New version: BtbN.FFmpeg.LGPL.7.1 version 7.1-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/LGPL/7/1/7.1-20250228/BtbN.FFmpeg.LGPL.7.1.installer.yaml
  manifests/b/BtbN/FFmpeg/LGPL/7/1/7.1-20250228/BtbN.FFmpeg.LGPL.7.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/LGPL/7/1/7.1-20250228/BtbN.FFmpeg.LGPL.7.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/LGPL/7/1/7.1-20250228/BtbN.FFmpeg.LGPL.7.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233738 New version: BtbN.FFmpeg.LGPL.6.1 version 6.1.2-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/LGPL/6/1/6.1.2-20250228/BtbN.FFmpeg.LGPL.6.1.installer.yaml
  manifests/b/BtbN/FFmpeg/LGPL/6/1/6.1.2-20250228/BtbN.FFmpeg.LGPL.6.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/LGPL/6/1/6.1.2-20250228/BtbN.FFmpeg.LGPL.6.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/LGPL/6/1/6.1.2-20250228/BtbN.FFmpeg.LGPL.6.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233850 New version: Dagger.Cli version 0.16.2
  manifests/d/Dagger/Cli/0.16.2/Dagger.Cli.installer.yaml
  manifests/d/Dagger/Cli/0.16.2/Dagger.Cli.locale.en-US.yaml
  manifests/d/Dagger/Cli/0.16.2/Dagger.Cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233851 New version: NickGasson.NVC version 1.15.2
  manifests/n/NickGasson/NVC/1.15.2/NickGasson.NVC.installer.yaml
  manifests/n/NickGasson/NVC/1.15.2/NickGasson.NVC.locale.en-US.yaml
  manifests/n/NickGasson/NVC/1.15.2/NickGasson.NVC.locale.zh-CN.yaml
  manifests/n/NickGasson/NVC/1.15.2/NickGasson.NVC.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233860 Remove version: Deezer.Deezer version 5.30.540
  manifests/d/Deezer/Deezer/5.30.540/Deezer.Deezer.installer.yaml
  manifests/d/Deezer/Deezer/5.30.540/Deezer.Deezer.locale.en-US.yaml
  manifests/d/Deezer/Deezer/5.30.540/Deezer.Deezer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233861 Remove version: Deezer.Deezer version 6.0.30
  manifests/d/Deezer/Deezer/6.0.30/Deezer.Deezer.installer.yaml
  manifests/d/Deezer/Deezer/6.0.30/Deezer.Deezer.locale.en-US.yaml
  manifests/d/Deezer/Deezer/6.0.30/Deezer.Deezer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233863 Remove version: Deezer.Deezer version 6.0.90
  manifests/d/Deezer/Deezer/6.0.90/Deezer.Deezer.installer.yaml
  manifests/d/Deezer/Deezer/6.0.90/Deezer.Deezer.locale.en-US.yaml
  manifests/d/Deezer/Deezer/6.0.90/Deezer.Deezer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233864 Remove version: Deezer.Deezer version 7.0.10
  manifests/d/Deezer/Deezer/7.0.10/Deezer.Deezer.installer.yaml
  manifests/d/Deezer/Deezer/7.0.10/Deezer.Deezer.locale.en-US.yaml
  manifests/d/Deezer/Deezer/7.0.10/Deezer.Deezer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233862 Remove version: Deezer.Deezer version 6.0.80
  manifests/d/Deezer/Deezer/6.0.80/Deezer.Deezer.installer.yaml
  manifests/d/Deezer/Deezer/6.0.80/Deezer.Deezer.locale.en-US.yaml
  manifests/d/Deezer/Deezer/6.0.80/Deezer.Deezer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233869 New version: Bin-Huang.Chatbox version 1.10.3
  manifests/b/Bin-Huang/Chatbox/1.10.3/Bin-Huang.Chatbox.installer.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.3/Bin-Huang.Chatbox.locale.en-US.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.3/Bin-Huang.Chatbox.locale.zh-CN.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.3/Bin-Huang.Chatbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233872 New version: Ventoy.Ventoy version 1.1.05
  manifests/v/Ventoy/Ventoy/1.1.05/Ventoy.Ventoy.installer.yaml
  manifests/v/Ventoy/Ventoy/1.1.05/Ventoy.Ventoy.locale.en-US.yaml
  manifests/v/Ventoy/Ventoy/1.1.05/Ventoy.Ventoy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233871 New version: Ventoy.Ventoy version 1.1.04
  manifests/v/Ventoy/Ventoy/1.1.04/Ventoy.Ventoy.installer.yaml
  manifests/v/Ventoy/Ventoy/1.1.04/Ventoy.Ventoy.locale.en-US.yaml
  manifests/v/Ventoy/Ventoy/1.1.04/Ventoy.Ventoy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233873 Update version: Zen-Team.Zen-Browser.Twilight version 1.8.2t
  manifests/z/Zen-Team/Zen-Browser/Twilight/1.8.2t/Zen-Team.Zen-Browser.Twilight.installer.yaml
  manifests/z/Zen-Team/Zen-Browser/Twilight/1.8.2t/Zen-Team.Zen-Browser.Twilight.locale.en-US.yaml
  manifests/z/Zen-Team/Zen-Browser/Twilight/1.8.2t/Zen-Team.Zen-Browser.Twilight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233874 New version: Bin-Huang.Chatbox version 1.10.4
  manifests/b/Bin-Huang/Chatbox/1.10.4/Bin-Huang.Chatbox.installer.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.4/Bin-Huang.Chatbox.locale.en-US.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.4/Bin-Huang.Chatbox.locale.zh-CN.yaml
  manifests/b/Bin-Huang/Chatbox/1.10.4/Bin-Huang.Chatbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233641 New version: Microsoft.OneDrive version 25.020.0202.0001
  manifests/m/Microsoft/OneDrive/25.020.0202.0001/Microsoft.OneDrive.installer.yaml
  manifests/m/Microsoft/OneDrive/25.020.0202.0001/Microsoft.OneDrive.locale.en-US.yaml
  manifests/m/Microsoft/OneDrive/25.020.0202.0001/Microsoft.OneDrive.locale.zh-CN.yaml
  manifests/m/Microsoft/OneDrive/25.020.0202.0001/Microsoft.OneDrive.yaml
Labels: Validation-Completed, Moderator-Approved

#233700 New version: nektos.act version 0.2.75
  manifests/n/nektos/act/0.2.75/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.75/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.75/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233884 New version: NGWIN.PicPick version 7.3.3
  manifests/n/NGWIN/PicPick/7.3.3/NGWIN.PicPick.installer.yaml
  manifests/n/NGWIN/PicPick/7.3.3/NGWIN.PicPick.locale.en-US.yaml
  manifests/n/NGWIN/PicPick/7.3.3/NGWIN.PicPick.locale.zh-CN.yaml
  manifests/n/NGWIN/PicPick/7.3.3/NGWIN.PicPick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233880 New version: OpenSCAD.OpenSCAD.Nightly version 2025.02.28
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.02.28/OpenSCAD.OpenSCAD.Nightly.installer.yaml
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.02.28/OpenSCAD.OpenSCAD.Nightly.locale.en-US.yaml
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.02.28/OpenSCAD.OpenSCAD.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233867 New version: Warzone2100Project.Warzone2100 version 4.5.5
  manifests/w/Warzone2100Project/Warzone2100/4.5.5/Warzone2100Project.Warzone2100.installer.yaml
  manifests/w/Warzone2100Project/Warzone2100/4.5.5/Warzone2100Project.Warzone2100.locale.en-US.yaml
  manifests/w/Warzone2100Project/Warzone2100/4.5.5/Warzone2100Project.Warzone2100.yaml
Labels: Validation-Completed, Moderator-Approved

#233707 New version: JesseDuffield.lazygit version 0.48.0
  manifests/j/JesseDuffield/lazygit/0.48.0/JesseDuffield.lazygit.installer.yaml
  manifests/j/JesseDuffield/lazygit/0.48.0/JesseDuffield.lazygit.locale.en-US.yaml
  manifests/j/JesseDuffield/lazygit/0.48.0/JesseDuffield.lazygit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233876 Remove version: Google.Chrome.Canary version 135.0.7018.0
  manifests/g/Google/Chrome/Canary/135.0.7018.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/135.0.7018.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/135.0.7018.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/135.0.7018.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/135.0.7018.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233875 Remove version: Google.Chrome.Canary version 135.0.7017.0
  manifests/g/Google/Chrome/Canary/135.0.7017.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/135.0.7017.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/135.0.7017.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/135.0.7017.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/135.0.7017.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233731 New version: BtbN.FFmpeg.GPL version N-118579-gbb87d19cd9-20250228 (2025-02-28-13-02)
  manifests/b/BtbN/FFmpeg/GPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.GPL.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.GPL.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.GPL.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/N-118579-gbb87d19cd9-20250228/BtbN.FFmpeg.GPL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233877 New version: SimpleX.SimpleX-Chat version 6.2.5
  manifests/s/SimpleX/SimpleX-Chat/6.2.5/SimpleX.SimpleX-Chat.installer.yaml
  manifests/s/SimpleX/SimpleX-Chat/6.2.5/SimpleX.SimpleX-Chat.locale.en-US.yaml
  manifests/s/SimpleX/SimpleX-Chat/6.2.5/SimpleX.SimpleX-Chat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233878 Update manifest: NexusMods.Vortex version 1.13.7
  manifests/n/NexusMods/Vortex/1.13.7/NexusMods.Vortex.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233127 New version: ShiningLight.OpenSSL.Dev version 3.4.1
  manifests/s/ShiningLight/OpenSSL/Dev/3.4.1/ShiningLight.OpenSSL.Dev.installer.yaml
  manifests/s/ShiningLight/OpenSSL/Dev/3.4.1/ShiningLight.OpenSSL.Dev.locale.en-US.yaml
  manifests/s/ShiningLight/OpenSSL/Dev/3.4.1/ShiningLight.OpenSSL.Dev.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, New-Package

#233588 New version: JetBrains.dotUltimate version 2024.3.6
  manifests/j/JetBrains/dotUltimate/2024.3.6/JetBrains.dotUltimate.installer.yaml
  manifests/j/JetBrains/dotUltimate/2024.3.6/JetBrains.dotUltimate.locale.en-US.yaml
  manifests/j/JetBrains/dotUltimate/2024.3.6/JetBrains.dotUltimate.locale.zh-CN.yaml
  manifests/j/JetBrains/dotUltimate/2024.3.6/JetBrains.dotUltimate.yaml
Labels: Validation-Completed, Moderator-Approved

#233670 New version: MartiCliment.UniGetUI version 3.1.7
  manifests/m/MartiCliment/UniGetUI/3.1.7/MartiCliment.UniGetUI.installer.yaml
  manifests/m/MartiCliment/UniGetUI/3.1.7/MartiCliment.UniGetUI.locale.en-US.yaml
  manifests/m/MartiCliment/UniGetUI/3.1.7/MartiCliment.UniGetUI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233879 New version: OpenWhisperSystems.Signal.Beta version 7.45.0-beta.1
  manifests/o/OpenWhisperSystems/Signal/Beta/7.45.0-beta.1/OpenWhisperSystems.Signal.Beta.installer.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/7.45.0-beta.1/OpenWhisperSystems.Signal.Beta.locale.en-US.yaml
  manifests/o/OpenWhisperSystems/Signal/Beta/7.45.0-beta.1/OpenWhisperSystems.Signal.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233888 Update: KDE.Konsole version 25.03.70 (3913)
  manifests/k/KDE/Konsole/25.03.70/KDE.Konsole.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233887 Update: KDE.Elisa version 25.03.70 (3707)
  manifests/k/KDE/Elisa/25.03.70/KDE.Elisa.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233891 New version: Speakeasy.speakeasy 1.508.1
  manifests/s/Speakeasy/speakeasy/1.508.1/Speakeasy.speakeasy.installer.yaml
  manifests/s/Speakeasy/speakeasy/1.508.1/Speakeasy.speakeasy.locale.en-US.yaml
  manifests/s/Speakeasy/speakeasy/1.508.1/Speakeasy.speakeasy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233892 Update version: Zen-Team.Zen-Browser.Twilight version 1.8.2t
  manifests/z/Zen-Team/Zen-Browser/Twilight/1.8.2t/Zen-Team.Zen-Browser.Twilight.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233893 Update CrystalDewWorld.CrystalDiskInfo.installer.yaml
  manifests/c/CrystalDewWorld/CrystalDiskInfo/9.6.1/CrystalDewWorld.CrystalDiskInfo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233894 New version: Google.Chrome.Canary version 135.0.7044.0
  manifests/g/Google/Chrome/Canary/135.0.7044.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/135.0.7044.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/135.0.7044.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/135.0.7044.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/135.0.7044.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#233896 New version: SpecialK.SpecialK version 25.3.1.1
  manifests/s/SpecialK/SpecialK/25.3.1.1/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.3.1.1/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.3.1.1/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.3.1.1/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233897 New version: XMediaRecode.XMediaRecode version 3.6.0.8
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.8/XMediaRecode.XMediaRecode.installer.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.8/XMediaRecode.XMediaRecode.locale.en-US.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.8/XMediaRecode.XMediaRecode.locale.zh-CN.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.8/XMediaRecode.XMediaRecode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233909 Fix x64 install (was rerefencing ARM)
  manifests/n/nomic/gpt4all/3.9.0/nomic.gpt4all.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233903 New version: RandomEngy.VidCoder version 11.11
  manifests/r/RandomEngy/VidCoder/11.11/RandomEngy.VidCoder.installer.yaml
  manifests/r/RandomEngy/VidCoder/11.11/RandomEngy.VidCoder.locale.en-US.yaml
  manifests/r/RandomEngy/VidCoder/11.11/RandomEngy.VidCoder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#233913 Update: KDE.Konsole version 25.03.70 (3918)
  manifests/k/KDE/Konsole/25.03.70/KDE.Konsole.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#233914 New version: Hashicorp.Boundary version 0.19.0
  manifests/h/Hashicorp/Boundary/0.19.0/Hashicorp.Boundary.installer.yaml
  manifests/h/Hashicorp/Boundary/0.19.0/Hashicorp.Boundary.locale.en-US.yaml
  manifests/h/Hashicorp/Boundary/0.19.0/Hashicorp.Boundary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
