Repository microsoft/winget-pkgs, pull requests merged in 2025-04, with the labels that each got.

#243990 New version: Google.Chrome.Canary version 136.0.7102.0
  manifests/g/Google/Chrome/Canary/136.0.7102.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/136.0.7102.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/136.0.7102.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/136.0.7102.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/136.0.7102.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243599 Voiceflow 1.15.0
  manifests/x/xavidop/voiceflow/1.15.0/xavidop.voiceflow.installer.yaml
  manifests/x/xavidop/voiceflow/1.15.0/xavidop.voiceflow.locale.en-US.yaml
  manifests/x/xavidop/voiceflow/1.15.0/xavidop.voiceflow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243935 New version: matchmycolor.ColibriBeta version 25.1.0.14455
  manifests/m/matchmycolor/ColibriBeta/25.1.0.14455/matchmycolor.ColibriBeta.installer.yaml
  manifests/m/matchmycolor/ColibriBeta/25.1.0.14455/matchmycolor.ColibriBeta.locale.en-US.yaml
  manifests/m/matchmycolor/ColibriBeta/25.1.0.14455/matchmycolor.ColibriBeta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243973 New version: DavidRios.Remindr version 2.2.1
  manifests/d/DavidRios/Remindr/2.2.1/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.2.1/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.2.1/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243941 Automatic version update: InterfaceFluidics.Autobench.Beta version 0.90.0.0
  manifests/i/InterfaceFluidics/Autobench/Beta/0.90.0.0/InterfaceFluidics.Autobench.Beta.installer.yaml
  manifests/i/InterfaceFluidics/Autobench/Beta/0.90.0.0/InterfaceFluidics.Autobench.Beta.locale.en-US.yaml
  manifests/i/InterfaceFluidics/Autobench/Beta/0.90.0.0/InterfaceFluidics.Autobench.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243979 New version: DavidRios.Remindr version 2.1.17
  manifests/d/DavidRios/Remindr/2.1.17/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.1.17/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.1.17/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved, New-Manifest

#243976 New version: DavidRios.Remindr version 2.1.14
  manifests/d/DavidRios/Remindr/2.1.14/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.1.14/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.1.14/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243986 New version: matchmycolor.ColibriAlpha version 25.2.0.14630
  manifests/m/matchmycolor/ColibriAlpha/25.2.0.14630/matchmycolor.ColibriAlpha.installer.yaml
  manifests/m/matchmycolor/ColibriAlpha/25.2.0.14630/matchmycolor.ColibriAlpha.locale.en-US.yaml
  manifests/m/matchmycolor/ColibriAlpha/25.2.0.14630/matchmycolor.ColibriAlpha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243978 New version: DavidRios.Remindr version 2.1.16
  manifests/d/DavidRios/Remindr/2.1.16/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.1.16/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.1.16/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243980 New version: DavidRios.Remindr version 2.1.18
  manifests/d/DavidRios/Remindr/2.1.18/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.1.18/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.1.18/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243983 New version: yt-dlp.yt-dlp version 2025.03.31
  manifests/y/yt-dlp/yt-dlp/2025.03.31/yt-dlp.yt-dlp.installer.yaml
  manifests/y/yt-dlp/yt-dlp/2025.03.31/yt-dlp.yt-dlp.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/2025.03.31/yt-dlp.yt-dlp.locale.zh-CN.yaml
  manifests/y/yt-dlp/yt-dlp/2025.03.31/yt-dlp.yt-dlp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243977 New version: DavidRios.Remindr version 2.1.15
  manifests/d/DavidRios/Remindr/2.1.15/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.1.15/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.1.15/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243981 New version: DavidRios.Remindr version 2.2.0
  manifests/d/DavidRios/Remindr/2.2.0/DavidRios.Remindr.installer.yaml
  manifests/d/DavidRios/Remindr/2.2.0/DavidRios.Remindr.locale.en-US.yaml
  manifests/d/DavidRios/Remindr/2.2.0/DavidRios.Remindr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243996 New version: BandicamCompany.Bandicam version 8.1.1.2518
  manifests/b/BandicamCompany/Bandicam/8.1.1.2518/BandicamCompany.Bandicam.installer.yaml
  manifests/b/BandicamCompany/Bandicam/8.1.1.2518/BandicamCompany.Bandicam.locale.en-US.yaml
  manifests/b/BandicamCompany/Bandicam/8.1.1.2518/BandicamCompany.Bandicam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243997 New version: SteelSeries.GG version 83.1.0
  manifests/s/SteelSeries/GG/83.1.0/SteelSeries.GG.installer.yaml
  manifests/s/SteelSeries/GG/83.1.0/SteelSeries.GG.locale.en-US.yaml
  manifests/s/SteelSeries/GG/83.1.0/SteelSeries.GG.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243984 New version: yt-dlp.yt-dlp.nightly version 2025.03.31.214356
  manifests/y/yt-dlp/yt-dlp/nightly/2025.03.31.214356/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.03.31.214356/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2025.03.31.214356/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243991 New version: vim.vim.nightly version 9.1.1265
  manifests/v/vim/vim/nightly/9.1.1265/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.1265/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.1265/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243994 New version: Taiko2k.TauonMusicBox version 8.0.0
  manifests/t/Taiko2k/TauonMusicBox/8.0.0/Taiko2k.TauonMusicBox.installer.yaml
  manifests/t/Taiko2k/TauonMusicBox/8.0.0/Taiko2k.TauonMusicBox.locale.en-US.yaml
  manifests/t/Taiko2k/TauonMusicBox/8.0.0/Taiko2k.TauonMusicBox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243992 Move mtrojnar.osslsigncode to MichalTrojnara.osslsigncode
  manifests/m/mtrojnar/osslsigncode/2.9/mtrojnar.osslsigncode.installer.yaml
  manifests/m/mtrojnar/osslsigncode/2.9/mtrojnar.osslsigncode.locale.en-US.yaml
  manifests/m/mtrojnar/osslsigncode/2.9/mtrojnar.osslsigncode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#243998 New version: blacktop.ipsw 3.1.589
  manifests/b/blacktop/ipsw/3.1.589/blacktop.ipsw.installer.yaml
  manifests/b/blacktop/ipsw/3.1.589/blacktop.ipsw.locale.en-US.yaml
  manifests/b/blacktop/ipsw/3.1.589/blacktop.ipsw.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243999 New version: blacktop.ipswd 3.1.589
  manifests/b/blacktop/ipswd/3.1.589/blacktop.ipswd.installer.yaml
  manifests/b/blacktop/ipswd/3.1.589/blacktop.ipswd.locale.en-US.yaml
  manifests/b/blacktop/ipswd/3.1.589/blacktop.ipswd.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244002 New version: SpecialK.SpecialK version 25.4.1
  manifests/s/SpecialK/SpecialK/25.4.1/SpecialK.SpecialK.installer.yaml
  manifests/s/SpecialK/SpecialK/25.4.1/SpecialK.SpecialK.locale.en-US.yaml
  manifests/s/SpecialK/SpecialK/25.4.1/SpecialK.SpecialK.locale.zh-CN.yaml
  manifests/s/SpecialK/SpecialK/25.4.1/SpecialK.SpecialK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243989 Moved mtrojnar.osslsigncode to MichalTrojnara.osslsigncode
  manifests/m/MichalTrojnara/osslsigncode/2.9/MichalTrojnara.osslsigncode.installer.yaml
  manifests/m/MichalTrojnara/osslsigncode/2.9/MichalTrojnara.osslsigncode.locale.en-US.yaml
  manifests/m/MichalTrojnara/osslsigncode/2.9/MichalTrojnara.osslsigncode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Package

#243920 New package: davidegiacometti.EdgeFavoritesForCmdPal version 0.0.1
  manifests/d/davidegiacometti/EdgeFavoritesForCmdPal/0.0.1/davidegiacometti.EdgeFavoritesForCmdPal.installer.yaml
  manifests/d/davidegiacometti/EdgeFavoritesForCmdPal/0.0.1/davidegiacometti.EdgeFavoritesForCmdPal.locale.en-US.yaml
  manifests/d/davidegiacometti/EdgeFavoritesForCmdPal/0.0.1/davidegiacometti.EdgeFavoritesForCmdPal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#243873 New version: BtbN.FFmpeg.LGPL.Shared.7.1 version 7.1.1-20250331 (2025-03-31-12-55)
  manifests/b/BtbN/FFmpeg/LGPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.LGPL.Shared.7.1.installer.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.LGPL.Shared.7.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.LGPL.Shared.7.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.LGPL.Shared.7.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244003 New version: goreleaser.goreleaser-pro 2.8.2
  manifests/g/goreleaser/goreleaser-pro/2.8.2/goreleaser.goreleaser-pro.installer.yaml
  manifests/g/goreleaser/goreleaser-pro/2.8.2/goreleaser.goreleaser-pro.locale.en-US.yaml
  manifests/g/goreleaser/goreleaser-pro/2.8.2/goreleaser.goreleaser-pro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244006 New version: AppByTroye.KoodoReader version 1.9.0
  manifests/a/AppByTroye/KoodoReader/1.9.0/AppByTroye.KoodoReader.installer.yaml
  manifests/a/AppByTroye/KoodoReader/1.9.0/AppByTroye.KoodoReader.locale.en-US.yaml
  manifests/a/AppByTroye/KoodoReader/1.9.0/AppByTroye.KoodoReader.locale.zh-CN.yaml
  manifests/a/AppByTroye/KoodoReader/1.9.0/AppByTroye.KoodoReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243866 New version: BtbN.FFmpeg.GPL.Shared.6.1 version 6.1.2-20250331 (2025-03-31-12-55)
  manifests/b/BtbN/FFmpeg/GPL/Shared/6/1/6.1.2-20250331/BtbN.FFmpeg.GPL.Shared.6.1.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/6/1/6.1.2-20250331/BtbN.FFmpeg.GPL.Shared.6.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/6/1/6.1.2-20250331/BtbN.FFmpeg.GPL.Shared.6.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/6/1/6.1.2-20250331/BtbN.FFmpeg.GPL.Shared.6.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243867 New version: BtbN.FFmpeg.GPL.Shared.7.1 version 7.1.1-20250331 (2025-03-31-12-55)
  manifests/b/BtbN/FFmpeg/GPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.GPL.Shared.7.1.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.GPL.Shared.7.1.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.GPL.Shared.7.1.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/7/1/7.1.1-20250331/BtbN.FFmpeg.GPL.Shared.7.1.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243871 New version: BtbN.FFmpeg.LGPL.Shared version N-119094-g3e32dc8b08-20250331 (2025-03-31-12-55)
  manifests/b/BtbN/FFmpeg/LGPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.LGPL.Shared.installer.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.LGPL.Shared.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.LGPL.Shared.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/LGPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.LGPL.Shared.yaml
Labels: Validation-Completed, Moderator-Approved, New-Manifest

#241964 New package: Navratovi.RemoteBoulderTimer version 1.0.0.3
  manifests/n/Navratovi/RemoteBoulderTimer/1.0.0.3/Navratovi.RemoteBoulderTimer.installer.yaml
  manifests/n/Navratovi/RemoteBoulderTimer/1.0.0.3/Navratovi.RemoteBoulderTimer.locale.en-US.yaml
  manifests/n/Navratovi/RemoteBoulderTimer/1.0.0.3/Navratovi.RemoteBoulderTimer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#243865 New version: BtbN.FFmpeg.GPL.Shared version N-119094-g3e32dc8b08-20250331 (2025-03-31-12-55)
  manifests/b/BtbN/FFmpeg/GPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.GPL.Shared.installer.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.GPL.Shared.locale.en-US.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.GPL.Shared.locale.zh-CN.yaml
  manifests/b/BtbN/FFmpeg/GPL/Shared/N-119094-g3e32dc8b08-20250331/BtbN.FFmpeg.GPL.Shared.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243519 New package: davidegiacometti.VisualStudioForCmdPal version 0.0.1
  manifests/d/davidegiacometti/VisualStudioForCmdPal/0.0.1/davidegiacometti.VisualStudioForCmdPal.installer.yaml
  manifests/d/davidegiacometti/VisualStudioForCmdPal/0.0.1/davidegiacometti.VisualStudioForCmdPal.locale.en-US.yaml
  manifests/d/davidegiacometti/VisualStudioForCmdPal/0.0.1/davidegiacometti.VisualStudioForCmdPal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#243924 Crate-CI.Typos version 1.31.1
  manifests/c/Crate-CI/Typos/1.31.1/Crate-CI.Typos.installer.yaml
  manifests/c/Crate-CI/Typos/1.31.1/Crate-CI.Typos.locale.en-US.yaml
  manifests/c/Crate-CI/Typos/1.31.1/Crate-CI.Typos.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#243097 Move RazerInc.RazerInstaller4 2.1.0.766 to RazerInc.RazerInstaller.Synapse4 2.1.0.766
  manifests/r/RazerInc/RazerInstaller/Synapse4/2.1.0.779/RazerInc.RazerInstaller.Synapse4.installer.yaml
  manifests/r/RazerInc/RazerInstaller/Synapse4/2.1.0.779/RazerInc.RazerInstaller.Synapse4.locale.en-US.yaml
  manifests/r/RazerInc/RazerInstaller/Synapse4/2.1.0.779/RazerInc.RazerInstaller.Synapse4.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#244134 Standardize Formatting of manifests/s/SteelSeries/SteelSeriesEngine/3.19.2
  manifests/s/SteelSeries/SteelSeriesEngine/3.19.2/SteelSeries.SteelSeriesEngine.installer.yaml
  manifests/s/SteelSeries/SteelSeriesEngine/3.19.2/SteelSeries.SteelSeriesEngine.locale.en-US.yaml
  manifests/s/SteelSeries/SteelSeriesEngine/3.19.2/SteelSeries.SteelSeriesEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244107 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3785
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3785/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3785/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3785/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244106 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3734
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3734/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3734/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3734/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244104 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3477
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3477/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3477/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3477/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244108 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3904
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3904/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3904/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3904/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244091 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/21.1.7691.0
  manifests/m/MasterPackager/MasterPackager/21.1.7691.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/21.1.7691.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/21.1.7691.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244080 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/12.0.0
  manifests/j/JohannesMillan/superProductivity/12.0.0/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/12.0.0/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/12.0.0/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244075 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.0.2
  manifests/j/JohannesMillan/superProductivity/11.0.2/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.2/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.2/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244078 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.1.2
  manifests/j/JohannesMillan/superProductivity/11.1.2/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.2/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.2/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244055 Standardize Formatting of manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.2
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.2/CrystalDewWorld.CrystalDiskInfo.AoiEdition.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244056 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.06.24.2036/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244089 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/20.3.7519.0
  manifests/m/MasterPackager/MasterPackager/20.3.7519.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/20.3.7519.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/20.3.7519.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Moderator-Approved

#244049 Standardize Formatting of manifests/a/Adobe/Brackets/1.8
  manifests/a/Adobe/Brackets/1.8/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.8/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.8/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244125 Standardize Formatting of manifests/q/QMK/QMKToolbox/0.0.21
  manifests/q/QMK/QMKToolbox/0.0.21/QMK.QMKToolbox.installer.yaml
  manifests/q/QMK/QMKToolbox/0.0.21/QMK.QMKToolbox.locale.en-US.yaml
  manifests/q/QMK/QMKToolbox/0.0.21/QMK.QMKToolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244079 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.1.3
  manifests/j/JohannesMillan/superProductivity/11.1.3/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.3/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.3/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244074 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.0.0
  manifests/j/JohannesMillan/superProductivity/11.0.0/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.0/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.0/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244092 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/21.2.7837.0
  manifests/m/MasterPackager/MasterPackager/21.2.7837.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/21.2.7837.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/21.2.7837.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244054 Standardize Formatting of manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.1
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.1/CrystalDewWorld.CrystalDiskInfo.AoiEdition.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244126 Standardize Formatting of manifests/r/RIDI/Ridibooks/0.10.2
  manifests/r/RIDI/Ridibooks/0.10.2/RIDI.Ridibooks.installer.yaml
  manifests/r/RIDI/Ridibooks/0.10.2/RIDI.Ridibooks.locale.en-US.yaml
  manifests/r/RIDI/Ridibooks/0.10.2/RIDI.Ridibooks.locale.ko-KR.yaml
  manifests/r/RIDI/Ridibooks/0.10.2/RIDI.Ridibooks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244063 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.26.2000/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244095 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/22.2.8187.0
  manifests/m/MasterPackager/MasterPackager/22.2.8187.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/22.2.8187.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/22.2.8187.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244045 Standardize Formatting of manifests/a/Adobe/Brackets/1.4
  manifests/a/Adobe/Brackets/1.4/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.4/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.4/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244053 Standardize Formatting of manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.0
  manifests/c/CrystalDewWorld/CrystalDiskInfo/AoiEdition/9.2.0/CrystalDewWorld.CrystalDiskInfo.AoiEdition.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244077 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.1.1
  manifests/j/JohannesMillan/superProductivity/11.1.1/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.1/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.1.1/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244046 Standardize Formatting of manifests/a/Adobe/Brackets/1.5
  manifests/a/Adobe/Brackets/1.5/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.5/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.5/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244048 Standardize Formatting of manifests/a/Adobe/Brackets/1.7
  manifests/a/Adobe/Brackets/1.7/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.7/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.7/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244069 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.14.1314/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244098 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3233
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3233/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3233/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3233/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244044 Standardize Formatting of manifests/a/Adobe/Brackets/1.3
  manifests/a/Adobe/Brackets/1.3/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.3/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.3/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244040 Standardize Formatting of manifests/a/Adobe/Brackets/1.14.17740
  manifests/a/Adobe/Brackets/1.14.17740/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.14.17740/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.14.17740/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244096 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.2534
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.2534/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.2534/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.2534/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244042 Standardize Formatting of manifests/a/Adobe/Brackets/1.14.17770
  manifests/a/Adobe/Brackets/1.14.17770/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.14.17770/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.14.17770/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244068 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.02.09.1314/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244066 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2025.01.02.2300
  manifests/d/DuckStudio/FufuDevTools/2025.01.02.2300/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.01.02.2300/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2025.01.02.2300/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244032 Standardize Formatting of manifests/a/Adobe/Brackets/0.43
  manifests/a/Adobe/Brackets/0.43/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/0.43/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/0.43/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244081 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/12.0.1
  manifests/j/JohannesMillan/superProductivity/12.0.1/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/12.0.1/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/12.0.1/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244043 Standardize Formatting of manifests/a/Adobe/Brackets/1.2
  manifests/a/Adobe/Brackets/1.2/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.2/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.2/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244122 Standardize Formatting of manifests/p/Parallels/Parallels/18.3.22916
  manifests/p/Parallels/Parallels/18.3.22916/Parallels.Parallels.installer.yaml
  manifests/p/Parallels/Parallels/18.3.22916/Parallels.Parallels.locale.en-US.yaml
  manifests/p/Parallels/Parallels/18.3.22916/Parallels.Parallels.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244128 Standardize Formatting of manifests/r/RIDI/Ridibooks/0.9.5
  manifests/r/RIDI/Ridibooks/0.9.5/RIDI.Ridibooks.installer.yaml
  manifests/r/RIDI/Ridibooks/0.9.5/RIDI.Ridibooks.locale.en-US.yaml
  manifests/r/RIDI/Ridibooks/0.9.5/RIDI.Ridibooks.locale.ko-KR.yaml
  manifests/r/RIDI/Ridibooks/0.9.5/RIDI.Ridibooks.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244041 Standardize Formatting of manifests/a/Adobe/Brackets/1.14.17752
  manifests/a/Adobe/Brackets/1.14.17752/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.14.17752/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.14.17752/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244065 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.11.27.2000/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244094 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/22.1.8131.0
  manifests/m/MasterPackager/MasterPackager/22.1.8131.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/22.1.8131.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/22.1.8131.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244031 Standardize Formatting of manifests/a/Adobe/Brackets/0.42
  manifests/a/Adobe/Brackets/0.42/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/0.42/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/0.42/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244052 Standardize Formatting of manifests/b/BinaryFortress/WindowInspector/2.5.0.0
  manifests/b/BinaryFortress/WindowInspector/2.5.0.0/BinaryFortress.WindowInspector.installer.yaml
  manifests/b/BinaryFortress/WindowInspector/2.5.0.0/BinaryFortress.WindowInspector.locale.en-US.yaml
  manifests/b/BinaryFortress/WindowInspector/2.5.0.0/BinaryFortress.WindowInspector.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244039 Standardize Formatting of manifests/a/Adobe/Brackets/1.13.17699
  manifests/a/Adobe/Brackets/1.13.17699/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.13.17699/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.13.17699/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244100 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3331
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3331/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3331/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3331/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244102 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3442
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3442/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3442/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3442/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244050 Standardize Formatting of manifests/a/Adobe/Brackets/1.9
  manifests/a/Adobe/Brackets/1.9/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.9/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.9/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244036 Standardize Formatting of manifests/a/Adobe/Brackets/1.10
  manifests/a/Adobe/Brackets/1.10/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.10/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.10/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244038 Standardize Formatting of manifests/a/Adobe/Brackets/1.12.1
  manifests/a/Adobe/Brackets/1.12.1/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/1.12.1/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/1.12.1/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244076 Standardize Formatting of manifests/j/JohannesMillan/superProductivity/11.0.3
  manifests/j/JohannesMillan/superProductivity/11.0.3/JohannesMillan.superProductivity.installer.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.3/JohannesMillan.superProductivity.locale.en-US.yaml
  manifests/j/JohannesMillan/superProductivity/11.0.3/JohannesMillan.superProductivity.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244030 Standardize Formatting of manifests/a/Adobe/Brackets/0.41
  manifests/a/Adobe/Brackets/0.41/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/0.41/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/0.41/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244062 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.09.08.2000/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244093 Standardize Formatting of manifests/m/MasterPackager/MasterPackager/21.3.7996.0
  manifests/m/MasterPackager/MasterPackager/21.3.7996.0/MasterPackager.MasterPackager.installer.yaml
  manifests/m/MasterPackager/MasterPackager/21.3.7996.0/MasterPackager.MasterPackager.locale.en-US.yaml
  manifests/m/MasterPackager/MasterPackager/21.3.7996.0/MasterPackager.MasterPackager.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244099 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3284
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3284/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3284/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3284/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244133 Standardize Formatting of manifests/s/SteelSeries/SteelSeriesEngine/3.17.9
  manifests/s/SteelSeries/SteelSeriesEngine/3.17.9/SteelSeries.SteelSeriesEngine.installer.yaml
  manifests/s/SteelSeries/SteelSeriesEngine/3.17.9/SteelSeries.SteelSeriesEngine.locale.en-US.yaml
  manifests/s/SteelSeries/SteelSeriesEngine/3.17.9/SteelSeries.SteelSeriesEngine.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244064 Standardize Formatting of manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.installer.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.locale.en-GB.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.locale.en-US.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.locale.ja-JP.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.locale.zh-CN.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.locale.zh-TW.yaml
  manifests/d/DuckStudio/FufuDevTools/2024.10.01.0630/DuckStudio.FufuDevTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244156 Standardize Formatting of manifests/u/UniversalMediaServer/UniversalMediaServer/10.12.0
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.12.0/UniversalMediaServer.UniversalMediaServer.installer.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.12.0/UniversalMediaServer.UniversalMediaServer.locale.en-US.yaml
  manifests/u/UniversalMediaServer/UniversalMediaServer/10.12.0/UniversalMediaServer.UniversalMediaServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244158 Standardize Formatting of manifests/z/z-------------/cpod/1.28.1
  manifests/z/z-------------/cpod/1.28.1/z-------------.cpod.installer.yaml
  manifests/z/z-------------/cpod/1.28.1/z-------------.cpod.locale.en-US.yaml
  manifests/z/z-------------/cpod/1.28.1/z-------------.cpod.locale.zh-CN.yaml
  manifests/z/z-------------/cpod/1.28.1/z-------------.cpod.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#243960 Moonsworth.LunarClient version 3.2.25
  manifests/m/Moonsworth/LunarClient/3.2.25/Moonsworth.LunarClient.installer.yaml
  manifests/m/Moonsworth/LunarClient/3.2.25/Moonsworth.LunarClient.locale.en-US.yaml
  manifests/m/Moonsworth/LunarClient/3.2.25/Moonsworth.LunarClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244105 New version: Fly-io.flyctl version 0.3.95
  manifests/f/Fly-io/flyctl/0.3.95/Fly-io.flyctl.installer.yaml
  manifests/f/Fly-io/flyctl/0.3.95/Fly-io.flyctl.locale.en-US.yaml
  manifests/f/Fly-io/flyctl/0.3.95/Fly-io.flyctl.locale.ko-KR.yaml
  manifests/f/Fly-io/flyctl/0.3.95/Fly-io.flyctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244109 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.7030
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.7030/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.7030/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.7030/Microsoft.Azure.FunctionsCoreTools.locale.zh-CN.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/4.0.7030/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244162 Update: Apple.AppleSoftwareUpdate version 2.7.0.3
  manifests/a/Apple/AppleSoftwareUpdate/2.7.0.3/Apple.AppleSoftwareUpdate.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244124 Standardize Formatting of manifests/p/Parallels/Parallels/19.4.25171
  manifests/p/Parallels/Parallels/19.4.25171/Parallels.Parallels.installer.yaml
  manifests/p/Parallels/Parallels/19.4.25171/Parallels.Parallels.locale.en-US.yaml
  manifests/p/Parallels/Parallels/19.4.25171/Parallels.Parallels.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244150 New version: Jackett.Jackett version 0.22.1714
  manifests/j/Jackett/Jackett/0.22.1714/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1714/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1714/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#238516 Moved: Mozilla.Thunderbird.ESR.fi version 128.7.1
  manifests/m/Mozilla/Thunderbird/ESR/fi/128.7.1/Mozilla.Thunderbird.ESR.fi.installer.yaml
  manifests/m/Mozilla/Thunderbird/ESR/fi/128.7.1/Mozilla.Thunderbird.ESR.fi.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ESR/fi/128.7.1/Mozilla.Thunderbird.ESR.fi.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ESR/fi/128.7.1/Mozilla.Thunderbird.ESR.fi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Validation-Forbidden-URL-Error, New-Manifest, Bulk-Modify-Metadata

#244163 New version: Anthropic.Claude version 0.9.1
  manifests/a/Anthropic/Claude/0.9.1/Anthropic.Claude.installer.yaml
  manifests/a/Anthropic/Claude/0.9.1/Anthropic.Claude.locale.en-US.yaml
  manifests/a/Anthropic/Claude/0.9.1/Anthropic.Claude.locale.zh-CN.yaml
  manifests/a/Anthropic/Claude/0.9.1/Anthropic.Claude.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244071 Standardize Formatting of manifests/g/Google/AndroidStudio/2023.1.1.28
  manifests/g/Google/AndroidStudio/2023.1.1.28/Google.AndroidStudio.installer.yaml
  manifests/g/Google/AndroidStudio/2023.1.1.28/Google.AndroidStudio.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/2023.1.1.28/Google.AndroidStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244072 Standardize Formatting of manifests/g/Google/AndroidStudio/2023.2.1.25
  manifests/g/Google/AndroidStudio/2023.2.1.25/Google.AndroidStudio.installer.yaml
  manifests/g/Google/AndroidStudio/2023.2.1.25/Google.AndroidStudio.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/2023.2.1.25/Google.AndroidStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244160 New version: 8x8.Work version 8.21.2 (8.21.2.1)
  manifests/8/8x8/Work/8.21.2/8x8.Work.installer.yaml
  manifests/8/8x8/Work/8.21.2/8x8.Work.locale.en-US.yaml
  manifests/8/8x8/Work/8.21.2/8x8.Work.locale.zh-CN.yaml
  manifests/8/8x8/Work/8.21.2/8x8.Work.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244165 New version: Icecat.Icecat version 115.21.1
  manifests/i/Icecat/Icecat/115.21.1/Icecat.Icecat.installer.yaml
  manifests/i/Icecat/Icecat/115.21.1/Icecat.Icecat.locale.en-US.yaml
  manifests/i/Icecat/Icecat/115.21.1/Icecat.Icecat.locale.zh-CN.yaml
  manifests/i/Icecat/Icecat/115.21.1/Icecat.Icecat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Manifest

#238242 Moved: Mozilla.Thunderbird.ESR.en-GB version 128.7.0
  manifests/m/Mozilla/Thunderbird/ESR/en-GB/128.7.0/Mozilla.Thunderbird.ESR.en-GB.installer.yaml
  manifests/m/Mozilla/Thunderbird/ESR/en-GB/128.7.0/Mozilla.Thunderbird.ESR.en-GB.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ESR/en-GB/128.7.0/Mozilla.Thunderbird.ESR.en-GB.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ESR/en-GB/128.7.0/Mozilla.Thunderbird.ESR.en-GB.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Validation-Forbidden-URL-Error, New-Manifest, Bulk-Modify-Metadata

#244161 Update: Apple.Bonjour version 3.1.0.1
  manifests/a/Apple/Bonjour/3.1.0.1/Apple.Bonjour.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#238359 Moved: Mozilla.Thunderbird.ESR.es-MX version 128.4.1
  manifests/m/Mozilla/Thunderbird/ESR/es-MX/128.4.1/Mozilla.Thunderbird.ESR.es-MX.installer.yaml
  manifests/m/Mozilla/Thunderbird/ESR/es-MX/128.4.1/Mozilla.Thunderbird.ESR.es-MX.locale.en-US.yaml
  manifests/m/Mozilla/Thunderbird/ESR/es-MX/128.4.1/Mozilla.Thunderbird.ESR.es-MX.locale.zh-CN.yaml
  manifests/m/Mozilla/Thunderbird/ESR/es-MX/128.4.1/Mozilla.Thunderbird.ESR.es-MX.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Validation-Forbidden-URL-Error, New-Package, New-Manifest, Manifest-Metadata-Consistency, Bulk-Modify-Metadata

#242875 New package: UnityExtractor.UnityExtractor version 0.1.3
  manifests/u/UnityExtractor/UnityExtractor/0.1.3/UnityExtractor.UnityExtractor.installer.yaml
  manifests/u/UnityExtractor/UnityExtractor/0.1.3/UnityExtractor.UnityExtractor.locale.en-US.yaml
  manifests/u/UnityExtractor/UnityExtractor/0.1.3/UnityExtractor.UnityExtractor.locale.zh-CN.yaml
  manifests/u/UnityExtractor/UnityExtractor/0.1.3/UnityExtractor.UnityExtractor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#244101 Standardize Formatting of manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3388
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3388/Microsoft.Azure.FunctionsCoreTools.installer.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3388/Microsoft.Azure.FunctionsCoreTools.locale.en-US.yaml
  manifests/m/Microsoft/Azure/FunctionsCoreTools/3.0.3388/Microsoft.Azure.FunctionsCoreTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244033 Standardize Formatting of manifests/a/Adobe/Brackets/0.44
  manifests/a/Adobe/Brackets/0.44/Adobe.Brackets.installer.yaml
  manifests/a/Adobe/Brackets/0.44/Adobe.Brackets.locale.en-US.yaml
  manifests/a/Adobe/Brackets/0.44/Adobe.Brackets.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244166 New version: Microsoft.VisualStudioCode.Insiders version 1.99.0
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.99.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#243850 New package: DEIF.iectl version 0.0.0
  manifests/d/DEIF/iectl/0.0.0/DEIF.iectl.installer.yaml
  manifests/d/DEIF/iectl/0.0.0/DEIF.iectl.locale.en-US.yaml
  manifests/d/DEIF/iectl/0.0.0/DEIF.iectl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#244179 JanDeDobbeleer.OhMyPosh version 25.10.2
  manifests/j/JanDeDobbeleer/OhMyPosh/25.10.2/JanDeDobbeleer.OhMyPosh.installer.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/25.10.2/JanDeDobbeleer.OhMyPosh.locale.en-US.yaml
  manifests/j/JanDeDobbeleer/OhMyPosh/25.10.2/JanDeDobbeleer.OhMyPosh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#242857 KhronosGroup.VulkanRT version 1.4.309.0
  manifests/k/KhronosGroup/VulkanRT/1.4.309.0/KhronosGroup.VulkanRT.installer.yaml
  manifests/k/KhronosGroup/VulkanRT/1.4.309.0/KhronosGroup.VulkanRT.locale.en-US.yaml
  manifests/k/KhronosGroup/VulkanRT/1.4.309.0/KhronosGroup.VulkanRT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#243699 New version: Barry-ran.QtScrcpy version 3.1.3
  manifests/b/Barry-ran/QtScrcpy/3.1.3/Barry-ran.QtScrcpy.installer.yaml
  manifests/b/Barry-ran/QtScrcpy/3.1.3/Barry-ran.QtScrcpy.locale.en-US.yaml
  manifests/b/Barry-ran/QtScrcpy/3.1.3/Barry-ran.QtScrcpy.locale.zh-CN.yaml
  manifests/b/Barry-ran/QtScrcpy/3.1.3/Barry-ran.QtScrcpy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244007 New version: nektos.act version 0.2.76
  manifests/n/nektos/act/0.2.76/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.76/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.76/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244010 New version: XMediaRecode.XMediaRecode version 3.6.0.9
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.9/XMediaRecode.XMediaRecode.installer.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.9/XMediaRecode.XMediaRecode.locale.en-US.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.9/XMediaRecode.XMediaRecode.locale.zh-CN.yaml
  manifests/x/XMediaRecode/XMediaRecode/3.6.0.9/XMediaRecode.XMediaRecode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244009 New version: Finkitd.o.o.ManicTime version 25.1.3.0
  manifests/f/Finkitd/o/o/ManicTime/25.1.3.0/Finkitd.o.o.ManicTime.installer.yaml
  manifests/f/Finkitd/o/o/ManicTime/25.1.3.0/Finkitd.o.o.ManicTime.locale.en-US.yaml
  manifests/f/Finkitd/o/o/ManicTime/25.1.3.0/Finkitd.o.o.ManicTime.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244118 New version: Y2Z.Monolith version 2.10.1
  manifests/y/Y2Z/Monolith/2.10.1/Y2Z.Monolith.installer.yaml
  manifests/y/Y2Z/Monolith/2.10.1/Y2Z.Monolith.locale.en-US.yaml
  manifests/y/Y2Z/Monolith/2.10.1/Y2Z.Monolith.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#243638 New version: Roblox.Roblox version 1.6.2.6660608
  manifests/r/Roblox/Roblox/1.6.2.6660608/Roblox.Roblox.installer.yaml
  manifests/r/Roblox/Roblox/1.6.2.6660608/Roblox.Roblox.locale.en-US.yaml
  manifests/r/Roblox/Roblox/1.6.2.6660608/Roblox.Roblox.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#244155 Remove Google.AndroidStudio 2024.2.1.10 in favor of 2024.2.2.15
  manifests/g/Google/AndroidStudio/2024.2.1.10/Google.AndroidStudio.installer.yaml
  manifests/g/Google/AndroidStudio/2024.2.1.10/Google.AndroidStudio.locale.en-US.yaml
  manifests/g/Google/AndroidStudio/2024.2.1.10/Google.AndroidStudio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#244168 New version: Ecosia.EcosiaBrowser version 134.0.6998.16
  manifests/e/Ecosia/EcosiaBrowser/134.0.6998.16/Ecosia.EcosiaBrowser.installer.yaml
  manifests/e/Ecosia/EcosiaBrowser/134.0.6998.16/Ecosia.EcosiaBrowser.locale.en-US.yaml
  manifests/e/Ecosia/EcosiaBrowser/134.0.6998.16/Ecosia.EcosiaBrowser.locale.zh-CN.yaml
  manifests/e/Ecosia/EcosiaBrowser/134.0.6998.16/Ecosia.EcosiaBrowser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244131 Standardize Formatting of manifests/s/Sandboxie/Plus/0.7.5
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.installer.yaml
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.locale.en-US.yaml
  manifests/s/Sandboxie/Plus/0.7.5/Sandboxie.Plus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#244170 New version: Xiaoyaoyixia.KOOK version 0.93.2
  manifests/x/Xiaoyaoyixia/KOOK/0.93.2/Xiaoyaoyixia.KOOK.installer.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.93.2/Xiaoyaoyixia.KOOK.locale.en-US.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.93.2/Xiaoyaoyixia.KOOK.locale.zh-CN.yaml
  manifests/x/Xiaoyaoyixia/KOOK/0.93.2/Xiaoyaoyixia.KOOK.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244171 New version: VoyagerX.Vrew version 2.12.2
  manifests/v/VoyagerX/Vrew/2.12.2/VoyagerX.Vrew.installer.yaml
  manifests/v/VoyagerX/Vrew/2.12.2/VoyagerX.Vrew.locale.en-US.yaml
  manifests/v/VoyagerX/Vrew/2.12.2/VoyagerX.Vrew.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244173 New version: LukiLabs.Craft version 3.1.4
  manifests/l/LukiLabs/Craft/3.1.4/LukiLabs.Craft.installer.yaml
  manifests/l/LukiLabs/Craft/3.1.4/LukiLabs.Craft.locale.en-US.yaml
  manifests/l/LukiLabs/Craft/3.1.4/LukiLabs.Craft.locale.zh-CN.yaml
  manifests/l/LukiLabs/Craft/3.1.4/LukiLabs.Craft.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244180 New version: Brave.Brave.Beta version 135.1.78.72
  manifests/b/Brave/Brave/Beta/135.1.78.72/Brave.Brave.Beta.installer.yaml
  manifests/b/Brave/Brave/Beta/135.1.78.72/Brave.Brave.Beta.locale.en-US.yaml
  manifests/b/Brave/Brave/Beta/135.1.78.72/Brave.Brave.Beta.locale.zh-CN.yaml
  manifests/b/Brave/Brave/Beta/135.1.78.72/Brave.Brave.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244181 New version: Maxthon.Maxthon version 7.2.2.7200
  manifests/m/Maxthon/Maxthon/7.2.2.7200/Maxthon.Maxthon.installer.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.7200/Maxthon.Maxthon.locale.en-US.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.7200/Maxthon.Maxthon.locale.zh-CN.yaml
  manifests/m/Maxthon/Maxthon/7.2.2.7200/Maxthon.Maxthon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244174 New version: REALiX.HWiNFO version 8.24
  manifests/r/REALiX/HWiNFO/8.24/REALiX.HWiNFO.installer.yaml
  manifests/r/REALiX/HWiNFO/8.24/REALiX.HWiNFO.locale.en-US.yaml
  manifests/r/REALiX/HWiNFO/8.24/REALiX.HWiNFO.locale.zh-CN.yaml
  manifests/r/REALiX/HWiNFO/8.24/REALiX.HWiNFO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244187 New version: 360.360Chrome.X version 22.3.3137.64
  manifests/3/360/360Chrome/X/22.3.3137.64/360.360Chrome.X.installer.yaml
  manifests/3/360/360Chrome/X/22.3.3137.64/360.360Chrome.X.locale.en-US.yaml
  manifests/3/360/360Chrome/X/22.3.3137.64/360.360Chrome.X.locale.zh-CN.yaml
  manifests/3/360/360Chrome/X/22.3.3137.64/360.360Chrome.X.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#244182 New version: NetEase.UURemote version 3.8.0.3728
  manifests/n/NetEase/UURemote/3.8.0.3728/NetEase.UURemote.installer.yaml
  manifests/n/NetEase/UURemote/3.8.0.3728/NetEase.UURemote.locale.en-US.yaml
  manifests/n/NetEase/UURemote/3.8.0.3728/NetEase.UURemote.locale.zh-CN.yaml
  manifests/n/NetEase/UURemote/3.8.0.3728/NetEase.UURemote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244184 New version: Tencent.WeChat.Universal version 4.0.3.22
  manifests/t/Tencent/WeChat/Universal/4.0.3.22/Tencent.WeChat.Universal.installer.yaml
  manifests/t/Tencent/WeChat/Universal/4.0.3.22/Tencent.WeChat.Universal.locale.en-US.yaml
  manifests/t/Tencent/WeChat/Universal/4.0.3.22/Tencent.WeChat.Universal.locale.zh-Hans-CN.yaml
  manifests/t/Tencent/WeChat/Universal/4.0.3.22/Tencent.WeChat.Universal.locale.zh-Hans.yaml
  manifests/t/Tencent/WeChat/Universal/4.0.3.22/Tencent.WeChat.Universal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244190 New version: Grammarly.Grammarly version 1.2.148.1640
  manifests/g/Grammarly/Grammarly/1.2.148.1640/Grammarly.Grammarly.installer.yaml
  manifests/g/Grammarly/Grammarly/1.2.148.1640/Grammarly.Grammarly.locale.en-US.yaml
  manifests/g/Grammarly/Grammarly/1.2.148.1640/Grammarly.Grammarly.locale.zh-CN.yaml
  manifests/g/Grammarly/Grammarly/1.2.148.1640/Grammarly.Grammarly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244193 Update `PackageName` of RazerInc.RazerInstaller.Synapse4.locale.en-US…
  manifests/r/RazerInc/RazerInstaller/Synapse4/2.1.0.779/RazerInc.RazerInstaller.Synapse4.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244194 New version: AlgorandFoundation.AlgoKit version 2.6.2
  manifests/a/AlgorandFoundation/AlgoKit/2.6.2/AlgorandFoundation.AlgoKit.installer.yaml
  manifests/a/AlgorandFoundation/AlgoKit/2.6.2/AlgorandFoundation.AlgoKit.locale.en-US.yaml
  manifests/a/AlgorandFoundation/AlgoKit/2.6.2/AlgorandFoundation.AlgoKit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244204 New version: AngeloConvento.OverKeys version 0.2.10
  manifests/a/AngeloConvento/OverKeys/0.2.10/AngeloConvento.OverKeys.installer.yaml
  manifests/a/AngeloConvento/OverKeys/0.2.10/AngeloConvento.OverKeys.locale.en-US.yaml
  manifests/a/AngeloConvento/OverKeys/0.2.10/AngeloConvento.OverKeys.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244195 Version Update: Henry++.simplewall version 3.8.6
  manifests/h/Henry++/simplewall/3.8.6/Henry++.simplewall.installer.yaml
  manifests/h/Henry++/simplewall/3.8.6/Henry++.simplewall.locale.en-US.yaml
  manifests/h/Henry++/simplewall/3.8.6/Henry++.simplewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244198 New version: SwitTechnologiesInc.Swit version 12.2.3
  manifests/s/SwitTechnologiesInc/Swit/12.2.3/SwitTechnologiesInc.Swit.installer.yaml
  manifests/s/SwitTechnologiesInc/Swit/12.2.3/SwitTechnologiesInc.Swit.locale.en-US.yaml
  manifests/s/SwitTechnologiesInc/Swit/12.2.3/SwitTechnologiesInc.Swit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244200 New version: Readdle.Spark version 3.22.5 (3.22.5.103979)
  manifests/r/Readdle/Spark/3.22.5/Readdle.Spark.installer.yaml
  manifests/r/Readdle/Spark/3.22.5/Readdle.Spark.locale.en-US.yaml
  manifests/r/Readdle/Spark/3.22.5/Readdle.Spark.locale.zh-CN.yaml
  manifests/r/Readdle/Spark/3.22.5/Readdle.Spark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244191 New version: ByteDance.StreamingTool version 9.6.3
  manifests/b/ByteDance/StreamingTool/9.6.3/ByteDance.StreamingTool.installer.yaml
  manifests/b/ByteDance/StreamingTool/9.6.3/ByteDance.StreamingTool.locale.en-US.yaml
  manifests/b/ByteDance/StreamingTool/9.6.3/ByteDance.StreamingTool.locale.zh-CN.yaml
  manifests/b/ByteDance/StreamingTool/9.6.3/ByteDance.StreamingTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244113 Standardize Formatting of manifests/n/Nozbe/NozbePersonal/3.19.0
  manifests/n/Nozbe/NozbePersonal/3.19.0/Nozbe.NozbePersonal.installer.yaml
  manifests/n/Nozbe/NozbePersonal/3.19.0/Nozbe.NozbePersonal.locale.en-US.yaml
  manifests/n/Nozbe/NozbePersonal/3.19.0/Nozbe.NozbePersonal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244112 Standardize Formatting of manifests/n/Nozbe/NozbePersonal/3.13
  manifests/n/Nozbe/NozbePersonal/3.13/Nozbe.NozbePersonal.installer.yaml
  manifests/n/Nozbe/NozbePersonal/3.13/Nozbe.NozbePersonal.locale.en-US.yaml
  manifests/n/Nozbe/NozbePersonal/3.13/Nozbe.NozbePersonal.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244111 Standardize Formatting of manifests/n/NoMachine/NoMachineClient/7.3.2
  manifests/n/NoMachine/NoMachineClient/7.3.2/NoMachine.NoMachineClient.installer.yaml
  manifests/n/NoMachine/NoMachineClient/7.3.2/NoMachine.NoMachineClient.locale.en-US.yaml
  manifests/n/NoMachine/NoMachineClient/7.3.2/NoMachine.NoMachineClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244117 Standardize Formatting of manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.2.3.1851
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.2.3.1851/OpenVPNTechnologies.OpenVPNConnect.installer.yaml
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.2.3.1851/OpenVPNTechnologies.OpenVPNConnect.locale.en-US.yaml
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.2.3.1851/OpenVPNTechnologies.OpenVPNConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244121 Standardize Formatting of manifests/o/Oracle/JavaRuntimeEnvironment/8.0.251
  manifests/o/Oracle/JavaRuntimeEnvironment/8.0.251/Oracle.JavaRuntimeEnvironment.installer.yaml
  manifests/o/Oracle/JavaRuntimeEnvironment/8.0.251/Oracle.JavaRuntimeEnvironment.locale.en-US.yaml
  manifests/o/Oracle/JavaRuntimeEnvironment/8.0.251/Oracle.JavaRuntimeEnvironment.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#244175 New version: Tencent.Yuanbao version 1.8.1
  manifests/t/Tencent/Yuanbao/1.8.1/Tencent.Yuanbao.installer.yaml
  manifests/t/Tencent/Yuanbao/1.8.1/Tencent.Yuanbao.locale.en-US.yaml
  manifests/t/Tencent/Yuanbao/1.8.1/Tencent.Yuanbao.locale.zh-CN.yaml
  manifests/t/Tencent/Yuanbao/1.8.1/Tencent.Yuanbao.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#244206 New version: Proton.ProtonMailBridge version 3.19.0
  manifests/p/Proton/ProtonMailBridge/3.19.0/Proton.ProtonMailBridge.installer.yaml
  manifests/p/Proton/ProtonMailBridge/3.19.0/Proton.ProtonMailBridge.locale.en-US.yaml
  manifests/p/Proton/ProtonMailBridge/3.19.0/Proton.ProtonMailBridge.locale.zh-CN.yaml
  manifests/p/Proton/ProtonMailBridge/3.19.0/Proton.ProtonMailBridge.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#244119 Standardize Formatting of manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.3.0.2171
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.3.0.2171/OpenVPNTechnologies.OpenVPNConnect.installer.yaml
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.3.0.2171/OpenVPNTechnologies.OpenVPNConnect.locale.en-US.yaml
  manifests/o/OpenVPNTechnologies/OpenVPNConnect/3.3.0.2171/OpenVPNTechnologies.OpenVPNConnect.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
