Repository microsoft/winget-pkgs, pull requests merged in 2025-08, with the labels that each got.

#279512 New version: MongoDB.Compass.Full version 1.46.7
  manifests/m/MongoDB/Compass/Full/1.46.7/MongoDB.Compass.Full.installer.yaml
  manifests/m/MongoDB/Compass/Full/1.46.7/MongoDB.Compass.Full.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Full/1.46.7/MongoDB.Compass.Full.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279510 New version: MongoDB.Compass.Isolated version 1.46.7
  manifests/m/MongoDB/Compass/Isolated/1.46.7/MongoDB.Compass.Isolated.installer.yaml
  manifests/m/MongoDB/Compass/Isolated/1.46.7/MongoDB.Compass.Isolated.locale.en-US.yaml
  manifests/m/MongoDB/Compass/Isolated/1.46.7/MongoDB.Compass.Isolated.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279529 Update: KDE.KBruch version 25.11.70 (711)
  manifests/k/KDE/KBruch/25.11.70/KDE.KBruch.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279531 New version: Macabacus.Macabacus version 9.8.3
  manifests/m/Macabacus/Macabacus/9.8.3/Macabacus.Macabacus.installer.yaml
  manifests/m/Macabacus/Macabacus/9.8.3/Macabacus.Macabacus.locale.en-US.yaml
  manifests/m/Macabacus/Macabacus/9.8.3/Macabacus.Macabacus.locale.zh-CN.yaml
  manifests/m/Macabacus/Macabacus/9.8.3/Macabacus.Macabacus.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279535 New version: OpenJS.NodeJS.LTS version 22.18.0
  manifests/o/OpenJS/NodeJS/LTS/22.18.0/OpenJS.NodeJS.LTS.installer.yaml
  manifests/o/OpenJS/NodeJS/LTS/22.18.0/OpenJS.NodeJS.LTS.locale.en-US.yaml
  manifests/o/OpenJS/NodeJS/LTS/22.18.0/OpenJS.NodeJS.LTS.locale.zh-CN.yaml
  manifests/o/OpenJS/NodeJS/LTS/22.18.0/OpenJS.NodeJS.LTS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279536 New version: SST.opencode version 0.3.102
  manifests/s/SST/opencode/0.3.102/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.3.102/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.3.102/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.3.102/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#278097 New package: Cogin.QueueMonitor.Std version 1.6.34
  manifests/c/Cogin/QueueMonitor/Std/1.6.34/Cogin.QueueMonitor.Std.installer.yaml
  manifests/c/Cogin/QueueMonitor/Std/1.6.34/Cogin.QueueMonitor.Std.locale.en-US.yaml
  manifests/c/Cogin/QueueMonitor/Std/1.6.34/Cogin.QueueMonitor.Std.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#279566 New version: SST.opencode version 0.3.104
  manifests/s/SST/opencode/0.3.104/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.3.104/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.3.104/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.3.104/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279559 New version: KDE.Kate version 25.08.0 (25.08-9901)
  manifests/k/KDE/Kate/25.08.0/KDE.Kate.installer.yaml
  manifests/k/KDE/Kate/25.08.0/KDE.Kate.locale.en-US.yaml
  manifests/k/KDE/Kate/25.08.0/KDE.Kate.locale.zh-CN.yaml
  manifests/k/KDE/Kate/25.08.0/KDE.Kate.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#278429 New package: Catch22.HexEdit version 2.0.9
  manifests/c/Catch22/HexEdit/2.0.9/Catch22.HexEdit.installer.yaml
  manifests/c/Catch22/HexEdit/2.0.9/Catch22.HexEdit.locale.en-GB.yaml
  manifests/c/Catch22/HexEdit/2.0.9/Catch22.HexEdit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#278379 New package: emuell.restic-browser version 0.3.2
  manifests/e/emuell/restic-browser/0.3.2/emuell.restic-browser.installer.yaml
  manifests/e/emuell/restic-browser/0.3.2/emuell.restic-browser.locale.en-US.yaml
  manifests/e/emuell/restic-browser/0.3.2/emuell.restic-browser.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279508 New package: erez-c137.NetSpeedTray version 1.0.8.0
  manifests/e/erez-c137/NetSpeedTray/1.0.8.0/erez-c137.NetSpeedTray.installer.yaml
  manifests/e/erez-c137/NetSpeedTray/1.0.8.0/erez-c137.NetSpeedTray.locale.en-US.yaml
  manifests/e/erez-c137/NetSpeedTray/1.0.8.0/erez-c137.NetSpeedTray.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#278583 New package: LargeAddressAware.laa version 2.0.4
  manifests/l/LargeAddressAware/laa/2.0.4/LargeAddressAware.laa.installer.yaml
  manifests/l/LargeAddressAware/laa/2.0.4/LargeAddressAware.laa.locale.en-US.yaml
  manifests/l/LargeAddressAware/laa/2.0.4/LargeAddressAware.laa.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279563 Update: KDE.KTurtle version 25.11.70 (987)
  manifests/k/KDE/KTurtle/25.11.70/KDE.KTurtle.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279564 Update: KDE.Parley version 25.11.70 (800)
  manifests/k/KDE/Parley/25.11.70/KDE.Parley.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279595 New version: SST.opencode version 0.3.106
  manifests/s/SST/opencode/0.3.106/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.3.106/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.3.106/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.3.106/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#278376 New package: netheril96.securefs 1.1.1
  manifests/n/netheril96/securefs/1.1.1/netheril96.securefs.installer.yaml
  manifests/n/netheril96/securefs/1.1.1/netheril96.securefs.locale.en-US.yaml
  manifests/n/netheril96/securefs/1.1.1/netheril96.securefs.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279583 New version: KDE.Filelight version 25.08.0 (25.08-1828)
  manifests/k/KDE/Filelight/25.08.0/KDE.Filelight.installer.yaml
  manifests/k/KDE/Filelight/25.08.0/KDE.Filelight.locale.en-US.yaml
  manifests/k/KDE/Filelight/25.08.0/KDE.Filelight.locale.zh-CN.yaml
  manifests/k/KDE/Filelight/25.08.0/KDE.Filelight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279602 Update version: JAMSoftware.HeavyLoad version 4.0
  manifests/j/JAMSoftware/HeavyLoad/4.0/JAMSoftware.HeavyLoad.installer.yaml
  manifests/j/JAMSoftware/HeavyLoad/4.0/JAMSoftware.HeavyLoad.locale.de-DE.yaml
  manifests/j/JAMSoftware/HeavyLoad/4.0/JAMSoftware.HeavyLoad.locale.en-US.yaml
  manifests/j/JAMSoftware/HeavyLoad/4.0/JAMSoftware.HeavyLoad.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279594 New version: KDE.Okular version 25.08.0 (25.08-6587)
  manifests/k/KDE/Okular/25.08.0/KDE.Okular.installer.yaml
  manifests/k/KDE/Okular/25.08.0/KDE.Okular.locale.en-US.yaml
  manifests/k/KDE/Okular/25.08.0/KDE.Okular.locale.zh-CN.yaml
  manifests/k/KDE/Okular/25.08.0/KDE.Okular.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279649 Remove: Tencent.UGit version 5.36.0
  manifests/t/Tencent/UGit/5.36.0/Tencent.UGit.installer.yaml
  manifests/t/Tencent/UGit/5.36.0/Tencent.UGit.locale.en-US.yaml
  manifests/t/Tencent/UGit/5.36.0/Tencent.UGit.locale.zh-CN.yaml
  manifests/t/Tencent/UGit/5.36.0/Tencent.UGit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279582 Update: KDE.Bovo version master (690)
  manifests/k/KDE/Bovo/master/KDE.Bovo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279590 Update: KDE.KBreakOut version master (708)
  manifests/k/KDE/KBreakOut/master/KDE.KBreakOut.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279558 Update: KDE.Blinken version 25.11.70 (651)
  manifests/k/KDE/Blinken/25.11.70/KDE.Blinken.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279581 Update: KDE.Bomber version master (695)
  manifests/k/KDE/Bomber/master/KDE.Bomber.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279584 Update: KDE.Kapman version master (721)
  manifests/k/KDE/Kapman/master/KDE.Kapman.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279587 Update: KDE.KBlackbox version master (708)
  manifests/k/KDE/KBlackbox/master/KDE.KBlackbox.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279588 Update: KDE.KBlocks version master (763)
  manifests/k/KDE/KBlocks/master/KDE.KBlocks.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279591 Update: KDE.KDiamond version master (718)
  manifests/k/KDE/KDiamond/master/KDE.KDiamond.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279619 New version: Amazon.WorkspacesClient version 5.29.0.5570
  manifests/a/Amazon/WorkspacesClient/5.29.0.5570/Amazon.WorkspacesClient.installer.yaml
  manifests/a/Amazon/WorkspacesClient/5.29.0.5570/Amazon.WorkspacesClient.locale.en-US.yaml
  manifests/a/Amazon/WorkspacesClient/5.29.0.5570/Amazon.WorkspacesClient.locale.zh-CN.yaml
  manifests/a/Amazon/WorkspacesClient/5.29.0.5570/Amazon.WorkspacesClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#278626 Dillonb.nmuidi version 0.1.4
  manifests/d/Dillonb/nmuidi/0.1.4/Dillonb.nmuidi.installer.yaml
  manifests/d/Dillonb/nmuidi/0.1.4/Dillonb.nmuidi.locale.en-US.yaml
  manifests/d/Dillonb/nmuidi/0.1.4/Dillonb.nmuidi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#278671 RafaelCossovandeFrança.MenuTools version 1.0.2.20250729
  manifests/n/navossoc/MenuTools/1.0.2.20250729/navossoc.MenuTools.installer.yaml
  manifests/n/navossoc/MenuTools/1.0.2.20250729/navossoc.MenuTools.locale.en-US.yaml
  manifests/n/navossoc/MenuTools/1.0.2.20250729/navossoc.MenuTools.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279624 Update: KDE.Kigo version master (764)
  manifests/k/KDE/Kigo/master/KDE.Kigo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279629 Update: KDE.KJumpingCube version master (739)
  manifests/k/KDE/KJumpingCube/master/KDE.KJumpingCube.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279631 Update: KDE.Klines version master (704)
  manifests/k/KDE/Klines/master/KDE.Klines.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279626 Update: KDE.Killbots version master (773)
  manifests/k/KDE/Killbots/master/KDE.Killbots.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279634 Update: KDE.Kollision version master (682)
  manifests/k/KDE/Kollision/master/KDE.Kollision.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279633 Update: KDE.KMines version master (793)
  manifests/k/KDE/KMines/master/KDE.KMines.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279641 Update: KDE.KSudoku version master (850)
  manifests/k/KDE/KSudoku/master/KDE.KSudoku.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279644 Update: KDE.LSkat version master (756)
  manifests/k/KDE/LSkat/master/KDE.LSkat.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279642 New version: KDE.Lokalize version 25.08.0 (25.08-2268)
  manifests/k/KDE/Lokalize/25.08.0/KDE.Lokalize.installer.yaml
  manifests/k/KDE/Lokalize/25.08.0/KDE.Lokalize.locale.en-US.yaml
  manifests/k/KDE/Lokalize/25.08.0/KDE.Lokalize.locale.zh-CN.yaml
  manifests/k/KDE/Lokalize/25.08.0/KDE.Lokalize.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279656 New version: Forkgram.Forkgram version 6.0.0
  manifests/f/Forkgram/Forkgram/6.0.0/Forkgram.Forkgram.installer.yaml
  manifests/f/Forkgram/Forkgram/6.0.0/Forkgram.Forkgram.locale.en-US.yaml
  manifests/f/Forkgram/Forkgram/6.0.0/Forkgram.Forkgram.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279630 Update: KDE.KMahjongg version 25.04.3 (857)
  manifests/k/KDE/KMahjongg/25.04.3/KDE.KMahjongg.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279621 New version: Catsxp.Catsxp version 139.5.8.1
  manifests/c/Catsxp/Catsxp/139.5.8.1/Catsxp.Catsxp.installer.yaml
  manifests/c/Catsxp/Catsxp/139.5.8.1/Catsxp.Catsxp.locale.en-US.yaml
  manifests/c/Catsxp/Catsxp/139.5.8.1/Catsxp.Catsxp.locale.zh-CN.yaml
  manifests/c/Catsxp/Catsxp/139.5.8.1/Catsxp.Catsxp.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279636 Update: KDE.KReversi version master (743)
  manifests/k/KDE/KReversi/master/KDE.KReversi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279657 New version: kukuruzka165.materialgram version 6.0.0.1
  manifests/k/kukuruzka165/materialgram/6.0.0.1/kukuruzka165.materialgram.installer.yaml
  manifests/k/kukuruzka165/materialgram/6.0.0.1/kukuruzka165.materialgram.locale.en-US.yaml
  manifests/k/kukuruzka165/materialgram/6.0.0.1/kukuruzka165.materialgram.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279659 New version: bootandy.dust version 1.2.3
  manifests/b/bootandy/dust/1.2.3/bootandy.dust.installer.yaml
  manifests/b/bootandy/dust/1.2.3/bootandy.dust.locale.en-US.yaml
  manifests/b/bootandy/dust/1.2.3/bootandy.dust.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279667 New version: NicolasBonamy.Witsy version 2.12.4
  manifests/n/NicolasBonamy/Witsy/2.12.4/NicolasBonamy.Witsy.installer.yaml
  manifests/n/NicolasBonamy/Witsy/2.12.4/NicolasBonamy.Witsy.locale.en-US.yaml
  manifests/n/NicolasBonamy/Witsy/2.12.4/NicolasBonamy.Witsy.locale.zh-CN.yaml
  manifests/n/NicolasBonamy/Witsy/2.12.4/NicolasBonamy.Witsy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279632 Update: KDE.KNetWalk version master (684)
  manifests/k/KDE/KNetWalk/master/KDE.KNetWalk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279669 Update: SoftPerfect.NetWorx version 25.7
  manifests/s/SoftPerfect/NetWorx/25.7/SoftPerfect.NetWorx.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279668 New version: Postman.Postman version 11.56.4
  manifests/p/Postman/Postman/11.56.4/Postman.Postman.installer.yaml
  manifests/p/Postman/Postman/11.56.4/Postman.Postman.locale.en-US.yaml
  manifests/p/Postman/Postman/11.56.4/Postman.Postman.locale.zh-CN.yaml
  manifests/p/Postman/Postman/11.56.4/Postman.Postman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279672 New version: FastStone.Viewer version 8.1
  manifests/f/FastStone/Viewer/8.1/FastStone.Viewer.installer.yaml
  manifests/f/FastStone/Viewer/8.1/FastStone.Viewer.locale.en-US.yaml
  manifests/f/FastStone/Viewer/8.1/FastStone.Viewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279670 New version: SST.opencode version 0.3.109
  manifests/s/SST/opencode/0.3.109/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.3.109/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.3.109/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.3.109/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279498 New version: MillerPuckette.PureData version 0.56-0
  manifests/m/MillerPuckette/PureData/0.56-0/MillerPuckette.PureData.installer.yaml
  manifests/m/MillerPuckette/PureData/0.56-0/MillerPuckette.PureData.locale.en-US.yaml
  manifests/m/MillerPuckette/PureData/0.56-0/MillerPuckette.PureData.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279653 SmartSoft.SmartFTP version 10.0.3282.0
  manifests/s/SmartSoft/SmartFTP/10.0.3282.0/SmartSoft.SmartFTP.installer.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3282.0/SmartSoft.SmartFTP.locale.en-US.yaml
  manifests/s/SmartSoft/SmartFTP/10.0.3282.0/SmartSoft.SmartFTP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279635 Update: KDE.Kolf version master (849)
  manifests/k/KDE/Kolf/master/KDE.Kolf.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279680 Update: SoftPerfect.WiFiGuard version 25.6
  manifests/s/SoftPerfect/WiFiGuard/25.6/SoftPerfect.WiFiGuard.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279678 Update: KDE.Elisa version 25.11.70 (3977)
  manifests/k/KDE/Elisa/25.11.70/KDE.Elisa.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279683 New version: KDE.NeoChat version 25.08.0 (25.08-12547)
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.installer.yaml
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.locale.en-US.yaml
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.locale.zh-CN.yaml
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279689 New version: Jackett.Jackett version 0.22.2217
  manifests/j/Jackett/Jackett/0.22.2217/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.2217/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.2217/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279688 Dillonb.nmuidi version 0.1.5
  manifests/d/Dillonb/nmuidi/0.1.5/Dillonb.nmuidi.installer.yaml
  manifests/d/Dillonb/nmuidi/0.1.5/Dillonb.nmuidi.locale.en-US.yaml
  manifests/d/Dillonb/nmuidi/0.1.5/Dillonb.nmuidi.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279690 New version: BitSum.ProcessLasso.Beta version 16.0.1.15
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.15/BitSum.ProcessLasso.Beta.installer.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.15/BitSum.ProcessLasso.Beta.locale.en-US.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.15/BitSum.ProcessLasso.Beta.locale.zh-CN.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.15/BitSum.ProcessLasso.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279686 New version: OctopusDeploy.Server version 2025.2.13027
  manifests/o/OctopusDeploy/Server/2025.2.13027/OctopusDeploy.Server.installer.yaml
  manifests/o/OctopusDeploy/Server/2025.2.13027/OctopusDeploy.Server.locale.en-US.yaml
  manifests/o/OctopusDeploy/Server/2025.2.13027/OctopusDeploy.Server.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279637 Update: KDE.KShisen version master (740)
  manifests/k/KDE/KShisen/master/KDE.KShisen.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279639 Update: KDE.KSpaceDuel version master (641)
  manifests/k/KDE/KSpaceDuel/master/KDE.KSpaceDuel.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279697 New version: Huawei.PCClone version 14.0.5.970(C233) (14.0.5.970)
  manifests/h/Huawei/PCClone/14.0.5.970(C233)/Huawei.PCClone.installer.yaml
  manifests/h/Huawei/PCClone/14.0.5.970(C233)/Huawei.PCClone.locale.en-US.yaml
  manifests/h/Huawei/PCClone/14.0.5.970(C233)/Huawei.PCClone.locale.zh-CN.yaml
  manifests/h/Huawei/PCClone/14.0.5.970(C233)/Huawei.PCClone.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279696 New version: ByteDance.StreamingTool version 10.3.2
  manifests/b/ByteDance/StreamingTool/10.3.2/ByteDance.StreamingTool.installer.yaml
  manifests/b/ByteDance/StreamingTool/10.3.2/ByteDance.StreamingTool.locale.en-US.yaml
  manifests/b/ByteDance/StreamingTool/10.3.2/ByteDance.StreamingTool.locale.zh-CN.yaml
  manifests/b/ByteDance/StreamingTool/10.3.2/ByteDance.StreamingTool.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279702 New version: OpenSCAD.OpenSCAD.Nightly version 2025.07.31
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.07.31/OpenSCAD.OpenSCAD.Nightly.installer.yaml
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.07.31/OpenSCAD.OpenSCAD.Nightly.locale.en-US.yaml
  manifests/o/OpenSCAD/OpenSCAD/Nightly/2025.07.31/OpenSCAD.OpenSCAD.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279713 New version: FrancisBanyikwa.MediaDownloader version 5.4.2
  manifests/f/FrancisBanyikwa/MediaDownloader/5.4.2/FrancisBanyikwa.MediaDownloader.installer.yaml
  manifests/f/FrancisBanyikwa/MediaDownloader/5.4.2/FrancisBanyikwa.MediaDownloader.locale.en-US.yaml
  manifests/f/FrancisBanyikwa/MediaDownloader/5.4.2/FrancisBanyikwa.MediaDownloader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279712 New version: ElectronCommunity.ElectronFiddle version 0.37.2
  manifests/e/ElectronCommunity/ElectronFiddle/0.37.2/ElectronCommunity.ElectronFiddle.installer.yaml
  manifests/e/ElectronCommunity/ElectronFiddle/0.37.2/ElectronCommunity.ElectronFiddle.locale.en-US.yaml
  manifests/e/ElectronCommunity/ElectronFiddle/0.37.2/ElectronCommunity.ElectronFiddle.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279699 Update: KDE.KSudoku version master (852)
  manifests/k/KDE/KSudoku/master/KDE.KSudoku.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#279710 New version: Tandem.Tandem version 2.2.1632
  manifests/t/Tandem/Tandem/2.2.1632/Tandem.Tandem.installer.yaml
  manifests/t/Tandem/Tandem/2.2.1632/Tandem.Tandem.locale.en-US.yaml
  manifests/t/Tandem/Tandem/2.2.1632/Tandem.Tandem.locale.zh-CN.yaml
  manifests/t/Tandem/Tandem/2.2.1632/Tandem.Tandem.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279720 New version: AnyDesk.AnyDesk version 9.5.11
  manifests/a/AnyDesk/AnyDesk/9.5.11/AnyDesk.AnyDesk.installer.yaml
  manifests/a/AnyDesk/AnyDesk/9.5.11/AnyDesk.AnyDesk.locale.en-US.yaml
  manifests/a/AnyDesk/AnyDesk/9.5.11/AnyDesk.AnyDesk.locale.zh-CN.yaml
  manifests/a/AnyDesk/AnyDesk/9.5.11/AnyDesk.AnyDesk.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279725 Update: Waytech.CloudDrive2 version 1.0 (0.9.3)
  manifests/w/Waytech/CloudDrive2/1.0/Waytech.CloudDrive2.installer.yaml
  manifests/w/Waytech/CloudDrive2/1.0/Waytech.CloudDrive2.locale.en-US.yaml
  manifests/w/Waytech/CloudDrive2/1.0/Waytech.CloudDrive2.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279722 New version: NativeSoft.NativeRest version 2.7.4
  manifests/n/NativeSoft/NativeRest/2.7.4/NativeSoft.NativeRest.installer.yaml
  manifests/n/NativeSoft/NativeRest/2.7.4/NativeSoft.NativeRest.locale.en-US.yaml
  manifests/n/NativeSoft/NativeRest/2.7.4/NativeSoft.NativeRest.locale.zh-CN.yaml
  manifests/n/NativeSoft/NativeRest/2.7.4/NativeSoft.NativeRest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279723 New version: Ruihu.Apifox version 2.7.26
  manifests/r/Ruihu/Apifox/2.7.26/Ruihu.Apifox.installer.yaml
  manifests/r/Ruihu/Apifox/2.7.26/Ruihu.Apifox.locale.en-US.yaml
  manifests/r/Ruihu/Apifox/2.7.26/Ruihu.Apifox.locale.zh-CN.yaml
  manifests/r/Ruihu/Apifox/2.7.26/Ruihu.Apifox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279724 New version: Tencent.DeskGo version 4.2.1656.127
  manifests/t/Tencent/DeskGo/4.2.1656.127/Tencent.DeskGo.installer.yaml
  manifests/t/Tencent/DeskGo/4.2.1656.127/Tencent.DeskGo.locale.en-US.yaml
  manifests/t/Tencent/DeskGo/4.2.1656.127/Tencent.DeskGo.locale.zh-CN.yaml
  manifests/t/Tencent/DeskGo/4.2.1656.127/Tencent.DeskGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279728 Update: Archi.Archi version 5.6.0
  manifests/a/Archi/Archi/5.6.0/Archi.Archi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279731 LogicCircuit.LogicCircuit version 2.24.02.27
  manifests/l/LogicCircuit/LogicCircuit/2.24.02.27/LogicCircuit.LogicCircuit.installer.yaml
  manifests/l/LogicCircuit/LogicCircuit/2.24.02.27/LogicCircuit.LogicCircuit.locale.en-US.yaml
  manifests/l/LogicCircuit/LogicCircuit/2.24.02.27/LogicCircuit.LogicCircuit.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279708 Update: RARLab.WinRAR version 7.13.0 (7.13)
  manifests/r/RARLab/WinRAR/7.13.0/RARLab.WinRAR.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279749 New version: Speakeasy.speakeasy 1.595.2
  manifests/s/Speakeasy/speakeasy/1.595.2/Speakeasy.speakeasy.installer.yaml
  manifests/s/Speakeasy/speakeasy/1.595.2/Speakeasy.speakeasy.locale.en-US.yaml
  manifests/s/Speakeasy/speakeasy/1.595.2/Speakeasy.speakeasy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279751 New version: NodirTemirkhodjaev.FortFirewall version 3.18.10
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.18.10/NodirTemirkhodjaev.FortFirewall.installer.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.18.10/NodirTemirkhodjaev.FortFirewall.locale.en-US.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.18.10/NodirTemirkhodjaev.FortFirewall.locale.zh-CN.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.18.10/NodirTemirkhodjaev.FortFirewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279750 Update: KDE.NeoChat version 25.08.0 (25.08-12555)
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#279380 New package: LANCOM.TrustedAccessClient version 6.23.30776
  manifests/l/LANCOM/TrustedAccessClient/6.23.30776/LANCOM.TrustedAccessClient.installer.yaml
  manifests/l/LANCOM/TrustedAccessClient/6.23.30776/LANCOM.TrustedAccessClient.locale.en-US.yaml
  manifests/l/LANCOM/TrustedAccessClient/6.23.30776/LANCOM.TrustedAccessClient.locale.zh-CN.yaml
  manifests/l/LANCOM/TrustedAccessClient/6.23.30776/LANCOM.TrustedAccessClient.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279758 New package: Untis.Untis.2025 version 2025
  manifests/u/Untis/Untis/2025/2025/Untis.Untis.2025.installer.yaml
  manifests/u/Untis/Untis/2025/2025/Untis.Untis.2025.locale.de-AT.yaml
  manifests/u/Untis/Untis/2025/2025/Untis.Untis.2025.locale.en-US.yaml
  manifests/u/Untis/Untis/2025/2025/Untis.Untis.2025.locale.zh-CN.yaml
  manifests/u/Untis/Untis/2025/2025/Untis.Untis.2025.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279761 Update: marha.VcXsrv version 21.1.16.1
  manifests/m/marha/VcXsrv/21.1.16.1/marha.VcXsrv.installer.yaml
  manifests/m/marha/VcXsrv/21.1.16.1/marha.VcXsrv.locale.en-US.yaml
  manifests/m/marha/VcXsrv/21.1.16.1/marha.VcXsrv.locale.zh-CN.yaml
  manifests/m/marha/VcXsrv/21.1.16.1/marha.VcXsrv.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279752 Update: RARLab.WinRAR version 7.13.0 (7.13)
  manifests/r/RARLab/WinRAR/7.13.0/RARLab.WinRAR.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279765 New version: UpNote.UpNote version 9.12.4
  manifests/u/UpNote/UpNote/9.12.4/UpNote.UpNote.installer.yaml
  manifests/u/UpNote/UpNote/9.12.4/UpNote.UpNote.locale.en-US.yaml
  manifests/u/UpNote/UpNote/9.12.4/UpNote.UpNote.locale.zh-CN.yaml
  manifests/u/UpNote/UpNote/9.12.4/UpNote.UpNote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#279767 New version: Microsoft.EdgeDriver version 138.0.3351.121
  manifests/m/Microsoft/EdgeDriver/138.0.3351.121/Microsoft.EdgeDriver.installer.yaml
  manifests/m/Microsoft/EdgeDriver/138.0.3351.121/Microsoft.EdgeDriver.locale.en-US.yaml
  manifests/m/Microsoft/EdgeDriver/138.0.3351.121/Microsoft.EdgeDriver.locale.zh-CN.yaml
  manifests/m/Microsoft/EdgeDriver/138.0.3351.121/Microsoft.EdgeDriver.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279772 Remove Nonexistent Version
  manifests/t/Tencent/DeskGo/3.3.1527.127/Tencent.DeskGo.installer.yaml
  manifests/t/Tencent/DeskGo/3.3.1527.127/Tencent.DeskGo.locale.en-US.yaml
  manifests/t/Tencent/DeskGo/3.3.1527.127/Tencent.DeskGo.locale.zh-CN.yaml
  manifests/t/Tencent/DeskGo/3.3.1527.127/Tencent.DeskGo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279773 Update Netron to 8.4.7
  manifests/l/LutzRoeder/Netron/8.4.7/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/8.4.7/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/8.4.7/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279774 New version: Tencent.TencentVideo version 11.130.1224.0
  manifests/t/Tencent/TencentVideo/11.130.1224.0/Tencent.TencentVideo.installer.yaml
  manifests/t/Tencent/TencentVideo/11.130.1224.0/Tencent.TencentVideo.locale.en-US.yaml
  manifests/t/Tencent/TencentVideo/11.130.1224.0/Tencent.TencentVideo.locale.zh-CN.yaml
  manifests/t/Tencent/TencentVideo/11.130.1224.0/Tencent.TencentVideo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279795 Remove version: Google.Chrome.Canary version 140.0.7301.0
  manifests/g/Google/Chrome/Canary/140.0.7301.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/140.0.7301.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/140.0.7301.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/140.0.7301.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/140.0.7301.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279794 Remove version: Google.Chrome.Canary version 140.0.7302.0
  manifests/g/Google/Chrome/Canary/140.0.7302.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/140.0.7302.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/140.0.7302.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/140.0.7302.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/140.0.7302.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279777 New version: Anysphere.Cursor version 1.3.8
  manifests/a/Anysphere/Cursor/1.3.8/Anysphere.Cursor.installer.yaml
  manifests/a/Anysphere/Cursor/1.3.8/Anysphere.Cursor.locale.en-US.yaml
  manifests/a/Anysphere/Cursor/1.3.8/Anysphere.Cursor.locale.zh-CN.yaml
  manifests/a/Anysphere/Cursor/1.3.8/Anysphere.Cursor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279782 New version: WeMod.WeMod.Beta version 11.0.0-beta02
  manifests/w/WeMod/WeMod/Beta/11.0.0-beta02/WeMod.WeMod.Beta.installer.yaml
  manifests/w/WeMod/WeMod/Beta/11.0.0-beta02/WeMod.WeMod.Beta.locale.en-US.yaml
  manifests/w/WeMod/WeMod/Beta/11.0.0-beta02/WeMod.WeMod.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279799 Remove version: mikf.gallery-dl.Nightly version 2025.07.17
  manifests/m/mikf/gallery-dl/Nightly/2025.07.17/mikf.gallery-dl.Nightly.installer.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.07.17/mikf.gallery-dl.Nightly.locale.en-US.yaml
  manifests/m/mikf/gallery-dl/Nightly/2025.07.17/mikf.gallery-dl.Nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279788 New version: jdx.mise version 2025.8.1
  manifests/j/jdx/mise/2025.8.1/jdx.mise.installer.yaml
  manifests/j/jdx/mise/2025.8.1/jdx.mise.locale.en-US.yaml
  manifests/j/jdx/mise/2025.8.1/jdx.mise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279797 New version: NetEase.UURemote version 4.2.6.4677
  manifests/n/NetEase/UURemote/4.2.6.4677/NetEase.UURemote.installer.yaml
  manifests/n/NetEase/UURemote/4.2.6.4677/NetEase.UURemote.locale.en-US.yaml
  manifests/n/NetEase/UURemote/4.2.6.4677/NetEase.UURemote.locale.zh-CN.yaml
  manifests/n/NetEase/UURemote/4.2.6.4677/NetEase.UURemote.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279798 New version: SST.opencode version 0.3.111
  manifests/s/SST/opencode/0.3.111/SST.opencode.installer.yaml
  manifests/s/SST/opencode/0.3.111/SST.opencode.locale.en-US.yaml
  manifests/s/SST/opencode/0.3.111/SST.opencode.locale.zh-CN.yaml
  manifests/s/SST/opencode/0.3.111/SST.opencode.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279791 New version: BitSum.ProcessLasso.Beta version 16.0.1.16
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.16/BitSum.ProcessLasso.Beta.installer.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.16/BitSum.ProcessLasso.Beta.locale.en-US.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.16/BitSum.ProcessLasso.Beta.locale.zh-CN.yaml
  manifests/b/BitSum/ProcessLasso/Beta/16.0.1.16/BitSum.ProcessLasso.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279314 New version: Jan.Jan version 0.6.6
  manifests/j/Jan/Jan/0.6.6/Jan.Jan.installer.yaml
  manifests/j/Jan/Jan/0.6.6/Jan.Jan.locale.en-US.yaml
  manifests/j/Jan/Jan/0.6.6/Jan.Jan.locale.zh-CN.yaml
  manifests/j/Jan/Jan/0.6.6/Jan.Jan.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest

#279796 New version: Microsoft.Bicep version 0.37.4
  manifests/m/Microsoft/Bicep/0.37.4/Microsoft.Bicep.installer.yaml
  manifests/m/Microsoft/Bicep/0.37.4/Microsoft.Bicep.locale.en-US.yaml
  manifests/m/Microsoft/Bicep/0.37.4/Microsoft.Bicep.locale.zh-CN.yaml
  manifests/m/Microsoft/Bicep/0.37.4/Microsoft.Bicep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279789 New version: Gruntwork.Terragrunt version 0.84.0
  manifests/g/Gruntwork/Terragrunt/0.84.0/Gruntwork.Terragrunt.installer.yaml
  manifests/g/Gruntwork/Terragrunt/0.84.0/Gruntwork.Terragrunt.locale.en-US.yaml
  manifests/g/Gruntwork/Terragrunt/0.84.0/Gruntwork.Terragrunt.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279803 Update: KDE.NeoChat version 25.08.0 (25.08-12559)
  manifests/k/KDE/NeoChat/25.08.0/KDE.NeoChat.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279805 New version: WeMod.WeMod version 11.0.0
  manifests/w/WeMod/WeMod/11.0.0/WeMod.WeMod.installer.yaml
  manifests/w/WeMod/WeMod/11.0.0/WeMod.WeMod.locale.en-US.yaml
  manifests/w/WeMod/WeMod/11.0.0/WeMod.WeMod.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279819 Remove version: yt-dlp.yt-dlp.nightly version 2024.02.25.232703
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.25.232703/yt-dlp.yt-dlp.nightly.installer.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.25.232703/yt-dlp.yt-dlp.nightly.locale.en-US.yaml
  manifests/y/yt-dlp/yt-dlp/nightly/2024.02.25.232703/yt-dlp.yt-dlp.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#279813 JiriPolasek.RecentFilesforCommandPalette version 0.6.1
  manifests/j/JiriPolasek/RecentFilesforCommandPalette/0.6.1/JiriPolasek.RecentFilesforCommandPalette.installer.yaml
  manifests/j/JiriPolasek/RecentFilesforCommandPalette/0.6.1/JiriPolasek.RecentFilesforCommandPalette.locale.en-US.yaml
  manifests/j/JiriPolasek/RecentFilesforCommandPalette/0.6.1/JiriPolasek.RecentFilesforCommandPalette.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279808 New version: Amazon.AWSCLI version 2.28.1
  manifests/a/Amazon/AWSCLI/2.28.1/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.28.1/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.28.1/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279815 New version: Snowflake.SnowSQL version 1.4.4
  manifests/s/Snowflake/SnowSQL/1.4.4/Snowflake.SnowSQL.installer.yaml
  manifests/s/Snowflake/SnowSQL/1.4.4/Snowflake.SnowSQL.locale.en-US.yaml
  manifests/s/Snowflake/SnowSQL/1.4.4/Snowflake.SnowSQL.locale.zh-CN.yaml
  manifests/s/Snowflake/SnowSQL/1.4.4/Snowflake.SnowSQL.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279820 New version: raphamorim.rio version 0.2.24
  manifests/r/raphamorim/rio/0.2.24/raphamorim.rio.installer.yaml
  manifests/r/raphamorim/rio/0.2.24/raphamorim.rio.locale.en-US.yaml
  manifests/r/raphamorim/rio/0.2.24/raphamorim.rio.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#279809 Update: RARLab.WinRAR version 7.13.0 (7.13)
  manifests/r/RARLab/WinRAR/7.13.0/RARLab.WinRAR.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279826 Update: Mozilla.Firefox.DeveloperEdition.af version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/af/142.0/Mozilla.Firefox.DeveloperEdition.af.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/af/142.0/Mozilla.Firefox.DeveloperEdition.af.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279881 Update: Mozilla.Firefox.DeveloperEdition.ko version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/142.0/Mozilla.Firefox.DeveloperEdition.ko.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/142.0/Mozilla.Firefox.DeveloperEdition.ko.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279889 Update: Mozilla.Firefox.DeveloperEdition.nb-NO version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nb-NO/142.0/Mozilla.Firefox.DeveloperEdition.nb-NO.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/nb-NO/142.0/Mozilla.Firefox.DeveloperEdition.nb-NO.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279899 Update: Mozilla.Firefox.DeveloperEdition.ro version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/142.0/Mozilla.Firefox.DeveloperEdition.ro.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/142.0/Mozilla.Firefox.DeveloperEdition.ro.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279895 Update: Mozilla.Firefox.DeveloperEdition.pl version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pl/142.0/Mozilla.Firefox.DeveloperEdition.pl.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/pl/142.0/Mozilla.Firefox.DeveloperEdition.pl.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279921 Update: Mozilla.Firefox.DeveloperEdition.vi version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/vi/142.0/Mozilla.Firefox.DeveloperEdition.vi.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/vi/142.0/Mozilla.Firefox.DeveloperEdition.vi.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279924 Update: Mozilla.Firefox.DeveloperEdition.zh-TW version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/zh-TW/142.0/Mozilla.Firefox.DeveloperEdition.zh-TW.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/zh-TW/142.0/Mozilla.Firefox.DeveloperEdition.zh-TW.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279834 Update: Mozilla.Firefox.DeveloperEdition.br version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/br/142.0/Mozilla.Firefox.DeveloperEdition.br.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/br/142.0/Mozilla.Firefox.DeveloperEdition.br.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279877 Update: Mozilla.Firefox.DeveloperEdition.kab version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/142.0/Mozilla.Firefox.DeveloperEdition.kab.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/142.0/Mozilla.Firefox.DeveloperEdition.kab.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279859 Update: Mozilla.Firefox.DeveloperEdition.fy-NL version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fy-NL/142.0/Mozilla.Firefox.DeveloperEdition.fy-NL.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/fy-NL/142.0/Mozilla.Firefox.DeveloperEdition.fy-NL.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279858 Update: Mozilla.Firefox.DeveloperEdition.fur version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fur/142.0/Mozilla.Firefox.DeveloperEdition.fur.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/fur/142.0/Mozilla.Firefox.DeveloperEdition.fur.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279833 Update: Mozilla.Firefox.DeveloperEdition.bn version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bn/142.0/Mozilla.Firefox.DeveloperEdition.bn.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/bn/142.0/Mozilla.Firefox.DeveloperEdition.bn.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279832 Update: Mozilla.Firefox.DeveloperEdition.bg version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bg/142.0/Mozilla.Firefox.DeveloperEdition.bg.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/bg/142.0/Mozilla.Firefox.DeveloperEdition.bg.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279845 Update: Mozilla.Firefox.DeveloperEdition.en-CA version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/en-CA/142.0/Mozilla.Firefox.DeveloperEdition.en-CA.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/en-CA/142.0/Mozilla.Firefox.DeveloperEdition.en-CA.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279842 Update: Mozilla.Firefox.DeveloperEdition.de version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/de/142.0/Mozilla.Firefox.DeveloperEdition.de.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/de/142.0/Mozilla.Firefox.DeveloperEdition.de.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279851 Update: Mozilla.Firefox.DeveloperEdition.es-MX version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-MX/142.0/Mozilla.Firefox.DeveloperEdition.es-MX.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-MX/142.0/Mozilla.Firefox.DeveloperEdition.es-MX.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279854 Update: Mozilla.Firefox.DeveloperEdition.fa version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fa/142.0/Mozilla.Firefox.DeveloperEdition.fa.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/fa/142.0/Mozilla.Firefox.DeveloperEdition.fa.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279860 Update: Mozilla.Firefox.DeveloperEdition.ga-IE version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ga-IE/142.0/Mozilla.Firefox.DeveloperEdition.ga-IE.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ga-IE/142.0/Mozilla.Firefox.DeveloperEdition.ga-IE.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279862 Update: Mozilla.Firefox.DeveloperEdition.gl version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/gl/142.0/Mozilla.Firefox.DeveloperEdition.gl.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/gl/142.0/Mozilla.Firefox.DeveloperEdition.gl.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279852 Update: Mozilla.Firefox.DeveloperEdition.et version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/et/142.0/Mozilla.Firefox.DeveloperEdition.et.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/et/142.0/Mozilla.Firefox.DeveloperEdition.et.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279866 Update: Mozilla.Firefox.DeveloperEdition.hi-IN version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hi-IN/142.0/Mozilla.Firefox.DeveloperEdition.hi-IN.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/hi-IN/142.0/Mozilla.Firefox.DeveloperEdition.hi-IN.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#279867 Update: Mozilla.Firefox.DeveloperEdition.hr version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hr/142.0/Mozilla.Firefox.DeveloperEdition.hr.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/hr/142.0/Mozilla.Firefox.DeveloperEdition.hr.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279870 Update: Mozilla.Firefox.DeveloperEdition.hy-AM version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hy-AM/142.0/Mozilla.Firefox.DeveloperEdition.hy-AM.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/hy-AM/142.0/Mozilla.Firefox.DeveloperEdition.hy-AM.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279871 Update: Mozilla.Firefox.DeveloperEdition.ia version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ia/142.0/Mozilla.Firefox.DeveloperEdition.ia.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ia/142.0/Mozilla.Firefox.DeveloperEdition.ia.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279872 Update: Mozilla.Firefox.DeveloperEdition.id version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/id/142.0/Mozilla.Firefox.DeveloperEdition.id.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/id/142.0/Mozilla.Firefox.DeveloperEdition.id.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279873 Update: Mozilla.Firefox.DeveloperEdition.is version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/is/142.0/Mozilla.Firefox.DeveloperEdition.is.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/is/142.0/Mozilla.Firefox.DeveloperEdition.is.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279880 Update: Mozilla.Firefox.DeveloperEdition.kn version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kn/142.0/Mozilla.Firefox.DeveloperEdition.kn.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/kn/142.0/Mozilla.Firefox.DeveloperEdition.kn.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279882 Update: Mozilla.Firefox.DeveloperEdition.lij version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/lij/142.0/Mozilla.Firefox.DeveloperEdition.lij.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/lij/142.0/Mozilla.Firefox.DeveloperEdition.lij.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279884 Update: Mozilla.Firefox.DeveloperEdition.lv version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/lv/142.0/Mozilla.Firefox.DeveloperEdition.lv.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/lv/142.0/Mozilla.Firefox.DeveloperEdition.lv.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279876 Update: Mozilla.Firefox.DeveloperEdition.ka version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ka/142.0/Mozilla.Firefox.DeveloperEdition.ka.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ka/142.0/Mozilla.Firefox.DeveloperEdition.ka.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279890 Update: Mozilla.Firefox.DeveloperEdition.ne-NP version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ne-NP/142.0/Mozilla.Firefox.DeveloperEdition.ne-NP.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ne-NP/142.0/Mozilla.Firefox.DeveloperEdition.ne-NP.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279885 Update: Mozilla.Firefox.DeveloperEdition.mk version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/mk/142.0/Mozilla.Firefox.DeveloperEdition.mk.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/mk/142.0/Mozilla.Firefox.DeveloperEdition.mk.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279892 Update: Mozilla.Firefox.DeveloperEdition.nn-NO version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nn-NO/142.0/Mozilla.Firefox.DeveloperEdition.nn-NO.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/nn-NO/142.0/Mozilla.Firefox.DeveloperEdition.nn-NO.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279900 Update: Mozilla.Firefox.DeveloperEdition.ru version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ru/142.0/Mozilla.Firefox.DeveloperEdition.ru.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ru/142.0/Mozilla.Firefox.DeveloperEdition.ru.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279897 Update: Mozilla.Firefox.DeveloperEdition.pt-PT version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-PT/142.0/Mozilla.Firefox.DeveloperEdition.pt-PT.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-PT/142.0/Mozilla.Firefox.DeveloperEdition.pt-PT.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279902 Update: Mozilla.Firefox.DeveloperEdition.sco version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sco/142.0/Mozilla.Firefox.DeveloperEdition.sco.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/sco/142.0/Mozilla.Firefox.DeveloperEdition.sco.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279906 Update: Mozilla.Firefox.DeveloperEdition.son version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/son/142.0/Mozilla.Firefox.DeveloperEdition.son.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/son/142.0/Mozilla.Firefox.DeveloperEdition.son.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#279909 Update: Mozilla.Firefox.DeveloperEdition.sv-SE version 142.0 (142.0b6)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sv-SE/142.0/Mozilla.Firefox.DeveloperEdition.sv-SE.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/sv-SE/142.0/Mozilla.Firefox.DeveloperEdition.sv-SE.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved
