Repository microsoft/winget-pkgs, pull requests merged in 2025-05, with the labels that each got.

#250960 New package: Dialpad.DialpadMeetings version 2503.2.0
  manifests/d/Dialpad/DialpadMeetings/2503.2.0/Dialpad.DialpadMeetings.installer.yaml
  manifests/d/Dialpad/DialpadMeetings/2503.2.0/Dialpad.DialpadMeetings.locale.en-US.yaml
  manifests/d/Dialpad/DialpadMeetings/2503.2.0/Dialpad.DialpadMeetings.locale.zh-CN.yaml
  manifests/d/Dialpad/DialpadMeetings/2503.2.0/Dialpad.DialpadMeetings.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#251352 New package: FreedomScientific.JAWS.2025 version 2025.2504.89.400
  manifests/f/FreedomScientific/JAWS/2025/2025.2504.89.400/FreedomScientific.JAWS.2025.installer.yaml
  manifests/f/FreedomScientific/JAWS/2025/2025.2504.89.400/FreedomScientific.JAWS.2025.locale.en-US.yaml
  manifests/f/FreedomScientific/JAWS/2025/2025.2504.89.400/FreedomScientific.JAWS.2025.locale.zh-CN.yaml
  manifests/f/FreedomScientific/JAWS/2025/2025.2504.89.400/FreedomScientific.JAWS.2025.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#251623 Update: GauzyTech.NeatConverter version 4.0.1
  manifests/g/GauzyTech/NeatConverter/4.0.1/GauzyTech.NeatConverter.installer.yaml
  manifests/g/GauzyTech/NeatConverter/4.0.1/GauzyTech.NeatConverter.locale.en-US.yaml
  manifests/g/GauzyTech/NeatConverter/4.0.1/GauzyTech.NeatConverter.locale.zh-CN.yaml
  manifests/g/GauzyTech/NeatConverter/4.0.1/GauzyTech.NeatConverter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#251633 ReleaseNotes: kangfenmao.CherryStudio version 1.2.9
  manifests/k/kangfenmao/CherryStudio/1.2.9/kangfenmao.CherryStudio.locale.en-US.yaml
  manifests/k/kangfenmao/CherryStudio/1.2.9/kangfenmao.CherryStudio.locale.zh-CN.yaml
Labels: Validation-Completed, Moderator-Approved

#252610 Modify: Z-DBackup.Z-Cron version 6.4 (Auto)
  manifests/z/Z-DBackup/Z-Cron/6.4/Z-DBackup.Z-Cron.installer.yaml
  manifests/z/Z-DBackup/Z-Cron/6.4/Z-DBackup.Z-Cron.locale.en-US.yaml
  manifests/z/Z-DBackup/Z-Cron/6.4/Z-DBackup.Z-Cron.locale.zh-CN.yaml
  manifests/z/Z-DBackup/Z-Cron/6.4/Z-DBackup.Z-Cron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252629 New version: Ripose.Memento version 1.6.0
  manifests/r/Ripose/Memento/1.6.0/Ripose.Memento.installer.yaml
  manifests/r/Ripose/Memento/1.6.0/Ripose.Memento.locale.en-US.yaml
  manifests/r/Ripose/Memento/1.6.0/Ripose.Memento.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252761 New version: OpenJS.Electron.34 version 34.5.4
  manifests/o/OpenJS/Electron/34/34.5.4/OpenJS.Electron.34.installer.yaml
  manifests/o/OpenJS/Electron/34/34.5.4/OpenJS.Electron.34.locale.en-US.yaml
  manifests/o/OpenJS/Electron/34/34.5.4/OpenJS.Electron.34.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252762 New version: OpenJS.Electron.36 version 36.0.1
  manifests/o/OpenJS/Electron/36/36.0.1/OpenJS.Electron.36.installer.yaml
  manifests/o/OpenJS/Electron/36/36.0.1/OpenJS.Electron.36.locale.en-US.yaml
  manifests/o/OpenJS/Electron/36/36.0.1/OpenJS.Electron.36.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252763 New version: AresEmulator.Ares version 144
  manifests/a/AresEmulator/Ares/144/AresEmulator.Ares.installer.yaml
  manifests/a/AresEmulator/Ares/144/AresEmulator.Ares.locale.en-US.yaml
  manifests/a/AresEmulator/Ares/144/AresEmulator.Ares.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#250513 New version: Akko.CloudDriver version 370.1.48
  manifests/a/Akko/CloudDriver/370.1.48/Akko.CloudDriver.installer.yaml
  manifests/a/Akko/CloudDriver/370.1.48/Akko.CloudDriver.locale.en-US.yaml
  manifests/a/Akko/CloudDriver/370.1.48/Akko.CloudDriver.locale.zh-CN.yaml
  manifests/a/Akko/CloudDriver/370.1.48/Akko.CloudDriver.yaml
Labels: Validation-Completed, Moderator-Approved

#251624 Update: GauzyTech.NeatReader version 9.0.10
  manifests/g/GauzyTech/NeatReader/9.0.10/GauzyTech.NeatReader.installer.yaml
  manifests/g/GauzyTech/NeatReader/9.0.10/GauzyTech.NeatReader.locale.en-US.yaml
  manifests/g/GauzyTech/NeatReader/9.0.10/GauzyTech.NeatReader.locale.zh-CN.yaml
  manifests/g/GauzyTech/NeatReader/9.0.10/GauzyTech.NeatReader.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252766 Update AresEmulator.Ares.locale.en-US.yaml version 142
  manifests/a/AresEmulator/Ares/142/AresEmulator.Ares.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#251728 New version: TobySuggate.GitFiend version 0.45.3
  manifests/t/TobySuggate/GitFiend/0.45.3/TobySuggate.GitFiend.installer.yaml
  manifests/t/TobySuggate/GitFiend/0.45.3/TobySuggate.GitFiend.locale.en-US.yaml
  manifests/t/TobySuggate/GitFiend/0.45.3/TobySuggate.GitFiend.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#251674 New version: JetBrains.Rider version 2025.1.1
  manifests/j/JetBrains/Rider/2025.1.1/JetBrains.Rider.installer.yaml
  manifests/j/JetBrains/Rider/2025.1.1/JetBrains.Rider.locale.en-US.yaml
  manifests/j/JetBrains/Rider/2025.1.1/JetBrains.Rider.locale.zh-CN.yaml
  manifests/j/JetBrains/Rider/2025.1.1/JetBrains.Rider.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#252557 New version: Mozilla.Firefox.oc version 138.0
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.installer.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/oc/138.0/Mozilla.Firefox.oc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#252565 New version: Mozilla.Firefox.sc version 138.0
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.installer.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/sc/138.0/Mozilla.Firefox.sc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#252502 New version: Mozilla.Firefox.cak version 138.0
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.installer.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/cak/138.0/Mozilla.Firefox.cak.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#251780 Modify: MicroDicom.DICOMViewer version 2025.2
  manifests/m/MicroDicom/DICOMViewer/2025.2/MicroDicom.DICOMViewer.installer.yaml
  manifests/m/MicroDicom/DICOMViewer/2025.2/MicroDicom.DICOMViewer.locale.en-US.yaml
  manifests/m/MicroDicom/DICOMViewer/2025.2/MicroDicom.DICOMViewer.locale.zh-CN.yaml
  manifests/m/MicroDicom/DICOMViewer/2025.2/MicroDicom.DICOMViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252682 New version: LLVM.LLVM version 20.1.4
  manifests/l/LLVM/LLVM/20.1.4/LLVM.LLVM.installer.yaml
  manifests/l/LLVM/LLVM/20.1.4/LLVM.LLVM.locale.de-DE.yaml
  manifests/l/LLVM/LLVM/20.1.4/LLVM.LLVM.locale.en-US.yaml
  manifests/l/LLVM/LLVM/20.1.4/LLVM.LLVM.locale.zh-CN.yaml
  manifests/l/LLVM/LLVM/20.1.4/LLVM.LLVM.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#252768 New version: Sidero.talosctl version 1.10.0
  manifests/s/Sidero/talosctl/1.10.0/Sidero.talosctl.installer.yaml
  manifests/s/Sidero/talosctl/1.10.0/Sidero.talosctl.locale.en-US.yaml
  manifests/s/Sidero/talosctl/1.10.0/Sidero.talosctl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#251759 New version: mmozeiko.wcap version 2025.02.10
  manifests/m/mmozeiko/wcap/2025.02.10/mmozeiko.wcap.installer.yaml
  manifests/m/mmozeiko/wcap/2025.02.10/mmozeiko.wcap.locale.en-US.yaml
  manifests/m/mmozeiko/wcap/2025.02.10/mmozeiko.wcap.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252280 New package: OCSInventoryNG.WindowsAgent version 2.11.0.0
  manifests/o/OCSInventoryNG/WindowsAgent/2.11.0.0/OCSInventoryNG.WindowsAgent.installer.yaml
  manifests/o/OCSInventoryNG/WindowsAgent/2.11.0.0/OCSInventoryNG.WindowsAgent.locale.en-US.yaml
  manifests/o/OCSInventoryNG/WindowsAgent/2.11.0.0/OCSInventoryNG.WindowsAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package

#252769 New version: AuraMarker.Lattics version 2.5.3
  manifests/a/AuraMarker/Lattics/2.5.3/AuraMarker.Lattics.installer.yaml
  manifests/a/AuraMarker/Lattics/2.5.3/AuraMarker.Lattics.locale.en-US.yaml
  manifests/a/AuraMarker/Lattics/2.5.3/AuraMarker.Lattics.locale.zh-CN.yaml
  manifests/a/AuraMarker/Lattics/2.5.3/AuraMarker.Lattics.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252770 New version: EuSoft.Dehelper version 14.0.5.0
  manifests/e/EuSoft/Dehelper/14.0.5.0/EuSoft.Dehelper.installer.yaml
  manifests/e/EuSoft/Dehelper/14.0.5.0/EuSoft.Dehelper.locale.en-US.yaml
  manifests/e/EuSoft/Dehelper/14.0.5.0/EuSoft.Dehelper.locale.zh-CN.yaml
  manifests/e/EuSoft/Dehelper/14.0.5.0/EuSoft.Dehelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252772 New version: EuSoft.Eudic version 14.0.5.0
  manifests/e/EuSoft/Eudic/14.0.5.0/EuSoft.Eudic.installer.yaml
  manifests/e/EuSoft/Eudic/14.0.5.0/EuSoft.Eudic.locale.en-US.yaml
  manifests/e/EuSoft/Eudic/14.0.5.0/EuSoft.Eudic.locale.zh-CN.yaml
  manifests/e/EuSoft/Eudic/14.0.5.0/EuSoft.Eudic.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252771 New version: EuSoft.Eshelper version 14.0.5.0
  manifests/e/EuSoft/Eshelper/14.0.5.0/EuSoft.Eshelper.installer.yaml
  manifests/e/EuSoft/Eshelper/14.0.5.0/EuSoft.Eshelper.locale.en-US.yaml
  manifests/e/EuSoft/Eshelper/14.0.5.0/EuSoft.Eshelper.locale.zh-CN.yaml
  manifests/e/EuSoft/Eshelper/14.0.5.0/EuSoft.Eshelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252668 New package: Coder.CoderDesktop version 0.2.0
  manifests/c/Coder/CoderDesktop/0.2.0/Coder.CoderDesktop.installer.yaml
  manifests/c/Coder/CoderDesktop/0.2.0/Coder.CoderDesktop.locale.en-US.yaml
  manifests/c/Coder/CoderDesktop/0.2.0/Coder.CoderDesktop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#251789 New package: MicroDicom.ShellExtension version 4.0.0
  manifests/m/MicroDicom/ShellExtension/4.0.0/MicroDicom.ShellExtension.installer.yaml
  manifests/m/MicroDicom/ShellExtension/4.0.0/MicroDicom.ShellExtension.locale.en-US.yaml
  manifests/m/MicroDicom/ShellExtension/4.0.0/MicroDicom.ShellExtension.locale.zh-CN.yaml
  manifests/m/MicroDicom/ShellExtension/4.0.0/MicroDicom.ShellExtension.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#251672 New version: JetBrains.dotUltimate version 2025.1.1
  manifests/j/JetBrains/dotUltimate/2025.1.1/JetBrains.dotUltimate.installer.yaml
  manifests/j/JetBrains/dotUltimate/2025.1.1/JetBrains.dotUltimate.locale.en-US.yaml
  manifests/j/JetBrains/dotUltimate/2025.1.1/JetBrains.dotUltimate.locale.zh-CN.yaml
  manifests/j/JetBrains/dotUltimate/2025.1.1/JetBrains.dotUltimate.yaml
Labels: Validation-Completed, Moderator-Approved

#252453 New version: OmegaT.OmegaT version 6.0.1
  manifests/o/OmegaT/OmegaT/6.0.1/OmegaT.OmegaT.installer.yaml
  manifests/o/OmegaT/OmegaT/6.0.1/OmegaT.OmegaT.locale.en-US.yaml
  manifests/o/OmegaT/OmegaT/6.0.1/OmegaT.OmegaT.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252773 New version: EuSoft.Frhelper version 14.0.5.0
  manifests/e/EuSoft/Frhelper/14.0.5.0/EuSoft.Frhelper.installer.yaml
  manifests/e/EuSoft/Frhelper/14.0.5.0/EuSoft.Frhelper.locale.en-US.yaml
  manifests/e/EuSoft/Frhelper/14.0.5.0/EuSoft.Frhelper.locale.zh-CN.yaml
  manifests/e/EuSoft/Frhelper/14.0.5.0/EuSoft.Frhelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252447 [Update Request]: KeePassXCTeam.KeePassXC Install location is incorrect
  manifests/k/KeePassXCTeam/KeePassXC/2.7.10/KeePassXCTeam.KeePassXC.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252572 New version: Mozilla.Firefox.sr version 138.0
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.installer.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/sr/138.0/Mozilla.Firefox.sr.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#252697 Remove version: Nvidia.GeForceNow version 2.0.68.147
  manifests/n/Nvidia/GeForceNow/2.0.68.147/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.147/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.147/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.147/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252698 Remove version: Nvidia.GeForceNow version 2.0.68.154
  manifests/n/Nvidia/GeForceNow/2.0.68.154/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.154/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.154/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.68.154/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252699 Remove version: Nvidia.GeForceNow version 2.0.69.149
  manifests/n/Nvidia/GeForceNow/2.0.69.149/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.69.149/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.69.149/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.69.149/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252700 Remove version: Nvidia.GeForceNow version 2.0.71.162
  manifests/n/Nvidia/GeForceNow/2.0.71.162/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.71.162/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.71.162/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.71.162/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252701 Remove version: Nvidia.GeForceNow version 2.0.72.124
  manifests/n/Nvidia/GeForceNow/2.0.72.124/Nvidia.GeForceNow.installer.yaml
  manifests/n/Nvidia/GeForceNow/2.0.72.124/Nvidia.GeForceNow.locale.en-US.yaml
  manifests/n/Nvidia/GeForceNow/2.0.72.124/Nvidia.GeForceNow.locale.zh-CN.yaml
  manifests/n/Nvidia/GeForceNow/2.0.72.124/Nvidia.GeForceNow.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252748 New version: Speakeasy.speakeasy 1.541.2
  manifests/s/Speakeasy/speakeasy/1.541.2/Speakeasy.speakeasy.installer.yaml
  manifests/s/Speakeasy/speakeasy/1.541.2/Speakeasy.speakeasy.locale.en-US.yaml
  manifests/s/Speakeasy/speakeasy/1.541.2/Speakeasy.speakeasy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252733 New version: astral-sh.uv version 0.7.2
  manifests/a/astral-sh/uv/0.7.2/astral-sh.uv.installer.yaml
  manifests/a/astral-sh/uv/0.7.2/astral-sh.uv.locale.en-US.yaml
  manifests/a/astral-sh/uv/0.7.2/astral-sh.uv.locale.zh-CN.yaml
  manifests/a/astral-sh/uv/0.7.2/astral-sh.uv.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252776 TopalaSoftwareSolutions.SIW version 2025.04.30.1
  manifests/t/TopalaSoftwareSolutions/SIW/2025.04.30.1/TopalaSoftwareSolutions.SIW.installer.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2025.04.30.1/TopalaSoftwareSolutions.SIW.locale.en-US.yaml
  manifests/t/TopalaSoftwareSolutions/SIW/2025.04.30.1/TopalaSoftwareSolutions.SIW.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252784 Update: Mozilla.Firefox.DeveloperEdition.ar version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ar/139.0/Mozilla.Firefox.DeveloperEdition.ar.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252777 New version: Microsoft.Bicep version 0.35.1
  manifests/m/Microsoft/Bicep/0.35.1/Microsoft.Bicep.installer.yaml
  manifests/m/Microsoft/Bicep/0.35.1/Microsoft.Bicep.locale.en-US.yaml
  manifests/m/Microsoft/Bicep/0.35.1/Microsoft.Bicep.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252812 New version: Postman.Postman version 11.43.4
  manifests/p/Postman/Postman/11.43.4/Postman.Postman.installer.yaml
  manifests/p/Postman/Postman/11.43.4/Postman.Postman.locale.en-US.yaml
  manifests/p/Postman/Postman/11.43.4/Postman.Postman.locale.zh-CN.yaml
  manifests/p/Postman/Postman/11.43.4/Postman.Postman.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252869 Update: Mozilla.Firefox.DeveloperEdition.te version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/te/139.0/Mozilla.Firefox.DeveloperEdition.te.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252778 New version: ExpressVPN.ExpressVPN version 12.101.0.45
  manifests/e/ExpressVPN/ExpressVPN/12.101.0.45/ExpressVPN.ExpressVPN.installer.yaml
  manifests/e/ExpressVPN/ExpressVPN/12.101.0.45/ExpressVPN.ExpressVPN.locale.en-US.yaml
  manifests/e/ExpressVPN/ExpressVPN/12.101.0.45/ExpressVPN.ExpressVPN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252785 Update: Mozilla.Firefox.DeveloperEdition.ast version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ast/139.0/Mozilla.Firefox.DeveloperEdition.ast.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252780 Update: Mozilla.Firefox.DeveloperEdition version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/139.0/Mozilla.Firefox.DeveloperEdition.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252783 Update: Mozilla.Firefox.DeveloperEdition.an version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/an/139.0/Mozilla.Firefox.DeveloperEdition.an.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252782 Update: Mozilla.Firefox.DeveloperEdition.af version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/af/139.0/Mozilla.Firefox.DeveloperEdition.af.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252781 Update: Mozilla.Firefox.DeveloperEdition.ach version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ach/139.0/Mozilla.Firefox.DeveloperEdition.ach.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252278 New package: Mozilla.Firefox.oc version 137.0.2
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.installer.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/oc/137.0.2/Mozilla.Firefox.oc.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package, New-Manifest

#251632 ReleaseNotes: kangfenmao.CherryStudio version 1.2.7
  manifests/k/kangfenmao/CherryStudio/1.2.7/kangfenmao.CherryStudio.locale.en-US.yaml
  manifests/k/kangfenmao/CherryStudio/1.2.7/kangfenmao.CherryStudio.locale.zh-CN.yaml
Labels: Validation-Completed, Moderator-Approved

#252787 Update: Mozilla.Firefox.DeveloperEdition.be version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/be/139.0/Mozilla.Firefox.DeveloperEdition.be.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252788 Update: Mozilla.Firefox.DeveloperEdition.bg version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bg/139.0/Mozilla.Firefox.DeveloperEdition.bg.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#250938 New package: DigitalScience.Papers version 4.37.2395
  manifests/d/DigitalScience/Papers/4.37.2395/DigitalScience.Papers.installer.yaml
  manifests/d/DigitalScience/Papers/4.37.2395/DigitalScience.Papers.locale.en-US.yaml
  manifests/d/DigitalScience/Papers/4.37.2395/DigitalScience.Papers.locale.zh-CN.yaml
  manifests/d/DigitalScience/Papers/4.37.2395/DigitalScience.Papers.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#252791 Update: Mozilla.Firefox.DeveloperEdition.bs version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bs/139.0/Mozilla.Firefox.DeveloperEdition.bs.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252792 Update: Mozilla.Firefox.DeveloperEdition.ca-valencia version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ca-valencia/139.0/Mozilla.Firefox.DeveloperEdition.ca-valencia.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252789 Update: Mozilla.Firefox.DeveloperEdition.bn version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/bn/139.0/Mozilla.Firefox.DeveloperEdition.bn.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252802 Update: Mozilla.Firefox.DeveloperEdition.en-GB version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/en-GB/139.0/Mozilla.Firefox.DeveloperEdition.en-GB.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252805 Update: Mozilla.Firefox.DeveloperEdition.es-CL version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-CL/139.0/Mozilla.Firefox.DeveloperEdition.es-CL.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252790 Update: Mozilla.Firefox.DeveloperEdition.br version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/br/139.0/Mozilla.Firefox.DeveloperEdition.br.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252793 Update: Mozilla.Firefox.DeveloperEdition.ca version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ca/139.0/Mozilla.Firefox.DeveloperEdition.ca.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252806 Update: Mozilla.Firefox.DeveloperEdition.es-ES version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-ES/139.0/Mozilla.Firefox.DeveloperEdition.es-ES.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252808 Update: Mozilla.Firefox.DeveloperEdition.et version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/et/139.0/Mozilla.Firefox.DeveloperEdition.et.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252815 Update: Mozilla.Firefox.DeveloperEdition.fur version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fur/139.0/Mozilla.Firefox.DeveloperEdition.fur.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252798 Update: Mozilla.Firefox.DeveloperEdition.de version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/de/139.0/Mozilla.Firefox.DeveloperEdition.de.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252814 Update: Mozilla.Firefox.DeveloperEdition.fr version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fr/139.0/Mozilla.Firefox.DeveloperEdition.fr.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252823 Update: Mozilla.Firefox.DeveloperEdition.hi-IN version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hi-IN/139.0/Mozilla.Firefox.DeveloperEdition.hi-IN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252809 Update: Mozilla.Firefox.DeveloperEdition.eu version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/eu/139.0/Mozilla.Firefox.DeveloperEdition.eu.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252803 Update: Mozilla.Firefox.DeveloperEdition.eo version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/eo/139.0/Mozilla.Firefox.DeveloperEdition.eo.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252822 New version: Mozilla.Firefox.DeveloperEdition.he version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/he/139.0/Mozilla.Firefox.DeveloperEdition.he.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/he/139.0/Mozilla.Firefox.DeveloperEdition.he.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/he/139.0/Mozilla.Firefox.DeveloperEdition.he.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/he/139.0/Mozilla.Firefox.DeveloperEdition.he.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252842 Update: Mozilla.Firefox.DeveloperEdition.mk version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/mk/139.0/Mozilla.Firefox.DeveloperEdition.mk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252827 Update: Mozilla.Firefox.DeveloperEdition.hy-AM version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/hy-AM/139.0/Mozilla.Firefox.DeveloperEdition.hy-AM.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252843 Update: Mozilla.Firefox.DeveloperEdition.mr version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/mr/139.0/Mozilla.Firefox.DeveloperEdition.mr.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252832 New version: Mozilla.Firefox.DeveloperEdition.ja version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ja/139.0/Mozilla.Firefox.DeveloperEdition.ja.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ja/139.0/Mozilla.Firefox.DeveloperEdition.ja.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ja/139.0/Mozilla.Firefox.DeveloperEdition.ja.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ja/139.0/Mozilla.Firefox.DeveloperEdition.ja.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252804 Update: Mozilla.Firefox.DeveloperEdition.es-AR version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-AR/139.0/Mozilla.Firefox.DeveloperEdition.es-AR.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252834 New version: Mozilla.Firefox.DeveloperEdition.kab version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/139.0/Mozilla.Firefox.DeveloperEdition.kab.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/139.0/Mozilla.Firefox.DeveloperEdition.kab.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/139.0/Mozilla.Firefox.DeveloperEdition.kab.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/kab/139.0/Mozilla.Firefox.DeveloperEdition.kab.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252848 Update: Mozilla.Firefox.DeveloperEdition.nl version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nl/139.0/Mozilla.Firefox.DeveloperEdition.nl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252854 Update: Mozilla.Firefox.DeveloperEdition.pt-PT version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-PT/139.0/Mozilla.Firefox.DeveloperEdition.pt-PT.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252845 Update: Mozilla.Firefox.DeveloperEdition.my version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/my/139.0/Mozilla.Firefox.DeveloperEdition.my.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252835 Update: Mozilla.Firefox.DeveloperEdition.kk version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kk/139.0/Mozilla.Firefox.DeveloperEdition.kk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252850 Update: Mozilla.Firefox.DeveloperEdition.oc version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/oc/139.0/Mozilla.Firefox.DeveloperEdition.oc.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252857 Update: Mozilla.Firefox.DeveloperEdition.ru version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ru/139.0/Mozilla.Firefox.DeveloperEdition.ru.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252861 Update: Mozilla.Firefox.DeveloperEdition.sk version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sk/139.0/Mozilla.Firefox.DeveloperEdition.sk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252849 Update: Mozilla.Firefox.DeveloperEdition.nn-NO version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nn-NO/139.0/Mozilla.Firefox.DeveloperEdition.nn-NO.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252868 Update: Mozilla.Firefox.DeveloperEdition.ta version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ta/139.0/Mozilla.Firefox.DeveloperEdition.ta.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252852 Update: Mozilla.Firefox.DeveloperEdition.pl version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pl/139.0/Mozilla.Firefox.DeveloperEdition.pl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252875 Update: Mozilla.Firefox.DeveloperEdition.uk version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/uk/139.0/Mozilla.Firefox.DeveloperEdition.uk.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#251997 New version: TechSmith.Camtasia version 25.1.0.9076 (25.1.0)
  manifests/t/TechSmith/Camtasia/25.1.0.9076/TechSmith.Camtasia.installer.yaml
  manifests/t/TechSmith/Camtasia/25.1.0.9076/TechSmith.Camtasia.locale.en-US.yaml
  manifests/t/TechSmith/Camtasia/25.1.0.9076/TechSmith.Camtasia.locale.zh-CN.yaml
  manifests/t/TechSmith/Camtasia/25.1.0.9076/TechSmith.Camtasia.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#252859 Update: Mozilla.Firefox.DeveloperEdition.sco version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sco/139.0/Mozilla.Firefox.DeveloperEdition.sco.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252866 Update: Mozilla.Firefox.DeveloperEdition.sv-SE version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sv-SE/139.0/Mozilla.Firefox.DeveloperEdition.sv-SE.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252867 Update: Mozilla.Firefox.DeveloperEdition.szl version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/szl/139.0/Mozilla.Firefox.DeveloperEdition.szl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252813 Update: Mozilla.Firefox.DeveloperEdition.fi version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/fi/139.0/Mozilla.Firefox.DeveloperEdition.fi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252846 Update: Mozilla.Firefox.DeveloperEdition.nb-NO version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/nb-NO/139.0/Mozilla.Firefox.DeveloperEdition.nb-NO.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252837 Update: Mozilla.Firefox.DeveloperEdition.kn version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/kn/139.0/Mozilla.Firefox.DeveloperEdition.kn.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252851 Update: Mozilla.Firefox.DeveloperEdition.pa-IN version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pa-IN/139.0/Mozilla.Firefox.DeveloperEdition.pa-IN.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252847 Update: Mozilla.Firefox.DeveloperEdition.ne-NP version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ne-NP/139.0/Mozilla.Firefox.DeveloperEdition.ne-NP.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252870 Update: Mozilla.Firefox.DeveloperEdition.tg version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/tg/139.0/Mozilla.Firefox.DeveloperEdition.tg.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252627 New version: Netbird.Netbird version 0.43.1
  manifests/n/Netbird/Netbird/0.43.1/Netbird.Netbird.installer.yaml
  manifests/n/Netbird/Netbird/0.43.1/Netbird.Netbird.locale.en-US.yaml
  manifests/n/Netbird/Netbird/0.43.1/Netbird.Netbird.locale.zh-CN.yaml
  manifests/n/Netbird/Netbird/0.43.1/Netbird.Netbird.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252881 Update: Mozilla.Firefox.DeveloperEdition.zh-TW version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/zh-TW/139.0/Mozilla.Firefox.DeveloperEdition.zh-TW.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252786 Update: Mozilla.Firefox.DeveloperEdition.az version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/az/139.0/Mozilla.Firefox.DeveloperEdition.az.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252281 New package: Mozilla.Firefox.pl version 137.0.2
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.installer.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/pl/137.0.2/Mozilla.Firefox.pl.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package, New-Manifest

#252795 Update: Mozilla.Firefox.DeveloperEdition.cs version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/cs/139.0/Mozilla.Firefox.DeveloperEdition.cs.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252807 Update: Mozilla.Firefox.DeveloperEdition.es-MX version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/es-MX/139.0/Mozilla.Firefox.DeveloperEdition.es-MX.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252385 Update: Codeium.Windsurf version 1.98.0 (1.7.3)
  manifests/c/Codeium/Windsurf/1.98.0/Codeium.Windsurf.installer.yaml
  manifests/c/Codeium/Windsurf/1.98.0/Codeium.Windsurf.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved

#252797 Update: Mozilla.Firefox.DeveloperEdition.da version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/da/139.0/Mozilla.Firefox.DeveloperEdition.da.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252796 Update: Mozilla.Firefox.DeveloperEdition.cy version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/cy/139.0/Mozilla.Firefox.DeveloperEdition.cy.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252055 Remove validation file for VMPK package
  manifests/v/VMPK/VMPK/.validation
Labels: Moderator-Approved, Author-Not-Authorized, Needs-Attention

#252466 New version: AVer.AVerTouch version 1.3.2109.0
  manifests/a/AVer/AVerTouch/1.3.2109.0/AVer.AVerTouch.installer.yaml
  manifests/a/AVer/AVerTouch/1.3.2109.0/AVer.AVerTouch.locale.en-US.yaml
  manifests/a/AVer/AVerTouch/1.3.2109.0/AVer.AVerTouch.locale.zh-CN.yaml
  manifests/a/AVer/AVerTouch/1.3.2109.0/AVer.AVerTouch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252684 Update: MediaHuman.YouTubeDownloader version 3.9.11
  manifests/m/MediaHuman/YouTubeDownloader/3.9.11/MediaHuman.YouTubeDownloader.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252801 Update: Mozilla.Firefox.DeveloperEdition.en-CA version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/en-CA/139.0/Mozilla.Firefox.DeveloperEdition.en-CA.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252828 Update: Mozilla.Firefox.DeveloperEdition.ia version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ia/139.0/Mozilla.Firefox.DeveloperEdition.ia.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252836 Update: Mozilla.Firefox.DeveloperEdition.km version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/km/139.0/Mozilla.Firefox.DeveloperEdition.km.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252800 Update: Mozilla.Firefox.DeveloperEdition.el version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/el/139.0/Mozilla.Firefox.DeveloperEdition.el.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252831 Update: Mozilla.Firefox.DeveloperEdition.it version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/it/139.0/Mozilla.Firefox.DeveloperEdition.it.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252856 New version: Mozilla.Firefox.DeveloperEdition.ro version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/139.0/Mozilla.Firefox.DeveloperEdition.ro.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/139.0/Mozilla.Firefox.DeveloperEdition.ro.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/139.0/Mozilla.Firefox.DeveloperEdition.ro.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ro/139.0/Mozilla.Firefox.DeveloperEdition.ro.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252838 New version: Mozilla.Firefox.DeveloperEdition.ko version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/139.0/Mozilla.Firefox.DeveloperEdition.ko.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/139.0/Mozilla.Firefox.DeveloperEdition.ko.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/139.0/Mozilla.Firefox.DeveloperEdition.ko.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/ko/139.0/Mozilla.Firefox.DeveloperEdition.ko.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252882 Add version: Google.FirebaseCLI version 14.2.2
  manifests/g/Google/FirebaseCLI/14.2.2/Google.FirebaseCLI.installer.yaml
  manifests/g/Google/FirebaseCLI/14.2.2/Google.FirebaseCLI.locale.en-US.yaml
  manifests/g/Google/FirebaseCLI/14.2.2/Google.FirebaseCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252839 Update: Mozilla.Firefox.DeveloperEdition.lij version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/lij/139.0/Mozilla.Firefox.DeveloperEdition.lij.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252889 ReleaseNotes: Iterate.Cyberduck version 9.1.4.43177
  manifests/i/Iterate/Cyberduck/9.1.4.43177/Iterate.Cyberduck.installer.yaml
  manifests/i/Iterate/Cyberduck/9.1.4.43177/Iterate.Cyberduck.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252830 Update: Mozilla.Firefox.DeveloperEdition.is version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/is/139.0/Mozilla.Firefox.DeveloperEdition.is.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252883 New version: openpubkey.opkssh version 0.6.0
  manifests/o/openpubkey/opkssh/0.6.0/openpubkey.opkssh.installer.yaml
  manifests/o/openpubkey/opkssh/0.6.0/openpubkey.opkssh.locale.en-US.yaml
  manifests/o/openpubkey/opkssh/0.6.0/openpubkey.opkssh.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252855 Update: Mozilla.Firefox.DeveloperEdition.rm version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/rm/139.0/Mozilla.Firefox.DeveloperEdition.rm.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252277 New package: Mozilla.Firefox.nn-NO version 137.0.2
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.installer.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/nn-NO/137.0.2/Mozilla.Firefox.nn-NO.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package, New-Manifest

#251775 Revert "New version: GeoDa.GeoDa version 1.22.0.14 (#251505)"
  manifests/g/GeoDa/GeoDa/1.22/GeoDa.GeoDa.installer.yaml
  manifests/g/GeoDa/GeoDa/1.22/GeoDa.GeoDa.locale.en-US.yaml
  manifests/g/GeoDa/GeoDa/1.22/GeoDa.GeoDa.locale.zh-CN.yaml
  manifests/g/GeoDa/GeoDa/1.22/GeoDa.GeoDa.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#252853 New version: Mozilla.Firefox.DeveloperEdition.pt-BR version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-BR/139.0/Mozilla.Firefox.DeveloperEdition.pt-BR.installer.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-BR/139.0/Mozilla.Firefox.DeveloperEdition.pt-BR.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-BR/139.0/Mozilla.Firefox.DeveloperEdition.pt-BR.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/DeveloperEdition/pt-BR/139.0/Mozilla.Firefox.DeveloperEdition.pt-BR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#252858 Update: Mozilla.Firefox.DeveloperEdition.sc version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sc/139.0/Mozilla.Firefox.DeveloperEdition.sc.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252862 Update: Mozilla.Firefox.DeveloperEdition.sl version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sl/139.0/Mozilla.Firefox.DeveloperEdition.sl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252864 Update: Mozilla.Firefox.DeveloperEdition.sq version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/sq/139.0/Mozilla.Firefox.DeveloperEdition.sq.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252873 Update: Mozilla.Firefox.DeveloperEdition.tr version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/tr/139.0/Mozilla.Firefox.DeveloperEdition.tr.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252874 Update: Mozilla.Firefox.DeveloperEdition.trs version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/trs/139.0/Mozilla.Firefox.DeveloperEdition.trs.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252877 Update: Mozilla.Firefox.DeveloperEdition.uz version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/uz/139.0/Mozilla.Firefox.DeveloperEdition.uz.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252872 Update: Mozilla.Firefox.DeveloperEdition.tl version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/tl/139.0/Mozilla.Firefox.DeveloperEdition.tl.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252878 Update: Mozilla.Firefox.DeveloperEdition.vi version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/vi/139.0/Mozilla.Firefox.DeveloperEdition.vi.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252876 Update: Mozilla.Firefox.DeveloperEdition.ur version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ur/139.0/Mozilla.Firefox.DeveloperEdition.ur.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252879 Update: Mozilla.Firefox.DeveloperEdition.xh version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/xh/139.0/Mozilla.Firefox.DeveloperEdition.xh.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252884 New version: kangyu-california.PersistentWindows version 5.63
  manifests/k/kangyu-california/PersistentWindows/5.63/kangyu-california.PersistentWindows.installer.yaml
  manifests/k/kangyu-california/PersistentWindows/5.63/kangyu-california.PersistentWindows.locale.en-US.yaml
  manifests/k/kangyu-california/PersistentWindows/5.63/kangyu-california.PersistentWindows.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252886 New version: abgox.InputTip version 2.37.4
  manifests/a/abgox/InputTip/2.37.4/abgox.InputTip.installer.yaml
  manifests/a/abgox/InputTip/2.37.4/abgox.InputTip.locale.en-US.yaml
  manifests/a/abgox/InputTip/2.37.4/abgox.InputTip.locale.zh-CN.yaml
  manifests/a/abgox/InputTip/2.37.4/abgox.InputTip.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252887 ttu-base-suite-2000 20.00.22.00
  manifests/t/Teradata/TTUBase/20.00.22.00/Teradata.TTUBase.installer.yaml
  manifests/t/Teradata/TTUBase/20.00.22.00/Teradata.TTUBase.locale.en-US.yaml
  manifests/t/Teradata/TTUBase/20.00.22.00/Teradata.TTUBase.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252890 New version: nektos.act version 0.2.77
  manifests/n/nektos/act/0.2.77/nektos.act.installer.yaml
  manifests/n/nektos/act/0.2.77/nektos.act.locale.en-US.yaml
  manifests/n/nektos/act/0.2.77/nektos.act.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#252897 Modify: Delinea.ThycoticLocalSecurityAgent version 12.0.3185
  manifests/d/Delinea/ThycoticLocalSecurityAgent/12.0.3185/Delinea.ThycoticLocalSecurityAgent.installer.yaml
  manifests/d/Delinea/ThycoticLocalSecurityAgent/12.0.3185/Delinea.ThycoticLocalSecurityAgent.locale.en-US.yaml
  manifests/d/Delinea/ThycoticLocalSecurityAgent/12.0.3185/Delinea.ThycoticLocalSecurityAgent.locale.zh-CN.yaml
  manifests/d/Delinea/ThycoticLocalSecurityAgent/12.0.3185/Delinea.ThycoticLocalSecurityAgent.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252896 Modify: Meld.Meld version 3.22.2
  manifests/m/Meld/Meld/3.22.2/Meld.Meld.installer.yaml
  manifests/m/Meld/Meld/3.22.2/Meld.Meld.locale.en-US.yaml
  manifests/m/Meld/Meld/3.22.2/Meld.Meld.locale.zh-CN.yaml
  manifests/m/Meld/Meld/3.22.2/Meld.Meld.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252926 Remove version: BigSweetPotatoStudio.HyperChat version 1.6.0 (Auto)
  manifests/b/BigSweetPotatoStudio/HyperChat/1.6.0/BigSweetPotatoStudio.HyperChat.installer.yaml
  manifests/b/BigSweetPotatoStudio/HyperChat/1.6.0/BigSweetPotatoStudio.HyperChat.locale.en-US.yaml
  manifests/b/BigSweetPotatoStudio/HyperChat/1.6.0/BigSweetPotatoStudio.HyperChat.locale.zh-CN.yaml
  manifests/b/BigSweetPotatoStudio/HyperChat/1.6.0/BigSweetPotatoStudio.HyperChat.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252844 Update: Mozilla.Firefox.DeveloperEdition.ms version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/ms/139.0/Mozilla.Firefox.DeveloperEdition.ms.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252282 New package: Mozilla.Firefox.pt-BR version 137.0.2
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.installer.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/pt-BR/137.0.2/Mozilla.Firefox.pt-BR.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package, New-Manifest

#252279 New package: Mozilla.Firefox.pa-IN version 137.0.2
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.installer.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.cs-CZ.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.da-DK.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.de-DE.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.el-GR.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.en-GB.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.en-US.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.es-MX.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.fr-FR.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.hu-HU.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.ja-JP.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.nb-NO.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.ru-RU.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.ta-IN.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.locale.zh-CN.yaml
  manifests/m/Mozilla/Firefox/pa-IN/137.0.2/Mozilla.Firefox.pa-IN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Package, New-Manifest

#252841 Update: Mozilla.Firefox.DeveloperEdition.lv version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/lv/139.0/Mozilla.Firefox.DeveloperEdition.lv.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#252871 Update: Mozilla.Firefox.DeveloperEdition.th version 139.0 (139.0b2)
  manifests/m/Mozilla/Firefox/DeveloperEdition/th/139.0/Mozilla.Firefox.DeveloperEdition.th.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#252923 New version: YSTYLE.kaf-cli version 1.3.11
  manifests/y/YSTYLE/kaf-cli/1.3.11/YSTYLE.kaf-cli.installer.yaml
  manifests/y/YSTYLE/kaf-cli/1.3.11/YSTYLE.kaf-cli.locale.en-US.yaml
  manifests/y/YSTYLE/kaf-cli/1.3.11/YSTYLE.kaf-cli.locale.zh-CN.yaml
  manifests/y/YSTYLE/kaf-cli/1.3.11/YSTYLE.kaf-cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest
