Repository microsoft/winget-pkgs, pull requests merged in 2025-02, with the labels that each got.

#220132 Standardize formatting of manifests/o/OSGeo/QGIS/3.36.2
  manifests/o/OSGeo/QGIS/3.36.2/OSGeo.QGIS.installer.yaml
  manifests/o/OSGeo/QGIS/3.36.2/OSGeo.QGIS.locale.en-US.yaml
  manifests/o/OSGeo/QGIS/3.36.2/OSGeo.QGIS.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#216108 Remove version: TechPowerUp.ThrottleStop version 9.6
  manifests/t/TechPowerUp/ThrottleStop/9.6/TechPowerUp.ThrottleStop.installer.yaml
  manifests/t/TechPowerUp/ThrottleStop/9.6/TechPowerUp.ThrottleStop.locale.en-US.yaml
  manifests/t/TechPowerUp/ThrottleStop/9.6/TechPowerUp.ThrottleStop.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Highest-Version-Removal

#216107 Remove version: TechPowerUp.NVCleanstall version 1.17.0
  manifests/t/TechPowerUp/NVCleanstall/1.17.0/TechPowerUp.NVCleanstall.installer.yaml
  manifests/t/TechPowerUp/NVCleanstall/1.17.0/TechPowerUp.NVCleanstall.locale.en-US.yaml
  manifests/t/TechPowerUp/NVCleanstall/1.17.0/TechPowerUp.NVCleanstall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Highest-Version-Removal

#218622 New package: Webrandt.Ax version 1.0.0
  manifests/w/Webrandt/Ax/1.0.0/Webrandt.Ax.installer.yaml
  manifests/w/Webrandt/Ax/1.0.0/Webrandt.Ax.locale.en-US.yaml
  manifests/w/Webrandt/Ax/1.0.0/Webrandt.Ax.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#220915 Standardize formatting of manifests/b/BinanceTech/Binance/1.50.4
  manifests/b/BinanceTech/Binance/1.50.4/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.50.4/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.50.4/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220913 Standardize formatting of manifests/b/BinanceTech/Binance/1.50.2
  manifests/b/BinanceTech/Binance/1.50.2/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.50.2/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.50.2/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220920 Standardize formatting of manifests/b/BinanceTech/Binance/1.52.4
  manifests/b/BinanceTech/Binance/1.52.4/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.52.4/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.52.4/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220925 Standardize formatting of manifests/b/BinanceTech/Binance/1.53.7
  manifests/b/BinanceTech/Binance/1.53.7/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.53.7/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.53.7/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220926 Standardize formatting of manifests/b/BinanceTech/Binance/1.53.8
  manifests/b/BinanceTech/Binance/1.53.8/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.53.8/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.53.8/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220927 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.0
  manifests/b/BinanceTech/Binance/1.54.0/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.0/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.0/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220928 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.1
  manifests/b/BinanceTech/Binance/1.54.1/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.1/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.1/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220931 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.2
  manifests/b/BinanceTech/Binance/1.54.2/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.2/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.2/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220934 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.3
  manifests/b/BinanceTech/Binance/1.54.3/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.3/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.3/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220937 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.4
  manifests/b/BinanceTech/Binance/1.54.4/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.4/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.4/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220943 Standardize formatting of manifests/b/BinanceTech/Binance/1.54.5
  manifests/b/BinanceTech/Binance/1.54.5/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.54.5/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.54.5/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220916 New version: Google.Chrome.Canary version 134.0.6990.2
  manifests/g/Google/Chrome/Canary/134.0.6990.2/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/134.0.6990.2/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/134.0.6990.2/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/134.0.6990.2/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/134.0.6990.2/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220135 Standardize formatting of manifests/o/OSGeo/QGIS/3.38.1
  manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.installer.yaml
  manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.locale.en-US.yaml
  manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.locale.zh-CN.yaml
  manifests/o/OSGeo/QGIS/3.38.1/OSGeo.QGIS.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#220128 Standardize formatting of manifests/o/OSGeo/QGIS/3.34.1
  manifests/o/OSGeo/QGIS/3.34.1/OSGeo.QGIS.installer.yaml
  manifests/o/OSGeo/QGIS/3.34.1/OSGeo.QGIS.locale.en-US.yaml
  manifests/o/OSGeo/QGIS/3.34.1/OSGeo.QGIS.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#218595 New version: lin-ycv.EverythingPowerToys version 0.88.0
  manifests/l/lin-ycv/EverythingPowerToys/0.88.0/lin-ycv.EverythingPowerToys.installer.yaml
  manifests/l/lin-ycv/EverythingPowerToys/0.88.0/lin-ycv.EverythingPowerToys.locale.en-US.yaml
  manifests/l/lin-ycv/EverythingPowerToys/0.88.0/lin-ycv.EverythingPowerToys.locale.es-ES.yaml
  manifests/l/lin-ycv/EverythingPowerToys/0.88.0/lin-ycv.EverythingPowerToys.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved

#220962 Remove: Google.PlayGames.Beta version 24.11.76.6
  manifests/g/Google/PlayGames/Beta/24.11.76.6/Google.PlayGames.Beta.installer.yaml
  manifests/g/Google/PlayGames/Beta/24.11.76.6/Google.PlayGames.Beta.locale.de-DE.yaml
  manifests/g/Google/PlayGames/Beta/24.11.76.6/Google.PlayGames.Beta.locale.en-US.yaml
  manifests/g/Google/PlayGames/Beta/24.11.76.6/Google.PlayGames.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220860 New version: kwaroran.RisuAI version 148.1.0
  manifests/k/kwaroran/RisuAI/148.1.0/kwaroran.RisuAI.installer.yaml
  manifests/k/kwaroran/RisuAI/148.1.0/kwaroran.RisuAI.locale.en-US.yaml
  manifests/k/kwaroran/RisuAI/148.1.0/kwaroran.RisuAI.locale.zh-CN.yaml
  manifests/k/kwaroran/RisuAI/148.1.0/kwaroran.RisuAI.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved, Validation-Retry

#220053 CologneCodeCompany.XYplorer version 26.80.0300
  manifests/c/CologneCodeCompany/XYplorer/26.80.0300/CologneCodeCompany.XYplorer.installer.yaml
  manifests/c/CologneCodeCompany/XYplorer/26.80.0300/CologneCodeCompany.XYplorer.locale.en-US.yaml
  manifests/c/CologneCodeCompany/XYplorer/26.80.0300/CologneCodeCompany.XYplorer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220055 CologneCodeCompany.XYplorerPortable version 26.80.0300
  manifests/c/CologneCodeCompany/XYplorerPortable/26.80.0300/CologneCodeCompany.XYplorerPortable.installer.yaml
  manifests/c/CologneCodeCompany/XYplorerPortable/26.80.0300/CologneCodeCompany.XYplorerPortable.locale.en-US.yaml
  manifests/c/CologneCodeCompany/XYplorerPortable/26.80.0300/CologneCodeCompany.XYplorerPortable.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220145 New version: KDE.Filelight version 24.12.2 (24.12-1622)
  manifests/k/KDE/Filelight/24.12.2/KDE.Filelight.installer.yaml
  manifests/k/KDE/Filelight/24.12.2/KDE.Filelight.locale.en-US.yaml
  manifests/k/KDE/Filelight/24.12.2/KDE.Filelight.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#220363 New version: Speakeasy.speakeasy 1.480.1
  manifests/s/Speakeasy/speakeasy/1.480.1/Speakeasy.speakeasy.installer.yaml
  manifests/s/Speakeasy/speakeasy/1.480.1/Speakeasy.speakeasy.locale.en-US.yaml
  manifests/s/Speakeasy/speakeasy/1.480.1/Speakeasy.speakeasy.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220833 New version: NLnetLabs.Unbound version 1.22.0
  manifests/n/NLnetLabs/Unbound/1.22.0/NLnetLabs.Unbound.installer.yaml
  manifests/n/NLnetLabs/Unbound/1.22.0/NLnetLabs.Unbound.locale.en-US.yaml
  manifests/n/NLnetLabs/Unbound/1.22.0/NLnetLabs.Unbound.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220891 UltraSearch V4.6.1
  manifests/j/JAMSoftware/UltraSearch/4.6.1/JAMSoftware.UltraSearch.installer.yaml
  manifests/j/JAMSoftware/UltraSearch/4.6.1/JAMSoftware.UltraSearch.locale.en-US.yaml
  manifests/j/JAMSoftware/UltraSearch/4.6.1/JAMSoftware.UltraSearch.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220522 New package: Microsoft.Sysinternals.Whois version 1.21
  manifests/m/Microsoft/Sysinternals/Whois/1.21/Microsoft.Sysinternals.Whois.installer.yaml
  manifests/m/Microsoft/Sysinternals/Whois/1.21/Microsoft.Sysinternals.Whois.locale.en-US.yaml
  manifests/m/Microsoft/Sysinternals/Whois/1.21/Microsoft.Sysinternals.Whois.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#220919 New version: HearthSim.HearthstoneDeckTracker version 1.38.6
  manifests/h/HearthSim/HearthstoneDeckTracker/1.38.6/HearthSim.HearthstoneDeckTracker.installer.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.38.6/HearthSim.HearthstoneDeckTracker.locale.en-US.yaml
  manifests/h/HearthSim/HearthstoneDeckTracker/1.38.6/HearthSim.HearthstoneDeckTracker.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220936 New version: NativeSoft.NativeRest version 2.4.1
  manifests/n/NativeSoft/NativeRest/2.4.1/NativeSoft.NativeRest.installer.yaml
  manifests/n/NativeSoft/NativeRest/2.4.1/NativeSoft.NativeRest.locale.en-US.yaml
  manifests/n/NativeSoft/NativeRest/2.4.1/NativeSoft.NativeRest.locale.zh-CN.yaml
  manifests/n/NativeSoft/NativeRest/2.4.1/NativeSoft.NativeRest.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220946 New Version: WildfireGames.0AD to version 0.27.0
  manifests/w/WildfireGames/0AD/0.27.0/WildfireGames.0AD.installer.yaml
  manifests/w/WildfireGames/0AD/0.27.0/WildfireGames.0AD.locale.en-US.yaml
  manifests/w/WildfireGames/0AD/0.27.0/WildfireGames.0AD.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, New-Manifest

#220939 New version: Amazon.AWSCLI version 2.23.11
  manifests/a/Amazon/AWSCLI/2.23.11/Amazon.AWSCLI.installer.yaml
  manifests/a/Amazon/AWSCLI/2.23.11/Amazon.AWSCLI.locale.en-US.yaml
  manifests/a/Amazon/AWSCLI/2.23.11/Amazon.AWSCLI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220942 New version: WeMod.WeMod.Beta version 10.1.0-beta00
  manifests/w/WeMod/WeMod/Beta/10.1.0-beta00/WeMod.WeMod.Beta.installer.yaml
  manifests/w/WeMod/WeMod/Beta/10.1.0-beta00/WeMod.WeMod.Beta.locale.en-US.yaml
  manifests/w/WeMod/WeMod/Beta/10.1.0-beta00/WeMod.WeMod.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220945 New version: jdx.mise version 2025.1.17
  manifests/j/jdx/mise/2025.1.17/jdx.mise.installer.yaml
  manifests/j/jdx/mise/2025.1.17/jdx.mise.locale.en-US.yaml
  manifests/j/jdx/mise/2025.1.17/jdx.mise.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220976 Microsoft.VisualStudioCode.Insiders.CLI_v1.97.0 cli
  manifests/m/Microsoft/VisualStudioCode/Insiders/CLI/1.97.0/Microsoft.VisualStudioCode.Insiders.CLI.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220977 New version: GitHub.cli version 2.66.1
  manifests/g/GitHub/cli/2.66.1/GitHub.cli.installer.yaml
  manifests/g/GitHub/cli/2.66.1/GitHub.cli.locale.en-US.yaml
  manifests/g/GitHub/cli/2.66.1/GitHub.cli.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220975 Microsoft.VisualStudioCode.Insiders_v1.97.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.97.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220949 New version: Discord.Discord.Canary version 1.0.543
  manifests/d/Discord/Discord/Canary/1.0.543/Discord.Discord.Canary.installer.yaml
  manifests/d/Discord/Discord/Canary/1.0.543/Discord.Discord.Canary.locale.en-US.yaml
  manifests/d/Discord/Discord/Canary/1.0.543/Discord.Discord.Canary.locale.zh-CN.yaml
  manifests/d/Discord/Discord/Canary/1.0.543/Discord.Discord.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220951 Update: KDE.Konsole version 25.03.70 (3822)
  manifests/k/KDE/Konsole/25.03.70/KDE.Konsole.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220923 Standardize formatting of manifests/b/BinanceTech/Binance/1.53.6
  manifests/b/BinanceTech/Binance/1.53.6/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.53.6/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.53.6/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#221004 New version: NodirTemirkhodjaev.FortFirewall version 3.15.9
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.9/NodirTemirkhodjaev.FortFirewall.installer.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.9/NodirTemirkhodjaev.FortFirewall.locale.en-US.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.9/NodirTemirkhodjaev.FortFirewall.locale.zh-CN.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.9/NodirTemirkhodjaev.FortFirewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221002 New version: Blix.BlueMail version 1.140.76
  manifests/b/Blix/BlueMail/1.140.76/Blix.BlueMail.installer.yaml
  manifests/b/Blix/BlueMail/1.140.76/Blix.BlueMail.locale.en-US.yaml
  manifests/b/Blix/BlueMail/1.140.76/Blix.BlueMail.locale.zh-CN.yaml
  manifests/b/Blix/BlueMail/1.140.76/Blix.BlueMail.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220958 New version: Google.Chrome.Canary version 134.0.6991.0
  manifests/g/Google/Chrome/Canary/134.0.6991.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/134.0.6991.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/134.0.6991.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/134.0.6991.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/134.0.6991.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220997 New version: hatoo.oha version 1.7.0
  manifests/h/hatoo/oha/1.7.0/hatoo.oha.installer.yaml
  manifests/h/hatoo/oha/1.7.0/hatoo.oha.locale.en-US.yaml
  manifests/h/hatoo/oha/1.7.0/hatoo.oha.locale.zh-CN.yaml
  manifests/h/hatoo/oha/1.7.0/hatoo.oha.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220950 New version: JetBrains.PhpStorm.EAP version 251.18673.45
  manifests/j/JetBrains/PhpStorm/EAP/251.18673.45/JetBrains.PhpStorm.EAP.installer.yaml
  manifests/j/JetBrains/PhpStorm/EAP/251.18673.45/JetBrains.PhpStorm.EAP.locale.en-US.yaml
  manifests/j/JetBrains/PhpStorm/EAP/251.18673.45/JetBrains.PhpStorm.EAP.locale.zh-CN.yaml
  manifests/j/JetBrains/PhpStorm/EAP/251.18673.45/JetBrains.PhpStorm.EAP.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220989 Update: Codeium.Windsurf version 1.94.0 (1.2.5)
  manifests/c/Codeium/Windsurf/1.94.0/Codeium.Windsurf.installer.yaml
  manifests/c/Codeium/Windsurf/1.94.0/Codeium.Windsurf.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220935 New version: CodeStory.Aide version 1.96.4.25031
  manifests/c/CodeStory/Aide/1.96.4.25031/CodeStory.Aide.installer.yaml
  manifests/c/CodeStory/Aide/1.96.4.25031/CodeStory.Aide.locale.en-US.yaml
  manifests/c/CodeStory/Aide/1.96.4.25031/CodeStory.Aide.locale.zh-CN.yaml
  manifests/c/CodeStory/Aide/1.96.4.25031/CodeStory.Aide.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#221003 New version: Google.Chrome.Canary version 134.0.6992.0
  manifests/g/Google/Chrome/Canary/134.0.6992.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/134.0.6992.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/134.0.6992.0/Google.Chrome.Canary.locale.nb-NO.yaml
  manifests/g/Google/Chrome/Canary/134.0.6992.0/Google.Chrome.Canary.locale.zh-CN.yaml
  manifests/g/Google/Chrome/Canary/134.0.6992.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220981 Microsoft.VisualStudioCode.Insiders_v1.97.0 desktop
  manifests/m/Microsoft/VisualStudioCode/Insiders/1.97.0/Microsoft.VisualStudioCode.Insiders.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220991 New version: Jackett.Jackett version 0.22.1355
  manifests/j/Jackett/Jackett/0.22.1355/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1355/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1355/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221008 New version: TailwindLabs.TailwindCSS version 4.0.3
  manifests/t/TailwindLabs/TailwindCSS/4.0.3/TailwindLabs.TailwindCSS.installer.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.3/TailwindLabs.TailwindCSS.locale.en-US.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.3/TailwindLabs.TailwindCSS.locale.zh-CN.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.3/TailwindLabs.TailwindCSS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220924 New version: TailwindLabs.TailwindCSS version 4.0.2
  manifests/t/TailwindLabs/TailwindCSS/4.0.2/TailwindLabs.TailwindCSS.installer.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.2/TailwindLabs.TailwindCSS.locale.en-US.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.2/TailwindLabs.TailwindCSS.locale.zh-CN.yaml
  manifests/t/TailwindLabs/TailwindCSS/4.0.2/TailwindLabs.TailwindCSS.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220918 Standardize formatting of manifests/b/BinanceTech/Binance/1.52.11
  manifests/b/BinanceTech/Binance/1.52.11/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.52.11/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.52.11/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220917 Standardize formatting of manifests/b/BinanceTech/Binance/1.52.0
  manifests/b/BinanceTech/Binance/1.52.0/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.52.0/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.52.0/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220922 Standardize formatting of manifests/b/BinanceTech/Binance/1.53.4
  manifests/b/BinanceTech/Binance/1.53.4/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.53.4/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.53.4/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220675 Standardize formatting of manifests/s/Sogou/SogouInput/14.6.0.9606
  manifests/s/Sogou/SogouInput/14.6.0.9606/Sogou.SogouInput.installer.yaml
  manifests/s/Sogou/SogouInput/14.6.0.9606/Sogou.SogouInput.locale.en-US.yaml
  manifests/s/Sogou/SogouInput/14.6.0.9606/Sogou.SogouInput.locale.zh-CN.yaml
  manifests/s/Sogou/SogouInput/14.6.0.9606/Sogou.SogouInput.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220721 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.8.12
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.12/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.12/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.12/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220716 Standardize formatting of manifests/s/Spyder/Spyder/6.0.2
  manifests/s/Spyder/Spyder/6.0.2/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/6.0.2/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/6.0.2/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220706 Standardize formatting of manifests/s/Spyder/Spyder/5.4.0
  manifests/s/Spyder/Spyder/5.4.0/Spyder.Spyder.installer.yaml
  manifests/s/Spyder/Spyder/5.4.0/Spyder.Spyder.locale.en-US.yaml
  manifests/s/Spyder/Spyder/5.4.0/Spyder.Spyder.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220722 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.8.13
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.13/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.13/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.13/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220996 Zoho.Arattai version 1.0.4
  manifests/z/Zoho/Arattai/1.0.4/Zoho.Arattai.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221011 Update manifest: ramdor.Thetis version 2.10.3.8
  manifests/r/ramdor/Thetis/2.10.3.8/ramdor.Thetis.locale.en-US.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220759 Move KDE.digikam 8.2.0 to KDE.digiKam 8.2.0
  manifests/k/KDE/digiKam/8.2.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/8.2.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/8.2.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#220757 Move KDE.digikam 8.1.0 to KDE.digiKam 8.1.0
  manifests/k/KDE/digiKam/8.1.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/8.1.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/8.1.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#220762 Move KDE.digikam 8.3.0 to KDE.digiKam 8.3.0
  manifests/k/KDE/digiKam/8.3.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/8.3.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/8.3.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#220740 Move KDE.digikam 7.1.0 to KDE.digiKam 7.1.0
  manifests/k/KDE/digiKam/7.1.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/7.1.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/7.1.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Manifest-Version-Deprecated, New-Package

#220766 Move KDE.digikam 8.5.0 to KDE.digiKam 8.5.0
  manifests/k/KDE/digiKam/8.5.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/8.5.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/8.5.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#220751 Move KDE.digikam 7.7.0 to KDE.digiKam 7.7.0
  manifests/k/KDE/digiKam/7.7.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/7.7.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/7.7.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#220744 Move KDE.digikam 7.3.0 to KDE.digiKam 7.3.0
  manifests/k/KDE/digiKam/7.3.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/7.3.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/7.3.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#220748 Move KDE.digikam 7.6.0 to KDE.digiKam 7.6.0
  manifests/k/KDE/digiKam/7.6.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/7.6.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/7.6.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#220746 Move KDE.digikam 7.4.0 to KDE.digiKam 7.4.0
  manifests/k/KDE/digiKam/7.4.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/7.4.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/7.4.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Needs-Author-Feedback, Manifest-Version-Deprecated, New-Package

#220764 Move KDE.digikam 8.4.0 to KDE.digiKam 8.4.0
  manifests/k/KDE/digiKam/8.4.0/KDE.digiKam.installer.yaml
  manifests/k/KDE/digiKam/8.4.0/KDE.digiKam.locale.en-US.yaml
  manifests/k/KDE/digiKam/8.4.0/KDE.digiKam.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#219636 New version: EclipseAdoptium.Temurin.8.JRE version 8.0.442.6
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.442.6/EclipseAdoptium.Temurin.8.JRE.installer.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.442.6/EclipseAdoptium.Temurin.8.JRE.locale.en-US.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.442.6/EclipseAdoptium.Temurin.8.JRE.locale.zh-CN.yaml
  manifests/e/EclipseAdoptium/Temurin/8/JRE/8.0.442.6/EclipseAdoptium.Temurin.8.JRE.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, Network-Blocker, New-Manifest

#221095 New version: Jackett.Jackett version 0.22.1359
  manifests/j/Jackett/Jackett/0.22.1359/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1359/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1359/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221080 New version: vim.vim.nightly version 9.1.1065
  manifests/v/vim/vim/nightly/9.1.1065/vim.vim.nightly.installer.yaml
  manifests/v/vim/vim/nightly/9.1.1065/vim.vim.nightly.locale.en-US.yaml
  manifests/v/vim/vim/nightly/9.1.1065/vim.vim.nightly.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220914 Standardize formatting of manifests/b/BinanceTech/Binance/1.50.3
  manifests/b/BinanceTech/Binance/1.50.3/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.50.3/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.50.3/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221104 New version: Google.Chrome.Canary version 134.0.6994.0
  manifests/g/Google/Chrome/Canary/134.0.6994.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/134.0.6994.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/134.0.6994.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221081 New version: kwaroran.RisuAI version 149.0.0
  manifests/k/kwaroran/RisuAI/149.0.0/kwaroran.RisuAI.installer.yaml
  manifests/k/kwaroran/RisuAI/149.0.0/kwaroran.RisuAI.locale.en-US.yaml
  manifests/k/kwaroran/RisuAI/149.0.0/kwaroran.RisuAI.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Retry-1, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220897 Standardize formatting of manifests/b/BinanceTech/Binance/1.46.2
  manifests/b/BinanceTech/Binance/1.46.2/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.46.2/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.46.2/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221017 Update: ElementLabs.LMStudio version 0.3.9
  manifests/e/ElementLabs/LMStudio/0.3.9/ElementLabs.LMStudio.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220772 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.4.5
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.5/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.5/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.5/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221015 New version: Google.GoogleUpdater version 134.0.6985.0
  manifests/g/Google/GoogleUpdater/134.0.6985.0/Google.GoogleUpdater.installer.yaml
  manifests/g/Google/GoogleUpdater/134.0.6985.0/Google.GoogleUpdater.locale.en-US.yaml
  manifests/g/Google/GoogleUpdater/134.0.6985.0/Google.GoogleUpdater.locale.zh-CN.yaml
  manifests/g/Google/GoogleUpdater/134.0.6985.0/Google.GoogleUpdater.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220728 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.9.4
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.4/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.4/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.4/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220773 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.4.7
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.7/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.7/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.4.7/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220725 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.9.12
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.12/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.12/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.12/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220280 Remove manifests/e/ElectronCash/ElectronCash/4.2.2
  manifests/e/ElectronCash/ElectronCash/4.2.2/ElectronCash.ElectronCash.installer.yaml
  manifests/e/ElectronCash/ElectronCash/4.2.2/ElectronCash.ElectronCash.locale.en-US.yaml
  manifests/e/ElectronCash/ElectronCash/4.2.2/ElectronCash.ElectronCash.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220842 Standardize formatting of manifests/c/Canva/Canva/1.93.1
  manifests/c/Canva/Canva/1.93.1/Canva.Canva.installer.yaml
  manifests/c/Canva/Canva/1.93.1/Canva.Canva.locale.en-US.yaml
  manifests/c/Canva/Canva/1.93.1/Canva.Canva.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220726 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.9.13
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.13/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220723 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.8.5
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.5/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.5/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.8.5/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221019 New version: Readdle.Spark version 3.20.3 (3.20.3.97948)
  manifests/r/Readdle/Spark/3.20.3/Readdle.Spark.installer.yaml
  manifests/r/Readdle/Spark/3.20.3/Readdle.Spark.locale.en-US.yaml
  manifests/r/Readdle/Spark/3.20.3/Readdle.Spark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220731 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.0.2
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.2/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.2/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.2/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221028 New version: PBH-BTN.PeerBanHelper version 7.4.2
  manifests/p/PBH-BTN/PeerBanHelper/7.4.2/PBH-BTN.PeerBanHelper.installer.yaml
  manifests/p/PBH-BTN/PeerBanHelper/7.4.2/PBH-BTN.PeerBanHelper.locale.en-US.yaml
  manifests/p/PBH-BTN/PeerBanHelper/7.4.2/PBH-BTN.PeerBanHelper.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220789 Standardize formatting of manifests/c/Canva/Canva/1.39.0
  manifests/c/Canva/Canva/1.39.0/Canva.Canva.installer.yaml
  manifests/c/Canva/Canva/1.39.0/Canva.Canva.locale.en-US.yaml
  manifests/c/Canva/Canva/1.39.0/Canva.Canva.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220729 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/2.9.5
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.5/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.5/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/2.9.5/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220775 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.5.3
  manifests/t/Telegram/TelegramDesktop/Beta/3.5.3/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.5.3/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.5.3/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221010 New version: RogerZander.RZGet version 1.7.3.8
  manifests/r/RogerZander/RZGet/1.7.3.8/RogerZander.RZGet.installer.yaml
  manifests/r/RogerZander/RZGet/1.7.3.8/RogerZander.RZGet.locale.en-US.yaml
  manifests/r/RogerZander/RZGet/1.7.3.8/RogerZander.RZGet.locale.zh-CN.yaml
  manifests/r/RogerZander/RZGet/1.7.3.8/RogerZander.RZGet.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220736 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.1.2
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.2/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.2/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.2/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220734 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.1.12
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.12/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.12/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.1.12/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220732 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.0.4
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.4/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.4/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.0.4/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220902 Standardize formatting of manifests/b/BinanceTech/Binance/1.48.2
  manifests/b/BinanceTech/Binance/1.48.2/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.48.2/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.48.2/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220782 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/4.2.1
  manifests/t/Telegram/TelegramDesktop/Beta/4.2.1/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/4.2.1/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/4.2.1/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221075 New version: Google.Chrome.Canary version 134.0.6993.0
  manifests/g/Google/Chrome/Canary/134.0.6993.0/Google.Chrome.Canary.installer.yaml
  manifests/g/Google/Chrome/Canary/134.0.6993.0/Google.Chrome.Canary.locale.en-US.yaml
  manifests/g/Google/Chrome/Canary/134.0.6993.0/Google.Chrome.Canary.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220769 Standardize formatting of manifests/t/Telegram/TelegramDesktop/Beta/3.2.8
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.installer.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.locale.en-US.yaml
  manifests/t/Telegram/TelegramDesktop/Beta/3.2.8/Telegram.TelegramDesktop.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221097 New version: NodirTemirkhodjaev.FortFirewall version 3.15.10
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.10/NodirTemirkhodjaev.FortFirewall.installer.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.10/NodirTemirkhodjaev.FortFirewall.locale.en-US.yaml
  manifests/n/NodirTemirkhodjaev/FortFirewall/3.15.10/NodirTemirkhodjaev.FortFirewall.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221107 New version: JurgenRathlev.innounp version 2.64.1
  manifests/j/JurgenRathlev/innounp/2.64.1/JurgenRathlev.innounp.installer.yaml
  manifests/j/JurgenRathlev/innounp/2.64.1/JurgenRathlev.innounp.locale.en-US.yaml
  manifests/j/JurgenRathlev/innounp/2.64.1/JurgenRathlev.innounp.yaml
  manifests/j/JurgenRathlev/innounp/2.64/JurgenRathlev.innounp.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220841 Standardize formatting of manifests/c/Canva/Canva/1.93.0
  manifests/c/Canva/Canva/1.93.0/Canva.Canva.installer.yaml
  manifests/c/Canva/Canva/1.93.0/Canva.Canva.locale.en-US.yaml
  manifests/c/Canva/Canva/1.93.0/Canva.Canva.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220912 Standardize formatting of manifests/b/BinanceTech/Binance/1.50.1
  manifests/b/BinanceTech/Binance/1.50.1/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.50.1/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.50.1/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221069 New version: OpenRCT2.OpenRCT2 version 0.4.19 (0.4.19)
  manifests/o/OpenRCT2/OpenRCT2/0.4.19/OpenRCT2.OpenRCT2.installer.yaml
  manifests/o/OpenRCT2/OpenRCT2/0.4.19/OpenRCT2.OpenRCT2.locale.en-US.yaml
  manifests/o/OpenRCT2/OpenRCT2/0.4.19/OpenRCT2.OpenRCT2.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220844 Standardize formatting of manifests/c/Canva/Canva/1.95.0
  manifests/c/Canva/Canva/1.95.0/Canva.Canva.installer.yaml
  manifests/c/Canva/Canva/1.95.0/Canva.Canva.locale.en-US.yaml
  manifests/c/Canva/Canva/1.95.0/Canva.Canva.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220889 Standardize formatting of manifests/b/BinanceTech/Binance/1.43.1
  manifests/b/BinanceTech/Binance/1.43.1/BinanceTech.Binance.installer.yaml
  manifests/b/BinanceTech/Binance/1.43.1/BinanceTech.Binance.locale.en-US.yaml
  manifests/b/BinanceTech/Binance/1.43.1/BinanceTech.Binance.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221106 New version: chen08209.FlClash version 0.8.73+202502021 (0.8.73)
  manifests/c/chen08209/FlClash/0.8.73+202502021/chen08209.FlClash.installer.yaml
  manifests/c/chen08209/FlClash/0.8.73+202502021/chen08209.FlClash.locale.en-US.yaml
  manifests/c/chen08209/FlClash/0.8.73+202502021/chen08209.FlClash.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220153 Modify: Mozilla.Firefox version 134.0.2
  manifests/m/Mozilla/Firefox/134.0.2/Mozilla.Firefox.installer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221092 New version: chrisant996.Clink version 1.7.9
  manifests/c/chrisant996/Clink/1.7.9/chrisant996.Clink.installer.yaml
  manifests/c/chrisant996/Clink/1.7.9/chrisant996.Clink.locale.en-US.yaml
  manifests/c/chrisant996/Clink/1.7.9/chrisant996.Clink.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221105 Add version: TeamSpeakSystems.TeamSpeakClient.Beta.6 version 6.0.0-beta2
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/6/6.0.0-beta2/TeamSpeakSystems.TeamSpeakClient.Beta.6.installer.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/6/6.0.0-beta2/TeamSpeakSystems.TeamSpeakClient.Beta.6.locale.en-US.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/6/6.0.0-beta2/TeamSpeakSystems.TeamSpeakClient.Beta.6.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Package

#221109 Move TeamSpeakSystems.TeamSpeakClient.Beta 5.0.0 to TeamSpeakSystems.…
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.5.installer.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.5.locale.en-US.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.5.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Possible-Duplicate, Moderator-Approved, New-Package

#221110 Remove TeamSpeakSystems.TeamSpeakClient.Beta 5.0.0 to TeamSpeakSystem…
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.installer.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.locale.en-US.yaml
  manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta/5.0.0/TeamSpeakSystems.TeamSpeakClient.Beta.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220944 New version: Microsoft.PerfView version 3.1.19
  manifests/m/Microsoft/PerfView/3.1.19/Microsoft.PerfView.installer.yaml
  manifests/m/Microsoft/PerfView/3.1.19/Microsoft.PerfView.locale.en-US.yaml
  manifests/m/Microsoft/PerfView/3.1.19/Microsoft.PerfView.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221113 New version: Digola.InstaMonitr version 18.1
  manifests/d/Digola/InstaMonitr/18.1/Digola.InstaMonitr.installer.yaml
  manifests/d/Digola/InstaMonitr/18.1/Digola.InstaMonitr.locale.en-US.yaml
  manifests/d/Digola/InstaMonitr/18.1/Digola.InstaMonitr.yaml
  manifests/d/Digola/InstaMonitr/18/Digola.InstaMonitr.locale.zh-CN.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220849 Remove version: MoonchildProductions.PaleMoon version 33.4.1 (Auto)
  manifests/m/MoonchildProductions/PaleMoon/33.4.1/MoonchildProductions.PaleMoon.installer.yaml
  manifests/m/MoonchildProductions/PaleMoon/33.4.1/MoonchildProductions.PaleMoon.locale.en-US.yaml
  manifests/m/MoonchildProductions/PaleMoon/33.4.1/MoonchildProductions.PaleMoon.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221360 New version: MilosParipovic.OneCommander version 3.95.4 (3.95.4.0)
  manifests/m/MilosParipovic/OneCommander/3.95.4/MilosParipovic.OneCommander.installer.yaml
  manifests/m/MilosParipovic/OneCommander/3.95.4/MilosParipovic.OneCommander.locale.en-US.yaml
  manifests/m/MilosParipovic/OneCommander/3.95.4/MilosParipovic.OneCommander.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221361 New version: vkbo.novelWriter version 2.6.1
  manifests/v/vkbo/novelWriter/2.6.1/vkbo.novelWriter.installer.yaml
  manifests/v/vkbo/novelWriter/2.6.1/vkbo.novelWriter.locale.en-US.yaml
  manifests/v/vkbo/novelWriter/2.6.1/vkbo.novelWriter.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221359 New version: Gitify.Gitify version 6.0.0
  manifests/g/Gitify/Gitify/6.0.0/Gitify.Gitify.installer.yaml
  manifests/g/Gitify/Gitify/6.0.0/Gitify.Gitify.locale.en-US.yaml
  manifests/g/Gitify/Gitify/6.0.0/Gitify.Gitify.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221210 New version: Anydo.Anydo version 5.0.89
  manifests/a/Anydo/Anydo/5.0.89/Anydo.Anydo.installer.yaml
  manifests/a/Anydo/Anydo/5.0.89/Anydo.Anydo.locale.en-US.yaml
  manifests/a/Anydo/Anydo/5.0.89/Anydo.Anydo.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221397 New version: NGWIN.PicPick version 7.3.0
  manifests/n/NGWIN/PicPick/7.3.0/NGWIN.PicPick.installer.yaml
  manifests/n/NGWIN/PicPick/7.3.0/NGWIN.PicPick.locale.en-US.yaml
  manifests/n/NGWIN/PicPick/7.3.0/NGWIN.PicPick.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220511 Standardize formatting of manifests/p/PaulSori/mStreamServer/5.2.9
  manifests/p/PaulSori/mStreamServer/5.2.9/PaulSori.mStreamServer.installer.yaml
  manifests/p/PaulSori/mStreamServer/5.2.9/PaulSori.mStreamServer.locale.en-US.yaml
  manifests/p/PaulSori/mStreamServer/5.2.9/PaulSori.mStreamServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220508 Standardize formatting of manifests/p/PaulSori/mStreamServer/5.2.4
  manifests/p/PaulSori/mStreamServer/5.2.4/PaulSori.mStreamServer.installer.yaml
  manifests/p/PaulSori/mStreamServer/5.2.4/PaulSori.mStreamServer.locale.en-US.yaml
  manifests/p/PaulSori/mStreamServer/5.2.4/PaulSori.mStreamServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220509 Standardize formatting of manifests/p/PaulSori/mStreamServer/5.2.5
  manifests/p/PaulSori/mStreamServer/5.2.5/PaulSori.mStreamServer.installer.yaml
  manifests/p/PaulSori/mStreamServer/5.2.5/PaulSori.mStreamServer.locale.en-US.yaml
  manifests/p/PaulSori/mStreamServer/5.2.5/PaulSori.mStreamServer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221619 New version: Jackett.Jackett version 0.22.1363
  manifests/j/Jackett/Jackett/0.22.1363/Jackett.Jackett.installer.yaml
  manifests/j/Jackett/Jackett/0.22.1363/Jackett.Jackett.locale.en-US.yaml
  manifests/j/Jackett/Jackett/0.22.1363/Jackett.Jackett.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#221536 Remove version: Tencent.Weiyun version 5.2.970
  manifests/t/Tencent/Weiyun/5.2.970/Tencent.Weiyun.installer.yaml
  manifests/t/Tencent/Weiyun/5.2.970/Tencent.Weiyun.locale.en-US.yaml
  manifests/t/Tencent/Weiyun/5.2.970/Tencent.Weiyun.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221547 Remove version: Alibaba.Quark version 1.0.5.9
  manifests/a/Alibaba/Quark/1.0.5.9/Alibaba.Quark.installer.yaml
  manifests/a/Alibaba/Quark/1.0.5.9/Alibaba.Quark.locale.en-US.yaml
  manifests/a/Alibaba/Quark/1.0.5.9/Alibaba.Quark.locale.zh-CN.yaml
  manifests/a/Alibaba/Quark/1.0.5.9/Alibaba.Quark.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221574 Remove version: binjr.core-x64 version 3.21.0
  manifests/b/binjr/core-x64/3.21.0/binjr.core-x64.installer.yaml
  manifests/b/binjr/core-x64/3.21.0/binjr.core-x64.locale.en-US.yaml
  manifests/b/binjr/core-x64/3.21.0/binjr.core-x64.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221588 Remove version: Avidemux.Avidemux version 2.7.8.210306
  manifests/a/Avidemux/Avidemux/2.7.8.210306/Avidemux.Avidemux.installer.yaml
  manifests/a/Avidemux/Avidemux/2.7.8.210306/Avidemux.Avidemux.locale.en-US.yaml
  manifests/a/Avidemux/Avidemux/2.7.8.210306/Avidemux.Avidemux.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221463 Remove version: Redisant.RedisantToolbox version 1.0.6.1
  manifests/r/Redisant/RedisantToolbox/1.0.6.1/Redisant.RedisantToolbox.installer.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.6.1/Redisant.RedisantToolbox.locale.en-US.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.6.1/Redisant.RedisantToolbox.locale.zh-CN.yaml
  manifests/r/Redisant/RedisantToolbox/1.0.6.1/Redisant.RedisantToolbox.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#221018 New Version: Sigil-Ebook.Sigil version 2.4.2
  manifests/s/Sigil-Ebook/Sigil/2.4.2/Sigil-Ebook.Sigil.installer.yaml
  manifests/s/Sigil-Ebook/Sigil/2.4.2/Sigil-Ebook.Sigil.locale.en-US.yaml
  manifests/s/Sigil-Ebook/Sigil/2.4.2/Sigil-Ebook.Sigil.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#221603 Revert "Remove version: TechPowerUp.GPU-Z version 2.61.0"
  manifests/t/TechPowerUp/GPU-Z/2.61.0/TechPowerUp.GPU-Z.installer.yaml
  manifests/t/TechPowerUp/GPU-Z/2.61.0/TechPowerUp.GPU-Z.locale.en-US.yaml
  manifests/t/TechPowerUp/GPU-Z/2.61.0/TechPowerUp.GPU-Z.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Package

#221070 New version: dorssel.usbipd-win version 4.4.0
  manifests/d/dorssel/usbipd-win/4.4.0/dorssel.usbipd-win.installer.yaml
  manifests/d/dorssel/usbipd-win/4.4.0/dorssel.usbipd-win.locale.en-US.yaml
  manifests/d/dorssel/usbipd-win/4.4.0/dorssel.usbipd-win.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest

#220954 cthoeing.PasswordTech version 3.5.6
  manifests/c/cthoeing/PasswordTech/3.5.6/cthoeing.PasswordTech.installer.yaml
  manifests/c/cthoeing/PasswordTech/3.5.6/cthoeing.PasswordTech.locale.en-US.yaml
  manifests/c/cthoeing/PasswordTech/3.5.6/cthoeing.PasswordTech.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, New-Manifest, Manifest-Metadata-Consistency

#220042 New version: Cygwin.Cygwin version 3.5.7
  manifests/c/Cygwin/Cygwin/3.5.7/Cygwin.Cygwin.installer.yaml
  manifests/c/Cygwin/Cygwin/3.5.7/Cygwin.Cygwin.locale.en-US.yaml
  manifests/c/Cygwin/Cygwin/3.5.7/Cygwin.Cygwin.yaml
Labels: Validation-Completed, Retry-1, Moderator-Approved, Validation-Retry

#221031 New version: Anysphere.Cursor version 0.45.8
  manifests/a/Anysphere/Cursor/0.45.8/Anysphere.Cursor.installer.yaml
  manifests/a/Anysphere/Cursor/0.45.8/Anysphere.Cursor.locale.en-US.yaml
  manifests/a/Anysphere/Cursor/0.45.8/Anysphere.Cursor.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest, Manifest-Metadata-Consistency

#220850 Remove version: QXYZLabs.Sanctum version 1.9.0 (Auto)
  manifests/q/QXYZLabs/Sanctum/1.9.0/QXYZLabs.Sanctum.installer.yaml
  manifests/q/QXYZLabs/Sanctum/1.9.0/QXYZLabs.Sanctum.locale.en-US.yaml
  manifests/q/QXYZLabs/Sanctum/1.9.0/QXYZLabs.Sanctum.locale.zh-CN.yaml
  manifests/q/QXYZLabs/Sanctum/1.9.0/QXYZLabs.Sanctum.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220933 New version: MicroDicom.DICOMViewer version 2025.1
  manifests/m/MicroDicom/DICOMViewer/2025.1/MicroDicom.DICOMViewer.installer.yaml
  manifests/m/MicroDicom/DICOMViewer/2025.1/MicroDicom.DICOMViewer.locale.en-US.yaml
  manifests/m/MicroDicom/DICOMViewer/2025.1/MicroDicom.DICOMViewer.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220940 WHTA.Tamara version 2025.0.3.1
  manifests/w/WHTA/Tamara/2025.0.3.1/WHTA.Tamara.installer.yaml
  manifests/w/WHTA/Tamara/2025.0.3.1/WHTA.Tamara.locale.en-US.yaml
  manifests/w/WHTA/Tamara/2025.0.3.1/WHTA.Tamara.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220941 New version: nomic.gpt4all version 3.8.0
  manifests/n/nomic/gpt4all/3.8.0/nomic.gpt4all.installer.yaml
  manifests/n/nomic/gpt4all/3.8.0/nomic.gpt4all.locale.en-US.yaml
  manifests/n/nomic/gpt4all/3.8.0/nomic.gpt4all.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#220983 Remove version: LutzRoeder.Netron version 8.1.1 (Auto)
  manifests/l/LutzRoeder/Netron/8.1.1/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/8.1.1/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/8.1.1/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220985 Remove version: LutzRoeder.Netron version 8.0.9 (Auto)
  manifests/l/LutzRoeder/Netron/8.0.9/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/8.0.9/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/8.0.9/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed

#220984 Remove version: LutzRoeder.Netron version 8.0.8 (Auto)
  manifests/l/LutzRoeder/Netron/8.0.8/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/8.0.8/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/8.0.8/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220986 Remove version: LutzRoeder.Netron version 8.1.2 (Auto)
  manifests/l/LutzRoeder/Netron/8.1.2/LutzRoeder.Netron.installer.yaml
  manifests/l/LutzRoeder/Netron/8.1.2/LutzRoeder.Netron.locale.en-US.yaml
  manifests/l/LutzRoeder/Netron/8.1.2/LutzRoeder.Netron.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved

#220992 New version: Oven-sh.Bun version 1.2.2
  manifests/o/Oven-sh/Bun/1.2.2/Oven-sh.Bun.installer.yaml
  manifests/o/Oven-sh/Bun/1.2.2/Oven-sh.Bun.locale.en-US.yaml
  manifests/o/Oven-sh/Bun/1.2.2/Oven-sh.Bun.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest

#221000 Remove version: ZhornSoftware.Stickies version 10.1d (Auto)
  manifests/z/ZhornSoftware/Stickies/10.1d/ZhornSoftware.Stickies.installer.yaml
  manifests/z/ZhornSoftware/Stickies/10.1d/ZhornSoftware.Stickies.locale.en-US.yaml
  manifests/z/ZhornSoftware/Stickies/10.1d/ZhornSoftware.Stickies.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Needs-Author-Feedback, Highest-Version-Removal

#221014 the-sz.Trion version 1.25
  manifests/t/the-sz/Trion/1.25/the-sz.Trion.installer.yaml
  manifests/t/the-sz/Trion/1.25/the-sz.Trion.locale.en-US.yaml
  manifests/t/the-sz/Trion/1.25/the-sz.Trion.yaml
Labels: Azure-Pipeline-Passed, Validation-Completed, Moderator-Approved, New-Manifest
